### ISSUE TITLE
Suggestion: What about a Dark theme?

### ISSUE THREAD

**Issue by DakshMiglani** [keybase/client#10016]
The Electron Client is pretty light at night, so yeah why no dark theme? when most devs chat through KeyBase?

**Comment by specious** [comment]
Consider making a contribution?

**Comment by kenkit** [comment]
yeah, the other one is not so pretty when chatting

**Comment by NobbZ** [comment]
Especially for modern AMOLED displays a light gray on **real** black (`#000000`) should be done quickly I think.

**Comment by kenkit** [comment]
this should be a feature request tagged "themes"

**Comment by kenkit** [comment]
Also I think improving the chat system to be like telegram would be good.

**Comment by yohanboniface** [comment]
Dup of #7447

**Comment by Avamander** [comment]
Ping.

**Comment by CypherXero** [comment]
definitely need a dark theme and colored text to offset the darker background...

**Comment by NetwarSystem** [comment]
This is definitely needed.

**Comment by cy6erlion** [comment]
+1 for the Dark Theme

**Comment by briansok** [comment]
When is this going to happen?

**Comment by maduce** [comment]
+100

**Comment by glyph** [comment]
Any chance that the latest WWDC makes this more likely? :)

**Comment by livejamie** [comment]
Can we please make this happen?

**Comment by Mati20187** [comment]
Love keybase, but the theme is burning my eyes at night. Please, add a dark theme

**Comment by dkotik** [comment]
Dark theme should be the default - saves batteries and saves eyes. +100

**Comment by heronhaye** [comment]
Dark mode released in Keybase 4.6.0 under Settings->Display->Appearance.

**Comment by glyph** [comment]
Thank you—I love it!
