### ISSUE TITLE
You accessed a private folder with X

### ISSUE THREAD

**Issue by maartenbusstra** [keybase/client#10042]
Every time I start up Keybase on my mac, I get this popup, even though I haven't actually accessed the folder at all. It's always regarding the same shared folder. Would it help if I provide the folder name?

**Comment by maxtaco** [comment]
Hah, I have this issue too.  Can you open the "preview" app and see if you have a KBFS share in the "Recent places" of the dropdown menu?

cc: @strib

**Comment by maartenbusstra** [comment]
I don't seem to have any KBFS shares there. :/

**Comment by maxtaco** [comment]
Ok, if you try `keybase log send`, we can investigate

**Comment by strib** [comment]
It's likely something like recent files, or maybe something in your shell.  You can avoid it by following the person.  You can do so locally (without making it public) with `keybase follow -l` from the terminal.

**Comment by maartenbusstra** [comment]
Thanks for the follow tip, that helped. :)
