### ISSUE TITLE
[DEBIAN INSTALL] Keybase

### ISSUE THREAD

**Issue by toorusr** [keybase/client#10065]
> ```
> >> sudo dpkg -i keybase_amd64.deb 
> (Reading database ... 458174 files and directories currently installed.)
> Preparing to unpack keybase_amd64.deb ...
> Unpacking keybase (1.0.38-20171221170044.4c1f9803e) over (1.0.38-20171221170044.4c1f9803e) ...
> Setting up keybase (1.0.38-20171221170044.4c1f9803e) ...
> gtk-update-icon-cache: The generated cache was invalid.
> dpkg: error processing package keybase (--install):
>  installed keybase package post-installation script subprocess returned error exit status 1
> Processing triggers for desktop-file-utils (0.23-2) ...
> Processing triggers for mime-support (3.60) ...
> Processing triggers for hicolor-icon-theme (0.17-1) ...
> gtk-update-icon-cache: The generated cache was invalid.
> WARNING: icon cache generation failed
> Errors were encountered while processing:
>  keybase
> ```

**Comment by oconnor663** [comment]
@toorusr could you tell me what platform you're running on? Maybe the output of `uname -a` and `cat /etc/os-release`?

**Comment by toorusr** [comment]
@oconnor663 I don't know why and how, but now it works.
