### ISSUE TITLE
keybase wants to upload my private key

### ISSUE THREAD

**Issue by tessus** [keybase/client#10068]
I just created a new gpg key and thus had to reset my keybase account.

When I now try to add my new gpg key, by using `keybase pgp select` as described in the window when clicking `add a PGP key`, keybase wants to export my private key.

What??? 

The window explicitly states `add a public key`. see following screenshot:

<img width="574" alt="screen shot 2018-01-01 at 17 54 54" src="https://user-images.githubusercontent.com/223439/34471687-9a241ef0-ef1d-11e7-882d-e36113e8605d.png">

I will not give keybase access to my private key. This would mean that keybase could use my private key at any time. Somehow there seems to be a flaw in the current setup. I can't recall ever uploading my private key to keybase when I did it the first time.

Please let me know what the problem is and how to fix this.

**Comment by tessus** [comment]
Ok. I've finally found out why keybase wants my private key and what it does with it.

The private key is not uploaded, but added to the local keybase keyring.

**Comment by maxtaco** [comment]
Try `keybase help gpg` for more documentation here.
