### ISSUE TITLE
Icon in KDE's small panel is oversized and clipped

### ISSUE THREAD

**Issue by Avamander** [keybase/client#10060]
![Screenshot](https://i.imgur.com/PVkiecG.png)

It would be nice if it autoresized based on the panel's size.

OS: Kubuntu 17.04

**Comment by anatolyborodin** [comment]
Also related: #7783, #3772

**Comment by anatolyborodin** [comment]
The icon should look and behave like this https://keybase.io/getting-started, but it looks like this:

![screenshot_20180109_131251](https://user-images.githubusercontent.com/35176/34720431-f6aaaeec-f53e-11e7-803e-3078c4a7209a.png)

```
ii  keybase                                 1.0.39-20180108170104.cb amd64                    Keybase's command line client
```

Kubuntu

```
Distributor ID: Ubuntu
Description:    Ubuntu Bionic Beaver (development branch)
Release:        18.04
Codename:       bionic
```

```
ii  plasma-desktop                                  4:5.11.4-0ubuntu2                                          amd64        Tools and widgets for the desktop
```

**Comment by Avamander** [comment]
Okay, latest version (at least since 1.0.45-20180319160058.429a547345) seems to have fixed the situation.

**Comment by Avamander** [comment]
Okay, it's broken again. At least since 2.3.0-20180709200003.45fcb46147 if not earlier.

**Comment by Avamander** [comment]
This is really really weird. It sometimes starts up with the correct, right size icon, sometimes doesn't. On KUbuntu the icon is just oversized, on KFedora it's just really really blurry.

**Comment by Avamander** [comment]
It seems to be fixed now for a last few updates.

**Comment by heini** [comment]
Hmm, just updated to 4.1.0-20190612201656.952fee6c59, and the icon still looks like shown above by @anatolyborodin, so still hardly visible.
