### ISSUE TITLE
Git clone fails with MDServer unauthorized

### ISSUE THREAD

**Issue by ericfode** [keybase/client#10131]
No idea. It happens for one person on my team but not anyone else. 

my log id: 195fdea9b135308bf98da61c

**Comment by iBotPeaches** [comment]
Additionally confirmed. Happened today for 2 members of the team.

log: 5e640725937340932e38a81c

**Comment by maxtaco** [comment]
Sorry guys, should be fixed, can you retry?

**Comment by iBotPeaches** [comment]
@maxtaco All good here. Working great again. Thanks for quick fix.

**Comment by maxtaco** [comment]
Super, @iBotPeaches, thanks for the update. @ericfode you good?

**Comment by ericfode** [comment]
Confirmed!

**Comment by maxtaco** [comment]
:+1: thanks all!
