### ISSUE TITLE
Inconsistent state of a team

### ISSUE THREAD

**Issue by bhean** [keybase/client#10142]
Hi!

Checking the team functions, I created a team, and after a few checks, I removed it...
Now, I'm trying to create the team again, without success...

![image](https://user-images.githubusercontent.com/6599289/34693777-2f40ab46-f4c5-11e7-9696-009d01d9af8a.png)

Looks like if the team was not "totally deleted" or something like that...

Thank you,

**Comment by maxtaco** [comment]
You are not allowed to recreate a team once deleted. We have a pretty big
warning about that.

**Comment by bhean** [comment]
Wow... I didn't see this warning...
I really interested in create the team again... what can I do?

**Comment by maxtaco** [comment]
At some point we hope to work on it but it is buried pretty deep in the
backlog. It doesn’t really come up much.  Sorry but I would just start with
a different team.

**Comment by bhean** [comment]
Ok... there are nothing to do then. Very bad news for me...

Thaks again,
