### ISSUE TITLE
Memory leak with kbfsfuse

### ISSUE THREAD

**Issue by ricpruss** [keybase/client#10172]
Keybase GUI Version: 1.0.39-20180110172312+1d1159e4a

I rebooted yesterday because of the issue and this morning kbfuse is back to 25.097g vitual 4.513g  there is one large text file in the teams directory of 5.3g.

Kernel: 4.4.0-109-generic
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.3 LTS
Release:	16.04
Codename:	xenial

**Comment by strib** [comment]
Sorry about this.  Can you please do a `keybase log send` and report the log ID here?  Also, how are you using it?  Are you the one who tried to write the 5.3g file?  Or just reading it?  Or doing nothing at all?

**Comment by ricpruss** [comment]
No the file was written by someone else on a mac.  I just unwisely ran bunzip2 on it without catting it off to local storage so it made it allot bigger.

**Comment by ricpruss** [comment]
(pyt36) ric@rog17:~/github/universal-portfolios$ keybase log send
This command will send recent keybase log entries to keybase.io
for debugging purposes only.

These logs don’t include your private keys or encrypted data,
but they will include filenames and other metadata keybase normally
can’t read, for debugging purposes.

Continue sending logs to keybase.io? (type 'YES' to confirm): YES
Enter feedback (or ENTER to send): 
▶ INFO ignoring UI logs: context deadline exceeded
▶ ERROR API network error: Post https://api.keybase.io/_/api/1.0/logdump/send.json: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
(pyt36) ric@rog17:~/github/universal-portfolios$

**Comment by strib** [comment]
Hmm that's weird.  Can you try `keybase log send` one more time please?  Maybe it was a temporary flake.

**Comment by ricpruss** [comment]
532b7a2fd56ffe616a55dc1c

**Comment by zatricky** [comment]
Possible this is a duplicate. If not, I can submit a new issue. Memory leak of between 600MB and 850MB per day: e182c0455bfef12021c6781c

**Comment by ricpruss** [comment]
I have not seen this again since early December so by all means close.

Thanks for a great product guys.
Ric

Sent from Astro <https://www.helloastro.com> for Mac

On 14 Mar 2018 at 4:27 pm, Brendan <notifications@github.com> wrote:


Possible this is a duplicate. If not, I can submit a new issue. Memory leak
of between 600MB and 850MB per day: e182c0455bfef12021c6781c

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/keybase/client/issues/10172#issuecomment-372918044>,
or mute
the thread

**Comment by maxtaco** [comment]
@zatricky hard to tell from the logs what's going on here, so give us some more info.  Which process was it?

**Comment by zatricky** [comment]
It's the kbfsfuse process - still running. I have almost zero "content" as I'm not actively using the software. I have memory available, so it is up to 1260M resident currently.

**Comment by maxtaco** [comment]
Cc @strib

**Comment by strib** [comment]
@maxtaco do you know what this error means?  Coming from the service:

```
101851 2018-03-14T07:16:58.393908+02:00 ▶ [INFO kbfs mdserver_remote.go:250] 2999c Error getting current session (No device found no synced devices during pubkey login), skipping resetAuth
101852 2018-03-14T07:16:58.393990+02:00 ▶ [WARN kbfs connection.go:486] 2999d (CONN MDServerRemote 7788225e) Connection: error calling OnConnect handler: No device found no synced devices during pubkey login
101853 2018-03-14T07:16:58.394033+02:00 ▶ [WARN kbfs mdserver_remote.go:376] 2999e MDServerRemote: connection error: "No device found no synced devices during pubkey login"; retrying in 2s
```

@jzila or @songgao can you please take a look and see why this would cause a mem leak?  I don't think I'll have time soon.  Probably in RPC or mdserver_remote.

**Comment by maxtaco** [comment]
I don’t

Cc @patrickxb

**Comment by patrickxb** [comment]
@strib the service doesn't think it is connected so it is not trying to get the device information from the api server.  Since it isn't doing that and there is no device information in leveldb, it can't login.

        if s.G().ConnectivityMonitor.IsConnected(context.Background()) == ConnectivityMonitorNo {
            s.G().Log.Debug("| not connected, won't sync with server")
            return
        }

I'm not sure how it got stuck in this state, the log doesn't go back any further to see.

@zatricky you could try this:

    keybase login

which will probably fix it all up.

If that doesn't work, restarting the app or 

    keybase logout
    keybase login

I'm not sure if this would have anything to do with a memory leak, but the service does seem to be stuck.

**Comment by songgao** [comment]
Sure; I’ll look today.

**Comment by strib** [comment]
By the way @zatricky it would be useful if you could share the file `/keybase/.kbfs_profiles/heap` with us.  There should be anything secret in it, so zipping it and attaching it here should be fine.  Though if you prefer something more secure, and your Keybase still isn't working, we can figure something else out.

**Comment by zatricky** [comment]
Re restarting the app, technically I've been restarting it regularly. It occurred throughout last week with daily shutdowns*. I last restarted the laptop ~31 hours ago and left it at the office whilst troubleshooting this issue.

`keybase login` gave no output with exit status 0 and made no change to kbfsfuse memory status

`keybase logout` also gave exit status 0, also made no change to kbfsfuse memory status, but at least gave the following output in Orange (possibly brown):
`▶ WARNING (CONN gregor 4048bfb8) Connection: error dialing transport: context canceled`

`keybase login` at this point took a long time to get output - but gave exit status 2 with the following output in Red:
`▶ ERROR Operation timed out`

Resident memory is still at 1330M for the kbfsfuse process.

I could probably restart the kbfs service - but won't take action without instructions for now. :)

*the battery is in poor condition and I generally move it between work and home - so hibernation/sleep is out of the question currently

**Comment by songgao** [comment]
@zatricky would you mind sharing that heap file strib mentioned above? It'd help us better understand which part the memory leak might be.

**Comment by strib** [comment]
(Edited my above comment to fix a typo: there *shouldn't* be anything secret in the heap file.)

**Comment by zatricky** [comment]
Inspected the file. It is 1.8M - seems highly compressible. Do you have a preferred upload method?

**Comment by songgao** [comment]
@zatricky if you KBFS is working, please place it at `/keybase/private/songgao,tr1cky`. Otherwise feel free to send me a compressed tarball through email: song@gao.io Thanks!

**Comment by zatricky** [comment]
I wasn't able to copy it there on the laptop itself. rsync'd it to another desktop - worked there. :)

`cp: failed to access '/keybase/private/songgao,tr1cky/heap': Permission denied`

**Comment by zatricky** [comment]
It turned out that the logout worked - just wasn't looking at the GUI so didn't see the prompts for passphrase/etc

**Comment by zatricky** [comment]
To confirm, running updated version. After 5 hours, memory usage at 18MB whilst application is fully functional. Thanks. :)

**Comment by songgao** [comment]
Cool; thanks for confirming @zatricky! I think it should fix your KBFS permission error as well.
