### ISSUE TITLE
cloning a team repo fails

### ISSUE THREAD

**Issue by maxhowald** [keybase/client#10189]
I have a team repo that I can't seem to clone. When I try, it gets to "Counting" and continues to count  upwards at 1 GB/s or so, forever. Note, the actual repo is only a few hundred MB in size, over a few hundred commits.

```
git clone keybase://team/walrussecurity/docs
Cloning into 'docs'...
Initializing Keybase... done.
Syncing with Keybase... done.
Counting: 246.86 GB... ^C
```

One weird thing is, I can initialize an empty repo, manually set the remote, and everything works fine:

```
mkdir docs; cd docs
git init
git remote add origin keybase://team/walrussecurity/docs
git pull origin master
# I can pull the whole repo in a normal amount of time and everything afterwards works fine
```

Pushing and pulling seem to work perfectly fine.

I confirmed this happens on multiple machines and for multiple users, using the latest version of Keybase on Debian Linux. But it only happens for the walrussecurity/docs repo; I can clone our other team repos just fine.

**Comment by strib** [comment]
Hmm, weird, thanks for the report.  Would you mind trying a clone, letting it go for a little while, then running `keybase log send` and reporting the log ID here?  I can take a look.  Thanks!

**Comment by maxhowald** [comment]
I tried that, but I'm not sure it worked. I got both an error message and a success message. So perhaps the logs were sent, but they are empty because of a permissions issue?
 ```
$ git clone keybase://team/walrussecurity/docs
Cloning into 'docs'...
Initializing Keybase... done.
Syncing with Keybase... done.
Counting: 149.65 GB... ^C
$ keybase log send
This command will send recent keybase log entries to keybase.io
for debugging purposes only.

These logs don’t include your private keys or encrypted data,
but they will include filenames and other metadata keybase normally
can’t read, for debugging purposes.

Continue sending logs to keybase.io? (type 'YES' to confirm): yes
Enter feedback (or ENTER to send): I tried cloning a team repo. It gets stuck at "Counting: and just counts upwards
 in GBs forever 
Enter feedback (or ENTER to send): 
▶ INFO ignoring UI logs: context deadline exceeded
Hint: You are currently not seeing messages from other users and the system.
      Users in the 'systemd-journal' group can see all messages. Pass -q to
      turn off this notice.
No journal files were opened due to insufficient permissions.
▶ ERROR Error reading logs: Journalctl exited with an error: exit status 1


------------
Success! Your log ID is:

  683f52e82a50b52bfacace1c

Here's a URL to submit new bug reports containing this ID:

  https://github.com/keybase/client/issues/new?body=[write%20something%20useful%20and%20descriptive%20here]%0A%0Amy%20log%20id:%20683f52e82a50b52bfacace1c

Thanks!
------------

```

**Comment by strib** [comment]
It worked, I got it thanks.  cc: @oconnor663 on the weird systemd errors on the log send above.

**Comment by strib** [comment]
@maxhowald is there anything unusual about the repo, say for example submodules?

**Comment by oconnor663** [comment]
@strib I suspect that warning is just from an old-ish version of systemd. @maxhowald could you show me your `systemctl --version`?

**Comment by maxhowald** [comment]
No submodules. It's kind of big because it has some images and powerpoints. 

It's probably been force-pushed to a couple of times in the past.

**Comment by maxhowald** [comment]
systemd 236
+PAM +AUDIT +SELINUX +IMA +APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD -IDN2 +IDN default-hierarchy=hybrid

**Comment by oconnor663** [comment]
Thanks. Looks like it's very up to date, actually. Let me play with it some more.

**Comment by strib** [comment]
@maxhowald I think I see the problem; it is actually happening for one of my private repos too.  It looks like this repo was created before we put a fix in that ignored requests for creating a `.` directory.  Now it is stuck in a loop while walking the directory tree, continually recursing on `.`.

I will fix the recursive code to ignore the `.` directory, and should be able to get that out in the next release.  In the meantime, deleting and recreating the repo should fix the issue, if that's an acceptable solution for you.  (I don't think anyone on the team would see any effects as long as you give it the same name after you delete it, and do a `git push --mirror` from a local checkout to populate it.)  Or you can wait for the next release.

**Comment by oconnor663** [comment]
Ok, I think that's a warning that I don't see because I'm in my system's `wheel` group, but that users not configured that way will see. The `-q` flag that it suggests to suppress it will also remove `-- Reboot --` and similar info lines from journal logs we pull, which is a shame. Another option would be to suppress stderr entirely, but then I'm afraid of losing more interesting error messages if something unexpected happens.

I think I'll actually file an upstream bug. It doesn't make much sense to print that warning when the `--user-unit` flag is in use, as it is here. We're not trying to read logs from other users or the system, of course.

**Comment by maxhowald** [comment]
Great, thanks! This repo was indeed created very shortly after the release of keybase git.

As for a workaround, the manual init + pull will works just fine for the short-term, but thanks for the tips.

**Comment by maxhowald** [comment]
@oconnor663 just a note, even if I run it with -q, it still exits with nonzero status, so keybase will probably still print (part of) the error message.
```
$ journalctl -q
No journal files were opened due to insufficient permissions.
$ echo $?
1
```
