### ISSUE TITLE
Keybase Cilent FS sharing does not work

### ISSUE THREAD

**Issue by nambrot** [keybase/client#10191]
I have created a folder under `/keybase/private/nambrot,otherusername` and put a file in there, but it does not look like it is available for `otherusername`, nor for me on my other devices. Am I missing something obvious?

**Comment by strib** [comment]
I don't know!  If you're on macOS, did you and the other user both install the FS kernel drivers from the Folders tab in the Keybase GUI?  If not, please do so.  If so, please run `keybase log send` and report the log ID here and I can take a look.

**Comment by nambrot** [comment]
Wow, this is such a great setup. My id is `46cf6bc1ed91f5a3edfe301c`. I have installed both FS drivers. My private folder syncs among my devices, just not the one shared with `otherusername`. Thanks!

**Comment by nambrot** [comment]
@strib fixed this for me! My client ended up in an inconsistent state
