### ISSUE TITLE
Can't use chat on Fedora 27

### ISSUE THREAD

**Issue by hreese** [keybase/client#10201]
Keybase GUI Version: 1.0.39-20180112170026+092199594

GUI shows error `ERROR CODE 218 - method 'teamListUnverified' not found in protocol 'keybase.1.teams' in method keybase.1.teams.teamsListUnverified` on startup. Opening/starting any chat results in a neverending display of the green `securing…` animation. Keybase works on Windows, Android and iOS. Chat returns to working state when someone sends a message to it.

Restart using `run_keybase-` does not fix the problem.

Running `keybase chat ls` alternates between two states:
* `INFO Starting keybase.service.` + last chat messages
* `WARNING Restarting after upgrade; service is running v1.0.34, while v1.0.39-20180112170026+092199594 is available` and
`ERROR dial unix /run/user/1000/keybase/keybased.sock: connect: no such file or directory`

my log id: a44f4ba13ff94b3bcaff9c1c

**Comment by maxtaco** [comment]
Quit the app and try ‘killall keybase’

**Comment by hreese** [comment]
> Quit the app and try ‘killall keybase’

@mextaco Does not fix the problem. I even added a `killall kbfsfuse` to get rid of everything.

**Comment by maxtaco** [comment]
Maybe it's a path problem.  Seems like the old version of `keybase` is still on your system.  Try `keybase --version`.  

@oconnor663: is this some sort of `systemd` conundrum?

**Comment by maxtaco** [comment]
Also, do `ps -ax | grep keybase` and `which keybase`.  The service process is the older version of keybase and everything else is the newer version. I'm not sure how that happened.

**Comment by hreese** [comment]
```
# keybase --version
keybase version 1.0.39-20180115170027+d47493abf
```

```
# which keybase
/usr/bin/keybase
```
Here's the culprit:
```
# ps -ax | grep keybase
[…]
$HOME/go/bin/keybase -d service
[…]
```
Looks like I compiled a keybase client three month ago and never got rid of it.

`/usr/bin` is searched before `$HOME/go/bin`, I wonder why `$HOME/go/bin/keybase` go called.

The keybase GUI client is currently stuck in the loading screen. I'll get my system in a cleaner state and either report back or close the ticket…

**Comment by hreese** [comment]
```
# keybase --version
keybase version 1.0.39-20180115170027+d47493abf
```

```
# which keybase
/usr/bin/keybase
```
Here's the culprit:
```
# ps -ax | grep keybase
[…]
$HOME/go/bin/keybase -d service
[…]
```
Looks like I compiled a keybase client three month ago and never got rid of it.

`/usr/bin` is searched before `$HOME/go/bin`, I wonder why `$HOME/go/bin/keybase` go called.

The keybase GUI client is currently stuck in the loading screen. I'll get my system in a cleaner state and either report back or close the ticket…

**Comment by hreese** [comment]
Note for everyone who build the client from scratch and didn't clean it up: make sure to remove all binaries from `$GOPATH/bin` **and** `$HOME/.config/systemd/user/keybase.service`.

**Comment by maxtaco** [comment]
👍 Glad it's fixed 👍
