### ISSUE TITLE
keybase.io - site validation fails for HTTPS only site (update: works in keybase CLI with warnings)

### ISSUE THREAD

**Issue by robertpeteuil** [keybase/client#10208]
**updated with workaround - use `keybase` CLI)**

**keybase.io issue**
Site validation broke after switching website to `https` only (`http` no longer routed)
- the [proof](https://www.robertpeteuil.com/keybase.txt.bak) was available, even though keybase cannot see it.  

**Failed fix**
Used *keybase.io* to revoked & re-add the website, hoping it would re-try on https:
- Adding the URL resulted in the error: **That domain isn't loading. Are you running a site there?**
- **Yes** I'm running a [website](https://www.robertpeteuil.com) there.

**Workaround**
Used keybase CLI command  `keybase prove https`  (note: `https` isn't listed for prove in help, but it works)
- It found the site and proof text was displayed
- However, while it was waiting for me to type 'y' to verify the proof, *a connection error warning message was displayed (included at bottom of post).*
- After placing the proof text into the proper file and typing `y`, it correctly verified my site.

Here's the warning message that was displayed in yellow:
> *WARNING (CONN keybase service 59798407) Connection: error dialing transport: x509: certificate signed by unknown authority (possibly because of "crypto/rsa: verification error" while trying to verify candidate authority certificate "Keybase KBFS CA prod")*

**Comment by Ryonez** [comment]
I'm surprised you closed this, a workaround doesn't mean a valid issue is fixed.

**Comment by robertpeteuil** [comment]
Good point. Is this still an issue as I described?  If so, I’ll reopen it

**Comment by Ryonez** [comment]
I don't know, I use dns validation. Guess it'll be left to someone else.
