### ISSUE TITLE
Windows 10 Explorer Keybase folder squatted by Google Drive File Stream

### ISSUE THREAD

**Issue by claudiobgit** [keybase/client#10268]
A weird thing happened this morning after the automatic update of _Google Drive File Stream_ on my Windows 10 Pro machine. I cannot see anymore _Keybase_ folders under L:\ and instead I have a Google  takeover.

I attach below a screenshot where you see K:\ now not accesible and L:\ with Property Window detail with the OG Keybase icon in place and a way different content.

![image](https://user-images.githubusercontent.com/20387258/35168078-f7508530-fd57-11e7-9a82-d25423757e4d.png)

**Note: This is probably not a Keybase direct issue but something that would be rad to investigate on and that may affect others.**

**Comment by zanderz** [comment]
It looks like this is a giant Google problem and the only workaround is to twiddle registry entries:
https://productforums.google.com/forum/#!topic/apps/5ORv8wJBe8U;context-place=forum/apps
looks like lots of rage-quitting over this.
