### ISSUE TITLE
Support purpose-specific PGP keys, with team support

### ISSUE THREAD

**Issue by hach-que** [keybase/client#10273]
We're using keybase to support easy signing and verification of NPM packages in [pkgsign](https://github.com/RedpointGames/pkgsign). Currently it works great for single developers (who use keybase) and organisations (which just publish a PGP public key on a HTTPS URL).

However, we need to find a good solution for groups of developers, where the signer of a package might rotate. We also need to handle scenarios like developers leaving the team and who should no longer have rights to create a signed package.

Keybase has this nice thing called Teams, which is built for groups of individuals. Unfortunately it doesn't (yet?) have any kind of key system for signing things on behalf of a team.

Ideally I think a solution could look something like this:

**For individuals, allow Keybase to generate PGP keys that are for a predefined purpose.**

So as part of pkgsign when we're signing the package, we could request a once-off PGP key for the purpose of "npm-package:pkgsign@0.1.3". We sign the package with the private key provided, and Keybase publishes the public key at https://keybase.io/hachque/pgp_role_keys/npm-package%3Apkgsign%400.1.3.asc.

We know the version and package name, so we'd be able to calculate the URL at which to expect the PGP key. This ensures newer packages can't be signed with a different, older public key which an attacker might know the private key to.

We'd also need users some way of revoking previously issued role keys in the case of compromise.

By supporting the feature at this level, we have a consistent interface to also use with teams. It also reduces risk (because private keys aren't imported into PGP or elsewhere, and are used for a once-off signing operation), and reduces impact in the case of compromise because only a single package version would be affected.

**For teams, the same feature basically, with PGP keys underneath a team identifier instead of a user URL**

With role-specific keys, when old team members are removed from a team, they'll no longer be able to generate private/public key pairs for roles for the team, and thus can not sign for new package versions automatically.

So this is basically the same feature as for individuals, but with keybase presenting the PGP keys underneath a team-based URL like, https://keybase.io/team/someteam/pgp_role_keys/npm-package%3Apkgsign%400.1.3.asc.

**Comment by junderw** [comment]
I like the idea, but in order for the verifier to know that it is actually you, they would need the keybase client to verify your sigchain / the sigchain of the team.

Otherwise you're just kicking the can down the road and trusting the owner of keybase.io DNS record.

**Comment by junderw** [comment]
and I don't think a bunch of developers would like the "you need to install keybase to verify" requirement as it seems there is a small vocal community that have qualms with some of the decisions made by this app... plus keybase is a lot heavier than a simple GPG install where all the WOT management is done manually by the user... keybase tries to automate and do that in the background using social proofs etc.

I reeeeeeally like the idea of pkgsign and I hope that keybase can offer a solution though.

**Comment by maxtaco** [comment]
This is a very nice idea.  For this to work, we need *public* teams, for which membership information is available to non-members.

We've built public teams and are slowly releasing them, but the UI probably needs a fair amount of work.

Would it be OK to use EdDSA (in PGP) for this? Or would you need an old-school RSA PGP key?

**Comment by hach-que** [comment]
@maxtaco We're using https://github.com/openpgpjs/openpgpjs to verify the PGP signature. It looks like support for EdDSA might have been added recently? https://github.com/openpgpjs/openpgpjs/pull/618

@junderw Users can use PGP public keys at HTTPS URLs instead of Keybase if they prefer to host the PGP public key themselves. In this case the identity is the full HTTPS URL instead of the Keybase user ID. We don't yet install the Keybase client.

At this point we're trusting keybase.io, because our options are:
- Ship the keybase client. Keybase could always just ship a compromised client through automatic updates or through whatever mechanism we use to download the client, so I don't believe this gains us any additional trust.
- We reimplement verifying the sigchain of a Keybase user inside pkgsign. This sounds like a lot of work since as far as I'm aware, that basically involves reimplementing a good portion of the Keybase client.

**Comment by mahrud** [comment]
@hach-que EdDSA is only in the `openpgpjs/ecc_nist` branch for now (disregard the "nist" in the title). The plan is to review and merge it by the end of the month.

**Comment by jacob-koren-zooz** [comment]
Any progress here?
