### ISSUE TITLE
Merkle root no longer being hashed to blockchain.

### ISSUE THREAD

**Issue by primis** [keybase/client#10282]
As of December 8th, keybase has stopped hashing itself to the Bitcoin blockchain. [According to Bitref](https://bitref.com/1HUCBSJeHnkhzrVKVjaVmWg2QtZS1mdfaz) there is still a balance in the wallet. It might also be in the best interest of keybase to change to a cheaper coin in the future (like Etherium).

**Comment by maxtaco** [comment]
Agreed it's an issue, we're working on something, but have been busy with a product release.

**Comment by holvonix-eng** [comment]
Looks like it was working again until April 23, and then died again.  Is this not expected to work anymore?

https://blockchain.info/address/1HUCBSJeHnkhzrVKVjaVmWg2QtZS1mdfaz

**Comment by TravisWhitehead** [comment]
It looks like the blockchain transactions have been going strong for a while now, so it might be okay to close this.
