### ISSUE TITLE
Importing from GPG2 (macOS) into Keybase using CURL is fooked.

### ISSUE THREAD

**Issue by MiGzY** [keybase/client#10293]
$ curl https://keybase.io/[them]/key.asc | gpg2 --import
curl: (3) [globbing] bad range in column 21
gpg: no valid OpenPGP data found.
gpg: Total number processed: 0

**Comment by maxtaco** [comment]
Your command line is producing a curl error. Who is `[them]`? You have to put an actual username there without square brackets.

**Comment by MiGzY** [comment]
OK thanks for the heads up maxtaco, I didn't notice the [them] bit, should be [username] in the code tip on the site?

**Comment by MiGzY** [comment]
It tried and failed again.  Must be because my key hasn't imported properly into the keybase database...

curl https://keybase.io/miguelmanzano/key.asc | gpg2 --import
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    32  100    32    0     0     56      0 --:--:-- --:--:-- --:--:--    56
gpg: no valid OpenPGP data found.
gpg: Total number processed: 0

**Comment by maxtaco** [comment]
Visit [this url](https://keybase.io/miguelmanzano/key.asc) and you'll see you don't have a key on keybase

**Comment by MiGzY** [comment]
That's strange because I assigned it on the website and it said it was OK.  I'll try again thanks Max.
