### ISSUE TITLE
Can't sync folders?

### ISSUE THREAD

**Issue by ili-codes** [keybase/client#10305]
I'm using Keybase to encrypt files in my `private` folder, as well as share with my `public` folder.
I got a new computer, revoked the old one, added it back under a different name.

My old computer was a MacBook and I bring it to school, however when I'm home I do my schoolwork on my new desktop Hackintosh, and I keep my school files sync'd on my `private` keybase folder.

Recently, changes I've made on my MacBook don't reflect on my Desktop, and vice versa. Same thing with my other 2 computers I use as backups.

I rekeyed everything, but I checked `keybase rekey status` and it outputs `No TLFs need rekeying.` right after I begin the rekey.

Not sure what's going on.. but I'd like to keep my files in sync.

Thanks for the amazing service!

Keybase GUI Version: 1.0.39-20180122031025+5e5798149

**Comment by strib** [comment]
Hi @ili-codes, hmm one of your devices might be stuck in a bad state.  Can you please do a `keybase log send` from both your MacBook and your Hackintosh, and post the resulting log IDs here?  I can take a look.

**Comment by ili-codes** [comment]
`0b1c3ec6f384b4440674051c`: Hackintosh
`e94c00477c46ed26dce9991c`: MacBook

**Comment by strib** [comment]
Thanks for the logs!  It looks to me like things are fine, though the MacBook finished syncing its files after you did the `Hackintosh` log send.  So maybe the files were still being synced when you checked, and it was taking a while, and when you turned the MacBook back on, things started working again.  Do they look to be in sync now?

**Comment by ili-codes** [comment]
Oh yeah, they are synced! It's taking a long time though. It's never taken this long.

Thanks!
I'll close this issue now.
