### ISSUE TITLE
Keybase CLI Powershell Coloring

### ISSUE THREAD

**Issue by Wolf1098** [keybase/client#10368]
Keybase cli when producing an -ERROR- break the coloring scheme of Powershell. I am wondering if it was possible for Keybase to check the style properties and use them instead of defaulting to red on black text then back to white on black text. Especially with Powershell being the new "defacto" command shell on of Windows for quite some time. [https://blogs.windows.com/windowsexperience/2016/11/17/announcing-windows-10-insider-preview-build-14971-for-pc/](url) --link worked 2018-01-27
I understand not everyone will change to using Powershell and cmd.exe usage will persist for the far future but it would be nice to not have to reset Powershell when I encounter an error. The same change would apply to anything that changes/recolors the text

log id: 0f87b2275e6e8271ea4e811c

**Comment by maxtaco** [comment]
Cc @zanderz

**Comment by zanderz** [comment]
Verified this regression and have a fix for an upcoming release. Note this is an issue for any nonstandard color scheme, not just Powershell.
Tracking internally with CORE-7128
Thanks for the report.
