### ISSUE TITLE
run_keybase failed after 1.0.40

### ISSUE THREAD

**Issue by willysr** [keybase/client#10367]
I'm updating kbfs from 1.0.38-20171221170044+4c1f9803e to 1.0.40_20180127033950+76a4b90c9 on top of Slackware and now i suddenly can't complete run_keybase with the following error

Shutting down keybase service...
Launching keybase service...
Mounting the file system...
Cannot get keybasehelper user: user: unknown user keybasehelper

I tried to add keybasehelper user but still no luck.

Everything works well with 1.0.38, but suddenly it failed in 1.0.40.

Any pointers would be appreciated.

Thanks

**Comment by strib** [comment]
Hi @willysr, sorry about this.  I don't have a Slackware environment to test, but the new package post-install do a `useradd --system -s /bin/false -U -M keybasehelper` as root -- does that not work on Slackware?  Is there an equivalent command that works?

**Comment by strib** [comment]
It looks like there might be a community package for Slackware I didn't know about, that doesn't use our debian post-install script?  Sorry about that!  I guess you would have to the new things in the post-install script manually: https://github.com/keybase/client/blob/76a4b90c976368f55a534c9fed3518d40b09e722/packaging/linux/post_install.sh#L22-L48

**Comment by willysr** [comment]
OK, i managed to fix that by creating a post-install on my side.

However, the mount point is no longer in /keybase, but rather in /var/lib/keybase/mount1.
Is that by design?

**Comment by strib** [comment]
@willysr the new `run_keybase` script is supposed to create a `/keybase` symlink pointing to `/var/lib/keybase/mount1`, which is managed by the suid program `keybase-mount-helper` and is supposed to be turned into `~/.local/share/keybase/fs` the first time you run `run_keybase`.

**Comment by strib** [comment]
(Edited the above, I meant the post-install script creates the /keybase symlink.)

**Comment by willysr** [comment]
perhaps it failed on my end since i don't setup sudo here?
FYI, i'm using deb format as the source and extract them, so no post-install script is executed here

**Comment by strib** [comment]
Yeah, you need to do the post-install things I linked above, manually I guess if you don't want to run the script itself.

**Comment by willysr** [comment]
ok, got it

Thanks @strib

**Comment by strib** [comment]
Sorry for breaking this, I didn't know about the slackware package.  Let me know if I can help more.

**Comment by willysr** [comment]
you have been a great help on this issue.
i'll let you know if i found another issue.

Thanks

**Comment by willysr** [comment]
Now i got this
```
ls -al / | grep keybase
lrwxrwxrwx   1 root    root     23 Jan 28 00:22 keybase -> /var/lib/keybase/mount1

ls -al /var/lib/keybase/
lrwxrwxrwx  1 keybasehelper users           37 Jan 28 00:22 mount1 -> /home/willysr/.local/share/keybase/fs
```
I hope it's correct per upstream design

**Comment by strib** [comment]
Yep, that looks right.  is it working?

**Comment by willysr** [comment]
yes, all files are in place and keybase GUI is running well here
