### ISSUE TITLE
Remove colors from the menu bar icon in MacOS

### ISSUE THREAD

**Issue by groue** [keybase/client#10371]
Hello,

Would it be possible to have a colorless icon in the menu bar?

The current icon looks like something requires my attention, and is distracting. It does not honor the platform conventions.

<img width="291" alt="capture d ecran 2018-01-27 a 14 41 15" src="https://user-images.githubusercontent.com/54219/35472477-36aeefc8-0370-11e8-8982-6ca521de71bb.png">

Furthermore, after the icon has been muted, you'll be able, in the future, to add colors in it, for whatever good reason you will come up with.

Thanks for reading, and for the excellent software in general 😄

**Comment by groue** [comment]
I also have the feeling that this issue is one of the reasons behind #9418.

**Comment by will-normand** [comment]
I think the colour icon is actually indicating that you've got unread messages.  I spent a while hunting through the Settings, Google results and this github repo trying to work out why my menu bar item had changed last week.  

Then I dismissed the 'new feature' message from the People tab in the Keybase app (I think it was advertising "Teams" or something).  The menu bar icon immediately went back to black!

So it seems like this is a feature, but to me changing the whole icon to colour doesn't indicate new notifications very well and I can't think of any other app which does this.

**Comment by groue** [comment]
Hello @will-normand. I think you're right, Keybase is trying to notify me something.

The issue should be renamed: "unable to clear notification badge".

Because I'm unable to remove this notification and colorful icon, despite heavy random clicking.

**Comment by groue** [comment]
Even more random and purposeless clicking later, I managed to remove the color. Keybase was talking about a *lot* of things very interesting but not quite as interesting as it thinks : news like git repo support, strong suggestion to edit my profile, whatever.

None if these had the right to hijack my attention. This menubar icon gave me a lot of shit work until I could mute this annoying color (a *lot* of random clicking + opening this issue). This is the essence of what needs to be fixed :-)

**Comment by groue** [comment]
It happens again, with Version 1.0.45-20180305194145+3a1c65a05:

It's impossible to remove a notification that some user has started following me. No matter where I click, this notification is sticky, and makes the menu bar icon forever colorful.

**Comment by maxtaco** [comment]
What if you click to the home screen, so that you see the badged row, the
click to chat tab?

**Comment by groue** [comment]
I see the badged row in the main window: blue bar on the left, People tab selected (with a red dot), notification row at the top, reading "foo followed you" and a red dot on the right. From here, whatever I click, those red dots just won't vanish 😅

**Comment by maxtaco** [comment]
Please do `keybase log send`

**Comment by maxtaco** [comment]
Also, if you can, please send me a screenshot of what you see (censoring any private info). Thanks

**Comment by groue** [comment]
Sure!
![keybase](https://user-images.githubusercontent.com/54219/37466128-4836dc1c-285d-11e8-8614-7acbd9ffd70c.png)

**Comment by maxtaco** [comment]
Thanks, if you send a log, I'll take a look on our side.

**Comment by groue** [comment]
> Your log ID is:
>
> 158c9be9abfe71b8b4e1881c

**Comment by maxtaco** [comment]
Thanks. If you visit [this link](https://keybase.io/_/api/1.0/home.json?record_visit=1) when logged in from your browser, does it clear it?

Cc: @buoyad  and @keybase/react-hackers, the log shows that `markViewed` isn't being called.

**Comment by groue** [comment]
I'm logged in my browser, I click the link (which outputs a lot of JSON). The badge remains colorful. Quit Keybase App, relaunch: red dots are still there.

**Comment by maxtaco** [comment]
How about now, did the badge clear?

**Comment by groue** [comment]
YES! 🎉

**Comment by maxtaco** [comment]
OK, glad it's fixed, I'm still unsure why (1) your client wasn't calling `markViewed` or; (2) your visiting that link didn't clear the badged. I guess reopen this ticket if the problem recurs.

**Comment by groue** [comment]
All right! Thank you very much @maxtaco!!
