### ISSUE TITLE
Linux Mint: Autostart cannot be disabled

### ISSUE THREAD

**Issue by goetzkluge** [keybase/client#10385]
Autostart cannot be disabled. Also disabling autostart after login in the Linux Mint configuration settings is overridden once Keybase is started again.

Observation on the side: After quitting from Keybase and running »pkill keybase«, the »df« command gets stuck.

**Comment by dabura667** [comment]
You need to remove the entry from crontab.

**Comment by goetzkluge** [comment]
dabura667, you guided me to crontab. That helped me to understand the issue although in Linux Mint I have no crontab. I found this file

~/.config/keybase_autostart.desktop:
```
# This file is autogenerated when Keybase starts. Keybase will recreate it if you
# delete it, so to disable autostart you should uncomment the line below.

[Desktop Entry]
Name=Keybase
Comment=Keybase Filesystem Service and GUI
Type=Application
Exec=env KEYBASE_START_UI=hideWindow run_keybase

# Uncomment the following line to disable Keybase autostart:
#Hidden=true
```
It seems, that in Linus Munt (and Ububntu?), disabeling autostart via GUI doasn't do anything. But uncommenting the last line does the job.

**Comment by dabura667** [comment]
Linux Mint has a crontab.

I use Linux Mint and I use crontab all the time.

**Comment by dabura667** [comment]
Glad to hear you found a solution

**Comment by heronhaye** [comment]
You can also do this with `keybase ctl autostart --disable`.
