### ISSUE TITLE
[git] can't clone into /team/keybasefriends/demo

### ISSUE THREAD

**Issue by NobbZ** [keybase/client#10383]
```
$ git clone keybase://team/keybasefriends/demo
Cloning into 'demo'...
Initializing Keybase... done.
Syncing with Keybase... done.
git-remote-keybase error: (1) Journal not enabled for 4d78ca7513472c7ada3b7948ed027226
```

log id: 32b019b130ab425012f58c1c

**Comment by strib** [comment]
Hi @NobbZ, it looks like you may have built this yourself, rather than using an official package?  If so, what commit of the KBFS repo are you building from?  This error looks similar to ones we fixed a long time ago, so I'm wondering if you're using an out-of-date build.

**Comment by NobbZ** [comment]
Im using the provided package of my Linux distribution (funtoo), I'll check which version it identifies itself as as soon as I'm back at my computer. Also I'll report back how it's obtaining the sources to build the package.

**Comment by NobbZ** [comment]
The package installs from the following file:

https://github.com/keybase/kbfs/archive/v1.0.36.tar.gz

The reported version in `keybase status` does match the version of the source archive.

If there were newer releases I could easily override the version with a local package, but I do not want to build from pure git checkout...

**Comment by strib** [comment]
Thanks for looking into it.  I just tagged a 1.0.40 release: https://github.com/keybase/kbfs/archive/v1.0.40.tar.gz

Hopefully your package can be updated to use that instead.  Sorry for the lazy tagging.

**Comment by NobbZ** [comment]
Works with the new release.

I'd be happy if there were releases more often. The only way for the packaging team of my distro to know about a release is a formal channel that announces them. Github-releases and tags are a well known channel for them. 

For the CLI tagging is done, and so far I never was more than a single release (tag) behind.

**Comment by NobbZ** [comment]
PS: I consider this one closed, but shall I probably open an issue at the KBFS repo for having releases/tags more often?

**Comment by maxtaco** [comment]
We should have a public releases channel in a keybase team. Good way to get
more signatures on the binaries too.

**Comment by NobbZ** [comment]
I do not think that the packaging team of funtoo or the upstream packaging team of gentoo would look into that channel. How ever updates get communicated, it needs to be as public as possible especially without the necessity of installing additional tools.

The github API is already used by those teams to become aware about releases.

By requiring them to install keybase to actually get aware of releases, we will never get it properly into (fu|ge)ntoo, which I'd consider a pity then.

I'd also like to push having the GUI available, but that is just another topic.
