### ISSUE TITLE
keybase doesn't start with run_keybase

### ISSUE THREAD

**Issue by infosec-o4it** [keybase/client#10387]
Debian buster / Linux 4.14.0-2-amd64
i can't start my keybase with run_keybase.
my log id: edce61927d4b8be24f78991c

**Comment by maxtaco** [comment]
Check permissions, did you run something as root by accident?

**Comment by infosec-o4it** [comment]
no, the file *.sock  doesn't exist, I delete all files in ~/.config/keybase/* and reboot, for that keybase starts but require a new login, so I log again and create a new device.

**Comment by strib** [comment]
@infosec-o4it why did you delete all the files in `~/.config/keybase`?  Was it before or after you started having the issue?  In any case, are things working for you now that you created a new device?

**Comment by infosec-o4it** [comment]
yeah, pretty fine!
