### ISSUE TITLE
git upstream is gone (remote repo is suspiciously empty)

### ISSUE THREAD

**Issue by fleish** [keybase/client#10391]
I created a team git repo to test out the functionality. It was/is a very low-volume repo, with only a handful of commits by me. Things seemed to work OK at first, but now I'm trying to work in the repo again and it seems the remote repo is empty. Checking the Keybase desktop client, it claims the last push to this repo was 18 days ago by me, which gives with what I see in my local git log:

commit xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx (HEAD -> master)
Author: Fleish
Date:   Thu Jan 18 11:39:12 2018 -0800

A git pull returns this:
Initializing Keybase... done.
Syncing with Keybase... done.
Your configuration specifies to merge with the ref 'refs/heads/master'
from the remote, but no such ref was fetched.

So I decided to try and clone it from scratch and got this:
Cloning into 'reponame'...
Initializing Keybase... done.
Syncing with Keybase... done.
warning: You appear to have cloned an empty repository.

Finally, git status shows this:
On branch master
Your branch is based on 'origin/master', but the upstream is gone.
  (use "git branch --unset-upstream" to fixup)

nothing to commit, working tree clean

Any ideas what could have caused this? I've got the same files in a private keybase git repo and it is still intact. I'm not sure if I did something in the team repo that caused this, or if it's a failure on the Keybase end of things or what. Thanks in advance.

**Comment by strib** [comment]
@fleish can you please do a `keybase log send` and report the log ID here, and I'll take a look.

**Comment by strib** [comment]
Also note that you can inspect the bare git repo yourself by navigating to `/keybase/team/<teamname>/.kbfs_git/<reponame>`.  But note it is dangerous to change anything in there.

**Comment by fleish** [comment]
@strib 941c28162c326925a981311c

FWIW, I don't see any .kbfs_git directory in /keybase/team/<teamname>

ls: .kbfs_git: No such file or directory

**Comment by strib** [comment]
@fleish you have to go into the <teamname> under `/keybase/team`.  And note it's a magic folder that doesn't show up in `ls -la`, you just have to `cd` into it.

**Comment by strib** [comment]
@fleish I don't see anything weird in the logs.  My best guess is that someone accidentally deleted the branch with a "push :refs/heads/master" or something like that.  You can probably restore it by pushing from the local branch.

**Comment by fleish** [comment]
@strib thanks for checking, that seems like a fair enough assumption. Though I am curious, would that action not show up as a more recent "last push" in the keybase UI?

**Comment by strib** [comment]
Good question.  I think deleting branches goes through a slightly different path and it might not end up in the GUI.  I think we will start showing deleted branches in the chat history for the team soon, but that's not ready yet.  Let me know if I can help with anything else.

**Comment by fleish** [comment]
Sounds good, thanks.
