### ISSUE TITLE
several issues with linux client started recently

### ISSUE THREAD

**Issue by williamkray** [keybase/client#10394]
I get a lot of errors, as described in my log-send comments. here are some screenshots, but the gist of it is:

unboxing errors almost every time i switch to a different team channel (https://imgur.com/a/ydbeJ)
channels disappear from the ui, and i have to run `run_keybase` to see them again
a weird mystery team without a name, and any investigation of it returns an error suggesting i run `keybase log send` (which is why i'm here) https://imgur.com/kFDhfj4 (jobmachine is an actual team, but the empty user logo is the one that i clicked the gear next to in this screenshot, which then shows me the following error: https://imgur.com/a/tWETL)

my log id: b569bf0f8411655feee5951c

**Comment by maxtaco** [comment]
Pretty sure we fixed this bug, can you upgrade your app?

**Comment by maxtaco** [comment]
cc: @mlsteele / @oconnor663

**Comment by williamkray** [comment]
i've updated and restarted, will need to wait a while to see if the issue presents itself within the next hour or so.

**Comment by williamkray** [comment]
looks like that did the trick, haven't seen those errors so far! sorry for the false alarm folks.

**Comment by maxtaco** [comment]
cool thanks!
