### ISSUE TITLE
Neither in nor not in a team

### ISSUE THREAD

**Issue by abstractOwl** [keybase/client#10400]
I was added to a team before I installed the Keybase app (not sure if that's relevant) and it seems like I'm in some bizarre limbo state where I'm neither in nor not in a team.

```
λ> keybase team list-memberships
Team    Role    Members
λ> keybase team list-requests
No requests at this time.
λ> keybase team request-access techworkersco
▶ ERROR You are already a member of this team (code 2665)
λ> keybase team leave techworkersco
▶ ERROR You are not a member of this team (code 2623)
```

**Comment by maxtaco** [comment]
Can you `keybase log send`? Thanks

**Comment by abstractOwl** [comment]
```
Success! Your log ID is:

  d03cba30132851af91c4891c
```

**Comment by zapu** [comment]
Was the admin of the team online since you tried that?

**Comment by abstractOwl** [comment]
Looks like the issue has been resolved by the admin updating their keybase client and logging back in
