### ISSUE TITLE
Keeps creating directory named " (quote)

### ISSUE THREAD

**Issue by thejpster** [keybase/client#10426]
I found a mysterious folder in ~ called ". I deleted and on the next reboot it reappeared.
It seems to have a keybase folder inside it.

```
$ pwd
/home/jonathan
$ ls \" -ld
drwxrwxr-x. 3 jonathan jonathan 4096 Feb  4 15:34 "
$ find \"
"
"/home
"/home/jonathan
"/home/jonathan/.local
"/home/jonathan/.local/share
"/home/jonathan/.local/share/keybase
"/home/jonathan/.local/share/keybase/fs"
$ keybase --version
keybase version 1.0.40-20180126170042+ae6b97736
$ cat /etc/fedora-release 
Fedora release 27 (Twenty Seven)
```

It seems some bad escaping has occurred.

**Comment by strib** [comment]
Hi @thejpster, sorry about this, I think you got a bad release that was live for an hour or two.  Please upgrade to the latest release and then do some manual cleanup.

```sh
sudo rm /var/lib/keybase/mount1
sudo ln -s /opt/keybase/mount-readme /var/lib/keybase/mount1
sudo chown keybasehelper:keybasehelper /var/lib/keybase/mount1
run_keybase
```

After that you should be able to delete it and it won't come back.
