### ISSUE TITLE
Unable to rekey folders, chat

### ISSUE THREAD

**Issue by mpatton125** [keybase/client#10422]
Just re-installed Keybase on my laptop and got a message that some folders needed rekeying and to open keybase on my other machine.  The other machine is a headless server and so I use the command line exclusively there.

I tried creating a paper key on the server and rekeying, but nothing seems to get rid of the messages on my laptop.  Logs are from the laptop.

my log id: cd150472baa1d763608c3e1c

**Comment by strib** [comment]
Looks like the folder in question is only keyed for your device `Server-Home`.  Is that device online? If not can you run Keybase on there and see if it fixes the problem?

**Comment by mpatton125** [comment]
Yes that's my headless server, and it's online.

**Comment by maxtaco** [comment]
It could be your keybase instance died when your session ended.  Is keybase running on your headless server?

**Comment by strib** [comment]
Can you please send logs from your headless server too?

**Comment by mpatton125** [comment]
For the headless server:

7eadcf90701e27fb164e041c

**Comment by strib** [comment]
@mpatton125 KBFS doesn't seem to be running on that server.  Did you run `run_keybase`?  That's required on Linux.

**Comment by mpatton125** [comment]
That seems to be it.  I had run `run_keybase`, of course, but I wasn't aware I had to run it every time I wanted to use keybase.  I thought it was just a final installation step.

All working now, thank you!
