### ISSUE TITLE
Network errors after reinstalling

### ISSUE THREAD

**Issue by mike-au-451** [keybase/client#10457]
On a fresh xubuntu instance (Ubuntu 17.10), following instructions at https://keybase.io/docs/the_app/install_linux, the following
![keybase_2018-02-07_14-51-23](https://user-images.githubusercontent.com/35354157/35899742-d3254a9e-0c19-11e8-85ce-59d0f81a7c93.png)
:

1.  DNS seems to have crashed.  This might be a coincidence.  See the attached screenshot.

2.  Attempting to login using the command line results in timeouts:

▶ ERROR {-} Error in transport: API network error: doRetry failed, attempts: 1, timeout 5s, last err: context deadline exceeded
▶ WARNING fixHeaders: need session, but session token empty

3.  Attempting to obtain the status results in timeouts:

mike@bugz:~> keybase status
▶ ERROR LoginState request timeout - attempted: loginReq loginProvision.device - Run provisionee [yZLwdyBr], active request: acctReq LoggedInProvisionedCheck [3ANkw7x7], duration: 5.000909774s

Moreover the login process seems to want me to change device names, which I find puzzling.

At the moment I am unable to log in.  Any suggestions?

**Comment by maxtaco** [comment]
This all seems according to plan (maybe the error messages can be prettified).  Seems like your network is down (does a browser work?) and that since you reinstalled, you need to provision a new device.
