### ISSUE TITLE
Keybase private git for server backup

### ISSUE THREAD

**Issue by TomFaulkner** [keybase/client#10473]
Not sure if issues is the right place for this, if not I'm sorry, but I haven't found anything on this.

I am thinking that I want to use Keybase's private git to push config and data to from a directory on a VPS. I would have a cron job that does the git commit / push. My concern is that I don't want to put other files on Keybase at risk of this VPS being compromised.

That is, I would have the Keybase client on a server somewhere that commit/pushes a directory, but I don't want the server to have any access to anything other than that git repo.

Thanks!

**Comment by strib** [comment]
You can make a bot Keybase user, and log the bot into the server. Then make a team with yourself and that bot user, and use a team git repo for this data.  That way the bot doesn't have access to any of your personal private Keybase files. Would that work?

**Comment by TomFaulkner** [comment]
@strib I hadn't thought about that, but that sounds ideal. Thank you!
