### ISSUE TITLE
Need Private Folders Reset

### ISSUE THREAD

**Issue by ravenium** [keybase/client#10470]
Sorry to bug, I wish there was a more optimal way to accept that I'm a forgetful klutz and blow away my private folders.  But alas, they sit in the keybase fs tree, mocking me, so I need to file a request with you.  When I switched laptops and cubes, I managed to lose all my devices that had access to the folder.  I've put the paper key in a far better spot so this shouldn't happen again!

BEGIN KEYBASE SALTPACK SIGNED MESSAGE. kXR7VktZdyH7rvq v5weRa0zkQiYekZ PUOziwPfa6qj07e XTP1NtiHby0k4yG 7WsyFaCNBe90FaE r99TASBShQsesix 6TjhlkxCsMyXme1 OYxsxmJkjHtW59x tgDbi3jL7lVFJlk KDn8Mqjzw2itzob H84rwz4MIcoiQQH xshN6jPDJQaaDaS E7IV5i3oY8cMINh hsH5cHN8r2jwij4 ynhIw7f5LThCulN 7tpmOVAMX9a27TL ZhoeENwun52YkfS Nm4R861g3iihNxM 7GFx3wA4D111Zbi K0ZO5fCug23SY8t kR861g3iihNxM7G Fx3wA4D1175bwqq 3xd2ULEbsKpSlcN 6KXf8UvHbJwrBSE SYEGdDynMcxm7k4 Gq9T7BtM5mCp17Q rRBhoVFmoCewRfJ unDjmN7m. END KEYBASE SALTPACK SIGNED MESSAGE.

**Comment by strib** [comment]
I reset the folders.  Please check it out and close this if everything seems ok.  (Might require a Keybase restart.)

**Comment by ravenium** [comment]
Thanks - verified.
