### ISSUE TITLE
Provide a way to mute notification for specific channels of a team

### ISSUE THREAD

**Issue by ChristianKleineidam** [keybase/client#10504]
Currently, all messages in channels towards which an user is subscribed produce a notification. On the other hand both Slack and Discourse allow the user to manage which channels are supposed to produce notifications. 

It would be great if the Keybase team chat would have similar ways to manage notifications on a per-channel basis.

**Comment by jasonslay** [comment]
This exists now. On the desktop app if you click the "i" logo and then choose "Settings" you should see notification settings for that channel.

**Comment by bitmage** [comment]
Does this only exist on the desktop? What about iOS/Android?

**Comment by Ambros94** [comment]
The same option is available on iOS
