### ISSUE TITLE
Forgot old keys: need kbfs reset

### ISSUE THREAD

**Issue by keepwatch** [keybase/client#10502]
Similar to #6408. I lost my oldest device and paper key but not my passphrase, and Keybase wants me to rekey my folders with my older keys. I'm not able to delete the old keys or rekey the folders (obviously). 

-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

Please reset /keybase/private/keepwatch as I can no longer rekey it.

Also, please reset or remove the folder I have shared with a twitter user who never logged into keybase (don't want to share the username in a public context).

-----BEGIN PGP SIGNATURE-----
Version: Keybase OpenPGP v2.0.76
Comment: https://keybase.io/crypto

wsBcBAABCgAGBQJafuTuAAoJEAAJG3BIX9i+1fEH/3uhF/1X7lzkSKmOSI0GMSTV
HY2kaPR5jT/bSDYPzEVkw4Dv+J0imJRb9a9cU3kIZQktayGqPXfWOI54Fh1aEypq
nmMrJAg5Ih1VAm4guHSXblcPPcuMxXv8/ZfFN7BtWkTMIfzdhngY7jjf92rgWeku
ucwNkUGBKe8NFfDXP9Ts2ln75xxdt2BqeGp1TO+qbHBRFUyaYsQC9sa2oJiv+YP9
D24FXgN6LV9rp8TMCrq/PRCAjzwD10QpUoq95Y+mxuddls4X9TxVAvCpBEvKWGOu
npaHyuChkc61dZb41CSc1HWID1n3oMqBwjht7QlfUN9HZU4tHPSKxbzhLtiTJoQ=
=adYE
-----END PGP SIGNATURE-----

**Comment by strib** [comment]
@keepwatch I can reset your folders, but I can't seem to verify this PGP message. Probably some kind of whitespace issue.  It would be easier with Keybase encryption. Can you please run this command on a currently-valid keybase device, and substitute the current date and time where indicated:

```
keybase sign -m "<DATE_AND_TIME>: Please reset folder /keybase/private/keepwatch and the folder I shared with a twitter user because all the devices that have access have been revoked."
```

and post the results here.

**Comment by keepwatch** [comment]
Aaaaand actually I found my old paper key. Crisis averted! Thanks for your help.

**Comment by strib** [comment]
Oh close one, I was just about to reset.  Nice!
