### ISSUE TITLE
How do I turn an existing folder into a Git repository?

### ISSUE THREAD

**Issue by ChristianKleineidam** [keybase/client#10516]
I created an existing folder "testfolder" that contains a single textfile.
I created `testing` as a private repository. I tried the following to create a git repository there that gets uploaded to Keybase:

```
C:\Users\chris\Documents\Programming\testfolder>git push keybase://private/christiankl/testing
fatal: The current branch master has no upstream branch.
To push the current branch and set the remote as upstream, use

    git push --set-upstream keybase://private/christiankl/testing master

C:\Users\chris\Documents\Programming\testfolder>git push --set-upstream keybase://private/christiankl/testing master
Initializing Keybase... done.
error: src refspec master does not match any.
error: failed to push some refs to 'keybase://private/christiankl/testing'
```

I created a question at https://superuser.com/questions/1293619/how-do-i-transform-an-existing-folder-on-my-computer-into-a-keybase-git-director
Given that the Keybase download page explicitely asks for bug reports I also posted this issue.

**Comment by strib** [comment]
@ChristianKleineidam: The following steps work fine for me.  Did you do the same thing and it didn't work?  if so, please do a `keybsae log send` and we can try to figure it out:

```sh
$ cd /tmp/
$ mkdir test10516
$ cd test10516/
$ keybase git create test10516
Repo created! You can clone it with:
  git clone keybase://private/strib/test10516
$ git init
Initialized empty Git repository in /tmp/test10516/.git/
$ echo test > testfile.txt
$ git add testfile.txt
$ git commit -a -m test
[master (root-commit) 2b5108d] test
 1 file changed, 1 insertion(+)
 create mode 100644 testfile.txt
$ git push --set-upstream keybase://private/strib/test10516 master
Initializing Keybase... done.
Syncing with Keybase... done.
Syncing encrypted data to Keybase: (100.00%) 9.47/9.47 KB... done.
Counting objects: 208 bytes... done.
Preparing and encrypting objects: (100.00%) 208/208 bytes... done.
Counting refs: 41 bytes... done.
Preparing and encrypting refs: (100.00%) 41/41 bytes... done.
To keybase://private/strib/test10516
 * [new branch]      master -> master
Branch master set up to track remote branch master from keybase://private/strib/test10516.
```

**Comment by dabura667** [comment]
Just like github or bitbucket, you need to create the repository on the service first.

In Keybase you can use

keybase git create xxxx

Then

git remote add origin keybase://private/user/xxxx

git push --set-upstream origin master

**Comment by ChristianKleineidam** [comment]
@strib 
I did follow your commands but when I create a test repo and add files on the other side and push them and then try to pull them again, I get:
```
git.exe pull -v --progress "keybase://private/christiankl/testing"

Initializing Keybase... done.
Syncing with Keybase... done. [175.9644ms]
git-remote-keybase error: (1) malformed refspec, separators are wrong
git-remote-keybase error: (1) malformed refspec, separators are wrong


git did not exit cleanly (exit code 1) (5281 ms @ 2018-02-17 15:16:01)

```

**Comment by strib** [comment]
@ChristianKleineidam please do a `keybase log send` and let me know the resulting log ID here, so I can see what refs you have in your repo that are giving you trouble.

**Comment by ChristianKleineidam** [comment]
When going through that process, I think it would be great to see a summary of what will be send beforehand.

When giving the command I first got:
- INFO ignoring UI logs: context deadline exceeded
- ERROR error opening log "C:\\Users\\chris\\AppData\\Local\\Keybase\\Keybase.app.log": open C:\Users\chris\AppData\Local\Keybase\Keybase.app.log: Access is denied.

Afterwards it did give me an ID:
eab84712ee63d7f670959f1c

**Comment by strib** [comment]
Oh, the git command you ran is interpreting "keybase://private/christiankl/testing" as the remote ref name.  You can set a remote ref this way:

```sh
$ git remote add origin keybase://private/christiankl/testing
```

Then you can do, for example:

```
$ git pull -v --progress origin 
```

(These are general git tips, they are not specific to Keybase git repos.)

**Comment by ChristianKleineidam** [comment]
Thanks.
