### ISSUE TITLE
No way to tell if keybase is on the latest version

### ISSUE THREAD

**Issue by ftrotter** [keybase/client#10515]
Keybase GUI Version: 1.0.40-20180205183337+269845275

I can see that I am on the version above. Is that the latest? I have no idea. 
When I download the .dmg file to OSX, and try to copy it over, it indicates that my copy is later than the one that is downloaded... so I am assuming that it is updated. 

It would be lovely if it would say something like "you are on the latest stable version" on the "about keybase" page, so that I did not have to wonder. 

It would also be good if there was a version on the download page, so that I could generally see that the version offered through the web (and presumably protected by DNSSEC, etc etc) is the version that my software at least claims to be running... 

-FT

**Comment by timfallmk** [comment]
@ftrotter I agree that this is non-obvious. However, you can use the built-in update mechanism to check for the availability of a new release (and get the new one if there is one).

`keybase update check` should get you what you want. The JSON it spits out will also tell you what the current and latest versions are.

**Comment by ftrotter** [comment]
Thanks for the tip. I hope that feature gets moved "in GUI" soon.

**Comment by ftrotter** [comment]
Closing as out of date... I hope its been fixed.
