### ISSUE TITLE
request: make command line proof for web save the text file

### ISSUE THREAD

**Issue by bjmgeek** [keybase/client#10534]
I tried to prove a website, with `keybase prove web`
I copied/pasted the generated text, saved it in a text file, and put it in the web server's /.well-known directory.  I can view the file from other internet hosts, but the keybase command line client is not recognizing the proof.  I wonder if I mis-copied it.  It would be nice if the command line tool could create the `keybase.txt` file, and I could just move the generated file, instead of relying on the clipboard.

**Comment by bjmgeek** [comment]
update: The client recognized the proof (I had a misconfigured webserver), but I still think this could be a useful feature.

**Comment by timfallmk** [comment]
@bjmgeek Are you asking for behavior similar to piping to a file (ala `keybase prove web > some-proof.txt`) or something more complex?

**Comment by bjmgeek** [comment]
If the client already provides the proof on standard output, then that would be fine.

**Comment by timfallmk** [comment]
@bjmgeek It seems to do this by default. Additionally, there's a `-o` flag to specify an output file.

**Comment by bjmgeek** [comment]
In that case, I'll mark this issue as closed.
