### ISSUE TITLE
Can't create a PGP Key for Emails in the GUI

### ISSUE THREAD

**Issue by DiesDasJenes** [keybase/client#10538]
I want to create for my three Emailaccounts a PGP Key and store it in keybase.

Keybase has a function for this in the GUI. When i press the Button "Let the math begin" it seems that nothing happens. I am using ubuntu 16.04 but i also tried it on Win7 .

May log ID is: eae29f39353333595472b11c

Best regards

**Comment by artfulhacker** [comment]
I manually ran `keybase pgp gen` in the console and it worked. see #10448

**Comment by DiesDasJenes** [comment]
Due the remarks to thread #10448 and #10550 i close this issue.
