### ISSUE TITLE
error code 1009 from  hardware fix

### ISSUE THREAD

**Issue by phillipstrauss** [keybase/client#10558]
The mother board on my laptop failed and needed to replacement.  After confirming the fix keybase client cannot encrypt attachments to chat but chat still works otherwise.
Tried removing the laptop as a device then re-adding it.  Now getting error during the re-addition of the laptop.
"There was an error provisioning
unknown error: ERROR CODE 1009 - bad signature: your computers clock is wrong: signature is dated 43217 seconds in the past in method keybase.1.login.login

**Comment by maxtaco** [comment]
Is your clock or timezone wrong? Seems like it is

**Comment by phillipstrauss** [comment]
well the cock is right but I just noticed its off by exactly 1 day.  :(
