### ISSUE TITLE
Switch to a v3 onion address

### ISSUE THREAD

**Issue by bn4t** [keybase/client#10555]
It would be great if Keybase would be reachable using a new v3 onion addresses.

See: https://blog.torproject.org/tors-fall-harvest-next-generation-onion-services

**Comment by Mikaela** [comment]
This has been done sometime, as  the bottom of Keybase.io says:

>  Keybase, 2019 | Available within Tor at http://keybase5wmilwokqirssclfnsqrjdsi7jdir5wy7y7iu3tanwmtp6oid.onion

(ref https://github.com/keybase/keybase-issues/issues/482)

**Comment by bn4t** [comment]
@Mikaela Thanks for making me aware that this is now fixed:+1:
