### ISSUE TITLE
keybase pgp pull tries to pull keys even from a deleted user that was followed

### ISSUE THREAD

**Issue by elyezer** [keybase/client#10557]
It seems that the follow relationship is not being removed when a user decides to delete their account. Then that block us to pull the pgp keys with the following error:

```console
$ keybase pgp pull
▶ INFO Imported key for user1.
▶ INFO Imported key for user2.
▶ INFO Imported key for user3.
▶ INFO Imported key for user4.
▶ ERROR Failed to load user deleteduser: user "ee6a243826dd159693580d31986686ed" deleted
```

Since there is no way to stop following the deleted user I will always get that error message.

**Comment by zapu** [comment]
From my observation it prints this error but it just skips the problematic user. Does it fail the entire command for you? It should still pull keys for everyone that came before and comes after.

**Comment by elyezer** [comment]
It seems to not fail but it is annoying to see that every time and I can't really stop following the deleted account.

**Comment by zapu** [comment]
Can you paste the error you get when you try to unfollow them?

**Comment by elyezer** [comment]
Ok so I can unfollow using the command line but I wasn't able to do using the web UI. After calling `keybase unfollow deleteduser` it stopped showing that message.

Maybe an usability improvement would be to suggest unfollowing so that message would disappear.

Thank you for the commend because I didn't think to unfollow using the CLI since I tried via web UI and I can't even find the deleted user listed in there.

**Comment by zapu** [comment]
Got it, thanks! We are going to fix `pgp pull` nevertheless.

**Comment by elyezer** [comment]
Cool. I am glad you found this issue useful

**Comment by elyezer** [comment]
Thank you!
