### ISSUE TITLE
Android notifications are unreliable

### ISSUE THREAD

**Issue by Avamander** [keybase/client#10560]
So I managed to convince a few of my friends to use Keybase, but due to constantly not getting notifications they're considering it too unreliable. Are there any fixes other than enabling the email notifications (that come with a large delay) are any planned in the future?

**Comment by fastjack77** [comment]
Same problem here on version 3 Android. All notification settings are on but no notifications..

**Comment by einarmagnus** [comment]
I am also experiencing this problem on version 4.1.0 on OxygenOS 5.0.8 (android 8.0.0)

**Comment by ivan-avalos** [comment]
Yeah, has this problem been solved? It seems like my dad's not getting notifications, even though notification settings are on.

**Comment by Avamander** [comment]
If it's a Xiaomi or a Huawei device then you might want to try disabling
power "optimizations" for the app. It worked for me.

>

**Comment by ivan-avalos** [comment]
Oh, thanks! My dad's phone is a Huawei, I think that's the problem.

**Comment by ivan-avalos** [comment]
But also, now that he's receiving my notifications, there's not any sound at all, with or without the "use system notification sound" option enabled. Why are notifications so problematic?
