### ISSUE TITLE
Can't open my own private folder: Permission denied

### ISSUE THREAD

**Issue by korishev** [keybase/client#10566]
I believe I have the same issue as others with losing access to private home dir after revoking keys...

42d529170020fb9df6718f1c   -- keybase log send ID

BEGIN KEYBASE SALTPACK SIGNED MESSAGE. kXR7VktZdyH7rvq v5weRa0zk8YKzwM b7ytHQ9c9hNxVf1 LiPxRBGg6qUE460 DjhrTGGAp3kMemZ 5NOiXpZsMwtt3lb y1tDHhZWOVycq5D wDjUxTL9PscMuMy jG5qYbxwE6DAyFY TR35qK8t00TLSbT nxnfL7zc7RhYZRe 4O7UPMaW3db3l5V UUcOnmD7RRY3RdQ Tb0olZZ3lMyP5I2 SaloxO3a65TzeTr AG5FqNBeQTMFAiy 6yL11WqRbguY2Vf HPvOkqTJwSl8E8m Tje5QT7PdJT0FlC EVti1PwqUTRaZtE TS4tswWu0K2m4Pg RgRIFm7FM0l1Qcs vleS4Oae5LengE0 BV8kflGqAHqY. END KEYBASE SALTPACK SIGNED MESSAGE.

**Comment by strib** [comment]
I reset the folder.  Please check it out and close this if everything seems ok.  (Might require a Keybase restart.)

**Comment by korishev** [comment]
That did it.  Thank you very much!

Morgan
