### ISSUE TITLE
Lost old device, can't delete key or device

### ISSUE THREAD

**Issue by mazamats** [keybase/client#10583]
I have a chat which I've lost keys to.

Every time I open up the keybase app, I get this:

![screen shot 2018-02-15 at 17 02 07](https://user-images.githubusercontent.com/25627421/36287430-01a7fae8-1272-11e8-8e3f-188eb58da958.png)

After reading the docs, I came across `keybase chat delete-history`

However, I get this when I try to run it.

```
$ keybase chat delete-history
▶ ERROR error unboxing chat message: This device does not yet have read access to directory /keybase/private/azamatms,contex, log into Keybase from one of your other devices to grant access: could not find params for uid=7014f896e841a9cc4ed24320f3dc0319 device key=0121f3aa49b6afa5cb6f6734178e2985667395d843020391743d00f313677ded9c480a
github.com/keybase/kbfs/libkbfs.(*KeyManagerStandard).getTLFCryptKeyParams
	/Users/build/go/src/github.com/keybase/kbfs/libkbfs/key_manager.go:311
github.com/keybase/kbfs/libkbfs.(*KeyManagerStandard).getTLFCryptKey
	/Users/build/go/src/github.com/keybase/kbfs/libkbfs/key_manager.go:157
github.com/keybase/kbfs/libkbfs.(*KeyManagerStandard).getTLFCryptKeyUsingCurrentDevice
	/Users/build/go/src/github.com/keybase/kbfs/libkbfs/key_manager.go:81
github.com/keybase/kbfs/libkbfs.(*KeyManagerStandard).GetTLFCryptKeyOfAllGenerations
	/Users/build/go/src/github.com/keybase/kbfs/libkbfs/key_manager.go:65
github.com/keybase/kbfs/libkbfs.(*KBFSOpsStandard).GetTLFCryptKeys
	/Users/build/go/src/github.com/keybase/kbfs/libkbfs/kbfs_ops.go:496
github.com/keybase/kbfs/libkbfs.(*KeybaseServiceBase).GetTLFCryptKeys
	/Users/build/go/src/github.com/keybase/kbfs/libkbfs/keybase_service_base.go:1083
github.com/keybase/kbfs/vendor/github.com/keybase/client/go/protocol/keybase1.TlfKeysProtocol.func2
	/Users/build/go/src/github.com/keybase/kbfs/vendor/github.com/keybase/client/go/protocol/keybase1/tlf_keys.go:200
github.com/keybase/kbfs/vendor/github.com/keybase/go-framed-msgpack-rpc/rpc.(*callRequest).Serve
	/Users/build/go/src/github.com/keybase/kbfs/vendor/github.com/keybase/go-framed-msgpack-rpc/rpc/request.go:76
github.com/keybase/kbfs/vendor/github.com/keybase/go-framed-msgpack-rpc/rpc.(*receiveHandler).handleReceiveDispatch.func1
	/Users/build/go/src/github.com/keybase/kbfs/vendor/github.com/keybase/go-framed-msgpack-rpc/rpc/receiver.go:121
runtime.goexit
	/usr/local/Cellar/go/1.9/libexec/src/runtime/asm_amd64.s:2337
```

---

Is there any fix for this? I just want to get rid of that chat. I'm hoping I won't need to do a full reset of my account.

**Comment by strib** [comment]
First, you should immediately revoke the device `macbook` from your account if you have lost control of it.

Second, it looks like this is a chat with another Keybase user.  Can you ask that person to sign into Keybase and see if they can rekey it for you?

If that person has also lost all the keys that can rekey the chat, then we can reset it for you.  
If you want us to reset the folder, please run this command on a currently-valid keybase device, and substitute the current date and time where indicated:

```
keybase sign -m "<DATE_AND_TIME>: Please reset folder /keybase/private/azamatms,contex because all the devices that have access have been revoked."
```

and post the results here.

**Comment by mazamats** [comment]
Hi @strib, thanks for the response.

I'm not able to remove the device from Keybase, it comes up with this error.

I'm assuming its because of the chat that needs to be rekeyed. Thankfully, the device isn't lost. I just didn't backup keybase on another device before I reformatted.

If I were to lose the only device I use keybase on, would this prevent me from removing that device later? Its very inconvenient to not have the ability to remove that device, you would need to wipe your account quickly to ensure nobody accessed keybase.

<img width="465" alt="screen shot 2018-02-17 at 16 42 52" src="https://user-images.githubusercontent.com/25627421/36346766-1a5612aa-1402-11e8-844b-0a17e50a3d77.png">


Can you reset the chat for me?

```
kbook:~ azamat$ keybase sign -m "Sat Feb 17 16:48:39 MST 201: Please reset folder /keybase/private/azamatms,contex because all the devices that have access have been revoked."
BEGIN KEYBASE SALTPACK SIGNED MESSAGE. kXR7VktZdyH7rvq v5weRa0zkK3ZHqQ BgpYl0N64bEeNrC EHo4R4nco7Ajk7u Os3o2HR6xb6mbcQ zzDLvGdUVK2Oh6M 0oHwImlOYYvuOZa 7QkX1oIFaNFXYvd 9FKEIn7XRnl9M5l 5HNelvRH7H3foUf qFBGejJKW1XjV22 BCiO6R4TiwANp1V FjnpAhIoLKjOuaP mPIj1g92lsLheNf V0V19JwpE12wfUW Edx03BpqcDRGKKR xv89j5Mn2QYzkwN HVqN6jN0RDxFNpN mwaikxcxqw47vFO yfZVCjM9XUgUbKq 1Rqlz8i7udKATFB 6NmU8r8WpNOwWZE yMflvZdMopsYyJG 6Mmc0dn2Ofps8NA RY0ES7xMrhQNIfm . END KEYBASE SALTPACK SIGNED MESSAGE.
```

**Comment by strib** [comment]
> If I were to lose the only device I use keybase on, would this prevent me from removing that device later? Its very inconvenient to not have the ability to remove that device, you would need to wipe your account quickly to ensure nobody accessed keybase.

cc: @cjb, @chrisnojima and @patrick for the black bar on device removal.  @mazamats that's definitely a bug, you should be able to remove that device.  We'll look into it.

> Can you reset the chat for me?

I can, but the message you signed has a small error.  The date looks like this:

```
Sat Feb 17 16:48:39 MST 201: Please reset...
```

The last digit in the year was dropped off somehow.  Can you please try it again so we have a complete date. Thanks!

**Comment by mazamats** [comment]
Thanks for the reset!

```
$ keybase sign -m "Tue Feb 20 14:08:31 MST 2018: Please reset folder /keybase/private/azamatms,contex because all the devices that have access have been revoked."
BEGIN KEYBASE SALTPACK SIGNED MESSAGE. kXR7VktZdyH7rvq v5weRa0zkK3ZHqQ BgpYl0N64bEeNrC EHo4R4nco7Ajk7u Os3o2HR6xbE46wG Z9QwXExjWptCFL1 NbzvW6ttAA1pzOU 4dJPc3pARWEZNil PM8YCRrw9m8Bg44 fPURXWNF4dedqhd kjzwyRqcgpXkylm rvGEnocrztZgy8P SCU83aMe8KBxLCc 5YDxlNdXwicaYBD mSyPLJwpE12we35 XdsUH4Xdq4BrM4E ezn2yoiyBYsWCRR 1L7NKP0Ss2D3ic4 AgfQZ8OUIo8XO6T HgOoSCFu36GydkC xN6qgmZwwmakjMN kdBSYPmIMjiTpKB 7HGOZtFS4YpA2r1 4TxRAxAf9FtUGWo GC4I6bhtSd2GEKa xK. END KEYBASE SALTPACK SIGNED MESSAGE.
```

**Comment by strib** [comment]
I reset the folder.  Please check it out and close this if everything seems ok.  (Might require a Keybase restart.)

**Comment by mazamats** [comment]
@strib Thanks, it seems to have worked.

You can close this issue, I'm guessing you won't be tracking the above bug on this one.
