### ISSUE TITLE
where do merkle block data specification?

### ISSUE THREAD

**Issue by nakajo2011** [keybase/client#10599]
I am learning keybase specification.
i get my leaf data:
```
my_leaf_data:
 [ 2,
  [ 12,
    '2adf24c6ce3ac152288b3ba4e69e950960864b4635b7117e804513bd54b2f1cd',
    '2513feaa7e689dd0af98fd179cb8b49c8e6670606f1219e70205ee145a75ea58' ],
  [],
  '01208858ecb04808f9794c497d4ca4fd7e691a3f826af9ff3225da81c66b6474ed130a' ]
```
leaf_data[1] is descripted in document. leaf_data[3] is eldest-kid perhaps. but i have no idea other leaf datas.
where do i see the others description?

**Comment by maxtaco** [comment]
leaf_data[0] is version of leaf.  It is 2 for everyone. leaf_data[2] is a
“semi private” chain. It is empty for users and exists for teams.

**Comment by maxtaco** [comment]
Correct about leaf[3].  We recently rolled out leaf[4] to better document
account resets too.

**Comment by nakajo2011** [comment]
thx @maxtaco
