### ISSUE TITLE
On ubuntu cannot open any folder

### ISSUE THREAD

**Issue by mitkokostakev** [keybase/client#10607]
Keybase GUI Version: 1.0.41-20180216170155+d426d58b11

**Comment by mitkokostakev** [comment]
lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.5 LTS
Release:	14.04
Codename:	trusty

**Comment by strib** [comment]
Please do `keybase log send` and report the resulting log ID here, and we'll take a look.  Thanks!

**Comment by wundrellama** [comment]
I believe I'm having the same problem on Arch Linux.
Keybase service version: 1.0.41-20180216170155+d426d58b11.  
Log ID: a9e0044704c6398acac0441c

I can't launch the GUI, keybase status shows KBFS not running, and by extension, I'm unable to access any of my KBFS directories.

**Comment by strib** [comment]
@wundrellama: You are not running the filesystem currently.  Please try `run_keybase` and see if that helps.

(There was an upgrade recently that required running `run_keybase` afterward.)

**Comment by wundrellama** [comment]
@strib I tried `run_keybase` and was presented with the following:
```
Shutting down keybase service...
Starting via systemd.
/usr/bin/run_keybase: line 121: 11183 Segmentation fault      keybase-mount-helper -user-mount "$mountdir"
```

**Comment by strib** [comment]
Ah sorry about that, you hit #10487, you must be on a newish kernel.  We are working on a fix.

**Comment by wundrellama** [comment]
Ah, no problem! I should have done some more searching myself. Let me know if there's anything I can do to help. Not a programmer, but I can follow directions and send logs.
