### ISSUE TITLE
Folders not found

### ISSUE THREAD

**Issue by kontrag** [keybase/client#10604]
Keybase GUI Version: 1.0.40-20180205105656+493a528

I click on "Open Folders" and nothing opens. In Windows Explorer I see the 'Keybase' disk but I get a "Location Not found" error.

![kb](https://user-images.githubusercontent.com/23030513/36356507-5d8fe86a-14f3-11e8-8de2-601b3690abad.png)

Any ideas why?

**Comment by taruti** [comment]
Can you do a `keybase log send`? Have you rebooted recently (after the last update)?

**Comment by kontrag** [comment]
Hi,
I restarted my laptop and it works fine. 
Thanks.
