### ISSUE TITLE
Error code 218 : GENERIC in method keybase.1.login.login

### ISSUE THREAD

**Issue by matbilodeau** [keybase/client#10671]
Keybase GUI Version: 1.0.41-20180221184830+80361c9

On windows 8, GUI client started giving error sending messages after approval to join open teams.  Android app couldn't send messages either.  Restarting devices got me some error codes with key family and paths, uninstalled and reinstalled android app, signed with another paper key and it worked.  Windows still gives trouble after repair followed by uninstall reboot reinstall reboot, 
There was an error provisionning
Key path not found
Error code 218: GENERIC in method keybase.1.login.login

went to command line 
C:\Users\Absinth>keybase device list
Name                            Type         ID
Created                Last Used
==========                      ==========   ==========
==========             ==========
DifferenceEngine                desktop      c9ec5d6f1b55c7bc98c8f086963b8e18
2017 Feb 12 09:35:01   2018 Feb 22 23:53:08
Paper Key (approve change...)   backup       0d5fa7e9c1cf6b6b38e194fef9ebb218
2017 Feb 12 09:35:02   2017 Feb 12 09:35:02
Paper Key (owner vast...)       backup       fdf09ab9c005d37b7dc6f80a7aaaa718
2018 Feb 22 23:24:06   2018 Feb 22 23:50:08
Pr0nMuncher                     desktop      b3dfba10654274b18667a5acb5a1f218
2017 Feb 25 17:32:40   2017 Aug 22 14:32:34
RaiseDead                       desktop      2988754c9282ea2d1af4e90036165b18
2017 Oct 24 21:13:08   2018 Feb 22 23:53:08
TechLeash                       mobile       6fc410bdf452a404b3f2ff33bcf6ba18
2017 Jun 26 21:06:34   2018 Feb 22 23:18:47
Vag-Abund                       desktop      c070e8e602c943b9777a2a3e12102918
2017 Sep 19 22:22:04   2018 Feb 23 00:01:54
techleash2                      mobile       a13968f9bd5a46a0b4835a99f2767d18
2018 Feb 22 23:50:08   2018 Feb 22 23:52:35

C:\Users\Absinth>keybase status
- ERROR EOF

C:\Users\Absinth>keybase id
- WARNING (CONN gregor 38af0dd6) Connection: error calling OnConnect handler: co
nnection auth error: msg: failed to check logged in status shouldRetry: false
- INFO CheckRegistryKeybaseDokan: Searching registry for {65A3A964-3DC3-0100-000
4-170726135020}
- ERROR Key path not found

C:\Users\Absinth>keybase login
- WARNING No ComputedKeyFamily found for matbilodeau
- ERROR Bad key family: not found for matbilodeau

C:\Users\Absinth>keybase logout

C:\Users\Absinth>keybase login
- ERROR Key path not found

C:\Users\Absinth>keybase login matbilodeau
- ERROR Key path not found

C:\Users\Absinth>keybase status
Username:      matbilodeau
Logged in:     no
Session:       no session
    is valid:  no
    keys:      locked

Key status:
    stream:    not cached
    secret:    not stored
    dev sig:   not cached
    dev enc:   not cached
    paper sig: not cached
    paper enc: not cached
    prompt:    show
    tsec:      not cached

KBFS:
    status:    running
    version:   1.0.2-20180221184254+07c0138
    log:       C:\Users\Absinth\AppData\Local\Keybase\keybase.kbfs.log
    mount:     N:

Service:
    status:    running
    version:   1.0.41-20180221184254+80361c9
    log:       C:\Users\Absinth\AppData\Local\Keybase\keybase.service.log

Updater:
    log:       C:\Users\Absinth\AppData\Local\Keybase\keybase.updater.log

Platform Information:
    OS:        windows
    OS vers:   Microsoft Windows [Version 6.3.9600]
    Runtime:   go1.9.1
    Arch:      386

Client:
    version:   1.0.41-20180221184254+80361c9

Desktop app:
    status:    running
    version:   1.0.41-20180221184830+80361c9
    log:       C:\Users\Absinth\AppData\Local\Keybase\Keybase.app.log

Config path:   C:\Users\Absinth\AppData\Local\Keybase\config.json
Default user:  matbilodeau
Other users:

command-line client:
    keybase status [pid: 4996, version: 1.0.41-20180221184254+80361c9]

desktop:
    C:\Users\Absinth\AppData\Local\Keybase\Gui\Keybase.exe --type=renderer --no-
sandbox --primordial-pipe-token=C8ABB565351FB0ED781835E94B93F586 --lang=en-US --
app-user-model-id=electron.app.Keybase --app-path=C:\Users\Absinth\AppData\Local
\Keybase\Gui\resources\app --node-integration=true --webview-tag=true --no-sandb
ox --enable-pinch --device-scale-factor=1 --num-raster-threads=1 --content-image
-texture-target=0,0,3553;0,1,3553;0,2,3553;0,3,3553;0,4,3553;0,5,3553;0,6,3553;0
,7,3553;0,8,3553;0,9,3553;0,10,3553;0,11,3553;0,12,3553;0,13,3553;0,14,3553;0,15
,3553;1,0,3553;1,1,3553;1,2,3553;1,3,3553;1,4,3553;1,5,3553;1,6,3553;1,7,3553;1,
8,3553;1,9,3553;1,10,3553;1,11,3553;1,12,3553;1,13,3553;1,14,3553;1,15,3553;2,0,
3553;2,1,3553;2,2,3553;2,3,3553;2,4,3553;2,5,3553;2,6,3553;2,7,3553;2,8,3553;2,9
,3553;2,10,3553;2,11,3553;2,12,3553;2,13,3553;2,14,3553;2,15,3553;3,0,3553;3,1,3
553;3,2,3553;3,3,3553;3,4,3553;3,5,3553;3,6,3553;3,7,3553;3,8,3553;3,9,3553;3,10
,3553;3,11,3553;3,12,3553;3,13,3553;3,14,3553;3,15,3553;4,0,3553;4,1,3553;4,2,35
53;4,3,3553;4,4,3553;4,5,3553;4,6,3553;4,7,3553;4,8,3553;4,9,3553;4,10,3553;4,11
,3553;4,12,3553;4,13,3553;4,14,3553;4,15,3553 --service-request-channel-token=C8
ABB565351FB0ED781835E94B93F586 --renderer-client-id=6 --mojo-platform-channel-ha
ndle=1712 /prefetch:1 [pid: 4056, version: 1.0.41-20180221184830+80361c9, descri
ption: Main Renderer]

KBFS:
    C:\Users\Absinth\AppData\Local\Keybase\kbfsdokan.exe -debug -log-to-file -mo
unt-from-service [pid: 4692, version: 1.0.2-20180221184254+07c0138]

C:\Users\Absinth>keybase log send
This command will send recent keybase log entries to keybase.io
for debugging purposes only.

These logs don't include your private keys or encrypted data,
but they will include filenames and other metadata keybase normally
can't read, for debugging purposes.

Continue sending logs to keybase.io? (type 'YES' to confirm): YES
Enter feedback (or ENTER to send):

------------
Success! Your log ID is:

  97dfc67f8e2be92e7036101c

Here's a URL to submit new bug reports containing this ID:

  https://github.com/keybase/client/issues/new?body=[write%20something%20useful%
20and%20descriptive%20here]%0A%0Amy%20log%20id:%2097dfc67f8e2be92e7036101c

Thanks!
------------

**Comment by maxtaco** [comment]
Cc @zanderz

I think you have a broken windows build

**Comment by bs1978ta** [comment]
Yes I woke up to the same error code running win 7. Worked perfect last night - today errors.

**Comment by matbilodeau** [comment]
Android chat now gives me this 

ERROR CODE 218 - no TLF name specified in method chat.1.local.postTextNonblock

construct@index.android.bundle:175:435
e@index.android.bundle:1053:622
e@index.android.bundle:1053:463
l@index.android.bundle:1053:2816
convertToError@index.android.bundle:1053:198
index.android.bundle:493:5012
index.android.bundle:1092:641
_call@index.android.bundle:1063:1844
index.android.bundle:1063:1988
c@index.android.bundle:1063:816
_fulfill@index.android.bundle:1063:1954
l@index.android.bundle:1063:345
index.android.bundle:1057:3607
index.android.bundle:1057:619
index.android.bundle:1070:3793
index.android.bundle:1070:4185
_call@index.android.bundle:1063:1844
index.android.bundle:1063:1988
c@index.android.bundle:1063:816
_fulfill@index.android.bundle:1063:1954
l@index.android.bundle:1063:345
_call_cb@index.android.bundle:1070:2525
_dispatch_handle_response@index.android.bundle:1070:2357
_dispatch@index.android.bundle:1070:2161
_get_msg@index.android.bundle:1071:1767
packetize_data@index.android.bundle:1071:2071
index.android.bundle:1056:1454
value@index.android.bundle:213:1363
value@index.android.bundle:199:3559
index.android.bundle:199:1044
value@index.android.bundle:199:2986
value@index.android.bundle:199:1016
[native code]

**Comment by bs1978ta** [comment]
Yeah i can post to friends but not in teams. Something is all jacked up!

**Comment by matbilodeau** [comment]
i'm on linux right now and all is good , same for win 7, for now
the broken build might not only be windows

Linux
Client:  1.0.39-20180122170048+194147649
Service: 1.0.39-20180122170048+194147649

win7 
Client:  1.0.40-20180205105125+493a528
Service: 1.0.40-20180205105125+493a528
(i copy pasted this in a chat from win7, shows up on linux but android -> error unboxing chat message: Key path... can't see the rest, doesn't even show error when accessing chat) Clicking a profile also gives a key path not found.  

Keybase is supposed to ask you for your passphrase as a security measure if your phone doesn't have a lockscreen -> doesn't anymore and all the data that was pre-loaded until the errors shows up for anyone to see, fortunately it's me for now.
Notifications seem to be pushed fine in the android app, "someguy sent you a message", I see the "1" next to the chat tab but in chat, a blank conversation with "error unboxing chat message key path .."

**Comment by mmaxim** [comment]
We just launched a fixed for this on all platforms, please update and hopefully you are fixed. Sorry for the trouble.

**Comment by matbilodeau** [comment]
I'd rather not get fixed.

**Comment by matbilodeau** [comment]
Ok it's fixed on my side but a friend of mine got Key path not found
Error code 218: GENERIC in method keybase.1.login.login after updating; his app worked before.  Looking into it with him.

**Comment by maxtaco** [comment]
He needs to update too

**Comment by matbilodeau** [comment]
Yeah actually he just needed to reboot after the update.  Thanks and I will mark this issue as closed.

**Comment by matbilodeau** [comment]
Update fixed the issues.

**Comment by maxtaco** [comment]
Thanks for your help in reporting and debugging this issue.

**Comment by marccarre** [comment]
Experiencing the same on macOS with a version I just downloaded from https://keybase.io/docs/the_app/install_macos
```console
$ gsha256sum Keybase.dmg 
6ab91e2400c621e3414f1e9f398e6c6e9f9ad258f8c780fb493ef6427f8294c4  Keybase.dmg
```
First time installing Keybase and I get:
> There was an error provisioning
> GPG error: exit status 2
> Error code 218: GENERIC in method keybase.1.login.login

**Comment by maxtaco** [comment]
@marccarre, please run `keybase log send` and we'll take a look

**Comment by marccarre** [comment]
Thanks @maxtaco, just did it, here is the log ID `e51ad904ea93e3266a164b1c`. Please let me know if I can do anything else to help with the diagnosis. Cheers ✨

**Comment by maxtaco** [comment]
@marccarre you have this error: 

```734 2018-07-21T08:07:09.056379+02:00 ▶ [DEBU keybase gpg_cli.go:336] 2d0 gpg: signing failed: Inappropriate ioctl for device```

likely because of a GPG_TTY misconfiguration or a pinentry misconfiguration.  It should work from the command line: `keybase log`

**Comment by marccarre** [comment]
@maxtaco, indeed `keybase login` did the job 👍 
Thanks for the help! ✨

**Comment by maxtaco** [comment]
glad it worked.  i'm going to close out this issue

**Comment by maxtaco** [comment]
(it was already closed)

**Comment by maxtaco** [comment]
@tf2manu994 seems to work for me to load your user, though your client cannot. try `keybase db nuke` and then try it again?

**Comment by tf2manu994** [comment]
@maxtaco, it doesn't work:

```ps
PS C:\Users\Hannah> keybase db nuke
- ERROR {pipe://\\.\pipe\kbservice\Users\Hannah\AppData\Local\Keybase\keybased.sock} Error in transport: msgpack decode error [pos 3]: file has already been closed
Really blast away your local database? (type 'YES' to confirm): YES
- WARNING Nuking database C:\Users\Hannah\AppData\Local\Keybase\keybase.leveldb
- WARNING Nuking chat database C:\Users\Hannah\AppData\Local\Keybase\keybase.chat.leveldb
PS C:\Users\Hannah> keybase login
- ERROR {pipe://\\.\pipe\kbservice\Users\Hannah\AppData\Local\Keybase\keybased.sock} Error in transport: msgpack decode error [pos 3]: file has already been closed
Your keybase username or email address: haboutnnah
- NOTICE Failed to parse public key at position 0
- NOTICE Failed to parse public key at position 3
- ERROR Bad key family: No key found for 0101263e2ebb04151a817611e50011483d8c9797248fc04a15369e8000bd8eb68bf80a
PS C:\Users\Hannah>
```ps

Log ID b190cadd28229912e0fbdc1c

**Comment by maxtaco** [comment]
`keybase db nuke` and then quit, and then restart

**Comment by tf2manu994** [comment]
Same thing with same error: 

![Error again](https://i.imgur.com/mGL6xTG.png)

```ps
PS C:\Users\Hannah\AppData\Local\Keybase> Get-ChildItem | Where-Object {$_.Name -match "keybased"}


    Directory: C:\Users\Hannah\AppData\Local\Keybase


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
-a----       15/09/2018  11:06 AM             66 keybased.info
-a----       15/09/2018  11:06 AM              5 keybased.pid
```

**Comment by maxtaco** [comment]
ok, we'll look into it next sprint...

**Comment by maxtaco** [comment]
@haboutnnah I can't repro this problem and you're the only one that seems to have it.  Why don't you try to reset your account, provision a new device, and then do a `keybase pgp select` after the fact to associate your PGP key with your new device. Thanks.

**Comment by santosadrian** [comment]
I get another error, I tried to send the logs but this happens:
https://i.imgur.com/kFISz3L.png

**Comment by ninabarzh** [comment]
ALAS, me too. I get a Error: ERROR CODE 218 - context deadline exceeded in method keybase.1.SimpleFS.simpleFSSetFolderSyncConfig at new RPCError (file:///opt/keybase/resources/app/desktop/dist/main.bundle.js:1:1064198) at convertToRPCError (file:///opt/keybase/resources/app/desktop/dist/main.bundle.js:1:1065085) at convertToError (file:///opt/keybase/resources/app/desktop/dist/main.bundle.js:1:1065144) at file:///opt/keybase/resources/app/desktop/dist/main.bundle.js:1:2541166 at file:///opt/keybase/resources/app/desktop/dist/vendors~main.bundle.js:2:204647 at Deferrals._call (file:///opt/keybase/resources/app/desktop/dist/vendors~main.bundle.js:2:11095) at file:///opt/keybase/resources/app/desktop/dist/vendors~main.bundle.js:2:11287 at trampoline (file:///opt/keybase/resources/app/desktop/dist/vendors~main.bundle.js:2:10823) at Deferrals._fulfill (file:///opt/keybase/resources/app/desktop/dist/vendors~main.bundle.js:2:11240) at ret (file:///opt/keybase/resources/app/desktop/dist/vendors~main.bundle.js:2:10236)

And apparently all of my devices are affected. Could not send logfiles. Got an error for that too. :(
