### ISSUE TITLE
Can't use Private kbfs on Mac

### ISSUE THREAD

**Issue by aaranmcguire** [keybase/client#10684]
**Issue:**
When trying to create a folder in /keybase/private/aaranmcguire it asks for credentials, and then gives the following error:

![](https://cl.ly/3A3O0r391d0W/Screen%20Shot%202018-02-24%20at%2018.45.01.png)

**What I've tried:**
- I've tried upgrading keybase, I'm now on version 1.0.44-20180223192708+9a9ccec79
- running the following:

```
➜  ~ keybase uninstall --components=helper,fuse,mountdir,kbfs
▶ INFO Removing /Users/mcguirea/Library/LaunchAgents/keybase.kbfs.plist
▶ INFO Waiting for keybase.kbfs to exit...
▶ INFO Stopped keybase.kbfs
▶ INFO Trying to unmount: /keybase
▶ INFO Removing KBFuse
▶ INFO Removing privileged helper tool
➜  ~ keybase install --components=helper,fuse,mountdir,kbfs
▶ INFO Installing Helper
▶ INFO Installing KBFuse
▶ INFO Creating mount directory
▶ INFO log directory "/Users/mcguirea/Library/Logs" is writable by current user
▶ INFO log path "/Users/mcguirea/Library/Logs/keybase.start.log" exists and is writable by current user
▶ INFO paths in plist look ok and have valid permissions
▶ INFO Saving /Users/mcguirea/Library/LaunchAgents/keybase.kbfs.plist
▶ INFO Starting keybase.kbfs
▶ INFO Waiting for keybase.kbfs to be loaded...
```

- revoking the device and re-adding it.
- try adding files via CLI.

All still fail. Is this intended?

my log id: 90da5fd9afcf9d4f184e611c

**Comment by strib** [comment]
Hi @aaranmcguire, it looks like your private folder is keyed only for devices that don't exist anymore.  Is it possible you haven't used it since before you set your account a couple years ago?

I'm not back in the office until Monday, and then I'll have time to check more carefully what's going on.  If the above theory is correct, we'll need to reset your folder.  
If you want us to reset your folder, please run this command on a currently-valid keybase device, and substitute the current date and time where indicated:

```
keybase sign -m "<DATE_AND_TIME>: Please reset folder /keybase/private/aaranmcguire because all the devices that have access have been revoked."
```

and post the results here.

**Comment by aaranmcguire** [comment]
Awesome! Heres the result:

```
keybase sign -m "Sat 24 Feb 2018 22:12:48 GMT: Please reset folder /keybase/private/aaranmcguire because all the devices that have access have been revoked."

BEGIN KEYBASE SALTPACK SIGNED MESSAGE. kXR7VktZdyH7rvq v5weRa0zk9T2KUy exsTIhKY583EKBc w2Q0TqqKC1AHsIu c3Zz2OVRCOOoR90 lDqINeeraKKX03C lnw8zBMg7TP7AjB 4oGm9iV27QKrQlY cikeT0ga3eenV7L P7jwixoc6a0v7pl IhlMHNrtn4cyHEF Qgpk8mpDleohxR0 L1JkvEUShZcSyJ1 99HN6ZgYqYgNgHo nQmscCNjRkX6eoP Pr4pHcvFagWVAxM Vg1DewNUElwcSZ5 kufNKP0Ss2D3ic4 AgfQZ8OHMfRVTqT JM4d19uCYr0Uvy4 pNyluCodiGQTtnz fMh0qS014jVuRxR JTTFkdqvWronJ71 612n4UDnXIpihsY RbnVaJ9IyAsUY. END KEYBASE SALTPACK SIGNED MESSAGE.
```

**Comment by strib** [comment]
I reset the folder.  Please check it out and close this if everything seems ok.  (Might require a Keybase restart.)

For the record, the folder was only keyed for device `C02LV1FTFH03`, which has been revoked.
