### ISSUE TITLE
keybase git settings - confusing USAGE

### ISSUE THREAD

**Issue by jamesstout** [keybase/client#10687]
```bash
$ keybase git settings james
Error parsing command line arguments: team name argument required

NAME:
   keybase git settings - View and change repo settings

USAGE:
   keybase git settings [command options] <repo name> [--team=<team name>]

OPTIONS:
   --team 		keybase team name
   --channel 		chat channel where git push notifications will be sent
   --disable-chat	disable chat notifications for git pushes
```

The error says [team name argument required](https://github.com/keybase/client/blob/af892092926bb234b36a1744e64c3bfa147e8ee5/go/client/cmd_git_settings.go#L60) but the usage seems to show it as an [optional arg](https://github.com/keybase/client/blob/af892092926bb234b36a1744e64c3bfa147e8ee5/go/client/cmd_git_settings.go#L26)? Am I using it incorrectly? Thanks

**Comment by joshblum** [comment]
@jamesstout thanks for reporting! Was a bug with the documentation on our end
