### ISSUE TITLE
can't import gpg key "unsupported cipher in private key: 4"

### ISSUE THREAD

**Issue by mizerlou** [keybase/client#10686]
attempting to import this particular key gives the following error:
`▶ ERROR ImportKey (secret: true) error: openpgp: unsupported feature: unsupported cipher in private key: 4
`

key details:
```
sec   1024D/DAA47511 1999-02-24
uid                  lantz moore <lmoore@debian.org>
uid                  lantz moore <lmoore@tump.com>
ssb   2048g/41B9788E 1999-02-24
```

```
$ keybase --version
keybase version 1.0.44-20180223192708+9a9ccec79
$ gpg --version
gpg (GnuPG/MacGPG2) 2.0.30
libgcrypt 1.7.0
```

**Comment by maxtaco** [comment]
Sorry, we're not going to implement that old blowfish algorithm....  Sorry we can't support this key.
