### ISSUE TITLE
A javascript error occurred in the main process

### ISSUE THREAD

**Issue by AlexMclellan** [keybase/client#10689]
I'm getting an error when keybase starts the GUI 
![image](https://user-images.githubusercontent.com/1209117/36677795-050efc5c-1b07-11e8-96b8-0643a303df82.png)

my log id: 5cefee24e395b6bcf8deac1c

So I tried uninstalling keybase, but after (i assume) automatic updates, Windows 10 add/remove no longer points to the correct location in "C:\Users\alexm\AppData\Local\Package Cache". I've tried setting something up and even modifying the windows registry to point to the correct installer without much success.

Running the installer from the website; I get...
![image](https://user-images.githubusercontent.com/1209117/36677912-4f3d02ec-1b07-11e8-82bd-636c30d6052c.png)
If I point it to the correct MSI within the Package Cache, I get 
![image](https://user-images.githubusercontent.com/1209117/36677943-655b79b4-1b07-11e8-9e0a-0225f6171e73.png)

**Comment by AlexMclellan** [comment]
Ah, the installer is trying to use the older installer, to remove the original installation and I'm pointing it to the latest. But it doesn't exist anymore. I'm not sure why the installer for the existing installation has disappeared, but it's not something I've consciously removed.

**Comment by maxtaco** [comment]
cc @zanderz

**Comment by AlexMclellan** [comment]
I've managed to fix the issue, by manually removing keybase from the list of installed apps in the Windows registry and reinstalling the program.

It might be an idea to have the installer fall back to doing this, if it can't identify the location original installer.

If you agree this is the right course of action, I don't mind fixing the installer, which I presume is located here; https://github.com/keybase/client/tree/master/packaging/windows/WIXInstallers.

**Comment by AlexMclellan** [comment]
Actually this looks like a duplicate of #10619 with the original issue being a duplicate of #10627.
