### ISSUE TITLE
chown keybase helper fails during upgrade to 1.0.44-20180223200436

### ISSUE THREAD

**Issue by ncFoCo** [keybase/client#10692]
# Issue Details
Keybase stopped working after the recent upgrade and the app would hang at startup. The issue was that my system could not change owner for some directories to the keybasehelper account. I was able to manually create the account after the upgrade and then switch ownership of /var/lib/keybase over to the keybasehelper account. After this, I was able to start up keybase.  

# System Information
``` Text
DISTRIB_ID=Ubuntu  
DISTRIB_RELEASE=16.04  
DISTRIB_CODENAME=xenial  
Linux 4.4.0-116-generic x86_64 x86_64 x86_64 GNU/Linux  
```

my log id: 4b866d4b779f6c6bac57a41c

**Comment by strib** [comment]
Hmm, thanks for the report.  We're currently changing the way this works so it probably won't be an issue in the future, but I'm confused as to why your system couldn't change the permissions.  Were you installing/upgrading Keybase with `apt` as `root`, as I would expect?  Or do you do package management in some other way?

**Comment by ncFoCo** [comment]
I did run `sudo apt upgrade` to upgrade keybase. It could be that I am on a managed system with sudo privileges though. My workstation is set up with network account and a local account. I mainly use the local account so I don't muck up my home folder with developer garbage. Both accounts have sudo. The sudoers file is controlled by our admins. I am able to append sudo privileges from a separate file.  

As a test, I uninstalled keybase, deleted user keybasehelper, and reinstalled the app. Here is the output of aptitude:

``` bash
xxxx@host:~$ sudo apt-get install keybase
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following NEW packages will be installed:
  keybase
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 83.7 MB of archives.
After this operation, 310 MB of additional disk space will be used.
Get:1 http://prerelease.keybase.io/deb stable/main amd64 keybase amd64 1.0.44-20180223200436.9a9ccec79 [83.7 MB]
Fetched 83.7 MB in 6s (13.7 MB/s)                                                                                                       
Selecting previously unselected package keybase.
(Reading database ... 388200 files and directories currently installed.)
Preparing to unpack .../keybase_1.0.44-20180223200436.9a9ccec79_amd64.deb ...
Unpacking keybase (1.0.44-20180223200436.9a9ccec79) ...
Processing triggers for gnome-menus (3.13.3-6ubuntu3.1) ...
Processing triggers for desktop-file-utils (0.22-1ubuntu5.1) ...
Processing triggers for bamfdaemon (0.5.3~bzr0+16.04.20160824-0ubuntu1) ...
Rebuilding /usr/share/applications/bamf-2.index...
Processing triggers for mime-support (3.59ubuntu1) ...
Processing triggers for hicolor-icon-theme (0.15-0ubuntu1) ...
Setting up keybase (1.0.44-20180223200436.9a9ccec79) ...
chown: invalid user: ‘keybasehelper:keybasehelper’

xxxx@host:~$ run_keybase 
Shutting down Keybase GUI...
Unmounting /home.local/xxxx/.local/share/keybase/fs...
Shutting down kbfsfuse...
Shutting down keybase service...
Starting via systemd.
Cannot get keybasehelper user: user: unknown user keybasehelper
```

**Comment by strib** [comment]
Thanks!  Hmm, I guess the `adduser` command in the post-install failed somehow (helpfully, we pipe its output and errput to `/dev/null`).  Maybe your user has sudo restrictions on creating new users somehow?  Anyway, this should change in the near future to no longer require a helper user at all.

In the meantime, let me know if you need any more help getting things to work.

**Comment by ncFoCo** [comment]
Thanks for the help and quick response. It is working after I figured out the issue.  

It seems weird that I am able to create the account post-install with useradd, but it doesn't work with aptitude?

**Comment by strib** [comment]
Yeah not sure.  Maybe it's the specific parameters we pass in?  https://github.com/keybase/client/blob/35f45a3dccd66e0169f88fabb3751bcd3c13f960/packaging/linux/post_install.sh#L23

**Comment by ncFoCo** [comment]
I think it is the --system flag.
``` bash
xxxx@host:~$ sudo useradd --system test
[sudo] password for xxxx: 
useradd: Invalid configuration: SYS_GID_MIN (101), GID_MIN (20), SYS_GID_MAX (19)
useradd: can't create group
~~~

**Comment by heronhaye** [comment]
Closing as this behavior does not exist anymore, please make a new issue if you update and still have trouble, thanks!
