### ISSUE TITLE
Not really a bud but unable to find answer.

### ISSUE THREAD

**Issue by bs1978ta** [keybase/client#10710]
I have keybase installed on 2 different OS win 7 and win 10 in a dual boot setup. How do you completely remove all traces of keybase on say win 10. Reason being the 2 os have different profiles. I want the same profile in both. Everytime I delete keybase on win 10 and reinstall it it comes back with the same profile. The profile i would think would have to be completely wiped off win 10 but uninstall does not do this. Any help would be appreciated. Thanks

**Comment by timfallmk** [comment]
@bs1978ta I don't necessarily know the directory layout for the windows client, but have you removed the associated configuration directories? A good list might be here: https://github.com/keybase/client/issues/10640#issuecomment-368168590
