### ISSUE TITLE
new private folder doesn't appear in Explorer or on command line until you first cd into it

### ISSUE THREAD

**Issue by tranoire** [keybase/client#10725]
On Windows 10.  Friend added a new private folder which was /private/'<my username>,<his username>'.  I can see it in the keybase Windows app.  Cannot see in Explorer or from command line, can only see /private/<my username>

From command line try to cd into new folder.  Takes several seconds but then works and I get in.  Can also see in Explorer now.

my log id: 0bacee90712f97826d11771c

**Comment by strib** [comment]
This is the intended behavior -- we don't want random people to be able to make things appear on your command line.

The folder should show up in the Keybase GUI for you to click through or ignore, as you want.
