### ISSUE TITLE
Cannot login to keybase: no secret key available

### ISSUE THREAD

**Issue by taohansen** [keybase/client#10722]
KBFS was mounting to ~/.local/share with only a single directory symlinked to /keybase. Uncertain what to do, I blew away the .local/share/keybase and .config/keybase directories. On attempted re-login I am greeted with "No secret key available"

**Comment by maxtaco** [comment]
You threw away your private key

**Comment by taohansen** [comment]
@maxtacoIs Is there a solution?

**Comment by maxtaco** [comment]
Use one of your other devices to revoke that device, and then reprovision it.
