### ISSUE TITLE
GitHub Desktop: "fatal: Unable to find remote helper for 'keybase' (128)"

### ISSUE THREAD

**Issue by kristovatlas** [keybase/client#10738]
The online documentation suggests that I can simply drag my local keybase repo into GitHub Desktop and use that as a GUI.

However, when trying to publish my first commit to master, I get the error message in GitHub Desktop:

> fatal: Unable to find remote helper for 'keybase' (128)

This is my first time attempting to use a remote helper on this machine, so it seems likely there's some other setup step I missed.

**Comment by strib** [comment]
Hi @kristovatlas: it's complaining that it can't find the binary `git-remote-keybase`.  So a few questions:

1. What OS are you using?
2. Do "keybase://"-style URLs work fine with `git` from the command line?
3. Does the PATH environment variable (under which you started Github Desktop) contain the directory of the `git-remote-keybase` binary?

**Comment by kristovatlas** [comment]
1. MacOS 10.11. (Also possibly relevant: git version 2.15.0, GitHub Desktop 223, Keybase Version 1.0.44-20180223192708+9a9ccec79)
2. Yes, that's how I was able to create a local clone of the keybase repo via `git clone keybase://team/...`
3. Yes: the binary is located at `/usr/local/bin/git-remote-keybase` and `/usr/local/bin` is part of my $PATH variable's value.

**Comment by strib** [comment]
Hmm, that all seems right. Looks like it could be related to a recent dugite issue, a library that I think is used in both atom and Github Desktop?

atom/github#1243
desktop/dugite#113

**Comment by kristovatlas** [comment]
Thanks for looking those up. I reported the error to GitHub support. Guess I'll have to stick with the command line for now. I encountered no problems with pushing via command line.

**Comment by kristovatlas** [comment]
The fix was to update to a new major version of GitHub Desktop (1.1.0) -- my old version was no longer supported.

**Comment by kristovatlas** [comment]
Thanks for your help, @strib.

**Comment by strib** [comment]
Great, glad you got it working!
