### ISSUE TITLE
Windows 7 / Keybase console ?

### ISSUE THREAD

**Issue by ThierryIT** [keybase/client#10740]
Hi,
I have done many update of Keybase during the last two-three months but I am a bit lost, where the Keybase console ??
What I was using few months ago ... whre to type  `keybase pgp list` as exemple ?

Thx

**Comment by zanderz** [comment]
There used to be a separate "Keybase Shell" icon which was just a CMD window with Keybase added to the path, but instead we now add keybase's location to the global path by default. So just open CMD and Keybase commands should work.

**Comment by ThierryIT** [comment]
yes working thx
