### ISSUE TITLE
Login Failure:Error code 236: MERKLE_RACE

### ISSUE THREAD

**Issue by daviddob** [keybase/client#10753]
can't find a race-free state for a904f29fb9ff569b3008cd966ac68419
Error code 236: MERKLE_RACE in method keybase.1.login.login

Cannot log in on any devices. What are the steps to troubleshoot/resolve this?

**Comment by Shwam** [comment]
I just created an account and am getting the same error, with that same hash. I can log in via web, but no devices.

**Comment by ryukinix** [comment]
Same here.

**Comment by maxtaco** [comment]
Sorry folks, we had a small outage, it should work again now. Let me know if not.

**Comment by ryukinix** [comment]
Yes, now is working!

**Comment by maxtaco** [comment]
ok, thanks, sorry about that

**Comment by daviddob** [comment]
Thanks for the quick resolution.

**Comment by dkvasnicka** [comment]
Got this now when adding a device to a new Keybase account. When I try to log in again the app is acting as if the device I am on and I just created was some other device, so now my option only seems to be to reset the whole account, which I need to wait 5 days for.

Any other options for me?

**Comment by SrivastavaAnubhav** [comment]
I had the same issue as @dkvasnicka today. In case it matters, I used the default name "Mac Device".

**Comment by yoza111** [comment]
@maxtaco im having the same problem but with my whole team. nobody can post up in any channel in my team message reads, cant find race-free state for 5004b083e94e088e9f88bdb9ede5a724 (error code 236) any help apricated
