### ISSUE TITLE
Put the crypto_squirrel.txt in KBFS

### ISSUE THREAD

**Issue by thinrope** [keybase/client#10773]
I am not 100% sure what is the idea behind [crypto_squirrel](https://github.com/keybase/client/blob/master/packaging/linux/crypto_squirrel.txt), but instead of installing it on the user disk, it will be way better to put it in KBFS itself in some public space, so it can serve as a proof system is working.

Then [run_keybase](https://github.com/keybase/client/blob/master/packaging/linux/run_keybase#L197) will need to be fixed like:
````patch
diff --git a/packaging/linux/run_keybase b/packaging/linux/run_keybase
index 90c657e36..22cd363c4 100755
--- a/packaging/linux/run_keybase
+++ b/packaging/linux/run_keybase
@@ -194,7 +194,10 @@ main() {
   echo 'Success!'
   # Magical squirrel produced by https://github.com/erkin/ponysay
   if [ "${KEYBASE_NO_SQUIRREL:-}" != "1" ]; then
-    cat /opt/keybase/crypto_squirrel.txt
+    DELAY=5
+    echo "Waiting ${DELAY} seconds (to have everything warm and fuzzy)..."
+    sleep ${DELAY}
+    cat ~/keybase/public/kalin/crypto_squirrel.txt
   fi
 }

````
Of course, feel free to choose better dir than mine (=kalin) :-)
And add better code (check if mounted?) instead of fixed '${DELAY}' :-))

**Comment by heronhaye** [comment]
Sorry, we can't do this because some people may not want KBFS. Cool idea though!

**Comment by thinrope** [comment]
!?! Sorry, it seems I missed something... Without KBFS, what else is there? Just chat?
 Anyway, the idea is to use it as a proof that installation went fine and is working.

**Comment by heronhaye** [comment]
You can still prove and validate proofs from the commandline, and send chat messages without KBFS. Thanks for the suggestion.

**Comment by heronhaye** [comment]
You can still prove and validate proofs from the commandline, and send chat messages without KBFS. Thanks for the suggestion.
