### ISSUE TITLE
[windows] keybase fs drive (K:\) no longer accessible, works on other devices

### ISSUE THREAD

**Issue by adnissen** [keybase/client#10781]
Hey folks, at some point kbfs on windows broke for me, as I can't access K:\ anymore. I reinstalled both dokan and keybase to no avail, as well as tried to get the status of my private folder:
```
C:\Users\andrew>keybase fs ls /keybase/private/adnissen
- ERROR Access is denied.
```

The device I'm on is Desktop 1 (https://keybase.io/adnissen/sigchain#2eb37d84ba3f4b6ffac1f3d040eaf5220ac94a15db720e4a3f200632b28588580f), and like I said all my other devices can access the fs fine.

One other thing that might be useful is that when I did `keybase log send` I got a couple more access denied errors:

```
- INFO ignoring error getting keybase status: Access is denied.
- INFO ignoring UI logs: Access is denied.
```

Maybe I should try rekeying the device? I can chat and everything from it fine, so it's not like the keys got wiped from the machine or something.

Any help would be much appreciated, thanks!

my log id: 98bc7ee9fbf2863cb6521c1c

**Comment by strib** [comment]
> keybase fs ls /keybase/private/adnissen

Hmm, I don't see this command in the logs, I only see `keybase fs ps` and `keybase fs stat /keybase`.  That, along with the log send issues, makes me think that you are running Keybase in some way that you can't even execute the `keybase` command from the terminal.  (i.e., the "Access is denied" error is coming from Windows, not from Keybase.)

Did you install Keybase as the administrator by chance, and are running other operations as a regular user?

**Comment by adnissen** [comment]
@strib hmm, definitely didn't do that...now the keybase app won't open at all, getting an "oops can't connect to our services" error. This time doing `keybase fs ls /keybase/private/adnissen` returned `- ERROR Keybase services aren't running - KBFS client not found.` made a new log with `f4d8ca41b8de483a46898f1c`

**Comment by strib** [comment]
Cliche, but have you tried a full system reboot since your last install?

cc: @zanderz

**Comment by adnissen** [comment]
aaaaaaaand with another restart it all works fine, folders and all. thanks for the help @strib, hopefully this is unique to me but if not I hope the logs might help with the stability. going to close this, my advice to anyone reading is aggressive reinstalls and restarts until it works.
