### ISSUE TITLE
ERROR CODE 205 - uid <id> has never been a member of this team.

### ISSUE THREAD

**Issue by vilitux** [keybase/client#10788]
After user changed his PGP key, keybase errors in the chat with "<user> lost all his devices ....." and I need to let him back in the chat (trying to start new chat with him takes me back to the old chat). Trying to let him back in, however, results in:
`SC_NOT_FOUND: ERROR CODE 205 - uid <id> has never been a member of this team.`

How can I get this working again so we can start a new chat? :-) 

my log id: 30c7f6c39a5692ce77cd3c1c

**Comment by vilitux** [comment]
Also seems to be somewhat the same as issue #10575

**Comment by maxtaco** [comment]
@mmaxim is this issue fixed in master?

**Comment by mmaxim** [comment]
It was supposed to be, @zapu is this the case you fixed?

**Comment by mmaxim** [comment]
Ah yeah it just isn't in the latest Linux build, the one that goes out today should have the fix.

**Comment by zapu** [comment]
That's correct, it was only merged 6 days ago.

**Comment by vilitux** [comment]
Seems to work like a charm now. Thanks for the fix :+1:

**Comment by zapu** [comment]
Thanks for letting us know!
