### ISSUE TITLE
Capitalize the H in GitHub.

### ISSUE THREAD

**Issue by Haacked** [keybase/client#10808]
This is such a tiny minor issue I hesitate to even bother with it, but folks at GitHub tend to care about it. The option to "Prove your Github identity" has a lower-case H. The proper casing is `GitHub`.

![image](https://user-images.githubusercontent.com/19977/37118316-ba3ed9fa-2208-11e8-8584-bb29e27347d3.png)

**Comment by maxtaco** [comment]
Thanks for pointing this out. Should be fix, but LMK if not, I couldn't verify it without creating a sockpuppet or deleting my Git*H*ub proof.

**Comment by Haacked** [comment]
I can't verify it either, but I'll trust you did it right. :smile:
