### ISSUE TITLE
Unable to clone keybase git repo due to 'Directory is not empty and can't be removed'

### ISSUE THREAD

**Issue by jeham** [keybase/client#10837]
I'm trying to clone my new repo (testrepo). Getting the error message below:

```
c:\tmp\>git clone keybase://team/my-team/testrepo
Initializing Keybase... done.
Syncing with Keybase... done.
git-remote-keybase error: (1) Directory secret-git012070d309a02098a3a588bc347d15fc4afc5d388ba54b50716122322963dbc577ff0a-1520435297266928900 is not empty and can't be removed
git-remote-keybase error: (1) Directory secret-git012070d309a02098a3a588bc347d15fc4afc5d388ba54b50716122322963dbc577ff0a-1520435297266928900 is not empty and can't be removed

```
Note that "secret-git" was a test repository created and then later deleted by me (using one of my other devices). 

my log id: 969691970d2e232d4766a01c

**Comment by strib** [comment]
@jeham Do you know how long ago you made "secret-git"? There was a bug in the very first version of git, last October, that could leave around a directory entry and cause this bug.  If you think this repo could be that old, maybe just move it out of the way, something like this on Windows (substituting in your team name):

```
keybase fs mv /keybase/team/my-team/.kbfs_git/.kbfs_deleted_repos/secret-git012070d309a02098a3a588bc347d15fc4afc5d388ba54b50716122322963dbc577ff0a-1520435297266928900 /keybase/team/my-team/.kbfs_git/.kbfs_old_broken_secretgit
```

**Comment by jeham** [comment]
Can't get rid of the directory even though it looks empty:

```
d:\tmp>keybase fs ls /keybase/team/my-team/.kbfs_git/.kbfs_deleted_repos/secret-git012070d309a02098a3a588bc347d15fc4afc5d388ba54b50716122322963dbc577ff0a-1520435297266928900
.

d:\tmp>keybase fs rm /keybase/team/my-team/.kbfs_git/.kbfs_deleted_repos/secret-git012070d309a02098a3a588bc347d15fc4afc5d388ba54b50716122322963dbc577ff0a-1520435297266928900
- ERROR Directory secret-git012070d309a02098a3a588bc347d15fc4afc5d388ba54b50716122322963dbc577ff0a-1520435297266928900 is not empty and can't be removed

```

**Comment by strib** [comment]
Yep, that's expected if it's the bug I think it is.  I recommend just moving it as I said above.

(It probably has a "." entry that's not shown by `keybase fs ls`.)

**Comment by jeham** [comment]
Your suggested "mv" command sadly has no effect:

```
k:\team>keybase fs mv /keybase/team/my-team/.kbfs_git/.kbfs_deleted_repos/secret-git012070d309a02098a3a588bc347d15fc4afc5d388ba54b50716122322963dbc577ff0a-1520435297266928900 /keybase/team/my-team/.kbfs_git/.kbfs_old_broken_secretgit

k:\team>keybase fs ls /keybase/team/my-team/.kbfs_git/.kbfs_deleted_repos
secret-git012070d309a02098a3a588bc347d15fc4afc5d388ba54b50716122322963dbc577ff0a-1520435297266928900

k:\team>keybase fs ls /keybase/team/my-team/.kbfs_git/.kbfs_old_broken_secretgit
- ERROR file does not exist

k:\team>keybase fs ls /keybase/team/my-team/.kbfs_git
.kbfs_deleted_repos  company  development

```

**Comment by strib** [comment]
Oh darn, sorry, I forgot you can't name things starting with `.kbfs_`.  Try this instead:

```
keybase fs mv /keybase/team/my-team/.kbfs_git/.kbfs_deleted_repos/secret-git012070d309a02098a3a588bc347d15fc4afc5d388ba54b50716122322963dbc577ff0a-1520435297266928900 /keybase/team/my-team/.kbfs_git/.old_broken_secretgit
```

**Comment by jeham** [comment]
Sorry to say it did not help:

```
k:\team>keybase fs ls /keybase/team/my-team/.kbfs_git
.kbfs_deleted_repos  company  development

k:\team>keybase fs mv /keybase/team/my-team/.kbfs_git/.kbfs_deleted_repos/secret-git012070d309a02098a3a588bc347d15fc4afc5d388ba54b50716122322963dbc577ff0a-1520435297266928900 /keybase/team/my-team/.kbfs_git/.old_broken_secretgit

k:\team>keybase fs ls /keybase/team/my-team/.kbfs_git
.kbfs_deleted_repos  .old_broken_secretgit  company  development

k:\team>keybase fs ls /keybase/team/my-team/.kbfs_git/.kbfs_deleted_repos
secret-git012070d309a02098a3a588bc347d15fc4afc5d388ba54b50716122322963dbc577ff0a-1520435297266928900

k:\team>keybase fs ls /keybase/team/my-team/.kbfs_git/.old_broken_secretgit

k:\team>git clone keybase://team/my-team/company
Cloning into 'company'...
Initializing Keybase... done.
Syncing with Keybase... done.
git-remote-keybase error: (1) Directory secret-git012070d309a02098a3a588bc347d15fc4afc5d388ba54b50716122322963dbc577ff0a-1520435297266928900 is not empty and can't be removed
git-remote-keybase error: (1) Directory secret-git012070d309a02098a3a588bc347d15fc4afc5d388ba54b50716122322963dbc577ff0a-1520435297266928900 is not empty and can't be removed

k:\team>

```

**Comment by strib** [comment]
Arg sorry, looks like the `keybase mv` command doesn't do what I thought.  Do you have the file system drivers installed?  (That is, do you have a K:\ drive?)  If so, just navigate there via the files explorer and move/rename the folder manually, using the path above.

(Sorry, I don't spend a lot of time on Windows, I forgot exactly how things worked.)

**Comment by jeham** [comment]
I have a K-drive but my directory k:\team\my-team is empty when viewing it via eg. Explorer so there's no way of moving/renaming the directory from outside of Keybase AFAIK.

I found the following in your code, kbfs\libkbfs\folder_block_ops.go:

```
var hiddenEntries = map[string]bool{
	".kbfs_git":     true,
	".kbfs_autogit": true,
}

```
Maybe that's why I can't see any file or dir below my team folder?

**Comment by strib** [comment]
Arg yeah, they are special directories that aren't listed by default but you can still `cd` into them from the terminal/command prompt.  Maybe you can try from there?

**Comment by jeham** [comment]
Yes, it was possible to cd into it from CMD prompt and also from Cygwin. Still unable to remove (rmdir/rm -rf) the directory, though. Same error message ("Directory not empty") as before.

**Comment by strib** [comment]
Yes I wouldn't expect the rm to work, but a move/rename should work.

**Comment by jeham** [comment]
Yes! A "move" via command prompt fixed the error!

Thanks for the help and for a great software!

**Comment by strib** [comment]
Yay!  Sorry for the trouble and all the back and forth here.  I don't think this should happen again in the future, it stemmed from a bug in the very early version of git, if I'm guessing correctly.  I'll close this out, please re-open or file a new issue if you see it again.
