### ISSUE TITLE
Annoying/Frequent "Create a paper key" notification

### ISSUE THREAD

**Issue by MiLeung** [keybase/client#10856]
Keybase GUI Version: 1.0.45-20180305194145+3a1c65a05

I keep getting this notification. How do I stop it?

<img width="876" alt="screen shot 2018-03-11 at 10 55 04 pm" src="https://user-images.githubusercontent.com/9166324/37267718-50c9012e-257f-11e8-9543-da601bd9a81e.png">

**Comment by dabura667** [comment]
Make a paper key and it stops.

**Comment by MiLeung** [comment]
When I click Create paper key, it brings me to the devices tab, and my only options are to either add another device or revoke a device.

**Comment by MiLeung** [comment]
Got it, on the add devices page, you can add a paper key by pressing the "+ Add new..."
