### ISSUE TITLE
Reset private folder

### ISSUE THREAD

**Issue by jacquesbh** [keybase/client#10851]
Hi,

It seems my private folder was first created by an old computer which is revoked now. And I started from scratch after that probably.

Is it possible to reset my private folder please?

```
BEGIN KEYBASE SALTPACK SIGNED MESSAGE. kXR7VktZdyH7rvq v5weRa0zkS3m1Wy hTdQfXBQN4aBJRH NhUF653eKVAyFUR xuVjOY172HFXGKr CTFZj4hCydUNqvM 2w7wXE8Wvyrm94A 3gCuMu5Vz4MBsFZ cYtCa2AYAGLBDkH f9ZynOSu23jQDCj fBNkIJPIQHXutfA elRJlwE0Hj9oXec v12NhuNCr3lokUR LYxH7jrgR1QS2e1 m91u5DmZqRwjydP kxKhwZbrSox9SYj pV7iabYY1tBJQZD GtMR861g3iihOJD LpjIuE9N6ny4W26 pEWGWg05KlgNx35 B7gESj5JrLwflQJ rwj3ULvraM2wzgt vVkhzZzIAQEMba0 eoKeOM7wT1nIc8Q o. END KEYBASE SALTPACK SIGNED MESSAGE.
```

(I can't access git repositories, I think these issues are related)

**Comment by strib** [comment]
I reset the folder.  Please check it out and close this if everything seems ok.  (Might require a Keybase restart.)

**Comment by jacquesbh** [comment]
Thank you! It works perfectly well. (files directory and git repositories)
