### ISSUE TITLE
Cannot mount keybasefs

### ISSUE THREAD

**Issue by zkascak** [keybase/client#10855]
I am unable to mount keybasefs on my surface pro 4 running Windows 10 Pro 1709 build 16299.48. Everytime I click on the button to open a public or private folder the app does nothing.

**Comment by zanderz** [comment]
Can you do a `keybase log send` at the CLI? Thanks.

**Comment by zkascak** [comment]
sorry about the delay; was dealing with some problems at work. log id = 0dd861ad826cd70d277bd21c

**Comment by zanderz** [comment]
kbfs was not able to connect to the Dokan mounting service:
`102858 2018-02-14T01:17:42.867158-05:00 - [ERRO kbfs mounter.go:30] 032 Failed to mount dokan filesystem (i=8): Dokan failed: code=-3 "Driver install error"`
If there is another filesystem driver installed, it could conflict. Or if it was installed under a different user account. You could try uninstalling Dokan from the control panel and reinstalling from [their released package](https://github.com/dokan-dev/dokany/releases/download/v1.1.0.2000/DokanSetup_redist.exe), which would let you try using their sample program, mirror.exe, (`%ProgramFiles%\Dokan\Dokan Library-1.1.0\sample\mirror\mirror.exe`). That would tell whether something is interfering with Dokan itself.

**Comment by zkascak** [comment]
By another filesystem driver, do you mean something like Paragon HFS+? I use that to mount drives formatted for Mac OS that I receive from students.

**Comment by zkascak** [comment]
That has fixed it. KBFS is back and usable. Is there anything else that you need?

**Comment by zanderz** [comment]
Do you mean that you removed Paragon HFS+ and the KBFS mount started working again, or what happened? That would be useful information.
