### ISSUE TITLE
keybase installing but won't run in Linux

### ISSUE THREAD

**Issue by scurl** [keybase/client#10871]
The errors look like this:

▶ INFO Starting keybase.service.
Job for keybase.service failed because the control process exited with error code. See "systemctl --user status keybase.service" and "journalctl -xe" for details.
▶ ERROR Failed to start keybase.service.
▶ ERROR Error in spawning server process: exit status 1
▶ ERROR exit status 1
$ systemctl --user status keybase.service
● keybase.service - Keybase core service
   Loaded: loaded (/usr/lib/systemd/user/keybase.service; disabled; vendor prese
   Active: inactive (dead)

Mar 12 21:09:11 laptop-home systemd[1517]: Stopped Keybase core service.
Mar 12 21:09:11 laptop-home systemd[1517]: Starting Keybase core service...
Mar 12 21:09:11 laptop-home systemd[1517]: keybase.service: Main process exited,
Mar 12 21:09:11 laptop-home systemd[1517]: Failed to start Keybase core service.
Mar 12 21:09:11 laptop-home systemd[1517]: keybase.service: Unit entered failed 
Mar 12 21:09:11 laptop-home systemd[1517]: keybase.service: Failed with result '
Mar 12 21:09:11 laptop-home systemd[1517]: keybase.service: Service hold-off tim
Mar 12 21:09:11 laptop-home systemd[1517]: Stopped Keybase core service.
Mar 12 21:09:11 laptop-home systemd[1517]: keybase.service: Start request repeat
Mar 12 21:09:11 laptop-home systemd[1517]: Failed to start Keybase core service.

$ journalctl -xe

-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit UNIT has failed.
-- 
-- The result is failed.
Mar 12 21:09:11 laptop-home systemd[1517]: keybase.service: Unit entered failed state.
Mar 12 21:09:11 laptop-home systemd[1517]: keybase.service: Failed with result 'exit-code'.
Mar 12 21:09:11 laptop-home systemd[1517]: keybase.service: Service hold-off time over, scheduli
Mar 12 21:09:11 laptop-home systemd[1517]: Stopped Keybase core service.
-- Subject: Unit UNIT has finished shutting down
-

**Comment by strib** [comment]
cc @oconnor663 

Can you please do a `keybase log send`, and let us know the resulting log ID?  Thanks.

**Comment by scurl** [comment]
773ee965475e22d65528db1c

thanks!

**Comment by maxtaco** [comment]
cc @oconnor663 there could be a break in last night's build

**Comment by oconnor663** [comment]
```
open /home/stefan/.config/autostart/keybase_autostart.desktop: permission denied
```

I see that error in the log. It could be that your `~/.config` folder is root owned, or at least some important subset of it. You might need to `chmod -R ...` that directory.

**Comment by scurl** [comment]
That was indeed the fix (just now). The folder was root owned. Running as the user didn't have access, but trying to run as root was not allowed by keybase. Changing the /.config/keybase with chmod -R (as above, but just for /keybase) fixed it.

**Comment by cheapRoc** [comment]
It sounds like in the future this error message could be more clear, at least in this case.

**Comment by jazire** [comment]
> ```
> open /home/stefan/.config/autostart/keybase_autostart.desktop: permission denied
> ```
> 
> I see that error in the log. It could be that your `~/.config` folder is root owned, or at least some important subset of it. You might need to `chmod -R ...` that directory.

This works for me, thanks!
