### ISSUE TITLE
Contents of my root folder has disappeared 

### ISSUE THREAD

**Issue by choiway** [keybase/client#10873]
Keybase GUI Version: 1.0.45-20180312163100+eb8e5c2534

On my Ubuntu machine the contents of `/keybase` has disappeared. They are still available on my machine through the keybase client and in `/run/user/1000/keybase/kbfs` but they no longer appear in `/keybase`

**Comment by sot001** [comment]
$ keybase version
Client:  1.0.45-20180312163100+eb8e5c2534
Service: 1.0.45-20180312163100+eb8e5c2534

I have the same symptoms as above, on Ubuntu 16.04. I've uploaded my logs, LOG ID: 59b2f2b2fe572e810cbd1f1c

thanks

**Comment by strib** [comment]
Hi all, this is a known bug.  It will be fixed in the latest release.  If you want to fix it before then, do:

```sh
nohup keybase-redirector /keybase &> /dev/null &
```

**Comment by sot001** [comment]
Thanks, that fixed it :)

**Comment by choiway** [comment]
Worked for me too...thanks!

**Comment by MyC-Greg** [comment]
Hi I have the same problem as @choiway but on my mac.
Keybase GUI Version: 3.2.1-20190410040938+61d9000f85
It started with a word document that could not be saved anymore, then an alert from keybase and then `/keybase` not being accessible.
