### ISSUE TITLE
please distribute a version without keybase-redirector

### ISSUE THREAD

**Issue by kwantam** [keybase/client#10876]
Hello,

As you know, `keybase-mount-helper` was recently replaced by `keybase-redirector`, a setuid binary owned by root; and at the same time, the client added a configuration option to enable or disable redirector.

The purpose of this ticket is to request that you go further, and distribute a version of the package that does not contain `keybase-redirector` at all. For anyone (like me) who disables `keybase-redirector`, the vestigial binary's only purpose is to serve as a potential vector for attack.

As a stopgap measure (which may be useful to those finding themselves in the same position, at least if they use Debian-ish systems), I've added a dpkg post-invoke hook that deletes `/usr/bin/keybase-redirector` (necessary because each time I upgrade the keybase package, that binary is re-installed).

    # /etc/apt/apt.conf.d/81no-keybase-redirector
    DPkg::Post-Invoke {"rm -f /usr/bin/keybase-redirector";};

**Comment by strib** [comment]
We won't be doing this, but other distributions are welcome to.  We've put up instructions at https://keybase.io/docs/kbfs/understanding_kbfs about turning it off and clearing the suid bit if it bothers you.

Thanks for sharing your hook!

**Comment by eli-schwartz** [comment]
@kwantam, the obvious solution to this is to have distro packages that conform to distro policy. I think Arch Linux is the only distro which currently packages keybase though -- and we certainly won't be packaging this setuid binary...

**Comment by eli-schwartz** [comment]
Also note that a post-install hook merely turns a potential vector for attack, into a race condition for a potential vector for attack. In between the time that the files are extracted to disk and the post-install hook gets run, that attack vector still exists...
