### ISSUE TITLE
Ok, i cant send chat messages.

### ISSUE THREAD

**Issue by internetpersoncode** [keybase/client#10886]
So i cant send chat messages. I have recently reset my account and i cant send messages in keybase. when i do, this happens. [LINK TO SCREENSHOT](https://media.discordapp.net/attachments/418174852600692737/423274978096578574/unknown.png) Please help!

**Comment by maxtaco** [comment]
Do `keybase log send`

**Comment by internetpersoncode** [comment]
Ok. Done. My log id is `e8e31c3f1142cbe589ae081c`

**Comment by maxtaco** [comment]
What's going on with your network?  Your DNS server is lying about the IP address of our servers.

**Comment by maxtaco** [comment]
```
84580 2018-03-13T20:22:40.596831-04:00 - [WARN keybase connection_log.go:65] 94f (CONN gregor a51a0bb5) Connection: error dialing transport: dial tcp 172.27.0.1:443: connectex: A connection attempt failed because the connected party did not properly respond aft
```
That's not the right IP address.  Do you have some security software or something running?

**Comment by internetpersoncode** [comment]
No, but i have my VPN running. Nothing else really security related other than my AV. (which im pretty sure isnt messing with anything.)

**Comment by Nirudium** [comment]
VPNs don't like Keybase for some odd reason.

**Comment by maxtaco** [comment]
The issue is likely your VPN, yeah...

**Comment by internetpersoncode** [comment]
ok, imma try it with my vpn off then get back to you :)

**Comment by internetpersoncode** [comment]
Ok. Its working now! Thanks guys!
