### ISSUE TITLE
Teams notification not going away

### ISSUE THREAD

**Issue by rhubinak** [keybase/client#10892]
Teams notification is displayed and cannot be removed.
Keybase 1.0.45-20180305114930+3a1c65a

Affected environments:
Windows 10 Professional Version 1709 16299.248
Android 6.0.1
iOS 11.2.6

<img width="960" alt="untitled" src="https://user-images.githubusercontent.com/5836793/37409059-ae4feb8a-279d-11e8-8cab-e28fa9a7d2a5.png">

**Comment by mvyletel** [comment]
same on fedora 27 and keybase-1.0.45.20180313160419.f0de728311-1.x86_64

**Comment by mvyletel** [comment]
and on ios 11.3 and 1.0.45-20180305195401+3a1c65051

**Comment by maxtaco** [comment]
If you guys can run `keybase log send` we can investigate

**Comment by mvyletel** [comment]
sure thing. is this sufficient?
------------
Success! Your log ID is:

  5aa01ab8d5d0898bb9a9ab1c

**Comment by rhubinak** [comment]
f13fae3975fdfa7d81022d1c

**Comment by mmaxim** [comment]
@patrickxb

**Comment by maxtaco** [comment]
@rhubinak  / @mvyletel can you keybase message me with the name of the team?  I'm `max`. Thx

**Comment by mvyletel** [comment]
@maxtaco already messaged you the team name but as mentioned on the chat the notification is gone on both Linux and iOS.
Linux keybase-1.0.45.20180314153959.acd706b851-1.x86_64
iOS 1..45-20180305195401...

**Comment by maxtaco** [comment]
Hmmm, ok....  Out of curiosity, did one of your team members recently reset his account?

**Comment by mvyletel** [comment]
I believe so. not sure how long ago but couple weeks ago give or take.

**Comment by rhubinak** [comment]
Notification is gone on both Windows and Android

**Comment by rhubinak** [comment]
Notification is gone on both Windows and Android
