### ISSUE TITLE
Windows KBFS previously working, now stopped working

### ISSUE THREAD

**Issue by OliverCole** [keybase/client#10954]
I tried accessing K:, my KBFS drive, it was unavailable:

> K:\ is unavailable. If the location is on this PC, make sure that the device or drive is connected or the disc is inserted, then try again.....

I did a repair with the latest Keybase installer, and restarted when prompted. Then I could access K:, but it was empty. Now I can no longer access it again ("unavailable").

The Keybase client still shows my KBFS directories.

my log id: b7b584423a17c0f4ebf4c41c

**Comment by zanderz** [comment]
KBFS was unable to reach its servers:
`103076 2018-03-19T12:39:42.328749-04:00 - [WARN kbfs mdserver_remote.go:403] 090 MDServerRemote is disconnected
`
....
`103142 2018-03-19T12:50:38.921739-04:00 - [WARN kbfs(BSR) connection_log.go:65] 0d2 (CONN BlockServerRemoteGet 25faf4b6) Connection: error dialing transport: dial tcp: lookup bserver-0.kbfs.keybase.io: no such host`

Do you have a spotty connection or are you behind a restrictive firewall?

**Comment by OliverCole** [comment]
Connection is fine.
Firewall - not to my knowledge - just the built in Windows 10 one for this device.

If you give me the port number I can try and hit this directly?

**Comment by zanderz** [comment]
mdserver.kbfs.keybase.io:443
bserver.kbfs.keybase.io:443

looks kind of like dns errors though - @strib?

**Comment by strib** [comment]
Yeah, must be local DNS errors.

The exact DNS above to try is `bserver-0.kbfs.keybase.io:443`.  For example, this should work:

```sh
openssl s_client -connect bserver-0.kbfs.keybase.io:443
```

Assuming you have the openssl package installed for Windows.

**Comment by OliverCole** [comment]
Unfortunately it's now started working again. I will try the above if it happens again.

**Comment by OliverCole** [comment]
Issue reoccurring - same symptoms. Connection fine.

```
C:\Users\Oliver>openssl s_client -connect bserver-0.kbfs.keybase.io:443
WARNING: can't open config file: /etc/ssl/openssl.cnf
Loading 'screen' into random state - done
CONNECTED(0000024C)
depth=0 DC = io, DC = kbfs.keybase, CN = bserver.kbfs.keybase.io
verify error:num=20:unable to get local issuer certificate
verify return:1
depth=0 DC = io, DC = kbfs.keybase, CN = bserver.kbfs.keybase.io
verify error:num=27:certificate not trusted
verify return:1
depth=0 DC = io, DC = kbfs.keybase, CN = bserver.kbfs.keybase.io
verify error:num=21:unable to verify the first certificate
verify return:1
---
Certificate chain
 0 s:/DC=io/DC=kbfs.keybase/CN=bserver.kbfs.keybase.io
   i:/DC=io/DC=kbfs.keybase/CN=Keybase KBFS CA prod
---
Server certificate
-----BEGIN CERTIFICATE-----
MIIF/TCCA+WgAwIBAgIQGi3ESvl25KOWykKitIGlHjANBgkqhkiG9w0BAQsFADBR
MRIwEAYKCZImiZPyLGQBGRYCaW8xHDAaBgoJkiaJk/IsZAEZFgxrYmZzLmtleWJh
c2UxHTAbBgNVBAMMFEtleWJhc2UgS0JGUyBDQSBwcm9kMB4XDTE3MTEwMzIyNTIx
MVoXDTIyMTEwMjIyNTIxMVowVDESMBAGCgmSJomT8ixkARkWAmlvMRwwGgYKCZIm
iZPyLGQBGRYMa2Jmcy5rZXliYXNlMSAwHgYDVQQDDBdic2VydmVyLmtiZnMua2V5
YmFzZS5pbzCCAiIwDQYJKoZIhvcNAQEBBQADggIPADCCAgoCggIBAKXdqL0o/9Vu
AtfEVpi74dfKW77PQ4GLUZNa30so8b4vSiawys/dxfab/QLWKSxc6dpC1rn/Fmjo
CFLlkliRVhjAkJzVWliauOyguA2yOz/1e6fsxCozLwfr6JKRxDnzXv8oGjyJxClo
InN7vp4KSncpw52QAbrES4SAQmIO6fHrMR2YTxtYemjUy8aP6KMD+3KAjcHnCCyp
MGoZEv60X6PM9c9UWCtpmcK092Kdzwmp7qhubor27EgnOi0fHoSepQHnaKgRr9MX
GpY0YxQ0PkhhS5wcIvFLvFKuU+AJcQZUy49dARp2IxSTAXfHqKzuTSuRM48rk5Ar
UtD5v/OWL2DKmfz2it9kbGT03JzYaGQvfMSpqbJ9I1wRNUBXYkGttlfP2KM8fMVQ
sOumcmWQEShws2v7KhDvTGYSaXix945F9Pwssa4EbiNIBS4jHj8wWCdQy3Mg0m7R
bOVI82vrvwAIfn7Fc77LLlJie2oXDYd+S0GqyqhCH/5x7rHTwxeaU0JRbM/kL71I
hIjfMyr7gq2XC7gtgzExcO7RcdHtmyMwUp3e58dbZQe/3qpQBEz8ig4wMe8qfxC6
m5noHsUDE6/bf7IJEZcUHdAGh3POQhRdabU3W76/yQvyTF7sRzTODLpzFyYfv4Vg
AUaXkp+1e1RNRlBSFWkxbj5HDuEAMJddAgMBAAGjgc0wgcowDgYDVR0PAQH/BAQD
AgeAMB0GA1UdDgQWBBQ6gc2+ijrL+Tpfbbf/15W+wW87HzCBmAYDVR0RBIGQMIGN
ghdic2VydmVyLmtiZnMua2V5YmFzZS5pb4IZYnNlcnZlci0wLmtiZnMua2V5YmFz
ZS5pb4IZYnNlcnZlci0xLmtiZnMua2V5YmFzZS5pb4IdYnNlcnZlci0wLmtiZnMu
a2V5YmFzZWFwaS5jb22CHWJzZXJ2ZXItMS5rYmZzLmtleWJhc2VhcGkuY29tMA0G
CSqGSIb3DQEBCwUAA4ICAQAHm+6JrEJlanA1bDdy3qbdmyv37OG6ukMBbcm5Gs7E
pBiRpRCEw+FoRcjTQ+rj7KKXjbOt3uLO9cgD+kjajK0a4SerTNpA15TxaSfzhicz
3axZhjnxZKscO/DY0Bq/jNq03+u9gE8kniYrG7ETPBiQJznzQSPHDNej1I/RqDlT
4DVA/niHNUVHThYTZtvA3esulwjlbxTlOQZ7gUm6/Zu4Y0U0faPmnvVj3OmfaGvB
tPS27O7uxvgfxf7Sqyt7hv/mB51N8cldQyUWd5zBSZTJh0p9zOBRjDk3hLyux2le
eocqaV0Mof5EQodfJXFlELazp2IyrelvJsZo+W/4F8ZI82ZuY/OnpU/6tzvfEl0K
k9eSuzX5G1qCVXWqH/Mn637FL2EENBCZG3fNKY072JA7kTLx/dHL8NaEyMCYJ2EX
JspbM3YuS5qz/5s+VqfDqdbo30LmlRk1pyAXdktTdYhfSbtxHKBVwkxTHoz97F9Y
hr4JQLK3c6e1Y+9+ansZFZblIPpX+Xr23Tqh3z7stSpGnneCSJf3WLXVI7v9rtgb
EQAqbgO9gPaIxkpPadTPfrLghbn14CTG1vvcaOi7qwHNQyAkDYawfZAVqqxMMFbL
e8kEfa4Bkv1UyC1S/4N74wV/Elw6lOWW+PZznUKmRYz+ps65JNCsOFcmhzB0lkG/
nA==
-----END CERTIFICATE-----
subject=/DC=io/DC=kbfs.keybase/CN=bserver.kbfs.keybase.io
issuer=/DC=io/DC=kbfs.keybase/CN=Keybase KBFS CA prod
---
No client certificate CA names sent
---
SSL handshake has read 2399 bytes and written 417 bytes
---
New, TLSv1/SSLv3, Cipher is ECDHE-RSA-AES256-GCM-SHA384
Server public key is 4096 bit
Secure Renegotiation IS supported
Compression: NONE
Expansion: NONE
SSL-Session:
    Protocol  : TLSv1.2
    Cipher    : ECDHE-RSA-AES256-GCM-SHA384
    Session-ID: A55D116E723B537725197A30EE3D84B62602EF8226FFC6977A03758F7F551C99
    Session-ID-ctx:
    Master-Key: 0FDDA106099E5E91EEFC8F5AFD5FBC91434EF24CF60E74BB9C9D8C0CF3AD4731938A315D94EB19B0BDBDB198D0DF920B
    Key-Arg   : None
    PSK identity: None
    PSK identity hint: None
    SRP username: None
    TLS session ticket:
    0000 - 1b 85 4f 4c a7 6a ed cf-0e dc 6f 18 16 90 24 61   ..OL.j....o...$a
    0010 - aa e2 e7 4c 2b 21 0d 26-4f 78 cf f5 0b 8c 67 93   ...L+!.&Ox....g.
    0020 - 7a f5 7c 75 b6 a7 92 e5-7b d7 ac 3f d1 d5 6e 51   z.|u....{..?..nQ
    0030 - 0f 25 c6 21 0f 70 52 3c-fe aa 32 7c 21 ab ac 79   .%.!.pR<..2|!..y
    0040 - df 18 df d7 58 63 07 83-90 6e 3a ae ab a9 73 e0   ....Xc...n:...s.
    0050 - 9b 8b 91 23 d9 d4 3f 13-c3 76 7d e3 ba ff ad bc   ...#..?..v}.....
    0060 - 5b 9b 35 57 fb 3b 33 11-1d 98 e1 a3 c4 b5 07 00   [.5W.;3.........
    0070 - 26 f5 a8 b9 5f 20 a7 ed-                          &..._ ..

    Start Time: 1521997718
    Timeout   : 300 (sec)
    Verify return code: 21 (unable to verify the first certificate)
---
read:errno=10093

C:\Users\Oliver>keybase log send
This command will send recent keybase log entries to keybase.io
for debugging purposes only.

These logs don’t include your private keys or encrypted data,
but they will include filenames and other metadata keybase normally
can’t read, for debugging purposes.

Continue sending logs to keybase.io? (type 'YES' to confirm): yes
Enter feedback (or ENTER to send): https://github.com/keybase/client/issues/10954
Enter feedback (or ENTER to send):


------------
Success! Your log ID is:

  bfb8b37b064052034b00a21c

Here's a URL to submit new bug reports containing this ID:

  https://github.com/keybase/client/issues/new?body=[write%20something%20useful%20and%20descriptive%20here]%0A%0Amy%20log%20id:%20bfb8b37b064052034b00a21c

Thanks!
------------
```

**Comment by maxtaco** [comment]
No other reports of this. Are you behind a proxy?

**Comment by maxtaco** [comment]
(Deleted the above comment / question...)

**Comment by zanderz** [comment]
This most recent log does point to a different problem - Dokan thinks the mount drive letter is unavailable:
`
112928 2018-03-25T08:46:29.211297+01:00 - [ERRO kbfs mounter.go:30] 06f Failed to mount dokan filesystem (i=16): Dokan failed: code=-5 "Mount error"`
Is there a chance K: is used by something else? All I can think of to try is to change the letter and reboot:
`keybase kbfsmount set X`

**Comment by OliverCole** [comment]
I've not added or removed any physical or software drives. But I'll give that a go.

**Comment by OliverCole** [comment]
No change on a different drive letter.

    Your log ID is: 2cbe6dbd7e2cf2dbc4b8391c

**Comment by zanderz** [comment]
Thanks for trying that, but I'm afraid it still shows Dokan mount error "-5", meaning the driver couldn't connect to the drive letter, and it is unclear why that might be.

**Comment by OliverCole** [comment]
Would you be able to open a Dokan issue with the necessary details, and I can jump in if they need any tests running?
Also if you wanted to recommend a simple app that also relies on Dokan we can eliminate Keybase as the issue?

**Comment by zanderz** [comment]
You can isolate Dokan with the mirror.exe sample, typically located at `C:\Program Files\Dokan\Dokan Library-1.1.0\sample\mirror`. If you don't have it, you can uninstal your current Dokan with the control panel and reinstall from 
`https://github.com/dokan-dev/dokany/releases/download/v1.1.0.2000/DokanSetup_redist.exe`
(doing the necessary reboot(s)) in between)
Open a cmd window as admin and mount some local directory with the sample, like `mirror /r c:\test /l m` and then see if your test directory is available at `m:`. For me it works even while KBFS is mounted. If it doesn't work, there is a driver issue. If that works, we may have some KBFS problem.

**Comment by OliverCole** [comment]
Interestingly I was running 1.0.0. It didn't have the samples, so obviously uninstalling and installing 1.1.0 has again fixed the issue, for now.
See you next time!
