### ISSUE TITLE
Windows Save Folder Locations, Start/Stop Control & Mount in a Folder

### ISSUE THREAD

**Issue by cyberpunkbln** [keybase/client#10957]
Hello,

i have a few short Questions:

1. How can i set the save locations for the kbfs-folders on windows? I don't want the kbfs save locations on my system-ssd. The same questions go to other big files like cache.

2. How can i better control the start/stop/restart mechanisms? I want to control the whole keybase installation with an powershell/batch-skript, where i can stop completly all keybase-tasks, restart and start again.

3. Can i mount kbfs with kbfsmount on a Folder like this kbfsmount set e:\KeybaseFolder, he take the command but i don't feel after a restart it can be an desaster;).

thx
ps: give it an location where i can see all keybase command options?

**Comment by cyberpunkbln** [comment]
Hello,
a little update from my own attempt. I have found the keybase ctl stop/start/restart command. When i deactivate the two autostarts, then can i determine when keybase and kbfs starts. But when i try to restart or start, the dokan driver will not be started and i must complete stop and then start the keybase gui. I search the command for a complete start with the cli.

**Comment by zanderz** [comment]
If you examine the service startup shortcut, `%appdata%\Microsoft\Windows\Start Menu\Programs\Startup\KeybaseStartup.lnk` it does this:
`%localappdata%\Keybase\keybaserq.exe keybase.exe ctl watchdog2`
`keybaserq.exe` just runs the console command without showing the console. `watchdog2` is what causes a copy of the process to persist and open kbfsdokan.exe.
You could just drag this shortcut out of the start menu and onto the desktop if you prefer. Note that the GUI will start the services if they are not already running when invoked.

**Comment by cyberpunkbln** [comment]
Thx, that is it. Cool one problem fewer;).

I have a read another Post from you where you give an manual to set another path for the whole app. That is was i try to became another kbfs_block_cache and other dirs location.

set an new %localappdata% location does not seem to work, but iam at start to test another possibilites:).

I think keybase uses the %appdata% for the roaming caches, that i must set, too.

Hmm seems complicated to make keybase a little bit portable;).

I know i can make junction or symbolic links but this is every time a hack that i use only when the app does have internal configs for data dirs or so.

Its a feature-request in the future from me to make keybase directory structure more configurable;).

**Comment by strib** [comment]
@cyberpunkbln for what it's worth, data in KBFS folders are not persisted on your local hard drive; unlike something like dropbox, data is downloaded over the network whenever you access it.  So there's not a huge need to change any KBFS disk locations.

We do have on-disk caches for performance reason, and those are under %appdata% as you say, but those are limited to a small percentage of the current available disk usage.  I.e., if you start using more of your disk for something else, Keybase will automatically cache fewer things.

**Comment by cyberpunkbln** [comment]
@strib thx for the answer, you show me that i have not really understand the system behind kbfs and keybase. I have searched for under the dokan-website for encfswin and then i have read

dokan-project-link
Keybase | A cryptographically secure file mount using PGP key.

And I thought, oh cool an encfswin and cryptomator alternative that i must try;).

My guess was that /private/myusername is like encfswin/cryptomator and /public and /team are like a filecloud;).

kbfs was an completly filecloud;), cool (i was hoping that the kbfs-part was an gpg-replacement for encfswin or cryptomator with dokan functionality) i will use keybase nevertheless;).

Now i know why a delete in  the drive locally not garbage the kbfs_block_cache *smile*.

But i want to not stress my SSD and that is the next reason why i want another install/cache location on my other hdds.

PS: Give it a project that use gpg and dokan for local enrypted directorys like encfswin or cryptomator?

**Comment by strib** [comment]
Cool.  You can find more detailed info about KBFS here: https://keybase.io/docs/kbfs/understanding_kbfs

**Comment by cyberpunkbln** [comment]
Ah thx for the docu-link.

Now i understand it;), that what i wanted first complete locally like encfswin, will be completly fileclound-based implemented in kbfs. Very cool is a possibility for me but i search for an kbfs completly locally hosted or locally filebased.

ps: Give it an docu-link for the help advanced commands? I try to tuse --db and others like this?

**Comment by cyberpunkbln** [comment]
I think i use junction-points or symbolic-links for the portable-mode:).

set %localappdata% and %appdata% don't work, --db e:\newdb don't work, too.
