### ISSUE TITLE
Incorrect fingerprint for github proof?

### ISSUE THREAD

**Issue by lindhe** [keybase/client#10953]
The output I got when trying to prove my Github identity seems to use a fingerprint I do not recognise. It starts out like this:

```
### Keybase proof

I hereby claim:

  * I am lindhe on github.
  * I am lindhe (https://keybase.io/lindhe) on keybase.
  * I have a public key ARB61KejAt8j-Z8OHwbrT4gZz0eyA2nE3V_xMKgsZIasQgo
```

As you can tell, it does not at all look like a fingerprint usually does, and it's certainly not `4EEECFA0147F71215C72CF2E34C14B6996D5B89E` which I expected to see.

It might well be something fancy like a NaCL fingerprint or something else I'm not familiar with. If it is not, I'll provide more details to debug. But I don't feel like writing an essay in case this is expected output.

**Comment by lindhe** [comment]
Can I make it use GPG instead of NaCL if that is what's happening here?

**Comment by dabura667** [comment]
Base64 for a NaCl kid

Written in hex it would be

`01107ad4a7a302df23f99f0e1f06eb4f8819cf47b20369c4dd5ff130a82c6486ac420a`

**Comment by dabura667** [comment]
https://gist.github.com/lindhe/e3b5310aed8073d361298689eed6e6f5

Your proof says:

`I have a public key whose fingerprint is 4EEE CFA0 147F 7121 5C72 CF2E 34C1 4B69 96D5 B89E`

I'm confused.

What's your problem?

**Comment by lindhe** [comment]
After five or so "failed" attempts using the keybase cli client, I tried the `bash + crul + gpg` method and got a proof with a PGP fingerprint. I now realize that it most likely was a legitimate proof the first time(s) also, but I didn't understand that since I expected to see a PGP style fingerprint. My issue was further compounded by the fact that a third party client I used incorrectly said that the proofs using NaCl cloud not be verified (so I started to think something was broken on your end). So I guess I have figured things out by now, and there was no real bug (in your client) to begin with.

But I would like to propose a give the alternative to use PGP instead of NaCl. I'm pretty well versed with cryptography, but the rather unusual fingerprint threw me off. Frankly, I don't even know what key that is or how to check that the fingerprint corresponds to the correct key. What I want to say is that I think it would be more user friendly if it had the option to use PGP keys instead of NaCl. I understand that your client can easily verify either, but people can't.

**Comment by dabura667** [comment]
PGP is not user friendly.

PGP is developer-that-knows-how-to-use-PGP friendly.

I am not affiliated with Keybase, but PGP keys are not compatible with the use cases that keybase is looking to fill with their services.

You can still generate proofs with PGP if you want. You just need to be aware that it is not default.

That’s not keybase’s fault.

Also, the third party app says that keybase support is experimental. So saying that keybase should change to match some third party’s app that is only experimental stage is not realistic.

**Comment by lindhe** [comment]
Please try not to warp the meaning of my words like that. I have never said anything anything along those lines.

> I am not affiliated with Keybase, but PGP keys are not compatible with the use cases that keybase is looking to fill with their services.

Yes, PGP keys are absolutely compatible with the use case of creating proofs. PGP is one of the core technologies used in Keybase. As you yourself have already pointed out, _[my proof was signed with a PGP key](https://gist.github.com/lindhe/e3b5310aed8073d361298689eed6e6f5)_.

NaCl might have some technical benefit that I do not know of, and if that is the case I have no issue at all with them having it as the default. But if PGP can be used (which it can) I would rather like to generate my own proofs with that technique, so that it's easier for me to compare the proofs with my key and so on. There are _a lot_ of users who know how to compare the PGP fingerprint with the correct key. No reason to not let them do that.

> You can still generate proofs with PGP if you want. You just need to be aware that it is not default.
> 
> That’s not keybase’s fault.

It is most certainly up to Keybase what's the default settings in their client. And while I would rather see PGP being their default setting I did not even propose that. I proposed giving us the option, not changing the default.

> Also, the third party app says that keybase support is experimental. So saying that keybase should change to match some third party’s app that is only experimental stage is not realistic.

The third party app clearly has a broken implementation of the Keybase proof verification, and there is an [open issue](https://github.com/open-keychain/open-keychain/issues/1638) for it. I said that my issue was compounded by the fact that the app _incorrectly_ were not able to verify the proofs. But maybe I should have rather written that "because of the fact that a third party app I use have an incorrect implementation for verifying Keybase proofs, I was further led to believe that the proofs with fingerprints I did not recognize were broken". But I was on mobile, so I chose not to be so precise.

---

What it boils down to, and what I think you misunderstood from what I wrote, is that it would be nice to be able to generate the proofs using signatures with PGP, directly using their client. As it stands, their web client generates proofs with PGP. The alternative "hardcore" version of CLI (I.E. bash + gpg + curl) uses PGP. The keybase cli client by some reason, does not. And as far as I can tell from the documentation, there is no flag for it. I think there should be one.
