### ISSUE TITLE
Team git repository has gone missing.

### ISSUE THREAD

**Issue by tobytripp** [keybase/client#10963]
```
➜  RepoName git:(master) ✗ git push
Initializing Keybase... done.
Syncing with Keybase... There is no repo named "reponame".
git-remote-keybase error: (1) There is no repo named "reponame".
```
my log id: ad2099c729c98be5a3c7421c

**Comment by strib** [comment]
@tobytripp does `keybase git list` show the repo you're trying to access?

**Comment by tobytripp** [comment]
It does.

**Comment by strib** [comment]
I followed up with @tobytripp in private chat.  Turns out some process on his device had explicitly deleted the kbfs git subdirectory.  Don't know how that could have happened, but anyway we were able to restore the repo.
