### ISSUE TITLE
Windows 10 - Icon Replace for ntfs-junction-folder

### ISSUE THREAD

**Issue by cyberpunkbln** [keybase/client#10977]
Hello,

i trusted dokan and set the kbfsmount to e:\Keybase and it's works;), but now i have the problem that the source-drive gets the icon from the original drive. Is there a possible to set this off? that no icon will be given for an mountpoint or the possibility to set an own icon?

thx

**Comment by zanderz** [comment]
These mount icons are controlled by the registry, at `HKCU\SOFTWARE\Classes\Applications\Explorer.exe\Drives\`
Keybase will write its icon there every time a drive letter is set, though.

**Comment by cyberpunkbln** [comment]
Ah okay, thx for the info. Is there a possibility to turn that off? or set another icon?

At the moment i del the reg-key with a script;).

**Comment by zanderz** [comment]
Once the mount point is set, Keybase should leave it alone. Otherwise, there is no setting or facility for changing it.
