### ISSUE TITLE
Reset private folder

### ISSUE THREAD

**Issue by byronrode** [keybase/client#10987]
Hey guys, it seems that during some of my device changes (theft/reinstalls/etc) my private folder has some access issues, similar to those of a few other issues I have seen.

I am sure it is related to the devices being revoked/reinstalled or the folder resetting and because my account is quite old, wasn't handled correctly.

You can go ahead and reset my folder. Signed message below:

```
BEGIN KEYBASE SALTPACK SIGNED MESSAGE. kXR7VktZdyH7rvq v5weRa0zkXqEgIH p7mE4hD4VfA3Sxg 5jc40iFt2zNuGYU y10vBiN241Jddsi q8aOry5bfO0Jzn3 x1mqPcQy7DWhADd g26OiV5KqsakSGl sxQXdLcxHUUkFIX bZpavs5Wjqv9N1v hpHTpxDY4ywlQXH 5rhqo4CElBGlraX q5110jwJzGHkcoR 2gO18iciBB3yexX yojK5RMY7R6Xr7X ONhZ7bZdQ8GhL5Z HSbg80GkE90ogX5 spBBEea4imQ80r6 0lXM9NoZX1i3Wo8 LD0h8QJU2QIHsMh 1O3WXNCEfHlndFH I1BMj47lRiDpspn 0CGyzD48Yj8AC50 aybxRb1a. END KEYBASE SALTPACK SIGNED MESSAGE.
```

**Comment by strib** [comment]
I reset the folder.  Please check it out and close this if everything seems ok.  (Might require a Keybase restart.)

**Comment by byronrode** [comment]
All sorted. Thanks
