### ISSUE TITLE
unable to send messages to a single user after fresh install (Linux)

### ISSUE THREAD

**Issue by JeffMelton** [keybase/client#11072]
I've just set up Keybase on a new machine (Linux/KDE Neon), and one private chat is exhibiting errors _only on this machine_ (i.e., it still works fine from my iOS client). I'm receiving messages from this user on this machine, and from other users on this machine. As far as I know, the only hiccup with her account was that she accidentally removed her Facebook proof, but that's since been rectified.

I have uninstalled/reinstalled the client; uninstalled/removed .local, .config, .cache keybase data/set up the device as new/reinstalled. I was able to send a single message after the purge and reinstall cycle, then reverted to error state again.

Relevant data (tell me if you need more):

```
$ keybase version
Client:  1.0.45-20180326162638+7f5ecfe57a
Service: 1.0.45-20180326162638+7f5ecfe57a
```

```
$ keybase chat ls
[1]  (unverified) tm2            [???] error unboxing chat message: Could not verify metadata (revision=38) for directory /keybase/private/jnm,tm2 (id=fc76...
```

```
$ keybase chat read 1
▶ ERROR Unable to find conversation.
When considering 2 as a username or a list of usernames, received error: failed to open chat conversation: TLF name 2 is in an incorrect format.
When considering 2 as a team name, received error: invalid team name: team names must be between 2 and 16 characters long.
```

From the Keybase GUI, when I try to send a message:
```
GENERIC: ERROR CODE 218 - no TLF name specified in method chat.1.local.postTextNonblock at o.t (file:///opt/keybase/resources/app/desktop/dist/index.bundle.js:1:388234) at o (file:///opt/keybase/resources/app/desktop/dist/index.bundle.js:1:388540) at a (file:///opt/keybase/resources/app/desktop/dist/index.bundle.js:1:387902) at t.convertToError (file:///opt/keybase/resources/app/desktop/dist/index.bundle.js:1:388100) at _rpcClient.invoke.t (file:///opt/keybase/resources/app/desktop/dist/index.bundle.js:1:344350) at file:///opt/keybase/resources/app/desktop/dist/index.bundle.js:1:1003195 at e.t.Deferrals.e._call (file:///opt/keybase/resources/app/desktop/dist/index.bundle.js:1:660045) at file:///opt/keybase/resources/app/desktop/dist/index.bundle.js:1:660196 at s (file:///opt/keybase/resources/app/desktop/dist/index.bundle.js:1:659825) at e.t.Deferrals.e._fulfill (file:///opt/keybase/resources/app/desktop/dist/index.bundle.js:1:660155)
```

And from keybase CLI, when I try to send a message:
```
▶ ERROR error unboxing chat message: Could not verify metadata (revision=38) for directory /keybase/private/jnm,tm2 (id=fc76e81c5697e809d99cf051a90d3b16): MD contained unexpected handle path /keybase/private/jnm,teenamariemelton@facebook (/keybase/private/jnm,tm2 -> /keybase/private/jnm,tm2) (/keybase/private/jnm,teenamariemelton@facebook -> /keybase/private/jnm,teenamariemelton@facebook)
```

Log ID: 91cecdf17ef38fee7b69671c

**Comment by strib** [comment]
@JeffMelton: thanks for the detailed report.  It looks like user `tm2` still has a problem with their facebook proof:

```
$ keybase id tm2
▶ INFO Identifying tm2
✔ "teenamariemelton" on facebook failed: Could not find proof markup comment in Facebook's response (code=106)
```

And it seems like your folder/conversation with the user actually used that facebook identity as the original handle (I think -- let me know if that sounds wrong).  I think if the facebook proof gets fixed, the chat should be fixed as well.

**Comment by JeffMelton** [comment]
@strib Yep, that was it. Her ID showed green, but with an "IGNORED" badge, in my GUI clients. I didn't think about looking at it with the command line client. Thanks!
