### ISSUE TITLE
Keybase public folder inaccessible in both client and keybase.pub website

### ISSUE THREAD

**Issue by Myl0g** [keybase/client#11108]
Beginning today, accessing my keybase public folder both in my filesystem and on [keybase.pub](https://keybase.pub) gives "Input/Output error" and "Not found" respectively.

In other words, it looks like my public folder disappeared overnight (my username is myl0g).

Any ideas? Thanks in advance for any help you can provide!

my log id: f8f1c54dab78de16dfc3dd1c

**Comment by strib** [comment]
We had a bug in yesterday's Linux release (the one you're running) that didn't deal with revoked devices correctly.  Try upgrading and it should work.  I can see it from my computer.

Not sure about keybase.pub -- @jzila any chance you upgraded keybase.pub to yesterday's release?  If so, can you try upgrading it to today's please?

**Comment by jzila** [comment]
Rotating keybase.pub now.

**Comment by jzila** [comment]
Should be working again.

**Comment by Myl0g** [comment]
Serves me right for not upgrading before asking; totally slipped my mind.

Thanks for your help!
