### ISSUE TITLE
Our team is Open, but it seems nobody can join it

### ISSUE THREAD

**Issue by Agorise** [keybase/client#11135]
Our team is set to Open, and we are not requiring anyone to request access to it either (that flag is set to Yes in the cli). 
 
https://keybase.io/team/agorise 
 
Also, we have two (2) group Admins, but only one of them is showing on the Keybase website above as you can see. 
 
The main admin (kenCode) runs keybase on his phone and linux mint pc (Keybase GUI Version: 1.0.45-20180319160058+429a547345), both.

**Comment by maxtaco** [comment]
Can kenCode please do ‘keybase log send’ from his Linux mint pc?

Cc @zapu

**Comment by Agorise** [comment]
------------
Success! Your log ID is:

  04f9e7f2b5fc49435bf15e1c

Here's a URL to submit new bug reports containing this ID:

  https://github.com/keybase/client/issues/new?body=[write%20something%20useful%20and%20descriptive%20here]%0A%0Amy%20log%20id:%2004f9e7f2b5fc49435bf15e1c

Thanks!
------------

**Comment by zapu** [comment]
Would it be OK if I reached out to kenCode thorugh Keybase chat? We might need more logs that `log send` did not include.

**Comment by Agorise** [comment]
Please do @zapu :)

**Comment by maxtaco** [comment]
@Agorise go to the team settings panel and then uncheck "Ignore requests to join this team".  I think that should solve the problem.  It's a bug that we allow that box to be checked when the team is open, we'll work on that.

**Comment by Agorise** [comment]
aaaah, I found it. i had to un-check the "make this an open team" box first. then, i could uncheck the "Ignore requests to join this team" box, and then i re-checked the "make this an open team" box and clicked on the save button. can you guys test it out for me real quick? pleeeeze :) just see if you can join the Agorise team now.. https://keybase.io/team/agorise 
 
MUCH appreciated for your awesome help guys, thank you :)

**Comment by Agorise** [comment]
nm, i just saw the message from @maxtaco just now in the agorise group, thank you guys!! GO GO KEYBASE WOOHOO!!!!! :)  
Peace, Love, and Agorism.
