### ISSUE TITLE
Lost access to my private folder, please reset it?

### ISSUE THREAD

**Issue by zack6849** [keybase/client#11137]
I've had some fumbling with keybase and it's keys before, and am not surprised i've lost access to my private folder, but would like to fix that so I have access to it for private git repositories.

If you could reset the folder, that'd be great

my log id: d725effddb9027f59d169b1c

BEGIN KEYBASE SALTPACK SIGNED MESSAGE. kXR7VktZdyH7rvq v5weRa0zkV0lsft qp5ryDfYZW6KG6M vhbgLsVIS9ZddD2 X7E5rma4TpIMwu5 we8NXSZ1iHT74TI wO7QfvcnToDRZ7r uUINqrHoDPXFAUJ TB4B7RwCArL9ujf y0m4QqLcVt5o64P erzsyf8unl3OuBm qlVGKm3YEIfLnYt sZVf6x7WpSEvzGK H7NO9em0uigoMs3 V0byX7eRpUDpAvh q8cHiU77bsZL0HW fEk3GxgPJMW9Rup qmfRMYKMgLpVxNO v2Bd2Orh2EFRJsW 1r6oRuOrK1acHdb x1GsAxdZBsGuLZD HRjSMRsynZc0oer E. END KEYBASE SALTPACK SIGNED MESSAGE.

I would have reached out via a support form but couldn't find one, and emailing someone directly at keybase for support seemed like the wrong way to go about it

**Comment by strib** [comment]
I reset the folder.  Please check it out and close this if everything seems ok.  (Might require a Keybase restart.)

**Comment by zack6849** [comment]
Thank you!
