### ISSUE TITLE
Custom or more-fleshed-out emoji support?

### ISSUE THREAD

**Issue by alien35** [keybase/client#11169]
I realize emojis are not at the top of anyone's radar, but they're pretty essential for people moving away from Facebook.
There are a couple of options:
1. Use emoji-mart's custom emoji API features and curate the packs.
2. Enable 'renderable links' in which image files in your keybase public folder can be pasted as links in a chatroom and render. 

I currently have an image collection in my public folder. I can drag-and-drop the images from the folder onto the chatroom, but with time it'll clog the database with a large amount of duplicate data. A renderable link would just have enough data to point to the source of the file and then render whatever's in the source. Naturally security considerations would have to be taken into account for that to happen, in which case option 1 is easier/potentially-safer.

Also, I know an artist who'd be happy to make a pack.

**Comment by ataner** [comment]
I support the idea of custom emojis. I understand there are a lot of features that deserve priority, but many teams love their custom emojis (and gifs), it would be a very welcome feature.

**Comment by apiontek** [comment]
Stickers are great, but one of the things both slack & mastodon support is adding custom emoji, that behave the same way as regular emoji. Personally I feel that is distinct from stickers. Facebook supports both stickers and emoji, and Matrix.org recently got stickers in the riot/synapse ecosystem, but it's not the same as custom emoji, which is acknowledged in their [proposal document](https://github.com/matrix-org/matrix-doc/issues/1256).

Stickers are also a fine feature but they're not the same as being able to define custom emoji. My slack team makes heavy use of custom emoji, which have found their way to my mastodon instance as well. It may seem silly but I'm pretty unwilling to switch to any chat platform that doesn't have them, at this point :)

**Comment by dabura667** [comment]
I think stickers = you can only send them one at a time. not in the middle of sentences.

emoji = literally Japanese for "picture letters" which implies being mid-sentence. Thus they can be inserted in mid-sentence.

**Comment by chg20** [comment]
This is one of those technically uninteresting, but socially crucial issues.  Per group emoji/sticker sets would address a big gap w/ Slack.

**Comment by Avamander** [comment]
Just pinging this so that the feature gap between Telegram/Slack and KB is addressed. People care more about not losing features than getting a few new ones.

**Comment by fleish** [comment]
I'll add another vote to the pile for this feature

**Comment by robrigo** [comment]
Aye! This is important for team culture. Would love to see this happen.

**Comment by cdacamar** [comment]
+1 to this feature.  There are some conversations that are simply incomplete without the accent flare of custom emojis.

**Comment by xkr47** [comment]
Also crucial to be able to use custom emojis (or what you want to call them) in reactions!

**Comment by tstrijdhorst** [comment]
+1 would be great to have custom emojis

**Comment by ChrisRenfrow** [comment]
+1 My friends and colleagues coming from Slack miss this feature greatly. We simply must allow the [cult of the party parrot](https://cultofthepartyparrot.com/) to expand to Keybase! :smile:

**Comment by bnjmnjns** [comment]
+1 :)

**Comment by yincrash** [comment]
It's in v5.4.0- https://github.com/keybase/client/releases

**Comment by Avamander** [comment]
v5.4.0 has custom reactions, not the same thing as the "stickers" OP described.

**Comment by klue** [comment]
How do you delete a custom emoji?

**Comment by Wyntuition** [comment]
> How do you delete a custom emoji?

It doesn't appear to exist yet, https://github.com/keybase/client/issues/23929

**Comment by ChrisRenfrow** [comment]
> > How do you delete a custom emoji?
> 
> It doesn't appear to exist yet, #23929

This seems to only apply to the CLI, keybase-gui supports the removal of emojis as of v5.4.0. 

To answer @klue, under Team Info > Emojis you should see a contextual menu button (three horizontal dots) next to each emoji, select that and then select 'Delete emoji".

**Comment by klue** [comment]
Thanks Chris. I was actually able to delete it via the
`keybase chat emoji-remove <conversation> <alias>`
command. Nice to see it's possible via the UI as well.

**Comment by Wyntuition** [comment]
I can't seem to delete any. I added a few custom emojis not paying attention to what channel I was in, and later tried deleting them with the cli - no error but they're still available in any channel. I went in a few channels to Team Info > Emojis and there are none available.

**Comment by xkr47** [comment]
@alien35 happy with the result? ready to close?

**Comment by alien35** [comment]
Looks awesome! @xkr47
