### ISSUE TITLE
My main keybase PC detected as "new device" but it is not the case

### ISSUE THREAD

**Issue by ThierryIT** [keybase/client#11165]
Hello,
Yesterday, I have reinstall Keybase on my Windows platform.
Things have been configured and it was working, except for my folders pb.
This morning, I start Keybase:

1) login
2) Already in keybase
3) Enter my username
4) Which keybase install would you like to connecxt with ?
5) If choosing my Windows PC: Set a public name for this device
text in code etc.
Why does it asked me this has it was a new device ?

I cannot log in

Ideas ?

**Comment by dabura667** [comment]
When you uninstall the windows, your private key is gone, so you can no longer login with that PC without re-provisioning it as a new device.

**Comment by zanderz** [comment]
The device keys are stored in `%localappdata%\Keybase\[keybase username].mpack`. If you logged in under a different account or deleted those files somehow, Keybase will think it is a new device. Sending logs with `keybase log send` is always preferred. In this case it likely would just show those file not found, but we'll take a closer look.

**Comment by ThierryIT** [comment]
working thx !
