### ISSUE TITLE
Getting a Keybase Install Error when upgrading

### ISSUE THREAD

**Issue by kfl** [keybase/client#11195]
I just tried to upgrade my keybase. After giving my password for upgrading the keybase filesystem to allow multiple users under MacOS X I got an error.

My log id: c11d4b90ffa0f22026a28f1c

**Comment by strib** [comment]
Thanks for the report!  This is likely a dup of #11197 -- if everything seems to be working, you can disregard the error as harmless.  Sorry for the inconvenience.
