### ISSUE TITLE
Should not be suggested to consider following myself

### ISSUE THREAD

**Issue by rex4539** [keybase/client#11217]
Keybase 1.0.47-20180403021644+19ebebe08b

![screen shot 2018-04-04 at 19 11 50](https://user-images.githubusercontent.com/227442/38320214-a30ea266-383c-11e8-808c-de57ca8c9f99.png)

[Logs.zip](https://github.com/keybase/client/files/1876635/Logs.zip)

**Comment by strib** [comment]
cc: @malgorithms

**Comment by malgorithms** [comment]
thanks should be fixed (although you might have this cached in your app for a bit)
