### ISSUE TITLE
KBFS not working / showing up

### ISSUE THREAD

**Issue by Sakul6499** [keybase/client#11226]
[First of all I probably messed up the feedback dialog ...]
I can't open KBFS.
The drive is not showing up, but my C drive is now called "keybase (C:)" with the KBFS folder logo.
Keybase tells me, that Dokan is running (it got a PID), but also prints out "KBFS Error!" and sometimes something like "Drive cache isn't enabled" (or something like that? the message gets canceled almost immediately with "KBFS Error!".

In addition, I tried gathering some more information:
 - (re)running `C:\Users\Sakul\AppData\Local\Keybase\kbfsdokan.exe -debug -log-to-file -mount-from-service` doesn't help / does the same thing
 - there is no drive in CMD (or WSL)
 - Windows version is: 1709, build 16299.309 (must be one of the newest versons), but this also apperas on my second machine with Windows Insider (1803, 17133.1)
 - Keybase is fresh installed with the latest version (1.0.47-20180403195507+d3b2e30)
 - KBFS has a different version (1.0.2-20180403195507+eecab64) [I don't know if it's supposed to be?]
 - Windows is also freshly installed
 - There is no other drive, that is blocking 'drive k'

my log id: 414461455b19b3b3bde9ec1c

**Comment by zanderz** [comment]
Sorry about that, we shipped a bad update today and will have a fix soon. Meanwhile, if you go to the CLI and do `keybase kbfsmount set K`  and reboot, it should work again.

**Comment by Sakul6499** [comment]
Thanks a lot, especially for the fast answer!
That worked like a charm :)
