### ISSUE TITLE
Stuck on loading screen

### ISSUE THREAD

**Issue by drphelps** [keybase/client#11235]
High Sierra macOS 10.13.3 (17D102) 
Keybase Version 1.0.47-20180403021644+19ebebe08b (1.0.47-20180403021644+19ebebe08b)
my log id: ebea0c434246feec318f9b1c

`keybase login` errors out with:
`▶ ERROR There were multiple errors: dial unix ~/Library/Group Containers/keybase/Library/Caches/Keybase/keybased.sock: connect: no such file or directory; dial unix /Users/dphelps/Library/Caches/Keybase/keybased.sock: connect: no such file or directory`

Related to https://github.com/keybase/client/issues/10681

**Comment by maxtaco** [comment]
Never seen this one before. Your leveldb got corrupted.  

1. Shut down keybase: `keybase ctl stop`
1. Nuke your level dbs: `rm -rf ~/Library/Application\ Support/Keybase/*.leveldb`
1. Start your app again. LMK if this works..

**Comment by drphelps** [comment]
That got me going again. Thanks for the prompt reply.

**Comment by maxtaco** [comment]
Great, glad it worked.  Troubling though, I really wonder why that happened....

**Comment by maxtaco** [comment]
This is the root bug it seems: https://github.com/syndtr/goleveldb/issues/201

**Comment by sshanky** [comment]
Same happened to me today on Mojave. The solution above worked for me.

**Comment by henrik242** [comment]
Same happened to me today on Catalina with Keybase 5.6.2-20210202191343+d72cc00cd3.  @maxtaco's fix worked fine.

**Comment by jcalfee** [comment]
Same here, but on Linux I do not see any level db files `*.leveldb` anywhere under /opt/keybase or ~.config/Keybase .. Is there logging?  I had no choice but to move a backup to another machine.

**Comment by xdc0** [comment]
Happened here on macOS, Sonoma 14.3.1
