### ISSUE TITLE
Issues with run_keybase with keybase-bin AUR package.

### ISSUE THREAD

**Issue by WolfieWolfie** [keybase/client#11238]
After the few updates that I've seen happen to Keybase in my AUR helper (Trizen, if that matters), I noticed that I have kernel updates (or something that requires remaking of the kernel image (this time it was mkinitcpio-busybox))  and Keybase-bin updates. Even if these aren't related to my issue, which I think they are.

Anwyays, installing Keybase finishes with no errors in pacman or during the package build process. Running run_keybase after the upgrade results in ```▶ ERROR dial unix /run/user/1000/keybase/keybased.sock: connect: no such file or directory```. Running it again results in Keybase restarting. 

Log ID: eb17c37c572f98b904e3011c

I reinstalled mkinitcpio-busybox to see if it would cause it to happen again, but it didn't, perhaps it's due to the upgrade or the kernel images changing.

Edit: It might be worth noting I did not restart after the kernel images updating, and still haven't.

**Comment by strib** [comment]
cc: @oconnor663 -- any ideas why the service wasn't running?

**Comment by NobbZ** [comment]
I got this on arch as well, first time was 2 or 3 days ago without any kernel related upgrades.

Some systemd component has been updated recently though. also I am able to observe the missing path for more than only one time. I had to try 4 times yesterday.

Also I noticed that the GUI switches to some 'unable to connect' screen shortly after running a failing `run_keybase` and recovers from this within  a second.

**Comment by oconnor663** [comment]
I've seen it myself a couple times, not sure of the cause yet. If anyone gets a consistent repro, please let me know.

**Comment by eli-schwartz** [comment]
> I noticed that I have kernel updates (or something that requires remaking of the kernel image (this time it was mkinitcpio-busybox)) and Keybase-bin updates.

The two are not related at all. The initramfs image regeneration is triggered in order to update the busybox binary inside the initramfs, but this hardly causes your running system to conk out... nor would kernel updates in general cause this. (The only thing that kernel updates without an associated reboot can cause in the way of issues, is the inability to modprobe new modules that need to be used for the first time in that boot session.)

**Comment by heronhaye** [comment]
This is odd, I don't the the kernel updates are the issue here. We added some delays around the restart, please update, try again and make a new issue if you still have trouble!
