### ISSUE TITLE
It should not be possible to chat with yourself

### ISSUE THREAD

**Issue by rex4539** [keybase/client#11243]
Keybase 1.0.47-20180404193753+38f952ce5b
macOS 10.13.5 (17F35e)

Reproducibility: always

Prerequisites:
You are a member of a team.

Steps:
Teams -> Select a team you are a member of -> Find yourself in the members list -> Click on the chat icon on the right

What happened:
You are able to chat with yourself.

![screen shot 2018-04-05 at 18 10 11](https://user-images.githubusercontent.com/227442/38374824-607a4c5e-38fd-11e8-8a90-ed1c1373432f.png)

Expected result:
The chat icon does not appear for yourself in the members list.

**Comment by 5h4d0ww0lf** [comment]
why? Just upload message signed by you and encrypted for you? btw cli allow you much more than gui.

**Comment by TheZ3ro** [comment]
This is useful for an online encrypted notepad.

Anyway, much simpler:
From the "Chat" start a new conversation, search for your nickname, send a message and you have a chat with yourself

**Comment by rex4539** [comment]
This is a bug and should be fixed. There is no sane use case here :)

**Comment by rex4539** [comment]
Are you a UX person by profession? No offense but I don't think so :)

You may think it's a valid use case but I argue it is not.

For example, if Keybase wants a notepad feature they could develop one. But they aren't.

This is a bug. Not much to be said here :)

**Comment by rex4539** [comment]
@maxtaco @malgorithms @cecileboucheron What are your thoughts on this?

**Comment by TheZ3ro** [comment]
So you are a UX professional but not a crypto one, I see (no offense :)

What is the "bug"? Being able to encrypt a text with a key that happen to be my own? 

From the keybase crypto/chat docs [https://keybase.io/docs/crypto/chat] 
> When Alice sends a message to Bob, she uses the same keys that she would use to save a file in /keybase/private/alice,bob.

Here you can read about Home Directories [https://keybase.io/docs/crypto/kbfs], that use the same key as the self-chat.
Home Directories are a special case of a private group formed by 2 member that are the same user: for example `/keybase/private/alice,alice` (that use the same encryption key as `/keybase/private/alice`)

The UX here is just fine, if you open a new conversation with yourself and click the "Share" button (top-right corner) the `/keybase/private/<username>` folder opens, that is exactly your private folder from "Files".

-----

Other examples within keybase but with PGP messages:
- login into keybase.io, click on your avatar on top right corner, now you are in your profile page and you can see the PGP Encrypt and the Keybase Chat button.
- click on the encrypt icon on the top-right corner in keybase.io website, search for your user, encrypt a message

----

IMHO: intended feature.

Have a nice day

**Comment by malgorithms** [comment]
It's an intended feature. I personally use it often. If anything, I think we make it too hard to do.

I often do things like this from the command line:

```
keybase chat send chris "some random note"
# or:
shasum somefile.txt | keybase chat send chris
```

I understand why it might feel like a bug, but I think the simple answer is that it's harmless for people who don't want it, and helpful for people who do. like emailing yourself or iMessaging yourself (both possible)

**Comment by rex4539** [comment]
If the boss it's an intended feature, I accept it (although I strongly disagree) :)

**Comment by jaysonvirissimo** [comment]
Example sane use case: you want to get a file from your phone to your laptop, but you don't have a compatible connector and you don't trust the local wireless network (which is common in coffee shops, etc...).
