### ISSUE TITLE
client keeps on opening on startup even after removing shortcut from startup

### ISSUE THREAD

**Issue by joestafford** [keybase/client#11242]
This is undesired behavior.  I am happy for the keybase client to run in the system tray however I don't like having a new "facebook here's your friends list" window open every time I start up my computer.

Keybase GUI Version: 1.0.47-20180403200126+d3b2e30

**Comment by maxtaco** [comment]
This sounds like a regression. CC: @patrickxb 

sorry about this

**Comment by maxtaco** [comment]
Actually @joestafford: why platform are you on?

**Comment by joestafford** [comment]
Windows 10 (Education) version 1709 OS Build 16299.309

**Comment by maxtaco** [comment]
Ok, cc: @zanderz

**Comment by joestafford** [comment]
Happy to provide any other info needed!  Previously I just removed newly created Startup Shortcuts, this time I disabled it via TaskMan Startup tab.  A desired feature would be a settings toggle in the application for startup behavior.

**Comment by zanderz** [comment]
There is a GUI control, under settings -> advanced. It toggles an entry under the `Run` registry key.
The startup shortcut is for the background processes - it can be removed, in which case the GUI will start them as needed, it just takes it longer the first time and filesystem access won't work.

**Comment by joestafford** [comment]
Afraid that is not the case for me:
![image](https://user-images.githubusercontent.com/9386650/38434830-cfdd1356-399d-11e8-873e-1a8e9732b7b0.png)
![image](https://user-images.githubusercontent.com/9386650/38434882-f74f9760-399d-11e8-9fd4-462838cc30d1.png)
![image](https://user-images.githubusercontent.com/9386650/38434901-073f3b76-399e-11e8-89b9-d2479d45dbc9.png)
![image](https://user-images.githubusercontent.com/9386650/38434911-103d16bc-399e-11e8-8db6-cfcfa5edf3f6.png)

**Comment by zanderz** [comment]
It's in the settings "tab", not the native menus. But you raise a good point - why shouldn't it be in the native menus too?
![image](https://user-images.githubusercontent.com/862397/38438338-0f7b11a2-398f-11e8-8588-6ded4d016300.png)

**Comment by joestafford** [comment]
because I had to manually pull the window down, huzzah!  
![image](https://user-images.githubusercontent.com/9386650/38438682-321b36be-39a9-11e8-8a08-b33c00fff45d.png)
How about either:  a)  force resizing the main application window just once upon client upgrade, or b) make the side menu scroll-able.  I never knew this new portion existed.  I feel like Fry when he discovered that Bender had a closet at the Robot Arms Apartments.  https://cs5.pikabu.ru/images/big_size_comm/2015-12_3/144978302417769378.jpg

**Comment by zanderz** [comment]
that's a bug I never noticed, thanks, will ticket it, thanks.

**Comment by heronhaye** [comment]
Should work on all platforms now in Keybase 5.0. Make a new ticket if it doesn't.
