### ISSUE TITLE
Can't change avatar on keybase.io

### ISSUE THREAD

**Issue by AugustoResende** [keybase/client#11266]
Error: "Sorry, your upload didn't work."

Chromium console: Error: Server failure: RPC error 200: Error: could not load file for sending to aws

**Comment by strib** [comment]
cc @malgorithms

**Comment by malgorithms** [comment]
Is this fixed now?

**Comment by AugustoResende** [comment]
yes

**Comment by koltigin** [comment]
The error started again.
I have a profile picture in mobile application, but it does not exist on the website. Interesting situation.
