### ISSUE TITLE
Debian Buster: run_keybase does not succeed

### ISSUE THREAD

**Issue by miwie** [keybase/client#11296]
Already created an account and added two (mobile, Android) devices. 
Installed the Debian package _keybase_amd64.deb_ (1.0.47-20180403160041.242bcf96eb) on a Debian Buster system. No errors so far. 
After installing I tried to run _run_keybase_ as suggested on the webpage.   
All I get is this error message:

```
error: Usage: Need either 0,1 or 2 arguments for setting values in config
error: Need either 0,1 or 2 arguments for setting values in config
```

Any hints what's going wrong?

**Comment by miwie** [comment]
Yes, `$XDG_RUNTIME_DIR` is set to `/run/user/1000`

**Comment by oconnor663** [comment]
I'm still not entirely sure where this error is happening. The obvious spot would be `keybase config set mountdir "$mountdir"`, except that I really don't think that variable can be empty.

@miwie could you make a copy of `/usr/bin/run_keybase`, and add this line near the top:

    set -v -x

The please rerun this copy of `run_keybase`. It'll print out a ton of stuff before (presumably) running into this error again. Could you please send us all the output?

**Comment by miwie** [comment]
Looks indeed like an error with `keybase config set mountdir "$mountdir"` but I don't know how to handle this.

[run_keybase-err.txt](https://github.com/keybase/client/files/1890548/run_keybase-err.txt)

**Comment by oconnor663** [comment]
Thanks for the logs. This is still super confusing! It really looks like that command should be valid. I wonder if you have a `keybase` binary that's shadowing the installed one, or something else surprising like that. Could you please show us the output of these commands?

- `dpkg -s keybase`
- `dpkg -L keybase`
- `which keybase`
- `keybase version`

**Comment by miwie** [comment]
Oops, the output of `which keybase` explains the error!
There has been an (very) old (unfortunately forgotten) installation in `/usr/local/bin` of `keybase`.
After deleting this everything seems to work.
Sorry for the trouble ...

**Comment by oconnor663** [comment]
![image](https://user-images.githubusercontent.com/860932/38570440-ddae59d8-3cbb-11e8-90c7-39d41cf8ebe2.png)

**Comment by xarses** [comment]
Also had problems trying to update from an very old version, really obscure error message. removing the old version fixed the problem.

**Comment by tom-dalton-fanduel** [comment]
I've also just encountered this.

**Comment by oconnor663** [comment]
The PR above adds a warning for this case in `run_keybase`.

**Comment by heronhaye** [comment]
@Flyingmana, what is the result of `which keybase` and `keybase version` for you? Also, which OS are you on and how did you install Keybase?
