### ISSUE TITLE
I have a team which I seem to be the only owner of, but I'm not a member

### ISSUE THREAD

**Issue by tlycken** [keybase/client#11299]
It's very possible that I created this team a while ago and now forgot about it, but the fact is that I see the team as having 0 members, but I'm also given the option to leave it. When I try, I'm given the message "You can't leave the team because you're the only owner."

Keybase GUI Version: 1.0.47-20180404145836+0fe66b9

**Comment by dabura667** [comment]
If it’s a subteam (with a period in it) it’s normal.

You can delete from terminal:

keybase team delete yourteam.yoursubteam

Deleted subteams can be remade, but deleted teams can not be remade (the name is lost forever.)

**Comment by tlycken** [comment]
It's not a subteam. Also, it seems that the team does have members, only not anyone visible to me.

**Comment by joannebester** [comment]
did you try adding yourself as a member again?

**Comment by tlycken** [comment]
I did not, but I managed to get it working again. Not sure how.
