### ISSUE TITLE
Adding new device hangs

### ISSUE THREAD

**Issue by sowbug** [keybase/client#11305]
Keybase GUI Version: 1.0.47-20180403160041+242bcf96eb

On new Ubuntu 18.04 beta 2 machine, install Keybase, run_keybase, enter username, select an existing working mobile device. Enter new device name. See QR code. On mobile device, scan QR code. Code seems to be read correctly. At this point both devices are doing nothing. The mobile device says to continue setup on the desktop, but the desktop is just waiting for the QR code to be scanned.

Tried about 10 different times, including entering the text instead of scanning the QR code.

**Comment by sowbug** [comment]
I didn't see the device appear anywhere, including the Device tab on the website, until I entered a paper key on the new machine. That worked.

I just sent the keybase log and referenced this issue.

**Comment by maxtaco** [comment]
Can you also send a log from the phone you were scanning a QR code with?

**Comment by lucaszanella** [comment]
same here

**Comment by maxtaco** [comment]
@lucaszanella  need way more info if I'm going to look into it. What's most helpful is a log sent from both devices.

**Comment by sowbug** [comment]
Just sent the phone logs. Sorry, would have sent sooner but it took me a while to find the feature in the app (feedback).

**Comment by maxtaco** [comment]
Thanks @sowbug. I'm seeing tons of network errors on your phone, was your network up at the time?

**Comment by sowbug** [comment]
I was at home on my usually rock-solid WiFi network, and I don't recall
anything being off. I had also tried several times on a Pixel C tablet and
saw the same thing -- just sent that log as well.

If both are complaining about network errors, then maybe something indeed
was squirrelly on my side.

**Comment by maxtaco** [comment]
Thanks @sowbug. Puzzling

@lucaszanella I just saw your log from the phone. Also Android, also showing network errors when posting provisioning info.

**Comment by wundrellama** [comment]
I was having the exact same problem.  Trying to add keybase on a Windows 7 machine. Tried connecting it through my android phone, and another machine running Arch Linux.  I get the exact same results that sowbug described.  Then I tried the process again, but removed the space that I had for the name of the new device and everything worked.

**Comment by lucaszanella** [comment]
I almost lost all my work (actually I have backups but not in git form), because whenever I tried to press 'backup paper key' it didn't work, both on phone and computer, and I suddenly lost my keybase on both computers, only this single phone was left. I was trying to do login in other ways now and discovered that I can add create a paper key and log into it. Now I backed this key and there's no risks anymore :)

**Comment by lucaszanella** [comment]
@wundrellama my device name had no spaces

**Comment by maxtaco** [comment]
Sorry all. It was a server outage. Should be fixed now.  Thanks for reporting and sorry for a bad experience here.

**Comment by queglay** [comment]
I'm seeing this currently, and it worked fine an hour ago.  I can't add an ubuntu device from a mac device.  if server outages cause it, I'd like to suggest that the device being added confirm the verification key was succesfully sent to the server (or failing if it wasn't).
