### ISSUE TITLE
could I please get a private folder reset!

### ISSUE THREAD

**Issue by one19** [keybase/client#11306]
Hi there! Been using keybase for a long long time. I moved computers about a year ago, and borked something with the private folder permissions. I've never bothered to figure out what until now, and now that encrypted repos are out, i'd love to give that a try (and therefore, need access to the private folder again)! Thanks so much!

my log id: 246f5288be99b7d9f0b3221c

**Comment by strib** [comment]
Hi @one19, yes I'm happy to reset the folder for you.  But for security reasons, if you want us to reset your folder, please run this command on a currently-valid keybase device, and substitute the current date and time where indicated:

```
keybase sign -m "<DATE_AND_TIME>: Please reset folder /keybase/private/werd119 because all the devices that have access have been revoked."
```

and post the results here.

**Comment by one19** [comment]
BEGIN KEYBASE SALTPACK SIGNED MESSAGE. kXR7VktZdyH7rvq v5weRa0zkDKtXYZ POJxDc1Uggxv3EO sfOEEkKO1eRyRyN ULpTukHHwDHqasL Aqg9DrxNXswbauk QJGdtJLj94dKHKs 3GY5v44Evt2E3Qy ZafjlcfTCxogalK lFs6rOeZUE0VRz1 M9O6SWE35qNuXeC KpoDSqxj7IBLVWk x5DSqXldXoATqHx pnVrRwre6x3Wqe9 TAWDmDnXxGYKxlm ija9xuOlBODijmX Cs0E7cYP3apAgTl DepPSx6rEciW1I6 oTd0tbkm74V5mpt a17FvYUCw1NavXu qN6KXf8UvHbJwrB SESYEGdDynMcxm7 k4Gq9T7BtM5mCp1 7QrRBhoVFmoCewR fJunDjmN7m. END KEYBASE SALTPACK SIGNED MESSAGE.

**Comment by one19** [comment]
sorry for the tardy reply!

**Comment by strib** [comment]
I reset the folder.  Please check it out and close this if everything seems ok.  (Might require a Keybase restart.)

**Comment by one19** [comment]
yay thank you!
