### ISSUE TITLE
keep rekeying

### ISSUE THREAD

**Issue by tkisme** [keybase/client#11318]
[keep rekeying]

my log id: 8f40f203e4375313cc6c251c

**Comment by tkisme** [comment]
related to #11291

**Comment by strib** [comment]
@tkisme I'm looking at your logs now, and the underlying issue is very different from #11291.  Can we re-open this?

**Comment by tkisme** [comment]
Confirmed,problem gone

**Comment by strib** [comment]
Great!  And I merged a permanent fix into master in keybase/kbfs#1543.  Closing again.
