### ISSUE TITLE
iOS client crashes on login attempt with complex password

### ISSUE THREAD

**Issue by onatbas** [keybase/client#11324]
I'm unable to login on the ios client. I have a very complex password with weird characters in the string so that might be it. 

Try this password and you'll get an app crash.
{6h22}--{=2e2}--{_ob5}--{7X-a}--{{g0G}--{715Q}--{d%33}--{71}
P.S.: This is NOT my password, doesn't reveal anything about my password, but it can reproduce the issue for me. 

It's an iPhone 6s.

**Comment by maxtaco** [comment]
We have a fix. Out soon. The UI on our last release is crashing for
passwords that are long.

Sorry for the inconvenience!!

**Comment by maxtaco** [comment]
Cc @chrisnojima who found the bug

**Comment by chrisnojima** [comment]
yeah we have a fix for this, it'll be in the next release. luckily (please reopen if this isn't true) the login actually works, so if you start back up it'll work.

**Comment by jafish** [comment]
I’m seeing a similar issue in the current version of the iPhone app (2.3) but it’s on account creation. I get past the username/email screen, attempt to paste in a complex generated passcode. Keybase accepts the paste (I see the masked password get pasted it) but then a second later it crashes.
