### ISSUE TITLE
Feature suggestion: Allow proving facebook identity using public contact information instead of posting

### ISSUE THREAD

**Issue by neil-orans** [keybase/client#11353]
Under 'Contact Information' on an individuals Facebook account, there is a field for PGP public key. This field can be made public so everyone/everything can see it. 

Perhaps, instead of requiring users to make a Facebook post (which is pretty undesirable IMO) to link/verify their Facebook and keybase account, you could have the user upload their public key to this field, and make it public so the API can scrape it.

Thoughts on this? Sorry if there was a better way to suggest this, I couldn't find a feature suggestion option on the website.

**Comment by 5h4d0ww0lf** [comment]
@neil-orans posting public key isn't proof that's why it is called public.
