### ISSUE TITLE
git push hangs

### ISSUE THREAD

**Issue by TheMRod** [keybase/client#11364]
``
Initializing Keybase... done.
Syncing with Keybase... done.
Counting and decrypting: 3 objects... done.
Preparing and encrypting: (100.00%) 3/3 objects... done.
Indexing hashes: (100.00%) 3/3 objects... done.
Indexing CRCs: (100.00%) 3/3 objects... done.
Indexing offsets: (100.00%) 3/3 objects... done.
Syncing encrypted data to Keybase: (0.00%) 0.00/19.20 KB... ^C934 /(100.00%) 19.20/19.20 KB... done.
``

This is using Linux and client 1.0.45. It worked OK earlier today, so maybe it's on the server side?

my log id: 62b4021814cb435ae1a7611c

**Comment by strib** [comment]
We had some downtime, things should be fixed now. Working better now?

**Comment by TheMRod** [comment]
Things were working great by the time I got home and started working on my project again. Thanks!
