### ISSUE TITLE
Login via device-to-device pairing flow

### ISSUE THREAD

**Issue by BigBlueHat** [keybase/client#11379]
I just setup Keybase desktop on another machine. While browsing the Settings area in the Desktop client, I clicked the "not like the others" Sign Out link--which immediately signed me out--despite it's being positioned in a list of "tabs." 😢 

Now, to login, I have to use a passphrase--which I currently can't recall.

However, I still have several auth'd devices--one which I just used a QR code from to setup this machine. Consequently, I'd like to do that flow again for authentication and avoid the passphrase.

Is that a thing that can be done?

Thanks!
🎩

**Comment by maxtaco** [comment]
Change your passphrase on one of other devices.  You can do so without your
current passphrase if the device is logged in.

**Comment by BigBlueHat** [comment]
Awesome! That did the trick. 😁 

Might be good to add that info to the "reset passphrase" info on the web site. Far less scary and option than "we'll send you and email to reset it and you'll loose everything." 😃 

Appreciate the help!
