### ISSUE TITLE
FileSystem Input/Output error

### ISSUE THREAD

**Issue by piotr-sokolowski** [keybase/client#11401]
Can't access files. No meaningful error, just Input/Output error. Makes Keybase completely unusable for work

my log id: 3d577292c622c9954572cf1c

**Comment by piotr-sokolowski** [comment]
BTW: https://mdserver-1.kbfs.keybase.io/ gives SSL error when opening in browser

**Comment by strib** [comment]
We had some downtime due to flaky hosted hardware.  Things should be back up now.  Let me know if they're not.  Sorry for the inconvenience.

**Comment by piotr-sokolowski** [comment]
Yes, it's OK now. Thank you for fast response
