### ISSUE TITLE
Can't open private KBFS files on ubuntu 16.04

### ISSUE THREAD

**Issue by nick-parker** [keybase/client#11403]
My kbfs files aren't accessible, I can see nickparkerprint as well as conversation specific nickparkerprint, foo directories under private, but clicking on nickparkerprint gives a loading symbol for a long time and eventually `Sorry, could not display all the contents of “nickparkerprint”: Error opening directory '/keybase/private/nickparkerprint': Input/output error`

my log id: 3c9b2095e8a5ffd43d0ec51c

**Comment by strib** [comment]
We had some downtime due to flaky hosted hardware.  Things should be back up now.  Let me know if they're not.  Sorry for the inconvenience.

**Comment by nick-parker** [comment]
Working perfectly now, thanks!
