### ISSUE TITLE
Cannot get into KBFS

### ISSUE THREAD

**Issue by taxborn** [keybase/client#11410]
So for a while now I have not been able to get into my KBFS files. I've tried uninstalling and reinstalling, logging out and logging back in again, to no avail.

I am on Arch Linux.

my log id: 4e85fa23ca0b7cdcdc02131c

**Comment by strib** [comment]
I see this in your logs:

```
30491 2018-04-14T17:41:14.757616-05:00 ▶ [DEBU kbfs start.go:37] 064 Mounting: "/run/user/1000/keybase/kbfs"
30492 2018-04-14T17:41:14.757643-05:00 ▶ [DEBU kbfs mount_interrupter.go:42] 065 Starting to mount the filesystem
30493 2018/04/14 17:41:14 mount helper error: fusermount: mount failed: Operation not permitted
30494 2018/04/14 17:41:14 mount helper error: fusermount: mount failed: Operation not permitted
30495 2018-04-14T17:41:14.760753-05:00 ▶ [ERRO kbfs mount_interrupter.go:52] 066 Mounting the filesystem failed: fusermount: exit status 1
```

For some reason your user (UID=1000) doesn't have permissions to mount `/run/user/1000/keybase/kbfs`.  I would guess either that user is not part of the `fuse` group on your machine, or somehow the permissions for `/run/user/1000/keybase/kbfs` were messed up.

**Comment by taxborn** [comment]
Alright, that makes sense, _kind of_. How would I go about adding those permissions?

**Comment by taxborn** [comment]
![Terminal](http://i.imgur.com/DHywJou.png)

**Comment by strib** [comment]
Does the command `usermod -aG fuse taxborn` help at all?  I'm not sure if this is a requirement on arch or not.

**Comment by taxborn** [comment]
It simply tells me this message:
`usermod: group 'fuse' does not exist`

**Comment by strib** [comment]
What does this command say:

```
ls -l `which fusermount`
```

**Comment by taxborn** [comment]
That seems to fix it! Thank you for your help.
