### ISSUE TITLE
source build

### ISSUE THREAD

**Issue by jcalfee** [keybase/client#11463]
Do you plan to have reliable source builds in the future?  That is the best way I know of to verify that the binaries match the code.  I don't necessarily need an installer.  I'll be running keybase on my desktop directly from a docker image.  Any tips are appreciated..

>Warnings
>
> We'd love you to read our source code.
>
> But -

**Comment by eli-schwartz** [comment]
Keybase is already very much able to build from source, not sure what you mean? :/

If you're referring to https://reproducible-builds.org/ then the keybase and kbfs binaries seem to be reproducible according to https://tests.reproducible-builds.org/archlinux/archlinux.html (we're the only distro currently packaging it I think).

If you're referring to the warning in the README, that just says the git development sources are unstable and you should use the tested releases instead. This is... not an uncommon sentiment in the software world.

**Comment by jcalfee** [comment]
Yes reproducible builds.  Would make my life so much easier!

Site appears to be down: https://reproducible-builds.org/

I'll re-check this link later.. thank you
