### ISSUE TITLE
notification stuck

### ISSUE THREAD

**Issue by maartenbusstra** [keybase/client#11489]
I can't seem to get rid of my last notification. Help, my OCD is killing me.

my log id: 878b46f7f3c8ead3d1fd8c1c

**Comment by shellster** [comment]
I should clarify on mine then. I have not experienced the issue on Android.

**Comment by maxtaco** [comment]
cc @buoyad and @chrisnojima 

we're changing this right now.  but if you are on the home page (with the "consider following..." section, etc), and then you click to a different tab, it should clear the badge.

it won't clear the badge if you start on the home screen, then click on the new follower, then click to a different tab (which we're fixing)

if i'm wrong lmk

**Comment by maartenbusstra** [comment]
It appears to have been fixed! Can't confirm for others, but I'll close this issue.
