### ISSUE TITLE
Files not synching in team folder

### ISSUE THREAD

**Issue by mmattimoe** [keybase/client#11532]
Keybase GUI Version: 1.0.47-20180410052738+f705a9510f

Our files are not synching in the team folder between users even after waiting 24 hours.

**Comment by strib** [comment]
@mmattimoe: please run `keybase log send` on both devices that don't seem to be synced up, and post the resulting log IDs here.  I'll take a look and see what's wrong.

**Comment by mmattimoe** [comment]
I don’t know how to do that...

--

**Comment by strib** [comment]
What OS are you on?  If you can get to a terminal or command line, simply type `keybase log send` and hit enter.

**Comment by mmattimoe** [comment]
Mac OS High Sierra - just updated to the most recent one.

I’ve never been able to figure out how to get to the command line :(

--

**Comment by strib** [comment]
Click the magnifying glass that's usually in the upper right, and type "terminal" in the box.

**Comment by mmattimoe** [comment]
Ahhh, okay! I’ll try that in a little bit here.

--

**Comment by mmattimoe** [comment]
Sent mine, my colleague will send hers shortly.

It is happening with more than one of us, but it might be difficult for me to get everyone to send a log right now - we work from a mobile office most of the time.

Sincerely,

Megan K. Mattimoe, J.D.
Executive Director
Advocating Opportunity
1119 Adams Street, Second Floor
Toledo, Ohio 43604

Phone 855-855-1945, ext. 700
Fax 855-855-1945
Mobile 419-260-4217

Email mm@advocatingopportunity.com (mailto:mm@advocatingopportunity.com)
Website www.advocatingopportunity.com (http://www.advocatingopportunity.com)
Facebook www.facebook.com/advocatingopportunity (http://www.facebook.com/advocatingopportunity)
Twitter https://twitter.com/AOAdvocate

Confidentiality Statement: This electronic message contains information from the law firm of Megan K. Mattimoe, Esq., and may be confidential or privileged. The information is intended to be for the use of the individual or entity named above. If you are not the intended recipient, be aware that any disclosure, copying, distribution or use of the contents of this message is prohibited. If you have received this electronic message in error, please notify the sender immediately by reply e-mail.

**Comment by strib** [comment]
Thanks, your log ID was 98bc01429201267a616c391c (for the searchable record).

@mmattimoe I'm guessing from your log that someone else added a lot of data to the folder, and it's showing up for some of the other users but not for you.  It seems like your device hit what we call a _conflict_ with another device, some time ago -- probably two people tried to write to the folder at the same time  (Unfortunately, the logs you sent do not cover the time period where the conflict happened initially.)  Conflicts like this are common and our software usually resolves them automatically.

In this case, it seems like maybe network problems prevented your computer from resolving the conflict quickly enough, and now your device is stuck that way -- it's not seeing any new updates.  It's supposed to get out of this situation automatically, but there seems to be a bug.  So I can walk you through fixing it yourself.

1. If you have written any data to the folder that other people are not yet seeing, make sure you save it somewhere safe on your computer before doing the next steps -- at the end of this process, you won't see that data in your keybase folder either.
2. Quit Keybase using the "Quit" menu option.
3. Open the terminal, just like you did before.
4. Copy and paste this command exactly into the terminal, then hit enter: `mv "~/Library/Application Support/Keybase/kbfs_journal/v1/0120c1064b0e59d252ca499cd96b14ea6964-e1d57d010a8d40e2" "~/Library/Application Support/Keybase/kbfs_journal/v1/e1d57d010a8d40e2.bkp"`
5. Re-launch Keybase by double-clicking it from your Applications folder (or any shortcuts you might have on your desktop or task bar).

After this, you should see the same view of the folder that your colleagues do, and you can add any other files back to the folder.  Let me know if this works!

I'm sorry for the bad experience here, we'll work on making it better.

**Comment by strib** [comment]
(Oops, I had a mistake above, and just edited my comment to fix it, so don't use the steps from the email github sent you, please read the changes here: https://github.com/keybase/client/issues/11532#issuecomment-384381835)

**Comment by mmattimoe** [comment]
Terrific, thank you!!

No worries about the bug - it happens. We GREATLY appreciate having access to Keybase. It’s invaluable to us and our clients because it helps us keep them (and us) and their information safe.

Sorry I’m not great at coding stuff - I’m learning! Slowly... Hoping to find a boot camp or something around me.

Have a great day! If I get stuck I’ll email you.

--

**Comment by mmattimoe** [comment]
Dumb question: Do I include the "" in the command?

**Comment by mmattimoe** [comment]
I assume, yes...

**Comment by mmattimoe** [comment]
Oh wait, the full command is this, right?
mv "$HOME/Library/Application Support/Keybase/kbfs_journal/v1/0120c1064b0e59d252ca499cd96b14ea6964-e1d57d010a8d40e2" "$HOME/Library/Application Support/Keybase/kbfs_journal/v1/e1d57d010a8d40e2.bkp"

**Comment by strib** [comment]
@mmattimoe yes, and yes include the quotes.

**Comment by mmattimoe** [comment]
I'll run the logs again. I think I did something wonky...

**Comment by strib** [comment]
@mmattimoe you weren't supposed to see anything as the result of the command, but after you ran it and then restarted Keybase, your view of the folder should have been restored.  Was it not?

**Comment by strib** [comment]
@mmattimoe it looks like you didn't quit Keybase (step 2 above) before you ran the command in step 3.  Can you please try quitting it now, and then restarting it, and see if that helps?

**Comment by strib** [comment]
(New log: 1e8a11d856010b3adee35e1c)

**Comment by mmattimoe** [comment]
No, it was not. Should I do it again? I still cannot see what our other staff members see.

**Comment by strib** [comment]
Just try restarting Keybase  and/or your computer.  You shouldn't need to run anything else on the command line right now.

**Comment by mmattimoe** [comment]
I quit a few times. I'll try again. It removed everything I added but did not let me see what others added. Or did it just remove everything?

**Comment by mmattimoe** [comment]
Okay

**Comment by strib** [comment]
In the most recent log you sent, I didn't see any Keybase restarts, so maybe the Quit didn't work for some reason.

**Comment by mmattimoe** [comment]
Perhaps I tried to restart it too quickly. It looks different now. Checking with my colleague. Give me a couple of min.

**Comment by mmattimoe** [comment]
She can see everything I think. Yay!!! If our other colleagues cannot, I'll let you know. THANK YOU, THANK YOU!! 

If I need to add a lot of files is there a certain way I should do that? Or just copy in small batches? It may have been that two of us were trying to add files at the same time.
