### ISSUE TITLE
Message Deletion

### ISSUE THREAD

**Issue by CryptoForks** [keybase/client#11547]
In a conversation I see the option under "Message Deletion" to "keep forever."  

So if I have deleted a portion or all of a conversation, where do I find the portion that was deleted and kept forever?

ty

**Comment by 5h4d0ww0lf** [comment]
Isn't it under team chat? There can be set timer when all messages older are deleted so you can have team where are only messages kept one day.

**Comment by CryptoForks** [comment]
I see the timer and ours is currently set to keep forever. 

Something was deleted and everything above it was deleted to. 

I want to try and recover all of it.

**Comment by CryptoForks** [comment]
So where do I find the messages that were deleted?

**Comment by CryptoForks** [comment]
*deleted too

**Comment by strib** [comment]
The "Keep Forever" retention policy only applies to the automatic time-based deletion that we do on our server (or not).  If messages are explicitly deleted by the user, they are gone forever.

cc: @malgorithms @cecileboucheron for the possibly confusing text.

**Comment by CryptoForks** [comment]
Ok. Ty.  Future version rec. maybe to have option for undo deletions for certain timeframe.

**Comment by CryptoForks** [comment]
Or maybe make “delete” and “delete and everything above” farther apart on menu options bc easy to misclick.

**Comment by 5h4d0ww0lf** [comment]
@CryptoForks No, it won't be implemented because the main reason for deleting is that it's irreversible so nobody can recover what you deleted
