### ISSUE TITLE
Error 2512 (private folder)

### ISSUE THREAD

**Issue by NullFlex** [keybase/client#11588]
![image](https://user-images.githubusercontent.com/19937917/39400777-ff077e32-4b04-11e8-904c-59bdc40c0e67.png)

I can't seem to access my private folder. I do not mind if my **private folder** is wiped. I would prefer not to have my public folder wiped.

things I have tried:
-revoking current device and adding it back
-rekeying using paper key
-db nuke

nothing worked.

**Comment by strib** [comment]
@NullFlex if you do a `keybase log send` and post the resulting log ID here, I can try to figure out what's happening.

**Comment by NullFlex** [comment]
Done, 7fe0c40409fc798eb3b2e91c

**Comment by NullFlex** [comment]
Still doesnt work, any help?

**Comment by strib** [comment]
Looks like your private folder is only keyed for devices that have been revoked a long time ago.  
If you want us to reset your folder, please run this command on a currently-valid keybase device, and substitute the current date and time where indicated:

```
keybase sign -m "<DATE_AND_TIME>: Please reset folder /keybase/private/nullflex because all the devices that have access have been revoked."
```

and post the results here.

**Comment by NullFlex** [comment]
Odd glitch.

BEGIN KEYBASE SALTPACK SIGNED MESSAGE. kXR7VktZdyH7rvq v5weRa0zkKVRTOM WXgoweddR23eJP6 whMZUjz2hTVHFHJ KcBP1BLyqda0eZD kgIE6Oogc3zW87r BnIm1wUNTU64og3 qdyM1MlNWH7Bs3q LPz67UAL7xZfCAr vkwQBnOhcjMTIeI assDhhGBwIgzOGz aIoYGtRumGY0pzn KAlwoLwyCd0Sm1W m4a35eJhl6IxJh3 WLhALN6jMxJ5ld1 ReUj9p6Z85G7GYz TQMbrZa9nWcYEhT AqiNzdUrokqs0jt h1xClQNi59BqT5U n9yWdREFTzktEGf rO3WXNCEfHlndFH I1BMj47lRiDpspn 0CGyzD48Yj8AC50 aybxRb1a. END KEYBASE SALTPACK SIGNED MESSAGE.

**Comment by NullFlex** [comment]
@strib any updates?

**Comment by strib** [comment]
I reset the folder.  Please check it out and close this if everything seems ok.  (Might require a Keybase restart.)

For the record, here's the original saltpack message that got edited away, which I used for verification:

```
BEGIN KEYBASE SALTPACK SIGNED MESSAGE. kXR7VktZdyH7rvq v5weRa0zkKVRTOM WXgoweddR23eJP6 whMZUjz2hTVHFHJ KcBP1BLyqda0eZD kgIE6Oogc3zW87r BnIm1wUNTU64og3 qdyM1MlNWH7Bs3q LPz67UAL7xZfCAr vkwQBnOhcjMTIeI assDhhGBwIgzOGz aIoYGtRumGY0pzn KAlwoLwyCd0Sm1W m4a35eJhl6IxJh3 WLhALN6jMxJ5ld1 ReUj9p6Z85G7GYz TQMbrZa9nWcYEhT AqiNzdUrokqs0jt h1xClQNi59BqT5U n9yWdREFTzktEGf rO3WXNCEfHlndFH I1BMj47lRiDpspn 0CGyzD48Yj8AC50 aybxRb1a. END KEYBASE SALTPACK SIGNED MESSAGE.
```

**Comment by NullFlex** [comment]
Very nice. Works fine, thanks for helping.
