### ISSUE TITLE
Why does sig/post_auth need the private key to be registered on Keybase's servers to be used for verification?

### ISSUE THREAD

**Issue by pchara20** [keybase/client#11590]
If the user signs the "auth" payload, isn't Keybase able to verify the identity without having an encrypted copy of the private key on their servers? 

Sorry if i misunderstood how this works, thank you in advance

**Comment by pchara20** [comment]
Can i use this if i don't have my private key hosted on keybase ?

**Comment by maxtaco** [comment]
Of course

**Comment by maxtaco** [comment]
A hosted private key is useless to us for the purposes of auth, because we can't decrypt it.  Plus, very few people use encrypted PGP storage, so it would be silly to build an auth mechanism around it.

**Comment by pchara20** [comment]
Oh, good!!
Another question, if i use my PGP key to sign the payload, should the UID field stay empty ?

**Comment by maxtaco** [comment]
No, the same payload is required whether using PGP or NaCl device keys.

**Comment by pchara20** [comment]
Thank you.
