### ISSUE TITLE
sig/post_auth call returns neither pgp nor kb sig: (Error: Error parsing PGP data: no header found, Error: bad base 64 string)

### ISSUE THREAD

**Issue by pchara20** [keybase/client#11605]
I have a JSON file with contents just as described here: https://keybase.io/docs/api/1.0/call/sig/post_auth

For fields UID and KID i used output by /userlookup call.
uid = them.id 
id= them.publickeys.primary.id

I signed the JSON file using keybase pgp sign -i file.json -o output
Then copied the contents of the "output" file as the "sig" parameter of the POST call to sig/post_auth.

The results i get are: 
{
"status": {
"code": 218,
"desc": "neither pgp nor kb sig: (Error: Error parsing PGP data: no header found, Error: bad base 64 string)",
"fields": {
"sig": "neither pgp nor kb sig: (Error: Error parsing PGP data: no header found, Error: bad base 64 string)"
},
"name": "GENERIC"
}
}

Is the mistake in the format of the PGP signature? (Maybe cause it has the newline character?)
Or are the ID and UID fields wrong ? 

Thank you in advance 

edit: fields   
"ctime": 1386537779,
    "expire_in": 86400,

remained as they were in the doc..

**Comment by maxtaco** [comment]
Can you paste the whole post?

**Comment by pchara20** [comment]
HEADERS
Accept: */*
Accept-Encoding: gzip, deflate
Content-Length: 962
Content-Type: application/x-www-form-urlencoded
User-Agent: runscope/0.1

PARAMETERS
email_or_username: pchara20
sig: BEGIN KEYBASE SALTPACK SIGNED MESSAGE. kXR7VktZdyH7rvq v5weRa0zkAh1HoF UaSWnQI39s1CrGI BPBloEmzPVPaHSD sRe60MkO4nmJsOc ZwArjdEmbOeLcHU aQefSwmnqetv2Fo lyzft8urZseio2f V2pyJg1nE10rDmI 2TadTkpk2NNpL41 FJVqv6t98nvrkOY zIjVfKn3q8Vws8Y vMQDVLBTurNaW2x P8QRzBucJ3X2NMt gCy7U7cJNA1WPrd Kwl8Y7emWBeyzJc QYmvbKro3eGLsLj lCM7dnwxm0KhWk8 CxeJwviORN2LcyZ mtA4V0D4Fs9DtJz gNzyhjipO3YmYGT UUWFGAyM9TJ1F0Y mAcgnjBNIqUKR9C NcYpfvQXmc9kwbI tVdsAUDYD8rJHd7 tShgSvPygx2gDmZ CmJmcFav6tDHuUO 1WJBG8IPk5QtIqv u5yM0C118zNkAwv lFJ9cv7dOH7FA0g x6gXm8MW1hukxAj YySDMYwlNl2Jp0B 7e7HX7B0udpIctu 7cayexRDZDEJbZp ksLl9O7cRbtjhBJ sErnJs5CJF2kGZn rGO8YrV4qO7R3rV 61ui7cRP1WKgldm GmcTyZALLVDkzSk pvqIFQaaFUtYczd OARqN9mUzPYbpqp xr5jAkqiTJdNtNL iF5kKw26X4TBWIc 7cRP1WKgld9OM3F etlPBkoPAgSJ8AQ MaX1fa4o5Rtzm7c JNA6EBRjDuNn8N5 okQdVWh4JPNfb51 ZHa3qj5ssO435hx 8TaI7YeTlvJMCfX BfgM4iffXaMPRei BJNXBGfbuGbY4Ps t7vaakfSRH9hfG1 JD7RRF. END KEYBASE SALTPACK SIGNED MESSAGE.

**Comment by pchara20** [comment]
I also tried with PGP signature, same result

**Comment by pchara20** [comment]
Im using website hurl.it to create the POST request.
I add sig and username in the "parameters" section

**Comment by pchara20** [comment]
This is the JSON file in case you need it ..
[file.log](https://github.com/keybase/client/files/1964063/file.log)

**Comment by maxtaco** [comment]
you can't use saltpack here, you have to use PGP.  but event then, sounds like your PGP sig wasn't formatting properly and that newlines weren't being escaped? hard for me to know... the error message you got is seen when our servers don't see a valid PGP signature

**Comment by pchara20** [comment]
Is there anything i can do or try to solve this ?

I just pass the output of the > sign command to the POST request.

**Comment by maxtaco** [comment]
Can you post the complete script?

**Comment by maxtaco** [comment]
There's almost certainly a problem encoding your parameters (that's what that error message is saying) but you haven't provided enough information to figure out where your bug is.

**Comment by pchara20** [comment]
I have posted the JSON file above

**Comment by maxtaco** [comment]
I'll give you one hint that I can see, you're going to need `--data-urlencode` rather than `--data`.  For more ideas, use our Web site to see how we generate gpg/curl pipelines for people to use with their hosted pgp keys.
