### ISSUE TITLE
git repository storage usage

### ISSUE THREAD

**Issue by panmail** [keybase/client#11602]
Hi, is there a way to see how much storage have I consumed with my Keybase.io git repository?

**Comment by strib** [comment]
If you have file system drivers enabled for your Keybase installation (and you're on mac or linux), you can do `cat /keybase/.kbfs_status` and look for "GitUsageBytes".

**Comment by panmail** [comment]
I'm on Windows 10.
Can I use those cmds in Ubuntu on Win10 ?

**Comment by strib** [comment]
You should just be able to read `K:\.kbfs_status` from the terminal using your preferred Windows command line reader. Maybe `type K:\.kbfs_status`?  Sorry, I'm not a Windows expert.

**Comment by panmail** [comment]
so the K: drive storage usage and capacity includes those consumed by the
git repository?

**Comment by strib** [comment]
No, the `.kbfs_status` file is a special file that shows a bunch of stuff, including how much git storage you're using.  Regular file storage is listed as just "UsageBytes" in the file.

**Comment by panmail** [comment]
Hi Jeremy,

My K: on win10 PC is showing 0-bytes used but I definitely have some files
checked into my git repository.
I just want to see how close am I to my storage limits on Keybase.io?  But
sadly looking at K: doesn't give me that info.


On another note, I am experiencing difficulty pulling git with Git
Extension.
It can't get past the 'Fetch and decrypting objects', do you have any
suggestions as to what's causing this?

**Comment by strib** [comment]
@panmail Sounds like you're having some issues in general.  If you do a `keybase log send`, and post the resulting ID here, I can take a look.

**Comment by panmail** [comment]
where would I issue this command?
I'm running on Win10 on PC BTW.

**Comment by strib** [comment]
From the command prompt.

**Comment by panmail** [comment]
here is the output....
------------
Success! Your log ID is:
  d9a4bef0de025d019957201c
Here's a URL to submit new bug reports containing this ID:

https://github.com/keybase/client/issues/new?body=[write%20something%20useful%20and%20descriptive%20here]%0A%0Amy%20log%20id:%20d9a4bef0de025d019957201c
Thanks!
------------

**Comment by strib** [comment]
I sent you a private Keybase chat message with your git usage.

Did your `git pull` eventually finish?  I don't see any errors in your logs, maybe it just took a long time because of the amount of data you have?

**Comment by panmail** [comment]
Hi Jeremy,

Could you please help me with another issue?
I'm trying to install keybase on my Ubuntu 18.04 LTS following the steps
here <https://keybase.io/docs/the_app/install_linux>.
But I can't login, instead I get the following message.  I have also sent
in the log.
------------
Success! Your log ID is:
  3acd256e5571c9e2f1957b1c
Here's a URL to submit new bug reports containing this ID:

https://github.com/keybase/client/issues/new?body=[write%20something%20useful%20and%20descriptive%20here]%0A%0Amy%20log%20id:%203acd256e5571c9e2f1957b1c
Thanks!
------------

**Comment by strib** [comment]
Hi, please open a new issue for that with an appropriate subject, otherwise the right person won't look at it.  (I'm not the right person for login issues.)

**Comment by panmail** [comment]
ok, for sure I'll do that Jeremy.
sorry this sounds dumb...but could you point me to where I go to open a
ticket?

thx, John

On Wed, May 23, 2018 at 11:14 AM, Jeremy Stribling <notifications@github.com

**Comment by strib** [comment]
No problem, you should see a green "New issue" button at the top of this page.

**Comment by panmail** [comment]
I don't see the "New Issue" nor green button... this is what my screen
looks like in Ubuntu Chrome.



On Wed, May 23, 2018 at 11:18 AM, Jeremy Stribling <notifications@github.com

**Comment by strib** [comment]
You didn't post a screenshot, but the direct link is here: https://github.com/keybase/client/issues/new

**Comment by panmail** [comment]
Hi,

I had submitted a ticket to gitHub, but I haven't heard any replies.
Could someone please check into for me please?
https://github.com/keybase/client/issues/12174

Thanks, John

**Comment by strib** [comment]
I'll check out the other issue, but let's close this one out now.
