### ISSUE TITLE
Team member reset account, unable to rejoin team

### ISSUE THREAD

**Issue by robrigo** [keybase/client#11615]
I can't re-add a team member that reset their account to my team. The GUI says they are still on the team, so it doesn't allow me to invite them. If I try to accept an offer to join, or remove them from the team, the following error occurs:

GENERIC: ERROR CODE 218 - user "lovejoy" is not a member of team "eosdetroit" in method keybase.1.teams.teamEditMember at o.t (file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/index.bundle.js:1:392177) at o (file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/index.bundle.js:1:392483) at a (file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/index.bundle.js:1:391845) at t.convertToError (file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/index.bundle.js:1:392043) at _rpcClient.invoke.t (file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/index.bundle.js:1:349202) at file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/index.bundle.js:1:1012401 at e.t.Deferrals.e._call (file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/index.bundle.js:1:663274) at file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/index.bundle.js:1:663425 at s (file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/index.bundle.js:1:663054) at e.t.Deferrals.e._fulfill (file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/index.bundle.js:1:663384)

**Comment by maxtaco** [comment]
Can you do a `keybase log send`?

**Comment by robrigo** [comment]
Done @maxtaco. Log ID: e47ce266d9ff8e19ee85071c

**Comment by robrigo** [comment]
This user is reporting that he is receiving email notifications for the channels he can't access. So it seems that he is partially joined to our group, but can not actually chat in the team channels via the Keybase app.

**Comment by maxtaco** [comment]
@zapu  can you take a look?

**Comment by zapu** [comment]
Looks like it was fixed here: https://github.com/keybase/client/pull/11479

@robrigo you might have more luck from the CLI with `keybase team add-member` command as it uses slightly different code path.

**Comment by robrigo** [comment]
Great news, I was going to play with the API tonight, thanks for giving me
the proper command!
