### ISSUE TITLE
Mac app doesn't recognise device already registered

### ISSUE THREAD

**Issue by 42piratas** [keybase/client#11619]
I'm trying to log in to my mac app. After entering my username, the app asks me "Which keybase install would you like to connect with?". The notebook I'm using is listed there, as if it was a different device. Anyway, I choose a different device (my tablet, for example). Then the app asks me which public name I would like to set to the current device - and if I try to use its default name (which, as I mentioned, is already listed among the registered devices), it won't accept it.

I do not intend to set a different name. What should I do? 

Thanks!

**Comment by mctom987** [comment]
I'm having a similar issue, but on the same device. _THIS_ device is already added, but within the keybase app, it somehow desynced. I can't add the device, because the device already exists, and I can't add it as a new one, because it's asking me to login to the device I'm on to setup the device I'm on.

How do I say "No, this is the device that is setup" or something

**Comment by mctom987** [comment]
My log file: 395cfed4578e9d60528be11c

**Comment by 42piratas** [comment]
Would appreciate any help, as I'm currently unable to use the app in my main device.

**Comment by maxtaco** [comment]
We've only ever had an issue here if you blasted away the Keybase config and secret keys. Is that a possible explanation?  If you blast away your config.json, then there's no way for the software to recognize a device as "registered", it'll just look like a new device.

**Comment by 42piratas** [comment]
@maxtaco what I can say for sure is that I haven't deleted either the app or any related file myself. Anyway, trying to be more practical, how to debug/fix?

**Comment by maxtaco** [comment]
Do a `keybase log send`.   Also give me some vague time frames. When did the work app, and when did it fail to recognize the current device.

**Comment by 42piratas** [comment]
@maxtaco Log ID b6dfcb35e3ce509062cef61c

I can't think of any specific event related to the time frame in which the app stopped recognizing my main device. It was working fine, and simply one day (about two weeks ago I'd say) t wasn't anymore. That said, I'm always installing and updating general software and environmental stuff related to Python and also to Ethereum, but I don't remind of having changed anything related to Keybase.io (of course, I could be wrong).

Thank you in advance for your help.

**Comment by maxtaco** [comment]
@42piratas your best bet is to pick a different device name. We don't allow device reuse, and the previous device with that name is gone since the keys and config file appear wiped.

**Comment by 42piratas** [comment]
Thanks!

**Comment by 42piratas** [comment]
@maxtaco is there any to revoke a device from my account in keybase.io rather than from the device itself?
