### ISSUE TITLE
Smaller (or less frequent) updates

### ISSUE THREAD

**Issue by smhg** [keybase/client#11696]
Would it be possible to shrink the size of the Keybase client's updates? Or, if not, to update Keybase less often?

The Ubuntu client is updated _a lot_ (through package repo). At between 50MB and 100MB this is eating a good amount of monthly bandwidth. When you have a data cap, you basically have to choose between not updating or uninstalling.

**Comment by abitrolly** [comment]
Some `dpkg` or incremental updates would be very welcome for Fedora.

**Comment by MartinX3** [comment]
I can confirm, that the update frequency is disturbing.
And if I ignore them, I miss important system updates, because my updater always notify me about an update....

I would like, if you only release the github releases via the repo.
Not the nightlys.
