### ISSUE TITLE
Now I want to export my private key and save to your server

### ISSUE THREAD

**Issue by kmahyyg** [keybase/client#11690]
But I choose not to export the private key at the very beginning, I checked you document but still don't know how to do.

**Comment by kmahyyg** [comment]
Already uninstalled and deregistered

**Comment by ctd1500** [comment]
Well, your profile still exists, so you could certainly reinstall. 
Anyway, what you were looking for is the edit link on the profile page next to your key.
There you can export keys like this:
![export](https://user-images.githubusercontent.com/2068060/40219811-cc17df7c-5a2b-11e8-936f-0f30279c6949.png)
