### ISSUE TITLE
Error code 218: No such handle in method keybase.1...

### ISSUE THREAD

**Issue by ACBullen** [keybase/client#11729]
Opened keybase to this error: ```Error code 218: No such handle in method keybase.1.SimpleFS.simpleFSWait```

 Seems like something has gone wrong with displaying the file system information. I can still access the files via Finder once they've been decrypted, but I find it concerning. Running OSX High Sierra screenshot below
![screen shot 2018-05-08 at 11 01 14 am](https://user-images.githubusercontent.com/25515614/39774500-e0841260-52af-11e8-957d-cd4f50c05080.png)

**Comment by maxtaco** [comment]
Can you run `keybase log send`?

Cc: @jzila / @songgao

**Comment by ACBullen** [comment]
Yes, sent. Do you need the log id?

**Comment by maxtaco** [comment]
It's here: 5c47e4758c7553a17222961c.  We'll take a look, thanks!

**Comment by songgao** [comment]
Whoa first Files bug! Looking ...

**Comment by songgao** [comment]
Looks like somehow the app didn't fully restart. The frontend is running the new version, but the service and KBFS daemons are still from April. @ACBullen would you mind try quiting the app and try again? After the app is quit, please do `ps aux | grep -ie 'keybase\|kbfs'` in command line and see if there's any Keybase processes hanging around.

**Comment by songgao** [comment]
In fact, if you haven't done it, would you mind sharing the output of `ps aux | grep -ie 'keybase\|kbfs'` before quiting the app?

**Comment by ACBullen** [comment]
I shut things down and then restarted the application, but the error still appears. Grabbed output from this time:
```
root             28125   0.0  0.7 558499876 122188   ??  S    10:53AM   0:00.54 /var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T/8051E64E-9B53-4FFF-A279-73F686F5B601-1586-0000557C1B36D644/keybase-redirector /keybase
alexb            22914   0.0  1.3 558546424 213032   ??  S    Fri07PM   0:41.91 /Applications/Keybase.app/Contents/SharedSupport/bin/kbfs -debug -log-file=/Users/alexb/Library/Logs/keybase.kbfs.log -runtime-dir=/Users/alexb/Library/Caches/Keybase /Volumes/Keybase (alexb)
root              1586   0.0  0.0  4381092   3688   ??  Ss   Wed07PM   0:00.76 /Library/PrivilegedHelperTools/keybase.Helper
alexb            35239   0.0  0.0  4276984    924 s002  S+   11:51AM   0:00.00 grep keybase\|kbfs
alexb            35195   0.0  1.2 558514120 200552   ??  S    11:48AM   0:01.86 /Applications/Keybase.app/Contents/SharedSupport/bin/kbfs -debug -log-file=/Users/alexb/Library/Logs/keybase.kbfs.log -runtime-dir=/Users/alexb/Library/Caches/Keybase /Volumes/Keybase (alexb)
alexb            35118   0.0  0.5 558576464  86336   ??  S    11:48AM   0:00.96 /Applications/Keybase.app/Contents/SharedSupport/bin/keybase -d --log-file=/Users/alexb/Library/Logs/keybase.service.log service
alexb            35042   0.0  0.1 558468196   8832   ??  S    11:47AM   0:00.02 /Applications/Keybase.app/Contents/SharedSupport/bin/updater -path-to-keybase=/Applications/Keybase.app/Contents/SharedSupport/bin/keybase
```

**Comment by songgao** [comment]
Looks like there's a stranded `kbfs` process from Friday. Could you please do `kill -ABRT 22914`, then do another log send?

**Comment by ACBullen** [comment]
Did and sent. Keybase has booted up without error. Thanks for the assistance! For future reference, should I be deliberately closing out and shutting down keybase to avoid this kind of thing, or is this a kind of fluke edge case which the app should normally be able to deal with when updating?

**Comment by songgao** [comment]
Thanks Alex! You shouldn't have to do this every time. The updater is designed to take care of restarting all processes.

**Comment by ACBullen** [comment]
Awesome, thanks for the quick responses and take care.
