### ISSUE TITLE
Unable to proof Hacker News

### ISSUE THREAD

**Issue by kmichl** [keybase/client#11723]
Hey,

I can not proof [my HN](https://news.ycombinator.com/user?id=0x9d) with [my Account](https://keybase.io/kmichl). I got the mail, that the proof has failed but i double checked it, and it looks right.

Thanks for the help.

**Comment by kmichl** [comment]
Fixed it ages ago. Closing this old issue.

**Comment by KenBonny** [comment]
Actually, I have the same problem. Check my account [here](https://news.ycombinator.com/user?id=KenBonny).
