### ISSUE TITLE
Chat messages visible on macOS after revoking device

### ISSUE THREAD

**Issue by jbonhag** [keybase/client#11789]
Hi!  I recently revoked a macOS laptop from my mobile device.  However, when I open the Keybase app on that computer I'm still logged in and I can read old chat messages.  It looks like the app can't make any new network requests, but I can still see messages that are cached locally.

<img width="742" alt="screenshot 2018-05-11 09 44 41" src="https://user-images.githubusercontent.com/6937257/39927475-50df31e6-5500-11e8-80da-c322d44eb493.png">

If I try to use any of the buttons on the left sidebar, I get an error message such as:

```
Error: ERROR CODE 201 - your session has expired in method
keybase.1.teams.teamListUnverified at new a
(file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/index.bundle.js:1:441743)
at
file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/index.bundle.js:1:442272
at s
(file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/index.bundle.js:1:442311)
at _rpcClient.invoke.t
(file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/index.bundle.js:1:12053)
at
file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/index.bundle.js:1:1475433
at e.t.Deferrals.e._call
(file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/index.bundle.js:1:671644)
at
file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/index.bundle.js:1:671795
at s
(file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/index.bundle.js:1:671424)
at e.t.Deferrals.e._fulfill
(file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/index.bundle.js:1:671754)
at s
(file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/index.bundle.js:1:670958)
```

I would expect that revoking a device would log you out on that device.  Thanks for checking this out!

Keybase version: Version 1.0.47-20180511010500+206cfc714b (1.0.47-20180511010500+206cfc714b)

**Comment by jbonhag** [comment]
My log id is cfb6e588f606157050a9e41c.

**Comment by maxtaco** [comment]
It doesn't look like `hero` was revoked according to https://keybase.io/jbonhag/devices

Are you sure the device revoked work?

**Comment by jbonhag** [comment]
Hey, thanks for responding.  The revoked device was actually this one:

![img_688332fd2d48-1](https://user-images.githubusercontent.com/6937257/40253145-ad8090f0-5aac-11e8-89b4-705bbf57704f.jpeg)

**Comment by maxtaco** [comment]
Can you do a `keybase log send` from the revoked device?
