### ISSUE TITLE
macOS Sierra 10.12.6 — stuck at first loading screen after installing

### ISSUE THREAD

**Issue by OmarGanai** [keybase/client#11788]
Keybase GUI Version: 1.0.47-20180508010858+c06519b740

![image](https://user-images.githubusercontent.com/13069014/39921612-91dd57f2-54e9-11e8-9ded-617f71869e24.png)

First time user. I've seen the other threads with similar reports. How do I do `keybase log send` if keybase command line won't start?

Thanks for any help!

**Comment by maxtaco** [comment]
We fixed this with the most recent release.

**Comment by OmarGanai** [comment]
After trying to fix this issue for a couple days, it fixed itself a few minutes after I started this thread. Reporting in case it helps other people.

I received a notification from the app to install a "helper tool" and to enter my mac admin password. After I did that, I was able to enter my keybase username and password. And now I'm in.

**Comment by maxtaco** [comment]
Can you reinstall?

**Comment by maxtaco** [comment]
Super!

**Comment by OmarGanai** [comment]
Ah, we posted at the same time. See my comment above :)
