### ISSUE TITLE
macOS desktop client showing revoked github proof as "unreachable"

### ISSUE THREAD

**Issue by kode54** [keybase/client#11818]
macOS desktop client, Version 1.0.47-20180511010500+206cfc714b (1.0.47-20180511010500+206cfc714b), is showing a GitHub proof on "sylke" user page, which it fails to retrieve, because it no longer exists, and it was revoked according to their chain of authority.

my log id: 8728537c896fa4691218761c

**Comment by maxtaco** [comment]
The proof wasn't actually revoked, it was just deleted from the GitHub side.  To revoke a proof, one has to issue a revocation signature from Keybase, which is signed into the user's sigchain.  It's pretty easy to do that in UI, just click on the icon to the right of the proof and use the tooltip.

**Comment by kode54** [comment]
Oh. It didn't even show it as an invalid proof on their profile page, though. So that's where my confusion came from.
