### ISSUE TITLE
Stuck in "This conversation is waiting for a participant to open their Keybase app."

### ISSUE THREAD

**Issue by pengi** [keybase/client#11821]
I added a new phone to my account, and now a conversation can't be accessed, not from the new phone, my old phone or my computers. The conversation just states "This conversation is waiting for a participant to open their Keybase app"

I have talked with the other person in the conversation, and he has sent me messages, and I get notifications that I got new messages in the conversation. So he has apparently started the Keybase app.

**Comment by pengi** [comment]
BEGIN KEYBASE SALTPACK SIGNED MESSAGE. kXR7VktZdyH7rvq v5weRa0zkWi7o6R VJSyRPnsqlvGpQl Rac5D7sNionWFx2 gAGOK0KZ2DgPXWR yj8QSebdlx2s0CC yyXMl3TVhOC9XeB Oymvj01vqNTL2KF 66jooL59FR7b9j1 BLyPHce7ZBAKitc uRlHnRTA8H5l7Di kWIYL2paNe3DgxU M2fBgdP7cGYaqyh amEUSbVGZqCf5Zp QFnRTBFntCePOPQ gLrHW. END KEYBASE SALTPACK SIGNED MESSAGE.

**Comment by strib** [comment]
Please do a `keybase log send` and let us know the resulting log ID, and we can take a look to see why it's not getting rekeyed.

**Comment by pengi** [comment]
log ID: 5f375ed3c6ddf3b52a6ed91c

**Comment by maxtaco** [comment]
Cc @mmaxim since it is likely a migrated conversation.

**Comment by pengi** [comment]
If it helps, I have prevously reset the keys on this account, which ended up in issue #10098

Might be a trace after that...

**Comment by strib** [comment]
@mmaxim there are a lot of requests in the KBFS log for the pre-reset folder for the conversation, which can't be read by this device.

**Comment by mmaxim** [comment]
Is this still busted? There might be two of these conversations in your inbox, but only one will work. Do you see two, or just one?

**Comment by mmaxim** [comment]
Actually I see the problem, looks like another KBFS conv upgrade/reset user bug.

**Comment by charlesmadere** [comment]
Hello, I am having this exact same issue. I am using an account that was reset, and I already nuked my DB on Android and OSX. But I still can't read the messages from my friend... Any help?

**Comment by mmaxim** [comment]
@charlesmadere I fixed that conversation for you as well, let me know if it works now.

**Comment by charlesmadere** [comment]
@mmaxim thank you! That worked perfectly. 🙂

**Comment by pengi** [comment]
Havn't managed to sync with the other person in the conversation until now. And now it works fine. Thanks!

**Comment by ralfr** [comment]
@mmaxim Can you fix it for me, too? I've got one conversation that is stuck and really want to have a clean interface. :-) Username: ralf
