### ISSUE TITLE
proof for my <username>.keybase.pub broke; site now gives 404 error even though files exist

### ISSUE THREAD

**Issue by brentmaxwell** [keybase/client#11833]
My keybase.pub site proof broke (brentmaxwell.keybase.pub), and the site is now returning a 404 error. When I click the link in the error to go to keybase.pub/brentmaxwell, I get a "Not found" error.

I haven't changed or updated anything in my keybase filesystem in a long time, nor have I changed my username.

When I use the keybase app on Windows, it shows the files that I expect in my keybase/public/brentmaxwell folder (an index.html, my keybase.txt proof, and my pgp key.)

**Comment by strib** [comment]
Dup of keybase/kbfs#1578, please follow the discussion there.
