### ISSUE TITLE
Chat buttons broken in macOS and iOS clients; starting conversation fails

### ISSUE THREAD

**Issue by socketbox** [keybase/client#11861]
### (Probably Irrelevant) Background:  
  
It'd been forever since I logged in after establishing an account. Even though I was successfully logged in via browser, verifying the active key was not an option via that client. So I opted for the command line.

`keybase login chb` succeeded, but when prompted to add a device immediately afterward, I got the following message:
```
Enter a public name for this device: chb-laptop
▶ ERROR You need to delete your active key before uploading a new one (via multikey) (code 908)
```
I gave up and re-keyed my account. After that, everything seemed hunky-dory: I added two devices and proved my Github account.

### Problem:
Soon thereafter, a friend attempted to chat with me, but I was not receiving his message. Also, the chat buttons in both the iOS and macOS clients didn't (and don't) work. Nothing happens at all when I press them.

I followed him, and he me, hoping that that would remedy the situation. No joy. Then attempted to initiate a chat by way of finding his account and chatting with him. Results below.

Sent logs. My log id: 46847c6571c99353a5d2831c

![screen shot 2018-05-15 at 8 19 10 pm](https://user-images.githubusercontent.com/1593835/40090448-c40ea822-587f-11e8-9bc1-6293c76cfbb9.png)

**Comment by mmaxim** [comment]
I'm honestly not sure how this got messed up, but I fixed it manually. If you type `keybase db nuke` from the CLI, and then restart Keybase you should see the conversation. Sorry!

**Comment by mmaxim** [comment]
Also what do you mean you "rekeyed your account"? What did you do exactly?

**Comment by socketbox** [comment]
Hi,

`keybase db nuke` worked like a charm.

By "rekeyed" I'm referring to the action I took when, instead of signing and verifying my active key (which was listed in red in the web UI), I chose to delete a key and destroy the cryptographic identity and record associated with it. I then created a new key (all of this done within the browser).

**Comment by mmaxim** [comment]
OK glad it works!
