### ISSUE TITLE
User friendly way to remove teams

### ISSUE THREAD

**Issue by JadonZufall** [keybase/client#11877]
I would like for there to be a user friendly way to delete teams for most people on this platform it is not past them to go into terminal or command prompt in order to delete a team but it's annoying when using the mobile client if you want to delete a team also it would just be nicer to be able to delete a team from the application its self

TLDR : Ability to delete teams from the application its self mobile and desktop

**Comment by mmaxim** [comment]
@cecileboucheron we have a design for this right?

**Comment by cecileboucheron** [comment]
We do have designs but it's not implemented yet. 
UX is: if you're the last member to leave a team, we should give you the option to delete the team. Right now in the GUI you can't leave a team if you're the last member.

**Comment by mmaxim** [comment]
@keybase/react-hackers would be nice to get this in, there is no way to delete a team from the UI right now.
