### ISSUE TITLE
keybase pgp decrypt -> Error: No username known

### ISSUE THREAD

**Issue by xamox** [keybase/client#11875]
I've confirmed I'm logged in.

```
$ keybase id                      
▶ INFO Identifying xamox
✔ public key fingerprint: C71E E3E8 F61A 166A D268 5ADA 8447 06FB 6E28 BC35
```

Same key fingerprint in my gpg list
```
$ gpg --list-keys --fingerprint | grep C71E
      Key fingerprint = C71E E3E8 F61A 166A D268  5ADA 8447 06FB 6E28 BC35
```

I've also tried keybase logout, keybase db nuke, then keybase login again but still same issue occurs.

```
$ keybase version
Client:  1.0.48-20180516160417+b56432f520
Service: 1.0.48-20180516160417+b56432f520
```

```
$ lsb_release -a    
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.4 LTS
Release:	16.04
Codename:	xenial
```

**Comment by maxtaco** [comment]
Thanks for the bug report, I'll look into it right away

**Comment by xamox** [comment]
@maxtaco Great, let me know if you would like the debug output as well.

**Comment by maxtaco** [comment]
Looks like the issue closed with my merge. We'll get a release out soon.  Thank you!

**Comment by xamox** [comment]
Great thanks!

**Comment by mattvonrocketstein** [comment]
What's the status on that release, or another workaround?  With increasing numbers of tools like vault and terraform integrating with keybase, I think fixing breakage like this is should be high priority

**Comment by maxtaco** [comment]
@mattvonrocketstein, does `keybase logout; keybase login` work?

**Comment by mattvonrocketstein** [comment]
Yes! tyvm
