### ISSUE TITLE
Avatars turn blank in desktop client

### ISSUE THREAD

**Issue by andyhhp** [keybase/client#11885]
I'm sorry for such a poor bug report, but I've got no idea what is going on here.  Recently, the destop client (Win7 64bit) updated from 1.0.47 to 1.0.48, and this problem started occuring.  (My andriod client, and separate Linux desktop client have no issues whatsoever.)

The avatar icons for users and teams have disappeared and are rendered blank.  Users with "No Avatar" are rendered properly, but all others are blank grey circles/boxes.

If I exit keybase fully, delete all the `avatar$N.avatar` files in the keybase directory (which I presume are local copies of the images), and restart keybase, then the avatars render correctly for a few seconds, after which they all turn blank again.  This behaviour is deterministic.

When searching for people explicitly, the followers and following tabs begin by rendering the avatars correctly, then similarly turn blank after a few seconds.

Once an individual avatar has turned blank, it never renders correctly again (including across full restarts of keybase) until I purge the `avatar$N.avatar` files.

Can anyone suggest any further debugging tips?

**Comment by mmaxim** [comment]
This is a pretty good bug report! Can you do a `keybase log send` though? Thanks!

**Comment by andyhhp** [comment]
Log id 12d5b88d3a4b678e74ca1d1c

**Comment by mmaxim** [comment]
Ah I see, I think there is a problem because your username has a space in it.

**Comment by mmaxim** [comment]
I just merged a change which will hopefully fix it for you, will be available in the next release.

**Comment by andyhhp** [comment]
hmm - I don't know whether to congratulate or curse younger me.  Any ETA on the next release?

**Comment by mmaxim** [comment]
Probably in a week or two, sorry!

**Comment by andyhhp** [comment]
Just tested 2.0.0-20180604093219+f899a761a7 and this issue is resolved.  TYVM!
