### ISSUE TITLE
I have a public key but not the private

### ISSUE THREAD

**Issue by mehdibo** [keybase/client#11893]
I'm trying to upload my e-mail's public key to Keybase, I'm using Protonmail and I don't have a copy of the private key.

How can I add the public key to Keybase?

**Comment by 5h4d0ww0lf** [comment]
No way because protonmail is owning your privatekey you need your own.

**Comment by mehdibo** [comment]
Thanks

**Comment by 5h4d0ww0lf** [comment]
@mehdibo Do you really want to use a certificate which isn't private? Private key should be only in your possession not shared with protonmail.

**Comment by mehdibo** [comment]
@5h4d0ww0lf My goal was to add a public key to keybase, so that if someone wants to send me an e-mail to my protonmail he can use the public key in keybase.
