### ISSUE TITLE
harder to quit than vim

### ISSUE THREAD

**Issue by simbalion** [keybase/client#11935]
If I kill keybase processes they're restarted but I don't see a service named Keybase running. This is bad design. Please offer a way to kill the app which follows intuitive standards.

**Comment by strib** [comment]
Dup of keybase/keybase-issues#3242.

**Comment by heronhaye** [comment]
Keybase 4.0 has a Quit Keybase button in the main app in the GUI.

![2019-05-08-164233_367x601_scrot](https://user-images.githubusercontent.com/28712558/57407074-5671eb80-71b0-11e9-9713-581f9baa3808.png)

Also, `keybase ctl stop` should work as expected on Linux.
