### ISSUE TITLE
Team issue after laptop crash

### ISSUE THREAD

**Issue by thomasmorse** [keybase/client#11989]
My laptop crashed and hard drive got nuked when IT was working on the laptop.
I lost my paper key during the crash.
I got keybase setup on the new laptop but keep getting prompted to enter paper key for a team to regain access.
I was the sole owner/member of the team and don't have the paper key.
Accessing the team via GUI gives this error:
error unboxing chat message: You are not a member of this team (error 2623).
When I try to delete the team via cli I get the same error.
What is the best way to proceed?

keybase version
Client:  1.0.48-20180516160420+b56432f520
Service: 1.0.48-20180516160420+b56432f520

my log id: 1a2a51ef8778dae4d4355e1c

**Comment by maxtaco** [comment]
cc: @mmaxim

**Comment by mmaxim** [comment]
I'm not sure how this paper key flow works here, cc @mlsteele

**Comment by maxtaco** [comment]
It is likely a KBFS rekey popup.  Maybe there is a broken TLF for this user.

**Comment by thomasmorse** [comment]
I re-installed keybase and rebooted my laptop and the prompts for the paper key have stopped.
In my case the team in question was owned by someone who had to rekey after losing his device which  seems to be causing the team issues.
