### ISSUE TITLE
Keybase breaks on OSX if login shares aren't mounted.

### ISSUE THREAD

**Issue by kglick** [keybase/client#12007]
Keybase GUI Version: 1.0.48-20180516160420+b56432f520

This problem was brought up over a year ago.  Keybase seems to look for samba, or other mounts, in a users login scripts.  If the shares aren't mounted the app becomes unstable and hangs.  

At what point are you going to do something about this? I'm not interested in the tool even thinking about my shares unless I explicitly ask it to do so.  The fact that this hasn't been addressed is highly suspicious.

**Comment by strib** [comment]
Dup of #6359, let's keep the discussion there.
