### ISSUE TITLE
Notifications on iOS do not show content

### ISSUE THREAD

**Issue by pitweval** [keybase/client#12017]
For text messages and other messaging apps when you put focus (touch the notification) the message expands slightly to show part of the content, keybase notifications do not do this, you have to open the app in order to read the message.  In some instances I can even respond to a text or message from other apps, with out fulling opening the app in question.  Keybase cannot do this since you have to ope the app to interact with the message.  Not sure if this is a problem on Android, but is annoying on iOS.

**Comment by JadonZufall** [comment]
It doesn't show notifications on android or apple and I feel like this is more a feature then a issue seeing as the nature of the app is to be encrypted and stuff I feel like it would be a major over sight to show the content of a message in the notification

**Comment by pitweval** [comment]
Turns out you can actually turn on notifications, it's a setting that is turned off by default (listed as a security setting under notifications).

**Comment by drmercer** [comment]
The setting does not work on Android currently. :(
