### ISSUE TITLE
Permission denied for public and private dir

### ISSUE THREAD

**Issue by ronhorm** [keybase/client#12156]
I have 2 devices.  On device #1  I am able to use kbfs w/o issue.   On device #2 though I get Permission Denied when I try to access my public or private dir.

`ls /keybase/public
ls: /keybase/public: Permission denied`

my log id: 11871cd8d1c931124bd4d21c

**Comment by strib** [comment]
According to the logs, Keybase isn't configured to mount the filesystem.  Have you enabled Finder integration on device 2?  Check the settings tab in the Keybase app.

**Comment by ronhorm** [comment]
I have enabled Finder integration am able to browse public and private folder through the Keybase client now.   Still unable however to access via the command line.   Permission denied still popping up

**Comment by strib** [comment]
> and am able to browse public and private folder through the Keybase client now

You mean you can browse within the "Files" section of the Keybase client?  That doesn't depend on Finder integration, it's just part of our app.  Is there a `Keybase` favorite available in your Finder that you can browser like a local folder?

If not, try quitting Keybase and relaunching the app, maybe Finder integration hasn't completed yet.

**Comment by ronhorm** [comment]
Restarting keybase fixed it.  Able to browse via finder and command line now.   Thanks for your help

**Comment by strib** [comment]
cc: @jzila maybe another issue with the Finder integration setting not restarting things anymore.
