### ISSUE TITLE
Error when requested invite

### ISSUE THREAD

**Issue by j-mikhail** [keybase/client#12169]
Hello,

Whenever I use the request invite function, and click the submit button after entering my email and name, I see the following output. Can anybody advise?

![image](https://user-images.githubusercontent.com/3420913/40861723-195690f2-65b8-11e8-8b9f-7ac407ff6652.png)

Thank you.

**Comment by maxtaco** [comment]
cc @keybase/react-hackers

**Comment by buoyad** [comment]
@j-mikhail would you mind submitting logs via `keybase log send`?

**Comment by j-mikhail** [comment]
@buoyad Kept fiddling and just resolved it. Occurs when \Keybase\Gui\Keybase.exe has network access but \Keybase\keybase.exe does not. Might I suggest a more graceful error message in that circumstance?

**Comment by buoyad** [comment]
Ah ok, thanks for the repro, that's interesting. Sure, we'll take a look!
