### ISSUE TITLE
Keybase FS never mounted, macOS

### ISSUE THREAD

**Issue by kode54** [keybase/client#12180]
I recently Internet restored an iMac to 10.10, and upgraded directly to 10.13.4, then to 10.13.5.

Keybase doesn't mount itself any longer. It is claiming it mounted to /Volumes/Keybase, but that directory does not exist.

My log id is: 2e24fe4704c3bf06fe19b41c

**Comment by strib** [comment]
@kode54 did you enable the Finder integration after you restored?  Go into Settings -> Files in the Keybase GUI app.  You may have to restart KBFS after doing that.  Right now it looks like Keybase thinks this hasn't been configured yet.

**Comment by kode54** [comment]
I enabled that in the Files tab of the main page of the application, where it had an Enable button for that. I have not logged out or restarted since then.
