### ISSUE TITLE
Communication issue just after update to ver. 2.0.0, but IP sessions exist

### ISSUE THREAD

**Issue by tomlog01** [keybase/client#12197]
Despite the fact that kbfsdokan.exe & keybase.exe both have various IP sessions, 
keybase reports "Oops, we had a problem communication with our services ..." just after update to ver. 2.0.0-20180604093219+f899a761a7 on Windows 7 (32bit).

"HERGESTELLT" means "ESTABLISHED" in the following excerpt of a netstat -banvo command:

[kbfsdokan.exe]
 TCP    192.168.99.20:2007     52.200.106.130:443     HERGESTELLT     7620
[keybase.exe]
 TCP    192.168.99.20:2008     52.4.87.2:443          HERGESTELLT     8148
[kbfsdokan.exe]
 TCP    192.168.99.20:2010     52.4.87.2:443          HERGESTELLT     8148
[kbfsdokan.exe]
 TCP    192.168.99.20:2028     35.161.168.59:443      HERGESTELLT     3872

my log id: 4cddc708d95d6caf0c098a1c

**Comment by Fredar** [comment]
Same happened to me, right after update yesterday. Can also confirm established IP sessions.
Keybase GUI Version: 2.0.0-20180604093723+f899a761a7

my log id: 681d5b276e681963f9db491c

**Comment by tglaeser** [comment]
This issue seems to be duplicate to #12216.

**Comment by Fredar** [comment]
@tglaeser Seems the same true. Wish we could get our hands on old 1.0.x installer.

**Comment by maxtaco** [comment]
Sorry about this bug.  We have a fix up here before we get a release out: https://prerelease.keybase.io/windows/Keybase_2.0.0-20180605100109%2B9aa86bcb87.386.exe

Does this fix the problem for you?

cc @zanderz

**Comment by bs78ta** [comment]
I just used the pre release and it fixed the problem. Thanks guys!!!!

**Comment by Fredar** [comment]
Fixed, thanks.

**Comment by ksaylor11** [comment]
That addressed my problems as well

**Comment by maxtaco** [comment]
Let's close this issue. Thanks all.
