### ISSUE TITLE
Oops, we had problem communicating with our services. (Reload)

### ISSUE THREAD

**Issue by DarkAngelStrike** [keybase/client#12216]
![keybase](https://user-images.githubusercontent.com/716555/41004598-6c350212-68e8-11e8-9049-71d19c849972.png)

I'll try to reinstall ...

my log id: 0ca699e59ff849b8dd1e6e1c

**Comment by tglaeser** [comment]
I'm getting the same error after upgrading to version `2.0.0-20180604093219`. Also login from the terminal is timing out ...
```
$ keybase ping
2018-06-05T18:47:01.838872-04:00 - [INFO keybase cmd_ping.go:40] 001 API Server at https://api-0.core.keybaseapi.com is up

$ keybase login
2018-06-05T18:50:04.839200-04:00 - [ERRO keybase main.go:90] 001 Operation timed out

```

**Comment by bs78ta** [comment]
What OS are you using. I am having the same problem on Windows 7

**Comment by maxtaco** [comment]
@zanderz can you post a link to the fixed build?

**Comment by bs78ta** [comment]
Pre release did not change my results. Good luck

**Comment by DarkAngelStrike** [comment]
The installation of the pre-release Keybase_2.0.0-20180605100109+9aa86bcb87.386.exe linked in this comment https://github.com/keybase/client/issues/12197#issuecomment-394904222 solved the issue. Thanks!
