### ISSUE TITLE
Error when add a new paper key

### ISSUE THREAD

**Issue by InTheFlipside** [keybase/client#12288]
https://i.imgur.com/qoy9RCn.png

I can't click on "okay". And the message "you need a paper key to rekey your file" always appear when I start the software

**Comment by maxtaco** [comment]
@InTheFlipside you likely have a broken folder somewhere. Can you do a `keybase log send`?

**Comment by InTheFlipside** [comment]
@maxtaco I revoke the only device that has access to this folder. 
I sended a `keybase log send` before and after this 

thank for your answer

**Comment by maxtaco** [comment]
thanks.  cc @strib

**Comment by strib** [comment]
We took care of this on #12290.
