### ISSUE TITLE
macOS Finder Extension Error

### ISSUE THREAD

**Issue by djdesign** [keybase/client#12309]
macOS 10.14 Finder Extension was working until upgrading xcode-select to Xcode version 10.
Returns error _The operation can’t be completed because the original item for “Keybase” can’t be found._
Any input would help appreciated. Besides the obvious using developer release software results in unknown and unexpected results to incur. 

my log id: c4095a99129ee84dfb91fd1c

Steps to resolve: 
1. Complete Uninstall & Restart
2. Fresh Install & Restart
3. Repair Disk Permissions

**Comment by strib** [comment]
Thanks for the report.  The current state of your system (at the time you sent the logs) was that Finder integration wasn't enabled.  Note that there's currently a bug where you have to restart Keybase after enabling Finder integration, so if you turned it off for testing purposes and haven't restarted Keybase since, you'll want to try a Keybase restart.

An hour earlier though, at the time of your previous Keybase restart, everything looked fine from the perspective of our logs.

Can you give a little more detail about what problem you saw exactly, and what time you started seeing it (local time on your computer)?  Did `/keybase` disappear?  When you say "Returns error" -- what operation did you try to when you got that error?  Is that when you tried to open the Keybase favorite entry from the Finder sidebar?

**Comment by djdesign** [comment]
Good afternoon,

When attempting to access from Finder: Desktop Drive Icon, Sidebar Favorite returns that error. Unable to access from terminal either, it doesn’t show the volume keybase is mounted.

Regards,
Daniel

**Comment by strib** [comment]
Ok, thanks. Have you tried restarting Keybase since you sent the logs?  And what does it say in the Settings section of your Keybase app right now, under "Files"?

**Comment by djdesign** [comment]
Yes, No Access. I see that the extension option was disabled, so I enabled, then restarted keybase then finder. Upon opening trying to access keybase from finder favorite, same as initial result.

Here is the updated log ID# 491dc7ac52dd99cb7d84371c

**Comment by strib** [comment]
Ok thanks.  From the logs it looks like there was good progress now -- it should be available at `/keybase` and under `/Volumes`.  Can you confirm that your files are accessible in those places now?

I'm unsure why the favorite is still broken though.  Can you please run this command from the terminal and let me know what it says?

```
ls -l ~/Library/Application\ Support/Keybase/Keybase
```

**Comment by djdesign** [comment]
```bash
/  ls -l ~/Library/Application\ Support/Keybase/Keybase                                                                                                                                           13:36:21
lrwxr-xr-x  1 DJ  staff  21 Apr  3 10:30 /Users/DJ/Library/Application Support/Keybase/Keybase -> /Volumes/Keybase (DJ)
/ keybase ctl restart                                                                                                                                                                             13:36:22
▶ INFO Stopping Keybase app
▶ INFO Terminated Keybase [10014]
▶ INFO Uninstall mount: /Volumes/Keybase (DJ)
▶ INFO log directory "/Users/DJ/Library/Logs" is writable by current user
▶ INFO log path "/Users/DJ/Library/Logs/keybase.start.log" exists and is writable by current user
▶ INFO paths in plist look ok and have valid permissions
▶ INFO Saving /Users/DJ/Library/LaunchAgents/keybase.service.plist
▶ INFO Starting keybase.service
▶ INFO Waiting for keybase.service to be loaded...
▶ ERROR stat /Volumes/Keybase (DJ): no such file or directory
▶ INFO log directory "/Users/DJ/Library/Logs" is writable by current user
▶ INFO log path "/Users/DJ/Library/Logs/keybase.updater.log" exists and is writable by current user
▶ INFO paths in plist look ok and have valid permissions
▶ INFO Saving /Users/DJ/Library/LaunchAgents/keybase.updater.plist
▶ INFO Starting keybase.updater
▶ INFO Waiting for keybase.updater to be loaded...
▶ INFO Opening /Applications/Keybase.app
▶ ERROR stat /Volumes/Keybase (DJ): no such file or directory
```

**Comment by strib** [comment]
Those error during restart are normal; I see them too, and my `/Volumes` mountpoint is fine.  You can ignore them.

Are your files showing up under `/keybase` and `/Volumes/Keybase (DJ)`?

**Comment by djdesign** [comment]
@strib yes I can see files in `/Volumes/Keybase (DJ)` but not `/keybase/`

**Comment by strib** [comment]
Hmm, can you try this to see if that fixes `/keybase`?

```
keybase uninstall -c redirector
keybase install -c redirector
```

**Comment by djdesign** [comment]
@strib that successfully fixed the issue.

**Comment by strib** [comment]
Great.  Does the Finder favorite work now as well?

**Comment by djdesign** [comment]
@strib correct, that resolved terminal mount point and finder favorite access.

**Comment by strib** [comment]
Ok great. Not sure why this happened in the first place, I guess your Finder-integration setting got messed up somehow. We'll be on the lookout for similar issues.  Thanks!

**Comment by djdesign** [comment]
Yep Np. Maybe it has todo with ... 10.14 Mojave. Had some other weird permission issues with application extensions having extended attributes of com.apple.quarantine ; resolved that in single user mode.
