### ISSUE TITLE
Error when changing git repo update channel

### ISSUE THREAD

**Issue by pierwill** [keybase/client#12414]
When clicking on the link ("#general") to change the announcement channel for team git repo, I get this error:

![screen shot 2018-06-18 at 11 09 44 am](https://user-images.githubusercontent.com/19642016/41548338-50264ba8-72e8-11e8-9640-87628729bb8a.png)

**Comment by buoyad** [comment]
I see this too, I'll take a look at it. Thanks for the issue!

**Comment by buoyad** [comment]
I have a fix for this here: https://github.com/keybase/client/pull/12437. It'll be fixed in the next update!

**Comment by pierwill** [comment]
This is working for me now
