### ISSUE TITLE
Broken folders after device-add rekey event

### ISSUE THREAD

**Issue by saxrussell** [keybase/client#12462]
#### Issue description
I had to reinstall my OS on a work laptop that was using keybase normally. After the reinstall of said OS and keybase, I added the new device (before revoking the old one), followed by adding a new paper key from the new device, and some private conversation folders are now inaccessible and not getting fixed by logging in from other devices or initiating paper key rekeys from those devices.

#### Steps to reproduce the issue
MBP_Personal = macbook pro running macOS 10.13.4, keybase v 2.0.0-201806044163023+f899a761a7
google pixel : Android 8.1.0 - keybase v 1.0.49-21080605022941+da5061f5ff
credo_pop : Pop!_OS (Ubuntu) 18.04 - keybase v 2.1.0-20180615162035+8625b772b1
​
the sequence of events went like this:
​
1. add new device `credo_pop` via device `google pixel`  
2. prompted to create paper key on newly-added `credo_pop`
3. created paper key on `credo_pop` which triggered initial rekey event
4. "Unable to read folders" error pops up.
5. followed instructions by ensuring both MBP and Pixel turned on and logged into Keybase
6. nothing happened, so attempted to use paper key i had just created. keyboard input does not fill the field (separate issue [#12461](https://github.com/keybase/client/issues/12461)).
7. notice that my old OS i just installed over is still active, so revoke that. no effect
8. revoke paper key. no effect
9. create another new paper key
10. `keybase rekey paper` on MBP_Personal ... no effect. 
​
keybase rekey status shows 3 private conversations that need rekeying (they're old conversations and i have no beef losing them) and that either MBP_Personal or google pixel can rekey them, but still no dice.

Log send id (from MBP): 8b7929e97091d173946edf1c

#### What's the expected result?

- Logging in from one of the listed devices corrects the problem as advertised

#### What's the actual result?

- Nothing happens. After logging in both clients on the other devices, the output of `keybase rekey status` still lists TLFs need rekeying and that the MBP_Personal and google pixel devices can rekey them.

#### Additional details / screenshot

- ![Screenshot](https://s3.us-west-2.amazonaws.com/com.dsmall.general/share/screenshots/UnlockFolders_007.png)

**Comment by strib** [comment]
@saxrussell I think you're hitting a known rekey bug in the last release.  We just released a version with the fix (like an hour ago), can you please try to upgrade on your devices that previously had access to the conversations and see if that helps?

**Comment by saxrussell** [comment]
Yes indeed, that fixed it. I'll try and dig through the already-open issues a bit more thoroughly next time. Thanks a ton for the help!

**Comment by strib** [comment]
No worries about the duplicate issue, our open issues aren't very organized.  Glad it worked!
