### ISSUE TITLE
starting keybase.service kept failing on Ubuntu 16.04

### ISSUE THREAD

**Issue by gulprun** [keybase/client#12521]
Running Keybase with > run_keybase command returns errors all the time. 
my log id: 2100ffef14b31e07d176ae1c

```
▶ INFO Starting keybase.service.
Job for keybase.service failed because the control process exited with error code. See "systemctl --user status keybase.service" and "journalctl -xe" for details.
▶ ERROR Failed to start keybase.service.
▶ ERROR Error in spawning server process: exit status 1
▶ ERROR exit status 1
```

**Comment by strib** [comment]
I'm seeing errors like this:

```
LevelDb.open -> ERROR: resource temporarily unavailable
```

Maybe that means there's another `keybase` process still running somewhere that has the leveldb locks?  @gulprun can you check `ps auwwx` for keybase processes?

**Comment by oconnor663** [comment]
`run_keybase` should kill everything, unless there are some weird shenanigans going on with UIDs. Maybe you wound up with something root-owned in `ls -l ~/.local/share/keybase`?

**Comment by adeel** [comment]
Same issue here (Ubuntu 16.04.5 LTS).  Log id: 5cc54ff4dd70fecec4b6351c.

There wasn't anything root-owned in `ls -l ~/.local/share/keybase`, but there was a running keybase process:

```
adeel@24474:~$ ps auwwx|grep keybase
adeel     1013  0.0  0.1  14164  1060 pts/5    S+   04:04   0:00 grep --color=auto keybase
adeel     5255  0.1  2.4 355720 25848 pts/1    Sl   01:23   0:16 keybase -d --log-file=/home/adeel/.cache/keybase/keybase.service.log service --auto-forked
adeel     5257  0.1  1.5 295676 16220 pts/1    Sl   01:23   0:11 kbfsfuse -debug -log-to-file /home/adeel/.config/keybase/kbfs
```

After running `kill -9 5255` and `kill -9 5257`, it worked:

```
adeel@24474:~$ run_keybase
Shutting down keybase service...
Starting via systemd.
Success!

[redacted chipmunk(?)]
```

**Comment by cheapRoc** [comment]
Same, I had a hung `keybase` process that was holding the leveldb lock (or something like that). Once I killed the other process `keybase.service` seems to be running properly.

```
justin   26450  0.1  0.1 1219632 48564 ?       Ssl  16:06   0:08 /usr/bin/keybase --debug --log-file /home/justin/.cache/keybase/keybase.service.log service --chdir /home/justin/
.config/keybase --auto-forked
```

**Comment by heronhaye** [comment]
Closing as resolved, please make a new issue if you still have trouble, thanks!
