### ISSUE TITLE
FEATURE REQUEST iOS/Mobile App Remember Passphrase option!

### ISSUE THREAD

**Issue by danthegoodman1** [keybase/client#12529]
One thing I love about apps like Signal and Wickr is that I can have them require a passcode/TouchID/FaceID when I reopen the app, or even have them log out every time.

The Keybase Electron app has this (macOS but that's not OS specific), why can't it be implemented into the iOS/Android App? Having the code/ID or re-login on app open would be really awesome and pretty much move me entirely to the keybase platform!

**Comment by webdigi** [comment]
Was this closed?
