### ISSUE TITLE
Can't read conversation messages, getting error: invalid team name: team names must be between 2 and 16 characters long

### ISSUE THREAD

**Issue by blitzstern5** [keybase/client#12539]
Hello. I'm trying to read conversation messages by sending:

{'method': 'read', 'params': {'options': {'channel': {'name': 'genesiscommunity', 'topic_name': 'general', 'members_type': 'team'}}}}

and getting error:

{"error":{"code":0,"message":"invalid team name: team names must be between 2 and 16 characters long"}}

This script worked for months till the last weekend

my log id: 14486fb829d6c216b5d8231c

**Comment by maxtaco** [comment]
Fixed in the next release, should be out soon

cc @mmaxim

**Comment by blitzstern5** [comment]
Yep, it works. Mac Version 2.1.2-20180625190314+836e4aeaca. Thanks!
