### ISSUE TITLE
Website verification broken after changing SSL certificate

### ISSUE THREAD

**Issue by anthonywilliams** [keybase/client#12568]
Yesterday I changed the SSL certificate for my website from a purchased to a letsencrypt one. The website seems to be working for me and other people, and the keybase.txt file is still there, but I got an email from keybase that the website proof was broken.

Does keybase not support letsencrypt certificates?

My web proof is at:

https://www.justsoftwaresolutions.co.uk/keybase.txt

**Comment by samueltardieu** [comment]
According to https://www.ssllabs.com/ssltest/analyze.html?d=www.justsoftwaresolutions.co.uk&s=178.79.187.92&latest you seem to be lacking an intermediate certificate between yours and the authority ("Let's Encrypt Authority X3" is missing between your own certificate and the authority "DST Root CA X3" in the trust store). Also, it looks like you offer an intermediate certificate "AlphaSSL CA - SHA256 - G2 " which is not needed.

**Comment by anthonywilliams** [comment]
Thanks. It was an incorrect ssl chain file in apache. Thankfully, most browsers seem to accept Let's Encrypt certificates directly, so the website was working OK. It appears the keybase proof is now accepted again.
