### ISSUE TITLE
kbfs folder location?

### ISSUE THREAD

**Issue by davidneedham** [keybase/client#12592]
I cannot access /keybase (permission denied) or any folders within it (such as /keybase/public/davidneedham). I notice that I'm able to get to /Volumes/Keybase (davidneedham)/public/davidneedham, but that's not what your help article suggests I should get (https://keybase.io/docs/kbfs). Is the doc out of date?

my log id: d2f1b938ac8257f19ce0611c

**Comment by strib** [comment]
We resolved this via chat.  The solution was:

```
keybase uninstall -c redirector
keybase install -c redirector
```

There was some weirdness with a company policy around certain apps that may have contributed to the problem.
