### ISSUE TITLE
Advice on a malicious user going after members of my team

### ISSUE THREAD

**Issue by jpboudreault** [keybase/client#12608]
Hi,
A malicious user has been very active recently and found some of my team's KeyBase usernames. He has been creating fake KeyBase profiles very similar to the original ones. He has been going after the team members directly. Is there a way to block those profiles or flag them. We are working on raising awareness and making sure folks are careful. I would like to know if there are tools and best practices to deal with this situation.

Thanks

Edit: typos

**Comment by strib** [comment]
cc @malgorithms

**Comment by jpboudreault** [comment]
Anything?

**Comment by strib** [comment]
I'm sorry for the delay.  Unfortunately with the US holidays this week, things are a bit slower than normal for us. Usually things like this are best handled by direct communication with @malgorithms by email or with a Keybase direct chat.  

We don't yet have any tools for users to handle this sort of thing, so I recommend trying to get in touch with @malgoirthms in a more direct way if you haven't already, with more details.

**Comment by malgorithms** [comment]
discussed privately, closing this ticket out.
