### ISSUE TITLE
certificate issue - new user

### ISSUE THREAD

**Issue by mattharg** [keybase/client#12630]
Installed mac Client today. First time with keybase.  All OK initially.  Then installed mobile client.  All good there as well.  Now on the mac client I am getting certificate errors.   Here's a few command-line diagnostics.

>keybase verify
▶ WARNING (CONN gregor 15020968) Connection: error dialing transport: x509: certificate signed by unknown authority
▶ WARNING (CONN gregor 15020968) Connection: error dialing transport: x509: certificate signed by unknown authority
▶ WARNING (CONN gregor 15020968) Connection: error dialing transport: x509: certificate signed by unknown authority
▶ WARNING (CONN gregor 15020968) Connection: error dialing transport: x509: certificate signed by unknown authority
▶ WARNING (CONN gregor 15020968) Connection: error dialing transport: x509: certificate signed by unknown authority

keybase update check
2018/07/01 13:15:54 DEBG Using default path to keybase: /Applications/Keybase.app/Contents/SharedSupport/bin/keybase
2018/07/01 13:15:54 DEBG Execute: /Applications/Keybase.app/Contents/SharedSupport/bin/keybase [version -S]
2018/07/01 13:15:54 DEBG Executed /Applications/Keybase.app/Contents/SharedSupport/bin/keybase [version -S]
2018/07/01 13:15:54 DEBG Execute: /usr/bin/sw_vers [-productVersion]
2018/07/01 13:15:54 DEBG Executed /usr/bin/sw_vers [-productVersion]
2018/07/01 13:15:54 INFO Checking for update, current version is 2.1.2-20180625190314+836e4aeaca
2018/07/01 13:15:54 INFO Using updater source: Keybase.io
2018/07/01 13:15:54 DEBG Using options: updater.UpdateOptions{Version:"2.1.2-20180625190314+836e4aeaca", Platform:"darwin", DestinationPath:"/Applications/Keybase.app", URL:"", Channel:"", Env:"prod", Arch:"x86_64\n", Force:false, OSVersion:"10.13.5", UpdaterVersion:"0.3.0"}
2018/07/01 13:15:54 INFO Request "https://api.keybase.io/_/api/1.0/pkg/update.json?arch=x86_64%0A&auto_update=0&install_id=8238afc903f9b417b02190e080a172a528342ce80d5d0f1d&os_version=10.13.5&platform=darwin&run_mode=prod&upd_version=0.3.0&version=2.1.2-20180625190314%2B836e4aeaca"
2018/07/01 13:15:55 INFO Reporting: https://api.keybase.io/_/api/1.0/pkg/error.json map[error_type:[find] description:[Update Error (find): Get https://api.keybase.io/_/api/1.0/pkg/update.json?arch=x86_64%0A&auto_update=0&install_id=8238afc903f9b417b02190e080a172a528342ce80d5d0f1d&os_version=10.13.5&platform=darwin&run_mode=prod&upd_version=0.3.0&version=2.1.2-20180625190314%2B836e4aeaca: x509: certificate signed by unknown authority] version:[2.1.2-20180625190314+836e4aeaca] upd_version:[0.3.0]]
2018/07/01 13:15:56 WARN Error notifying about an error: Post https://api.keybase.io/_/api/1.0/pkg/error.json: x509: certificate signed by unknown authority
2018/07/01 13:15:56 ERR  [Update Error (find): Get https://api.keybase.io/_/api/1.0/pkg/update.json?arch=x86_64%0A&auto_update=0&install_id=8238afc903f9b417b02190e080a172a528342ce80d5d0f1d&os_version=10.13.5&platform=darwin&run_mode=prod&upd_version=0.3.0&version=2.1.2-20180625190314%2B836e4aeaca: x509: certificate signed by unknown authority]
Error running "/Applications/Keybase.app/Contents/SharedSupport/bin/updater": exit status 1

 

>keybase dump-keyfamily
▶ WARNING (CONN gregor 15020968) Connection: error dialing transport: x509: certificate signed by unknown authority
▶ ERROR error loading user: API network error: Get https://api-0.core.keybaseapi.com/_/api/1.0/merkle/path.json?last=3180887&load_deleted=1&load_reset_chain=1&poll=10&sig_hints_low=6&uid=66bfe99a228477de4130748c1b7d1a19: x509: certificate signed by unknown authority (error 1601)

**Comment by maxtaco** [comment]
Are you behind a proxy or firewall that might be MiTM'ing your TLS connections?

**Comment by mattharg** [comment]
Thanks for the response.
Yes.  Now it's fixed.

FYI - I work on a Mac'.   I'd installed Kaspersky and not de-installed it
correctly, leaving behind a bit of a firewall which was very hard to
detect.  Solution:  Download and deploy Kaspersky's removal tool from their
site and deploy.  Lesson learnt.

Thanks again.

Matt



Regards,

Matt Hargreaves -

Executive Director -  IoT Security Institute

Phone, TXT:        +61 411 090 168
Telegram:            https://t.me/mattharg
Linkedin:              http:// <http://au.linkedin.com/in/matthewhargreaves>
www.linkedin.com/in/matthew-hargreaves
Website:              https://iotsecurityinstitute.com/
Teleconference:   VC-Room <https://appear.in/iotsec01>

<https://appear.in/iotsec01>
