### ISSUE TITLE
Can't open my own private folder: Permission denied

### ISSUE THREAD

**Issue by fgsch** [keybase/client#12634]
```
/keybase/private/fgsch$ ls -l
ls: .: Permission denied
```

**Comment by strib** [comment]
If you do a `keybase log send`, and post the resulting ID here, I can take a look.

**Comment by fgsch** [comment]
Done. ID 128839033208b5c871d4781c

**Comment by strib** [comment]
You have revoked all devices that had access to your folder, over a year ago, probably back when we might have had some relaxed standards for provisioning new devices such that the folder never got rekeyed for your new devices.

Looks like there probably wasn't much in there. If you want us to reset your folder, please run this command on a currently-valid keybase device, and substitute the current date and time where indicated:

```
keybase sign -m "<DATE_AND_TIME>: Please reset folder /keybase/private/fgsch because all the devices that have access have been revoked."
```

and post the results here.

**Comment by fgsch** [comment]
Below.

BEGIN KEYBASE SALTPACK SIGNED MESSAGE. kXR7VktZdyH7rvq v5weRa0zk8sXGqa mEpqTGNfK9qEWRP tLBgLHROJCmbu5I 8OFIxMLPzYLJwip 3pNrTJQkZH5lLc1 PHkPsu1uL9sVhCJ nau6y02PTHbk96o SN70p9heW2aaRLh 4JzcQhUyp07be63 6tpzZfJAHSeg0aR xpqCvH8Yj0n4eyg o0qwuNSmRoZo0Sc rk4IhONdrcxavIP RoWBGBQh53BxAlX hEmg1vEdCVDEBMs osgCBZYOfbYcuPg jSzNKP0Ss2D3ic4 AgfQZ8Z2eTleSYl F4PqMPm7kOmQjHO eOkpHO6K3ckl6VW ft6BeaT4sYI0jb1 S5zGqPnq1NfLQz3 aE3FLt9Vhr6Y9Yp rEE. END KEYBASE SALTPACK SIGNED MESSAGE.

Thanks.

**Comment by strib** [comment]
I reset the folder.  Please check it out and close this if everything seems ok.  (Might require a Keybase restart.)

**Comment by fgsch** [comment]
Getting `ls: .: Input/output error` now after restart.

log ID 844106ed7ee03cceae80961c

**Comment by strib** [comment]
@mmaxim @maxtaco looks like we need to reset @fgsch's private implicit team to restore access to their private folder.

**Comment by fgsch** [comment]
Any chance this can be sorted soon? Thanks!

**Comment by strib** [comment]
Sorry, with the US holiday this week there are lots of vacations happening.  It might take a few days.

@mmaxim @maxtaco if you get time, the implicit team in question that needs resetting is `11248bea50944cb47e51024b53602d24`.

**Comment by fgsch** [comment]
@strib No worries. I completely forgot about it. Thanks for reminding me.

**Comment by op01** [comment]
Hi, I think I get the same problem. Could you please take a look at my case too

My log ID is 911e8203c3ee49c55aeb7e1c.

![image](https://user-images.githubusercontent.com/5538399/42337437-0373e5d2-80b1-11e8-9305-18e09b0f154c.png)

**Comment by mmaxim** [comment]
@maxtaco I'm not sure what you did last time, but I guess these TLFs need the same treatment.

**Comment by strib** [comment]
@op01 yeah it looks like your private folder became unreadable way back in December 2016.  
If you want us to reset your folder, please run this command on a currently-valid keybase device, and substitute the current date and time where indicated:

```
keybase sign -m "<DATE_AND_TIME>: Please reset folder /keybase/private/op01 because all the devices that have access have been revoked."
```

and post the results here.

@mmaxim @maxtaco from an initial look, it doesn't seem like op01's private implicit team has the KBFS ID set, so I don't think we'll run into that same problem.

**Comment by op01** [comment]
BEGIN KEYBASE SALTPACK SIGNED MESSAGE. kXR7VktZdyH7rvq v5weRa0zk8t0rQy rSw8wFHEPGXIuWl csGgTkjrv7KZMbh TN9p7n4RUituDDH 1h8YVAdYdd0e3jJ BF01LCi3fB9uSEx H1KlggjZ2EACaCg Cffp6uTvoQ4WVKb 2IhBjBUCPtU4Td1 OGc2cmc4yoru0WM ww2Yi5FQdRAteX2 eDh6R8QYpfLQhXQ nc6YTynfMGgoDoG 8MH0cBQkdpR4pzW Lz0V7JQnt8Yvkf1 fQLnd1NlXw4oaJe izC7dBpUUzRugVN cyD3ChYjI9yXquy 3r0HlLo0izqfR1n 7Pi2KPMPiffaCQP 8ILux5gPyRAfPxJ 8iVcpfWYYGU86y0 sA0rjTg68hycGSM 1XLJFU7NW. END KEYBASE SALTPACK SIGNED MESSAGE.

**Comment by strib** [comment]
@op01 I reset the folder.  Please check it out and close this if everything seems ok.  (Might require a Keybase restart.)

**Comment by op01** [comment]
@strib It's working now. Thanks

**Comment by fgsch** [comment]
Ping

**Comment by strib** [comment]
Sorry, I think @maxtaco is the only one who can fix this right now, and he's on vacation.

**Comment by strib** [comment]
@fgsch ok, vacation over, your situation should be cleaned up now. Any better?

**Comment by fgsch** [comment]
@strib Thanks. All working fine now.
