### ISSUE TITLE
Keybase is not accessible to Snaps in Ubuntu

### ISSUE THREAD

**Issue by da-code-a** [keybase/client#12669]
I'm running Ubuntu 18.04 (Bionic Beaver) and I've installed VSCode as my main editor because I loved the built-in SCM features and the ability to have terminal running just below my editor and a little icon tracking my changes. However, I switched my personal repo from GitHub to to Keybase.
Because VSCode runs as a Snap in Ubuntu, it doesn't seem to be able to access the system Keybase. I'm not sure if this more a bug with Keybase or VSCode/Snaps in general, but Keybase is the only thing I'm noticing it in.
Using VSCode's built in SCM module, trying to push gives me a "Keybase is not running, try run_keybase" error dialog. Using `git push` in the terminal built into VSCode (which should just be my system terminal as I can run other commands in it) also gives me the not running error. However, trying to run `run_keybase` in the VSCode terminal emulator gives me a "no such file or directory" error.
![2018-07-03-125343](https://user-images.githubusercontent.com/20977880/42239254-99cdffce-7ec0-11e8-8c51-2212ca837183.png)
![2018-07-03-125455](https://user-images.githubusercontent.com/20977880/42239255-99e670fe-7ec0-11e8-81e7-a70714c33656.png)
![2018-07-03-125651](https://user-images.githubusercontent.com/20977880/42239256-99f9a9d0-7ec0-11e8-8d0d-77cbfe7301c6.png)

**Comment by DonaldKBrown** [comment]
To Note: This is only an issue if you install VS Code with `sudo snap install vscode`. Otherwise, downloading the `.deb` file from Microsoft's website and installing with `dpkg` makes this work fine.

**Comment by Mikaela** [comment]
I am having a problem where the Firefox extension claims that Keybase is not installed. I am using Firefox from snap, so I think it's this same issue, but please do tell if I should open a new one for it.

```
name:      firefox
summary:   Mozilla Firefox web browser
publisher: mozilla
license:   unknown
description: |
<I have manually snipped Firefox advertising here as I am sure it has nothing to do with this issue.>
commands:
  - firefox
snap-id:      3wdHCAVyZEmYsCMFDE9qt92UV8rC8Wdk
tracking:     edge
refresh-date: yesterday at 13:00 EEST
channels:                                
  stable:        61.0.2-1    (118) 204MB -
  candidate:     61.0.2-1    (118) 204MB -
  beta:          62.0b18-1   (121) 204MB -
  edge:          ↑                       
  esr/stable:    60.1.0esr-2 (102) 205MB -
  esr/candidate: ↑                       
  esr/beta:      ↑                       
  esr/edge:      ↑                       
installed:       62.0b18-1   (121) 204MB -
```

* * * * *

I hope https://github.com/keybase/client/issues/9191 will fix these issues regardless of are they the same or not.

**Comment by da-code-a** [comment]
This is intended behavior for Snaps, and I was unaware of it at the time of creating this issue. Closing.
