### ISSUE TITLE
Cannot drop PGP key

### ISSUE THREAD

**Issue by matticala** [keybase/client#12696]
Hello!

I am having problems dropping my PGP key. I was trying to export its secret key but the client was complaining there was none, so I generated a new key storing the private key into keybase.

Now I want to only use the newly generated key, so I'm trying to drop the old one. **But**:

```
~ ❯❯❯ keybase pgp drop 'myKeyID'
▶ INFO Revoking KIDs:
▶ INFO   myKeyID
▶ ERROR post claims 2 existing userEKs, but server sees 1 (code 2903)
```

**Comment by maxtaco** [comment]
Ok, this is our bug.  Please ‘keybase log send’ and then @joshblum can check it out.  Thanks!

**Comment by matticala** [comment]
Thank you @maxtaco , log id is b11e7c275d3d9ced46cc381c

**Comment by joshblum** [comment]
thanks! looking

**Comment by joshblum** [comment]
Closing this, @matticala let me know if you have any further issues!
