### ISSUE TITLE
How to install keybase silently

### ISSUE THREAD

**Issue by kenkit** [keybase/client#12715]
Hi I have a project that requires I build the project on appveyor to protect the sources from thirdparty access.
However I can't seem to get the installer to work

**Comment by maxtaco** [comment]
Which platform?

**Comment by kenkit** [comment]
Windows Appveyor

**Comment by zanderz** [comment]
Do you mean you are building the installer, or trying to run our shipping .msi automatically on Appveyor? I'm not sure it will quite work but invoking the .msi with `/quiet` will at least not require any user interaction.

**Comment by kenkit** [comment]
I mean running the msi. 
Is it possible to install it from command prompt and call the cli using the same command prompt ?

**Comment by kenkit** [comment]
I'll do some more research on a system that doesn't have the client.
Thanks all the same

**Comment by zanderz** [comment]
@kenkit Yes, but there are 2 possible problems:
1. On a new install (not an upgrade), the current CMD window will not have the modified path, but Keybase always goes in %localappdata%\Keybase, so you can call it directly there.
2. More problematic is that invoking the msi will return immediately before installation is complete, so you have to come up with something creative there.
