### ISSUE TITLE
Compact UI mode on desktop

### ISSUE THREAD

**Issue by Avamander** [keybase/client#12733]
It would be nice if Keybase allowed the window to be smaller and when resized auto-hides the blue sidebar and if resized even smaller also hides the chat names (and last message). `messenger.com` is a good example of what I mean.

**Comment by Avamander** [comment]
Those who are interested, you can zoom out with `Ctrl`+`-` when using desktop clients.

**Comment by rohansingh** [comment]
Unfortunately the "zoom out" workaround also makes text size very small, so it quickly becomes unreadable.
