### ISSUE TITLE
"You accessed a private folder with x" on every boot

### ISSUE THREAD

**Issue by EmpireJones** [keybase/client#12740]
After running `tar -czf /keybase/private/strib@github,empirejones/client-12730.tgz ~/.cache/keybase/keybase.git*` per the request on 
#12730, I'm now getting this popup every time I start my computer.

![image](https://user-images.githubusercontent.com/15959998/42416708-75ceecd2-822b-11e8-9590-8adedca118f9.png)

This seems related to #6262, although I'm getting it on every boot.

Is there a way to make this not happen? Thanks!

**Comment by strib** [comment]
It's a lovely image, though, isn't it?  Your OS/distro must have put that on a list of recently-visited files or something, and loads it every time you start.  You can suppress it by clicking the "Follow" button.  If you'd rather not follow me publicly (understandable), you can `keybase follow -l strib` from the command line, to follow _locally_ just on that device.

**Comment by strib** [comment]
Oh actually, I think this is a Linux bug that I fixed on late Friday.  Following me will fix it, or you can also wait for the next linux release, probably tomorrow.

**Comment by EmpireJones** [comment]
ok, I'll try the update once it's available. Thanks!

**Comment by EmpireJones** [comment]
Fixed with latest update!
