### ISSUE TITLE
[ Feature request ] Keyboard shortcuts

### ISSUE THREAD

**Issue by cig0** [keybase/client#12744]
Actually the GUI client can be navigated using a pointer only (mouse or trackpad), please consider adding hotkeys support. Thanks!

**Comment by Kukunin** [comment]
Happened to me, when my touchpad broke. I found out it that Keybase is completely unusuable without a pointer

**Comment by cig0** [comment]
I'm closing this issue since I stopped using Keybase. If you're still affected, feel free to reference this issue in our own report -- thanks.

**Comment by krstp** [comment]
Why is this closed? Can we reopen this? This is a major issue.
