### ISSUE TITLE
error code 2512 again

### ISSUE THREAD

**Issue by bobuk** [keybase/client#12741]
absolutely the same as #11588
BEGIN KEYBASE SALTPACK SIGNED MESSAGE. kXR7VktZdyH7rvq v5weRa0zkUZHIPc 5vyOfClafXfMXXc BPZryxCdA8glB6c Fz1D3sGtP0Mv3dR bjNkG31b0j9Hq6H zRZQ5ifILwCmRgP Sfjjuh1mgXEZeyJ DZX3nDR0ZQbwKaT 7QFii19acnboztc ZByubuUhAanbqcE IcidT36lWl4iCEV MoUzJyZE8BbJJgu 9I9xZjg6nooMV9j EpisdHoVRphzcy1 HsbtgvoLmk3CQcM OCc0dvi3e2mG27T 8rxNKP0Ss2D3ic4 AgfQZ8QXQn3LQOO T8b9yA7mLTFcwn5 AOkpHO6K3ckl6VW ft6BeaT4sYI0jb1 S5zGqPnq1NfLQz3 aE3FLt9Vhr6Y9Yp rEE. END KEYBASE SALTPACK SIGNED MESSAGE.

**Comment by strib** [comment]
I reset the folder.  Please check it out and close this if everything seems ok.  (Might require a Keybase restart.)
