### ISSUE TITLE
Sharing links to files

### ISSUE THREAD

**Issue by eddic** [keybase/client#12764]
First off, epically cool project. I feel like I'm 12 years old again and discovering PGP; only this time other people I know can actually figure out how to use it!

Anyway, is there any capability to somehow "link" to a file stored in a shared or team kbfs in the chat? I've often found myself wanting to mention a specific file but I need to type out the whole path in the chat window and the person on the other end has to manually browse their way to the file. It'd be really nice to be able right-click on a file in the keybase client and "share" it through chat via some sort of keybase specific URI.

Does this functionality somewhat exist already? If it doesn't, is it a possibility?

**Comment by strib** [comment]
Doesn't exist yet, but it's on our roadmap; probably coming within a few months (but no promises on timing).

Thanks!

**Comment by eddic** [comment]
Well alrighty then. Thanks for the info and thanks again for the incredible work you guys are doing here.

**Comment by ViperGeek** [comment]
Hello Keybase coders.

Is there any updated ETA on an official keybase:// URI?  Our org has recently gone all in on Keybase, and being able to reference team docs via a shared "link" would be sweet.

_– Dave_
