### ISSUE TITLE
Multi-user support

### ISSUE THREAD

**Issue by Avamander** [keybase/client#12783]
It would be really nice if keybase apps allowed easy and effortless user switching.

**Comment by 5h4d0ww0lf** [comment]
@Avamander Sorry I don't see use in it what is the scenario?
Keep in mind that main keybase use is identity verification so you should have one account.

**Comment by Avamander** [comment]
@5h4d0ww0lf Why should one be limited to only one identity?

**Comment by boistordu** [comment]
Plus should I add that everyone as multiple faces. 
You can be a genius in astrophysics and want to be contacted privately through your specific pgp key to that effect or exchange files privately from that field of expertise.
And at the same time you could be a recovered addicted or having an uncurable sickness but you want to share thought, speak groups about it, having a mastodon instance talking about it etc and don't want other people to know it about.

So yes everyone is entitled to have multiples identities to actually channel informations according to specific criteria. So a multi-user support for the mobile, desktop and the web version is essential!

**Comment by wmertens** [comment]
I think this is a duplicate of #8586

**Comment by Avamander** [comment]
Closing as a duplicate of #8586
