### ISSUE TITLE
"KBFS: Disk case not initialised - please send feedback"

### ISSUE THREAD

**Issue by gwpl** [keybase/client#12792]
Keybase GUI Version: 0.0.0

**Comment by gwpl** [comment]
![screenshot_20180712_175115](https://user-images.githubusercontent.com/221403/42644546-2ced8e54-85fc-11e8-98f4-8c26f060e1e8.png)

First of all, when I click this notification, I do not get more info.
When I open keybase-gui I see sometimes "...FS..." errors overlayed over GUI... (it appears in random moment, I can't reproduce now to attach extra screenshot)

**Comment by gwpl** [comment]
Could it be related? 
https://github.com/keybase/kbfs/issues/1655

The issue I find it that IMHO for greated adoption error messages should be more helpful.
I can start debugging it as developer, but most users won't have skills or time to figure out "what's next step".

So you can treat this bug twofold:

* issue of KBFS storage
* issue of how it's presented to user and what clues keybase give user regarding next steps

(And in general, that maybe it's possible to make it either self fix, or display dialog to user "I can fix this and that in this and that way, do you agree [Yes/No/Later/I need more info]"

**Comment by strib** [comment]
If you do a `keybase log send`, and post the resulting ID here, we can take a look.

**Comment by gwpl** [comment]
my log id: 7de22749b69e5f413e804b1c

**Comment by strib** [comment]
You were getting a "resource temporarily unavailable" error when trying to access a database from your local disk.  It seems like that maybe you had two `kbfsfuse` processes running at once somehow as the same user.

cc: @jzila

**Comment by jzila** [comment]
FWIW this error is harmless. That said, restarting your computer should fix it.

**Comment by gwpl** [comment]
Great to know!
Still: the way it was communicated to user (me) by program was unclear. Maybe it's opportunity to polish some error messages?

**Comment by gwpl** [comment]
Btw. another error:
"ERROR CODE 218 - Async result not found in method keybase.1.SimpleFS.simpleFSReadList"

![screenshot_20180720_211052](https://user-images.githubusercontent.com/221403/43020759-63131b1e-8c61-11e8-86db-34a1fe4d2420.png)

Does it belong to this thread (and repo) or should I move this one to separate one?

**Comment by jzila** [comment]
@gwpl that is a separate issue, thanks.

**Comment by jzila** [comment]
FYI we've figured out that the original issue you saw was actually a real bug on our end, that we've since fixed. There should be an outgoing Linux build soon to resolve it.
