### ISSUE TITLE
unpacking a zip file in an encrypted folder killed the kbfs service

### ISSUE THREAD

**Issue by leitmedium** [keybase/client#12845]
After double clicking on a zip file the kbfs service died and continues to do so. 

keybase.kbfs.log shows the following error over and over:

> 2018-07-17T21:40:06.920761+02:00 ▶ [DEBU kbfs(FBO 300c6fb9) folder_branch_ops.go:2389] 0f3 Final op: sync [{off=0, len=4096}, {off=4096, len=0}]
> 2018-07-17T21:40:06.920793+02:00 ▶ [DEBU kbfs(FBO 300c6fb9) folder_branch_ops.go:2389] 0f4 Final op: rename .BC.T_adGmQH -> .DS_Store (FILE)
> panic: Unknown ID suffix  0
> 
> goroutine 317 [running]:
> github.com/keybase/kbfs/tlf.ID.Type(0x0, 0x0, 0x0)
>         /Users/build/go/src/github.com/keybase/kbfs/tlf/id.go:252 +0x65
> github.com/keybase/kbfs/libkbfs.buildCanonicalPathForTlf(0x0, 0x0, 0xc423df0e28, 0x1, 0x1, 0x1, 0x1)
>         /Users/build/go/src/github.com/keybase/kbfs/libkbfs/path.go:72 +0x2b

Is it possible, that the filename ".DS_Store" is the issue?

my log id: 5c0376b0eec6da4d5b677b1c

**Comment by strib** [comment]
Hi @leitmedium, thanks for the report and sorry for the inconvenience.  This is a dup of #12817, and in that ticket there's a link to a build that should fix the problem for you.  Let's track any followups there.  Thanks!
