### ISSUE TITLE
I am unable to import my GPG created key into keybase

### ISSUE THREAD

**Issue by milanaleksic** [keybase/client#12895]
To get the idea how I got those files, I was simply following reproducable manual from https://github.com/drduh/YubiKey-Guide

my log id: 24b7eef59eecb3842f05511c

**Comment by maxtaco** [comment]
```
70264 2018-07-20T15:39:14.877056+02:00 ▶ [DEBU keybase gpg_cli.go:357] 3589 | running Gpg: /usr/bin/gpg2 --no-tty --with-colons --fingerprint -K
```
returns empty, we can't do anything

**Comment by milanaleksic** [comment]
Alright. This is because during the course of that tutorial I followed the env variable `GNUPGHOME` is set to a temp dir, and the env is not visible to the `keybase` because probably it's not the same application that runs the CLI and the one that executes import I guess, right?

Is there a trick how to make sure the background agent can handle this case with different temporary `GNUPGHOME`?

**Comment by milanaleksic** [comment]
I searched previous issues, I was able to resolve this by combining solutions to other issues. Putting it here for the future:

```
keybase config set gpg.command $GNUPGHOME/test.sh
cat $GNUPGHOME/test.sh
> #!/bin/bash
> export GNUPGHOME="..."
> /usr/bin/gpg "$@"
keybase pgp import --multi
```

Thanks for the hint that no output was available, that was the key clue what piece was missing
