### ISSUE TITLE
ERROR CODE 1600 - 414 Request-URI Too Large in method keybase.1.teams.teamRemoveMember

### ISSUE THREAD

**Issue by qntmpkts** [keybase/client#12910]
Cannot remove a team member. Full error code:

`Error: ERROR CODE 1600 - 414 Request-URI Too Large in method keybase.1.teams.teamRemoveMember at new i (file:///opt/keybase/resources/app/desktop/dist/index.bundle.js:1:431816) at file:///opt/keybase/resources/app/desktop/dist/index.bundle.js:1:432345 at s (file:///opt/keybase/resources/app/desktop/dist/index.bundle.js:1:432384) at _rpcClient.invoke.t (file:///opt/keybase/resources/app/desktop/dist/index.bundle.js:1:233890) at file:///opt/keybase/resources/app/desktop/dist/index.bundle.js:1:1753053 at e.t.Deferrals.e._call (file:///opt/keybase/resources/app/desktop/dist/index.bundle.js:1:1638927) at file:///opt/keybase/resources/app/desktop/dist/index.bundle.js:1:1639078 at s (file:///opt/keybase/resources/app/desktop/dist/index.bundle.js:1:1638707) at e.t.Deferrals.e._fulfill (file:///opt/keybase/resources/app/desktop/dist/index.bundle.js:1:1639037) at s (file:///opt/keybase/resources/app/desktop/dist/index.bundle.js:1:1638241)`

**Comment by maxtaco** [comment]
Please do `keybase log send`

**Comment by qntmpkts** [comment]
The submitter notes the log ID has been provided.
