### ISSUE TITLE
Unclearable team notification

### ISSUE THREAD

**Issue by benjumanji** [keybase/client#12939]
Hi,

This is driving me a little nuts. I have a notification that I _cannot_ clear from the UI. I have tried clicking everything it's driving me mad because it means I can never see when there are _new_ notifications by glancing at the tray. This is persistent across at least android and linux (the clients I use).

![2018-07-24t14 16 40_160x45](https://user-images.githubusercontent.com/290429/43140654-34bd5516-8f4c-11e8-9645-81320718ff55.png)

Linux:
Client:  2.4.0-20180720182402+3050d74e9b
Service: 2.4.0-20180720182402+3050d74e9b

Android:
2.3.0-20180710..+80a2aa7a43

My account is bene on keybase.

**Comment by benjumanji** [comment]
cc1b9c953bc8bdd4b40a851c

Thanks!

**Comment by benjumanji** [comment]
I don't know if you did anything to clear this, but the notification is now gone.

Thanks!

**Comment by jairoxyz** [comment]
I have the same problem.

my log id: eee2a50d1ec03f1ae50fa71c

**Comment by jairoxyz** [comment]
It really looks the same as in the first post. I've sent it via keybase.

Thanks for helping.

**Comment by crackmac** [comment]
I am seeing the same issue and the screenshot looks the same (number is different)
Log: 1b15bcb593a7dee67c47f11c

**Comment by rr-jonathan-lundy** [comment]
seems related: #13822

**Comment by rr-jonathan-lundy** [comment]
i have the same problem. 6b63b7299b5200bd1d2ef41c

**Comment by samuelmanzanera** [comment]
I also have the same issue: 655fa08bb4a0fd5c5105ac1c
