### ISSUE TITLE
git-remote-keybase error: (1) Can't get TLF private key for key generation 1

### ISSUE THREAD

**Issue by poblahblahblah** [keybase/client#12973]
Keybase GUI Version: 2.3.0-20180710171051+64615d6258

Pulling and Cloning a git repo appears to be broken for me.

```
me@computer:~/src/personal/blog  git:(master) $ git pull
Initializing Keybase... done.
Syncing with Keybase... Can't get TLF private key for key generation 1
git-remote-keybase error: (1) Can't get TLF private key for key generation 1

me@computer:~/src/personal  $ git clone keybase://private/pobrien/blog
Cloning into 'blog'...
Initializing Keybase... done.
Syncing with Keybase... Can't get TLF private key for key generation 1
git-remote-keybase error: (1) Can't get TLF private key for key generation 1
```

Not sure what changed on my end. I can still access everything else in keybase.

**Comment by strib** [comment]
@maxtaco implicit team `bd4e5ab26ef6f52bfbd56f97d47ec924` needs to be reset, because it contains the ID of an old, reset TLF.

**Comment by strib** [comment]
@poblahblahblah The bad data has been cleared out now.  Is it working better now?  (Might need a keybase restart.)

**Comment by poblahblahblah** [comment]
Much better - thank you @strib and @maxtaco
