### ISSUE TITLE
Can't access private folder

### ISSUE THREAD

**Issue by dfischer** [keybase/client#13018]
Hi, it seems I cannot access my private folder. I did in the past have my account reset so maybe that is why?

```
➜ cd /keybase/private/dfischer
cd: permission denied: /keybase/private/dfischer
```

```
BEGIN KEYBASE SALTPACK SIGNED MESSAGE. kXR7VktZdyH7rvq v5weRa0zkYg6RQr BMoZB5AtmJTYcOl qMQAmupZAoIHg41 1xQkTibtelnagEs OtlRQth243QC3rC 5zAD2ADaGpi7CAg jNDvSH4Bsw97A9K qd3KSLMhnWQXSqa 6SYV2EqkdQkR0bg z4Clu9UGs0P9siw c5yMoZsWetxAz7d r2UcjwSPwXhSgb5 GjkeTO89ym7fQlQ 3hGe8PheJ7z3VR0 xuI7sWfjXQJOIDn adTDeAYEX1XyLcH wSEN6mvldIYajFd 2l3NPdT3qSCVWkj q3gsMKWNEVb5xoX OOzQeKGi6ahq0NF L2o193Xn0VhE4nd Xnsmxi9scmClEW9 ovbAherEAI. END KEYBASE SALTPACK SIGNED MESSAGE.
```

**Comment by dfischer** [comment]
Log ID: 22c45258391df0103763eb1c 

Thanks!

**Comment by strib** [comment]
Looks like mounting the file system failed:
```
Mounting the filesystem failed: exit status 2
```

Some thing to check:
* https://github.com/keybase/client/wiki/Troubleshooting
* Try completely quitting Keybase, then `rmdir` the Keybase volume directory in `/Volumes`, and start things up again.
* `keybase install -c --debug fuse`

**Comment by dfischer** [comment]
Solved (restarted my comp as `rmdir` wasn't working, had weird errors) also saw two dirs `Keybase (dfischer)` and `Keybase`
