### ISSUE TITLE
ERROR CODE 218 - Keybase services aren't running - KBFS client not found.

### ISSUE THREAD

**Issue by pwelch** [keybase/client#13020]
### Issue
Unable to view/use Keybase Files

my log id: 1669eb4c0b470701d8e9571c

```
Error: ERROR CODE 218 - Keybase services aren't running - KBFS client not found. in method keybase.1.SimpleFS.simpleFSList
```

### System Information
- macOS 10.13.6
  * Just upgraded from macOS 10.12. Keybase Files was working before the upgrade.
- Keybase GUI Version: 2.3.0-20180710171051+64615d6258

### Full Error Message
```
Error: ERROR CODE 218 - Keybase services aren't running - KBFS client not found. in method keybase.1.SimpleFS.simpleFSList at new i (file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/index.bundle.js:1:420688) at file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/index.bundle.js:1:421217 at s (file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/index.bundle.js:1:421256) at _rpcClient.invoke.t (file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/index.bundle.js:1:229672) at file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/index.bundle.js:1:1743390 at e.t.Deferrals.e._call (file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/index.bundle.js:1:1628073) at file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/index.bundle.js:1:1628224 at s (file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/index.bundle.js:1:1627853) at e.t.Deferrals.e._fulfill (file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/index.bundle.js:1:1628183) at s (file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/index.bundle.js:1:1627387)
```
### Solutions Attempted
In the past I have seen the issue that macOS has a limited number of kernel extension slots.

I unloaded the ones I did not need and restarted Keybase but it doesn't seem to directly fix the issue.
kext unloaded:
```
 sudo kextunload -b org.virtualbox.kext.VBoxNetFlt
 sudo kextunload -b org.virtualbox.kext.VBoxNetAdp
 sudo kextunload -b org.virtualbox.kext.VBoxDrv\n}
 sudo kextunload -b org.virtualbox.kext.VBoxDrv
 sudo kextunload -b com.valvesoftware.SteamInput
```
kbfuse seems to be running:
```
kextstat | grep kbfuse
  173    0 0xffffff7f85db2000 0x19000    0x19000    com.github.kbfuse.filesystems.kbfuse (3.6.3) CF01E167-07E1-35DD-BDDE-82E1295AE185 <7 5 4 3 1>
```
I currently only have 3 kext loaded (including kbfuse): `kextstat | grep -v com.apple`

**Comment by pwelch** [comment]
@strib I installed the test build you referenced and it seems to have fixed the problem! 🎉 

Thanks for the fast response! 

Any idea when an official release will have the patch?

Thanks again

**Comment by strib** [comment]
Hopefully our next release will be next week, but it depends on how soon some other projects wrap up.  Sorry for the inconvenience.

**Comment by pwelch** [comment]
No worries, it's software and sometimes there are bugs. 

Thanks for helping make awesome privacy software! 

Closing as resolved for now since the test build got me working. Will upgrade on the next release.

**Comment by turnkit** [comment]
Just got this error today with what I think is the current version,
 "Error: ERROR CODE 218 - method 'GetPreferredMountDirs' not found in protocol"
