### ISSUE TITLE
Git pull hangs

### ISSUE THREAD

**Issue by admmasters** [keybase/client#13048]
git pull keeps hanging for me:

git clone keybase://private/admmasters/xxx
Cloning into 'xxx'...
Initializing Keybase... done.
Syncing with Keybase...

my log id: f1de438fba4837321caf401c

**Comment by strib** [comment]
This is hanging trying to verify an identity.

@patrick @maxtaco search the client logs for XKkHr38YkzIvuvusj2dr_A, looks like an Identify that doesn't return.

**Comment by strib** [comment]
(ping @patrickxb, I originally had the wrong patrick handle above)

**Comment by maxtaco** [comment]
Hey @strib, as was the case last time, this is electron being broken and not replying to RPCs.

@admmasters: did you just come out of sleep?

@mmaxim: this might be that power-save bug again

**Comment by maxtaco** [comment]
cc: @keybase/react-hackers

**Comment by maxtaco** [comment]
@admmasters likely killing the app and starting it again will solve your problem

**Comment by admmasters** [comment]
Hi apologies for the late reply, yes that did work in the end. Thanks!
