### ISSUE TITLE
Allow provisioning via gpg without importing secret key to local key storage

### ISSUE THREAD

**Issue by patrickxb** [keybase/client#1308]
Currently, to provision an installation of keybase via GPG, keybase uses GPG to export a secret key and import it into its local encrypted key store.  It is never sent to the server, however we could use gpg to sign the provisioning statement without importing a secret key.

**Comment by maxtaco** [comment]
keybase benefits from its own local copy of a PGP secret key to run `pgp sign` and `pgp decrypt`.  If you don't need these commands, keybase doesn't need access to your secret key after the initial provisioning step.  If your use case doesn't include `pgp sign` or `pgp verify`, :+1: here.

**Comment by dainnilsson** [comment]
This also doesn't work when your private key is on an OpenPGP-card device (such as a YubiKey NEO), as the private key cannot be exported. So, a :+1: from me!

**Comment by koluke** [comment]
I'm in the same situation as @dainnilsson.  My encryption keys are on an OpenPGP card, and I am unable to import them into keybase.  :+1: from me as well.

**Comment by maxtaco** [comment]
Should be available in the next release. The fix just went in yesterday.
Thanks!

**Comment by maxtaco** [comment]
PR #1359

**Comment by nlopes** [comment]
:+1:

**Comment by maxtaco** [comment]
Should be closed as of v1.0.1. We're having some issues with Yubikeys and offline primary keys though.
