### ISSUE TITLE
Unable to uninstall on Windows 10

### ISSUE THREAD

**Issue by ischyrus** [keybase/client#13114]
I am unable to uninstall KeyBase, which has been preventing me from upgrading.
![uninstall](https://user-images.githubusercontent.com/41187/43587423-0fec7f6c-961f-11e8-95ac-9e294065db0c.png)

**Comment by ischyrus** [comment]
I think I just need to download the MSI for 1.0.40.5. How can I get the download url for that?

**Comment by maxtaco** [comment]
cc: @zanderz

**Comment by zanderz** [comment]
It may be easier to just run the msi cleaner from Microsoft:
 https://support.microsoft.com/en-us/help/17588

But if you like, the above installer is still at http://s3.amazonaws.com/prerelease.keybase.io/windows/Keybase_1.0.40-20180123113512%2B895471b.386.exe

**Comment by ischyrus** [comment]
Thanks! Finally got back to this. 

I ended up having to run the cleaner, which then enabled me to successfully use the re-downloaded old version to uninstall.
