### ISSUE TITLE
2 Stuck "People" Notifications

### ISSUE THREAD

**Issue by ProgrammingByPermutation** [keybase/client#13134]
I have two notifications attached to "People" that I cannot clear on my Windows 10 x64 system. I tried reinstalling but it was still present after the re-install. I haven't had a new follow in 2 months so I'm not sure what the 2 notifications are for or how to clear them.

my log id: fe1e249cf4514d5cdbb1171c

**Comment by maxtaco** [comment]
should be fixed, let me know if not...

**Comment by ProgrammingByPermutation** [comment]
All fixed! Closing.

**Comment by maxtaco** [comment]
Cool, sorry about that.
