### ISSUE TITLE
KBFS Restarting

### ISSUE THREAD

**Issue by benkietzman** [keybase/client#13174]
KBFS appears to restart every time I attempt to modify a file in my private folder.  I see the following in /var/log/syslog:

kbfs.service: Main process exited, code=exited, status=2/INVALIDARGUMENT.

I'm not sure why KBFS keeps restarting, but I am unable to modify files in my private folder.

my log id: d6626cbfb4a6086ea97d711c

**Comment by benkietzman** [comment]
Reading from the file-system appears to work okay.  It is when I attempt to write that it has a problem.  I do not encounter this issue when interacting with other shared private folders or team folders.  So far it has only cropped up in my own private folder.  Even my public folder works okay.  It is only happening within my private folder.

**Comment by strib** [comment]
Thanks.  I put up keybase/kbfs#1722 to fix this, as soon as I merge it I'll make a new linux release that includes it.  Sorry for the inconvenience.

**Comment by benkietzman** [comment]
Thank you for the quick turn around!

**Comment by strib** [comment]
No problem.  The new release `2.5.0-20180807010541.97d81021e1` is out, please give it a try when you get a chance and let me know if it helps.

**Comment by benkietzman** [comment]
You are the man!  That did it.  Working much better now.  Thank you so much!
