### ISSUE TITLE
O RLY? (aka, show me the proof this message was sent by that person)

### ISSUE THREAD

**Issue by jcayzac** [keybase/client#13204]
Hi there!

It would be really sweet if the "Encrypted and Signed" dialog/menu shown when clicking on `…` next to a chat message allowed to copy the signature. Otherwise I'm not sure I see the point in supporting message deletion/explosion, since you can't really prove I wrote the non-deleted messages in the first place (you could be using a custom built of the keybase client that just shows messages on your end that I never wrote).

Thank you!

**Comment by cjb** [comment]
It sounds like you might be thinking that GPG keys are used for Chat message.  This isn't true -- they're signed using Keybase device keys, which aren't GPG keys.

In which case, I don't think your feature helps: if you are running a build of Keybase that you can't trust (how and why?), it wouldn't be trustworthy to perform the signature verification properly either.

**Comment by jcayzac** [comment]
@cjb my assumption was that messages could be verified, indeed.

The scenario I had in mind was when user A wants to frame user B for e.g. harassment. It seems easy enough to show a message on user's A machine claiming it's coming from user B, encrypted and signed. But since user B's messages can't be verified using their public key anyway, well…
