### ISSUE TITLE
[ Idea ] Make Keybase the best secrets manager out there!

### ISSUE THREAD

**Issue by cig0** [keybase/client#13253]
We ❤️ Keybase!

- I been  a long time user of KeePass in it's many inceptions, however it was never thought to be 'cloud-native' and as such it is a pain to keep a KP database synced over different devices
- Gopass is a gorgeous alternative to the venerable `Pass', however it's a deal breaker for my phone
- 1Password: it is multi-platform/multi-device, I like it very much and have been using it for little more than year now; problem with 1Password is that the company is greedy as fuck and I'm not going to shell out a thick stack of bucks again for a full version since they don't offer an upgrade path. Also, it's closed source and when security is a concern, F/LOSS wins
- Currently migrating my 1Password stuff over Bitwarden, highlights: open-source, multi-platform and multi-device, cloud-ready, possibility to self host your vault(s) running a stack of Docker containers, premium version offers added functionality for just $10/y -- I gladly already made my contribution. However it has some quirks that I hope will be ironed out in the future
- Lastpass / Dashlane / Sticky / whatever: thanks, but I prefer to stick with a F/LOSS solution. Also, Lastpass was breached some time ago, by the time (IIRC) they bought (and then obliterated) Xmarks; I read that Dashlane makes it almost impossible to export your data in a universal readable format and about the rest of them, I haven't heard good things or at least something that makes me want to give them a spin

Maybe there's space to make Keybase also the goddamn best secrets manager in the world?

If you're still reading up to this point, thanks from the bottom of my heart.

**Comment by koyuawsmbrtn** [comment]
Would be a hella nice idea since I'm currently saving my passwords at Google

**Comment by cig0** [comment]
Give a check to Bitwarden, like 1Password or LastPass but 100% open source — and they also provide a super easy strait forward way to host the vault yourself using Docker and a local volume ;)

**Comment by MisterY** [comment]
It might be preferable to utilize existing "best secrets managers out there" and simply integrate better with them? That would be more in line with Keybase's vision statement.
For this, we would need a reliable file sync (PC, mobile), exposing the offline files in the mobile clients. Or creating addons for clients (KeePass or KeePassXC on a PC; KeePass2Android, etc.) which allow reading and writing the key file from/to KBFS.
I would prefer this option since the existing password managers work fairly well and there is no need to reinvent the wheel.

**Comment by cig0** [comment]
Thanks for your feedback @MisterY.

It has been a while since I've been using Bitwarden myself (tried a lot of similar apps), and I love it.

*However* I'd prefer to have that functionality consolidated into a single app - Keybase here - that already provides admirably high levels of comms security and entities validation.

Cheers

**Comment by elisboa** [comment]
There is an initiative where you combine `pass` + gpg + keybase + git, as you can see [here](https://www.youtube.com/watch?v=8_L6XljCZzA). Hope you like it @cig0

**Comment by koyuawsmbrtn** [comment]
Bitwarden is good, I don't trust Zoom/Keybase anymore

**Comment by cig0** [comment]
Hey @elisboa, thanks for the heads up! However, following the acquisition of Keybase by Zoom, we all moved away to Matrix.org for our secure communication needs.

As @koyuawsmbrtn suggested, personally I've been using Bitwarden since a while, but it still has some quirks and constraints that I can't fully understand, mostly design choices by its developers, like the inability to offline save a record (i.e. your internet connections goes off), or being unable to create a note long enough to store a GPG key.

I'm considering stick to it though with my data being stored in a self-hosted vault, since no doubt it is handy to be able to access the it when on the move, but I'm still looking for a better solution.

Anyway, as I'm not using KB anymore I don't see any need to keep necrobumping this issue, feel free to reproduce it on your own if anything here is still relevant to you :)

Take care you'll!
