### ISSUE TITLE
KBFS says my device has no valid public keys

### ISSUE THREAD

**Issue by g-a-c** [keybase/client#13272]
I was trying to use KBFS (which I've never really been able to use before due to the limitations around slot numbers and the use of FUSE). As of this morning I had two devices provisioned, a macOS laptop and an Android phone. macOS tells me that I can't access my own private folder because I don't have a valid public key, and that I can fix this by logging into another device and granting access. I didn't see anywhere on the Android app to grant this, so I installed Keybase on another computer, but didn't see any options there either.

So for all intents and purposes, my KBFS account is now broken. Almost definitely my fault for revoking old devices, but oh well.

Given that there's no data on there that I care about (anything that is stored there is long forgotten and I don't need it) is there a way to simply reset my account, but keep my Keybase username, and I can then setup my devices and proofs from scratch?

my log id: 7eaefab2e08cd895aa52041c

**Comment by strib** [comment]
Yes, it looks like you revoked all the devices that could have accessed your private folder.  
If you want us to reset your folder, please run this command on a currently-valid keybase device, and substitute the current date and time where indicated:

```
keybase sign -m "<DATE_AND_TIME>: Please reset folder /keybase/private/gac because all the devices that have access have been revoked."
```

and post the results here.

**Comment by g-a-c** [comment]
BEGIN KEYBASE SALTPACK SIGNED MESSAGE. kXR7VktZdyH7rvq v5weRa0zkR0SERn 98GPT2ESI8MOxAP QzvA8lzjxVDAi8H kxXlwZLzAjpPQKL IqBNs4uM0MWXRvk hIjMgvtSrUD3wy8 e31YOhAWGs3rdCu 5EBEMjL3qKT46OA dh3QpMjJHgp51Bc 4K2Nt5Ecp9c2ZJe iasfb5TEcsFA07E 0YASkHv1uR8uDZm IwI6EQjQfzRUp7I Dsi1YDnUMroughU m6WLVr23zTcpW3y 8asPlNIOLAodlq0 1YJNzdWa7Uy5bfj K1NSkEUuoEpjIF1 jvtg707skQRobnl dS4tswWu0K2m4Pg RgRIFm7FM0l1Qcs vleS4Oae5LengE0 BV8kflGqAHqY. END KEYBASE SALTPACK SIGNED MESSAGE.

Thanks!

**Comment by strib** [comment]
I reset the folder.  Please check it out and close this if everything seems ok.  (Might require a Keybase restart.)

**Comment by g-a-c** [comment]
Seems good to me, no more I/O errors when creating files. Thanks for your help!
