### ISSUE TITLE
git-remote-keybase error: (1) Can't get TLF private key for key generation 1

### ISSUE THREAD

**Issue by sean666888** [keybase/client#13280]
`sean@terra:~/Documents$ git clone keybase://private/sean666888/test
Cloning into 'test'...
Initializing Keybase... done.
Syncing with Keybase... Can't get TLF private key for key generation 1
git-remote-keybase error: (1) Can't get TLF private key for key generation 1
sean@terra:~/Documents$`

![keybase_005](https://user-images.githubusercontent.com/7919941/44060321-6c0bae0c-9fa8-11e8-8072-b3050e9d1e2c.png)
![selection_006](https://user-images.githubusercontent.com/7919941/44060359-910c01ac-9fa8-11e8-842a-f127fd64b293.png)

my log id: 80cd8344bcd003289254601c
my log id: d65862b8020b01f0df16c41c

**Comment by strib** [comment]
@sean666888 this should be fixed now.  It was related to the fact that we manually reset your folder back in #6426.  If things look ok now, please close this out.

**Comment by MunifTanjim** [comment]
Facing the same error:

```
[munif:~] $ keybase fs ls /keybase/private/muniftanjim\ \(files\ before\ account\ reset\ 2018-08-14\)/
▶ ERROR Can't get TLF private key for key generation 2
```

**Comment by strib** [comment]
@MunifTanjim You can't read files from before you reset your account, so that's working as expected.

**Comment by MunifTanjim** [comment]
@strib  but `keybase fs rm` is not working too. Is there absolutely no way to delete that folder?

**Comment by strib** [comment]
@MunifTanjim you can ignore the folder in the Keybase GUI, or if you have the file system integration enabled, you can `rmdir` it.

**Comment by MunifTanjim** [comment]
`keybase fs rm`, `rmdir`, `rf -rf` nothing works.

```
[munif:/keybase/private] $ rmdir "muniftanjim (files before account reset 2018-08-14)"
rmdir: failed to remove 'muniftanjim (files before account reset 2018-08-14)': Input/output error
[munif:/keybase/private] 1 $ rm -rf "muniftanjim (files before account reset 2018-08-14)"
rm: cannot remove 'muniftanjim (files before account reset 2018-08-14)': Input/output error
[munif:/keybase/private] 1 $ keybase fs rm "/keybase/private/muniftanjim (files before account reset 2018-08-14)"
▶ ERROR Can't get TLF private key for key generation 2
```

Seems like the only option is to ignore it. It's nothing serious but it just bugs me. There should be an option for force removing unwanted directories.

Anyway, thanks for looking into it. :smiley:

**Comment by strib** [comment]
`rmdir` should be doing exactly the same thing as ignoring in the GUI, but I guess there's a bug there.  Anyway, it's unrelated to the rest of this issue -- if you want me to look into it, feel free to open a new issue and provide a log ID from `keybase log send` after trying an `rmdir`.

**Comment by sean666888** [comment]
Fixed for me
