### ISSUE TITLE
--no-self-encrypt is not doing what I would expect

### ISSUE THREAD

**Issue by johnraz** [keybase/client#13296]
Hi there,

Maybe I'm missing something but I have the feeling that the `--no-self-encrypt` flag is doing nothing:

```
┌─[john]
└─▪ keybase encrypt --no-self-encrypt -i fixtures/hello.txt -o /tmp/hello.txt.enc chris
┌─[john]
└─▪ keybase decrypt -i /tmp/hello.txt.enc
Message authored by johnraz
Hey! Hello!!
┌─[john]
└─▪ keybase encrypt -i fixtures/hello.txt -o /tmp/hello.txt.enc chris
┌─[john]
└─▪ keybase decrypt -i /tmp/hello.txt.enc
Message authored by johnraz
Hey! Hello!!
```

I'm going to give the code a look but figured I would still post that here too.

**Comment by AMarcedone** [comment]
Hi! Thanks for reporting this... I can reproduce it, and it is not the expected behavior. 

The bug was probably introduced in the latest version, we are in a transition phase with respect to which keys are used to encrypt saltpack messages. 
Will put in a fix for the next release.

**Comment by AMarcedone** [comment]
Fixed! Thanks again for letting us know!

**Comment by johnraz** [comment]
Splendid!
