### ISSUE TITLE
KBFS does not start (and can't reinstall)

### ISSUE THREAD

**Issue by M-Pixel** [keybase/client#13316]
Context:  Problem began to occur following a hard-shutdown.
Platform:  Windows 10
Symptoms:

- KBFS drive is not available.  
- GUI fails to load.
- Installer fails with "The specified account already exists"

Rebooting does not help.

my log id: 1e48bc10c2043a64ad978c1c

**Comment by M-Pixel** [comment]
Fixed by uninstalling before attempting to reinstall.

**Comment by kode54** [comment]
I was unable to fix it by uninstalling it first. Now it just says "Gathering required information...", the meter fills up, then it quits.

**Comment by taruti** [comment]
CC @zanderz installer broken at least?

**Comment by zanderz** [comment]
@kode54 What does `keybase version` say? Can you do a `keybase log send`?

**Comment by kode54** [comment]
I got it to install successfully by deleting the HKCU\Software\Keybase key, then reinstalling. It also managed to change the KBFS mount to L: instead of K:.
