### ISSUE TITLE
Keybase ui segfault after glibc upgrade on Antergos glibc 2.28-1

### ISSUE THREAD

**Issue by mikaelkall** [keybase/client#13335]
Keybase ui segfault after glibc upgrade on Antergos glibc 2.28-1

my log id: 8fcb994c0887962aaba6d41c

**Comment by AWildBeard** [comment]
I can confirm I'm getting the same issue under Arch Linux with glibc 2.28-1. 

my logs: 2505b18b544b1edbd6b64d1c

**Comment by jerryaldrichiii** [comment]
Also seeing the same with keybase-bin 2.6.0_20180816164108+2154e265f3-1

**Comment by AWildBeard** [comment]
I updated again, got a kernel update, a glibc update to 2.28-4, and a keybase update to 2.6.0_20180815194228+604cfa0d29-1

Its working fine at this stage, but I see on the AUR that there is indeed a newer keybase I need to update to. I'm in the middle of a project right now but I will see if I can upgrade later and report back. Think this might be a glibc problem that just got fixed today on the glibc end? I.E. glibc 2.28-4?

**Comment by AWildBeard** [comment]
Upgraded keybase to: 
keybase-bin 2.6.0_20180817210538+0b2dcf191f-1

And everything seems to be working just fine.

Like a phantom this segfault has gone away as fast as it came for me.

**Comment by jerryaldrichiii** [comment]
I can also confirm that upgrading to glibc-2.28-4 and keybase-bin_2.6.0_20180817210538+0b2dcf191f-1 fixed the issue.

What a strange couple of days @AWildBeard.

**Comment by mikaelkall** [comment]
Resolved

**Comment by eli-schwartz** [comment]
This is really just #13180 and therefore https://github.com/electron/electron/issues/13972 (an error in electron itself generating invalid code).

It's worked around by the glibc update, and fixed properly by the electron 2.0.8 update.
