### ISSUE TITLE
Repeated installations (or upgrades) add to PATH unnecessarily (windows)

### ISSUE THREAD

**Issue by rivy** [keybase/client#13454]
Keybase GUI Version: 2.5.1-20180808131430+bbc9797a57

When installing or upgrading, the Windows client adds it's path to PATH, even if it is already present. This leads to a larger and larger PATH with repeated iterations of "C:\Users\...\AppData\Local\Keybase" at the tail.

**Comment by maxtaco** [comment]
cc @zanderz

**Comment by rivy** [comment]
@maxtaco , @zanderz 
FYI ... this is still a problem with Keybase GUI Version: 2.7.2-20181003093825+89c6c11dc6

**Comment by maxtaco** [comment]
@zanderz can you take a look?

**Comment by rivy** [comment]
+bump ( @maxtaco @zanderz )
... still an issue as of "keybase version 2.9.0-20181029140609+02197a56e8"

**Comment by rivy** [comment]
Thanks for the attention.

It looks like the problem is the trailing backslash, used on the WIX installer side (which, I believe, is there by design).

There's a lot of variation in path style for paths added to `PATH`, with the narrow majority edging towards no trailing slash. I like, and have standardized my `PATH`, to the no trailing backslashes style. So, it must be that WIX doesn't see my existing `PATH` entry as a match when installing / updating `keybase` and is adding the additional entry.

I can special case my normalization to skip that entry which should fix the issue.

I would, however, like to request an option to not modify my `PATH` at all for install and updates.

P.S. Note to self ... [SO information on WIX path backslash manipulation](https://stackoverflow.com/questions/947141/remove-trailing-slash-from-paths-in-wix).

**Comment by rivy** [comment]
# ⚰️
