### ISSUE TITLE
Android Scrolling

### ISSUE THREAD

**Issue by lukefrasera** [keybase/client#13510]
Currently on Android on the Pixel 2XL and Pixel 2 phones having a scrolling issue that makes it difficult to scroll.

Description:

When scrolling in a conversation the only viable method is to slowly scroll up and then completely stop moving with your finger before letting go to continue scrolling. It appears that the velocity computed from a flicking scroll gets negated resulting in a bounce back of the messages. It is as if you scroll quickly and as soon as you let go the message scrolls the other way.

**Comment by JohnTheodore** [comment]
I also have this same issue, can confirm. It's super annoying, it breaks scrolling in a pretty bad way.

**Comment by yermakova** [comment]
Also having this issue, makes using the platform very unpleasant. I have a pixel 2.

**Comment by lukefrasera** [comment]
Seems to have been resolved in the latest released version of the Android keybase app.
