### ISSUE TITLE
Keybase causes a complete system freeze on MacOS Mojave 10.14 Beta (18A377a)

### ISSUE THREAD

**Issue by meeDamian** [keybase/client#13537]
Every time Keybase is launched, it causes a cascade of problems that end up with a necessity to manually power off MBP by holding the power button, and then quickly `rm -rf /Applications/Keybase.app` upon reboot (as Keybase automatically adds itself to startup items) frequently necessitating multiple forced reboots :/. 

Some of the symptoms include:

* Finder being completely unable to access any files:
![img_20180831_163331](https://user-images.githubusercontent.com/526657/44906140-46ab2900-ad3e-11e8-9626-2eb7c2da2ab7.jpg) <img width="158" alt="macos 2018-08-31 at 16 40 18" src="https://user-images.githubusercontent.com/526657/44906216-7e19d580-ad3e-11e8-9412-382958463f69.png">

* Any shell command interacting with the file system hangs indefinitely and becomes impossible to interrupt:
<img width="358" alt="macos 2018-08-31 at 16 33 10" src="https://user-images.githubusercontent.com/526657/44906208-78bc8b00-ad3e-11e8-9d7d-bfda5a52821e.png">

* Gradually all apps become unresponsive and hang indefinitely, with the OS being unable to (force) kill them nor reboot.

**I'm happy to provide any info required**, ideally if it doesn't require running Keybase client…

Here are the logs I've found, and can provide (if they don't contain any sensitive data):

```
Keybase.app.log                                               keybase.service.log
Keybase.app.log.1                                             keybase.service.log-20180629T105625+0700-20180704T102128+0700
keybase.git.log                                               keybase.service.log-20180802T091856+0700-20180807T122430+0700
keybase.kbfs.log                                              keybase.start.log
keybase.kbfs.log-20180221T132226+0700-20180223T144655+0700    keybase.updater.log
keybase.kbfs.log-20180605T112419+0700-20180607T223602+0700
```

**Comment by strib** [comment]
@meeDamian Thanks for the report.  I haven't heard from others that Keybase causes problems like this on Mojave, so I'm a little stumped.  I assume you had the Finder extension installed?  (If not, it seems pretty unlikely that Keybase could be so disruptive.)

That extension uses osxfuse, and there have been some reports of issues with it (https://github.com/osxfuse/osxfuse/issues/508), but nothing like this.  It might be a good idea for us to upgrade though.

Have you looked in any of your kernel/boot logs for any panics related to Keybase or KBFS?

You might try uninstalling the keybase kernel extension (`kextunload`).

If you can get me those logs you mention, I'll take a look through them and see if there's anything unusual.  Normally you could do that with `keybase log send`, but if that doesn't work for you you can zip them up and put them somewhere for me to download.  The logs don't contain super sensitive data, but they will reveal who you've interacted with on Keybase, and the names of files and directories you've accessed in KBFS.

**Comment by meeDamian** [comment]
I'm not sure if I had "Finder extension" installed, but keybase fs used to be available under `/keybase/…` (if that answers the question?).

Logs were almost 700Mb, so here's a compressed version: https://www.dropbox.com/s/8gg9pi62l03c7lw/keybase-logs.7z?dl=0

> Have you looked in any of your kernel/boot logs for any panics related to Keybase or KBFS?

I'm sorry, I wouldn't know how, but I'm happy to run commands and provide output :).

**Comment by strib** [comment]
Hmm, from the logs I don't see any issues mounting the file system under the usual `/Volumes/Keybase` location.  (`/keybase` is a separate mountpoint that redirects to the `/Volumes` one.)

I'd start by looking in `/var/log/system.log` and `/var/log/kernel.log`, to see if there's anything related to keybase, or kbfs, or the keybase kernel extensions.

If you still have access to the keybase command line, you can try to get rid of the kernel extension with `keybase uninstall -c fuse,redirector`.  If not, maybe you can try:

```
sudo kextunload -b com.github.kbfuse.filesystems.kbfuse
```

to get rid of the extension until we can figure out if and why it's causing problems for you.

**Comment by meeDamian** [comment]
Here's (slightly redacted) the output of: `zgrep -i -A10  keybase /var/log/system.log.*` https://gist.github.com/meeDamian/f66ecc382f3b82ebee602078463cad95 . `/var/log/kernel.log` doesn't exist. Again, do lmk if you need anything more from there.

I'll definitely try both ways you've described! Hope to regain access to chats at least :).

**Comment by strib** [comment]
Thanks!  The most unusual thing I see here is this:

```
/var/log/system.log.3.gz:Aug 31 16:30:30 DM-2 com.apple.xpc.launchd[1] (keybase.kbfs[12188]): Service did not exit 5 seconds after SIGTERM. Sending SIGKILL.
/var/log/system.log.3.gz:Aug 31 16:30:33 DM-2 com.apple.xpc.launchd[1] (keybase.kbfs[12188]): Service did not exit 3 seconds after SIGKILL.
/var/log/system.log.3.gz:Aug 31 16:30:33 DM-2 com.apple.xpc.launchd[1] (keybase.kbfs[12188]): Abandoning service instance. This may lead to deadlocks.
```

Is this around the time things starting freezing for you?  Though I guess you've rebooted several times and are still seeing the issues, so it's not a one-time thing.

We're going to try building a new version with an upgraded osxfuse kernel extension, including the Mojave-specific changes, and we'll see if that helps.

**Comment by meeDamian** [comment]
If useful, I can send complete syslogs as well.

I needed to reboot several times, if I didn't manage to stop/uninstall keybase before it started. If I did manage to prevent it from starting, everything was fine & no reboot was necessary.

**Comment by docdyhr** [comment]
sometime ago I removed a version of MacOSFuse: https://osxfuse.github.io

**Comment by songgao** [comment]
Hey Folks, we've put together a test build that includes an updated Fuse extension (3.8.2) that has beta Mojave support. Before we put it into a public release, could any of you please try it and see if it solves the issue for you?

Here's the build to install: https://s3.amazonaws.com/prerelease.keybase.io/darwin-test/Keybase-2.5.2-20180907045719%2B47eb1322da.dmg

You'd need to quit the Keybase app (either by right clicking the dock icon, or through the menu icon) first, then drag the Keybase app in the dmg into Applications as instructed. After installing, open the Keybase app, and check the new `kbfuse` version:

```
kextstat | grep kbfuse
```

If it says 3.8.2, you have the new version effective. Please let us know if it works!

Note that if other users have logged in on your machine, and has Keybase opened, it'd prevent the auto updater from installing the new fuse extension. But after a reboot it should install the new extension fine. If you are the only one logged in, you shouldn't need to reboot.

**Comment by docdyhr** [comment]
Hi Song Gao,

Thank you for the update to Keybase with the updated Fuse extension. I followed your instructions and installed and started Keybase with out any problems.

I will let you know about any issues on the thread:

https://github.com/keybase/client/issues/13537 <https://github.com/keybase/client/issues/13537>

Nice ;)

--
Thomas Juul Dyhr
thomas@dyhr.com

**Comment by JinOhChoi** [comment]
I had a similar issue. It fixed my issue too. :)

**Comment by docdyhr** [comment]
I just submitted a new error message through the 'Keybase log send' mechanism. Not enough slots available for kbsf.. as startup message for Keybase - although Keybase seems to work?!  log ID is:
  47a68826ce52520e4ee1471c

**Comment by meeDamian** [comment]
Yay, it works 🎉🎉🎉🎉🎉.

After all this time I'm able to use Keybase on my computer again 😃!

**Comment by songgao** [comment]
Thanks all for testing! I'm gonna try to get it into the coming public release then. You all could thank Benjamin [here](https://github.com/osxfuse/osxfuse/issues/508) for making osxfuse work with Mojave. We just "fused" it into KBFS :)

@docdyhr thanks for the log! We'll take a look. As long as it works it's likely fine (i.e. the error message might have been wrong).
