### ISSUE TITLE
Is there pvl instruction executor implementation 

### ISSUE THREAD

**Issue by Gozala** [keybase/client#13577]
Hi,

I would like to be able to perform Proof Verifications in custom JS client. I went through the [pvl](https://keybase.io/docs/client/pvl_spec) wondering if there is a reference implementation I could use, or if my best bet is to write one from scratch.

Thanks

**Comment by maxtaco** [comment]
cc @mlsteele

**Comment by mlsteele** [comment]
@Gozala There's the [implementation in client](https://github.com/keybase/client/blob/master/go/pvl/interp.go#L106). It's in Go and the only implementation right now. It's got [tests](https://github.com/keybase/client/blob/master/go/pvl/interp_test.go#L44) that might come in handy.

Also depending on what you're up to, shelling out to a local keybase client to verify proofs could be an easier way to check proofs. `keybase id npmregistry+npmjs.org@dns+npmjs@twitter`
