### ISSUE TITLE
`e.split is not a function` upon "Upload a file"

### ISSUE THREAD

**Issue by JElchison** [keybase/client#13586]
I'm unable to upload a file using `Keybase GUI Version 2.6.0-20180831151322+712a8b67c8`

Steps to reproduce:
1. Click Keybase icon in app tray --> Show Keybase
2. Click "files" icon
3. Click "Private" directory
4. Click "+ New..." in upper right
5. Click "Upload a file..."
6. Select a text file to upload (I tried 2 different text files)

Output image:
![Output image](https://jelchison.keybase.pub/Screenshot%20from%202018-09-05%2011-06-34.png)

Output text:

```
TypeError: e.split is not a function at Object.b (file:///opt/keybase/resources/app/desktop/dist/index.bundle.js:1:330250) at Object.Te 
(file:///opt/keybase/resources/app/desktop/dist/index.bundle.js:1:328350) at Va 
(file:///opt/keybase/resources/app/desktop/dist/index.bundle.js:1:3615852) at Va.next (<anonymous>) at T 
(file:///opt/keybase/resources/app/desktop/dist/index.bundle.js:1:1156545) at f 
(file:///opt/keybase/resources/app/desktop/dist/index.bundle.js:1:1156272) at R 
(file:///opt/keybase/resources/app/desktop/dist/index.bundle.js:1:1159878) at 
file:///opt/keybase/resources/app/desktop/dist/index.bundle.js:1:1158674 at I 
(file:///opt/keybase/resources/app/desktop/dist/index.bundle.js:1:1158695) at T 
(file:///opt/keybase/resources/app/desktop/dist/index.bundle.js:1:1156605)
```

Repeatability:  10 of 10 attempts

Environment:
```
$ uname -a
Linux xxxxxx 4.10.0-37-generic #41-Ubuntu SMP Fri Oct 6 20:20:37 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 17.10
Release:	17.10
Codename:	artful
```

Please let me know what else I can provide.  Thanks!

**Comment by maxtaco** [comment]
cc @jzila

**Comment by strib** [comment]
I assume this is on Linux?  If so, please upgrade to the latest release (from yesterday).

**Comment by strib** [comment]
(Oh, now I see that it's definitely on Linux. Missed that at first.)

**Comment by JElchison** [comment]
Sorry for wasting your time.  Keybase updated overnight but did not automatically restart the Keybase client.  So, while I had the latest version installed, the previous version of the client was still running.

**I no longer experience this issue on `2.6.0-20180904195507+230d87e9ad`.**  I recommend closing this issue.

Some ideas to reduce future confusion:
* Consider kicking a running instance of Keybase during the package upgrade process.  I understand that the downsides may outweigh the upsides.
* Consider making it easier to determine the running version number from within the app.  Maybe I've overlooked it, but the only way I've found to see the running version number is clicking "Report a bug" link and seeing what pre-populates into the GitHub issue.

Thanks for a great tool!

**Comment by strib** [comment]
Cool.  Yeah other platforms restart automatically, but Linux apps don't usually work that way so we haven't done it there yet.  We do have plans to build a chrome-style restart notifier, but haven't gotten to it yet.

`keybase status` on the CLI shows the versions of the running processes, but yeah Linux doesn't have a way to show it from the app yet. It should.
