### ISSUE TITLE
Follow up my report

### ISSUE THREAD

**Issue by romainneutron** [keybase/client#13582]
By the way, to contact me, I'm here

my log id: 7a6678e261112deed9a4221c

**Comment by maxtaco** [comment]
Please send feedback from all 3 devices. 

What if you start the process over again on both the old and new device?

**Comment by romainneutron** [comment]
Logs for the Phone and osx have been sent

**Comment by romainneutron** [comment]
If I start the process over and again, it still fails

**Comment by maxtaco** [comment]
ok thanks, i think I have a fix here: https://github.com/keybase/client/pull/13583

Sorry about that, it's a new feature that was buggy.  Linux gets immediate access....

**Comment by romainneutron** [comment]
okay cool.
Let me know once it's released

**Comment by romainneutron** [comment]
Bug has been fixed and released. My issue is fixed. Thanks
