### ISSUE TITLE
inbox.mpack placed in Home Directory on Keybase Start.

### ISSUE THREAD

**Issue by matrix8967** [keybase/client#13604]
Ubuntu 18.04  Kernel 4.17.12-041712-generic

When Opening Keybase (on boot, or manually) an "inbox.mpack" file is placed in the home directory. 
![inbox](https://user-images.githubusercontent.com/29032283/45165162-cbbc9500-b1b9-11e8-9f67-f27eb9eeaf02.gif)

my log id: 7ba095aa54c78534ca97711c

**Comment by mmaxim** [comment]
Sorry about that, it will keep coming back until I push an update to fix it, then you can delete it.

**Comment by mmaxim** [comment]
(Update will hit very shortly)

**Comment by mmaxim** [comment]
https://github.com/keybase/client/pull/13611

**Comment by matrix8967** [comment]
Awesome! Thanks for the quick response! 

Just updated, and everything looks good!
