### ISSUE TITLE
Upgrade to 2.5.2 on macOS requires admin credentials - cancelling out renders KBFS unavailable

### ISSUE THREAD

**Issue by fleish** [keybase/client#13615]
Hi all, I got prompted for my admin credentials on the latest keybase client install (2.5.2) for macOS for an installer helper update and mistakenly cancelled the password input and now am not able to use kbfs via my client. I've tried downgrading to 2.5.0 and re-updating (via CLI using keybase update) but I do not get prompted for the installer/helper admin auth now. Can someone advise how to fix this and restore my access to KBFS?

Tagging @cjb as the person who posted the release.

**Comment by strib** [comment]
@fleish If you go into the Files tab in the Keybase GUI, do you see the option for re-enabling KBFS in Finder?

If not, you can try `keybase uninstall -c fuse,redirector`, and then restart the GUI and see if it shows up.

**Comment by fleish** [comment]
@strib I do see that option, and while it does prompt me for authentication (twice, actually), the end results seem to be the same and I still cannot access KBFS on this machine. I did some digging on another machine while installing the update properly the first time and found the following command gets run (which seems to be the same command that runs when selecting re-enable KBFS in the Keybase GUI): 

`/Applications/Keybase.app/Contents/Resources/KeybaseInstaller.app/Contents/MacOS/Keybase --debug --run-mode=prod --app-path=/Applications/Keybase.app --timeout=10 --install-helper`

I tried running this manually on the command line to see the output and got the following:

> 09.06.2018 12:52:18.047 Installer:55[DEBG] Version: 1.1.62
> 09.06.2018 12:52:18.065 KBInstaller:27[DEBG] Installables: (
>     "Privileged Helper"
> )
> 09.06.2018 12:52:18.065 KBInstaller:32[DEBG] Install: Privileged Helper
> 09.06.2018 12:52:18.066 KBHelperTool:73[INFO] Connecting to keybase.Helper (privileged=1)
> 09.06.2018 12:52:18.066 KBHelperTool:73[INFO] Connected
> 09.06.2018 12:52:18.066 KBHelperTool:73[INFO] Connection invalid, clearing connection
> 09.06.2018 12:52:18.066 KBHelperTool:73[INFO] Retrying (attempt=1, requestId=0) after XPC error: Error Domain=MPMessagePack Code=-10 "XPC Error: Connection invalid" UserInfo={NSLocalizedDescription=XPC Error: Connection invalid, NSLocalizedRecoveryOptions=(
>     OK
> )}
> 09.06.2018 12:52:18.066 KBHelperTool:73[INFO] Cleared connection
> 09.06.2018 12:52:18.615 KBHelperTool:73[INFO] Connecting to keybase.Helper (privileged=1)
> 09.06.2018 12:52:18.615 KBHelperTool:73[INFO] Connected
> 09.06.2018 12:52:18.616 KBHelperTool:73[INFO] Retrying (attempt=2, requestId=0) after XPC error: Error Domain=MPMessagePack Code=-10 "XPC Error: Connection invalid" UserInfo={NSLocalizedDescription=XPC Error: Connection invalid, NSLocalizedRecoveryOptions=(
>     OK
> )}
> 09.06.2018 12:52:18.616 KBHelperTool:73[INFO] Connection invalid, clearing connection
> 09.06.2018 12:52:18.616 KBHelperTool:73[INFO] Cleared connection
> 09.06.2018 12:52:19.160 KBHelperTool:73[INFO] Connecting to keybase.Helper (privileged=1)
> 09.06.2018 12:52:19.160 KBHelperTool:73[INFO] Connected
> 09.06.2018 12:52:19.161 KBHelperTool:73[INFO] Connection invalid, clearing connection
> 09.06.2018 12:52:19.161 KBHelperTool:73[INFO] Retrying (attempt=3, requestId=0) after XPC error: Error Domain=MPMessagePack Code=-10 "XPC Error: Connection invalid" UserInfo={NSLocalizedDescription=XPC Error: Connection invalid, NSLocalizedRecoveryOptions=(
>     OK
> )}
> 09.06.2018 12:52:19.161 KBHelperTool:73[INFO] Cleared connection
> 09.06.2018 12:52:19.708 KBHelperTool:73[INFO] Connecting to keybase.Helper (privileged=1)
> 09.06.2018 12:52:19.708 KBHelperTool:73[INFO] Connected
> 09.06.2018 12:52:19.708 KBHelperTool:73[INFO] Max attempts reached (4 >= 4)
> 09.06.2018 12:52:19.708 KBHelperTool:73[INFO] Connection invalid, clearing connection
> 
> ***
> *** here is where I am prompted to authenticate via popup
> ***
> 
> 09.06.2018 12:52:30.905 KBHelperTool:185[DEBG] Removing /Library/PrivilegedHelperTools/keybase.Helper
> 09.06.2018 12:52:30.927 KBHelperTool:194[DEBG] Installing helper tool via SMJobBless
> 09.06.2018 12:52:30.954 KBHelperTool:199[DEBG] Failed, retrying
> 09.06.2018 12:52:30.977 KBInstaller:45[INFO] Install complete
> 09.06.2018 12:52:30.978 KBInstaller:49[INFO] Privileged Helper: Install Error: The operation couldn’t be completed. (CFErrorDomainLaunchd error 9.)
> Error: XPC Error: Connection invalid
> Error, Bundle Version: 1.0.32
> 09.06.2018 12:52:30.981 KBHelperTool:73[INFO] Cleared connection
> 09.06.2018 12:52:30.981 Installer:95[INFO] Exit(1)


I also tried uninstalling fuse & redirector and the same behavior persisted. Here is the output from that command:

`keybase uninstall -c fuse,redirector`

> ▶ ERROR Error stopping the redirector: exit status 1
> ▶ INFO Removing KBFuse
> ▶ ERROR Error uninstalling fuse: exit status 1
>

**Comment by strib** [comment]
Hmm.  Does `keybase --debug uninstall -c helper` do anything or output anything interesting?

**Comment by fleish** [comment]
That seems to fail as well with a similar message about not being able to make a valid connection:

> keybase --debug uninstall -c helper
> 2018-09-06T13:41:10.519978-07:00 ▶ [DEBU keybase globals.go:451] 001 Created Identify2Cache, max age: 5m0s
> 2018-09-06T13:41:10.520067-07:00 ▶ [DEBU keybase globals.go:454] 002 Created LinkCache, max size: 4000, clean dur: 1m0s
> 2018-09-06T13:41:10.520093-07:00 ▶ [DEBU keybase globals.go:456] 003 Created CardCache, max age: 5m0s
> 2018-09-06T13:41:10.520115-07:00 ▶ [DEBU keybase globals.go:474] 004 made a new full self cache
> 2018-09-06T13:41:10.520199-07:00 ▶ [DEBU keybase globals.go:476] 005 made a new cached UPAK loader (timeout=10m0s)
> 2018-09-06T13:41:10.521748-07:00 ▶ [DEBU keybase ui.go:604] 006 Setting GPG_TTY to /dev/ttys004
> 2018-09-06T13:41:10.521807-07:00 ▶ [DEBU keybase secret_store.go:152] 007 NewSecretStoreLocked: using os-specific SecretStore
> 2018-09-06T13:41:10.521957-07:00 ▶ [DEBU keybase globals.go:387] 008 Keybase CLI 2.5.2-20180906142014+a801e75b82
> 2018-09-06T13:41:10.521987-07:00 ▶ [DEBU keybase globals.go:387] 009 - Built with go1.10.3
> 2018-09-06T13:41:10.522002-07:00 ▶ [DEBU keybase globals.go:387] 00a - Visit https://keybase.io for more details
> 2018-09-06T13:41:10.522706-07:00 ▶ [DEBU keybase main.go:212] 00b + configureProcesses
> 2018-09-06T13:41:10.522751-07:00 ▶ [DEBU keybase main.go:323] 00c + configureLogging
> 2018-09-06T13:41:10.522777-07:00 ▶ [DEBU keybase main.go:332] 00d Disabling log forwarding
> 2018-09-06T13:41:10.522794-07:00 ▶ [DEBU keybase main.go:325] 00e - configureLogging
> 2018-09-06T13:41:10.522812-07:00 ▶ [DEBU keybase main.go:214] 00f - configureProcesses -> <nil>
> 2018-09-06T13:41:10.522977-07:00 ▶ [DEBU keybase install_darwin.go:750] 010 Uninstalling components: [helper]
> 2018-09-06T13:41:10.523059-07:00 ▶ [INFO keybase app.go:124] 011 Removing privileged helper tool
> 2018-09-06T13:41:12.287376-07:00 ▶ [DEBU keybase app.go:77] 012 Output ([--debug --run-mode=prod --app-path=/Applications/Keybase.app --timeout=10 --uninstall-helper]): 09.06.2018 13:41:10.626 Installer:55[DEBG] Version: 1.1.62
> 09.06.2018 13:41:10.644 KBHelperTool:223[DEBG] Removing /Library/PrivilegedHelperTools/keybase.Helper
> 09.06.2018 13:41:10.644 KBHelperTool:73[INFO] Connecting to keybase.Helper (privileged=1)
> 09.06.2018 13:41:10.644 KBHelperTool:73[INFO] Connected
> 09.06.2018 13:41:10.644 KBHelperTool:73[INFO] Connection invalid, clearing connection
> 09.06.2018 13:41:10.644 KBHelperTool:73[INFO] Cleared connection
> 09.06.2018 13:41:10.645 KBHelperTool:73[INFO] Retrying (attempt=1, requestId=0) after XPC error: Error Domain=MPMessagePack Code=-10 "XPC Error: Connection invalid" UserInfo={NSLocalizedDescription=XPC Error: Connection invalid, NSLocalizedRecoveryOptions=(
>     OK
> )}
> 09.06.2018 13:41:11.191 KBHelperTool:73[INFO] Connecting to keybase.Helper (privileged=1)
> 09.06.2018 13:41:11.191 KBHelperTool:73[INFO] Connected
> 09.06.2018 13:41:11.192 KBHelperTool:73[INFO] Connection invalid, clearing connection
> 09.06.2018 13:41:11.192 KBHelperTool:73[INFO] Retrying (attempt=2, requestId=0) after XPC error: Error Domain=MPMessagePack Code=-10 "XPC Error: Connection invalid" UserInfo={NSLocalizedDescription=XPC Error: Connection invalid, NSLocalizedRecoveryOptions=(
>     OK
> )}
> 09.06.2018 13:41:11.192 KBHelperTool:73[INFO] Cleared connection
> 09.06.2018 13:41:11.739 KBHelperTool:73[INFO] Connecting to keybase.Helper (privileged=1)
> 09.06.2018 13:41:11.739 KBHelperTool:73[INFO] Connected
> 09.06.2018 13:41:11.739 KBHelperTool:73[INFO] Retrying (attempt=3, requestId=0) after XPC error: Error Domain=MPMessagePack Code=-10 "XPC Error: Connection invalid" UserInfo={NSLocalizedDescription=XPC Error: Connection invalid, NSLocalizedRecoveryOptions=(
>     OK
> )}
> 09.06.2018 13:41:11.739 KBHelperTool:73[INFO] Connection invalid, clearing connection
> 09.06.2018 13:41:11.739 KBHelperTool:73[INFO] Cleared connection
> 09.06.2018 13:41:12.264 KBHelperTool:73[INFO] Connecting to keybase.Helper (privileged=1)
> 09.06.2018 13:41:12.264 KBHelperTool:73[INFO] Connected
> 09.06.2018 13:41:12.264 KBHelperTool:73[INFO] Max attempts reached (4 >= 4)
> 09.06.2018 13:41:12.264 KBHelperTool:73[INFO] Connection invalid, clearing connection
> 09.06.2018 13:41:12.264 Installer:104[ERROR] Error uninstalling: Error Domain=MPMessagePack Code=-10 "XPC Error: Connection invalid" UserInfo={NSLocalizedDescription=XPC Error: Connection invalid, NSLocalizedRecoveryOptions=(
>     OK
> )}
> 2018-09-06T13:41:12.334880-07:00 ▶ [ERRO keybase install_darwin.go:832] 013 Error uninstalling helper: exit status 1
> 2018-09-06T13:41:12.335048-07:00 ▶ [DEBU keybase out_of_date.go:14] 014 + PrintOutOfDateWarnings
> 2018-09-06T13:41:12.335147-07:00 ▶ [DEBU keybase socket.go:65] 015 + GetSocket
> 2018-09-06T13:41:12.343818-07:00 ▶ [DEBU keybase rpc.go:25] 016 - GetSocket -> ok
> 2018-09-06T13:41:12.343928-07:00 ▶ [DEBU keybase socket.go:75] 017 | empty socket wrapper; need a new one
> 2018-09-06T13:41:12.343961-07:00 ▶ [DEBU keybase socket_nix.go:100] 018 + SocketInfo#dialSocket(unix:/Users/fleish/Library/Group Containers/keybase/Library/Caches/Keybase/keybased.sock)
> 2018-09-06T13:41:12.343997-07:00 ▶ [DEBU keybase socket_nix.go:124] 019 | net.Dial(unix:/Users/fleish/Library/Group Containers/keybase/Library/Caches/Keybase/keybased.sock)
> 2018-09-06T13:41:12.344507-07:00 ▶ [DEBU keybase socket_nix.go:125] 01a - SocketInfo#dialSocket(unix:/Users/fleish/Library/Group Containers/keybase/Library/Caches/Keybase/keybased.sock) -> ok
> 2018-09-06T13:41:12.350696-07:00 ▶ [DEBU keybase socket.go:90] 01b | DialSocket -> ok
> 2018-09-06T13:41:12.432430-07:00 ▶ [DEBU keybase out_of_date.go:28] 01c Got OutOfDateInfo: keybase1.OutOfDateInfo{UpgradeTo:"", UpgradeURI:"", CustomMessage:"", CriticalClockSkew:0}
> 2018-09-06T13:41:12.432482-07:00 ▶ [DEBU keybase out_of_date.go:44] 01d - PrintOutOfDateWarnings
> 2018-09-06T13:41:12.532917-07:00 ▶ [DEBU keybase globals.go:589] 01e GlobalContext#Shutdown(0xc4203a8700)
> 2018-09-06T13:41:12.533054-07:00 ▶ [DEBU keybase globals.go:633] 01f exiting shutdown code=0; err=<nil>

**Comment by strib** [comment]
@fleish can you please run `keybase log send` and report the log ID here?  And if you haven't already, can you try a reboot?

When we test this by hitting cancel, we get a nice prompt explaining what's happening, and then kbfs is easily re-enabled afterward.  So we can't reproduce what you've seen.

**Comment by fleish** [comment]
@strib I had previously tried rebooting to no avail. I did manage to fix things just now by following the steps outlined in a comment in #8905 @ https://github.com/keybase/client/issues/8905#issuecomment-335267082

Re-quoting the steps below with a few modifications as my findings were slightly different from the other user:

launchctl print-disabled system

this showed: `"keybase.Helper" => true` for me, vs disabled as the other user reported

`sudo launchctl load -w /Library/LaunchDaemons/keybase.Helper.plist`

`sudo rm /Library/PrivilegedHelperTools/keybase.Helper`

`sudo rm /Library/LaunchDaemons/keybase.Helper.plist`

`keybase install --components=helper` or `keybase install --components=helper,fuse,mountdir,kbfs` if you need everything

I had to run the latter command to install everything before my KBFS started to work again. Let me know if a keybase log send would still be helpful since the issue is now fixed.

**Comment by strib** [comment]
Oh cool, glad you got it working.  Yeah if you're willing to share it, a `log send` would still be good, so we can try to understand how you got into the situation in the first place.  Thanks!

**Comment by strib** [comment]
Also, you might need a `keybase install -c redirector` if you want `/keybase` to work.

**Comment by fleish** [comment]
log ID d3475073be9bb0a5d72af41c

/keybase is working currently

**Comment by strib** [comment]
Great, thanks!
