### ISSUE TITLE
not able to access or create files in private folder

### ISSUE THREAD

**Issue by bobinson** [keybase/client#13637]
not able to access or create files in private folder via cli and app 

my log id: bfc86390d8733565b373971c

Error message from GUI:

`Error: ERROR CODE 218 - Can't get TLF private key for key generation 1 in method keybase.1.SimpleFS.simpleFSWait at new r (file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/index.bundle.js:1:441228) at file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/index.bundle.js:1:441757 at u (file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/index.bundle.js:1:441796) at rpcClient.invoke.t (file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/index.bundle.js:1:245338) at file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/index.bundle.js:1:1758890 at e.t.Deferrals.e.call (file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/index.bundle.js:1:1649609) at file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/index.bundle.js:1:1649760 at s (file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/index.bundle.js:1:1649389) at e.t.Deferrals.e._fulfill (file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/index.bundle.js:1:1649719) at s (file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/index.bundle.js:1:1648923)
`

Error message from CLI:

[06:32 PM] bobinson@air 🖖  [/keybase/private/bobinson]ls
ls: .: Input/output error

corresponding  log id : 18568fb8a7502c4d7492731c

OS:

Darwin air.local 17.7.0 Darwin Kernel Version 17.7.0: Thu Jun 21 22:53:14 PDT 2018; root:xnu-4570.71.2~1/RELEASE_X86_64 x86_64

**Comment by strib** [comment]
Looks like long ago you had only one device with your account (`mac1`), but then you revoked it and added other devices later.  So your private folder has not been rekeyed for your new devices.  
If you want us to reset your folder, please run this command on a currently-valid keybase device, and substitute the current date and time where indicated:

```
keybase sign -m "<DATE_AND_TIME>: Please reset folder /keybase/private/bobinson because all the devices that have access have been revoked."
```

and post the results here.

(It might take me a few days to get to resetting it, I'm offline most of this weekend.)

**Comment by bobinson** [comment]
thank you!

**keybase signed message:**

`BEGIN KEYBASE SALTPACK SIGNED MESSAGE. kXR7VktZdyH7rvq v5weRa0zkAiWRCt I55xfgZWAocoHEQ KHPnU4MHb0OyOtV ftYDIjaGVlxOsij OrStgos3GSoaJg8 oTF8vCGmsZ2C7ab f0ZcQB13bClP7pR bCQFfZ9rIyZYArL RIWAcIe5iMbSdcs cPTrCIqLWAfsgBd L47QhjpPAK6o1cZ CoTey5tx1ceZrl4 Be2O2HRwqDDjwfp 4KifoILX9ZO1u2C 5WC2ojNPukO0Dw9 7sSKJb2aavL4nZZ 3K6N6jN0RDxFNpN mwail65smxEDsQT yY1YciWA8GN3iFs i7h9TR92tqNsEkk MbbXayxRf0rP7yP 8rPfda8K7DdK5Z3 bPJBoPW5OA7tioy mCXlNe. END KEYBASE SALTPACK SIGNED MESSAGE.`

**Comment by strib** [comment]
I reset the folder.  Please check it out and close this if everything seems ok.  (Might require a Keybase restart.)

**Comment by bobinson** [comment]
This works fine now. thank you @strib
