### ISSUE TITLE
Not able to rekey private folder

### ISSUE THREAD

**Issue by deepakjois** [keybase/client#13663]
I keep getting the error below.

![screenshot from 2018-09-10 21-11-35](https://user-images.githubusercontent.com/5342/45308018-26e5e300-b53e-11e8-9218-ab864f3c8291.png)

I have tried rekeying using `keybase rekey paper` multiple times, but I am not able to do it. I keep seeing the error above.

```
$ keybase rekey status
TLFs need rekeying:
private/debugjois

Devices that can rekey:
desktop vyommac
desktop vesuvius
```

**Comment by strib** [comment]
@deepakjois have you tried logging into Keybase on your non-revoked devices `vesuvius` and `vyommac`, as suggested? It seems like the folder is keyed for those devices, and they will be able to rekey it for your new device.

**Comment by deepakjois** [comment]
I am not sure what exactly I need to do. I tried this.

First on my current device, I did:
```
keybase paperkey
```

and then entered the paperkey in the gui, and got to the following screen.

![screenshot from 2018-09-10 23-36-00](https://user-images.githubusercontent.com/5342/45315734-c0b78b00-b552-11e8-8850-df631c4611c6.png)

I have done this multiple times now. But everytime, I do `run_keybase`, I get the error in the original issue above.

**Comment by strib** [comment]
Paper keys won't work in your case, because the folder isn't keyed for any of your paper keys.  You need to turn on one of those desktop devices I mentioned, and run keybase on them.  If you're already running keybase on them, please do `keybase log send` from one of them and I can see why it's not rekeying.

**Comment by deepakjois** [comment]
Ok. I had to do `run_keybase` on the `vesuvius` and not my current computer. That seemed to work.

Thanks for the hint.

**Comment by strib** [comment]
Ah ok, great!
