### ISSUE TITLE
kbfs not available after reboot

### ISSUE THREAD

**Issue by mortenkjarulff** [keybase/client#13682]
See ls command at start and end

my log id: 87cfb861aa5eefc96702341c

bitnami@ip-172-26-14-174:~$ ls /run/user/1000/keybase/
kbfsd.sock  keybased.info  keybased.pid  keybased.sock
bitnami@ip-172-26-14-174:~$ keybase log send
This command will send recent keybase log entries to keybase.io
for debugging purposes only.

These logs don’t include your private keys or encrypted data,
but they will include filenames and other metadata keybase normally
can’t read, for debugging purposes.

Continue sending logs to keybase.io? (type 'YES' to confirm): YES
Enter feedback (or <Enter> to send): kbfs not available after reboot
More feedback (or press <Enter> when done): run_keybase will make it available
More feedback (or press <Enter> when done): systemctl --status kbfs.service show
s an error
More feedback (or press <Enter> when done):
▶ INFO ignoring UI logs: GUI main process wasn't found

------------
Success! Your log ID is:

  87cfb861aa5eefc96702341c

Here's a URL to submit new bug reports containing this ID:

  https://github.com/keybase/client/issues/new?body=[write%20something%20useful%20and%20descriptive%20here]%0A%0Amy%20log%20id:%2087cfb861aa5eefc96702341c

Thanks!
------------

bitnami@ip-172-26-14-174:~$ run_keybase
Shutting down kbfsfuse...
Shutting down keybase service...
Starting via systemd.
Success!
                                                  ▄▄▄▄█▀
╭───────────────────────╮          ▄▄          ▄▄▄█▄▄▀
│                       │         ███▄▄▄▄▄▄▄▄▄▄███▄██
│  Encrypt everything!  │       ▄▄▄████▄▄▄███████████
│                       ├────  ▄▄▄▄▄████▄█████████████
╰───────────────────────╯      ███▄█▄█████████████████▄▄
                                ▀▄███████▄▀ ███████████▄▄
                                  ▄▄▄▄███    ███████████▄▄
                                 ▄████████   ██████████████
                                ▄███▄█████▄▄  ▀▄████████████
                               ███████▄▄██▄█▄▄ █████████████
                              ▄▄█████████████▄▄ ████████████
                           ▄██▄▄████▄▄▄█▄▄█████ ████████████
                                ███▄▄▄▄▄███████▄▄█████████▄▀
                                ▄█████▄▄█████████████▄█████
                                █▄██████████▄▄▄▄▄▄▄███████
                              ▄▄▄▄▄██▄▄█████▄████████████
                            ▀▀▀▀▀▀▀▀▄▄▄▄██▄▀ ▀▀▄▄▄▄▄▄▀▀▀
                                  ▀▀▀▀▀▀▀▀▀
bitnami@ip-172-26-14-174:~$ ls /run/user/1000/keybase/
kbfs        keybased.info  keybased.sock    startup_mode
kbfsd.sock  keybased.pid   keybase.gui.env
bitnami@ip-172-26-14-174:~$

**Comment by mortenkjarulff** [comment]
/keybase is empty

Welcome to Ubuntu 16.04.4 LTS (GNU/Linux 4.4.0-1066-aws x86_64)
       ___ _ _                   _
      | _ |_) |_ _ _  __ _ _ __ (_)
      | _ \ |  _| ' \/ _` | '  \| |
      |___/_|\__|_|_|\__,_|_|_|_|_|

  *** Welcome to the Bitnami Nginx 1.14.0-0 ***
  *** Documentation:  https://docs.bitnami.com/aws/infrastructure/nginx/ ***
  ***                 https://docs.bitnami.com/aws/ ***
  *** Bitnami Forums: https://community.bitnami.com/ ***
Last login: Tue Sep 11 06:27:22 2018 from 192.38.139.189
bitnami@ip-172-26-14-174:~$ ls /
bin   etc         initrd.img.old  lib64       mnt   root  snap  tmp  vmlinuz
boot  home        keybase         lost+found  opt   run   srv   usr  vmlinuz.old
dev   initrd.img  lib             media       proc  sbin  sys   var
bitnami@ip-172-26-14-174:~$ cd /keybase/
bitnami@ip-172-26-14-174:/keybase$ ls
bitnami@ip-172-26-14-174:/keybase$

**Comment by strib** [comment]
@mortenkjarulff KBFS is hitting this error:

```
Mounting the filesystem failed: stat /run/user/1000/keybase/kbfs: no such file or directory
```

github mangled your terminal output above and I'm not quite clear on the timeline of things, but if I understand right, your first post shows that `/run/user/1000/keybase/kbfs` does exist?

Can you give a clear timeline of what went wrong?  Was it working for a long time before the last reboot?  Did it start working again after you did `run_keybase`?

**Comment by mortenkjarulff** [comment]
After reboot
/run/user/1000/keybase
Contains
kbfsd.sock  keybased.info  keybased.pid  keybased.sock
And /keybase is empty.

run_keybase when logged in, fixes it.

A new reboot breaks it.

Don't know if it ever worked after reboot.

/Morten

**Comment by strib** [comment]
@mortenkjarulff is it the case that this machine doesn't have a desktop environment?  `run_keybase` makes an entry at `~/.config/autostart/keybase_autostart.desktop` that launches `run_keybase` whenever the desktop environment starts.  If that file is being ignored in your system, you might have to make a startup item to `mkdir /run/user/1000/keybase/kbfs` on startup, before the keybase systemd services start.

**Comment by strib** [comment]
Note that you can also change the mount directory to something else that will persist across restarts, like this for example:

```sh
keybase config set mountdir /home/$USER/.local/share/keybase/kbfs
```
or even:
```sh
keybase config set mountdir /home/$USER/keybase
```

Then make that directory and re-run `run_keybase`, and you should be all set.  `/keybase` will point to it, as long as it has "keybase" in it somewhere.

**Comment by mortenkjarulff** [comment]
Hi

I did
keybase config set mountdir /home/$USER/keybase

Now, after reboot, /keybase is empty, but ~/keybase is there.

systemctl --user status kbfs.service
Shows an error.

If it has a desktop environment, I am not using it, I am logging in with ssh. My goal is to have a script running unattended.

/Mortenkjarulff

bitnami@ip-172-26-14-174:~$ ls /keybase
bitnami@ip-172-26-14-174:~$ ls keybase/public
spuncut
bitnami@ip-172-26-14-174:~$ systemctl --user status kbfs.service
● kbfs.service - Keybase Filesystem service
   Loaded: loaded (/usr/lib/systemd/user/kbfs.service; enabled; vendor preset: enab   Active: active (running) since Thu 2018-09-13 05:58:49 UTC; 5min ago
  Process: 1864 ExecStartPre=/bin/sh -c fusermount -uz "$(keybase config get -d -b  Main PID: 1890 (kbfsfuse)
   CGroup: /user.slice/user-1000.slice/user@1000.service/kbfs.service
           └─1890 /usr/bin/kbfsfuse -debug -log-to-file

Sep 13 05:58:44 ip-172-26-14-174 systemd[1856]: Starting Keybase Filesystem serviceSep 13 05:58:44 ip-172-26-14-174 sh[1864]: Systemd reported an unexpected status: sSep 13 05:58:44 ip-172-26-14-174 sh[1864]: 2018-09-13T05:58:44.521744Z ▶ [INFO keybSep 13 05:58:47 ip-172-26-14-174 sh[1864]: fusermount: entry for /home/bitnami/keybSep 13 05:58:49 ip-172-26-14-174 systemd[1856]: Started Keybase Filesystem service.bitnami@ip-172-26-14-174:~$

**Comment by mortenkjarulff** [comment]
run_keybase brings /keybase back.

**Comment by heronhaye** [comment]
Closing as resolved, please make a new issue if you still have trouble, thanks!
