### ISSUE TITLE
Sending passphrase to other user beginning with @ shifts case lower

### ISSUE THREAD

**Issue by bhperform** [keybase/client#13710]
Wanted to send a passphrase to a contact, it was something like `@QQdf*55jQf` but if it was the first item on the line the resulting paste became `@qqdf*55jqf `. If it was a second word in the sentence then this was not an issue.

OS: Windows 10

**Comment by taruti** [comment]
Writing ```@foobar``` tries to reference the user called foobar. Using quotes around will work, e.g. ```"@foobar"```.

Please feel free to reopen this if you'd like more options.

**Comment by bhperform** [comment]
Expected behaviour: if the account name cannot be found, don't shift the case.
