### ISSUE TITLE
iOS: Can't press the close button on photo in KBFS

### ISSUE THREAD

**Issue by aaronraimist** [keybase/client#13735]
The close button when you open images in KBFS on the iPhone X is under the current time so I can't press it. Just use the same code that opens images in Keybase Chat and it will work.

The only way to get out of the photo that I can find is to force quit the entire app.

iOS 12 GM (but I'm pretty sure I had the same thing in the last version of iOS 11)

**Comment by strib** [comment]
cc: @jzila @songgao.

**Comment by aaronraimist** [comment]
Looks ok now in 2.10.0
