### ISSUE TITLE
Errors creating files or git-repos on teams with no existing data

### ISSUE THREAD

**Issue by soekul** [keybase/client#13741]
I receive various errors while trying to create files or git repos on teams I created last year. No existing files or git repositories have ever been created. This happens in mobile and client versions of the app, on linux and os x, through command line or gui. Other teams that I'm apart of have no issues at all.

my log id: a5c1f7f256d8fe9c86239f1c

**Comment by strib** [comment]
Thanks, I saw your logs already and am looking into it.  Will update soon.

**Comment by strib** [comment]
@soekul I cleared out some old state on our servers.  Can you try again please?

I looks like when the team was created, about a year ago, one client got partway through creating a KBFS folder for the team and then stopped or crashed unexpectedly.  It left some old state around that we weren't dealing with very smoothly.  Let me know if things work now.

**Comment by soekul** [comment]
@strib Thank you! Everything seems work fine now.
