### ISSUE TITLE
Failed to list folder - Error code 2704 BLOCK_NONEXISTENT 

### ISSUE THREAD

**Issue by zot24** [keybase/client#13751]
I'm getting the error code 2704 and a message `BLOCK_NONEXISTENT` when trying to access to my private files.

my log id: 16f1ba9aeaf2d34af040da1c

**Comment by strib** [comment]
This is a very strange error.  It might help if you could do a `keybase log send` from your device `Hydros`, which I think was the most rccent device to have written to the folder.

Have you ever successfully written actual data to the folder before?

**Comment by zot24** [comment]
> Have you ever successfully written actual data to the folder before?

I did

>  It might help if you could do a keybase log send from your device Hydros

Sadly I don't have access to that device anymore

However same error was shown on both laptops, sorry can't be of more help

**Comment by strib** [comment]
That's unfortunate. I really have no idea what happened here, without seeing that original log.  I'll look into it again on Monday, but if I can't figure it out, would you be ok with me resetting the folder?  I suspect that device `Hydros` was doing something very buggy...

If you're ok with us resetting your folder, please run this command on a currently-valid keybase device, and substitute the current date and time where indicated:

```
keybase sign -m "<DATE_AND_TIME>: Please reset folder /keybase/private/zot24 because all the devices that have access have been revoked."
```

and post the results here.

**Comment by zot24** [comment]
BEGIN KEYBASE SALTPACK SIGNED MESSAGE. kXR7VktZdyH7rvq v5weRa0zkFQHZqt B6qlhkbGQehQGgH IqFJhfZmfLLslZe NlRLl6tvAmctbwW d3GQmXRkFYa1ats b3uekmv7okBWmWA pVLbBrF2krQxsno fiaEVo5xJMgzSBe Oe9clUyzd0EZQHy xLhwpkoIHb757Qn MAhYqXeCDOP4G9g f3phTwzk3eQ4B7a QiYLMGC3TpNK2XH 0is6KBfZec7rB5n l4uFvyrrQ7Rqhdj sVvHKbdloBFmX12 dk0BFALhhW2kpUx Zl5HWoag4LgqYV2 WspjpRtltkf2VAg 5Pi2KPMPiffaCQP 8ILux5gPyRAfPxJ 8iVcpfWYYGU86y0 sA0rjTg68hycGSM 1XLJFU7NW. END KEYBASE SALTPACK SIGNED MESSAGE.

**Comment by strib** [comment]
I reset the folder.  Please check it out and close this if everything seems ok.  (Might require a Keybase restart.)

But, I still have no clue what happened here.  Basically, we have two types of KBFS servers your client is supposed to talk to when it commits data with us.  There's the block server (bserver) and the metadata server (mdserver).  The encrypted data goes to the block server first, and then a full view of the folder gets commited to the mdserver when all the data is uploaded.  In this case, it looks like the bserver never got ANY data from your client at all, and only the mdserver received data. I've never seen it happen before.

Is there any chance you were running the `kbfsfuse` process with non-standard command-line options (such as `-bserver=memory`), or specific `$KEYBASE` environment variables, on your `Hydros` machine?

Also, I'm curious to learn why you don't have access to `Hydros` anymore, if you're willing to share.  Was the hardware in any way faulty?

**Comment by zot24** [comment]
> Is there any chance you were running the kbfsfuse process with non-standard command-line options (such as -bserver=memory), or specific $KEYBASE environment variables, on your Hydros machine?

Nop

> Also, I'm curious to learn why you don't have access to Hydros anymore, if you're willing to share. Was the hardware in any way faulty?

That was the machine my company provided me but I'm not longer working for them so had to return it 😄 

I have just checked and the `public` folder works just fine but it's the `private` folder that doesn't, if I try to open it it won't and if I try to drag and drop a file into it would got stuck til Finder say it can't move the file into that folder. So can see in the image below the `Loading...` message when I try to access it

<img width="1043" alt="screenshot 2018-09-18 13 28 31" src="https://user-images.githubusercontent.com/678498/45687807-9b74df00-bb47-11e8-953e-461d3f4a9c7a.png">

**Comment by strib** [comment]
@zot24 is this after a Keybase restart?  If not, please try restarting.  If so, please do another `keybase log send`.

**Comment by zot24** [comment]
Yes I have restarted not only Keybase but my laptop too and no luck for the prrivate folder. I have tested it again and this time I have got the same error I had first time.

<img width="865" alt="screenshot 2018-09-19 11 12 47" src="https://user-images.githubusercontent.com/678498/45748885-e5ba9680-bc01-11e8-86bc-9ec55a21ff8c.png">

This is my log id 5aeed2258f851b9b003e571c

**Comment by strib** [comment]
@zot24 Sorry, we had to reset one more thing on our server.  NOW things should work, especially after a Keybase restart.  Please check it and close this out if it seems ok.

**Comment by zot24** [comment]
Great 😄 @strib 👏 it seems to be working again! any idea why this happened in the first place? Thanks,

**Comment by strib** [comment]
Great!

> any idea why this happened in the first place?

I wish I did.  I would really have needed logs from the original machine to debug it.  It feels like there was some weird configuration on that machine, or maybe a weird disk failure, but I can't know for sure without seeing the logs.  Unsatisfying, I know, sorry for the inconvenience!

**Comment by whakapapa** [comment]
> This is a very strange error. It might help if you could do a `keybase log send` from your device `Hydros`, which I think was the most recent device to have written to the folder.
> 
> Have you ever successfully written actual data to the folder before?

Could you apply the same magic to my account? Cannot access private folder anymore (RPC, error 2704, block or cache not initialized, ...)
