### ISSUE TITLE
Username of a deleted account is unusable

### ISSUE THREAD

**Issue by pl4nty** [keybase/client#13799]
My username is `Planty` with a capital `P`, but when signing up to Keybase I used a lowercase `p` by accident. So, I deleted the account and attempted to reregister (forgot to check if there was a `change display name` option), but got the error 

> `Username Planty is unavailable. That account has been deleted.`

**Comment by junderw** [comment]
Keybase names are case insensitive. so "Planty" and "planty" are the same, and will always be shown as "planty" everywhere.

Also, Keybase is append only, so deleting the account means you can not ever create a new account with the same name, even if it is deleted.

This was all explained to you before you deleted your account.

I'm sorry for your loss.

**Comment by Pl4nty** [comment]
Thanks, I must have missed that. Was considering changing to `Pl4nty` anyway since `Planty` is already occupied on lots of platforms, may as well now.
