### ISSUE TITLE
Error in transport: msgpack decode error [pos 3]: file has already been closed

### ISSUE THREAD

**Issue by Tomalak** [keybase/client#13868]
I'm using the keybase CLI

```
Client:  2.6.2-20180920135656+0f17a92adc
Service: 2.6.2-20180920135656+0f17a92adc
```

On Windows 7 x64, and most commands (e.g. `keybase chat read`, or any `encrypt`/`decrypt` command) trigger the following error, although the command itself completes normally:

```
- ERROR {pipe://\\.\pipe\kbservice\Users\myself\AppData\Local\Keybase\keybased.sock} Error in transport: msgpack decode error [pos 3]: file has already been closed
```

Unfortunately, nothing gets written to the logs for this error.

**Comment by maxtaco** [comment]
Hi, please `keybase log send`

CC: @zanderz

**Comment by Tomalak** [comment]
The logs are rather large, will that upload the whole thing? 

![screenshot](https://user-images.githubusercontent.com/28300/45886889-910e4b80-bdba-11e8-9aa7-e0b8c664ee51.png)

**Comment by Tomalak** [comment]
-> 54024262edfec00ee905df1c

**Comment by Anumita** [comment]
Any update on this? I am getting the same error.

**Comment by maxtaco** [comment]
@Anumita and @Tomalak, we have it fixed in master, it will go out with the next release. I don't think it went out with the hotfix last week (2.6.2).  Thanks for your patience

**Comment by Tomalak** [comment]
Awesome, thanks!

**Comment by sleegitus** [comment]
I am getting the same error when trying to provision my Ubuntu (16.04) box.
