### ISSUE TITLE
unable to 'enable keybase in finder' - unresponsive KBFS on Mac after installing keybase on my Ubuntu

### ISSUE THREAD

**Issue by lee2sman** [keybase/client#13889]
Apologies, I see a bunch of similar issues but I'm opening another because I didn't find someone describing exactly what I'm seeing. 

I get the "We were unable to load KBFS (Fuse kext). at application startup" error on my Mac that many people have posted. When I go to Gear > Files  then I am unable to click on "Yes, enable" OR on "Enable Keybase in Finder". They are unresponsive. I have not done anything new on my Mac in months or installed new software. However, I did just recently install a new Ubuntu computer and setup keybase on that. Is it possible that I've granted permissions on that and somehow it removed kbfs from my Mac?

I followed the [troubleshooting guide](https://github.com/keybase/client/wiki/Troubleshooting) by unloading smb kext. I don't have VMware, Virtualbox, and I'm not sure what HAXM is. I ran the code to fix driver permissions. I've logged out of keybase, logged back in. I've restarted. Still doesn't work.

My log ID: 51d4d7d27357d99aafb44a1c

**Comment by strib** [comment]
@lee2sman we've dropped support for macOS 10.10 due to kernel incompatibility issues.  Please try upgrading your macOS installation.  Sorry for the inconvenience.
