### ISSUE TITLE
KBFS not working

### ISSUE THREAD

**Issue by RyanSinger** [keybase/client#13892]
KBFS wouldn't open in finder, went to terminal and got this:

```
Ryans-MacBook-Pro:ryan_singer ryan$ open .
LSOpenURLsWithRole() failed with error 5 for the file /Volumes/Keybase (ryan)/private/ryan_singer.

```

my log id: e0f6af21a2d14823712dd51c

**Comment by RyanSinger** [comment]
Works now. Weird.

**Comment by strib** [comment]
Known rare racy bug with macOS/osxfuse I think:

https://github.com/osxfuse/osxfuse/issues/478
https://github.com/osxfuse/osxfuse/issues/421
