### ISSUE TITLE
Download attachment via client gives error on Linux

### ISSUE THREAD

**Issue by mortenkjarulff** [keybase/client#13906]
It seems that this one
```
echo '{"method": "download", "params": {"options": {"channel": {"name": "myteam.mysubteam", "members_type": "team", "topic_name": "mychannel"}, "message_id": 6, "output": "6.jpg"}}}' | keybase chat api -p
```
Gives
```
{
    "error": {
        "code": 0,
        "message": "GetUnverifiedConv: conversation not found"
    }
}
```
On Linux, but works fine on windows.
Windows user is admin of team, Linux user is writer.

**Comment by maxtaco** [comment]
cc  @patrickxb

**Comment by patrickxb** [comment]
I tried this as a writer in a subteam and it worked.

@mortenkjarulff can you do `keybase log send` from the linux machine right after running the above command?  

Thanks!

**Comment by mortenkjarulff** [comment]
d90527d10bb4fe0113df501c

**Comment by patrickxb** [comment]
@mortenkjarulff the user who is logged in on the linux machine is not a member of the team, according to our servers.

**Comment by mortenkjarulff** [comment]
He was member of the team, but had not joined the channel.

Confirm it works after he joined the channel on my phone, but strange he could read the channel without joining
