### ISSUE TITLE
Keybase wants access to control "System Events" - scary warning on Mojave

### ISSUE THREAD

**Issue by crw** [keybase/client#13911]
Hi, installed Mojave, and saw this scary warning when restarting:

![screen shot 2018-09-25 at 9 21 08 am](https://user-images.githubusercontent.com/57712/46028089-80085780-c0a4-11e8-8518-ef7fcae7cc30.png)

Can anyone confirm this is actually generated by Keybase? Is this level of access actually necessary, or is it something that can be removed in future versions? Thanks!

**Comment by strib** [comment]
Yes it is legitimate.  Here is the code asking for permission, here is one example (the others are also in that same file): https://github.com/keybase/client/blob/100c837e36a309ceb21a37352e6ced9038f124e0/shared/desktop/app/app-state.desktop.js#L158

This is just adding Keybase to autostart.  I think you can disallow it if you want, and Keybase just won't be added automatically to your login items.

**Comment by crw** [comment]
Perfect, thanks for the info!
