### ISSUE TITLE
ERROR Decryption error: This device does not yet have read access to directory

### ISSUE THREAD

**Issue by cjuneja** [keybase/client#13963]
▶ ERROR Decryption error: This device does not yet have read access to directory /keybase/private/aaronyu,cajunejacz (files before cajunejacz account reset 2018-08-28), log into Keybase from one of your other devices to grant access: could not find params for uid=7fc055a345741012670007558c8fcc19 device key=0121e3d68e2abe7cf9394e7f149eed8a0e30108962765c72e7e9a4c2cacb7938526b0a
github.com/keybase/kbfs/libkbfs.(*KeyManagerStandard).getTLFCryptKeyParams
	/Users/build/go/src/github.com/keybase/kbfs/libkbfs/key_manager.go:312
github.com/keybase/kbfs/libkbfs.(*KeyManagerStandard).getTLFCryptKey
	/Users/build/go/src/github.com/keybase/kbfs/libkbfs/key_manager.go:173
github.com/keybase/kbfs/libkbfs.(*KeyManagerStandard).getTLFCryptKeyUsingCurrentDevice
	/Users/build/go/src/github.com/keybase/kbfs/libkbfs/key_manager.go:82
github.com/keybase/kbfs/libkbfs.(*KeyManagerStandard).GetTLFCryptKeyOfAllGenerations
	/Users/build/go/src/github.com/keybase/kbfs/libkbfs/key_manager.go:66
github.com/keybase/kbfs/libkbfs.(*KBFSOpsStandard).GetTLFCryptKeys
	/Users/build/go/src/github.com/keybase/kbfs/libkbfs/kbfs_ops.go:586
github.com/keybase/kbfs/libkbfs.(*KeybaseServiceBase).GetTLFCryptKeys
	/Users/build/go/src/github.com/keybase/kbfs/libkbfs/keybase_service_base.go:1325

**Comment by strib** [comment]
This is expected, your post-reset devices shouldn't be able to access your pre-reset folders.  You can ignore this folder in the Keybase GUI, or `rmdir` it from the terminal.

**Comment by cjuneja** [comment]
![screen shot 2018-09-27 at 11 28 40 am](https://user-images.githubusercontent.com/4822048/46166645-8f280a80-c248-11e8-8ede-f74abbf4b4e1.png)

**Comment by cjuneja** [comment]
I just want to get my message decrypted. I do not care about the extra junk messages but these are legit errors preventing the decryption of the message. 

i get this btw when i perform the rmdir action

rmdir "/keybase/private/aaronyu,cajunejacz (files before cajunejacz account reset 2018-08-28)"
rmdir: /keybase/private/aaronyu,cajunejacz (files before cajunejacz account reset 2018-08-28): Not a directory
➜  ~ rmdir "/keybase/private/aaronyu,cajunejacz"                                                   
rmdir: /keybase/private/aaronyu,cajunejacz: Not a directory

**Comment by strib** [comment]
Oh, you never said what your goal was.  I guess I made a wrong assumption.  What command did you run, when you got the error?

**Comment by cjuneja** [comment]
this is what i ran 

keybase decrypt -m "encypted message"

i am logged into keybase client on the mac

**Comment by strib** [comment]
Please run `keybase log send` and report the resulting log ID here, and someone on our team can take a look.  I personally don't know much about that command.

**Comment by cjuneja** [comment]
ok. thanks. just did that. 

Success! Your log ID is:

  3e1c90cfd560d7e22383231c



****one of the most tools to use**** i have ever came across 👎

**Comment by strib** [comment]
It seems like you're trying to decrypt a message from that user, and that it pre-dates when you reset your account, so it's no longer possible for you to decrypt it.

cc: @max @mmaxim @mlsteele -- not sure who looks into saltpack issues these days.

**Comment by maxtaco** [comment]
Yes, this is likely working as intended.  I told @cjuneja as much when he contacted me over email. We do a lot of badging and notification that users should install multiple devices and that resetting your account means you're going to lose data. If we said otherwise, that you could lose all of your decryption keys, and could still recover your encrypted data, well that would imply that we had a copy of your decryption key, or some chicanery like that. We don't have or want your decryption keys, so we can't help you if you've lost them.

**Comment by maxtaco** [comment]
Yes, the sender can definitely resend the message to you, that would work.  As long as he hasn't reset, he can still decrypt it.

**Comment by cjuneja** [comment]
Thanks @maxtaco ! will try that now
