### ISSUE TITLE
Can't undo 'keybase chat hide'

### ISSUE THREAD

**Issue by apatil** [keybase/client#14001]
I used 'keybase chat hide' to hide a chat because I didn't want it to show in the UI list. That was only because I didn't anticipate any more messages for a while, I didn't want to hide or block the conversation permanently.

Now, it looks like the conversation with that person has been irreversibly blocked.

**Comment by strib** [comment]
What happens when you try `keybase chat hide -u`?  If that doesn't work, please send logs with `keybase log send`.

**Comment by apatil** [comment]
It worked! Thanks!!
