### ISSUE TITLE
Private folder reset

### ISSUE THREAD

**Issue by ItaySharon** [keybase/client#14022]
2018-10-02 11:01 UTC: Please reset folder /keybase/private/itaysharon because all the devices that have access have been revoked.

`BEGIN KEYBASE SALTPACK SIGNED MESSAGE. kXR7VktZdyH7rvq v5weRa0zkMxmuJo PxIJtOIrFNp3OKp NzoRajxsNaxCgve 1fKV1n5QkPizdLx oTP0me2UJaZbB3M jPzQiDj9aMyh82s moOYzWIEwS3Jq2j 51CIVfZ1cMRctNE fhAzLpQGl43iG4b v6uAVFymDz19fCS YgkYDkL6L0OTTts FPSbazUM9kCpsxX EglL2uwDgNoS9US foEMKJ4OQO97AIo XwSyMjs05DruYA7 4w8Jw8OlGxs29KU pj7S4RdVknQYHJR 5oPFSTwDqsCjS2Q caVSBN3lS8UVJnu qNo2Lvhn5JaNDLB wX7MWE0Po1DGxzH i6aSrK3SAItsrF9 t1GFjoZG7lhFRm. END KEYBASE SALTPACK SIGNED MESSAGE.`

**Comment by strib** [comment]
I reset the folder.  Please check it out and close this if everything seems ok.  (Might require a Keybase restart.)
