### ISSUE TITLE
Cannot add a user to a team from the command line 

### ISSUE THREAD

**Issue by steve4444** [keybase/client#14046]
I can add users from the Windows app using their email, but 

    keybase team add-member myteam --user=jon.doe@gmail.com --role=writer

gives

    - ERROR Unknown social network: gmail.com

**Comment by maxtaco** [comment]
Use this instead:

```
keybase team add-member myteam --email=jon.doe@gmail.com --role=writer
```

**Comment by steve4444** [comment]
Thanks.

Can I also, invite multiple people with a single command? (This is possible with GUI)

Running

    keybase team add-member myteam --email=jon.doe@gmail.com,jane.doe@gmail.com --role=writer

does not work.

Also, if, given multiple membership invitations, I resend an invitation to the same contact, will it be automatically discarded or send twice?
