### ISSUE TITLE
Unable to run Keybase on Windows 10 after updating to 2.7.2

### ISSUE THREAD

**Issue by duckpuppy** [keybase/client#14092]
When I try to run Keybase now, I get a dialog stating "The application was unable to start correctly (0xc000007b). Click OK to close the application."

Running keybase from the command line provides no further output, there's no output from the CLI at all, it just exits immediately.

**Comment by duckpuppy** [comment]
I've tried uninstalling, rebooting, and reinstalling from a newly downloaded installer.  It seems that the installer might not be completing the installation (the progress bar never gets more than about 10% of the way across during installation), but there's no errors, it just stops.

**Comment by maxtaco** [comment]
cc @zanderz --- is this a x86 vs 64-bit problem?

**Comment by duckpuppy** [comment]
64-bit

**Comment by maxtaco** [comment]
@zanderz  can you help you debug it

**Comment by thurloat** [comment]
I ran into the same issue starting yesterday. The keybase service runs and I can interact with the service via the CLI tool, only the GUI application crashes.

I've followed the same process as you, and the installer just seemed to disappear after a while on reinstall with no confirmation though the service is still running the same as before in the crash state.

Other 0xc00007b errors online have pointed to missing or corrupt DLLs being loaded, i've tried reinstalling visual c++ redist.

**Comment by maxtaco** [comment]
@zanderz : there's a log send here 1debbbfaafd6d01c43ba7d1c

**Comment by zanderz** [comment]
@thurloat Your install log doesn't show anything too unusual (except a target driver other than c: which shouldn't matter). I've installed this version several times on different win10 machines without problems like these. If one of you having these troubles could make an extra verbose log by doing this with the MSI that may help:
msiexec /liwearumopvx! %temp%\keybaseinstall.log Keybase[...].msi
I will try on more machines, with more different start conditions.

**Comment by steve4444** [comment]
Same issue here. 
The command line works, the GUI doesn't. 

I installed KeyBase in a virtual machine and the GUI worked. So it might be a problem with a conflicting application.  I do not use any Firewall/Antivirus software by the way.   

Is there any other command to be executed before  `Gui\Keybase.exe`?  E.g. `kbfsdokan`.

**Comment by thurloat** [comment]
@zanderz that command doesn't work for me, just pops open a windows installer window with help text, being non-windows native I'm not sure where the command is going wrong.

I've tried mucking with the args ordering and trying to make the `msiexec` command happy, but the furthest i've made it is it complaining about an unknown log location.

**Comment by thurloat** [comment]
The latest update seems to have fixed it for me.

**Comment by steve4444** [comment]
Can I update from the command line?

**Comment by steve4444** [comment]
issue solved for me after updating, thx

**Comment by duckpuppy** [comment]
Updating has solved it for me too.  Looks like this issue can be closed at this point.

**Comment by taruti** [comment]
Solved for all the users here it seems, so closing this.
