### ISSUE TITLE
Add multiple members to a team

### ISSUE THREAD

**Issue by steve4444** [keybase/client#14132]
Can I invite multiple members to a team with a single command? (This is possible with the GUI)

Running:

    keybase team add-member myteam --email=jon.doe@gmail.com,jane.doe@gmail.com --role=writer

does not work.

Also, if, given multiple membership invitations, I resend an invitation to the same contact, will it be automatically discarded or send twice?

**Comment by maxtaco** [comment]
We should fix this. Not right now, though there is RPC support for it, since the electron/RN frontend

**Comment by steve4444** [comment]
The command 

    keybase team add-members-bulk ... 

fixes this
