### ISSUE TITLE
Keybase Filesystem on Ubuntu 16.04 unresponsive after several minutes

### ISSUE THREAD

**Issue by tsaubergine** [keybase/client#14136]
If I restart the client I can access my files for a few minutes (team folder of Keybase Filesystem), but after a bit, the folders become inaccessible (e.g. "ls /keybase/team/{teamname}" hangs indefinitely.

I posted a log with ID:
  0caefe3271ef76efad755b1c

**Comment by strib** [comment]
Sorry about this.  There's a regression in the latest Linux build for people that use the Keybase app to access their folders, which is fixed in keybase/kbfs#1846.  We'll put out a new build once it's merged to master.

**Comment by strib** [comment]
@tsaubergine should be fixed in the latest release, `2.8.0-20181008202958.7cf71f6fcb`.  (Re-run `run_keybase` after updating to it.)

**Comment by tsaubergine** [comment]
Thanks!
