### ISSUE TITLE
Can't "allow" Keybase in High Sierra security center

### ISSUE THREAD

**Issue by jpmurray** [keybase/client#14135]
I've seen a lot of issues regarding the "allow" button not appearing, but it's not my case, so I'm trying a new issue.

Trying to integrate to the finder gives me "action needed" and instruction window, so far so good. Opening the Security & Privacy panel, I do see the possibility to allow Keybase to do it's thing.

<img width="576" alt="screen shot 2018-10-08 at 11 06 56 am" src="https://user-images.githubusercontent.com/1550428/46617264-527ecd80-caea-11e8-80da-ea107e9065ec.png">

Clicking on the button though, do nothing. I've just sent the log after clicking on the button, the log ID is : a7b0eb228528eae6369aea1c.

I really wanted to upload a file to my private folder, so I decided to use the UI. So I went on, created a folder, then uploaded a file, and sure enough, it worked. But now I have a folder in my favorite, but I can't access it because of permissions. Same goes if I try to access it via CLI.

**Comment by strib** [comment]
@jpmurray which issue specifically have you ruled out as not being your case?  In the past, I've seen something like this due to Apple not allowing clicks from certain mouse accessories, but I don't know if that's what you're talking about.

**Comment by jpmurray** [comment]
@strib I've searched a couple of times in the issues for specific keywords. Every of those I clicked, they spoke about the fact that the button wasn't there, which is not my case. I can search and link back to them if you want...

As for accessories, I'm using my MBP trackpad... Admittedly, I don't have to allow things often in a year, but I've never had this trouble outside of the use with Keybase.

**Comment by strib** [comment]
See if  https://github.com/keybase/client/issues/11763#issuecomment-410790612 helps.

**Comment by jpmurray** [comment]
First, thank you, that's one post that I did not get with the keywords I searched!

And... Yes, it works. That's plain crazy! But it work!

**Comment by strib** [comment]
Great!  Yeah, it's total madness on Apple's part.  No clue what's going on.
