### ISSUE TITLE
pgp sign/verify documentation is incorrect

### ISSUE THREAD

**Issue by paul-pearce** [keybase/client#1414]
https://keybase.io/docs/command_line errors I've found thus far:

* keybase pgp sign -i foo.txt --detach-sign
    * This should be keybase pgp sign -i foo.txt --detached
* keybase pgp verify -i foo.txt.asc
    * This generates an EOF on detached signatures, which is not obvious from the docs.
* keybase pgp verify -i foo.txt.asc foo.txt  
    * This is just completely broken and generates "Error parsing command line arguments: Command `pgp verify` doesn't talk any non-flag arugments"
    * Should be: keybase pgp verify -d foo.txt.asc -i foo.txt

**Comment by maxtaco** [comment]
Fixed the two simple issues, made tickets for the other issue. Thanks so much!
