### ISSUE TITLE
Unable to delete git repo

### ISSUE THREAD

**Issue by rapidstephan** [keybase/client#14155]
I managed to create two team git repositories in one step by accidentally double clicking the create button. The first one was deleted correctly, the other one can't be deleted:

* Client returns error: 
`ERROR CODE 2304 - There is no repo named "...". in method keybase.1.git.deleteTeamRepo`
* keybase git delete returns a warning and an error: 
`▶ WARNING Git repo doesn't exist. Deleting metadata anyway.`
`▶ ERROR can't find repo named ".../..."`

my log id: e7917bf8ff9f6a36535a931c

**Comment by strib** [comment]
@rapidstephan when you say it can't be deleted, do you mean that it's still being listed on the list of repos in the Keybase app?

@mlsteele this looks similar to what happened to you; do you know of any way to manually delete the entry on the server side?  Since it's gone from KBFS, there's not much I can do.

**Comment by mlsteele** [comment]
If a record exists on the non-kbfs server then I would expect `keybase git delete` to issue that `WARNING` and but to also delete the record and not `ERROR`. Try deleting it with and without a `.git` suffix. Like `keybase git delete blah` and `keybase git delete blah.git`.

**Comment by rapidstephan** [comment]
@strib sorry for being unclear. ;) Yes, by saying „cant be deleted“ I am referring to the fact that the repo is still listed in the UI as well as in the command line tool. `keybase git list` Lists the repo while telling me it does not exist when I try to delete it. Same sort of problem in the UI client: the repo is listed but every attempt to delete it within the UI client results in the error message stated in my first post. At the same time the repo does not work in git clients (because it apparently does not exist). 😄

**Comment by mlsteele** [comment]
Is there any chance you are confusing a personal repo named "t/r" with a team repo in team "t" named "r"? A slash in the name doesn't mean anything special to `keybase git delete`.
Could try to get rid of all four combinations and see if that hits it.
```
keybase git delete r
keybase git delete t/r
keybase git delete r --team=t
keybase git delete t/r --team=t
```

**Comment by poffe** [comment]
I'm experiencing the exact same issue. I've tried all the four combinations mentioned by @mlsteele above and also tried deleting the repo using the GUI.

I have a vague memory that I might have experienced a timeout the first time I tried to delete the repo though the GUI.

My log id: fb5d46d44f76b6de121dd41c

**Comment by strib** [comment]
@mlsteele the user is getting the error `There is no repo named "<repo_name>"` back from KBFS.  So I guess the service delete code should just treat that error as a success?  Or would you prefer no error in that case?  I don't know what assumptions that code makes.

**Comment by mlsteele** [comment]
@strib The service has a special case for RepoDoesntExistError. But it was only in the personal repo case. Patch coming up for the team case.

**Comment by mlsteele** [comment]
@poffe We could probably make your repo disappear by meddling with the server. But I would prefer waiting for the next client release and then have you try `git delete` again. To make sure it's fixed for everyone.

**Comment by poffe** [comment]
@mlsteele I'm in no rush so I can wait for the next client release. I'm happy to help out.

**Comment by poffe** [comment]
@mlsteele I'm happy to inform you that this issue is now solved (at least for me). Thx for the fix.

**Comment by rapidstephan** [comment]
Resolved for me, too. I successfully removed the repo now. Thank you. :)

**Comment by mlsteele** [comment]
Great!
