### ISSUE TITLE
Login issue

### ISSUE THREAD

**Issue by xidninja** [keybase/client#14181]
Keybase GUI Version: 2.7.3-20181005122557+83f5d808a7

While Login I am facing issue on my Windows 10. Not sure why it is showing me this error. As my computer has perfectly connected with WIFI as well as LAN and both are working. Please can you help to solve this.

Thanks

![image](https://user-images.githubusercontent.com/6700306/46744028-ece83800-ccc7-11e8-82d0-a4faa9ba2833.png)

**Comment by maxtaco** [comment]
Please send a log. ‘keybase log send’ from the command line.

**Comment by xidninja** [comment]
Hey,

I have tried to run command line but it is showing data can not send and then close my command line.

What I need to do here?

Thanks

**Comment by xidninja** [comment]
This command will send recent keybase log entries to keybase.io
for debugging purposes only.

These logs don’t include your private keys or encrypted data,
but they will include filenames and other metadata keybase normally
can’t read, for debugging purposes.

Continue sending logs to keybase.io? (type 'YES' to confirm): Yes
Enter feedback (or <Enter> to send):
- INFO Not sending up a UID for logged in user; none found

This is information that I am getting.

**Comment by xidninja** [comment]
Issue is solved. I have Check http_proxy from environment and removed it after restarting application it works again.

Thanks
