### ISSUE TITLE
keybase cli on Ubuntu 18.04 resulting in EOF

### ISSUE THREAD

**Issue by StevenXL** [keybase/client#14243]
Hi - 

The interactive feature of the keybase CLI is broken for me. The app won't wait for me to type in any info, and will instead error out with an EOF, since it is expecting some input. I'm running on Ubuntu 18.04:

```
lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.1 LTS
Release:        18.04
Codename:       bioni

keybase version
Client:  2.8.0-20181008202958+7cf71f6fcb
Service: 2.8.0-20181008202958+7cf71f6fcb
```

I've attached an example screenshot:

<img width="680" alt="screen shot 2018-10-14 at 5 40 32 pm" src="https://user-images.githubusercontent.com/7391433/46923085-5b830980-cfd8-11e8-916d-cc7983a64123.png">

**Comment by maxtaco** [comment]
cc @heronhaye who recently made some changes to the terminal.

**Comment by heronhaye** [comment]
@StevenXL Thanks for the report. Could you repro and do a `$ log send` from terminal?
