### ISSUE TITLE
keybase package no longer installs on Debian sid

### ISSUE THREAD

**Issue by yoe** [keybase/client#14287]
keybase installs a native messaging host for chromium by dropping a file in /etc/chromium/native-messaging-host

However, the new Debian package for chromium now creates a *file* /etc/chromium. This conflicts with the /etc/chromium directory in keybase, resulting in both packages not being allowed to be installed at the same time without a `--force` parameter to dpkg.

Keybase should move its native messaging host configuration file elsewhere, so that it continues working with new versions of Chromium.

**Comment by maxtaco** [comment]
Thanks for the headsup, we'll look into it right away

**Comment by zapu** [comment]
@yoe I looked around, and it looks like it has been fixed in debian: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=911056

can you confirm that a new version of chromium works for you?

**Comment by yoe** [comment]
Yes, that does seem to fix it. Thanks, and sorry for the noise :-)
