### ISSUE TITLE
Keybase on Mac App Store

### ISSUE THREAD

**Issue by mmattioli** [keybase/client#14282]
Can we bring Keybase to the Mac App Store?

**Comment by mmattioli** [comment]
@maxtaco bumping this

**Comment by maxtaco** [comment]
We can't, since we need to install fuse for KBFS, which needs a privileged helper.

**Comment by mmattioli** [comment]
@maxtaco the interest is more in the distribution of the app in large enterprise and education environments than it is in discoverability. Earlier this year at Apple's WWDC, [it was announced that Microsoft Office, BBEdit and Panic Transmit will be returning to the Mac App Store because of sandboxing improvements](https://9to5mac.com/2018/06/04/new-sandboxing-improvements-bring-transmit-back-to-the-mac-app-store/) so perhaps there is a way to achieve this with the enhancements in Mojave (10.14)?

**Comment by mmattioli** [comment]
I'm not 100% keen on the details but just did some quick digging and [this article points out](https://sixcolors.com/post/2018/06/with-mojave-apple-makes-changes-inside-and-outside-mac-app-store/):

> But in Mojave, the Mac App Store is getting more expansive. For example, Apps are able to ask for permission to creep out of the restrictive “sandbox” and access files more broadly across your Mac’s hard drive.

**Comment by mmattioli** [comment]
@maxtaco it'd be pretty nice, I think it's worth taking a good look at 😁

**Comment by mmattioli** [comment]
@maxtaco *bump*

**Comment by maxtaco** [comment]
It's not possible for us with our current feature set.  Now you're talking about having several Mac packages, which is a huge investment, and we're a small team.
