### ISSUE TITLE
MacOS Mojave KBFS not reading

### ISSUE THREAD

**Issue by mrjhnsn** [keybase/client#14292]
As of this morning, days after it was already working fine with Mojave, keybase FS is no longer reading files.

Have had a few other updates and restarts since Mojave upgrade and this is a new issue with Keybase.
I restarted keybase `keybase ctl start` before digging for logs, and it worked fine to re-establish the connection to the KBFS.

(edited as I accidentally saved the comment before I was done writing)
my log id: 41ebf91c872f2c2b0fc1561c

**Comment by strib** [comment]
@mrjhnsn It looks like you are having network issues trying to connect to our servers. From your kbfs log:

```
ping error write tcp [redacted]->52.2.201.95:443: write: can't assign requested address
```

That's the correct IP address for our server, but you can't seem to connect and I don't know of any outages right now.  So I'd check your network configuration, like any proxies or filters you're behind that might be blocking the traffic.

**Comment by mrjhnsn** [comment]
I figured it was a network connection issue but I was manually resolving the above ip fine. 
Restarting keybase fixed it, and I've largely found that `keybase ctl start` tends to resolve any issues.
BTW: Good effing job. I've had nearly zero issues with keybase, and I only filled this out and sent the log as I figured that there might be useful data for you from my env re this crash. Seriously good stuff guys.

**Comment by maxtaco** [comment]
A quick google yields this, and complaints that "no, the folks in Cupertino haven't fixed this bug yet": https://www.ibvpn.com/billing/knowledgebase/145/OpenVPN-error-write-UDPv4-Canandsharp039t-assign-requested-address-codeequals49.html

Oy, I hope that's not the right answer
