### ISSUE TITLE
This conversation needs to be rekeyed.

### ISSUE THREAD

**Issue by benkietzman** [keybase/client#14319]
I have a Kebyase chat with a buddy of mine.  We have had this chat going for a long time.  I have six authorized devices.  I have noticed the following error message on two of the devices when I attempt to open the chat conversation with this particular user:

This conversation needs to be rekeyed.

There is also a Rekey button.  I don't see this on any other conversations and I only see it on two of my devices and not the others.  The two devices I see it failing on happen to be Ubuntu Linux desktops.  Not sure if that has anything to do with the problem.  I have tried clicking the Rekey button, but it does not seem to do anything.  I chose one of the two devices and proceeded to uninstall the keybase application.  I also removed the ~/.cache/keybase and ~/.local/share/keybase directories for good measure.  I then reinstalled the keybase application, but the problem still persists.

I'm not sure what to try next.  Any suggestions?  Thank you.  I still chat with my buddy using two other devices, but they are not the primary places I usually use Keybase.  Any suggestions?  Thanks.

**Comment by strib** [comment]
If you run `keybase log send` from a device that has tried and failed to read the conversation, and post the resulting log ID here, one of us can take a look for you.

**Comment by benkietzman** [comment]
Log ID:  3a8d80731096a7e39f7bf01c

Thank you so much!

**Comment by strib** [comment]
@maxtaco: The folder is keyed for @benkietzman on their old devices named `server`, `slim2`, `file inner`, and `office`.  All of these devices are listed in https://keybase.io/benkietzman/sigchain, and none is revoked.  However, they don't appear in https://keybase.io/benkietzman/devices.  It feels like an account reset to me, except that the eldest key is the same now as in link 1 of the chain.

Any idea what's going on?  Were there bugs in the past that didn't properly change the eldest key after a reset?

**Comment by maxtaco** [comment]
The sigchain page recently broke (cc @xgess, @zapu, not sure who else)

There was an account reset at link 40 that's not being shown as such.

**Comment by maxtaco** [comment]
Those devices you mentioned are all prereset, as you suspected.  See [raw chain]( https://keybase.io/benkietzman/chain) and grep for `"eldest"`

**Comment by strib** [comment]
Ok thanks @maxtaco!

> Those devices you mentioned are all prereset, as you suspected. See raw chain and grep for "eldest"

This is exactly why I'm confused -- the eldest key on the newest links (past 40) still point to link 1 in the chain.

@benkietzman Looks like we need to reset the KBFS folder for you, if you want to regain access.  (You reset your account before we handled this automatically.  Your new devices won't be able to see the old data in the conversation (from before your reset), but hopefully it will get rid of the rekey message for you.

If you want us to reset your folder, please run this command on a currently-valid keybase device, and substitute your friend's name and the current date and time where indicated:

```
keybase sign -m "<DATE_AND_TIME>: Please reset folder /keybase/private/benkietzman,<FRIEND_NAME> because all the devices that have access have been revoked."
```

and post the results here.

**Comment by benkietzman** [comment]
BEGIN KEYBASE SALTPACK SIGNED MESSAGE. kXR7VktZdyH7rvq v5weRa0zkVIl2nL 2GDY1pekqVa0ZrL vJtkJmy6XHmSn3M 7c26fDySiKLdQn1 CfTORmqNcV8iZBJ tYEzTYuXSZ9NBlW dNVuXeEfRMVGb0H 9GvTs6wGedcF4Lx 1PHpCVCz8m56TKE RwwpPlUOC7GfPxB 03Rv7CWZ8x2fN98 g7Zvj0tBQrK1byw m3YvAbcGrDiU8vJ FosngJ4OQO97AIo XwSyMjs05DruYA7 4w8Jw8OlGxs29KU pj7S4RdVknLBu5s j4pk4nmlT3oUjqB rozmqIi3JkSNhSQ FN6qgmZwwmakjMN kdBSYPmIMjiTpKB 7HGOZtFS4YpA2r1 4TxRAxAf9FtUGWo GC4I6bhtSd2GEKa xK. END KEYBASE SALTPACK SIGNED MESSAGE.

**Comment by strib** [comment]
I reset the folder.  Please check it out and close this if everything seems ok.  (Might require a Keybase restart.)

**Comment by strib** [comment]
@benkietzman please do a new `keybase log send` and we'll investigate.

> I attempted to access our private files and received the following error:

This error was within the Keybase app, or from the command line / finder?

**Comment by benkietzman** [comment]
This was from within the Keybase app.  From the Ubuntu Linux command line is see the following error when attempting to get a listing of the private directory:

ls: cannot open directory '.': Permission denied

By the way, I also restarted Keybase using the run_keybase command and see the same result afterward.

**Comment by strib** [comment]
Ok.  When you get a chance please do `keybase log send` again, post the log ID here, and we'll take a look.

**Comment by benkietzman** [comment]
Log ID:  0744597b6fecf5eeadb5ee1c

Thank you.

**Comment by strib** [comment]
Looks like there's still one more piece that needs to be reset.  It's not something that I can do on the server-side though, not without nuking your entire chat history with your friend.

But we don't yet have a way for you to do it more selectively, which is why I've just put up keybase/kbfs#1867 and #14358 for review.  Once those are ready, I can make a special release for you (so you don't have to wait for the next public release), so you can run the reset command yourself.

**Comment by benkietzman** [comment]
I look forward to running the reset when the time comes.  Thank you for all the assistance.

**Comment by strib** [comment]
@benkietzman I made a release with the `keybase fs reset` command included in it: https://s3.amazonaws.com/prerelease.keybase.io/darwin-test/Keybase-2.8.0-20181023181333%2Bc53fd9baf6.dmg

You should be able to install that, run the command, and you should be able to have access to that folder again (it will be empty).

The above release includes everything in our upcoming 2.8.0 public release, plus this command and maybe a few other relatively untested things, so there's a small chance you'll experience some weirdness.  If so, let me know!

**Comment by benkietzman** [comment]
I installed the new MacOS version you provided.  I only have one Mac laptop so I installed it there.  I ran the "keybase fs reset /keybase/private/benkietzman,[buddy]" command and typed "YES" to confirm.  It responded with the following error message:

ERROR method 'simpleFSReset' not found in protocol 'keybase.1.SimpleFS'

Log ID:  070e8259eb7f20e7c35dac1c

**Comment by strib** [comment]
Sorry for the delay, I got distracted.

Here's the new build, please try the command again after installing it: https://s3.amazonaws.com/prerelease.keybase.io/darwin-test/Keybase-2.8.0-20181023202214%2Bc53fd9baf6.dmg

**Comment by benkietzman** [comment]
Thank you for the updated version.  I used it to run the command and it worked.  You were right that it wiped out the storage in the KBFS for the shared private folder.  However, that folder does work again.

I then did a run_keybase from my Ubuntu Linux laptop and attempted to view my chat history with my buddy.  I can no longer see our chat history.  All our historic chat message say the following error:

error unboxing chat message: decryption key not found for generation: 17 kbfsEncrypted: true public: false

I'm okay with those errors I guess, but then I attempted to chat my buddy and received the following error:

Failed to send: boxing error: invalid TLFID for name in header, [...] != [...] perm: true

Log ID:  42e9d645c15ddf0387b4981c

**Comment by strib** [comment]
I'll have to hand this off to @mmaxim, who knows about the chat side of things.

@mmaxim: the relevant implicit team ID is `4b57f012e823faa2ed48a5ee63e90724`.  The reset command I had the user run adds a new kbfs link to the team sigchain with a new TLF ID in it.  The previous version of the TLF has been reset and its keys are no longer available.  Looks like chat is upset when the TLF ID changes, but I thought you had fixed a bug related to that already.

**Comment by mmaxim** [comment]
I'll take a look. In the meantime, if you want to keep chatting you can create a team with your friends and start a new conversation on it. Sorry!

**Comment by benkietzman** [comment]
This is no longer an issue as I am no longer using Keybase on a MacBook.  Thank you for the assistance along the way.  It was much appreciated.
