### ISSUE TITLE
conflict with chromium package in debian

### ISSUE THREAD

**Issue by pnl** [keybase/client#14368]
Hi,

It seems that the debian package (in sid) for chromium changed layout in `/etc`:

```
dpkg: error processing archive /var/cache/apt/archives/keybase_2.8.0-20181023124437.06221a8264_amd64.deb (--unpack):
 trying to overwrite '/etc/chromium', which is also in package chromium 70.0.3538.54-2
```

**Comment by maxtaco** [comment]
This happened last week, and should be fixed.  I should mention it was out of our control.

**Comment by pnl** [comment]
Thanks for the prompt answer.

Are you implying the issue is fixed?
Can't seem to find the fix in master branch.
Today's build is still affected.

Am I using the best source for debian sid packages?
```
# apt-cache policy keybase
keybase:
  Installed: (none)
  Candidate: 2.8.0-20181023124437.06221a8264
  Version table:
     2.8.0-20181023124437.06221a8264 500
        500 http://prerelease.keybase.io/deb stable/main amd64 Packages
```

**Comment by maxtaco** [comment]
Maybe if you update `chromium`?

**Comment by pnl** [comment]
Yes.  The change was reverted in debian and this issue is moot.

Thanks.
