### ISSUE TITLE
keybase hijacks Cmd+Shift+f

### ISSUE THREAD

**Issue by nicholascloud** [keybase/client#14388]
Keybase GUI Version: 2.7.3-20181005191950+83f5d808a7
OSX 10.14 Mojave

When I hit `Cmd+Shift+f`, a common IntelliJ IDE family shortcut for "find in x", my keybase public key fingerprint is pasted into an input that has focus. (Verified this occurs in PHPStorm, TextEdit, and iTerm. FireFox and Chrome don't seem to be affected. Not sure why some programs have this issue and others do not.)

**Comment by solace** [comment]
I have this issue. Not only does it paste my key into the input, but also intermittently triggers the passphrase prompt.

**Comment by nicholascloud** [comment]
This appears to be an issue with OpenPGP registering keyboard services in OSX.

<img width="780" alt="screen shot 2018-10-29 at 3 44 57 pm" src="https://user-images.githubusercontent.com/513420/47679217-bc424280-db91-11e8-94ae-fbec625cba53.png">

So likely not a bug with Keybase. Disabling this service fixed the problem.

`System Preferences -> Keyboard -> Shortcuts -> Services`
