### ISSUE TITLE
git "Last push" date incorrect

### ISSUE THREAD

**Issue by srsudar** [keybase/client#14423]
I have a keybase git repo that appears to be behaving correctly. I can make local changes, `git push`, and I can clone the repo (using the `keybase://` scheme but on the same machine), and everything appears to be working.

However, the keybase client it incorrectly shows "last push 9 days ago", which is when I created the repo. This makes me nervous that something isn't updating correctly. This problem has persisted across a restart. Is there anything else I should be trying to correct it?

I am on Mac OS.

**Comment by strib** [comment]
@srsudar please run `keybase log send` from the device that did the pushes that aren't showing, and post the resulting log ID here.

cc: @patrickxb @mlsteele for the server-side of this.  I'm not aware of any git-remote-keybase changes that would affect it.

**Comment by srsudar** [comment]
Here is the ID:

    46c4f6e7df5e363b9fd4dc1c

The command failed the first time with `Client.Timeout exceeded while awaiting headers`. This makes me realize that perhaps I should add that I have a few hundred photos in the repo, which makes it big and slow to clone. No idea if that matters in this case, but it's the only way I think it is an unusual repo.

**Comment by strib** [comment]
Is it possible you did something unusual when creating the repo, like writing it with different cases, or with/without the `.git` prefix, and then deleted it and recreated it?

I wonder if there's some leftover old repo with the same name in our server-side database that is confusing things.  (The names are encrypted on our side, so I can't check.)

**Comment by srsudar** [comment]
Hmm, maybe. I tried to follow your instructions [here](https://keybase.io/blog/encrypted-git-for-everyone) on moving an existing repo to keybase. I would believe that I ctrl+c'd somewhere in there, did a step weird or something.

In that case I would be cloning the correct version with my clone on the same machine (assuming it hits the server and isn't clever using the local file system instead) but the timestamp is being taken from the old version?

**Comment by strib** [comment]
Yeah that's my best theory.  If the case, we might be able to fix it server-side by clearing out the stale state, or you could just delete the repo, recreate it, and re-push everything to it.  Though that might be painfully slow with a big enough repo.

**Comment by srsudar** [comment]
I tried deleting and re-pushing. I'll monitor it over the next few days and will close if that fixes it.

**Comment by srsudar** [comment]
Huh. I re-created the repo yesterday, and 9 hours or so later did a push. The timestamp didn't update. But I just did a tiny edit and a push, and it now it correctly says "updated a few seconds ago". Confusing...

I'm going to leave this open a bit longer as I continue to monitor it.

**Comment by strib** [comment]
Great find!  I just put up a PR that should fix it, and should also fix other issues I noticed around mismatched branch names between the local repo and the server: keybase/kbfs#1882.

**Comment by srsudar** [comment]
Awesome, glad to hear it. Out of curiosity, are there tests somewhere for the git helpers? I only see the implementation on keybase/kbfs#1882.

**Comment by strib** [comment]
The git helper has plenty of tests in the kbfs repo, but not specifically for the metadata update messages we send to the servers which contain the timestamps, etc, as that's a multi-component test and much harder to write.  Hopefully some day.

**Comment by srsudar** [comment]
Ah I see.

Where were my pushes to `HEAD` going, in that case? Was everything working, just the timestamp was failing? Do I have a remote branch named `HEAD`? The PR mentions something was erroring out--was data not being pushed? From the CLI it looked like everything was fine. If this was more than a cosmetic failure I'd have expected an error message somewhere.

**Comment by strib** [comment]
Data was being pushed -- all git functions were working as expected.  It was erroring internally before updating our separate DBs that power the cosmetic timestamp thing.  And because it's cosmetic, we don't surface an error to the user.  There was one in the logs though.

**Comment by srsudar** [comment]
Perfect, glad to understand it. Probably could have gotten that if I'd spent some time on the PR; thanks for walking me through it.

I'll let you close when merging. Thanks for the good work!

**Comment by strib** [comment]
Merged!
