### ISSUE TITLE
macOS Ugly Error Message

### ISSUE THREAD

**Issue by fargozhu** [keybase/client#14432]
OS version: macOS 10.14 (18A391)
Keybase version: 2.8.0-20181023171250+c7287208b0

![screenshot 2018-10-26 at 10 17 40](https://user-images.githubusercontent.com/904062/47557603-63647700-d911-11e8-80a6-c7ebbeb7328b.png)

**Comment by maxtaco** [comment]
CC @keybase/react-hackers

**Comment by chrisnojima** [comment]
investigating

**Comment by chrisnojima** [comment]
PR up, thanks!
