### ISSUE TITLE
FUSE integration error

### ISSUE THREAD

**Issue by benhinc** [keybase/client#14448]
Error: FUSE integration is not enabled at On.q.j.e.fs.fuseStatus.e.fs.fuseStatus.kextStarted.Promise (file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/index.bundle.js:1:2560159) at new Promise (<anonymous>) at On (file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/index.bundle.js:1:2560138) at file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/index.bundle.js:1:1223901 at A (file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/index.bundle.js:1:1224002) at T (file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/index.bundle.js:1:1221912) at F (file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/index.bundle.js:1:1222689) at file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/index.bundle.js:1:1224636 at A (file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/index.bundle.js:1:1224659) at T (file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/index.bundle.js:1:1221912)

my log id: 6627585f8ea2f99054cfbf1c

**Comment by strib** [comment]
The error here is really weird, it seems to be complaining that a file doesn't exist, which usually comes with the distribution:

```
/Applications/Keybase.app/Contents/Resources/KeybaseInstaller.app/Contents/Resources/kbfuse.bundle
...
Fuse: Install Error: The file "kbfuse.bundle" doesn't exist.
```

Maybe reinstalling Keybase will help?  Not sure how this is possible.

**Comment by benhinc** [comment]
I was able to get it to work.

FUSE for macOS was listed in my System Preferences but reported that it wasn't installed when I accessed it. I downloaded it from https://osxfuse.github.io/ and installed it. Next time I launched Keybase, everything was fine.

This issue started after I formatted my disk and reinstalled from a Time Machine backup.
