### ISSUE TITLE
Facebook proof failed.

### ISSUE THREAD

**Issue by brav0charlie** [keybase/client#14497]
Getting an error when trying to verify Facebook. 

"Error 500. Something is not right. We will look into it."

Link to FB proof post: https://www.facebook.com/billclark/posts/10156145985291902

Post is set to public.

I've tried both via curl & via the Keybase CLI app, same result each time. Link above is to my most recent try that failed.

**Comment by mlsteele** [comment]
Fixed see https://github.com/keybase/client/issues/14537#issuecomment-435939898

**Comment by brav0charlie** [comment]
Tested & confirmed working. Thanks!
