### ISSUE TITLE
Cant access group repo after user deleted his account

### ISSUE THREAD

**Issue by kotoyants** [keybase/client#14525]
We have a couple group repos and after one of the members deleted his keybase account we cant access repos any more:
`git clone keybase://team/private_group/repo1
Cloning into 'repo1'...
Initializing Keybase... done.
Syncing with Keybase... Could not verify metadata (revision=50) for directory /keybase/team/private_group (id=00b765c13312be48f54a0fbfa4a70326): No public key found
git-remote-keybase error: (1) Could not verify metadata (revision=50) for directory /keybase/team/private_group (id=00b765c13312be48f54a0fbfa4a70326): No public key found`

**Comment by maxtaco** [comment]
@kotoyants can you `keybase log send`?

**Comment by kotoyants** [comment]
Log ID: 901ed6113fc866009bafe21c

**Comment by maxtaco** [comment]
Thanks @kotoyants. CC @strib

**Comment by joshblum** [comment]
@kotoyants the fix is merged in #14541 and we just released a new linux build with the changes (2.10.0_20181101184721+aad4943508), let us know if you have any other issues!

**Comment by kotoyants** [comment]
Fixed
