### ISSUE TITLE
MacOS client, High Sierra 10.13.6 - FACEBOOK proof is unreachable

### ISSUE THREAD

**Issue by chluther** [keybase/client#14568]
While attempting to validate against Facebook I'm experiencing a problem.  Keybase presents the FB Posting Window, but after I save I'm redirected to: 

`https://keybase.io/_/facebook_post_redirect?sig_id_med=REDACTED&keybase_token=REDACTED 
`

And the error says:

"Error 500. Something is not right. We will look into it."

I approve the Keybase dialog and it is unable to verify.

I close the window and return to Facebook https://www.facebook.com/chris.d.luther and the post is there - and it is set to public.  However in Keybase my facebook provide is shown as "unreachable"

I wait several hours I get an email:

========

>   Hi, cluther, your attempted facebook identity proof of chris.d.luther never succeeded. We've been checking it repeatedly, and from our perspective, it's either (a) not there, or (b) not posted precisely.

=======

Following recommendation in keybase/keybase-issues#2957, I deleted the FB proof and FB post and tried again.  Same thing.

On the third try I follow the email's suggestion and in terminal run:

    $ keybase prove facebook

Eventually the function returns

=================

`   https://facebook.com/v2.9/dialog/oauth?client_id=REDACTED&display=popup&response_type=code&scope=user_posts&redirect_uri=https%3A%2F%2Fkeybase.io%2F_%2Ffacebook_login_redirect&state=%7B%22sig_id_med%22%3A%22K_oLuTqfCicJEWV8Nq-REDACTED`

================

I tried to use this URL to create a new FB post, but the error persists.

I'm unable to verify against Facebook.

Thanks,

Chris Luther

**Comment by mlsteele** [comment]
Fixed see https://github.com/keybase/client/issues/14537#issuecomment-435939898

Thanks for the detailed report!

**Comment by chluther** [comment]
verified.  Thanks for the quick fix.
