### ISSUE TITLE
Keybase copies public key fingerprint into Intellij Search!?

### ISSUE THREAD

**Issue by dnno** [keybase/client#14594]
Keybase GUI Version: 2.9.0-20181029210507+02197a56e8

Hi since a few days, I notice that when I use Intellij IDEA, my gpg public key fingerprint is copied into the search window whenever I open it. When I restart without keybase, this doesn't happen. When I start keybase, the behaviour shows again. No other application shows this behaviour.

I know this sounds weired and oddly specific... :-/

Any ideas? Please tell me if I can add additional info to help you get to the bottom of this.
![screenshot](https://user-images.githubusercontent.com/2003552/48059958-d3e58080-e1ba-11e8-87e9-d9e425fb17df.png)

**Comment by dnno** [comment]
It seems I was to quick, opening this issue. Even with keybase closed, the behaviour started showing again. I reset the project and it looks like it's gone now. Closing this issue for now. Sorry...

**Comment by wielinde** [comment]
@dnno I had that issue before and it came back somewhen around the time I updating my Mac to Mojave, GpgMail and Rubymine (IntelliJ). I don't use keybase. So this is the wrong place here... However, did you find any solution yet?
