### ISSUE TITLE
Exploding message shows in chat description after its exploded.

### ISSUE THREAD

**Issue by jayuuza** [keybase/client#14595]
I created a message that was specified to explode after 5 minutes. It exploded fine. However, the chat description on the left of the chat shows a preview of the last message sent. Which in this case was a key I sent.

Previous chats show a boom! emoji in their preview but not for my latest one. I haven't closed my client or started a new chat since.

Not sure what data to give to support this claim.

**Comment by joshblum** [comment]
@jayuuza can you do a log send and note the id here?

**Comment by benoittgt** [comment]
I just saw this error too. I can try to reproduce with logs if needed.

**Comment by joshblum** [comment]
@benoittgt logs would be great!

**Comment by joshblum** [comment]
https://github.com/keybase/client/pull/22656 should fix this
