### ISSUE TITLE
unable to generate pgp key

### ISSUE THREAD

**Issue by tcondit** [keybase/client#14627]
This is on a Mac with Mojave 10.14.1

➜ keybase pgp gen --multi
Enter your real name, which will be publicly visible in your new key: Tim Condit
Enter a public email address for your key: tcondit@gmail.com
Enter another email address (or <enter> when done):
Push an encrypted copy of your new secret key to the Keybase.io server? [Y/n]
When exporting to the GnuPG keychain, encrypt private keys with a passphrase? [Y/n]
▶ ERROR could not find UID or username for self

my log id: 3a85bf1f774cbe5fbeeaf51c

**Comment by maxtaco** [comment]
`keybase login` and then try again

**Comment by maxtaco** [comment]
We just need a better error message there, but I repro'ed this issue locally, and it should work with a login.
