### ISSUE TITLE
can't chat to someone when you've hidden previous conversations

### ISSUE THREAD

**Issue by brakesec** [keybase/client#14625]
I have a number of conversations in my keybase  chat application for Windows (I use it for work). scrolling through them because a bit of a pain, so I thought it might be easier to 'hide' some of my co-workers that I'd not spoken to in a while, not realizing there isn't an 'unhide'. "Not a problem, I'll just find them in a team chat, open up the chat window and talk to them again."  Easier said than done. When I find the person, the first message I get is "you haven't chatted with '$USER' yet." , which is not true, I just haven't spoken to them in a month. I click 'Start Chatting' and my chat history with them opens, and I can see it with no issues.  I then start typing a message to them, and hit "enter" to send. $USER's chat window with me disappears, and when I ask them if they received the message (I emailed him asking him WTF is he not answering me), and he stated he did not. The only way to 'fix' the problem is to have the person message me, which appears to fix the problem and we can continue to chat as normal.

Steps to Reproduce:

Step 1: Chat to a $USER
Step 2: Open the Command line (powershell or cmd), and type "keybase chat hide $USER"
Step 3: Find $USER again in Keybase, open $USER's profile panel and click 'Chat'  (should error with "you haven't chatted with $USER yet)
Step 4: Click "Start Chatting" (box should open with previous chat history)
Step 5: Type a message to $USER, hit enter (notice how the $USER chat window disappears from side bar on the app, requiring you to attempt Steps 1-4 again)
Step 6: Reach out to $USER through another media, and ask them to send you a message
Step 7: chat window will come back and stay, operating as per normal

**Comment by maxtaco** [comment]
Have you tried `keybase chat hide --unhide $USER` ?

**Comment by brakesec** [comment]
great... that worked... but when I re-open the chat through the GUI it should allow me to send messages and should be smart enough to realize that I want to continue the conversation, even after I hid it... and leave it unhid. That the whole reason for the bug... 
Just seems like too many things not in the GUI... opening a CLI for deleting a team, for example...

Appreciate the help... keep at it, the GUI will get there one day
