### ISSUE TITLE
Unable to create personal git repository

### ISSUE THREAD

**Issue by brkattk** [keybase/client#14680]
Windows 10

GUI gives `ERROR CODE 218 - Can't get TLF private key for key generation 5 in method keybase.1.git.createPersonalRepo`

Command line gives `- ERROR Can't get TLF private key for key generation 5`

**Comment by maxtaco** [comment]
Can you `keybase log send` ?

CC: @strib

**Comment by maxtaco** [comment]
OR cc: @mmaxim

**Comment by brkattk** [comment]
my log id: 0b2c25ff0d82a4e279d8571c

**Comment by strib** [comment]
@brkattk looks like that folder is keyed for the device you're using (`xuul-9370`).  Can you log into Keybase from one of your existing devices with access, either `mbp-zuul`, `zuul18`, or `pixel-two`?  If those are already online or you've already tried that, it would be useful to get a `keybase log send` or feedback sent from one of those devices, to figure out why it hasn't been rekeyed.

Seems like you added this device just today, from `pixel-two` -- maybe you closed the app right away after provisioning it, and it didn't have time to rekey?  Or maybe something else is wrong...

**Comment by strib** [comment]
(Edit above -- *not* keyed.)

**Comment by brkattk** [comment]
I may have tried creating the git repo too soon? I did do it almost immediately after adding the new device, from the new device.

I got that error above and tried also adding the git repo from the `pixel-two` device, but I don't know how to send logs from the phone.

Here's some logs from `zuul18`: `ffaa5d3a9bdf9dd5572b061c` `fc5817c94dda39dac061a91c`

I tried creating the repo on that machine and it did eventually work

**Comment by strib** [comment]
Thanks.  Yeah things look fine now for all your devices on our side.  I think you hit a known performance bug where everything gets slow when you revoke a device that had written to that folder in the past.  We have a fix but it's not out in a release yet.  So probably it just took a while to do make the folder available to your new device.  Sorry about that!

P.S.: On the phone, you can "Send feedback" from one of the menus, to send us logs.  But don't worry about that now, all looks fine.

**Comment by brkattk** [comment]
No worries. Thanks!
