### ISSUE TITLE
Keybase keeps sending error code 218 on chat and filesystem operations

### ISSUE THREAD

**Issue by euribe** [keybase/client#14707]
Cannot see chats nor filesystem no newly provisioned device.

Log ID: 7e6a06333cff434fadcf9a1c

**Comment by strib** [comment]
@euribe your local disk is giving input/output errors when we try to read or write it.  You should run diagnostics on it and try to repair it.

**Comment by euribe** [comment]
Ran fsck and scan surface. No errors reported. If it helps, I'm able to mount other fuse filesystems  (sshfs and encfs).

**Comment by strib** [comment]
The error is unrelated to mounting.  It's that Keybase is trying to read a database from disk and the disk is return an I/O error.

The db is just a cache so maybe you can try removing it and somehow that will magically fix it?  Something like:
```sh
killall kbfsfuse
rm -rf $HOME/.local/share/keybase/kbfs_block_cache
run_keybase
```

But I suspect you'll eventually hit that bad disk sector again.

If that doesn't work, please do another `keybase log send`.

**Comment by euribe** [comment]
You were right. Once deleted the db, the app started to work seamlessly. Thank you very much.

**Comment by GwynethLlewelyn** [comment]
For those coming to this topic and using macOS, the equivalent directory on a Mac is
```bash
~/Library/Application Support/Keybase/kbfs_block_cache
```
I'm actually surprised at how many problems this fixes (when you get those dreaded 'error code 218' messages all over the place)!
