### ISSUE TITLE
Unclearable team notification

### ISSUE THREAD

**Issue by crackmac** [keybase/client#14779]
Seeing the same unclear able team notification as GitHub issue #12939 

my log id: 1b15bcb593a7dee67c47f11c

**Comment by crackmac** [comment]
Cleared by @maxtaco. Thank you!

**Comment by maxtaco** [comment]
Sure, thanks.  There's still an underlying issue we need to fix... Next sprint....

**Comment by rr-jonathan-lundy** [comment]
seems related: #13822
