### ISSUE TITLE
[question] Official alpine package

### ISSUE THREAD

**Issue by trsdln** [keybase/client#14792]
Is this https://pkgs.alpinelinux.org/package/edge/testing/x86/keybase-client official alpine package?

**Comment by maxtaco** [comment]
Not sure, but it's pretty out of date!

**Comment by trsdln** [comment]
are there any alternative ways to get it up and running at Alpine?

**Comment by holycleugh** [comment]
You can build it from source and/or inspect the `.deb` file with `ar` at https://prerelease.keybase.io/keybase_amd64.deb to see how it's installed on other distros.

**Comment by heronhaye** [comment]
You can build it from source and/or inspect the .deb file with ar at https://prerelease.keybase.io/keybase_amd64.deb to see how it's installed on other distros. Let us know if you have any questions!

**Comment by trsdln** [comment]
I can figure it out. Thanks.
