### ISSUE TITLE
install on Android custom rom crashes

### ISSUE THREAD

**Issue by DieterVanWerkum** [keybase/client#14809]
Hi guys,

There's nothing wrong with the logs I just filed 
my log id: 387de7f0a8c963f01d36191c

I just wished to let you know that Android Install (succeeded but) crashes my (faithfull) custom rom everytime. 
([GT-I9001][ROM][ION][4.4.4][KTU84Q] CyanogenMod 11.0 by ADC-Team - Release 17 [EOL]

I know it's old so maybe you don't consider this a bug? Would updating to LineageOS make any difference?

Best regards,
Dieter

**Comment by Hattshire** [comment]
Probably it's not due the customrom, but due to it being a kitkat rom, it's the same on my kitkat tablet on stock samsung.
This is due to compiling react's javascriptCore with NDK targetting API21+, were the function "signals"  it's not inline anymore.

Related:
#14828

**Comment by DieterVanWerkum** [comment]
Okay, thanks.
