### ISSUE TITLE
Latest keybase_amd64 on Ubuntu 16.04 fails `run_keybase`

### ISSUE THREAD

**Issue by yorinasub17** [keybase/client#14801]
Hello!

It looks like `keybase_2.11.0-20181121142914.6c100090f3_amd64.deb` has a regression where `run_keybase` fails to complete on ubuntu 16.04. The error I get is:

```
▶ ERROR dial unix /run/user/1000/keybase/keybased.sock: connect: no such file or directory
```

Downgrading to `keybase_2.10.0-20181112152732.f71edc2808_amd64.deb` worked.

**Comment by heronhaye** [comment]
@yorinasub17 Sorry about that, could you try installing the latest version?

**Comment by yorinasub17** [comment]
Thanks @heronhaye and @strib ! I have tried the latest version and it worked. Thanks for the quick turnaround!
