### ISSUE TITLE
Job for kbfs.service failed because a timeout was exceeded

### ISSUE THREAD

**Issue by mortenkjarulff** [keybase/client#14813]
Hi,

my log id: 5f1275db48ee68a553f66e1c

Some kind of timeout.

/Morten

morten@morten-Lenovo-M30-70:~$ run_keybase
Shutting down keybase service...
Starting via systemd...
Job for kbfs.service failed because a timeout was exceeded.
See "systemctl --user status kbfs.service" and "journalctl --user -xe" for details.
Job for keybase.service failed because a timeout was exceeded.
See "systemctl --user status keybase.service" and "journalctl --user -xe" for details.
morten@morten-Lenovo-M30-70:~$ ls /keybase/private/mortenkjarulff/
kbfsbak.sh  mshare  ssh  tmp
morten@morten-Lenovo-M30-70:~$ keybase log send

**Comment by maxtaco** [comment]
Bug from yesterday. Upgrade? Cc @heronhaye

**Comment by heronhaye** [comment]
Yes, that should've been fixed by the update.

@mortenkjarulff Are you on the latest version? If you are, could you post your OS and the info that's in each of 
```
$ systemctl -user status keybase.service
$ systemctl -user status kbfs.service
$ sha256sum /usr/lib/systemd/user/keybase.service
```

**Comment by mortenkjarulff** [comment]
Hi,

After I reported this issue, I upgraded my ubuntu from 18.04 to 18.10, and now it seems to work fine.

Client:  2.11.0-20181121195344+99751ac04f
Service: 2.11.0-20181121195344+99751ac04f

Do you want me to debug something? Else - I am glad ;-)

/Morten

**Comment by heronhaye** [comment]
Nope, all good. Thanks for the report, glad it's working again.
