### ISSUE TITLE
trying to write to kbfs

### ISSUE THREAD

**Issue by voobofdoom** [keybase/client#14818]
[write something useful and descriptive here]
first time, just installed and `echo 'hello' > ~/keybase/public/voobofdoom/hello.txt` 

logs show
```
[WARN kbfs(PRE) prefetcher.go:683] 00b error prefetching block 0171eac9df95176e8337370fe932e0499e24f437780e28ab3b0677bd9d15c644d0: Couldn't get block 0171eac9df95176e8337370fe932e0499e24f437780e28ab3b0677bd9d15c644d0, canceling [tags:FBOID=Z0oR3KqflhmBXGe06bmSMA]
```

my log id: bfa21e2350abde4d04b6271c

**Comment by strib** [comment]
That's expected.  In general our logs aren't very readable by non-devs, sorry about that.

If you are experiencing an actual error with reads or writes, please re-open.
