### ISSUE TITLE
UI glitch on iOS

### ISSUE THREAD

**Issue by rex4539** [keybase/client#14811]
2.10.1-20181120161535+c259d175df

Reproducibility: always

Steps:
1. Search for user `gka`
2. Tap on Following
3. Scroll down until just a bit before the end 

What happened:

https://www.icloud.com/sharedalbum/#B0e5CmvAS4nF3q;0E8EDF82-B97F-4DEA-88A3-CC8D70AE04BA

Expected result:
No UI glitch.

**Comment by rex4539** [comment]
@maxtaco Any updates on this?

**Comment by maxtaco** [comment]
cc @chrisnojima on this, my guess is it's all getting ripped out and replaced pretty soon

can't see that shared photo btw

**Comment by maxtaco** [comment]
Oh, I can see the video.  @chrisnojima is your person for this

**Comment by chrisnojima** [comment]
Yeah in the next release this screen is entirely rewritten

**Comment by rex4539** [comment]
Fixed with 3.1.0
