### ISSUE TITLE
Preview permission prompt does not have "just now" or "just today" option

### ISSUE THREAD

**Issue by Avamander** [keybase/client#14814]

**Comment by joyeusenoelle** [comment]
More information: 

When a website offers a preview card, Keybase may attempt to fetch it, but it will ask permission first. The permission options look like this:

![Screenshot of Keybase preview card options](https://user-images.githubusercontent.com/4139417/49346671-ca3d2480-f663-11e8-869b-a2d0830ab294.png)

For those without images enabled, the options are:

* Always, for any site
* Always, for <site linked to>
* Not now
* Never, for any site

This list should include at least one more option - the option to include the preview card this time but not set a preference:

* Yes, for this link

If I want to allow a certain event, it's bad UI design to force me to allow all future events of that type - especially when the UI also doesn't appear to allow me the ability to change my mind.

**Comment by joyeusenoelle** [comment]
In addition, there's room for a second additional option, the option to not include preview cards for this site without disabling them 100%:

* Never, for <site linked to>

This one is not as necessary, though.

**Comment by strib** [comment]
Try upgrading to the latest Linux release, there are more options and you can change your choices in the Settings menu.

**Comment by joyeusenoelle** [comment]
This must have been very recent; my build was less than a week old. Thanks for the heads-up.
