### ISSUE TITLE
"Root redirector" syntax error when updating under Ubuntu 18.04

### ISSUE THREAD

**Issue by myersjustinc** [keybase/client#14815]
Just did an `apt upgrade` on my Ubuntu 18.04 machine and noticed this output when it got to the Keybase client:

```
Setting up keybase (2.11.0-20181121195344.99751ac04f) ...
Restarting existing root redirector.
bash: -c: line 0: syntax error near unexpected token `('
bash: -c: line 0: `nohup "/usr/bin/keybase-redirector" "/keybase" &>> /keybase/keybase.redirector.log &'
Root redirector now running as jcm.
Redirector hasn't started yet.
```

Haven't noticed any other weird behavior yet (and didn't see anything else in my apt output), but is this anything I should be worried about?

**Comment by strib** [comment]
@myersjustinc interesting.  Is `$XDG_CACHE_HOME` set to anything unusual for the account that's running keybase (`jcm`)?  Maybe something with a parenthesis in it?

**Comment by myersjustinc** [comment]
For what it's worth, I just updated again to 2.11.0-20181127185939.b44f456354 using Ubuntu's Software Updater utility (since it prompted me), and I didn't get that error. Only got the line that said `Restarting existing root redirector.` Maybe nothing to worry about!

**Comment by heronhaye** [comment]
Thanks for the update. Let us know if it happens again!

**Comment by myersjustinc** [comment]
@heronhaye As requested, letting you know since this has happened again. It's happened for the last few updates, at least, but I don't remember for sure when it started again. In any case, it's been helpful that the `run_keybase` instruction has been added.

Relevant portion of my `apt upgrade` run, along with the packages immediately before and after:

```
Setting up linux-headers-generic (4.15.0.66.68) ...
Setting up keybase (4.7.0-20191021162721.67d9526320) ...
Restarting existing root redirector.
Redirector hasn't started yet.
-su: -c: line 0: syntax error near unexpected token `('
-su: -c: line 0: `XDG_RUNTIME_DIR=/run/user/1000 systemctl --user -q is-active keybase.service 2> /dev/null'
Keybase not running via systemd for jcm.
Restart Keybase manually by running 'run_keybase' as jcm.
Setting up linux-modules-extra-4.15.0-66-generic (4.15.0-66.75) ...
```

**Comment by heronhaye** [comment]
Sorry to hear that, We're going to get rid of this autorestarting mechanism in the nearish future so this code won't run.
