### ISSUE TITLE
Android app crashing after fresh install

### ISSUE THREAD

**Issue by salmanaligeek** [keybase/client#14828]
Hi,
I have used Keybase on my phone in the past. But today, freshly installed Keybase is crashing again and again, not able to run it once successfully, I don't know why.

My phone is:
Motorola Droid XT-1030 with Android 4.4.4

**Comment by salmanaligeek** [comment]
How I can send feedback from app if hasn't launched once yet?

**Comment by maxtaco** [comment]
Yeah, that's what I figured, but that's what we usually do. Which version of the OS are you on?  You might be S.O.L. unless you attach a debugger yourself, sorry... This never happens as far as we know...

**Comment by salmanaligeek** [comment]
My phone is:
Motorola Droid XT-1030 with Android 4.4.4

**Comment by maxtaco** [comment]
Ah, that's an ancient OS version, we don't support it, sorry.

**Comment by maxtaco** [comment]
Here for one, sorry!

**Comment by Hattshire** [comment]
you do support it 7-7

https://github.com/keybase/client/blob/787e7fe9f3460e006a9f75ea4255357bec523301/shared/react-native/android/build.gradle#L6

**Comment by Hattshire** [comment]
https://github.com/react-community/jsc-android-buildscripts/issues/8

It's a problem with the way libjsc is compiled, i've copied the lib from another app and it worked fine (playstore version)

**Comment by Avamander** [comment]
@Hattshire From which app did you copy libjsc from? I'm encountering the same issue now.
