### ISSUE TITLE
Unable to run keybase as root.

### ISSUE THREAD

**Issue by DiagonalArg** [keybase/client#14840]
Similar, though not identical to the report [here](https://github.com/keybase/client/issues/11594), I am also unable to start keybase as root.  [Unsetting `XDG_RUNTIME_DIR`](https://github.com/keybase/client/issues/11594) is not working, nor does it help to add `Environment=KEYBASE_ALLOW_ROOT=1` to /usr/lib/systemd/user/keybase.service.  In addition, `keybase version` is not working as root.  I'm on Ubuntu 18.04.

As user:

```
$ keybase version
Client:  2.11.0-20181121195344+99751ac04f
Service: 2.11.0-20181121195344+99751ac04f
```

As root:

```
# keybase version
Oops, you are trying to run as an admin user (Uid: 0). This isn't supported.

# env KEYBASE_ALLOW_ROOT=1 --unset=XDG_RUNTIME_DIR run_keybase
▶️ INFO Starting keybase.service.
Job for keybase.service failed because the control process exited with error code.
See "systemctl --user status keybase.service" and "journalctl --user -xe" for details.
▶️ ERROR Failed to start keybase.service.
▶️ ERROR Error in spawning server process: exit status 1
▶️ ERROR exit status 1
# systemctl --user status keybase.service
● keybase.service - Keybase core service
   Loaded: loaded (/usr/lib/systemd/user/keybase.service; disabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Mon 2018-11-26 22:11:57 PST; 1min 24s ago
  Process: 2972 ExecStart=/usr/bin/keybase --debug --log-file=/root/.cache/keybase/keybase.service.log service (code=exited, status=2)
 Main PID: 2972 (code=exited, status=2)

# systemctl --user status keybase.service
Nov 26 22:11:57 ThinkPad-T440p systemd[2313]: keybase.service: Service hold-off time over, scheduling restart.
Nov 26 22:11:57 ThinkPad-T440p systemd[2313]: keybase.service: Scheduled restart job, restart counter is at 4.
Nov 26 22:11:57 ThinkPad-T440p systemd[2313]: Stopped Keybase core service.
Nov 26 22:11:57 ThinkPad-T440p systemd[2313]: keybase.service: Start request repeated too quickly.
Nov 26 22:11:57 ThinkPad-T440p systemd[2313]: keybase.service: Failed with result 'exit-code'.
Nov 26 22:11:57 ThinkPad-T440p systemd[2313]: Failed to start Keybase core service.
```

**Comment by DiagonalArg** [comment]
Ok, rebooting has gotten it working as long as I have (1) `Environment=KEYBASE_ALLOW_ROOT=1` in /usr/lib/systemd/user/keybase.service and (2) start it from the command line as `env KEYBASE_ALLOW_ROOT=1 run_keybase`

One problem remains.  The directory /keybase is linked to /opt/keybase/mount-readme, but that latter file does not exist.

**Comment by maxtaco** [comment]
If you guys want to use KEYBASE_ALLOW_ROOT, you might consider skipping `run_keybase` and just launching the keybase services by hand.

**Comment by DiagonalArg** [comment]
@maxtaco - ok, you would mean:

`systemctl enable --user keybase.service && systemctl enable --user kbfs.service && systemctl enable --user keybase-gui.service`

Is that right?  Since I'm not booting into root, is there a way to get that to run on startup?  

I'm not sure why other people are trying to do this, but I'm just trying to figure out [how to monitor kbfs](https://github.com/keybase/kbfs/issues/1931) with [inotify](https://en.wikipedia.org/wiki/Inotify) or [incron](https://github.com/ar-/incron) or the like, and running as root seems the only way given that "allow_root" is ignored in fuse.conf.  Others have asked for a [caching solution for kbfs](https://github.com/keybase/kbfs/issues/1592), but as yet this is the only approach that seems viable.

**Comment by heronhaye** [comment]
Hi @DiagonalArg. I would still suggest not running Keybase as root.

If you're using systemd, I'd enable `keybase.service` and `kbfs.service` with the systemd user manager and then run `loginctl enable-linger` so it keeps running after logout. Enabling it will start it on boot.

However, it seems like you got it working anyway...

>One problem remains. The directory /keybase is linked to /opt/keybase/mount-readme, but that latter file does not exist.
Sorry, that shouldn't happen in recent releases. Try this:

```bash
systemctl --user stop keybase kbfs
# make sure kbfs is not running!
pkill -f keybase-redirector
rm -r /keybase
```

And then run `run_keybase`. Make sure you're on the latest version too. If this doesn't work please file a new issue, thanks!
