### ISSUE TITLE
keybase pgp select fails with qubes split gpg (undetected env variable?)

### ISSUE THREAD

**Issue by mossy-nw** [keybase/client#14897]
`keybase pgp select` fails unexpectedly using QubesOS split gpg configuration.

**To reproduce**
1. configure qubes-split-gpg environment: `export QUBES_GPG_DOMAIN=vault` 
2. set qubes-split-gpg as keybase gpg command: `keybase config set gpg.command /usr/bin/qubes-gpg-client`
3. `keybase pgp select`

**Expected behavior**
qubes system prompt should appear asking to confirm `vault` as qubes appVM containing pgp keys

**Actual behavior**
no system prompt appears, keybase fails with `GPG error: exit status 1`

**Troubleshooting**
`keybase -d pgp select` gives the following relevant messages:
~~~
configured GPG w/ path: /usr/bin/qubes-gpg-client
running Gpg: /usr/bin/qubes-gpg-client --no-tty --with-colons --fingerprint -K
ERROR: Destination domain not defined! Set it with QUBES_GPG_DOMAIN env variable.
~~~
`echo $QUBES_GPG_DOMAIN` returns `vault`
`qubes-gpg-client --no-tty --with-colons --fingerprint -K` gives expected qubes-split-gpg system prompt, then lists secret key fingerprints. 

so keybase is simply not able to see the QUBES_GPG_DOMAIN variable?

**Related issues**
#4722 -- indicates qubes-split-gpg should be functional

**Comment by holycleugh** [comment]
>so keybase is simply not able to see the QUBES_GPG_DOMAIN variable?
Are you using systemd?

**Comment by heronhaye** [comment]
>so keybase is simply not able to see the QUBES_GPG_DOMAIN variable?

Are you using systemd?

**Comment by heronhaye** [comment]
So there are two problems: systemd doesn't pass in environment variables by default to its processes, and we don't pass in any environment variables to the gpg client either. 

We pass in optional command line arguments to the gpg client though. Do you know if `QUBES_GPG_DOMAIN` can be configured as a command line option in `qubes-gpg-client?

**Comment by mossy-nw** [comment]
hello thank you for the suggestion! it works perfectly well now.  I am not with much experience at bash scripting, so although this worked without problems, please suggest a more elegant way if you imagine one:
~~~
#!/bin/bash
export QUBES_GPG_DOMAIN=keys--sGPG && /usr/bin/qubes-gpg-client $1 $2 $3 $4
~~~
