### ISSUE TITLE
"Minimum role to post" disallows people from initially joining without that role

### ISSUE THREAD

**Issue by Bauke** [keybase/client#14936]
Currently, if you set the "Minimum role to post" of a channel in Teams, it disallows anyone without that role (or higher) to initially join it, effectively making it unreadable by anyone who doesn't have the required role.

However, if you joined the channel and then the minimum role is changed, you can still read the channel just not send messages anymore (it'll display an error saying you don't have the required role).

**Comment by joshblum** [comment]
@Bauke thanks for reporting! a fix is in review, will update when live

**Comment by joshblum** [comment]
@Bauke the fix has been deployed! closing this for now, let me know if you have any other issues
