### ISSUE TITLE
git-remote-keybase error: (1) Can't get TLF private key for key generation 1

### ISSUE THREAD

**Issue by andromedarabbit** [keybase/client#14976]
> [write something useful and descriptive here]
> 
> my log id: eb085e675b30c1088875cf1c

According #14680 , I believe you can help me to fix my Keybase using my log id. Am I right?

**Comment by strib** [comment]
Hmm I don't see that error in your git log.  What command did you run when you saw that?  Was it on the same device you sent the logs from?  I need to figure out the location of the git repo you were trying to use.

**Comment by andromedarabbit** [comment]
Following is the error message from my terminal:

```
$ keybase git create keaton
▶ ERROR Can't get TLF private key for key generation 1
```

Also I have run the command as you requested:

```
$ keybase sign -m "2018-12-07 13:47:00: Please reset folder /keybase/private/jaehoonchoi because all the devices that have access have been revoked."
BEGIN KEYBASE SALTPACK SIGNED MESSAGE. kXR7VktZdyH7rvq v5weRa0zkTJFU5A tsJGOe5nRrHmMX5 4GsUr1b21MFcw7G 8TPK0VhmKDicMQb 9QlscJrAYU3Li31 viIK11ZctB8zGih as9a0EOrSHHPCeA Xlp4d7yvbUnqKFD KGqGYD2GMggtseT ISdTdjzYV4SeXsK VIQRKJTNJJdw9aD HkfQqYq1UK6tPrE fEx2SA15O0mHicr CQaGGPheJ7z3VR0 xuI7sWfjXQJOIDn adTDeAYEX1XyLcH wSEN6mvldbJNbiW GmM4XH4KX7Hidyt 0O4ajNKrXDsDs0S uNo2Lvhn5JaNDLB wX7MWE0Po1DGxzH i6aSrK3SAItsrF9 t1GFjoZG7lhFRm. END KEYBASE SALTPACK SIGNED MESSAGE.
```

**Comment by strib** [comment]
I reset the folder.  Please check it out and close this if everything seems ok.

**Comment by andromedarabbit** [comment]
@strib It works now! I appreciate it!
