### ISSUE TITLE
Twitter proof failed

### ISSUE THREAD

**Issue by pears0** [keybase/client#14992]
It appears that twitter proofs are failing, possibly due to twitter truncating the url:

https://twitter.com/pears0/status/1070324975142354945

Is it possible to resolve this, or add any detailed that's needed to prevent the truncation when doing the proof?

**Comment by heronhaye** [comment]
Hi @pears0, it looks like you were able to post your proof successfully. Did you do anything different?

**Comment by pears0** [comment]
I re-did my verification tweet. 

I think the wording in the text is a little ambiguous, and I may have missed the first section mistaking it for not being part of the verification text. Might be worth reconsidering parts of the plain English phrase to prevent confusion and mis-reported issues?

**Comment by heronhaye** [comment]
Cool, thanks for the feedback.
