### ISSUE TITLE
ArchLinux Error with git

### ISSUE THREAD

**Issue by HaoZeke** [keybase/client#14999]
# Error

![image](https://user-images.githubusercontent.com/4336207/49691172-9762c700-fb62-11e8-91df-1d0817bc3108.png)

# Repo Details

![image](https://user-images.githubusercontent.com/4336207/49691153-5d91c080-fb62-11e8-947a-28018ce16318.png)

# System Details

![image](https://user-images.githubusercontent.com/4336207/49691163-844ff700-fb62-11e8-9271-967810bb1656.png)

![image](https://user-images.githubusercontent.com/4336207/49691174-a184c580-fb62-11e8-8948-fc53e738a369.png)

From the AUR package as suggested by the [docs](https://keybase.io/docs/the_app/install_linux)

my log id: 8be6f05a31fb589d6c303f1c

**Comment by strib** [comment]
I'm a little confused about what the error is.  Your log message said that `git push` failed, but you didn't show that error above.  Is it the same `/usr/share/keybase` error?  That message doesn't appear to be generated by keybase; at least I don't see it in the logs.  I wonder if that's something related to an interesting variable you have set in your environment, like `$LD_LIBRARY_PATH` or some `$XDG` variable.

Or is it just the `--set-upstream` issue?

**Comment by HaoZeke** [comment]
Well my `$LD_LIBRARY_PATH` is unchanged, it's simply `:/usr/local/lib`.

The `--set-upstream` is not really the problem, since:

![image](https://user-images.githubusercontent.com/4336207/49698064-d89bbb00-fbe4-11e8-972c-dcca4ea791dd.png)

It might be a quirk of the AUR installation method but then I am confused as to why it has not been reported before...

**Comment by strib** [comment]
I'm sorry, I don't have any ideas.  Maybecheck your `.git/config` to see if there's anything related to `/usr/share/keybase` in there?  I'm not an Arch expert and I don't have an environment available for testing; wish there was more I can do.

**Comment by maxtaco** [comment]
We have lots of folks using this install and this is the first such complaint so I would guess it’s specific to your config.

**Comment by HaoZeke** [comment]
![image](https://user-images.githubusercontent.com/4336207/49701368-95a40c80-fc11-11e8-8f7e-3278c3ae12cb.png)

If that helps...

**Comment by maxtaco** [comment]
Try `which keybase` then `ls` it? Maybe there is a deal symlink somewhere in your path.

**Comment by maxtaco** [comment]
`ls -ls /usr/bin/keybase`

**Comment by HaoZeke** [comment]
![image](https://user-images.githubusercontent.com/4336207/49705815-42e54780-fc47-11e8-954e-62ff87cdcda0.png)

**Comment by maxtaco** [comment]
Oh, I don't know what `sl` is.  Sorry, i don't know

**Comment by heronhaye** [comment]
@HaoZeke This is pretty odd. Could you try making a fresh git repo and pushing and pulling from that?

If that doesn't work either, could you give the output of 
```
$ pacman -Qkk keybase-bin
$ \ls -ls /usr/bin/keybase
$ env | grep XDG
```

**Comment by HaoZeke** [comment]
![image](https://user-images.githubusercontent.com/4336207/49853646-d36d8480-fe0d-11e8-9ef7-68e865b23fc2.png)
I am not sure what the right permissions are though...

**Comment by maxtaco** [comment]
XDG_DATA_HOME not writable by you? That seems like a serious misconfig.

**Comment by maxtaco** [comment]
(One that has nothing to do with our software by the way)

**Comment by heronhaye** [comment]
Yup, that seems like the issue. Check if you're setting $XDG_DATA_HOME anywhere in your shell rc files. A good default is `$HOME/.local/share`. Better yet, just unset it if you don't know what it is/don't want to customize it.

**Comment by HaoZeke** [comment]
Yikes, that was the issue. I am so sorry for bugging everyone here. Thanks a ton everyone!
