### ISSUE TITLE
Private folder reset

### ISSUE THREAD

**Issue by quentez** [keybase/client#15036]
Hello. My private folder "quentez" is not accessible from any of my devices (the rest appear to be working). Would it be possible to reset it? (I don't have anything of value inside).

my log id: 599be2be94645fbcd280ad1c

Here's the signature of the Log ID:

```
BEGIN KEYBASE SALTPACK SIGNED MESSAGE. kXR7VktZdyH7rvq v5weRa0zkWArBAo DWI9Z85tUJOEU8X qTnD9yZFDp0f13U Xn5nekdlSJK3DN7 S5bPChA3Haifok6 XMzrd4IKAKnAxUU qOKRypY4u2rsDdk Fz5YiiutjrsCrCq d6hkIgaOs6WI7H5 ciTrDy9soKCmfJ0 qpMP0eN6MUzMMb0 zowknDSSxKUln6W fXE7DibCyrGkeyi 1Ze5M3Hv. END KEYBASE SALTPACK SIGNED MESSAGE.
```

**Comment by strib** [comment]
Hi @quentez, I can reset it for you.  Looks like it was made a long time ago, and is now only keyed to old devices.

But, the message you signed above is just the log ID.  If you want us to reset your folder, please run this command on a currently-valid keybase device, and substitute the current date and time where indicated:

```
keybase sign -m "<DATE_AND_TIME>: Please reset folder /keybase/private/quentez because all the devices that have access have been revoked."
```

and post the results here.

**Comment by quentez** [comment]
```
BEGIN KEYBASE SALTPACK SIGNED MESSAGE. kXR7VktZdyH7rvq v5weRa0zkWArBAo DWI9Z85tUJOEU8X qTnD9yZFDp0f13U Xn5nekdlSIE8413 oQrDh6zJgtGHSCV XXfFddJLKV6gUrs Ri9ZASCYOUnPoIp 8a6OkkmG0mEJ6mb 7nMJ63pr4KFmwl1 DNrhkGqbVTKd2JU wuEMCOZffoOCedR cK6XGizREi6o0cf XHJ6QBTiNMO7s5Y l7LHfJwpE12we35 XdsUH4Xdq4BrM4E ezn2yoiyBYsWCRR 1L7NKP0Ss2D3ic4 AgfQZ8wj4AXUdks t6S7xUC8EnYMRDy e7h9TR92tqNsEkk MbbXayxRf0rP7yP 8rPfda8K7DdK5Z3 bPJBoPW5OA7tioy mCXlNe. END KEYBASE SALTPACK SIGNED MESSAGE.
```

**Comment by strib** [comment]
I reset the folder.  Please check it out and close this if everything seems ok.  (Might require a Keybase restart.)

**Comment by quentez** [comment]
@strib This now appears to be working. Thank you for the help!
