### ISSUE TITLE
Unable to rekey private folder

### ISSUE THREAD

**Issue by jaredallard** [keybase/client#15087]
Not sure what to do here. It asked for an existing device to be turned on, an Android client, which I did, but that didn't do anything. I then generated a new paper key from that mobile device to be used on the client. That rekeyed all my other conversations & etc but not my private one. Any ideas? I was migrating OS installations so all of my stuff is on there...

Log ID: `fc5d2e35cc739527ee510c1c`

**Comment by jaredallard** [comment]
@strib Any info on what I should include from my phone? I had the app open for a while and it never did anything.

**Comment by strib** [comment]
Hmm thanks.  I can't find the logs on our end.  Can you please write some kind of feedback message when you send them?  Like "for strib" would be fine.  Thanks!

**Comment by jaredallard** [comment]
@strib Sent!

**Comment by strib** [comment]
Got it thanks, will look now.

**Comment by jaredallard** [comment]
@strib Will do! Hopefully it works :pray:

**Comment by strib** [comment]
Thanks. I'll keep monitoring it on my end, and if it doesn't seem to be working after a while, I'll ask for more logs.

**Comment by strib** [comment]
Ok, seems like it still hasn't worked.  Assuming your app has indeed been open this whole time, I guess there's a deeper issue.  Can you please send logs again from your phone, with the same message as before?

**Comment by jaredallard** [comment]
Yep it's been open for awhile, will do.

Sent with "for strib"

**Comment by strib** [comment]
Looks like you might have hit _another_ bug in our code, this time an internal deadlock.  I'm still investigating the logs (thank you!), but you might see more progress if you kill the app and re-open it fresh.  Then again navigate into the folder and leave it open for a bit.

**Comment by jaredallard** [comment]
Cool, at least it's noticed! When I restart the app and go to "Hamburger Menu > Files > private > jaredallard" it doesn't open immediately. I wait 3-5 seconds and "An error occured." pops up. If I tap it again it will open the file list and show "loading" seemingly forever.

**Comment by strib** [comment]
Sigh, ok.  Can you please send more logs after that?  I wonder if it hit the same crazy problem again.

**Comment by jaredallard** [comment]
@strib Sent!

**Comment by strib** [comment]
Ok great.  The good news is that I figured out the issue and a fix is in review now: keybase/kbfs#1972.

The bad news is that it will require a new app release from us to let you upgrade and get past this bug.  Our next release is scheduled for early next week.

If this is more urgent than that, I can ask around about making a one-off release for you to try out.  Off the top of my head I don't know how to do that, but I can probably find out.

**Comment by jaredallard** [comment]
@strib If you can get a one-off release for me that would be awesome since I have all my stuff on there, ssh keys, gpg, etc.... but I get it if you're unable too! Thanks for looking into this

**Comment by strib** [comment]
I'm afraid our Android release story is way too complicated to make a one-off release.  (I was hoping it would be similar to our macOS story, but it is not.)  So I think you'll have to wait until next week.  Hopefully it will be out Monday.

If you happen to be an Android developer, you can probably build your own apk from our open-source repos, but that's a long shot.

Sorry for the inconvenience.  In the meantime, treat your Android phone with the utmost care, it contains the only key to your private folder right now!  At least you have a paper key now, so if this happens in the future you can recover using that.

**Comment by jaredallard** [comment]
Closing since this was resolved! Thanks :)
