### ISSUE TITLE
Windows Installer Notes

### ISSUE THREAD

**Issue by zQueal** [keybase/client#1512]
Notes on the Keybase Windows client. 

# Installation

Installed perfectly. __Not__ added to path by the installer making the rest of the installation manual. Because I feel unsafe putting the entire directory in my path (because of the uninstall), I opted to use a batch method that I use for most other programs, too:

    @ECHO OFF
    "C:\Program Files (x86)\Keybase\keybase.exe" %*

Works just fine.

# Login

I tried to login several different ways. First, I tried to use my paper key of which I received an error:

    λ keybase login
    How would you like to sign this install of Keybase?
    
    (1) Use an existing device
    (2) Use a paper key
    (3) Use my Keybase passphrase
    (4) Use GPG
    Choose a signing option: 2
    - ERROR KID not found (error 205)

Next, I tried GPG:

    λ keybase login
    How would you like to sign this install of Keybase?
    
    (1) Use an existing device
    (2) Use a paper key
    (3) Use my Keybase passphrase
    (4) Use GPG
    Choose a signing option: 4
    In order to authorize this installation, keybase needs to sign this installation
    with your GPG secret key.
    
    You have two options.
    
    (1) Keybase can use GPG commands to sign the installation.
    
    (2) Keybase can export your secret key from GPG and save it to keybase's local encrypted
    keyring. This way, it can be used in 'keybase pgp sign' and 'keybase pgp decrypt'
    going forward.
    Which do you prefer?: 2
    #    Algo   Key Id             Created      UserId
    =    ====   ======             =======      ======
    1    R      B1DA56DCB73E8516   2014-03-28   [...]
    Choose a key: 1
    - ERROR openpgp: invalid data: user ID self-signature invalid: openpgp: invalid signature: hash tag doesn't match

I then tried to use an existing device. This worked as expected, however, I realized I had no other devices authored with my Keybase account. Since `keybase.exe` is looking for some form of acknowledgement, when I `<C-c>` to exit the process, it never gracefully stops. After this happens, running keybase again returns this error:

    λ keybase login
    - ERROR Provision transaction already in progress

After force closing the keybase.exe process in task manager normal behavior resumes.

Finally, I simply did my Keybase passphrase which worked as intended. 

    λ keybase status
    Username: zqueal
    User ID: 15b4292135d9 [...]
    Device ID: a5d1fd4eee [...]
    Device name: Home_PC

After logging in, in addition to the paper key generated for my device, I generated an extra one. I logged out, and when I executed `keybase login` to attempt to use the paper key, immediately a pinentry password prompt is shown. I'm unable to figure out how to reset this functionality to anything other than password login.

# Verify

I was moderately confused with the new functionality with `keybase pgp verify`. Normally I would expect to either pass it STDIN or a file to verify. This doesn't seem to be the case:

    λ keybase pgp verify test.asc
    Error parsing command line arguments: Command `pgp verify` doesn't talk any non-flag ~~arugments~~arguments

    λ keybase pgp verify -i test.asc
    - INFO Starting background server with pid=5780
    - ERROR Check engine error: PGPVerify: Check engine error: requires ui "PgpUI"

    λ keybase pgp verify
    - INFO Starting background server with pid=1100
    - ERROR Check engine error: PGPVerify: Check engine error: requires ui "PgpUI"
    (hang)
    Terminate batch job (Y/N)? Y

    λ pclip | keybase pgp verify
    - INFO Starting background server with pid=6476
    - ERROR Check engine error: PGPVerify: Check engine error: requires ui "PgpUI"
    (hang)
    Terminate batch job (Y/N)? Y

For the record, `pclip` is a command line utility which pastes the contents of my clipboard into the terminal. I copied a signed statement and tried to pipe it to keybase which failed like all the others. Other then that, all other items seem to be working flawlessly.

# Sign

    λ uname -a | keybase pgp sign
    - INFO Starting background server with pid=4960
    -----BEGIN PGP MESSAGE-----
    Comment: https://keybase.io/download
    Version: Keybase Go 1.0.6 (windows)
    
    xA0DAAoBsdpW3Lc+hRYBy+F0AOIAAAAA5XdpbmRvd3MzMiB4YW56YS1wYyAyLjYu
    MSA3NjAxIGl45Dg2LXBjIEFNRCB1bmtub3fjbiBNaW5HVw3gCgDCwVwEAAEKABAF
    AlZqRFoJELHaVty3PoUWAABBHxAApJOmiV2w+AVhThdeNFGAR0DTIQIe5qzCwRNh
    rBCbF5zCBKrAPGH8DcEGsPpJFLa6O7i6GmX0JyoZwv54yejf6uN+R0igTCvGv+Tq
    4bV7d9IjtatAo/yg2iuloJlAS8RGnPSYPYcegv/Q8SUVpNkE648Xl1JR7aoWXtWD
    NwaJN1MTfyeyh3ICvI0qZwO7PrjxDNjuXNxibL3P5xGKxj+o9g12f2hP67nYJEEE
    n1zBaz5Oig13znEwJ6yiRMFAEEj6PmeNRjoKEk1O4EQz+SU9G8jOALUmY+I+A67U
    S0vYdee48EIhrxBm6kdlHBQYD1UQESM2iy9wlENyyafQN35p7Ps58wKM7wkKyc6a
    siVRC2EpG0t7BAJ6b93oY3Ye4Iungko+8x+0bEJ/IWbckqNc68rbxOfLVgYlzoMf
    dp7psXQN8C2lBoQhoOE+rLP0jIhAEohm7gH1bfPDekQXcUTyR6wRWE1SJv4EHqNf
    MDswvnDquiz5ivzrD4g0wlXCrgZNP7K2/V91JCccsJJsBGQVvCv21pJpPYHKNMLj
    JdjrJ1s5BSHZtG8fP1R0bzn5M+lBpKU283phlWPey4dXIa4NXEcB2WUpc1K3sfjL
    tNsv1fJCRdMAx8Rc+Y56jKd/43sbRPcqwjHMb47s/UQlpWZmwbllaHATDvikHwNc
    QV1Zlkc=
    =/DR8
    -----END PGP MESSAGE-----

# System Information

Windows 7 Ultimate x86_64 (6.1, build 7601) Service Pack 1

I couldn't think of any other pertinent system information. If you want or need something else, just let me know.

# Final Thoughts

All in all the install was super fast and I was up and running in seconds (I was mostly trying to break things, though). If the install location was added to path, no other user intervention would have been necessary and this would be a 1 click install of Keybase on Windows. I can see some really great things in the future and hopefully explosive adoption.

**Comment by maxtaco** [comment]
Thanks for this great feedback.  Some of these bugs are known. The first issue is likely because your paper key is from `stage0.keybase.io` and therefore isn't known to the production server.

**Comment by zQueal** [comment]
> The first issue is likely because your paper key is from stage0.keybase.io and therefore isn't known to the production server.

Hey, this makes total sense! I tried to test this again by logging out then back in, however, I'm simply greeted with a pinentry login prompt. I was going to give `deprovision` a try, but I'm not sure _exactly_ what it does, as in revoking my generated paper keys, etc. So I opted not to.

**Comment by zanderz** [comment]
That was fast, thanks again for the feedback.
About the path: a shortcut gets installed called "Keybase CMD" which opens a cmd with keybase on the path already, did you try using that? Adding each program to the global path is somewhat frowned upon nowadays, but if people expect it we can still do it.
-Steve

**Comment by zQueal** [comment]
> a shortcut gets installed called "Keybase CMD" which opens a cmd with keybase on the path already

I didn't see this! This is probably fine for the general populace, IMO. The reason why I ran into an issue is because I use `cmder` instead of `cmd.exe`. Quite honestly, if this is added then there's no real reason to add the executable to the path in any other way but what's already done. Anyone who has a CLI replacement will probably know how to manually add it to the path if they so choose. Even if they don't, it's just a Google search away.

As far as I can tell, aside from the login problems the only __real__ issue is with verifying a message. I'm able to create a clear signed message with no problem, but I cannot verify it using the CLI:

    λ keybase pgp verify -i test.asc
    - ERROR Check engine error: PGPVerify: Check engine error: requires ui "PgpUI"
    λ cat test.asc
    -----BEGIN PGP SIGNED MESSAGE-----
    Hash: SHA256
    
    This is just a test.
    -----BEGIN PGP SIGNATURE-----
    
    wsFcBAEBCAAQBQJWaxs1CRCx2lbctz6FFgAA9j4QAJfnnOCudG6Pzitp4iqcfLqS
    MK+qHTAS5FoDzLAb+rPuk/+9NzpBvDzswX10cnT63gyTswmFm2shDWwa/LH7Lrg9
    lTcK9S5y2KVGy3dTJAY19Rr+iO/yf9bZmW+KH2WRlCQLR7H5z+2+pSagqQ7bgcEa
    i3MYKC9LOxr9Jt8bhNRjcsRvQSreFv8lFN9BwwFiAm/lQrKsN9xb+cmOSRhmqOuC
    ow+JfWC1G7nq0ACeFKuzT6eLr/LfIcSxtO6nyX0Ne8Gprc7fQYFt++9QhiSbqEJC
    82z417mUu5l6C3GaLp35lulLFnGHHq4xGPkUjedJWxHSqIfejIefeMnQjXbd97Kf
    dQab0KybDslXVXGhgjLeLLEmtSlBl5O3BzewhHVievRDw++NTKNcj8a6l0kJyiNg
    Re/9ah2i8juMl/mgpqFvSBQTnLes1CiAhyF5kz7I46NUOqvpb7qaN0JKpgCDy0Q0
    SbXAW5SFLX1okpxYaSgWUJEYP3YXbVC1oPFlkXbJ9onJlwXsZkMcEyvKKZDhmqAq
    qG2/zgDoqUnyUHpPIBWMFu2QEN50oMHH+sk+58pSByOI29mBlbBSS+/gcZCxgeg5
    mbcUMV6Ob3m7vIb4BASMY94WQIGRd1vKTeJKKo/zCkvP3pSlqxMKs8njjoka85zM
    bMIAzUnlUduqS+COpLxk
    =UcHc
    -----END PGP SIGNATURE-----

However, verification of an encrypted and signed message works just fine:

    λ keybase pgp decrypt -i test.asc -o test.txt
    - INFO Identifying zqueal
    OK public key fingerprint: 7B5A C030 0E2C 74FD 355C CC81 B1DA 56DC B73E 8516
    BTC bitcoin 12csNifta955YUAT7kBC9Dh47bW1Ueieo7
    OK "zqueal" on coinbase: https://coinbase.com/zqueal/public-key [cached 2015-12-11 13:58:08 EST]
    OK "zQueal" on github: https://gist.github.com/1fa438d29795ac9476ea [cached 2015-12-11 13:58:07 EST]
    OK "Xanza" on hackernews: https://news.ycombinator.com/user?id=Xanza [cached 2015-12-11 13:58:07 EST]
    OK admin of DNS zone queal.net: found TXT entry keybase-site-verification=ckK1iVirIRJjyVZ7JU5Fzb94AF1peZCpTFBZJhJ8MAQ [cached 2015-12-11 13:58:07 EST]
    OK "zqueal" on twitter: https://twitter.com/zqueal/status/449697262059663360 [cached 2015-12-11 13:58:07 EST]
    Signature verified. Signed by zqueal 24 seconds ago (2015-12-11 13:58:30 -0500 EST).
    PGP Fingerprint: 7b5ac0300e2c74fd355ccc81b1da56dcb73e8516.

Here's the test (encrypted to myself and zanderz):

    -----BEGIN PGP MESSAGE-----
    Comment: https://keybase.io/download
    Version: Keybase Go 1.0.6 (windows)
    
    wcFMA7HaVty3PoUWARAALGy5F5M/4cHe7HwY/Cwdm/dpHn9OHz56KRuYxfksJfbR
    UouKlMnJJXsIPGJl5a2gevXuSE10R3rP++Lc9O+X/HrHSyGrRr93VSr4kDCh7x5R
    jTHNTEYjmGYwqcS9iwtItSShP0yoyBiOCl5LecoEyKa1aFlTe161cLHRoPJz7Q4v
    mDCxy60yX9cYXc83HsGLmRK6qCtC0pqbo+zSJCiEr6PGmOY4ydoqqM0CXopsXkBE
    hERLxUSiAgSDxwbyZrn97hVEH7AAkAnTxNnlgwtqah7n7wxcAGCS+cKBbkR3N/zG
    iZ4Auv8ozr346SiacZOAFNFAp0V9Fu8xmwp5R9cyeU4mNbJo1q/5SvrJdnhshoI5
    0ZzHtyP6f7CqMEGcEit4ftPnTlgIfX8ccG9P9Du6vCpHDYo4NuugiAkpqNUaJHt8
    EAE2zj7IkRiue+s4xOU0OBqN9TKfmuDCUBDxho54AJzFQS8i9joFCwunRMM2p/1v
    Zy9tttCKtro1Sg3CyE1dQZqlNtI/af8DthbqfGg6RMC9OlVQqBgxMs3MCiQDALkJ
    tJXZVL40oin7SFC067r5TaNlRC6Fdt3otc8owRPyrNKdYelSAPRVtekP/nQkKK/6
    zBcRwHB0dG3ZvEaaRaYnxeoPK0x5FuAKdExCLr1GGiDRW9RPpqZWJ5AO8M7YhvvB
    wEwDvWw7+yHuCigBCABWcZcDzdtrECEc4yMKpg6m76YlpLy/Z7bbhdxZBK63Qlk0
    rOrG3WcdkOePzs2zseRsjpBL84NER4UdgZiHIeFPgCjZuE8Wx7wgGQOcID/h/thg
    skbWai7+8jsiRTckN31crM6ZPJMKefS1ato4znlmyyViQaPertyneive9PXo5eMy
    O+MLkBcoqpmRm1bMS6M70BPyBQaTEu198Ni9cEu5ur9jlm5mS48HCKUMmswkIcVM
    CyrAsJXBlUfyh/YuIEOhjXfmJ0gPRYQ+GuRMruYDk3OVBcs7lZr8qDJxrPiuRB/U
    aWyZTbMjTpM3Jib3Y7FPio4WwOZHANUw4K2CXuG40uAB5LwcyIulp1J95992o7sp
    Tdvh3/3hYWjjXFd464iP4Zzi11S0guBr4MLgZ+GqAuC84s/ek1Xgf+SeldiRTqb7
    pxPjbUjleXH24NjiAFdYaOAu4fgf4MHh+97gUeTy6lQNoRIGk7SFj2jIwWU24irB
    zA/hKTLhW9fh5hPhHhLphN4dAg8vDKixN3dBeHiLSgRETJKtqyrrack/rm2Gyb4k
    ecy4ZxSRt8Pi8DTx1uXdWEBoVz3ZUxQtlfkKq/ZUH8T/71XLFHYqMt954N8zGjmU
    RsooXrLmxP/B3dqKBrlea4KR5manRxok2jG3WNTtFxPhVWKfVR4bQxGo+INgtLcr
    j4vXr74ZVtc1kKofa+99o1duDB+o9bw9BkrnrcD9tWbiCI9wC5f0mrdif4Fss3T3
    mDMbRxUFKr9G3W+rgHXUxAT4cbmKEDWD8O0KyqNC6VJs2PX1qwgJGXyVzklTvKIY
    dXAdveYWg1tqbFSqgY4M5s9jRi12Uk6xaDqABaQfBGhhRW5PAoaOQ5gGFGiTDvaj
    2OCgQBLLY19jL91VEv/W39+fPENmiNtpTjzuB7PtDaiAfcRw0I1qqWbm5v1w7sGz
    +QVpuUy+Q+DdQtoorbBve2qq6Zp2ndqZ+9yj9DCY304kX5USCDJLPqDtKUT/tO0w
    10Xi5QNszOa7Rh3kfdZN/MQgejRXnA2xLTwlE5hHMr5J383zn1L5+dV1WG0Gsidn
    gn1qakL1WAOcPqZuiPXcOjJ1JThzuD5UNubsVTa0SNsCTxA7ck8mYtGxsIXbbXjZ
    oD8HK0rfHjsytA+YWxJvlNPrfoSkLCcPCJi1t3vjvdcyEWHdhM8dyiEJpqeHZXzk
    fiyqmSem95G2Vi+qb001UOK4Y/PY4f4cAA==
    =1rds
    -----END PGP MESSAGE-----

**Comment by zanderz** [comment]
Thanks again, I'll try that too and see if I can figure it out.

I get a different error when I follow your login sequence: "No username known." I get it even when providing a username to the command. We'll look into this too.

```
C:\Program Files\Keybase>keybase login zanderz
How would you like to sign this install of Keybase?

(1) Use an existing device
(2) Use a paper key
(3) Use my Keybase passphrase
(4) Use GPG
Choose a signing option: 4
In order to authorize this installation, keybase needs to sign this installation

with your GPG secret key.

You have two options.

(1) Keybase can use GPG commands to sign the installation.

(2) Keybase can export your secret key from GPG and save it to keybase's local e
ncrypted
    keyring. This way, it can be used in 'keybase pgp sign' and 'keybase pgp dec
rypt'
    going forward.
Which do you prefer?: 1
#    Algo   Key Id             Created      UserId
=    ====   ======             =======      ======
1    R      FFAD8BFA52E03114   2015-12-11   Steve Sanders <steve@keyba.se>
Choose a key: 1
- ERROR No username known
```

**Comment by zQueal** [comment]
This may be of little consequence, but IIRC I ran simply `keybase login` and __not__ `keybase login zqueal`.

**Comment by zQueal** [comment]
@zanderz 

Instead of opening a new issue I'm just going to amend this one. The Windows update flow is still...left wanting?

The actual install _usually_ works on the first time (I've had some issues where it would fail for some unknown reason the first attempt)--however the real issue is the __forced__ restart after the install. It's totally unprompted. I'll close the installer after a successful install without restarting (because I don't have a burning need for Keybase at that particular moment or are wrapped up in something at the time) and about an hour later my PC magically restarts by itself. It's incredibly inconvenient and makes me not want to keep Keybase updated.

Is there anything that can be done about this? Forced restarts are a little 90s for me and it's happened twice now--both times I've lost (momentarily) about 25-30 minutes of work each.

**Comment by zanderz** [comment]
There have been at least 2 causes of this reboot identified + fixed, the second of which sounds like it matches the scenario you describe. Can you tell which versions were being upgraded to + from, and when this happened most recently, to make sure it isn't a new one?

As background, we build and ship one single installer which is supposed to be able to do all of the following, depending on the situation:
- initial install
- driver update, requiring UAC permission and user interaction, regardless of auto update settings
- silent update, in case auto update is set and drivers are already up to date on the target

so there is a fragile chicken and egg situation where the updater has to determine whether it is able to silently perform the current update before launching this monolithic installer, and we are still working out some kinks. Sorry about that!

**Comment by zQueal** [comment]
> Can you tell which versions were being upgraded to + from, and when this happened most recently, to make sure it isn't a new one?

Afraid I don't know this. It happened before I went on vacation and I figured I'd open a ticket about it.

> so there is a fragile chicken and egg situation where the updater has to determine whether it is able to silently perform the current update before launching this monolithic installer, and we are still working out some kinks.

I'll try to monitor the next update (?) and grab some diagnostic information for you. I'll close this until then.
