### ISSUE TITLE
Keybase can't fetch git repo

### ISSUE THREAD

**Issue by mesirendon** [keybase/client#15162]
Just updated my system and one of the packages that got an update was keybase to version `2.13.0-20181218221625+d72e065cbe`.

Since the update I can't access my repos. When I try `git fetch --all` the response is

```
Fetching origin
Initializing Keybase... done.
Syncing with Keybase... done.
error: Could not fetch origin
```

**Comment by maxtaco** [comment]
Hi, Please `keybase log send`? Thanks

**Comment by mesirendon** [comment]
Gives me this `ERROR API network error: Post https://api-0.core.keybaseapi.com/_/api/1.0/logdump/send.json: net/http: request canceled (Client.Timeout exceeded while awaiting headers)`

**Comment by maxtaco** [comment]
Firewall? VPN? Anything like that.  IF you can't reach our servers, not much we can do!

**Comment by mesirendon** [comment]
No. I haven't set up anything... just `sudo apt upgrage` and I saw the client being updated. Since that, I got problems with keybase.

**Comment by maxtaco** [comment]
Can you do a DNS lookup on the hostname?  Or make a connection on port 443 to it?

**Comment by strib** [comment]
I would try `keybase log send` a few more times.  Sometimes the timeouts are temporary.

**Comment by mesirendon** [comment]
Just installed the latest version on a cloud device and tried to clone the repo... same answer (still can't access any repo).

I launched the log send command from there and got this log ID: d98e1b94b162d047f4a6a91c

**Comment by strib** [comment]
Thanks, I see the bug.  Something we just introduced today I think.  I'll fix it and try to get a release out soon.

**Comment by mesirendon** [comment]
What would you recommend... maybe installing a previous version while the fix is done? I still have to work :stuck_out_tongue:

**Comment by strib** [comment]
Sure, the previous revision should work, sorry!  https://s3.amazonaws.com/prerelease.keybase.io/linux_binaries/deb/keybase_2.13.0-20181218150045.944a2610ed_amd64.deb

**Comment by mesirendon** [comment]
Thank you so much

**Comment by heronhaye** [comment]
@mesirendon @adam-lee Fix is out, you can upgrade safely now. Thanks.

**Comment by mesirendon** [comment]
Just upgraded to version `2.13.0-20181219142726+01e9fa19eb`. Works like a charm. Thank you guys.
