### ISSUE TITLE
Can't create or clone Git repo

### ISSUE THREAD

**Issue by adam-lee** [keybase/client#15166]
On Ubuntu 18.10, I can't seem to clone my personal repo from my Keybase account. Regular git repos from Github.com works fine.

```
adam@tp470:~/Code$ git clone keybase://private/adamyhlee/dotfiles
Cloning into 'dotfiles'...
Initializing Keybase... done.
Syncing with Keybase... done.
```
And I can't create a repo either:

```
adam@tp470:~/Code$ keybase git create test
▶ ERROR EOF
```
Thoughts?

```
VERSION:
   2.13.0-20181218221625+d72e065cbe
```

**Comment by maxtaco** [comment]
I think there was a bug in the last release. Cc @strib

**Comment by adam-lee** [comment]
> I think there was a bug in the last release. Cc @strib

Good to know. Looking forward to the fix.

**Comment by heronhaye** [comment]
@adam-lee Fix is out, please upgrade to get it! Thanks.
