### ISSUE TITLE
Git doesn't work

### ISSUE THREAD

**Issue by IvanStanul** [keybase/client#15175]
For few days (maybe over a week) git stopped working for me.  
Gitlab repos for example works perfectly, so it seems something is wrong with Keybase. 

When I try do add do current repos and push - I get something like this: 

```
work git:(master) ✗ git status
On branch master
Your branch is up to date with 'origin/master'.

Changes to be committed:
  (use "git reset HEAD <file>..." to unstage)

        modified:   information_systems/system_requitements_specification/darbas.aux
        modified:   information_systems/system_requitements_specification/darbas.log
        modified:   information_systems/system_requitements_specification/darbas.pdf
        modified:   information_systems/system_requitements_specification/darbas.synctex.gz
        modified:   information_systems/system_requitements_specification/darbas.tex
        modified:   information_systems/system_requitements_specification/darbas.toc

➜  work git:(master) ✗ gaa
➜  work git:(master) ✗ gcmsg "specification"
[master dc039aa] specification
 6 files changed, 63 insertions(+), 71 deletions(-)
 rewrite information_systems/system_requitements_specification/darbas.synctex.gz (99%)
➜  work git:(master) gp
Initializing Keybase... done.
Syncing with Keybase... done.
➜  test git:(master) git status
On branch master
Your branch is ahead of 'origin/master' by 2 commits.
  (use "git push" to publish your local commits)

nothing to commit, working tree clean
➜  test git:(master) git push
Initializing Keybase... done.
Syncing with Keybase... done.
➜  test git:(master) git status
On branch master
Your branch is ahead of 'origin/master' by 2 commits.
  (use "git push" to publish your local commits)

nothing to commit, working tree clean
```
But it skips actual pushing part. For example when I push Gitlab repos I get output as :
```
  programming_practice_2 git:(master) gp
Enumerating objects: 4, done.
Counting objects: 100% (4/4), done.
Writing objects: 100% (4/4), 259 bytes | 259.00 KiB/s, done.
Total 4 (delta 0), reused 0 (delta 0)
To gitlab.com:IvanStanul/programming_practice_2.git
 * [new branch]      master -> master

```
I stopped getting same "push progression" on Keybase repos. And if I clone nonempty Keybase repo I get:

```
➜  keybasetest git clone keybase://private/ivanstanul/work
Cloning into 'work'...
Initializing Keybase... done.
Syncing with Keybase... done.

```

But no files or folders appear. And as it doesn't give me any error messages I've no idea why it stopped syncing properly.

**Comment by strib** [comment]
We had a buggy linux release last night, but this morning we updated it.  If you're on last night's Linux build can you please update and try again?

**Comment by strib** [comment]
Oh wait, it's been happening for multiple days?  If updating doesn't help, can you please do a `keybase log send` after seeing the weird behavior and post the log ID here.

**Comment by IvanStanul** [comment]
Sure, log ID is:
2829ed142b3072ebca7ee61c

**Comment by strib** [comment]
Your latest clone definitely hit the issue I mentioned above, and you are running the version from last night.  Please try updating, and then try to reproduce the issue and send new logs.  Thanks.

**Comment by IvanStanul** [comment]
Now everything seems working fine, but I'm sure few days ago it wasn't pushing properly.. Well, it's all good now.
