### ISSUE TITLE
[Android 9] Photos taken through client are saved to Google Photos

### ISSUE THREAD

**Issue by psidhu** [keybase/client#15206]
This is fairly recent, but on older versions, photos taken through the Keybase app weren't saved to google photos (which is *good*). However, the latest version that I have causes photos to always be saved back (*bad*).

I think adding an option (maybe per chat?) would be a great way to solve this.

keybase version: 2.11.0-20181203214554+ec71fb1ab3

**Comment by strib** [comment]
cc: @chrisnojima @akalin-keybase

**Comment by chrisnojima** [comment]
investigating thanks!

**Comment by chrisnojima** [comment]
thanks for the heads up. this has been disabled and rolled out. the commit hash in the settings | about should read `a4dfb790d08299f86c99f1bcecfd7dac48f67641`
