### ISSUE TITLE
Can't find uninstaller on Windows

### ISSUE THREAD

**Issue by owenmann** [keybase/client#15218]
![keybase error](https://user-images.githubusercontent.com/1134144/50378215-e98ff780-05fa-11e9-8de9-c55d6bbe8948.png)
[Every hour or so I get Keybase trying to uninstall so it can upgrade, but it can't find its MSI. My Windows profile was migrated with Profwiz (https://www.forensit.com/domain-migration.html) so that may be a factor). In the meantime, can I get a copy of Keybase_2.11.0-20181203203419+ec71fb1ab3.amd64.msi please?]

my log id: 1779a8d2e4e72226e06efa1c

**Comment by zanderz** [comment]
Most people find they can get past this problem by running Microsoft's tool: https://support.microsoft.com/en-us/help/17588/fix-problems-that-block-programs-from-being-installed-or-removed

**Comment by owenmann** [comment]
Thanks for the link I was able to uninstall with it. The reinstall wouldn't work unless I renamed the installation directory out of the way and create a "new" device in Keybase. How do I tell Keybase it's the same device? E.g. can I copy the device key from the old installation folder into the new one?

**Comment by zanderz** [comment]
Yes, that should work - just copy the .ns2 and .ss2 files. Very unusual that the old directory would cause that problem, I'd be curious to see those logs.

**Comment by owenmann** [comment]
Which logs would you like? Via PM? Else do they need to be redacted?

**Comment by zanderz** [comment]
Only we will see them if you do `keybase log send`. What time/date roughly did the install fail after uninstalling?

**Comment by owenmann** [comment]
I don't think that will work since I had to rename the directory and install fresh to make it work, right?
I never could uninstall properly; I had to use the MSI cleanup tool from MS linked above.

**Comment by zanderz** [comment]
Install logs go in %temp%, so likely would not be affected by uninstalling or removing %localappdata%\Keybase, but it seems unlikely that anything useful could be gleaned at this point. But if you ever get to the point where you have uninstalled Keybase and a new installation fails, you could log the failure with `msiexec keybase_XXX.msi /L [some_filename] and send that file.

**Comment by owenmann** [comment]
Will do.
Thanks!
