### ISSUE TITLE
Error code 218: GENERIC in method keybase.1.login.login

### ISSUE THREAD

**Issue by TheFuzzStone** [keybase/client#15228]
Hello.

Can't login into my Keybase app on Linux Mint 19.1 Cinnamon:

`missing provisioning key in login context Error code 218: GENERIC in method keybase.1.login.login`

* Keybase GUI Version: 2.13.0-20181219142726+01e9fa19eb
* my log id: 13a55142752879137d7dd91c

How can I fix that? 
Thanks!

**Comment by TheFuzzStone** [comment]
Someone?

**Comment by maxtaco** [comment]
Won't get to it until the holidays are over.

**Comment by TheFuzzStone** [comment]
Holidays are over? :-)

**Comment by maxtaco** [comment]
sure we'll take a look. Can you try to login again and generate a new log?

**Comment by maxtaco** [comment]
Oh, you're trying to use GPG login and you have a modern account.  Urg, that might be an issue...

cc @joshblum  / @mlsteele

**Comment by mlsteele** [comment]
You can't provision a device with a PGP key once you've had a device. Unfortunately I think to get back in you'll need to reset your account. If you choose to reset your account all of your existing data in kbfs, chats, proofs, etc will be lost and you'll be starting from scratch.

We've added some more warnings to revocation to avoid this situation, but you may have removed your device before those were added. I click "recover account" on your account on the website from an incognito window. So you'll probably get an email from that, which you can ignore or use.

**Comment by maxtaco** [comment]
Or maybe you have another active device you can provision with?

**Comment by TheFuzzStone** [comment]
@mlsteele, account reset isn't an option for me. Thanks for your answer! 

@maxtaco, no, I don't have. 

Thanks guys!

**Comment by TheFuzzStone** [comment]
@maxtaco @mlsteele 

If I choose "**Reset your keys and start from scratch**":

1) I will lost my nickname? (thefuzzsto0ne)
2) Can I upload again the same key on keybase?

**Comment by maxtaco** [comment]
yes x2

**Comment by maxtaco** [comment]
Sorry, edit: (1) no; (2) yes

**Comment by TheFuzzStone** [comment]
@maxtaco @mlsteele 
And the last question, if I will decide to change my laptop (or will need to reinstall the system), what do I have to do first so that I don't have to reset my account again?
