### ISSUE TITLE
Keybase Helper Installation loops

### ISSUE THREAD

**Issue by bertjwregeer** [keybase/client#15252]
key base log send has been completed.

I can't open or use Keybase because the helper installation is looping.

my log id: 69a8e8a2487dca29f40cab1c

**Comment by bertjwregeer** [comment]
Looking at the system logs, it seems that the issue is related to me running as a non-admin user, and something in the helper requires an admin user.

**Comment by maxtaco** [comment]
See previous issue

**Comment by bertjwregeer** [comment]
Which previous issue?

**Comment by maxtaco** [comment]
https://github.com/keybase/client/issues/14183#issuecomment-450441417

**Comment by maxtaco** [comment]
Sorry, it wasn’t the previous issue, my bad. Working from my phone.

**Comment by bertjwregeer** [comment]
No worries. Will follow that one, posted work-around for not being able to uninstall the fuse/finder integration as a non-admin user.
