### ISSUE TITLE
Keybase Files Not Mounting Correctly

### ISSUE THREAD

**Issue by SCOTT0852** [keybase/client#15266]
Everything worked fine until Keybase said that I had to update my Dokan thingy, so I uninstalled the old one and installed the new one (rebooted after uninstalling & have rebooted since installing the new one). However, after that the K drive never mounted and clicking "Show in Finder" just gave me a standard Windows error saying there was no K drive. I typed something relating to "keybase kbfsmount" in command prompt, which did mount a K drive but Windows just says the drive is inaccessible when I click on it/click "Show in Finder". I can download stuff from the drive just fine, but I can't view it in Explorer like I used to be able to and I don't think I can upload to it from the keybase menu.

my log id: 7ff9fa63cca43fa2d63a321c

**Comment by zanderz** [comment]
Hi, these logs show a bunch of errors contacting our servers on Jan 1, along with being logged out of Keybase for a time. Aside from that, mounting `K:` seems to have worked. Is your connection solid?

When you say you can download stuff from the drive, how exactly are you doing that? not via `K:`?

@keybase/kbfs-hackers

**Comment by SCOTT0852** [comment]
Yes, I have a solid connection (tested with speedtest.net and fast.com, 18 ping, 25Mbps download, 24Mbps upload). I'm downloading stuff through `Download a copy` in the three dots that appear when you mouse over a file.

**Comment by jzila** [comment]
@SCOTT0852 when you browse your files in the Keybase app directly, does it show you a banner asking to enable viewing the files in Windows Explorer?

**Comment by SCOTT0852** [comment]
Nope, I actually can't toggle that off in the settings.

**Comment by jzila** [comment]
Strange, your log actually reports that the mount succeeded.

**Comment by jzila** [comment]
@taruti mind taking a look please?

**Comment by SCOTT0852** [comment]
If I had to guess, the mount "succeeded" because I can see a K: drive in Explorer.

**Comment by jzila** [comment]
@SCOTT0852 as a workaround, you might want to try to manually uninstall Dokan (using Add/Remove Programs), rebooting, then enabling KBFS again.

**Comment by SCOTT0852** [comment]
I uninstalled Dokan just fine, shut down, rebooted, but when I tried to install Dokan again after _just booting up_ it errored and said "Installation failed because a Windows reboot is still pending after a Dokan driver uninstall."

**Comment by SCOTT0852** [comment]
Rebooted again to install WSL and tried running the Dokan installer again, it works now. I just hope something like this won't happen again when it needs Dokan to update again...
