### ISSUE TITLE
Private folder reset

### ISSUE THREAD

**Issue by smileisak** [keybase/client#15264]
```bash
$ keybase sign -m "Tue Jan  1 16:44:03 CET 2019: Please reset folder /keybase/private/smileisak because all the devices that have access have been revoked because i am a moron."
```
BEGIN KEYBASE SALTPACK SIGNED MESSAGE. kXR7VktZdyH7rvq v5weRa0zkPByaWh tIVbk4lgNjuz2OM Q5hT4FldrBlIsGF zNLy9PczZ3Gvj39 wSuGn69a037rm8U qNzrFA0UXlOzxhT XRt5pmzNqCYJsh2 EYYoS5pkg68Adn1 uSFihQhyphqHV5Z awem4yZJghuMT0l 6jmcfxRreWg1fQ3 8CnSM3vQLViptvP zqkWWfFxdyzcXxh V2HkTJwpE12weoB 4fb2tOy66FBrUiR y9EtHbBfMZNWBPn VzFNKP0Ss2D3ic4 AgfQZ90walgJDPP tkIgmX5kaAuuFNM fPi2KPMPiffaCQP 8ILux5gPyRAfPxJ 8iVcpfWYYGU86yO kcEVTqnoSWzGjxz sP8ZwRqAGMAXrtM teBt6iI5aYWf0fn rBofw8U. END KEYBASE SALTPACK SIGNED MESSAGE.

**Comment by strib** [comment]
I reset the folder.  Please check it out and close this if everything seems ok.  (Might require a Keybase restart.)
