### ISSUE TITLE
Can't install update. Fails on helper install

### ISSUE THREAD

**Issue by bradmurray** [keybase/client#15273]
It just keeps asking for my password and eventually fails

my log id: 502a2de8b2aa2ccd955e101c

**Comment by maxtaco** [comment]
ah ok, you already did...

**Comment by maxtaco** [comment]
@bradmurray, so you tried this:

```
sudo dseditgroup -o edit -a $(whoami) -t user staff
```

And then restarted the app, and it didn't work?  can you run `keybase log send` after those steps, and then I'll take another look? Sorry about the bug...

**Comment by bradmurray** [comment]
That looks like it did the trick, but it didn't ask for the helper install on the next start so I'm not sure if something else cleared it up instead.

**Comment by maxtaco** [comment]
No, the install should just silently succeed in the success case. Sorry about the bug, we'll get a proper fix out soon.
