### ISSUE TITLE
Update Error

### ISSUE THREAD

**Issue by michaelh-mg** [keybase/client#15281]
Whenever Keybase starts on my mac, it says it needs to update and prompts me for my password. After I enter it, I get the same message saying it needs to update. That happens three times, and then it says there was an error.

my log id: db8615a8b29746e4d5f7441c

**Comment by maxtaco** [comment]
Sorry about the bug.  For a workaround, see this comment on github:

https://github.com/keybase/client/issues/13997#issuecomment-450845052
