### ISSUE TITLE
Can't uninstall Keybase on MacOS 10.14

### ISSUE THREAD

**Issue by gschmidt** [keybase/client#15280]
The only instructions I could find for uninstalling Keybase on Mac were those in #4226. Following the directions in #on a clean boot of MacOS 10.14, I got:

```
$ keybase uninstall
▶ ERROR Error stopping the redirector: exit status 1
▶ INFO Removing /Users/gschmidt/Library/LaunchAgents/keybase.kbfs.plist
▶ INFO Waiting for keybase.kbfs to exit...
▶ INFO Stopped keybase.kbfs
▶ INFO Nothing to stop (homebrew.mxcl.kbfs)
▶ INFO Removing /Users/gschmidt/Library/LaunchAgents/keybase.service.plist
▶ INFO Waiting for keybase.service to exit...
▶ INFO Stopped keybase.service
▶ INFO Nothing to stop (homebrew.mxcl.keybase)
▶ INFO Removing /Users/gschmidt/Library/LaunchAgents/keybase.updater.plist
▶ INFO Waiting for keybase.updater to exit...
▶ INFO Stopped keybase.updater
▶ INFO Removing KBFuse
▶ ERROR Error uninstalling fuse: exit status 1
▶ INFO Uninstalling KBNM NativeMessaging whitelists
▶ INFO Removing privileged helper tool
▶ ERROR Error uninstalling helper: exit status 1
▶ INFO Removing /usr/local/bin/keybase
▶ ERROR Error uninstalling command line: remove /usr/local/bin/keybase: permission denied

You can now remove /Applications/Keybase.app to complete your uninstall.
```

Running uninstall as root doesn't work:
```
$ sudo keybase uninstall
Password:
Oops, you are trying to run as an admin user (Uid: 0). This isn't supported.
```

Trying to run it again suggests that Keybase is now in some kind of half installed state:
```
$ keybase uninstall
▶ ERROR Error stopping the redirector: exit status 1
▶ INFO Nothing to stop (keybase.kbfs)
▶ INFO Nothing to stop (homebrew.mxcl.kbfs)
▶ INFO Nothing to stop (keybase.service)
▶ INFO Nothing to stop (homebrew.mxcl.keybase)
▶ INFO Nothing to stop (keybase.updater)
▶ INFO Removing KBFuse
▶ ERROR Error uninstalling fuse: exit status 1
▶ INFO Uninstalling KBNM NativeMessaging whitelists
▶ INFO Removing privileged helper tool
▶ ERROR Error uninstalling helper: exit status 1
▶ INFO Removing /usr/local/bin/keybase
▶ ERROR Error uninstalling command line: remove /usr/local/bin/keybase: permission denied

You can now remove /Applications/Keybase.app to complete your uninstall.
```

Quitting the app (both the one you open and the one that appears in the menu bar) doesn't help. This was a basic, clean install of Keybase that I did a couple of days ago.

How do I uninstall Keybase? Thanks in advance for your help :)

**Comment by maxtaco** [comment]
I have been testing this a bunch recently so I think it mainly works, but sadly you have hit a bug.  Is your user in group `admin`? It might be related to a recent regression.

**Comment by gschmidt** [comment]
Thanks @maxtaco! I don't think I've changed anything from the MacOS defaults. Here is the output of `groups`:

```
$ groups
staff everyone localaccounts _appserverusr admin _appserveradm _lpadmin _appstore _lpoperator _developer _analyticsusers com.apple.access_ftp com.apple.access_screensharing com.apple.access_ssh com.apple.sharepoint.group.1
```

**Comment by maxtaco** [comment]
Thanks. Did you install via homebrew?

**Comment by gschmidt** [comment]
No, I used the GUI installer downloaded from the website, following the prompts in the webapp.

**Comment by maxtaco** [comment]
Can you `keybase log send` and I'll take a look? Thank you, and sorry for the bug

**Comment by maxtaco** [comment]
These errors are safe to ignore. They mean you never installed the FS integration, so the uninstaller is failing to uninstall it. I'd say just delete Keybase.app and you're done. LMK if you see any vestiges of the install after that and we can dig deeper. Thanks

**Comment by gschmidt** [comment]
Doesn't just the fact that I can even run `keybase log send` mean that the installer failed and that parts of Keybase are still installed?

**Comment by maxtaco** [comment]
> You can now remove /Applications/Keybase.app to complete your uninstall.

I'm assuming you didn't do that ^ ?

**Comment by maxtaco** [comment]
It looks like after you do, you'll have a dangling `/usr/local/bin/keybase` symlink, which is a bug that we'll work on a fix for. You can `sudo rm /usr/local/bin/keybase` to get rid of that.

**Comment by gschmidt** [comment]
There was clearly some permissions problem that prevented keybase from uninstalling cleanly. This is concerning to me because - contrary to my expectations for a key management tool - keybase is evidently very complicated including multiple daemons, system services, system-wise menu bar items that start at start at startup and evidently can’t be turned off on the app, and even filesystem drivers.

I would like confidence that keybase has been fully uninstalled from my Mac and won’t create problems for me in the future. That confidence is especially important given that Keybase’s purpose is to manage secure key material. How can I get that confidence?

I do feel that it is a reasonable expectation that an app targeted at non-programmers, with a graphical installer, have a working uninstaller that cleanly removes the app from your computer.

**Comment by maxtaco** [comment]
We have been working on this part of the code recently. What do you want me to say other than that there is a bug, a minor one I would argue, and we'll work on a fix?

**Comment by maxtaco** [comment]
To provide slightly more details:
* You can disable app on startup. Settings > Advanced > Open Keybase on Startup
* Multiple daemons: we try to use principle of least privilege, so we have one daemon for crypto services, one for the GUI, one for FS operations, and one for install/upgrade operations
* File system driver: that's optional, and people really like this feature
* Confidence: I'm pretty sure that after your experience, you were left with one dangling symlink in `/usr/local/bin`, which we'll fix in our next release. We can't promise 0 bugs, and I'm not sure anyone should.
* Clean removal: this is something we obviously intend to work well. I think evidence of that is that I'm spending lots of time on it today, debugging this issue with you.

**Comment by gschmidt** [comment]
Thanks for the extra information. I appreciate your help, and your work on the important (and legendarily difficult) problem of providing everyone with secure, decentralized, and private ways to communicate.

**Comment by maxtaco** [comment]
@gschmidt thanks for the follow-up!  PR with a fix is now up here: https://github.com/keybase/client/pull/15307/files

**Comment by gschmidt** [comment]
Awesome! Thank you and much appreciated.
