### ISSUE TITLE
cannot run keybase

### ISSUE THREAD

**Issue by black-phillip616** [keybase/client#15465]
`▶ INFO Starting keybase.service.
Failed to restart keybase.service: Unit keybase.service is not loaded properly: Invalid argument.
See user logs and 'systemctl --user status keybase.service' for details.
▶ ERROR Failed to start keybase.service.
▶ ERROR Error in spawning server process: exit status 1
▶ ERROR exit status 1
`
ive tried to redirect the paths with no avail and also tried to run with sudo and still no dice.
`Linux dick 4.15.0-20-generic #21-Ubuntu SMP Tue Apr 24 06:16:15 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
`

**Comment by black-phillip616** [comment]
`● keybase.service - Keybase core service
   Loaded: error (Reason: Invalid argument)
   Active: failed (Result: exit-code) since Sun 2019-01-13 12:00:15 EST; 2h 32min ago
 Main PID: 3142 (code=exited, status=2)

Jan 13 12:00:15 dick systemd[981]: Failed to start Keybase core service.
Jan 13 12:00:15 dick systemd[981]: keybase.service: Service hold-off time over, scheduling restart.
Jan 13 12:00:15 dick systemd[981]: keybase.service: Scheduled restart job, restart counter is at 4.
Jan 13 12:00:15 dick systemd[981]: Stopped Keybase core service.
Jan 13 12:00:15 dick systemd[981]: keybase.service: Start request repeated too quickly.
Jan 13 12:00:15 dick systemd[981]: keybase.service: Failed with result 'exit-code'.
Jan 13 12:00:15 dick systemd[981]: Failed to start Keybase core service.
Jan 13 12:00:31 dick systemd[981]: /usr/lib/systemd/user/keybase.service:16: Unknown lvalue 'Environment' in section 'Install'
Jan 13 12:00:31 dick systemd[981]: /usr/lib/systemd/user/keybase.service:17: Missing '='.
Jan 13 14:33:05 dick systemd[981]: /usr/lib/systemd/user/keybase.service:17: Missing '='.
`
i also get this output

**Comment by heronhaye** [comment]
That's odd, what version are you on? How did you install Keybase?

```
keybase --version
```

Also, could you give the output of the following commands too? 
```bash
stat ~/.config/keybase
systemd-run /usr/bin/true
systemd-run --user /usr/bin/true
```
And if possible, can you do a `keybase log send` from the command line?

**Comment by black-phillip616** [comment]
i did it with the instrucitons on keybase.io with curling the .deb package, linux mint seems to not really like .deb packages.
`keybase --version`
`keybase version 2.13.0-20190104191034+69b3ee25b7
`
`  File: /home/tj/.config/keybase
  Size: 4096      	Blocks: 8          IO Block: 4096   directory
Device: 802h/2050d	Inode: 3932448     Links: 2
Access: (0755/drwxr-xr-x)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2019-01-13 01:58:18.202851487 -0500
Modify: 2019-01-13 12:41:12.116236415 -0500
Change: 2019-01-13 12:41:12.116236415 -0500
 Birth: -
`
`systemd-run /usr/bin/true
Failed to find executable /usr/bin/true: No such file or directory
`
`systemd-run --user /usr/bin/true
Failed to find executable /usr/bin/true: No such file or directory`

`cat /usr/lib/systemd/user/keybase.service
[Unit]
Description=Keybase core service

[Service]
# "notify" means we promise to call SdNotify() at the end of startup.
Type=notify
Environment=KEYBASE_SERVICE_TYPE=systemd
# import keybase environment variables
EnvironmentFile=-%t/keybase/keybase.env
ExecStart=/usr/bin/keybase --use-default-log-file --debug service
Restart=on-failure

[Install]
WantedBy=default.target`

**Comment by black-phillip616** [comment]
`keybase log send
This command will send recent keybase log entries to keybase.io
for debugging purposes only.

These logs don’t include your private keys or encrypted data,
but they will include filenames and other metadata keybase normally
can’t read, for debugging purposes.

Continue sending logs to keybase.io? (type 'YES' to confirm): yes
Enter feedback (or <Enter> to send): 
▶ INFO ignoring error getting keybase status: dial unix /run/user/1000/keybase/keybased.sock: connect: no such file or directory
▶ INFO ignoring UI logs: dial unix /run/user/1000/keybase/keybased.sock: connect: no such file or directory
▶ INFO Not sending up a UID for logged in user; none found


------------
Success! Your log ID is:

  7a15601f1e6fe4c98629201c

Here's a URL to submit new bug reports containing this ID:

  https://github.com/keybase/client/issues/new?body=[write%20something%20useful%20and%20descriptive%20here]%0A%0Amy%20log%20id:%207a15601f1e6fe4c98629201c

Thanks!
------------
`

**Comment by black-phillip616** [comment]
probably have to point some libraries, or compile from source? theres just no instructions on how to do this

**Comment by black-phillip616** [comment]
closed out my account and switched distros, now it works

**Comment by heronhaye** [comment]
I think it's just an old systemd version. There might be an issue with root owning your local config as well. Anyway, please open a new ticket if you experience something like that again. Thanks!

**Comment by black-phillip616** [comment]
yea it could have been the fact that form my phone i revoked the computer.
    On Monday, January 14, 2019, 12:48:04 AM EST, heronhaye <notifications@github.com> wrote:  
 
 
I think it's just an old systemd version. There might be an issue with root owning your local config as well. Anyway, please open a new ticket if you experience something like that again. Thanks!
