### ISSUE TITLE
rekey not working

### ISSUE THREAD

**Issue by NULLx76** [keybase/client#15498]
I'm trying to rekey my keybase files but after executing `keybase rekey paper` and entering my paper key nothing seems to happen. I'm sure the paper key should work as it is listed under `keybase status` but it doesn't. I've tried this on various devices to no avail.

my log id: e1dbc9267c2733320045351c

**Comment by strib** [comment]
@NULLx76 it looks like your device `eevee_2019_01_14` started to run a background "upgrade" function on that folder, but for some reason it never completed and now the folder is locked from more rekeys.  I can unlock it, but first I'd like to see logs from that device if you don't mind doing a `keybase log send` from it and reporting the log ID here.  Thanks!

**Comment by strib** [comment]
Actually I think I've answered my own question.  That new device actually _couldn't_ upgrade the folder because it didn't have access yet, so that's probably why it got stuck.  I'll fix this in the code, and unlock your folder for more rekeys in the meantime.

**Comment by strib** [comment]
@NULLx76 Actually I take it back.   It was actually your device `HP_x360_2018_07_28` that tried to upgrade the folder and never finished.  I would like a `keybase log send` from that device if you are willing to share.

In the meantime, your folder should be rekeyed automatically soon (within an hour I think), or you can force it with `keybase rekey paper` if you want.

(Sorry for the back-and-forth, I misread our server logs at first.)

**Comment by strib** [comment]
Great!
