### ISSUE TITLE
Dependency breaks `crouton` update

### ISSUE THREAD

**Issue by aanastasiou** [keybase/client#15509]
Not really sure if this is something that can be fixed via apt but I thought that it might be good to leave this notification:

I am running [crouton](https://github.com/dnschneid/crouton) on a chromebook and prefer to update the distribution via the provided `crouton` script. However, because of the `libappindicator` dependency, after installing keybase, the update process halts because the dependencies are not satisfied.

Trying to install `libappindicator` on its own fails because it depends on certain packages that (as far as I can tell) are unavailable on crouton.

Besides a possible fix that this issue might bring for keybase, is there something I can do so that I can keep keybase installed on that computer but also continue keeping that installation up to date via its normal update procedure?

**Comment by heronhaye** [comment]
To clarify, installing libappindicator (a dependency of keybase) breaks crouton updates?

**Comment by aanastasiou** [comment]
@heronhaye, No. The fact that keybase has that unresolved dependency associated with it, stops the crouton update process.

This is not a crouton specific process, it is the normal Linux update process by which a dependency tree is built and checked, etc. Unfortunately at the moment I don't have the exact message with me but it is along the same lines of the messae that is produced during installation (about libappindicator) only that this time around it halts the process completely.

**Comment by heronhaye** [comment]
When you installed Keybase, did you have to explicitly stop apt from installing libappindicator then?

**Comment by aanastasiou** [comment]
@heronhaye I did not take any further action than [this](https://keybase.io/docs/the_app/install_linux).

During installation of keybase, I get:

```
Preparing to unpack keybase_amd64.deb ...
Unpacking keybase (2.13.1-20190115203650.eec94506e4) ...
dpkg: dependency problems prevent configuration of keybase:
 keybase depends on libappindicator1; however:
  Package libappindicator1 is not installed.
 keybase depends on lsof; however:
  Package lsof is not installed.

dpkg: error processing package keybase (--install):
 dependency problems - leaving unconfigured
Processing triggers for desktop-file-utils (0.22-1ubuntu5.2) ...
Processing triggers for mime-support (3.59ubuntu1) ...
Processing triggers for hicolor-icon-theme (0.15-0ubuntu1.1) ...
Errors were encountered while processing:
 keybase
```
And this was the same message that was halting the update. I just tried to do it again but the "update" went ahead. I am not sure if the process went over the same steps however, since the machine must have been up to date. I am also not sure if installing it once, removing it with `apt-get purge keybase` and then installing it again might be an unofficial "fix" :)

It might re-surface in the future however, any ideas in that case?

**Comment by heronhaye** [comment]
I'm pretty confused on how you were able to install keybase in the first place actually without giving `dpkg` a specific flag to ignore dependencies, but I'm not very familiar with dpkg/apt.

Yeah, it sounds like the `purge` and reinstall could resolve some dependency issues. Do you have `libappindicator` installed now or still no? What about `lsof`? If you have both I don't think there'll be any more errors. There's probably some flag you can pass to the updater that tells it to ignore unmet dependencies...but it might just be easier to remove and reinstall. Make a new issue if you run into any more trouble though, thanks!
