### ISSUE TITLE
git push error

### ISSUE THREAD

**Issue by magicstone1412** [keybase/client#15508]
I got the error below when using push command. Can you please help me?

```
$ git push
Initializing Keybase... done.
Syncing with Keybase... team key generation too low: 7 < 14
git-remote-keybase error: (1) team key generation too low: 7 < 14
git-remote-keybase error: (1) team key generation too low: 7 < 14
```

**Comment by heronhaye** [comment]
Hi, please try again and then do a `keybase log send` if you still get an error. Thanks!

**Comment by heronhaye** [comment]
hmm, do you see the text
```
Continue sending logs to keybase.io? (type 'YES' to confirm): 
```
under that line? Maybe try another terminal?

**Comment by keybase-travis** [comment]
What version of keybase are you on?

**Comment by magicstone1412** [comment]
> under that line? Maybe try another terminal?

I change the terminal to power shell and it shows the results below 
```

This command will send recent keybase log entries to keybase.io
for debugging purposes only.

These logs don’t include your private keys or encrypted data,
but they will include filenames and other metadata keybase normally
can’t read, for debugging purposes.

Continue sending logs to keybase.io? (type 'YES' to confirm): YES
Enter feedback (or <Enter> to send): github issues #15508
More feedback (or press <Enter> when done):
- ERROR API network error: Post https://api-0.core.keybaseapi.com/_/api/1.0/logdump/send.json: net/http: request cancele
d (Client.Timeout exceeded while awaiting headers)
```
> What version of keybase are you on?

```
$ keybase version
Client:  2.6.2-20180920135656+0f17a92adc
Service: 2.6.2-20180920135656+0f17a92adc

```
Thank you

**Comment by maxtaco** [comment]
Very old version, try upgrading, and it should work.

**Comment by maxtaco** [comment]
(if you're not having network problems, which you might...)

**Comment by magicstone1412** [comment]
> 
> 
> Very old version, try upgrading, and it should work.

I use 32bit version. I could not find 32bit on the download page of keybase

> (if you're not having network problems, which you might...)

My network is okay because I can access to the other services

**Comment by heronhaye** [comment]
Sorry, Keybase no longer supports 32-bit Windows.
