### ISSUE TITLE
Duplicate Minimize menu item in Window drop-down menu

### ISSUE THREAD

**Issue by tonymagro** [keybase/client#15556]
Keybase GUI Version: 2.13.1-20190115113807+c5be116f6b
OS: Windows 10

There appears to be two Minimize menu items in the Window drop-down menu on the Menu Bar.
![image](https://user-images.githubusercontent.com/393717/51275163-c60c6280-1996-11e9-8565-26d39d3b321b.png)

**Comment by zanderz** [comment]
tracked internally with DESKTOP-8787

**Comment by tonymagro** [comment]
Looks like a fix was merged with pull request #15691
Verified fixed in Keybase GUI Version: 3.0.0-20190205104115+6394d03e6c
