### ISSUE TITLE
what does "keyed with a key generation (5) that we don't know" mean

### ISSUE THREAD

**Issue by vacuumboots** [keybase/client#15575]
I'm getting the message "Syncing with Keybase... The data for 6fff2313003e3b18d58ffff00d5a5616 is keyed with a key generation (5) that we don't know
git-remote-keybase error: (1) The data for 6fff2313003e3b18d58ffff00d5a5616 is keyed with a key generation (5) that we don't know" when I try to push or pull a keybase repo

I don't know what that means

my log id: f12327dee17afe1f4d65cb1c

**Comment by maxtaco** [comment]
Likely our bug, we'll take a look, thanks!

**Comment by vacuumboots** [comment]
Can no longer replicate,
git pushes and pulls to keybase repo are now successful.

**Comment by strib** [comment]
@vacuumboots hmm, I'm glad it's working again, but I'm still struggling to figure out the earlier behavior.  Would you mind doing another `keybase log send` so we can see what changed to fix it?

**Comment by vacuumboots** [comment]
log ID is:

  1f35694f24a87576fd59451c
