### ISSUE TITLE
Cannot log in to desktop client 

### ISSUE THREAD

**Issue by ana0** [keybase/client#15591]
Immediately after logging in for the first time, trying to export secret key gives `GPG error: exit status 2`.  Trying to open a one-time shell gives `GPG error: exit status 2 Error code 218: GENERIC in method keybase.1.login.login`

Any help/suggestions very appreciated!

my log id: 7afed4e47bc9ac86e6fd791c

**Comment by maxtaco** [comment]
Ah, happy to help with this!

Saw the log, try this:

```
export GPG_TTY=$(tty)
keybase login
```

**Comment by ana0** [comment]
Thanks @maxtaco! I tried it, and it let me sign the install, but the option to import my key to keybase's keyring still fails in the cli interface with `exit status 2` - just in case that's not expected

Anyway, have logged in successfully now either way :smile:

**Comment by maxtaco** [comment]
I'm glad it worked to log in.  The import option sometimes doesn't work depending on GPG setup, but it's strictly optional.

**Comment by ana0** [comment]
Good to know!  Thanks again
