### ISSUE TITLE
Git push after squash takes a long time

### ISSUE THREAD

**Issue by vraravam** [keybase/client#15613]
I have my home folder (many ignored dirs/files) with some other files stored in keybase. I am on the latest public release of both keybase and git (both are installed via `homebrew`).

Sometimes, the number of commits becomes too huge, and in those cases, I squash many commits (even ones that have been pushed to remote). Doing this, when I try to `git push -f`, the time taken to push takes above 30 mins. Is there some setting that I can make for it to use multiple threads, or have a higher http buffer or ...?
My global `.gitconfig` is present [here](https://gist.github.com/vraravam/eab090e70a545934f409) in case it helps

Its been stuck in this state for approx 10 mins now.

```
Initializing Keybase... done.
Syncing with Keybase... done.
Preparing and encrypting: (100.00%) 686/686 objects... done.
Indexing hashes: (35.13%) 241/686 objects... done.
Indexing CRCs: (35.13%) 241/686 objects... done.
Indexing offsets: (35.13%) 241/686 objects... done.
Syncing encrypted data to Keybase: (37.93%) 67.86/178.92 MB...
```

**Comment by maxtaco** [comment]
Can you send `keybase version`?

**Comment by vraravam** [comment]
```
Client:  2.13.1-20190115193453+c5be116f6b
Service: 2.13.1-20190115193453+c5be116f6b
```

**Comment by vraravam** [comment]
Update: Just now, the push is still here:
```
Initializing Keybase... done.
Syncing with Keybase... done.
Preparing and encrypting: (100.00%) 686/686 objects... done.
Indexing hashes: (35.13%) 241/686 objects... done.
Indexing CRCs: (35.13%) 241/686 objects... done.
Indexing offsets: (35.13%) 241/686 objects... done.
Syncing encrypted data to Keybase: (72.73%) 130.12/178.92 MB...
```

**Comment by vraravam** [comment]
Update: the push finally successfully completed.

**Comment by maxtaco** [comment]
Ok that is a new version.  @strib might have some ideas.  `keybase log send` might be useful too.

**Comment by strib** [comment]
If you do `keybase log send` and report the log ID here I can take a look this week.  There are known issues with slowness that we will be tackling soon, so this might fall into that same category.

**Comment by vraravam** [comment]
This is what I am getting:
```
▶ ERROR API network error: Post https://api-0.core.keybaseapi.com/_/api/1.0/logdump/send.json: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
```

**Comment by vraravam** [comment]
Here's the log id: `3d541c284cfe5ac7a3629a1c`

**Comment by strib** [comment]
@vraravam in the logs it looks like your client was unable to maintain a TCP connection with our servers for long amounts of time.  Even though it tries to upload lots of things in parallel, it was only able to maintain about a 30KB/s connection with our server most of the time, and even that was constantly interrupted by timeouts.  (Which, for 172MB, comes out to an estimate of over 1.5 hours.)

I can't say for sure where in the network the issue actually lays, but I don't know of any problems our servers/network was having at this time.  Maybe there is a VPN or other middlebox interfering with or shaping your traffic to us?  (Also evident in the timeout you got while sending logs.)

We don't have any other settings in our software to try other things, unfortunately.  We will be spending time soon to see what we can improve in our upload performance in general, but it will always be gated by network performance of course.  Sorry for the bad experience!

**Comment by vraravam** [comment]
thanks for the update @strib - Let's hope that the general improvements can reduce this scenario as well. Should we close this issue for now?

**Comment by strib** [comment]
Sure, let us know if anything else comes up.
