### ISSUE TITLE
Linux desktop notifications always show content

### ISSUE THREAD

**Issue by dandv** [keybase/client#15620]
This is a privacy issue - I don't want the text of a sensitive message to pop up while I'm showing my screen to someone else.

Is there a setting to control whether to display desktop notification text? Other messaging system can optionally display only the notification sender, or even only a generic "New message" notification.

![image](https://user-images.githubusercontent.com/33569/51465686-44f9f600-1d1d-11e9-92bb-48fe581aeab3.png)

**Comment by AnthonyMBonafide** [comment]
I think this is a great idea. I have removed the Linux client from my computer for this very reason.

**Comment by AnthonyMBonafide** [comment]
If an engineer on the team can point out generally where these changes need to be made and any potential issues, I wouldn't mind trying to tackle this in some of my spare time.

**Comment by AnthonyMBonafide** [comment]
@dandv, Just as a quick fix to this problem. When you are in the chat section of the desktop app, you can click the `i` in the top right corner and configure your notifications that way. It seems like you would have to configure the notifications per conversation/team. This is what I am doing until this feature is added to the codebase.

**Comment by AnthonyMBonafide** [comment]
@heronhaye , any thoughts or ideas regarding this issue?

**Comment by heronhaye** [comment]
We have a ticket for this issue, I'll update with PR # when it's ready.
cc @joshblum 

In the meantime, you could do something like set up hotkeys to disable and enable your notification daemon when presenting, e.g., https://wiki.archlinux.org/index.php/Dunst#Disable_dunst_temporarily.

**Comment by joshblum** [comment]
closed via #17337
