### ISSUE TITLE
Android: Wallet notification badge for non-primary account

### ISSUE THREAD

**Issue by mikaelf** [keybase/client#15641]
If there's a transaction in a secondary wallet, in the android app there is a notification badge (a number) shown on:
* the hamburger menu in the bottom tab bar, and
* the Wallet option in the menu.

However, tapping into the Wallet doesn't bring you to the account for which the notification is for, but your (last used or primary?) account. It's not obvious that you will have to go and browse through your accounts in the top list. There is no notification badge on the wallet screen to indicate where to go to see the transaction.

**Comment by buoyad** [comment]
@mikaelf Good observation, thanks for the report. This will be fixed in the next release by https://github.com/keybase/client/pull/15741
