### ISSUE TITLE
Keybase menu will open, main app will not

### ISSUE THREAD

**Issue by eblanton** [keybase/client#15650]
I was just able to open the small Keybase menu-like window on Linux, but clicking "Open main app" would not open the main Keybase window, nor would clicking any of the chats or notifications in the menu-like window.  Running run_keybase fixed the problem.

my log id: ae8abbd6e242dee1bac3421c

**Comment by heronhaye** [comment]
Sorry, couldn't find much in the logs. Seems the service crashed for some reason and that's why the gui probably didn't open and `run_keybase` worked. Let us know if it happens again.
