### ISSUE TITLE
Have paper key, but can't find any way to use it to recover account.

### ISSUE THREAD

**Issue by gilbertw1** [keybase/client#15700]
Hi, I no longer have access to a logged in device, however I do have my paper key. Unfortantely running 'keybase login' only prompts me for a password and I can't find any way to provide my paper key. 

I know I have the paper key tied to the account because if I attempt to recover the account via the web it lists the paper key with the exact two starting words as an option with the "power to change your passphrase".

Am I missing something? I can't find any documentation about how to use a paper key other than it exists, how to generate one, and that it can somehow be used to recover my account.

**Comment by gilbertw1** [comment]
Thanks for the response. You are correct in that `deprovision` does not seem to work since I'm not logged in. I've removed the directories in both `~/.config` and `~/.local/share`, and I still seem to be unable to find a way to use the paper key. Running `keybase login <username>` simply prompts me to enter a password and provides no opportunity or option to enter a paper key.

What should I be expecting here? Or are there any alternatively login methods that should allow me to specify a paper key?

Also, not sure if it's relevant, but I'm using the command line client on arch linux as installed using the AUR `keybase-bin` package. The version is `3.0.0-20190125162145+5b9b6acf43`

**Comment by heronhaye** [comment]
Have you forgotten your password? I think you need to enter that and then the paperkey afterwards.

**Comment by strib** [comment]
@gilbertw1 I should have mentioned, but you probably want to kill the keybase processes before you moved those directories, and restart them afterward.  Have you restarted it yet?

**Comment by gilbertw1** [comment]
I tried the following:
 - Completely removed the keybase package (`pacman -R keybase-bin`)
 - Reboot
 - Verify no keybase processes are running (`ps -aux | keybase`)
 - Removed keybase directories
   + `rm -r ~/.config/keybase`
   + `rm -r ~/.local/share/keybase`
   + `rm -r ~/.cache/keybase`
  - Reinstalled keybase package (`yay -S keybase-bin`)

After all of the above, running `keybase login <username>` still prompts me to enter a "Keybase passphrase" for the account, with no option to enter a paper key. Additionally, I've tried using the keybase app on Android and it only prompts me for a password as well. 

Should the client(s) be determining that a paper key is attached to the account and prompting to enter one based on a response from the Keybase service?

**Comment by maxtaco** [comment]
Are you using your username and not an email address?

**Comment by gilbertw1** [comment]
Oh man, that was it. I was using the email address, I thought they could be used interchangeably!

After remembering and using the (actual) username, I was prompted and able to enter my paper key. Sorry for wasting your time :)

**Comment by maxtaco** [comment]
Cool, glad it works. Yeah, we need the password for the email-based flow, since it would leak private data otherwise.

**Comment by akashnimare** [comment]
`keybase login username` shows me the prompt for password. How do I get an option to enter my paper key?
