### ISSUE TITLE
git-remote-keybase: metadata for folder ... is of a version (4) that we can't read

### ISSUE THREAD

**Issue by pschulten** [keybase/client#15724]
* Created a test git repo in the client 
* cloning :
```bash
(🕹 stan:lines-dev) pschu@snook ~/tmp/home-test> sudo ln -s /Applications/Keybase.app/Contents/SharedSupport/bin/git-remote-keybase /usr/local/bin/git-remote-keybase
Password:
(🕹 stan:lines-dev) pschu@snook ~/tmp/home-test> git clone keybase://private/pschulten/test
Cloning into 'test'...
Initializing Keybase... done.
Syncing with Keybase... The metadata for folder c45a403506600a6b4ef6886f85226116 is of a version (4) that we can't read
git-remote-keybase error: (1) The metadata for folder c45a403506600a6b4ef6886f85226116 is of a version (4) that we can't read

(🕹 stan:lines-dev) pschu@snook ~/tmp/home-test> /usr/local/bin/git-remote-keybase --version
1.0.2-20190123014507+6bb157b5d0
```
Not sure how to fix this. It used to work flawlessly in the past.

my log id: bb6f547c4419d7ddcf65dc1c

**Comment by strib** [comment]
@pschulten this was a bug in a previous release, but it looks like you're running the latest release.  However, your git logs indicate you might still be running an old git version somehow.  Have you ever compiled your own version of `git-remote-keybase`, or somehow messed with the execution/install paths of your keybase app such that it might still be using an old version?

**Comment by strib** [comment]
(I'm also curious if you can read your private folder at `/keybase/private/pschulten` without any errors.)

**Comment by pschulten** [comment]
@strib I'm an idiot:
```
snook:~ root# find / -name git-remote-keybase 2>/dev/null
/usr/local/bin/git-remote-keybase
/Users/pschu/bin/git-remote-keybase
^C
``` 
sorry for the noise :(
