### ISSUE TITLE
kbfs.service won't start

### ISSUE THREAD

**Issue by eblanton** [keybase/client#15721]
When I run_keybase, kbfs.service doesn't start, and logs the following:

```
Jan 26 18:42:23 colt systemd[4774]: Starting Keybase Filesystem service... 
Jan 26 18:42:24 colt sh[13495]: fusermount: entry for /run/user/1000/keybase/kbfs not found in /etc/mtab 
Jan 26 18:42:24 colt systemd[4774]: kbfs.service: Main process exited, code=exited, status=2/INVALIDARGUMENT 
Jan 26 18:42:24 colt sh[13548]: fusermount: entry for /run/user/1000/keybase/kbfs not found in /etc/mtab 
Jan 26 18:42:24 colt systemd[4774]: Failed to start Keybase Filesystem service. 
Jan 26 18:42:24 colt systemd[4774]: kbfs.service: Unit entered failed state. 
Jan 26 18:42:24 colt systemd[4774]: kbfs.service: Failed with result 'exit-code'. 
Jan 26 18:42:24 colt systemd[4774]: kbfs.service: Service hold-off time over, scheduling restart. 
Jan 26 18:42:24 colt systemd[4774]: Stopped Keybase Filesystem service. 
Jan 26 18:42:24 colt systemd[4774]: Starting Keybase Filesystem service... 
Jan 26 18:42:24 colt sh[13571]: fusermount: entry for /run/user/1000/keybase/kbfs not found in /etc/mtab 
Jan 26 18:42:24 colt systemd[4774]: kbfs.service: Main process exited, code=exited, status=2/INVALIDARGUMENT 
Jan 26 18:42:25 colt sh[13615]: fusermount: entry for /run/user/1000/keybase/kbfs not found in /etc/mtab 
Jan 26 18:42:25 colt systemd[4774]: Failed to start Keybase Filesystem service. 
Jan 26 18:42:25 colt systemd[4774]: kbfs.service: Unit entered failed state. 
Jan 26 18:42:25 colt systemd[4774]: kbfs.service: Failed with result 'exit-code'. 
Jan 26 18:42:25 colt systemd[4774]: kbfs.service: Service hold-off time over, scheduling restart. 
Jan 26 18:42:25 colt systemd[4774]: Stopped Keybase Filesystem service. 
Jan 26 18:42:25 colt systemd[4774]: Starting Keybase Filesystem service... 
Jan 26 18:42:25 colt sh[13636]: fusermount: entry for /run/user/1000/keybase/kbfs not found in /etc/mtab 
Jan 26 18:42:25 colt systemd[4774]: kbfs.service: Main process exited, code=exited, status=2/INVALIDARGUMENT 
Jan 26 18:42:25 colt sh[13677]: fusermount: entry for /run/user/1000/keybase/kbfs not found in /etc/mtab 
Jan 26 18:42:25 colt systemd[4774]: Failed to start Keybase Filesystem service. 
Jan 26 18:42:25 colt systemd[4774]: kbfs.service: Unit entered failed state. 
Jan 26 18:42:25 colt systemd[4774]: kbfs.service: Failed with result 'exit-code'. 
Jan 26 18:42:26 colt systemd[4774]: kbfs.service: Service hold-off time over, scheduling restart. 
Jan 26 18:42:26 colt systemd[4774]: Stopped Keybase Filesystem service. 
Jan 26 18:42:26 colt systemd[4774]: kbfs.service: Start request repeated too quickly. 
Jan 26 18:42:26 colt systemd[4774]: Failed to start Keybase Filesystem service. 
Jan 26 18:42:26 colt systemd[4774]: kbfs.service: Unit entered failed state. 
Jan 26 18:42:26 colt systemd[4774]: kbfs.service: Failed with result 'exit-code'. 
```

keybase log send 36b1c5f707b8949767505a1c

**Comment by holycleugh** [comment]
Sorry about this, we're investigating to figure out what is causing this. In the meantime, please stop all Keybase services: 

```
systemctl --user stop keybase kbfs keybase.gui
```

verify everything is shut down with
```
ps aux | grep -i -E 'keybase|kbfsfuse'
```

and then
```
rm -r ~/.local/share/keybase/kbfs_conflicts/
run_keybase
```

Let me know if KBFS is able to start up after that.

**Comment by heronhaye** [comment]
Sorry about this, we're investigating to figure out what is causing this. In the meantime, please stop all Keybase services: 

```
systemctl --user stop keybase kbfs keybase.gui
```

verify everything is shut down with
```
ps aux | grep -i -E 'keybase|kbfsfuse'
```

and then
```
rm -r ~/.local/share/keybase/kbfs_conflicts/
run_keybase
```

Let me know if KBFS is able to start up after that.

**Comment by eblanton** [comment]
That procedure worked, and kbfs started normally.

It may be relevant that earlier today I had a graphics driver crash and had to reboot my system (so kbfs would not have been shut down cleanly).  Perhaps that left some state in kbfs_conflicts?  I don't believe that I had written to kbfs in the time leading up to the crash (for several hours or more), however.

**Comment by heronhaye** [comment]
Thanks for the info, it's possible. We had another report of this issue a few days ago as well, let us know if this happens again.

cc @jakob223

**Comment by atoponce** [comment]
FWIW, I just ran into this issue, and work-around by @heronhaye did not work for me.

    $ ps aux | grep -i -E 'keybase|kbfsfuse'
    atoponce  3334 25.0  1.4 1750472 179732 ?      Ssl  09:48   1:01 /usr/bin/keybase --use-default-log-file --debug service
    atoponce  3388  0.0  0.0 599816  4872 ?        Ssl  09:48   0:00 /usr/bin/keybase-redirector /keybase
    atoponce  3579  9.1  3.1 2114148 387148 ?      Ssl  09:51   0:05 /usr/bin/kbfsfuse -debug -log-to-file
    atoponce  3606  0.0  0.0   6212   892 pts/5    S+   09:52   0:00 grep -i -E keybase|kbfsfuse
    $ systemctl --user stop keybase kbfs keybase.gui keybase-redirector
    $ ps aux | grep -i -E 'keybase|kbfsfuse'
    atoponce  3627  0.0  0.0   6212   892 pts/5    S+   09:52   0:00 grep -i -E keybase|kbfsfuse
    $ rm -r ~/.local/share/keybase/kbfs_conflicts/
    $ run_keybase -g
    Starting via systemd...
    Job for kbfs.service failed because a timeout was exceeded.
    See "systemctl --user status kbfs.service" and "journalctl --user -xe" for details.
    $ systemctl --user status kbfs.service
    ● kbfs.service - Keybase Filesystem service
       Loaded: loaded (/usr/lib/systemd/user/kbfs.service; disabled; vendor preset: enabled)
       Active: activating (start) since Fri 2019-05-03 09:49:44 MDT; 1min 25s ago
      Process: 3438 ExecStartPre=/bin/sh -c fusermount -uz "$(keybase config get -d -b mountdir)" (code=exited, status=1/FAILURE)
     Main PID: 3459 (kbfsfuse)
       CGroup: /user.slice/user-1000.slice/user@1000.service/kbfs.service
               └─3459 /usr/bin/kbfsfuse -debug -log-to-file
    
    May 03 09:49:44 xxxxxxxxxxx systemd[1123]: Starting Keybase Filesystem service...
    May 03 09:49:44 xxxxxxxxxxx sh[3438]: fusermount: entry for /run/user/1000/keybase/kbfs not found in /etc/mtab

My situation isn't too unlike @eblanton. I had a hard drive failure that brought down my workstation. After replacing the drive, and restoring my `/home` data from backup, I cannot mount KBFS.

**Comment by heronhaye** [comment]
Could you do a `keybase log send`?

Also, do you see any data in `ls $(keybase config get -d -b mountdir)`?

**Comment by atoponce** [comment]
Log send. The log id is `7616850f8e5e0a2574efae1c`.

    $ ls -d $(keybase config get -d -b mountdir)
    ls: cannot access '/run/user/1000/keybase/kbfs': No such file or directory
    $ mkdir $(keybase config get -d -b mountdir)
    $ ls -d $(keybase config get -d -b mountdir)
    /run/user/1000/keybase/kbfs
    $ run_keybase   
    Unmounting and shutting down kbfsfuse...
    Shutting down keybase service...
    Starting via systemd...
    Job for kbfs.service failed because a timeout was exceeded.
    See "systemctl --user status kbfs.service" and "journalctl --user -xe" for details.
