### ISSUE TITLE
Reset Keys and unable to talk with anyone that I used to

### ISSUE THREAD

**Issue by ckipp01** [keybase/client#15750]
After resetting my keys, I'm now unable to chat with people I have been in conversations with in the past, and I'm unable to start a new conversation with them. I've testing this with someone and they have both re-followed each other, and he has tried to let me back into the conversation. It just tells him that I have invalid proofs. I can still see the conversation when I `keybase chat ls`, but when I try to delete the conversation with `keybase chat delete-history <name>` it tells me that I not a member of this team (code 2623). When I try to start a new conversation it just tells me that an error occurred. So essentially, after resetting, re-following each other, we can't have any type of conversation anymore.

Log id: 104f26d5e795395b8a77d91c

**Comment by keybase-travis** [comment]
They have to let you back into the conversation.
