### ISSUE TITLE
Unable to acces files in gui for ubuntu

### ISSUE THREAD

**Issue by Haadem** [keybase/client#15751]
Suddenly my access to files in keybase was gone. Get: "unexplained error occurred" in GUI. ### run_keybase:

Job for kbfs.service failed because the control process exited with error code. See "systemctl --user status kbfs.service" and "journalctl -xe" for details

### systemctl --user status kbfs.service:
● kbfs.service - Keybase Filesystem service
   Loaded: loaded (/usr/lib/systemd/user/kbfs.service; disabled; vendor preset: enabled)
   Active: failed (Result: start-limit-hit) since Tue 2019-01-29 11:27:23 CET; 2min 47s ago
  Process: 23801 ExecStop=/bin/sh -c fusermount -uz "$(keybase config get -d -b mountdir)" (code=exited, status=1/FAILURE)
  Process: 23778 ExecStart=/usr/bin/kbfsfuse -debug -log-to-file (code=exited, status=2)
  Process: 23755 ExecStartPre=/bin/sh -c fusermount -uz "$(keybase config get -d -b mountdir)" (code=exited, status=1/FAILURE)
 Main PID: 23778 (code=exited, status=2)

Jan 29 11:27:22 Titan systemd[2382]: Failed to start Keybase Filesystem service.
Jan 29 11:27:22 Titan systemd[2382]: kbfs.service: Unit entered failed state.
Jan 29 11:27:22 Titan systemd[2382]: kbfs.service: Failed with result 'exit-code'.
Jan 29 11:27:23 Titan systemd[2382]: kbfs.service: Service hold-off time over, scheduling restart.
Jan 29 11:27:23 Titan systemd[2382]: Stopped Keybase Filesystem service.
Jan 29 11:27:23 Titan systemd[2382]: kbfs.service: Start request repeated too quickly.
Jan 29 11:27:23 Titan systemd[2382]: Failed to start Keybase Filesystem service.
Jan 29 11:27:23 Titan systemd[2382]: kbfs.service: Unit entered failed state.
Jan 29 11:27:23 Titan systemd[2382]: kbfs.service: Failed with result 'start-limit-hit'.

my log id: 705a7ce65d9e7604ea6a6b1c

**Comment by strib** [comment]
@Haadem sorry about this, you're hitting a known bug that we currently have a fix under review for: #15728 

To work around it in your case, stop all the keybase processes and:
```sh
rm -rf .local/share/keybase/kbfs_conflicts
```

That should clear it up.  Sorry for the bad experience.

cc: @jakob223

**Comment by Haadem** [comment]
That worked. Thanks!

**Comment by ebi-droid** [comment]
I still have the same error: ExecStartPre=/bin/sh -c fusermount -uz "$(keybase config get -d -b mountdir)" (code=exited, status=1/FAILURE)

removing  $HOME/.local/share/keybase/kbfs_conflicts  does not help
