### ISSUE TITLE
Windows 10 tray icon popup is mispositionned

### ISSUE THREAD

**Issue by louisgrasset** [keybase/client#15770]
Here's the result : 
![image](https://user-images.githubusercontent.com/9489181/51948832-613b1880-242a-11e9-94fb-ba888ea935f2.png)

Keybase GUI Version: 2.13.2-20190122174654+6bb157b5d0

**Comment by louisgrasset** [comment]
![preview](https://user-images.githubusercontent.com/9489181/51971342-30ce9b00-2479-11e9-8169-fefd74e0c2d9.png)

**Comment by pzduniak** [comment]
Randomly noticed this issue, I'll chime in with how it looks here:
![image](https://user-images.githubusercontent.com/917230/52014713-91dd8980-24e0-11e9-9f02-e412677c0dec.png)

I know that most users won't have that many apps running in the background, but the current workaround doesn't really fix anything and when you the app to the bar, you get this ugly popup that Louis is seeing.

**Comment by louisgrasset** [comment]
A lots of app are able to place their menu following icon context : 
![image](https://user-images.githubusercontent.com/9489181/52214580-3c173180-2892-11e9-985b-79013e489e43.png)

**Comment by zanderz** [comment]
Probably not Electron apps drawing a widget there instead of a standard native menu.
I think it would be best if we just let people move it to where they want to see it, I'll look into it.

**Comment by zanderz** [comment]
@cecileboucheron
