### ISSUE TITLE
Unable to access the team files

### ISSUE THREAD

**Issue by yuhuisiyu** [keybase/client#15923]
Hi there,

I'm having trouble to access my team files. I can see private files with other person and send files within the chat. When i go into the team files, it is empty while my other team members can all see the files. I have tried the following ways:
- reinstall the app
- Delete my laptop and add it in again
- reset my account 

My keybase version is: keybase version 3.0.0-20190205183613+6394d03e6c
My log id: a2df354a78b7f07081ffcd1c

Thank you.

**Comment by strib** [comment]
@yuhuisiyu thanks for the report, and sorry for the bad experience.  I don't actually see any attempt to access any "team" folders in your logs (i.e., ones under `/keybase/team`).  I do see access of a shared folder with one other named user (under `/keybase/private`) -- is that the one you mean?  If so, it seems from your logs that it's returning 2 files in that shared folder, so I'm confused about what's going on.

If it's some other folder, can you tell me the name?  Feel free to message me (`strib`) on Keybase if you want to keep the name private.

It could be that the other person in your team is having issues writing the files as well -- maybe ask them to send a log too so I can check.

**Comment by strib** [comment]
We talked privately.  In this case, the solution was to `ls /keybase/team/<teamname>`, due to some bug on the Keybase servers that didn't correctly add the team folder to her favorites list.  We've opened an internal issue to investigate, but now @yuhuisiyu has access again after the `ls`.
