### ISSUE TITLE
My twitter post wasn't proof

### ISSUE THREAD

**Issue by freizl** [keybase/client#15936]
- here is my twitter: https://twitter.com/freizl/status/1091403850500603904
- my keybase name: https://keybase.io/freizl

**Comment by the-exodus** [comment]
### This account's Tweets are protected.

Only confirmed followers have access to @freizl's Tweets and complete profile. Click the "Follow" button to send a follow request.

**Comment by freizl** [comment]
retry but still not work.

**Comment by the-exodus** [comment]
The reason it isn't working is that you have set your Twitter to private, or "protected." That means only those following you on Twitter can read the post, and Keybase isn't.

The tweet needs to be public.

**Comment by freizl** [comment]
gotcha. thx!!
