### ISSUE TITLE
input/output error on all Keybase folders

### ISSUE THREAD

**Issue by taohansen** [keybase/client#15946]
I've reprovisioned this device 3 times now with no success. I also deleted ~/.local/share/keybase for good measure between provisions. 

my log id: b36a698858d5fc1c3a99911c

**Comment by strib** [comment]
We talked privately. @taohansen is running NixOS distributions, which seems to still have Keybase version of 2.6.0 in their packages, which is pretty old and likely not allowed to contact our servers anymore.

**Comment by worldofpeace** [comment]
The versions we currently have for keybase on master are
- keybase-client - 2.13.1
- kbfs - 2.11.0
- keybase-gui - 2.13.1

It's possible that @taohansen is probably using the 18.09 release and we have
- keybase-client - 2.10.1
- kbfs - 2.10.1
- keybase-gui - 2.11.0

I think you should probably update your machine so you get these newer versions.

However in NixOS this has been a running issue for some people https://github.com/NixOS/nixpkgs/issues/50999

**Comment by taohansen** [comment]
It was an old version that was the issue. I upgraded to 2.10.1 and now have access.
