### ISSUE TITLE
Unable to view private directory or create private git repository

### ISSUE THREAD

**Issue by savanto** [keybase/client#15987]
I'm getting similar errors to #15609, #14976, #13280, #12973 when trying to create a private git repository, or viewing my private directory:

`ERROR Can't get TLF private key for key generation 1`

Here are some log ids: 
`53ed36823e68c729058db71c`
`6f7e99b5fe4dfdc93670c51c`

I also got the following error when trying to send logs, so I'm not sure they got through:

`ERROR Error reading logs: Journalctl exited with an error: exit status 1`

I'm guessing the fix is the same? Ie. please reset my private directory `/keybase/private/savanto/`. Here is the signed request as in the above issues:
```
BEGIN KEYBASE SALTPACK SIGNED MESSAGE. kXR7VktZdyH7rvq v5weRa0zkBDcSah K7pJ8zecn9fhoMr SaR601BhN4Kq0MV KVMfObGVB9w6CaF 6mzwQ4v8Vbz2T5t WZn54hLk75coO0B rPJDenE8FgPS5qc GuQITA7URfnJSw9 Sa0tAcGqsOMfsjS fCFLO7TXtY68QaF dIFX7MqSOSw3G4O GWykkrlPjND2N95 K25rIyiQm3DW3n2 Ez9NCBu2a6VzrAG vpwUfwKEu6BPF3M TrXFe8BgLM5jAOG FA7PSx6rEciW1I6 oTd0tbkm74NVzqO mVzVODbsTRKTcD6 ON6KXf8UvHbJwrB SESYEGdDynMcxm8 Kf32zAU5LWF4D5G 6Mmc0dn2Ofps8NA RY0ES7xMrhQNIfm . END KEYBASE SALTPACK SIGNED MESSAGE.
```

Or please let me know what other info I can get you. Thanks for your time!

**Comment by strib** [comment]
I reset the folder.  Please check it out and close this if everything seems ok.  (Might require a Keybase restart.)

**Comment by savanto** [comment]
Unfortunately it looks like I'm still having the same problem.
```
$ run_keybase
...
$ ls /keybase/private/savanto/
ls: cannot open directory '/keybase/private/savanto/': Input/output error

$ keybase fs ls /keybase/private/savanto/
▶ ERROR Can't get TLF private key for key generation 1

$ keybase git create pass
▶ ERROR Can't get TLF private key for key generation 1

$ keybase git create repo
▶ ERROR Can't get TLF private key for key generation 1
```
I've tried logging out/in as well, with no effect.
I've resolved the issue with logs not sending properly, here's a new log id: `08f64f35bedafdef1c8e191c`

**Comment by strib** [comment]
Ah sorry @savanto, you need to do one more step on your end (not everyone needs it and I didn't notice you needed it before, sorry).  Try

```sh
keybase fs reset /keybase/private/savanto
```

**Comment by savanto** [comment]
@strib That did it. Thanks so much!
