### ISSUE TITLE
Windows intel processor

### ISSUE THREAD

**Issue by terryhik** [keybase/client#15981]
Is there an installer for intel processors? When I was on a win 7notebook with a intel processor it gave the download file of keybase_setup_AMD64.msi. When running it it gives the error the this package will not work on this processor. Is there a seperate build for intel? I did install it on another  notebook with an intel chip.

**Comment by the-exodus** [comment]
There is no separate build, but you most likely have a 32-bit version of Windows installed.

**Comment by terryhik** [comment]
Yes the issue is 32-bit. It is an old system. The file name with the AMD name and the error message threw me off. Is the a description of system requirements on the keybase.io website?

**Comment by terryhik** [comment]
32-bit not supported
