### ISSUE TITLE
Huge amount of animation events cause constant redraw

### ISSUE THREAD

**Issue by the-exodus** [keybase/client#16043]
After hearing complaints about 30-50% cpu usage from people with integrated GPUs I launched a profiling session and found that 75% of the total runtime is spent animating an invisible bouncing box. Every frame of animation causes a few events, and invalidates the layout forcing a regeneration and redraw.

![image](https://user-images.githubusercontent.com/40674427/52753282-49e95700-2ff6-11e9-91be-97689effe37a.png)

![image](https://user-images.githubusercontent.com/40674427/52753453-f75c6a80-2ff6-11e9-9e3a-f37c37fcd69e.png)

**Comment by strib** [comment]
cc: @chrisnojima -- we've been getting reports of lots of CPU usage from the Keybase process on Linux, and I've seen it too.

**Comment by chrisnojima** [comment]
K it's the typing animation. Easy fix

**Comment by chrisnojima** [comment]
PR up
