### ISSUE TITLE
Can't signup for Keybase on Shared System

### ISSUE THREAD

**Issue by Rudi9719** [keybase/client#16049]
[write something useful and descriptive here]

my log id: b525445352e7d1c0a90a2d1c

Trying to issue the command `keybase signup`

my error: 
`▶ ERROR dial unix /run/user/2011/keybase/keybased.sock: connect: permission denied`

**Comment by Rudi9719** [comment]
After some debugging with @the-exodus he concluded that it would be relevant to add that the package was installed via the snap, and that one of the admin accounts has UID 2011 (not my UID of 284828)

**Comment by Rudi9719** [comment]
After having the admin run `keybase ctl stop` I get the following error (and am unable to send my logs)

```Failed to reach user-level systemd daemon.
▶ INFO Starting background server with pid=12715
▶ ERROR open /dev/tty: no such device or address
rudolpg@gaben:~$ keybase log send
This command will send recent keybase log entries to keybase.io
for debugging purposes only.

These logs don’t include your private keys or encrypted data,
but they will include filenames and other metadata keybase normally
can’t read, for debugging purposes.

▶ ERROR open /dev/tty: no such device or address
rudolpg@gaben:~$ ```

**Comment by heronhaye** [comment]
We don't support the Snap distribution, I'm not sure if it's out of date or doesn't play nicely with multiuser systems.

Keybase should work fine running a service for each user (but not for root). Could you try removing the Snap package and installing Keybase from https://keybase.io/docs/the_app/install_linux#ubuntu-debian-and-friends?

**Comment by heronhaye** [comment]
(You probably want to make a paper key backup if you don't already have Keybase on another device)

**Comment by Rudi9719** [comment]
We uninstalled the snap version and installed the .deb (then did an `apt install keybase` to ensure it was up to date) and then the admin ran `run_keybase` and I tried my `keybase signup` again. Even with curling the deb I still get the same error, and it still has the admin's UID in the error output  `▶ ERROR dial unix /run/user/2011/keybase/keybased.sock: connect: permission denied` for signup and `mkdir: cannot create directory ‘/run/user/2011’: Permission denied` for run_keybase (as me)

**Comment by heronhaye** [comment]
Thanks. Our model is that each user has to run their own Keybase service. What happens if you do `run_keybase` as your own user?

**Comment by heronhaye** [comment]
Sorry, I misread your last comment. What is the output if `echo $XDG_RUNTIME_DIR` for you and for the admin?

**Comment by Rudi9719** [comment]
It's `/run/user/2011` for both of us, 2011 is his UID

**Comment by heronhaye** [comment]
That's the problem. Are you using systemd? How are you logged into this system? SSH? `su`?

**Comment by Rudi9719** [comment]
Systemd
Ubuntu 18.04.1
He's su'd into me
I just tried to `run_keybase` as a fresh SSH (as me) and was able to start `keybase signup`
However now he can't run anything and (including `keybase log send`) 
It spits out a huge error
```runtime/cgo: pthread_create failed: Resource temporarily unavailable
runtime/cgo: pthread_create failed: Resource temporarily unavailable
SIGABRT: abort
PC=0x7f8f7b573e97 m=3 sigcode=18446744073709551610

goroutine 0 [idle]:
runtime: unknown pc 0x7f8f7b573e97
stack: frame={sp:0x7f8f73ffe820, fp:0x0} stack=[0x7f8f737ff290,0x7f8f73ffee90)
00007f8f73ffe720:  00007f8f73ffe750  00007f8f73ffe760 
00007f8f73ffe730:  00007f8f7c18d4c8  0000000000000000 
00007f8f73ffe740:  00007f8f00000002  0000000000000000 
00007f8f73ffe750:  00000000ffffffff  0000000000000003 
00007f8f73ffe760:  00007f8f7b53c140  00007f8f7c179ef0 
00007f8f73ffe770:  00007f8f7c17a4c8  0000000000000000 
00007f8f73ffe780:  0000000000000006  00007f8f7c179ef0 
00007f8f73ffe790:  0000000000000000  000000008ff9ac08 
00007f8f73ffe7a0:  00007f8f7c18d4c8  00005632ddb8f038 
00007f8f73ffe7b0:  00005632dc4d2159  00005632df1ad3f0 
00007f8f73ffe7c0:  00000000000000f1  0000000000000011 
00007f8f73ffe7d0:  0000000000000000  00007f8f7bf73ec3 
00007f8f73ffe7e0:  0000000000000005  0000000000000000 
00007f8f73ffe7f0:  0000000000000001  00007f8f7b53c140 
00007f8f73ffe800:  00007f8f73ffea50  00007f8f7bf7b643 
00007f8f73ffe810:  000000000000000a  00007f8f7b6656d9 
00007f8f73ffe820: <0000000000000000  00007f8f7b921703 
00007f8f73ffe830:  00007f8f7b9228b0  0000000000000000 
00007f8f73ffe840:  00007f8f7b9228b0  0000000000000000 
00007f8f73ffe850:  000000000000037f  0000000000000000 
00007f8f73ffe860:  0000000000000000  0000ffff00001fa0 
00007f8f73ffe870:  0000000000000000  0000000000000000 
00007f8f73ffe880:  0000000000000000  0000000000000000 
00007f8f73ffe890:  0000000000000000  0000000000000000 
00007f8f73ffe8a0:  fffffffe7fffffff  ffffffffffffffff 
00007f8f73ffe8b0:  ffffffffffffffff  ffffffffffffffff 
00007f8f73ffe8c0:  ffffffffffffffff  ffffffffffffffff 
00007f8f73ffe8d0:  ffffffffffffffff  ffffffffffffffff 
00007f8f73ffe8e0:  ffffffffffffffff  ffffffffffffffff 
00007f8f73ffe8f0:  ffffffffffffffff  ffffffffffffffff 
00007f8f73ffe900:  ffffffffffffffff  ffffffffffffffff 
00007f8f73ffe910:  ffffffffffffffff  ffffffffffffffff 
runtime: unknown pc 0x7f8f7b573e97
stack: frame={sp:0x7f8f73ffe820, fp:0x0} stack=[0x7f8f737ff290,0x7f8f73ffee90)
00007f8f73ffe720:  00007f8f73ffe750  00007f8f73ffe760 
00007f8f73ffe730:  00007f8f7c18d4c8  0000000000000000 
00007f8f73ffe740:  00007f8f00000002  0000000000000000 
00007f8f73ffe750:  00000000ffffffff  0000000000000003 
00007f8f73ffe760:  00007f8f7b53c140  00007f8f7c179ef0 
00007f8f73ffe770:  00007f8f7c17a4c8  0000000000000000 
00007f8f73ffe780:  0000000000000006  00007f8f7c179ef0 
00007f8f73ffe790:  0000000000000000  000000008ff9ac08 
00007f8f73ffe7a0:  00007f8f7c18d4c8  00005632ddb8f038 
00007f8f73ffe7b0:  00005632dc4d2159  00005632df1ad3f0 
00007f8f73ffe7c0:  00000000000000f1  0000000000000011 
00007f8f73ffe7d0:  0000000000000000  00007f8f7bf73ec3 
00007f8f73ffe7e0:  0000000000000005  0000000000000000 
00007f8f73ffe7f0:  0000000000000001  00007f8f7b53c140 
00007f8f73ffe800:  00007f8f73ffea50  00007f8f7bf7b643 
00007f8f73ffe810:  000000000000000a  00007f8f7b6656d9 
00007f8f73ffe820: <0000000000000000  00007f8f7b921703 
00007f8f73ffe830:  00007f8f7b9228b0  0000000000000000 
00007f8f73ffe840:  00007f8f7b9228b0  0000000000000000 
00007f8f73ffe850:  000000000000037f  0000000000000000 
00007f8f73ffe860:  0000000000000000  0000ffff00001fa0 
00007f8f73ffe870:  0000000000000000  0000000000000000 
00007f8f73ffe880:  0000000000000000  0000000000000000 
00007f8f73ffe890:  0000000000000000  0000000000000000 
00007f8f73ffe8a0:  fffffffe7fffffff  ffffffffffffffff 
00007f8f73ffe8b0:  ffffffffffffffff  ffffffffffffffff 
00007f8f73ffe8c0:  ffffffffffffffff  ffffffffffffffff 
00007f8f73ffe8d0:  ffffffffffffffff  ffffffffffffffff 
00007f8f73ffe8e0:  ffffffffffffffff  ffffffffffffffff 
00007f8f73ffe8f0:  ffffffffffffffff  ffffffffffffffff 
00007f8f73ffe900:  ffffffffffffffff  ffffffffffffffff 
00007f8f73ffe910:  ffffffffffffffff  ffffffffffffffff 

goroutine 1 [runnable, locked to thread]:
runtime.chanrecv(0xc42008c000, 0x0, 0x1, 0x5632daca37ea)
	/usr/local/go/src/runtime/chan.go:415 +0x6a0
runtime.chanrecv1(0xc42008c000, 0x0)
	/usr/local/go/src/runtime/chan.go:400 +0x2b
runtime.gcenable()
	/usr/local/go/src/runtime/mgc.go:217 +0x71
runtime.main()
	/usr/local/go/src/runtime/proc.go:161 +0x126
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2361 +0x1

rax    0x0
rbx    0x7f8f7b921840
rcx    0x7f8f7b573e97
rdx    0x0
rdi    0x2
rsi    0x7f8f73ffe820
rbp    0x5632dc4d2159
rsp    0x7f8f73ffe820
r8     0x0
r9     0x7f8f73ffe820
r10    0x8
r11    0x246
r12    0x5632df1ad3f0
r13    0xf1
r14    0x11
r15    0x0
rip    0x7f8f7b573e97
rflags 0x246
cs     0x33
fs     0x0
gs     0x0```

**Comment by heronhaye** [comment]
Thanks for the quick responses. If you use `su` you aren't "really" logged in as the user from systemd's perspective. An alternative for the admin to act as another user is machinectl, which does set up those environment variables properly.

Okay, so if I'm understanding correctly, keybase works fine for you but not for the admin? Can the admin do things like `keybase id`, or does every Keybase command return that error? What happens if the admin runs `run_keybase`? If that doesn't work, what happens if the admin runs `KEYBASE_SYSTEMD=0 run_keybase`?

**Comment by Rudi9719** [comment]
For all of those commands `keybase id` `run_keybase` and `KEYBASE_SYSTEMD=0 run_keybase` they all return that massive (or similar) errors. I have been able to sign up and create a PGP key as my user. The idea behind this service is we want users to be able to sign up, create PGP keys, and publish them on the keybase keyserver for simplicity. I really appreciate your help!

**Comment by Rudi9719** [comment]
Not sure if this is a related bug, separate bug, or feature but I also noticed there's a file in /keybase called KBFS_NOT_RUNNING and well... yeah! haha

**Comment by heronhaye** [comment]
Hm, that is a problem but I think something to handle after fixing admin's build.

That sounds like a great use of Keybase, hopefully we can get this set up. This is a very strange error I haven't seen before.

If the admin does `journalctl --since=today`, is there anything in there about Keybase? It may be easier to talk with Keybase chat actually, could you message `modalduality` with an attachment of the contents of the journalctl command?

**Comment by heronhaye** [comment]
Also, could you maybe try this for both admin and your own user?
```
systemctl --user set-property keybase.service TasksMax=infinity
systemctl --user set-property kbfs.service TasksMax=infinity
systemctl --user daemon-reload
systemctl --user restart keybase kbfs
```

What happens if you both do run_keybase after that?

**Comment by Rudi9719** [comment]
I messaged you, that didn't seem to effect the user, however the admin still died with the massive error. Even after closing all shells and sessions.

2baa9f0e4a1632cf3a3bb11c is the logs from the user

**Comment by heronhaye** [comment]
(continuing from private chat, where the solution was to kill -9 all keybase processes and restart)

@Rudi9719 so, everything is working ok now for both users? What about KBFS and /keybase for both users?
I'm not totally sure what could have caused that giant stacktrace, it seems something on the system was taking up a ton of resources for some reason. Let us know if you ever have that problem again.

**Comment by Rudi9719** [comment]
Keybase is working for both users, however KBFS/ /keybase are giving an error
`[rudolpg-r@gaben:~]$ ls /keybase 
ls: cannot access '/keybase': Transport endpoint is not connected
~
[rudolpg-r@gaben:~]$ `

**Comment by heronhaye** [comment]
Ok, I think I see the problem. The initial run_keybase with `su` set a bad value for the mountdir for your user. Could you do `keybase config set -d -b mountdir $XDG_RUNTIME_DIR/keybase/kbfs` and then `run_keybase`? Do this in a real SSH shell on your user account.

Then check if `keybase fs ls /keybase/public/<YOUR-USERNAME>/` succeeds (though it might be empty).

If that all works, then does `ls /keybase` work?

**Comment by Rudi9719** [comment]
After running the keybase config command, I was able to do `keybase fs ls` however `ls /keybase` failed. When I tried to do a keybase log send, it also failed with that large error. The output of the `systemctl` command is as follows:
```● kbfs.service - Keybase Filesystem service
   Loaded: loaded (/usr/lib/systemd/user/kbfs.service; disabled; vendor prese
   Active: active (running) since Thu 2019-02-14 21:54:36 UTC; 1min 48s ago
  Process: 19937 ExecStartPre=/bin/sh -c fusermount -uz "$(keybase config get
 Main PID: 19966 (kbfsfuse)
   CGroup: /user.slice/user-2011.slice/user@2011.service/kbfs.service
           └─19966 /usr/bin/kbfsfuse -debug -log-to-file

Feb 14 21:54:35 gaben systemd[19319]: Starting Keybase Filesystem service...
Feb 14 21:54:35 gaben sh[19937]: fusermount: entry for /run/user/2011/keybase
Feb 14 21:54:36 gaben systemd[19319]: Started Keybase Filesystem service.

● keybase-redirector.service - Keybase Root Redirector for KBFS
   Loaded: loaded (/usr/lib/systemd/user/keybase-redirector.service; disabled
   Active: inactive (dead) since Thu 2019-02-14 21:54:35 UTC; 1min 49s ago
  Process: 19956 ExecStart=/usr/bin/keybase-redirector /keybase (code=exited,
  Process: 19936 ExecStartPre=/usr/bin/keybase --use-root-config-file config 
 Main PID: 19956 (code=exited, status=0/SUCCESS)

Feb 14 21:54:35 gaben systemd[19319]: Starting Keybase Root Redirector for KB
Feb 14 21:54:35 gaben keybase[19936]: false
Feb 14 21:54:35 gaben systemd[19319]: Started Keybase Root Redirector for KBF
Feb 14 21:54:35 gaben keybase-redirector[19956]: Mount error, exiting cleanly
lines 1-23

**Comment by heronhaye** [comment]
Is that output from the admin account or from the user account? The giant stacktrace appeared again? For both accounts? Could you paste it once more?

**Comment by the-exodus** [comment]
Try using keybase config set mountdir ${!$XDG_RUNTIME_DIR*}/keybase/kbfs instead, so the env-var doesn't resolve.

**Comment by heronhaye** [comment]
No, do not do that.

**Comment by Rudi9719** [comment]
@the-exodus `-bash: ${!$XDG_RUNTIME_DIR*}/keybase/kbfs: bad substitution` was the result of your command

**Comment by Rudi9719** [comment]
So on both accounts, `keybase fs ls` works, however `ls /keybase` does not. 2ec3aa589e6d9b8bd7236a1c is the log from the non-admin, and 52ada87e8264795230a8361c are the admin logs! One of the commands must have appeased the giant error?

**Comment by heronhaye** [comment]
Cool, we're getting closer...

What is the output of  
``` 
keybase --use-root-config-file ctl redirector --status
```
If it's enabled, try
```
fusermount -uz /keybase
```
I believe that last command needs root. If both succeed, try run_keybase once again and see if /keybase works.

**Comment by Rudi9719** [comment]
The output of the redirector status was `enabled` The admin ran that fusermount command and /keybase now just shows as empty

**Comment by Rudi9719** [comment]
Correction! after Run Keybase it works on them all!

**Comment by heronhaye** [comment]
That's great!

We recently made some changes to make the multiuser system experience better but it clearly still needs some work.

For now, when using Keybase, admins should use `machinectl shell` instead of `su` when logging onto another user account (you could also hardcode the correct XDG_RUNTIME_DIR directly with `su` but that's kind of a hack).

If Keybase is run the first time with that set correctly, KBFS should work out of the box. I believe the /keybase issue was caused by the `kill -9` you did earlier. If it happens again, try the `fusermount -uz /keybase` again.

Now the only problem is that giant stacktrace starting with `runtime/cgo: pthread_create failed: Resource temporarily unavailable`. I'm still unclear on how this happened, and we've never seen reports like that before, but my best guess is something on the system is doing a lot of IO so Keybase is erroring out. If `run_keybase` doesn't fix it then you might have to resort to `kill -9` again (and then `fusermount -uz` to restore /keybase).

If it does happen again please let us know and we can try to investigate further, it definitely shouldn't be happening at all.

Thanks for the report. Feel free to make more issues if you run into any other problems. I think running Keybase for a class on a shared server is a great usecase, hopefully we can make this experience better for you.

**Comment by heronhaye** [comment]
By the way, if you do encounter that runtime/cgo coredump again, send me (`modalduality`) the results of `journalctl --since=today` over Keybase. There is private information in there, so look through it and redact anything you need to first.

**Comment by Rudi9719** [comment]
Groovy! Thanks!
