### ISSUE TITLE
Can't re-request a team invite after leaving team

### ISSUE THREAD

**Issue by NfNitLoop** [keybase/client#16105]
## Steps to Reproduce ##

1) User requests an invite to team.
2) Invite is ignored. (Maybe accidentally.)
3) If the user re-requests an invite, it fails with "▶️ ERROR access already requested (code 2663)" (As expected. This is likely to protect against spamming/abuse.)
4) Admin manually add user to the team.
5) User leaves team.
6) User re-requests invite.
7) "▶️ ERROR access already requested (code 2663)"

## Expected Results ##

After a user has been in a team, he/she should be able to leave the team and later request to join the team again.

## Elaboration ## 
Once a team invite request is ignored (either intentionally or unintentionally) neither the admin nor the other user can recover from that state.

* The admin (AFAICT?) can't list "ignored" invite requests to later accept them via their token.
* The user can't re-request an invite to the team.
* Even if the admin manually adds the user to the team (somehow remembers their username) the bad state will persist if the user ever leaves the team.

**Comment by maxtaco** [comment]
@zapu  can you triage this one

**Comment by zapu** [comment]
@NfNitLoop I can confirm the issue, I've reproduced this today. Thank you for your report, we are on it.

**Comment by zapu** [comment]
@NfNitLoop this should be fixed now, although we did not go and fix the statuses of old team access requests that might be invalid. If there are some specific teams that suffer from this greatly and you'd like to have them fixed, let me know. Thanks!
