### ISSUE TITLE
keybase not ready after run_keybase (in docker container)

### ISSUE THREAD

**Issue by mortenkjarulff** [keybase/client#16125]
Hi,

I am running keybase in a docker container. `keybase oneshot` gave an error that it could not find `/home/keybaser/.config/keybase/keybased.sock`.

I fixed it by this loop:

```
# Start keybase
run_keybase

# Wait for keybase to be ready?
for i in 0 1 2 3 4 5 6 7 8 9 ; do
  if [ -e /home/`whoami`/.config/keybase/keybased.sock ] ; then
    echo "keybase is up" >&2
    break
  fi
  echo "keybase is NOT up $i" >&2
  if [ $i = 9 ] ; then
    echo "keybase did NOT come up" >&2
    exit 1
  fi
  sleep 1
done

# Login
keybase oneshot
``` 

I see the output `keybase is NOT up $i` normally once.

Is this as expected?

log fdee2e77d400c7e5b41ee81c.

All files:
[keybase-docker.tar.gz](https://github.com/keybase/client/files/2882014/keybase-docker.tar.gz)

/Morten

**Comment by heronhaye** [comment]
In general, if using fallback mode of run_keybase when not using systemd, the service will have started but possibly not finished initialization, so you need workarounds like the loop you have here. But it shouldn't take exceedingly long after - one second sounds about right. 

If you are using systemd (see https://github.com/keybase/client/blob/master/packaging/linux/test/README.md#ubuntu-with-systemd for an example for a container that can run keybase with systemd), run_keybase will only exit once the service and kbfs have completed initialization (or have timed out/failed), and commands should succeed immediately right after.

**Comment by mortenkjarulff** [comment]
Ok, fine
