### ISSUE TITLE
Private folders giving input/output error

### ISSUE THREAD

**Issue by fearoffish** [keybase/client#16172]
I don't access my kbfs that often, but whenever I do there's usually an error. This time it's:

`ls: .: Input/output error`
`ERROR Can't get TLF private key for key generation 2`

my log id: a760e93425514f054b6bf41c

**Comment by strib** [comment]
Your folder is very old and the only devices that have access to it are revoked now.  
If you want us to reset your folder, please run this command on a currently-valid keybase device, and substitute the current date and time where indicated:

```
keybase sign -m "<DATE_AND_TIME>: Please reset folder /keybase/private/fearoffish because all the devices that have access have been revoked."
```

and post the results here.

**Comment by fearoffish** [comment]
Thanks:

```
keybase sign -m "Thu 21 Feb 2019 21:06:28 GMT: Please reset folder /keybase/private/fearoffish because all devices that have access have been revoked"
BEGIN KEYBASE SALTPACK SIGNED MESSAGE. kXR7VktZdyH7rvq v5weRa0zkHJeYiw boweaSwXTqPOTXx kd35ds0C1CzXCMH IinOiVoDvvYF1EM XpWZBAdZDiICs4H s5SPqbnVF1SK2ZX FGi7arGHO1nlRHy ksIanTMZRXMCfgc D8PLw3TKAlSqVs5 feNZ38Yeay1Ss3p QVjIbmDRfY3pzPC rE1PVajB7AuM2gO NnFWN2DMX0t7YrQ NlgZWBuKNvn7JuA h1EuvolBZwiM54w firsTPUAmeoL5bX maPNKP0Ss2D3ic4 AgfQZ8Z1ZsnVk7x rclQj2q4l347T7a 4N6KXf7gi7ztCV1 0kiSjCyogA6TRRY tCfDlLJxQ96UVSB BwfF4bkh1JNZfA4 n00. END KEYBASE SALTPACK SIGNED MESSAGE.
```

**Comment by strib** [comment]
Oh oops, looks like we already reset this folder last year.  So all you need to do is run this command locally:

```sh
keybase fs reset /keybase/private/fearoffish
```

And that should restore your access to the new folder.  Sorry, I should have checked that first.

**Comment by fearoffish** [comment]
Unfortunately, after trying that the error is identical.

```
$ keybase fs reset /keybase/private/fearoffish                                                       
This command will reset the entire folder /private/fearoffish
You will completely lose access to all data in that folder
You should probably only do this if someone at Keybase told you to.
Before resetting, contact Keybase admins for a server-side reset by:
  1) Filing an issue at https://github.com/keybase/client; or
  2) Running `keybase log send` and describing the problem.)
Continue resetting the folder? (type 'YES' to confirm): YES
$ keybase fs ls /keybase/private/fearoffish
ls: .: Input/output error
$ ls -hal /keybase/private/fearoffish
ls: .: Input/output error
```

**Comment by fearoffish** [comment]
In case you need it:

```
$ keybase version                                                                                              
Client:  3.0.0-20190205183613+6394d03e6c
Service: 3.0.0-20190205183613+6394d03e6c
```

**Comment by strib** [comment]
Hmm can you do another `keybase log send` and then try restarting Keybase?  Things look good on the server side so I think it should be fine after a restart, but we need to fix whatever error there was after the `reset` too.

**Comment by fearoffish** [comment]
Ah, okay, restarting everything worked. The folder is empty (I wasn't sure) but I get no errors now.

Thanks @strib, much appreciated!

**Comment by strib** [comment]
Cool, the folder is empty because it was reset completely.  But I don't think there was much of anything in the original folder either.

**Comment by fearoffish** [comment]
Nothing I care about anyway :)
