### ISSUE TITLE
Unblock request for keybase.io username zero24

### ISSUE THREAD

**Issue by zero-24** [keybase/client#16218]
Dear Keybase Team,

i was about to register as "zero24" but it seams this username is blocked for some reason? As it does not look like to be used ( https://keybase.io/zero24 ) is it possible to unblock the username, and what can be done on my site to request such an unblock? Is this the right place to post such issues? Please direct me to the right place if it is not here.

Thanks

**Comment by the-exodus** [comment]
There's probably a team named zero24, in which case you can't register a user with the same name.

**Comment by zero-24** [comment]
Thanks for the reponse just double checked the error message:
![image](https://user-images.githubusercontent.com/2596554/53293237-4b720680-37d0-11e9-9308-13a77c4d0c01.png)

Well when the account has been deleted can we free that account name than anyhow?

**Comment by junderw** [comment]
nope.

a deleted account can not be reused on the blockchain.

**Comment by zero-24** [comment]
Ah. Didn't know this is a blockchain. Than thanks for your feedback. Closing.
