### ISSUE TITLE
Is the staging server obsolete?

### ISSUE THREAD

**Issue by PublicStartup** [keybase/client#1624]
Just getting oriented here, reading the source for the first time, poking around the staging server:

https://stage0.keybase.io/

Compare:
https://keybase.io/docs/client/client_architecture
With:
https://stage0.keybase.io/docs/client/client_architecture

"The code lives in the keybase/client-beta GitHub repository."

Except there is no such animal -- "client-beta" does not compute. 404 Not Found, here:

https://github.com/keybase/client-beta

This is expected now, correct? There isn't a beta client any longer, but is the staging server still being kept up-to-date? It would seem not. How can haz remedy?

The non-existent beta client is also referenced here, in the staging server doc prominently linked to from the top of the home page:

https://stage0.keybase.io/docs/cli_kbstage

**Comment by cjb** [comment]
Yeah, it's not being kept up to date.  Where did you see a link to the staging server?

**Comment by burningtree** [comment]
Staging server is easily traceable on Google: 
https://www.google.com/search?q=site:stage0.keybase.io

It would be better for this domain to disallow indexing (robots.txt).

**Comment by maxtaco** [comment]
[We tried](https://stage0.keybase.io/robots.txt).  Is there anything more we should do?

**Comment by anowlcalledjosh** [comment]
@maxtaco Wikipedia says you should include a `User-agent: *` line above, like so:

```
User-agent: *
Disallow: /
```

**Comment by maxtaco** [comment]
thanks fixed!
