### ISSUE TITLE
Bug: It's too white.

### ISSUE THREAD

**Issue by juanandresgs** [keybase/client#16272]
Use it every single day. My team uses teams for work. Love it. Works fairly well.
It's just.. so.. white. Please add a dark theme. Succeed where Slack has so miserably failed. Please give us a dark theme. It's searing my retinas.

Thank you.

**Comment by cmbankester** [comment]
I'm seeing this issue as well (pun intended) in the Electron app. Please allow for theme/color customization, or at the very least provide a dark theme. It's very difficult to focus my eyes on the chat screen, and I've found that, generally speaking, dark-theme UIs are easier to discern.

**Comment by duckydan** [comment]
I would really like to see this too.

**Comment by cecton** [comment]
Maybe a temporary "fix":

Darkens the whole UI a little bit.

I have that plugin on Firefox and it already helps a lot on white websites: https://addons.lightalex.com/darkview

It just dims out the light a little bit.

**Comment by heronhaye** [comment]
Dark mode released in Keybase 4.6.0 under Settings->Display->Appearance.
