### ISSUE TITLE
out of memory

### ISSUE THREAD

**Issue by mortenkjarulff** [keybase/client#16354]
Hi,

I had an AWS lightsail ubuntu (512MB memory). It used to work fine. Then I started to get "out of memory" and the terminal hung.

I created a new instance, and also in this one I get out of memory.

I made this script:
```
#!/bin/sh

run_keybase

while true ; do
  date
  ls /keybase/private/mortenkjarulff
  keybase log send --no-confirm
  sleep 60
done
```
And let it ran for about 10 minutes.

Output attached. There is a log id.
[t.log](https://github.com/keybase/client/files/2923205/t.log)

Hope you can see something.

/Morten

**Comment by strib** [comment]
@mortenkjarulff do you know what process was taking up all the memory?

Logs:

6234bc9fd99a46929f6e6c1c
748e30c5d880008a64b21d1c
8b682139cc04fb63470ce61c
f0b7603bd426938531f4821c
b4d1831e5b166ba8c69e6e1c
4b04c4f08285147e2c9bd51c
fb7e87c2e1e7e295a490351c

**Comment by mortenkjarulff** [comment]
Not sure how I can find out? Last time I tried, `top` hung.

**Comment by strib** [comment]
In your loop, you can run something like `ps aux --sort -rss` to print the sorted mem usage of all processes periodically.

**Comment by strib** [comment]
Maybe all check your system logs to see if the out-of-memory killer is targeting anything in particular?

**Comment by mortenkjarulff** [comment]
Each time I try to recreate, it works fine. When I think everything is ok, it suddenly hang.

:(
