### ISSUE TITLE
Can't get TLF private key for key generation 1

### ISSUE THREAD

**Issue by GertSchepens** [keybase/client#16398]
Hi!
I'm getting "error code 218 - Can't get TLF private key for key generation 1" when trying to create a new repo.
And "an unexplained error has occured" when trying to open my private folder (amongst others).

I saw earlier posts referring to this being caused by deleting my early keybase devices & I definitely had the misfortune of having to do that.

Can you help me out?
Thanks!

**Comment by strib** [comment]
If you do a `keybase log send`, and post the resulting ID here, I can take a look.

**Comment by GertSchepens** [comment]
Thanks for the very fast reaction!

> gert@Benedikt:~$ keybase log send
> This command will send recent keybase log entries to keybase.io
> for debugging purposes only.
> 
> These logs don’t include your private keys or encrypted data,
> but they will include filenames and other metadata keybase normally
> can’t read, for debugging purposes.
> 
> Continue sending logs to keybase.io? (type 'YES' to confirm): yes
> Enter feedback (or <Enter> to send): regarding https://github.com/keybase/client
> /issues/16398
> More feedback (or press <Enter> when done): 
> Hint: You are currently not seeing messages from other users and the system.
>       Users in the 'systemd-journal' group can see all messages. Pass -q to
>       turn off this notice.
> No journal files were opened due to insufficient permissions.
> ▶ ERROR Error reading logs: Journalctl exited with an error: exit status 1
> 
> 
> ------------
> Success! Your log ID is:
> 
>   05b6788b95becdbfeb1dce1c
> 
> Here's a URL to submit new bug reports containing this ID:
> 
>   https://github.com/keybase/client/issues/new?body=[write%20something%20useful%20and%20descriptive%20here]%0A%0Amy%20log%20id:%2005b6788b95becdbfeb1dce1c
> 
> Thanks!
> ------------

**Comment by strib** [comment]
Yes, it seems like you've revoked all the devices that have had access to that folder.  
If you want us to reset your folder, please run this command on a currently-valid keybase device, and substitute the current date and time where indicated:

```
keybase sign -m "<DATE_AND_TIME>: Please reset folder /keybase/private/gertschepens because all the devices that have access have been revoked."
```

and post the results here.

**Comment by GertSchepens** [comment]
Again, thanks for the swift support!

C:\Users\gert>keybase sign -m "05/03/2019 - 18:52: Please reset folder /keybase/private/gertschepens because all the devices that have access have been revoked."

BEGIN KEYBASE SALTPACK SIGNED MESSAGE. kXR7VktZdyH7rvq v5weRa0zkLl2OX6 2HWHVoRNNhFKcSb 6phCb16gwoGEc42 JVTjd1QuDxTR3SW 4sQBu5PWK3nj5xQ zyTOOZk6aMSPpDd hepF2hFGUmhjd9f QAxPQEP3l9IQzrd TvEIicIzkyakoVB 1HgI6AV65z8QzlD ImBYR3xkvgdETsk skb8rfVtH9inGhE l5N2yYRy1g8anxJ 696UOO2VbByGCPC MOpuQKDVGkyShnj CHkYvgAVbq49opC RftRbFrFA9SaJNr kd0RgYehA6SkvTz sWNU90lZCulTrNd ANo2Lvhn5JaNDLB wX7MWE0Po1DGxzH i6aSrK3SAItsrF9 t1GFjoZG7lhFRm. END KEYBASE SALTPACK SIGNED MESSAGE.

**Comment by strib** [comment]
I reset the folder.  Please check it out and close this if everything seems ok.  (Might require a Keybase restart.)

**Comment by GertSchepens** [comment]
It's all working now! Thanks for the awesome support!
Making a point of not having simultaneous device crashes anymore 🙈
