### ISSUE TITLE
Unable to log in (User has been deleted?)

### ISSUE THREAD

**Issue by potato4444** [keybase/client#16406]
I am unable to log into my account "potato44". When I try I get  
"There was an error provisioning  
User has been deleted." instead of asking for the rest of my login details. I have not made a request for my account to be deleted.  

my log id: d316c3d8fdd43739b6998e1c

**Comment by junderw** [comment]
did you leave your PC or phone with keybase logged in and unattended with someone?

there is a button to delete your account. maybe a child clicked it.

**Comment by potato4444** [comment]
@junderw Nope, my laptop has been on my person (and most of the time off) since I last used Keybase. The only other device attached to the account was a paper key.

**Comment by potato4444** [comment]
Was there some kind of event that caused a large number of accounts to be deleted? I noticed that I can no longer find several accounts that were in a team with me via the website.

**Comment by shadow87qft** [comment]
my old account got deleted too, together with at least 10 of the people i followed
