### ISSUE TITLE
Cannot Push to Personal Repository

### ISSUE THREAD

**Issue by DonaldKBrown** [keybase/client#16420]
After trying to push an updated commit to a personal repository, I got errors about how data is not available offline and how a folder (which is not in my project) is not empty so it cannot be removed.

my log id: 98d813947044b48a139dc31c

```
donald@noreallyitis:~/homesite$ git push
Initializing Keybase... done.
Syncing with Keybase... done.
git-remote-keybase error: (1) Directory directory-name-here is not empty and can't be removed
```

Similar issue when trying to clone the repository on my local machine rather than the server the project is  running on.

Log ID on local machine: f3d1dde37be98ff5317b7b1c

```
donald@yavin-iv:~$ git clone keybase://private/donaldkbrown/project_target
Cloning into 'project_target'...
Initializing Keybase... done.
Syncing with Keybase... done.
git-remote-keybase error: (1) Directory directory-name-here is not empty and can't be removed
```

It references the same directory on both machines.

**Comment by strib** [comment]
This is a symptom of a really old bug -- you probably deleted a repo that you created back when we first released git.

You can clean the deleted repo up manually if you have by going to `/keybase/private/donaldkbrown/.kbfs_git/.kbfs_deleted_repos`, and renaming the problematic directory to something else, say `reponame.bkp` or something.  Let me know if that fixes it.

**Comment by DonaldKBrown** [comment]
Thank you, @strib . I didn't remember that ancient repo. Renaming it there fixed my issue.
