### ISSUE TITLE
High CPU usage in Chat tab

### ISSUE THREAD

**Issue by mzabaluev** [keybase/client#16442]
With `keybase-3.0.0.20190205202117.6394d03e6c-1.x86_64` on Fedora Linux, I see constant 20-30% CPU load caused by Keybase when the Chat tab is selected. In other tabs, Keybase is more quiescent.

**Comment by Avamander** [comment]
Same issue, Keybase takes a lot of CPU when just in foreground.

**Comment by heronhaye** [comment]
Closing this out since we did a stable release that should fix this. Please make another issue if you still run into high CPU usage, thanks!
