### ISSUE TITLE
Stellar transactions with multiple operations aren't displayed, but cause undismissable notification badge

### ISSUE THREAD

**Issue by rainyday** [keybase/client#16469]
I recently had the Keybase app tell me I have 3 unread notifications in my wallet, but upon looking in Keybase there appeared to be no new transactions. As a result I still have unread notifications on the app that cannot be dismissed since there's nothing to actually read.

Investigating further (using another wallet app) I found that there actually have been some new transactions on my wallet: a couple transaction fee refunds from stellarx and an inflation bonus from lumenaut which aren't showing up in the keybase app. I tried to view them using the `keybase wallet details` command but get the error: `ERROR error summarizing payment: <transaction id> transaction not simple payment: transaction had multiple operations (100)`

I'm guessing the Keybase app is able to tell there are new transactions but is not able to display them and that's what's causing my undismissable notification alerts.

**Comment by maxtaco** [comment]
cc @patrickxb

**Comment by patrickxb** [comment]
The next release will show them.  

The badging is my bug on the server.  I'll fix it momentarily as our release has been delayed for unrelated reasons.

**Comment by patrickxb** [comment]
@rainyday badging should be fixed now.
