### ISSUE TITLE
Rsync hangs after transfer to KBFS

### ISSUE THREAD

**Issue by 501st-alpha1** [keybase/client#16467]
I'm trying to sync a directory to KBFS, and while it was making progress before, it has since stopped.  The directory contains approximately 700 files, the total size of which should be under 100 MB.

Here's the form of an `rsync` command I'm using to sync:

```
rsync --progress --recursive --partial --partial-dir=.rsync-partial /mnt/data/[snip] /keybase/private/501st_alpha1/[snip]
```

and here is the output that now appears when I run it on a specific file:

```
sending incremental file list
17c/fcb/SHA256E-s302988--495fae9ac176879ebede1b4bb5ab9f4e57c06414d8c6828d7169c8b12e49dc46.pdf/SHA256E-s302988--495fae9ac176879ebede1b4bb5ab9f4e57c06414d8c6828d7169c8b12e49dc46.pdf
        302,988 100%  642.06kB/s    0:00:00 (xfr#1, to-chk=0/5)
```

Even though the progress bar shows 100% (and is animated before that when I watch it), it hangs there and doesn't finish.  I even left one running overnight, and that didn't help.  I also tried restarting the Keybase service, and that didn't seem to help either.

My log ID is `e6e1bf01c5bbbf0b71c4991c` (sent immediately after attempting and then canceling one such `rsync` command), but one thing I noticed earlier was this line:

```
2019-03-06T19:09:03.043213-08:00 ▶ [DEBU kbfs(FBO df40b1c5) folder_branch_ops.go:7383] 25046c8 Background sync triggered: 199 dirty files, 892 dir ops in batch [tags:FBOID=UogffUclR9G2NVPeJSz-tg]
```

The `dirty files` number goes up every time I trigger the `rsync` command, even for the same file.

How can I fix this?

**Comment by strib** [comment]
Hmm.  Yeah, the important error in the log is this:

```
SyncAll done: Server: block does not exist 
```

The `keybase log send` only sends a portion of your logs, and it's not enough to figure out the root cause of this.  Would you be willing to send more?  If so, please do something like this:

```
tar -czf /keybase/private/strib,501st_alpha1/client-16467.tgz $HOME/.cache/keybase/keybase.kbfs*
```

You said you restarted the "Keybase service" -- what did you do exactly?  A full `run_keybase`, or did you just do a restart of keybase.service?  If the latter, try doing a full restart via `run_keybase`, which will also restart KBFS.

**Comment by 501st-alpha1** [comment]
> You said you restarted the "Keybase service" -- what did you do exactly? A full `run_keybase`, or did you just do a restart of keybase.service? If the latter, try doing a full restart via `run_keybase`, which will also restart KBFS.

I did `keybase ctl restart`, which I assume is the latter.

Just now tried `run_keybase`, and that seems to have fixed the issue, thanks!

Let me know if the rest of the logs would still be helpful; otherwise feel free to close this issue.

**Comment by strib** [comment]
Ah, `keybase ctl restart` just restarts the `keybase` process, not the `kbfsfuse` process.

The rest of the logs would still be useful if you're willing to share, I'd like to try to fix whatever the underlying bug is.

**Comment by 501st-alpha1** [comment]
Sent.  (Had to split the command into two steps though, because tar complained when the log was written to as it was reading it, since I was trying to save the archive to KBFS, haha.)

**Comment by strib** [comment]
Thanks!  Unfortunately the logs rolled over and lost whatever caused the original bug, so I'll have to keep hoping for a reproduction from someone else.  Thanks for your patience and help!
