### ISSUE TITLE
Not able to interact with Team. Conflicting UI messages

### ISSUE THREAD

**Issue by todd-davenport** [keybase/client#16472]
I was recently added to a Team. I can't see other members or interact with them.

```
$ keybase team request-access <redacted>
▶ ERROR You are already a member of this team (code 2665)
```
https://www.dropbox.com/s/2v9y2hz7sowpqhr/Screen%20Shot%202019-03-07%20at%206.41.36%20AM.png?dl=0

https://www.dropbox.com/s/5ryvf3rf3tlv708/Screen%20Shot%202019-03-07%20at%206.41.19%20AM.png?dl=0

https://www.dropbox.com/s/b28r22p9pid8kfp/Screen%20Shot%202019-03-07%20at%206.45.14%20AM.png?dl=0

my log id: 7a47dc856e9dd3f31deb581c

**Comment by todd-davenport** [comment]
This resolved itself sometime in the last 2 hours. Hopefully this report is useful for future UX improvements. I'm closing it now, but I would be happy to provide additional information if you would like.

**Comment by maxtaco** [comment]
We'll take a look, thanks for the report.
