### ISSUE TITLE
keybase login doesn't show all keys

### ISSUE THREAD

**Issue by ScottyTM** [keybase/client#1651]
When trying to login to keybase I select:

(4) Use GPG

(1) Keybase can use GPG commands to sign the installation.

then keybase only shows 2 secret keys (one of them twice), but not my new 4096 bit RSA key, which shows up when I run gpg --fingerprint -K manually.

**Comment by maxtaco** [comment]
Thanks so much for the bug report.  Sounds like a bug in our parsing the results of 

```
gpg -K --with-colons
```

Can you send the output of that command?  It's nothing that's not publicly available.  But you can always send it to me via https://keybase.io/max if that's preferable.

**Comment by ScottyTM** [comment]
Sorry, this has been a local issue. After kicking my gnupg installation around a bit everything is now working.
