### ISSUE TITLE
KBFS: Unable to open on Finder due to permission errors

### ISSUE THREAD

**Issue by arunsathiya** [keybase/client#16512]
I am seeing an odd one here. I see this error when I open Keybase on Mac's Finder app:

`The folder “Keybase (arunsathiya)” can’t be opened because you don’t have permission to see its contents.`

I don't remember this happening a few months ago. I did not open Keybase on Finder over the past few months. I also updated to Mojave during this time. Did that cause an issue?

my log id: 00cbae65e06e4e3cee1b2e1c

**Comment by strib** [comment]
@arunsathiya it seems like your computer is having resource issues.  Keybase is getting errors like this from the operating system: "too many open files".  This starts immediately when our process starts up, so I don't think it's something Keybase is doing; seems like at the time, your operating system was out of file descriptors.

If it's still happening, please update to the latest Keybase release (released Friday) just in case it helps.

**Comment by arunsathiya** [comment]
Can I ask where I can download the new version, please? I am not seeing the option to fetch the new version from the app menu or on the Mac menu at the top. 🤔 Thanks.

**Comment by strib** [comment]
You can run `keybase update check`.

**Comment by arunsathiya** [comment]
Looks like I am on the latest version, and Finder opens just fine now. I shall close this issue. 👍🏽 Thank you for your help.

**Comment by MattWeatherford** [comment]
I am having this problem on OSX 10.13.6 with latest Keybase
Version 5.6.2-20210202191343+d72cc00cd3 (5.6.2-20210202191343+d72cc00cd3)

I check the "I understand that a closed-source kernel extension (FUSE for macOS) will be installed.
I click "Yes, enable" and get a spinning circle, which does complete. But the message  and Yes, Enable never goes away.

are there debug logs I Can provide?

**Comment by jiy0** [comment]
> I am having this problem on OSX 10.13.6 with latest Keybase
> Version 5.6.2-20210202191343+d72cc00cd3 (5.6.2-20210202191343+d72cc00cd3)
> 
> I check the "I understand that a closed-source kernel extension (FUSE for macOS) will be installed.
> I click "Yes, enable" and get a spinning circle, which does complete. But the message and Yes, Enable never goes away.
> 
> are there debug logs I Can provide?

I’m having the same exact problem on the same OSX version. 

Tried the tips&tricks posted before but non of them worked.

Have you found a solution yet @MattWeatherford?

**Comment by bryanlandia** [comment]
I noticed somewhere in the installation logs a lot that read "Installed for
Mac OS 10.15".  I think the latest version may just not be compatible.

**Comment by jiy0** [comment]
> I noticed somewhere in the installation logs a lot that read "Installed for Mac OS 10.15". I think the latest version may just not be compatible.
> […](#)

Thanks Bryan. Do you if there’s still a dmg file for older version available that’s compatible with my OSX version?

**Comment by bryanlandia** [comment]
I haven't found one.  You can find old versions to compile from source but
haven't had time to try yet.

**Comment by lipengyuan1994** [comment]
I keep seeing this error after each time the Mac OS updates

**Comment by meffovic** [comment]
I'm having the same issue - it says i don't have permission to view the keybase folder content. Is there any way around this?
