### ISSUE TITLE
Exported pgp keys have an invalid signature structure

### ISSUE THREAD

**Issue by far-blue** [keybase/client#16518]
I was trying out the pgp related commands on the cli and used `keybase pgp pull` to import pgp public keys into my gpg keychain but find that gpg is complaining about them with the following:

`bad data signature from key <key>: Wrong key usage (0x19, 0x2)`

This appears to be related to this question: https://superuser.com/questions/1344523/how-to-resolve-the-error-gpg-bad-data-signature-from-key-wrong-key-usage-0x1

The suggestion is that each 0x19 signature entry should have a 0x18 signature entry matching it which is not the case for keys pulled from keybase.

**Comment by maxtaco** [comment]
cc @pzduniak  can you help out?

**Comment by pzduniak** [comment]
@far-blue 

Thank you for your report, what happened here is that someone has published their old non-modern-GPG2-compliant key on their profile, so this isn't exactly an issue with our client. I will create a pullreq that will change the severity of errors during the gpg import commands (and thus allow you to pull all keys _except_ that broken one), so that hopefully should fix your issue.

Out of curiosity, whose keys were you trying to fetch? I tried to reproduce it on my test account by following all the people you do and failed - was this on another account than https://keybase.io/farblue? Once I know that I will be able to figure out whether my fix is effective.

**Comment by far-blue** [comment]
Hello,

Sorry for the delay in replying,

Yes, this is with my farblue account. These are the users and key ids my gpg version is moaning about:
```
gpg: bad data signature from key A1F6C400E4DC297D: Wrong key usage (0x19, 0x2)
pub   rsa4096 2014-12-08 [SCEA]
      4230339C1023B77C5729B94787A2C5FC58A19E9A
uid           [ unknown] keybase.io/rowan_m <rowan_m@keybase.io>
sub   rsa2048 2014-12-08 [S] [expires: 2022-12-06]
sub   rsa2048 2014-12-08 [E] [expires: 2022-12-06]

gpg: bad data signature from key 2E02375479E8CBDB: Wrong key usage (0x19, 0x2)
pub   rsa4096 2015-02-06 [SCEA]
      B83E9B58DC5EE329B41142F2D938191317D6C872
uid           [ unknown] keybase.io/flyingbuddha <flyingbuddha@keybase.io>
sub   rsa2048 2015-02-06 [S] [expires: 2023-02-04]
sub   rsa2048 2015-02-06 [E] [expires: 2023-02-04]

gpg: bad data signature from key B30530F0A5A54799: Wrong key usage (0x19, 0x2)
pub   rsa4096 2016-10-30 [SC]
      C83A17217B3E3DE223F2F4C6A1F00911A32FD4DD
uid           [ unknown] Andre Cesar de Souza Medeiros <andre@staltz.com>
uid           [ unknown] Andre Cesar de Souza Medeiros <andre.medeiros@futurice.com>
sub   rsa2048 2016-10-30 [E] [expires: 2024-10-28]
sub   rsa2048 2016-10-30 [SA] [expires: 2024-10-28]

gpg: bad data signature from key EB20CE5B78658D8C: Wrong key usage (0x19, 0x2)
pub   rsa4096 2014-09-27 [SCEA]
      FAA64F09564E48E42E6704AFCA12304BF9A8D609
uid           [ unknown] keybase.io/diptanu <diptanu@keybase.io>
sub   rsa2048 2014-09-27 [S] [expires: 2022-09-25]
sub   rsa2048 2014-09-27 [E] [expires: 2022-09-25]

gpg: bad data signature from key E90F97ECE99FFC10: Wrong key usage (0x19, 0x2)
pub   rsa4096 2016-01-26 [SC]
      78BA604B30AAB4DF818DBB6401E34D93E69D9BDA
uid           [ unknown] Troy Hunt <troyhunt@hotmail.com>
sub   rsa2048 2016-01-26 [E] [expires: 2024-01-24]
sub   rsa2048 2016-01-26 [SA] [expires: 2024-01-24]
```

I can't be sure whether any of these keys were created using keybase or simply imported or linked but I'm pretty sure 'flyingbuddha' generated his as part of setting up keybase.

As a point of note, the import of the keys from keybase into gpg is successful and doesn't crash. As you say, there's a good chance these keys were simply generated incorrectly and nothing to do with keybase but thank you for investigating anyhow!

Robert
