### ISSUE TITLE
Emojis set to Skin Tone 6 do not render

### ISSUE THREAD

**Issue by robrigo** [keybase/client#16626]
I can't use skin tone 6, it either renders text if I am adding it inline, or yellow if I submit the emoji directly to chat.

<img width="283" alt="Screen Shot 2019-03-18 at 12 51 28 PM" src="https://user-images.githubusercontent.com/590263/54548221-cb2d6400-497d-11e9-8de3-4c7ed3a20803.png">

Keybase Version 3.1.2-20190312142912+4c383e6a53 (3.1.2-20190312142912+4c383e6a53)

**Comment by SethArchambault** [comment]
I'm seeing this issue too!

**Comment by buoyad** [comment]
Thanks for the report! I can repro this in the latest version. I made a ticket for this on our internal tracker, we'll look at it soon.

**Comment by robrigo** [comment]
Thank you @buoyad !

**Comment by thebearjew** [comment]
@robrigo This was just fixed by @buoyad 🎉
You'll see it soon 😄
