### ISSUE TITLE
Links are not opened in my default browser

### ISSUE THREAD

**Issue by rcorre** [keybase/client#16670]
If I click on a link in `keybase-gui`it opens it in `firefox`. However, `qutebrowser` is set as my default browser:

```
[rcorre@midova ~]$ xdg-settings get default-url-scheme-handler http
qutebrowser.desktop
[rcorre@midova ~]$ xdg-settings get default-url-scheme-handler https
qutebrowser.desktop
[rcorre@midova ~]$ xdg-settings get default-web-browser
qutebrowser.desktop
[rcorre@midova ~]$ xdg-settings check default-web-browser qutebrowser.desktop
yes
[rcorre@midova ~]$ echo $BROWSER
qutebrowser
[rcorre@midova ~]$ xdg-mime query default text/html
qutebrowser.desktop
```

It seems that keybase-gui doesn't respect `$BROWSER` or the XDG default browser.

**Comment by holycleugh** [comment]
If you add `BROWSER=qutebrowser` to `~/.config/keybase/keybase.env`, and restart all Keybase services, does it work?

**Comment by heronhaye** [comment]
Try adding `BROWSER=qutebrowser` to `~/.config/keybase/keybase.env`. If you restart all keybase services, is the setting now respected?

**Comment by rcorre** [comment]
@heronhaye no luck:

```
[rcorre@midova ~]$ cat ~/.config/keybase/keybase.env
BROWSER=qutebrowser
```

Still opens links in firefox, even after rebooting.

**Comment by heronhaye** [comment]
hi @rcorre,
You mentioned `keybase-gui`, so I'm assuming you're using the Arch community package. Do you have a file `~/.config/keybase/keybase.autogen.env`? And does it contain a line `XDG_CONFIG_HOME=`?
If yes to both, you should be able to put `XDG_CONFIG_HOME=/home/rcorre/.config` in `~/.config/keybase/keybase.env`, restart keybase, and it should use qutebrowser (you can remove the `BROWSER` line too).

In the next release, that will be unnecessary. Let me know if this doesn't work, thanks.

**Comment by rcorre** [comment]
I am using the Arch community package, but I don't have `~/.config/keybase/keybase.autogen.env`.

```
[rodencor@karminac ~]$ ls ~/.config/keybase/
autostart_created  config.json  device_clone.json  secretkeys.rcorre.mpack
```

config.json contains

```
{
    "current_user": "rcorre",
    "mountdir": "/home/rodencor/.local/share/keybase/fs/",
    "mountdirdefault": "/run/user/1000/keybase/kbfs",
    "users": {
        "rcorre": {
             ...
        }
    }
}
```

**Comment by heronhaye** [comment]
Could you try this anyway?
>You should be able to put `XDG_CONFIG_HOME=/home/rodencor/.config` in `~/.config/keybase/keybase.env`, restart keybase, and it should use qutebrowser (you can remove the BROWSER line too).

**Comment by rcorre** [comment]
```
[rcorre@midova ~]$ cat ~/.config/keybase/keybase.env
BROWSER=qutebrowser
```

Still no luck. I also tried bypassing the `keybase-gui` service that comes with the Arch package and starting it directly:

```
BROWSER=qutebrowser electron /usr/share/keybase-app/
```

**Comment by heronhaye** [comment]
Ok, it looks like the linked PR was another issue around this but yours is a different one.

So if you remove `~/.config/keybase/keybase.env`, run `systemctl --user stop keybase.gui` and then `electron /usr/share/keybase-app/` to start it outside of systemd, you're saying that it still opens up in Firefox?

What is the result of `echo $XDG_CACHE_HOME`? And do other applications respect the default qutebrowser setting?

**Comment by rcorre** [comment]
> So if you remove ~/.config/keybase/keybase.env, run systemctl --user stop keybase.gui and then electron /usr/share/keybase-app/ to start it outside of systemd, you're saying that it still opens up in Firefox?

>  And do other applications respect the default qutebrowser setting?

I thought so, but I just tried `xdg-open http://example.com` and it uses firefox (yet `xdg-open some-file.html` uses `qutebrowser`). Closing this, since it does indeed seem to be an issue with my config, but I'll update it for future viewers if I figure anything out. Thanks!

**Comment by laduygaga** [comment]
put to ~/.config/mineapps.list this:

[Default Applications]
x-scheme-handler/mailto=org.qutebrowser.qutebrowser.desktop
x-scheme-handler/http=org.qutebrowser.qutebrowser.desktop
x-scheme-handler/https=org.qutebrowser.qutebrowser.desktop

**Comment by rcorre** [comment]
Thanks @laduygaga, that worked!
