### ISSUE TITLE
Does Keybase client interact with the Bitcoin blockchain?

### ISSUE THREAD

**Issue by sbsomuncuoglu** [keybase/client#16673]
We know that Keybase server signs and publishes the root of the global Merkle Tree into the Bitcoin blockchain to prevent forking attacks.([https://keybase.io/docs/server_security/merkle_root_in_bitcoin_blockchain](url))

I went through the client source code and couldn't find anything related to reading from blockchain. If client interacts with blockchain, could you please tell me where is it in the source code? If it doesn't, I'm wondering why doesn't client make use of this extra security feature. 

We can still check the Bitcoin blockchain externally to verify that the server isn't lying about the state of the global Merkle tree. However, wouldn't it be possible to integrate this feature into the client?

**Comment by maxtaco** [comment]
You are exactly right, we haven't done the reader integration yet. I think the first thing to try is some sort of SPV, but we don't want to require clients to have a full copy of the bitcoin blockchain, especially mobile clients.

**Comment by pickhardt** [comment]
I'm curious, is this still unimplemented? I did a code search and didn't see anything but failure to find something doesn't mean it's not there, just that I didn't find it.
