### ISSUE TITLE
android client bloating

### ISSUE THREAD

**Issue by shadow87qft** [keybase/client#16768]
would be great if you guys can add a function to clear the cache files and the app log from the android client since those files bloat the app size a lot. especially the encrypted cache files in
\data\data\io.keybase.ossifrage\files\cache\keybase
as well as the logs in
\data\data\io.keybase.ossifrage\files
the log files were already 48MB in size after only a few minutes of chatting

**Comment by heronhaye** [comment]
Next release will limit log files to 16MB on mobile: https://github.com/keybase/client/pull/16624/files.
