### ISSUE TITLE
Sign-In Hangs Forever

### ISSUE THREAD

**Issue by M-Pixel** [keybase/client#16767]
I accidentally logged out (as in #7721 and #9115 ). However, after pressing "Sign Out", the GUI did not revert to a sign-in screen. Instead the various sections of the app showed skulls-and-crossbones, or other errors. After signing out, I'm unable to sign back in.  Terminal and GUI both hang for hours on end, without any errors displayed.  I've tried reinstalling.

my log id: 3cd0d421f6b0dbaeaab16c1c

**Comment by maxtaco** [comment]
Your app wound up in a broken state of some sort that I haven't seen. Do your other devices still work?  What if you kill the app and start it again?

**Comment by M-Pixel** [comment]
Yes, and in addition to closing and reopening the app, I've uninstalled and reinstalled it, and the issue persists.

**Comment by maxtaco** [comment]
Ok, we'll look.

**Comment by mlsteele** [comment]
@M-Pixel could you do me favor and quit the app, launch it but don't touch anything for about a minute, and then send a log? The log you sent before doesn't include when the app started up so a clean one would be helpful.

**Comment by M-Pixel** [comment]
This was fixed after updating to the latest version.
