### ISSUE TITLE
Sign Out from desktop client only partially logs out

### ISSUE THREAD

**Issue by M-Pixel** [keybase/client#16766]
Keybase GUI Version: 3.1.2-20190312073438+4c383e6a53

Today, I accidentally logged out (as in #7721 and #9115).  However, after pressing "Sign Out", the GUI did not revert to a sign-in screen.  Instead the various sections of the app showed skulls-and-crossbones, or other errors.

Log `3835efd7e65458502857321c`, however I don't believe it will be useful because I captured the log after closing the GUI.  I cannot sign back in to attempt a reproduction because of some other bug.

**Comment by maxtaco** [comment]
I think this issue and the next one you filed are related, let's close this one and use that one. #16767 

There's some sort of broken state you wound up in .
