### ISSUE TITLE
android client bloat

### ISSUE THREAD

**Issue by shadow87qft** [keybase/client#16826]
related to issue #16768 
after checking the app data folder of the android client i found that there are 2 folders within the files\.cache\keybase folder that get incredibly huge very fast
are the files inside [uploadedfulls] and [uploadedpreviews] really still required after the related file was uploaded successfully or could those maybe get automatically deleted?
or is there a way to include the files\.cache\keybase folder in the delete cache function from the app info page?

**Comment by shadow87qft** [comment]
and does the size limit for the log files mean that the size of all log files together will be 16MB or will there just be more but smaller log files?
asking because i just deleted 4 128MB log files from the .cache folder...

**Comment by maxtaco** [comment]
cc @heronhaye on this

**Comment by heronhaye** [comment]
It means total 16mb log files, but a release with that patch is not out yet.
cc @joshblum for other cache questions

**Comment by joshblum** [comment]
@shadow87qft not deleting files in `uploadedfulls`/`uploadedpreviews` was an oversight thanks for reporting! Will be fixed soon. In the meantime if you need to save some space go to `menu > advanced > db nuke` to clear local caches (not including the uploaded files or logs)

**Comment by joshblum** [comment]
@shazow i misspoke before, the uploadedfulls/previews are used as a cache for viewing the image after you upload it so we can't delete it immediately. My match will limit the total number of files that can exist and make sure they are delete if you explicitly clear caches

**Comment by joshblum** [comment]
@shadow87qft fix will be available in the next release which is coming soon
