### ISSUE TITLE
KBFS files not uploading to server

### ISSUE THREAD

**Issue by bs78ta** [keybase/client#16849]
Keybase GUI Version: 3.1.2-20190312073438+4c383e6a53 Running Keybase on windows 7 64 bit. The files I am putting in my keybase folder are not uploading to server. It will show them encrypting and uploading but the process never finishes. The timer will count down fron 8 sec to 4 and then just restarts again at 8. Never finishes the loop. Thanks

**Comment by strib** [comment]
If you do a `keybase log send`, and post the resulting ID here, I can take a look.

**Comment by bs78ta** [comment]
6b4977d7b870240eb3911c

**Comment by bs78ta** [comment]
Anything unusual stand out????  @strib

**Comment by strib** [comment]
Sorry for the delay.  You are stuck in "conflict mode", which means at some point in the past you tried to write some data to the folder at the same time as some other user/device, and our code that is supposed to resolve the conflict automatically hit a bug and failed in some way.

It would be helpful if you can go into that folder on the command prompt and run this command for me (you haven't associated your Keybase account with this github account, so below I'm using `<YOUR_KB_USER>` in place of your real Keybase account name):

```sh
copy .kbfs_status K:\private\strib,<YOUR_KB_USER>\status.json
```

After you do that, you can get out of this conflict mode with the following steps:

1. Whatever data you've put into the folder, but which hasn't uploaded yet, make sure you save a copy of it on your local hard drive (if you don't already have one).
2. Completely quit the Keybase app, so the mount goes away.
3. Go into the directory `%APPDATA%\Local\Keybase\kbfs_journal\v1\` and rename the directory `01204c9edc616ba343b930c42f69b76a01aa-f6d8ca2141e54884` to something else, like `f6d8ca2141e54884.bkp`.
4. Restart Keybase.

Now you should be synced back up to the server's view of the folder, and you can re-upload your data.

Sorry for the bad experience, we're actively working on fixing this.

**Comment by bs78ta** [comment]
I could not get the status Command line Kept saying
 no such file. But Your solution for the conflict mode worked perfectly. Thank you very much.

**Comment by bs78ta** [comment]
Not related to same problem but I get this on win7. Any ideas why it comes up red on Keybase drive. 
![Untitled](https://user-images.githubusercontent.com/32412352/55647083-6312b680-57a2-11e9-8d31-408f0e88511f.png)

**Comment by strib** [comment]
@bs78ta glad your conflict problem is worked out.  We have some issues reporting quotas right now.  What does the command `keybase fs quota` print for you on the command prompt?  I'm guessing it's showing a negative number, which is not a real problem, just an accounting bug on our side.

**Comment by bs78ta** [comment]
-679711

**Comment by strib** [comment]
The quota shouldn't be negative and that's confusing Windows.  We have fixed that negative quota bug going forward, but it will still affect users who previously got into this state.  Sorry for the annoyance!

**Comment by bs78ta** [comment]
Once i figured it to be no big deal stopped bothering me. I have keybase on win 7 and win 10 . Win 10 does not do it. And win 7 just decided to do it one day and been that way since. Once again I really appreciate the help getting this resolved so I guess the ticket can be closed.

**Comment by strib** [comment]
Great!
