### ISSUE TITLE
Linux Keybase ignoring default web browser

### ISSUE THREAD

**Issue by junderw** [keybase/client#16855]
```
$ xdg-settings get default-web-browser
chromium-browser.desktop
```

However, any link I click in keybase opens firefox.

**Comment by cmsteffen-code** [comment]
Huh. Mine open in Chrome, my default browser. I've got Firefox installed as well.

**Comment by holycleugh** [comment]
Can you try
```
echo "XDG_CONFIG_HOME=/home/$(whoami)/.config" > ~/.config/keybase/keybase.env
run_keybase
```

Does it open in Chromium after that?

**Comment by heronhaye** [comment]
Can you try

```
echo "XDG_CONFIG_HOME=/home/$(whoami)/.config" > ~/.config/keybase/keybase.env
run_keybase
```

Do links open in Chromium after that?

**Comment by junderw** [comment]
The workaround works. Will wait on the fix.

Since this is a duplicate I will close.

**Comment by heronhaye** [comment]
Resolved by https://github.com/keybase/client/pull/16710
