### ISSUE TITLE
Mastodon Verification forces the username to be lowercase

### ISSUE THREAD

**Issue by Eeems** [keybase/client#16943]
When attempting to add a mastodon proof in the client I enter my mastodon.social username with proper capitalization:
![image](https://user-images.githubusercontent.com/1176979/55899978-57006d80-5b83-11e9-92d2-53aeffd0f398.png)
When I click on Authorize I'm greeted with the following error (Cannot create a proof for eeems while logged in as Eeems. Log in as eeems and try again.):
![image](https://user-images.githubusercontent.com/1176979/55899986-5ec01200-5b83-11e9-9061-4c9e3a91c637.png)

**Comment by xgess** [comment]
thanks! we have already fixed this actually. it should be in the next mastodon release. sit tight and try again soon. :)

**Comment by Eeems** [comment]
@xgess _but I want my proof now!!!11_
Jokes aside, thanks for the quick response!

**Comment by xgess** [comment]
no thang: https://github.com/tootsuite/mastodon/pull/10544

**Comment by Eeems** [comment]
Can confirm that it now works. Thanks again @xgess
