### ISSUE TITLE
Input output error accessing folders

### ISSUE THREAD

**Issue by iz5wga** [keybase/client#16958]
I'm receiving this I/O error while accessing / listing / creating files inside private folders

~/.keybase/private/cyberpingu $ ls
ls: impossibile aprire la directory '.': **Errore di input/output**
13:02:04 mf18626@shaula ~/.keybase/private/cyberpingu $ 

my log id: e2ee72d3e5df7cfe80ea481c

**Comment by iz5wga** [comment]
Just in case...
> $ keybase fs reset /keybase/private/cyberpingu/
> This command will reset the entire folder /private/cyberpingu
> You will completely lose access to all data in that folder
> You should probably only do this if someone at Keybase told you to.
> Before resetting, contact Keybase admins for a server-side reset by:
>   1) Filing an issue at https://github.com/keybase/client; or
>   2) Running `keybase log send` and describing the problem.)
> Continue resetting the folder? (type 'YES' to confirm): YES
> ▶ ERROR EOF

**Comment by strib** [comment]
It looks like you revoked a number of devices, very quickly after provisioning your new devices?  In particular, device `Antergos` was used to add your new paper key, but maybe it was turned off too quickly to rekey your private folder, and then it was revoked?  Unfortunately your private folder hadn't yet been transitioned to our new system that does instantaneous rekeying when you add a device, so now no device has access.

If you want us to reset your folder, please run this command on a currently-valid keybase device, and substitute the current date and time where indicated:

```
keybase sign -m "<DATE_AND_TIME>: Please reset folder /keybase/private/cyberpingu because all the devices that have access have been revoked."
```

and post the results here.  After we do that, you should be able to run `keybase fs reset /keybase/private/cyberpingu` to reset the folder on your end.

**Comment by iz5wga** [comment]
$  keybase sign -m "Fri 12 Apr 2019 10:45 CET: Please reset folder /keybase/private/cyberpingu because all the devices that have access have been revoked."
BEGIN KEYBASE SALTPACK SIGNED MESSAGE. kXR7VktZdyH7rvq v5weRa0zkKxgJo4 UWlyaXLpZoLX7g1 dLHaUIb9SHJ77Ov WxvhKaCVwgbwCOW byEhBkC9ycrKbiv XM6KeJRSPJYhFnl Uir7OrbuZGpncFg EmuJl0T6tTlJr29 f0B1SOGAXvQCpM8 0mhpwKuDHHz1wNc dEteClJZygSJSjm SuxWr1uJx5HgLfo vhIalZpLZD6X3MP zL3XEFx1Q5DXEuK c7UVwd4XWLgZpQm mbX91T7a9uGMf2n 0MdNzdWa7Uy5bfj K1Dxb0ry8UcN2TM tw0lvRs3XVixtIA 07h9TR92tqNsEkk MbbXayxRf0rP7yP 8rPfda8K7DdK5Z3 bPJBoPW5OA7tioy mCXlNe. END KEYBASE SALTPACK SIGNED MESSAGE.

**Comment by strib** [comment]
I reset the folder.  Please run `keybase fs reset /keybase/private/cyberpingu` and close this if everything seems ok.  (Might require a Keybase restart.)

**Comment by iz5wga** [comment]
Thanks, I/O error's gone away!
