### ISSUE TITLE
Can't follow by command line OR by GUI (Error code 602) - Failed to follow

### ISSUE THREAD

**Issue by Bortseb** [keybase/client#16957]
I've tried following a few different people using the command line, some times it works fine, but when it doesn't my most common error looks something like this:

2019-04-11T00:59:22.527567-04:00 - [WARN keybase log_ui.go:36] 002 api error:  (error 602) [tags:ENG=DN0PVh-HvkYS]
2019-04-11T00:59:22.528567-04:00 - [ERRO keybase main.go:87] 003  (code 602)

When I try to follow the same person on the desktop app (I use windows 10), it also says
"Failed to follow" when I click the follow button.

**Comment by maxtaco** [comment]
Can you run `keybase log send` from the terminal?

**Comment by Bortseb** [comment]
Done

**Comment by maxtaco** [comment]
Oh, you're getting rate-limited

**Comment by Bortseb** [comment]
ah ok! I wrote a super simple shell script to follow a list of people, what is the rate limit so that I can maybe try and avoid it, and how long before I can add someone again?

**Comment by Bortseb** [comment]
602 seems to be related to being rate limited in terms of following others. Closing this issue, as I resolved my confusion.
