### ISSUE TITLE
Subteam-folder not visible

### ISSUE THREAD

**Issue by jokmie** [keybase/client#16959]
Keybase GUI Version: 3.2.1-20190410001724+61d9000f85

Subteam folder not visible on one PC (this one) but contains files on another PC.

**Comment by strib** [comment]
If you do a `keybase log send`, and post the resulting ID here, I can take a look. Also in the feedback of the log send, please give more info about which folder is not available.

**Comment by jokmie** [comment]
done. af0736685bc962951dc3bc1c

**Comment by strib** [comment]
@jokmie it looks like the user logged into that machine isn't a member of the team.  The user is just an "implicit admin" of the team, which means they're an admin of the parent team, but they haven't yet added themselves as an explicit member of the subteam.

**Comment by jokmie** [comment]
Ohh wow. I understand. That was counter-intuitive since I created the group from the same machine and same user.

**Comment by strib** [comment]
Yep, it's a little weird, but it makes sense when you consider admins in companies or something that are creating teams on behalf of other groups in the company.  Please let us know if anything else seems wrong.
