### ISSUE TITLE
My folders (public, private or team) cannot be accessed or listed.

### ISSUE THREAD

**Issue by mgiagante** [keybase/client#16986]
Hello,

After installing the desktop app and signing up via the command line, I found that my folders (public, private or team) cannot be accessed or listed.

In Settings > Files , it says that Keybase is enabled in my File Explorer.

I'm on Manjaro with the pacman-fm file manager and I installed keybase from the community repository.

my log id: 72dbe27317112b0743602a1c

**Comment by heronhaye** [comment]
Did you install kbfs?
https://www.archlinux.org/packages/community/x86_64/kbfs/
(I assume Manjaro can use this?)

See also keybase.io/docs/linux-user-guide.

**Comment by mgiagante** [comment]
It's working now. I didn't have kbfs installed. Indeed Manjaro uses that package, and the guide you linked me to was helpful. I also read https://wiki.archlinux.org/index.php/Keybase#Keybase_Filesystem_(KBFS) to enable the kbfs service.

Thank you for your quick reply!
