### ISSUE TITLE
Linux client not responding after suspend

### ISSUE THREAD

**Issue by xnaveira** [keybase/client#16987]
Using the Linux client in my laptop running Pop OS 18.10. After coming back from supension the client doesn't respond and has to be restarted.

**Comment by heronhaye** [comment]
Could you do a `keybase log send`?

**Comment by xnaveira** [comment]
You got it: b2475ed21961da611125121c

X

**Comment by heronhaye** [comment]
We'll look at it, thanks. 

For now could you run 
```keybase config set -b extra_net_logging 1``` and send us another log + post it here if this happens again (right after you restart if possible)?

**Comment by xnaveira** [comment]
I am afk right now but sure thing!

Xavier

**Comment by xnaveira** [comment]
I can reproduce it every time, here: 88bcf1e9880871893544fd1c

**Comment by heronhaye** [comment]
Ok, we'll investigate. Thanks for the logs!

**Comment by heronhaye** [comment]
I couldn't see much in your logs after you restarted. Could you clarify what you mean by "client doesn't respond"? When you're in this state after suspend, are you getting new chat messages in the GUI? Any spinners forever spinning? Does `keybase id` work? What about `keybase ping`? If these fail, could you send another log right after?

**Comment by xnaveira** [comment]
By not responding I mean the UI completely freezed, when I bring up the window I can see the title but the content of the window is either black or showing the background. I can try those commands the next time it happens, it looks more like a a purely ui problem. (btw it would be awesome to have a web interface for chat a la slack instead for the app imho)

**Comment by heronhaye** [comment]
Interesting, I conflated this with another recent network issue. 

If you can reproduce, the results of those commands would help, and maybe also some screenshots? Also, I'm not sure if you've already done so, but could you make sure you're on version 3.2.2 (we pushed an update recently)? Also, did you install Keybase via the .deb file on keybase.io?

**Comment by xnaveira** [comment]
I did some tests today and the issue seems to have vanished, either your updates or my OS's fixed the problem apparently. :smile: 
You may now close this if no one else has reported the problem.
Thank you!

**Comment by heronhaye** [comment]
Ok, let us know if it happens again. thanks!
