### ISSUE TITLE
Unable to access files in private directory

### ISSUE THREAD

**Issue by renatoathaydes** [keybase/client#16991]
I am trying to read files from my private directory but the file system does not seem to be responding.

Even on the terminal, I don't seem to be able to get into my private directory with `cd`, or list its contents with `ls`. It just hangs there.

I am on Ubuntu.

```
#167-Ubuntu SMP Wed Dec 5 10:40:15 UTC 2018
```

my log id: 303e80ca3423d50819e4b21c

**Comment by renatoathaydes** [comment]
Finally, it lists the following now:

```
go-hash-db
go-hash-db.conflicted (renatoathaydes's Curity Mac copy 2018-12-03)
go-hash-db.conflicted (renatoathaydes's Curity Mac copy 2019-01-03)
go-hash-db.conflicted (renatoathaydes's Renato's Small Laptop copy 2018-09-30)

```

This is a file I use from both a Mac and a Ubuntu Dell Laptop.

Just checked the file contents, it seems to work now, no content corruption I think.

**Comment by strib** [comment]
We talked privately; the user's machine was having connectivity issues to one of our servers.
