### ISSUE TITLE
Updates are not (honestly) disclosing changes

### ISSUE THREAD

**Issue by gitcnd** [keybase/client#17001]
I'm deeply suspicious about the flurry of updates that have been coming up over the last few days, and all of them say the same thing, while none of them actually disclose what has really changed.

Tell us what has REALLY changed please, and stop using the same "whats new" text over-and-over.

**Comment by maxtaco** [comment]
We'll work on it. There were two updates this week. The first was our planned release. Then, we made a "hot fix" to fix bugs with:
  * giphy search (https://github.com/keybase/client/pull/16954)
  * pgp decrypt (https://github.com/keybase/client/pull/16944)
  * iOS passphrase store (https://github.com/keybase/client/pull/16962)
