### ISSUE TITLE
Android 2.12.4: Error loading profiles with Unknown incoming RPC 181 keybase.1.identifyUi.start

### ISSUE THREAD

**Issue by arunsathiya** [keybase/client#17123]
I am currently using Keybase 2.12.4 on Android and when trying to load others' profiles, it fails with this error `Unknown incoming RPC 181 keybase.1.identifyUi.start`

![signal-attachment-2019-04-23-093357](https://user-images.githubusercontent.com/18581859/56567206-04d33980-65d2-11e9-9a36-dc3ffaaab62c.jpeg)

Trying to force-close the app and launch again fixes the issue. I am not sure what's causing this, as it happens often though.

Any clues would be fantastic. Thanks!

**Comment by maxtaco** [comment]
I would suggest updating the app, that app is very far out of date.

**Comment by arunsathiya** [comment]
I am no longer using Google Play Store. Would the team consider listing APKs on https://github.com/keybase/client/releases?
