### ISSUE TITLE
Input/output error

### ISSUE THREAD

**Issue by docon001** [keybase/client#17205]
Getting an `input/output` error on two of my folders every time I try to open them

my log id: 96c655000e9ee80878dbc71c

**Comment by strib** [comment]
@docon001 it looks like you hadn't added yourself to a subteam you created at the time of those errors, but now you have.  Is everything ok now?  If so, please close this out.

**Comment by docon001** [comment]
I am in the subteam, but I can't access the files. I can access it from a different device, but this device errors out.

**Comment by strib** [comment]
Can you please send new logs from the device giving you the problem?  The ones you last sent were all "not in subteam" errors.

**Comment by docon001** [comment]
New log ID: 8bbc5078322710e802f5831c

**Comment by docon001** [comment]
Not sure what the issue there was, tried following steps here: https://github.com/keybase/client/issues/16671

And specifically `keybase db nuke` worked to resolve my issue
