### ISSUE TITLE
Quote people from non group chat

### ISSUE THREAD

**Issue by IpsmLorem** [keybase/client#17206]
It would be nice to be able to quote people in chat and not only in group chat.

**Comment by IpsmLorem** [comment]
Works. Doesn't work on timed messages.

**Comment by IpsmLorem** [comment]
Maybe it would be nice to be able to quote exploding messages (and explode the quote at the same time)

**Comment by IpsmLorem** [comment]
Done in the last client version.

**Comment by kingleo103** [comment]
ayy
