### ISSUE TITLE
Ephemeral keys life span

### ISSUE THREAD

**Issue by IpsmLorem** [keybase/client#17202]
Is there a plan to destroy ephemeral keys of exploding messages accordind to their life span and not 7 days ?
Cf NCC Audit report https://keybase.io/docs-assets/blog/NCC_Group_Keybase_KB2018_Public_Report_2019-02-27_v1.3.pdf

**Comment by maxtaco** [comment]
Our plan is to stay with the current design for now, as it confers considerable scalability advantages over the Signal ratchet for groups even as big as 30 devices (not to mention some groups on keybase have over 2k users and 10k total devices). We'll potentially revisit the design as the MLS project makes progress.
