### ISSUE TITLE
automatic links for URLs are broken if they contain "https://"?

### ISSUE THREAD

**Issue by huyz** [keybase/client#17350]
When viewing a chat that contains the URL:
`https://webcache.googleusercontent.com/search?q=cache:fQQcoNv0f6UJ:https://keybase.io/docs/crypto/ephemeral+&cd=1&hl=en&ct=clnk`
which is the Google cached version of https://keybase.io/docs/crypto/ephemeral the link is broken and can't be clicked.

You end up with 2 separate broken links separated by `://`
[https://webcache.googleusercontent.com/search?q=cache:fQQcoNv0f6UJ:https](https://webcache.googleusercontent.com/search?q=cache:fQQcoNv0f6UJ:https)://[keybase.io/docs/crypto/ephemeral+&cd=1&hl=en&ct=clnk](keybase.io/docs/crypto/ephemeral+&cd=1&hl=en&ct=clnk)

**Comment by heronhaye** [comment]
Resolved by https://github.com/keybase/client/pull/17474
