### ISSUE TITLE
Debian packaging is missing some dependencies

### ISSUE THREAD

**Issue by strugee** [keybase/client#17365]
Installing Keybase on an extremely minimal Debian 9 system (specifically, Qubes OS' debian-9-minimal template) revealed the following missing dependencies:

* `libnss3`
* `libxtst6`
* `libxss1`
* `libasound2`

**Comment by heronhaye** [comment]
Thanks for the report. Continuing on linked PR.

**Comment by heronhaye** [comment]
Using the dockerfile from https://hub.docker.com/r/jgoerzen/debian-base-minimal, I found that I also needed libgtk-3-0. Did you already have it on your system?

**Comment by strugee** [comment]
I'm not in front of my computer but it seems probable!
