### ISSUE TITLE
Quit app via UI (Windows, Linux, possibly Mac?)

### ISSUE THREAD

**Issue by niklasb** [keybase/client#17374]
It used to be possible to quit the keybase app via the UI reachable from the system tray until this was changed very recently.

I want a way to quickly close the app without having to open a terminal and type `keybase ctl app-exit`.

Please bring back this feature.

**Comment by heronhaye** [comment]
This will be available in the next release in the main UI.

![2019-05-06-091310_406x799_scrot](https://user-images.githubusercontent.com/28712558/57227401-4f47b380-6fdf-11e9-8641-a69c6621d9a6.png)


However, why doesn't it work from the "UI reachable from the system tray"? That shouldn't have changed. What OS are you on?

**Comment by niklasb** [comment]
I am using Windows an Linux. There used to be a "..." button in the top right corner, but it has disappeared in recent versions (and replaced(?) with the link to Files)

![screen-2019-05-06_15-15-10](https://user-images.githubusercontent.com/94819/57227528-ec234480-7011-11e9-9bd5-cf7bd04590f3.png)

**Comment by niklasb** [comment]
Maybe it's just hidden, because it seems there is at least one more button which links to Teams on the right of which only 5 or so pixels are visible.

**Comment by heronhaye** [comment]
That looks like a UI bug related to long filenames. I believe that was fixed as well.

**Comment by niklasb** [comment]
I'm on the newest version. Could indeed be a long filename though.

**Comment by heronhaye** [comment]
Sorry, I meant it will be fixed in the next release*

**Comment by niklasb** [comment]
I see. OK this seems to be an unrelated issue then, produced not by an update but by some long file appearing in the UI, which just manifests itself very oddly. Closing.

**Comment by heronhaye** [comment]
Keybase 4.0 has a Quit Keybase button in the main app in the GUI.

![2019-05-08-164233_367x601_scrot](https://user-images.githubusercontent.com/28712558/57407074-5671eb80-71b0-11e9-9713-581f9baa3808.png)

Also, `keybase ctl stop` should work as expected on Linux.

**Comment by niklasb** [comment]
Good stuff, and the burger menu is also back :) Just love using keybase overall so far.

**Comment by sud0xenn** [comment]
<img width="246" height="88" alt="Image" src="https://github.com/user-attachments/assets/07102d1e-1f9b-489c-8f38-45dced28075a" />

Can confirm, the system tray in linux does not offer any options at all. @niklasb
