### ISSUE TITLE
multiple tray icon

### ISSUE THREAD

**Issue by vniche** [keybase/client#17498]
![Imgur](https://i.imgur.com/cudFB0s.png)

my log id: e33ce20760a160977106d41c

keybase version 4.0.0-20190508150240+6614a49937

**Comment by heronhaye** [comment]
That's odd. Do more show up when you start Keybase? What happens if you run `run_keybase` in terminal? If that doesn't fix it, what happens if you do `run_keybase -k` first, and then `run_keybase`?
