### ISSUE TITLE
Keybase always (always!!!!) starts on startup and cannot be disabled

### ISSUE THREAD

**Issue by alexcyco** [keybase/client#17507]
Keybase GUI Version: 3.2.2-20190412030505+5262f90fd9

**Comment by heronhaye** [comment]
Are you on Linux? Try `keybase ctl autostart --disable` in the terminal. For Windows and Mac, there's an option in Settings>Advanced in the GUI.

**Comment by belarm** [comment]
No, there actually isn't. So how do I turn this off?
