### ISSUE TITLE
[Crash] Android App 4.0.0: Secret Store not functional ...

### ISSUE THREAD

**Issue by zullinux** [keybase/client#17516]
Hi,

I've successfully installed the Keybase App (v 4.0.0) into my old Samsung Note 3 (Android 5.0 version).

After inserting username and password the app crashes with the following error:
"There was an error provisioning
Secret store not functional: error while storing secret: Android Keystore must be in initialized and unlocked state if encryption is required. 
Error code 218: GENERIC in method keybase1.login.login"

Any hint on what I'm doing wrong ?

**Comment by zullinux** [comment]
I solved the issue.
It was linked to the fact that my Phone did not use any secure unlock (swipe-only).
This prevented Keybase to access/initialize the Keystore.

**Comment by shful** [comment]
Same ERROR today with Keybase 4.0.1-20190516174408, after typing the username to log in.

Your workaround solved it (I never had found that on my own!) I replaced the phone Swipe-Unlock by an Unlock Pattern, and it works.

_Cyanogenmod 12.1 aka Android 5.1.1_
