### ISSUE TITLE
Use native window manager UI or ability to return to it in settings.

### ISSUE THREAD

**Issue by PresGas** [keybase/client#17541]
Since the update to 4.0.0, I can no longer control the window behavior from xfwm4 with the Keybase client. I have to go to the panel bar to do finer manipulations of my window (like making it present on every virtual desktop). Additionally, there are no pixels available in the window frame to properly drag-resize if necessary. Attaching screenshot with Signal below it to view the native xfwm4 decorations.

![KeybaseWindowUI201905-4 0 0](https://user-images.githubusercontent.com/4943849/57697972-7414da00-7622-11e9-8615-ee06887d025d.png)

I request the return to using whatever platform's native window manager or the ability to use it in settings. Chrome has this option available in their browser "Use system title bar and borders", I am attaching another screenshot for reference.

![KeybaseWindowUISettingOption201905-4 0 0](https://user-images.githubusercontent.com/4943849/57697982-78d98e00-7622-11e9-9164-c82326cb0c81.png)

**Comment by heronhaye** [comment]
Addressed by https://github.com/keybase/client/pull/17472.

**Comment by PresGas** [comment]
@heronhaye What release will this be in?

**Comment by heronhaye** [comment]
Will be available in the next release in a few weeks, or if you prefer, you can install the [nightly](https://keybase.io/docs/linux-user-guide#nightly-builds) and let us know if it works for you. It defaults to system frame but you can toggle it in Settings->Advanced.
