### ISSUE TITLE
Go client username -> uid

### ISSUE THREAD

**Issue by coen-hyde** [keybase/client#1754]
I'm building tool on top of the Keybase Go library and I'm having difficulty finding a way to lookup a user's uid if I have their username only. Is this possible with the client library?

Thanks

**Comment by maxtaco** [comment]
Hi, for most users it's just the hash of the lowercase of the username, plus a `19`, but early users predate that design decision.  So it's easiest to ask for server assist on all such lookups. 

The best endpoint these days is [merkle/path](https://keybase.io/_/api/1.0/merkle/path.json?username=linuxmodder), which you can look up by username.  In the case of old Username->Uid mappings, it will give proof from the merkle tree (so you can audit we're not lying to you).  On newer UIDs, you can compute it directly

**Comment by coen-hyde** [comment]
@maxtaco great, thanks, that's what I need.
