### ISSUE TITLE
Move keybase.io proof to a device key

### ISSUE THREAD

**Issue by dhess** [keybase/client#17594]
I'm an early adopter, therefore my PGP key is part of my sigchain. I'm preparing to move to a new PGP key and retire my current one, so out of an abundance of caution, I've revoked and re-verified most of my Keybase identity proofs, which were previously connected directly to the PGP key. These proofs are now connected directly to various Keybase device keys. (See https://keybase.io/dhess/graph)

The only remaining identity that's attached to my current PGP key is my keybase @dhess ID. Is there a way to move this identity to a Keybase device key?

This question is somewhat related to #4662, in that I'm trying to avoid that situation.

**Comment by maxtaco** [comment]
Nothing that you need to do, many of my early proofs are with my PGP key, that I've since rotated.

**Comment by dhess** [comment]
Thanks. So if I revoke the current key, it'll remain in the graph just like my revoked device key nodes do?

**Comment by maxtaco** [comment]
Yes.
