### ISSUE TITLE
Can not input any char

### ISSUE THREAD

**Issue by murrrf** [keybase/client#17638]
Keybase GUI Version: 4.0.0-20190508150240+6614a49937
my log id: f7c7ebe6a571963db91fa11c
OS version: Linux Mint 19.1

Keybase client doesn't accept any keyboard input. Even the password cannot be entered.
I can only paste text from the clipboard with the mouse, which is somewhat inconvenient in practical application.

However, version 3.2.2-20190412141809+5262f90fd9 works without any problems.

**Comment by heronhaye** [comment]
Do you have anything special about your keyboard input?

**Comment by murrrf** [comment]
No. All settings are default and did not change after installing the OS. I have not encountered such a problem in all other programs.

**Comment by heronhaye** [comment]
Are you using latin characters? Did you install Keybase from the website keybase.io or another way? And did you start keybase with `run_keybase`?

**Comment by murrrf** [comment]
Yes, I install Keybase from https://keybase.io/docs/the_app/install_linux ( `https://prerelease.keybase.io/keybase_amd64.deb`) accordingly the instruction.
Yes, I tried latin chars first and, after I could not enter them, cyrillic too, with the same result.
Yes, I use `run_keybase`  for start client.

**Comment by heronhaye** [comment]
Sorry about this, we're not sure. Does it work if you run
```
 KEYBASE_SYSTEMD=0 run_keybase
```
?

**Comment by murrrf** [comment]
No, nothing has changed.

**Comment by heronhaye** [comment]
But if you install 3.2.2 from https://s3.amazonaws.com/prerelease.keybase.io/linux_binaries/deb/index.html, the typing works again?

**Comment by murrrf** [comment]
Yes. I installed version 3.2.2-20190412141809 + 5262f90fd9 and it works without problems.

**Comment by heronhaye** [comment]
Which DE/WM are you using? Gnome, KDE, i3wm, etc? We'll try to repro.

**Comment by murrrf** [comment]
OS: Linux Mint 19.1 Tessa 64-bit
Kernel: Linux 4.15.0-50-generic x86_64
DE: MATE 1.20.1
CPU: i7-7700 CPU @ 3.60GHz × 8 
Memory: 8 Gb
What additional information would be useful?

Forgot to mention earlier. When adding a new (current) device, I used the QR code. The code on the monitor and on the phone screen did not visually match. However, the secret phrase coincided.

**Comment by murrrf** [comment]
The problem is gone after upgrading to version 4.1.0-20190612201656+952fee6c59. Now all working great and chars are input correctly.

**Comment by heronhaye** [comment]
@murrrf Great, glad it's working now. We looked into it but were not able to reproduce this behavior and didn't get any similar reports. Let us know if it happens again.
