### ISSUE TITLE
fusermount: exit status 1

### ISSUE THREAD

**Issue by SinTan1071** [keybase/client#17634]
Well, I install keybase client on Ubuntu16.04 manually , when I run "run_keybase", it tells me ``` KBFS failed to FUSE mount at $HOME/.config/keybase/kbfs: fusermount: exit status 1```, please give me a little help with it, thanks

**Comment by heronhaye** [comment]
Could you `run_keybase` and then `keybase log send` in terminal? Thanks.

**Comment by SinTan1071** [comment]
@heronhaye Sure thing, The log ID is 12b908cf5904e889d936c11c

**Comment by heronhaye** [comment]
It seems your device does not support FUSE. Is it a chromebook or something similar?

**Comment by SOF3** [comment]
Same issue when running on WSL, with log ID 9ceb8e8047ef8026877e871c

**Comment by heronhaye** [comment]
@SOF3 WSL doesn't support fuse either. You can still use KBFS with `keybase fs` commands or in the GUI.

**Comment by Lucky225** [comment]
I'm having the same issue, using kali-linux under windows with WSL2 which *does* support FUSE (see https://devblogs.microsoft.com/commandline/announcing-wsl-2/ -- "This introduces a whole new set of apps that you can run inside of WSL. Some exciting examples are the Linux version of Docker, as well as FUSE!")

log id:
56c03d046f2eded33682f41c

**Comment by nickkostov** [comment]
Log ID in WSL v1   1f6affc882940e220d0e5a1c

**Comment by WingsLikeEagles** [comment]
I get this error when I try to run keybase on AWS CloudShell... which does not have FUSE when I do a modprobe fuse.
modprobe: FATAL: Module fuse not found in directory /lib/modules/4.14.294-220.533.amzn2.x86_64
