### ISSUE TITLE
No visibility into network errors

### ISSUE THREAD

**Issue by davidk01** [keybase/client#17633]
Keybase GUI Version: 4.0.0-20190507154537+6614a49937

The application will randomly fail to send messages when I'm connected to one network and then switch to another one. This usually happens when I have the application open and then close the lid on the laptop and switch to another network. I've tried quitting and logging out but that doesn't do much to fix the problem. The only thing that seems to work is to wait until the issue magically goes away. Actually, the problem goes away after restarts but an application that requires an entire machine restart to fix itself is not really acceptable.

This is annoying on a few levels because the usual reset mechanisms seem to do nothing. So in the absence of the usual mechanisms fixing the problem I'd like more visibility into which part of the code is timing out and why so I can use some other application instead of trying to get keybase to work if the problem persists and is out of my control.

**Comment by heronhaye** [comment]
Could you switch netwo `keybase log send` in terminal? Thanks.

**Comment by davidk01** [comment]
Ok. Will update next time I notice the issue again.

**Comment by davidk01** [comment]
Sent the log

![image](https://user-images.githubusercontent.com/320776/58263009-2853e600-7d30-11e9-8624-f1539a46a5a8.png)

**Comment by heronhaye** [comment]
Thanks, we'll take a look. Just to be clear, when this happens, restarting Keybase by pressing "Quit Keybase" in the username dropdown and then starting Keybase back up again doesn't help?

**Comment by davidk01** [comment]
That's correct.
