### ISSUE TITLE
KBFS Not Running after Reboot / CentOS 7

### ISSUE THREAD

**Issue by Wintermute3** [keybase/client#17644]
CentOS 7 server, no GUI, KBFS does not start on reboot until I manually do *run_keybase*. 
 Running *keybase status* after reboot shows KBFS 'not running'.  After *run_keybase* all is fine until after next reboot.

[mnagy@hulk ~]$ systemctl --user status kbfs
Failed to get D-Bus connection: No such file or directory
[mnagy@hulk ~]$

Not sure what is up with ^^^, but it seems relevant.

my log id: d4ada3903859f1cfed42fd1c

**Comment by heronhaye** [comment]
Did this work in the past/did you configure something that would make this work?
I'm not super familiar with CentOS but I don't believe it has a systemd user manager which means the systemd units will not work, so you can't `systemctl --user enable kbfs` like you could on a Debian or Arch server.

You may want to put `run_keybase -g` in the system startup scripts (the `-g` so it doesn't try to start teh GUI). Some additional configuration may be needed to get it to keep running after your SSH session ends as well.

**Comment by Wintermute3** [comment]
This seems very relevant:

  https://bugs.centos.org/view.php?id=8767

Basically, CentOS 7 will never support --user (unprivileged systemd services).  :-(

**Comment by heronhaye** [comment]
Yeah, it's a bit annoying. If you do have a server with a systemd user manager, the docs at keybase.io/docs/linux-user-guide#systemd-and-running-headless-keybase should be helpful.

**Comment by Wintermute3** [comment]
Thanks heronhaye, keybase works fine regardless of ssh login/logout, it is just server reboots that bork things.  I can certainly cobble something together as you suggest to work around the issue, but it would be nice if keybase install was savvy enough to work around the issue for me.  :-)
