### ISSUE TITLE
problem with device name in macOS

### ISSUE THREAD

**Issue by ljtc** [keybase/client#17699]
Hello, I've just downloaded and installed Keybase in macOS Mojave 10.14.4. When I try to sign up, in the device name part, it always says that the name is reserved for Keybase staff no matter what name I try. 

<img width="797" alt="Captura de Pantalla 2019-05-24 a la(s) 10 46 50" src="https://user-images.githubusercontent.com/35584421/58340827-60cbf080-7e12-11e9-8db3-ff930c946485.png">

<img width="794" alt="Captura de Pantalla 2019-05-24 a la(s) 10 47 11" src="https://user-images.githubusercontent.com/35584421/58340835-6590a480-7e12-11e9-8bf1-490258bb07d6.png">

There is a kind of standard for device name or something I missing?

**Comment by pzduniak** [comment]
Your desired _account name_ has been reserved. That's the only constant in your form input :)
