### ISSUE TITLE
git pull failing with "fatal: protocol error: bad line length character"

### ISSUE THREAD

**Issue by telotortium** [keybase/client#17718]
This has been happening on one of my private git repos since around the beginning of this week:

```
$ git pull --verbose
fatal: protocol error: bad line length character: Port
```

From some cursory searching, I can see that this might happen when a request is too large ([source](https://github.com/bracke/bracke/blob/2e2e2fa89affecfb1f9f974ca2260f6dfffe721d/_posts/2016-01-31-Fix-Bonobo-Problem.md)). I also see

```
$ keybase git gc $REPO
This may take several minutes...
▶ ERROR file does not exist
```

**Comment by telotortium** [comment]
My log id: e1a420afae023c425c601d1c

**Comment by telotortium** [comment]
Never mind - https://stackoverflow.com/q/8170436/207384 tells me it's more likely to be an SSH error. And indeed, upon investigating further, it seems it's due to an issue with another remote in the same repo that's accessed over SSH.

**Comment by iqre8** [comment]
Fixed it by opening the ssh agent of putty and adding the key.
