### ISSUE TITLE
Get user's PGP fingerprints programatically? 

### ISSUE THREAD

**Issue by awensaunders** [keybase/client#17712]
I personally have two primary PGP keys, both of which are published to keybase. I like the ability to send PGP messages to keybase users (and all of their keys), so I decided to write a little script that would allow me to do that using the normal gpg tooling (as my keys aren't available in the keybase pgp keychain). When I run `keybase id <username>`, it shows me the PGP fingerprints that a user has published. This information does not seem to be available in JSON form however. When I run the command `keybase id -j <username>` on a user with multiple PGP keys (such as myself), only one `identifyKey` element with a corresponding PGP fingerprint shows up. I ended up writing my script scraping off the non-json version, but it's weird to me that the human readable part has more information than the JSON dump. Is this a bug, or is there something I'm missing?

**Comment by dabura667** [comment]
```bash
$ keybase dump-keyfamily awensaunders@github | grep "PGP Fingerprint" | cut -d':' -f2 | sed 's/ //g'
DA32B382C945385EE44F3BE9522B01F5A1B242E6
C0BE5EB55EA7E42B101DB121C21B710392C12407
```

**Comment by awensaunders** [comment]
Thanks for that. I hadn't seen the `dump-keyfamily` command, and that's a much cleaner pipeline than what I ended up writing (there were many control characters etc in `keybase id`).

I'm still curious why it isn't in the JSON dump, but I'll close the issue. Thanks.
