### ISSUE TITLE
Keybase folder items missing

### ISSUE THREAD

**Issue by nicodosw11** [keybase/client#17735]
Some of my folder items are missing (disappeared overnight).

<img width="976" alt="Screenshot 2019-05-29 at 11 27 01" src="https://user-images.githubusercontent.com/20165669/58557957-87759700-8217-11e9-9f1d-ef37102fdcb9.png">

This is the screen I get all the time. There is also a never ending encrypting process of some of the files running in the background.

log ID 2abe564dffbdd48142d2941c

Thanks

**Comment by strib** [comment]
@nicodosw11 your device is stuck in "conflict" mode, which means at some point in the past, your device wrote to the folder at the same time as another device, and so went into a mode where it tried to automatically resolve the changes between the two devices.  Normally this happens successfully in the background without you knowing about it, but apparently in this case (probably due some bug in our code) your device couldn't resolve the change, and got "stuck".  Now it is trying to view data from a version of the folder that is too old, and has already been cleaned up by other devices.  This happened months ago, I think.

We are currently working at surfacing these types of issues quickly to the user, so we can fix them right away.  But for now, you can fix this on your own by running this command from a terminal:

```
keybase fs clear-conflicts /keybase/team/consumer_team
```

That should get you back in sync with the latest version of the folder from our server's perspective.  Let me know how it goes.  Sorry for the inconvenience and bad experience.

**Comment by nicodosw11** [comment]
No worries. It looks like the command solved the problem. Items are back in the folder.
Thanks a lot for your help.

**Comment by strib** [comment]
Great!
