### ISSUE TITLE
Can't view people.

### ISSUE THREAD

**Issue by veddermatic** [keybase/client#17746]
Keybase GUI Version: 4.0.0-20190507193726+6614a49937

Whenever I click on a person, I get this: 

![Screen Shot 2019-05-29 at 2 33 15 PM](https://user-images.githubusercontent.com/322479/58582018-db37ae80-821e-11e9-82c5-3bd667543f24.png)

I looks like it loads their page for a moment, but then it's replaced by this.

**Comment by JuryA** [comment]
> Keybase GUI Version: 4.0.0-20190507193726+6614a49937
> Whenever I click on a person, I get this:
> 
> I looks like it loads their page for a moment, but then it's replaced by this.

I have the same issue - it looks like my profile was deleted but only in some cases. I can login with Desktop App and also on the Web bud I cannot view my Profile page.

**Comment by cjb** [comment]
It was a Keybase server outage, should be fixed now/ASAP.

**Comment by veddermatic** [comment]
I was in fact that thing @cjb said and appears to be all better now.
