### ISSUE TITLE
DOC – Keybase Pages

### ISSUE THREAD

**Issue by signalwerk** [keybase/client#17799]
On https://keybase.io/docs/kbp the `TXT` entry  is noted as:

```
_keybase_pages.example.com 300 TXT   "kbp=/keybase/private/yourname,kbpbot/my-site"
```
but with the quotes it is not working

```
_keybase_pages.example.com 300 TXT   kbp=/keybase/private/yourname,kbpbot/my-site
```
works perfect

**Comment by signalwerk** [comment]
Correction. I get not reliable results. See #17801

**Comment by songgao** [comment]
This differs among different DNS record UIs. The one with the quotes matches the output of `dig` command. Thanks for bringing it up; we'll clarify in the doc.

**Comment by signalwerk** [comment]
ok. thank you. I close the Issue. Feel free to reopen if you still need it for your track
