### ISSUE TITLE
Keybase error: "Login required: no sessionArgs available since no login path worked" on chromebook via chromebrew 

### ISSUE THREAD

**Issue by nealmcb** [keybase/client#17809]
I built keybase on chromebrew for my chromebook as discussed at https://github.com/skycocker/chromebrew/issues/3295

resulting in a keybase version 4.1.0 client which matches the current service.

It gave me this error:

    2019-06-04T10:30:57.206227-06:00 ▶ [ERRO keybase main.go:86] 001 Login required: no sessionArgs available since no login path worked

Here is my log id from keybase log send: `4c0be5a4eddf320130c6061c`

I also get

    $ keybase login
    ERROR EOF

**Comment by heronhaye** [comment]
Thanks, I see the bug. For now could you try

```
keybase config set -b force_less_safe_secret_store_file 1
keybase login
```

It seems the system keyring on your system is faulty, so as a fallback measure we have this secret store file (more info at https://keybase.io/docs/crypto/local-key-security).

Just curious, do you have anything like gnome-keyring or KWallet installed?

**Comment by nealmcb** [comment]
I removed keybase and recompiled it from source (I think). I ended up with the same version number: 4.1.0.
And I'm still getting the same errors.
I haven't figured out how to ensure that I do have the latest version. Do you ever add git commit info to version strings or the like?

**Comment by heronhaye** [comment]
Expected to still be on 4.1.0, git hashes would be something done by the package manager (i.e., chromebrew).

Could you stop all keybase processes and try to login again, and then send a log?

**Comment by nealmcb** [comment]
Thanks for the very quick help, folks!!

I stopped processes and got the same results.
I rebooted and got same results.

my log id: 7e31c88fe12e28cb4cb0f41c

**Comment by heronhaye** [comment]
Is it possible you didn't update to the latest code? You could try to remove the package and install again, maybe.

Anyway, if that doesn't work, try `keybase config set -b force_less_safe_secret_store_file 1`, stop processes, then `keybase login`. Send another log if it still doesn't work.

**Comment by nealmcb** [comment]
Yes - wrong source. Don't know why the --version says 4.1.0...

See skycocker/chromebrew#3295 again.

**Comment by heronhaye** [comment]
No, `--version` is accurate and you are on 4.1.0. Installing with `-s` compiles from git source instead of using the tarballs. However, I think it is possible you haven't updated to the latest master after the fix was committed.

**Comment by nealmcb** [comment]
As I noted in issue 3295, I'm not sure what the go get and go build lines are doing. Do they ever cache a version of master?

**Comment by nealmcb** [comment]
After working thru more build issues as noted in  skycocker/chromebrew#3295, keybase is working like a charm now on ChromeOS, including with git.

And it's **amazing** and so well suited to Chromebook usage patterns. So much better than the whole google drive integration for many many things....

Thanks, folks!
