### ISSUE TITLE
Keybase Pages – not reliable 

### ISSUE THREAD

**Issue by signalwerk** [keybase/client#17801]
When I run in terminal 

```sh
curl https://pad.signalwerk.ch/
```

I get sometimes `Hello, World!` and sometimes `no TXT record is found for kbp=`

See also #17799

I know it's experimental, but I guess it's ok to give you a response to it.

**Comment by songgao** [comment]
That's likely due to the DNS propagation delay where in a short window you see the record in some of the queries but not others. It should converge.

**Comment by signalwerk** [comment]
That was it. Now – a couple hours later – everything works. Sorry for bothering you.
