### ISSUE TITLE
Keybase Pages – Subdomain

### ISSUE THREAD

**Issue by signalwerk** [keybase/client#17800]
If I would like to have `sub.example.com` and `sub2.example.com` on Keybase Pages this doesn't work since the `TXT` entry is expected to be in folder `.../my-site` so I can't add two different subdirectories for the different sub-domains

Expected to work:
```
_keybase_pages.sub.example.com 300 TXT   "kbp=/keybase/private/yourname,kbpbot/subA"
_keybase_pages.sub2.example.com 300 TXT   "kbp=/keybase/private/yourname,kbpbot/subB"
```

**Comment by songgao** [comment]
Not sure I understand the issue. Are you saying `my-site` is required to be in the path? That's not true. As far as I can tell by eyeballing your examples should both work.

**Comment by signalwerk** [comment]
@songgao without `my-site` it was not working for me. But I just changed now again to test it. Probably it was also related to the DNS propagation. I'll report back here.

**Comment by signalwerk** [comment]
@songgao sorry for bothering you. works as expected. I was just not waiting for the DNS-Propagation.

**Comment by songgao** [comment]
No worries. Thanks for reaching out!
