### ISSUE TITLE
no example bash command to clone repo

### ISSUE THREAD

**Issue by ORESoftware** [keybase/client#17842]
We are adopting keybase for encrypted git repos

I just created a repo which is encrypted by default, and now I want to clone it:

<kbd>
<img width="1187" alt="Screen Shot 2019-06-06 at 11 23 48 AM" src="https://user-images.githubusercontent.com/11139560/59056724-b611f400-884d-11e9-9a3d-72149ce634db.png">
</kbd>

however I don't know what command to use to clone the repo, I tried

```bash
keybase git clone keybase://team/interos_team/ssh_keys
```

but that didn't work.  Why doesn't the UI show which command to use? If I have hover over something can it display the command?

Sorry if this is the wrong repo to file an issue.

**Comment by strib** [comment]
Sorry for the confusion.  keybase repos just work with the regular git command, so you can use:

```sh
git clone keybase://team/interos_team/ssh_keys
```

No need for the `keybase` in front of it.

**Comment by ORESoftware** [comment]
yeah I figured that out by reading more docs, but it should show that on the web ui, at least if you hover over something, thx
