### ISSUE TITLE
git-remote-keybase error: (1) Can't get TLF private key for key generation 1

### ISSUE THREAD

**Issue by thalesfsp** [keybase/client#17846]
`keybase log send`: `f447778601eba9271f0d7e1c`
@strib 

Thanks!

**Comment by strib** [comment]
@thalesfsp thanks for reporting.  Seems like you created your private folder back in 2016, and have since revoked all the devices.  New versions of Keybase don't let this happen anymore, but it could happen back then.

If you want us to reset your folder, please run this command on a currently-valid keybase device, and substitute the current date and time where indicated:

```
keybase sign -m "<DATE_AND_TIME>: Please reset folder /keybase/private/thalesfsp because all the devices that have access have been revoked."
```

and post the results here.

**Comment by megrxu** [comment]
I'm in a similar situation. I revoked all old devices and then I can't access to my private folder '/keybase/private/xugr' anymore.

log ID: `a60d1e141bf0d03b3b88001c`

Signed message:
```
BEGIN KEYBASE SALTPACK SIGNED MESSAGE. kXR7VktZdyH7rvq v5weRa0zkOAlBOm Nd79SKEfBWtJAYL v8kX4ogQvoZJBPd 4aNpI0nCyDy9Hc2 CcYXaSbptoxG0Dp Yfv7tvHDPrB9c4d lFPE0N1IxfhfJ5U sl7Cb6lhKuX6SCn 8e1NkYy3uPE1t7E 8yGTiMAmwigZabQ oyKeaBywct4oCqh ziKGMrbK9IkxVBB utGvPXzYywj89ni T9x2ACcNPvZwgjF rjc61xXiW6X4X76 4H9BTZOv0XraNxN hvTPSx6rEciW1I6 oTd0tbkm74X64Uh G1sVWLOKJyx2irm O7h9TR92tqNsEkk MbbXayxRf0rP7yP 8rPfda8K7DdK5Z3 bPJBoPW5OA7tioy mCXlNe. END KEYBASE SALTPACK SIGNED MESSAGE.
```

Thanks! @strib

**Comment by strib** [comment]
@megrxu I reset the folder.  Now you should run this command from a currently-valid Keybase device:

```sh
keybase fs reset /keybase/private/xugr
```
Please try it out and let me know if everything seems ok.  (Might require a Keybase restart on other devices.)

**Comment by megrxu** [comment]
Thanks! @strib

Everything works for now.

But I found that many users encountered with this issue. 
Is it possible to reset the folder by ourselves? That could relieve you out of these repetitive work.

**Comment by strib** [comment]
Good!  It's not possible to reset things by yourself.  Luckily for new folders getting into this state isn't possible anymore, it's just people with old folders.  We don't mind helping out, just have people make a new issue here.

**Comment by thalesfsp** [comment]
Hello, @strib 

Follow the result:

```
BEGIN KEYBASE SALTPACK SIGNED MESSAGE. kXR7VktZdyH7rvq v5weRa0zk9L9AuR 6mr5ySfvxPSKpcv 97lpVXrJWbVyQXL 1j7oBim8JiaE9qU 6CnEgHTpkC0PrpJ wGoOXwxARGZ1YPk UVzbwz9xwNmCwFD m4x57t4Eu4NuxJn yuPJy8lKf5NMVUv GAzHfJ0lPQ0A5ke Dn6d2qX3NZzF76P lJyIkzcUXvNhuCY IJ4B7RtXURDBriV Y7iHBRMY7R6Xr7X ONhZ7bZdQ8GhL5Z HSbg80GkE90ogX5 spBBFgR3w0zz1d0 mvOTdNEZGtnkcrX GLMwcUCoyX5ObCP jO3WXNCEfHlndFH I1BMj47lRiDpspn 0CGyzD48Yj8AC50 aybxRb1a. END KEYBASE SALTPACK SIGNED MESSAGE.
```

**Comment by strib** [comment]
@thalesfsp I reset the folder.  Please check it out and close this if everything seems ok.  (Might require a Keybase restart.)

**Comment by thalesfsp** [comment]
Hi, @strib! It's working! Thank you very much for the fast response!
