### ISSUE TITLE
Failed to list folder: ERROR CODE 218 Unknown hash type

### ISSUE THREAD

**Issue by rebeccadahl-mobile** [keybase/client#17869]
I've been having problems running KeyBase from my W10 tablet since a Keybase re-installation. However, I can see the files via the Android App. I just can't access the files from the W10 KeyBase app or from the KBFS K: drive in order to change or remove files.

my log id: 00adfce98d15c9ffacfc1b1c

Thanks in advance.

**Comment by strib** [comment]
Hi @rebeccadahl-mobile, thanks for reporting.  It looks like your windows version is very out of date (from Sep. 2018) -- the data format has changed since then, and that version can't understand it.  Please try upgrading Keybase on that device and let me know if that fixes it.  Thanks!

**Comment by strib** [comment]
*edited to clarify that it's your _Keybase_ version that's out of date, not your Windows OS version.

**Comment by rebeccadahl-mobile** [comment]
No good. The autoupdater is not pulling the latest build. Also, the current installer on the keybase.io website will not install on 32-bit W10 like the previous version does (I have no other hardware available at this time). The current .msi installer terminates with a "This installation package is not supported by this processor type. Contact your product vendor."

Is there a fix or am I frozen out of my files for good?

**Comment by rebeccadahl-mobile** [comment]
This is regarding the current installer:

Name: keybase_setup_amd64.msi
Size: 180584448 bytes (172 MiB)
CRC32: 5DEA4E29
CRC64: D6039387BE2EB17E
SHA256: 529D9E0CD2DD1843DC6E75D42F2C59D7D598A62C71F0081978A9CA90C9D693D2
SHA1: 212C5DFD2BF171383D6A9470FEF0643B19C51C3D
BLAKE2sp: 0304332BB8EB0BC6D71D89F85F58475B3787401B15D16CB1F821E70E1A236C27

Even the complications have complications.

**Comment by strib** [comment]
Ah sorry, we no longer support 32-bit Windows builds, so unfortunately you are locked out on that device.

Our client is open source, so if you are comfortable with that sort of thing you can try building it yourself on that device, but at this time we won't be officially supporting it.
