### ISSUE TITLE
Keybase won't start on Ubuntu 16.04

### ISSUE THREAD

**Issue by zerbey** [keybase/client#17916]
Keybase had previously been on this machine and revoked, I reinstalled and removed all configuration.  At least, I thought I did.  When I try to start keybase I get the following:

Starting via systemd...
Job for keybase.service failed because the control process exited with error code. See "systemctl --user status keybase.service" and "journalctl -xe" for details.

● keybase.service - Keybase core service
   Loaded: loaded (/usr/lib/systemd/user/keybase.service; disabled; vendor preset: enabled)
   Active: failed (Result: start-limit-hit) since Wed 2019-06-12 17:33:30 EDT; 10s ago
  Process: 7911 ExecStart=/usr/bin/keybase --use-default-log-file --debug service (code=exited, status=2)
 Main PID: 7911 (code=exited, status=2)

Jun 12 17:33:29 squidward systemd[7144]: Failed to start Keybase core service.
Jun 12 17:33:29 squidward systemd[7144]: keybase.service: Unit entered failed state.
Jun 12 17:33:29 squidward systemd[7144]: keybase.service: Failed with result 'exit-code'.
Jun 12 17:33:30 squidward systemd[7144]: keybase.service: Service hold-off time over, scheduling restart.
Jun 12 17:33:30 squidward systemd[7144]: Stopped Keybase core service.
Jun 12 17:33:30 squidward systemd[7144]: keybase.service: Start request repeated too quickly.
Jun 12 17:33:30 squidward systemd[7144]: Failed to start Keybase core service.
Jun 12 17:33:30 squidward systemd[7144]: keybase.service: Unit entered failed state.
Jun 12 17:33:30 squidward systemd[7144]: keybase.service: Failed with result 'start-limit-hit'.

my log id: 6e6ca240fe105f02f132d51c

**Comment by heronhaye** [comment]
Did you ever try to run keybase with sudo maybe? I'm seeing that you don't have access to write to `~/.local/share/keybase` in your logs.

Could you try this and then restart keybase (modify if needed)?

```
sudo chown -R $(whoami):$(whoami) $HOME/.local/share/keybase
```

**Comment by zerbey** [comment]
Already checked permissions and they are correct.  I rechecked to be sure.

**Comment by heronhaye** [comment]
@zerbey even within the folder? recursively?

**Comment by zerbey** [comment]
That did it, the share folder under .local was owned by a different user.  Thank you!

**Comment by heronhaye** [comment]
@zerbey that's odd, do you know why that happened/if keybase had anything to do with it?

**Comment by zerbey** [comment]
Oddly enough it was my Plex server, go figure.
