### ISSUE TITLE
Mentioning common channels with full path should turn it into a link

### ISSUE THREAD

**Issue by Avamander** [keybase/client#17938]
For example if user `a` and `b` share the team `foob.ar` that has the channel `general` then writing `#foob.ar.general` should be a link to that chat for convenience.

**Comment by heronhaye** [comment]
Try `@foob.ar#general`

**Comment by Avamander** [comment]
I tried multiple variations, none of them turn into a link?

**Comment by heronhaye** [comment]
Is your Keybase updated? Latest version is 4.1.0.

```bash
$ keybase version
```

**Comment by Avamander** [comment]
```
➜  ~ keybase version
Client:  4.0.0-20190508150240+6614a49937
Service: 4.0.0-20190508150240+6614a49937
```

**Comment by Avamander** [comment]
I'll update and test it out again.

**Comment by Avamander** [comment]
I updated and now it's link-ified
