### ISSUE TITLE
Add functionality to search posts in channel by user

### ISSUE THREAD

**Issue by DukeValentine** [keybase/client#17957]
I haven't found how to do something like this with the current search options, so it would be nice if it was possible to search all posts in  a channel by a certain user. Same flags that apply to regular search would apply here, like search by date.

**Comment by DukeValentine** [comment]
Sorry, I didn't read properly the documentation. I found the flag to do what I wanted.

**Comment by Cherubsta** [comment]
So what is the option to do this?
