### ISSUE TITLE
Keybase update seems to be broken

### ISSUE THREAD

**Issue by RyanSinger** [keybase/client#1799]
Ryans-MacBook-Pro:~ ryan$ keybase update run
▶ ERROR EOF
Ryans-MacBook-Pro:~ ryan$ keybase update check
▶ ERROR EOF
Ryans-MacBook-Pro:~ ryan$ keybase version
Client:  1.0.9-0
Service: 1.0.8-0
Ryans-MacBook-Pro:~ ryan$

**Comment by geneticgrabbag** [comment]
Had similar issue, receiving `ERROR EOF` on most commands.
Resolved for me by performing `key base uninstall` followed by `key base install`.
Hope it helps.

**Comment by RyanSinger** [comment]
That weirdly fixed it. Thanks!
