### ISSUE TITLE
Error I/O

### ISSUE THREAD

**Issue by KernelPan1k** [keybase/client#17994]
Hello,

It's impossible to list the content or create new files/folders in a shared private folder. 

     mm@r2d2:~$ ls /keybase/private/kernelpanik,qzll/
     ls: lecture du répertoire '/keybase/private/kernelpanik,qzll/': Erreur d'entrée/sortie

my log id: bebf148eadf605f00a07de1c

Thank you^^

**Comment by strib** [comment]
Hi @KernelPan1k, thanks for the report.  I'm investigating.  It looks like there might have been something weird happening with your device `portable1` on June 2nd.  Would you be able to do a `keybase log send` from that device and post the log ID here?  Thanks!

**Comment by strib** [comment]
Separately, it seems like there are some corrupt or zero-byte files on the disk of the device you did send logs from.  I don't think it is causing the IO error, but it might be affecting performance on that device.  I'd recommend doing the following (in addition to sending the logs I requested above):

1. Make sure you don't have any outstanding data being uploaded from that device in any of your folders.
2. Shutdown Keybase and KBFS completely.
3. Run this command:
```sh
mv $HOME/.local/share/keybase/kbfs_journal .local/share/keybase/kbfs_journal.bkp
```
4. Restart Keybase and KBFS.

At that point your disk issues should be fixed, but you'll still be getting the IO errors on that folder you mentioned.

**Comment by KernelPan1k** [comment]
Hello,

Thank you for your quick answers. I made your instructions and here is the id of the report from the other computer.

portable1 log id: d0a394bf71662cc9dce0b11c

Thank you again for everything.

**Comment by strib** [comment]
Thanks!  I'm making some progress, but during a `keybase log send` we only send the most recent part of the logs, and unfortunately I need some data from older logs.  If you're willing to share more logs with me from that device, it would be great if you can do the following on that device:

```sh
tar -czf /keybase/private/strib@github,kernelpanik/client-17994.logs.tgz $HOME/.cache/keybase/keybase.kbfs.*
```

Thanks!

**Comment by strib** [comment]
Actually, I have another theory -- it seems like your device `portable1` is still in the middle of an upload of some data.  It seems to be having network issues uploading the data sometimes, and whenever it's on it's been trying to upload data but sometimes failing.  You can check `/keybase/.kbfs_status` and look for `UnflushedBytes` to see if it's still trying to upload data.  If so, please try to leave it on until all the bytes are flushed, and that might fix your broken folder.

I'm also curious if the broken folder works correctly from this device.

(It's definitely a bug on our side that this would cause a problem on other devices, and the extra logs I requested above might help me figure out why that happened in the first place.)

Thanks!

**Comment by KernelPan1k** [comment]
Hello,

you're right the problem comes from an unfinished upload. It's a computer I don't use much, just on the road. I put documents in the shared folder and Keybase indicated 16h to finish uploading. I left it running all night but the next day it was still 14 hours. I then deleted the documents in Keybase and on my computer, but the upload continued. Now that the upload is finished, I can access the shared folder from "portable1" but not from my other devices.

The logs you asked me for are currently uploading to our shared folder. The first attempt returned an error, I had to do it again. 

    mm@r2d2:~$ tar -czf /keybase/private/strib@github,kernelpanik/client-17994.logs.tgz $HOME/.cache/keybase/keybase.kbfs.*
    tar: Suppression de « / » au début des noms des membres
    tar (child): /keybase/private/strib@github,kernelpanik/client-17994.logs.tgz : open impossible: Erreur d'entrée/sortie
    tar (child): Error is not recoverable: exiting now
    tar: /keybase/private/strib@github,kernelpanik/client-17994.logs.tgz: seulement 4096 octets sur 10240 ont été écrits
    tar: Child returned status 2
    tar: Error is not recoverable: exiting now
    mm@r2d2:~$ tar -czf /keybase/private/strib@github,kernelpanik/client-17994.logs.tgz $HOME/.cache/keybase/keybase.kbfs.*
    tar: Suppression de « / » au début des noms des membres
    tar: Suppression de « / » au début des liens physiques
    tar: /home/mm/.cache/keybase/keybase.kbfs.log : fichier modifié pendant sa lecture

Thank

**Comment by strib** [comment]
Thanks for the new logs!  The device is still uploading stuff to your shared folder -- it has about 3 GB left to go.  Even though you deleted the documents, the way it works is it still has to upload them all, and then delete them after -- it executes all the operations in order, even if a delete comes later, due to the nature of the file system structure.  Sorry for the confusion.  If you can keep the device online until `/keybase/.kbfs_status` shows no more unflushed bytes, you should be ok.

I will keep looking at these logs to try to fix the underlying bug.

**Comment by KernelPan1k** [comment]
Hello,

I left the computer on for 48 hours and the problem is still the same. I have two "UnflushedBytes" values, the first is at 0 and the second is a negative number that keeps growing. Is it possible to "reset" this folder even if I lose the content, it doesn't matter. 

Thank

**Comment by KernelPan1k** [comment]
Hello,

I left the computer on for 48 hours and the problem is still the same. I have two "UnflushedBytes" values, the first is at 0 and the second is a negative number that keeps growing. Is it possible to "reset" this folder ? If I lose the content, it doesn't matter. 

Thank

**Comment by strib** [comment]
Hmm, sorry about that, I have no idea why it would show a negative number.  Must be related to all the other bugs (which I'm fixing -- see the PRs that mention this issue).

Yes, we can fix the folder manually, I was just hoping it would fix itself.  As of yesterday afternoon (US Pacific time) the device was still uploading new data, so there's still hope, but I guess it's time to take some action.  First you should double check that you have all the data in the folder backed up somewhere else -- if not, you can copy it out from your device `portable1` before the next step.

Then, if you want us to reset your folder, please run this command on a currently-valid keybase device, and substitute the current date and time where indicated:

```
keybase sign -m "<DATE_AND_TIME>: Please reset folder /keybase/private/kernelpanik,qzll because of a Keybase bug that made it unreadable."
```

and post the results here.

Note there are a few other recovery options we can look into if you prefer.  1) I could roll back the versions of this folder until we find one that is readable; It would be a little harder than a full reset but you'd only lose the most recent data. 2) I could write some new code that could more easily recover data from `portable1`, and ship a special Keybase release to you with this code.

Let me know if you want the full reset by posting a signed message here, or one of the alternatives above.

**Comment by KernelPan1k** [comment]
Hello, don't be sorry Keybase is a great tool. I'll let the computer turn on a little longer and if in 3 days the problem is still present, I'll see to do a reset.

Thank you for your help

**Comment by KernelPan1k** [comment]
Hello, 

I choose a complete reset of the folder. Here is the signed message:

BEGIN KEYBASE SALTPACK SIGNED MESSAGE. kXR7VktZdyH7rvq v5weRa0zkH3TpCA q1qsw6z4Q1h59bQ mxWKJfPv8mPey05 T4T1gjEBAr3m5kM gZ2yFyyjHFma78y 5JlafZB0I0bphBa fPznyZosnPYOh1e pkTgdjZyoGhrf3W rjeMWm9vifA75ap r30TBAJiSr5s1TC 8y8xFjdGzpW15ke DBeN1PUg23JVZOt TFgt0rx58gPDFsK mIObAPheJ7z3VR0 xuI7sWfjXQJOIDn adTDeAYEX1XyLcH wSEN6mvldeUtCk9 nyz17Vt7Lgrewxc xbLjkgUNxVczo9w mN1xTZdYO7kumGd 12yBCx4q9UUPC11 xtSydLflPKaBKT0 VL7AVEMQ. END KEYBASE SALTPACK SIGNED MESSAGE.

Thank you

**Comment by strib** [comment]
Ok I reset the folder.  You now need to run this command once, from any Keybase device:

```sh
keybase fs reset /keybase/private/kernelpanik,qzll
```

After that you should be able to re-access the folder again, and re-add data to it.

Also, you should shutdown Keybase on the `portable1` device, and the run this command:
```sh
mv $HOME/share/keybase/kbfs_journal/v1/01205789bee0829e214e0c030acc7d439dda-0d43f40b7298ce31 HOME/share/keybase/kbfs_journal/v1/0d43f40b7298ce31.bkp
```
and then restart Keybase.  This will stop all background upload attempts that are still happening from that device.

Hope this finally fixes everything for you; please close this issue if everything looks good.  Thanks for your patience!
