### ISSUE TITLE
Reset private folder request

### ISSUE THREAD

**Issue by scrothers** [keybase/client#18054]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

I crothers on Keybase.io (https://keybase.io/crothers) wish for the Keybase support team to reset my public and private folders for my account, because at one point I deleted all my active devices without overlap.

I've been unable to access my folders for "a very long time", but now I wish to use Keybase more, so I need this reset.

The date is June 22, 2019 and it's approximately 11:30PM -5 EST time.
-----BEGIN PGP SIGNATURE-----
Version: Keybase OpenPGP v2.1.0
Comment: https://keybase.io/crypto

wsBcBAABCgAGBQJdDvJxAAoJEEoU4yT9fwYWR3cH/3jZkLd6R8yAMO3OSgDgyZOc
nMdSupGbyFAaOr6Ky0Q4slMefXFNqiOQLZLPha5NQFl1e57SbnrAlUlP604aQRS4
CERGcAZWiqcp4D7Hipo46VTbNIuC4EdPgQts8JuBL4y4nOJgpk2p+vZ0clbcQy88
2RqThHsm6uy73jBjxjmJmCO6qcroEn+xdSMo6ZGWjUzXiFAa33ZZ02J8y4h+Ajgo
58rpaEv8c9F/ho8N/dgyh6F4q2WPnX8vMR1efVEqnapRJ041C883y51rU6/Frklx
paTeQc0GNfXDtjOEcF/6wgJUeb2H93vlj9qu0quiR2tNnqFTFXwDV7z+ay0ADto=
=UA24
-----END PGP SIGNATURE-----

**Comment by keybase-travis** [comment]
Hello, I can reset your account, but it's a last-ditch recovery solution.

You'll lose all of your KBFS, git and chat data. You'll also lose all of
your followers, your proofs and who you are following (you can reestablish
these individually after the account reset).

Also, some users have reported UI bugs after an account reset.  We are
working to address these issues as fast as we can.

Please confirm it's OK to reset your account.

**Comment by strib** [comment]
@maxtaco 	@keybase-travis I plan to look into resettng these folders later today.

**Comment by strib** [comment]
@scrothers I get a "Hash mismatch" error when I try to verify your signed message, both on the keybase website and from the command line. I suspect github formatting changed it.  I'd prefer a messaged signed from the Keybase CLI if possible which won't be format-dependent, something like this:

```
keybase sign -m "<DATE_AND_TIME>: Please reset folder /keybase/private/crothers because all the devices that have access have been revoked."
```

and post the results here.

If you want to stick with PGP signing, maybe you can enclose the message in triple-backticks in the github message, so it doesn't get formatted?

Note that there should be no need to reset the public folder, as it is not keyed for old devices.  if your public folder isn't working, that sounds like a separate issue that should be dealt with.  If so, we can investigate if you do a `keybase log send` and report the resulting log ID here.  (For what it's worth, i can read your public folder just fine from here.)

**Comment by scrothers** [comment]
@strib,

You're correct, my public folder is actually fine and I can create/edit/delete files out of there.

As for my private folder:
```$ keybase sign -m "`date`: Please reset folder /keybase/private/crothers because all the devices that have access have been revoked."```

BEGIN KEYBASE SALTPACK SIGNED MESSAGE. kXR7VktZdyH7rvq v5weRa0zkG7s0HO TtVaF6shcjvGO1L DrjxB7bOjPicCDO 3Pq7tv6DhucUJwN io9wDxsHABIK8dP Trnf5gNp2wIzIJ1 0cRm8hNcTPBr7C7 EHCGOrAWgnpzO2x 3Ojaczrv4uWie4x TmfZz3dFMBx2oNk a2HPGfYTI58xHnS 1FZin9aQeEC7Ray NbJvFaIVHcnw9Ys 2EMGSJwpE12weoB 4fb2tOy66FBrUiR y9EtHbBfMZNWBPn VzFNKP0Ss2D3ic4 AgfQZ8ShqfT9Grn uwYprJxxE7bY4zo yPdgswPyquuTH19 XCOdFa3P110wTzF 3tOqauDe2nWZtwC FMilwOy5VjrLDbZ T0Y702A. END KEYBASE SALTPACK SIGNED MESSAGE.

Thank you!

**Comment by strib** [comment]
I reset the folder.  Please check it out and close this if everything seems ok.  (Might require a Keybase restart.)

**Comment by scrothers** [comment]
@strib, perfect! Both my private folder and private git repositories now function correctly :)
