### ISSUE TITLE
Can't mount kbfs file system

### ISSUE THREAD

**Issue by afk-mario** [keybase/client#18098]
[write something useful and descriptive here]

my log id: 8a40a2a55e474d743dc9861c

**Comment by strib** [comment]
@afk-mario it looks like you might have set your local user mountpoint to `/keybase`, which is actually the mountpoint for a redirector process that allows multiple users on the same machine to all share `/keybase` path for access to their own individual mountpoints (mounted by default at something like `/run/user/1000/keybase/fs`, depending on your distro).

You can clear your setting to get the default back with:
```sh
keybase config set -c mountdir
```

Or set it to something else, say:
```sh
keybase config set mountdir $HOME/kbfs
```

and then restart all of keybase, and things should work again.

**Comment by afk-mario** [comment]
That did the trick thanks!
