### ISSUE TITLE
Unable to rekey some private folders

### ISSUE THREAD

**Issue by Domon** [keybase/client#18102]
Hi,

All my existing devices cannot open some private folders. Those devices are probably too new.

I've tried `keybase rekey paper` with an old paper key but it doesn't seem to work.

`keybase rekey status` returns `No TLFs need rekeying.`.

Is resetting the folders the only way to move forward? Or is there anything I could do to confirm my existing keys are definitely unable to access those folders?

Thanks.

**Comment by strib** [comment]
@domon if you run `keybase log send` and report the resulting log ID here, I can check each folder with problems individually and let you know if they can be recovered.  If `keybase rekey status` doesn't show anything, that could mean that none of them are recoverable by you.  But if they are folders with other users, they might be able to recover them.

If your private personal folder is one of them though, and you've revoked or lost all the devices that once had access, resetting is the only option.  (Note that recent folders can no longer get into this state -- either you have access to the folder or you have to reset your whole Keybase account, nothing in between.)

**Comment by Domon** [comment]
> @Domon if you run `keybase log send` and report the resulting log ID here, I can check each folder with problems individually and let you know if they can be recovered.

Hi @strib,

I have sent the log. The log ID is `fccdd83da90f58d9a74a851c`.

My private personal folder is one of the folders that I can't access.

**Comment by strib** [comment]
Ok, I see two problems with issues, and they both need to be reset.  I will send you a private message on Keybase with instructions on how to authorize them to be reset, so I don't expose the other private folder name here on github.

**Comment by strib** [comment]
We reset the folders and all is good now. Thanks for the report!
