### ISSUE TITLE
Keybase stuck on "Loading..." on Windows 10 1903

### ISSUE THREAD

**Issue by whalehub** [keybase/client#18105]
Are you ever going to fix this issue?

https://github.com/keybase/client/issues/11235 https://github.com/keybase/client/issues/5399 https://github.com/keybase/client/issues/10681 https://github.com/keybase/client/issues/5418 https://github.com/keybase/client/issues/14222
https://github.com/keybase/client/issues/10241 https://github.com/keybase/client/issues/11765 https://github.com/keybase/client/issues/7397 https://github.com/keybase/client/issues/4456 https://github.com/keybase/client/issues/5928
https://github.com/keybase/client/issues/5975 https://github.com/keybase/client/issues/5733 https://github.com/keybase/client/issues/11731 https://github.com/keybase/client/issues/5839 https://github.com/keybase/client/issues/4075

**Comment by maxtaco** [comment]
It's not just a single issue, and we can't repro it. Send us a long and we'll check it out.

```keybase log send```

**Comment by whalehub** [comment]
Log ID: a5d506604394163c30ef9b1c

**Comment by captainkovalsky** [comment]
I can not access to my files((((

**Comment by AltVRat** [comment]
My main PC Mobo died and I updated/uninstalled off both iPhones. I have the HDD from my old computer on my new PC but when I launch Keybase.exe from the folder called GUI I get stuck on loading screen. I'm trying to open v3.0.11. Any way to add a new device from the website? Or restore from iPhone backup (unencrypted)? ![keybase](https://user-images.githubusercontent.com/20691259/64756212-f6cf7800-d4e2-11e9-9fcd-113d71ab4c63.png)

**Comment by AltVRat** [comment]
[keybase.app.log.txt](https://github.com/keybase/client/files/3603852/keybase.app.log.txt)

**Comment by AltVRat** [comment]
Or move old config files from H Drive to a new installation folder on current PC?

**Comment by AltVRat** [comment]
Hello?
