### ISSUE TITLE
Error accessing /keybase/private/madprime,cjb

### ISSUE THREAD

**Issue by madprime** [keybase/client#1824]
Keybase GUI Version: 1.0.9-20160125203736+0906d7c

I can write to `/keybase/public/madprime` and `/keybase/private/madprime`, but not `/keybase/private/madprime,cjb`. Here's the kbfs log file: https://gist.github.com/madprime/c5e89a0c56f9c7a9ee83

**Comment by maxtaco** [comment]
Our first bug report! Cue the balloons and confetti!

**Comment by madprime** [comment]
:confetti_ball: Happy to help, looking forward to this! :)

**Comment by aalness** [comment]
Thanks @madprime! You helped us flush out 2 bugs: We had a server-side bug when a folder was created for a user prior to that user having any registered devices. And then we had a client-side bug on mishandling the rekey requests for such folders.

The back-end has been redeployed and there's a new build of the client available, `keybase_1.0.9-20160126170800+276b82d`. Note though, that @cjb will need to have at least one of his devices online for you to be able to access the specific folder in this issue. I'll keep this issue open until we confirm you can access that folder. Thanks again!

Direct URL to update:

```
BEGIN KEYBASE SALTPACK ENCRYPTED MESSAGE. kiS2n6W4XB3QNEC peK0Xp8djETWqei 55BNVZBDgH4Q9Gv 3ycwBcwS01lHdDk uDRptmfGgxLligq wdmeAeGHPlTNOLb mZz4pcwDhp8npjd NDiO14qGxGoqny9 V01KYwLHnMVTmsc wnDhtV42Wsf2K79 bTAFV9Ok6gPs7GC nyyJuSatOiA6iZE Ko0sBjaRJ7NOUSD pVkbEP1J523xBi4 avUVw1e5EJwcNcS jlE4CQP0BluAOIr NFJWnSekmERCit1 gh3uWFWetVYqmvK QY0C54EKyVEo3sG pZUF2ImNuicv8fW y5spvG7Xa5BBk6A Y2ABMfz0oSCRT1n qs24dO2H1dYa7dE OUY26rbPIiBmhSB Gh80TMc2q6TOBF7 7ZTMIEiFHzqYu4x ZTjvcA7ee8vE11q Lxkk6kzKjWJtGoA Wn93PGTdJAR6tGL qkNGpRQENWS4nlz I3tOkMuPIh1ycH6 uoHVLCpj2O5y3EH S1uIIwDsMOSCgxE Z2Yp6J6nFIkREFp xIRSTgIlnQaKC74 8dQtdvqJkUtFmn9 DWNjpxH9Idt6qTs 9RVQqyY1liFWMIm 7nWcALHWtRi43gL Z1ax1NqpxAfSnMs Yjqch8yeceo0DWc KFTULv9aFQsBGjs qSRHagIMuklrL8G m3mfx8rzDq5234V yMWNs5pg1OQduMV 2wwfPAqWJoZbzJh NbT5mBk3t6Ca2J4 yJ2arLvda3zO0Q1 yMkYOym56HaPYNB kNSHFtdROpi4Oiw lHCSHsSvkDJTxlJ 3ZrkaR9HXyau4aA YsQ74NKeu9sgJaV 814Fd6Vf14TNsXG srUK9K6RrVMKprG DwokN1aK2NWnCTo cfYhUvsp50MFn0e CCafypqh71IZzLz CkWZdnUGGeJ9oH4 A1uoSHlpLQ4C1He INDGbFxxj6rmiL1 efXLAXit8rj9Dy4 zmbSXZcciYBAC94 iZUsPuoPAJcg0lu 6fyTNlKlI35O2uF oHquKR8grjjWIPG FRj7JLCjQ6InwCa 3AwDqQvEQvXxnQs boTrqVEz0xdzMSu U5nN1z742qswGlW 4nQNejbcfIMTs6F Yvb1RGF2dGhtgB6 vGzGZI1uXg49fgC bc5vvqBR7gdns2M pCkaacoZ2wkJ3lq tWFvxXpSfgC7FFI hjGCL0In6aSTc6E YkGdWUAiAJiwf0S u62SveidWPKOKXA 09dZ9fFthhPUxLT HPjIFCOGzEbwvYQ kzCHQTsgHx1ktLM de4eWDwSqWT3vcU 0Pd6txwAmSMSMFJ Er0HiRS9eG46Bi4 PyQC7JgtJ9uOchc qWx5pRC1MOcyV1k bezUoiWSfhr6gbU BKA43Nz7iIAnaee s71FM1r73HozyFI xKRqR0gBsFCSfkU YDNGytY2cq8iTtw aoV4PgHf7ehv8A2 2BdJrmpjieQCyt7 eNTI8WSHs7ajHic a0eqkzjc3UEkIpv 0y7YShmIBN7ujLp I0FSOZHMwfIEHlb CAj2qXJEM7sUZ3Y rKtKarEHwl8vPAe BaLw2I4ckfBN6zG ptYMlDdh6Arfo3K CdaHiZV7skUF3Om xQKaa22hSTXJI1A StLZLRmk0rKaej8 g6Sk. END KEYBASE SALTPACK ENCRYPTED MESSAGE.
```

**Comment by madprime** [comment]
Sorry, still not working. I have what appears to be the same error.

@cjb says he is online.

My version looks updated:
> keybase version                                                                                                                                                                                                                                  Client:  1.0.9-20160126170800+276b82d
Service: 1.0.9-20160126170800+276b82d

A gist of the kbfs log file: https://gist.github.com/madprime/8a6834a933c990c74226

**Comment by madprime** [comment]
It works now! Awesome :)

**Comment by strib** [comment]
Yay!  The latest issue was that cjb has tracked you before you reset your Keybase account a few months ago, and his client refused to rekey for you until he tracked your new account.  We discovered a few improvements we can make to make this process a little more obvious and filed tickets on ourselves.

Thanks for testing, and thanks for the report!
