### ISSUE TITLE
Unable to see files under /keybase

### ISSUE THREAD

**Issue by syerrawa** [keybase/client#18354]
keybase folder in mac shows empty. However, keybase UI shows that there are files in it.

**Comment by syerrawa** [comment]
Also under keybase settings -> files I see "Yes, enable" button. But nothing happens when I click on it.
It shows red text "Action needed!" beside the Finder integration section.

Please help

**Comment by syerrawa** [comment]
Here is the log ID after running ``` keybase log send

**Comment by syerrawa** [comment]
Here is the log ID after running `keybase log send`

**Comment by syerrawa** [comment]
Here is the log ID `67b3b8dcd43792d4d360941c` after running `keybase log send`

**Comment by strib** [comment]
One quick suggestion: looks like you're on a slightly old version, maybe try upgrading using `keybase update check` to quickly see if that solves anything?

**Comment by strib** [comment]
Seems like your operating system doesn't have authorization for the keybase kernel module.  You can try the workaround discussed here: https://github.com/keybase/client/issues/11763#issuecomment-410790612

**Comment by syerrawa** [comment]
Ok let me try that.

**Comment by syerrawa** [comment]
After doing the above steps mentioned my keybase folder got created under Volumes -> Keybase (syerrawa)


Why is that? Shouldn't /keybase be at the root level?

**Comment by strib** [comment]
You should have both.  `/keybase` is a redirection point so multiple users on the same computer can use the `/keybase` paths.  If you're still not seeing `/keybase` after a Keybase restart, you can try:

```
keybase uninstall -c redirector
keybase install -c redirector
```

**Comment by syerrawa** [comment]
Got it.

The uninstall and install worked. 

Thanks.

**Comment by strib** [comment]
Great!
