### ISSUE TITLE
cd’ing to /keybase/private/{username} gives an i/o error

### ISSUE THREAD

**Issue by capndesign** [keybase/client#1848]
```
mbp-matt:~ mattjacobs$ cd /keybase/private/capndesign
-bash: cd: /keybase/private/capndesign: Input/output error
mbp-matt:~ mattjacobs$ ls -al /keybase/private/
mbp-matt:~ mattjacobs$
```

Relatedly, when I try to create or access a folder from the menubar duder, it does nothing.

Keybase GUI Version: 1.0.9-20160129170007+4c520a1

**Comment by strib** [comment]
Thanks for the report capn.  Would you be willing to share your logs to help us debug?  They may contain somewhat sensitive metadata like file names and sizes.  For Linux, the logs are in ~/.cache/keybase, and on OSX they are in ~/Libary/Logs/keybase*.

You probably shouldn't post them here, but if kbfs is working you can put them in /keybase/private/capndesign,strib.  Otherwise, maybe email them to me (gzipped) at strib at keyba.se.

If you're not comfortable sending logs, that's fine, I'll be asking you for more details about the setup and error experience.  We do know of a few different outstanding bugs you might be hitting.

**Comment by capndesign** [comment]
Sent!

**Comment by strib** [comment]
Thanks @capndesign.

Looks like for some reason kbfs can't communicate with the keybase service.

```
2016-01-29T15:56:47.646709 ▶ [DEBU kbfsfuse folderlist.go:40] 22c9 write unix -> /Users/mattjacobs/Library/Caches/Keybase/keybased.sock: write: broken pipe [tags:FID=xbHOC-KuaBJGUVnnlr3nTw]
2016-01-29T15:56:47.646732 ▶ [DEBU FUSE serve.go:817] 22ca -> [ID=0x7] Lookup error=EIO: write unix ->/Users/mattjacobs/Library/Caches/Keybase/keybased.sock: write: broken pipe
```

But his service log shows that it's running during that time:

```
2016-01-29T15:23:05.080458 ▶ [INFO keybase socket_nix.go:18] 00c Binding to unix:/Users/mattjacobs/Library/Caches/Keybase/keybased.sock
...
2016-01-29T15:56:42.093054 ▶ [DEBU keybase api.go:210] 0b5 | Result is: 200 OK
2016-01-29T15:56:42.093197 ▶ [DEBU keybase engine.go:66] 0b6 - RunEngine(FavoriteList) -> ok
2016-01-29T15:57:44.173105 ▶ [DEBU keybase engine.go:65] 0b7 + RunEngine(FavoriteList)
2016-01-29T15:57:44.173199 ▶ [DEBU keybase login_state.go:897] 0b8 + Account "LoggedInProvisionedLoad"
```

@capndesign: can you please post the output of `keybase status`?  (Or email it to me, if you prefer, though I don't think there's anything sensitive in it.)

**Comment by capndesign** [comment]
```
mbp-matt:Logs mattjacobs$ keybase status
Username:      capndesign
Logged in:     yes

Device:
    name:   My Laptop
    ID:     45d442ba191e34218ab711722b684418
    status: active

Local keybase keychain: locked
Session status:         no session

KBFS:
    status:    not running
    version:   1.0.0-20160129170046+4c520a1
    log:       /Users/mattjacobs/Library/Logs/Keybase/keybase.kbfs.log

Service:
    status:    running
    version:   1.0.9-20160129170007+4c520a1
    log:       /Users/mattjacobs/Library/Logs/Keybase/keybase.service.log

Platform Information:
    OS:        darwin
    Runtime:   go1.5.3
    Arch:      amd64

Client:
    version:   1.0.9-20160129170007+4c520a1

Desktop app:
    status:    running

Config path:        /Users/mattjacobs/Library/Application Support/Keybase/config.json
Default user:       capndesign
Provisioned users:

command-line client(s):
    keybase status [pid: 8355, version: 1.0.9-20160129170007+4c520a1]
```

**Comment by strib** [comment]
Thanks.

This starts happening after KBFS hits a timeout:

```
2016-01-29T15:51:31.676618 ▶ [DEBU kbfs kbfs_ops.go:116] 8a3 GetOrCreateRootNode ([redacted], true, ) [tags:FID=bqpwFKX6Rf_ZyU3GzHydmA]
2016-01-29T15:51:50.698941 ▶ [DEBU kbfs kbfs_ops.go:117] 8a4 Done: context deadline exceeded [tags:FID=bqpwFKX6Rf_ZyU3GzHydmA]
2016-01-29T15:51:50.699027 ▶ [DEBU kbfsfuse folderlist.go:40] 8a5 context deadline exceeded [tags:FID=bqpwFKX6Rf_ZyU3GzHydmA]
```

In the service log, this time shows:

```
2016-01-29T15:51:31.839055 ▶ [DEBU keybase user.go:420] 4e2 - VerifySelfSig via SigChain
2016-01-29T15:51:31.839205 ▶ [INFO keybase log.go:239] 4e3 {unix} Call canceled after reply sent. Seq: 43
```

This cancel happens way before the KBFS operation actually times out.  @maxtaco does this mean anything to do?  Possible bug where the service doesn't accept new requests once one has been canceled?

**Comment by capndesign** [comment]
Here is some other background information.

* Initially, I had the CLI installed via homebrew. It wouldn’t let me log in, but I tried quitting the app and then it did.
* Privately, Chris told me to uninstall the homebrew and npm versions, which I did.
* I opened the app and tried adding a new folder via the menubar and it hung, with the cursor stuck in "text input" mode. I ended up killing the app’s main process (which made my Finder go a bit batty, btw). The app responded when I relaunched it, but then same problem with adding folders.

**Comment by maxtaco** [comment]
@jzila any RPC insights on the above?

**Comment by maxtaco** [comment]
@capndesign do you see a dialog window asking for your passphrase?  It seems like your passphrase isn't known for the session and your key is still locked.

**Comment by capndesign** [comment]
I bet I entered it in the old CLI. I'll try logging out when I'm back in
front of my computer.

**Comment by maxtaco** [comment]
maybe try a logout / login. thanks!

**Comment by maxtaco** [comment]
@strib my best bet is that this is caused by a clash between the old brew install and the new DMG-based install, in which potentially KBFS was attempted to connect to the old process.

**Comment by jzila** [comment]
@maxtaco still need me to investigate?

**Comment by maxtaco** [comment]
I'm not sure I have a coherent theory as to what's going on here, on second thought. I'm not fully sure why we'd see those RPC failure messages

**Comment by capndesign** [comment]
Good news, everyone. Whatever version you pushed out tonight fixed it all. I will not send everyone encrypted cat gifs.

**Comment by strib** [comment]
Ok, I'm going to call this a win.  Thanks!
