### ISSUE TITLE
It seems keybase broke my dependency tree?

### ISSUE THREAD

**Issue by ruixif** [keybase/client#18490]
I installed keybase on my Ubuntu 18.04 system but the dependency tree broke after the installation. 

What does the "sudo apt-get install -f" exactly do when i try to install keybase on Ubuntu18.04?

**Comment by heronhaye** [comment]
It installs missing dependencies needed by Keybase. I've never heard of it messing up peoples' dependency trees, sorry about that. You could try uninstalling and reinstalling Keybase to see if it helps.

**Comment by heronhaye** [comment]
We've updated our install instructions to use `apt` to install dependencies directly, so this shouldn't be an issue in the future. Sorry about the trouble.

https://keybase.io/docs/the_app/install_linux

**Comment by heronhaye** [comment]
zp
