### ISSUE TITLE
Files not showing up on keybase.pub but on the windows app it shows its been added

### ISSUE THREAD

**Issue by jaygaga** [keybase/client#18509]
I uploaded files to https://keybase.pub/mintonium on the app in windows it shows it has been uploaded but when i visit the keybase pub link its showing empty on the browser why please?

**Comment by strib** [comment]
This is a known bug on our side that happens sometimes when users reset their account.  Should be fixed now.

**Comment by jaygaga** [comment]
Ok thanks but incase there is  a reset of account in future what can i do to quickly resolve this issue? or is there a normal waiting period of how long if there is?

**Comment by strib** [comment]
No, this is really rare so we don't have a process for it, just let us know.  Ideally you can avoid resetting your account by making a backup paper key and writing it down somewhere safe.
