### ISSUE TITLE
Linux keybase app's notification page does not share share the same template with other settings 

### ISSUE THREAD

**Issue by thecsw** [keybase/client#18502]
# Introduction

Hello there! I noticed a bit of a weird inconsistency in design templates on the settings page. 
Some background: 

### My system
``` sh
~ λ uname -a
Linux ctu 5.2.1-arch1-1-ARCH #1 SMP PREEMPT Sun Jul 14 14:52:52 UTC 2019 x86_64 GNU/Linux
```
### My keybase install (most recent)
``` sh
~ λ sudo pacman -Qi keybase-gui
Name            : keybase-gui
Version         : 4.2.0-1
Description     : GUI frontend for GPG with keybase.io
Architecture    : x86_64
URL             : https://keybase.io/
Licenses        : BSD
Groups          : None
Provides        : None
Depends On      : electron  keybase  kbfs
Optional Deps   : None
Required By     : None
Optional For    : None
Conflicts With  : None
Replaces        : None
Installed Size  : 33.70 MiB
Packager        : Eli Schwartz <eschwartz@archlinux.org>
Build Date      : Wed 10 Jul 2019 02:24:59 PM CDT
Install Date    : Sun 21 Jul 2019 06:52:05 PM CDT
Install Reason  : Explicitly installed
Install Script  : No
Validated By    : Signature
```
# Issue

Please see three images included and notice that the notification tab has the setting name and the *go back* button disappeared. This element change just makes the whole left tab to shift, which is not the best experience with jumping tabs.
## Chat (has the tools)
![DeepinScreenshot_select-area_20190721224815](https://user-images.githubusercontent.com/16922860/61605354-afc3b580-ac0a-11e9-852d-69d17c21f843.png)

## Notifications (doesn't have the tools)
![DeepinScreenshot_select-area_20190721224751](https://user-images.githubusercontent.com/16922860/61605353-af2b1f00-ac0a-11e9-8b43-b9d66d1c0e71.png)

## Feeback (has the tools)
![DeepinScreenshot_select-area_20190721224835](https://user-images.githubusercontent.com/16922860/61605355-afc3b580-ac0a-11e9-9d04-ec1e603269bc.png)

# Conclusion

I am not sure if this is intentional or not but it can bother some users due to its inconsistency.

**Comment by heronhaye** [comment]
Thanks for the report, it'll be fixed in the next release. You can check it out on the [nightly](https://keybase.io/docs/linux-user-guide#nightly-builds) if you like.
