### ISSUE TITLE
clean out the issues

### ISSUE THREAD

**Issue by wmertens** [keybase/client#18503]
At the moment of writing there are 2613 open issues, the oldest last updated in 2015.

I understand that this is most likely because Keybase uses a different internal issue tracker, but as a consumer it doesn't inspire confidence in the product.

Perhaps you could install an issue bot that auto-closes issues after a warning? They can always be reopened.

Same with those 118 PRs, perhaps auto-close really old ones with merge conflicts?

**Comment by alexmarkley** [comment]
:+1: I'm really not sure how to report bugs because the issue queue appears abandoned.

**Comment by Rudi9719** [comment]
Use [keybase/keybase-issues](https://github.com/keybase/keybase-issues) please :)

**Comment by wmertens** [comment]
Closing in favor of https://github.com/keybase/keybase-issues/issues/3471
