### ISSUE TITLE
Keybase --home option fails without absolute path

### ISSUE THREAD

**Issue by stanford-scs** [keybase/client#18541]
keybase does not handle relative paths with the `--home` or `-H` option, but instead fails in a very confusing way.

To reproduce, run:

```
pkill keybase
keybase -H $PWD/kbtemp id chris
```
And it works fine, while if you run:

```
$ pkill keybase
$ keybase -H kbtemp id chris
Failed to reach user-level systemd daemon.
â¶ INFO Starting background server with pid=10595
â¶ ERROR dial unix kbtemp/.config/keybase/keybased.sock: connect: no such file or directory
```

**Comment by maxtaco** [comment]
cc @heronhaye 

thanks for the feedback!

**Comment by heronhaye** [comment]
Should be fixed in next release. You can check it out on the [nightly](https://keybase.io/docs/linux-user-guide#nightly-builds). Thanks for the report!
