### ISSUE TITLE
Ubuntu upgrade loop, gui not launching

### ISSUE THREAD

**Issue by IEWbgfnYDwHRoRRSKtkdyMDUzgdwuBYgDKtDJWd** [keybase/client#18550]
Have not used keybase in a while, used to use gui on ubuntu. I tried launching it today and nothing happens, but the CLI works.

I downloaded newest version and updated/installed, still same issue only CLI no gui. Tried removing/purging/reinstalling. Nothing works. When I run_keybase I keep getting

> ▶ WARNING Please upgrade keybase for new features, improved performance, and security upgrades.
> ▶ WARNING Upgrade recommended to client version 2.11.0 or above (you have v4.2.1-20190718132443+117e8ce562)
> ▶ WARNING To upgrade, run the following command:
> ▶ WARNING     sudo apt-get update; sudo apt-get install keybase && run_keybase

I have already updated, and installed -f the newest version multiple times.

**Comment by heronhaye** [comment]
That's odd, could you do a `keybase log send`? Also, what is `keybase version`?

**Comment by IEWbgfnYDwHRoRRSKtkdyMDUzgdwuBYgDKtDJWd** [comment]
Thanks for reply, as for version this is strange, as it says above in the error message it says I have v4.2.1, however in keybase.info it says v2.4, in my dpkg log it says it installed 4.2.1, and in opt/keybase version it says v4.1.0

So apparently there is no consensus. And how do I view the log files myself? I searched everywhere for it, but the only logs I could find were from when I used to use keybase like a year ago.

**Comment by heronhaye** [comment]
Very weird. There might be some conflicting versions going on. Usually your log files are in `~/.cache/keybase/*log`. 

Where does `$(which keybase)` point to?

Have you always installed Keybase from the .deb provided on keybase.io? You might try nuking the keybase folder under `/run/`.

**Comment by IEWbgfnYDwHRoRRSKtkdyMDUzgdwuBYgDKtDJWd** [comment]
turning it off and on again of course worked.

**Comment by heronhaye** [comment]
All right, glad you got it working (`keybase version` should return 4.2.1). Feel free to make another issue if you run into more trouble.
