### ISSUE TITLE
I get the error "ERROR hub-virus doesn't exist" when trying to import into local keychain

### ISSUE THREAD

**Issue by tskardal** [keybase/client#18619]
Keybase GUI Version: 4.2.0-20190710181120+e7c0bdc4a2

This is the output I get when i run `keybase pgp pull-private <fingerprint>`:

```
❯ keybase pgp pull-private <fingerprint>
PLEASE READ THIS CAREFULLY -- PRIVATE KEYS ARE AT STAKE!

  This command will import PGP private keys from KBFS
  (found in .keys/pgp), and export them to the local GnuPG keychain. They might have been
  put there via keybase pgp push-private. After this
  operation, these keys will be available for local GnuPG operations.

Really pull your PGP private key from KBFS? (type 'YES' to confirm): YES
▶ ERROR hub-virus doesn't exist
```

**Comment by maxtaco** [comment]
Interesting, can you navigate to that folder on KBFS?

```
/keybase/private/<you>/.keys/pgp
```

(cc @strib)

**Comment by maxtaco** [comment]
(And BTW `hub-virus` is an obfuscated path name, seems like it made it all the way up to the terminal)

**Comment by tskardal** [comment]
> (And BTW `hub-virus` is an obfuscated path name, seems like it made it all the way up to the terminal)

OK, that explains why I didn't get any hits when searching similar errors!



> Interesting, can you navigate to that folder on KBFS?
> 
> ```
> /keybase/private/<you>/.keys/pgp
> ```

I don't have a `.keys` folder there. (First I didn't have a `/keybase` either, but I got it after enabling browsing with Finder. I assume this is the same as KBFS).

FWIW, I just recently reinstalled the Keybase.app (yes, I'm on macOS), and then imported one of my keys manually with `keybase pgp export` + `gpg --import`. After this I noticed the `pull-private` sub command.

**Comment by maxtaco** [comment]
Aha. Did you ever run `keybase pgp push-private`?

**Comment by strib** [comment]
@maxtaco Re: `hub-virus` yeah it's tricky with errors because they're printed in the logs, so I erred on the side of obfuscation there.  If this is going to be a common thing we can fix it for this case, but seems like it would be better for the CLI command to catch this case and print something a little better there.

**Comment by tskardal** [comment]
> Aha. Did you ever run `keybase pgp push-private`?

Probably not!

**Comment by maxtaco** [comment]
Nope, you need to opt in after ready a scary warning, we would never move your private PGP keys without explicitly asking and warning you first!

**Comment by tskardal** [comment]
I see. I guess the only issue then is the content of the error message. Do you want me to close this issue, or should I leave it open so it can be closed when the error message is improved?

**Comment by maxtaco** [comment]
Sure, we'll make a ticket to fix the error message.

**Comment by tskardal** [comment]
I've hesitated to close this as I haven't seen any matching issues being created. Anyway, I'll close it now, and assume you have everything under control @maxtaco  😎
