### ISSUE TITLE
Failed to list folder & load file metadata

### ISSUE THREAD

**Issue by irfansharif** [keybase/client#18640]
I no longer have access to one of my devices, and the file system is no longer usable as a result. Is it possible to reset it on the server's end?

Log ID: d73acdc57e05580e6ced691c

**Comment by strib** [comment]
If you want us to reset your folder, please run this command on a currently-valid keybase device, and substitute the current date and time where indicated:

```
keybase sign -m "<DATE_AND_TIME>: Please reset folder /keybase/private/irfansharif because all the devices that have access have been revoked."
```

and post the results here.  (I can do it in the morning tomorrow.)

**Comment by irfansharif** [comment]
BEGIN KEYBASE SALTPACK SIGNED MESSAGE. kXR7VktZdyH7rvq v5weRa0zk7p0FPb nQ5mtGOFVP4Uo4J hzoiY3ojcPsu2oc LLUbWCw6dkeEpid T4w5tYFDX4Zs17M eDd00pVlL2zYTpV LRpiYnm1WMS7awG F0mMOD3vHqk34T2 WYX63QvZJUBhOSM wdTEMDzfeK28Pch agBGeyTwHOuWbQd 822KRZvUaH0zDAI QFEESw9S0jezoDD ncHhcDmZqRwjydP kxKhwZbrSox9SYj pV7iabYY1tBJQZD GtMR861g3iihOGd UBywac9d1oePqX7 hjoxYefsBSlljMf 6OkpHO6K3ckl6VW ft6BeaT4sYI0jb1 S5zGqPnq1NfLQz3 aE3FLt9Vhr6Y9Yp rEE. END KEYBASE SALTPACK SIGNED MESSAGE.

Thanks!

**Comment by irfansharif** [comment]
Ping.

**Comment by strib** [comment]
Sorry for the delay!  I reset the folder.  Please check it out and close this if everything seems ok.  (Might require a Keybase restart.)

**Comment by irfansharif** [comment]
Worked great, thanks!
