### ISSUE TITLE
client unable to find gpg keys, while available

### ISSUE THREAD

**Issue by rejozenger** [keybase/client#1866]
I am unable to select a key to use with keybase:

     rejo@broop-kidron:~$ keybase pgp select
     ▶ ERROR No PGP keys available to choose from.

This happens while I do have pgp keys available:

    rejo@broop-kidron:~$ gpg -K |grep ^sec
    sec>  4096R/0x0994094621DBEFD4 2009-06-26 [expires: 2016-01-30]
    sec   4096R/0x9E501484CEF8A86B 2015-01-19 [expires: 2015-07-18]

Both gnupg2 and keybase are installed using homebrew:

    rejo@broop-kidron:~$ keybase -v
    keybase version 1.0.9-0

    rejo@broop-kidron:~$ gpg --version
    gpg (GnuPG) 2.0.29
    libgcrypt 1.6.4

When run with debug mode on:

    rejo@broop-kidron:~$ keybase -d pgp select
    09:34:13.106493 ▶ [DEBU keybase json.go:50] 001 + loading config file: /Users/rejo/Library/Application Support/Keybase/config.json
    09:34:13.106655 ▶ [DEBU keybase json.go:78] 002 - successfully loaded config file
    09:34:13.109973 ▶ [DEBU keybase ui.go:451] 003 Setting GPG_TTY to /dev/ttys000
    09:34:13.110029 ▶ [DEBU keybase globals.go:205] 004 Keybase CLI 1.0.9-0
    09:34:13.110043 ▶ [DEBU keybase globals.go:205] 005 - Built with go1.5.3
    09:34:13.110052 ▶ [DEBU keybase globals.go:205] 006 - Visit https://keybase.io for more details
    09:34:13.110068 ▶ [DEBU keybase main.go:120] 007 + configureProcesses
    09:34:13.110130 ▶ [DEBU keybase install_osx.go:479] 008 + AutoInstall for launchd
    09:34:13.110198 ▶ [DEBU keybase install_osx.go:492] 009 | already installed at /Users/rejo/Library/LaunchAgents/homebrew.mxcl.keybase.plist
    09:34:13.110218 ▶ [DEBU keybase install_osx.go:481] 00a - AutoInstall -> false, <nil>
    09:34:13.110229 ▶ [DEBU keybase main.go:186] 00b | After forks; newProc=false
    09:34:13.110264 ▶ [DEBU keybase main.go:207] 00c + configureLogging
    09:34:13.110299 ▶ [DEBU keybase socket_nix.go:23] 00d Dialing unix:/Users/rejo/Library/Caches/Keybase/keybased.sock
    09:34:13.111451 ▶ [DEBU keybase main.go:209] 00e - configureLogging
    09:34:13.111504 ▶ [DEBU keybase versionfix.go:21] 00f + FixVersionClash
    09:34:13.111621 ▶ [DEBU keybase log.go:30] 010 LogHandler::RegisterLogger: {SessionID:0 Name:CLI client Level:1}
    09:34:13.111946 ▶ [DEBU keybase log.go:30] 011 + LogHandler::RegisterLogger
    09:34:13.112195 ▶ [DEBU keybase log.go:30] 012 Registering logger: CLI client @ level 1
    09:34:13.112279 ▶ [DEBU keybase versionfix.go:33] 013 | Contacted service; got version: 1.0.9-0
    09:34:13.112336 ▶ [DEBU keybase versionfix.go:55] 014 | version check 1.0.9-0 v 1.0.9-0
    09:34:13.112367 ▶ [DEBU keybase versionfix.go:57] 015 | versions check out
    09:34:13.112378 ▶ [DEBU keybase versionfix.go:23] 016 - FixVersionClash -> <nil>
    09:34:13.112393 ▶ [DEBU keybase main.go:122] 017 - configureProcesses -> <nil>
    09:34:13.112429 ▶ [DEBU keybase log.go:30] 018 Registered logger: CLI client: level 1, handle id 37
    09:34:13.112805 ▶ [DEBU keybase log.go:30] 019 - LogHandler::RegisterLogger -> ok
    09:34:13.113034 ▶ [DEBU keybase log.go:30] 01a | configured GPG w/ path: /usr/local/bin/gpg2
    09:34:13.113300 ▶ [DEBU keybase log.go:30] 01b | configured GPG w/ path: /usr/local/bin/gpg2
    09:34:13.113503 ▶ [DEBU keybase log.go:30] 01c + RunEngine(GPGImportKeyEngine)
    09:34:13.113688 ▶ [DEBU keybase log.go:30] 01d | getUI(libkb.SecretUIKind) returned nil
    09:34:13.113887 ▶ [DEBU keybase log.go:30] 01e + UIRouter.GetSecretUI
    09:34:13.114093 ▶ [DEBU keybase log.go:30] 01f + Account "LoggedInLoad"
    09:34:13.114287 ▶ [DEBU keybase log.go:30] 020 + Loading session
    09:34:13.114478 ▶ [DEBU keybase log.go:30] 021 - Skipped; already loaded
    09:34:13.114667 ▶ [DEBU keybase log.go:30] 022 + Checking session
    09:34:13.114924 ▶ [DEBU keybase log.go:30] 023 - session is recent, short-circuiting
    09:34:13.115156 ▶ [DEBU keybase log.go:30] 024 - Account "LoggedInLoad"
    09:34:13.115401 ▶ [DEBU keybase log.go:30] 025 LoadUser: {Contextified:{g:0xc8201724e0} UID: Name: PublicKeyOptional:true NoCacheResult:false Self:true ForceReload:false AllKeys:false LoginContext:<nil> AbortIfSigchainUnchanged:false ResolveBody:<nil>}
    09:34:13.115579 ▶ [DEBU keybase log.go:30] 026 + Account "G - GetMyUID - GetUID"
    09:34:13.115805 ▶ [DEBU keybase log.go:30] 027 - Account "G - GetMyUID - GetUID"
    09:34:13.116006 ▶ [DEBU keybase log.go:30] 028 + LoadUser(uid=ef8989cac4241efa0f05d5836fc75400, name=)
    09:34:13.116183 ▶ [DEBU keybase log.go:30] 029 | resolved to ef8989cac4241efa0f05d5836fc75400
    09:34:13.116395 ▶ [DEBU keybase log.go:30] 02a + loadUserFromLocalStorage(ef8989cac4241efa0f05d5836fc75400)
    09:34:13.118215 ▶ [DEBU keybase log.go:30] 02b | Loaded successfully
    09:34:13.118456 ▶ [DEBU keybase log.go:30] 02c + ParseKeyFamily
    09:34:13.179984 ▶ [DEBU keybase log.go:30] 02d - ParseKeyFamily -> ok
    09:34:13.180283 ▶ [DEBU keybase log.go:30] 02e | Loaded username rejozenger (uid=ef8989cac4241efa0f05d5836fc75400)
    09:34:13.180531 ▶ [DEBU keybase log.go:30] 02f - loadUserFromLocalStorage(rejozenger,ef8989cac4241efa0f05d5836fc75400)
    09:34:13.180734 ▶ [DEBU keybase log.go:30] 030 + MerkleClient.LookupUser(map[uid:ef8989cac4241efa0f05d5836fc75400 poll:10])
    09:34:13.180893 ▶ [DEBU keybase log.go:30] 031 + MerkleClient.LoadRoot()
    09:34:13.181163 ▶ [DEBU keybase log.go:30] 032 - MerkleClient.LoadRoot() -> &{{0xc8201724e0} 359851 [3 225 70 205 175 129 54 104 10 213 102 145 42 50 52 12 236 140 148 146] 0xc82097ecf0 {"body":{"key":{"fingerprint":"03e146cdaf8136680ad566912a32340cec8c9492","key_id":"2A32340CEC8C9492"},"legacy_uid_root":"d3450288d233fe9125d0b6f8196dbc93447bca2630300898781a637a44752032","prev":"ba7475e94fd7fd5c3ebcac5b91fd12e786c0071d73737002732657547c6d69fd9b8c9678d6fa8bdb3a1a175be5249f124875742acd29810b819f054468ed9183","root":"045008637651a96ee3c6eae4e34b1b126a7dd21522fa44d09bc544063138e3f32c348685dfcf1fa7d300233dff8ecbd8ca8670133322a31c424c792638d98055","seqno":359851,"txid":"3465744c7bb0e1a313a8a3441abb4f15","type":"merkle_root","version":1},"ctime":1454401449,"tag":"signature"} 0xc82097ef30 [4 80 8 99 118 81 169 110 227 198 234 228 227 75 27 18 106 125 210 21 34 250 68 208 155 197 68 6 49 56 227 243 44 52 134 133 223 207 31 167 211 0 35 61 255 142 203 216 202 134 112 19 51 34 163 28 66 76 121 38 56 217 128 85] [211 69 2 136 210 51 254 145 37 208 182 248 25 109 188 147 68 123 202 38 48 48 8 152 120 26 99 122 68 117 32 50] 1454401449}
    09:34:13.200768 ▶ [DEBU keybase log.go:30] 033 | LookupPath
    09:34:13.201157 ▶ [DEBU keybase log.go:30] 034 + API GET request to https://keybase.io/_/api/1.0/merkle/path.json?poll=10&uid=ef8989cac4241efa0f05d5836fc75400
    09:34:14.918734 ▶ [DEBU keybase log.go:30] 035 | Result is: 200 OK
    09:34:15.449351 ▶ [DEBU keybase log.go:30] 036 - successful API call
    09:34:15.449750 ▶ [DEBU keybase log.go:30] 037 | VerifyRoot
    09:34:15.450110 ▶ [DEBU keybase log.go:30] 038 | Merkle root: got back 359851, >= cached 359851
    09:34:15.450415 ▶ [DEBU keybase log.go:30] 039 | VerifyUser
    09:34:15.453143 ▶ [DEBU keybase log.go:30] 03a + ParsingMerkleUserLeaf
    09:34:15.453409 ▶ [DEBU keybase log.go:30] 03b - ParsingMerkleUserLeaf -> ok
    09:34:15.453732 ▶ [DEBU keybase log.go:30] 03c | VerifyUsername
    09:34:15.454029 ▶ [DEBU keybase log.go:30] 03d | Failed to map Username rejozenger -> UID ef8989cac4241efa0f05d5836fc75400 via direct hash
    09:34:15.454983 ▶ [DEBU keybase log.go:30] 03e | Username rejozenger mapped to ef8989cac4241efa0f05d5836fc75400 via Merkle lookup
    09:34:15.455264 ▶ [DEBU keybase log.go:30] 03f - MerkleClient.LookupUser(map[uid:ef8989cac4241efa0f05d5836fc75400 poll:10]) -> OK
    09:34:15.455503 ▶ [DEBU keybase log.go:30] 040 | Local basics version is up-to-date @ version 304
    09:34:15.455805 ▶ [DEBU keybase log.go:30] 041 | Freshness: basics=true; for ef8989cac4241efa0f05d5836fc75400
    09:34:15.456052 ▶ [DEBU keybase log.go:30] 042 + SigChainLoader.Load(ef8989cac4241efa0f05d5836fc75400)
    09:34:15.456297 ▶ [DEBU keybase log.go:30] 043 | SigChainLoader.Load(ef8989cac4241efa0f05d5836fc75400) GetFingerprint
    09:34:15.456511 ▶ [DEBU keybase log.go:30] 044 | SigChainLoader.Load(ef8989cac4241efa0f05d5836fc75400) AccessPreload
    09:34:15.456707 ▶ [DEBU keybase log.go:30] 045 | Preload failed
    09:34:15.456945 ▶ [DEBU keybase log.go:30] 046 | SigChainLoader.Load(ef8989cac4241efa0f05d5836fc75400) LoadLinksFromStorage
    09:34:15.457155 ▶ [DEBU keybase log.go:30] 047 + SigChainLoader.LoadFromStorage(ef8989cac4241efa0f05d5836fc75400)
    09:34:15.457361 ▶ [DEBU keybase log.go:30] 048 | Setting loadKID=01203978b23da5119ce606cdc9e64ee0f66972be4e2a08739891e899ffcb2aa665790a
    09:34:15.462357 ▶ [DEBU keybase log.go:30] 049 | Stop loading at KID=01203978b23da5119ce606cdc9e64ee0f66972be4e2a08739891e899ffcb2aa665790a (!= KID=0101dcd7b313f64668e09269a674900fc566fca41f3dc338ecfb989db3b692f4faa60a)
    09:34:15.462566 ▶ [DEBU keybase log.go:30] 04a | Loaded 12 links
    09:34:15.462849 ▶ [DEBU keybase log.go:30] 04b - SigChainLoader.LoadFromStorage(ef8989cac4241efa0f05d5836fc75400) -> ok
    09:34:15.463031 ▶ [DEBU keybase log.go:30] 04c | SigChainLoader.Load(ef8989cac4241efa0f05d5836fc75400) MakeSigChain
    09:34:15.463235 ▶ [DEBU keybase log.go:30] 04d | SigChainLoader.Load(ef8989cac4241efa0f05d5836fc75400) VerifyChain
    09:34:15.463453 ▶ [DEBU keybase log.go:30] 04e + SigChain::VerifyChain()
    09:34:15.463647 ▶ [DEBU keybase log.go:30] 04f - SigChain::VerifyChain() -> ok
    09:34:15.463869 ▶ [DEBU keybase log.go:30] 050 | SigChainLoader.Load(ef8989cac4241efa0f05d5836fc75400) CheckFreshness
    09:34:15.464076 ▶ [DEBU keybase log.go:30] 051 + CheckFreshness
    09:34:15.464348 ▶ [DEBU keybase log.go:30] 052 | Server triple: &{86 5be03f68bfda9f2e1cee359d46150688ebaa47701655ea0dd0eeb6ed2b6ff88d a460e91a2af9af524a73848a400defa95f9d504f94fb9be7cde5b68815e7097a0f}
    09:34:15.464587 ▶ [DEBU keybase log.go:30] 053 | Client triple: &{86 5be03f68bfda9f2e1cee359d46150688ebaa47701655ea0dd0eeb6ed2b6ff88d a460e91a2af9af524a73848a400defa95f9d504f94fb9be7cde5b68815e7097a0f}
    09:34:15.464784 ▶ [DEBU keybase log.go:30] 054 | Future triple=nil
    09:34:15.464966 ▶ [DEBU keybase log.go:30] 055 | Local chain version is up-to-date @ version 86
    09:34:15.465217 ▶ [DEBU keybase log.go:30] 056 - CheckFreshness (ef8989cac4241efa0f05d5836fc75400) -> (false,ok)
    09:34:15.465476 ▶ [DEBU keybase log.go:30] 057 | Sigchain was fully cached. Short-circuiting verification.
    09:34:15.465688 ▶ [DEBU keybase log.go:30] 058 - SigChainLoader.Load(ef8989cac4241efa0f05d5836fc75400) -> (true, ok)
    09:34:15.465883 ▶ [DEBU keybase log.go:30] 059 + LoadSigHints(ef8989cac4241efa0f05d5836fc75400)
    09:34:15.466089 ▶ [DEBU keybase log.go:30] 05a | SigHints loaded @v9
    09:34:15.466289 ▶ [DEBU keybase log.go:30] 05b - LoadSigHints(ef8989cac4241efa0f05d5836fc75400)
    09:34:15.466510 ▶ [DEBU keybase log.go:30] 05c + Refresh SigHints() for uid=ef8989cac4241efa0f05d5836fc75400
    09:34:15.466726 ▶ [DEBU keybase log.go:30] 05d + API GET request to https://keybase.io/_/api/1.0/sig/hints.json?low=9&uid=ef8989cac4241efa0f05d5836fc75400
    09:34:16.146563 ▶ [DEBU keybase log.go:30] 05e | Result is: 200 OK
    09:34:16.147022 ▶ [DEBU keybase log.go:30] 05f - successful API call
    09:34:16.154018 ▶ [DEBU keybase log.go:30] 060 | No changes; version 9 was up-to-date
    09:34:16.154471 ▶ [DEBU keybase log.go:30] 061 - Refresh SigHints() for uid=ef8989cac4241efa0f05d5836fc75400
    09:34:16.154964 ▶ [DEBU keybase log.go:30] 062 + Store user rejozenger
    09:34:16.155253 ▶ [DEBU keybase log.go:30] 063 + SigHints.Store() for uid=ef8989cac4241efa0f05d5836fc75400
    09:34:16.155501 ▶ [DEBU keybase log.go:30] 064 | SigHints.Store() skipped; wasn't dirty
    09:34:16.155809 ▶ [DEBU keybase log.go:30] 065 - SigHints.Store() for uid=ef8989cac4241efa0f05d5836fc75400 -> ok
    09:34:16.156062 ▶ [DEBU keybase log.go:30] 066 - Store for rejozenger skipped; user wasn't dirty
    09:34:16.156349 ▶ [DEBU keybase log.go:30] 067 + HasActiveKey
    09:34:16.156595 ▶ [DEBU keybase log.go:30] 068 | Checking user's ComputedKeyFamily
    09:34:16.156894 ▶ [DEBU keybase log.go:30] 069 - HasActiveKey -> true
    09:34:16.157119 ▶ [DEBU keybase log.go:30] 06a + Populate ID Table
    09:34:16.157377 ▶ [DEBU keybase log.go:30] 06b - Populate ID Table
    09:34:16.157657 ▶ [DEBU keybase log.go:30] 06c + VerifySelfSig for user rejozenger
    09:34:16.157949 ▶ [DEBU keybase log.go:30] 06d | Found self-signature for rejozenger @uid=ef8989cac4241efa0f05d5836fc75400, seq=86, link=5be03f68bfda9f2e1cee359d46150688ebaa47701655ea0dd0eeb6ed2b6ff88d
    09:34:16.158216 ▶ [DEBU keybase log.go:30] 06e - VerifySelfSig via SigChain
    09:34:16.158475 ▶ [DEBU keybase log.go:30] 06f | configured GPG w/ path: /usr/local/bin/gpg2
    09:34:16.158740 ▶ [DEBU keybase log.go:30] 070 | running Gpg: /usr/local/bin/gpg2 [--no-tty --with-colons --fingerprint -K]
    09:34:16.164774 ▶ [DEBU keybase log.go:30] 071 - RunEngine(GPGImportKeyEngine) -> ERROR: No PGP keys available to choose from.
    09:34:16.266840 ▶ [DEBU keybase globals.go:250] 072 Calling shutdown first time through
    09:34:16.267032 ▶ [DEBU keybase login_state.go:897] 073 + Account "LoginState - Shutdown"
    09:34:16.267116 ▶ [DEBU keybase login_state.go:899] 074 - Account "LoginState - Shutdown"
    09:34:16.267154 ▶ [DEBU keybase globals.go:290] 075 exiting shutdown code=0; err=<nil>
    09:34:16.267196 ▶ [ERRO keybase main.go:58] 076 No PGP keys available to choose from.
    rejo@broop-kidron:~$

**Comment by maxtaco** [comment]
Your keys are both expired.

**Comment by rejozenger** [comment]
Damn. You are right. Sorry for wasting your time. By the way, I now ran into the error "openpgp: unsupported feature: unknown S2K GNU protection mode: 2", so I still can't import a key. Haven't looked into that enough.

**Comment by maxtaco** [comment]
Does it work to just sign your install without importing your key?  Thanks

**Comment by rejozenger** [comment]
Not sure what "sign your install" exactly means, but if you meant something like "keybase pgp sign -m 'Hello'", then I'll end up with "▶ ERROR No secret key available".

**Comment by maxtaco** [comment]
Oh sorry, this is the select command.  Yeah, this is on our list of
features we'd like to implement, but we're not there yet.  The Go libraries
we are using have no support for external devices, we'd have to shell out
to GPG.

**Comment by rejozenger** [comment]
Ah. Yes. So, I have a key on a Gemalto Smartcard. That explains.
