### ISSUE TITLE
Error: ERROR CODE 218 - internal chat storage error: failure to read chat read outbox: failed to decrypt item in method chat.1.local.markAsReadLocal at new s

### ISSUE THREAD

**Issue by benkietzman** [keybase/client#18694]
Receiving the following error message on a single device in a particular team chat room:

Error: ERROR CODE 218 - internal chat storage error: failure to read chat read outbox: failed to decrypt item in method chat.1.local.markAsReadLocal at new s (file:///opt/keybase/resources/app/desktop/dist/main.bundle.js:1:534131) at file:///opt/keybase/resources/app/desktop/dist/main.bundle.js:1:534683 at c (file:///opt/keybase/resources/app/desktop/dist/main.bundle.js:1:534722) at _rpcClient.invoke.t (file:///opt/keybase/resources/app/desktop/dist/main.bundle.js:1:1135315) at file:///opt/keybase/resources/app/desktop/dist/main.bundle.js:1:3412713 at e._call (file:///opt/keybase/resources/app/desktop/dist/main.bundle.js:1:2913300) at file:///opt/keybase/resources/app/desktop/dist/main.bundle.js:1:2913440 at s (file:///opt/keybase/resources/app/desktop/dist/main.bundle.js:1:2913080) at e._fulfill (file:///opt/keybase/resources/app/desktop/dist/main.bundle.js:1:2913410) at s (file:///opt/keybase/resources/app/desktop/dist/main.bundle.js:1:2912611)

I have not seen this error on any other device or in any other regular or team chat room.  I am running my Keybase client on Ubuntu Linux.  I see the error as a horizontal drop-down from the top of the page.  The background color of the drop-down is a slightly transparent black and the text is white.

The error does not seem to noticeably impact anything.  Chat message still arrive and I am able to chat to the room as well.  Not sure whether I should do anything to fix it or just do a "sudo apt purge keybase" and then reinstall again.  Any recommendation?  Thanks.

**Comment by andrew-anguiano** [comment]
I'm having this issue on MacOS. It started happening after I logged out/revoked my machine and then re-added it shortly after.

**Comment by plttn** [comment]
Also having this occurring on revoked/re-provisioned hardware on MacOS. 

`a187dd1837d02e15acf6ec1c`

**Comment by andrew-anguiano** [comment]
It looks like the error disappeared after I nuked the local database, although I’m not sure that that’s the recommended fix. I still get duplicate notifications on my iPhone though.

**Comment by plttn** [comment]
Yeah, same, I nuked the contents of `~/Library/Application Support/Keybase` and that did it.

**Comment by benkietzman** [comment]
I run on Ubuntu Linux.  Based on what you two said, I removed the ~/.config/Keybase directory and ran run_keybase to restart Keybase.  That did not quite work for me.  I ended up running the following steps:

1) sudo apt purge keybase
2) rm -r ~/.config/keybase
3) rm -r ~/.config/Keybase
4) sudo apt install keybase
5) run_keybase

That got things working normally for me again.
