### ISSUE TITLE
Move saltpack to it's own repo?

### ISSUE THREAD

**Issue by gabriel** [keybase/client#1872]
Do we want to move saltpack out of `keybase/client/go` into `keybase/saltpack` since this is our "kitchen sink" repo and saltpack is a separate more standard-y thing?

**Comment by jacobhaven** [comment]
I think this is a good idea. Just create a new `keybase/saltpack` repo and `git filter-branch --prune-empty --subdirectory-filter go/saltpack/` (Preserving the commit log with just that directory, like https://github.com/jacobhaven/saltpack)

Then a few imports will need to be re-written, but that's about it.

**Comment by gabriel** [comment]
@strib we should do this history preserving move for kbfs too?

**Comment by strib** [comment]
@gabriel: yeah eventually.  There's a JIRA for it already.  Though some people will argue that we should put it into the kitchen sink repo, rather than its own.
