### ISSUE TITLE
Can't access /keybase/private/jessk,mlsteele

### ISSUE THREAD

**Issue by seveneightn9ne** [keybase/client#1874]
I just installed kbfs.
I can't read or write /keybase/private/jessk,mlsteele (permission denied) but I do have access to /keybase/private/jessk and public folders.
I also didn't see any tracking dialog when I tried to open /keybase/private/jessk,mlsteele
log dump id 9c2b1497aa5238e729a6ee1c

**Comment by seveneightn9ne** [comment]
Ok, this is probably expected. It happened because mlsteele put a file in there, then went offline, then I installed keybase and tried to access the folder. Then mlsteele ran keybase and rekeyed, now I have access. I guess it would be nice if some UI indicated what's going on.

**Comment by strib** [comment]
Hi @seveneightn9ne, thanks for the report.  You're exactly right, that's working as intended.  In the next major version, we're planning to have nice error popups when that happens, letting you know that misteele needs to come back online before you can access the folder.  Thanks for trying it out!
