### ISSUE TITLE
Keybase won't run after install - Linux Mint 18.3

### ISSUE THREAD

**Issue by NginUS** [keybase/client#18908]
$ run_keybase
▶ WARNING Permission denied opening config file /home/username/.config/keybase/config.json
▶ WARNING Permission denied opening gui config file /home/username/.config/keybase/gui_config.json
▶ WARNING Permission denied opening updater config file /home/username/.config/keybase/updater.json
▶ ERROR open /home/username/.config/keybase/keybase.autogen.env: permission denied

I saw a similar issue here & made sure I did own ~/.config, so their fix doesn't apply.
https://github.com/keybase/client/issues/15233

my log id: 3f4ae08efa8d42784b129f1c

**Comment by heronhaye** [comment]
Are you sure permissions are correct, recursively? What if you do

```
sudo chown -R $(whoami):$(whoami) ~/.config/keybase
```

**Comment by NginUS** [comment]
@heronhaye 
That did it- thanks!

**Comment by heronhaye** [comment]
Thanks. Do you know how the permissions might have gotten messed up? Did you run any keybase commands with `sudo`, perhaps?

**Comment by NginUS** [comment]
As per the published instructions here:
https://keybase.io/docs/the_app/install_linux

I ran the sudo apt etc. but that shouldn't have done anything...

**Comment by bogn83** [comment]
> As per the published instructions here:
> https://keybase.io/docs/the_app/install_linux
> 
> I ran the sudo apt etc. but that shouldn't have done anything...

Exactly the same steps I did and the same symptoms but on kubuntu 19.04. Also the chown above fixed it.
