### ISSUE TITLE
Stop nagging about email verification and allow disabling unwanted features

### ISSUE THREAD

**Issue by nulldowntime** [keybase/client#18903]
I switched to Keybase because it was supposed to be a "non-corporate", user friendly, secure messaging app. It's not that any more. 

Please stop nagging me about email verification. It's not a valid notification. I should be able to disable it in notification settings. I should be able to say "ignore". 

I believe I should be able to disable:
- wallet
- unwanted notifications about anything
- "consider following"
- any other attempt at monetizing me and "driving engagement"

It's ultimately about user CHOICE. If you want to waste development time on cramming questionable features into what used to be a great app, oh well, but at least don't force them on people.

I realize it's open source and forking Keybase is an option. Abandoning it might be quicker.

**Comment by tsuthers-ccpgames** [comment]
>Abandoning it might be quicker.
That was literally my first thought on firing up my computer and seeing a request for email verification this morning. "Oh dear, time to leave".

My reflexive disgust reactions aside, I'd encourage the keybase devs to read this:

https://onezero.medium.com/why-apples-notification-bubbles-are-so-stressful-65a544e51f10

An orange "1" dot notification when I open the app is extremely aggressive. I've been trained by 10 years of mobile phone UI's to pay attention to it, and it has a cognitive cost every time I see it that makes me just a little stressed for just a moment. It should be reserved for things that must be dealt with now. Using it for something that users can choose to ignore is bad UI design. Making it impossible to suppress if the user chooses to ignore it is malicious UI design.

**Comment by junderw** [comment]
Top 3 feature requests for any app ever:

1. "Allow me to fully customize everything in your UI"
2. "Stop doing anything I don't like. Here's a few completely unrelated examples, surely you'll figure it out"
3. "Never charge money, or hide features behind a pay wall. Also never sell my data"

**Comment by nulldowntime** [comment]
>     1. "Allow me to fully customize everything in your UI"
Plugins?

>     2. "Stop doing anything I don't like. Here's a few completely unrelated examples, surely you'll figure it out"
Plugins?

>     3. "Never charge money, or hide features behind a pay wall. Also never sell my data"
A PRIVACY-CENTRIC project that sells user data would be a bit of a disappointment, don't you think?

I guess the bottom line is that I was still thinking about Keybase as an open source project, with some mildly annoying additions to fund development and continue serving and protecting (yes, NOT a cliche) its users. Not sure if that was ever right, but it's not any more.

Also, I'm happy to pay. But not for this.

**Comment by jamesdwilson** [comment]
Vote to re-open. I am still affected by this.

**Comment by maxtaco** [comment]
I just verified the above. You are welcome to opt out of email or phone number. The one state that's not ideal is an unverified email, so if you don't want to verify it, then just delete it and forgo notifications.

**Comment by jamesdwilson** [comment]
Removing the email worked! Thank you!

**Comment by maxtaco** [comment]
Note we don't recommend this for most users, since email notifications are good for security hygiene. It's good to get a notification, for instance, when a new device is added to your account.
