### ISSUE TITLE
keybase:// url scheme does not support electron path-to-app invocation

### ISSUE THREAD

**Issue by eli-schwartz** [keybase/client#18925]
The feature introduced in #18555 does not function in my Arch Linux package for keybase-gui, because keybase is not invoked via a renamed electron binary running the default app in resources/app/ -- instead, it is invoked via an electron binary in /usr/bin/electron /path/to/app

```
$ /usr/bin/electron
Electron 6.0.1 - Build cross platform desktop apps with JavaScript, HTML, and CSS
Usage: electron [options] [path]

A path to an Electron app may be specified. It must be one of the following:
  - index.js file.
  - Folder containing a package.json file.
  - Folder containing an index.js file.
  - .html/.htm file.
  - http://, https://, or file:// URL.
```

(and in the GUI)
> To run a local app, execute the following on the command line:
> `/usr/lib/electron/electron path-to-app`

This is generally useful functionality, and in my case, it's used to ensure that all electron apps use the same runtime, with the system ffmpeg/icu/http_parser/libevent/fontconfig/etc/more/things, and built using the distro-approved clang and relevant CFLAGS.

However, keybase seems to be looking for command-line options exclusively in argv1 (which is, in the case of `electron path-to-app`, going to be "path-to-app") and not seeing the keybase:// url at all. It would be nice to support this use case.

**Comment by eli-schwartz** [comment]
For context, this is probably caused by the parsing done here:
https://github.com/keybase/client/blob/8283633e9626ae34a29792b0f6695e507702de8a/shared/desktop/app/node.desktop.tsx#L75-L81
https://github.com/keybase/client/blob/8283633e9626ae34a29792b0f6695e507702de8a/shared/desktop/app/node.desktop.tsx#L164-L166

**Comment by heronhaye** [comment]
Merged. Do you need us to do anything else or will you cherry pick for this release?

**Comment by eli-schwartz** [comment]
I'm fine with cherry-picking it. Thanks!
