### ISSUE TITLE
can not execute run_keybase

### ISSUE THREAD

**Issue by joshua10110** [keybase/client#18929]
[write something useful and descriptive here]

my log id: 6680f18ad74a8455ff64101c

I am not able to execute the command run_keybase.
It does show me 3 different errors. Online I was not able to find anything what could help me to resolve this issue.

**Comment by heronhaye** [comment]
What are the errors?

**Comment by joshua10110** [comment]
▶ WARNING Permission denied opening config file /home/john/.config/keybase/config.json
▶ WARNING Permission denied opening gui config file /home/john/.config/keybase/gui_config.json
▶ WARNING Permission denied opening updater config file /home/john/.config/keybase/updater.json
▶ ERROR open /home/john/.config/keybase/keybase.autogen.env: permission denied

**Comment by heronhaye** [comment]
Cam you try this?

```
sudo chown -R $(whoami):$(whoami) ~/.config/keybase
```

**Comment by joshua10110** [comment]
working!!!!thanks
