### ISSUE TITLE
OSX KBFS not running.

### ISSUE THREAD

**Issue by tbelaire** [keybase/client#1897]
I just updated keybase but it looks like KBFS is not running.
I am unable to see /keybase at all.
```
$ keybase version
Client:  1.0.9-0
Service: 1.0.9-0
$ keybase launchd list
homebrew.mxcl.keybase: Running (pid=24562) [Keybase]
No KBFS services.
```

**Comment by maxtaco** [comment]
The brew install doesn't have KBFS included.  We're making a DMG-based install, that we're slowly letting people in for...

**Comment by tbelaire** [comment]
Can I build it off the github source?

**Comment by kballard** [comment]
How does one get in on the DMG-based install?

**Comment by maxtaco** [comment]
BEGIN KEYBASE SALTPACK ENCRYPTED MESSAGE. kiXxI0Cp4MBEQrs K7GWO3e4f3P5vin klaB1s2dwnTKPvt ZtIkdwRq802n8mn wVM6X9l47poNJnP YDNZUm5yWjOmVI9 3Y3JPPGxMCg0W3Q jOvA899mMH1ZUeb 7xUJlGQydOSwx49 P2xcegaMpzka0zH LKscpadTugoOPyE sXxbEwPBvfAVNLu VABSvcH09vAJeKv OpebP76dS4Gccv5 IdwrQSrhceSnYHW bNTKSC8vciuFstr 0dEf9tW4UfzMTM6 G24T5uBTelNIhkr djxJzVbpxb9TqhR X4s0b79MWDaqm9I mtKOeSKDtSWW7en ryZIoHxElehU25n Zi4hw5uZFNgRvQb m4ZOASsU8y8epYe RD2Z4xwGVTH0KIO yjjFAB34g9BUKLc PCzpjnRRxea8JHB UkMR6LsJJkZ3iwL NQZdMdPIp9RzB6I JSb3slD6JDHr6PD XOd3O1Uiezrr7cp RfnyeyOp5zTMpPa BxSoLwryxSoBNNP 1ULOrbiEFslVPk5 CHQU6oyUbeNOrKN ysTHnF3qq9JLV3t jcFCVglRC8fo9hi n180tkvYTvYZVKM 88UCpnYdOJR527f BqqwtuYDQweNEo4 XxSUcnhrHMbshLZ vSC7OgzAwkhrGyV JAU7ObRaxHpoe3q xWWBFHnC9ByRROR nQLIKVDVest4f25 xgnCQalm5XJazFy UPDpkHR4Avh6m4H 4zyevyYZlspNiAr Y2dZXTCqu7R9S2p d1dDa8TMaQg31PK Ga3kHyZIcZoFVSD zYjKHbNNdgZe5zL TC7NrS7zBI8CcjE Z74XNdmwX9DqHwn DFKNt5QZ5q1UlBa eiXurARaQaNdmrF LbsjMv3nzES1AnP VbF1mxjXsH3Bnat YzSoGufyxvNy3t2 Uln9EZF7djzkx31 81cWiaYjQBejMiv 5mDmR24MGoIGPqf PpdKapcB4uT0urx eQNrPVohBLF92w3 vPSewc4zJuJutNl yGsm8cA94AwvsBk fyOEfG4vldIx2We Z1z0kfH3OO0IyLD bB9YiG3Wrr3ca4j lt8vyIF3lhlkvdG Id9pcbs620uwPwg FRhyVucHY8gfJL6 2TmUsZaDNK7uDX1 OiWuLpHHn8LnZwd 3xHQGWmD0fE6lpf zqP5X9aF3pDPFR1 jYyTtINIiuC4h9s zL0LryuTBDPZGCp Dj89qiDeCEcs0jk X5V7dyzOTC6a9X6 YmLtgqb0IUc5UNL 6LwL2nEHzkSBuQr mZdJvlK3xVwl6Wu SfYob83yHJF1Dnu xO1b4b7JDrQifiR q4zh2zqID0oO6q3 F4tXOepUxE5qngQ buNIwabFnbItFqc HmRf7fLBIXHG90Y yWrm0msYaqxexSF luuXVqScOeNMaU8 r7Hc1pEBBxvXzZx lsmNn48zrJpJ6xp R1iZfCRS2xyOSRB wxmYFqKFeB5jokQ w3szb3JG2NXQOGa PGR8DfquZPV8AOc mAM8AF1B1tbPf2r Gih4npzNA7ZZiLI LP9Iq7Ln0PimUgI 994NzOVCTKlJD8r sYpUBn1JuEw6L54 5cQQkGv9BEzECCe f2sdwHwcJBSH7zg 6K8s2oqWDNR6PTy Jk1XbCiVFKRdmip 0ptaJE0B4QzWMxg 9ubFrFWHHauHC0s jfr25mPHzXTQ4oX cuuBm00gEuQhjQr dNFoth2pcHgsU39 GB8yzIRKbrxoouV Hos8KIa62oDD0Br CXSCHADt5wxnXOB x7Aqok0R61nLlgo PDW3r2HTU3vD3IS AtDtUn58D6X5vDo GBVFgL3s7hCYZ4y 94mCoVMa557HPVl 4E86E7gswIsQ4x3 Yx55FmsU2tWcYNI V6eC0s76LyLGHX0 F2Jd69T93JymSi8 vYkpCzEu2MgARyC 2IImyAPTt4s7tHC v8wMW5J3OWRp0Dz ybOS8xyYQtq0dYc zBDRCqvk2L5LG2N zneABTkKgXUFYzu gDKfqGUWi1P7iOm ZKPtS6NTmrKuU07 hupowey9ILxL7iw rN9faOjvKbmEMbr blqKu7RjqIFh9KT qcW5qkItMY2cYg1 udOnSEb5dC4rsf7 AvVh08cv94fx4GY 3gMYPrkakmT1aoP 0tinM3fxbrlPhjY OoKTaXYt4h7Frcu 6qiO431JNwae1Eh p7VeKm6be6SE0V6 I6L4FrqQocp8UPq 8Yj0yNPSsf079qp doZDGCHzjP4uZr8 2tqHGoJ4cnKYmd0 xPekVTK1fZTTAMV Bp89Q8JxWZmeSBK UlDKI7ZoiONBQrl UkQ2RMxPo61bXvB HqkgqBeHRVGlF2y qzZsaSo3NixGIsL TtzSTriP10jg2i7 TPudh24pqeBJAy5 xYqpi76hkH602bO s5cVhIN0ed4mjVH o9G8pm18aD43WMU q56wfls3IP9HmyL obif7j3LabKJJ5f 7U6xgSCmdN9EHN6 6EOMucVJoYmEWQr Wl4Vpx5Ro8VzjAF xOtWlnx8jolatrM YY59eyTZJcsjrBS lFQYr3trXo5oeSD oFRHTTo1eQUHsrb 9HahWVSRjf9MI2R 2I2NqRqcBhJ5Q5z jXajfHhAQM00B1Q Be. END KEYBASE SALTPACK ENCRYPTED MESSAGE.

**Comment by kballard** [comment]
Nice, but unfortunately I'm getting a 404 :(

**Comment by maxtaco** [comment]
Sorry that was my type. Try again:

```
BEGIN KEYBASE SALTPACK ENCRYPTED MESSAGE. kiXxI0Cp4MBEQrs K7GWO3e4f3ScLaS JV49pg1fVTWoI9b 0adcGEW8aSmFxi4 0sClVNnoMuQirgM WfD4qMh6AsiGmEb 9jsO1JVOALxZccp JKYESNsMc1tC9KH NNtJPBWE3APcUcP bSwAcBOXEfLMYok 1iYzUHTM6jNYXDK CChxUH5Iphj70zp aZXkQdqiVqzCUhi V4RZM10ffRqLndM 72zxx4yMYzJkqzb MlLxPSA82elvq50 xnVCDKgbBIM9EY7 dgWT5uBTelNIhkr djxJzVbpxb9TqhR X4s0b79MWDaqm9I mkLIGvM3enTsbov wABhsNVsEMfou1P tnYpZV5oXFUIPWU uViCTSwY0WJe6ai iNAXHnSJcAOth5N WSmOHPtdbj9oKLc PCzpjnRRxea8JHB UkMR6LsJJkX0hwG 1SSRdgwwuC5ip7m uoRDpAyLk8U5NYu FIVvtD8e8naKWw0 KcI1qMXn7xg5AgX 7myQgLfyt0fEzAx 6ZTj9vkpTmAcGp5 FQ88uk22l6oack2 09g7A9b6in4OSIn POOhcSOmHHFd3xU jouLGLFqLGdJhH8 RLTSv3atj14vfVN 9aUq3TQ00wGKTWS 4GV97eD5EygfMVp v76jZ3uLblbyaOj FaJAqEfoKNnOIwl MSHnJ65LK1CEIgP zQ9l0qFmo6EjFmC v6UmU2IrdMTH7Mz SVMJB99LqyRkCu9 hwaCf9YrQfGsbxC cOulyJZWzKH82Oy 4r6MCRnLBDxZIFJ Je88xdwGuvERPS4 5RrYmvNQmWLe92U d4Qupx968vxtHND EInxEu5IAxwe5G0 45jHNOK61Vzwywr nSbjpgPtC3bmdEl PrjktOMrEZn17ln 8MdNnMnJmJzpQz4 FqezaI6OcaUGRKf qxsoCDdGub6nOIF tfL2npXiAtG9OdH ZFkyeQzLNHSTq8s j7uSQ2n1lkvYNne gQNrPVohBLF92w3 vPSewc4zJuJutNl yGsm8cA94AwmpOn XYRwHqJ62xh8ArQ U2mbDr7G2M4ch2H aYav0xYpKB3ZaQS zX9KCVSSFgRXySO sWoonjYI1s8QPvY HzQTwbMJEegfJL6 2TmUsZaDNK7uDX1 OiWuLpdUI5oSs4M mQdWMFXi43vs8GX Uuxlp1FcAYunkC1 DeuBcBLdpw7ME0J Ns4DnOQUKE0nFwt RktPkNnlH1zwQbe WyILc5sLadNOCkK jpyHgqb0IUc5UNL bYSU1gnpPRMB1w4 PHsVfSzkHTm7vn0 7qn0CzMkn7tN7mm 3Jsv6VzfZ1sL9zA e5J7nXMvuiPJbmd F4tXOepUxE5qngQ buNIwabFnbItFqc HmRf7fLBIzD4KVe w8ujUzfYdtfDWA2 qM6IEh421i4xwbO veDN7ST5aubGdIR xyugc9K0OlQCAdM 8IjGilmWgDDCDrd IsxbcrjZ5N9CWKs 6ixvwBqpCK0gbVZ 4rxZbGv63BLojN3 YRtYjdDa1s0OeXz cD9DmV6ocJ3GozJ Ysd2luxsDl7S5Vh PcIxXL1nKgROCWi 6alva8dyO9Ek1bw mPj64CtoJX7VYNE SCitxp39af2qupB b0GJxSUWY5UedIA HftQTAA3IycjYWp yRL0n8lxTBjgVGr mXJ5GXOCGBeihIT RpN0vi2n7eNdKi7 vSSEylceKIGMVmb PP44wbanQ8zrTKB 8TE8c6M7jCE03xG Kw0e16H7zzIeVCY JXDYDMc7JNVAynO Mx4dd65PF3t8mX9 mlj2EiVLDSmh8zq Z8FsooVVEDdlOQO J7wA52kW7nq412F oCv9zZ9hcLc1zZE GJL8u6hjzOaQk4W TfqBWelMyyD2SsX EMqenNoUaFmdp9n Z4jDL27TH2Xk7To e5ZI4E2AKJenSsv 5SNpvjxPmrMtEjG KFrliym0QciabzE pqhQTUSjFwoj3Ee P2fAtFimxNNCfOe 9nt64sLedOKzgii mvn4CTN1TZmUWEz NQbtNvWwibnISHh Mbav0b3seb08x4T ENjvWk1q5CNOc8y sTZLzbfjOGs2uZx 2V2gvCKaNxdopfe AZnb1d8Ekm1x1NH WQRfZM3286jXq3c OVF62jo1A8ye6em aVw6fhnomSp2onl WROXCsXJ4hHdOXa HkZlvo2bri5DJ7D Ia5DR2Gp8ptsvw3 AUpDAxRQEYL6EML 32ziLhuXrS1tNOR 5YYggpLg81k3j6U RFvuIxPApVXRj1z AWK7bJpF9dYk0iK PRgG6IE2zgNG6Qn 5saV8Yo68MjkJ81 yLHkaIl93U1UCup PXyl1IItYHpm1mv YTxvIRgXo9cNfRe TeMwErVm7vnqDcx E1h4VcAUdEczume QKEuMjSGwOj8uK7 i8JpYs2GBtn6ZHc uv8vl9zy8AwQBs5 KHVqbgUMNmovX9J IHZA79jw12sztgk 0x2kU8C156rxvY5 AcVx0CefRYTZXtY ihnjK49LiD5IOTy iTTJhGzq1XLPLDf L1JgZGcEjTEYObg DPzgfHNwZ8zbLcf tUGhOUzXMxPYnJd 3x2w536eQZgu3g9 08kHv1jyYTnxfCw xe7BSvCxYWbB3ay i. END KEYBASE SALTPACK ENCRYPTED MESSAGE.
```

**Comment by kballard** [comment]
Excellent, that worked :) Although there's a bit of a bug in the CLI tool, it printed the output intermingled with info lines about validating your identity.

**Comment by maxtaco** [comment]
Yeah, we should fix that.  The output is going to stdout and the ID info is going to stderr, so you can pipe them in different directions..

thanks...

**Comment by kballard** [comment]
I'm filing a ticket on it now.

**Comment by Jestre** [comment]
Saw the blog post re: kbfs, emailed Chris as per the directions, and received two more invites.  Do I need to use one of those to set up a new account to gain access?  Or were those merely autobot replies which issued standard invites?

**Comment by pjv** [comment]
hey @maxtaco, can i get one of those fancy encrypted messages with a DMG url too?

**Comment by RyanSinger** [comment]
I would love to test kbfs on OSX, too. :-)

**Comment by offbyone** [comment]
I'm +1 to that. I went and upgraded my client hoping to try it and... no joy.

**Comment by strib** [comment]
The standard way to get into KBFS is to email chris about it, as per https://keybase.io/introducing-the-keybase-filesystem.  Thanks for all the interest!  We'll open it up more and more widely over time, we promise!

**Comment by OJFord** [comment]
Why do we need a separate GUI version to get KBFS?

Particularly annoying as it seems that on Arch:
-  `community/keybase 1.0.17` does not have the filesystem
-  `aur/keybase-bin 1.0.17` does
