### ISSUE TITLE
Keybase GUI not opening on Ubuntu

### ISSUE THREAD

**Issue by shermisaurus** [keybase/client#18975]
I have tried everything that comes on Google and issues here with the search "Keybase GUI Not working Ubuntu" but I can't come up with anything that fixes the problem. I tried both stable and nightly packages. I've included log id at bottom of this comment.

I tried using keybase cli to login but it came up with the following block:

```
shermisaurus@pop-os:~$ keybase login 
▶ WARNING Permission denied opening config file /home/shermisaurus/.config/keybase/config.json
▶ WARNING Permission denied opening gui config file /home/shermisaurus/.config/keybase/gui_config.json
▶ WARNING Permission denied opening updater config file /home/shermisaurus/.config/keybase/updater.json
▶ ERROR Failed to open config file /home/shermisaurus/.config/keybase/config.json.QISZRPRLR6PD4DA27QJTMEPR for writing: open /home/shermisaurus/.config/keybase/config.json.QISZRPRLR6PD4DA27QJTMEPR: permission denied
▶ ERROR Failed to open config file /home/shermisaurus/.config/keybase/config.json.W632ZQ4JCFFU44WWC57ACGAH for writing: open /home/shermisaurus/.config/keybase/config.json.W632ZQ4JCFFU44WWC57ACGAH: permission denied
▶ INFO Starting keybase.service.
▶ WARNING Permission denied opening config file /home/shermisaurus/.config/keybase/config.json
Your keybase username: ▶ WARNING Permission denied opening gui config file /home/shermisaurus/.config/keybase/gui_config.json
▶ WARNING Permission denied opening updater config file /home/shermisaurus/.config/keybase/updater.json


```
my log id: fe55417b9397f6d19771181c

**Comment by shermisaurus** [comment]
I guess it's due to encrypted LVM partition on my ubuntu based machine. Any workarounds for this, like changing config file location to some other location. Or maybe an AppImage for that?

**Comment by heronhaye** [comment]
Can you try this?
```
sudo chown -R $(whoami):$(whoami) ~/.config/keybase
```

**Comment by shermisaurus** [comment]
I see there has been a discussion on [here](https://github.com/keybase/client/issues/8264) about flatpak support. I think flatpak can solve issues on fully encrypted LVM machines. Correct me if I am wrong, I've just a rough idea about these things.

**Comment by shermisaurus** [comment]
[](url)

> Can you try this?
> 
> ```
> sudo chown -R $(whoami):$(whoami) ~/.config/keybase
> ```

I tried this. There's no output in the terminal.

**Comment by heronhaye** [comment]
And then try run_keybase again?

**Comment by shermisaurus** [comment]
> And then try run_keybase again?

Yeah, it worked this time, as expected. KBFS is working as it should.
I wonder how this happened without actually doing anything? Just curious.

**Comment by heronhaye** [comment]
I believe it's a bug in our code. We're looking into it.

**Comment by heronhaye** [comment]
Did you already have Keybase installed on this computer, and this happened after an upgrade? Or was this the first time Keybase was installed on this computer?

**Comment by shermisaurus** [comment]
I had keybase installed on this computer before but recently I performed a clean wipe and fresh Pop_OS! (Ubuntu based) installation with full LVM encrypted installation on my primary drive. I am all set-up now. Thanks for looking into it :). Let me know if I need to provide some logs or anything else.

**Comment by heronhaye** [comment]
Did you already have Keybase installed on this computer, and this happened after an upgrade? Or was this the first time Keybase was installed on this computer?

**Comment by shermisaurus** [comment]
On an another freshly installed elementary OS today on a different laptop I got the same error as before. And as usual the mentioned fix worked just fine. Just for a  fyi
@heronhaye 

```
shermisaurus@elementary-os:~$ run_keybase 
▶ WARNING Permission denied opening config file /home/shermisaurus/.config/keybase/config.json
▶ WARNING Permission denied opening gui config file /home/shermisaurus/.config/keybase/gui_config.json
▶ WARNING Permission denied opening updater config file /home/shermisaurus/.config/keybase/updater.json
▶ ERROR open /home/shermisaurus/.config/keybase/keybase.autogen.env: permission denied
```
