### ISSUE TITLE
KBFS Login required

### ISSUE THREAD

**Issue by ZucchiniZe** [keybase/client#1898]
With the latest liniux prerelease that includes kbfs, it complains that login is required even when I am logged in. I have provided the outputs of various commands below that I think will be useful.

```shell
$ keybase version
Client:  1.0.9-20160204170021+c846d32
Service: 1.0.9-20160204170021+c846d32
$ kbfsfuse --version
1.0.0-33
$ keybase status
Username:      alexb
Logged in:     yes

Device:
    name:   ab-laptop
    ID:     eebd8d45f2bafafd5d3626b5cc947918
    status: active

Local keybase keychain: locked
Session status:         no session

KBFS:
    status:    not running
    version:   
    log:       /home/alex/.cache/keybase/keybase.kbfs.log

Service:
    status:    running
    version:   1.0.9-20160204170021+c846d32
    log:       /home/alex/.cache/keybase/keybase.service.log

Platform Information:
    OS:        linux
    Runtime:   go1.5.1
    Arch:      amd64

Client:
    version:   1.0.9-20160204170021+c846d32

Desktop app:
    status:    not running
    log:       /home/alex/.cache/keybase/keybase.gui.log

Config path:        /home/alex/.config/keybase/config.json
Default user:       alexb
Provisioned users:  

command-line client(s):
    keybase status [pid: 6505, version: 1.0.9-20160204170021+c846d32]
```

**Comment by maxtaco** [comment]
Can you try a `keybase unlock` ?

**Comment by ZucchiniZe** [comment]
Ok, it looks like that worked, yay! Thanks a lot. Is there an option to daemonize quite yet?

**Comment by maxtaco** [comment]
there definitely should be!?!  by default?!?!

**Comment by ZucchiniZe** [comment]
Odd, right now it logs to stdout and when I `Ctrl-C` it stops the FUSE transport.

**Comment by maxtaco** [comment]
@oconnor663 can you check this out^^^

**Comment by ZucchiniZe** [comment]
And, after I `Ctrl-C` it I must try the command with sudo, exit that, and try it again other wise it throws
```
2016/02/04 19:49:03 mount helper error: fusermount: failed to access mountpoint /keybase: Permission denied
2016/02/04 19:49:03 mount helper error: fusermount: failed to access mountpoint /keybase: Permission denied
kbfsfuse error: (2) fusermount: exit status 1```

**Comment by strib** [comment]
@ZucchiniZe: what distro of Linux is this, and what command did you actually run here?  `run_keybase` or something else?

**Comment by ZucchiniZe** [comment]
@strib my distro is fedora 23. Here is a better version of the previous error, sorry for not including it in the previous comment.
```shell
$ uname -a
Linux ab 4.2.8-300.fc23.x86_64 #1 SMP Tue Dec 15 16:49:06 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
$ kbfsfuse /keybase
▶ INFO KBFS version 1.0.0-33
2016/02/04 20:26:09 mount helper error: fusermount: failed to access mountpoint /keybase: Permission denied
2016/02/04 20:26:09 mount helper error: fusermount: failed to access mountpoint /keybase: Permission denied
kbfsfuse error: (2) fusermount: exit status 1
```

**Comment by strib** [comment]
Ah ok.  Did you ever try `run_keybase`?  Or maybe that's what you did at first, that got you into this mess?

It's currently not supported to run `kbfsfuse` on its own, though it shouldn't cause an error like that . . .

**Comment by ZucchiniZe** [comment]
I did not know about about `run_keybase` thank you for letting me know. It might be an error with my linux installation then.

**Comment by strib** [comment]
Ah, sorry.  The page where you downloaded the distro should have had the instructions to run `run_keybase`.  Let me know if it's still giving you problems.

**Comment by ZucchiniZe** [comment]
After 2 hours of continuous use, it looks like it is working for me :). Thanks for making this, it is an awesome product!

**Comment by oconnor663** [comment]
Sweet. We have `run_keybase` in the install instructions somewhere, but for the most part we hide it from people after install is done. (You end up with a `~/.config/autostart/keybase_autostart.desktop` file that runs it for you.)
