### ISSUE TITLE
Private folder requires reset

### ISSUE THREAD

**Issue by aaranmcguire** [keybase/client#19133]
Hi,

Please would you be able to reset my private folder. Account: `aaranmcguire`.

```
keybase sign -m "Mon 26 Aug 2019 15:11:23 EDT: Please reset folder /keybase/private/aaranmcguire because all the devices that have access have been revoked."

BEGIN KEYBASE SALTPACK SIGNED MESSAGE. kXR7VktZdyH7rvq v5weRa0zk9T2KUy exsTIhKY583EKBc w2Q0TqqKC1AHsIu c3Zz2OVRCPVU4ab 7KafxvDJkifbKtM kreAsuVdjS8dION i6nAYiiV4TdMpsj ZDGqN3FLoCaP5li hQKtaCoVe51guLn btryhbzqR9LiYNr 2RAjseqCamki6yx O9bvwEtqAQVRC8I AHMLUgVMPr27TIF NteqgBu2a7LLY3I VjdvgERChZ3Hoow KpK70A1DTaynzTI FI1NKP0Ss2D3ic4 AgfQZ8OHMfRVTqT JM4d19uCYr0Uvy4 pNyluCodiGQTtnz fMh0qS014jVuRxR JTTFkdqvWronJ71 612n4UDnXIpihsY RbnVaJ9IyAsUY. END KEYBASE SALTPACK SIGNED MESSAGE.
```

**Comment by strib** [comment]
@aaranmcguire sorry for the delay, but here's a build with a command that will hopefully help you:

https://s3.amazonaws.com/prerelease.keybase.io/darwin-test/Keybase-4.3.2-20190829234136%2Bd8773bc86e.dmg

It is based on the current macOS release, but has one new command you can run from a terminal (cherry-picked from #19164).  Once you install it (open the dmg and drag it into your Applications folder and restart Keybase), you should be able to run this command:

```sh
keybase fs reset --id 7a1e8147fcecae97dff6fc913b31e716 /keybase/private/aaranmcguire
```

Please let me know if that helps!  (Might require a Keybase app restart on your devices.)

**Comment by aaranmcguire** [comment]
Great, that worked. Thank you very much!
