### ISSUE TITLE
Public files not showing up on web UI for user patcon

### ISSUE THREAD

**Issue by patcon** [keybase/client#1918]
This appears empty to me, even though I have files there: https://keybase.pub/patcon

* should be two text files: `signal.hex.key` and `signal.base64.key`
* when I added them, a desktop notifcation said it was being sync'd
* I can add other users via the GUI, and their folders are accessible on my filesystem
* have not yet checked whether other keybase users can mount my public files

Keybase GUI Version: 1.0.9-20160205170023+ce05b7a

**Comment by patcon** [comment]
OK, @tehbmar informed me that he can mount my public dir and see the files. So it seems that it's the web UI.

Let me know if I should reticket in another repo :)

**Comment by strib** [comment]
Hi @patcon.  I think this is a known bug that we have an outstanding fix for (pending internal code review right now).  Looks like it's working on keybase.pub (https://keybase.pub/patcon/), so I think you are good to go.  (We probably just needed to restart the KBFS daemon on the GUI.)  Please close if things seem ok to you now.

**Comment by patcon** [comment]
Yep, looks good to me! Thanks! I did restart quite a few times fwiw, using `keybase ctl restart`. This seemed to require another `keybase unlock` as well

**Comment by strib** [comment]
It wasn't you that needed the restart, it was our daemon on KBFS pub.  Sorry for the confusion.
