### ISSUE TITLE
Keybase client freezing on Debian Buster.

### ISSUE THREAD

**Issue by nickray** [keybase/client#19215]
Not sure what's going on, `run_keybase` unfreezes but it's a bit painful.

my log id: ce2b03ac23b81f655ba51f1c

**Comment by heronhaye** [comment]
Is it freezing or crashing? Has this always happened on this Buster system or is this new behavior after an update? Does `notify-send hey` work in a terminal?

**Comment by nickray** [comment]
It freezes. Can't type, no more new messages. There were no recent relevant Buster updates I believe; it's become worse recently. Will check `hey` next time.

**Comment by nickray** [comment]
What is the exact command? I don't see a `keybase notify-send` command.

**Comment by heronhaye** [comment]
It's provided by `libnotify`. There's a problem where the client can freeze upon trying to display a notification when there's no notification server running. Could this be related to your issue? You can trigger a "Permission denied" notification by running `ls /keybase/private/notme`. Does the client freeze when you do that?

(See https://github.com/keybase/keybase-issues/issues/3438)

**Comment by nickray** [comment]
That was it, thanks. Now to figure out why xfce4-notifyd doesn't run...
