### ISSUE TITLE
/keybase/public/chris causes hangs and brokenness

### ISSUE THREAD

**Issue by Habbie** [keybase/client#1922]
```
[peter:/keybase/public] $ cd chris
[peter:/keybase/public/chris] $ ls
ls: .: Device not configured
[peter:/keybase/public/chris] 1 $ ls -al
ls: .: Device not configured

```

after the `cd`, my whole terminal (iTerm2) started beachballing. This lasted for at least a minute. Then I started Terminal and typed `open /keybase/public/chris`. This did not work (`The file /keybase/public/chris does not exist.
`), but at that moment iTerm stopped beachballing - except the whole /keybase filesystem was now dead.

About two minutes later I got a popup with Chris' face on it asking me to confirm that he is a writer of that dir, I retried the `open` and the `cd` and now everything appears to work.

my log id: 2035c4659cd28e18857ba31c

**Comment by noxowe** [comment]
@Habbie with which method did you install KBFS? + which OS do you use?

**Comment by strib** [comment]
Hi @Habbie -- hmm, from your logs I don't see any weird gaps or kbfs restarts that would explain what you saw.  By chance, do you remember about what time this happened, so I can try to correlate it to a point in the logs?

**Comment by Habbie** [comment]
@strib with `%s` timestamps from bash history:

  555  1454757698 cd chris
  556  1454757763 ls
  557  1454757765 ls -al

@noxowe downloaded DMG from site (version 1.0.7 or similar). OS is OS X 10.10. I just got an upgrade note for keybase 10.0.10-20160206170009+ade448b, will report back if this also breaks.

**Comment by strib** [comment]
Thanks.  Some recent changes to the way we locally initialize folders makes for a bad user experience on OSX when something is causing the operation to take a long time (network latency, etc).  All KBFS operations are supposed to timeout after 19 seconds, but looking in a folder for the first time no longer does.  Unfortunately under OSXfuse, that means once the operation takes longer than a minute, your whole mountpoint goes away (hence the "device not configured" error.  We will get this issue fixed ASAP.

I don't have much to go on in the logs about why this particular operation took so long for you.  It could have been random network connectivity issues, or a deadlock somewhere in our code.  It's hard to say.  It doesn't look to me like any of your requests during this time made it to our KBFS servers, but that's all I can say.  You resolved the "chris" username using the Keybase API server, but nothing after that worked:

```
1464 2016-02-06T12:21:38.130500 ▶ [DEBU keybase api.go:135] 5b8 + API GET request to https://keybase.io/_/api/1.0/user/lookup.json?fields=basics&multi=1&username=chris
1465 2016-02-06T12:21:38.267636 ▶ [DEBU keybase api.go:210] 5b9 | Result is: 200 OK
1466 2016-02-06T12:21:38.267741 ▶ [DEBU keybase api.go:518] 5ba - successful API call
```

There's a big gap in the logs after this where I have no insight into what is happening.

The best I can do right now is fix the timeout issues and add more debugging, and we'll have to see if we can reproduce.

**Comment by strib** [comment]
A fix for the indefinite hang is in master, and will be included in tomorrow's release.  Once you upgrade, if you hit this again, please open a new bug and we'll hopefully be able to track it down a little better.  Thanks for the report!

**Comment by Habbie** [comment]
Thanks!
