### ISSUE TITLE
Disable autostart on boot

### ISSUE THREAD

**Issue by TheBubblePopped** [keybase/client#19224]
Where for gods sake is the button to disable autostart on bootup?

**Comment by heronhaye** [comment]
If you're on Linux, try `keybase ctl autostart --disable`

**Comment by tobypinder** [comment]
There are workarounds (as @heronhaye suggests) but every other Electron-like app I use has this toggle in the options. It becomes an impediment to rolling this out within an organisation if we have to tell people to follow complex post-install tasks from the terminal.

**Comment by TheBubblePopped** [comment]
I uninstalled it before getting this answer and i will most likely never come back just for the reason @tobypinder pointed out. 
My though was that i alrdy spend too much time figuring out. 
But thank you heronhaye for answering anyway.

**Comment by TheBubblePopped** [comment]
Keybase ctl autostart --disable didn't work on a friends pc. His keybase got uninstalled as well now. 
!Warning Permission denied opening guo config file!

**Comment by heronhaye** [comment]
@TheBubblePopped It'd be helpful to do a `keybase log send` and also `cat ~/.config/autostart/keybase_autostart.desktop` to help us debug the problem.

**Comment by heronhaye** [comment]
In Keybase 5.0, you can change this setting on all platforms. Please make a new issue if you are still having trouble. Thanks!

**Comment by heronhaye** [comment]
As of Keybase 5.0, you can change the autostart settings in the GUI in the Settings tab on all platforms. Please make another ticket if you're still having trouble. Thanks!
