### ISSUE TITLE
public folders don't exist

### ISSUE THREAD

**Issue by timonson** [keybase/client#19227]
my log id: 3b65b6fa6d1149f2a0e3401c

The following is happening since I reset my account:
When I type 'cd /keybase/public/timonson' (any username) into the terminal or when I try to access a public folder or file through your GUI it says: "No such file or directory" or "Failed to open path" respectively.
I can access the files through the GUI but it fails to open them when I click on 'Show in File Explorer'.

The files I had in my folder before I reset the account are gone, which I guess is what we would expect.

I reinstalled the app via keybase-bin on arch but the problem continues.

**Comment by strib** [comment]
@timonson it looks like your computer doesn't have the FUSE module installed, which is required for file system access:

```
2019/09/01 19:42:50 mount helper error: fusermount: fuse device not found, try 'modprobe fuse' first
```

Most distros come with it installed by default, but maybe your arch distro doesn't?

**Comment by timonson** [comment]
Thank you for the help. The module was already installed but I suspect that something in relation to it crashed that day on my system. I really don't know exactly what it was, but it started working again the next day. So problem solved, I guess.
