### ISSUE TITLE
Can't prove GitHub account

### ISSUE THREAD

**Issue by Ryan-Goldstein** [keybase/client#19347]
I'm getting an 'UNREACHABLE' error when trying to prove my GitHub account:

![keybase-github-unreachable](https://user-images.githubusercontent.com/8300089/64558794-c2a55d00-d312-11e9-8fb6-85c36adf1a5e.png)

Here's the gist: https://gist.github.com/Ryan-Goldstein/34ac45a36dab204ccc02312f1a9c01d5

Any ideas?

**Comment by Ryan-Goldstein** [comment]
It seems to have resolved itself; I guess it was a temporary glitch.

**Comment by eikaramba** [comment]
i have the same problem
