### ISSUE TITLE
airdrop group

### ISSUE THREAD

**Issue by bitdeep** [keybase/client#19360]
Hi... I'm admin of airdrop group on keybase, I'm getting some users here in preparation for airdrop.
Can someone ask keybase team to contact me about what to do with the group? 
For now, posting on group is closed to admin only to prevent users posting dangerous links.

**Comment by SF52Akurey** [comment]
yeah.... seems not working the connection between github andkeybase....

**Comment by bitdeep** [comment]
Contacted chris on Keybase, the group now point to oficial keybase page.
