### ISSUE TITLE
Stellar federation addresses don't get resolved correctly

### ISSUE THREAD

**Issue by s-a-y** [keybase/client#19388]
When you enter address like 
`umbre1*papayabot.com`
Federation request is sent to 
`https://papayame.com/api/federation?q=umbre1*papayabot.com&type=name`

Which comes back with 3 important pieces of information:
- account_id
- memo_type
- memo

All three are required to make sure payment reaches the correct user, because some services (including papayabot.com and apay.io) have 1 address for all users and differentiate users based on memo provided.

Currently keybase populates the account_id, but leaves memo to be filled by the user (who has no idea, that some specific memo is mandatory)

Correct behaviour: populate memo with values from federation response and restrict user ability to change it.
If federation response doesn't contain memo_type/memo, then you can keep it as is and let user put the memo

Sites like
stellarport.io do it correctly.

**Comment by pselden** [comment]
Yes this is pretty important to handling federation. If any of the big exchanges ever implemented federation addresses they would be unusable because of this.

**Comment by patrickxb** [comment]
This is fixed and will be in the next release.
