### ISSUE TITLE
Screenshot on Android 

### ISSUE THREAD

**Issue by mdzor** [keybase/client#19380]
Hi!
Any reason for preventing screenshot from the android app? I understand that you are promoting keybase team as a way to communicate with group of friends, family etc.
Which is good, but what chat app would prevent its user to screenshot his own chat ? 

Thank you!

**Comment by mdzor** [comment]
![image](https://user-images.githubusercontent.com/7092335/64586821-13c75680-d3d0-11e9-9c3c-3c345fb2f22b.png)

**Comment by kcseb** [comment]
Go the menu on your Keybase app (looks like a little hamburger) and click 'Screen Protector'...
https://i.imgur.com/drBDKk6.jpg

Disable the 'Screen Protector' option...
https://i.imgur.com/Wd25uRE.jpg

Screenshots should now work without issue throughout the application.
