### ISSUE TITLE
Failed to open path: /keybase/private. Failed to load TLF lists.

### ISSUE THREAD

**Issue by avalonv** [keybase/client#19383]
The files tab won't load, I get lots of errors, similar to #16474

I'm on Void Linux, keybase version 4.4.0

![2019-09-09-223642_maim](https://user-images.githubusercontent.com/29720696/64578675-8693eb80-d356-11e9-831f-77d9517e6f2f.png)

**Comment by strib** [comment]
If you do a `keybase log send`, and post the resulting ID here, I can take a look.

**Comment by luksamuk** [comment]
Same thing happens to me. Here is what I tried:

- kbfsfuse was complaining about `/run/user/1000/keybase/keybased.sock`, which did not exist. I had to add `export XDG_RUNTIME_DIR=""` so it would look where it was supposed to;
- kbfsfuse then complained about `~/.config/keybase/keybased.sock`, which also did not exist. I logged off, deleted the `~/.config/keybase` folder, ran `run_keybase` again.
- The Keybase client fails after I type in my username with a "There was an error provisioning" error.
- The Keybase CLI login (`keybase login`) fails with an "ERROR EOF".

My log ID: `6bee8f915b129a900e627d1c`

**Comment by avalonv** [comment]
@strib my log id is `f88ad12c8776bf95a976591c`

**Comment by strib** [comment]
Hi @avalonv -- I've never looked at Void Linux before, and I'm not sure how packages are made for it, but it seems like you're running a very old version of the `kbfsfuse` binary, though the other binaries (`Keybase`, `keybase`) seem like they might be up to date.  If you built it yourself, make sure you build it from the source in the github.com/keybase/client repo (under `go/kbfs/kbfsfuse`), and NOT from the `github.com/keybase/kbfs` repo, which is old and deprecated.

@luksamuk I can't tell what distro you're on, but it seems to be a similar issue, with the `kbfsfuse` binary being old.

**Comment by luksamuk** [comment]
> Hi @avalonv -- I've never looked at Void Linux before, and I'm not sure how packages are made for it, but it seems like you're running a very old version of the `kbfsfuse` binary, though the other binaries (`Keybase`, `keybase`) seem like they might be up to date. If you built it yourself, make sure you build it from the source in the github.com/keybase/client repo (under `go/kbfs/kbfsfuse`), and NOT from the `github.com/keybase/kbfs` repo, which is old and deprecated.
> 
> @luksamuk I can't tell what distro you're on, but it seems to be a similar issue, with the `kbfsfuse` binary being old.

Thank you for your reply. Just want to say that I am also a Void Linux user, since I did not make it very clear.
