### ISSUE TITLE
File created in public folder using Keybase FS not showing up on Keybase.pub.

### ISSUE THREAD

**Issue by CameronBanga** [keybase/client#1938]
Had created a file on Friday and placed it in my /public folder. I created it using Vim, after cd-ing into my public folder. Here's a screen grab of what I see, and explains the problem a bit. Basically, can't see this folder on my keybase.pub page, although it definitely exists on my computer in my /public folder.

<img width="1605" alt="napkin 02-08-16 11 41 18 am" src="https://cloud.githubusercontent.com/assets/611354/12893799/dfbce7ea-ce58-11e5-80a6-fb1e44d9f302.png">
 
my log id: 5c9a9e5315e70eb414a1841c

**Comment by strib** [comment]
This is a known problem (#1855), and will be fixed the next time we update KBFS on keybase.pub.  Sorry!
