### ISSUE TITLE
Keybase app shows Github proof as 'unreachable'

### ISSUE THREAD

**Issue by xkessonx** [keybase/client#19398]
Hello. My Windows Keybase app tells: Your proof could not be found. Keybase has stopped checking. How would you loke to proceed. Here's the link: https://gist.github.com/xkessonx/59f54c3dc925592d3b5a2f87d6a724e1 and here's the link to Keybase https://keybase.io/xkessonx/sigchain#eab4a7a2c9dc331ba890cb0bfed01bddaa7c4d351b6ff4ba7d9170e06b7baad50f (why the last line is crossed out?)
But I did everything right. Can anyone help me with this?

win promt:
C:\WINDOWS\system32>keybase prove github
You already have a proof for xkessonx@github; overwrite? [y/N]  wtf?

But the app says unreachable thing

**Comment by erikdstock** [comment]
Is the gist private? Your link is a 404 and if keybase cannot find it then you will not be verified.

**Comment by xkessonx** [comment]
Yes. It is public.  I tried for 3 times to do that (forgot to update the link). Check it out now. The coomand promt says that the gist is private (facepalm) and cannot resolve the issue with it. I think that this thing is  buggy like hell. I copy everything that the app suggests, do the check thing..aannnddd....I get the unreachable thing. Tried out for 2 hours...nothing happens.
