### ISSUE TITLE
Access to folder

### ISSUE THREAD

**Issue by MyC-Greg** [keybase/client#19405]
Keybase GUI Version: 4.4.0-20190829183920+8f13068775
My log ID is:
  a2a2801b308766ff8719ea1c

Hi I can't access my keybase folder, neither on the finder nor directly in the app (through my mac). I still have access to the docs on my mobile. 
While trying to access my docs through the finder I get this error:
`The folder “Keybase (gregoirenedelec)” can’t be opened because you don’t have permission to see its contents.`
and on the keybase app:
`an unexplainable error occured`
`Failed to load TLF list`
`Error: ERROR CODE 218 - Keybase services aren't running - KBFS client not found. in method keybase.1.SimpleFS.simpleFSSyncStatus at new s (file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/main.bundle.js:1:561326) at file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/main.bundle.js:1:561922 at u (file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/main.bundle.js:1:561961) at file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/main.bundle.js:1:1242674 at file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/main.bundle.js:1:3018547 at e._call (file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/main.bundle.js:1:2580383) at file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/main.bundle.js:1:2580523 at s (file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/main.bundle.js:1:2580163) at e._fulfill (file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/main.bundle.js:1:2580493) at (file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/main.bundle.js:1:2579694)`

Any help would be welcome!

**Comment by maxtaco** [comment]
cc @strib

**Comment by strib** [comment]
Hi @MyC-Greg, thanks for the report.  It looks like you've uncovered a looping crasher bug in the KBFS code. I need to investigate more how this happened, but in the meantime I think you can recover it with the following steps.  However, this will rewind your local view of a team folder that you've recently written to (data that you wrote but hasn't yet been saved on our servers yey, so no other team members have seen it).  If you can't recover this data from elsewhere on your system, let me know and I can work with you to recover it from the backup folder made by the steps below.

Here's what to do:

1. Stop the Keybase app completely.
2. Run this command from a terminal:
```sh
mv "$HOME/Library/Application Support/Keybase/kbfs_journal/v1/012066403ca721b8a42b5699a3c5ae4d20cd-fb7600b43fd927fe" "$HOME/Library/Application Support/Keybase/kbfs_journal/v1/fb7600b43fd927fe.bkp"
```
3. Re-launch the Keybase app.

Let me know if that seems to fix it for you.  I'll look into what caused the problem in the first place.

**Comment by MyC-Greg** [comment]
Hi @strib , the hack works fine with me, I have access to my folders both in the keybase app and through the finder. Thanks!
