### ISSUE TITLE
proof has failed 

### ISSUE THREAD

**Issue by akecew** [keybase/client#19409]
im have a problem to link github account and i have email notify  *We've been checking it repeatedly, and from our perspective, it's either (a) not there, or (b) not posted precisely.*
do you can help me

**Comment by erikdstock** [comment]
did you post the public gist?

**Comment by Loutenant4** [comment]
delete the gist you have and then go to your windows command prompt.
type in 
keybase prove github
i don't remember exactly what happens, but i copied and pasted the text from the command prompt into a new public gist, and in command prompt it asked me if i wanted to check again.  when i said yes, it worked in less than 2 seconds.

**Comment by akecew** [comment]
@erikdstock
yes but proof failed
do you can help me

**Comment by Loutenant4** [comment]
did you read my comment?  everyone seems to be having the same problem when trying to verify the github through the app.  until keybase fixes something on their end, you'll have to use the command prompt method.

**Comment by akecew** [comment]
@loutenant4
i try this wait 😉

**Comment by akecew** [comment]
@loutenant4
 command prompt in web or in computer
because i play keybase in phone

**Comment by Loutenant4** [comment]
I had to do this from my computer.

**Comment by akecew** [comment]
done, but i dont know my proof succesfully🤣
thanks for your help @loutenant4
