### ISSUE TITLE
Github proof unreachable

### ISSUE THREAD

**Issue by peterjmarko** [keybase/client#19400]
Created public keybase.md using code from Keybase
Keybase says "Your proof could not be found"
"I fixed it - recheck" still gives the same answer ("unreachable")

**Comment by krishanbtc** [comment]
Wait for half an hour and you will be visible

**Comment by peterjmarko** [comment]
Will try - thank you!

**Comment by xkessonx** [comment]
Did it work?

**Comment by peterjmarko** [comment]
Yes, it did. Wait was much less than a half hour, maybe ten minutes.

**Comment by xkessonx** [comment]
I'm waiting for more than an hour - nothing happens

**Comment by xkessonx** [comment]
C:\WINDOWS\system32>keybase prove github
You already have a proof for xkessonx@github; overwrite? [y/N]... WTF?

**Comment by peterjmarko** [comment]
No idea, sorry - I'm new to Keybase

**Comment by xkessonx** [comment]
> No idea, sorry - I'm new to Keybase

Same theing. It is great that this buggy thing let you in.
