### ISSUE TITLE
kbfs keybase client not logging in correctly first time

### ISSUE THREAD

**Issue by simonjgreen** [keybase/client#1943]
On both of my devices the kbfs client errors during `keybase login` with:
`WARNING error saving exported gpg key in lksec: k.ToLksSKB() error: openpgp: invalid argument: unknown private key type`
`ERROR k.ToLksSKB() error: openpgp: invalid argument: unknown private key type`

When I run `keybase login` again it completes without error, and apparently logs in.

OSX log id: 3fc737e3afe58859adaac11c
AND
Ubuntu log id: de1b29340c7153b5589acf1c

**Comment by maxtaco** [comment]
Do you have an ElGamal encryption subkey?  I think we've fixed this issue, not released yet.

**Comment by simonjgreen** [comment]
Yes it's a 2048 ElGamal.

**Comment by maxtaco** [comment]
Yes, it's fixed in master. Same as keybase/keybase-issues#1943. Thanks for the bug report!

**Comment by simonjgreen** [comment]
What are the odds of both reports being ID 1943?!

**Comment by maxtaco** [comment]
Wow, very cool.
