### ISSUE TITLE
Getting LastFlushErr of "couldn't evict any more blocks from the disk block cache"

### ISSUE THREAD

**Issue by 501st-alpha1** [keybase/client#19445]
Keybase got stuck on uploading a file to KBFS again, and this time `.kbfs_status` shows:
```
"LastFlushErr": "couldn't evict any more blocks from the disk block cache"
```

I did have low free space when I first got the error, but I have since cleared it up so I have 1.1 GB free, and have restarted Keybase since then, but that didn't help.

Log ID is 238f32029c9322e3193e6b1c.

**Comment by strib** [comment]
@501st-alpha1 hmm, seems like the cache db on disk might be in some weird corrupt state, likely related to running out of disk space.  Maybe try:

1. Stopping Keybase and KBFS completely.
2. `rm -rf $HOME/.local/share/keybase/kbfs_block_metadata/`
3. Restart Keybase+KBFS

This just blows away the transient performance cache, without causing any server or local data loss.

**Comment by 501st-alpha1** [comment]
I tried that just now but I'm still getting the same error.  New log ID is bdbc1b645232b2ef062bea1c if you need it.

**Comment by strib** [comment]
Ah, I should have said:

```
rm -rf $HOME/.local/share/keybase/kbfs_block_{cache,metadata}
```

If you do that, is it any better?  Sorry.

**Comment by 501st-alpha1** [comment]
No problem.  Yes, that one worked, thanks!
