### ISSUE TITLE
Привет всем ! Желаю щастья!

### ISSUE THREAD

**Issue by Juliko68** [keybase/client#19489]
Много хороших XLM

**Comment by id1609** [comment]
Я сегодня зарегистрировался на GitHup.
Не пускают в airdrop. Что можно сделать чтобы пустили?

**Comment by Juliko68** [comment]
чтобы пустили , надо быть зарегистрированым до 9.09 2019 .но не позже. Так
 как вы зарегились сегодня все ето в пустую🚿🏬🗿🗿🗿🗾🗽

ср, 11 сент. 2019, 18:07 id1609 <notifications@github.com>:
