### ISSUE TITLE
Files missing from keybase.pub

### ISSUE THREAD

**Issue by bkendall** [keybase/client#1949]
I put a couple files into `/keybase/public/bkendall`, however they haven't shown up in the UI yet. Submitting in hopes that it will be useful!

my log id: eb1bc1460c8446146a3c401c

**Comment by simonjgreen** [comment]
it took quite a while for them to appear first time for me, but now changes are nearly instant

**Comment by bkendall** [comment]
okay, I'll keep watching, for sure. https://keybase.pub/bkendall

**Comment by cjb** [comment]
This one's a bug that we landed a fix for today, it'll be fixed soon when I upgrade the keybase.pub machine to the latest package.

**Comment by strib** [comment]
Dup #1855, though thanks for the report!

**Comment by bkendall** [comment]
much success! :+1:
