### ISSUE TITLE
I'm not qualified for xlm airdrop

### ISSUE THREAD

**Issue by ubiqland** [keybase/client#19493]
I'm on GitHub from may2019 and correctly 
Registered on keybase but when I try to Joy to ad ...I have a red x ☹️☹️☹️☹️

**Comment by Flangler** [comment]
How can I check If I'm qualified for and airdrop. I can't find this option in the app.

**Comment by kenorb** [comment]
> How can I check If I'm qualified for and airdrop. I can't find this option in the app.

Go to Wallet tab of your Keybase app and check the Airdrop section.

**Comment by Flangler** [comment]
The point is that I don't have the AIrdrop section in my APP. https://imgur.com/xyMxQ1U

**Comment by kenorb** [comment]
> The point is that I don't have the AIrdrop section in my APP. https://imgur.com/xyMxQ1U

Then you're not qualified.

**Comment by ubiqland** [comment]
The airdrop  tab it's disappeared...

**Comment by ubiqland** [comment]
https://keybase.io/a/i/r/d/r/o/p/spacedrop2019

Il mer 18 set 2019, 14:29 Rafal W. <notifications@github.com> ha scritto:

**Comment by ubiqland** [comment]
https://keybase.io/a/i/r/d/r/o/p/spacedrop2019

**Comment by skateman12** [comment]
Hi, im not able to qualify and i dont get why. Its written im living in an approved country. I add two phone numbers (verified) to my account and its still saying that i still havent success this condition. What can i do? Thanks you
