### ISSUE TITLE
KeyBase.md

### ISSUE THREAD

**Issue by MansterG** [keybase/client#19508]
### Keybase proof

I hereby claim:

  * I am mansterg on github.
  * I am manster (https://keybase.io/manster) on keybase.
  * I have a public key ASDMzczokB-ycW4zUUvDCe8UTfmzdsf_6K-AlL783FHsRgo

To claim this, I am signing this object:

```json
{
  "body": {
    "key": {
      "eldest_kid": "0120cccdcce8901fb2716e33514bc309ef144df9b376c7ffe8af8094befcdc51ec460a",
      "host": "keybase.io",
      "kid": "0120cccdcce8901fb2716e33514bc309ef144df9b376c7ffe8af8094befcdc51ec460a",
      "uid": "1f18da866f859723ef1ecfef274bc219",
      "username": "manster"
    },
    "merkle_root": {
      "ctime": 1568230656,
      "hash": "b890ed49f9256d95495b6620abb8856b39f52e1dee6ee4cfd978b756c016e0249da8b16293c8289212fadae38d9788664dc8e48d402983aeb406cb670667cb7d",
      "hash_meta": "db97f7d28a06031c7a0653289f22e7b80f2090c0671b771ddec42ca9f4cb7516",
      "seqno": 6800208
    },
    "service": {
      "entropy": "z5uLIRvHcyE5ifLJnFSSYVNG",
      "name": "github",
      "username": "mansterg"
    },
    "type": "web_service_binding",
    "version": 2
  },
  "client": {
    "name": "keybase.io go client",
    "version": "4.4.0"
  },
  "ctime": 1568230662,
  "expire_in": 504576000,
  "prev": "e457a4a312384701b6e1574e9c63efe6d96b7ca98f554e876aa00ff72cdf7231",
  "seqno": 9,
  "tag": "signature"
}
```

with the key [ASDMzczokB-ycW4zUUvDCe8UTfmzdsf_6K-AlL783FHsRgo](https://keybase.io/manster), yielding the signature:

```
hKRib2R5hqhkZXRhY2hlZMOpaGFzaF90eXBlCqNrZXnEIwEgzM3M6JAfsnFuM1FLwwnvFE35s3bH/+ivgJS+/NxR7EYKp3BheWxvYWTESpcCCcQg5FekoxI4RwG24VdOnGPv5tlrfKmPVU6HaqAP9yzfcjHEIAAnGmHlV1L6rTC+V8C+mqTkZXth/OGsmMGyEagds4xIAgHCo3NpZ8RAYQAR0Ip9gnEeejzglnL6C+8MWINZ5gD84CJAPcbfA1y0JaDBesgcBmavcYDq7odmGPifki672f4fXxpdhzaCDKhzaWdfdHlwZSCkaGFzaIKkdHlwZQildmFsdWXEIDK9BrwxdIfYS4PRQLxRrmQ6q/SayD3FSG8W4KIeUZUNo3RhZ80CAqd2ZXJzaW9uAQ==

```

And finally, I am proving ownership of the github account by posting this as a gist.

### My publicly-auditable identity:

https://keybase.io/manster

### From the command line:

Consider the [keybase command line program](https://keybase.io/download).

```bash
# look me up
keybase id manster
```

**Comment by paxart-81** [comment]
{
  "body": {
    "key": {
      "eldest_kid": "01207b620c9b4c4587928a78570b80eff57a8846f6618fb59107e4ff39c3db3cc14e0a",
      "host": "keybase.io",
      "kid": "01207b620c9b4c4587928a78570b80eff57a8846f6618fb59107e4ff39c3db3cc14e0a",
      "uid": "09b3457bd50dacc56c8e35a6ac0c5719",
      "username": "paxart"
    },
    "merkle_root": {
      "ctime": 1568240719,
      "hash": "888fb8bf8333ae680c6d3837da8127db2d768d24df2d06827a6fd836db2ce1412c7e75530a5a6efd86840d6c23ebae1e8e8ad95f01f09ec0a3a28fb8985ead62",
      "hash_meta": "d7de3bdcb11c9f20a5ce1d415426e18d0c9bcf956a5ddd88e572e50d3008e7eb",
      "seqno": 6828683
    },
    "service": {
      "entropy": "OR3ie8fupHOhEVp2tY/5OGUv",
      "name": "github",
      "username": "paxart"
    },
    "type": "web_service_binding",
    "version": 2
  },
  "client": {
    "name": "keybase.io go client",
    "version": "4.4.0"
  },
  "ctime": 1568240730,
  "expire_in": 504576000,
  "prev": "193844d6f3f858340acc0665e163774decba49b4f0a91b86befb03aeb96b2487",
  "seqno": 5,
  "tag": "signature"
}
