### ISSUE TITLE
Join airdrop Error 505 Database

### ISSUE THREAD

**Issue by vakhoa1410** [keybase/client#19515]
Hi, I can not join airdrop since I got every verifed

`Error: ERROR CODE 505 - DB error in method stellar.1.local.airdropRegisterLocal at new s (file:///opt/keybase/resources/app/desktop/dist/main.bundle.js:1:550669) at file:///opt/keybase/resources/app/desktop/dist/main.bundle.js:1:551265 at d (file:///opt/keybase/resources/app/desktop/dist/main.bundle.js:1:551304) at file:///opt/keybase/resources/app/desktop/dist/main.bundle.js:1:1223905 at file:///opt/keybase/resources/app/desktop/dist/main.bundle.js:1:2974754 at e._call (file:///opt/keybase/resources/app/desktop/dist/main.bundle.js:1:2558372) at file:///opt/keybase/resources/app/desktop/dist/main.bundle.js:1:2558512 at s (file:///opt/keybase/resources/app/desktop/dist/main.bundle.js:1:2558152) at e._fulfill (file:///opt/keybase/resources/app/desktop/dist/main.bundle.js:1:2558482) at s (file:///opt/keybase/resources/app/desktop/dist/main.bundle.js:1:2557683)`

**Comment by Arceus17** [comment]
Yeah me too

**Comment by 4eldovek** [comment]
same problem 505

**Comment by kenorb** [comment]
Related:
- https://github.com/keybase/client/issues/15257#issuecomment-531395333
- #19515
- #19531
- #19548
- #19572
- #19642
- #19644
- #19646
- #19647

**Comment by kenorb** [comment]
Solved: #19718
