### ISSUE TITLE
kbfs - shared, public, private inaccessible

### ISSUE THREAD

**Issue by mannkind** [keybase/client#1952]
break ALL the things. 

I initially had kbfs working between my Mac and a Linux VM. I tried to do a private share another user kbfs user, and was getting input/output errors. I thought *maybe* I was doing something wrong, and revoked one of the machines … apparently the last one to touch my public/private folders. Le sigh. I've locked myself out of everything, heck, even keybase.pub/mannkind is broken for me (I seem to be in a similar state as keybase.pub/zdsmith)

Fwiw, probably not terribly relevant now but my log id: ee69d966bb1b1cee3c6f641c

**Comment by strib** [comment]
Yeah, you hit our main weak spot.  Do you want us to reset `private/mannkind` and `public/mannkind` to a revision signed by a non-revoked key?  You will lose whatever data you wrote with the revoked device (though it's basically lost now anyway).

Is the log you mention above the one that shows the I/O errors you were getting that led you to do the revoke?  I don't see anything obvious before the revoked-device-key errors start, although I'm not exactly sure what time in the log I should be inspecting.

I see other I/O errors as a result of trying to make a folder with another Keybase user (I'll refrain from saying the name here in public), someone you had previously tracked but now one of their proofs is broken and you likely need to re-track them.

**Comment by strib** [comment]
I should note that resetting folders is not going to something we plan to do after the next major release, once we have the infrastructure in place to check whether a folder revision happened before a key was revoked.  It's obviously a little sketchy for us to do that, and once we start hashing the KBFS roots into the blockchain, we won't be able to pull this kind of stuff off.  But for now, we're in super-early alpha and reserve the right to throw your data out the window, so . . . we're here to help!

Though, I'd feel better if you could post a signed statement here with a key from the mannkind sigchain, or write something into `/keybase/private/strib,mannkind`, asking me to do the resetting.

**Comment by mannkind** [comment]
Left you a note in /keybase/private/strib,mannkind - let me know if I need to do more. 

No worries about losing data, I was really just echoing short strings into files (both publicly and privately). And as this was a preview, I don't expect anything to stick around anyway. 


I'm not exactly sure what the log sent you, but I did the revoking in the early afternoon (PST). I know another user (same as I mentioned in the shared file) tried to share a file with me, but I never could see it. 


Again, sorry for breaking all the things so quickly. I wanted to actually help test kbfs, not be a burden. Bah.

**Comment by strib** [comment]
No worries, thank you for testing!  Didn't intend to imply you were being a burden, just didn't want the general public to think we were resetting folders willy-nilly.

I've asked our folder-resetter to roll your public folder back one revision.  Your private folder, however, looks fine, it was last written by a different device.  The I/O errors are because it looks like a rekey hasn't happened for that folder yet, using an existing device or paper key with the proper access.  Your remaining device is with access to that directory (I'm guessing the device you call "Apollo") needs to connect to KBFS to give your new device access to it.  Looks to me like it hasn't connected in 6 hours or so.

**Comment by strib** [comment]
(By the way, the "folder-resetter" I reference above is a human being who may be asleep, so this might not happen until tomorrow.)

**Comment by aalness** [comment]
Hey @mannkind you should be all set. Mind performing at least one write to that folder asap and letting us know if it worked? Thanks!

**Comment by strib** [comment]
And I left you a note in our shared folder about why the private share with your friend isn't working.  You should have had a tracker popup when you tried to access the shared folder inviting you to re-track the individual.  Do you remember if that happened or not?

**Comment by aalness** [comment]
@mannkind to be clear: the folder I'm referring to is your public folder.

**Comment by mannkind** [comment]
@strib Thanks for the info via our share - I've re-tracked the user and I can now see the file shared with me. Sweet! A tracker popup did not happen for me – not on the Mac nor the Linux VM.

@aalness Thank you for your help. I'm still unable to write to the public share from either machine (just a quick echo to file test). Tried to submit a clean log - 46cafd39b2bd1529c3adff1c

**Comment by strib** [comment]
D'oh, the revision we reverted to was written by ANOTHER device you revoked ("HeliosVM").  Sorry, I didn't notice that you had multiple revokes.  Let me figure out what revision has a good key and we'll get back to you.

**Comment by strib** [comment]
Actually, that folder has never been written to by a device that isn't now revoked.  Bleh.  I guess we'll just have to delete the whole thing.

**Comment by mannkind** [comment]
Works for me ("deleting the whole thing") – Sorry, at the time I thought I'd just "start fresh", but sounds like I just made it worse.

**Comment by strib** [comment]
@cjb: any clue why a tracker popup didn't happen for the "1 track component failed" error in logs ee69d966bb1b1cee3c6f641c?

**Comment by cjb** [comment]
@strib I can't easily tell if it's the case here, but we have an open bug where the tracker popup isn't shown if the track component that failed is the signing statement itself -- i.e. A tracks B, B resets her sigchain, now A has a broken track of B but we don't offer to correct it.

**Comment by strib** [comment]
@cjb: it might be the same thing.  In this case, the sigchain wasn't reset, but all the proofs in it were deleted and then later re-done.

**Comment by aalness** [comment]
@mannkind wiped all revisions for your public folder. Mind giving it a try again? Thanks for your patience!

**Comment by strib** [comment]
And @mannkind we have a revision number on each folder that is not supposed to go backwards, but in your case it has.  So to avoid confusing clients that may have already tried looking at your public folder (including keybase.pub) you might do something like this within the folder:

```
i=0; while [ $i -lt 12 ]; do touch $i; rm $i; i=$[i+1]; done
```

**Comment by mannkind** [comment]
@aalness and @strib  - Thank you so much for your help. Seems like my revisions are working after using that snippet. I've been able to use a private shared folder with another user, and use my public folder (and it shows up on keybase.pub). I can only use my private folder on 'Apollo'; if I try to use it on 'HeliosMBP' I get errors in the logs related to "mannkind does not have read access to directory mannkind" -- I added a log: 8c5cb29e0067a0a593101f1c

No rush or anything. I'm sure you have dev work to do.  Again, I apologize for making such a mess of things. I'll try not to destroy everything again :)

**Comment by strib** [comment]
A log from "Apollo" would be more useful -- that error means the existing device hasn't yet rekeyed the folder to allow in the new device.  So we need to figure out why Apollo hasn't rekeyed.

**Comment by strib** [comment]
Actually, nevermind.  You're not getting the "read access" error anymore.  You're getting:

```
11325 2016-02-09T12:45:15.184658 ▶ [DEBU FUSE serve.go:817] 122b -> [ID=0x8] Lookup error=EIO: Could not verify metadata for directory mannkind: MD (id=4cd22ba2fca674f5d4c5a2931a73cd16) contained unexpected handle uid:5aaa065e52ab8ed0b2122686944d4400
```

Never seen this before.  Investigating.

**Comment by strib** [comment]
Oh actually you did get the "read access" error right before this other error.  Arg.  Logs from Apollo would still be useful.

**Comment by mannkind** [comment]
Log from Apollo: 4cfb022c9004c7638a17f61c

**Comment by strib** [comment]
You managed to tickle another bug here.  Great job finding these!

This one was a bug in our conflict resolution code.  You got into conflict mode when your Apollo device removed a file at the same time your other device requested a rekey.  We hadn't tested this before, and it caused some breakage.  So now that folder on Apollo is in "staged" mode, meaning all the updates to it are local (you won't see them on other devices), and it can't complete any rekeys.  And because of a bug, you are stuck in this mode.

I was able to repro this in our testing framework, and I just merged a fix.  It'll be in tomorrow's builds.  So tomorrow, please upgrade Apollo and then go into your private folder.  That _should_ fix everything.

**Comment by mannkind** [comment]
Sweet - the update this morning fixed the remaining issue! Thank you again for your help @strib and @aalness
