### ISSUE TITLE
Аttempted github identity proof

### ISSUE THREAD

**Issue by marlanpuh89** [keybase/client#19538]
Аttempted github identity proof of @marlanpuh89 never succeeded
link:
https://gist.github.com/marlanpuh89/054495cb0820a0c231ab472d1d6713e6

**Comment by marlanpuh89** [comment]
Sorry, my mistake. Corrected.
https://gist.github.com/marlanpuh89/054495cb0820a0c231ab472d1d6713e6

**Comment by marlanpuh89** [comment]
up

**Comment by kenorb** [comment]
> Sorry, my mistake. Corrected.
> https://gist.github.com/marlanpuh89/054495cb0820a0c231ab472d1d6713e6

Don't correct it, revoke and try again. Keybase should give you the exact gist to copy and paste, so don't try to modify by hand.

**Comment by marlanpuh89** [comment]
Everything worked out. Thank.
