### ISSUE TITLE
How to connect Github to Keybase (Guide)

### ISSUE THREAD

**Issue by farhanleo23** [keybase/client#19535]
I see a lot of people asking this question, so here's a guide for you.

https://www.youtube.com/watch?v=TOuLdeU_4eA

**Comment by CB1965** [comment]
Also, I haven't  Tiweter, Reddit Github
link. My acccounts are from some
years ago.

**Comment by kenorb** [comment]
Here is another guide: https://github.com/keybase/client/issues/12062#issuecomment-392260040

**Comment by kenorb** [comment]
Guide no longer relevant, see #19718

**Comment by touchtonebeats** [comment]
I assume it will work once they sort out security issue
