### ISSUE TITLE
Extremely annoying UI bug

### ISSUE THREAD

**Issue by juanandresgs** [keybase/client#19585]
It seems the UI is exceedingly white throughout the entire app. The issue is consistent across desktop and mobile clients. Requires an urgent fix. The excess white is really annoying considering the app is meant to be used all day.

I think this may be a related issue: #16272. Please address.

**Comment by Angel418** [comment]
Yes, please fix. Even something like a total color-inversion script would be excellent at this point.

**Comment by heronhaye** [comment]
Dark mode released in Keybase 4.6.0 under Settings->Display->Appearance.
