### ISSUE TITLE
'keybase pgp pull' fails with error "GPG error: signal: trace/BPT trap"

### ISSUE THREAD

**Issue by scotthammack** [keybase/client#1958]
When I attempt to run the command 'keybase pgp pull' on OS X, the client returns this error and fails to pull any keys:

> ▶ ERROR GPG error: signal: trace/BPT trap

my log id: 9d2b80cf75cd9a760892291c

**Comment by maxtaco** [comment]
Thanks for the bug report.  Looks like your GPG is crapping out.  What happens if you 

```sh
(curl https://keybase.io/max/key.asc | /usr/local/bin/gpg2 --list-packets) && echo $?
```

thanks!

**Comment by scotthammack** [comment]
> dyld: Library not loaded: /usr/local/lib/libintl.8.dylib
>   Referenced from: /usr/local/bin/gpg2
>   Reason: image not found
>   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
>                                  Dload  Upload   Total   Spent    Left  Speed
> 100  7315  100  7315    0     0   5276      0  0:00:01  0:00:01 --:--:--  5277
> (23) Failed writing body

It's true, there is no /usr/local/lib/libintl.8.dylib, only libintl.8.0.2.dylib. I guess my GPG installation is screwed up somehow... sounds like it's probably not Keybase's fault though.

**Comment by maxtaco** [comment]
Yeah, seems like your local gpg install is horked.
