### ISSUE TITLE
spacedrop locked out

### ISSUE THREAD

**Issue by zvineyard** [keybase/client#19587]
I was unable to authorize a login and ended up reseting the keys in my account. I've now been locked out of a chat with spacedrop that I'd like to read, but it says "participants have to accept to let you back in." Any pointers?

**Comment by smartins** [comment]
> I was unable to authorize a login and ended up reseting the keys in my account. I've now been locked out of a chat with spacedrop that I'd like to read, but it says "participants have to accept to let you back in." Any pointers?

I'm getting the exact same message as well as I needed to also reset the account.

**Comment by brandedux** [comment]
following... 👀
