### ISSUE TITLE
Joined on the 9th

### ISSUE THREAD

**Issue by tableaunaut** [keybase/client#19588]
I joined the airdrop on the 9th, not before, not after. Will I receive the first airdrop?

**Comment by kenorb** [comment]
No, see: https://keybase.io/airdrop

> To qualify: you must have a Keybase account registered before this announcement OR if you're new to Keybase, you must connect your Keybase account to a GitHub or HackerNews account that was registered before this announcement. This is to prevent bot signups to Keybase.

**Comment by ezzygith** [comment]
What of those who registered after 9th Sept. Will they be eligible for October giveway

**Comment by johncodesit** [comment]
@kenorb do you know how to properly connect my github to keybase? I know how to create a repository in keybase but not how to merge it github... thanks in advance

**Comment by kenorb** [comment]
See the guide here: #19535
