### ISSUE TITLE
Can't join 'Team' even though it exists, and I created it.

### ISSUE THREAD

**Issue by brandedux** [keybase/client#19582]
I thought i was just resetting the passphrase for my personal Keybase account (tahoedesigner), but it removed it and I had to add it back. Now I lost access to everything including messages  (says "locked out"). 
![image](https://user-images.githubusercontent.com/32825782/64840157-061bf780-d5af-11e9-86bf-877c0fe9faa5.png)

 The Team is also not allowing me to access it at all from any account and is saying "Root team has been abandoned: All members have left or reset." 
![image](https://user-images.githubusercontent.com/32825782/64840268-8b9fa780-d5af-11e9-8d98-173807b68ed0.png)

**Comment by tahoedesigner** [comment]
bump...

**Comment by maxtaco** [comment]
If you create a team, then reset your account, you cannot access the team you made pre-reset. Resetting deletes all of your keys and makes you a new cryptographic person, you need to accept that disclaimer before we allow it.

Think about it this way: if you could reclaim a team after a reset, then keybase could use the reset feature to steal teams from users, or inject fake users into teams. So it's not arbitrary we have chosen this constraint.

**Comment by tahoedesigner** [comment]
If that is the case, at present it is unusable and forever lost to the community based on what you said which makes no sense to me.

Seems like if there are "no persons" associated with the team including the person who created it, the Team name should go back into a pool after being wiped of any data or key associations (reset) as well, No?

**Comment by maxtaco** [comment]
If we could snap our fingers, sure, but it's complicated to implement and we have a big list of other projects that we think are higher priority.

**Comment by tahoedesigner** [comment]
I wasn't insisting it should be done right away, only that perhaps, there is a more obvious, better approach.
