### ISSUE TITLE
Unable to reset password on Keybase

### ISSUE THREAD

**Issue by smartins** [keybase/client#19597]
I seem to have misplaced my details to login to keybase (have the username and email though), it says I can still login from "Desktop" but I formatted that PC a few weeks ago by re-installing the OS.

I have emails back from 2017 where I confirmed ownership via twitter and reddit.

It doesn't allow me to reset the account because it says I still have one device active (which I don't).

How do I reset the account? Thanks!

**Comment by junderw** [comment]
login on the website and reset all keys

**Comment by smartins** [comment]
Thanks I was able to remember my login password and reset the account.
