### ISSUE TITLE
Not recognizing qualified github account created January 2019 for XLM airdrop 

### ISSUE THREAD

**Issue by glincit** [keybase/client#19604]
![FE60D3C3-4C21-48CD-A8E7-7841E200A465](https://user-images.githubusercontent.com/46649492/64861930-8281fb00-d5ee-11e9-871a-32733b3502c2.png)
![96B5BEE8-CB85-4BBC-AD01-09947B8570F4](https://user-images.githubusercontent.com/46649492/64861931-8281fb00-d5ee-11e9-8b45-7a18bfca98a3.png)
![02121FFD-0934-4FD7-8075-43E88050549A](https://user-images.githubusercontent.com/46649492/64861932-8281fb00-d5ee-11e9-93ec-87d30ec2ce52.png)

**Comment by kenorb** [comment]
Dup of #19603
