### ISSUE TITLE
Airdrop qualifier not recognizing github created 1-2019

### ISSUE THREAD

**Issue by glincit** [keybase/client#19603]
![8404587E-B4EB-443A-8058-DE485342FCBF](https://user-images.githubusercontent.com/46649492/64861427-27033d80-d5ed-11e9-8ba7-2af3761e63fc.png)
![6D5C271A-552A-4E41-AD0B-180FE36B5EC1](https://user-images.githubusercontent.com/46649492/64861428-27033d80-d5ed-11e9-9978-219598c93a72.png)

**Comment by kenorb** [comment]
You didn't connect your GitHub account yet. See your [profile](https://keybase.io/glinc).

**Comment by Aptyp85** [comment]
Hey. I solved it. You need to revoke and send proof again.
