### ISSUE TITLE
Github account created January 2019 correctly linked for XLM airdrop but qualifier not recognizing

### ISSUE THREAD

**Issue by glincit** [keybase/client#19605]
![DE3C331A-5F62-44EF-96FF-F8394013D53D](https://user-images.githubusercontent.com/46649492/64862409-adb91a00-d5ef-11e9-84b2-fd663adffae1.png)
![C3DB1F88-080E-4EFA-8CF0-E9A950FF94AF](https://user-images.githubusercontent.com/46649492/64862410-adb91a00-d5ef-11e9-8939-2d2378fcf93c.png)
![88CF3F61-2596-4323-A7A4-E00491822569](https://user-images.githubusercontent.com/46649492/64862411-ae51b080-d5ef-11e9-9fde-5387115ed57d.png)
![3B25C167-93BB-4843-B111-B2A06B0F6B6C](https://user-images.githubusercontent.com/46649492/64862413-ae51b080-d5ef-11e9-975c-20df6bf8a2a8.png)
![D7892BDB-A583-44CA-AFB0-F006B29C4B04](https://user-images.githubusercontent.com/46649492/64862414-ae51b080-d5ef-11e9-89c7-2fd57206886b.png)

**Comment by kenorb** [comment]
On the screenshot, you've it connected, but on your [profile](https://keybase.io/glinc) I think you revoke it.

**Comment by Aptyp85** [comment]
Hi. Do you solved it? I have the same Problem.
