### ISSUE TITLE
Why my stellar badge was gone ??

### ISSUE THREAD

**Issue by rahasia98** [keybase/client#19600]
![Screenshot_20190913-152845_Keybase](https://user-images.githubusercontent.com/53851675/64848392-4923ac80-d63b-11e9-97d3-035401042ad5.jpg)

What happend ??
All task already successfull complete and now why my stellar badge was gone ??.. and i can't  rejoin airdrop ??

**Comment by qrlk** [comment]
Same.

**Comment by hotbin17** [comment]
Same

**Comment by Rotehut** [comment]
i dont know, But same.

**Comment by rahasia98** [comment]
i know in the rules prohibited use multiple account or bot..
in this case i'm just have one account, and not using multiple account or any bot, but
the badge disappears on its own without any notice...
Dear Keybase team, can u explain what kind of rule is this ???

**Comment by kenorb** [comment]
Related:
- https://github.com/keybase/client/issues/15257#issuecomment-531395333
- #19515
- #19531
- #19548
- #19572
- #19600
- #19607
- #19642
- #19644
- #19646
- #19647

**Comment by kenorb** [comment]
Solved: #19718
