### ISSUE TITLE
Airdrop Error

### ISSUE THREAD

**Issue by Selfmukti** [keybase/client#19607]
[write something useful and descriptive here]
When I try to participate in Stellar airdrop, I get this error

my log id: 46c5904b5dab1357ac1a811c
<img width="549" alt="error" src="https://user-images.githubusercontent.com/22121306/64864000-c56bbf00-d63e-11e9-8df8-93e652ee95f6.png">

**Comment by sky1912** [comment]
me too

**Comment by kenorb** [comment]
Related:
- https://github.com/keybase/client/issues/15257#issuecomment-531395333
- #19515
- #19531
- #19548
- #19572
- #19607
- #19642
- #19644
- #19646
- #19647

**Comment by kenorb** [comment]
Solved: #19718

**Comment by cnukaus** [comment]
Hi, my error message was Keybase can't verify the github signature.

Is the file required keybase.md or keybase.md. (that's what the app displayed, with another dot after filename)? I tried after a few days creating both files and worked.

Are you able to clarify how do I tell if I am registered for the airdrop? (I saw the halt message 16th September). If I have Stellar address associated, is that enough? I understand it is necessary to fight scam, just want to clarify.

Thanks!

**Comment by kenorb** [comment]
> Are you able to clarify how do I tell if I am registered for the airdrop? (I saw the halt message 16th September). If I have Stellar address associated, is that enough? I understand it is necessary to fight scam, just want to clarify.

Open app, go to Wallet tab. If you don't see Airdrop section, then you're most likely not qualified.
