### ISSUE TITLE
Airdropee qualified but shows me error when I join

### ISSUE THREAD

**Issue by beil24** [keybase/client#19646]
Hi, Im qualified airdroper but it's say an error 
![Screenshot_20190914-144228](https://user-images.githubusercontent.com/48794017/64904531-f65ef900-d6fd-11e9-9422-f48807aab5d8.png)
My keybase user name is motoh04
I'm qualified but when I join to airdrop always error using android apps

**Comment by Rotehut** [comment]
Me too

**Comment by manhito** [comment]
Me too

**Comment by kenorb** [comment]
Related:
- https://github.com/keybase/client/issues/15257#issuecomment-531395333
- #19515
- #19531
- #19548
- #19572
- #19642
- #19644
- #19646
- #19647

**Comment by kenorb** [comment]
Solved: #19718
