### ISSUE TITLE
ERROR 505 after i was registered for the airdrop 3 days ago

### ISSUE THREAD

**Issue by Rotehut** [keybase/client#19644]
I just came back to check my account. And I see the golden badge for airdrop disappear and I can't re-register again. What's going wrong?

**Comment by kenorb** [comment]
Related:
- https://github.com/keybase/client/issues/15257#issuecomment-531395333
- #19515
- #19531
- #19548
- #19572
- #19642
- #19644
- #19646
- #19647

**Comment by kenorb** [comment]
Solved: #19718
