### ISSUE TITLE
keybase error Have registered for air drop and passed but now must registered again

### ISSUE THREAD

**Issue by jull27** [keybase/client#19643]
I was registered for airdrop at keybase app ... And it done with pass and im in at airdrop 
It 3 day after update ... Its say im must join airdrop again but always fail and say it error

**Comment by manhito** [comment]
err same

**Comment by beil24** [comment]
Same error to me

**Comment by Rotehut** [comment]
me too

**Comment by kenorb** [comment]
Related:
- https://github.com/keybase/client/issues/15257#issuecomment-531395333
- #19515
- #19531
- #19548
- #19572
- #19600
- #19607
- #19642
- #19643
- #19644
- #19646
- #19647

**Comment by elvirafitriani** [comment]
Me too

**Comment by radencrypto** [comment]
Scam. Taidrop

**Comment by eetot** [comment]
same problem.Scam.

**Comment by kenorb** [comment]
Solved: #19718
