### ISSUE TITLE
showing errror' like oops  wehad a provlem communicating with our service.this might  be lost of connectivty'

### ISSUE THREAD

**Issue by sanketh11** [keybase/client#19652]
Keybase GUI Version: 2.6.2-20180920140058+0f17a92adc

please tell the solution  and also i dont  have commond line option

**Comment by Manhkk1st** [comment]
Tôi không thể join airdrop

**Comment by sanketh11** [comment]
already i have mobile app /. now iam trying to open in windows32bit version it not loading  showing this kind of eror

**Comment by sanketh11** [comment]
already i have mobile app /. now iam trying to open in windows32bit version it not loading  showing this kind of eror

> Tôi không thể join airdrop

already i have mobile app /. now iam trying to open in windows32bit version it not loading  showing this kind of eror

**Comment by Manhkk1st** [comment]
do i get an airdrop reward ???

Vào 22:04, CN, 17 thg 11, 2019 Maxwell Krohn <notifications@github.com> đã
viết:
