### ISSUE TITLE
Error To Join Airdrop

### ISSUE THREAD

**Issue by Bian6989** [keybase/client#19666]
Dear Keybase

Why can't I join the stellar airdrop? even though I have qualified to join, please be told what my mistake is, because I see a Bug on the registration page. My Github account is correct, I've made 3 Paper keys, I'm very disappointed and sad if it's like this. I hope that there will be improvements and I will be welcome again at this Airdrop Event. thank you

**Comment by Crypt05haman** [comment]
Me too, having problems to register for airdrop

**Comment by roccoida** [comment]
Stellar sent to my kraken wallet. Two days ago. Nothing received. 
Forget about you.

**Comment by Rotehut** [comment]
I think "Stellar Founding Member" maybe siphon tokens to his and her wallets. So they make a bug for a lot of adopters and waste your time.

**Comment by Bian6989** [comment]
Oh if they only gave pretend airdrops, I wouldn't use Keybase anymore, they were unprofessional then. very disappointing for beginners like me.

**Comment by kenorb** [comment]
Clarify on errors guys, what errors do you get?

**Comment by roccoida** [comment]
I didn’t have transfer on my external stellar account from Keybase. Simply.

**Comment by Bian6989** [comment]
Kenob, yes, yesterday I was approved to receive, even got a stellar badge pin on my profile, but this morning when I opened my keybase account through the application it disappeared, and I was expelled from the airdrop event, without notification what my mistake was, this is unfair isn't it? when I want to join the list again instead An Error, what is it that makes me confused? or am I no longer allowed to participate in this event?

**Comment by Bian6989** [comment]
The application is very bad full of fraud, the Admin can not detect where the user is honest, where is the cheater? I think you are cheating on holding an Airdrop but all your people are banned without notice and explain what they are doing wrong, that is where your unprofessionality makes people leave Keybase faster! if you can't honest, don't hold an Airdrop Event !!! very stupid and bad

**Comment by roccoida** [comment]
It’s only scam.

**Comment by Bian6989** [comment]
Yes, I agree..
they just want to attract people to use the keybase application, but they don't intend to share Airdrop Stellar, I think this is just a marketing trick or trick so that many interested people use the keybase application, so many people are disappointed at being blocked from following the airdrop without cause and reason. it shows they have cheated, and it is not fair to interested ones, if they are sophisticated smart, why can't they differentiate between honest users who have 1 keybase account, those who have many keybase accounts to chase the airdrop instead they are not banned, those banned as I play honest and have 1 account, I'm also a beginner who is disappointed in the ignorance of the management of the Airbase keybase developer section airdrop.

**Comment by kenorb** [comment]
Related:
- https://github.com/keybase/client/issues/15257#issuecomment-531395333
- #19515
- #19531
- #19548
- #19572
- #19600
- #19607
- #19642
- #19643
- #19644
- #19646
- #19647

**Comment by roccoida** [comment]
No way to obtain any response.
It’s a real, big SCAM.

**Comment by roccoida** [comment]
No support, no response, nothing. Only SCAM.

**Comment by bitcoinoplomo** [comment]
Easy on the useless pointing finger. 
That doesn't help at all on the ones that are really trying to solve the problem.

**Comment by roccoida** [comment]
What’s your problem, @bitcoinoplomo? Can you read old posts? Well, just do it.

**Comment by kenorb** [comment]
> It’s only scam.

Maybe they think your account is fake, as your account is almost not used. Just saying. Not sure what's their criteria of detecting "bots". Whatever they are, they should change it.

**Comment by kenorb** [comment]
Maybe they should add some kind of captcha proving humans?

**Comment by bitcoinoplomo** [comment]
I am also trying to figure what happen.
I know a few people that are in my contact list that still have the badge and have no problem at all.
My github account is very active. 
I don't know what happen to have this error. But I want to know.

**Comment by eetot** [comment]
No support, no response, nothing. Only SCAM.

**Comment by eetot-z** [comment]
Is it not possible to join the airdrop as long as the conditions are met?Why should Github be used?

**Comment by Bian6989** [comment]
Never mind sir, you do not have to defend Keybase !!! THEY ARE NOT PROFESSIONAL AND NOT FAIR TO BEGINNERS! I LOOK AT MYSELF A LOT WHO HAVE PASSED THEIR AIRDROPS THOSE CHEAT 1 PARTICIPANTS HAVE MANY HANDPHONES TO PURCHASE AIRDROP !! IF I DON'T GET THE AIRDROP ALSO THE ISSUE, BUT I JUST WANT TO EXPLAIN FROM THE KEYBASE PARTIES, WHERE DO I BLOCK MY ERROR? THEN I WILL CORRECT AND RETURN IN FOLLOWING THIS EVENT !! THEY'RE ALL FRAUDS!

**Comment by Bian6989** [comment]
I JUST NEED A CLARIFICATION OF THE "KEYBASE.IO" DEVELOPER TEAM WHY I WAS BLOCKED, THAT'S IT !!!!! THEY SHOULD LIKE THE LIVING UNCOMFORTABLE! BASIC FRAUD!

**Comment by kenorb** [comment]
Checkout: https://twitter.com/malgorithms/status/1173785764544569345 and public announcement at https://keybase.io/airdrop

**Comment by Bian6989** [comment]
I dont care for about it! They are not fair and stupid!

**Comment by mK7768** [comment]
### Keybase proof

I hereby claim:

  * I am mk7768 on github.
  * I am mrkl (https://keybase.io/mrkl) on keybase.
  * I have a public key ASAgcBFZIjDgEujardzidJPJwQhOCCYL7jTwYcglShpyTQo

To claim this, I am signing this object:

```json
{
  "body": {
    "key": {
      "eldest_kid": "0120207011592230e012e8daaddce27493c9c1084e08260bee34f061c8254a1a724d0a",
      "host": "keybase.io",
      "kid": "0120207011592230e012e8daaddce27493c9c1084e08260bee34f061c8254a1a724d0a",
      "uid": "bb907a91f581bcb47b7a4b7da2306419",
      "username": "mrkl"
    },
    "merkle_root": {
      "ctime": 1568746936,
      "hash": "bc245613139e51bb05235651b5852841568b0affd07d92cee75969fe6f6a822cf32f406c1bed90fd9085f1c9a1218b475fd1a5cb7bbda5e0480c3e4c53a4ef88",
      "hash_meta": "e4370cd1588208a15e79a431b580a616e13c34322c50cef83e4ed9c84bb25f72",
      "seqno": 7531757
    },
    "service": {
      "entropy": "2hurqIktBQtMGFBXfAyIbVFL",
      "name": "github",
      "username": "mk7768"
    },
    "type": "web_service_binding",
    "version": 2
  },
  "client": {
    "name": "keybase.io go client",
    "version": "4.4.2"
  },
  "ctime": 1568746950,
  "expire_in": 504576000,
  "prev": "3490b034d7d9d3288efb4fb6ef807bf1ce9b745fedd7200f8ff535995055b47c",
  "seqno": 21,
  "tag": "signature"
}
```

with the key [ASAgcBFZIjDgEujardzidJPJwQhOCCYL7jTwYcglShpyTQo](https://keybase.io/mrkl), yielding the signature:

```
hKRib2R5hqhkZXRhY2hlZMOpaGFzaF90eXBlCqNrZXnEIwEgIHARWSIw4BLo2q3c4nSTycEITggmC+408GHIJUoack0Kp3BheWxvYWTESpcCFcQgNJCwNNfZ0yiO+0+274B78c6bdF/t1yAPj/U1mVBVtHzEIJ1q6hfEBcohSAi9Ii8MrPk0W7S53abU90uvLof7+DoJAgHCo3NpZ8RAtJb+l9qFckwRE66OUoCrNg1QXLwrZlmwDBRJot3Zb/dFKuCVK/szdq/qLigM4p1M9rMwSx2xUXYm5LKxSnMkBqhzaWdfdHlwZSCkaGFzaIKkdHlwZQildmFsdWXEIAN1MRpnFYt6RzH8EotjZWJYkb2hs7FJrVza0m7jobdfo3RhZ80CAqd2ZXJzaW9uAQ==

```

And finally, I am proving ownership of the github account by posting this as a gist.

### My publicly-auditable identity:

https://keybase.io/mrkl

### From the command line:

Consider the [keybase command line program](https://keybase.io/download).

```bash
# look me up
keybase id mrkl
```

**Comment by mK7768** [comment]
6Pk5WayRBzEPtpe9YgQAgf4N9JVeJMyFC3

**Comment by ACGeek** [comment]
> Checkout: https://twitter.com/malgorithms/status/1173785764544569345 and public announcement at https://keybase.io/airdrop

I registered before September 9th and should qualify based on all listed requirements, but still fail.
