### ISSUE TITLE
Report error

### ISSUE THREAD

**Issue by Nandaokta** [keybase/client#19667]
When I click the airdrop banner in the application, an error appears

**Comment by LUIGINO666** [comment]
https://keybase.io/luigino666

**Comment by kenorb** [comment]
> When I click the airdrop banner in the application, an error appears

Post the screenshot and send the logs.

**Comment by LUIGINO666** [comment]
Trimis din Yahoo Mail pe Android 
 
  Pe dum., sept. 15, 2019 la 15:11, Rafal W.<notifications@github.com> a scris:   

When I click the airdrop banner in the application, an error appears


Post the screenshot and send the logs.

**Comment by Nandaokta** [comment]
hi admin I think this is unfair, why can't I register airdrop, my
requirements are complete, and I am not cheating, right yesterday I was
confused when connecting my github account to my keybase, but now it's
correct check again, don't decide unilaterally we are not cheating  feel
disadvantaged over time, and my energy to inform people, that you have a
good project, but the behavior of dev, less professional.because a project
will be big if many people support and use it, sorry if my words are a bit
harsh, but with me criticizing your application, hopefully in the future
this project is better,

my account :
@nanda00

Pada tanggal Min, 15 Sep 2019 19.11, Rafal W. <notifications@github.com>
menulis:
