### ISSUE TITLE
Login Failure

### ISSUE THREAD

**Issue by deanland** [keybase/client#19678]
login failure -- username not recognized, then goes gray, same for forgot password.
 Then comes error message with a number, but it disappeared.

my log id: 4e020402b58412f6076c2d1c

**Comment by kenorb** [comment]
Yep, it seems Keybase is removing a lot of accounts for unknown reasons.

Related:
- #18808
- #19107
- #19655
- #19677
- #19670
- #16889

**Comment by deanland** [comment]
Thanks, kenorb.

**Comment by kenorb** [comment]
See: https://twitter.com/malgorithms/status/1173785764544569345

> And just had to turn off new GitHub Space Drop registrations also, due to bad actors. Even after all these years, the Internet can find a way to let ya down. http://keybase.io/airdrop
