### ISSUE TITLE
Error to join Airdrop

### ISSUE THREAD

**Issue by dvid** [keybase/client#19684]
Hi, Admin. I was a lucky airdropee, until I wanted to put my GitHub account on my real name Keybase account. So I did, since I cannot participate anymore. I get an error joining the airdrop, even with my GitHub account connected. I didn't cheat or even try to. I already uploaded the logs.

**Comment by kenorb** [comment]
My guess you probably are blacklisted from the server for unknown reason as many people got the same server error.

Related:
- https://github.com/keybase/client/issues/15257#issuecomment-531395333
- #19515
- #19531
- #19548
- #19572
- #19600
- #19607
- #19642
- #19643
- #19644
- #19646
- #19647 
- #19684

**Comment by kenorb** [comment]
Solved: #19718
