### ISSUE TITLE
Airdrop 505 DB Error

### ISSUE THREAD

**Issue by denisdikanov** [keybase/client#19688]
Hello. I was a "lucky airdropee", but 3 days ago my status was changing and I got an 505 error "Error: ERROR CODE 505 - DB error in method stellar.1.local.airdropRegisterLocal at new s ". Why? And How I can contact to support team?

**Comment by kenorb** [comment]
Related:
- https://github.com/keybase/client/issues/15257#issuecomment-531395333
- #19515
- #19531
- #19548
- #19572
- #19600
- #19607
- #19642
- #19643
- #19644
- #19646
- #19647 
- #19669
