### ISSUE TITLE
duplicate folders in /keybase/private

### ISSUE THREAD

**Issue by dhgwilliam** [keybase/client#1968]
I believe the "first" one was created when I navigated to /keybase/public/dhgwilliam (favorited?) and the second one was created when I navigated to /keybase/private/dhgwilliam

```
drwx------ 1 root root 4 Feb  9 22:55 dhgwilliam
drwx------ 1 root root 4 Feb  9 22:55 dhgwilliam
```

my log id: 8b9db94b5fa3fdaecceb481c

**Comment by strib** [comment]
Thanks for the report.  This is a known problem with today's build, that should be fixed in tomorrow's build.  Can you please take tomorrow's update and let us know if the problem is fixed?

**Comment by cjb** [comment]
I think the new build should be available now.

**Comment by dhgwilliam** [comment]
What's the preferred upgrade mechanism? I'm `curl`ing the package from the S3 url but it's not clear to me that it's a different build from yesterday.

**Comment by cjb** [comment]
OS X: Run `keybase update check`

Linux: `sudo apt-get update && sudo apt-get upgrade keybase && run_keybase`

**Comment by dhgwilliam** [comment]
works for me
