### ISSUE TITLE
My Status Airdrop not join there Error Bugs

### ISSUE THREAD

**Issue by krisdiansyah09** [keybase/client#19700]
Why My Accounts become not join Airdrop? before I have joined Airdrop and complete All qualify, But now status my Accounts not join Airdrop.

**Comment by kenorb** [comment]
See: https://twitter.com/malgorithms/status/1173785764544569345

> And just had to turn off new GitHub Space Drop registrations also, due to bad actors. Even after all these years, the Internet can find a way to let ya down. http://keybase.io/airdrop
