### ISSUE TITLE
leejaycantA

### ISSUE THREAD

**Issue by leejaycantA** [keybase/client#19716]
probs with  =  github identity proof of @leejaycanta never succeeded. We've been checking it repeatedly, and from our perspective, it's either (a) not there, or (b) not posted precisely.

how

why...

The Hacker News Daily Updates | The Hacker News Daily Updates
-- | --
The Hacker News Daily Updates
.

![Screenshot 2019-09-17 08 17 53](https://user-images.githubusercontent.com/54041096/65025197-2856a200-d92e-11e9-9a3d-adc4ae39744d.png)

.

![Screenshot 2019-09-17 09 33 41](https://user-images.githubusercontent.com/54041096/65025292-5d62f480-d92e-11e9-91ba-eda129ca5672.png)

.

how to get air drop

leejaycant@yahoo.co.uk

or

leejaycant@gmail.com

thanks

lee

**Comment by kenorb** [comment]
See: https://twitter.com/malgorithms/status/1173785764544569345

> And just had to turn off new GitHub Space Drop registrations also, due to bad actors. Even after all these years, the Internet can find a way to let ya down. http://keybase.io/airdrop

**Comment by leejaycantA** [comment]
big   Thank you Rafal to Awake to see frauds, + hunt the criminals + audit
to Correct codes etc....
lee

xxx
Rafal W. <notifications@github.com>
