### ISSUE TITLE
eror

### ISSUE THREAD

**Issue by rufy12** [keybase/client#19715]
Hello, good afternoon
Why does my account suddenly have a GitHub account in abuse
even though I only use 1 personal account
and I have also been approved at Github for a long time since 2018
please check this error again
thank you
regards

Keybase GUI Version: 4.4.2-20190912155038+4931602c61

**Comment by rufy12** [comment]
when joining for airdrop status i was connected and now it's not connected

**Comment by kenorb** [comment]
Can you post the screenshot?

**Comment by kenorb** [comment]
See: https://twitter.com/malgorithms/status/1173785764544569345

> And just had to turn off new GitHub Space Drop registrations also, due to bad actors. Even after all these years, the Internet can find a way to let ya down. http://keybase.io/airdrop

**Comment by rufy12** [comment]
> Bisakah Anda memposting tangkapan layar?

![image](https://user-images.githubusercontent.com/40128738/65104409-8bfad100-d9fb-11e9-8e05-fa88b3806095.png)

**Comment by rufy12** [comment]
![image](https://user-images.githubusercontent.com/40128738/65104497-c7959b00-d9fb-11e9-840b-17d2ff65bc52.png)
