### ISSUE TITLE
is it a bug or not 

### ISSUE THREAD

**Issue by markace1** [keybase/client#19727]
I just wondering why my account like this. my 1st screenshot is the one that i qualified the airdrop then now not qualified.. hmmmm
![Screenshot_20190917_232747_com android chrome](https://user-images.githubusercontent.com/33613150/65056800-1f081c80-d9a4-11e9-92ca-8e06258f2ff4.jpg)

![Screenshot_20190911_114638_com android chrome](https://user-images.githubusercontent.com/33613150/65056827-2deecf00-d9a4-11e9-9c3e-6d7ca826864c.jpg)

**Comment by kenorb** [comment]
The rules changed yesterday, see: https://keybase.io/airdrop

**Comment by markace1** [comment]
@kenrob how to be qualified?

**Comment by markace1** [comment]
how to fixed that hmmm 🤔

**Comment by kenorb** [comment]
> how to fixed that hmmm 🤔

It's no longer bug, it's a feature.

**Comment by markace1** [comment]
https://github.com/keybase/client/issues/19727#issuecomment-532308439

Any option to approve in the airdrop i registered sept 10
