### ISSUE TITLE
/keybase/public/samlanning/signal.txt has an archived block

### ISSUE THREAD

**Issue by strib** [keybase/client#1973]
Hi @samlanning, we noticed one of the files in your public directories isn't readable by other users.  The issue seems to be that one of the underlying blocks of the file is "archived", which means your client told us the block is no longer a part of the current folder, even though it is.  This is likely a bug in the keybase client.

Would you be willing to do a `keybase log send` on whatever device wrote that signal.txt file, and let us know the resulting log ID, so we can debug what happened?  Thanks!

**Comment by samlanning** [comment]
Sure, here it is: 7384386f09c0d6817629e01c

For a bit of extra context, i was speaking a little bit with @malgorithms regarding this issue. Previously none of my files were being displayed at all on `keybase.pub`, and neither was the directory listing, since yesterday 2 of the 3 files are readable from `keybase.pub`, and the directory listing is available.

**Comment by strib** [comment]
Thanks!  I'll check it out as soon as I can.

**Comment by strib** [comment]
Ok, this seems to be a server issue actually -- it's marking a block as historical even though the client hasn't said it should be.  We're looking into it.  If possible, I'd like to keep this file in this broken state for now while we investigate, but if that's a problem let me know.

**Comment by samlanning** [comment]
Alright sure, I'll leave it as is for now! =)

**Comment by strib** [comment]
We have updated our servers with a change that we think will fix this race condition in the future.  However, it doesn't work retroactively, so you'll need to overwrite that file with a new version.  When you do, let me know and I'll confirm I can read it.  (That won't guarantee the bug is gone, since it's a race, but at least we can close this issue).

Also, you can check the file on keybase.pub to see if it's readable by others.

**Comment by samlanning** [comment]
I have updated the file (added some stuff at the top to ensure all blocks change), but unable to check if it's working as keybase.pub seems down.

It's returning a `503`:

```
> GET / HTTP/1.1
> Host: keybase.pub
> User-Agent: curl/7.46.0
> Accept: */*
> 
< HTTP/1.1 503 Service Unavailable: Back-end server is at capacity
< Content-Length: 0
```

**Comment by cjb** [comment]
Sorry about that, keybase.pub is back up now.

**Comment by samlanning** [comment]
Alright, all seems to be working. =)

**Comment by strib** [comment]
Great!
