### ISSUE TITLE
Airdrop Error

### ISSUE THREAD

**Issue by dsmh** [keybase/client#19747]
I fulfill all the requirements for the airdrop, however, when I tried to apply, I did not have the backup devices. Now that I have them I'm not able to find the apply button again. How can I access to the airdrop check again?

**Comment by beyeu1** [comment]
Hịi

**Comment by beyeu1** [comment]
Hello anh

**Comment by ubiqland** [comment]
https://keybase.io/a/i/r/d/r/o/p/spacedrop2019
