### ISSUE TITLE
For airdrop problem

### ISSUE THREAD

**Issue by ihavemage** [keybase/client#19751]
I just want to convey my thoughts to solve this problem...

Keybase just need to add the kyc system to their airdrop. it is to see the original register and not

**Comment by Harrymon12** [comment]
Why am I not qualified?
I am qualified last time.
My github account is qualified for "You have an old enough Keybase account."

**Comment by kenorb** [comment]
> Why am I not qualified?
> I am qualified last time.
> My github account is qualified for "You have an old enough Keybase account."

The airdrop rules changed.

See: https://twitter.com/malgorithms/status/1173785764544569345 and the public announcement at https://keybase.io/airdrop.

**Comment by Harrymon12** [comment]
Does it mean all github user will be blocked?Including me?All github and hackernews would be banned?Would they just check the account if legit?Like checking connected accounts that are old enough and legit?
Sent from Yahoo Mail on Android 
 
  On Wed, 18 Sep 2019 at 6:41 PM, Rafal W.<notifications@github.com> wrote:   

Why am I not qualified?
I am qualified last time.
My github account is qualified for "You have an old enough Keybase account."


The airdrop rules changed.

See: https://twitter.com/malgorithms/status/1173785764544569345 and the public announcement at https://keybase.io/airdrop.
