### ISSUE TITLE
Created second account and no longer in airdrop?

### ISSUE THREAD

**Issue by nicholasmartin** [keybase/client#19752]
Did I just get removed from Airdrop? My account "A" was all set up and approved for the airdrop. Then I wanted to create a team but realized I couldn't use "A" for name as I had used that for my account. So I wanted to change my account name but learned that I couldn't. I did not want to delete my account because it was already setup for airdrop, so instead, I created a new account "B" and approved that with my same phone number. 

I did this just to secure my personal name as an account name. Now when I log back into my "A" account I don't see any mention of an airdrop. Did I mess something up?

**Comment by kenorb** [comment]
You won't be able to join airdrop from the second newly created account as the rules changed.

See: https://twitter.com/malgorithms/status/1173785764544569345 and the public announcement at https://keybase.io/airdrop:

**Comment by nicholasmartin** [comment]
That's totally cool, I'm just worried that my original account has been taken out of the Airdrop, as I don't see any mention about it in there. I'm sure I had a "you are eligible for airdrop" notice in there somewhere...
