### ISSUE TITLE
Got kicked out of Keybase airdrop

### ISSUE THREAD

**Issue by cdittmann** [keybase/client#19756]
I think the people of Keybase should be more careful. They launch an airdrop campaign and then stop it after a while. I understand there are some ill-disposed actors trying to take advantage of this. I understand they need to pause it to study and take the necessary measures, but come on, stop the registering process after the news update but don't remove user who already legitimately qualified for the airdrop. They are stepping on a thin line between protecting the security of the operation and losing the loyalty of potential new users to the product and the brand itself.

**Comment by kenorb** [comment]
> don't remove user who already legitimately qualified for the airdrop

How do you know if somebody is legitimately qualified for the airdrop, and not using somebody's else stolen account instead?

**Comment by HououinKyouma01** [comment]
Dunno. You tell me. It wasn't OP's or my idea to do an airdrop. Also, if someone's got his account hacked, then it's only his fault. Using same passwords everywhere is resulting in something like this. Why would you care about it and "punish" people that legitimately signed for this airdrop?
