### ISSUE TITLE
Please do not punish users following the airdrop rules.

### ISSUE THREAD

**Issue by jackylimel** [keybase/client#19753]
It's ridiculous to announce the airdrop and then turn it off. The new users didn't do anything wrong as they are following the rules: create an account and then link the account to an old github account. 

People who followed the rules should not be published. 

You could say "we are not airdropping to new users who registered after this tweet (or announcement)", but you cannot just cancel the whole thing as people have spent time to participate.

**Comment by kenorb** [comment]
> The new users didn't do anything wrong as they are following the rules: create an account and then link the account to an old github account.

There are people who created thousands of fake accounts per day and ticked all the boxes, so how 'the new users didn't do anything wrong'?

**Comment by jackylimel** [comment]
> > The new users didn't do anything wrong as they are following the rules: create an account and then link the account to an old github account.
> 
> There are people who created thousands of fake accounts per day and ticked all the boxes, so how 'the new users didn't do anything wrong'?

Did you mention in the original post that one person can only create one account per day? If not, why are you saying they are wrong?

Even if they are wrong, there are still normal users who registered after the 1st announcement to participate in the airdrop, why are they all punished?

**Comment by 09Bryan09** [comment]
I have only one account.But unfortunately,it suddenly it included after the announcement.Lets say some made multiple account, the how about us..hope they will trace them  by checking  ip address.not a techy her.but i think its one of possible way to trace them.

**Comment by sajjad0084** [comment]
my account is origanal but some made multiple accounts for airdrop ..you do not punish all users for this reason you solave this problum with kyc proses or phone number veryifcation

**Comment by NelsonJr2016** [comment]
I believe in Stellar, I can verify my account is legitimate by connecting it to my tweeter, facebook..etc..I'm hoping they would give legitimate users chance for the airdrop. Just add more controls to determine the legitimacy of the account.

**Comment by kenorb** [comment]
> I have only one account.But unfortunately,it suddenly not included after the announcement.Lets say some made multiple account, the how about us..hope they will trace them by checking ip address.not a techy her.but i think its one of possible way to trace them.

Using VPN and Tor networks, you can have random IP each time.

**Comment by kenorb** [comment]
> Did you mention in the original post that one person can only create one account per day? If not, why are you saying they are wrong?

There are huge databases of GitHub accounts on the darknet, all you had to do is to create Keybase account for each, a simple shell script. So hackers can easily create thousands of Keybase accounts per hour, no big deal.

I think the challenge is to distinguish real user from hacked one.
