### ISSUE TITLE
An Idea for XLM Airdrop: Just give another condition to be qualified, such as holding XLM (50 or 100)

### ISSUE THREAD

**Issue by RiandArmata** [keybase/client#19757]
As a legit GitHub user registered before Sept 9 (used it for KuCoinPlay connected account), it shocked me much that Keybase decided to cancel one condition to get approvement for XLM airdrop.

I suggest, leave the condition like before. But ADD another condition to prevent fake accounts, or at least to make them hard to get the airdrop.

One idea is, to get the airdrop an account should have XLM on distribution date, such as 50 or 100 XLM.

Legit single users wouldn't mind to make the XLM available on their account. But for those who have multiple accounts, such as hackers with hundreds or maybe thousands 
account, it will be harder. Not only they should have many XLM for each account deposit, they should do it manually too. Because if many accounts got the XLM from single address, it means, the addresses are from one person and this person have multiple accounts.

Maybe there are another better idea. But at least, don't cut off the legit users' right to get XLM airdrop.

Thanks for your concern, Keybase Elites!

**Comment by kenorb** [comment]
How can you prevent fake accounts? What's you idea?

**Comment by DYevseyev** [comment]
Do KYC 
rofl

**Comment by Girlfriend1990** [comment]
Please . Delete My Account From Keybase. Not participating in an airdrop with only 1 Github account Created before 9/9, Each day must receive nearly 100 mail from Keybase / github sent to. It was annoying and tiring.

**Comment by RiandArmata** [comment]
Fake accounts can't be prevented 100%, my idea mostly to reduce the activity of those who hack/steal accounts to own many. Because it's impossible they did that for only to create one or two 'fake' accounts.

KYC is good, but with Keybase's time frame, i think it's hard to do that. They should check within 1 month, not only once, because someone who got rejected can be re-apply.

And after what we see on blockchain.com XLM airdrop, that was one bad example of doing KYC. Many legit users who already waited for a year, got nothing in the end. And blockchain.com become unpopular. I got one after months, but i don't really like to use their service. I don't use it now.

KYC is good, only if Keybase capable to handle it properly and fast. We don't want to hear someone complaints, 'why do my KYC haven't been approved for months'.

If Keybase want to be one of Stellar-base main wallet, follow the example of LOBSTR. They did XLM airdrop long before, successful without KYC, and now they have grown to be one of the best Stellar wallet-exchanges. They have loyal users.

**Comment by DYevseyev** [comment]
I don't care for KYC. I do not want to send my documents to anyone.
It's nice that they offer a wallet, but most people prefer to run their own full nodes.
If they really want to enter the crypto currency arena, they should offer Lightning Network and more mainstream coins.

Keybase is an amazing platform for securing your online communication, maybe it would be best to just forget about becoming a jack of all trades and stick to their roots. 
If it helps to fund Keybase development then I don't mind the crypto currency addon features as long as functionality of the app stays true to its core.
Keybase promised a voip solution back in 2017. It would be nice to collect on that promise by 2020 :)

**Comment by RiandArmata** [comment]
I believe they choose Stellar for future consideration, for payment method between members, not really for jumping onto crypto arena.

Why Stellar? not other 'mainstream' coins? because Stellar is hell fast and cheap, the fastest, transaction done within seconds, and the cheapest, as almost no fees at all, comparing to the others.

Of course, Stellar helps Keybase development with notes, to spread, strengthen and add XLM users.

**Comment by ivan-avalos** [comment]
> Do KYC
> rofl

No, please don't do KYC!
