### ISSUE TITLE
Legitimately Registered Through GitHub, But Have Been Removed

### ISSUE THREAD

**Issue by joshuathemessenger** [keybase/client#19760]
What's the deal Keybase? I followed your rules, and I have been on GitHub long enough. Are you going to fix this, and re-include people that are legit? I am a huge fan of Stellar, and I like your platform, but this is needs to be fixed please. -UPDATE- Try checking out https://keybase.io/a/i/r/d/r/o/p/spacedrop2019 It returned the UID reference at the bottom of the page as registered, might be an indicator.

**Comment by DYevseyev** [comment]
Stellar is a shitcoin. I am just glad it shined light on this amazing app.
I was looking for something like this for years! I got kicked out of airdrop as well but I don't care.

**Comment by jbvla** [comment]
I disagree with your opinion on the coin, but the app is rather nice. IBM & Franklin Templeton seem to like it, as well. I certainly hope they work this out better than they have so far.

**Comment by bigdcrypto** [comment]
Same

**Comment by skadycygnus** [comment]
I registered on September 10th and I even informed friends about keybase and that with a Github account they still can take part at the airdrop!
If that is the final word, than Keybase' and Stellar's reputation will be irreparable damaged.

**Trustworthiness is everything, especially in finance and data-security**

**How can I  trust a company that isn't even capable to filter out scammers, that they'll be able to protect my important data?** 

The upswing in Stallar (re)gained me more than $500 in the last 24h.. I'm not just here for those lousy airdrop. But this business conduct isn't acceptable.

**Comment by nguyenvannghiatran** [comment]
Same here.  Its ridiculous! Is it so hard to filter scammers? I think People who have github accounts can protect their data...

**Comment by jbvla** [comment]
Hey everyone. So I was digging in, and I think it's just new registration, at least I'm hoping so. I went to https://keybase.io/a/i/r/d/r/o/p/spacedrop2019 and it showed my user as still registered for the drops. Might want to check it, and see what it returns. It'll show on the bottom of the page, where it uses the UID to address the reader.
