### ISSUE TITLE
Had to reset my account, now locked out of Spacedrop chat

### ISSUE THREAD

**Issue by chiefmonky** [keybase/client#19788]
Error message: "Since you reset your account, participants have to accept to let you back in."

Please accept me?... I'm a nice person really ;o)

**Comment by robc430** [comment]
I am also having this issue..... please re-add me.

**Comment by MattXcz** [comment]
yes.... same here

**Comment by MattXcz** [comment]
Is there some other way to be part od SpaceDrop ? @strib
