### ISSUE TITLE
Please Delete account me  . please ! ! ! 

### ISSUE THREAD

**Issue by Girlfriend1990** [keybase/client#19790]
Please delete my affiliate account. more than 100 messages a day. So annoying. It was too wrong when I joined this airdrop. The place where spam spam perfect.
![Screenshot_2019-09-19-20-20-37-336_com google android gm](https://user-images.githubusercontent.com/54014968/65248449-61ed0000-db1c-11e9-8fe7-97366d3e1a96.png)

**Comment by maxtaco** [comment]
GitHub is sending you these messages. Change your preferences on GitHub.
