### ISSUE TITLE
Cant join to the airdrop

### ISSUE THREAD

**Issue by twisterdw** [keybase/client#19819]
Hi there.i am new user.i have registred yesterday but i cant join to the airdrop.i dont know what is a problem because i have an old medium account.app does not show me the airdrop joining button on the mobile device or windows pc.can you help me with that?thanks

**Comment by Rohan-Bansal** [comment]
If you go to keybase.io/airdrop, they comment on this issue.

**Comment by twisterdw** [comment]
Cant find it on this page

**Comment by Rohan-Bansal** [comment]
It is the highlighted paragraph. I just checked, and the page should work, for both users and non-users.
