### ISSUE TITLE
deleted issue

### ISSUE THREAD

**Issue by coofercat** [keybase/client#19818]
deleted issue

**Comment by coofercat** [comment]
Still the same - which effectively means my keybase account is now dead - I can't use it and I can't reset it or recover it.

I'm guessing this isn't a server issue per-se, although I see there has been some server abuse going on trying to get to peoples Lumens - is that the cause?

**Comment by vuetokill** [comment]
Basically every time I scan the QR code the android app just hangs or it comes back with an error message in capitals like - STREAM_ERR.... but never come back with BAD SESSION from what I've viewed. I've tried typing the Pass Phrase instead and that just comes back with a different error. There just seems to be no way to recover at the present time.

**Comment by vuetokill** [comment]
One of the error messages I have received from the Windows application:
**There was an error provisioning**
msgpack decode error [pos 0]: operation timed out Error code 218: GENERIC in method keybase.1.login.login

**Comment by vuetokill** [comment]
Got that stream error message:
Error code 1504: STREAM_EOF in method keybase.1.login.login

**Comment by coofercat** [comment]
Looks like this is same/similar to #19107 and #18808 - both say:

> kenorb commented 9 days ago
> Solved: #19718

...but apart from someone saying they've turned off Airdrop and whatnot, there doesn't seem to be any steps to resolve.

**Comment by kenorb** [comment]
> In my Mac client (Version 4.5.0-20190919040131+93e889ab01 (4.5.0-20190919040131+93e889ab01)), pretty much every page says "We're having a hard time loading that page" and the additional details say `Error 202 - server rejected session; is your device revoked? in method keybase.1.home.homeGetScreen`
> 
> Online, if I enter my username and password, it says `Unknown error: BAD_SESSION / Failure in verify PDPKA5`. If I enter my email and password, it seems to accept it and sends me off to my profile page, but I can't see any evidence I've actually logged into anything.
> 
> 
> Anyone else got this problem? Is there something wrong with my devices, or is there a server issue going on?

It's the issue with your account, which is probably blocked. If you're still logged in, you can try to recover the account.

Try sending the logs via `keybase log send`. Otherwise, I don't know if it's possible to recover your account, you need to contact the support.

**Comment by coofercat** [comment]
I think I already did send logs, but just did it again:
```
Success! Your log ID is:

  7aa68ac2d5d1eaec82003d1c
```
I'm not logged out, but I can't use the app on either device, so I don't see a way to recover my account.

How do I contact support? I can't use Keybase to chat to them :-( Do they look at these issues (or can someone ping them the link to this one?)

**Comment by kenorb** [comment]
@coofercat What's your Keybase account again?

**Comment by coofercat** [comment]
my keybase username is `coofercat` :-)

**Comment by maxtaco** [comment]
@coofercat try it now?

**Comment by coofercat** [comment]
Awesome! It's working again - thank you so much!

What was the problem? Is it something I did, or could have resolved myself (or resolved via some other means of contact)?

**Comment by coofercat** [comment]
Ah... I can see messages from you and other people, but I can't send any back. It just says:

`This message has failed to send. Cancel or Retry`

**Comment by maxtaco** [comment]
hmm ok....  let me think....

**Comment by maxtaco** [comment]
try to log out and log in? make sure you know your password first.

**Comment by coofercat** [comment]
Sorry - still not working :-(

(UI is pretty nice there by checking you know your password!)
