### ISSUE TITLE
Got kicked out of Keybase airdrop !

### ISSUE THREAD

**Issue by letsgo3979** [keybase/client#19831]
Dear keybase !
I had join airdrop ok . But i dont know why . I Got kicked out of Keybase airdrop . Please , help me. Thank you very much .
![AAFC7116-49E8-4B56-A76E-475E865D7C8F](https://user-images.githubusercontent.com/35184983/65366845-9a432a00-dc53-11e9-94a0-cee2d0140358.jpeg)
![740E6C79-0625-4232-85CC-6E6C9220C7C7](https://user-images.githubusercontent.com/35184983/65366846-a4fdbf00-dc53-11e9-9e0d-1042b4b1a61d.jpeg)

**Comment by samscalet** [comment]
The airdrop just lie. The story of hackernews github hacked was old they use that reason to stop airdrop

**Comment by HououinKyouma01** [comment]
Yeah. Me too. That's just laughable. I bet that no "hack" occurred or anything. Just come on.
