### ISSUE TITLE
Folder permissions lost

### ISSUE THREAD

**Issue by gvnmccld** [keybase/client#1984]
I don't believe I changed anything, the other day I could write to my public/private and a shared folder with a friend, now all 3 I get permission denied.

my log id: c0835a50cc802593d3a4e71c

**Comment by strib** [comment]
The server thinks that your session token has expired.  This is a known bug in the version you're running.  It should be fixed now -- can you update Keybase and try again please?

**Comment by gvnmccld** [comment]
I'm on version: 1.0.11-20160211170011+0b33bc6 now (just prompted me to update a minute ago)

Updated on one machine, it can see public folders but nothing in private.  Other machine (can't see public/private) fails to update with this error:

 ERROR symlink Versions/Current/Electron Framework /var/folders/v8/ytsxty651x35b7nsn48gfyk40000gn/T/KeybaseUpdates/Keybase-1.0.11-20160211170011+0b33bc6.zip.unzipped/Keybase.app/Contents/Frameworks/Electron Framework.framework/Electron Framework: file exists

**Comment by maxtaco** [comment]
cc: @gabriel ^

**Comment by strib** [comment]
@gvnmccld: can you please do a `keybase log send` on the machine that can't read from private?

**Comment by gvnmccld** [comment]
Can see public not private: d1254134a7330d4d389bdc1c

Can't update, see public or private: 9da040a3c866335789bd351c

**Comment by strib** [comment]
@gvnmccld: the first device (private not public) appears to be a new device that hasn't been rekeyed into any of your private folders.  From the log, it looks like it was has never been able to read from private directories.  I suspect it will work once @gabriel or something on the OSX install side figures out the issue with your other device and it comes online (and is able to rekey folders for you).

You can confirm this by trying to do something in a private shared folder that you've never looked in before (say `/keybase/private/cannonc,strib,chris` or something).

**Comment by gvnmccld** [comment]
I was just able to successfully add a file to /keybase/private/cannonc,strib

I'm pretty sure the other day all was working on both.  Strange.

**Comment by strib** [comment]
Unless you manually rolled the logs on that device, or nuked its Keybase install and re-provisioned the device, I don't see anything in the history that shows successful access to private directories.

**Comment by gabriel** [comment]
@gvnmccld To fix the update issue you mentioned, you need to manually clear out the existing update files:

```
rm -rf /var/folders/v8/ytsxty651x35b7nsn48gfyk40000gn/T/KeybaseUpdates/*
```

And then retry the update... running `keybase update check` will trigger an update check.

There was a bug in an older version where if a previous update was interrupted, an update may fail.

**Comment by gvnmccld** [comment]
It made it further, but then failed with this error:

ERROR chown /var/folders/v8/ytsxty651x35b7nsn48gfyk40000gn/T/KeybaseUpdates/Keybase-1.0.11-20160211170011+0b33bc6.zip.unzipped/Keybase.app: operation not permitted

**Comment by gabriel** [comment]
Ah so I think the update is failing cause it won't have permissions (and currently it doesn't ask for permission). Do you run as non-admin on that computer (maybe after installing as an admin?)

You can try this... remove /Applications/Keybase.app from your computer, and then install this version here:
https://s3.amazonaws.com/prerelease-test.keybase.io/darwin/Keybase-1.0.11-20160211233436%2B0b33bc6.dmg

This hopefully should fix your issue

**Comment by gvnmccld** [comment]
@gabriel That fixed all of my issues! Thanks!
