### ISSUE TITLE
[MacOS] KBFS: Cannot access /keybase

### ISSUE THREAD

**Issue by PierrickGT** [keybase/client#19843]
As the title say, it failed to install KBFS and now I can't install it again and access to the Finder through Keybase.
Log ID: 9819c3fed8e6de7563efd81c

**Comment by strib** [comment]
You are getting the following error code when trying to install fuse: `-603946985`.

Similar to other issues like #13254, this usually means you are out of "device slots".  Meaning other applications, like VMware or Virtual Box for example, have used all the available OS resources and there are none left for Fuse/KBFS.  Usually there is a pop-up explaining this, I'm sorry if it didn't happen in your case.  You can try uninstalling those programs if you don't need them and see if it helps.

**Comment by PierrickGT** [comment]
Ok well, I'll do without it.
