### ISSUE TITLE
keybase doesn't like my website proof

### ISSUE THREAD

**Issue by stevecheckoway** [keybase/client#19878]
Here's my [proof](https://checkoway.net/.well-known/keybase) for https://checkoway.net. I copied the text that was printed out from running `keybase prove web https://checkoway.net`.

**Comment by Depado** [comment]
Maybe that's because you're serving it with an `octet-stream` Content-Type?
Just a wild guess here.

**Comment by Depado** [comment]
Well as said in the instructions when validating a website, you could just add a `.txt` suffix to your [stevecheckoway.github.io/.well-known/keybase](https://github.com/stevecheckoway/stevecheckoway.github.io/blob/master/.well-known/keybase), and that should work I guess. As far as I understand, GitHub determines the correct MimeType according to the extension of your file.

**Comment by stevecheckoway** [comment]
Oh wow. I completely failed to follow the instructions. I'm not sure how I missed the very clear directions that the file should be `.well-known/keybase.txt` and not `.well-known/keybase`. That was the whole problem. Thank you very much.
