### ISSUE TITLE
Can't put anything in my /keybase

### ISSUE THREAD

**Issue by MSch** [keybase/client#2000]
Tried to share a small file with just `hello` in it, failed with error -36.

my log id: 3a37304731799f7a2ed7151c

**Comment by strib** [comment]
The tracking statement for the user whose folder's you're trying to access is broken. We should have popped up a tracker window for you to re-track the person if you trusted their new identity.  But if that didn't work or you ignored the window, you can try `keybase track <username>`.

**Comment by MSch** [comment]
No window popped up. Thanks.

**Comment by MSch** [comment]
Working perfectly now, thanks again!

**Comment by strib** [comment]
Great! @cjb: another instance of a tracker popup not showing when we get a "X track components failed" error.
