### ISSUE TITLE
How do you "forget" a public folder?

### ISSUE THREAD

**Issue by sbromberger** [keybase/client#2002]
I haven't found a good way to do this: Following the guide, I added a user's public folder and confirmed I could see it in `/keybase/public`. Now, however, I'd like to remove it from Finder / the Keybase menu / etc.

What's the proper way to do this? It persists across kbfs remounts and moving to trash doesn't work.

**Comment by strib** [comment]
I'm sorry, we don't have support for this yet.  Coming soon!

**Comment by sbromberger** [comment]
Ah, good to know. Thanks! I'll close this out since it sounds like it's already on your todo list.
