### ISSUE TITLE
Failed git delete, error 218, "Directory banana-social is not empty and can't be removed"

### ISSUE THREAD

**Issue by ryanstraight** [keybase/client#20025]
Keybase GUI Version: 4.5.0-20190919001132+93e889ab01

Attempted to clone git repo in GitHub and received error 218 (worktree). Tried deleting repo in Keybase and get error that directory isn't empty. Get same error using CLI. Happened on two Keybase repos that were new and had never cloned or used at all.

**Comment by strib** [comment]
If you do a `keybase log send`, and post the resulting ID here, I can take a look.

**Comment by ryanstraight** [comment]
First attempt, tried to send the log but received the following error in the terminal: `ERROR API network error: Post https://api-0.core.keybaseapi.com/_/api/1.0/logdump/send.json: net/http: request canceled (Client.Timeout exceeded while awaiting headers)`

Second attempt, same error.

**Comment by strib** [comment]
Hmm ok sorry.  A few more attempts might eventually work, but no worries.  If you have file system integration enabled with your operating system (not sure what platform you're on), you can try navigating to the corresponding directory that holds the git repos from the terminal.  For example, if the repo is in `keybase://private/ryanstraight` and you're on linux or macOS, go to `/keybase/private/ryanstraight`.

From there:
```sh
cd .kbfs_git/.kbfs_deleted_repos
```
Then you can try renaming the directory in there to something else, like `broken_repo` maybe.  If the repo you deleted was super old (back from when we first announced git) it might have a known bug where there was an undeletable `.` file in it, but renaming it to a different file name scheme should work ok.

**Comment by ryanstraight** [comment]
Worked like a charm. Thanks!
