### ISSUE TITLE
keybase process steady 100% CPU load on OSX 10.14.6

### ISSUE THREAD

**Issue by checkraze** [keybase/client#20072]
My keybase process has been at a near constant 100% CPU load for about 24 hours. This started after deleting a large file structure from a shared private folder, then attempting to add a new set of files to the same shared private folder. 

I let the client run overnight and it was still at 100% today. 

my log id: 8953806043d79145842a5d1c

**Comment by strib** [comment]
@checkraze we're looking into it.  Would you be willing to turn on extra KBFS debugging and sending another log, in case that helps?  If so, please do:

```sh
$ keybase fs set-debug-level 2
<wait a few minutes>
$ keybase log send
$ keybase fs set-debug-level 0
```

And, if you happen to be familiar with Go development, it would be very useful to get a CPU profile of the `keybase` process, but that might be asking too much.

**Comment by strib** [comment]
Another thing to try is running `keybase db nuke` -- let us know if that helps at all.

cc: @mmaxim

**Comment by checkraze** [comment]
`keybase db nuke` seems to have done the trick for me. Process is at nominal CPU levels after monitoring for 5 minutes. Thanks for the quick response!

**Comment by strib** [comment]
Nice! We'll be looking into fixing this in a better way.
