### ISSUE TITLE
Tried to write files to KBFS public dir (first time) and failed

### ISSUE THREAD

**Issue by grempe** [keybase/client#2013]
cp of files to public dir (slowly) failed.  Took about 1 min for all four file copies to fail.

my log id: 9a4c2a719a04fc4122bd4b1c

```
/keybase/public$ cp ~/src/grempe.github.io/downloads/keys/* /keybase/public/grempe/
cp: cannot stat '/keybase/public/grempe/0x2C4C3C144301224F.asc': Input/output error
cp: cannot stat '/keybase/public/grempe/0x37B8284B4B3EBE74.asc': Input/output error
cp: cannot stat '/keybase/public/grempe/0x63608B66C0929A67.asc': Input/output error
cp: cannot stat '/keybase/public/grempe/0xA4A288A3BECCAE17.asc': Input/output error
```

PS - possibly related? Visiting keybase KBFS public pages throwing 501 errors. Perhaps just a service down issue? Not sure if those systems are directly tied.

```
/keybase/public$ curl -i https://keybase.pub/chris/index.md
HTTP/1.1 503 Service Unavailable: Back-end server is at capacity
Content-Length: 0
Connection: keep-alive

/keybase/public$ curl -i https://chris.keybase.pub/index.md
HTTP/1.1 503 Service Unavailable: Back-end server is at capacity
Content-Length: 0
Connection: keep-alive
```

**Comment by strib** [comment]
Thanks for the report.  keybase.pub is a separate system, and I think is down for purely local reasons.

Looks like you're hitting timeouts during one of the very first KBFS operations that needs to be done when accessing a folder.   It's trying to resolve the folder name to our backend identifier for the folder, and timing out, presumably while trying to access one of our servers.

It's not obvious from the log where exactly it's hanging, but in the server logs I see a nearly hour-long gap between requests from you (and usually there's a ping at least once a minute).  Any chance you might have had a drop in internet connectivity or DNS around 22:45 local time, for a few minutes?

I see more activity now from you on the servers, and I see those asc in your public dir now.  Are things working again?

**Comment by grempe** [comment]
Yes it worked a short time later when I tried the same operation. I don't
think I was having any outage (I was able to log the report and add info on
github moments later).

I was getting 501's from the web server for hours last night though.

**Comment by strib** [comment]
> Yes it worked a short time later when I tried the same operation. I don't
think I was having any outage (I was able to log the report and add info on
github moments later).

Hmm, ok.  Sorry for the inconvenience,  It might have just been a short connectivity problem to our servers.  Anyway, I'm glad it's working for you now.  Not sure what else to look at, so I will close, but please reopen or open a new issue if you have troubles like this again.

> I was getting 501's from the web server for hours last night though.

The keybase.pub website?  Yeah, we had some downtime for it last night.  Should be fixed now, sorry.

**Comment by maxtaco** [comment]
It might have been the backups.  I need to take a look if I can get a
chance.

**Comment by maxtaco** [comment]
Oh from keybase pub? Yeah different issue.
