### ISSUE TITLE
Can't move files into /keybase/*

### ISSUE THREAD

**Issue by griffey** [keybase/client#2015]
Installed kbfs, everything seemed to install with no errors. 

When I try to add a file to either /public or /private, I get "The Finder can’t complete the operation because some data in “testing.txt” can’t be read or written.
(Error code -36)"

and nothing happens. I've tried multiple filetypes (txt, jpg) and the same error occurs. 

Directory permissions look like the attached. 

<img width="396" alt="screen shot 2016-02-13 at 9 54 42 am" src="https://cloud.githubusercontent.com/assets/220018/13028258/f35eac6a-d237-11e5-8b24-4575c9a12654.png">

my log id: 8ec31e3ef59267b695d3811c

**Comment by strib** [comment]
Hi @griffey -- looks like you're trying to move the files directly into `/keybase/private` or `/keybase/public`.  The way KBFS works is that you have your own home directories, like `/keybase/private/griffey` and `/keybase/public/griffey`.  Can you try putting files in those instead?

**Comment by griffey** [comment]
So that was my understanding, yes...except neither /private nor /public had /griffey present...and when I attempted to mkdir I was told they already existed. But weren't visible.

So I attempted to move a text file into /public/griffey via command line, and...it seemed to work, but still wasn't visible vis ls nor in the GUI. Then a few seconds later, the /griffey directory I mv'd the file into became visible...but the file that I moved into it weren't there. 

I don't know enough about the underpinnings to make a guess as to what is going on, but there's clearly something not quite right. Now, after having moved files into both invisible /griffey folders (that I can't see in any way), they have both appeared (triggered by moving a file into them). The files that I moved are not there, BUT it does now allow me to move files into them either by CLI or GUI, the files appear, and the kbfs app gives me an alert that they are being encrypted and uploaded. It's almost like I had to add a sacrificial file to this invisible folder to make the system kick in? 

Anyway, you can see the progression of the process here. Please ignore the fumble-finger. :-) 

<img width="552" alt="screen shot 2016-02-13 at 11 38 14 am" src="https://cloud.githubusercontent.com/assets/220018/13028786/49313ffe-d247-11e5-9f71-27e5f9fdc0f0.png">

**Comment by strib** [comment]
You copied the file into `/griffey`, not `/keybase/public/griffey`, as far as I can tell.

**Comment by griffey** [comment]
When initially viewing either /keybase/public OR /keybase/private, neither of them had a directory griffey in them. Should /keybase/public/griffey and /keybase/private/griffey both be created automatically by the installer? I would expect that to be the case...in my case, after installation, neither of those existed (or at least, neither were visible). I would maybe suggest that they should be auto-generated and visible for users.  What is the expected behavior there? Should I have seen them?

**Comment by strib** [comment]
Thanks for the feedback.  A few users have been confused by this behavior, so we will probably change it.  But the idea behind KBFS is that all possible folders already exist, and you can start using them right away, even if they aren't listed.  By not showing the directories named after you, we're trying to teach you that you can just create the folders by simply doing `cd /keybase/private/griffey` for example, or `cd /keybase/private/strib@github,griffey`, or any other combination of users.

But since this seems to be more confusing than helpful, future versions will probably show your personal directories by default.

Is everything working for you now?

**Comment by dblandin** [comment]
> By not showing the directories named after you, we're trying to teach you that you can just create the folders by simply doing cd /keybase/private/griffey for example, or cd /keybase/private/strib@github,griffey, or any other combination of users.

That is so cool. I ran into the same permissions issue when trying to create/copy/move files directly into /keybase/public. Whoops. Just tried to `cd` into a directory that doesn't yet exist locally and it worked like magic! :sparkles: 

```bash
$ ls /keybase/public
devon
$ cd /keybase/public/chris
$ ls
'Man in the Middle.psd'  index.md         plan.txt        verified_software
Photos                   lemon_party.jpg  security_stuff  zcash.txt
$ ls /keybase/public
chris devon

**Comment by griffey** [comment]
Yeah, I'll close the issue...it appears that everything is ok. :-) 

I think your planned behavior might be ok, but if you want that, I'd include a walk-through and force people to create their own as part of the install. At the end, seeing their own is an important thing for usability, IMNSHO. 

Thanks for letting me check this out...very excited for the possibilities.
