### ISSUE TITLE
I love it

### ISSUE THREAD

**Issue by egp** [keybase/client#2017]
Everything is working fine. I expected KBFS to be slower than the regular file system, but it is faster than I thought it would be.  Kudos to the team.  I look forward to an iOS version someday.

my log id: 7ae7ad2f5e139ecbee166a1c

**Comment by malgorithms** [comment]
What great feedback!

The Android + iOS versions will definitely happen and are already in the works.

**Comment by oconnor663** [comment]
Woo!

**Comment by strib** [comment]
Nicest github issue I've ever seen.  Thanks!  I guess I can close this one as "user satisfied with solution"!
