### ISSUE TITLE
mv: failed to preserve ownership for '/keybase/public/<user>/file: Function not implemented

### ISSUE THREAD

**Issue by dblandin** [keybase/client#2018]
Hi Keybase! Loving the filesystem so far!!

I'm getting this error when moving files into my public keybase folder. The error is descriptive and accurate but I wonder if this is expected behavior for every `mv` operation into a keybase filesystem folder.

```
$ echo 'test' > ~/test.txt
$ ls -lsa ~/ | grep text.txt
4 -rw-r--r--    1 devon         5 Feb 13 22:25 test.txt
$ mv test.txt /keybase/public/devon
mv: failed to preserve ownership for '/keybase/public/devon/test.txt': Function not implemented
$ ls -lsa /keybase/public/devon
4 -rw-r--r-- 1 root   5 Feb 13 22:24 test.txt
```

**Comment by strib** [comment]
Yes, that's expected for every `mv` into the FS.  We have an internal issue to figure out a better plan for avoiding that, but it seems the only alternative is lying to the operating system that we can preserve ownership, when we really can't  (e.g., you will have different user IDs on different OSes, your user ID or name probably won't even appear on your friend's OS, etc).  If the community has suggestions, we'd love to hear them!

**Comment by dblandin** [comment]
@strib Gotcha. Thanks for the context! :+1:
