### ISSUE TITLE
I cannot add my PGP key

### ISSUE THREAD

**Issue by cweagans** [keybase/client#2020]
No matter what proof method I try to use, I cannot add my PGP key. My public key can be found [here](http://pgp.mit.edu/pks/lookup?op=get&search=0x6BC866F60B9E4D7A).

On my normal machine, my main private key is not loaded. The main private key only exists on an airgapped machine. I have separate authentication, signing, and encryption subkeys available, and perhaps one of those might be a better target, but I'm not 100% sure on how to approach that with Keybase.

I use a Yubikey 4 for storing my private keys, if it matters. https://www.jclement.ca/articles/2015/gpg-smartcard/ is what I followed to generate my keys.

**Comment by maxtaco** [comment]
We don't support yubikeys yet.

**Comment by cweagans** [comment]
Well, that'd do it. I'm a little confused as to why Yubikeys wouldn't be supported, though. If the idea is that I'm only proving ownership of the key, shouldn't I be able to just upload any public key and sign a proof? I definitely don't expect a somewhat non-standard setup to work OOTB with the CLI client, but a signature is a signature, isn't it?

**Comment by maxtaco** [comment]
Which provisioning path did you take? There is one that should work with
yubikeys since it shells out to gpg.

**Comment by cweagans** [comment]
I tried the bash/gpg/curl method, but after I submit the given command, I get this:

```
gpg: signing failed: Inappropriate ioctl for device
gpg: signing failed: Inappropriate ioctl for device
Error in your post
-------------------

Code: 
Name: 
Description:
```

I'm thinking that the error is because I don't have the main private key on the machine I'm trying to do the proof with. I'm guessing maybe I should replace the key ID with my signing key ID to make it work, but I'm not 100% sure.

**Comment by cweagans** [comment]
I was able to upload a key last night by following the same steps as before, but this time, with GPG 2.1 (rather than 2.0.11).

Thanks!

**Comment by Zenexer** [comment]
To anyone coming here from Google:

```
keybase pgp select --multi --no-import 0xXXXXXXXX
```

`--multi` allows multiple PGP keys to be added to your account.  `--no-import` prevents attempts to import the private key, which will be necessary with a YubiKey (that's the whole point of such a device).  Replace `XXXXXXXX` with the hex ID of your key (typically either 4 or 8 hex digits).  If you're not sure what your key ID is, run `gpg --card-status` and look at the `General key info` field.  Note that gpg-agent will need to be running, as the keybase utility will need to perform a signature.
