### ISSUE TITLE
ERROR First live link has to be eldest (got sibkey) (code 1014)

### ISSUE THREAD

**Issue by tozz** [keybase/client#20233]
My account also seems to affected by `ERROR First live link has to be eldest (got sibkey) (code 1014)` and I can't reset my account on the web site, any way to resolve this?

my log id: 6ec15ea52637a89f90a6391c

**Comment by jdtech3** [comment]
I have this problem as well, and when I try to reset account on the website, I get a `Error 500. Something is not right. We will look into it.` :/

**Comment by maxtaco** [comment]
I can look into manually resetting the account, sorry about this.  Can you give usernames in both cases?

**Comment by tozz** [comment]
Mine is "tozz"

**Comment by maxtaco** [comment]
@tozz see email, thx

**Comment by jdtech3** [comment]
Sorry for poking an old issue, just got notification 😅 but here's mine: `jdtech`
