### ISSUE TITLE
MacOS - kbfs wont load

### ISSUE THREAD

**Issue by em0ney** [keybase/client#20253]
Looks like kbfs wont load. Both the keybase app and finder cannot access my keybase files.

my log id: d98c7b48376fcd902c650b1c

**Comment by em0ney** [comment]
▶ keybase uninstall --components=helper,fuse,mountdir,kbfs
▶ INFO Removing /Users/e/Library/LaunchAgents/keybase.kbfs.plist
▶ INFO Waiting for keybase.kbfs to exit...
▶ INFO Stopped keybase.kbfs
▶ INFO Nothing to stop (homebrew.mxcl.kbfs)
▶ ERROR Error uninstalling mount dir: exit status 1
▶ INFO Removing KBFuse
▶ INFO Removing privileged helper tool

▶ keybase install --components=helper,fuse,mountdir,kbfs
▶ INFO Installing Helper
▶ INFO Installing KBFuse
▶ ERROR Error installing KBFuse: exit status 1
▶ INFO Creating mount directory
▶ INFO Nothing to stop (keybase.kbfs)
▶ INFO Nothing to stop (homebrew.mxcl.kbfs)
▶ INFO log directory "/Users/e/Library/Logs" is writable by current user
▶ INFO log path "/Users/e/Library/Logs/keybase.start.log" exists and is writable by current user
▶ INFO paths in plist look ok and have valid permissions
▶ INFO Saving /Users/e/Library/LaunchAgents/keybase.kbfs.plist
▶ INFO Starting keybase.kbfs
▶ INFO Waiting for keybase.kbfs to be loaded...

**Comment by strib** [comment]
This is the same issue as #14366 and some others.  Basically, macOS has restrictions on how many kernel-level apps it allows, and apparently you're already at your limit by the time Keybase starts.  Check for things like VMware, HAXM, and VirtualBox that might be using kernel device slots.  If you can't free a slot, you can still use KBFS via `keybase fs` commands or through the GUI.

**Comment by em0ney** [comment]
Yeah, confirmed that dropping com.intel.kext.intelhaxm does the trick. Don't do any android development anymore.

For anyone stumbling across this and unfamiliar with the commands:

```
# to see all kexts that don't belong to apple
kextstat | grep -v apple 
# to free a slot
sudo kextunload -b com.intel.kext.intelhaxm
```

Frustrating how few slots are available after apple is done installing security sandboxes and what not.

Thanks for the help!
