### ISSUE TITLE
Issue mounting /keybase after macOS Catalina upgrade

### ISSUE THREAD

**Issue by jsfour** [keybase/client#20284]
Hi I updated to catalina and my `/keybase` mount stopped working.

When I click "Enable Keybase In Finder" the icon just spins indefinitely.

<img width="787" alt="image" src="https://user-images.githubusercontent.com/1569744/66623720-d6f2a900-eba1-11e9-8a09-2f647bdce7ad.png">

my log id: ed15017593dddf27a58ed51c

**Comment by jsfour** [comment]
I just received a "/keybase is unavailable please try again" message in the ui.

**Comment by strib** [comment]
@jsfour is `/Volumes/Keybase` working correctly for you? macOS no longer lets us use `/keybase` in Catalina.  I don't see any obvious problems in your log.

If that's not working, maybe try from the command line:
```
keybase uninstall -c redirector,fuse
keybase --debug install -c fuse,redirector
```
And see if that helps.

**Comment by jsfour** [comment]
Yes it looks like the `/Volumes/Keybase` folder still works. Looks like this is a ui misunderstanding.

Thanks.
