### ISSUE TITLE
You are qualified to join! (or not)

### ISSUE THREAD

**Issue by jaypikay** [keybase/client#20298]
Keybase GUI Version: 4.6.0

The account check on the wallet tells me I am qualified. If I click on "Become a lucky airdropee". It says "You are not qualified".

**Comment by On3-Ey3dW1lly** [comment]
Same here :(

**Comment by Joseavilez20** [comment]
too me ,I have published https://github.com/keybase/client/issues/20254

**Comment by SingaFx** [comment]
me too..sad face

**Comment by phamtrantrong** [comment]
In the end what is the satisfaction condition ?

**Comment by SingaFx** [comment]
all my friends has the same result. all green then not qualified. at first i though this is country issue, but my friends in USA, German & Italy got the same result too. So..

**Comment by jaypikay** [comment]
Nobody cared
