### ISSUE TITLE
keybase-redirector tries to restart several times if disabled

### ISSUE THREAD

**Issue by bepvte** [keybase/client#20338]
Hi! I've noticed that if one disables keybase-redirector using the /etc/keybase/config.json method, keybase-redirector will run the service and the keybase config json several times, and also make a noisy failure.

The way the conditional unit is written is not in the "idiomatic systemd way", which would be: `ConditionPathExists=!/etc/keybase/disable_redirector`, instead of https://github.com/keybase/client/blob/57d6559b09a7e2d197bf95dd7145f063cf1b74ff/packaging/linux/systemd/keybase-redirector.service#L12

ExecStartPre isnt supposed to be used to check if a service should be started since it results in a failure (noisy and sets systemctl status to "degraded") instead of a silent skip. However, if you would like to use ExecStartPre still, you should at least remove `Restart=on-failure` since you throw a failure when its disabled which causes a small loop.

I would provide a pull request for this, but I am unsure if you would like to use ExecStartPre still, and if you want to add something to the update script to convert to the new setting. 

I'm on Fedora 31 x86_64.

```
$ journalctl -u keybase-redirector -e  --user -o cat

Starting Keybase Root Redirector for KBFS...
2019-10-12T14:59:46.167693-04:00 ▶ [WARN keybase json.go:81] 001 Permission denied opening config file /etc/keybase/config.json
2019-10-12T14:59:46.167746-04:00 ▶ [WARN keybase json.go:81] 002 Permission denied opening gui config file /etc/keybase/gui_config.json
2019-10-12T14:59:46.167765-04:00 ▶ [WARN keybase json.go:81] 003 Permission denied opening updater config file /etc/keybase/updater.json
Started Keybase Root Redirector for KBFS.
Can't setreuid: operation not permitted
keybase-redirector.service: Main process exited, code=exited, status=1/FAILURE
keybase-redirector.service: Failed with result 'exit-code'.
keybase-redirector.service: Service RestartSec=100ms expired, scheduling restart.
keybase-redirector.service: Scheduled restart job, restart counter is at 1.
Stopped Keybase Root Redirector for KBFS.
Starting Keybase Root Redirector for KBFS...
[json warning from before]
Started Keybase Root Redirector for KBFS.
Can't setreuid: operation not permitted
keybase-redirector.service: Main process exited, code=exited, status=1/FAILURE
keybase-redirector.service: Failed with result 'exit-code'.
keybase-redirector.service: Service RestartSec=100ms expired, scheduling restart.
keybase-redirector.service: Scheduled restart job, restart counter is at 2.
Stopped Keybase Root Redirector for KBFS.
Starting Keybase Root Redirector for KBFS...
[warning from before]
Started Keybase Root Redirector for KBFS.
Can't setreuid: operation not permitted
keybase-redirector.service: Main process exited, code=exited, status=1/FAILURE
keybase-redirector.service: Failed with result 'exit-code'.
keybase-redirector.service: Service RestartSec=100ms expired, scheduling restart.
keybase-redirector.service: Scheduled restart job, restart counter is at 3.
Stopped Keybase Root Redirector for KBFS.
Starting Keybase Root Redirector for KBFS...
[json warning from before]
Started Keybase Root Redirector for KBFS.
Can't setreuid: operation not permitted
keybase-redirector.service: Main process exited, code=exited, status=1/FAILURE
keybase-redirector.service: Failed with result 'exit-code'.
keybase-redirector.service: Service RestartSec=100ms expired, scheduling restart.
keybase-redirector.service: Scheduled restart job, restart counter is at 4.
Stopped Keybase Root Redirector for KBFS.
Starting Keybase Root Redirector for KBFS...
[json warning from before]
Started Keybase Root Redirector for KBFS.
Can't setreuid: operation not permitted
keybase-redirector.service: Main process exited, code=exited, status=1/FAILURE
keybase-redirector.service: Failed with result 'exit-code'.
keybase-redirector.service: Service RestartSec=100ms expired, scheduling restart.
keybase-redirector.service: Scheduled restart job, restart counter is at 5.
Stopped Keybase Root Redirector for KBFS.
keybase-redirector.service: Start request repeated too quickly.
keybase-redirector.service: Failed with result 'exit-code'.
Failed to start Keybase Root Redirector for KBFS.
```

**Comment by strib** [comment]
@heronhaye any idea on this one?  Should we remove the "Restart" line?  Unsure what that will do if the service is enabled and crashes.

**Comment by heronhaye** [comment]
Or we could do as suggested and allow making the file instead of using the json config.

**Comment by strib** [comment]
@heronhaye The goal of the redirector, which is suid, is to be as dirt simple as possible.  I'm not sure I'm comfortable adding a json parsing library to it.

I still want to allow the config file to control things, at least on macOS, because I don't want to change the helper there.  So we can either support and document both, or figure out a way to get around the restart issue, if we think this is worth pursuing.

**Comment by heronhaye** [comment]
Ok, for a minimal changeset how about editing the systemd unit file as specified and then updating docs to indicate you can make the file instead? (But leaving in the ExecStartPre for users configuring via config.json).

**Comment by strib** [comment]
@heronhaye is taking out the restart line a bad risk though?  i guess it means if the redirector really does crash, we lose the redirector service?

**Comment by heronhaye** [comment]
Yeah. I'm not sure how often that happens - I'm fine with doing that too.

**Comment by strib** [comment]
I thought that's what you were suggesting with "editing the systemd unit file as specified".  Di dyou have something else in mind?

**Comment by heronhaye** [comment]
Oh, I was referring to `ConditionPathExists=!/etc/keybase/disable_redirector`

**Comment by strib** [comment]
I see.  Sure if that would solve the issue without changing the other lines at all, I'm fine with it.

**Comment by bepvte** [comment]
I just realized that another (in my opinion more straightforward) way to go about this would be to ditch the custom disable file and just instruct the user to use regular `systemctl disable` or `systemctl mask`. Both of these things can be done by external tools (like the keybase cli) too, as they are just creating symbolic links.

**Comment by heronhaye** [comment]
I think `mask` is what we need since the redirector is `Want`ed by kbfs. Seems to work well on my machine. @strib want me to edit the docs?

**Comment by strib** [comment]
@heronhaye sure thanks!

**Comment by heronhaye** [comment]
@bepvte docs updated at https://keybase.io/docs/kbfs/understanding_kbfs#root-redirector to mention the mask option.
