### ISSUE TITLE
ERROR CODE 4207 - Sorry, you do not qualift, in method stellar.1.local.airdropRegisterLocal

### ISSUE THREAD

**Issue by f-steff** [keybase/client#20358]
I've received the invitation to to participate in a Lumens Airdrop, and find that I qualify to participate. However once I attempt to sign up for it, I get error code 4207.

I've tested this on Mac (logs included) and on Windows, both with the same analysis result, followed by the same "Sorry you do not qualify" error. On the Mac the error code 4207 and the full text seen in the subject is shown, on Windows it just says that I don't qualify.

![image](https://user-images.githubusercontent.com/7275320/66778589-682c8d00-eecc-11e9-8bc6-0a4b8a3da142.png)

![image](https://user-images.githubusercontent.com/7275320/66778600-75497c00-eecc-11e9-9c14-fad2a3841abc.png)

![image](https://user-images.githubusercontent.com/7275320/66778603-7e3a4d80-eecc-11e9-875e-ce9ed85dd071.png)

my log id: 23af311ca2ea03e77aedfb1c

**Comment by Z86-tech** [comment]
same issue, already reported. you are not the only one https://github.com/keybase/client/issues/20264
