### ISSUE TITLE
ERROR CODE 218/2614 - Team does not exist in method

### ISSUE THREAD

**Issue by Iouns** [keybase/client#20364]
I have two stucked users. I can't rekey or leave conversation with them.
As suggested on others bug reports, I'll try to "fs reset" them.
Can you please approve the following two resets?

**Comment by Iouns** [comment]
logs id : f8a000782cc4234be0bb331c

**Comment by Iouns** [comment]
/keybase/private/iouns,theartefact

BEGIN KEYBASE SALTPACK SIGNED MESSAGE. kXR7VktZdyH7rvq v5weRa0zkPOljs0 OO6bDVJnfwxyrfD N2VE7vmmTJQmJmJ 2iaOcrC1CQ9ajuS 0usixFm1N2XrkBv qnNVTF3RJgeZm0f GnytNwmK9qLo20i osE2L4cPMBqeB6t Vuto4B4yiunoda9 NDI1idfBnpTcQ07 jTpT8vSCAe0v6MK kIwhOH4wXP1UTU8 MJMxfKtKCz3VfTA v33xXPhanoNPpMl byL8KzvbIaKLk4D 65h1ViHWpztTn35 4dtR8ixPQEa6XZc UK1YIOSwrrqV7w5 X7Zajd8PqTA5Cqc iRbREgiXJcu0plM 8zLW83dcBJD9edf WqnileyudUePPv0 Rsbu. END KEYBASE SALTPACK SIGNED MESSAGE.

**Comment by Iouns** [comment]
/keybase/private/iouns,flou

BEGIN KEYBASE SALTPACK SIGNED MESSAGE. kXR7VktZdyH7rvq v5weRa0zkPOljs0 OO6bDVJnfwxyrfD N2VE7vmmTJQmJmJ 2iaOcrC1CPiFiA4 KDgaAb9G5HgB6fo ELZwNUhuFFsvHDx DWCCjJQMW2NBpaD mQOcZ4ztSWrLkK2 vfC7P4puq6TYSjb XknHhYggOIKf1Dl gi3TFyPXL5U1Pmh SQ8OCOGHgqMiwDz 1nSVoAhNSr4Y29w 5fAwpPhanoNPpMl byL8KzvbIaKLk4D 65h1ViHWpztTmnC eE17g7L8hWeHXWU W3I9dyDZbBWXgP9 B280rYLmRYjmS0B t5zHte2YErjyDj2 EWf80MKIEfOcI12 gkEjnEEYw. END KEYBASE SALTPACK SIGNED MESSAGE.

**Comment by Iouns** [comment]
The main issue is that it looks like I have stucked conversations with both users.
I can't tchat with them. You're right, conversations are old and probably before my account reset.

When I try to leave conversation:
    Error: ERROR CODE 218 - Team does not exist in method keybase.1.teams.teamLeave

When I try to show the team details on the conversation:
    Error: ERROR CODE 2614 - Root team does not exist in method chat.1.local.findConversationsLocal

Thank you for your time,

**Comment by strib** [comment]
@mmaxim any ideas?

**Comment by Iouns** [comment]
@strib is there anything I can do to help? I don't want to take too much of your time, if there's nothing to do, we can close this issue.

**Comment by strib** [comment]
I'm sorry, I don't know how to help with the issue.  Hopefully @mmaxim or @maxtaco will chime in.

**Comment by maxtaco** [comment]
@louns, please visit the bad conversations, and then send logs please via `keybase log send`.

**Comment by Iouns** [comment]
Thank you for your replies.

@maxtaco 
log ID: 43316fe2adaa2ae4e5ca4d1c
