### ISSUE TITLE
qualilfy on airdrop?

### ISSUE THREAD

**Issue by joaoqueroiz** [keybase/client#20377]
what i need to qualilfy on airdrop?

**Comment by dafik150689** [comment]
SCAM maybe.

i found comment on twitter says he's from UK
and not qualified. you can check here > > > > > https://twitter.com/avunduk3/status/1182759397732376576

last time im read
The current list of acceptable countries is: Australia, Austria, Belgium, Bolivia, Brazil, Bulgaria, Chile, Croatia, Ecuador, Republic of Cyprus, Czech Republic, Denmark, Estonia, Finland, France, French Guiana, Germany, Greece, Guyana, Hungary, Ireland, Italy, Japan, Latvia, Lithuania, Luxembourg, Malta, Mexico, Netherlands, New Zealand, Paraguay, Peru, Poland, Portugal, Romania, Slovakia, Slovenia, Spain, Sweden, Switzerland, United Kingdom, United States, Venezuela.

3.4 on on play store
3.9 on on appstore
