### ISSUE TITLE
Do i qualified in your airdrop? 

### ISSUE THREAD

**Issue by vodanh7x** [keybase/client#20449]
Dear support,
  My account is : vodanh7xkaka, I am finished three requirements when i clicked on qualifted airdrop, it was shown error and then i am restarted your application, it was lost announcement about airdrop. 
 I logged in your website for checking but my account didn't confirm.
Regards,
Duy Vu

**Comment by madminez** [comment]
I would like to also know this. I get the same error

**Comment by Z86-tech** [comment]
this is a well known error. https://github.com/keybase/client/issues/20264

**Comment by madminez** [comment]
Yes but Is it resolved or any answers as to why or what it means?

**Comment by Z86-tech** [comment]
afaik it is not resolved

**Comment by CyberClouseau** [comment]
Not resolved! It really sucks!  I wonder why they don't reply
