### ISSUE TITLE
I am qualified for airdrop but after "become a lucky.."get message "you do not qualify"

### ISSUE THREAD

**Issue by juliandewit** [keybase/client#20455]
Hello,

When I press "See if you qualify" for the airdrop.
Then it says I'm qualified.
Then I press "become a lucky airdropee".
Then it says "Sorry you are not qualified to join".

This does not make sense to me.
Can someone enlighten me ?

**Comment by Z86-tech** [comment]
https://github.com/keybase/client/issues/20264
