### ISSUE TITLE
Report The Apple IOS KeyBase App Error That Not Complete Correctly The AirDrop Process Whit All The Requirement’s.

### ISSUE THREAD

**Issue by AndresJlloCorp** [keybase/client#20453]
Gentlemen KeyBase - Support.
  
The Greeting Cordially To Confirm Support And Authorize Apply Stellar AirDrop To My Principal
KeyBase Personal Account @AndresJlloCorp Whit My Corporate Mail AndresJllo@JaramilloGroup.com 
In The Less Time Possible, Confirm Additionally My Principal KeyBase Personal Account Complete
All The Account Requirements, Confirm Additionally Inform The Send On Attachment File
The Information And Report The Apple IOS KeyBase App Error That Not Complete Correctly
The AirDrop Process Whit All The Requirement’s, Confirm Authorize Apply Stellar AirDrop To My
Principal KeyBase Personal Account And Restore And Solve The KeyBase App Error In The Least
Time Possible. Confirm The Received In The Least Time Possible.
  
For More Information Contact Our Sucursal Office.
  
Appreciate You're Attention.
  
  
Cordially Regard's,
  
  
Andrés F. Jaramillo Z.
Jaramillo Corporation Group.
President.

Jaramillo Corporation Group.
Financial Sector Nyse, New York, United States.
Avenue 102 West, Street 57Th, Manhattan.
United States Pbx/Fax. +1 (646) 846-02-55.
Corporate Mail. - Investments@JaramilloCorpGroup.com
Corporation Portal. - www.JaramilloCorpGroup.com
New York - United States.
  
  
Send from Andrés F. Jllo. IPhone 11Pro.
Powered by Microsoft Dynamic's.  

![1299CD9F-4345-4112-A3A6-FAE3301E975E](https://user-images.githubusercontent.com/55369682/67069597-3ffa9380-f143-11e9-8e75-b0821e5c72d8.png)
![C40B5D21-EA14-4B86-8662-AEF0650CBE8D](https://user-images.githubusercontent.com/55369682/67069598-3ffa9380-f143-11e9-9e06-e3d97bcfebc8.png)
![B47CC553-5E7B-4CC9-948D-8CE7CBB45F7B](https://user-images.githubusercontent.com/55369682/67069599-40932a00-f143-11e9-8bdf-c9b2aa14b65b.png)

**Comment by Z86-tech** [comment]
same issue here https://github.com/keybase/client/issues/20264
