### ISSUE TITLE
Unable to delete account: Get "Account deletion failsafe was not disengaged. This is a bug!" message

### ISSUE THREAD

**Issue by jesuscriss** [keybase/client#20450]
![kbdeletebug](https://user-images.githubusercontent.com/56710033/67065381-1ab65700-f13c-11e9-97df-84a9d86a0c6f.png)

Hello,
top error message dissapears after a couple seconds and red button loading wheel of doom is infinite.
Acc name: DdayTst1

Thank you

**Comment by maxtaco** [comment]
Sorry about this bug. We'll fix it for the release after next, it probably can't get into this next release since it's close to going out.  Can you delete from the Web site in the mean time. Thanks!

**Comment by heronhaye** [comment]
Should be fixed if you update to 4.7.2. Sorry about that!
