### ISSUE TITLE
KB GUI doesn't load on Win10

### ISSUE THREAD

**Issue by vwal** [keybase/client#20466]
Keybase GUI Version: 4.6.1-20191014130446+3592f81d6f

After the most recent update KB GUI doesn't start up. Rebooting doesn't help. I haven't tried reinstalling KB client yet. Others in the company are seeing the same problem on Windows 10 PCs (Mac client doesn't have this problem).

![keybase_prob](https://user-images.githubusercontent.com/533507/67127419-f059ad80-f1be-11e9-8215-410c2c8a170a.png)

**Comment by maxtaco** [comment]
What sort of virus protection are you running? That's my guess for what the issue is, your antivirus is preventing the crypto service from running.

**Comment by vwal** [comment]
The latest commercial version of ESET Endpoint Protection. But other people with the same issue are running Cylance.

Deprovisioning on the command line, uninstalling (using Revo as to remove all the 5000+ remnants Keybase's own uninstaller leaves behind), then reboot, and reinstall and reprovision seemed to fix the problem – the GUI starts again.

**Comment by maxtaco** [comment]
Right, there are the two providers we have see issues with: Cylance and ESET.

**Comment by vwal** [comment]
Interesting.. I spotted the two then! Anyway, a KB reinstall seems to solve it, just a bit of a pain to deprovision/reprovision.
