### ISSUE TITLE
Multiple "failed to list folder" errors

### ISSUE THREAD

**Issue by rivy** [keybase/client#20473]
On one machine, I'm getting multilple "failed to list folder" errors, and I'm unable to access team folders. Other machines are operating normally.

my log id: 83cc91b8259e5906f1727d1c

**Comment by strib** [comment]
Hi, I work at Keybase and saw your issue about folders failing to list.  It looks like one of your team folders is stuck on that device and trying to read an out-dated version.  I'm going to message you privately on Keybase with a command (so I don't expose your team membership here).

**Comment by rivy** [comment]
Fixed.
Thanks!
