### ISSUE TITLE
see if you quality

### ISSUE THREAD

**Issue by SvetlanaB383** [keybase/client#20484]
Hello!
see if you quality
the phone number is in an approved country, you can add a phone number in the settings.
but he is confirmed
thank you

**Comment by SvetlanaB383** [comment]
i can get airdrop?

**Comment by maxizmius** [comment]
Такая же проблема, а в настройках номер телефона указан.

**Comment by Sasha-Sorokin** [comment]
Basically, big ---k you from them:

![Screenshot](https://user-images.githubusercontent.com/10401817/68542457-42b57500-03df-11ea-982b-4ca1f743ec25.png)
