### ISSUE TITLE
Device named 'reset' is being treated as an account reset option

### ISSUE THREAD

**Issue by transparentCF** [keybase/client#20492]
I am trying to authenticate my phone using my laptop. Its name is 'reset.' Because the Keybase client treats 'reset' as a special value, it displays an account reset option in place of the device, therefore I am unable to authenticate my device.

![wtf is this](https://user-images.githubusercontent.com/50483690/67217834-94598800-f44f-11e9-98b3-a6b85061cecb.jpg)

Looks like the line below is to blame:

https://github.com/keybase/client/blob/79f45c68554de2eb987c2f2666917574b8b3c17f/shared/provision/select-other-device/index.tsx#L22

**Comment by maxtaco** [comment]
Good point, we'll get a fix up shortly

**Comment by transparentCF** [comment]
@maxtaco That's the spirit!

**Comment by maxtaco** [comment]
in the mean time you can workaround this with your paper key or a new paper key

**Comment by transparentCF** [comment]
@maxtaco already done it in a very private room in my house. I didn't want family members to see my paper key.

**Comment by buoyad** [comment]
I've put up a fix here: https://github.com/keybase/client/pull/20496

**Comment by transparentCF** [comment]
The issue has been resolved, so I am closing this issue myself.
