### ISSUE TITLE
ERROR proof error for proof 'team link before user key revocation': seqno 1050 > 1049

### ISSUE THREAD

**Issue by ferasdour** [keybase/client#20503]
Been having some issues with keybase group chats since revoking a twitter proof. This issue started around 12:40am cst sat oct 19th (5:40 AM zulu?). When going into the chat I only get failed to send after a while sitting there on the loading padlock thing. When going to settings (confirmed this happens for other members of the group chat as well (example pornography team, I would use more appropriate examples but other chats aren't open chats)) this appears to show this error there: "ERROR proof error for proof 'team link before user key revocation': seqno 1050 > 1049"

I've tried reinstalling, switching between systems, cli versus gui, checking with other users (who I can directly contact but messages are delayed), and in other chats (which work just fine if I wasn't owner). I can understand where this error may come from but don't have any means of fixing it. Tried to add a new twitter proof, which failed as well. 

Everything that I've seen in other errors shows that this issue has been a problem for others too in some ways but not a lot of updates on them. This particular error I didn't see mentioned in anything recent however so started my own.

**Comment by maxtaco** [comment]
Sorry about this, this sounds like a bug on our part. We'll have to look into. No amount of reinstalling, etc, will fix it.

**Comment by ferasdour** [comment]
Doing so from linux and mac computers both ended in:

ERROR API network error: Post https://api-0.core.keybaseapi.com/_/api/1.0/logdump/send.json: net/http: request canceled (Client.Timeout exceeded while awaiting headers)

Trying from app on phone to do feedback ended with saying it was sent

**Comment by maxtaco** [comment]
Is something wrong with your network or are you on a proxy?

**Comment by maxtaco** [comment]
The logs from the mobile phone didn't show the issue, so repro the issue first on the phone and then send the log from the phone again.

**Comment by ferasdour** [comment]
no proxy set in keybase client on either computer, tried different networks now. currently can curl the site with no issue.

curl -kI https://api-0.core.keybaseapi.com
HTTP/2 200 
date: Mon, 21 Oct 2019 19:00:48 GMT
content-type: text/html; charset=utf-8
content-length: 17468
x-frame-options: SAMEORIGIN
x-xss-protection: 1; mode=block
x-content-type-options: nosniff
set-cookie: guest=lgHZIDJlZTJiNTgzOWRjYWQ4OGQzMGFiYjYyNDA0NTMwMDA4zl2uAGDOAAFRgMDEILo1Ng0Jt8DrIC5GaJtKHuK%2FnlLQELzpPoB8Z0L5yzEu; Max-Age=604; Domain=.keybase.io; Path=/; Expires=Mon, 21 Oct 2019 19:10:53 GMT; HttpOnly; Secure
etag: W/"443c-wzHyY8ycJo6VFGZ4nY2Lhq49QCo"
strict-transport-security: max-age=31536000; includeSubdomains; preload

Reproduced error on phone by going to settings of the group, showed error, resent. i enabled screen shots and grabbed one if needed as well.

**Comment by ferasdour** [comment]
oops, should have added this too:
curl https://api-0.core.keybaseapi.com/_/api/1.0/logdump/send.json -kI
HTTP/2 404 
date: Mon, 21 Oct 2019 19:07:10 GMT
content-type: text/html; charset=utf-8
content-length: 23
x-frame-options: SAMEORIGIN
x-xss-protection: 1; mode=block
x-content-type-options: nosniff
etag: W/"17-kg0c4uGqVJ3up/HJ27+pPVKFQOY"

curl https://api-0.core.keybaseapi.com/_/api/1.0/logdump/send.json -kI -X POST
HTTP/2 200 
date: Mon, 21 Oct 2019 19:07:58 GMT
content-type: application/json; charset=utf-8
content-length: 276
vary: X-HTTP-Method-Override
x-frame-options: SAMEORIGIN
x-xss-protection: 1; mode=block
x-content-type-options: nosniff
etag: W/"114-7B/tX2ntbM+KM+V/AISTLwmWK6g"
strict-transport-security: max-age=31536000; includeSubdomains; preload

**Comment by maxtaco** [comment]
Work around PR: https://github.com/keybase/client/pull/20511

The fix is on the server

**Comment by ferasdour** [comment]
Sooo... still getting this error, did I need to do anything on my side? 

keybase team settings pornography
▶ ERROR proof error for proof 'team link before user key revocation': seqno 1050 > 1049

keybase team show-tree pornography
▶ ERROR proof error for proof 'team link before user key revocation': seqno 1050 > 1049

**Comment by maxtaco** [comment]
We need a new client release for this

**Comment by maxtaco** [comment]
Can you update your software and try again? Thanks

**Comment by ferasdour** [comment]
keybase team settings pornography
▶ ERROR proof error for proof 'team link before user key revocation': seqno 1050 > 1049
keybase version
Client:  4.7.2-20191028173732+6fc2e969b4
Service: 4.7.2-20191028173732+6fc2e969b4

This appears to be the latest release according to the releases page. I went over and tried out the nightly builds too from a vm:
┌─[user@parrot]─[~]
└──╼ $keybase team settings pornography
▶ ERROR PushHandler: failed to run teamHandler handler: proof error for proof 'team link before user key revocation': seqno 1050 > 1049 [tags:user-agent=linux:Keybase CLI (go1.13):4.9.0,GRGRONCONN=qr8Kxq5wbOcA,GRGIBM=s_znKRSVU4ho,chat-trace=GWxLqc_CneUn,platform=linux,apptype=desktop]
▶ ERROR proof error for proof 'team link before user key revocation': seqno 1050 > 1049
┌─[✗]─[user@parrot]─[~]
└──╼ $keybase version
Client:  4.9.0-20191112170031+6c30e56c4b
Service: 4.9.0-20191112170031+6c30e56c4b

**Comment by maxtaco** [comment]
Can you please send another log?

**Comment by maxtaco** [comment]
Keybase log send

**Comment by ferasdour** [comment]
Success! Your log ID is:

  0fed69ec6a6946dcd167ca1c

**Comment by maxtaco** [comment]
Thank you

**Comment by maxtaco** [comment]
Seems fixed, thanks for your patience.
