### ISSUE TITLE
Keybase airdrop

### ISSUE THREAD

**Issue by Olerpestinhos** [keybase/client#20514]
I was trying to join in but an error appeared and now i dont found a way to get to the drop again.
Any thoughts?

**Comment by Z86-tech** [comment]
click on "my wallet", then there will be a button join airdrop. after that try your luck, but be adviced right  now there is a well known bug - https://github.com/keybase/client/issues/20264
![2w2w](https://user-images.githubusercontent.com/25160132/67368687-69228600-f580-11e9-944a-c86eb9915159.png)

**Comment by Olerpestinhos** [comment]
I tried to join from there and I'm qualify but when i press the "become a luckily airdropee" it says that I'm not qualify. Is this part of the bug?

**Comment by Z86-tech** [comment]
Probably a bug. We don't have clear answer from dev. Im sorry we are all in the same boat, you can check my previous post, you are not only one

**Comment by Olerpestinhos** [comment]
Ok, thanks for the help
