### ISSUE TITLE
KBFS didn't restart after daily update

### ISSUE THREAD

**Issue by NeilNjae** [keybase/client#2052]
After the first daily update, KBFS didn't restart. 

my log id: 5e2b46738f70ce8c3f04541c

## Terminal output

neil@temujin:~$ run_keybase
Shutting down Keybase GUI...
Shutting down keybase service...
Launching keybase service...
Mounting /keybase...
Launching Keybase GUI...
Success!
                                                  ▄▄▄▄█▀    
╭───────────────────────╮          ▄▄          ▄▄▄█▄▄▀      
│                       │         ███▄▄▄▄▄▄▄▄▄▄███▄██       
│  Encrypt everything!  │       ▄▄▄████▄▄▄███████████       
│                       ├────  ▄▄▄▄▄████▄█████████████      
╰───────────────────────╯      ███▄█▄█████████████████▄▄    
                                ▀▄███████▄▀ ███████████▄▄   
                                  ▄▄▄▄███    ███████████▄▄  
                                 ▄████████   ██████████████ 
                                ▄███▄█████▄▄  ▀▄████████████
                               ███████▄▄██▄█▄▄ █████████████
                              ▄▄█████████████▄▄ ████████████
                           ▄██▄▄████▄▄▄█▄▄█████ ████████████
                                ███▄▄▄▄▄███████▄▄█████████▄▀
                                ▄█████▄▄█████████████▄█████ 
                                █▄██████████▄▄▄▄▄▄▄███████  
                              ▄▄▄▄▄██▄▄█████▄████████████   
                            ▀▀▀▀▀▀▀▀▄▄▄▄██▄▀ ▀▀▄▄▄▄▄▄▀▀▀    
                                  ▀▀▀▀▀▀▀▀▀                 
neil@temujin:~$ keybase status
Username:      neilnjae
Logged in:     yes

Device:
    name:   Home
    ID:     ......
    status: active

Local keybase keychain: locked
Session status:         no session

KBFS:
    status:    not running
    version:   
    log:       /home/neil/.cache/keybase/keybase.kbfs.log

Service:
    status:    running
    version:   1.0.12-20160217170050+a290ca2
    log:       /home/neil/.cache/keybase/keybase.service.log

...

**Comment by oconnor663** [comment]
I think "KBFS status: not running" is a bug in status. Can you please check whether KBFS is actually running with `ls /keybase`?

**Comment by NeilNjae** [comment]
It wasn't.

I've just updated with todays update, and it's working now. That was an easy fix!

Ta
