### ISSUE TITLE
Keybase status shows I have a secret key - yet I cant sign

### ISSUE THREAD

**Issue by vtkstef** [keybase/client#20523]
I installed keybase on a new computer and I was hoping that I could use it to import my gpg keys onto it, yet I can't access my secret key

```
C02ZC27ALVDQ:toastsign-service stefano$ keybase status
Username:      vtkstef
Logged in:     yes

Device:
    name:      Toast MacBookPRO
    ID:        6b552a6b3d2ff4ca441ec888acae9418
    status:    active

Session:
    is valid:  yes
    keys:      unlocked

Key status:
    stream:    cached
    secret:    stored
    dev sig:   cached
    dev enc:   cached
    paper sig: not cached
    paper enc: not cached
    prompt:    show
    tsec:      not cached
```
when I try to sign I get 

```
keybase pgp sign -m "message"
▶ ERROR No secret key available
```

**Comment by maxtaco** [comment]
Doesn't seem like you have the secret key for `DAC6F498FBF3394E` available on that machine, and we don't sync it by default. Which machine did you create this key on?

**Comment by vtkstef** [comment]
It was in my previous job's workstation. I removed the device from keybase

**Comment by maxtaco** [comment]
then i'd drop the existing key and generate a new one

**Comment by vtkstef** [comment]
then what is the point of importing secret keys and not being able to export them? I was drawn to keybase for exactly this ability...

**Comment by maxtaco** [comment]
The private PGP key is now gone if you no longer have access to that machine.  If you want a new key, and want to sync it across your devices, you can use `keybase pgp push-private` and `keybase pgp pull-private`.
