### ISSUE TITLE
Stellar airdrop qualification confusion

### ISSUE THREAD

**Issue by mag669** [keybase/client#20526]
Hi although its been confirmed on app that ive met all conditions to qualify when I want to join the airdrop the message says "Sorry, you dont qualify"

Can yiu please check it 

Many thanks

**Comment by Z86-tech** [comment]
https://github.com/keybase/client/issues/20264 known issue

**Comment by mag669** [comment]
Thanks weird situation

**Comment by bazmanv** [comment]
hello dear... make sure read the rules
