### ISSUE TITLE
Question: remote reflog on Keybase Git repositories

### ISSUE THREAD

**Issue by NieDzejkob** [keybase/client#20537]
I messed up.

I use pass as my password manager, syncing between computers with Keybase git repositories. Long story short, the password for an encrypted backup is, if anywhere, in a no-longer-referenced commit on a Keybase git remote. I suspect this is a result of using two remotes and configuring git to rebase instead of merging when pulling.

In a local git repo, one can see such commits with `git reflog`. My limited understanding of KBFS suggests that it should be possible to do the same with a Keybase git remote. Alternatively, is there a way I can fetch all objects in a repository?

**Comment by strib** [comment]
@NieDzejkob you can always do a full `git clone --mirror keybase://...` to get all the commits in the repo.  Or you can inspect it manually if you have the KBFS explorer/finder integration enabled, by going to `/keybase/team/teamname/.kbfs_git/reponame` (for a given `teamname` and `reponame`) to see the bare git repo.

**Comment by NieDzejkob** [comment]
@strib Thanks! This was really helpful. Unfortunately, I didn't find anything.
