### ISSUE TITLE
Emacs doesn't like writing to KBFS

### ISSUE THREAD

**Issue by timmc** [keybase/client#2056]
When I open foo.txt and editing it, I get the following on save:

`Opening output file: input/output error, /keybase/public/timmc/foo.txt`

The file *does* get saved, though. Another editor I tried worked fine. I don't know enough about Emacs to say why this failed to go smoothly, but it might indicate a problem in the filesystem.

**Comment by strib** [comment]
If you do a `keybase log send`, and give us the ID, I can check it out for you.  Could be something transient, I've had success with emacs in the past.

**Comment by timmc** [comment]
Sorry, keep forgetting to do that. Here it is: 4aa12edaa48feb7b2cdfe81c

**Comment by strib** [comment]
Hrm, looks like your emacs is interrupting file system calls after ~90 ms?

```
85069 2016-02-18T06:46:46.252713 ▶ [DEBU kbfs(FBO ea17495f) folder_branch_ops.go:4195] 1193a Sync 0xc8204f67d0 [tags:FID=5x2ptz2fqIXedtYs8PRXeA]
85070 2016-02-18T06:46:46.252924 ▶ [DEBU kbfs keybase_daemon_rpc.go:491] 1193b Sending notification for timmc#public/index.md
85071 2016-02-18T06:46:46.345718 ▶ [DEBU FUSE serve.go:755] 1193c <- Interrupt [ID=0x311d Node=0x0 Uid=0 Gid=0 Pid=0] ID 0x311c
85072 2016-02-18T06:46:46.345906 ▶ [DEBU FUSE serve.go:817] 1193d -> [ID=0x311d] Interrupt
85073 2016-02-18T06:46:46.345961 ▶ [DEBU kbfs(FBO ea17495f) folder_branch_ops.go:4196] 1193f Done: context canceled [tags:FID=5x2ptz2fqIXedtYs8PRXeA]
85074 2016-02-18T06:46:46.345957 ▶ [DEBU kbfs(BSR) bserver_remote.go:215] 1193e AddBlockReference id=01a305692a2150555f7f303545365bee74b08c4caa0e4edcda2897d2206c439b03 uid=c93c7385647d3b63a9cba871d6ef7800 err=context canceled [tags:FID=5x2ptz2fqIXedtYs8PRXeA]
85075 2016-02-18T06:46:46.346035 ▶ [DEBU kbfsfuse file.go:119] 11940 context canceled [tags:FID=5x2ptz2fqIXedtYs8PRXeA]
85076 2016-02-18T06:46:46.346083 ▶ [DEBU FUSE serve.go:817] 11941 -> [ID=0x311c] Setattr error=EIO: context canceled
```

I'll try to repro and/or investigate a bit more.

**Comment by tv42** [comment]
I'd like to see what was in the log before that snippet.

**Comment by strib** [comment]
@tv42: here is a larger snippet:

```
85063 2016-02-18T06:46:46.252096 ▶ [DEBU FUSE serve.go:755] 11934 <- Open [ID=0x311b Node=0x8c Uid=1000 Gid=1000 Pid=18245] dir=false fl=OpenWriteOnly
85064 2016-02-18T06:46:46.252187 ▶ [DEBU FUSE serve.go:817] 11935 -> [ID=0x311b] Open 0x3 fl=0
85065 2016-02-18T06:46:46.252404 ▶ [DEBU FUSE serve.go:755] 11936 <- Setattr [ID=0x311c Node=0x8c Uid=1000 Gid=1000 Pid=18245] size=0 handle=INVALID-0x0 lockowner
85066 2016-02-18T06:46:46.252499 ▶ [DEBU kbfsfuse file.go:118] 11937 File SetAttr [tags:FID=5x2ptz2fqIXedtYs8PRXeA]
85067 2016-02-18T06:46:46.252530 ▶ [DEBU kbfs(FBO ea17495f) folder_branch_ops.go:3452] 11938 Truncate 0xc8204f67d0 0 [tags:FID=5x2ptz2fqIXedtYs8PRXeA]
85068 2016-02-18T06:46:46.252667 ▶ [DEBU kbfs(FBO ea17495f) folder_branch_ops.go:3453] 11939 Done: <nil> [tags:FID=5x2ptz2fqIXedtYs8PRXeA]
85069 2016-02-18T06:46:46.252713 ▶ [DEBU kbfs(FBO ea17495f) folder_branch_ops.go:4195] 1193a Sync 0xc8204f67d0 [tags:FID=5x2ptz2fqIXedtYs8PRXeA]
85070 2016-02-18T06:46:46.252924 ▶ [DEBU kbfs keybase_daemon_rpc.go:491] 1193b Sending notification for timmc#public/index.md
85071 2016-02-18T06:46:46.345718 ▶ [DEBU FUSE serve.go:755] 1193c <- Interrupt [ID=0x311d Node=0x0 Uid=0 Gid=0 Pid=0] ID 0x311c
85072 2016-02-18T06:46:46.345906 ▶ [DEBU FUSE serve.go:817] 1193d -> [ID=0x311d] Interrupt
85073 2016-02-18T06:46:46.345961 ▶ [DEBU kbfs(FBO ea17495f) folder_branch_ops.go:4196] 1193f Done: context canceled [tags:FID=5x2ptz2fqIXedtYs8PRXeA]
85074 2016-02-18T06:46:46.345957 ▶ [DEBU kbfs(BSR) bserver_remote.go:215] 1193e AddBlockReference id=01a305692a2150555f7f303545365bee74b08c4caa0e4edcda2897d2206c439b03 uid=c93c7385647d3b63a9cba871d6ef7800 err=context canceled [tags:FID=5x2ptz2fqIXedtYs8PRXeA]
85075 2016-02-18T06:46:46.346035 ▶ [DEBU kbfsfuse file.go:119] 11940 context canceled [tags:FID=5x2ptz2fqIXedtYs8PRXeA]
85076 2016-02-18T06:46:46.346083 ▶ [DEBU FUSE serve.go:817] 11941 -> [ID=0x311c] Setattr error=EIO: context canceled
85077 2016-02-18T06:46:46.346155 ▶ [DEBU kbfs(BSR) bserver_remote.go:192] 11942 Put id=0169ac011a43750b3ab7d65e58937fdce1d7f3414731ce484cf8128e6319a071be uid=c93c7385647d3b63a9cba871d6ef7800 sz=313 err=context canceled [tags:FID=5x2ptz2fqIXedtYs8PRXeA]
85078 2016-02-18T06:46:46.348236 ▶ [DEBU FUSE serve.go:755] 11943 <- Release [ID=0x311e Node=0x8c Uid=0 Gid=0 Pid=0] 0x3 fl=OpenWriteOnly rfl=0 owner=0x0
85079 2016-02-18T06:46:46.348458 ▶ [DEBU FUSE serve.go:817] 11944 -> [ID=0x311e] Release
```

It's a truncate call that KBFS follows with a sync.  But there are lots of other places like this in the log, including `Symlink` calls, that get interrupted after ~100 ms.

**Comment by strib** [comment]
I can't repro on Emacs 24.3.1, on Linux Ubuntu 14.04.

@timmc: looks like you're on Linux too -- what flavor, and what version of Emacs?  Any weird config in your `.emacs` file related to timeouts or the file system?

**Comment by tv42** [comment]
IS this on OS X, with OSXFUSE 3.2.0? One theory would be that the new `daemon_timeout` logic is too trigger happy, or that you're configuring the timeout before interrupt very low.

**Comment by strib** [comment]
@tv42: no, looks like Linux to me (according to clues in his logdump.

**Comment by timmc** [comment]
Debian 7 (Wheezy) with GNU Emacs 23.4.1. Nothing too wild in the `.emacs.d/init.el`. Maybe there's something to do with how it does file backups on save:

```
(setq
 backup-by-copying t ; don't clobber symlinks
 backup-directory-alist
 '(("." . "~/.emacs-backups")) ; don't litter my fs tree
 delete-old-versions t
 kept-new-versions 6
 kept-old-versions 2
 version-control t) ; use versioned backups
```

I use an encrypted filesystem, so there's a little bit of latency on writes that might push something over the edge.

**Comment by strib** [comment]
Hmm, ok thanks.  And to save the files you were just doing `C-x C-s` right?  You didn't get impatient and hit some other command sequence?  I'm guessing not, just covering all the bases.

**Comment by tv42** [comment]
Maybe capture the syscalls emacs makes, `strace -s1000 -w foo -p PID_OF_EMACS_HERE`.. start that, save the file emacs, hit control-C on the strace. Beware the file may end up containing sensitive data.

**Comment by strib** [comment]
Ah, I was able to repro by using the same `backup` config.  Hmm, `backup-by-copying` does something weird?

@tv42, attached is my strace output.  Look for the `EIO`.


[trace.txt](https://github.com/keybase/client/files/137119/trace.txt)

**Comment by strib** [comment]
Err, look for the last EIO.

**Comment by strib** [comment]
I'm totally stumped.  Here's part of the strace from another repro:

```
16:22:22.766273 symlink("strib@hooks.3880:1455126981", "/keybase/private/strib/.#z") = -1 EIO (Input/output error)
16:22:23.073747 --- SIGIO {si_signo=SIGIO, si_code=SI_TKILL, si_pid=3880, si_uid=1000} ---
16:22:23.073779 rt_sigreturn()          = -1 EIO (Input/output error)
```

`3880` is the PID of my emacs process, and `1000` is my local UID.  So something deep within emacs is sending a thread kill signal after ~300 ms.  I've been trying to look through the emacs source code and the common lisp source code for any obvious thread killing behavior in file IO, and I've come up short.

@tv42: any ideas?

**Comment by tv42** [comment]
Well it seems emacs is using `SIGIO` to perform async network I/O *or* terminal I/O (not regular file I/O; it's incapable of that). *But* the `SI_TKILL` makes it look like this might have been an explicit `tgkill(2)` call, that is, threads communicating to each other.

Regardless of the above, the symlink really must work; emacs uses `.#*` as essentially a lock file. (Somewhat like vi's "swap files", if you're more familiar with those.)

The `rt_sigreturn` below should just be the signal handler (for the `SIGIO`) returning; its `EIO` may just be a repeat of the syscall that was in progress just before (= symlink).

It's worth noting that when emacs proceeds to open the file (`/keybase/private/strib/y` in the trace.txt), writes happily, but `fsync` on the file gives `EIO`.

Here's a theory: after I/O errors, emacs uses `tgkill(2)` to communicate across threads. This the `SIGIO` stuff is just emacs internals, and for the sake of understanding kbfs behavior we can largely ignore it.

It's funny that the `open` and `write` succeed just fine. The FUSE `Setattr` we saw interrupted should be seen at `open` time.

I'm also concerned with all the `EIO`s in the trace.

1. sort of unrelated to this, `stat` of `/keybase/private/.svn` etc giving `EIO` is probably a bad thing.
2.` fsync` giving `EIO` on a perfectly normal seeming file? you should have some explanation in the kbfs side logs

**Comment by strib** [comment]
@tv42: the `EIO`s on both the `fsync` and the `symlink` calls are being _caused_ by interrupts coming into FUSE from somewhere.  Both calls would otherwise succeed if not interrupted -- KBFS is having no problems.

The `open` and `write` calls don't get interrupted; hence they succeed.

**Comment by tv42** [comment]
I think we found the bug, system calls being interrupted by signals need to return `EINTR`, and the current code leads to `EIO` there, causing the "retry syscalls" logic to not retry.

Fix looks like it belongs in upstream FUSE lib, working on it...

**Comment by tv42** [comment]
Alright the problem is now well understood but fixing it will require some rocket surgery. The structure of the code in `bazil.org/fuse` is making easy fixes impossible.

**Comment by tv42** [comment]
How to reproduce:

1. Simulate slow networking even in local mode.

```
diff --git i/libfuse/file.go w/libfuse/file.go
index 0f5afd1..b373ebe 100644
--- i/libfuse/file.go
+++ w/libfuse/file.go
@@ -1,6 +1,8 @@
 package libfuse
 
 import (
+       "time"
+
        "bazil.org/fuse"
        "bazil.org/fuse/fs"
        "github.com/keybase/kbfs/libkbfs"
@@ -118,6 +120,7 @@ func (f *File) Setattr(ctx context.Context, req *fuse.SetattrRequest,
        f.folder.fs.log.CDebugf(ctx, "File SetAttr")
        defer func() { f.folder.fs.reportErr(ctx, err) }()
 
+       time.Sleep(1 * time.Second)
        valid := req.Valid
        if valid.Size() {
                if err := f.folder.fs.config.KBFSOps().Truncate(
```

2. Start kbfsfuse mount in local mode:

```
$ go build github.com/keybase/kbfs/kbfsfuse && ./kbfsfuse -server-in-memory -localuser strib -debug mnt
```

3. Use a standalone emacs to isolate the configuration effect:

```console
$ cat init.el
(setq
 backup-by-copying t ; don't clobber symlinks
 backup-directory-alist
 '(("." . "~/tmp")) ; don't litter my fs tree
 delete-old-versions t
 kept-new-versions 6
 kept-old-versions 2
 version-control t) ; use versioned backups
$ emacs -q -l init.el mnt/private/strib/foo
```

Type something, hit `C-x C-s`. Repeat 2-4 times if successful; usually triggers on second save.

Going to send a pull request soon.

**Comment by tv42** [comment]
And here's the observed behavior with the above reproduce scenario, running https://github.com/keybase/kbfs/pull/755 -- the relevant part is the `EINTR` at the end, and how emacs did not show errors.

```
2016-02-24T17:48:35.659107 ▶ [DEBU FUSE serve.go:776] 4f1 <- Setattr [ID=0x109 Node=0x7 Uid=1000 Gid=1000 Pid=23939] size=0 handle=INVALID-0x0 lockowner
2016-02-24T17:48:35.659194 ▶ [DEBU kbfsfuse file.go:120] 4f2 File SetAttr [tags:FID=2ACKF0ralMLE8bY1AYJS_A]
2016-02-24T17:48:35.894470 ▶ [DEBU FUSE serve.go:776] 4f3 <- Interrupt [ID=0x10a Node=0x0 Uid=0 Gid=0 Pid=0] ID 0x109
2016-02-24T17:48:35.894592 ▶ [DEBU FUSE serve.go:838] 4f4 -> [ID=0x10a] Interrupt
2016-02-24T17:48:36.659443 ▶ [DEBU kbfs(FBO de559d51) folder_branch_ops.go:3497] 4f5 Truncate 0xc8214787d0 0 [tags:FID=2ACKF0ralMLE8bY1AYJS_A]
2016-02-24T17:48:36.659542 ▶ [DEBU kbfs(FBO de559d51) folder_branch_ops.go:3498] 4f6 Done: context canceled [tags:FID=2ACKF0ralMLE8bY1AYJS_A]
2016-02-24T17:48:36.659592 ▶ [DEBU kbfsfuse file.go:121] 4f7 context canceled [tags:FID=2ACKF0ralMLE8bY1AYJS_A]
2016-02-24T17:48:36.659618 ▶ [DEBU FUSE serve.go:838] 4f8 -> [ID=0x109] Setattr error=EINTR
```

**Comment by magandrez** [comment]
@tv42 I've had a very similar issue regarding Emacs (26.0.50) + KBFS on Mac. 

The issue is regarding opening/saving encrypted org files under faulty connectivity. I can elaborate on this, should I open a new issue for that?

**Comment by strib** [comment]
Hi @magandrez -- KBFS doesn't support offline environments right now.  (It's on our TODO list, but not yet scheduled.)  So it's expected that writes won't work if connectivity doesn't work.  If you're experiencing issues when you're sure your connectivity is up, please do file a new issue with a log send.

**Comment by magandrez** [comment]
Hi @strib the issue I experience is perhaps more related to the way emacs is handling KBFS _after_ the computer goes offline. Mayhaps you could give some input if the following case falls in the realm of KBFS offline support or not?.
 
The use case I am aiming is to be able to open my org files when I still have connectivity, edit them (save backup somewhere else) and then properly save them again when I recover connectivity.

Currently when I open emacs org files from my private KBFS mountpoint (with connectivity) I have no problem. Then I loose connectivity, and emacs flashes errors every second like: 

`Opening output file: input/output error, /keybase/private/spavi/personal-todo.org.gpg`

I would like to continue working normally on  my files (without saving them) and then save those when I recover connectivity (e.g.: traveling, etc.)

**Comment by strib** [comment]
@magandrez: I assume that this is Emacs trying to do autosaves in the background.  Maybe you can edit your emacs settings so that autosaves under the /keybase tree go into /tmp/, rather than back into the same directory?  Or turn off autosave entirely?  You can find more info here: https://www.emacswiki.org/emacs/AutoSave (this seems to have settings for changing all auto-saves to /tmp/, but I bet there's a way to do it for just the /keybase mount...)

**Comment by tv42** [comment]
I wouldn't recommend `/tmp` for emacs autosaves, who knows what race attacks that opens up.

I have this in my customizations: ` '(backup-directory-alist (quote (("." . "/home/tv/.emacs-backup"))))`

**Comment by magandrez** [comment]
@strib @tv42 Regarding this issue, it turned out it wasn't Emacs' auto-save, as I already had it setup to backup files in a specific local folder in my home.

The problem turned out to be Emacs' lock files (which you cannot redirect to any other folder): here some [Emacs documentation on File Locks](https://www.gnu.org/software/emacs/manual/html_node/elisp/File-Locks.html).

So what I did was disable lock files entirely, as I am mostly working in machines alone, without danger of overwriting somebody else's work. For that, I set `(setq create-lockfiles nil)` in my Emacs config. 

With this config, I can safely open the org files individually (or via the agenda) -> /loose connectivity/ -> work on my files (without saving them) -> /regain connectivity/ -> save my work.

NOTE: Additionally, I had previously set EasyPg to skip autosave of (de)crypted files`(setq epa-file-inhibit-auto-save t)` [Emacs documentation on EasyPG](https://www.gnu.org/software/emacs/manual/html_mono/epa.html#index-epa_002dfile_002dinhibit_002dauto_002dsave-46).

Many thanks for pointing me in the right direction. I hope for long life to the keybase project, I love it!

**Comment by tonyarkles** [comment]
Another hint for people experiencing problems with this. Projectile-mode causes significant pain with Keybase. It's frequently looking for project files and that seems to slow Emacs down significantly. Here's some sample strace output:

```
faccessat(AT_FDCWD, "/keybase/private/tonyarkles/rebar.config", F_OK) = -1 ENOENT (No such file or directory)
faccessat(AT_FDCWD, "/keybase/private/tonyarkles/project.clj", F_OK) = -1 ENOENT (No such file or directory)
faccessat(AT_FDCWD, "/keybase/private/tonyarkles/build.boot", F_OK) = -1 ENOENT (No such file or directory)
faccessat(AT_FDCWD, "/keybase/private/tonyarkles/SConstruct", F_OK) = -1 ENOENT (No such file or directory)
faccessat(AT_FDCWD, "/keybase/private/tonyarkles/pom.xml", F_OK) = -1 ENOENT (No such file or directory)
faccessat(AT_FDCWD, "/keybase/private/tonyarkles/build.sbt", F_OK) = -1 ENOENT (No such file or directory)
faccessat(AT_FDCWD, "/keybase/private/tonyarkles/gradlew", F_OK) = -1 ENOENT (No such file or directory)
faccessat(AT_FDCWD, "/keybase/private/tonyarkles/build.gradle", F_OK) = -1 ENOENT (No such file or directory)
faccessat(AT_FDCWD, "/keybase/private/tonyarkles/Gemfile", F_OK) = -1 ENOENT (No such file or directory)
faccessat(AT_FDCWD, "/keybase/private/tonyarkles/requirements.txt", F_OK) = -1 ENOENT (No such file or directory)
faccessat(AT_FDCWD, "/keybase/private/tonyarkles/setup.py", F_OK) = -1 ENOENT (No such file or directory)
faccessat(AT_FDCWD, "/keybase/private/tonyarkles/tox.ini", F_OK) = -1 ENOENT (No such file or directory)
faccessat(AT_FDCWD, "/keybase/private/tonyarkles/package.json", F_OK) = -1 ENOENT (No such file or directory)
faccessat(AT_FDCWD, "/keybase/private/tonyarkles/gulpfile.js", F_OK) = -1 ENOENT (No such file or directory)
faccessat(AT_FDCWD, "/keybase/private/tonyarkles/Gruntfile.js", F_OK) = -1 ENOENT (No such file or directory)
faccessat(AT_FDCWD, "/keybase/private/tonyarkles/bower.json", F_OK) = -1 ENOENT (No such file or directory)
faccessat(AT_FDCWD, "/keybase/private/tonyarkles/composer.json", F_OK) = -1 ENOENT (No such file or directory)
faccessat(AT_FDCWD, "/keybase/private/tonyarkles/Cargo.toml", F_OK) = -1 ENOENT (No such file or directory)
faccessat(AT_FDCWD, "/keybase/private/tonyarkles/mix.exs", F_OK) = -1 ENOENT (No such file or directory)
faccessat(AT_FDCWD, "/keybase/private/tonyarkles/stack.yaml", F_OK) = -1 ENOENT (No such file or directory)
faccessat(AT_FDCWD, "/keybase/private/tonyarkles/info.rkt", F_OK) = -1 ENOENT (No such file or directory)
faccessat(AT_FDCWD, "/keybase/private/tonyarkles/TAGS", F_OK) = -1 ENOENT (No such file or directory)
faccessat(AT_FDCWD, "/keybase/private/tonyarkles/GTAGS", F_OK) = -1 ENOENT (No such file or directory)
faccessat(AT_FDCWD, "/keybase/private/rebar.config", F_OK) = -1 ENOENT (No such file or directory)
faccessat(AT_FDCWD, "/keybase/private/project.clj", F_OK) = -1 ENOENT (No such file or directory)
faccessat(AT_FDCWD, "/keybase/private/build.boot", F_OK) = -1 ENOENT (No such file or directory)
faccessat(AT_FDCWD, "/keybase/private/SConstruct", F_OK) = -1 ENOENT (No such file or directory)
faccessat(AT_FDCWD, "/keybase/private/pom.xml", F_OK) = -1 ENOENT (No such file or directory)
faccessat(AT_FDCWD, "/keybase/private/build.sbt", F_OK) = -1 ENOENT (No such file or directory)
faccessat(AT_FDCWD, "/keybase/private/gradlew", F_OK) = -1 ENOENT (No such file or directory)
faccessat(AT_FDCWD, "/keybase/private/build.gradle", F_OK) = -1 ENOENT (No such file or directory)
faccessat(AT_FDCWD, "/keybase/private/Gemfile", F_OK) = -1 ENOENT (No such file or directory)
faccessat(AT_FDCWD, "/keybase/private/requirements.txt", F_OK) = -1 ENOENT (No such file or directory)
faccessat(AT_FDCWD, "/keybase/private/setup.py", F_OK) = -1 ENOENT (No such file or directory)
faccessat(AT_FDCWD, "/keybase/private/tox.ini", F_OK) = -1 ENOENT (No such file or directory)
faccessat(AT_FDCWD, "/keybase/private/package.json", F_OK) = -1 ENOENT (No such file or directory)
faccessat(AT_FDCWD, "/keybase/private/gulpfile.js", F_OK) = -1 ENOENT (No such file or directory)
faccessat(AT_FDCWD, "/keybase/private/Gruntfile.js", F_OK) = -1 ENOENT (No such file or directory)
faccessat(AT_FDCWD, "/keybase/private/bower.json", F_OK) = -1 ENOENT (No such file or directory)
faccessat(AT_FDCWD, "/keybase/private/composer.json", F_OK) = -1 ENOENT (No such file or directory)
faccessat(AT_FDCWD, "/keybase/private/Cargo.toml", F_OK) = -1 ENOENT (No such file or directory)
faccessat(AT_FDCWD, "/keybase/private/mix.exs", F_OK) = -1 ENOENT (No such file or directory)
faccessat(AT_FDCWD, "/keybase/private/stack.yaml", F_OK) = -1 ENOENT (No such file or directory)
faccessat(AT_FDCWD, "/keybase/private/info.rkt", F_OK) = -1 ENOENT (No such file or directory)
faccessat(AT_FDCWD, "/keybase/private/TAGS", F_OK) = -1 ENOENT (No such file or directory)
faccessat(AT_FDCWD, "/keybase/private/GTAGS", F_OK) = -1 ENOENT (No such file or directory)
faccessat(AT_FDCWD, "/keybase/rebar.config", F_OK) = -1 ENOENT (No such file or directory)
faccessat(AT_FDCWD, "/keybase/project.clj", F_OK) = -1 ENOENT (No such file or directory)
faccessat(AT_FDCWD, "/keybase/build.boot", F_OK) = -1 ENOENT (No such file or directory)
faccessat(AT_FDCWD, "/keybase/SConstruct", F_OK) = -1 ENOENT (No such file or directory)
faccessat(AT_FDCWD, "/keybase/pom.xml", F_OK) = -1 ENOENT (No such file or directory)
faccessat(AT_FDCWD, "/keybase/build.sbt", F_OK) = -1 ENOENT (No such file or directory)
faccessat(AT_FDCWD, "/keybase/gradlew", F_OK) = -1 ENOENT (No such file or directory)
faccessat(AT_FDCWD, "/keybase/build.gradle", F_OK) = -1 ENOENT (No such file or directory)
faccessat(AT_FDCWD, "/keybase/Gemfile", F_OK) = -1 ENOENT (No such file or directory)
faccessat(AT_FDCWD, "/keybase/requirements.txt", F_OK) = -1 ENOENT (No such file or directory)
faccessat(AT_FDCWD, "/keybase/setup.py", F_OK) = -1 ENOENT (No such file or directory)
faccessat(AT_FDCWD, "/keybase/tox.ini", F_OK) = -1 ENOENT (No such file or directory)
faccessat(AT_FDCWD, "/keybase/package.json", F_OK) = -1 ENOENT (No such file or directory)
faccessat(AT_FDCWD, "/keybase/gulpfile.js", F_OK) = -1 ENOENT (No such file or directory)
faccessat(AT_FDCWD, "/keybase/Gruntfile.js", F_OK) = -1 ENOENT (No such file or directory)
faccessat(AT_FDCWD, "/keybase/bower.json", F_OK) = -1 ENOENT (No such file or directory)
faccessat(AT_FDCWD, "/keybase/composer.json", F_OK) = -1 ENOENT (No such file or directory)
faccessat(AT_FDCWD, "/keybase/Cargo.toml", F_OK) = -1 ENOENT (No such file or directory)
```
That seems to happen... maybe every time I move my cursor? It's brutal. Turning off projectile for the single org-mode file I've got open on Keybase makes things buttery-smooth again.
