### ISSUE TITLE
Can't do anything withou keybase.1.log?

### ISSUE THREAD

**Issue by paulehoffman** [keybase/client#2057]
Greetings. Using the client on MacOS, no matter what I do, I get:
`ERROR protocol not found: keybase.1.log`
I installed from brew, so I did a `brew uninstall --force keybase` and `brew install keybase`, but the problem persists. Clues?

**Comment by maxtaco** [comment]
Shoot, we thought we fixed this one.  Can you do a `keybase -d status` and a `keybase -d version`?

You can likely solve this issue via `pkill keybase`

**Comment by paulehoffman** [comment]
`# keybase -d status
07:16:23.773437 ▶ [DEBU keybase json.go:50] 001 + loading config file: /Users/paul.hoffman/Library/Application Support/Keybase/config.json
07:16:23.773559 ▶ [DEBU keybase json.go:78] 002 - successfully loaded config file
07:16:23.775041 ▶ [DEBU keybase ui.go:451] 003 Setting GPG_TTY to /dev/ttys003
07:16:23.775072 ▶ [DEBU keybase globals.go:205] 004 Keybase CLI 1.0.9-0
07:16:23.775083 ▶ [DEBU keybase globals.go:205] 005 - Built with go1.5.3
07:16:23.775089 ▶ [DEBU keybase globals.go:205] 006 - Visit https://keybase.io for more details
07:16:23.775107 ▶ [DEBU keybase main.go:120] 007 + configureProcesses
07:16:23.775125 ▶ [DEBU keybase install_osx.go:479] 008 + AutoInstall for launchd
07:16:23.775165 ▶ [DEBU keybase install_osx.go:492] 009 | already installed at /Users/paul.hoffman/Library/LaunchAgents/homebrew.mxcl.keybase.plist
07:16:23.775178 ▶ [DEBU keybase install_osx.go:481] 00a - AutoInstall -> false, <nil>
07:16:23.775186 ▶ [DEBU keybase main.go:186] 00b | After forks; newProc=false
07:16:23.775195 ▶ [DEBU keybase main.go:207] 00c + configureLogging
07:16:23.775218 ▶ [DEBU keybase socket_nix.go:23] 00d Dialing unix:/Users/paul.hoffman/Library/Caches/Keybase/keybased.sock
07:16:23.775866 ▶ [DEBU keybase main.go:209] 00e - configureLogging
07:16:23.775891 ▶ [DEBU keybase main.go:122] 00f - configureProcesses -> protocol not found: keybase.1.log
07:16:23.880384 ▶ [DEBU keybase globals.go:250] 010 Calling shutdown first time through
07:16:23.880500 ▶ [DEBU keybase login_state.go:897] 011 + Account "LoginState - Shutdown"
07:16:23.880559 ▶ [DEBU keybase login_state.go:899] 012 - Account "LoginState - Shutdown"
07:16:23.880581 ▶ [DEBU keybase globals.go:290] 013 exiting shutdown code=0; err=<nil>
07:16:23.880611 ▶ [ERRO keybase main.go:58] 014 protocol not found: keybase.1.log
# keybase -d version
07:16:32.102035 ▶ [DEBU keybase ui.go:451] 001 Setting GPG_TTY to /dev/ttys003
07:16:32.102087 ▶ [DEBU keybase globals.go:205] 002 Keybase CLI 1.0.9-0
07:16:32.102100 ▶ [DEBU keybase globals.go:205] 003 - Built with go1.5.3
07:16:32.102106 ▶ [DEBU keybase globals.go:205] 004 - Visit https://keybase.io for more details
07:16:32.102116 ▶ [DEBU keybase main.go:120] 005 + configureProcesses
07:16:32.102128 ▶ [DEBU keybase main.go:207] 006 + configureLogging
07:16:32.102136 ▶ [DEBU keybase main.go:216] 007 Disabling log forwarding
07:16:32.102142 ▶ [DEBU keybase main.go:209] 008 - configureLogging
07:16:32.102149 ▶ [DEBU keybase main.go:122] 009 - configureProcesses -> <nil>
Client:  1.0.9-0
07:16:32.102172 ▶ [DEBU keybase socket_nix.go:23] 00a Dialing unix:/Users/paul.hoffman/Library/Caches/Keybase/keybased.sock
Service: 1.0.7-0
07:16:32.211471 ▶ [DEBU keybase globals.go:250] 00b Calling shutdown first time through
07:16:32.211602 ▶ [DEBU keybase login_state.go:897] 00c + Account "LoginState - Shutdown"
07:16:32.211700 ▶ [DEBU keybase login_state.go:899] 00d - Account "LoginState - Shutdown"
07:16:32.211726 ▶ [DEBU keybase globals.go:290] 00e exiting shutdown code=0; err=<nil>
`
And `pkill keybase` worked.

**Comment by maxtaco** [comment]
It seems like your brew install failed to give you the most recent version. Can you confirm this hunch and send me a `keybase version`? Thanks

**Comment by paulehoffman** [comment]
`
# keybase version
Client:  1.0.9-0
Service: 1.0.9-0
# brew info keybase
keybase: stable 1.0.9-0 (bottled), HEAD
Command-line interface to Keybase.io
https://keybase.io/
/usr/local/Cellar/keybase/1.0.9-0 (4 files, 35.2M) *
  Poured from bottle
From: https://github.com/Homebrew/homebrew/blob/master/Library/Formula/keybase.rb
==> Dependencies
Build: go ✘
`

**Comment by maxtaco** [comment]
We have a much newer version if you update your brew database.  I believe the most recent version in brew is 1.0.13. Thanks!

**Comment by paulehoffman** [comment]
No, I gave you the brew info above. That's the latest they have.

**Comment by maxtaco** [comment]
if you run `brew update`, you get:

``` brew info keybase
keybase: stable 1.0.13-0 (bottled), HEAD
Command-line interface to Keybase.io
https://keybase.io/
Not installed
From: https://github.com/Homebrew/homebrew/blob/master/Library/Formula/keybase.rb
==> Dependencies
Build: go ✘
```

**Comment by paulehoffman** [comment]
My apologies. I was *sure* had done an update first. Now fixed. Thanks!
