### ISSUE TITLE
Stellar Airdrop qualification 

### ISSUE THREAD

**Issue by Wosiu3** [keybase/client#20589]
Hi although its been confirmed on app that ive met all conditions to qualify when I want to join the airdrop the message says "Sorry, you dont qualify"

Can yiu please check it

Wosiu thanks

![Screenshot_2019-10-23-17-29-46](https://user-images.githubusercontent.com/56981621/67528656-ebf72e00-f6b1-11e9-8ea3-e1cb29486967.png)

![Screenshot_2019-10-23-17-29-53](https://user-images.githubusercontent.com/56981621/67528676-fb767700-f6b1-11e9-8c1f-bcfd3f4941cd.png)

![Screenshot_2019-10-23-19-00-16](https://user-images.githubusercontent.com/56981621/67528728-121cce00-f6b2-11e9-8916-9f73ea59da34.png)

**Comment by Z86-tech** [comment]
hi, same issue here https://github.com/keybase/client/issues/20264

**Comment by dragononcrypto** [comment]
Likewse

**Comment by Wosiu3** [comment]
What likewse

**Comment by lewishatton** [comment]
Been having the same issue.

**Comment by nikoloskid** [comment]
Any fix!?
