### ISSUE TITLE
Stellar airdrop qualification 

### ISSUE THREAD

**Issue by Wosiu3** [keybase/client#20588]
Hi although its been confirmed on app that ive met all conditions to qualify when I want to join the airdrop the message says "Sorry, you dont qualify"

Can yiu please check it

Wosiu thanks
![Screenshot_2019-10-23-17-29-46](https://user-images.githubusercontent.com/56981621/67528289-054baa80-f6b1-11e9-9faf-c935a71971fb.png)

**Comment by revonoc** [comment]
Is this closed because it was fixed? If so, how? I'm having same issue
