### ISSUE TITLE
How to update keybase on Ubuntu?

### ISSUE THREAD

**Issue by pedro-roberto** [keybase/client#20627]
Have an version 2.13.0-20190104191034+69b3ee25b7 of keybase on Ubuntu but I don't find any option within the app to update it. 

When I try to run `/usr/bin/keybase update check` I get `Error finding updater path: Updater isn't supported on unix`. Google didn't help much too... Please help.

**Comment by heronhaye** [comment]
Can you run

```
apt-get update
apt-get upgrade keybase
```

?

**Comment by pedro-roberto** [comment]
yes, it worked. Thanks

**Comment by heronhaye** [comment]
@pedro-roberto Great. Latest version should be 4.7.
