### ISSUE TITLE
keybase fs sync show fails with ERROR method 'simpleFSSyncConfigAndStatus' not found in protocol 'keybase.1.SimpleFS'

### ISSUE THREAD

**Issue by pmantas** [keybase/client#20635]
Funtoo linux, keybase-4.7.0, /keybase path for kbfs turned off.

my log id: 7af16d602b0db78986539f1c

**Comment by strib** [comment]
Hi @pmantas it looks like your `kbfsfuse` binary is very out of date.  I'm not sure what distribution you're using with funtoo, but please make sure it's being built out of the keybase/client repo, in the `go/kbfs` subdirectory.  The old keybase/kbfs repo has been deprecated.

**Comment by pmantas** [comment]
Thanks, Funtoo is based on Gentoo and I used most recent keybase ebuild from Gentoo, but it turns out kbfs is built from separate ebuild which used the deprecated repo. I updated the keybase ebuild and 
keybase fs sync works now.
