### ISSUE TITLE
When will account resets be allowed again?

### ISSUE THREAD

**Issue by wjdp** [keybase/client#20653]
I haven't used keybase for a year or so and something is wrong with my paper key. I'm trying to reset my account but got the following a few weeks ago (still present):

![image](https://user-images.githubusercontent.com/1690934/67725496-84efb700-f9da-11e9-8f6a-ac5d2252e44e.png)

Any news on when we'll be able to recover accounts again?

**Comment by pzduniak** [comment]
How did you open this screen? I must've missed a button.

**Comment by heronhaye** [comment]
We've updated the link at https://keybase.io/#account-reset. You may need to clear your cache to see the new copy (Ctrl-Shift-R). Thanks for the report.

In any case, you should be able to start a reset by upgrading your app to Keybase 4.7 and trying to log in.

**Comment by wjdp** [comment]
Working, thanks!

![image](https://user-images.githubusercontent.com/1690934/67895110-d1113780-fb51-11e9-97ad-641d3e0293f4.png)
