### ISSUE TITLE
Cannot update or uninstall client

### ISSUE THREAD

**Issue by ftunholm** [keybase/client#20687]
Hi,

I have had Keybase installed on my work computer for a while. Since some week ago the company migrated all the machines to the company domain, I can't really tell what all the changes were.

Anyways, after the migration I get an error message while updating or uninstalling. I want to uninstall so that I can install it fresh.

![image](https://user-images.githubusercontent.com/8871986/67859694-86c19380-fb1c-11e9-8276-22f545e82f67.png)

Is there any workaround to get rid of the current installation?

Thanks!

**Comment by S-B99** [comment]
Download that specific MSI, and tell the installer where it is instead

**Comment by ftunholm** [comment]
Thank you, I will try to locate the that version of the installer, and it should do the trick.
