### ISSUE TITLE
No easy way to remove added users

### ISSUE THREAD

**Issue by privaterra** [keybase/client#2068]
Using the keybase GUI (on OS X) I added a keybase user to both my private and public space. Was able to test and confirm that sharing files with them worked.

While it is straightforward to add a user, there doesn't seem to be a way to remove the added user .

ie. I added created an entry for /keybase/private/rguerra,robertguerra - easily using the gui, but then don't know how to remove it (if needed).

Keybase GUI Version: 1.0.13-20160218170011+513e03d

**Comment by strib** [comment]
This should work in recent builds: `rmdir /keybase/private/rguerra,robertguerra`.  Please re-open if it doesn't.
