### ISSUE TITLE
Duplicate 'general' channel in team

### ISSUE THREAD

**Issue by xofer** [keybase/client#20693]
I have a team where I accidentally clicked to make it a "big team" (was a long time ago, so not sure exactly what that process was).

Now I have 2 `#general` channels, and both are treated as the main channel that cannot be deleted or renamed. I also occasionally see errors that complain about the channel being in use or something like that.

![image](https://user-images.githubusercontent.com/1231804/67871802-4c99c700-fb07-11e9-9b74-2fef07a62e50.png)

I'd prefer this to be a "small team" i.e. only one channel.

Anything I can do here to remove one of the channels (either one, doesn't matter)?

**Comment by joshblum** [comment]
Fixed in https://github.com/keybase/client/pull/20617 and resolved over chat.
