### ISSUE TITLE
Finder is having trouble copying to /keybase/public

### ISSUE THREAD

**Issue by RyanSinger** [keybase/client#2073]
https://www.dropbox.com/s/u4jfyu4jbmy8pd9/Screenshot%202016-02-19%2017.33.42.png?dl=0

/keybase/private works fine.

**Comment by RyanSinger** [comment]
Log id 6bac81d630ce53bf0acb031c

**Comment by strib** [comment]
Hi @RyanSinger: looks like you're trying to write `/keybase/public/bitcoin.pdf` directly.  In KBFS, subdirectories under `public` (and `private`) need to be named by the users with access to those folders.  So I think you should be writing to `/keybase/public/ryan_singer/bitcoin.pdf`.  Looks like that's what you did on the private side.

**Comment by RyanSinger** [comment]
You are correct.
