### ISSUE TITLE
Feature request: Groups

### ISSUE THREAD

**Issue by RyanSinger** [keybase/client#2074]
I would love the ability to have a private folder for my team on KBFS, instead of having to share folders bilaterally.

**Comment by malgorithms** [comment]
we agree. We've put a bunch of work spec'ing this out, although it will be later this year before we get to it. Group membership itself has to be auditable and without trusting the Keybase servers, so there's a lot to do to get it right. We also want to support non-public group membership, so an organization can have members without the general public knowing. 

In the meantime, you'll need to do something ugly like:

/keybase/private/you,friend1,friend2,friend3/

and maybe symlink to that in your own folder for convenience (`workfolder -> /keybase/private/you,p1,p2,p3,p4` or similar). The problem with this is that if your team changes you'll need to move the files. There'll be a much better story when we implement groups.

**Comment by briandant** [comment]
@malgorithms: Is there a way to follow the progress on the "groups" feature?

**Comment by maxtaco** [comment]
Good q! We've been testing, and almost all of the code is in master, but just feature-flagged off. We're shooting for early fall for a CLI-driven admin experience, with chat and KBFS support. In general the code is in `go/teams`.  We had a ton of JIRA docs on how it works under the hood, but need to make them public too.

**Comment by briandant** [comment]
Excellent, thanks for the update! cc @mrgnr @johnbaldwin

**Comment by styfle** [comment]
https://keybase.io/docs/teams/index

**Comment by maxtaco** [comment]
Closed!

**Comment by z0mbix** [comment]
Thanks so much, you all rock!
