### ISSUE TITLE
can't  join the Airdrop with all proved requirements 

### ISSUE THREAD

**Issue by jan1972** [keybase/client#20755]
I am qualified with all requirements for the Airdrop of Stellar and when I press: Become a lucky airdrop --> I get Sorry, you are not qualified to join.
No code or details on this error massage

Please help. Thanks 

![Screenshot_20191101-090013_Keybase](https://user-images.githubusercontent.com/57285183/68068715-3afb2e00-fd58-11e9-98ba-20057047a192.jpg)
![Screenshot_20191101-090021_Keybase](https://user-images.githubusercontent.com/57285183/68068716-3b93c480-fd58-11e9-9bde-a6a4d6d2fb79.jpg)

**Comment by flyingcactuscloud** [comment]
Same here. OnePlus 7 Pro, Oxygen OS 10.0.1 / Android 10, Keybase Version 4.7.2

Says I'm qualified but fails the same way like jan1972 explained

**Comment by revonoc** [comment]
Me too! No VPN or anything and I can't join - really hoping they get back to us before Nov 15!

**Comment by jan1972** [comment]
Whats wrong with GitHub, no support, no answers, no help!!!!

**Comment by flyingcactuscloud** [comment]
> Whats wrong with GitHub, no support, no answers, no help!!!!

Stay calm, it is still weekend!

**Comment by MickHardins** [comment]
Same as  #20264

**Comment by droslean** [comment]
@strib @patrickxb @maxtaco @chrisnojima 

Are you guys working on the fix?

**Comment by droslean** [comment]
@mmaxim @songgao

**Comment by jan1972** [comment]
Whats this?

closed with no comment and not solved???

Still have the same issue.
