### ISSUE TITLE
Keybase Airdrop, left by error and now i can't rejoin.

### ISSUE THREAD

**Issue by manugm05** [keybase/client#20769]
Don't really know why but I qualify and the system do not let me participate in the airdrop.

my log id: 9e54de3521ca46c9d865261c

**Comment by Ci1912** [comment]
Same issue here,
the UI design is not good.
there is not even a warning pop up to stop my fat finger.

I was no longer qualified to join after left.
There should be an instant re-join for the users who were qualified in the airdrop.

uid: 3f934275bc17b0686be9835e2d3e3519
username: clydez

**Comment by khrispe** [comment]
Hello,
Sorry to comment this bug, I don't know the resolution. One of my contact is reproducing it (he does not speak english), keybase contact: thomato.
Thanks for your help.
