### ISSUE TITLE
Join airdrop please

### ISSUE THREAD

**Issue by creepingdoubt** [keybase/client#20760]
I'm trying to join the Stellar airdrop for Keybase, and when I get to the screen with 3 checkmarks it says I qualify, but when I click through, it says I am not qualified.
![keybase airdrop 1](https://user-images.githubusercontent.com/57311123/68081444-63704000-fdcb-11e9-9b19-9193eacd6fbc.PNG)
![keybase airdrop 2](https://user-images.githubusercontent.com/57311123/68081447-69feb780-fdcb-11e9-9069-9f11238f290c.PNG)

I'm hoping to resolve this before the Nov 15 airdrop, please let me know if there is something else I need to complete or do in order to qualify.  

my log id: 7862ad60487067732cc4ed1c

Thanks!!

**Comment by MickHardins** [comment]
I have the same problem. Any Idea on how to solve it?

**Comment by wiiboksing** [comment]
I have the same problem too. I don't know how to solve this please help me solve this before 15 Nov.
