### ISSUE TITLE
Australia phone verification Continue Button gray out

### ISSUE THREAD

**Issue by Dion-Shi** [keybase/client#20763]
I am located in Australia, one of my friend told me about this awesome app.

When I tried to register my phone number (the carrier is Telstra) using keybase windows app, the continue button is gray out, but I tried to enter my friend's or my partner's number (same carrier as Telstra), the button turns green, I've been using my number for years, not sure what's going on. 

Please see image below:
![phone not works](https://user-images.githubusercontent.com/11415721/68096337-c2cd6d80-fefb-11e9-9543-5dce6fc29580.png)

![phone works](https://user-images.githubusercontent.com/11415721/68096343-c95be500-fefb-11e9-80de-20e5c1e9b45c.png)

**Comment by heronhaye** [comment]
Sorry about that. If you type your number on https://catamphetamine.github.io/libphonenumber-js/, does it show up as "Valid"?

**Comment by Dion-Shi** [comment]
> Sorry about that. If you type your number on https://catamphetamine.github.io/libphonenumber-js/, does it show up as "Valid"?

Thanks for your reply, the Valid show up as false. Please see image below. I've been using this number for years, and I used it to verify my bank account, gmail, fb and twitter.  

![phone failed](https://user-images.githubusercontent.com/11415721/68166406-02549200-ffae-11e9-81f7-ffdc29c46011.png)

**Comment by NycRonz01** [comment]
Doesn't work for me as well, my number is 0483580xxx, seems like libphonenumber-js doesn't recognise mobile starts with 0483.

**Comment by heronhaye** [comment]
Okay, we just pushed out a new Linux nightly build with the fix. You can get it here: https://keybase.io/docs/linux-user-guide#nightly-builds.
Otherwise, we will do a full release sometime this week, so you could wait for that instead. Thanks!

**Comment by Dion-Shi** [comment]
Works now, great job.
