### ISSUE TITLE
Keybase client no longer functions after update (not entirely sure on cause)

### ISSUE THREAD

**Issue by Tristor** [keybase/client#2086]
I updated from 1.0.9 to 1.0.13 through Homebrew and the client is no longer functional.

From https://keybase.io/tristor/devices you can see that I have Home MBA (the device I'm having the issue on) previously logged in and authenticated.

When I run `keybase login` I get 

```
❯ keybase login
▶ WARNING device id mismatch session <-> env
How would you like to sign this install of Keybase?

(1) Use an existing device
(2) Use a paper key
(3) Use my Keybase passphrase
(4) Use GPG
```

If I choose to Use GPG (as I did originally), after selecting my keypair it says

```
▶ ERROR LoginProvision: ppStream() -> nil PassphraseStreamCache
```

If I choose to use my Keybase passphrase, after entering it successfully it says

```
▶ ERROR in Login

Sorry, your account is already established with a PGP public key, but this
utility cannot access the corresponding private key. You need to prove
you're you. We suggest one of the following:

   - install GPG and put your PGP private key on this machine and try again
   - reset your account and start fresh: https://keybase.io/#account-reset
   - go back and provision with another device or paper key

```

It basically is acting like the private key isn't present.  To complicate things further, my configuration is setup so I have the master keypair on this system, but a set of subkeys which are stored on a Yubikey4 acting as an OpenPGP card.  My preferred signing key is on the Yubikey and it must be inserted to sign emails/other keys/etc.  During all of the above I had the Yubikey inserted, but it did not appear to be accessing it.

Bouncing the service does appear to get me somewhat further, but then I get two things that happen:

1) after providing my Keybase passphrase it says my device already exists, so I have to provide a new device name (which would make a duplicate...)

2) It goes to sign, pops the PIN entry dialog for my Yubikey, but then says it fails to find the key which is present on the card.

```
▶ ERROR bad signature: Can't find a key for 01d412181e294e72: No keys match the given key IDs (error 1002)
```

```
❯ gpg --card-status
Application ID ...: D2760001240102010006041393530000
Version ..........: 2.1
Manufacturer .....: Yubico
Serial number ....: 04139353
Name of cardholder: Tyler Duzan
Language prefs ...: en
Sex ..............: male
URL of public key : http://keypolicy.tristor.ro/key/tyler.duzan.asc
Login data .......: [not set]
Signature PIN ....: forced
Key attributes ...: 2048R 2048R 2048R
Max. PIN lengths .: 127 127 127
PIN retry counter : 3 0 3
Signature counter : 28
Signature key ....: 7474 1008 E285 56D3 11DC  FFB6 01D4 1218 1E29 4E72
      created ....: 2016-01-10 03:09:06
Encryption key....: A6C6 6AD5 B861 89E2 A44A  2B63 C42D 9CF2 52F3 DC32
      created ....: 2016-01-10 02:49:27
Authentication key: F8AA C331 C23F 1CB2 E67F  A763 BC15 4A95 6EA5 EB5D
      created ....: 2016-01-10 03:10:04
General key info..: pub  2048R/0x01D412181E294E72 2016-01-10 Tyler Duzan <tristor@gmail.com>
sec   8192R/0x191597E1CB676F29  created: 2014-02-25  expires: 2019-02-24
ssb   8192R/0x14D3F980FD9BE420  created: 2014-02-25  expires: 2019-02-24
ssb   8192R/0x16BF8FC85CA73DEF  created: 2014-02-25  expires: 2019-02-24
ssb   4096R/0xB3767C698A3C3871  created: 2016-01-07  expires: 2018-01-06
ssb>  2048R/0xC42D9CF252F3DC32  created: 2016-01-10  expires: 2017-01-09
                      card-no: 0006 04139353
ssb>  2048R/0x01D412181E294E72  created: 2016-01-10  expires: 2017-01-09
                      card-no: 0006 04139353
ssb>  2048R/0xBC154A956EA5EB5D  created: 2016-01-10  expires: 2017-01-09
                      card-no: 0006 04139353
scdaemon[79611]: updating slot 0 status: 0x0000->0x0007 (0->1)
```

The signing keypair is obviously present on the card, seen via GPG2, and is available for Keybase to use...  I didn't have any issues with the prior version.

Any thoughts on what might cause this or are there any steps you'd like me to take to get you more information for this issue report?

Thanks.

**Comment by maxtaco** [comment]
Sorry you hit so many issues.  I can take a look.  Can you do a  `keybase log send` from the machine that's presenting you this problem (I believe Home MBA).. 

Let's ignore the yubikey/GPG issues for now, which are the bane of my existence..

Thanks

**Comment by Tristor** [comment]
Thanks, I submitted a log.

```
------------
Success! Your log ID is:

  f99f6c9acf42da89bed5981c

```

**Comment by patrickxb** [comment]
Hi @Tristor I've looked through your log.  

First, to clarify:  everything was working for you on Home MBA with 1.0.9 and after an upgrade to 1.0.13 via brew when you typed `keybase login` it gave you the provisioning menu that you pasted above (the first one with the `device id mismatch` in it)?  You shouldn't have seen that interface on Home MBA after an upgrade, so I think something must have happened to your config file.  In the log you sent, there is nothing about the update from 1.0.9 to 1.0.13, so I can't see what happened there.  If you'd like, we can try to manually rewrite it and thus restore your access using Home MBA device.

Second, I see you trying to provision Home MBA-2 via gpg in the log.  It looks like you are selecting PGP Key 191597E1CB676F29 to provision with, but the result of the yubikey dialog is that it is signing the provisioning statement with PGP Key 01D412181E294E72, which is unknown to keybase.  You used 191597E1CB676F29 to provision Work rMBP.  If you'd like to continue provisioning Home MBA-2, is it possible via gpg/yubikey to select 191597E1CB676F29 for signing?  Or you could choose a different provisioning method.  You provisioned Home MBA via Work rMBP, so if you have access to Work rMBP you could use that, or your paper key would also work.

Let me know if you are interested in trying to restore your config file for Home MBA.

Sorry for the issues.

**Comment by Tristor** [comment]
I'm sorry it took me so long to reply.  GPG internally uses your newest secret subkey marked as a signing key to sign things when given the keyid of the master key.  The keyid provided is the keyid of the master key, there is a signing subkey on my Yubikey device.  AFAIK it is not possible for me to specifically indicate to sign with the master key rather than the subkey, and I'm not sure that I would want to do so in any case.

The background you provided does help significantly.  I do now recall that I had issues getting the Yubikey signing to work previously so enrolled this device by using my Work rMBP.  So, I assume I could do the same thing again to re-enroll.

All that however doesn't explain why it lost my device key or the device key became corrupted after the upgrade, because I shouldn't have to reauthenticate this device in theory if I'm understanding how device keys work correctly.

Let me know what steps I should take next if I'd like to try to restore my original device key for Home MBA?

**Comment by neutrinog** [comment]
I'm having a similar issue.

I've already proven a few identities and used my keys in the Nylas N1 client. Everything works fine except when I attempt to log into the keybase app it says that the corresponding private key is not on my machine. However I've double checked my private key finger print and it matches.

Note:
When I run `keybase login` it immediately asks for a username or email. It does not give me any other options. After I give my username it opens a dialog to receive my password. After I submit the password it gives me the error:

```
ERROR Sorry, your account is already established with a PGP public key, but this
utility cannot access the corresponding private key on this machine.
This is the fingerprint of the PGP key in your acocunt:

[finger print]

You need to prove you're you. We suggest one of the following:

   - put one of the PGP private keys listed above on this machine and try again
   - reset your account and start fresh: https://keybase.io/#account-reset
```

I am on Debian 8.

my log id: 2f922f6245c01d4ec90d9e1c

**Comment by maxtaco** [comment]
Can you run this command: `/usr/bin/gpg2 --no-tty --with-colons --fingerprint -K` ? It's what our client does to figure out which private GPG keys are on your machine. It doesn't output the keys, just the public fingerprints...

**Comment by neutrinog** [comment]
ah. There is no output. However if I run the command with `gpg` rather than `gpg2` it outputs the correct fingerprint.

**Comment by maxtaco** [comment]
Try this:

```
keybase config set gpg.command gpg
```

And then reattempt your login

**Comment by neutrinog** [comment]
still the same error.

**Comment by maxtaco** [comment]
Try a `keybase ctl restart` and then try one more time.  Then send a log again if it's still failing.

**Comment by neutrinog** [comment]
here's my log id `172f6bcc44127930e86d341c`

**Comment by maxtaco** [comment]
Let's try one last thing:

```
keybase config set gpg.command `which gpg`
```

And then let me see the output of:

```
keybase config get gpg.command
```

**Comment by neutrinog** [comment]
the output is `/usr/bin/gpg`

**Comment by maxtaco** [comment]
Ok cool, try `keybase login` one last time?

**Comment by neutrinog** [comment]
great! that worked. Thanks a lot.

**Comment by maxtaco** [comment]
Cool. We just needed the fullpath on the alternate GPG.  No restart required. Thank you.
