### ISSUE TITLE
OS X notifications are way too chatty

### ISSUE THREAD

**Issue by joeshaw** [keybase/client#2088]
This is obviously subjective, but I'm finding the OS X notifications to be excessive.

I am getting a ton of "Logged in to Keybase as: joeshaw" notifications.  While my machine is asleep, I get one roughly every hour -- I assume when the machine wakes up to check for various things.  These stack up.

Here's a screenshot of my notification area from today:

![](https://www.dropbox.com/s/42mzvh5ihpo98rm/Screenshot%202016-02-22%2010.27.08.PNG?dl=1)

I think you should do away with this particular notification entirely.  It's not very informative and requires no action from me.  It doesn't deserve to interrupt me.  A better notification would be if logging in fails, because then I need to take action to fix things.

**Comment by JustinTulloss** [comment]
I came here to file this same bug. It's real irritating. I know I'm logged in, that's not news.

**Comment by cjb** [comment]
Just wanted to leave a quick comment saying that we agree and have a fix (only notifying when you weren't logged in before) scheduled for our next sprint.  Thanks for the report!
