### ISSUE TITLE
The application Keybase has closed unexpectedly

### ISSUE THREAD

**Issue by alancwoo** [keybase/client#20884]
Every time I open the keybase app I am prompted with this message, perhaps it isn't quitting gracefully on shutdown or reboot?

The details state:
> Keybase crashed with signal 5

![image](https://user-images.githubusercontent.com/1481890/68533514-1fea7880-036d-11ea-9425-0793ce227d5f.png)

Ubuntu 19.10
Keybase 4.8.0-20191021160049+e5fcade9ba

**Comment by heronhaye** [comment]
Sorry about that. This is a known issue with Electron 6: https://github.com/electron/electron/issues/20509. You could add your debug logs to that issue.

**Comment by alancwoo** [comment]
I see, thanks @heronhaye I'll close this as a duplicate in the meantime then.
