### ISSUE TITLE
Cant join airdrop error 4207

### ISSUE THREAD

**Issue by aizhiman** [keybase/client#20896]
Wondering if anyone knows a fix for this. I have been trying to join the airdrop since it was announced. I have 3 devices and 3 private keys and I get all 3 green checkmarks. When i click "become airdropee" it says "sorry you are not able to join airdrop"

I dont know what to do next, I tried reinstalling the app and trying a different wifi signal incase i was blocked for some reason. 

I just want to get the airdrop man...

**Comment by mheppner** [comment]
@maxtaco any reason why all of these related issues keep getting closed?
