### ISSUE TITLE
input/output error while reading my public kbfs directory

### ISSUE THREAD

**Issue by psychoweb** [keybase/client#2090]
I cannot perform read/write operations on my public directory:

`ls /mnt/keybase/public/psychoweb
ls: impossibile aprire la directory '/mnt/keybase/public/psychoweb': Errore di input/output`

`touch /mnt/keybase/public/psychoweb/test
touch: impossibile fare touch di '/mnt/keybase/public/psychoweb/test': Errore di input/output`

kbfs complains that it "Could not find key with kid" (from debug logs).

Also, it seems that other users cannot see my public directory content either using the keybase client, although my sample file is visible through https://keybase.pub/psychoweb/hello.txt

my log id: d5f91f770b657a15967a1d1c

**Comment by cjb** [comment]
That's odd, your logs didn't show up.  Are you storing them in a non-standard place?  Can you symlink $HOME/.config/keybase to that place, maybe, to allow log send to work?

**Comment by psychoweb** [comment]
`keybase log send` gave this warning:

`WARNING error opening log "/home/psy/.cache/keybase/keybase.kbfs.log": open /home/psy/.cache/keybase/keybase.kbfs.log: no such file or directory`

`WARNING error opening log "/home/psy/.cache/keybase/Keybase.app.log": open /home/psy/.cache/keybase/Keybase.app.log: no such file or directory`

I `touch`-ed the two files but they have not been written. The best I could get was generating a raw one from the command `kbfsfuse -debug /mnt/keybase/ 2>> kbfs.txt`
[kbfs.txt](https://github.com/keybase/client/files/141093/kbfs.txt)

**Comment by strib** [comment]
Why is KBFS mounted at `/mnt/keybase` instead of `/keybase`?  How are you running the program?  Right now it's really only designed to be run with the `run_keybase` command, which uses `/keybase`.

**Comment by strib** [comment]
There are a few environment variables that are set by the `run_keybase` script that are required for proper usage, such as `KEYBASE_RUN_MODE`.

**Comment by psychoweb** [comment]
Thank you for the hints strib, since its initial release i used the kbfsfuse standalone program, and in fact ran smoothly until now.

I did like you said (with `run_keybase`), and now the daemon did populate some logs, my log id is 0eb2cb38622ef1b0cf618e1c .

Is some of you able to read my user's directory `/keybase/public/psychoweb/` ?

**Comment by psychoweb** [comment]
As an additional note, I don't have any problems reading other user's public directories, just mine.

**Comment by strib** [comment]
@psychoweb: no I can't read your directory either.  It looks like maybe you wrote to your directory with a device that later got revoked?  https://keybase.io/psychoweb/sigchain seems to imply that you reset your account recently, and haven't added any devices to it.

(Although strangely https://keybase.io/psychoweb/devices shows 3 active devices.  @malgorithms, why would the devices page show devices but the sigchain page wouldn't show anyway?)

Anyway, what is the history of your account?  Did you reset it before or after adding your devices?

**Comment by strib** [comment]
Ah, looks like you had a device `changme` (https://keybase.io/psychoweb/graph) which allocated your other devices and keys, and then you revoked `changeme`.  Which I guess explains why your sigchain looks empty but there are valid devices.  (But @malgorithms that still seems like a bug in the sigchain display to me.)

Unfortunately, as per the big yellow warning box on the kbfs download page, we don't currently support  writing to a KBFS folder and then later revoking the device that did the writing.  We are working on that now, but currently the only safe thing for us to do is not display the folder's contents.

If you want, we can reset the folder for you.  Just write me a note in our private folder `/keybase/private/psychoweb,strib` if you want that (or post something PGP-signed here).

**Comment by maxtaco** [comment]
Old devices should not show up after an account reset. I don't think they
do either.  Maybe there wasn't an account reset?

**Comment by malgorithms** [comment]
the sig chain looks empty due to a JS bug.

it appears to be a bug in the site's front end parsing of his sigchain (looking into it right now)...this could be a bug in the front end display code, or it could be the root of the problem - maybe a weird sigchain link.

**Comment by malgorithms** [comment]
I think there's a bug here that maybe there wasn't actually an account reset. here's what I'm seeing on the /sigchain page:

- This API only returns links starting at link 12: https://keybase.io/_/api/1.0/sig/get.json?compressed=true&uid=eecceac6dcde8e95605a8a429f5c5e19
- therefore the presentation JS thinks she/he did an account reset at link 12.
- all links have the same eldest key pointing back to link 1, both before and after link 12.
- this is causing all kinds of weirdness, because they continues to do things with links before 12, such as revocations

**Comment by malgorithms** [comment]
btw, here's the unprocessed full sigchain: https://keybase.io/psychoweb/chain

**Comment by psychoweb** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA256

@maxtaco: No account reset has been made, just a revocation of my "changeme" device I first logged into.
@strib: I understood. So, if I was to revoke my device, I'd have to back-up my files and delete them from my private/public folders? (for the time being, that is)
Also: yes, please, I'd like a reset of my folder.
-----BEGIN PGP SIGNATURE-----

wsFcBAEBCAAQBQJWy4sPCRDdv6CcYSrq1QAANowQAGEsyryHVWwNUtEnUeciWfCN
Num0dkFOq0rS4HZpE9+HRGMp7BFMeYJTYY7N7yyNJ0zra4hpl1DMvmbztemYem7d
Zpq3T4EkKdC4RNHCAibZdHF3OcQwFBRfpnBtgsrQItfet7mW/tXV5AS5Mi0yeND3
uQEk4o2S25fZ4netseUWoJI+VPl8LRfbKpPSK126jBZalMrVZGKZP0Gkfq2q5srJ
YxXi8DcQ3Cr9nxnKPGMWR9g+/DQghH2EqiJlUozLPjHwgzJhz5cqrLp4bxcIHHbs
Cd6x4pAbzUM9nOR4i8sVA/Nr5DiF6ft7HSbQiYGzMnEcmFsxpkJXQlKEa7eiV0et
FcGC22eqkBFHBVvmqxhAqj+8cmds0a+P74SdsM0rOIWQiDYm5ms/g2NFdgKZrzTd
u6lEsFIkr8E8HgSWNRDafzVfUqAvdfLDjGZsPJlcX8pOQCHqPMWZD/XNxbCam5Fx
fsIxJSc1whqhGAmhoJm82XXV1asI7EFUHRvcE08CaRDbABTLTn85kviVXsizX4N3
Mo1Dpj3knjl+JsanjyW/6LDPDW7x8MQBiH+jwcfF4eA3goFibTBmUTmFPEjnMkdb
S2pKZK5B1/lMXOrTlB8lf9thJuogrlJphtN4py0PqCD//jTN7580QDLQ2qIkTXcy
C3xsXuH0Ro+1l7oZyAT7
=aNe0
-----END PGP SIGNATURE-----

**Comment by maxtaco** [comment]
Agreed, there was no sigchain reset.  A lot of links and kids were
individually reset though...

**Comment by malgorithms** [comment]
@maxtaco  I'm going to make an internal issue for the API not including any links before 12. Are we concluding this and the KBFS issue are separate?

**Comment by maxtaco** [comment]
I think all of those links are revoked..

**Comment by maxtaco** [comment]
Hmm, if you take out `compressed=true` in the URL, you get the full set of
chainlinks...

**Comment by malgorithms** [comment]
ok, got it, but the front end can't explain your signature chain if it doesn't have a clear path to your currently active keys, proofs, right? I would assume it can only prune dead ends?

**Comment by strib** [comment]
@psychoweb: I've asked for your folder to be reset to empty, I'll let you know when that happens.

For now, revoking the last device that wrote to a folder leaves that folder unusable.  So I'd recommend a hack: before you revoke device A, use a different device B to write to the folder first, to make sure the last writer wasn't device A.  Then you are free to revoke device A.  The history of the folder will still look a bit messed up but the folder will be usable.

**Comment by maxtaco** [comment]
Right, so maybe there is a bug with `compressed=true`

**Comment by maxtaco** [comment]
(used only on for this purpose BTW)

**Comment by malgorithms** [comment]
@maxtaco  ok, making a ticket separate from this KBFS issue.

**Comment by strib** [comment]
@psychoweb: your public folder is now reset.  Can you please do a couple of writes to it, in order to bring its revision number back to what other clients might be expecting?  For example, something stupid like this would work:

```
mkdir -p /keybase/public/psychoweb/a/b && rm -rf /keybase/public/psychoweb/a
```

**Comment by psychoweb** [comment]
@strib: done, it worked flawlessly, thank you

**Comment by strib** [comment]
Great.  I'll close this out then.  They are tracking the sigchain display bug somewhere else.

**Comment by psychoweb** [comment]
One more issue I found (maybe related to this, if not I can open a new one):

Although everything is working from the command line, the https://keybase.pub/psychoweb/ link still lists (and displays) my old directory content.

Is this temporary?

**Comment by cjb** [comment]
@psychoweb I just restarted the service on keybase.pub, I think you're good now.

**Comment by strib** [comment]
Ah sorry.  The problem was probably that I didn't ask you to do enough writes to the new folder.  The protocol doesn't currently expect folders to be reset, and keeps track of the number of revisions it has seen.  Each client (including keybase.pub) keeps track of the latest revision number it has seen, and only pulls in changes with bigger revision numbers.  So it could be that the hacky write I asked you to do above wasn't enough to give your new folder a bigger revision number than it had before.  Sorry about that, I should have been more careful.
