### ISSUE TITLE
Stellar Lumen Airdrops 

### ISSUE THREAD

**Issue by Mickoski** [keybase/client#20946]
Hi Admin, I write to you to inquire about the status of the stellar Lumen Airdrops on keybase.io, I've done the necessary steps to qualify but when I click on "check to see if you are qualified" I get the message back "sorry you're not qualified to join" does this affect me getting the Lumens during the Airdrop? Thanks in advance as I await your response. 
![IMG-20191113-WA0028](https://user-images.githubusercontent.com/39128284/68758033-53e3c900-060d-11ea-8bdd-ce7545a49118.jpg)

**Comment by growbitcoin** [comment]
Phone no
 Is verified but airdrop show not verifed mark in front of mobile number is there any bug?

**Comment by Mickoski** [comment]
No bug. Kindly create two paper keys under device in your keybase app then check if you are qualified again

**Comment by growbitcoin** [comment]
is this restricted in some country?

**Comment by Mickoski** [comment]
Yes boss.
https://keybase.io/a/i/r/d/r/o/p/spacedrop2019

Check the list of countries

Mickoski

**Comment by growbitcoin** [comment]
<img width="960" alt="Untitled" src="https://user-images.githubusercontent.com/36338462/69011834-c26db180-0994-11ea-8399-3210ba68e843.png">
<img width="576" alt="Untitled11" src="https://user-images.githubusercontent.com/36338462/69011853-02349900-0995-11ea-8236-d04235ff3cf3.png">
why this prbm now

**Comment by Mickoski** [comment]
Not the slightest idea or probably rules weren't abide by

Mickoski

**Comment by Mickoski** [comment]
I got same issue too but I think I know why mine occurred.

**Comment by TechTronixx** [comment]
> I got same issue too but I think I know why mine occurred.

Any fix or update any sort for this ?

**Comment by Mickoski** [comment]
Delete the number you used in verifying the account earlier, add a
different number and verify it. Then join the Airdrop again. You'll be
qualified.

Mickoski
