### ISSUE TITLE
problem with airdrop keybase

### ISSUE THREAD

**Issue by yheryana** [keybase/client#20965]
Hi Admin, I want to ask about the status of the Lumen Airdrops star on keybase.io, I have taken the necessary steps to qualify but when I click "check to see if you are eligible" yes I am eligible and when I continue  I get a message back "Sorry you are not eligible to join".  Can Mr. Admin explain what is lacking in my keybase account?
![Screenshot_2019-11-14-08-20-57-612_io keybase ossifrage](https://user-images.githubusercontent.com/42206050/68818858-f7d67e80-06b8-11ea-91e0-b095f688c81b.png)
![Screenshot_2019-11-14-08-21-01-458_io keybase ossifrage](https://user-images.githubusercontent.com/42206050/68818866-fd33c900-06b8-11ea-9f3c-66452823af5b.png)

**Comment by Kboom21** [comment]
Please, I met the requirements to join the airdrop, and it tells me that I am not eligible. And the option to join the airdrop disappeared again, you can explain and check my account. : cryptolunatic0o@gmail.com that is my email registered in the account.

**Comment by periurium** [comment]
These issues seem to stem from Phone numbers, It won't allow VoIP numbers (For example Google Voice Numbers or other texting apps) and numbers can only be used once. That is what is being used to verify accounts. I recommend double checking on such.

**Comment by inate77** [comment]
Having same issue

**Comment by inate77** [comment]
![4E985C9B-CA52-4323-8C9F-D7E1EB88447B](https://user-images.githubusercontent.com/55263343/68923090-4b38e300-0732-11ea-960e-10f7dfdf1261.png)
![A9321ED3-242C-4864-9874-FDE8F87B2632](https://user-images.githubusercontent.com/55263343/68923092-4b38e300-0732-11ea-8fc2-e6ca5f75f9ce.png)

**Comment by inate77** [comment]
inate77

**Comment by hiken08** [comment]
Same with me..i dont know why it happen..so please help us

**Comment by AliciaLombarte** [comment]
Hi, i've the same problem. Do you know if there's a solution?

**Comment by ismailelk** [comment]
I have the same issue, username is 'ismelk'
