### ISSUE TITLE
Help!!!

### ISSUE THREAD

**Issue by MrLatoz14** [keybase/client#20971]
![Screenshot_2019-11-14-18-42-47-76](https://user-images.githubusercontent.com/45519101/68854435-9e993a00-070e-11ea-917d-725cd9e06f5b.png)
![Screenshot_2019-11-14-18-42-51-23](https://user-images.githubusercontent.com/45519101/68854447-a22cc100-070e-11ea-80cd-35850e315889.png)

hi admin why I can't follow airdrop what's the problem even though it's all right

**Comment by bazmanv** [comment]
please to trying for a day later... bcoz can't do same... airdrop+filter qualified user... this problem has begin at the first airdrop... so... I hope you will patient... many user in there wanna to join us... but its impossible to clear in one time... try to join again after 1 weeks of the end airdrop (22 Nov)... No way... when you are qualified... you will received our -email and our spacedrop will chat you in your keybase app... but you will received your first airdrop at 15 jan 2020... why 15 jan?... Our system and rules :)
