### ISSUE TITLE
Airdrop

### ISSUE THREAD

**Issue by jayan24007** [keybase/client#20996]
Hi,I mistakenly click leave airdrop,I joined 9october,plz accept me for airdrop,my keybase user name joy24007

**Comment by vipcaolan** [comment]
I participated in the airdrop round 1 (github link) and currently I have not received XLM, where do I send feedback? Contract me via : vipcaolan@gmail.com

**Comment by sjaaman** [comment]
Hola

**Comment by Kboom21** [comment]
Please help me. I did all the steps correctly to participate in the airdrop and I got a message that my account was not qualified ... Help me want to receive my bonus ..cryptolunatic0o@gmail.com 
User: kboom21
