### ISSUE TITLE
No longer in Airdrop 

### ISSUE THREAD

**Issue by inate77** [keybase/client#20994]
Curious as to why I’m no longer part of Airdrop and can’t get back in either. Email talon91977@gmail.com user name inate77 
![1632F0A1-8C8D-49DD-8E7C-5DD21DF8F314](https://user-images.githubusercontent.com/55263343/68923320-e6ca5380-0732-11ea-8559-c3836f21bd13.png)
![F7AAE175-E8B8-4EE4-B9BB-20074CB74FE4](https://user-images.githubusercontent.com/55263343/68923321-e6ca5380-0732-11ea-9f5d-0ae8ede91877.png)

**Comment by inate77** [comment]
Joined on October 9th

**Comment by sjaaman** [comment]
I have the same problem. Everything verified less twitter and gifhub I have problems to verify this, incompressible.

**Comment by inate77** [comment]
Yup I have updated removed and re added phone number, other forms of verifications as well uninstalled the app re installed tried going for December as well but still same message
