### ISSUE TITLE
Support ⌥↵ for inserting newlines into a chat message

### ISSUE THREAD

**Issue by cbeams** [keybase/client#21001]
When writing chat messages, it is frequently desirable to split a message up into multiple lines, e.g. some explanatory prose followed by a few lines of code fenced off with ```. In contexts where hitting the enter/return key submits the message immediately, it is a common convention to support pressing option-enter (⌥↵) to insert a newline and avoid actually sending the message. Slack works this way, for example, but Keybase does not. The only workaround I am aware of is to craft one's multiline messages in a text editor external to the Keybase chat client, then to copy and paste that content back into Keybase.

This is somewhat related to https://github.com/keybase/client/issues/18956.

**Comment by Avamander** [comment]
Does Shift+Enter not work?

**Comment by cbeams** [comment]
Shift+Enter *does* work! I thought sure I'd tried it before submitting this issue, but I was mistaken. Thank you. I'm closing this issue now.
