### ISSUE TITLE
cant register in airdrop, all checks are green

### ISSUE THREAD

**Issue by g13g13** [keybase/client#21005]
i am installing an app and then adding my phone from eligible country and then when i click register for airdrop inside the app it shows this

![image](https://user-images.githubusercontent.com/57812266/68970558-9d443c00-07f8-11ea-9018-f8896b06964b.png)

**Comment by g13g13** [comment]
before that i had the screen that says iam qualified

![image](https://user-images.githubusercontent.com/57812266/68970724-ff04a600-07f8-11ea-870a-016d6ca42fd0.png)

**Comment by justinsmalluk** [comment]
Getting the same issue

**Comment by hanshanski** [comment]
This same ...

**Comment by g13g13** [comment]
why was it closed?

**Comment by g13g13** [comment]
problem persists
