### ISSUE TITLE
Fails to Airdrop Even Though I supposedly Am Qualified

### ISSUE THREAD

**Issue by jonmchan** [keybase/client#21006]
Keybase GUI Version: 5.0.0-20191114182642+f73f97dac6

Please look at screenshots:

![image](https://user-images.githubusercontent.com/1827190/68974873-626de400-07b7-11ea-9d62-7cc13fe9443a.png)

Then I click on the "Become a lucky airdropee" and I get:

![image](https://user-images.githubusercontent.com/1827190/68974882-67329800-07b7-11ea-93da-ab22f21e1d5c.png)

**Comment by Kboom21** [comment]
Please help me. I did all the steps correctly to participate in the airdrop and I got a message that my account was not qualified ... Help me want to receive my bonus ..

**Comment by wf09** [comment]
There are similar problems on me.

**Comment by peterroth** [comment]
This is a known thing for more than months now and so far nobody found a working, trustworthy solution.
I also face this issue, I added my wife's number to my account, hoping that helps, but had no luck. Tried to validate through VPN in another country, also didn't help.

**Comment by wf09** [comment]
I don't think I have a fate with him, so I gave up.

发自我的iPhone

**Comment by jonmchan** [comment]
@maxtaco did i open up a ticket to the wrong place or is there any resolution for this?
