### ISSUE TITLE
I lost all the devices. Help me Please.

### ISSUE THREAD

**Issue by Albertron86** [keybase/client#21007]
Hi. I have 3 devices (1 smartphone and 2 papers) I lost both papers, and I sold the phone without adding my PC or my new phone. If I reset the account, will I lose the airdrop?
Is there any way to enter the APP without having any of the devices? Thanks

**Comment by peterroth** [comment]
I don't think it's possible. I re-added my phone many times (had to reset my system) and I had to use either the paper or my notebook to validate the new device and use the account I have.

**Comment by Albertron86** [comment]
> I don't think it's possible. I re-added my phone many times (had to reset my system) and I had to use either the paper or my notebook to validate the new device and use the account I have.

Thanks for answering.  If you reset the account, do you lose the airdrop?
