### ISSUE TITLE
Kenapa saya gagal dalam qualified airdrop

### ISSUE THREAD

**Issue by andrisairah** [keybase/client#21017]
Saya pengguna baru di keybase tetapi kenapa saya gagal dalam qualified Airdrop. Semua persyaratan qualified Airdrop sudah terpenuhi. Tetapi kenapa ditolak

**Comment by Xcallibur82** [comment]
Yes same with me. Have signed up with keybase way long ago and yet they disqualified Malaysia and Singapore. I think this is very unfair for real keybase supporters like us.

**Comment by Xcallibur82** [comment]
How can u close the thread without credible explanation? So u guys are centralized and not decentralized.
