### ISSUE TITLE
I still haven't received any lumes from the airdrop

### ISSUE THREAD

**Issue by doithaylaem** [keybase/client#21025]
I joined the airdrop program from keybase but until November 16, I still haven't received xlm from keybase.

**Comment by Nahid2234** [comment]
I still have not received xlm on keybase,  why??

**Comment by mujtabapapu** [comment]
Not recieve any xlm so for from keybase despite getting a message that i am in for the airdrop. I would like to know the reason??

**Comment by SJang1** [comment]
Looks like still transfering, just wait for few days. I am still waiting too.
You can see transfering details at its wallet, https://stellar.expert/explorer/public/account/GDV4KECLSZLKRVH4ZTWVAS4I3W2LPAPV66ADFFUZKGIVOTK6GMKGJT53

also airdrop page said : It will take a few days
```
UPDATE #4 November 15: 💖 Good news, everyone! @spacedrop is delivering Lumens right now to registrants. It will take a few days, as @spacedrop builds an encrypted conversation on Keybase with each recipient. You can watch the balance drain to see how far along it is..
```

**Comment by chindraba-work** [comment]
Also Keybase has nothing to do with the airdrop. It is all done by the [Stellar Development Foundation](https://www.stellar.org/blog/keybase-stellar-lumens-spacedrop), and Keybase cannot "fix" it as it's not their program and it is not broken.

**Comment by SJang1** [comment]
BTW if this is an issue, you may need to go to [orbitlens/stellar-expert-explorer
](https://github.com/orbitlens/stellar-expert-explorer/issues/)

**Comment by Huynhanh883** [comment]
Ban cho mình hỏi tí. Nói thật mình tạo này chứ chưa biết sử dụng sao. Bạn hướng dẫn mình dc hok? 

Được gửi từ iPhone của tôi

Vào ngày 16 thg 11, 2019, lúc 18:21, Huỳnh Phúc Thành <notifications@github.com> đã viết:

**Comment by doithaylaem** [comment]
Bạn muốn hướng dẩn cái nào?

Vào CN, 17 thg 11, 2019 lúc 15:40 Huynhanh83 <notifications@github.com> đã
viết:
