### ISSUE TITLE
Airdrop 

### ISSUE THREAD

**Issue by jona3599** [keybase/client#21038]
I am not qualified bat airdrop. Help me . My count of keybase is jona3599

**Comment by Alaverto** [comment]
Everyone with an active account qualify, just use it.

**Comment by jona3599** [comment]
It doesn't allow me to tell me that I'm not qualified

**Comment by 09Bryan09** [comment]
> Everyone with an active account qualify, just use it.

I have an active account,before mine is qualified after the said attact or cheat they are talking about..they remove my account..i was shock.,i only have one account so how come..many from my country recieved thier xlm..they remove anyone they like to remove without proof of cheating..that biased..:(
