### ISSUE TITLE
Unable join but passed checking qualification

### ISSUE THREAD

**Issue by bavinh2907** [keybase/client#21039]
![Screenshot_20191117-074220_Keybase](https://user-images.githubusercontent.com/7940744/69001305-b3442080-090e-11ea-8f47-e9210e314035.jpg)
![Screenshot_20191117-074215_Keybase](https://user-images.githubusercontent.com/7940744/69001306-b7703e00-090e-11ea-8dea-99b2a55f64bc.jpg)
Please help me to check.

**Comment by Justice442** [comment]
Please I passed all the requirements but I'm unable to join the airdrop, please help me out.

**Comment by Alaverto** [comment]
Is your country inthe list?

**Comment by Justice442** [comment]
Yes please, my country is qualified. A number of friends are qualified from
my county, why am I finding hard to please?

**Comment by Alaverto** [comment]
Reset account and try again

**Comment by Justice442** [comment]
Ok, I will do that. Thanks Sir

**Comment by Justice442** [comment]
Please, below is my profile, how do I go about resetting it?
