### ISSUE TITLE
Unable to join the airdrop after passing qualification

### ISSUE THREAD

**Issue by flfy** [keybase/client#21031]
OS: Windows 10

Following gif shows what I'm talking about: https://i.imgur.com/c34dCPU.gifv

**Comment by daniel0961** [comment]
Same here im approved in phone number but always saying my phone not qualified im from saudi

**Comment by TMNghia96** [comment]
Same issue

**Comment by flfy** [comment]
if you would respond before closing the issue, that would be nice, thanks.
