### ISSUE TITLE
Didnt get airdrop

### ISSUE THREAD

**Issue by Aliassaan** [keybase/client#21045]
I fullfilled my all requirements in the begining of the airdrop. My username is aliassaan but i didnt get airdrop sir

**Comment by admob22** [comment]
I list the September airdrop keybase. I feel not cheating and in accordance with predetermined procedures. why there is no logo logo on my profile that shows that I have successfully entered the airdrop. 

My username : marcuzt

**Comment by bazmanv** [comment]
hy marcuzt... add me hotelmoscow :)... iam september user too :)

**Comment by zcpaul93** [comment]
Yes Didnt get airdrop.
I completed all the tasks on September 10 but airdrop gain is not in my account

Username: zcpaul
