### ISSUE TITLE
Removed from Airdrop

### ISSUE THREAD

**Issue by jghjgfgh** [keybase/client#21042]
Back in September, I verified using my Github account, phone number, and 4 devices. It said I was successfully signed up for the airdrop.

Now today, I found out I was apparently removed because I am from Canada.

Meanwhile, 2 of my friends from Canada apparently still qualify. 

I have been a user on Github for over 10 years, so you should be able to verify my profile. I don't understand why you lied about me being signed up 2 months ago.

From my understanding, you are effectively saying that no Canadian citizens should use your application.

**Comment by 09Bryan09** [comment]
Same here..I was shocked..suddenly my account remove from the list,the system says my phone number came from a country that many try to each.though i only have one account..did not really made a sure investigation just remove people whether they cheat or not.like mini mini my nimo..

**Comment by jghjgfgh** [comment]
Why was this closed?

**Comment by csh** [comment]
>Canada is excluded due to our inability to verify Canadian phone numbers were not purchased at scale.

Excerpt from the Keybase airdrop website.

**Comment by munnamizan1494** [comment]
> > Canada is excluded due to our inability to verify Canadian phone numbers were not purchased at scale.
> 
> Excerpt from the Keybase airdrop website.

But on September there was no such rules. Everyone who joined on September got their drop.
