### ISSUE TITLE
problem with AirDrop 

### ISSUE THREAD

**Issue by DaManGold** [keybase/client#21046]
I can’t do The AirDrop, why?! I receive this Error: 

![51AA1F92-688C-46AE-8331-F035484A0A62](https://user-images.githubusercontent.com/57861073/69006528-65d8ab00-0930-11ea-9162-1c295c248826.png)
![F7050E54-B85B-4BB4-91FC-9D27B076B3B5](https://user-images.githubusercontent.com/57861073/69006529-65d8ab00-0930-11ea-8233-8133633bec55.png)

**Comment by bazmanv** [comment]
try again after 1 weeks :)

**Comment by DaManGold** [comment]
> try again after 1 weeks :)

I did all the steps correctly and I was eligible for AirDrop, but I didn't receive the coins.  Now it gives me this error. Can i get the coins i didn't receive?
