### ISSUE TITLE
🔥Stellar Wallet won't open and load assets and pages

### ISSUE THREAD

**Issue by solus-hq** [keybase/client#21075]
<img width="912" alt="Screenshot 2019-11-18 at 11 43 19" src="https://user-images.githubusercontent.com/26515805/69037270-9f74e900-09f8-11ea-9c21-df01f2be7d85.png">

**Comment by Truck124** [comment]
Почему

**Comment by agc93** [comment]
I'm also seeing this issue. Using the CLI to list balances works, but send operations fail.

**Comment by qamalluddeen02** [comment]
Hello 
I've received the message that my lumes has been sent, but it's not showing in my wallet.

**Comment by solus-hq** [comment]
`keybase wallet send` doesn't work and throws

```
▶ ERROR internal error
```

**Comment by cgaspart** [comment]
Same issue ! 🆙

**Comment by gs1960** [comment]
Same problem.

**Comment by BouweCeunen** [comment]
I have a feeling they are aware of the issue, just need to wait this out.

**Comment by solus-hq** [comment]
Seems the issue is now resolved
