### ISSUE TITLE
I am qualified for the Airdrop, I even have an Airdrop badge but I did not receive XLM

### ISSUE THREAD

**Issue by magnes975** [keybase/client#21088]
Hi. How are you?
I am qualified, in addition to my profile is the Airdrop badge, but I have not received XLM, payments are made alphabetically, my username is "magnes975", and at this precise moment they make the payment to "mikemacleod" That is, I should have already have received my XLM
Why did I not receive XLM? if everything is fine?
![image](https://user-images.githubusercontent.com/55520365/69071475-59238800-0a00-11ea-8ff6-f3469b88b55e.png)
![image](https://user-images.githubusercontent.com/55520365/69071495-650f4a00-0a00-11ea-9ecb-1ed9b5273f01.png)

**Comment by munnamizan1494** [comment]
Same issue :( username:munnamizanur

**Comment by Lastnet0709** [comment]
to many problem for username with M 
[https://github.com/keybase/client/issues/21097](url)

**Comment by magnes975** [comment]
> to many problem for username with M
> [https://github.com/keybase/client/issues/21097](url)

Your link https://github.com/keybase/client/issues/21097 does not work, can you explain what you mean?

**Comment by magnes975** [comment]
> to many problem for username with M
> [https://github.com/keybase/client/issues/21097](url)

Yes, I also commented there, but I think we have no solution :(

**Comment by Lastnet0709** [comment]
> Yes, I also commented there, but I think we have no solution :(

my friend has the same problem too, he said he had to wait 1 or 2 weeks. he got an answer from the keybase admin.
sorry for my bad english

**Comment by magnes975** [comment]
> > Sí, también comenté allí, pero creo que no tenemos solución :(
> 
> mi amigo también tiene el mismo problema, dijo que tuvo que esperar 1 o 2 semanas. recibió una respuesta del administrador de la base de claves. 
> Perdón por mi mal ingles

Hablas español? 
Tu amigo tuvo el problema de recibir la transferencia pero con un error? O en definitiva no recibió nada? Y la pregunta más importante, el administrador le dió los XLM de vuelta?

**Comment by inate77** [comment]
I joined it back in September but then a week prior was removed. Opened a case but is was closed with no reason as to why I was removed from drop. Friends I sent the link to no issues at all. :(
