### ISSUE TITLE
Can't browse team folder on MacOS

### ISSUE THREAD

**Issue by simpleauthority** [keybase/client#21089]
I'm unable to browse a public team folder on Keybase on MacOS either via client, finder, or terminal. It says "You cannot browse an unsynced folder while disconnected from Keybase servers". I'm not sure why it would be unsynced. I can view my private folder (seemingly). Let me know if there is any more info I can provide. Thanks.

my log id: 52f07e0aacc7bdcd5dff571c

**Comment by strib** [comment]
It looks like the folder of that team is in a bad state.  I'll contact the admins of the team and try to sort it out.

**Comment by dwhagar** [comment]
I have a similar issue, I don’t think it’s just this one team.

**Comment by strib** [comment]
@dwhagar you're actually both trying to look at the same team folder.  I'm working with the team owner to try to fix it.

**Comment by strib** [comment]
The folder seems to have hit some weird error during initialization.  We reset it and I think it's behaving correctly now.  Please close if things seem ok to you now.

**Comment by simpleauthority** [comment]
Seems to be working for me. @dwhagar ping if it's not fixed, closing.
