### ISSUE TITLE
(closed)Joined AirDrop but no token has been received yet.

### ISSUE THREAD

**Issue by ritikn2020** [keybase/client#21082]
![Screenshot_20191118-175825](https://user-images.githubusercontent.com/44635124/69052463-175d0680-0a2d-11ea-8a28-ccf6bdc642a4.png)
I joined Air Drop but I have not received any token yet.
![Screenshot_20191118-175837](https://user-images.githubusercontent.com/44635124/69052483-22179b80-0a2d-11ea-975d-bca72e6de68a.png)

**Comment by zeis974** [comment]
You click at **send** ?

**Comment by ritikn2020** [comment]
Thanks Airdrop Received
