### ISSUE TITLE
Not qualified for airdrop although app says differently 

### ISSUE THREAD

**Issue by TRtomasz** [keybase/client#21087]
**Description**
As screenshot says i'm qualified to airdrop (phone number from qualified country) 
after clicking "become lucky airdropee" app says "Sorry you are not qualified to join"
Could it be because my current country location is different than used phone number? I'm currently in UK fore few days and i have used Polish phone number. Should i use a vpn in such case?
**Screenshots**
![image](https://user-images.githubusercontent.com/40594253/69059969-d659f780-0a16-11ea-8d43-1ceeb58a8c73.png)
![image](https://user-images.githubusercontent.com/40594253/69059997-e07bf600-0a16-11ea-9c56-c2b8c447c41a.png)

**Comment by Bartek05** [comment]
I have the same message and I live in Poland and I have a Polish phone number...
![Screenshot_2](https://user-images.githubusercontent.com/23617249/69065420-0659c880-0a20-11ea-93bf-eb1aa06032bd.png)
![Screenshot_3](https://user-images.githubusercontent.com/23617249/69065427-0bb71300-0a20-11ea-9734-c21a1e1dee91.png)

**Comment by andreapede** [comment]
+1  italy over italy

**Comment by solus-hq** [comment]
Same here, US number

<img width="422" alt="Screenshot 2019-11-18 at 19 46 08" src="https://user-images.githubusercontent.com/26515805/69072271-6bbbb280-0a3c-11ea-9f45-e4c41490bd6d.png">

<img width="465" alt="Screenshot 2019-11-18 at 19 46 14" src="https://user-images.githubusercontent.com/26515805/69072275-6eb6a300-0a3c-11ea-83d0-9dbe67c33261.png">

**Comment by revonoc** [comment]
Yeah this has been happening to a lot of us for a long time. They closed the last threads without telling us anything sadly!

**Comment by zahangir1996** [comment]
![Screenshot_2019-11-19-11-53-40-11_c661a6be9afaec2a14fc529271fda7c0](https://user-images.githubusercontent.com/36542738/69124922-ec2af380-0ace-11ea-85c1-14cde8fc4296.png)
![Uploading Screenshot_2019-11-19-11-53-29-50_c661a6be9afaec2a14fc529271fda7c0.png…]()
I have the same message

**Comment by zahangir1996** [comment]
same hare
![Screenshot_2019-11-19-11-53-40-11_c661a6be9afaec2a14fc529271fda7c0](https://user-images.githubusercontent.com/36542738/69125146-59d71f80-0acf-11ea-8aef-af94d059a1bc.png)
![Uploading Screenshot_2019-11-19-11-53-29-50_c661a6be9afaec2a14fc529271fda7c0.png…]()

**Comment by cjwatt** [comment]
Same here I'm in the us and I have sa,e exact error..my username is mr watts

**Comment by pgl** [comment]
I'm seeing the same behaviour (user https://keybase.io/pgl).

**Comment by munnamizan1494** [comment]
Same here :( username: munnamizanur

**Comment by 86XIng** [comment]
Same too :<

**Comment by Nizar87** [comment]
Same here 😑

**Comment by zeis974** [comment]
Same :/

**Comment by Benjaki2** [comment]
Same here :(

**Comment by Zopieux** [comment]
See #21055.
