### ISSUE TITLE
Keybase Helper processes on macOS consumes all available memory

### ISSUE THREAD

**Issue by rys** [keybase/client#21091]
Keybase GUI Version: 5.0.0-20191114182642+f73f97dac6

A couple of times recently I've logged in to my Mac to find a disk space warning and two Keybase Helper processes sitting consuming exactly 48.0GB of RAM each, which eats all of my physical RAM (32GB) and fills up the remainder of my SSD with virtual memory swap files in `/private/var/vm`.

If it's not a known issue, let me know if and how I can provide more information about what's happening the next time it does.

**Comment by mpmc** [comment]
Same here, but on Win. Seems like there's a memory leak somewhere.

**Comment by karlbrown-va** [comment]
Had this same issue. Several  Keybase helper processes consuming many many GB of RAM.

**Comment by eleazargc** [comment]
Same issue, two processes of key base helper (renderer) consuming more than 200% CPU each.

**Comment by eleazargc** [comment]
> Same issue, two processes of key base helper (renderer) consuming more than 200% CPU each.

Already quit and force quit key base and the processes don't shut down.
