### ISSUE TITLE
Get 3 green ticks, but not qualified when join the airdrop

### ISSUE THREAD

**Issue by bacsonvv** [keybase/client#21104]
I just add an phone number to my account (my account registed in September and get all the things verified back there, but I don't know why i was out from the airdrop). Today when I check again and add another phone numer (in approved country), I got all 3 green ticks but when I click on "become a lucky airdropee" it said that "Sorry, I'm not qualified", anyone got this issue, and how can I join the airdrop again, all my keybase and github account were registed before September.
![keybase1](https://user-images.githubusercontent.com/33516020/69160847-ccbab780-0b1c-11ea-917f-25b7fb4e8536.PNG)
![keybase1](https://user-images.githubusercontent.com/33516020/69160924-e6f49580-0b1c-11ea-9867-5f05c3e27bde.PNG)

**Comment by Nizar87** [comment]
Yeahh same here

**Comment by GoldAthena** [comment]
Same

**Comment by bacsonvv** [comment]
Anyone who from the developer team can explain this issue to me? My friend who use a phone number from an unapproved country and he still get his airdrop which is about 45$. I check the website of keybase and it said that we still can join the airdrop till 15 December.

**Comment by munnamizan1494** [comment]
Same, got qualified when register. now not qualified :(

**Comment by trixxyz** [comment]
Same issue here, I got the last airdrop but not this one either :(

**Comment by trixxyz** [comment]
If it's saying qualified and then unqualified it means you're banned :/ Apparently they banned tons of account in the process banning all accounts that have used a vpn, so if you were signed into to keybase on your phone app and turned a vpn on it blacklisted you, same with your pc. Keybase staff won't reach out to anyone about this issue :/

**Comment by TechTronixx** [comment]
Same here
Can the staff confirm on this issue?
how does using the VPN effect as a banned account?

**Comment by joergpanke** [comment]
gleiches proplem bin seid 15 Oktober dabei, und nichts bekommen keiner kann helfen.
