### ISSUE TITLE
unexpected re-track confirmation upon entering someone's public directory

### ISSUE THREAD

**Issue by bjabes** [keybase/client#2111]
Steps:

1. went to https://keybase.io/johnsheehan and clicked Track.
2. immediately after, from terminal, typed 'cd /keybase/public/johnsheehan'  
3. was prompted that one of the identities could not be confirmed (an identity not listed on the webpage)

my log id: 46f6a58ba4c1f3dfa755b91c

**Comment by oconnor663** [comment]
The website doesn't show failing proofs (you can see them on the command line with `keybase id $person`, but if that also applies to the list of proofs you sign in a tracking statement, it could be a bug. @maxtaco do the website and the client differ in how they treat failing proofs at the time of tracking?

**Comment by maxtaco** [comment]
Website and client check on different timers.

**Comment by bjabes** [comment]
I figured this was a race condition. Thanks for the info.
