### ISSUE TITLE
Why can't I participate in the airdrop?

### ISSUE THREAD

**Issue by OlehShirokov** [keybase/client#21117]
Hey.  I have fulfilled all the conditions for participating in an airdrop, but it says to me that I cannot take part in it, why? My nickname - oleshkaa

**Comment by dnorhoj** [comment]
Same please fix this... When I click on join airdrop it checks out all three points but then when I click continue it says that I'm not qualified even though I was qualified like a second ago.

**Comment by trixxyz** [comment]
If it's saying qualified and then unqualified it means you're banned :/ Apparently they banned tons of account in the process banning all accounts that have used a vpn, so if you were signed into to keybase on your phone app and turned a vpn on it blacklisted you, same with your pc. Keybase staff won't reach out to anyone about this issue :/

**Comment by TechTronixx** [comment]
any update regarding this ?
