### ISSUE TITLE
Send XLM whithout MEMO

### ISSUE THREAD

**Issue by TheWoriwor** [keybase/client#21116]
Hi, I have a problem, i send 680XLM with a Stellar Adress but whitout a Memo and I lost this 680XLM

This is the transaction: https://stellar.expert/explorer/public/tx/115424089279045632#115424089279045633

How can I recover the XLM?
![2019-11-19 18_57_05-Window](https://user-images.githubusercontent.com/38791782/69190076-6cb51880-0afe-11ea-9263-2ca542cc0de7.png)

**Comment by Brianetta** [comment]
That's a Binance address. You need to contact Binance and ask them to help you. They have your Lumens, but weren't told which user they are meant for.

**Comment by tks3773** [comment]
I also sent lumens to my coinbase account without the memo and now my lumens are gone. How can I get them back?

**Comment by Brianetta** [comment]
> I also sent lumens to my coinbase account without the memo and now my lumens are gone. How can I get them back?

Talk to Coinbase. They have your Lumens, and you didn't tell them which Coinbase user they were for.

**Comment by maxtaco** [comment]
Off topic

**Comment by mathemaphysics** [comment]
I'm having another problem. My account won't update my XLM balance even though checking it directly on the blockchain shows the correct balance.

I noticed this after transferring XLM from Coinbase to my Keybase lumen wallet.
