### ISSUE TITLE
I am qualified and I didn't get the lumens 

### ISSUE THREAD

**Issue by tarastalian** [keybase/client#21113]
Hello, my alias is tarastalian. I was qualified last October, I have the budget but I didn't get the lumens this November's airdrop.
why could happen?

**Comment by trixxyz** [comment]
If your  name is tarastalian it may not be only you, mine is trixxyz and I have yet to receive mine, they may not have gotten to the T’s yet

**Comment by TravisWhitehead** [comment]
Please be patient and watch https://pacmam.keybase.pub/
You don't have cause for concern until all of the Lumens are distributed.

**Comment by tarastalian** [comment]
OK, but actually it's at the letter V

**Comment by munnamizan1494** [comment]
> Hello, my alias is tarastalian. I was qualified last October, I have the budget but I didn't get the lumens this November's airdrop.
> why could happen?

Please tell me! Did you loged in your keybase account on keybase apk version 4.01 or older?

**Comment by tarastalian** [comment]
OK, but actually it's at the letter V.

**Comment by tarastalian** [comment]
No, I didn't log anything. I have apk version 5

**Comment by tarastalian** [comment]
Anyone with thi problem has an answer? Please?

**Comment by munnamizan1494** [comment]
> Anyone with thi problem has an answer? Please?

same to me but admin closed this issue without solution :(
