### ISSUE TITLE
KBFS - Input/output error

### ISSUE THREAD

**Issue by Diagonactic** [keybase/client#2112]
Just got started using KBFS -- I'm getting an error writing files to /keybase/public

```bash
$ echo "test" > test.txt
-bash: test.txt: Input/output error
```

I performed this on an Kubuntu box running on a Samsung tablet.  When I ran `run_keybase`, it prompted me for my password, I provided it and it logged me in.  About every 5 minutes or so a message appears in the lower right hand corner of my KDE session indicating that I'm logged in as "mdip" (my account) with a view button.  When I click the "View" button, the dialog is dismissed but nothing else happens.  I'm not sure if that's related or not.

The logs seem to be having a problem related to that, though:

```
[DEBU FUSE serve.go:817] 055 -> [ID=0x11] Lookup error=EIO: invalid name (bad fields: username) (error 100)
```

After searching the issues, I also tried running `keybase unlock` but that didn't affect anything.

my log id: 1ec259bb39c27b04a31a4b1c

**Comment by strib** [comment]
Looks like you're trying to make files directly under `/keybase/private` and/or `/keybase/public`.  The listings there are supposed to be username-based folders.  Instead, try `/keybase/private/mdip` for example.  You can `cd` into the folder even if it doesn't look like it exists.

**Comment by Diagonactic** [comment]
Doh! PEBCAK error then. Thanks! That worked :+1:

**Comment by strib** [comment]
Sweet!
