### ISSUE TITLE
3 ticks on qualify but get error code when I hit qualify

### ISSUE THREAD

**Issue by trixxyz** [keybase/client#21120]
So I realized I wasn't qualified once I didn't receive my airdrop, I thought I already was registered since I got the drop in September but I guess I'm not. I went to qualify and get my badge. It gave me 3 ticks and said I was good to go but when I click qualify I get error code 4207. I guess I missed this months airdrop which sucks, is there a way I can fix this?

**Comment by patygoku** [comment]
### Keybase proof

I hereby claim:

  * I am patygoku on github.
  * I am patygoku (https://keybase.io/patygoku) on keybase.
  * I have a public key ASBQJpg1QfWgsxn3Sgu8Z8HyRGRN_nfdsEJNAyqYQyNNzAo

To claim this, I am signing this object:

```json
{
  "body": {
    "key": {
      "eldest_kid": "01205026983541f5a0b319f74a0bbc67c1f244644dfe77ddb0424d032a9843234dcc0a",
      "host": "keybase.io",
      "kid": "01205026983541f5a0b319f74a0bbc67c1f244644dfe77ddb0424d032a9843234dcc0a",
      "uid": "1e52d316b9c2dcbdddd9a8a37b1cb419",
      "username": "patygoku"
    },
    "merkle_root": {
      "ctime": 1574205509,
      "hash": "3da5f61b636cacc530878b0f7643730d5ffd4a7fc28ac5486d3251c67b09324ca624a6afef5f164bd765adf750851d751b83bb02cb972e2dc47d7ecc3888cbc3",
      "hash_meta": "0991838274c264fffc92711bb06cd6cde6970916f67ca269037b9d47d36f5cc7",
      "seqno": 10264741
    },
    "service": {
      "entropy": "GsS7c8b53S/lBpvhEr9rR0pS",
      "name": "github",
      "username": "patygoku"
    },
    "type": "web_service_binding",
    "version": 2
  },
  "client": {
    "name": "keybase.io go client",
    "version": "5.0.0"
  },
  "ctime": 1574205519,
  "expire_in": 504576000,
  "prev": "61e531d949edd877f1e58c33c236f563519ceff2ce169ffeae08bdf057d1d6f1",
  "seqno": 10,
  "tag": "signature"
}
```

with the key [ASBQJpg1QfWgsxn3Sgu8Z8HyRGRN_nfdsEJNAyqYQyNNzAo](https://keybase.io/patygoku), yielding the signature:

```
hKRib2R5hqhkZXRhY2hlZMOpaGFzaF90eXBlCqNrZXnEIwEgUCaYNUH1oLMZ90oLvGfB8kRkTf533bBCTQMqmEMjTcwKp3BheWxvYWTESpcCCsQgYeUx2Unt2Hfx5Ywzwjb1Y1Gc7/LOFp/+rgi98FfR1vHEIIftnqS+dI24z4Hza+Uhi5hulatr0seBetjVRwX/ejL+AgHCo3NpZ8RAD0JlxQBX4jiHppg370NOmLqpKXVZpzvGwh3FZ2nIsKsVZCorcWdXQyvPUwriL7De/sjmApA1796L+1RpiHCqB6hzaWdfdHlwZSCkaGFzaIKkdHlwZQildmFsdWXEIBPrPu3Mg/snIxOLQP0UkIT2Lcjbd5f48arYxLipRle3o3RhZ80CAqd2ZXJzaW9uAQ==

```

And finally, I am proving ownership of the github account by posting this as a gist.

### My publicly-auditable identity:

https://keybase.io/patygoku

### From the command line:

Consider the [keybase command line program](https://keybase.io/download).

```bash
# look me up
keybase id patygoku
```

**Comment by munnamizan1494** [comment]
> So I realized I wasn't qualified once I didn't receive my airdrop, I thought I already was registered since I got the drop in September but I guess I'm not. I went to qualify and get my badge. It gave me 3 ticks and said I was good to go but when I click qualify I get error code 4207. I guess I missed this months airdrop which sucks, is there a way I can fix this?

Please tell me! Did you loged in your keybase account on keybase apk version 4.01 or older?

**Comment by patygoku** [comment]
{
  "body": {
    "key": {
      "eldest_kid": "01205026983541f5a0b319f74a0bbc67c1f244644dfe77ddb0424d032a9843234dcc0a",
      "host": "keybase.io",
      "kid": "01205026983541f5a0b319f74a0bbc67c1f244644dfe77ddb0424d032a9843234dcc0a",
      "uid": "1e52d316b9c2dcbdddd9a8a37b1cb419",
      "username": "patygoku"
    },
    "merkle_root": {
      "ctime": 1574205509,
      "hash": "3da5f61b636cacc530878b0f7643730d5ffd4a7fc28ac5486d3251c67b09324ca624a6afef5f164bd765adf750851d751b83bb02cb972e2dc47d7ecc3888cbc3",
      "hash_meta": "0991838274c264fffc92711bb06cd6cde6970916f67ca269037b9d47d36f5cc7",
      "seqno": 10264741
    },
    "service": {
      "entropy": "GsS7c8b53S/lBpvhEr9rR0pS",
      "name": "github",
      "username": "patygoku"
    },
    "type": "web_service_binding",
    "version": 2
  },
  "client": {
    "name": "keybase.io go client",
    "version": "5.0.0"
  },
  "ctime": 1574205519,
  "expire_in": 504576000,
  "prev": "61e531d949edd877f1e58c33c236f563519ceff2ce169ffeae08bdf057d1d6f1",
  "seqno": 10,
  "tag": "signature"
}

**Comment by trixxyz** [comment]
> > So I realized I wasn't qualified once I didn't receive my airdrop, I thought I already was registered since I got the drop in September but I guess I'm not. I went to qualify and get my badge. It gave me 3 ticks and said I was good to go but when I click qualify I get error code 4207. I guess I missed this months airdrop which sucks, is there a way I can fix this?
> 
> Please tell me! Did you loged in your keybase account on keybase apk version 4.01 or older?

Apparently we've been banned for god know's why, staff won't tell anyone why they are blacklisting normal people so we are just sol :/

**Comment by magician11** [comment]
Yes seems that way. I understand why they don't want to explain their fraud detection system in detail so that hackers can't work to bypass it. And yet it feels like a lot of us are indirectly being accused of doing something fraudulent when I have no idea why, and they won't give us any reason for why we are blacklisted.

It's frustrating. And a little worrying now actually.. that we're on a blacklist for some unknown reason, and it's not clear if this impacts any other aspect of future use of keybase. Maybe people on this list suddenly won't be able to create big groups? Or have limits on number of team members?

I really like keybase, and I'm concerned with the lack of transparency here that they can limit or ban us from keybase functionality and give no reason as to why. My trust levels in their product is wavering.
