### ISSUE TITLE
Nobember 20 not recibed airdrop

### ISSUE THREAD

**Issue by weins3** [keybase/client#21129]
Good Morning, i testesd de aplication and email account and dont have email for the airdrop and my wallet its 0xlm. I did register 2 moth ago, and in the aplications appear:
![imagen](https://user-images.githubusercontent.com/50326878/69231044-b1859180-0b88-11ea-8222-1ce4a35df48a.png)
Can you help me?

**Comment by Taron0777** [comment]
hello i send my nuber and my number phone 
![Screenshot_5](https://user-images.githubusercontent.com/16327497/69241820-07722d80-0bb9-11ea-83bb-548dfec4134c.png)
approved but i can`t see my approved airdrop qualyfy why

**Comment by weins3** [comment]
why closed?
