### ISSUE TITLE
Airdrop Qualified But Cant Join

### ISSUE THREAD

**Issue by sleepycharlyy** [keybase/client#21139]
Hello, I got a Problem.
I did all the stuff to qualify for the airdrop and when I click "See if you Qualify" then I get all the ticks..
But once I click "Become a lucky airdropee" a new Window opens and says "You are not Qualified".. 
When I click:  "See if you Qualify"
![Screenshot_1](https://user-images.githubusercontent.com/52420852/69263687-18756b80-0bc6-11ea-9177-6ae523e3d6ee.png)
When I click: "Become a lucky airdropee"
![Screenshot_2](https://user-images.githubusercontent.com/52420852/69263683-16aba800-0bc6-11ea-8104-509308a85532.png)

Username: sleepycharlyy

**Comment by trixxyz** [comment]
Apparently this means we’ve been banned from the airdrops for some reason, staff isn’t coming forward and giving anyone explanations, they’re closing everyone’s posts that address this issue, you aren’t alone

**Comment by bbqlordd** [comment]
Username bbqlord on keybase... Same issue here

**Comment by yann-Solol** [comment]
Are you sure of that? Is there because of they leave all my accounts, and team requested me to create again all accounts (I never get back any data of course but in this cas that means they have got still data about my account they forget) but it was before airdrop announcement 🤔
