### ISSUE TITLE
Key path not found Error code 218: GENERIC in method keybase.1.login.login

### ISSUE THREAD

**Issue by Taogasat30** [keybase/client#21149]
Good day , i have been trying to register an account. after registering or trying to log in on the keybase app downloaded on my phone and laptop, this is what i have been seeing 
"key path not found
Error code 218: GENERIC in method keybase.1.login.login".
I also tried register with different email so as to detect if the fault was from my email, phone or laptop, yet same messages had been popping up till now . i have not been able to complete a registration even via the web adrress.
Can you please proffer a solution to this problem?
Thanks in anticipation.

**Comment by maxtaco** [comment]
super super old app. upgrade

**Comment by Taogasat30** [comment]
@maxtaco i just downloaded the app two days ago

**Comment by Taogasat30** [comment]
> 
> 
> super super old app. upgrade

I am using the website(https://keybase.io/) but i was not given the option to add device and paper key. Besides, how do I check if i have qualified for the airdrop?
