### ISSUE TITLE
I am qualify but not received my airdrop 

### ISSUE THREAD

**Issue by imranss014** [keybase/client#21159]
I am perform all task and I m also in airdrop. But I don't received any xlm on my keybase account on this wallet address is given below 
GAHLATSV7AX756TOJW6D5U7OJ45HPWS6PWUIYHGKRHHPBB3DQICF7FBX
Anyone can help me.... 🤔🤔🤔🤔

**Comment by munnamizan1494** [comment]
> I am perform all task and I m also in airdrop. But I don't received any xlm on my keybase account on this wallet address is given below
> GAHLATSV7AX756TOJW6D5U7OJ45HPWS6PWUIYHGKRHHPBB3DQICF7FBX
> Anyone can help me....

When you joined?

**Comment by imranss014** [comment]
11 September 2019
