### ISSUE TITLE
Updater Updates Regardless of Version

### ISSUE THREAD

**Issue by zQueal** [keybase/client#2115]
Keybase GUI Version: 1.0.13-20160223105128+aaabcc9

Before running `keybase update check`;

    λ keybase version
    Client:  1.0.13-20160223105128+aaabcc9
    Service: 1.0.13-20160223105128+aaabcc9

Then;

    λ keybase update check
    - INFO Checking for update, current version is 1.0.13-20160223105128+aaabcc9
    - INFO Using updater source: Remote ({redacted})
    - INFO Request "{redacted}"
    - INFO Checking update with version: 1.0.13-20160223130514+aaabcc9
    - INFO Request {redacted}
    - INFO Downloading to C:\Users\zqueal\AppData\Local\Temp\KeybaseUpdates\keybase_setup_gui_1.0.13-20160223105128+aaabcc9.386.exe.download
    - INFO Downloaded 51949096 bytes
    - INFO Verified digest: c1b17281fd781555bd7620bdccf2cbc95fa6f4a8c7aec20a6e4d2e7775ecde89 (C:\Users\zqueal\AppData\Local\Temp\KeybaseUpdates\keybase_setup_gui_1.0.13-20160223105128+aaabcc9.386.exe.download)
    - INFO Moving keybase_setup_gui_1.0.13-20160223105128+aaabcc9.386.exe.download to keybase_setup_gui_1.0.13-20160223105128+aaabcc9.386.exe
    - INFO Restarting app
    - WARNING App quit (for restart) was canceled or unsupported after update
    - ERROR EOF

Then running `keybase version` again;

    λ keybase version
    Client:  1.0.13-20160223105128+aaabcc9
    Service: 1.0.13-20160223105128+aaabcc9

No real need to update, but the updater re-downloads the current version and re-installs it. The biggest issue with this, is after Keybase re-installs the same version of itself the virtual disk which hosts Keybase files returns this error on access;

![xekwgdo](https://cloud.githubusercontent.com/assets/239193/13277675/be17c65e-da98-11e5-83c4-44b82019a4d1.png)

And forces a restart to fix it.

**Comment by cjb** [comment]
Thanks for the report, adding @zanderz.

**Comment by zanderz** [comment]
The spurious downloads were caused by a faulty configuration on the server, and should be fixed for now.

Losing drive K: access after upgrade may be a separate problem. There will be a period of time when the mounted KBFS drive is unavailable because the local keybase service goes down, but it shouldn't require a reboot unless drivers are being updated, which they haven't been yet. We'll keep an eye on this.

**Comment by zQueal** [comment]
Then I'm going to assume this was a crazy one time coincidence caused by Keybase being down and close this ticket. If I see it again I'll just reopen it.

Thanks!
