### ISSUE TITLE
KBFS Windows Random Re-Install

### ISSUE THREAD

**Issue by zQueal** [keybase/client#2122]
During normal workflow, when either working inside of KBFS or outside, randomly (maybe on an interval?) the installer (cached) will pop up and begin installing itself for no reason at all. This causes all Keybase services to be terminated and require a restart to be able to use any part of Keybase again, including KBFS. There doesn't seem to be any real rhyme or reason to prompt the update. Even if you interrupt the install it's already disconnected the KBFS service (even if it was active and currently in use) and you _must_ restart your computer to fix the issue (see below).

![k0by1km](https://cloud.githubusercontent.com/assets/239193/13301006/d775f1ca-db10-11e5-9a8a-a014100631a9.png)

This __may__ be temporarily solvable by removing the cached installer at `%appdata%\Temp\KeybaseUpdates\`. Testing that now, but as I'm unsure what the update trigger is, I'll have to wait and update later on.

--------------------------------

Removing the cached installer __does not__ fix this issue. While doing other things with Keybase (tracking a user) the update command hijacked my previous command and ended up re-downloading and launching the updater before I even knew what was going on.

    λ keybase track exiledsurfer
    - INFO Generating tracking statement for exiledsurfer
    You last tracked exiledsurfer on 2014-08-09 05:56:09 EDT
    OK <tracked> public key fingerprint: D4F9 0F1F CD25 22CB 455F E24D 0EB5 3D36 1FCF 2635
    BTC bitcoin 17xrePVBbPTdLUJDfkM1NpAjUrox9kjYJN
    OK <tracked> "exiledsurfer" on github: https://gist.github.com/e773e8e2eca430c1cbbb [cached 2016-02-24 16:25:34 EST]
    OK <tracked> "exiledsurfer" on twitter: https://twitter.com/exiledsurfer/status/477852771652501505 [cached 2016-02-24 16:25:33 EST]
    OK <tracked> admin of artificialeyes.tv via HTTP: http://artificialeyes.tv/keybase.txt [cached 2016-02-24 16:25:33 EST]
    BAD <new> Proof for bwb.is failed: API network error: Get http://bwb.is/keybase.txt: dial tcp 78.47.89.103:80: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. (code=170)
    Your tracking statement of exiledsurfer is still valid; update it to reflect new proofs? [Y/n] 
    - INFO Checking for update, current version is 1.0.13-20160223105128+aaabcc9
    - INFO Using updater source: Remote (https://s3.amazonaws.com/prerelease.keybase.io)
    - INFO Request "https://s3.amazonaws.com/prerelease.keybase.io/update-windows-prod.json"
    - INFO Checking update with version: 1.0.13-20160223130514+aaabcc9
    - INFO Request https://s3.amazonaws.com/prerelease.keybase.io/windows/keybase_setup_gui_1.0.13-20160223105128%2Baaabcc9.386.exe
    - INFO Downloading to C:\Users\zqueal\AppData\Local\Temp\KeybaseUpdates\keybase_setup_gui_1.0.13-20160223105128+aaabcc9.386.exe.download
    - ERROR input canceled

But it was too late, the installer is already running in the background;

![ouda4bg](https://cloud.githubusercontent.com/assets/239193/13301618/cbdc1fd0-db13-11e5-93d7-da3772cf204b.png)

Which again, requires a restart to fix. I'd say the update triggers every 8-10 minutes.

**Comment by zanderz** [comment]
Isn't this the same as https://github.com/keybase/client/issues/2115?

**Comment by zQueal** [comment]
It seemed unrelated at the time but you're probably right. Reguardless, it looks as though it's been fixed;

    λ keybase update check
    - INFO Checking for update, current version is 1.0.13-20160223105128+aaabcc9
    - INFO Using updater source: Remote (https://s3.amazonaws.com/prerelease.keybase.io)
    - INFO Request "https://s3.amazonaws.com/prerelease.keybase.io/update-windows-prod.json"
    - INFO Checking update with version: 1.0.13-20160223105128+aaabcc9
