### ISSUE TITLE
KBFS Storage Location

### ISSUE THREAD

**Issue by zQueal** [keybase/client#2123]
It's not entirely clear where files are being stored. On the Windows client, when connected to KBFS I can access any file on the KBFS by navigating to `K:`, however, if I've viewed the files in a folder the folder has a weight -- which does not forebode well for my tiny SSD. (if they are in fact being downloaded to my SSD)

Could I get some clarification on what's happening when I connect to a folder on the KBFS? Are all files in said folder downloaded automatically in the background, or only as opened? For example;

`User A` has a shared folder with `User B` which is at `/keybase/public/UserA,UserB`. `User B` checks out the folder and turns out there is 1GB of files in it. Does `User B` automatically download all 1GB of files in the folder? Or only as he opens them? If `User B` __does__ automatically download all 1GB on connecting to the folder this is a pretty big issue--for me anyways. Mainly because there doesn't seem to be a way to __remove__ content once it's connected. I've been checking the documentation to no avail. (I try `rm -rf folder` but get a permission denied error)

Would it be possible in a future build to customize the location of downloaded files? I have a 2TB storage HDD @ `D:` which would be no big deal if it downloaded the contents of all the folders.

I hope that's clear enough as a coherent thought.

**Comment by cjb** [comment]
Nothing should ever be downloaded to your SSD.

**Comment by strib** [comment]
Yup, we currently don't store anything (even a cache) on disk.  The only disk usage caused by the running is for keybase log files.

This could change in the future, but for now everything is completely network- and memory-based.

**Comment by zQueal** [comment]
Wow, that's simply amazing! I read a bunch on the FS and that wasn't apparent to me, so either it's obvious and I missed it, or maybe it's not very well documented yet?

**Comment by strib** [comment]
There's this sentence in https://keybase.io/docs/kbfs:

> Unlike Dropbox, Google Drive, and Box, there is no sync model. The files stream in on demand.

But I guess it's not super clear. Thanks for the feedback.

**Comment by strib** [comment]
Oh, also from https://keybase.io/docs/kbfs/understanding_kbfs:

> “Filesystem” means that there is no sync model -- files stream in and out on demand. Among other things, that means that files on KBFS don’t take up space on your devices.

**Comment by zQueal** [comment]
I've only ever seen the first instance.

> “Filesystem” means that there is no sync model -- files stream in and out on demand. Among other things, that means that files on KBFS don’t take up space on your devices.

Seems clear enough!
