### ISSUE TITLE
Behavior of "Log in as another user" is highly unintuitive with respect to obscure "Always stay logged in" option.

### ISSUE THREAD

**Issue by Hexstream** [keybase/client#21245]
On desktop, I DO NOT want to "Always stay logged in", because it's trivial to use my password manager anyway. On mobile, I DO want to "Always stay logged in", as I'm doing with most of my accounts, to make sure I always get notifications in real time (unless on "Do not disturb").

Now, if the obscure (?) "Always stay logged in" option buried in `Settings → Advanced` is NOT checked, then selecting "Log in as another user" *immediately logs you out*, which is **not intuitive at all**.

Note that if I *explicitly* try to log out, then by default I'm asked to enter my password to verify that I'll be able to log back in. So it really makes no sense that I get immediately logged out without warning if I'm just trying to *login to an additional account*, just because the very remote "Always stay logged in" has been left unchecked. I think it's entirely reasonable to want to be able to login to multiple accounts simultaneously while NOT "always staying logged in"...

I wonder if the "Always stay logged in" option should also appear on the login page (maybe as "Remember me") or something...

(Sorry for not explaining this better but I'm very busy with other stuff...)

**Comment by heronhaye** [comment]
The behavior you want is that as long as Keybase is running, you won't be asked to reenter passwords even with switching, but if Keybase restarts, then any user without "always stay logged in" will need to re-login?

**Comment by Hexstream** [comment]
Yeah, that sounds like what I want. I'm not sure why it would be otherwise...
