### ISSUE TITLE
Had waiting for 7days for reset account but still cant login

### ISSUE THREAD

**Issue by kevinrfasha** [keybase/client#21259]
Hi, my account name was Kevinrifal . Im waiting reset my account coz my phone was reset into factory mode and today is the 7th day and i still cant login or didnt get the code or link to reset my password or login into new device pls can u send me the link or something?

**Comment by zapu** [comment]
You should have received link to reset your account in SMS to the phone number that was added to that account.

**Comment by zapu** [comment]
Further investigation shows that we couldn't text you the reset link because of carrier error. Can you confirm that your phone still works and can receive texts?

**Comment by kevinrfasha** [comment]
Today my phone was offline (low battery and airplane mode), can u send me
the reset link tommorow? Just message me through my number +6281311860271
coz i had already waiting for 7days .
Thanks for your advice sir.
Have a good day.

Regards,

Kevin

Pada tanggal Sel, 26 Nov 2019 22.13, Michał Zochniak <
notifications@github.com> menulis:

**Comment by kevinrfasha** [comment]
> Further investigation shows that we couldn't text you the reset link because of carrier error. Can you confirm that your phone still works and can receive texts?

Definitely yes , my phone still works and now i can recieve the link. Can u send my the link right now? Or a soon as possible as u can do that. 
Thanks for your advice.

**Comment by kevinrfasha** [comment]
This is my proof sir. Now my phone online again.
![Screenshot_20191126-225557](https://user-images.githubusercontent.com/50563377/69650055-99d66d80-10a0-11ea-8d86-ac745b34ea0d.png)

**Comment by zapu** [comment]
We try to send the links every day, so you should get another link to complete reset tomorrow. If this doesn't happen we can assist more, manually. Let's see what happens in about 12 hours.

**Comment by kevinrfasha** [comment]
Why my funds of wallet gone and my address of wallet changed? May i
transfer my old wallet funds into new account?

Pada tanggal Rab, 27 Nov 2019 01.05, Michał Zochniak <
notifications@github.com> menulis:

**Comment by maxtaco** [comment]
sorry no, we don't have your keys
