### ISSUE TITLE
please help me

### ISSUE THREAD

**Issue by ndgamer** [keybase/client#21254]
My computer just reset and forgot to back up all my keybase data is gone I just reset the account they say wait 7 days does the account reset finish losing all xlm? please help me

**Comment by peterroth** [comment]
If you don't have any other device or paperkey to restore the account, yes, you lost XLM and everything you had there.

**Comment by PABcoin** [comment]
can you delete all the devices you can log in, and wallet xlm intact

**Comment by mbloms** [comment]
> can you delete all the devices you can log in, and wallet xlm intact

No _everything_ is lost on account reset. Keybase doesn't have any of your data.
