### ISSUE TITLE
Debian/Ubuntu .deb package issue: 'Problem parsing dependency Depends'

### ISSUE THREAD

**Issue by brbsix** [keybase/client#2129]
Running `sudo apt-get update` today (coinciding with the [v1.0.14-0](https://github.com/keybase/client/releases/tag/v1.0.14-0) release presents me with the following error:

> Reading package lists... Error!
> E: Problem parsing dependency Depends
> E: Error occurred while processing keybase (NewVersion2)
> E: Problem with MergeList /var/lib/apt/lists/dist.keybase.io_linux_deb_repo_dists_stable_main_binary-amd64_Packages
> E: The package lists or status file could not be parsed or opened.

*dist.keybase.io_linux_deb_repo_dists_stable_main_binary-amd64_Packages* reads as follows:

> Package: keybase
> Version: 1.0.14-0
> Architecture: amd64
> Installed-Size: 33876
> Maintainer: Keybase Bugs <bugs@keybase.io>
> Depends: 
> Priority: optional
> Section: misc
> Filename: pool/main/k/keybase/keybase_1.0.14-0_amd64.deb
> Size: 5639838
> SHA256: f58114299f06a8ddda009f8cb1b51f9d925c7eed40d0df2fee899352bfcce2af
> SHA1: 326f8a901350fa3998c8f0cda34ab81abb45be85
> MD5sum: 5a5748b57e9f4157e67863fa8d02ebe7
> Description: Keybase's command line client
> 

I suspect the empty *Depends:* line is causing the issue.

Perhaps related to f27b600ec78b78ad69f5020f81bf514b04949fff?

**Comment by auralon** [comment]
I'm also affected by this issue.

**Comment by zertrin** [comment]
Same problem, messes with the munin monitoring that checks every hour for new updates of the system and fails because of this issue, resulting in an alert email per hour.

I have commented out the keybase repository in `/etc/apt/sources.list.d/keybase.list` in the meantime...

**Comment by cjb** [comment]
Thanks everyone, we'll fix this soon.

@oconnor663 Dependencies is interpolated in all modes, but only set in the prerelease mode.

**Comment by oconnor663** [comment]
This should be fixed now with version 1.0.14-1. @brbsix and others, can you confirm?

**Comment by brbsix** [comment]
Confirmed it's fixed in the latest revision. Thanks
