### ISSUE TITLE
keybase login: ERROR Bad key family: No key found

### ISSUE THREAD

**Issue by sheldonh** [keybase/client#2130]
When I try to `keybase login`, I get `keybase login: ERROR Bad key family: No key found for ...`.

I choose to sign this install of Keybase with GPG (4) and ask for Keybase to use GPG commands to sign the installation (1). I then select my key, and get the error described above.

I've seen closed issues with the same error message, but I'm using keybase-1.0.14-0 (on Ubuntu 15.10 amd64) and the issue was fixed in keybase-1.0.11.

Debug log attached.
[keybase.txt](https://github.com/keybase/client/files/146501/keybase.txt)

**Comment by maxtaco** [comment]
Likely the cause is that your key is expired. Can you update it on the web
site and try again?

**Comment by sheldonh** [comment]
My key is valid until 2016-10-29. But I re-uploaded it anyway. I now get two NOTICE messages before the error.

It might be worth mentioning that I went through uploading my key to the website and verifying my identity with Github *before* I started with `keybase login`. Was that a mistake? If so, is it recoverable?

Debug log attached.
[keybase.txt](https://github.com/keybase/client/files/146544/keybase.txt)

**Comment by maxtaco** [comment]
Ah, ok, I'm back at my machine. Go OpenPGP's is puking on your public key. I will take a deeper look.  You're right that the key wasn't expired.

Our old flow didn't require your username, it would infer based on your public key.  But we're going to change that

BTW, this bug is repro'able simply via:

```
keybase id sheldonh@github
```

**Comment by maxtaco** [comment]
Seems like the error is this:

```
2016-02-25T08:36:55.310540 ▶ [DEBU keybase log.go:30] 043 Key parsing error: Too many keys (2) found
```

**Comment by sheldonh** [comment]
Thanks. Looking at the output of `gpg --list-keys`, I did have two keys with the same id. Goodness knows what happened there. Anyway...

I exported my key and imported into a fresh keyring. Now I get:

```
ERROR Sigchain specified that KID 01018422197bcdd7e52ed5fe963820b0353be4c978a4b9aada23a3289e6709c267190a is a PGP key with hash c5131a5d743b393cb76cfcb50067091fcfdd14e547eab37964a582fb6c20a9fa but no version of the key with that hash was found (error 901)
```

In issue #1908, you changed something in the DB on your end to resolve that issue. Perhaps I need the same now?

Debug log attached.
[keybase.txt](https://github.com/keybase/client/files/146615/keybase.txt)

**Comment by maxtaco** [comment]
Hah, had you not updated your pgp key the first time, you would have been OK.  But we have a feature that "pins" the exact PGP key to your signature chain, so we can't perform a server-side swap.  That's kind of the point, to prevent a compromise of our servers.

But good news, I'm working on a fix in our Go client to just merge the two keys and keep chugging merrily along. This is the second such complaint we've had this week (some version of GPG must have some bug somewhere), so it's worth a fix. Stay tuned!

**Comment by maxtaco** [comment]
See PR: #2131, which has a fix

**Comment by maxtaco** [comment]
Look for this in v1.0.15, but feel free to reopen if the fix doesn't work.

**Comment by jeremiah** [comment]
I just hit this on keybase (1.0.14-1) running on Debian testing stretch/sid.

**Comment by jeremiah** [comment]
keybase-latest-amd64.deb is at (1.0.14-1). Is there a more recent deb? Or should I download and build the client from GitHub?

**Comment by maxtaco** [comment]
@jeremiah  what's your keybase username?

**Comment by jeremiah** [comment]
My keybase username is jeremiahfoster.

**Comment by maxtaco** [comment]
Well this is one I haven't seen before. We have a situation in which our JS PGP library and GPG can read your key but the Go library cannot.  That's common, but in this case,  it's due to a slightly mangled armoring of your public key:

```
+/uGeK0BIALPzgwt46zRqIhPcjh/SmAJm+Z78cTctg3YygxJ2DehJ3mHjyBn5Cs8
BC8XNCdXFaP2XdvSBZo+i9n0RSBiKNyRSFPldFT7h2ufIzQ5kzAx/YUNkYPnJz/L
RfM0dve1bmKfCo9M5kEHtI3icckwZ8DLiUKzNjPspM5rp4uUfS1jxcJgCvkYCspNeQUFsgzpHFUwKERBkW/xHEGLo2zY8m4DclEq16Qmx7BZA+ya1gq+8nZs5WOaXena
7UirB0AErdHlnq/LwsVe8z0wH8Tq5Gs=
=74R+
-----END PGP PUBLIC KEY BLOCK-----
```

Seems like a newline was weirdly dropped toward the end.  Can you reexport your key, and try to update it via the website?  Check for that hanging chad, so to speak...  That would be the easiest way to fix this problem.  We could alternatively fix the Go libraries to be more lenient when parsing armored keys, but that would be pretty low priority seeing how infrequently it comes up.

**Comment by jeremiah** [comment]
Sure, I'll reexport and update via the website. I'd rather not hang Chad for this, I don't think he's responsible. :(

**Comment by jeremiah** [comment]
Fixed the formatting issue, removed chad, everything works.

Thanks!!
