### ISSUE TITLE
Error resetting account

### ISSUE THREAD

**Issue by baserinia** [keybase/client#21309]
My account was in lockdown mode. Mistakenly, I removed my device to rename it but now I'm locked out of the account.  My username is "baserinia".

When I try to login my account using the client I get this: "Cannot add a new device when all existing devices are revoked. Reset your account on keybase.io. Error code 218: GENERIC in method keybase.1.login.login"

When I try to reset or delete my account on keybase.io I get this: "Your account is in lockdown mode. You can delete your account in the Keybase client."

All I want at this point is to reclaim my email address because I cannot even use it for a new account. What are my options?

**Comment by baserinia** [comment]
Can someone let me know what I can do about a locked down account with no devices?

**Comment by Brianetta** [comment]
You can't do anything with it.

**Comment by baserinia** [comment]
Thanks! Sounds like a major design flaw. At the very least, I should be able to delete the account.

**Comment by Brianetta** [comment]
You can't prove it's yours, though.

**Comment by baserinia** [comment]
You mean I cannot prove the email address, that I used to create the account, is mine? Then how do you think I verified the email address in the first place? My problem is that my primary email address is locked in and apparently there is no way to use it to create even a different account.

**Comment by Brianetta** [comment]
You can't prove that the *account* is yours. The email address is a matter for Keybase staff to address. It might be worth tagging @malgorithms to see if anything can be done to free it up.

**Comment by baserinia** [comment]
@Brianetta Thanks! I don't care about the *account* per se, but this thread shows exactly why Keybase is not ready for prime time. Requiring an admin of a centralized service to fix issues with regard to a critical piece of info such as a PGP key is just unacceptable.

**Comment by heronhaye** [comment]
@baserinia You can use plus addressing for your new account. For example, if your email is alice@example.com, you could put your email as alice+keybase@example.com. Unfortunately, since you were in lockdown mode and lost access to all your devices, your account cannot be deleted or reset.
