### ISSUE TITLE
Airdrop issue

### ISSUE THREAD

**Issue by dariopascalw** [keybase/client#21327]
Hello! After I have registered, confirmed and everything I just open my wallet and start to add the paper keys, after that I just pressed the bottom "become a lucky airdropee" but I still receive the message "you are not qualified" I added a lot of info, got all the three point ("paper keys, verified phone number and beautiful smile") but still nothing 😔😔 someone can help??

**Comment by joergpanke** [comment]
Das gleiche Problem keiner kann helfen was können wir machen

**Comment by joergpanke** [comment]
Ich meinte keiner kann helfen

**Comment by joergpanke** [comment]
keiner kann helfen

**Comment by dariopascalw** [comment]
Ps: name of account: dariopascale

**Comment by iamdanialafridi** [comment]
hey my account  name danialafridi i add everything but still red cross on mobile phone number  my number is verified but still not qualified and red cross iam seeing

**Comment by dariopascalw** [comment]
Your country is not qualified as Canada for example, I have all the three cross but still i"m not able to join my account name is dariociccio

**Comment by devWithGit** [comment]
Hello, my account name is bashkeybase, I did everything, I did not use any not or even try to cheat system, but I was not lucky

Does it mean that I cannot never join or earn?

My country is Nigeria

**Comment by maxtaco** [comment]
![image](https://user-images.githubusercontent.com/866815/70337047-51454f80-1818-11ea-8ee9-1ab7a8bd1a4f.png)
