### ISSUE TITLE
Account reset doesn't work, like at all.

### ISSUE THREAD

**Issue by CrankyDragon** [keybase/client#21353]
Wanted to move keybase to a new machine, tried logging in using my credentials, and since I didn't have access to my old machine so I opted to reset, thinking that would be straight forward... I was wrong. By resetting my account got locked, to unlock it I need access to my old machine which I did an OS install. I can't delete my account because its locked. I can't seem to contact support because my account is locked. How do I unlock/reset/delete my account?

**Comment by heronhaye** [comment]
Hi, as is mentioned in the Lockdown Mode docs (https://keybase.io/docs/lockdown/index), account reset or delete is not impossible while in lockdown mode. Sorry.

**Comment by CrankyDragon** [comment]
I didn't issue a lockdown of my account, issuing a reset of my account did, locking me out. In the very least I want to be able to start over... there has to be some way of doing that. Can you guys delete it?
