### ISSUE TITLE
Confirm account for airdrop from Canada?

### ISSUE THREAD

**Issue by GregoryGHarding** [keybase/client#21372]
Hello,
I understand Canada is not on your list, but not because you've been attacked by fake accounts from there, only because you cannot verify bulk number purchases.

Is there a way for me to confirm with you that I am legitimate while being from Canada to participate in airdrop?

I have several verified accounts signed with keystore.

**Comment by GregoryGHarding** [comment]
Bumpity.

**Comment by maxtaco** [comment]
We would love to but can’t do it scalably. Sorry.
