### ISSUE TITLE
keybase fs clear conflict ... that can't be cleared

### ISSUE THREAD

**Issue by taw00** [keybase/client#21378]
```
keybase fs clear-conflicts /keybase/private/me
▶ ERROR PrevRoot A_BIG_HASH doesn't match expected A_DIFFERENT_BIG_HASH
```
my log id: db4b04afe4b6ca38f5e79b1c

**Comment by strib** [comment]
Thanks for the report.  Hmm, that is pretty weird.  This _might_ indicate a temporary bug in an in-memory cache, in which case it might be worthwhile to try restarting the Keybase app and trying `clear-conflicts` again.

if that still doesn't work, you can:
* Make sure that anything you have in that local version of your directory, that hasn't yet been uploaded to the Keybase servers, is backed up off of Keybase somewhere.
* Completely stop Keybase and KBFS.
* Run this command from a terminal:
```
mv $HOME/.local/share/keybase/kbfs_journal/
v1/01200ddbb35f03dcfc4c25d6751467460d57-3b8ffab7bf6edd33 $HOME/.local/share/keybase/kbfs_journal/v1/3b8ffab7bf6edd33.bkp
```
* Restart Keybase

At that point, your local view should be the same as the global server view, and you can re-try adding the new data to the folder.

Sorry for the bad experience, let me know how it goes.

**Comment by strib** [comment]
Oh and in the latter scenario, you should also do this before the restart:
```
rm -rf $HOME/.local/share/keybase/kbfs_conflicts
```

**Comment by taw00** [comment]
Thank you for responding.
I restarted keybase (`run_keybase -k` and then restarted). I even rebooted. Same error. It's been in this state for a long time, actually.

This may be related: I am on satellite internet. It actually works well most of the time. I can even video conference over it. It's latency prone, but the speed is ... not terrible (it's not good, but it is not terrible). So... that may be a fact here. Lot's of network services do not test on challenging networks.

Anyway. I had to follow your "move the journal data; nuke the conflicts file; and start" process. Now it is working, it seems.

Thanks. -t

**Comment by strib** [comment]
Great glad it's working.  Slow internet or slow disk/cpu might be the reason you were stuck in conflicts mode in the first place.  I'm still not sure about the `clear-conflicts` error you saw, that's a weird one.  Will look out for it in the future.

**Comment by taw00** [comment]
Note: Bandwidth is fast, but occasionally is highly latent.
CPU and Disk are plenty fast (high end machines).
