### ISSUE TITLE
Sorry you are not qualified to join

### ISSUE THREAD

**Issue by rbake69** [keybase/client#21392]
Hi, I live in France
Phone number ok
3 devices ok
But... Airdrop is not following. 
My account is rabo69
Thank you in advance

**Comment by aneesh1000** [comment]
I live in France
Phone number ok
3 devices ok
But... Airdrop is not following.
My account is aneesh
Thank you

**Comment by nilkos** [comment]
I live in Germany 
Phone number ok
3 devices ok
But... Airdrop is not following.
My account is nilkos
Thank you

**Comment by quickly1235** [comment]
I'm in an approved country, Poland with an approved phone number.
Airdrop says I am qualified with 3 devices and "A beautiful smile"
Then after selecting the "Become a lucky Airdropee" button it switches to
"Sorry you are not qualified to join"
My account is quickly123
Thanks for your review

**Comment by unicadesign** [comment]
I live in Italy
Phone number ok
4 devices ok
But... Airdrop is not following.
My account is unica_design
Thank you
