### ISSUE TITLE
Keybase app

### ISSUE THREAD

**Issue by woodsjesse607** [keybase/client#21408]
Can't login my keybase app on Android. It opens but won't go past the loading page when you first open it. I was going to delete and reinstall but don't want to lose my device keys.

**Comment by lauritzt** [comment]
Have you tried force stopping the app in Android's settings? Sometimes Keybase doesn't recognize that it's logged in, but a restart may help.

Do you have access your paper key beginning with `bleak wealth` or another device where you're logged in to Keybase? If you do, you can simply generate new keys for the device where you're logged out.
