### ISSUE TITLE
Encrypted file not showing up

### ISSUE THREAD

**Issue by ggtools** [keybase/client#2145]
Keybase GUI Version: 1.0.14-20160226204353+b6f4dba

tristan0x created a file in the private directory: /keybase/private/tristan0x,clabouisse/obviousness.txt but I cannot see it on my laptop:

    > cat /keybase/private/tristan0x,clabouisse/obviousness.txt
    cat: /keybase/private/tristan0x,clabouisse/obviousness.txt: Input/output error

**Comment by cjb** [comment]
Please could you run `keybase log send` and share the ID with us?

**Comment by ggtools** [comment]
No problem: 577c5e86133c22880576d31c

**Comment by strib** [comment]
Your tracking statement for `tristan0x` appears to be out of date.  There's a GUI bug we'll be fixing soon that keeps us from showing you a popup in this case probably.  But you can try `keybase track tristan0x` on the command line and see if that fixes the issue for you.

**Comment by ggtools** [comment]
OK it fixed the issue
