### ISSUE TITLE
My wallet data changed and I lost my XLM coins

### ISSUE THREAD

**Issue by iqballher** [keybase/client#21458]
Hi admin,
Can you help me. I just reset my keybase account because I lost my paper key.
After I got back in, my wallet data changed and I lost my XLM coins.

Gmail : mdhellena@gmail.com
Github : https://github.com/iqballher
Account Keybase.io : https://keybase.io/iqballher
Username Keybase.io : IQBALLHER

Thanks admin.
![Screenshot_20191209-013824](https://user-images.githubusercontent.com/54282182/70394232-b9b54c00-1a25-11ea-877e-081aaba52065.jpg)
I hope you can help to restore my coins from the previous swallow data. I really need the coin.

**Comment by maxtaco** [comment]
Sorry no, we don't have your keys
