### ISSUE TITLE
Client doesn't verify GitHub proof

### ISSUE THREAD

**Issue by mbloms** [keybase/client#21457]
# Steps to reproduce
* Edit keybase.md signature or payload
* Verify proof from client
* Proof still shows as valid

# Details
I tried tampering with my [keybase.md](https://gist.github.com/mbloms/6e96c7f6e448513bc15fa64947af2868) gist because I wanted to see how the client reports that a signature is invalid.

At first I only changed a few characters in the payload. Proof still shows as valid.
I tried using `keybase id -s mbloms` to make sure that the proof wasn't cached. Still valid.
Then I tried changing the signature. Still valid.
I tried squashing the history so that the original valid signature is not even in the git history. Still valid.
Now I removed the payload entierly and replaced the signature with `null`.

Still keybase says it's valid. It doesn't matter if I use my phone or my computer.
Is this a bug or why does it still think the proof is valid?

```
$ keybase id -s mbloms
- INFO Identifying mbloms
OK public key fingerprint: C708 0729 DBD7 5119 A53D 18AC 7F64 B7A3 F7F6 819E
BTC  bitcoin 1M5ZRjyqJDjVen3Yb3joZp24j2o5Qai84R
XLM  Stellar GDDUEQJUIHVJQDZZDK7WAXMJW4ZOFUVE7TQXG7LFWTQCHL5JNEKLLWP5 (mbloms*keyb
ase.io)
OK "chawlindel" on reddit: https://www.reddit.com/r/KeybaseProofs/comments/dcr0zb/
my_keybase_proof_redditchawlindel_keybasembloms/
OK "mbloms" on github: https://gist.github.com/6e96c7f6e448513bc15fa64947af2868
OK "mbloms" on twitter: https://twitter.com/mbloms/status/1176623629813071873

$ keybase id mbloms
- INFO Identifying mbloms
OK public key fingerprint: C708 0729 DBD7 5119 A53D 18AC 7F64 B7A3 F7F6 819E
BTC  bitcoin 1M5ZRjyqJDjVen3Yb3joZp24j2o5Qai84R
XLM  Stellar GDDUEQJUIHVJQDZZDK7WAXMJW4ZOFUVE7TQXG7LFWTQCHL5JNEKLLWP5 (mbloms*keyb
ase.io)
OK "mbloms" on github: https://gist.github.com/6e96c7f6e448513bc15fa64947af2868 [c
ached 2019-12-08 17:46:36 CET]
OK "chawlindel" on reddit: https://www.reddit.com/r/KeybaseProofs/comments/dcr0zb/
my_keybase_proof_redditchawlindel_keybasembloms/ [cached 2019-12-08 17:46:36 CET]
OK "mbloms" on twitter: https://twitter.com/mbloms/status/1176623629813071873 [cac
hed 2019-12-08 17:46:36 CET]
```

**Comment by rkevin-arch** [comment]
I stumbled upon this and was curious as well, so I MITM'd the `keybase id` traffic. Apparantly it's pulling down https://gist.githubusercontent.com/mbloms/6e96c7f6e448513bc15fa64947af2868/raw/ed3adc55398e85e425f03c9c38bfe81f6cdb5eb6/keybase.md which is your old revision that does have the signature in it. That's probably the underlying reason why keybase handles the changed gist, because under the hood it's using whichever revision the file is at when you first made the proof.

**Comment by mbloms** [comment]
Interesting. That explains why it didn't break when I force pushed over my gist. Weird that GitHub doesn't delete the original blob after I force push over it
