### ISSUE TITLE
Error accessing to my personal private folder

### ISSUE THREAD

**Issue by szaffarano** [keybase/client#21456]
Hello, I have the same error reported in #13222. Recently I changed my computer, and after reinstallingKeybase, I'm not able to access my private folder. I tried doing a rekey with my paper key, but it seems that it doesn't work.

my log id: 0a80ae9852e2f2d97a64951c

Thanks!

**Comment by strib** [comment]
Looks like your folder has been unkeyed since July 2016, and has basically no data in it.  It's probably unkeyed due to very old bugs that haven't been fixed yet.

If you want us to reset your folder, please run this command on a currently-valid keybase device, and substitute the current date and time where indicated:

```
keybase sign -m "<DATE_AND_TIME>: Please reset folder /keybase/private/szaffarano because all the devices that have access have been revoked."
```

and post the results here.

**Comment by szaffarano** [comment]
BEGIN KEYBASE SALTPACK SIGNED MESSAGE. kXR7VktZdyH7rvq v5weRa0zkHSiu0p 4kWMZhCUt8R524W V86juJI55tLN1OW 1en6uR2Vb31c5ox UUkie0CyUBhO5Sb h25keeHHQcLJ2Lu XEQ1pFOqpMkNs02 LFW5YXiopUq7eqA 0ubFbzN4kBzsr4i eSRGQP2wy2d74ku 7rzOZWygOfVuo8v wU75UQ26ZbocacY 49OJIcep4ekBCOG aEXWyPheJ7z3VR0 xuI7sWfjXQJOIDn adTDeAYEX1XyLcH wSEN6mvle3qFhgA 6UYzlWqqctqV2Yy oE5Yyd7ymAWUmuR QO3iEYFVeYZNCpP AeWiWWqv4aW3wRF cYwxm4oAKGxxYL2 bC6VfomdKgXde. END KEYBASE SALTPACK SIGNED MESSAGE.

**Comment by strib** [comment]
I reset the folder.   Now run this command on a Keybase device:

```
keybase fs reset /keybase/private/szaffarano
```

After that you should be good to go. Please check it out and close this if everything seems ok.  (Might require a Keybase restart.)

**Comment by szaffarano** [comment]
Thanks!
It worked fine :)
