### ISSUE TITLE
Keybase troubles plz help

### ISSUE THREAD

**Issue by asmerella** [keybase/client#21462]
So my device got factory reset and when I try to login on the app it wants the 9 word code. I lost the 9 word code. So if I reset my keybase I will lose my steller spacedrop?

**Comment by peterroth** [comment]
If you didn't add any other device, yes.
However, you shouldn't be able to join to the Airdrop (spacedrop) if you didn't add at least a paper key and one another device (which means, you should be able to restore your account).

**Comment by maxtaco** [comment]
Sorry, no, we don't have your keys
