### ISSUE TITLE
12GB of backed up Keybase.app versions

### ISSUE THREAD

**Issue by farktronix** [keybase/client#2146]
I have 146 copies of the Keybase.app in /private/var/folders/47/nrbhwsxd03q1v9c25lxbryxh0000gn/T/KeybaseBackup which adds up to 12GB of used space.

[keybase-ls.txt](https://github.com/keybase/client/files/149081/keybase-ls.txt)

Keybase GUI Version: 1.0.11-20160215170009+d9662a2

**Comment by maxtaco** [comment]
Thanks for the feedback. I believe this is now fixed in 1.0.14 and above.

**Comment by farktronix** [comment]
Thanks for the speedy answer!
