### ISSUE TITLE
Issues while testing private space versioning with git

### ISSUE THREAD

**Issue by tristan0x** [keybase/client#2150]
Hello guys,

I encountered bunch of issues while testing KeyBase filesystem on Linux.
After a successful `echo Hello World > /keybase/private/tristan0x/test` and sharing small files, I tried syncing a Git repository to see how it goes. The idea is to both stress your service and see if the private space can be versioned (like [etckeeper](https://github.com/joeyh/etckeeper)

### Creating bare repository:

Before creating a bare repository in /keybase/private/tristan0xś root, I made one in the `tests` subdir, and tried pushing a project I am working on.

#### IO error while initializing the Git repository:
```
cd /keybase/tristan0x/tests
git init --bare docido.git
fatal: cannot copy '/usr/share/git-core/templates/hooks/post-update.sample' to '/keybase/private/tristan0x/tests/docido.git/hooks/post-update.sample': Input/output error
```

#### 2nd attempt

The next tentative passed but took almost 10 minutes to complete.

### Pushing stuff to that repository

```
cd ~projects/docido
git remote add keybase /keybase/private/tristan0x/tests/docido_v2.git
git push keybase master
```

I experience IO error. He is the output of the stuck command:

```
Counting objects: 15941, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (4785/4785), done.
remote: fatal: write error: Input/output error
```

It always fails when objects compression start.

I tried to send you guys some logs with the `keybase log send` command, but it times-out:

```
keybase log send
This command will send recent keybase log entries to keybase.io
for debugging purposes only.

These logs don’t include your private keys or encrypted data,
but they will include filenames and other metadata keybase normally
can’t read, for debugging purposes.

Continue sending logs to keybase.io? (type 'YES' to confirm): YES
▶ ERROR API network error: Post https://keybase.io/_/api/1.0/logdump/send.json: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
```

**Comment by maxtaco** [comment]
Is your network flakey?

**Comment by tristan0x** [comment]
I don't think so.

**Comment by strib** [comment]
Huh, bummer.  It's especially weird that `log send` times out if you weren't having other network issues.  Can you please try it again when you're sure you have a stable connection?

That said, on Linux, you shouldn't get I/O errors as a result of a slow network -- it happens on OSX, but on Linux there's no default timeout on operations.  So to really know what caused the I/O errors, I'll have to look at the logs.  You can also try copying `/.cache/keybase/*log` to `/keybase/private/strib,tristan0x` (or post it in the private online location of your choice if that doesn't work either).

Finally, I'll note that git doesn't really fully work yet, since we don't support exclusive file creations yet (which git uses for file locking).  But that wouldn't manifest itself like that, instead your index would look corrupted or conflicted.  But fixing that is on the roadmap!

**Comment by tristan0x** [comment]
Thanks for the quick feedback.
Logs have been copied to `/keybase/private/strib,tristan0x/keybase-client-issue-2150`

Regarding the network issue, I still cannot upload logs thru keybase API.
I got a similar issue when running the curl command to track you: `curl: (52) Empty reply from server`
The `keybase track strib` command ran smoothly though.

Regards

**Comment by strib** [comment]
@tristan0x: looks like you posted a now-deleted message here (I got it by email) about sharing the logs with me, but they are no longer in our shared folder.  Looking at the folder history, it seems you explicitly removed them.  Anyway, if you still want me to look at them, just let me know where to find them.  I just wanted to let you know I can't find them now.

You can also email me using my github username at keyba.se if you don't want to discuss it on github.

**Comment by tristan0x** [comment]
@strib I removed the github message because the upload failed. I will look at  the logs on Monday evening next time I will be in front of my workstation.  I'll let you know. 
Thanks

**Comment by tristan0x** [comment]
My network was flakey after all. The DHCP server gave me stale DNS server. Now it is running smoothly.
