### ISSUE TITLE
AUR build seems to cache the client git repo, preventing updates

### ISSUE THREAD

**Issue by oconnor663** [keybase/client#2151]
@pritambaral reported this issue at https://github.com/keybase/client/issues/2024#issuecomment-189717654. Creating this one to avoid cluttering the original.

**Comment by pritambaral** [comment]
AUR builds don't cache the git repo, a specific option in `/etc/yaourtrc` does

On a fresh build of `keybase-git` without yaourt, where makepkg does a git clone and builds off of master, I still get 1.0.13 as of today. Running a `git log` (makepkg does a bare clone, so you have to use the GIT_DIR env variable) shows commit `cc71b63` at the top

**Comment by oconnor663** [comment]
(I don't need to set `GIT_DIR`. For me, running `git log` in the bare clone works fine. Normally I wouldn't pay attention to something like that but since we're trying to figure out *what the hell could be going on* I figured I should pay attention to everything :)

I'm worried there's going to be some subtle difference between what's happening in the bar clone that happens in the `makepkg` directory, and the secondary clone that `makepkg` puts in the `src` directory. Could you give me the output of all of these?

```
(cd client && git log -1 --oneline)
(cd client && GIT_DIR=. git log -1 --oneline)
(cd src/client && git log -1 --oneline)
(cd src/client && GIT_DIR=.git git log -1 --oneline)
./src/client/packaging/version.sh prerelease
```

Also, do you know if commenting out your settings in `/etc/yaourtrc` fixes all this? I don't think that should affect `makepkg`, but who knows at this point :|

**Comment by pritambaral** [comment]
> (cd client && git log -1 --oneline)
> (cd client && GIT_DIR=. git log -1 --oneline)

Both produce: `cc71b63 Fix up flow types`

> (cd src/client && git log -1 --oneline)
> (cd src/client && GIT_DIR=.git git log -1 --oneline)

Both produce: `33bc1eb add the calls to /opt/keybase/post_install.sh back in`

> ./src/client/packaging/version.sh prerelease

Produces: `1.0.13-20160227230241+33bc1eb`

Running a fresh `yaourt -S keybase-git` now, with `DEVELSRCDIR` commented out right now, though I don't expect any difference (unless origin/master itself has changed).

I will then try a build with the `source` entries in PKGBUILD edited to checkout `origin/master` explicitly.

**Comment by oconnor663** [comment]
Interesting. So the checkout under `src/` is *behind* the checkout at the root, even though the latter is supposed to be downstream of the former. I'm curious what's in your `src/client/.git/config`. Here's mine:

```
$ pwd
/tmp/tmp.HKX7SOiIV7/keybase-git
$ cat ./src/client/.git/config 
[core]
        repositoryformatversion = 0
        filemode = true
        bare = false
        logallrefupdates = true
[remote "origin"]
        url = /tmp/tmp.HKX7SOiIV7/keybase-git/client
        fetch = +refs/heads/*:refs/remotes/origin/*
[branch "master"]
        remote = origin
        merge = refs/heads/master
```

Any chance you have something special in `/etc/makepkg.conf` or `~/.makepkg.conf`? Otherwise I'm out of theories.

**Comment by pritambaral** [comment]
Both fresh `yaourt -S` without `DEVELSRCDIR` and a fresh `makepkg` without yaourt work correctly. I must have somehow had `src/client` cached when I first tried to repro this.

This issue can be closed now, sorry for my clumsiness. :-/

**Comment by oconnor663** [comment]
No worries, always good to kick the tires.
