### ISSUE TITLE
Reset

### ISSUE THREAD

**Issue by dmochustell** [keybase/client#21525]
Hi!
I did reinstall of keybase. I lost my paper keys when i was cleaning my room (ya im stupid). Is it any way for me to log in to keybase on app on the same device like before?

In my opinion paper keys are useless and thats not fair when i lost em and i can prove account is mine but still cant log in. however I should have access to my account

My kb: dmochu
Email: konraddmo@onet.pl

**Comment by maxtaco** [comment]
RTM
