### ISSUE TITLE
Keybase stellar airdrop shutdown

### ISSUE THREAD

**Issue by Hordunlarmy** [keybase/client#21522]
i think keybase just shutdown the airdrop. wasnt there supposed to be a month notice??. 
anyone still has their badge on?? mine s gone

**Comment by esbee10** [comment]
I'm also begging especially to us in poor countries like Nigeria, we are kids and trying to develop. We are learning and keybase drop is helping us. I come to know about keybase somedays ago. Keybase can just disqualify countries with the most fake accounts could have save us.
