### ISSUE TITLE
Feature Request: Chat: Mark messages as "unread" (like Slack)

### ISSUE THREAD

**Issue by powerman** [keybase/client#21586]
There is very useful Slack feature "Mark unread" which I miss very much in Keybase chat.

Sometimes you open chat to glance new messages and notice some new message which require some urgent reaction/response, but don't have time to do this right now. Ability to "mark unread" this message (and thus restore "new" notification on whole chat channel) is an easy way to set up a reminder for myself to return to this chat channel soon, when I'll have time to handle that message.

Without this feature either important messages will be often "lost", or people will have to react immediately on incoming messages which will hurt their current work.

**Comment by shanness** [comment]
Agreed, this would be a great addition, and is also my most missed feature (as a regular slack user).

**Comment by powerman** [comment]
Wow! After years of bugfix/security updates maintenance Keybase gets a new feature!!! :tada:
