### ISSUE TITLE
Todays Airdrop

### ISSUE THREAD

**Issue by zakatdee** [keybase/client#21602]
Hi, and thanx for a awesome wallet, the whole team thing seems great!

I was able to qualify for the last airdrop but I have not recived anthing so I wanna check if there is something wrong? 

See image on my wallet
![38A84A7E-6279-4220-A9E6-B6288FCAA6D0](https://user-images.githubusercontent.com/58863739/70832878-85130d00-1df6-11ea-9b86-7901aafc68f7.png)

**Comment by Trinitas** [comment]
Same here. I was qualifyed for the airdrop and now it says I'm not, because I reset my account

**Comment by zakatdee** [comment]
I am qualified for the airdrop and I have not got a message that Im not.

**Comment by zakatdee** [comment]
It would be really sad if I was one of the 100,000 disqualified garbage accounts :( 

Can some admin help me check this?

**Comment by mdixie** [comment]
I also qualified, but unfortunately did not receive my xlm in my wallet either.
Public address is.
GDUQYIFCO4O5XXTFB4IJ3GNRRZQNSG7ASTFP5LFTKIRAFKFIIM2RLGLK

**Comment by zakatdee** [comment]
This does not feel fair at all @mdixie 

It would me better if Keybase made a KYC verification of us who did not cheat or had garbage accounts :(

My Public address is:GC3YWCKPO3VTD3NG4ZM4HUYS5BVKMARRJBSSEMWIVUAM232X73GIZ5ND

**Comment by murad76** [comment]
Not recieved stellar airdrop this month. Last month recieved but this no. Whats wrong??? 
Stellar address in keybase app is
 GAZW5TAOGJV5VYKRMH7GAB5ZW3RKIXRFH2QICZJKTYSUP56E3AO5D4HZ
If there any admin, pls check it

**Comment by waggzbtc** [comment]
I didn’t receive any drop for November nor this latest. I was verified immediately then was unverified which triggered me to contact support, who then reverified my account to be part of the drop. 

Has anyone gotten any updates on how to determine if your account was among those accounts that were disqualified? My wallet and stellar account still exists. But I can’t find anywhere check current status. 

My public wallet is: GD4J76GJZV3VQVKFXQDCAXF5J3ISOQF5HNOY72EH662TYOSF257T33OS

**Comment by zakatdee** [comment]
Is'nt there any admins here?  It says support here on website. Do you know @akalin-keybase ?

**Comment by waggzbtc** [comment]
Nope. Admins aren’t here. They’re not answering anyone. That’s unfortunate.

**Comment by esbee10** [comment]
I'm saying SDF has no right to call off spacedrop, but atleast consider poor people like us in Nigeria who don't even know what hack is all about. Assist us pls. You can disqualify the country with the increasing fake accounts and could have saved us.

**Comment by miss-evelina** [comment]
Hey, me and my husband made the airdrop. He got his XLM but not me :( Does anyone know why?

My public address is: 
GDGVV7UMWRPGCDT2HQGHLWFLDN36ZQWPCL5ZGT3PSL7CKVWA2VZRS4BZ

**Comment by 101010101010101** [comment]
Hey, I also did not receive my Stellar Lumens airdrop for the month of December. 

My XLM address: GAWGRTZ4XUGU2N5YJBCHDTPXTAFPLASJSCSY2X6ZXBIGHRGQIHQGXIUZ
