### ISSUE TITLE
Keybase ignoring questions about ending Stellar Promo

### ISSUE THREAD

**Issue by waggzbtc** [keybase/client#21614]
Is it me or does it seem I read post after post asking why an account was dropped and Keybase doesn’t repsond? I can’t telL if I’ve been dropped or not. My wallet is empty. But sending of stellar is still being processed. 

Hey, Keybase! Step up to the plate!!! I feel you made the promise of handing out stellar and have now decided (or planned it this way to get people to download your app) not to give it out. 

I feel duped.

**Comment by anwar2702** [comment]
hey, this just a gift :"v
if SDF say stop, keybase can't do nothing :""v

**Comment by waggzbtc** [comment]
The notice said they were finding fake accounts and decided to just kill it because it was too much work. I was enticed to sign up with the impression that I was going to be given lumens for trying their platform. I held up my end. Now, conveniently, Keybase pulls the plug. Why should I lose out and Keybase is left with a bet positive?

**Comment by esbee10** [comment]
I think they can still do it by disqualifying the country with the most fake accounts. It can still be continued to support poor countries like Africans, Nigeria, etc
