### ISSUE TITLE
Airdrop sudden closure. Advice to Keybase

### ISSUE THREAD

**Issue by esbee10** [keybase/client#21618]
I think the aidrop unannounced closure made people feel bad. I'm not saying SDF has no right to stop whenever they feel like, but the complaint they made can be at least dealt with. Disqualify any country with the highest number of fake accounts. I'm saying this because I personally have been informing people to join. These people are really poor and need money to support their pursuit for sound education. We live in Nigeria, we are poor and I don't think we even have the knowledge to hack or make fake accounts. Please consider us. Give us a chance. I got it once because we got to know keybase early this month. Thank you.

**Comment by thuca1992** [comment]
Nigeria has the most fake accounts. are you kidding
