### ISSUE TITLE
Keybase is full of BS?

### ISSUE THREAD

**Issue by waggzbtc** [keybase/client#21626]
So, Keybase has cancelled the Space Drop. They claim that it’s because of fake accounts. But I’m calling BS. They cancelled everyone after the 1st 200k accounts no matter what (I say this because if they’d done as they said they did, then I and many others wouldn’t have been booted). Then say they split the remaining funds up evenly amongst the “real” accounts. 

But...Something is fishy. 

I’m looking through keybase’s space drop payments. And it seems their source wallet has been creating new wallets and depositing the exact amount in each new one that should have been deposited in existing accounts. Why would they need to create so many new wallets if they’re supposedly SHRINKING they number of wallets?! Why would a source wallet need to create a new one?! There’s one new wallet sitting somewhere with the XLM that was promised to me and I’m sure there are numerous other new wallets with other’s XLM in it, and these new wallets belong to Keybase. 

And conveniently, Keybase admins won’t address anyone’s questions on this page and continue to ignore everyone. 

My account is real and verified. But keybase unverified me (so that I wouldnt get paid) and left my account open (must NOT be one of the accounts that they find to be unworthy of staying open, just not worthy of being paid). 

Read their BS excuse here: https://keybase.io/a/i/r/d/r/o/p/spacedrop2019

Here is the link to the SpaceDrop source wallet showing the creation of all these new “ghost wallets”: https://stellar.expert/explorer/public/account/GDV4KECLSZLKRVH4ZTWVAS4I3W2LPAPV66ADFFUZKGIVOTK6GMKGJT53

**Comment by smoochiesmidz** [comment]
wow!
