### ISSUE TITLE
AIRDROP NOT RECEIVED 

### ISSUE THREAD

**Issue by Fmferary** [keybase/client#21628]
Hello keybase my airdrop hasn't drop kindly help out please

**Comment by qamalluddeen02** [comment]
Hello i didn't receive my tokens pls.....
And it's a qualified account already which i qualified for the November giveaway.

**Comment by brandonkal** [comment]
Seriously guys? The distribution is only at 40% at this time. Be patient. I would suggest you ask these questions in the stellar.public #spacedrop channel on Keybase. This isn't an issue with the keybase client code. @Fmferary @qamalluddeen02
