### ISSUE TITLE
Airdrop not received yet!!!

### ISSUE THREAD

**Issue by smoochiesmidz** [keybase/client#21627]
I see that I am not the only one who hasn't received what is due in all fairness. Please honor on your end.

**Comment by laufun** [comment]
Hi, I haven’t received anything and I was marked as having a valid profile and i connected my phone, comp and paper wallet so what’s up?

**Comment by Fmferary** [comment]
Hello keybase I haven't receive my airdrop kindly help out please

**Comment by qamalluddeen02** [comment]
Hello i didn't receive my tokens pls.....
And it's a qualified account already which i qualified for the November giveaway.
