### ISSUE TITLE
Airdrop: ADMIN help... Something is strange :(

### ISSUE THREAD

**Issue by miss-evelina** [keybase/client#21658]
Hey, me and my husband made the airdrop and we where both green marked. Yesterday my husband got his airdrop XLM but not me. I know its not much money but I think that this is a bit unfair cause both of us are equal to the tasks.

Can some admincheck my account and see what went wrong?

My public address is:
GDGVV7UMWRPGCDT2HQGHLWFLDN36ZQWPCL5ZGT3PSL7CKVWA2VZRS4BZ

/Evelina

**Comment by kerbyrok** [comment]
Why did I not receive the airdrop??

**Comment by msimkins** [comment]
The Airdrop is over because of bad accounts, but you may still be in the queue

See: https://keybase.io/a/i/r/d/r/o/p/spacedrop2019

**Comment by kerbyrok** [comment]
Yea I got it thanks didn't realize it took so long to distribute.
