### ISSUE TITLE
Git push is stuck on Syncing encrypted data to Keybase

### ISSUE THREAD

**Issue by ludorumjeoun** [keybase/client#21663]
Git push is stuck on Syncing encrypted data to Keybase.
it's team repo and I can't push it anymore.

my log id: 325744533c1f160c7bad811c

**Comment by strib** [comment]
Thanks for the report.  It looks like one of the local Keybase caches on disk was corrupted somehow.  Not sure how that happened: it could have been a Keybase bug, or just random disk corruption maybe?  I think you can fix it this way:

* Completely quit out of Keybase and KBFS, and cancel any outstanding git commands.
* Run this command from a terminal:
```sh
rm -rf $HOME/Library/Application Support/Keybase/kbfs_block_{cache,metadata}
```
* Relaunch Keybase.

Let me know if that helps.

**Comment by jmdots-green** [comment]
Didn't work for me. :(

**Comment by ludorumjeoun** [comment]
@strib it's working for me. thanks.
I think add feature for kbfs cache clear would be better. :D

**Comment by jeremy-brooks** [comment]
This has happened twice to me in 2022, we had to abandon our repo and create a new one each time, are there any other solutions other than doing this, it is getting to a point where we're thinking about moving away from keybase because of this now?
