### ISSUE TITLE
reset my public kbfs tlf

### ISSUE THREAD

**Issue by lelysses** [keybase/client#21661]
apparently im not able to reset my own kbfs TLF and i have to ask here so can someone please reset /keybase/public/lel? i can't sync my public tlf because kbfs's internal format for public directories changed last year and there's an open bug that public directories in the old format don't sync, so (and correct me if i'm wrong on this next point) im hoping resetting it will convert it to the new internal format. i 100% am aware that there will be data loss and i have backed up everything in that directory.

i see other people doing this have to use `keybase sign` to prove they are who they are so assuming the message itself doesn't exactly matter here is the result of `keybase sign -m 2019-12-16 @ 23:42: Please reset folder /keybase/public/lel because it's the old internal format so keybase fs sync doesn't work`

```
BEGIN KEYBASE SALTPACK SIGNED MESSAGE. kXR7VktZdyH7rvq v5weRa0zkTfvlHa iAOQ3nvymHBdjhC qnHrmC4qmQOIKMR 6qu3mJiNWM5SS05 RZ0xs7AnUJAeIT8 genmGxUFRYp09qc H33qHF5QSAXv389 wR2ZRG23IVHAigQ J6rBNGUIeuknzIz aQlAI4ks6iN9wJQ cAD3uN7JPYLBdTE Wu7X5O1n69Ve5DX yOSKZao0W8Oui3y mdMGiO2VbByGCPC MOpuQKDVGkyShnj CHkYvgAVbq49osZ hEHNWEPGnpbHOFo Cvqnv7T6K04AmUW bfICUtbqdXsuzX5 WQApH6hCbHHboj4 GiH7HRZnpqYrX95 xp5XGI3xPBd5392 OUlMNzCcOy4GR. END KEYBASE SALTPACK SIGNED MESSAGE.
```

if you need anything else to make this happen please let me know — thanks

**Comment by strib** [comment]
I reset the folder.  You are right that it should be re-created in the new format.  But first I think you have to run the following command from a terminal:

```
keybase fs reset /keybase/public/lel
```

After that it should be working as expected, if so please close this out, if not please let me know! 

(We are still planning a process to upgrade these automatically, but not sure when that will happen exactly.)

**Comment by lelysses** [comment]
@strib 
Trying that command throws this error:

```
$ keybase fs reset /keybase/public/lel                 
This command will reset the entire folder /public/lel
You will completely lose access to all data in that folder
You should probably only do this if someone at Keybase told you to.
Before resetting, contact Keybase admins for a server-side reset by:
  1) Filing an issue at https://github.com/keybase/client; or
  2) Running `keybase log send` and describing the problem.)
Continue resetting the folder? (type 'YES' to confirm): YES
▶ ERROR Can't create TLF ID for non-team-backed handle /keybase/public/lel
```

**Comment by strib** [comment]
Hmm ok.  When I tried it via the command line on a desktop, it seemed to work:

```
$ keybase fs sync enable /keybase/public/lel
$
```

And I can confirm that the new folder looks to be of the correct version now.

What exact behavior/error do you see when you try to sync it now?  Maybe your Keybase app just needs a restart?

**Comment by lelysses** [comment]
> What exact behavior/error do you see when you try to sync it now? Maybe your Keybase app just needs a restart?

The issue is that when I enable syncing, it is impossible to access the synced files on a reboot. I'm on Linux, and it claims that syncing worked, and if I do `keybase fs sync show` it says that it's fully synced, but I can't access it via fuse. My private TLF works perfectly fine. Trying to `ls /keybase/public/lel` makes fuse throw `ls: cannot open directory '/keybase/public/lel': Input/output error` until I get an Internet connection (but if I then turn off my Wifi, the files persist — it's only an issue after a reboot).

Also, if I try to run `keybase fs sync show` when it's in the error state and I can't access the files, it claims it's fine, but if I just enable syncing on a subdirectory of my public TLF, `keybase fs sync show` *hangs*, while throwing a bunch of errors every couple seconds about not being able to reach keybase's servers.
