### ISSUE TITLE
Missing Airdrop

### ISSUE THREAD

**Issue by PMTpro** [keybase/client#21695]
Hi Keybase,

I recently reset my account and when I returned I lost the Airdrop. Unfortunately, when I was mistaken for a junk account, I received XLM last month and I was removed this month.

Please keybase please review my case.

Thanks

![Screenshot_20191218-071340_Keybase](https://user-images.githubusercontent.com/25657732/71045035-128f8d80-2166-11ea-9cc2-e334e9785f65.jpg)
![Screenshot_20191218-071356_Keybase](https://user-images.githubusercontent.com/25657732/71045037-13282400-2166-11ea-98aa-5527eb775cde.jpg)

**Comment by AbuShayann** [comment]
I do not received my xlm airdrop so far, will it take anymore time ?
