### ISSUE TITLE
Problema de transferencia

### ISSUE THREAD

**Issue by falcondev03** [keybase/client#21732]
Hola tengo una dificultad.. hice una transferencia y no puse el memo y la transferencia lleva ya 72horas y nada que llega me gustaría saber si existe forma de cancelarla... Por favor respondanme y ayudenme a resolver mi problema o diganme a donde escribir no borren el tema

**Comment by adrisys** [comment]
Tengo el mismo problema.

**Comment by falcondev03** [comment]
Hi, I have a problem ... I made a transfer and I did not put the memo and the transfer has already been 72 hours and nothing that comes I would like to know if there is a way to cancel it ... Please answer me and help me solve my problem or tell me where to write no  delete the subject

**Comment by falcondev03** [comment]
Oye me parece impresionante que no respondan a este problema cuando evidentemente el problema viene por culpa de ustedes por que si el memo es algo necesario para una transferencia el formulario de envio de dinero no deberia dejarte enviar nada hasta que lo pongas.. en cambio lo permite para que el dinero se pierda... Ademas de eso no responden y borra las entradas... Respondanme o les saturo las entradas hasta que digan algo por es su culpa lo que sucede...

**Comment by falcondev03** [comment]
Hey, I find it impressive that you do not respond to this problem when obviously the problem comes because of you because if the memo is something necessary for a transfer, the money transfer form should not let you send anything until you put it on.  allows for the money to be lost ... Besides that they do not respond and delete the entries ... Answer me or I saturate the entries until they say something because it is their fault what happens ...

**Comment by junderw** [comment]
Stellar doesn't require a memo to send XLM... the place you sent to required it for some reason, that is THEIR problem. Contact their support, not keybase. They have your money, not keybase.

Learn how things work before you send money.

**Comment by falcondev03** [comment]
Oye hasta que por fin alguien se digna a responder porque lo que mas me molesto que se no tuvieran la bondad de responder...! Muy bien lo que dice me parece razonable buscare al sitio donde envie el dinero o con la misma platafoma de stellar
