### ISSUE TITLE
Login issue

### ISSUE THREAD

**Issue by iwuchris** [keybase/client#21756]
I can’t login in to my account at Keybase 
![F6E00108-737D-4DE3-886F-7F336367604A](https://user-images.githubusercontent.com/57894050/71219147-57313b00-22c4-11ea-8911-943e6010e2dd.png)

**Comment by iwuchris** [comment]
What does this mean

**Comment by maxtaco** [comment]
We'll look into it.

**Comment by iwuchris** [comment]
Still can’t login
