### ISSUE TITLE
Synced folders/files on Android

### ISSUE THREAD

**Issue by n0vember** [keybase/client#21767]
I have clicked on the "Sync on this device" on my private and public folders in Android client. I expected my files to be available on storage on the phone, but they are nowhere to be seen. Is it a misunderstanding of the feature ? Haven't I looked everywhere ?

I tried :
- finding documentation
- googling it
- run a find command from termux
- gone through the filesystem using a filemanager
- looked particularly in Android/data/io.keybase folder

But nothing...

version is 5.1.0-20191210204145+5d92cf7e30

**Comment by strib** [comment]
Yes you have misunderstood.  Syncing doesn't interact with your storage on Android.  it just downloads the encrypted data to a local Keybsae db so it is available through the Keybase app when your device is offline.

**Comment by ruphy** [comment]
hi @strib,
after reading this issue, I just tried out this feature on my phone with no luck: I have clicked on the "Sync on this device" on my private folder, I checked it was working, that everything was synced, and I went to bed.

The day after I got on my plane, confident I could still pick up some files to edit, and *poof* - Keybase only tells me that it "Failed to load TLF lists", and does not show me anything in its storage.

So it seems that while file are synced correctly I cannot access them offline. Judging from your words this does seem like a bug: am I misunderstanding something or should I open a new issue?

**Comment by strib** [comment]
Sorry this is a known bug with loading the folder list while offline that will be fixed in the next release.  It only affects listing the folders -- jumping straight to the folder would have worked if you had a way to do that.  For example, it probably would have worked to go into the corresponding chat for the folder, and click the folder icon to jump straight into it.
