### ISSUE TITLE
Why didn't I receive XLM?

### ISSUE THREAD

**Issue by naitsabes1** [keybase/client#21779]
did you notice that after the "ending" of XLM, there were over 170,000,000 left? Over 500 people were missed by the bot, including myself, I wrote about it yesterday ... please help
A month ago, everything was fine, I received XLM ... I note that I did interaction with aidrops and did not set up multi-accounts ...
Will I receive these 355 XLM? Is the topic already completed?

Account [Keybase Space Drop] GDV4KECLSZLKRVH4ZTWVAS4I3W2LPAPV66ADFFUZKGIVOTK6GMKGJT53
Current Account Balance
179,869.6521568 XLM

**Comment by nicolain15** [comment]
I did not receive my stellar, and I was qualified to receive it, since I qualified last month.  I had a message in the app that said I should accept them but then the message disappeared

**Comment by AsadullahHorlah** [comment]
I also didn't receive any XLM even though I registered properly and am qualified. Please do something about it soon enough.

**Comment by estcavdac** [comment]
IT is a massive data kidnapping. They paid just a few to collect a lot of personal ID.
