### ISSUE TITLE
I did not receive my stellar

### ISSUE THREAD

**Issue by nicolain15** [keybase/client#21794]
I did not receive my stellar this month, I am qualified to receive them but they never arrived, I had a message telling me that they were about to be approved and nothing ever came.  How should I claim it?

**Comment by estcavdac** [comment]
They are going to shut you down, if you wanna catch their attention complaint in their social media.

**Comment by nicolain15** [comment]
Good evening, I would like to know how to claim my stellar, I am qualified but they did not arrive
