### ISSUE TITLE
Error 202 signing in

### ISSUE THREAD

**Issue by perfectfate** [keybase/client#21803]
Username:perfectfate
I try to sign in using paper key and get the below error 202.

I get a notification on my devices a device has been added using a paper key but the devices are “offline” and I cannot view any chats. 
![65142F0F-E817-49A5-9243-427585AFC637](https://user-images.githubusercontent.com/59143748/71324363-cb213e00-2492-11ea-8db4-bb68ae12d177.png)

**Comment by maxtaco** [comment]
We'll look into it right away

**Comment by perfectfate** [comment]
Hello,
What is the solution?

**Comment by perfectfate** [comment]
@maxtaco How can I log into Keybase??

**Comment by perfectfate** [comment]
Still having the same issue. Error 202

**Comment by perfectfate** [comment]
Is there any way to resolve this?
