### ISSUE TITLE
echo + tail -f combination works from osx -> linux but not other way around

### ISSUE THREAD

**Issue by ekroon** [keybase/client#2181]
With a setup:
- OSX machine logged in with user1
- Ubuntu VM logged in with user2

Results:
- Two terminals on OSX in `/keybase/private/user1/temp` and executing  `tail -f chat` + `echo "hello" >> chat` shows the new line.
- One terminal in OSX and Ubuntu each in `/keybase/private/user1,user2/temp`
  - `echo "hello" >> chat` in OSX and `tail -f chat` shows new hello line right away
  - `echo "hello" >> chat` in Ubuntu VM and `tail -f chat` doesn't show a new line

Also tried with gtail on OSX, same result.

**Comment by strib** [comment]
Thanks for the tip.  That's super weird, but I can reproduce it, so I'm looking into it now.

**Comment by strib** [comment]
I see the issue.  Fun fact: it works properly for the first 19 seconds that kbfs is running, which makes this really hard to find in our unit tests.  But, I have a fix.  Should go in today and be available in tomorrow's build.

**Comment by strib** [comment]
The fix is in master.  Thanks again for the report -- please open if you can still reproduce in tomorrow's build.

**Comment by ekroon** [comment]
Great! A unit test with sleep(19) would do the trick btw? ;)
