### ISSUE TITLE
Coin flip messages cannot be deleted

### ISSUE THREAD

**Issue by yb66** [keybase/client#21825]
Hi there,

I was playing with the /flip coin feature in my chat-to-myself channel. I can't delete the flips. I can, however, set flip messages to explode.

I've also tried it in chat with someone else. Again, I wasn't able to delete the messages but exploding them does work.

The feature would be better with deletion, I feel. Not only could I then use the flips for secure generation but I could also clean up my messages!

Regards,
iain

PS Merry Christmas to all at Keybase

**Comment by joshblum** [comment]
This will be possible in the next release, fixed via #22693
