### ISSUE TITLE
ERROR Unable to change chat channels

### ISSUE THREAD

**Issue by kaayso** [keybase/client#21826]
Hello, i'm trying to create a new channel from the CLI by using this following command : 

`keybase chat create-channel --topic-type "chat" <TEAM_NAME> <CHANNEL> `

But I've got this error : ERROR Unable to change chat channels

It worked fine 1 month ago but actually I don't know why it doesn't work. I tried on GUI and on mobile but I've got the same error...

thank you for your help !

**Comment by joshblum** [comment]
@kaayso could you do a log send if you're still experience this? you can do `keybase log send` from the CLI or `settings > feedback` in the app. thanks!

**Comment by kaayso** [comment]
Done. 👍

**Comment by joshblum** [comment]
Closed via https://github.com/keybase/client/pull/23056

**Comment by kaayso** [comment]
Awsome !! Thank you ✌🏼
