### ISSUE TITLE
missing provisioning key in login context

### ISSUE THREAD

**Issue by zingmars** [keybase/client#21839]
When trying to log in into my account using the keybase client, I get the following error - 
![image](https://user-images.githubusercontent.com/917126/71545796-d6470300-2997-11ea-9bf0-3d9deb51c468.png)

I found a similar issue - https://github.com/keybase/client/issues/15228 that says that the fix is to reset your account. For some reason however, I'm unable to do that either. 
![image](https://user-images.githubusercontent.com/917126/71545809-21f9ac80-2998-11ea-853c-4caa32154c4a.png)

The username is the same as my github username.

**Comment by heronhaye** [comment]
Reproduce and run `keybase log send` in terminal please.

**Comment by zingmars** [comment]
Done: 6ad7627253657ba29c33021c

**Comment by zingmars** [comment]
Any updates @heronhaye?

**Comment by heronhaye** [comment]
Sorry, we're working on getting the reset flow working in this case. I'll have an update for you shortly.

**Comment by heronhaye** [comment]
@zingmars could you try resetting now?

**Comment by zingmars** [comment]
Yup, I can initiate the reset now. Thanks!
