### ISSUE TITLE
Files not syncing TO keybase.pub

### ISSUE THREAD

**Issue by hale6666** [keybase/client#2184]
When I add a file to my public folder `/keybase/public/hale6`, it doesn't appear at [https://keybase.pub/hale6](https://keybase.pub/hale6).  I can see the file in my file manager's GUI, and can also see it by using `ls` in the directory.  When the file is put into the directory, a little message/notification shows up that says "KBFS: signing and uploading".  No errors appear.

However, if I navigate to another user's public folder via the terminal, their files ***do*** indeed appear, so I know that the program is syncing correctly with the Internet.

my log id: 9eb47391cf73e1a9856d451

**Comment by hale6666** [comment]
It's there now!

**Comment by jaygaga** [comment]
Im facing same issue now how did you resolve this
