### ISSUE TITLE
Can't push to git or upload files

### ISSUE THREAD

**Issue by tsemczyszyn** [keybase/client#21857]
Git push hangs on syncing encrypted data and file upload in the keybase gui timer keeps resetting.

my log id: dc45e07da1f5029ab2ffce1c

**Comment by tsemczyszyn** [comment]
Started working again after a while. 
[keybase.kbfs.log](https://github.com/keybase/client/files/4011924/keybase.kbfs.log)

**Comment by songgao** [comment]
Thanks for reaching out. We had a server side issue around that time.
