### ISSUE TITLE
n

### ISSUE THREAD

**Issue by mortalzgr** [keybase/client#21901]
Keybase GUI Version: 5.1.1-20191211174240+15bbb94c23

**Comment by jgreever** [comment]
Want to tell us what issue you are experiencing please? Posting nothing but the version doesn’t help us to help you.

Thank you!

**Comment by mortalzgr** [comment]
I didn't write anything
  ----- Original Message -----

**Comment by jgreever** [comment]
Please close this issue. User unaware, auto reported via the app most likely.
