### ISSUE TITLE
Keybase fs sync isn't working on one computer

### ISSUE THREAD

**Issue by cespare** [keybase/client#21918]
I use keybase fs for sharing a small number of text files between multiple devices. I noticed that a file I edited in private/cespare on host 1 wasn't being reflected on host 2. On further inspection, it seemed that the problem was that host 2 wasn't seeing the update (I could see it on my phone).

This is despite the fact that keybase claimed that the sync was active on host 2:

```
$ keybase fs sync show
private/cespare
  Syncing enabled
  Status: fully synced
  541.59 KB bytes stored

Status: fully synced
541.59 KB bytes stored
814.78 GB (89.07%) of the local disk is available for caching.
```

After disabling and re-enabling sync, it seemed stuck:

```
$  keybase fs sync show
private/cespare
  Syncing enabled
  Status: sync not yet started
  0 bytes bytes stored

Status: sync not yet started
0 bytes bytes stored
814.78 GB (89.07%) of the local disk is available for caching.
```

This is after waiting for several minutes.

This problem seems similar to https://github.com/keybase/keybase-issues/issues/3747, so I followed the directions in that issue:

* `keybase fs set-debug-level 2`
* disabled and re-enabled sync again
* `keybase log send`

Is there anything you can learn about what's going wrong?

Thanks!

my log id: 73408b439d725b121749641c

**Comment by cespare** [comment]
By the way, I filed the issue in this repo after clicking the link that `keybase log send` gave me. I'm not sure if I should've filed this in `keybase/keybase-issues` instead.

**Comment by strib** [comment]
At a quick glance it looks like host 2 has hit a race condition where it got stuck trying to update something in the folder (the executable bit of some file I think?) and for some reason didn't/can't flush it to the server, and because of that it's not updating itself with the current server view.

I'll look more into how that is possible, but in the meantime, restarting the full Keybase app including KBFS on host 2 should fix it.  Let me know how it goes.

**Comment by strib** [comment]
Actually before you restart, can you get the output of this command please?

```
keybase fs read  /keybase/private/cespare/.kbfs_status
```

If it looks like there isn't anything sensitive in it, please post it here.  Otherwise share it with me privately over Keybase chat?  My username is `strib` there too.  Thanks.

**Comment by cespare** [comment]
@strib here you go:

```
{
  "Staged": false,
  "BranchID": "00000000000000000000000000000000",
  "HeadWriter": "cespare",
  "DiskUsage": 472682,
  "RekeyPending": false,
  "LatestKeyGeneration": 1,
  "FolderID": "f11f99d3777312065a31769f1dc30016",
  "Revision": 118,
  "LastGCRevision": 87,
  "MDVersion": 4,
  "RootBlockID": "024d5c0666a304e082e4512cccbd3da2f6c1ba7d06db79c207a56f8768afe74af2",
  "SyncEnabled": true,
  "PrefetchStatus": "NoPrefetch",
  "UsageBytes": 474076,
  "ArchiveBytes": 1697124,
  "LimitBytes": 268435456000,
  "GitUsageBytes": 0,
  "GitArchiveBytes": 0,
  "GitLimitBytes": 107374182400,
  "LocalTimestamp": "2020-01-03T18:16:36.80984329-08:00",
  "DirtyPaths": [
    "cespare/gold-walk/blind-motion.txt"
  ],
  "Unmerged": null,
  "Merged": null,
  "Journal": {
    "Dir": "/home/caleb/.local/share/keybase/kbfs_journal/v1/0120b08770a5665cf43cdde0fa9a92d123e2-f11f99d377731206",
    "RevisionStart": 0,
    "RevisionEnd": 0,
    "BranchID": "00000000000000000000000000000000",
    "BlockOpCount": 0,
    "StoredBytes": 0,
    "StoredFiles": 0,
    "UnflushedBytes": 0,
    "UnflushedPaths": null,
    "EndEstimate": null,
    "QuotaUsedBytes": 473308,
    "QuotaLimitBytes": 268435456000
  }
}
```

I don't think there's anything sensitive there, but let me know if one of those hex IDs is actually an important private key or something ><

One weird thing in there is:

```
  "DirtyPaths": [
    "cespare/gold-walk/blind-motion.txt"
  ],
```

I have no clue what `cespare/gold-walk/blind-motion.txt` is. No such file exists in my keybase files and the name doesn't ring any bells.

**Comment by maxtaco** [comment]
`gold-walk` is a pseudonym for your actual file, so that way logs don't convey file names.

**Comment by strib** [comment]
Yeah that `DirtyPaths` was the exact thing I was curious about.  I'll look into it more tomorrow.  For now feel free to restart Keybase on the machine.  Thanks!

**Comment by cespare** [comment]
@strib it's working after a restart.

**Comment by strib** [comment]
Great thanks. #21973 should prevent it from happening in future releases.
