### ISSUE TITLE
in mac os, keybase does not show up under /volumes when accessing it via the finder

### ISSUE THREAD

**Issue by marrie** [keybase/client#21930]
Using mac os 10.15, I noticed that the keybase volume does not show up even after typing the terminal command to install the keybase fs. I changed the permissions on the folder after going to the folder by hand by typing /volumes in the go dialogue in the finder itself. I then tried to open the volume but got the error that I did not have permissions to open. My permission were indeed set to custom. I set them to read and right via the inspector, but now I don't see the public, private and teams folder I should be seeing. In fact I did an ls in the directory, and there is indeed nothing there.

Thanks.

my log id: 6657f35f5d9fa73af496431c

**Comment by strib** [comment]
It seems like your kernel extension still isn't installed or enabled for some reason.  If you're the same user from reddit, did you run the `keybase install` command suggested there, or find the button in settings?

If the former, I wonder if adding "helper" might fix it for you, like:
```
keybase install -c helper,fuse,kbfs,mountdir,redirector
```

**Comment by marrie** [comment]
I am the same user, yes. Restarting the computer did fix it, I had to 
restart anyway due to some other issues like a keyboard that 
malfunctioned during class, all is working now, almost. The almost part 
I think I might be able to troubleshoot on my own as I think I know what 
might have happened.

Can the command given be put somewhere in the docs on the keybase fs  
install section for mac os? That would be good as well in case the 
reddit thread goes for some odd reason.

Thanks.

**Comment by strib** [comment]
Ok great.  Yeah we have an ongoing project to revamp our docs, so hopefully we can get this in there.  Thanks for your patience!
