### ISSUE TITLE
No build for Mavericks?

### ISSUE THREAD

**Issue by ajfisher** [keybase/client#2193]
I noticed that according to brew, latest OSX mavs version is 0.8.x and the more recent builds on 1.x series are all OSX 10.10+ 

Is there an OSX 10.9 build or documentation on *how* to build from source somewhere?

**Comment by ajfisher** [comment]
Nothing?

**Comment by oconnor663** [comment]
Sorry for missing your initial question, @ajfischer. The instructions on how to build from source are here: https://github.com/keybase/client/blob/master/go/README.md#building Someone who knows more about OSX will need to chime in to talk about what's expected to work on older versions, vs what's known to be broken. @gabriel?

**Comment by ajfisher** [comment]
Hmm - tried this today and keep getting 

```
package github.com/keybase/client: no buildable Go source files in /Users/andrewfisher/gopath/src/github.com/keybase/client
```

Go 1.5 etc is all working and docs followed and no errors to this point. I'm not very familiar with Go at all so not sure if the error is my system or the fact again I'm running mavs so potentially outdated...

**Comment by oconnor663** [comment]
That error was actually expected. If you continue with the next step, I think it will work fine?

In retrospect, I should've realized that would be confusing. I've [tweaked the instructions](https://github.com/keybase/client/commit/03d5b6569ffb3d7dfb0167399cbd51f75d7f41f0) to hopefully avoid that error. (The downside is that it now builds client twice, the first time with the wrong flags, but I still think it's better than showing the error.) Please let me know if that helps.

**Comment by ajfisher** [comment]
Cool - thanks for that - will give that a crack once I'm back in the office
in the morning.

**Comment by ajfisher** [comment]
Okay so current error is this:

package code.google.com/p/rsc/qr: unable to detect version control system
for code.google.com/ path

But then I thought I'd truck on through anyway and I get a build but it
results in this error on a `keybase login`

ERROR dial unix /Users/andrewfisher/Library/Caches/Keybase/keybased.sock:
connect: no such file or directory

Cheers
Andrew

**Comment by maxtaco** [comment]
Run 'keybase service' in a different terminal.

(For now at least)

**Comment by gabriel** [comment]
You have a few options to install the keybase service:

To install as launchd service:
```
keybase install --components=service
```

To run in background:
```
keybase --auto-fork ctl start
```

**Comment by gabriel** [comment]
I see a mavericks bottle in the brew formula: https://github.com/Homebrew/homebrew/blob/master/Library/Formula/keybase.rb

I don't have a pre 10.10 OS X  machine to test with though... Its possible we might have added a min os version check to the keybase client/service?

**Comment by ajfisher** [comment]
Thanks for all of that.

Manual install is now working and I've got the service running and
everything is working as I'd expect on my other machines.

Thanks
