### ISSUE TITLE
Fedora 23 desktop integration

### ISSUE THREAD

**Issue by skpy** [keybase/client#2198]
After #2180 was resolved, I now have the new Keybase client up and running.  All CLI operations appear to be functional.

There appears to be no CLI-only way to activate the KBFS, so far as I can tell.  It would be nice to support this for headless Linux systems, but that's not the point of this issue.

In my GNOME deskop, the Keybase interface is at the bottom left of my screen.  It's comprised of a very small and hard-to-notice widget just barely sticking out.  Mousing over this widget reveals  a ">" right arrow icon.  Clicking that reveals the Keybase squirrel mascot, and the ">" right arrow changes to a "<" left arrow. 

![keybase01](https://cloud.githubusercontent.com/assets/722830/13481774/69866324-e0b6-11e5-9494-455717d4de9b.png)

Clicking the squirrel icon creates a new notification at the top middle of my screen that simply says `"Keybase" is ready`. If I do nothing, that notification goes away.

![keybase02](https://cloud.githubusercontent.com/assets/722830/13481779/75793030-e0b6-11e5-8701-f9f4660af72e.png)

If I click that notification, a new widget appears in the top right of my screen listing my private and public directories.  This is the same widget that is displayed when clicking the squirrel icon on the OSX toolbar.

![keybase03](https://cloud.githubusercontent.com/assets/722830/13481782/7b43b10c-e0b6-11e5-9b3b-3b264ccf4f8a.png)

It's confusing to have the controls for Keybase spread so far across my screen, and require so many clicks: click bottom left, then click upper middle, then navigate top right.

It would be nice if the Keybase controls could be put into the GNOME panel up alongside the other controls for WiFi, sound, etc.  Failing that, it would be nice if Keybase could automatically register a shortcut in the "Files" application (nee Nautilus) so that I wouldn't have to click  through "Other Locations -> Computer -> keybase".

**Comment by cjb** [comment]
> There appears to be no CLI-only way to activate the KBFS, so far as I can tell.

`run_keybase && keybase login` will mount KBFS at /keybase.

**Comment by oconnor663** [comment]
My understanding of the tray on the bottom left is that that's just where Gnome 3 decided to put application icons. I agree that it's deeply inconvenient, and I don't know why they did it. I use the [TopIcons shell extension](https://extensions.gnome.org/extension/495/topicons/) to fix it. That puts Keybase on the top right, and it'll fix Dropbox and other apps along with it.

**Comment by skpy** [comment]
Thanks @oconnor663 for the link to topicons!  That's great.
