### ISSUE TITLE
cannot send log on CentOS

### ISSUE THREAD

**Issue by jczimm** [keybase/client#2200]
I am unable to `log send` on CentOS.

```sh
[kbuser@myserver ~]$ keybase log send
▶ ERROR dial unix /run/user/0/keybase/keybased.sock: connect: permission denied
```

**Comment by maxtaco** [comment]
Hmm, looks like you're using keybase as root?  I'm not sure if we support that.... @oconnor663 /

**Comment by jczimm** [comment]
I logged into a new `kbuser` after seeing that note when trying as `root`.

**Comment by oconnor663** [comment]
I think what's happened here is that the environment variable `XDG_RUNTIME_DIR` got set to directory created for your root user, probably by your desktop environment? Then when you switched users (maybe with `sudo -u kbuser bash` or something?) that variable was never overwritten, even though now it referred to an unwritable path.

Is that anything like what happened? If so, can you log out fully and log in again as `kbuser` without going through root first?

**Comment by jczimm** [comment]
@oconnor663 That is what happened, and your solution worked!  Thanks!

**Comment by oconnor663** [comment]
![image](https://cloud.githubusercontent.com/assets/860932/13485156/ba86faf6-e0d2-11e5-8b02-7a7ad18d7581.png)

**Comment by PeaStew** [comment]
Easier way is just to do XDG_RUNTIME_DIR="" and the do run_keybase again
