### ISSUE TITLE
Multiple keybase volumes showing up in finder with KBFS

### ISSUE THREAD

**Issue by grempe** [keybase/client#2208]
Keybase GUI Version: 1.0.14-20160303170019+d7c1ca4

I just noticed this today. Multiple keybase volume entries being created in OS X Finder. I have noticed the GUI client fail at login a couple of times over the last few days, presumably when doing and auto-update.  May be related.

<img width="173" alt="glenn_and_1__less" src="https://cloud.githubusercontent.com/assets/117/13507761/fa1c2bf8-e138-11e5-909c-ded53cd37b37.png">

**Comment by grempe** [comment]
Looks like duplicate of https://github.com/keybase/client/issues/2169

Sorry.  Will try to remove and update as suggested there.

**Comment by maxtaco** [comment]
A meta-meta duplicate

**Comment by grempe** [comment]
I removed finder shortcuts after quitting keybase client, and then running `keybase update client`.

@maxtaco I no longer have duplicates.  But I also don't have *any* keybase volume shortcut in the finder either.

Expected?

**Comment by maxtaco** [comment]
Expected, we've had to postpone that feature.  CC: @gabriel

**Comment by grempe** [comment]
ok, will close this issue.  Thx.
