### ISSUE TITLE
KBFS GUI does not play nicely with tiling window managers like i3

### ISSUE THREAD

**Issue by rpglover64** [keybase/client#2210]
I'm using i3 as my window manager. It seems that (since I have focus-follows-mouse behavior) whenever my mouse leaves the window I get by clicking on the tray icon (for any reason, including moving out, moving onto a floating window, and changing workspaces), the window closes.

my log id: d3ec1a5db90b2c77eb35601c

**Comment by dhgwilliam** [comment]
this looks like a dupe of #1979, yeah?

**Comment by rpglover64** [comment]
Yes.
