### ISSUE TITLE
[desktop] proxy settings through environment variables

### ISSUE THREAD

**Issue by je-vv** [keybase/client#22160]
Hi, I'm using keybase desktop package from Arch, and it's working at home and also at the office behind a corporate proxy, by setting the proxy configuration settings each time I change from/to no proxy, and from/t a particular proxy.  I do connect to different proxies depending on what's convenient.  For example if I need to remotely connect through VPN, I can choose the proxy to use that's closest to the VPN location, and when I'm in the office I usually use the local to the office one.  Of course when not at the office and not connected through VPN, I use no proxy.

Of course I do have to set the client proxy settings each time I change from environment, and that's not the best the client can do.  There can be an option like "Use environment variables proxy settings", or "Use system settings", which would evaluate if the proxy environment variables are set or not.  If set, then configure the proxy accordingly, and if not, then don't set any proxy.  Notice Firefox for example provides "Use system settings" that work well with environment variables.  I prefer environment variables given I don't use DEs like gnome or KDE with shells that update the environment variables upon configuration changes, but they do export such variables any ways.  Signal for example as well uses environment variables.

I set the following ones:

use_proxy
soap_use_proxy
http_proxy
https_proxy
ftp_proxy
rsync_proxy
no_proxy
USE_PROXY
SOAP_USE_PROXY
HTTP_PROXY
HTTPS_PROXY
FTP_PROXY
RSYNC_PROXY
NO_PROXY

But if the client more likely would use other specific ones, that's fine, I can set them as well.

This is more like a feature request, since as mentioned, the client is working behind a corporation proxy, and when not, but it could do so more conveniently.

Thanks a lot !

**Comment by heronhaye** [comment]
HTTP/HTTPS_PROXY should work automatically (ref https://github.com/keybase/client/blob/master/go/libkb/env.go#L1175-L1192). But the issue maybe that they're not exposed to your systemd user-level units (keybase is one).

Try

```
systemctl --user show-environment
```

and see if your proxy settings are there. If not, you should set the env vars via `.pam_environment`. 

If you want to set them just for keybase and not any other units, you can make a file at `~/.config/keybase/keybase.env` of the format

```
HTTP_PROXY=xyz
```

And then restart keybase with `systemctl --user restart keybase keybase.gui kbfs`.

**Comment by je-vv** [comment]
But then I have to write the systemd unit to change the environment variable in order for this to work, or even the pam_environment, or edit ~/.config/keybase/keybase.env?  That defeats the purpose of environment variables in my case.  I have to re-edit them any time I want to change environment variables.

If I don't use systemd, but instead call:  "/usr/bin/keybase --use-default-log-file --debug service" on bash_profile, after selecting the proxy env vars to usue if any (might select none), should keybase work apropriatelly?

**Comment by je-vv** [comment]
Seems like just starting keybase after seeting the env vars is enough, so no need to use systemd at all.  Question, is "--use-default-log-file" needed, given it seems it's calling to use the "default" log?  I guess "--debug service" is required to get less log?  "keybase help" doesn't show options, and keybase has no man page, so I can't see if those are required, though I know those are the ones used by the keybase systemd unit.

**Comment by je-vv** [comment]
BTW, I've tried several ways, both systemd or not, using keybase config set <proxy|proxy-type>, using .config/keybase/keybase.env, and nothing...  It seems the only way to get keybase to work behind a proxy is to set the gui.  But that would only work for chats and profile setup, since for accessing the keybase storage shows me always offline, no matter keybase has been configured through the gui.  Something else is that the gui doesn't work with proxy being set as "http://<hostname>:<port>", as all desktop apps I use do, and instead it seems to require "<hostname>:port".

So overall, keybase doesn't seem to support proxy environment variables at all, it also seems one can't configure proxy through the command line (config setting the same things set by the gui doesn't make it work), and storage doesn't seem to support proxy whatsoever.

Really sad.  As mentioned this is plain easy on Signal for example, if talking electron apps, firefox if talking gui apps, wget, curl and many others if talking command line.

All I need is to start keybase and its storage (I don't mind if it's with systemd, but systemd looks to me unnecessary and bloated, since it can read user environment variables set out of systemd) once I have configured the environment variables I need, and hopefully withou having to edit anything.  Right only chats get to work and only through the gui, which is not what I really need.

Supporting this functionality, not only makes keybase easier to use, it also makes it compliant to the use of user set env vars, and besides it would make it fully functional (right now, as far as I can tell, storage is not working for me under proxy, which makes the proxy support only partial).

**Comment by je-vv** [comment]
Found it out...  1st, in order to make sure to use env. vars, without editing files, neither configs, 1st, one needs to stop using systemd stuff, including "keybase ctl start", which in turns calls "keybase service", but it does so through a systemd unit.  So my recipe to avoid systemd stuff (I have scripts, but in brief):
```
if [ -n "$HTTP_PROXY" ]; then
   export PROXY=$(echo $HTTP_PROXY | /usr/bin/sed 's?http://??' | /usr/bin/sed 's/[ \t\n][ \t\n]*$//')
   export PROXY_TYPE="http_connect"
fi
keybase ctl init
keybase --use-default-log-file --debug service &
kbfsfuse -debug -log-to-file &
electron /usr/share/keybase-app &  <<-- This should be Keybase instead if using binary from keybase
```
I had to search into the source to find out the right env. vars:
>  client-v5.1.1/go/libkb/proxy.go
There you can find PROXY and PROXY_TYPE are the ones.  And can try using them on systemd, but of course you'll have to edit files or do keybase configs for them to have effect, see the extensive and useful comments on "proxy.go".
I would strongly suggest copying those comments (they're even written in markdown) on the documentation, or at least reference them on [github](https://github.com/keybase/client), to take advantage of the source.
Special attention to the difference between calling "keybase service" directly, and doing it through "keybase ctl start".  The last call as mentioned before in turns calls the 1st one, but also as mentioned before, it does it through a systemd unit, so your env. vars. get lost...
Closing, given there are env. vars. that can be used, but I'm afraid this is not very well documented, specially for the use case described.
