### ISSUE TITLE
KBFS mount missing.

### ISSUE THREAD

**Issue by greyspectrum** [keybase/client#22306]
Operating System: MacOS Catalina 10.15.3

Keybase: version 5.2.0

The Keybase file system is typically mounted at /Volumes/Keybase on MacOS Catalina. However, the mount point is currently missing, although the GUI is behaving normally.

```
% keybase config get -b mountdir
▶ ERROR <root>.mountdir: no such key: mountdir
```

```
% ls /Volumes/Keybase
ls: /Volumes/Keybase: No such file or directory
```

**Comment by strib** [comment]
If you do a `keybase log send`, and post the resulting ID here, we can take a look.  Note that this requires enabling Finder integration, so if you haven't done that yet on this device, you'll need to.  If you have done that, maybe there's a bug or a macOS security issue.

**Comment by MatthewDG** [comment]
My team experienced this issue too - we all had the Finder integration enabled for a while on our devices, but when we opened up Keybase this morning, the Finder integration was deactivated. We just had to re-enable and we were good to go.

**Comment by greyspectrum** [comment]
> If you do a `keybase log send`, and post the resulting ID here, we can take a look. Note that this requires enabling Finder integration, so if you haven't done that yet on this device, you'll need to. If you have done that, maybe there's a bug or a macOS security issue.

Done
------------
Success! Your log ID is:

  7b36b3a66e1bcb0db7e5f51c

**Comment by greyspectrum** [comment]
> My team experienced this issue too - we all had the Finder integration enabled for a while on our devices, but when we opened up Keybase this morning, the Finder integration was deactivated. We just had to re-enable and we were good to go.

This fixed my issue. Enabling finder integration and installing the kext for proprietary FUSE when prompted enabled the client to mount.
