### ISSUE TITLE
Crypto sign drops new lines

### ISSUE THREAD

**Issue by stratosgear** [keybase/client#22316]
This:

```
a

b

c
```

is signed as:

BEGIN KEYBASE SALTPACK SIGNED MESSAGE. kXR7VktZdyH7rvq v5weRa0zk9qninN D0SxG4C6DVdXflf qhdmXztwnUraMx3 Lx5E8Ar5tgbCcJd 024XBdKen96ROPn 0YQ10XxgMJwAwlj i5ckosoIFKaFrTF Woyt4uwPwdCTJkE XjNAuDnGfdtEmFE gW2OwGBrkMFyX8k XVofWs3C5ZtWSen bHyocFW18hIhlNj . END KEYBASE SALTPACK SIGNED MESSAGE.

but verify gives me:

```
a
b
c
```

This is a contrived example. A longer email message looks "uglier"

**Comment by heronhaye** [comment]
Thanks, we'll look into it.

**Comment by cjb** [comment]
This is fixed by #22609, so it'll be in the next release.
