### ISSUE TITLE
Bundle version doesn't match installed version

### ISSUE THREAD

**Issue by RandomLetter** [keybase/client#2234]
I get a Keybase error when I start the Keybase app - "Bundle version (1.0.1-20160305170047+41e7640) is less than installed version (1.0.1)".  If I ignore the error, even though I'm logged in on the CLI, the app shows me as logged out.  Logging out and back in had no effect.

my log id: 8f97bc8b98e7b5bc6172ca1c

**Comment by jonalmeida** [comment]
Seeing the same error after the update as well. My Keybase install seems to be borked.

**Comment by grempe** [comment]
Same:

<img width="628" alt="3__zsh_and_2__glenn_rp1_____ssh_" src="https://cloud.githubusercontent.com/assets/117/13550095/7194cbe4-e2ca-11e5-883d-be60272c8878.png">

**Comment by crcastle** [comment]
I'm getting the same error popup as @grempe.  Full error output: https://gist.github.com/crcastle/16ba4ef3bf03db762c7d

I woke up MBP from sleep this afternoon and this was almost immediately displayed.

If the install order might have caused the problem, I installed `keybase` from homebrew and then more recently installed the OS X installer that enabled kbfs, menu bar icon, GUI functionality.

Should I have uninstalled the hombrew version first?

Did an autoupdate bork one piece of keybase?

**Comment by cjb** [comment]
Very sorry about this, we pushed out a broken build.  There's a fixed one available now, but you'll have to apply it manually.  Here's the recipe:

* `keybase update run` to get the new build
* Click on the Keybase icon in the menubar, and "Quit" in the bottom right 
* Relaunch Keybase from Applications folder.

Let us know whether it works okay!  And sorry again for the hassle.

**Comment by crcastle** [comment]
Thanks @cjb.  After doing the steps you list above, I get an error saying `keybase.service is not running`.  There are three buttons: More Details, Ignore, and Quit.

If I click Ignore everything seems to be ok -- I'm able to browse `/keybase/public/` and `keybase status` shows that I'm logged in.

If I click Quit, the Keybase.app starts again in a few seconds and gives me the same keybase.service not running error popup.

So, it seems like everything is working ok, but I do not know why I'm getting this dialog and having to click Ignore.

Thanks!

**Comment by gabriel** [comment]
@crcastle can you run `keybase log send` and post the id?

**Comment by crcastle** [comment]
@gabriel, sent!
log ID: `7af5f3b49d1c3df4650ceb1c`

**Comment by gabriel** [comment]
@crcastle Moving this into separate issue here since I think unrelated to borked version problem above.. I posted a comment there which might help us diagnose (or fix issue)

**Comment by jonalmeida** [comment]
Thanks @cjb , my issues have been resolved!

**Comment by grempe** [comment]
I'm ok now too.
