### ISSUE TITLE
Keybase.service is not running error

### ISSUE THREAD

**Issue by gabriel** [keybase/client#2235]
@crcastle reported this issue here:
https://github.com/keybase/client/issues/2234#issuecomment-192750756

(moving into separate issue here since it seems unrelated to the borked version problem)

**Comment by gabriel** [comment]
It seems like there maybe multiple keybase services running or conflicting.. maybe from a much older install..

Can you post output of:

```
launchctl list | grep keybase
```

To fix you could try `pkill keybase` to kill any (and all) running keybase services... and then restart the Keybase.app

If that doesn't work, it might be something weird with the pid lock file, you could try removing that with: `rm /Users/crcastle/Library/Caches/Keybase/keybased.pid`

Another option is there might be multiple launch agents installed, could you post output of:

```
ls -al ~/Library/LaunchAgents | grep keybase
```

**Comment by crcastle** [comment]
Here is the output of those commands prior to killing any processes or removing lock file:
```
❯ launchctl list | grep keybase
-		0	keybase.service
60855	0	keybase.Electron.235232
59482	0	keybase.kbfs
```
```
❯ ls -al ~/Library/LaunchAgents | grep keybase
-rw-r--r--   1 crcastle  staff  1078 Mar  5 13:59 keybase.kbfs.plist
-rw-r--r--   1 crcastle  staff  1088 Mar  5 14:05 keybase.service.plist
```
Then when I try to pkill keybase processes I get an error:
```
❯ pkill keybase
pkill: signalling pid 953: Operation not permitted
```
So I was curious what keybase processes were running:
```
❯ ps aux | grep keybase
crcastle        59482   0.0  1.2 573430016  98668   ??  S     1:59PM   0:03.68 /Applications/Keybase.app/Contents/SharedSupport/bin/kbfs -debug /keybase
root              953   0.0  0.0  2482092    980   ??  Ss   Tue04PM   0:00.17 /Library/PrivilegedHelperTools/keybase.Helper
crcastle        68898   0.0  0.0  2445436    980 s000  S+    3:03PM   0:00.01 grep --color=auto keybase
crcastle        68880   0.0  0.2 573460096  20664   ??  S     3:02PM   0:00.13 /Applications/Keybase.app/Contents/SharedSupport/bin/keybase -d service
```
Should there be a root-owned process running?  Not sure so I didn't touch it.

Instead I killed the kbfs process and then started Keybase.app.  This time it loaded without showing the error dialog about keybase.service not running.  So the issue is resolved for me, but the root cause is not clear.  Sent logs again if you want to investigate further.  `dc9e489a8cf7be6f98238f1c`

Hope that helps!  Thanks for your help!

**Comment by gabriel** [comment]
Thanks for posting info, and helping debug... I'll need to dig in a little more to the logs but I think a zombie keybase service was running preventing the launchd from starting up...

You can ignore the "Operation not permitted" on pkill and yes keybase.Helper running as root is us. (It's called a privileged helper tool and it's one of ways we integrate with the OS.)

Do you think you have ever run `keybase ctl start` or background forked `keybase service`?

Currently I think there are ways to bork an install like this (since keybase is very configurable), perhaps we might need to add protections for this.

Thanks again!

**Comment by crcastle** [comment]
@gabriel, yes I did run `keybase ctl start` when I was previously experiencing the problems in #2234 (prior to this issue).  So maybe that started a duplicate process?

**Comment by maxtaco** [comment]
@gabriel if you start a second keybase service, it should die right away on attempting to acquire the pidfile lock.
