### ISSUE TITLE
Request: Arm binaries

### ISSUE THREAD

**Issue by Efreak** [keybase/client#2238]
Please provide binaries for linux systems on arm platforms. All of my non-mobile linux systems at home run on ARMHF processors.

**Comment by cjb** [comment]
Is this for the KBFS beta, or the Golang client tools?

For the golang client, your Linux distribution might have ARM packages already.  What are you using?

**Comment by Efreak** [comment]
For the client. `apt-cache search keybase` returns no results on Debian 8.3 and Ubuntu 14.04.4 LTS.

I have no idea what the kbfs is for (I noticed it, but I can't find any real explanation of it anywhere, though I didn't really look too hard either).

**Comment by Efreak** [comment]
I tried using the makfefile provided after installing the distro-provided go package (`sudo apt-get install golang-go`), but I got several errors:

[![](http://a.pomf.cat/auchhg.png)](https://gist.github.com/00ee1dfa97984f28100a)

Trying to install using the [commands](https://github.com/keybase/client/tree/master/go#building) given (`GO15VENDOREXPERIMENT=1 go install --tags production`) but I don't have a $GOPATH variable and I'm not sure how to create one. It appears to be looking for me to build other projects first?

[![](http://a.pomf.cat/xoumfr.png)](https://gist.github.com/8a8fb8ec9094803ba980)

**Comment by cjb** [comment]
@oconnor663 maybe it's easy to cross-compile the non-kbfs deb for ARM?

**Comment by oconnor663** [comment]
@Efreak you found the right instructions page, but what was there was pretty unclear. Sorry about that. I've updated them; here's the new version. Let me know if this works better for you:

```bash
# First we need to set up a GOPATH. This is a standard first step for
# building Go programs, so if you've done this already, skip on ahead.
# See also https://golang.org/doc/install.
mkdir ~/gopath
cd ~/gopath
export GOPATH="$HOME/gopath"     # Consider putting this in your ~/.bashrc.
export PATH="$PATH:$GOPATH/bin"  # Ditto.

# Now for the actual clone and build.
go get github.com/keybase/client
GO15VENDOREXPERIMENT=1 go install -tags production github.com/keybase/client/go/keybase

# If you did the PATH bit above, this should just work.
keybase
```

@cjb I haven't done cross-compilation before. I think that Go has pretty good support for it? Not sure if I want to add it to the official builds, though, with x86 already on the chopping block.

**Comment by Efreak** [comment]
Still not working.

[![](http://a.pomf.cat/jtzzwr.png)](https://gist.github.com/5e0253242cad45520e0c)

**Comment by Efreak** [comment]
I added `go get github.com/keybase/client/go/keybase` assuming it would fix the missing dependencies, and it fixed most of them. Unfortunately, google code is no longer available.

![](http://a.pomf.cat/wzjwsl.png)

**Comment by strib** [comment]
@Efreak: Looks like you didn't install with `GO15VENDOREXPERIMENT=1` set in your environment, like @oconnor663's instructions said.  (Or maybe you weren't using Go 1.5?)

**Comment by Efreak** [comment]
That would be the issue. I installed go from repos, not from source, seems 1.2.1 is installed.

**Comment by oconnor663** [comment]
Damn, sorry for sending you down that rabbit hole. I'll mention that in the instructions too.

**Comment by oconnor663** [comment]
For our Ubuntu build machines, we install the Go tarballs that they provide [on golang.org](https://golang.org/doc/install).

**Comment by Efreak** [comment]
working now. Thanks! I used the armv6 binaries from golang.org.

**Comment by oconnor663** [comment]
Sweet.
