### ISSUE TITLE
Where is the private key located?

### ISSUE THREAD

**Issue by ok3141** [keybase/client#22402]
In blog you wrote:

> Saltpack has a native notion of multiple devices, allowing you to decrypt data securely on devices you haven't bought yet. This might sound magical. But it's simple: when you provision a new device with an existing device, the old device securely gossips higher level decryption keys to the new device. As long as you have an uninterrupted chain of devices, you retain the ability to decrypt files and texts encrypted in the past. No more, “can you please resend the encryption? I lost my key.”

Here's one sentence I can't understand:

> when you provision a new device with an existing device, the old device securely gossips higher level decryption keys to the new device

My question is: from where does KeyBase copy **higher level decryption keys** if I lose all devices and recover account from paper key?

**Comment by maxtaco** [comment]
The secret-key of the higher-level keys are encrypted for your device keys, and then stored on our servers. When you recover from a paper key, you use that paperkey both to authenticate yourself to the server (obviously without sharing the key with the server), and to decrypt the secret keys you need.

**Comment by ok3141** [comment]
Thanks, now it's clear.
