### ISSUE TITLE
Keybase GUI shows "You're logged out" but CLI is logged in

### ISSUE THREAD

**Issue by stirlingpoon** [keybase/client#2241]
Keybase GUI Version: 1.0.14-20160305170008+41e7640
As title, Keybase GUI is logged out while keybase status shows that I am logged in.

**Comment by cjb** [comment]
Very sorry about this, we pushed out a broken build. There's a fixed one available now, but you'll have to apply it manually. Here's the recipe:

* `keybase update run` to get the new build
* Click on the Keybase icon in the menubar, and "Quit" in the bottom right
* Relaunch Keybase from Applications folder.

Let us know whether it works okay! And sorry again for the hassle.

**Comment by stirlingpoon** [comment]
Lovely, it works! Many thanks
