### ISSUE TITLE
KBFS / TLF time travel doesn't work on Mac

### ISSUE THREAD

**Issue by RayOei** [keybase/client#22446]
I have been trying the commands to check the 'time travel' (as described here: https://keybase.io/docs/kbfs/understanding_kbfs) but I don't get them to work.
As an example: 
`$keybase fs stat --show-archived /Volumes/Keybase/team/myteamfolder`
Shows result: /Volumes/Keybase (OSX username)/team/myteamfolder
▶ ERROR Cannot get revisions for non-KBFS path

I have tried different ways of providing the parameter, but nothing seems to work.
I am on OSX 10.15.2
Keybase: 5.2.0-20200130011203+cf82db8320
Keybase mount: `/Volumes/Keybase (OSX username)`
The OSX username is different from the Keybase user.

When I am _in_ the keybase folder **cat .kbfs_update_history** will work. So I am mystified what I am doing wrong??

**Comment by strib** [comment]
`keybase fs` commands use _global_ paths like `/keybase/team/myteamfolder` -- they don't correspond to your mountpoint.

**Comment by RayOei** [comment]
So how would _that_ look like? As `/keybase/team/myteamfolder` doesn't work (already tried that).

**Comment by strib** [comment]
That is supposed to work.  Please show the exact command you are running with the `/keybase` path, along with the exact error output please.

**Comment by strib** [comment]
I didn't mean you need to reveal the teamname though, you can redact that part if you want.

**Comment by RayOei** [comment]
Ouch... ofcourse I made a typo when I tried that one earlier (and wasn't reading the error message clearly)... My bad. OK, thanks, this works ;-)

Although slightly different question: I see that `-show-last-archived` only gives me the last 2 versions, instead of 5. I have made several changes while testing so I would expect to see more?

**Comment by strib** [comment]
> OK, thanks, this works ;-)

Great!

> Although slightly different question: I see that -show-last-archived only gives me the last 2 versions, instead of 5. I have made several changes while testing so I would expect to see more?

This depends a lot on the pattern of your updates (how close together in time they happened, for example), and also over how much time they were spread.  It also wouldn't really count your latest update, since that hasn't been archived yet.
