### ISSUE TITLE
Font issue on Ubuntu 18.04

### ISSUE THREAD

**Issue by syphyr** [keybase/client#22485]
When using version 5.2.0-20200130211428.cf82db8320 on Ubuntu 18.04, the font is not displayed correctly for the "crypto" link in left column.  Example below:

![Screenshot from 2020-02-11 00-53-14](https://user-images.githubusercontent.com/5009268/74201191-4ddfa180-4c69-11ea-8340-f2ab930ef9b9.png)

Note: If I select garbled "crypto" letters in left column, then the garbled font becomes fixed.  The font for "crypto" becomes garbled again when it is unselected.

**Comment by spielkind** [comment]
@syphyr is this fixed for you, sill having this issue.

**Comment by syphyr** [comment]
No, it is still not fixed, but I think the issue might be with Ubuntu. Maybe I should reopen it.

**Comment by spielkind** [comment]
I have the same issue using gnome-shell 3.34.4 on ArchLinux, so probably not Ubuntu specific. :)

**Comment by syphyr** [comment]
Thanks for pointing that out. I guess I missed the "leet" point too.  IMO it looks janky. I'll close this again, but I hope someone changes it.
