### ISSUE TITLE
Dialog is partially cut-off on OSX

### ISSUE THREAD

**Issue by colindean** [keybase/client#2249]
![screen shot 2016-03-07 at 21 58 45](https://cloud.githubusercontent.com/assets/197224/13590693/11a03808-e4b0-11e5-8bf6-af09f5d1ec70.png)

It affected the upgrade prompt dialog, as well, but I didn't think to get a screenshot until this dialog.

OSX 10.11.3, 13" rMBP 2015

**Comment by gabriel** [comment]
This is fixed in a recent build. Thanks for reporting the issue :)
