### ISSUE TITLE
KBFS (and Keybase in general) doesn't work well without internet connectivity

### ISSUE THREAD

**Issue by jlb1234** [keybase/client#2253]
I've noticed that Keybase won't work without internet connectivity. It seems to call the Keybase api, for instance, whenever encrypting or decrypting a message/file. This makes sense if you are encrypting for a user who you aren't tracking as the service needs to find out what their public key is - and perhaps that it wants to check that the public key of a tracked user isn't changed. However: I've also noticed that KBFS files aren't available when you aren't online. My understanding is that KBFS is built not as a sync service but a streaming one - the files aren't stored on your computer but are loaded on demand. But what about when you are away from internet connectivity - eg. on an airplane, or your internet is just plain spotty - and want to access files there? KBFS should have an offline cache of the files in your private & public folders to allow you to access at least your own files, although read-only, while you're offline.

**Comment by strib** [comment]
https://keybase.io/docs/kbfs/understanding_kbfs states this pretty bluntly:

> Currently, KBFS requires network connectivity, and no offline reads/writes are possible.

Offline access is on our roadmap, but it's a very long road and it won't happen in the near future.
