### ISSUE TITLE
Error object could specify if it was triggered due to "canceling"

### ISSUE THREAD

**Issue by gabriel** [keybase/client#226]
If the daemon knows that an error was due to the user canceling (like saying no to a prompt, or hitting cancel on a password entry), would be good to set a flag (maybe severity flag or even a canceled bool) on the error object, so the client can be dumb and not keep state on these types of interactions.

For example, if an error is due to cancelation I wouldn't show the error message to the user (because they just hit the cancel button).

I'm assuming that the daemon knows that its a cancelation and that it would be trivial to set this flag when this happens.

**Comment by maxtaco** [comment]
Should be no prob, on it...
