### ISSUE TITLE
The new 'Crypto' menu item is translated in a different (Asian-like) language.

### ISSUE THREAD

**Issue by pvdl** [keybase/client#22639]
If you hover on it, it shows the correct menu item 'Crypto'.

**Comment by pvdl** [comment]
<img width="291" alt="Screenshot 2020-02-19 at 09 29 49" src="https://user-images.githubusercontent.com/1476340/74816036-9f87cc00-52fa-11ea-859b-d0f8b8b07d55.png">

**Comment by maxtaco** [comment]
Feature, not a bug.

**Comment by itsnotsaved** [comment]
https://github.com/keybase/client/issues/7368
