### ISSUE TITLE
TypeError in Keybase Chat GUI

### ISSUE THREAD

**Issue by srid** [keybase/client#22755]
Seeing this JS error in the Chat section of Keybase GUI on Linux:

```
TypeError: Cannot read property 'vratan' of undefined
    at Function.u.p._onAuthorClick.u.l.En.x.username [as mapToProps] (file:///nix/store/j3h96z8ra2dn5j7q26rf6cgq6q2n68m5-keybase-gui-5.1.1/share/keybase/resources/app/desktop/dist/main.bundle.js:1:2042250)
 ```

The keybase-gui CLI did spit out this warning; not sure if that's relevant:

```
▶ WARNING Service is running v5.0.0, while client is running v5.1.1.
▶ WARNING Skipping restart, because their paths differ:
▶ WARNING service: /nix/store/wi4ns3hnf359cacg8f1gwv32ll4ya5c7-keybase-5.0.0-bin/bin/keybase
▶ WARNING  client: /nix/store/q828c6fzgp8vxz8j61cs2hcx79v3277b-keybase-5.1.1-bin/bin/keybase
Version: 5.1.1-20191211223501+15bbb94c23
```

For the record, I'm on NixOS (`nixos-unstable` channel).

my log id: 00b2de1a16770cbf89f22b1c

![image](https://user-images.githubusercontent.com/3998/75353918-25b38d80-587a-11ea-88fe-5dacb383b687.png)

**Comment by maxtaco** [comment]
your app is in a broken, half-restarted state

cc @heronhaye

**Comment by srid** [comment]
Restarting the service (`systemctl --user restart keybase.service`) fixed it for me.

I don't know where a fix would go here: in keybase, or in nixpkgs. But I'll let you folks decide.

**Comment by heronhaye** [comment]
Looks like when you upgraded Keybase, the GUI restarted but not keybase.service or kbfs.service. What are the Nix maintainers instructions for what to do after upgrading Keybase?
