### ISSUE TITLE
[Mac desktop] Font render bug

### ISSUE THREAD

**Issue by rdela** [keybase/client#22754]
"Crypto" left-hand nav text and "Try it" button in Keybase FM 87.7 update about in-app Crypto [1] both are displaying odd characters instead of appropriate text, but correct text appears on hover.

This is very difficult to describe, so I made some quick screencasts, available to play at https://rdela.keybase.pub/bug/ and for download at https://keybase.pub/rdela/bug/

Direct Keybase links to files:
keybase://public/rdela/bug/font-bug-keybase-1-crypto.mov
keybase://public/rdela/bug/font-bug-keybase-2-try-it.mov

Keybase Version 5.2.1-20200225174716+9845113a89 (5.2.1-20200225174716+9845113a89)
macOS 10.14.6 (18G3020)

Here is a still image/screenshot of the issue, with pink box around buggy text:

![Screen Shot 2020-02-26 at 055043](https://user-images.githubusercontent.com/74381/75351179-8d5ae000-585c-11ea-9de2-0109e01653fb.png)

Please let me know if there is something you want me to try to help diagnose or debug.

[1]: Update text above image (inbetween) and button (bottom):

> Encrypt, decrypt, sign, and verify all from within Keybase (desktop-only). 🔐

**Comment by maxtaco** [comment]
Feature, not a bug!

**Comment by tln** [comment]
It may be intended but it's very odd. Looks more like "CASINO" than "CRYPTO" to me.

<img width="331" alt="can you read this" src="https://user-images.githubusercontent.com/1626192/80412215-5e73e100-8882-11ea-8c47-53b0a8e843a7.png">
