### ISSUE TITLE
Logging in with GPG no longer possible

### ISSUE THREAD

**Issue by colons** [keybase/client#22840]
Many many moons ago, I set up a keybase account and attached it to a few devices. My model of the account was based on the assumption I'd be able to log in with GPG, which was true at the time, so I took care to ensure my GPG config was kept safe. Device keys, not so much; I had no reason to care.

Despite no advance notification that this was changing as far as I've been able to find, this is [no longer true](https://github.com/keybase/client/issues/9716), and I realise now that am unable to access messages that have been sent to me in the intervening years, because I can't log in without wiping everything, even though I still control the GPG key linked to my account.

What was I supposed to have done to prevent this? What should I do now?

**Comment by maxtaco** [comment]
GPG is only used for authentication, and not for encryption by our system. So your data was never encrypted for your GPG key, and if you threw away your device keys and paper keys, your data is not recoverable.  You can reset your account to reuse your username. And if you share data with other users, you can ask that they reshare that data with you after you reestablish your account.
