### ISSUE TITLE
keybase blocked by mcafee from making risky connection

### ISSUE THREAD

**Issue by Engelberg** [keybase/client#22964]
McAfee virus checker is saying:
```
We blocked a risky connection
An app was trying to connect to a suspicious address
App: keybase utility
IP address 52.216.90.86
```

Any idea why keybase would be connecting to that ip address (which appears to be on multiple blacklists)?

**Comment by cjb** [comment]
@Engelberg It's an AWS EC2 IP address. Keybase is hosted on AWS.
