### ISSUE TITLE
How to start GUI?

### ISSUE THREAD

**Issue by korjavin** [keybase/client#22967]
[write something useful and descriptive here]

my log id: c1ce049c323e52c986d64d1c

Can we have a particular command to start GUI ?

**Comment by carroarmato0** [comment]
run_keybase should start the gui

**Comment by korjavin** [comment]
Yes, update solved the problem. I'm closing the issue.

**Comment by heronhaye** [comment]
All right, we've released version 5.3.1 which should fix the issue. Please upgrade and let me know if it still doesn't work.

If you installed the nightly, you can downgrade to the release version (manually reinstall from https://keybase.io/docs/the_app/install_linux), or you can just stay on the nightly (you'll get an update for the next stable release when it comes out).

**Comment by rokejulianlockhart** [comment]
@ricardobalk

```sh
keybase run_keybase
run_keybase
```

```log
PS /home/rokejulianlockhart> keybase run_keybase
No help topic for 'run_keybase'
PS /home/rokejulianlockhart> run_keybase        
run_keybase: The term 'run_keybase' is not recognized as a name of a cmdlet, function, script file, or executable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
PS /home/rokejulianlockhart>
```

**Comment by Espionage724** [comment]
I installed `keybase` on a whim on FreeBSD and I'm stuck on this too :p

`run_keybase` nor `keybase-gui` are usable:

```
pkg info -l 'keybase' | grep 'bin'
	/usr/local/bin/git-remote-keybase
	/usr/local/bin/kbfsfuse
	/usr/local/bin/kbfstool
	/usr/local/bin/keybase
```

I'll look more into this later and expect this to be FreeBSD-specific, but it wasn't as-easy as installing `keybase` and having an app launcher for the GUI or `run_keybase` like I expected from previous Linux and Windows client usage.
