### ISSUE TITLE
Keybase login on fresh WSL2 install throws EOF

### ISSUE THREAD

**Issue by LaxisB** [keybase/client#23054]
Hi guys, i'm getting a `ERROR EOF` when trying to login on a freshly installed ubuntu in the WSL2.
```
❯ uname -a
Linux freya 4.19.84-microsoft-standard #1 SMP Wed Nov 13 11:44:37 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

❯ neofetch
            .-/+oossssoo+/-.               brixl@freya
        `:+ssssssssssssssssss+:`           -----------
      -+ssssssssssssssssssyyssss+-         OS: Ubuntu 18.04.4 LTS on Windows 10 x86_64
    .ossssssssssssssssssdMMMNysssso.       Kernel: 4.19.84-microsoft-standard
   /ssssssssssshdmmNNmmyNMMMMhssssss/      Uptime: 36 mins
  +ssssssssshmydMMMMMMMNddddyssssssss+     Packages: 684
 /sssssssshNMMMyhhyyyyhmNMMMNhssssssss/    Shell: zsh 5.4.2
.ssssssssdMMMNhsssssssssshNMMMdssssssss.   Terminal: /dev/pts/0
+sssshhhyNMMNyssssssssssssyNMMMysssssss+   CPU: AMD Ryzen 7 3700X 8- (16) @ 3.593GHz
ossyNMMMNyMMhsssssssssssssshmmmhssssssso   Memory: 192MiB / 25624MiB
ossyNMMMNyMMhsssssssssssssshmmmhssssssso
+sssshhhyNMMNyssssssssssssyNMMMysssssss+
.ssssssssdMMMNhsssssssssshNMMMdssssssss.
 /sssssssshNMMMyhhyyyyhdNMMMNhssssssss/
  +sssssssssdmydMMMMMMMMddddyssssssss+
   /ssssssssssshdmNNNNmyNMMMMhssssss/
    .ossssssssssssssssssdMMMNysssso.
      -+sssssssssssssssssyyyssss+-
        `:+ssssssssssssssssss+:`
            .-/+oossssoo+/-.


❯ keybase -v
keybase version 5.3.0-20200310205642+4f2689009b

❯ keybase ping
▶ INFO API Server at https://api-0.core.keybaseapi.com is up

❯ keybase login notmyuser
▶ ERROR in Login

This username doesn't exist.

❯ keybase login laxis
▶ INFO Starting background server with pid=9407
▶ ERROR EOF
```

This might be related to #14243 and/or https://github.com/keybase/client/issues/20423 

bash history:
```
sudo apt update
sudo apt upgrade
sudo apt install neovim
sudo apt install openjdk-11-jdk openjdk-11-jre openjdk-11-doc
sudo apt -y install vim apt-transport-https dirmngr wget software-properties-common
sudo add-apt-repository ppa:cwchien/gradle
sudo apt update
sudo apt install gradle

curl --remote-name https://prerelease.keybase.io/keybase_amd64.deb
sudo apt install ./keybase_amd64.deb
rm keybase_amd64.deb
run_keybase
keybase
keybase status
keybase login
```

my log id: 128bee032eafdfd0c45b6f1c

**Comment by osioke** [comment]
I have this same issue, my log ID is 646c0de3392e82082c68e91c

**Comment by LaxisB** [comment]
@osioke 
a workaround that helped me is to update the wsl to form the lts version to 19.10:

- edit/etc/update-manager/release-upgrades, and set Prompt=normal
- sudo apt update
- sudo  apt ugpgrade
-  sudo do-release-upgrade -d


it doesn't resolve the issue of apt keybase not working on lts ubuntu under wsl, but it at least lets you use keybase

**Comment by heronhaye** [comment]
@osioke what version of keybase are you on? `keybase version`

**Comment by osioke** [comment]
@heronhaye 

Client:  5.3.1-20200320154633+3e235215b3

**Comment by osioke** [comment]
@LaxisB thank you for that! But I have a custom setting set up that took me a while to get working on LTS, moving now is so not an option. There are too many unknowns.

**Comment by heronhaye** [comment]
@osioke, thanks. What does `dbus-launch` print in your terminal?

**Comment by osioke** [comment]
@heronhaye 
```
D-Bus library appears to be incorrectly set up: see the manual page for dbus-uuidgen to correct this issue. (Failed to open "/var/lib/dbus/machine-id": No such file or directory; UUID file '/etc/machine-id' should contain a hex string of length 32, not length 0, with no other text)
DBUS_SESSION_BUS_ADDRESS=unix:abstract=/tmp/dbus-TV3AAAA6Hz,guid=2757258a49190f0b48a8854b5e78c723
DBUS_SESSION_BUS_PID=6691
```

**Comment by heronhaye** [comment]
(For the record, @LaxisB it looks like you ran into the same issue)

@osioke Is that first line coming in through stdout or stderr? What's the status code?

```
dbus-launch > stdout 2> stderr
echo $?
cat stdout
cat stderr
```

**Comment by LaxisB** [comment]
https://github.com/Microsoft/WSL/issues/2016#issuecomment-435091497 might help with the dbus issue

**Comment by heronhaye** [comment]
@osioke the quickest way to resolve this is to set `keybase config set -b force_less_safe_secret_store_file 1` and restart Keybase.
See more details about that option at https://keybase.io/docs/crypto/local-key-security - the keyring doesn't seem to be installed on your system so it's ok to fallback to the secret store file, unless you want to try and get gnome keyring installed and working.

**Comment by heronhaye** [comment]
That being said, we'll try to fix this on our side so it falls back automatically with a warning instead of crashing.

**Comment by LaxisB** [comment]
Thanks for the quick turnaround, @heronhaye !

**Comment by osioke** [comment]
> (For the record, @LaxisB it looks like you ran into the same issue)
> 
> @osioke Is that first line coming in through stdout or stderr? What's the status code?
> 
> ```
> dbus-launch > stdout 2> stderr
> echo $?
> cat stdout
> cat stderr
> ```

The first line is coming through stderr:

`osioke@Osioke-XPS:~$ cat stdout
DBUS_SESSION_BUS_ADDRESS=unix:abstract=/tmp/dbus-1EgnQzep6f,guid=a3b6fcd59fa055d59e7a297e5e78c9e8
DBUS_SESSION_BUS_PID=6701
osioke@Osioke-XPS:~$ cat stderr
D-Bus library appears to be incorrectly set up: see the manual page for dbus-uuidgen to correct this issue. (Failed to open "/var/lib/dbus/machine-id": No such file or directory; UUID file '/etc/machine-id' should contain a hex string of length 32, not length 0, with no other text)`

**Comment by osioke** [comment]
> @osioke the quickest way to resolve this is to set `keybase config set -b force_less_safe_secret_store_file 1` and restart Keybase.
> See more details about that option at https://keybase.io/docs/crypto/local-key-security - the keyring doesn't seem to be installed on your system so it's ok to fallback to the secret store file, unless you want to try and get gnome keyring installed and working.

@heronhaye this worked! Thank you very much for the quick fix!
