### ISSUE TITLE
Bot commands without args are not always encrypted for the bot

### ISSUE THREAD

**Issue by kf5grd** [keybase/client#23080]
When a bot adevrtises a command but does not require any arguments, the Keybase client does not encrypt that command unless it is sent with a space at the end.

For example, the githubbot's `list` command, if sent as `!github list` (no space after `list`) will not be encrypted for the bot, but if sent as `!github list<space>` it does get properly encrypted and the bot responds as expected.

**Comment by joshblum** [comment]
@kf5grd this should be fixed with the corresponding client change
