### ISSUE TITLE
404 on Keybase update check

### ISSUE THREAD

**Issue by RyanSinger** [keybase/client#2311]
```
Ryans-MacBook-Pro:~ ryan$ keybase update check
▶ INFO Checking for update, current version is 1.0.14-20160312001243+91a29db
▶ INFO Using updater source: Remote (https://s3.amazonaws.com/prerelease.keybase.io)
▶ INFO Request "https://s3.amazonaws.com/prerelease.keybase.io/update-darwin-prod.json"
▶ ERROR Updater remote returned bad status 404 Not Found
```
my log id: 112fe860a72fd92e4fb1a41c

**Comment by cjb** [comment]
Thanks. Half of the behavior is intentional: we disabled the daily builds on weekends. But it should have continued offering an older build. That'll fix itself on Monday.

Just to confirm: you only see this at the terminal, and otherwise everything's working?

**Comment by RyanSinger** [comment]
yep.

**Comment by cjb** [comment]
Fixed, closing.
