### ISSUE TITLE
KBFS: Decrypting, verifying, and down...

### ISSUE THREAD

**Issue by Jestre** [keybase/client#2314]
I am seeing this error pop up about once per minute:

>  KBFS: Decrypting, verifying, and down...
>   /keybase/Keybase.app is not a Keybase folder.  All folders begin with /keybase/private or /keybase/public.

`keybase status` appears correct, so I'm not sure what I may need to do to correct/silence the errors.

Versions:
  - Keybase: 1.0.14-20160311170010+46770d9
  - KBFS: 1.0.2-20160311170049+8addaa2
  - OS: El Capitan + patches

my log id: 88e17f41207e4fe3b4fe611c

**Comment by strib** [comment]
I'll add an exception for this lookup name today, so it doesn't trigger an error popup.  Sorry for the inconvenience!

**Comment by cjb** [comment]
@strib (any idea why it happens?)

**Comment by strib** [comment]
Nope.  Some OSX vagary I assume. Wasn't planning to spend many cycles trying to figure it out.

**Comment by cjb** [comment]
@strib ah, I'm a little surprised we didn't see it earlier -- did that error path just go in?

**Comment by strib** [comment]
Yep, last week.

**Comment by strib** [comment]
This is fixed in kbfs master now, and will go out in a release soon (next few days).
