### ISSUE TITLE
Error notification: KBFS: Decrypting, verifying, and downloading...

### ISSUE THREAD

**Issue by alexlafroscia** [keybase/client#2315]
Error text: 

> /keybase/Keybase.app is no a Keybase folder.  All folders begin with /keybase/private or keybase/public

This pops up every time I open any app.  Despite what the error message suggests, there doesn't actually seem to be a `/keybase/Keybase.app` directory.

***
Keybase GUI Version: 1.0.14-20160311170010+46770d9

**Comment by strib** [comment]
Dup of #2314.
