### ISSUE TITLE
Segmentation fault (core dumped): /opt/keybase/Keybase

### ISSUE THREAD

**Issue by ostehamster** [keybase/client#23163]
xxx:~$ /opt/keybase/Keybase 
Version: 5.3.0-20200310205642+4f2689009b
(electron) The default value of app.allowRendererProcessReuse is deprecated, it is currently "false".  It will change to be "true" in Electron 9.  For more information please check https://github.com/electron/electron/issues/18397
(electron) 'setAutoHideMenuBar function' is deprecated and will be removed. Please use 'autoHideMenuBar property' instead.
Segmentation fault (core dumped)

xxx:~$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 19.10
Release:	19.10
Codename:	eoan

my log id: 2de365aba189b2e49556581c

**Comment by ostehamster** [comment]
Duplicate of #23018

**Comment by ricardobalk** [comment]
Related to #23073

**Comment by heronhaye** [comment]
@ostehamster, please try out the nightly build (instructions at https://keybase.io/docs/linux-user-guide#nightly-builds) and let me know if it fixes the issue for you. I'll let you know when the next stable release is out.

**Comment by heronhaye** [comment]
All right, we've released version 5.3.1 which should fix the issue. Please upgrade and let me know if it still doesn't work.

If you installed the nightly, you can downgrade to the release version (manually reinstall from https://keybase.io/docs/the_app/install_linux), or you can just stay on the nightly (you'll get an update for the next stable release when it comes out).
