### ISSUE TITLE
Team stuck with no owner

### ISSUE THREAD

**Issue by trev-dev** [keybase/client#23176]
Hey There,

My sister created a team. Then less than a month later, we reformatted her machine. We realized after the fact that she never made a paper key or set up another device. Without this, or the correct password, we had to reset her account.

Since the reset, our team has no "owner." So far as I can tell, this just means that our team is _indestructable_ lol. But I don't know if there will be unexpected consequences later on.

When I think about it, if an owner has lost his/her trust on keybase, ownership should intuitively be passed on to the next available admin (if one is available). If there isn't one, there should be a process to decide another.

**Comment by maxtaco** [comment]
I agree that there is some policy here that makes sense, but it will be tricky to implement, and it hasn't be a priority yet.
