### ISSUE TITLE
Starting the Electrion app breaks font cache on Ubuntu 18.04

### ISSUE THREAD

**Issue by jlavelle** [keybase/client#23200]
After updating to 5.3, every time I start the Electron app I need to run `fc-cache -r` to get fonts to display correctly in many other applications.  This leads me to believe that the app is corrupting the font cache somehow.

The only other thing I've noticed is that the system tray icon is now very small, about 1/2 its normal diameter.
EDIT: I just saw #23021 regarding the tray icon, I don't know enough about Electron to determine whether or not it is related to the font cache issues.

**Comment by heronhaye** [comment]
We'll fix the small icon issue. Haven't had any other reports about the font issue. Do you have more details about your system? Any errors in the journal?

**Comment by Hoolean** [comment]
Hey @heronhaye : )

I've been having this issue with another Electron app, having to reissue `fc-cache -r` similarly. Did you ever work out the cause?

Cheers,
H

**Comment by jlavelle** [comment]
@Hoolean no, it randomly stopped happening one day, sorry. There didn't seem to be anything in the logs about it either, iirc.

Closing since it is no longer a problem, and could be an upstream issue anyway.

**Comment by Hoolean** [comment]
Super odd. I'll make sure to post back here if I ever isolate it, as this is one of the first search results for the problem.
