### ISSUE TITLE
Hangs at startup on MacOS

### ISSUE THREAD

**Issue by jrlevine** [keybase/client#23264]
When I start the MacOS app, which used to work, it just hangs. I think only the updater daemon starts.

my log id: 011b259bee32c67b1427e51c

**Comment by maxtaco** [comment]
Sent you some ideas over Keybase chat, but it's a permissions issues:

```
ERROR: open /Users/<your username>/Library/Application Support/Keybase/keybase.leveldb/LOCK: permission denied
```

**Comment by jrlevine** [comment]
Huh, did a 
chmod -R u+rw Library/Application Support/Keybase
and now it's happy. Wonder what happened to the permissions.

**Comment by maxtaco** [comment]
Great, glad that fixed it (our error reporting could be better of course).

Maybe you tried to run keybase as root?

**Comment by jrlevine** [comment]
No, I owned the files but something made them all read-only, perhaps the migration process from the disk on my old dead mac to the current one.
