### ISSUE TITLE
/keybase/Keybase.app is not a Keybase folder

### ISSUE THREAD

**Issue by lox** [keybase/client#2327]
Keybase GUI Version: 1.0.14-20160312013917+cd6f696

This just started happening, but I'm getting an OSX notification regularly with this message:

![message](http://lachlan.me/s/gKjxv.png)

**Comment by strib** [comment]
Thanks!  Dup of #2314, fixed in master, should be in a release in the next day or two.

**Comment by lox** [comment]
Ooops, apologies, should have looked first!
