### ISSUE TITLE
keybase no longer minimizes to the system tray on Debian

### ISSUE THREAD

**Issue by hlwsmith** [keybase/client#23318]
In addition `keybase log send` failed to create this bug report properly or give it no title (I just added one) and no description, although I entered one on the command line. It did spit out an error though.
"
No journal files were opened due to insufficient permissions.
▶ ERROR Error reading logs: Journalctl exited with an error: exit status 1

"

[write something useful and descriptive here]

my log id: 0e1ae2fb99a33d6c4e8d8b1c

**Comment by hlwsmith** [comment]
Closing this and putting a comment in #23266 instead. Seems like the same probelm

**Comment by hlwsmith** [comment]
Closing this and putting a comment in #23266 instead as it seems like the same issue.

**Comment by Staudey** [comment]
From the release notes for 5.3.0:

> Note: On some Linux platforms, specifically with window managers like i3wm and others without support for StatusNotifier, the system tray icon will no longer appears, so if Keybase is minimized, it must be restarted to display it again, though it is running in the background. Two workarounds (in official Keybase packages) are running /opt/keybase/Keybase and with systemd, systemctl --user restart keybase.gui). We're working on a better UX around this experience.

This is preventing me from updating the package for Solus, because the tray icon doesn't show up in the Budgie DE (and maybe others), which would be terribly confusing for users.
