### ISSUE TITLE
Windows - Keybase instantly closes

### ISSUE THREAD

**Issue by Eduardogbg** [keybase/client#2331]
Not much to say, but on Windows 10 the windows shows some text very quickly then closes. After trying hard enough, I managed to read it, and was just the instructions on how to use it, no error or anything.

**Comment by zanderz** [comment]
Are you launching "Keybase CMD" or just keybase.exe? keybase.exe is a command line program which exits after each command is processed, so it will be hard to see without a persistent console.

**Comment by Eduardogbg** [comment]
Tried both, but figured out the problem was that Keybase wasn't on PATH. Everything is fine then, I guess...
