### ISSUE TITLE
No "K:" drive when syncing files on Windows 10

### ISSUE THREAD

**Issue by dgellow** [keybase/client#23331]
Hi there,

I'm using keybase on Windows. I tried today to use the Keybase Filesystem, but while I can upload files by dropping them on the Keybase client, I cannot access the synced directory from Windows, because no `K:` drive exists.

![image](https://user-images.githubusercontent.com/2451004/77794824-d45f0f80-706c-11ea-85ec-1fba765789ad.png)

The relevant part from [the documentation](https://keybase.io/docs/kbfs):

![image](https://user-images.githubusercontent.com/2451004/77795114-50595780-706d-11ea-8bce-693d45c81290.png)

**Comment by proukornew** [comment]
@dgellow Install https://dokan-dev.github.io/ driver

**Comment by dgellow** [comment]
@proukornew Thanks, that worked. The documentation should be updated.
