### ISSUE TITLE
PGP import failed

### ISSUE THREAD

**Issue by Green-m** [keybase/client#23396]
Hello guys:

I cannot import my pgp keys, I am sure my keys are not expired.

![image](https://user-images.githubusercontent.com/22535454/78014096-037dc580-737a-11ea-9126-a1eec2bf2c81.png)

And the first time importing this key to keybase is successful one year ago, and this time I have reset my account and to import the same key failed. 

How to solve this? Anything help would appreciate.

my log id: bf5d4d3afe38d27ac1c89b1c

**Comment by maxtaco** [comment]
We don't accept SHA-1 anymore because it deeply broken and insecure.

See if you can find a tutorial on upgrading your key to use SHA-2. GPG makes it really hard, but it's definitely possible. @zapu do you have a link?

**Comment by zapu** [comment]
There was a user who managed to get their key upgraded here: https://github.com/keybase/client/issues/22458

**Comment by Green-m** [comment]
@maxtaco @zapu 
It works! Grateful for your help!
