### ISSUE TITLE
KBFS - files copied not appearing other devices

### ISSUE THREAD

**Issue by kellytrinh** [keybase/client#23425]
copy files into folder on linux box - doesn't appears on other connected windows device.

going vice versa direction seems fine tho

my log id: ef69447c9f0803892ad7521c

**Comment by strib** [comment]
Hi there, thanks for the report. KBFS is getting this error when trying to flush the local data to the servers:

```
tls: use of closed connection
```

I'm not sure what this could mean.  My first instinct is that it's a network/VPN problem.  But maybe a restart would help?

**Comment by kellytrinh** [comment]
don't run a VPN - this is a VPS Ubuntu box... nonetheless, did a reboot and it seemed to fix things

However have seperate issue from windows boxes now (see other report)  but at least this one resolved so closing.
