### ISSUE TITLE
Reset Account

### ISSUE THREAD

**Issue by KasaiDot** [keybase/client#23452]
Hi, before creating this issue I sent many emails to the admins, but no answers so GitHub is my sole solution.

For the past months I can't login to my keybase account 'cause I "lost" all keys (changed devices since then) but I can't reset my account since it is in "lockdown" mode.

Is there any way for the admins to reset/recover my account?

My email: me@kasai.moe

Thank you.

**Comment by hponde** [comment]
I'm in a similar situation, the laptop I had the keys stored (and did not have a backup :(, I know!) is gone and I cannot recover my account. I even received lumens from spacedrop that I cannot access. Is there any way to recover that or I need to nuke my account from scratch (it seems like I do)

Thanks for all the help in any case!
