### ISSUE TITLE
Rekeying necessary when other user has KB but not KBFS

### ISSUE THREAD

**Issue by FiloSottile** [keybase/client#2347]
benjojo installed KBFS and put something in our shared folder. I didn't have KBFS but did have KB. Then I installed KBFS, keeping my PGP key. Now rekeying is failing because benjojo is offline. Why didn't the files get encrypted with my PGP key, so that I could perform the rekeying myself?

Keybase GUI Version: 1.0.14-20160315130050+fc26e6b

**Comment by strib** [comment]
We don't use PGP keys for encrypting files for KBFS, only your per-device keys that are created when you install newer versions of Keybase.  See https://keybase.io/docs/crypto/kbfs for more details on our file system crypto.

**Comment by FiloSottile** [comment]
Agreed that this is by the spec. However I wonder why not smoothing the upgrade path. Should I file spec issues somewhere else?

**Comment by strib** [comment]
We have made an explicit decision not to support PGP keys for the file system.  Aside from the code complexity it would cause to support the different types of keys, we think it's dangerous to assume that the general population can manage their PGP private key securely, especially given the fact that some users store it on our servers.  We want to encourage a world where your private key never leaves your device, and for that reason right now we only support the device keys created by Keybase.
