### ISSUE TITLE
Deleting devices to re-provision them doesn't appear to clear them from the server

### ISSUE THREAD

**Issue by nistur** [keybase/client#2357]
Keybase GUI Version: 1.0.14-20160316190012+580f36e

If I add a device with `keybase device add`/`keybase login` and then remove the device using `keybase device remove`, then once again try to re-provision the device with the same procedure, I cannot use the same name as it is already in use
`ERROR Device name is already in use by this user (error 1408)`

I have had to do this several times, once as I had lost my GPG password, and had to reset my keys. It seems weird that I cannot use the name again.

**Comment by cjb** [comment]
It's intentional for security reasons, but we've got another ticket open about improving the docs to make it clear that device names are permanent.

**Comment by BM5k** [comment]
@cjb like @nistur I re-installed my OS. I'm not renaming my laptop because "device names are permanent" it _is_ the same device.

Please advise.

**Comment by cjb** [comment]
@BM5k Do you still have a copy of the pre-reinstall OS with your device key on?  If so, it's possible restablish your new OS as being the same device by restoring the Keybase directories from the old OS.

If the device key was destroyed, then I'm afraid from the point of view of other people, it is no longer the same device and can't reuse the same name.

**Comment by tammersaleh** [comment]
@cjb  I'm in the same situation.  Which directories need to be recovered for this to work?
