### ISSUE TITLE
Keybase filesystem fail on public/chris and public/myself

### ISSUE THREAD

**Issue by OliverCole** [keybase/client#2358]
So I got this at the end of installation of the alpha:

````
$ run_keybase
Launching keybase service...
Mounting /keybase...
Launching Keybase GUI...
Success!
````

/keybase contains public and private. But accessing /keybase/public/chris or /keybase/public/olivercole blocks - with ls, or in a GUI tool.

my log id: fd66356e6f0bd08b87a5f41c

**Comment by strib** [comment]
Thanks @OliverCole.  It thinks you need to login to Keybase:

```
MDServerRemote: connection error: "Login required: KBFS Authentication"
```

Did you get a popup asking for your Keybase passphrase?

Perhaps relatedly, the `log send` tool didn't send any GUI logs, so maybe the GUI isn't working properly and that's why there was no passphrase popup?

**Comment by strib** [comment]
By the way, you can enter your passphrase manually with `keybase login` or maybe `keybase unlock` if the GUI popups aren't working still.

**Comment by OliverCole** [comment]
I did the `keybase login` after the install, it didn't return anything.
I did the install, login, cd and ls all over ssh to the device with keybase because I'm lazy... I didn't get a prompt at any point.
Doing `keybase unlock` (again over ssh) worked, and I can now see both directories.

Not sure what you mean by GUI - I've never seen one.

While I've got your attention - any thoughts on keybase/keybase-issues#2112 ?

**Comment by strib** [comment]
In the original post you mention a "GUI tool", I thought you meant the Keybase app GUI.  Do you mean the file explorer on your local machine then?  Do you have a GUI environment or are you trying to run headless (e.g., #1944/#2004, where `keybase unlock` is an undocumented requirement).

It looks like the Keybase GUI is not running in your environment for some reason.  If you think it should be, let us know.

(And sorry, I'm not the right person to look at OpenPGP issues, I know nothing.)

**Comment by OliverCole** [comment]
Ah yes, I just meant a file browser in ubuntu. I've previously used the main release in a terminal running in a console GUI session, and not seen a keybase GUI.

I guess today I was effectively running it headless over ssh, but that's not how I usually operate it. Should I open a separate issue for missing keybase GUI?

**Comment by strib** [comment]
The GUI is new to the file system alpha.

Did you run `run_keybase` in the ssh session?  If so, then it's a known issue that there's not a GUI (and it's not an officially supported mode yet).

**Comment by OliverCole** [comment]
I did. So I killed the keybase service and fuse session, and did `run_keybase` from the console. That got me a tray icon.

The resulting GUI says I wasn't logged in. `keybase login` had no effect, so I did `keybase unlock` instead, which did result in a GUI passphrase entry screen.

But the tray icon still says I'm not logged in. I've done a new `log send`.

2b561965e357007e8d95f71c

**Comment by strib** [comment]
Thanks.  @cjb is this latest issue a dup of anything known?

**Comment by cjb** [comment]
Not sure, better ask @patrickxb.

**Comment by strib** [comment]
@cjb: his `keybase status` shows that the service thinks it's logged in and unlocked:

```
 "LoggedIn": true,
   "KeychainUnlocked": true,
```

That's why I thought it was a GUI thing.  But I guess there could be a missing notification from the service that @patrickxb might be able to investigate.

**Comment by cjb** [comment]
Oh, I see:

957 log: Wed Mar 16 2016 22:16:31 GMT+0000 (GMT) (1458166591717): RPC [W] localhost: Error: connect ENOENT /keybase/keybased.sock

I wonder why it's looking there..

**Comment by patrickxb** [comment]
Both log dumps shows kbfs looking for a socket file in 

    21 Dialing unix:/home/oli/.config/keybase/keybased.sock

`.config/keybase` is what the node client used.  I wonder if that is confusing things?  However this account looks like it was created with the go client:

https://keybase.io/olivercole/sigchain#79aa25f235839f32e91abf51293a9f730afea3f58618a3d4bbfa8f764ed854de0f

I don't know how it could get that path.  On linux it should be `~/.config/keybased.sock`.

Confusingly, the gui is looking for the socket in `/keybase/keyabsed.sock`.

Are the environment variables  `KEYBASE_SOCKET_FILE` or `XDG_RUNTIME_DIR` set?

**Comment by OliverCole** [comment]
Account was created with go client.
There's no keybased.sock in ~/.config.
Those environment variables are not set.

**Comment by OliverCole** [comment]
Upgraded to Ubuntu 14.04 (about time too!) - folder GUI now works, KB branded pass phrase entry and notifications about rekeying etc in the corner. All looks good to me :)
