### ISSUE TITLE
I lost my files Error code 218 MD revision 3785

### ISSUE THREAD

**Issue by szirtes** [keybase/client#23607]
[write something useful and descriptive here]
![image](https://user-images.githubusercontent.com/63397092/78879041-a22db480-7a53-11ea-8518-4c219f09856b.png)

my log id: 19efaf6449c8c3432b2ca91c

**Comment by maxtaco** [comment]
Hi, did you try to push that "resolve conflict" button?

**Comment by szirtes** [comment]
Hi, Yes. After it i get this screen

**Comment by maxtaco** [comment]
Why did you close the issue?

**Comment by szirtes** [comment]
Sorry

**Comment by strib** [comment]
Hi, thanks for the report and sorry for the bad experience.  It looks like it hit a bug in our code that tries to automatically rewind your local file state when clearing a conflict.  I'll look into the bug, but for now here's a manual recovery process:

* Restart Keybase/KBFS, and you should be back to the correct local view of the folder (i.e., the one containing files that aren't uploaded yet).
* Save copies of any un-uploaded files to your local hard drive.
* Stop Keybase/KBFS.
* Then find the local directory `%APPDATA%\Local\Keybase\kbfs_journ
al\v1\01203ae6015cd85b0b172d02c87db668a200-0448977d38591ce0`, and rename it to something else like `0448977d38591ce0.bkp`.
* Restart KBFS, and you should be back to the server's view of the folder.
* Then you can try copying those files into it again.

**Comment by szirtes** [comment]
Thanks for your help. It's working. I'm very happy, thank you
