### ISSUE TITLE
`cd /keybase/` Permission denied

### ISSUE THREAD

**Issue by erikhuizinga** [keybase/client#23645]
Like #18303, I get a permission denied when I `cd /keybase/`.

It's been a while since I used keybase from the CLI, so I'm not sure if I'm doing something wrong. I already tried logging out and logging back in, to maybe reset an old session or something, but no luck.

I'll send my logs and reply here.

**Comment by erikhuizinga** [comment]
a6dbc17cf86d45f188a7d21c

**Comment by strib** [comment]
It looks like you don't have the Finder integration enabled for that device.  What happens when you go to the "Files" section in the Keybase app?  Does it give you an option to enable the integration?

**Comment by erikhuizinga** [comment]
That is the solution.

The setting does indeed prompt me to install the FUSE for macOS kernel extension, so I didn't have the Finder integration installed.

This is a UX issue, where it would have helped me if:

- that setting showed me that it applies to the macOS file system in general (e.g. for shell access), not just the macOS Finder.
- the shell access (e.g. `cd /keybase/` or `ls /keybase/`) would respond with an error message telling me about this Keybase setting, instead of 'Permission denied'.

**Comment by erikhuizinga** [comment]
Thanks for the help! :)
