### ISSUE TITLE
keybase needs dependency on fuse

### ISSUE THREAD

**Issue by qbi** [keybase/client#2368]
I installed the latest keybase version today and wanted to play around with the filesystem. However it didn't work. Looking at the logs I found

> kbfsfuse error: (2) fusermount: exec: "fusermount": executable file not found in $PATH

The software `fusermount` is in the package `fuse` (Debian GNU/Linux sid) and `fuse` was not installed at this computer. So I suggest to add a dependency to `fuse` so that it will be installed after running `sudo apt-get install -f`.

my log id: 337b01e01a5b4b92eb14621c

**Comment by cjb** [comment]
Thanks.  Did it work okay after you installed fuse?

**Comment by qbi** [comment]
Sorry, forgot to mention it.
Yes, after `apt-get install fuse` and `run_keybase` it worked.

**Comment by cjb** [comment]
@oconnor663 want to consider adding a fuse package .deb dependency?

**Comment by oconnor663** [comment]
Yep. I think we've already [eaten that banana](http://dilbert.com/strip/1998-08-15) with the `libappindicator` dependency.

**Comment by qbi** [comment]
keybase has a dependency on `libappindicator1`, but neither `libappindicator1` nor `keybase` itself have some dependency on `fuse`.

**Comment by oconnor663** [comment]
Yes, sorry, what I meant was, we allowed ourselves to take a dependency already, which means we need the `sudo apt-get install -f` step after the `dpkg` step. I didn't like that very much when we did it. But at this point taking another dependency doesn't cost us anything.

**Comment by oconnor663** [comment]
Should be fixed now!
