### ISSUE TITLE
two directories inside .config ?

### ISSUE THREAD

**Issue by fullmooninu** [keybase/client#23689]
Hi, I recently formatted my machine and I'm seeing this. T

~/.config$ ls -d *base
keybase  Keybase

I$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 19.10
Release:	19.10
Codename:	eoan

$ keybase version
Client:  5.3.1-20200320154633+3e235215b3
Service: 5.3.1-20200320154633+3e235215b3

**Comment by heronhaye** [comment]
`keybase` is for the core service and `Keybase` is for the Electron gui.
