### ISSUE TITLE
Can't prove github

### ISSUE THREAD

**Issue by squintgit** [keybase/client#23708]
My keybase.md public gist is here:

https://gist.github.com/squintgit/e7ef175939098d4b324ad573b7f5e020

But I got the email from you saying it the proof never succeeded:

-----------

Hi, squint, your attempted github identity proof of @squintgit never succeeded. We've been checking it repeatedly, and from our perspective, it's either (a) not there, or (b) not posted precisely.

If you think there's a bug, please post an issue on github. Include the link to your proof.

-----------

Is there a bug here? I renamed myself on github a few days ago, that's why my other proof broke.

**Comment by daten** [comment]
I believe I'm observing the same issue.

https://gist.github.com/daten/17bfc98a40a17911fe5d624100e198d2

**Comment by mmou** [comment]
Can you both try reposting your proof with the text you have before the `### Keybase proof....` removed? There cannot be any text before the "Keybase proof" heading. Thanks!

**Comment by squintgit** [comment]
Removed ‘squint’ above ### Keybase proof.  When I re-ran "keybase prove”, it ends up saying "Couldn't find posted proof.”

Maybe just needs some time?

<img width="363" alt="Screen Shot 2020-04-20 at 5 56 27 PM" src="https://user-images.githubusercontent.com/11663794/79807383-566eeb00-8330-11ea-9c36-aa8c7cb1657d.png">

**Comment by daten** [comment]
I had to revoke the previous attempt and try again with a fresh attempt. It worked without the additional text at the beginning (that the earlier keybase software auto-generated for me).

**Comment by squintgit** [comment]
Revoked and then recreating worked.

Not sure how that text snuck in the first one.

Thanks!
