### ISSUE TITLE
KBFS Keybase.dmg REALLY doesn't do anything

### ISSUE THREAD

**Issue by NoSubstitute** [keybase/client#2375]
Downloaded the file after being invited to the KBFS trial.
Moved it to my Applications folder. It still looks like Keybase.dmg.
Double-click, I get an error message. "Can't open image. Keybase.dmg Image not recognised."
Same if I double-click where the file is downloaded. DMG isn't recognised as an install image. Can't be mounted.

Tried downloading a few times, using different browsers, but getting the same (not working) result.

Updated homebrew version, but that doesn't include KBFS.

Eventually I figured out a way to get around this.
I used _Extractor_ to unpack the DMG and then I could add Keybase to my apps and it seems to work fine now.

**Comment by cjb** [comment]
Thanks for the report, this is fixed now.

**Comment by gabriel** [comment]
Oops, yeah, our build script had a bug yesterday where it was copying over the zip to the dmg path... which is why you were able to extract it... The zip and dmg both contain the same Keybase.app so you should be ok.
