### ISSUE TITLE
Copy fails 

### ISSUE THREAD

**Issue by sirishkumar** [keybase/client#2378]
Keybase GUI Version: 1.0.14
Copy to private folder on windows fails with below error

![keybase](https://cloud.githubusercontent.com/assets/27522/13885070/1183001a-ed31-11e5-907f-adb8b548ca11.png)

System is not low resources(neither cpu or harddisk). Not sure whether I reached my storage quota in keybase

**Comment by strib** [comment]
@sirishkumar: We are probably returning a generic error and that's how Windows is interpreting it.  Can you please do a `keybase log send` and report the ID here so we can see what went wrong?  Thanks.

**Comment by taruti** [comment]
That error is Windows being confused, not a lack of resources. 

Please send logs or steps to reproduce this.

**Comment by sirishkumar** [comment]
Here is the log id b0d75c4c9ef1e0dde12cc41c

**Comment by sirishkumar** [comment]
Works fine with Keybase GUI Version: 1.0.15-20160404143119+62c0932
