### ISSUE TITLE
Multiple identities set up to stay logged in don't show notifications

### ISSUE THREAD

**Issue by mvdan** [keybase/client#23850]
Multiple identities works great - thanks so much for this feature! I use this feature, along with "stay logged in" under advanced settings, to easily switch between accounts.

However, if someone sends me a message, or if I have any other notifications under one of my other accounts, I won't notice until I happen to switch to that account on my laptop or phone.

Is there a reason behind this design, like the cost of the extra traffic, or the extra CPU cost of the crypto work? If so, I would say that this should be up to the user. Maybe the client could have a limit on the number of accounts to keep "logged in", or at least show a warning, if the cost increases rapidly. For example, after five accounts, as I expect most only have 2-3 accounts at maximum.

**Comment by mvdan** [comment]
Also, please let me know if this is meant to work. I've done multiple tests on both desktop and mobile, and I only receive notifications for the account that I've got currently open.

**Comment by dhda** [comment]
I get notifications across all of my logged in accounts on iOS.

**Comment by mvdan** [comment]
Hm, I haven't been able to get that working on neither Linux desktop nor Android.

**Comment by jw4466261** [comment]
https://assetvest.org company is a changing situation in the world economy and financial markets. They ensure that the returns are satisfactory and 100% risk free. predominantly, Assetvest company has been the strong proponent investment strategies for natural resources, stock market and cryptocurrency investment program where investors make daily profits using the ROI (Return on investment) they have stabilized an efficient trading strategy to ensure maximum profit on real stocks, natural resources and Cryptocurrency investments.from what you've invested in the company and they also offer 2.25%-1.77% transfer commission with a minimum deposit of $ 100, The maximum deposit on their investment section (plan)depends on the investment category you are investing on. Their tier is unlimited as the company has multiple investment plans that work well and each of the investment plans has it own percentage offer. Their withdrawal are fast to any external wallet. meaning that after 3days of your investment, you can choose to withdraw both your capital and daily profits. You can even increase your investment by reloading your investment plan, making a new deposit or requesting a new withdrawal limit, you can choose to make a deposit as many times a day or at any time of your choosing as soon as you're liquid enough on your cash flow to make deposits. The same applies when prompted to do so, depending on the amount you have on your balance, you can withdraw at any time. The higher your investment, the faster the returns you will receive in return will grow. They're very stable and profitable. And also fast during the withdrawal on every withdrawal transaction.
