### ISSUE TITLE
Double and blank channels

### ISSUE THREAD

**Issue by xzell** [keybase/client#23866]
Login into keybase this morning I noticed my general channel in my team and subteams was blank (labeled as "#" instead of "#general"). So now I have an old general channel (#) and a new general channel (#general). The old general channel is listed as one that can be deleted but when I attempt to delete it I get Error code 2516 while the new general channel is greyed out. 

This bug is also inconsistent across platforms. On Windows it looks like # and #general but on Android it looks like there are two #general channels.

**Comment by joshblum** [comment]
@xzell can you do a log send and DM me the id? you can go to `settings > advanced > feedback` to submit

**Comment by joshblum** [comment]
Resolved via chat

**Comment by cedricwinterwolf** [comment]
@joshblum I'm having a similar issue, have a channel that I cannot seem to delete or change the name, error code 2516.

Could you post the fix publicly so I can delete this channel?

**Comment by joshblum** [comment]
@cedricwinterwolf can you do a log send and DM the id?

**Comment by cedricwinterwolf** [comment]
I sent the logs in through the "please tell us" submission a while ago. Not sure how to grab them and send them here.
