### ISSUE TITLE
Private key encrypt and upload hangs

### ISSUE THREAD

**Issue by jeremiah** [keybase/client#2398]
Private key encrypt and upload hangs when I enter my private GPG key. The "encrypt" button appears after I've uploaded my private key (or rather placed it in the text field) and then the "wait for it button" appears (grayed out) but nothing happens.

**Comment by maxtaco** [comment]
Hmmm, couldn't repro this one.  Did you see any errors in your JavaScript console?

**Comment by jeremiah** [comment]
I'll run this again with the JS console open. I have a largeish key (4096), would that be causing the issue?

**Comment by maxtaco** [comment]
Probably not!

**Comment by jeremiah** [comment]
Right-O. I'll come back to this report with some data from the console.

**Comment by jeremiah** [comment]
I've achieved success this time. Closing this bug, or "issue".
