### ISSUE TITLE
Keybase app fails to start on Windows 10

### ISSUE THREAD

**Issue by AleksueiR** [keybase/client#23993]
Keybase service runs fine and I can send messages with it, but when trying to start keybase app, nothing happens. No entries are written to `Keybase.app.log` either.

```
Service:
    status:    running
    version:   5.4.2-20200424164159+7b0bbf1e3c
    log:       ...\AppData\Local\Keybase\keybase.service.log
    eklog:     ...\AppData\Local\Keybase\keybase.ek.log
    perflog:   ...\AppData\Local\Keybase\keybase.perf.log

Platform Information:
    OS:        windows
    OS vers:   Microsoft Windows [Version 10.0.18363.815]
    Runtime:   go1.13.7
    Arch:      amd64

Client:
    version:   5.4.2-20200424164159+7b0bbf1e3c

Desktop app:
    status:    not running
    version:
    log:       ...\AppData\Local\Keybase\Keybase.app.log
```

Thank you.

**Comment by alex1a** [comment]
I think I'm experiencing the same problem, I tried to uninstall the client and when I try to install it again, the installer doesn't even open

**Comment by AleksueiR** [comment]
@alex1a I've tried that as well, but it doesn't work for me.

**Comment by alex1a** [comment]
> @alex1a I've tried that as well, but it doesn't work for me.

Already try to reinstall? I mean, uninstall, wipe all files from appdata and install again?

**Comment by AleksueiR** [comment]
Ran the uninstaller twice and nothing happened, as in the app is still here. However, now it actually starts up. 🎉  So, I guess this can be closed.

**Comment by alex1a** [comment]
> 
> 
> Ran the uninstaller twice and nothing happened, as in the app is still here. However, now it actually starts up (not sure what happened there). 🎉 So, I guess this can be closed.

Same problem with me, uninstaller doesn't do nothing, and magically keybase start working

**Comment by simon1tan** [comment]
this is called junk
