### ISSUE TITLE
Updating keybase client on server

### ISSUE THREAD

**Issue by sirishkumar** [keybase/client#2400]
Hi,

I installed keybase on a virtual machine hosted by digital ocean. Suddenly it stopped working and I no longer see the folders under /keybase directory. KBFS status indicate that it was not running. Restart of the host did not worked. 

So I downloaded the latest version again from s3 and followed the installation instructions. It started working again. 

Running keybase update run gave error 
> "Error parsing command line arguments: No default destination path for this environment"

How auto update of keybase client works in this case without UI?

Logid :  1320e4f5039a7a58955f941c

**Comment by cjb** [comment]
You upgrade using your system's package manager, e.g. `sudo apt-get update && sudo apt-get upgrade keybase && run_keybase`.
