### ISSUE TITLE
Can't access my account and I've lost my login

### ISSUE THREAD

**Issue by e-edgren** [keybase/client#24117]
Hi.

I want to login to my Keybase account, but I've lost my login credentials. On top of that, I deleted my email account few months ago and I believe that email address are registered on my Keybase account.

However, I can prove that I own my account at Keybase and I am only asking you for changing my email address. That's it. Is that possible?

**Comment by yericua** [comment]
you need to make a new account.

**Comment by e-edgren** [comment]
But I can prove that I own that account. Is there no way for me to get access to the account even if I can prove that I own that account?

**Comment by yericua** [comment]
No way..

**Comment by e-edgren** [comment]
I must ask, why?

**Comment by e-edgren** [comment]
I have my backup key for my Keybase account, I know my username, and I know what email address the account are registered on (99% sure now). Why can't you (Keybase) help me change my account's email address for me so I can continue using my account again?

**Comment by e-edgren** [comment]
I have now access to my account.
