### ISSUE TITLE
ERROR API network error: certificate is valid for *.videoblocksdev.com, not api-0.core.keybaseapi.com

### ISSUE THREAD

**Issue by max-l** [keybase/client#24127]
As of today, many GUI function are broken, keybase ping returns error below.
The message looks kind of scary, what is "videoblocksdev.com" doing in there... have I been hacked ?

Most functions are also broken on my phone, and the error messages are similar

     ~$ keybase --version 
         keybase version 5.4.2-20200424214931+7b0bbf1e3c

```
~$ keybase ping 
▶ ERROR API network error: Post https://api-0.core.keybaseapi.com/_/api/1.0/ping.json: x509: certificate is valid for *.videoblocksdev.com, not api-0.core.keybaseapi.com

```
`
Error: ERROR CODE 1601 - API network error: Get https://api-0.core.keybaseapi.com/_/api/1.0/team/get.json?lookup_only=1&team=genap: x509: certificate is valid for *.videoblocksdev.com, not api-0.core.keybaseapi.com in method keybase.1.SimpleFS.simpleFSStat at new RPCError (file:///opt/keybase/resources/app/desktop/dist/main.bundle.js:1:1034496) at convertToRPCError (file:///opt/keybase/resources/app/desktop/dist/main.bundle.js:1:1035383) at convertToError (file:///opt/keybase/resources/app/desktop/dist/main.bundle.js:1:1035442) at file:///opt/keybase/resources/app/desktop/dist/main.bundle.js:1:2408810 at file:///opt/keybase/resources/app/desktop/dist/vendors~main.bundle.js:2:205362 at Deferrals._call (file:///opt/keybase/resources/app/desktop/dist/vendors~main.bundle.js:2:10925) at file:///opt/keybase/resources/app/desktop/dist/vendors~main.bundle.js:2:11117 at trampoline (file:///opt/keybase/resources/app/desktop/dist/vendors~main.bundle.js:2:10653) at Deferrals._fulfill (file:///opt/keybase/resources/app/desktop/dist/vendors~main.bundle.js:2:11070) at ret (file:///opt/keybase/resources/app/desktop/dist/vendors~main.bundle.js:2:10066)
`

**Comment by yericua** [comment]
i just tested, not getting any issue. No weird error like you encountered. Is your computer infected by malware or something? worth to scan it out.

**Comment by max-l** [comment]
It seems like it could be a MITM (man in the middle) in my router or upstream in my network.

**Comment by max-l** [comment]
Rebooted the router and Keybase problem solved. The router problem is however not solved, will need a hard drive reset !
