### ISSUE TITLE
Keybase Mac client periodically shows notification "/keybase/Keybase.app not a keybase folder"

### ISSUE THREAD

**Issue by sirishkumar** [keybase/client#2413]
On Keybase Mac client I keep getting following notification periodically.

![screenshot 2016-03-21 21 28 59](https://cloud.githubusercontent.com/assets/27522/13932977/1d6c4db0-efab-11e5-8ada-8ca4a30504c5.png)

Log id: c713b2b46c7832cc4d984a1c

**Comment by strib** [comment]
That's fixed in more recent versions. Please try `keybase update run` to get a newer version of the client.

**Comment by sirishkumar** [comment]
Update fixes this issue
