### ISSUE TITLE
'You accessed a public folder with _NAME_' dialog is popping way too many times a day.

### ISSUE THREAD

**Issue by grempe** [keybase/client#2417]
I am seeing the attached dialog somewhere between 10 and 20 times a day.

When it pops I am typically doing nothing on the file system to intentionally cause that. I do not even have File Manager open.  I do have a folder tracking @malgorithms but I pretty much never open it.  I can only imagine that some sort background process like spotlight indexing or time machine is accessing that dir and causing this dialog to pop.

<img width="320" alt="screenshot_3_21_16__11_43_pm" src="https://cloud.githubusercontent.com/assets/117/13944107/884dab2e-efbf-11e5-9c05-3e18466479f5.png">

Help?!

**Comment by cjb** [comment]
Yeah, it does sound like a background process.  Please could you run `keybase log send`?

**Comment by grempe** [comment]
Success! Your log ID is:

  d39065b2f40967fc9d19491c

**Comment by cjb** [comment]
@grempe Please could you `keybase update run` to get a newer version?

It looks like you were hitting an app that used to be in @malgorithms' verified_software dir but isn't anymore.. I wonder if you accessed it intentionally or if Spotlight or a virus checker was doing so.  It looks like it's not there anymore, so I wonder why that's the case too!

**Comment by strib** [comment]
@cjb: but why is it triggering a tracker popup when he already tracks chris?  Is this a known bug that was fixed in a later version?

**Comment by maxtaco** [comment]
Indeed!  @malgorithms revoked a proof and the tracker popup was leaving that part off

**Comment by cjb** [comment]
Yes, as @maxtaco said.

**Comment by strib** [comment]
Ah, excellent, thanks for the explanation.

The spidering is a separate issue that shouldn't really cause any problems, but down the road we should try to discourage auto-spidering as much as possible.  I believe we already prevent Spotlight spidering because root cannot access the mount, but maybe time machine or a virus running as the user is able to spider still.

**Comment by grempe** [comment]
There is no process I am aware of that is spidering. I also do not have an anti-virus software running on OS X.  I do not keep a time machine drive hooked up all the time, only occasionally, but I am not sure if Time Machine is browsing that dir to keep local backups.

I have occasionally browsed in @malgorithms dir on my machine just to see what he has in there.  But I did not run any software from his dir.  I have not looked in that dir very recently.

I was thinking the popup might be related to the auto-update functionality of the client software which happens in the background and I have no visibility to?

When is it *intended* for me to see that popup?  That was not documented and it just started showing up one day.

**Comment by strib** [comment]
You were intended to see a version of that tracker popup, alerting you to changes in chris's profile, but due to a bug those changes weren't being shown to you.  Presumably, you would have re-tracked chris the first time you saw the popup (assuming you thought the changes were reasonable), and then it wouldn't have popped up again.

Yes, it's a little weird that you can get a popup when you're not actively browsing.  Unfortunately, KBFS can't tell the difference between you and a program (like anti-virus) acting on your behalf, and we need to make sure that you still trust this new version of chris before serving you up any data that is potentially compromised.

**Comment by grempe** [comment]
OK, makes sense.  Do I need to do anything?  Or will I see something different in an upcoming daily release?

**Comment by strib** [comment]
Once you update, the next time your machine tries to access a `chris` folder, you should see the right popup, at which point you can take an action (like re-track) and not have to suffer the popups anymore (until the next time chris makes a change like that).

**Comment by cjb** [comment]
@grempe Did you run `keybase update run`?  The new release is out already.

**Comment by grempe** [comment]
OK, I just ran the update.  I was under the impression that the client was updating itself automatically in the background and that I didn't have to take any action.  Looks like my client was about 10 days old.

```
~/$ keybase version
Client:  1.0.14-20160312001243+91a29db
Service: 1.0.14-20160312001243+91a29db
~/$ keybase update run
▶ INFO Checking for update, current version is 1.0.14-20160312001243+91a29db
▶ INFO Using updater source: Remote (https://s3.amazonaws.com/prerelease.keybase.io)
▶ INFO Request "https://s3.amazonaws.com/prerelease.keybase.io/update-darwin-prod.json"
▶ INFO Checking update with version: 1.0.14-20160321130023+389df14
▶ INFO Request https://s3.amazonaws.com/prerelease.keybase.io/darwin-updates/Keybase-1.0.14-20160321130023%2B389df14.zip
▶ INFO Downloading to /var/folders/q6/_0v1bz590bxfrmsmldsm8h4m0000gn/T/KeybaseUpdates/Keybase-1.0.14-20160321130023+389df14.zip.download
▶ INFO Downloaded 58457305 bytes
▶ INFO Verified digest: 32fc83a24ba754015691993c93f773998b112e6cedceddc2febed02d25dc3db7 (/var/folders/q6/_0v1bz590bxfrmsmldsm8h4m0000gn/T/KeybaseUpdates/Keybase-1.0.14-20160321130023+389df14.zip.download)
▶ INFO Moving Keybase-1.0.14-20160321130023+389df14.zip.download to Keybase-1.0.14-20160321130023+389df14.zip
▶ WARNING Continuing despite error in lsof: Error running /usr/sbin/lsof [-w -F pcuftn /keybase]: exit status 1 ()
▶ INFO Verifying signature BEGIN KEYBASE SALTPACK DETACHED SIGNATURE. kXR7VktZdyH7rvq v5wcIkPOwDJ1n11 M8RnkLKQGO2f3Bb fzCeMYz4S6oxLAy Cco4N255JFMYjyl vHpjdcDs8K00KL1 RuNATjUQarWhp1a Hpj6RuvM385AtUR QojLDJ7RQJNP6Rt X5VRq4TcM1tC1hC ICFnmTLEhVvZwfV F6Crafv0oploGyR F. END KEYBASE SALTPACK DETACHED SIGNATURE.

▶ INFO Signed by 01209092ae4e790763dc7343851b977930f35b16cf43ab0ad900a2af3d3ad5cea1a10a
▶ WARNING No codesigning keys to verify
▶ INFO Unzipping "/var/folders/q6/_0v1bz590bxfrmsmldsm8h4m0000gn/T/KeybaseUpdates/Keybase-1.0.14-20160321130023+389df14.zip" -> "/var/folders/q6/_0v1bz590bxfrmsmldsm8h4m0000gn/T/KeybaseUpdates/Keybase-1.0.14-20160321130023+389df14.zip.unzipped"
▶ INFO Unzip path: /var/folders/q6/_0v1bz590bxfrmsmldsm8h4m0000gn/T/KeybaseUpdates/Keybase-1.0.14-20160321130023+389df14.zip.unzipped
▶ INFO Checking update for /Applications/Keybase.app
▶ INFO Current user uid: 501, gid: 20
▶ INFO Touching, chowning files in /var/folders/q6/_0v1bz590bxfrmsmldsm8h4m0000gn/T/KeybaseUpdates/Keybase-1.0.14-20160321130023+389df14.zip.unzipped/Keybase.app
▶ INFO Removing /Applications/Keybase.app
▶ INFO Moving (update) /var/folders/q6/_0v1bz590bxfrmsmldsm8h4m0000gn/T/KeybaseUpdates/Keybase-1.0.14-20160321130023+389df14.zip.unzipped/Keybase.app to /Applications/Keybase.app
```

I saw the popup when the client restarted and I clicked on the track button (it was all green and didn't show any revocations or anything like that).  I guess we'll have to see if the popup comes any more?

**Comment by cjb** [comment]
Thanks; we had an updater bug ten days ago that left you stranded from automatic updates, sorry about that!  It looks like the revoked proofs change wasn't in this build and will be in tomorrow's instead.  But I agree that you shouldn't see the popup anymore.

**Comment by grempe** [comment]
ok.  I'll keep on eye on it. Thanks for the prompt attention.

**Comment by grempe** [comment]
Not seeing this particular issue any longer.  Closing.
