### ISSUE TITLE
[Git] Add option to select default branch in UI

### ISSUE THREAD

**Issue by Surendrajat** [keybase/client#24182]
It's a pain to clone repos with no master branch. You clone it and then find out the branches and then checkout. Can it be more like you select the default branch for all projects?

**Comment by chindraba-work** [comment]
Have you tried the `--branch <branch_name>` option to `git clone` ? As in

    git clone --branch pzduniak/Y2K-2027/channel-member-actions-fix https://github.com/keybase/client.git

**Comment by Surendrajat** [comment]
@chindraba-work I can if I remember the branch names for all of my projects correctly but sadly I don't.

**Comment by chindraba-work** [comment]
Well, in the end, Keybase isn't involved in that anyway. The UI involved is what ever you are using. KB just does the magic on the backend to handle the encryption and storage. All the git details are part of the repo and the branch names such are out of KB client control.

I'm actually working on a Linux/Bash script for cloning a repo, including all it branches.

**Comment by Surendrajat** [comment]
Then I think showing the branches on the client-side is the least expected and quite possible behavior.

**Comment by chindraba-work** [comment]
Actually, `git clone` will checkout branch pointed to by the cloned repository’s `HEAD` automatically. Odds are that is the default branch.
