### ISSUE TITLE
keybase.io: expired cert in chain

### ISSUE THREAD

**Issue by anishathalye** [keybase/client#24205]
keybase.io's cert chain still includes the [recently expired Sectigo AddTrust External CA Root](https://support.sectigo.com/articles/Knowledge/Sectigo-AddTrust-External-CA-Root-Expiring-May-30-2020), which breaks certain clients (e.g. OpenSSL 1.0.x).

This can be easily checked using https://whatsmychaincert.com/.

**Comment by heronhaye** [comment]
Could you check again? We updated the chain. Thanks.

**Comment by anishathalye** [comment]
Works now, thanks!
