### ISSUE TITLE
Keybase for mac is still preventing sleep

### ISSUE THREAD

**Issue by fleish** [keybase/client#24207]
Opening a new issue in the hopes of better visibility and action. The behavior described in #12985 is still occurring. This behavior poses a serious security threat to those who rely on macOS to automatically lock an idle system to prevent unauthorized access.

I can reproduce this 100% of the time with /giphy ... I find when I'm searching for or just display a gif in a channel/chat activity monitor shows keybase preventing sleep. It stops showing preventing sleep if I do any of the following:

-    stop using /giphy to search for a giphy
-    switch to another channel/chat that isn't displaying a giphy
-    collapse the giphy in the channel/chat

I re-read the issue described in #12822 again and noticed the output of `pmset -g assertions` - which appears to line up with what processes Activity Monitor reports as `preventing sleep` and obtained the following output for the /giphy triggered issue:

```
   pid 82703(Keybase): [0x000a6e7d00058aef] 00:00:22 NoDisplaySleepAssertion named: "Video Wake Lock"
   pid 82703(Keybase): [0x000a6e7b00058aee] 00:00:24 NoDisplaySleepAssertion named: "Video Wake Lock"
   pid 82703(Keybase): [0x000a6e7a00058aed] 00:00:25 NoDisplaySleepAssertion named: "Video Wake Lock"
   pid 82703(Keybase): [0x000a6e7a00058aec] 00:00:25 NoDisplaySleepAssertion named: "Video Wake Lock"
   pid 82703(Keybase): [0x000a6e7a00058aeb] 00:00:25 NoDisplaySleepAssertion named: "Video Wake Lock"
   pid 82703(Keybase): [0x000a6e7a00058aea] 00:00:25 NoDisplaySleepAssertion named: "Video Wake Lock"
   pid 82703(Keybase): [0x000a6e7a00058ae9] 00:00:25 NoDisplaySleepAssertion named: "Video Wake Lock"
   ```

Hopefully @maxtaco or @mmaxim or someone working on the Keybase client can take notice of this serious issue and advise on a fix.

**Comment by fleish** [comment]
Trying again since this is a pretty big security issue: @maxtaco @joshblum @songgao @mmaxim

**Comment by djMax** [comment]
Still happening
