### ISSUE TITLE
keybase.io TLS certificate expired

### ISSUE THREAD

**Issue by kalbasit** [keybase/client#24215]
![2020-06-10_10-42](https://user-images.githubusercontent.com/87115/84300390-12fe5500-ab07-11ea-8bba-36e423a1395f.png)

:point_right: https://www.ssllabs.com/ssltest/analyze.html?d=keybase.io&s=52.20.96.149&latest
:point_right: https://www.ssllabs.com/ssltest/analyze.html?d=keybase.io

```
λ curl https://keybase.io/ylcodes/pgp_keys.asc
curl: (60) SSL certificate problem: certificate has expired
More details here: https://curl.haxx.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
```

This is blocking our entire developer productivity setup on our end. Is it possible to fix this soon?

**Comment by kalbasit** [comment]
This seems to have been reported 9 days ago in #24205. Are there any Keybase employees monitoring this repository?

**Comment by maxtaco** [comment]
Yes, this is a bug in cURL that's fixed in newer cURLs, isn't it? CC @heronhaye, Keybase employee. cURL has expired certs. Note how the major browsers are fine.

**Comment by chindraba-work** [comment]
Can't speak to it being a bug, or not, in curl, of any version. I can say "no repo" as I was successful on the first attempt to use the command supplied in the code box by @kalbasit. For the record: 

```
chindraba@Meska:~> uname -a;curl --version
Linux Meska 5.6.14-1-default #1 SMP Wed May 20 08:32:48 UTC 2020 (b0ab48a) x86_64 x86_64 x86_64 GNU/Linux
curl 7.70.0 (x86_64-suse-linux-gnu) libcurl/7.70.0 OpenSSL/1.1.1g-fips zlib/1.2.11 libidn2/2.3.0 libpsl/0.21.0 (+libidn2/2.3.0) libssh/0.9.3/openssl/zlib nghttp2/1.41.0
Release-Date: 2020-04-29
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS GSS-API HTTP2 HTTPS-proxy IDN IPv6 Kerberos Largefile libz Metalink NTLM NTLM_WB PSL SPNEGO SSL TLS-SRP UnixSockets
```

Of course, there is a few expired certs in the chains presented, but having one valid chain presented should suffice for any implementation seeking to download a resource. Same as I have several expired PGP keys, and a few revoked keys as well. Yet I present at least one valid (unexpired, unrevoked) key whenever I use any keys.

**Comment by miry** [comment]
I have the same issue from MacOS and Linux. All clients could not login or connect to api.

Just to check the SSL it requires 3 mins to wait for response:

```
% openssl s_client -connect api-0.core.keybaseapi.com:443 -msg
CONNECTED(00000006)
>>> ??? [length 0005]
    16 03 01 01 42
>>> TLS 1.3, Handshake [length 0142], ClientHello
    01 00 01 3e 03 03 c1 a6 a9 c4 73 fb b8 93 51 87
    b8 79 46 a1 62 f3 16 a2 76 5b 96 ad 79 04 46 49
    6f b1 45 99 ee 1c 20 ac 9a be c1 88 fa 56 4e 33
    d8 39 54 89 d2 ee c3 15 59 6f 05 b9 7a 25 9b 9d
    4f 19 6b 2b a2 85 fb 00 3e 13 02 13 03 13 01 c0
    2c c0 30 00 9f cc a9 cc a8 cc aa c0 2b c0 2f 00
    9e c0 24 c0 28 00 6b c0 23 c0 27 00 67 c0 0a c0
    14 00 39 c0 09 c0 13 00 33 00 9d 00 9c 00 3d 00
    3c 00 35 00 2f 00 ff 01 00 00 b7 00 00 00 1e 00
    1c 00 00 19 61 70 69 2d 30 2e 63 6f 72 65 2e 6b
    65 79 62 61 73 65 61 70 69 2e 63 6f 6d 00 0b 00
    04 03 00 01 02 00 0a 00 0c 00 0a 00 1d 00 17 00
    1e 00 19 00 18 00 23 00 00 00 16 00 00 00 17 00
    00 00 0d 00 30 00 2e 04 03 05 03 06 03 08 07 08
    08 08 09 08 0a 08 0b 08 04 08 05 08 06 04 01 05
    01 06 01 03 03 02 03 03 01 02 01 03 02 02 02 04
    02 05 02 06 02 00 2b 00 09 08 03 04 03 03 03 02
    03 01 00 2d 00 02 01 01 00 33 00 26 00 24 00 1d
    00 20 81 76 42 d2 9b ba 3d 7a 75 62 4e ad 37 ac
    1e 07 17 cf 0b 2b 07 a9 8e 7f 51 81 2a 56 25 94
    79 10
write:errno=0
---
no peer certificate available
---
No client certificate CA names sent
---
SSL handshake has read 0 bytes and written 327 bytes
Verification: OK
---
New, (NONE), Cipher is (NONE)
Secure Renegotiation IS NOT supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
Early data was not sent
Verify return code: 0 (ok)
---
```

**Comment by kalbasit** [comment]
Yea, this is broken on every Mac machine. I did try a newer version of cURL on Linux, and I can confirm that it works.

We could sit here and debate for days whether this is a something that Keybase or Apple should fix, but the truth is until it's fixed you're alienating all Mac users with this issue. You can't really expect them to install a newer version of cURL just so they can pull an asc. The best case scenario, they'll open it in the browser, the worst case scenario is that they just pass the -k flag to disable TLS which in my usecase completely negates the purpose of Keybase altogher.

IMHO, Keybase should switch their TLS certificate/provider AND forcibly redirect HTTP to HTTPS to address the cert issue and the security concern. Honestly I was surprised and disappointed when I found out that keybase.io replies on clear HTTP.

**Comment by maxtaco** [comment]
That's not true about clear HTTP, you shouldn't be able to talk to us over HTTP aside from getting redirected to HTTPS. Where do you see otherwise?

**Comment by byeskille** [comment]
This error is still present on macOS 10.15.5, and it seem to originate from a combination of one of the intermediary certs expiring, old openssl connected to curl on macOS and bad chain building. See: [https://security.stackexchange.com/questions/232445/https-connection-to-specific-sites-fail-with-curl-on-macos/232446#232446](https://security.stackexchange.com/questions/232445/https-connection-to-specific-sites-fail-with-curl-on-macos/232446#232446)

This solution suggested for macOS 10.15 worked for me:
> On macOS 10.15, where cURL uses OpenSSL 0.9.8 by default, the issue apparently may be mitigated by setting the environment variable CURL_SSL_BACKEND=secure-transport.

To use it just type this in the terminal and press enter before running the keybase curl command: `export CURL_SSL_BACKEND=secure-transport`

**Comment by smiba** [comment]
Keyhub.io actively provides this expired certificate because its in their hosted certificate bundle, so it gets sent from the server to client.

You can see this on the ssllab test: https://www.ssllabs.com/ssltest/analyze.html?d=keybase.io&s=35.169.49.45     
"Sent by server"

I don't understand why the certificate has not been updated, this has been an issue for weeks now

**Comment by heronhaye** [comment]
Could you check again? We updated the chain. Thanks.

**Comment by chindraba-work** [comment]
If I understand correctly, the receiver, browser, curl, or whatever, should check the "bundle" for a cert which it considers valid, based on it's own rules, and ignore any others found. One browser might not recognize the CA of AbbaDabra, while another might not accept the CA Symentec as valid. If there is a cert, otherwise valid, from each CA, should the browsers emit an error, or even a warning? 

No, each browser should accept the cert it considers valid and ignore those which it doesn't accept the chain for, certs with expired dates, or expired certs on the CA chain, or even certs which are not for the intended purpose (email, ssh, etc. vs https).

An error, or warning, should only happen in the event that there are no certs found in the bundle which are acceptable as "valid," for the purpose and the host, by the receiver.

**Comment by kalbasit** [comment]
@heronhaye I can confirm it's working on my Mac now! Thank you!
