### ISSUE TITLE
Typo - Pub share folder

### ISSUE THREAD

**Issue by tripmine253** [keybase/client#24231]
# Most likely a typo
[Public Folder](https://keybase.pub/) _{USERNAME}_

### Typo
Who is also **provably**:

Who is also **probably**:

**Comment by ccesare** [comment]
I'm pretty sure "provably" is correct. Those other accounts are proofs, a la [this](https://book.keybase.io/account#proofs): 

> Proofs link your Keybase account to your other online accounts. Proofs help people trust that you are really you on Keybase.

**Comment by tripmine253** [comment]
I feel silly for my mistake, as context of that word should have been obvious enough. Words are hard :) ty.
