### ISSUE TITLE
git server block does not exist

### ISSUE THREAD

**Issue by nhejazi** [keybase/client#24256]
I'm having an error that seems to have come up and been resolved in the past, e.g., https://github.com/keybase/keybase-issues/issues/3156 and https://github.com/keybase/client/issues/10816. It seems I'd started using the git service at some point when it was initially released then fell off from it -- getting back to it now, I'm seeing the "server block does not exist" issue that others have reported. 

Interestingly, I can actually browse git repos via the client, but I cannot clone or delete the repos, since I get
```bash
$ git clone keybase://private/nhejazi/[REPO]
Cloning into '[REPO]'...
Initializing Keybase... done.
Syncing with Keybase... done.
git-remote-keybase error: (1) Server: block does not exist
```
and
```bash
$ keybase git delete keybase://private/nhejazi/[REPO]
Deletion is permanent. Are you sure you want to delete "keybase://private/nhejazi/[REPO]"? (type 'YES' to confirm): YES
▶ WARNING Git repo doesn't exist. Deleting metadata anyway.
▶ ERROR can't find repo named "keybase://private/nhejazi/[REPO]"
```

Maybe relatedly, I also seems to run into issues with creating new repos from the client, where I get "ERROR CODE 2704 - RPC Error: BLOCK_NONEXISTENT in method keybase.1.git.createPersonalRepo". Not sure what the next steps would be, but I'd ideally like to completely remove any/all existing git repos and be able to generate new ones. I'm using the latest keybase client for Ubuntu/Debian, installed via https://keybase.io/docs/the_app/install_linux

**Comment by strib** [comment]
Hi, thanks for the report and sorry for the bad behavior.  You might have hit an old bug a long time ago that broke some data in there, sorry about that!

Can you browse other non-git data in your local `/keybase/private/nhejazi` folder?  There is a secret subfolder in there, called `.kbfs_git` (doesn't show up in `ls`, but you can `cd` into it).  You can poke around in there and see if you can isolate where the broken data is exactly.  As a test you might be able to rename `.kbfs_git` to something else, say `git_backup`, and then start creating new repos again.

**Comment by strib** [comment]
(But if you do the renaming thing, it might still show your old repos as phantoms in the client display.)

**Comment by nhejazi** [comment]
Thanks for the quick reply. Looking around `/keybase/private/nhejazi/.kbfs_git` was very helpful. It looks like metadata from all the repos were still stored there so I went ahead and deleted them all. After restarting the client, I noticed two interesting things:

1. The repos were still displayed in the client (even though their respective subdirectories in `/keybase/private/nhejazi/.kbfs_git` had been deleted), but clicking through the delete repo interface in the client now allowed them to be removed without the error originally reported.
2. Trying to create a new personal repository from the client results in the same error as before ("ERROR CODE 2704 - RPC Error: BLOCK_NONEXISTENT in method keybase.1.git.createPersonalRepo"), but the corresponding subdirectory does get created in `/keybase/private/nhejazi/.kbfs_git`. After a restart, the client then displays this repo, but operations with it still fail with `git-remote-keybase error: (1) worktree should be provided`, which appears similar to https://github.com/keybase/keybase-issues/issues/3156

**Comment by strib** [comment]
Does creating, reading and writing files outside of `.kbfs_git` work? Like in the first level of your private folder?

If there a `.kbfs_git/.kbfs_deleted_repos` directory?  If so, look around in there a bit and see if there are any errors.  If so, it might work to rename that directory to something else.

**Comment by nhejazi** [comment]
Hmm, that's interesting -- so, in `/keybase/private`, I get
```
(base) nsh on delphi in /keybase/private
$ mkdir test2
mkdir: cannot create directory ‘test2’: No such file or directory
```
while in `/keybase/private/nhejazi` things work fine
```
(base) nsh on delphi in /keybase/private/nhejazi
$ mkdir test2
```

In both cases, the client also sends messages that I don't have read access to that directory. I'm not sure I understand how permissions are supposed to be set up throughout `/keybase/*`.

Looking around `.kbfs_git/.kbfs_deleted_repos`, there's a single repo preserved in there with the contents of it appearing like the contents of a standard `.git` directory (mostly, other than `kbfs_config` and `._kbfs_config`). Would it work to delete this repo, or just the whole `.kbfs_git/.kbfs_deleted_repos` directory?

**Comment by strib** [comment]
`/keybase/private` is read-only, you are only supposed to be able to make subdirectories inside folders where you have permission (like your private named folder).

I wouldn't delete anything just in case there's something important in there we need to rescue laet.  Just rename it, like `mv .kbfs_deleted_repos old_deleted_repos` or something like that.

**Comment by nhejazi** [comment]
After renaming `.kbfs_deleted_repos` things seem to be working. Thanks for the quick help with this.
