### ISSUE TITLE
Can’t login!

### ISSUE THREAD

**Issue by lolifamily** [keybase/client#24276]
@zanderz

**Comment by lolifamily** [comment]
![846139F2-0ED1-4DB2-83FF-391979FDA9CF](https://user-images.githubusercontent.com/47876607/88456453-7b837480-ceb0-11ea-8f7d-b7219496d5e3.png)

**Comment by lolifamily** [comment]
@strib @patrickxb @maxtaco @chrisnojima @cjb @mmaxim @jzila @gabriel @mlsteele @buoyad @songgao @joshblum @MarcoPolo @oconnor663 @akalin-keybase @chromakode @zapu @taruti @zanderz @adamjspooner

**Comment by lolifamily** [comment]
@heronhaye

**Comment by chrisnojima** [comment]
please do not spam people
