### ISSUE TITLE
Can't delete bot messages

### ISSUE THREAD

**Issue by inpharmaticist** [keybase/client#24295]
I was testing out a bot in a chat with myself and now the messages are stuck there and they are kind of annoying. Any solution?

**Comment by haukened** [comment]
Since it's not a team, there's no "ownership" in a 1:1 chat, and therefore no delete. This is essentially the same as any other chat with a person, you can't delete their messages either.

**Comment by inpharmaticist** [comment]
Darn.

**Comment by kf5grd** [comment]
@inpharmaticist if the bot in question was the rssbot, you can react to any of the bot's messages with :x: and the bot will delete that message for you. I don't know if any of the other bots have a feature like this.

**Comment by inpharmaticist** [comment]
That's a great idea. Doesn't look like it works for bottender though.

**Comment by inpharmaticist** [comment]
I learned that if you go to settings you can clear the entire conversation. That did the trick.
