### ISSUE TITLE
my web (AirdropsBMW.tk) proof has failed

### ISSUE THREAD

**Issue by linnbenton** [keybase/client#24307]
Hi, Keybase Team, my attempted web identity proof of https://AirdropsBMW.tk never succeeded. We've been checking it repeatedly, and from our perspective, it's either (a) not there, or (b) not posted precisely.

I think there's a bug or there is something missing to verify it. The link to my proof https://airdropsbmw.tk/keybase.txt

And here is my profile, in case you'd like to try again: https://keybase.io/xlmfaucet.

Thanks! -Keybase

**Comment by zfogg** [comment]
@linnbenton your link 404s

**Comment by linnbenton** [comment]
@zfogg I just remember that in order to make the URL as it is, I should add a new page in my web, but I did not do it, finally 404.

Now it has been verified by a keybase team by using DNS. thanks! 😎

**Comment by zfogg** [comment]
haha awesome ok. you should resolve this issue maybe :)

**Comment by linnbenton** [comment]
OK, Close this issue
