### ISSUE TITLE
Havent updated in a while, now it gets stuck on loading screen.

### ISSUE THREAD

**Issue by Brandonme** [keybase/client#24332]
Keybase GUI Version: 5.2.
0-20200130015427+cf82db8320
![image](https://user-images.githubusercontent.com/59538619/95026551-b963fc80-069a-11eb-8005-61321e608d95.png)

**Comment by noizo** [comment]
same here on Catalina 10.15.7 and latest keybase both from website or brew.
![Screenshot 2020-10-09 at 11 06 05](https://user-images.githubusercontent.com/1682474/95564681-6fbf3d00-0a1f-11eb-91d4-e51da96a96ea.png)
```
┗❯ keybase log send
This command will send recent keybase log entries to keybase.io
for debugging purposes only.

These logs don’t include your private keys, encrypted data or file names,
but they will include metadata Keybase normally can't read
(like file sizes and git repo names), for debugging purposes.

Continue sending logs to keybase.io? (type 'YES' to confirm): yes
Enter feedback (or <Enter> to send):

▶ ERROR API network error: Post https://api-0.core.keybaseapi.com/_/api/1.0/logdump/send.json: proxyconnect tcp: dial tcp 195.20.53.34:1080: i/o timeout
```

**Comment by umop-apisdn-wl** [comment]
im having the same issue

**Comment by joshblum** [comment]
can one of you try `keybase log send -n 10000` and send post the log idea here? `-n` limits the number of bytes to send so hopefully it will not time out

**Comment by Brandonme** [comment]
> can one of you try `keybase log send -n 10000` and send post the log idea here? `-n` limits the number of bytes to send so hopefully it will not time out
Noob here, how to do that?

**Comment by joshblum** [comment]
First open your terminal program: https://towardsdatascience.com/a-quick-guide-to-using-command-line-terminal-96815b97b955 

Then enter `keybase log send -n 10000` and copy the output here

**Comment by Brandonme** [comment]
C:\Users\-----\AppData\Local\Keybase\Gui>
 Version: 5.2.0-20200130015427+cf82db8320
(electron) 'setAutoHideMenuBar function' is deprecated and will be removed. Please use 'autoHideMenuBar property' instead.
requestStartService: starting keybase.exe
Not connected - starting keybase
Uncaught exception on main thread: Error: spawn C:\Users\-----\AppData\Local\Keybase\keybaserq.exe ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:264:19)
    at onErrorNT (internal/child_process.js:456:16)
    at processTicksAndRejections (internal/process/task_queues.js:77:11) {
  errno: 'ENOENT',
  code: 'ENOENT',
  syscall: 'spawn C:\\Users\\-----\\AppData\\Local\\Keybase\\keybaserq.exe',
  path: 'C:\\Users\\-----\\AppData\\Local\\Keybase\\keybaserq.exe',
  spawnargs: [
    'C:\\Users\\-----\\AppData\\Local\\Keybase\\keybase.exe',
    '--log-format=file',
    '--log-prefix=C:\\Users\\-----\\AppData\\Local\\Keybase\\watchdog.',
    'ctl',
    'watchdog2'
  ]
}

**lmk if I did it correctly.**

**Comment by Brandonme** [comment]
can I run a command and update from terminal, so it doesn't get stuck on loading screen?

**Comment by umop-apisdn-wl** [comment]
Macbooks-MacBook-Pro-2:~ macbookpro$ keybase log send -n 10000
-bash: keybase: command not found
Macbooks-MacBook-Pro-2:~ macbookpro$

**Comment by joshblum** [comment]
@Brandonme you can try `keybase update check`

**Comment by Brandonme** [comment]
@joshblum C:\Users\User1\AppData\Local\Keybase\Gui>
 Version: 5.2.0-20200130015427+cf82db8320
(electron) 'setAutoHideMenuBar function' is deprecated and will be removed. Please use 'autoHideMenuBar property' instead.
requestStartService: starting keybase.exe
Not connected - starting keybase
Uncaught exception on main thread: Error: spawn C:\Users\User1\AppData\Local\Keybase\keybaserq.exe ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:264:19)
    at onErrorNT (internal/child_process.js:456:16)
    at processTicksAndRejections (internal/process/task_queues.js:77:11) {
  errno: 'ENOENT',
  code: 'ENOENT',
  syscall: 'spawn C:\\Users\\User1\\AppData\\Local\\Keybase\\keybaserq.exe',
  path: 'C:\\Users\\User1\\AppData\\Local\\Keybase\\keybaserq.exe',
  spawnargs: [
    'C:\\Users\\User1\\AppData\\Local\\Keybase\\keybase.exe',
    '--log-format=file',
    '--log-prefix=C:\\Users\\User1\\AppData\\Local\\Keybase\\watchdog.',
    'ctl',
    'watchdog2'
  ]
}

**Comment by Brandonme** [comment]
perhaps I should just copy the files, like secret key file and some others and reinstall keybase from clean slate? I just dont know which files i should keep besides the secret keys

**Comment by Brandonme** [comment]
when I try to run the `keybase update check`
Only one instance of keybase GUI allowed, bailing!
So the situation is the same `stuck` on loading screen

**Comment by Brandonme** [comment]
![ttt](https://user-images.githubusercontent.com/59538619/101110915-bcb82d80-35e2-11eb-945c-18c050f06f4d.png)
