### ISSUE TITLE
Unable to login using paper key

### ISSUE THREAD

**Issue by vivianspencer** [keybase/client#24367]
I'm trying to setup keybase on my device again, I have a previous account **vivianspencer**, but I do not have access to the devices on the account, I only have a paper key for one of the devices on the account.

Ideally I do not want to reset the account, instead I'd like to add my new device using my old paper key to authenticate its provision. 

I've tried logging in via terminal using the following command:

`keybase login --paperkey="MY PAPER KEY" --devicename="NEW DEVICE NAME" vivianspencer`

However this results in the error **ERROR No paper keys available**

I've checked through the logs, and it looks like the paper key I'm using is valid and is successfully authenticating me, but it's throwing an error (loginProvision#chooseDevice -> No paper keys available *error) which I believe is the following block of code:
https://github.com/keybase/client/blob/c494e46bf75b29a8ee5c78fcd0aaec78cd73a6a2/go/engine/login_provision.go#L718-L731

Any help would be much appreciated, my log id: d89967f4e4f2dbd5557d3e1c

**Comment by kf5grd** [comment]
You don't actually have any paper keys. Paper keys are separate devices on an account and they show on the devices page. You can see on your devices page that you only have computers: https://keybase.io/vivianspencer/devices

**Comment by chindraba-work** [comment]
There were some paper keys, "erosion drop" and "warrior dutch", both revoked 2016-07-22. The PGP key, 1601 D973 5833 F04E D7C8  524D FB48 FD9F 3BFF 2DDD, is still valid. I don't know if it's possible to "authenticate" with that or not, provided you still have the secret key for it. If not, the account is inaccessible, as far as I know.

**Comment by kf5grd** [comment]
>I don't know if it's possible to "authenticate" with that

It's not possible. You can only use computers, phones, and paper keys to provision new devices.

**Comment by vivianspencer** [comment]
Ok thanks for the help, I didn't realise the keys appeared as separate devices and I can see they were revoked now, not sure why :(

**Comment by MattiJarvinen** [comment]
@vivianspencer just out of curiosity... How did you get fresh keybase account with the same user?

https://keybase.io/vivianspencer/sigchain#95b9d71c48918094513ba3e95cf0b1c9c2cca868daa671ba5f9ca6ccea6181f20f
