### ISSUE TITLE
I am the bug?

### ISSUE THREAD

**Issue by J-Vin** [keybase/client#24373]
"Hi, jacqvinson, your attempted github identity proof of @J-Vin never succeeded. We've been checking it repeatedly, and from our perspective, it's either (a) not there, or (b) not posted precisely.

If you think there's a bug, please post an issue on github. Include the link to your proof.

And here is your profile, in case you'd like to try again: https://keybase.io/jacqvinson.
You may also prove yourself with the keybase command line app.

Thanks!"

**Comment by kf5grd** [comment]
When you create a github proof on keybase you will be given some text to copy and paste into a puplic gist on your github account. You don't have any public gists: https://gist.github.com/J-Vin

If you made it private by accident then you may need to set it to private. If you didn't make the gist at all, you should re-do the proof in keybase and make a gist with the text provided, and make sure it's public
