### ISSUE TITLE
Can't invite to team — error 218, no such file, in teamAddMembersMultiRole

### ISSUE THREAD

**Issue by rptb1** [keybase/client#24374]
I attempted to add a person to my team in the mac OS app (version 5.5.0-20200526170801,139bb348af) by navigating to the team, clicking "Add/Invite people", then "From Keybase", then "A Keybase user", then choosing a person, clicking "Add", clicking "Writer" and changing the role to "Reader", clicking Save, then "Invite 1 person & finish".

I got a red error message: ERROR CODE 218 - Error adding "[redacted]": open /Users/[redacted]/Library/Application Support/Keybase/keybase.leveldb/052594.sst: no such file or directory in method keybase.1.teams.teamAddMembersMultiRole

The directory mentioned in the message contains *no* files with the .sst extension, and no files with the basename 052594.

The command line `keybase team add-member` fails with the same error message:
```
$ keybase team add-member [redacted] --user=[redacted] --role=reader
▶ ERROR open /Users/[redacted]/Library/Application Support/Keybase/keybase.leveldb/052594.sst: no such file or directory
```

I was able to add the person using Keybase 5.5.0 on Android, so I don't need immediate support.

my log id: d0031fe62b7247d07449a01c

**Comment by rptb1** [comment]
I'm getting similar errors from the command line:
```
$ keybase sigs list
▶ ERROR open /Users/[redacted]/Library/Application Support/Keybase/keybase.leveldb/052592.sst: no such file or directory
```

**Comment by keybase-travis** [comment]
Delete that level db

**Comment by rptb1** [comment]
> Delete that level db

I quit Keybase, then did `mv keybase.leveldb keybase.leveldb-` then restarted, and that seems to have fixed `keybase sigs list` and some other GUI weirdness.

I believe this is related to a power cut that I have since discovered has caused some APFS disk corruption.  I'm getting errors like this from numerous files that were probably touched just before the power cut.

```
$ tar cf /dev/null .
tar: ./keybase.leveldb-/052592.ldb: Cannot stat: No such file or directory
tar: ./keybase.leveldb-/052586.ldb: Cannot stat: No such file or directory
tar: ./keybase.leveldb-/052579.ldb: Cannot stat: No such file or directory
tar: ./keybase.leveldb-/052578.ldb: Cannot stat: No such file or directory
...
tar: Error exit delayed from previous errors.
```

So this is almost certianly not a bug in Keybase.  I'll close this issue.  Thanks for the help.
