### ISSUE TITLE
Can't login on android or windows devices

### ISSUE THREAD

**Issue by ijoosong** [keybase/client#24377]
Hi, i keep getting this error when trying to log in with my accounts on anything that's not the website:

First live link has to be eldest (got sibkey)
Error code 1014: SIG_NO_ELDEST in method keybase.1.login.login

my log id: 7a5cac62b6b97635c4a0471c

**Comment by ijoosong** [comment]
I see now from https://github.com/keybase/client/issues/15518 that this is an issue with old accounts. I wouldn't mind resetting my account but I remember that if I had my account for this time, i would have a certain number of lumens in there! any way i can keep those or figure out my wallet info?

**Comment by ijoosong** [comment]
Ping

**Comment by Rudi9719** [comment]
Mentioning the lumens might be why you didn't get traction, as keybase focuses on privacy and such and the Lumens were a part of the Stellar Foundation. Also, if your account is old enough where you have no eldest key to sign in with, chances are you did not meet the device requirements to claim the free XLM in the first place, what is your account name and I can check your balance? The process to reset your account is outlined here: https://github.com/keybase/keybase-issues/issues/3632#issuecomment-551040885

**Comment by ijoosong** [comment]
@Rudi9719 hey, my account name is "song" 
Thats potentially true regarding the lumens.  Thanks!

**Comment by Rudi9719** [comment]
@ijoosong you have no wallet, and therefore no lumens. Please close this issue at your convenience :)

**Comment by ijoosong** [comment]
Ah sad okay will just go ahead and restart then :) thanks!
