### ISSUE TITLE
canvas quits rendering, app turns white.

### ISSUE THREAD

**Issue by silence48** [keybase/client#24402]
Keybase GUI Version: 5.5.0-20200526131901+139bb348af

The issue is same as the title.  The app quits working randomly with the entire window turning white.  I have to kill it and restart it. have reinstalled. nothing is fixing it. on windows 10

**Comment by tmanlsd** [comment]
Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by silence48** [comment]
how would that help? I don't have an iphone!

**Comment by silence48** [comment]
This is resolved in newer versions; no idea the cause. closing the issue.
