### ISSUE TITLE
New iOS release 5.6.0 in app store, but not in github

### ISSUE THREAD

**Issue by fleish** [keybase/client#24428]
Does anyone know what is up with this? I just saw a new release version 5.6.0 pop up on the [iOS app store](https://i.ibb.co/DtMCX1w/Screen-Shot-2021-01-21-at-6-08-57-PM.png) but there is no such release listed [here on github](https://i.ibb.co/wcycMy7/Screen-Shot-2021-01-21-at-6-10-43-PM.png)

Tagging some well known contributors in the hopes of an answer @maxtaco @joshblum @songgao @mmaxim 

EDIT to upload linked screenshots:
<img width="1007" alt="Screen Shot 2021-01-21 at 6 08 57 PM" src="https://user-images.githubusercontent.com/2106430/105424004-7f504380-5c14-11eb-8cc5-a48733658ee9.png">

<img width="1364" alt="Screen Shot 2021-01-21 at 6 10 43 PM" src="https://user-images.githubusercontent.com/2106430/105424006-7fe8da00-5c14-11eb-9bb5-53a9e8b7429f.png">

**Comment by magneticflux-** [comment]
It seems like the current `master` branch builds version 5.6.0 (at least, the Android app does). Perhaps they just forgot to add a new release on GitHub?

**Comment by Tomalak** [comment]
The hand-wavy "various fixes" without any release log or a GitHub release seems more than a bit fishy after almost a year of no movement in the client and the sell-out to Zoom.

**Comment by tazmon95** [comment]
I'm on windows desktop and just had a popup to automatically update to 5.6.0 show up.  What are the changes included in "various fixes"?

**Comment by mathieujobin** [comment]
this is weird indeed

**Comment by mathieujobin** [comment]
That would be on Mike's fork https://github.com/keybase/client/tree/mike/560-release

There is an open pull request for 5.6.1
that's how I found it

**Comment by Tomalak** [comment]
This is not exactly solved, why close it? As far as I am aware, there's been no comment from anyone what's going on here.

**Comment by fleish** [comment]
@Tomalak I marked it solved b/c it is now showing up in the [releases](https://github.com/keybase/client/releases/) for this repo. I wouldn't expect any additional comments on this since they've been almost entirely radio silent since the Zoom purchase.

**Comment by mathieujobin** [comment]
code can be found on github this issue can be closed
