### ISSUE TITLE
Dialogs instead of notifications on Ubuntu 16.04

### ISSUE THREAD

**Issue by jcassee** [keybase/client#2443]
Notifications from Keybase show as dialogs instead of notifications on Ubuntu 16.04:

![electron_002](https://cloud.githubusercontent.com/assets/20749/14021326/4f5394e6-f1db-11e5-9cb5-851a7ba636c4.png)

Seems to be due to [a bug in Electron](https://github.com/atom/electron/issues/465) (or a bug in Ubuntu, depending how you look at it). A workaround is also discussed in [this Brightray issue](https://github.com/atom/brightray/pull/197).

**Comment by jcassee** [comment]
An [Ubuntu bug report on Launchpad](https://bugs.launchpad.net/ubuntu/+source/unity/+bug/1547448) suggested adding this to `~/.xinitrc`:

```
export ELECTRON_USE_UBUNTU_NOTIFIER=1
```

I had to add the line to `~/.profile`, but after that Keybase has been showing nice Unity notifications.

**Comment by jcassee** [comment]
@cjb Shall we close this issue or leave it open?

**Comment by cjb** [comment]
Let's leave it open until the workaround is unnecessary.

**Comment by 3v1n0** [comment]
This has been just fixed: https://github.com/electron/electron/issues/465

**Comment by cjb** [comment]
Cool, thanks, I'll close this out.
