### ISSUE TITLE
the keybase .onion site is down for a while now, I can't login from keybase-client CLI tool.

### ISSUE THREAD

**Issue by gwynne0190** [keybase/client#24477]
this is the first time logging into the computer, so I don't know for how long the site is down for.

I tried going to the website through tor, seems like the .onion site is down. I used the ```--tor-mode=leaky service``` flag, I think it has nothing to do with this because keybase defaults to the tor site anyway.

the output of ```$ keybase login``` after inputting username;

▶ ERROR API network error: doRetry failed, attempts: 3, timeout 13.5s, last err: Get "http://keybase5wmilwokqirssclfnsqrjdsi7jdir5wy7y7iu3tanwmtp6oid.onion/_/api/1.0/user/lookup.json?fields=basics%2Cpublic_keys%2Cpictures&load_deleted_v2=1&multi=1&username=myusername": socks connect tcp 127.0.0.1:9050->keybase5wmilwokqirssclfnsqrjdsi7jdir5wy7y7iu3tanwmtp6oid.onion:80: unknown error connection refused (code 1601)

**Comment by heronhaye** [comment]
Sorry about that, can you try again? Should be up now.

**Comment by dmp1ce** [comment]
Tor onion may be down again? I'm getting:

```
$ keybase login
▶ ERROR unexpected error in Login: API network error: Get http://keybase5wmilwokqirssclfnsqrjdsi7jdir5wy7y7iu3tanwmtp6oid.onion/_/api/1.0/merkle/root.json?c=1&last=22975350&skip_last=1: socks connect tcp 127.0.0.1:9050->keybase5wmilwokqirssclfnsqrjdsi7jdir5wy7y7iu3tanwmtp6oid.onion:80: unknown error host unreachable
```

**Comment by heronhaye** [comment]
Should be back up. Sorry.
