### ISSUE TITLE
Windows 10 - Keybase installer will start but after a while it disappears

### ISSUE THREAD

**Issue by blckmnt** [keybase/client#24569]
I have this weird problem on my win 10 machine, that when i launch the .msi installer it starts and when it reaches the: "Please wait while Windows configures Keybase" the installer window disappears in the middle of the loading. But Keybase program appears in "Programs and Features" in the control panel.

Please help!

**Comment by blckmnt** [comment]
Newermind it got installed on my system but i have to locate the .exe file myself to launch it.
The location of .exe file is in %LOCALAPPDATA%\Keybase\Gui\Keybase.exe

**Comment by goeb36** [comment]
Mgfd36.001

**Comment by goeb36** [comment]
%LOCALAPPDATA%\Keybase\Gui\Keybase.exe

**Comment by goeb36** [comment]
@goeb36
