### ISSUE TITLE
Cannot access /keybase: No such file or directory

### ISSUE THREAD

**Issue by anthony-y** [keybase/client#2458]
Just installed Keybase on my Ubuntu 15.10 laptop. 

Everything is working perfectly apart from the Keybase file system stuff.

I saw some people were having problems with the public and private directories but I don't have a Keybase folder at all O_o

I'm on the 64 bit debian package by the way.

**Comment by cjb** [comment]
Please run `keybase log send`, thanks.

**Comment by anthony-y** [comment]
Done!

My log id is 79019f527886ab89fe60961c, if that's necessary.

**Comment by cjb** [comment]
Ah, it looks like you don't have KBFS installed. KBFS is still in an invite-only beta, so just downloading keybase from our main site doesn't include it. Sorry for the hassle!

**Comment by anthony-y** [comment]
Oh! No worries lol

Is the beta randomly selected or can I sign up somewhere? I'd love to try it out :D

**Comment by anthony-y** [comment]
Edit: I just read through https://keybase.io/docs/kbfs properly and saw the "Getting access" part. I guess I just scanned through before.

Oops :P
