### ISSUE TITLE
Extreme Power Usage

### ISSUE THREAD

**Issue by davidmcooper** [keybase/client#2459]
Realize performance hasn't been a focus, but wanted to report significant power usage - above all other applications running on my machine.

my log id: 875b2e0240b0022fdf1fa21c

**Comment by cjb** [comment]
@davidmcooper Hi!  This is fixed, but the updater broke, leaving you on an old version.  Sorry about that!  You can run `keybase update run` to get the power fix and get back on the upgrade path.
