### ISSUE TITLE
kbfs Finder integration not working on macOS Monterey

### ISSUE THREAD

**Issue by rex4539** [keybase/client#24636]
Nothing happens when trying to enable it.

**Comment by zvictor** [comment]
Duplicates:

* #24578
*  #24668

**Comment by marcofranssen** [comment]
👍  same issue here

**Comment by evaldofelipe** [comment]
Same on new M1 pro with Monterey.

**Comment by lamebear** [comment]
Is there an ETA on this?

**Comment by maxtaco** [comment]
Thanks everyone. MacOS broke FUSE, as usual, with the Monterey upgrade. We're aware and working slowly through a bunch of upgrades (Go, React Native, FUSE, etc). We'll post an ETA when we know it. Thanks for your patience.

**Comment by marcofranssen** [comment]
@maxtaco showing my appreciation with some emoji. Thanks a lot for looking into this. If there is anything to test let me know, happy to help out.

**Comment by marcofranssen** [comment]
Today I received an update via Homebrew.

```bash
Version 5.9.0-20211216221146+9b33c9201f (5.9.0-20211216221146+9b33c9201f)
```

When trying to enable the finder integration from the settings it spins for a while and then finally finishes without actually enabling the feature.

![image](https://user-images.githubusercontent.com/694733/146924351-72ca7818-34af-48f7-870f-aba9098351b3.png)

Is there anything I can do to provide you with additional information? @maxtaco

**Comment by da-svats** [comment]
Any news on that?

**Comment by shikhir-arora** [comment]
I assume the fix is to update kbfuse and use the released https://github.com/osxfuse/osxfuse/releases/tag/macfuse-4.2.4 specifically targeting macOS Monterey.

**Comment by da-svats** [comment]
@shikhir-arora how to use that version, I've downloaded 4.2.4 macfuse, but ` keybase fuse status ` says me
```
{
  "version": "4.0.5",
  "bundleVersion": "",
  "kextID": "com.github.kbfuse.filesystems.kbfuse",
  "path": "/Library/Filesystems/kbfuse.fs",
  "kextStarted": false,
  "installStatus": 4,
  "installAction": 0,
  "mountInfos": [],
  "status": {
    "code": 0,
    "name": "OK",
    "desc": "OK",
    "fields": null
  }
}
```
How to target properly the right version of the kbfuse?

**Comment by shikhir-arora** [comment]
> @shikhir-arora how to use that version, I've downloaded 4.2.4 macfuse, but `keybase fuse status` says me
> 
> ```
> {
>   "version": "4.0.5",
>   "bundleVersion": "",
>   "kextID": "com.github.kbfuse.filesystems.kbfuse",
>   "path": "/Library/Filesystems/kbfuse.fs",
>   "kextStarted": false,
>   "installStatus": 4,
>   "installAction": 0,
>   "mountInfos": [],
>   "status": {
>     "code": 0,
>     "name": "OK",
>     "desc": "OK",
>     "fields": null
>   }
> }
> ```
> 
> How to target properly the right version of the kbfuse?

Keybase distributes their own signed versions of Fuse (for reasons described in the link below) - so installing it alone won't do anything.

The process is *fairly* straightforward and the `build.sh` compilation step described here: https://github.com/keybase/client/tree/master/osx/Fuse shows how one can target the newest version of macFUSE (and it will pull from the newest release, i.e. `VERSION=4.2.4 ./build.sh` - and then one has to modify the `build.sh` script to symlink and add macOS 12 in there, but this should result in a new `kbfuse.bundle` and `fsbundle.tgz` - it's a pretty clear-cut process but they need to be signed as the README indicates. 

Once that's done those bundles get packaged in a new `KeybaseInstaller.app` which needs to be compiled with the new bundles generated by the build step. That installer should then work fine - note that the newest version of macFUSE is the first to be built specifically with the macOS 12.1 SDK (vs 11).

I'll see if I have time to try this locally today (if I can get some free time from the family 😆 ). Any project maintainer should be able to do it much quicker as they already (presumably) have access to codesign using the Keybase dev key from Apple (which is part of the build process).

**Comment by jdoupe** [comment]
Problem being that macfuse source is not publicly available, which makes it pretty impossible for the average joe to compile this for themselves.  It seems that Keybase development has all but been destroyed by the acquisition by Zoom.  :(

**Comment by gtrabanco** [comment]
> 

It is sad because Keybase was such a good project.

**Comment by rnhurt** [comment]
I truly thought that Keybase would make it.  I've been trying to get people to use PGP | GPG for years and it's always been an uphill battle.  And these are smart "tech" people that are having issues!  When Keybase came along I thought I could finally get my non-tech people and family to use encryption.  It really was a game changer.

Then they started doing crypto stuff, which I thought was weird, but whatever.  Then they got bought by Zoom and I had a massive sinking feeling in my stomach.  I was hoping beyond hope that Keybase would somehow be OK.  I guess those hopes are now dashed.  :cry: 

What other options do we have?  Is any of this code usable by another project?

**Comment by jwisser** [comment]
It really is frustrating. I would happily pay for Keybase if that would keep the service active and the clients up-to-date, but somehow it doesn't seem like that's on the cards.

**Comment by 0x7d7b** [comment]
So, is there an other possibility using keybase on MacOS backing up all files stored on keybase? I see no option in the client app to download complete folders. Just single files. That would be very teadious...

**Comment by marcofranssen** [comment]
@0x7d7b `keybase fs --help` and write a bash script.

**Comment by terminalfool** [comment]
It's only the finder integration that's broken, so keybase is still fundamentally usable. It might be possible to fix it as shikhir-arora mentioned above, but requests to join keybase://team/keybase.keymasters go unanswered.

**Comment by hslavchev** [comment]
> It's only the finder integration that's broken, so keybase is still fundamentally usable.

Unless you use Keybase primarily with the FUSE integration for access from CLI and automation.

**Comment by sinewalker** [comment]
e.g. `keybase fs cp -rf /keybase/private/sinewalker/key key` to retrieve my private keys (overwriting local copy with the keybase version), and get back to work while this issue continues. They won't be _encrypted_ locally (except by FileVault), but at least I'll have them.

**Comment by drreen** [comment]
Looking forward to a fix here :)

**Comment by saschabraband** [comment]
> It's only the finder integration that's broken, so keybase is still fundamentally usable. It might be possible to fix it as shikhir-arora mentioned above, but there are too many caveats. Nevertheless, keybase fs still works.


I'd add to this that several Stellar updates have not yet been added to the wallet and keybase is giving errors on payments although the network accepted those.

**Comment by marcofranssen** [comment]
@saschabraband probably it would be good to create a new issue for the stellar parts to track those broken things.

**Comment by saschabraband** [comment]
> @saschabraband probably it would be good to create a new issue for the stellar parts to track those broken things.

True. I'm currently testing things and will create an issue if completed.

**Comment by dlion** [comment]
Same issue here, do we have an update on this problem?

**Comment by a-nldisr** [comment]
Made a little script this weekend to copy the files in your teams to your local machine. 
https://gist.github.com/a-nldisr/176f5da07187f827b6734edf2b62ca7a

There are some errors all over the place when you use the `keybase fs cp` command.

**Comment by terminalfool** [comment]
> There are some errors all over the place when you use the keybase fs cp command.
I've found that if you want a reliable copy, it's best to sync the files first (keybase fs sync enable /keybase/team/...).
This doubles the disk space involved, however.

**Comment by FrancYescO** [comment]
Same here, log id `7de9073d8f7ac5a8d5e24d1c`

**Comment by feded** [comment]
Any news?

**Comment by sinewalker** [comment]
Another workaround (might be preferable to using `keybase fs cp` if you don't want to keep sensitive files unencrypted on your mac):  Install a Linux virtual machine on your macOS host, and then install keybase into there.

Follow the instructions at https://keybase.io/docs/the_app/install_linux to install keybase, and then do `keybase login` to register the virtual machine, selecting your mac as the device to use for provisioning, and follow the instructions.

If you use Vagrant you can then access the keybase fs via fuse on the VM, as well as the host filesystem.

* `/keybase/private/you/secrets`
* `/vagrant` #maps to wherever you `Vagrantfile` lives

Similarly with Docker for Desktop, which may be faster/easier than Vagrant+VirtualBox.

**Comment by foss-** [comment]
Has anybody tested keybase 5.9.2 on macOS 12 Monterey? Seems kbfuse has been updated as per https://github.com/keybase/client/pull/24812 and 5.9.2 branching is here https://github.com/keybase/client/commit/a25f15e42bbf1c1d3393b337afc4f699a9c64d5d.

**Comment by rex4539** [comment]
Fixed with 5.9.2

**Comment by dooglio** [comment]
This is not fixed at all in 5.9.2 on Mac OS/X Catalina. I try to enable Keybase in Finder, it spins for a while and silently fails, as mentioned in above posts. Any suggestions on how to get this to work? Installing `macfuse` in brew also does not work.

**Comment by treeshateorcs** [comment]
works fine on monterey

**Comment by rnhurt** [comment]
I'm sorry, but it does not work "fine" on Monterey.  The Keybase team has chosen to use a kext (Kernel Extension) to implement this functionality.  kexts are [no longer supported on macOS](https://support.apple.com/guide/security/kernel-extensions-sec8e454101b/web) and require you to reconfigure secure boot to reduce security.  

There is no reason that this functionality requires a kext in a modern environment.  There are plenty of other tools that provide similar services that don't require this sort of invasive, outdated process.  Apple has provided the tools to build this properly and securely.  A kext in 2022 is not an acceptable solution.

**Comment by treeshateorcs** [comment]
> require you to reconfigure secure boot

that was the case before this issue

**Comment by easye** [comment]
> This is not fixed at all in 5.9.2 on Mac OS/X Catalina.

I can confirm that Keybase 5.9.2 broke Finder integration for me in macOS Catalina as well, where it was working just fine before the upgrade.  A separate issue should be opened for the breakage in 5.9.2.

**Comment by jernestosuarez** [comment]
I can confirm Keybase 5.92 broke Finder integration for the old Mojave as well.

**Comment by domq** [comment]
> works fine on monterey

Can confirm, I opened the System Preferences and something from Keybase, Inc wanted my permission to upgrade. It all went smoothly from there. Kudos to the team!

**Comment by HMCIV** [comment]
I was also able to get to my Keybase files using macOS Monterey after receiving the update. Many thanks for the fix! However, I'm still not able to connect GitHub Desktop to the Keybase gits which I created. Any guesses how I can remedy this error message:

 `'remote-keybase' is not a git command`

<img width="484" alt="GitHub Error" src="https://user-images.githubusercontent.com/48690502/152171867-be96ca2f-dc1a-4a0a-8d55-6874984b62e6.png">

**Comment by virtadpt** [comment]
It does not work on Big Sur, either.  Went through everything else in this ticket, none of it worked.

**Comment by dooglio** [comment]
@virtadpt even downgrading to the previous version? That still doesn't work?

**Comment by virtadpt** [comment]
Even after downgrading to 5.9.0-20220121194551+95a3939b3a, it worked once or twice and then stopped.  Checking this morning it seems to have automagically upgraded back to 5.9.2-20220131221715+a25f15e42b without asking me.  That new version still doesn't work.

**Comment by dooglio** [comment]
@virtadpt did you set the auto update flag to false in the config file? 

Here is the link: https://github.com/keybase/client/issues/24819#issuecomment-1034500046

**Comment by virtadpt** [comment]
That's a good question, let me check:
...
I did not.  Just set it, trying again.

**Comment by virtadpt** [comment]
Turned off automatic updates in the config file.  Still on v5.90 on Big Sur.  Really miss Finder integration.

**Comment by dooglio** [comment]
@virtadpt you might as well upgrade to the latest version since Finder integration is broken no matter what for you. Unless 5.9.2 has other issues?

**Comment by richardsj** [comment]
Nothing about this is fixed. Keybase is a broken product destroyed because it allows privacy (look at the owners and their agenda)

**Comment by amani1104** [comment]
@richardsj On Monterey it's fixed and finder integration works.

**Comment by Demwunz** [comment]
I can't get kbfuse to work on Monterey. 

Every time I try to enable it I get a prompt from MacOS

![image](https://user-images.githubusercontent.com/54713/175502105-14f6b738-cef6-41fa-82dd-98ddf4369107.png)

If I "open anyway" from system preferences - **vscode** opens up `kbfuse.fs`.

Stuck :/
