### ISSUE TITLE
kbfs does not work on MacOS Monterey 12.0.1

### ISSUE THREAD

**Issue by zesaver** [keybase/client#24675]
Hello,

I have updated my MacBook M1 to MacOS Monterey (12.0.1), can not start kbfs since that. The desktop application shows the "Yes, enable" button, but if I click it "thinks" for a half of a minute and nothing changes (I believe, the FUSE for MacOS can not be loaded).

my log id: 8470d300f270ffb70d75151c

**Comment by jms1voalte** [comment]
I have half a dozen machines that I haven't upgraded to macOS 12 yet, for this very reason - I'm either waiting for an announcement that it _does_ work, or an invitation to help _test_ a new release that they think _should_ work.

**Comment by zesaver** [comment]
Duplicate of https://github.com/keybase/client/issues/24668. May be closed
