### ISSUE TITLE
Keybase locks up, cant sync with repo on Windows 10

### ISSUE THREAD

**Issue by MattWeatherford** [keybase/client#24674]
Keybase locks up, cant sync with repo on Windows 10 desktop
my log id: 1141f93f417651219a354c1c

**Comment by MattWeatherford** [comment]
I quit keybase and restarted it - try to open /keybase/private/{username}/ but it just gives a spinning circle
Im seeing error 218 Sync context deadline exceeded ....FSSubscribePath


Heres another log id

 Your log ID is:   8396261f5e8a0b2cdd6a9e1c

**Comment by MattWeatherford** [comment]
I recently copied my hard drive from old to new SSD - could that break this?  I will try signing out and back in again

**Comment by jms1voalte** [comment]
Looks like something's going on on the server end. I've been wrestling with something similar for the past 3-4 hours, one of the Keybase devs just said on `keybasefriends#kbfs` that they are "looking at it". Hopefully it'll be a quick fix.

**Comment by MattWeatherford** [comment]
This is working fine for me on other windows 2019 servers, Mac OS X, and windows 10 boxes... although I am not looking closely at whether it is syncing or not.  A reinstall worked fine just now.  I suspect something about imaging my win10 box to a new hard drive confused keybase.  All good now.  Hopefully the logs I uploaded during this problem will be of some use. 

Thank you Keybase developers!

M
