### ISSUE TITLE
Incorrect balance shown

### ISSUE THREAD

**Issue by cercos** [keybase/client#24684]
I transferred XLM from coinbase to my address and it shows incorrect balance.  If I use another wallet it shows the correct balance

**Comment by wgroenewold** [comment]
Client doesn't support v18 of Stellar protocol. I transfered my XLM from Keybase to Coinbase and Keybase still shows original amount. When you view your wallet in StellarPort you see the right amount.

**Comment by windhamdavid** [comment]
@wgroenewold Hey. I'm trying your suggestion from #24678 of using Stellarport and it's still failing. Any additional advice?

**Comment by siliconmeadow** [comment]
@cercos - this might be resolved now? Could you check and close the ticket if so? :-)

**Comment by windhamdavid** [comment]
@siliconmeadow  I just tested and it's resolved.

**Comment by cercos** [comment]
@siliconmeadow yeah its resolved
