### ISSUE TITLE
user revoked in Teams room creates notification dialog that cannot be removed.

### ISSUE THREAD

**Issue by mpaujnpr01** [keybase/client#24683]
[write something useful and descriptive here]

my log id: acafe237a571ae8c11bf111c

 user in our chat room revoked his account as he'd lost his keys to it and a notification icon popped up in our Teams portion of the UI and now it won't go away, even after we've tried adding the user back to the group.  If you can please provide a clear notifications for Teams this would be helpful.

**Comment by mpaujnpr01** [comment]
duplicated, already opened 13 days ago by someone else.

**Comment by rr-jonathan-lundy** [comment]
seems related: #13822
