### ISSUE TITLE
Account error 603 - account flagged as spam? 

### ISSUE THREAD

**Issue by jflot** [keybase/client#24731]
Hello,
For the last few days I cannot any more manage users in my Keybase teams - I always get an error message "ERROR CODE 603 - you cannot do this right now". According to what I have read in the keybase-friends #help channel it seems that my account may have been flagged as spam. Could anyone look into this issue? I just sent a description of the problem together with my logs via the Keybase app. Thanks a lot in advance!

**Comment by jflot** [comment]
After sending feedback with my logs twice via the Keybase app (to no avail) I have now tried reporting this issue directly from the command line (`keybase log send`). My log ID: cbf2f40ca4ae55f328299c1c.

**Comment by joshblum** [comment]
reached out over chat
