### ISSUE TITLE
[macOS] Release 5.9.0 is not properly notarized

### ISSUE THREAD

**Issue by mdaloia** [keybase/client#24741]
Trying to open 5.9.0 downloaded from the page produce this message:

<img width="420" alt="Warning from official download" src="https://user-images.githubusercontent.com/1738654/146685625-fd2c9ee5-3f6d-461d-a147-5c0186c51db4.png">

Upgrading from brew produces:

<img width="420" alt="Warning from brew" src="https://user-images.githubusercontent.com/1738654/146685632-32558521-8936-49df-9b2a-5b825bdfcc03.png">

and after hitting `OK`:
```shell
Error: Failure while executing; `/Applications/Keybase.app/Contents/SharedSupport/bin/keybase install-auto` was terminated by uncaught signal KILL.
```

Comparison of notarization assessment of 5.9.0 vs 5.8.0

![Comparison of 5.9.0 and 5.8.0 notarization](https://user-images.githubusercontent.com/1738654/146685537-b58a9f11-b31e-4994-8fb5-1800ff6a35f5.png)

For 5.9.0 it says `rejected` and `Unnotarized`.
For 5.8.0 it says `accepted` and `Notarized`

**Comment by mjuszczak** [comment]
Also experiencing this issue.

**Comment by ericfurspan** [comment]
I am also having this issue. On a Mac w/ intel processor

**Comment by dotLou** [comment]
Does anyone know where we can download an old version of the client to get around this until its fixed?

**Comment by mdaloia** [comment]
@dotLou you could use:
https://prerelease.keybase.io/darwin-updates/Keybase-5.8.0-20210920184218%2Bac2177aec7.zip

(extracted from the previous revision of the Homebrew formula: https://github.com/Homebrew/homebrew-cask/blob/1bbf52686e45b49deb10bcdd7067fcc3d5dd15da/Casks/keybase.rb)

**Comment by Kage1** [comment]
@mdaloia The version you referenced is the last version that appears to install and signed properly. I tried a few of the newer ones with the same error. This is a bit concerning for a secure communications apps.

**Comment by KBio2021** [comment]
Hello guys, sorry jump in like this but do you know if any of the issues regarding the access to the KB desktop app will be treated ? There are dozens of them piling up... How are you guys still able to access it ? Many many thanks

**Comment by jksull** [comment]
@mdaloia @Kage1 

Not sure if you sorted this out, but I managed to get it to work with a (I'm not sure if it can be considered remarkable, or just embarrassing that I didn't try it sooner).

Basically I just right-clicked (two-finger) the keybase app in 'Applications', and opened it that way - instead of just double-clicking.  This was for version 5.9.0, and it wasn't working both on High Sierra or Big Sur.  It now works on Big Sur for me (but not sure about previous macOS as I updated it just for this reason.

**Comment by craftey** [comment]
Wow, 24 days, without a comment or a fix . This is not good.

**Comment by huyz** [comment]
24 days for a company that’s been acquired by Zoom isn’t bad :)

**Comment by banagale** [comment]
Can someone post a link to download the signed version of 5.8?

**Comment by craftey** [comment]
> Can someone post a link to download the signed version of 5.8?

https://github.com/keybase/client/issues/24741#issuecomment-999756157

**Comment by jorgenpt** [comment]
Looks like this was disabled in commit cb632cb17c2bf86ac0c8bb5970076df3649f4eb0 by @joshblum, commit description "debug build scripts post modules". Specifically [`package_darwin.sh` was changed to unconditionally set  `skip_notarize=1`](https://github.com/keybase/client/commit/cb632cb17c2bf86ac0c8bb5970076df3649f4eb0#diff-42fcf2544822302f4f5daeb8ce92284b2755c40d682406ad31eab334c5912991).

**Comment by joshblum** [comment]
hi all, we will be releasing a notarized version of 5.9 shortly. sorry for the issue.

**Comment by timfallmk** [comment]
[5.9.1](https://github.com/keybase/client/releases/tag/v5.9.1) appears to fix this issue, but it has not been pushed to the brew cask. Please do so as soon as is possible.

**Comment by timfallmk** [comment]
@joshblum 5.9.1 seems to still be missing from homebrew. Is there an automated release process for that?

**Comment by joshblum** [comment]
https://github.com/Homebrew/homebrew-cask/pull/118526
