### ISSUE TITLE
[Fedora] keybase 5.9.0 gpg check failed

### ISSUE THREAD

**Issue by andrehofman** [keybase/client#24750]
dnf update fails due to gpg failure

```
sudo dnf update
[sudo] password for andre: 
keybase                                                                                                         50 kB/s | 3.3 kB     00:00    
Dependencies resolved.
===============================================================================================================================================
 Package                    Architecture              Version                                                 Repository                  Size
===============================================================================================================================================
Upgrading:
 keybase                    x86_64                    5.9.0.20211217212642.29bfd9d39f-1                       keybase                    159 M

Transaction Summary
===============================================================================================================================================
Upgrade  1 Package

Total download size: 159 M
Is this ok [y/N]: y
Downloading Packages:
keybase-5.9.0.20211217212642.29bfd9d39f-1.x86_64.rpm                                                            64 MB/s | 159 MB     00:02    
-----------------------------------------------------------------------------------------------------------------------------------------------
Total                                                                                                           63 MB/s | 159 MB     00:02     
keybase                                                                                                         18 kB/s | 6.8 kB     00:00    
GPG key at https://keybase.io/docs/server_security/code_signing_key.asc (0x656D16C7) is already installed
The GPG keys listed for the "keybase" repository are already installed but they are not correct for this package.
Check that the correct key URLs are configured for this repository.. Failing package is: keybase-5.9.0.20211217212642.29bfd9d39f-1.x86_64
 GPG Keys are configured as: https://keybase.io/docs/server_security/code_signing_key.asc
The downloaded packages were saved in cache until the next successful transaction.
You can remove cached packages by executing 'dnf clean packages'.
Error: GPG check FAILED

```

**Comment by ich199** [comment]
I think this is the same issue as https://github.com/keybase/client/issues/24637

**Comment by orgcontrib** [comment]
Hey @andrehofman , you can easily see the huge amount of open issues on this project and yet, instead of digging into those cases looking for a matching symptom, you choose to create a brand new one. Just because we can, it doesn't mean we should. Read the first lines of my comment on (#24665). The community isn't sleeping...

**Comment by andrehofman** [comment]
> I think this is the same issue as #24637  

looks the same indeed.

**Comment by KBio2021** [comment]
Hello guys, sorry jump in like this but do you know if any of the issues regarding the access to the KB desktop app will be treated ? There are dozens of them piling up... How are you guys still able to access it ? Many many thanks

**Comment by andrehofman** [comment]
> Hello guys, sorry jump in like this but do you know if any of the issues regarding the access to the KB desktop app will be treated ? There are dozens of them piling up... How are you guys still able to access it ? Many many thanks

I've kept the old version, which runs fine. Due to the friendly replies, I am not bothered by it after excluding the KB package on my systems. But I am as well surprised by the lack of support for the issue.

**Comment by KBio2021** [comment]
Thanks André for you reply. May I ask where I could download the packages from the old version ? I couldn' find it. If you know how this would be a monster help for me.

**Comment by andrehofman** [comment]
This should help you find the previous version: 
https://s3.amazonaws.com/prerelease.keybase.io/linux_binaries/rpm/index.html

**Comment by KBio2021** [comment]
thank you ! are they all compatible with IOS ? I don't use Linux

**Comment by andrehofman** [comment]
IOS ? haha, no those are rpm's for rpm based system's like Red Hat or Fedora.
You might find an iOS version here: https://prerelease.keybase.io/

**Comment by KBio2021** [comment]
no version other than 5.9.0 I be damned :'(
