### ISSUE TITLE
prerelease.keybase.io https certificate just expired and since it uses HSTS it's inaccessible

### ISSUE THREAD

**Issue by gene1wood** [keybase/client#24763]
The certificate for prerelease.keybase.io is valid through `Dec 27 23:59:59 2021 GMT` and just expired. It's an Amazon certificate.

Ubuntu / Debian releases are inaccessible

**Comment by pzduniak** [comment]
Thanks for the report, we've renewed the certificate.

![image](https://user-images.githubusercontent.com/917230/147686661-27661570-7bc1-43b9-92c7-5bea20321f54.png)
