### ISSUE TITLE
ERR_CERT_DATE_INVALID unable to download current installer mac OS

### ISSUE THREAD

**Issue by shooby83** [keybase/client#24766]
https://prerelease.keybase.io/Keybase.dmg leads to a certification error and I'm unable to download the package

It says that I cannot open the page because it uses HSTS

Cheers, Matt

**Comment by gene1wood** [comment]
This was caused by #24763 which @pzduniak  fixed just now.

**Comment by KBio2021** [comment]
Hello guys, sorry jump in like this but do you know if any of the issues regarding the access to the KB desktop app will be treated ? There are dozens of them piling up... How are you guys still able to access it ? Many many thanks

**Comment by gene1wood** [comment]
@KBio2021 This issue is about the release website's HTTPs certificate. You may be looking for a different issue (this doesn't relate to the desktop app working or not.
