### ISSUE TITLE
Keybase / Finder Integration Does Not Work

### ISSUE THREAD

**Issue by StevenXL** [keybase/client#24786]
I have tried multiple ways to enable Keybase Files / macOS Finder integration. I have installed macFuse directly for its website, and I can see a "Keybase" folder in my Finder Sidebar, but when I click on it I get an error:

![Screen Shot 2022-01-12 at 10 21 52 AM](https://user-images.githubusercontent.com/7391433/149179871-0bb66b6e-f174-4d5a-865a-4656f5c64ef1.png)

my log id: db2ffbe2ce19a96a5e27ec1c

**Comment by a-nldisr** [comment]
see #24636
