### ISSUE TITLE
Finder integration with macOS 12.1 fails

### ISSUE THREAD

**Issue by storskegg** [keybase/client#24787]
## System:

- macOS 12.1
- MacFUSE 4.2.4 (installed via homebrew)
- Keybase Version
  - Client:  5.9.0-20211216221146+9b33c9201f
  - Service: 5.9.0-20211216221146+9b33c9201f

### Mount Point Info

New KBFS Mount Point `/Volumes/Keybase (w4pho)`; `ls -l`:
```
drw-------   2 w4pho  staff   64 Jan 13 10:46 Keybase (w4pho)
```
I noted that the previous mount point was `/Volumes/Keybase` and was chown'ed `root:wheel`, which I assume was supported by previous macOS versions, and is no longer.

## Problem Statement

Keybase is unable to install KBFS Finder integration. Logs show a permission error removing the mount point--even after I had removed it by hand. Maybe something within a FUSE config? FUSE mount returns an error code 2.

Problem may be between macOS and MacFUSE, but may also include KBFS extension. After reading [this thread](https://groups.google.com/g/osxfuse-group/c/zvOkJhn-an0), I was able to force FUSE to load the extension, which triggered the Security & Privacy confirmation, followed by reboot. Per the thread, the Finder integration was still unavailable after the subsequent reboot to enable use of the installed extension.

I haven't attempted the install on a clean 12.1 install, since this is my one machine for personal and work use, and would rather not take that time.

## Steps Taken to Resolve

- Manually updated MacFUSE to the latest available (4.2.4) via Homebrew
- Restarted computer
- Quit Keybase.app (including background service), and killed all running keybase processes
- `sudo rm -rf /Volumes/Keybase*`
- Delete all keybase logs up to this point to keep them noise-free when logging finder integration enablement
- Restart computer just for good measure
- Clicked `Enable Finder Integration` under Files in Keybase app
- `keybase log send`
- Tried the attempted measures in the Google thread linked above; no success.

my log id: cc241c6711d8bbfa32ab821c

**Comment by a-nldisr** [comment]
See #24636
