### ISSUE TITLE
Unnecessary systemd dependency in keybase-gui

### ISSUE THREAD

**Issue by djvs** [keybase/client#24800]
Keybase-gui start script assumes system has systemd.  Seems to work fine on non-systemd system, at least for basic feature usage, with just `keybase ctl init` and `electron13 /usr/share/keybase-app "$@"`.  Assuming that the systemd keybase/kbfs user services are required for other functionality, you could maybe just fork them into separate processes if systemd isn't found.

**Comment by heronhaye** [comment]
Are you referring to the Arch community package? This is true, but the package is not maintained by us. You will need to message Eli Schwartz. If you install the package `keybase-bin` from the AUR, you can start on systems without systemd using `run_keybase`.

**Comment by djvs** [comment]
Ah I see, wasn't expecting it was custom.  Thanks!
