### ISSUE TITLE
Finder integration broken

### ISSUE THREAD

**Issue by ermik** [keybase/client#24827]
Keybase GUI Version: 5.9.2-20220131221715+a25f15e42b

**Comment by abawany** [comment]
Are you also on MacOS Catalina? This previous issue (https://github.com/keybase/client/issues/24819) might help you with a workaround while hopefully they fix the problem.

**Comment by ermik** [comment]
Now on latest kb/macOS and I think other than being near impossible to enable (ctrl + Open opens kbfs bin as a text file) the fuse should be good. I'd prefer a custom mount and optionally disabling the Finder portion (I mostly use kbfs files via Terminal).
