### ISSUE TITLE
is there a way to run keybase on server without a gui?

### ISSUE THREAD

**Issue by NikosEfthias** [keybase/client#24853]
Is there a way to access my repos in keybase on the server ? this is quite the blocker I have to move all the repos elsewhere otherwise

**Comment by NikosEfthias** [comment]
I saw the docs about running it headless on the server however I could not find the binary to install for headless regular keybase wants to install a bunch of GUI stuff

**Comment by heronhaye** [comment]
Hi, unfortunately we don't have a package to just install the CLI and KBFS. You could try building it yourself, or install the entire package and ignore the GUI binary.

**Comment by kg4zow** [comment]
I run Keybase on several machines without GUIs. Install the same package, the only difference is when you run `run_keybase`, add the `-g` option to not start the GUI.

This is documented here: https://keybase.io/docs/the_app/install_linux

**Comment by NikosEfthias** [comment]
@kg4zow  that would require installation of a full desktop environment tho since the package depends on it

**Comment by jms1voalte** [comment]
My CentOS 7 server at home doesn't have any kind of GUI installed, and it installed (and upgraded) just fine. The package's dependencies are ...

```
# rpm -q keybase
keybase-6.0.2.20220610191041.a459abf326-1.x86_64
# rpm -qR keybase
/bin/bash
/sbin/service
at
fuse
libXss.so.1()(64bit)
lsof
procps
psmisc
rpmlib(CompressedFileNames) <= 3.0.4-1
rpmlib(PayloadFilesHavePrefix) <= 4.0-1
```

I don't use the Debian packages, but if you are, and it requires a GUI in order to install, you may want to talk to the Keybase devs about fixing the package's dependencies.

**Comment by kg4zow** [comment]
☝️ that was me, didn't realize I was signed into my work account. Sorry for any confusion.

**Comment by NikosEfthias** [comment]
@kg4zow seems development of keybase slowed down a lot since zoom bought them. :( I am wrong hopefully

**Comment by kg4zow** [comment]
@NikosEfthias What I've noticed is that development has slowed down *somewhat*, and that whatever changes are being made, are being made by people who (1) are not the original Keybase devs, and (2) think that "WIP" is a useful commit message, or maybe that commit messages just aren't important on open-source projects.

My real hope is that, at some point, they'll decide to release the source code for the back end.

**Comment by jw4466261** [comment]
https://assetvest.org company is a changing situation in the world economy and financial markets. They ensure that the returns are satisfactory and 100% risk free. predominantly, Assetvest company has been the strong proponent investment strategies for natural resources, stock market and cryptocurrency investment program where investors make daily profits using the ROI (Return on investment) they have stabilized an efficient trading strategy to ensure maximum profit on real stocks, natural resources and Cryptocurrency investments.from what you've invested in the company and they also offer 2.25%-1.77% transfer commission with a minimum deposit of $ 100, The maximum deposit on their investment section (plan)depends on the investment category you are investing on. Their tier is unlimited as the company has multiple investment plans that work well and each of the investment plans has it own percentage offer. Their withdrawal are fast to any external wallet. meaning that after 3days of your investment, you can choose to withdraw both your capital and daily profits. You can even increase your investment by reloading your investment plan, making a new deposit or requesting a new withdrawal limit, you can choose to make a deposit as many times a day or at any time of your choosing as soon as you're liquid enough on your cash flow to make deposits. The same applies when prompted to do so, depending on the amount you have on your balance, you can withdraw at any time. The higher your investment, the faster the returns you will receive in return will grow. They're very stable and profitable. And also fast during the withdrawal on every withdrawal transaction.
