### ISSUE TITLE
Keybase Android app now missing from Google Play Store

### ISSUE THREAD

**Issue by gene1wood** [keybase/client#24861]
The Keybase android app, https://play.google.com/store/apps/details?id=io.keybase.ossifrage returns a 404 now when you browse to it.

Doing a search for "keybase" in the Google Play Store does not return the keybase app.

Links on the Keybase site that point to the Android app take the user now to the 404

https://keybase.io/download

**Comment by GadisDEV** [comment]
I can see those pages, and keybase pops up in google play

**Comment by gene1wood** [comment]
Excellent, looks like it was a temporary problem and it's fixed, I also see that it's present in the Google Play store again now.
