### ISSUE TITLE
Certificate expired

### ISSUE THREAD

**Issue by tikoflano** [keybase/client#24871]
My keybase client on MacOS is failing. I assume that is due the certificate expiring?

<img width="692" alt="image" src="https://user-images.githubusercontent.com/6231202/160189873-ce80d5dd-86c3-4c0b-ab27-ba903324aebc.png">

**Comment by johnnysa2** [comment]
Same issue here in all devices

![image](https://user-images.githubusercontent.com/102386550/160190361-e798d958-c9fe-4f7c-9497-22f0afe92423.png)

**Comment by JElchison** [comment]
![image](https://user-images.githubusercontent.com/1757771/160190531-5d841e5a-3a61-48f3-a1c8-654f2daf8f71.png)

**Comment by c0mm0d0r3** [comment]
![image](https://user-images.githubusercontent.com/5230615/160190958-c9a5bc03-051d-451b-9501-ab2392042fad.png)
I'm having the same issue when trying to send messages.

**Comment by antevens** [comment]
Ditto

**Comment by Gotchi9106** [comment]
Looks like someone fucked up big time. Same issue here

**Comment by virtadpt** [comment]
Same here.  Tried from home as well as on my cell.

**Comment by virtadpt** [comment]
Looks like it's fixed.  Accessed both my files and Git repo backups.

**Comment by c0mm0d0r3** [comment]
It's fixed for me too. I've tested messages and files so far.

**Comment by tikoflano** [comment]
Closing as it was fixed
