### ISSUE TITLE
keybase app unable to start on Ubuntu 22.04

### ISSUE THREAD

**Issue by nutgaard** [keybase/client#24944]
After updating to ubuntu 22.04 the keybase GUI is not able to start. Manually installed libfuse2 as it was needed for jetbrains' toolbox, but this did not fix the issue. 

```sh
> lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 22.04 LTS
Release:        22.04
Codename:       jammy

> keybase version
Client:  5.9.3-20220216215910+c82d65a685
Service: 5.9.3-20220216215910+c82d65a685

> run_keybase 
Unmounting /run/user/1000/keybase/kbfs...
Unmounting and shutting down kbfsfuse...
Shutting down keybase service...
Starting via systemd...
run_keybase: Success!
```
The window appears shortly without any content before it closes, and the tray icon is gone.
Ubuntu's crash report includes this error message: `Keybase crashed with signal 31 in clone3()`

my log id: 4fb22a05b054898699717f1c

**Comment by ddl-ssenecal** [comment]
Having the same issue.  each attempt to launch shows the following in `dmesg`:


`Chrome_IOThread[193432] trap int3 ip:5643b7f12649 sp:7fce77671420 error:0 in Keybase[5643b58af000+6068000]`

**Comment by visvirial** [comment]
Same here.
Keybase uses 100% CPU resource and nothing appears in the window...

**Comment by visvirial** [comment]
As mentioned in https://github.com/keybase/client/issues/24868, I could start keybase by
```
$ cd /opt/keybase
$ ./Keybase --disable-gpu-sandbox
```

**Comment by woosal1337** [comment]
> As mentioned in #24868, I could start keybase by
> 
> ```
> $ cd /opt/keybase
> $ ./Keybase --disable-gpu-sandbox
> ```

Can not we just set it by default so every time it launches with that exact parameter?

**Comment by visvirial** [comment]
You need to kill the existing process and restart it with the command above.
This is just a workaround and we should wait the official team to fix this problem.

**Comment by josteinaj** [comment]
Instead of adding `--disable-gpu-sandbox` manually each time, it worked for me to edit `/usr/lib/systemd/user/keybase.gui.service` and replace:

```
ExecStart=/opt/keybase/Keybase
```

with:

```
ExecStart=/opt/keybase/Keybase --disable-gpu-sandbox
```

**Comment by heronhaye** [comment]
Hello all, please upgrade to Keybase 6.0.2. The workaround should not be necessary, but let me know if you run into issues. Thank you.

**Comment by iramello** [comment]
WFM, thank you @heronhaye

**Comment by OscarKevinXR** [comment]
I faced the same issue and followed @heronhaye's advice, now the install works!

**Comment by heronhaye** [comment]
Great, thanks for testing it out. I'm going to close this issue. If others are still encountering problems, please make a new issue. Thanks!
