### ISSUE TITLE
keybase is starting up

### ISSUE THREAD

**Issue by ipslfn** [keybase/client#25059]
Keybase GUI Version: 6.0.1-20220609140211+0fc9feea3d
![kb](https://user-images.githubusercontent.com/67012312/173411113-b5a13a56-0634-41dd-bf65-0a2459391b1a.png)

Ever since the most recent update on windows 10, keybase is just stuck in the starting up keybase part.
I've uninstalled and re-installed to no avail.

**Comment by aminhase** [comment]
> This might be an antivirus problem; some of the recent executables are (again) being falsely detected as malicious. VirusTotal example [here](https://www.virustotal.com/gui/file/aa9b818250e375cb4f798b93e17d1ea926863395b927ef37829b4c1fb516115c).

I've got the same issue, and I've noticed that my HIP rules have blocked Keybase from accessing memory! and even though I disabled HIP, Keybase still didn't work. and there is no log of detecting Keybae as a virus or malicious or etc.

**Comment by ipslfn** [comment]
It's working now

**Comment by leminhbee** [comment]
@ipslfn did you have to do anything? Mine is still stuck at starting up... has been since the recent update.

**Comment by ipslfn** [comment]
> @ipslfn did you have to do anything? Mine is still stuck at starting up... has been since the recent update.

okay so, I was messing around in the command line, specifically
keybase chat api-listen
when I received a message the icon changed colors and clicking it led to keybase then working normally, at least the chat function. this fix wasn't persistent but I could replicate it.

**Comment by hughsheehy** [comment]
Same issue. "Keybase starting up". Windows 11. Used to work on previous Windows 10 pc. Got new pc....keybase doesn't work.
