### ISSUE TITLE
Account reset causes public fs home to be inaccessible

### ISSUE THREAD

**Issue by daveio** [keybase/client#2508]
`/keybase/public/dave` is inaccessible after an account reset. I have no option to say "yes, I know I've revoked the key, remove whatever was there before, rekey with my new key, and start fresh".

`/keybase/private/dave` seems to be fine - that might of course be because it may have been empty, I don't think I ever put anything in there with my old devices.

having a look at a previous similar ticket, it might be useful to note that I do have a copy of my previous paper key.

thanks!

my log id: 222f72d80b0c885fe1f41c1c

os x version: 10.11.4 (15E65)

```
dave@dave-rmbp$ keybase version
Client:  1.0.14-20160331130044+9d7e300
Service: 1.0.14-20160331130044+9d7e300
```

**Comment by strib** [comment]
Hi @daveio, unfortunately we don't have an automated process for this yet.  We can reset your public folder manually, but we'd like a signed statement from you authorizing that first.  Can you please run the following command from one of your devices:

```
D=`date` keybase sign -m "$D: Please reset folder /keybase/public/dave because I reset the Keybase account dave"
```

and post the output here.  We'll verify that it was signed by the keybase user `dave`, and then reset the folder to an empty state.

**Comment by daveio** [comment]
Sure:

`BEGIN KEYBASE SALTPACK SIGNED MESSAGE. kXR7VktZdyH7rvq v5wcIkHbsFAFtn8 8qDYd5vsP3UEtHT TdEpjFzQQY0OxBY Fne0i4wYmLkWptw SngExvqDFQNFN8E Ior2PFDHIM4ndab P9M3W3Iuz5xFHzD iwoR7oycmsPxwNK LkDyNbOUj8jj55v DWFkwxSKNVZP8Aa 5wMJXtkEJ3lN9j0 leq7wKKV6QH46kH VyfkL7bryY5QCSV 7eqCdPSx6rEciW1 I6oxU8I1bRkZhpb 1pUSHgt52uvP2tm KhxRMZHb6ZjjQq8 5XVNZtapaEV0xtk V1gkJ3K0Fxi3hEb ofAxXrOi4vEXeUx OXwzNByJg5Voq4J i3eR1a6vgwo1TUr Yo63fj7wq2tmyqU da7NG3W87Psno2o Pjn0xeTrBpXY00. END KEYBASE SALTPACK SIGNED MESSAGE.`

**Comment by maxtaco** [comment]
Seems like the `date` command failed!

**Comment by strib** [comment]
Yeah that's weird.  I wonder what happened, maybe some shell weirdness.  @daveio can you try again?  Maybe just insert the date manually if it keeps giving you trouble.

**Comment by daveio** [comment]
```
BEGIN KEYBASE SALTPACK SIGNED MESSAGE. kXR7VktZdyH7rvq v5wcIkHbsFAFtn8 8qDYd5vsP3UEtHT TdEpjFzQQY0OxBY Fne0i4wYmLwNXfY TmAWkwILeSF9ErG Ngw9JqMTwtXtNXq UeiCzj8qZyk9Tyu 2lxsPt6XaVnX4zK GNXlyRVJZtPyK1g 0cuW6PfcRyJfRpG k5U2euUDbaZH78L Q9ObQImEEQG3A0I PLw4hJTKr671nqm ijQ3s7eH9Cbm1y2 a8JSACzJSBfwjPn wyX2Xj51pHsGN3g oN7RMYKMgV9T24f CMASOUuXGUqzl5m r7jmmZr6A4zUNQE WOkpHIsbaoXHhgw 3SfrSiUIXIr6lfE Xmik6Og38rl64ZS LJGEnsYUHlwN7fw KNE0MDCfqRTjUSb u3PGuJAKVRI80Wc A8xTRBDmusgxw4x yA5SZOuLgICaP5F p5TF2. END KEYBASE SALTPACK SIGNED MESSAGE.
```

How's that?

**Comment by strib** [comment]
Looks good to me!  We'll work on resetting it.

**Comment by daveio** [comment]
Thanks :)

And there's a learning experience. El Capitan stock bash doesn't seem to like local environment vars.

```
dave@dave-rmbp$ X=$(date) echo "$X"

dave@dave-rmbp$ echo $X

dave@dave-rmbp$ XYZZY=$(date) echo "$XYZZY"

dave@dave-rmbp$ echo $XYZZY

dave@dave-rmbp$ XYZZY=$(date); echo "$XYZZY"
Fri  1 Apr 2016 19:01:25 BST
dave@dave-rmbp$ echo $XYZZY
Fri 1 Apr 2016 19:01:25 BST
dave@dave-rmbp$ unset XYZZY
dave@dave-rmbp$ echo $XYZZY

dave@dave-rmbp$ echo "$(date): blah blah blah"
Fri  1 Apr 2016 19:01:49 BST: blah blah blah
```

**Comment by strib** [comment]
Oh weird.  Ok, @daveio can you please try your public folder again?  Should be reset.

**Comment by daveio** [comment]
The client seems happy, I've put a text file and I'm no longer getting an error, however it's not showing up on https://keybase.pub/dave/ when I check there.

**Comment by strib** [comment]
@daveio: can you try writing a few more times?  Probably keybase.pub thinks your folder should be at revision 3, and it's only at revision 2?

It's possible we need to restart the client on keybase.pub as well to fix this. @cjb can maybe help with that.

For what it's worth, I can see it just fine on my client.

**Comment by daveio** [comment]
I've written a bunch of junk to various files in there, and still nothing showing up on keybase.pub - I think it's probably going to need a kick.

**Comment by strib** [comment]
Hrm, bummer.  @cjb, can you kick keybase.pub please?  Might want to do a `keybase log send` too.

**Comment by cjb** [comment]
The kick is done now, I see that it worked.

@strib maybe file a ticket for making the restart unnecessary?

**Comment by strib** [comment]
Ah great.  @cjb can you do a `keybase log send` so I can figure out why it didn't work?

**Comment by cjb** [comment]
I ran log send: 50a833caa37ae0e44f51861c

But I'm using KBFS' log rotation feature, so I have three log files, and I'm not sure they all got uploaded.

**Comment by daveio** [comment]
Yep, it's picking up further changes in real time now. Thanks for your time, all, this can be closed from my perspective.

**Comment by strib** [comment]
Ah, the uploaded log has 100K lines, but it only covers 4 minutes!  Anyway, we already have a ticket for supporting TLF resets, so I'm going to close this and we'll figure it out when we start on that ticket.  Thanks.

**Comment by patrickxb** [comment]
You can increase the number of lines with `-n`.  Up to 1M.  

`keybase log send -h` shows the flag.

**Comment by cjb** [comment]
Or bug me for SSH access to the machine, if you don't have it, to poke at the log files in place.

**Comment by daveio** [comment]
Sorry to repoen, but new files in my public directory aren't being noticed by `keybase.pub` any more - the client seems perfectly happy, files remain accessible locally after a client restart, but the site sees an empty directory.

**Comment by cjb** [comment]
Log send from keybase.pub: 9d10fc1f6bff0671f34f591c

**Comment by strib** [comment]
@daveio: our logs don't go back far enough to tell what's going on.  Would you mind making another write to your public folder, and we can watch the logs to see if anything interesting shows up?

**Comment by daveio** [comment]
`/keybase/public/dave/testfile.001` created.

**Comment by strib** [comment]
@daveio: thanks.  That didn't help, but it seems to have fixed itself.  For the record, it wasn't updating my public folder either during that time.  Now both yours and mine seem fixed.  Investigating why now.

**Comment by strib** [comment]
Ok, it looks like the KBFS server that keybase.pub was connected to was way behind in sending out notifications.  We are still investigating but it looks like some bad behavior on the part of our stream-processing code.  It only affected some updates, because updates that happened to be received by the same server that keybase.pub connected to would have been able to short-circuit the process.

In any case, we're already working on a project to overhaul that stream-processing code, so it should be obsoleted in a few weeks anyway.  Sorry for the inconvenience; hopefully it is a rare occurrence until we fix it.
