### ISSUE TITLE
Windows client problem

### ISSUE THREAD

**Issue by zong0** [keybase/client#2522]
Keybase GUI Version: 1.0.15-20160401165611+c259913

After installation on Windows 7 64bit SP1, the contents of the mapped drive are not accessible (see public and private, but cannot open), either through Explorer, the command line, or the UI app. Rerunning Keybase.vbs and/or the UI app sometimes restores the drive mapping (with duplicate processes running it seems), but the contents of the mapped drive remain inaccessible. Example:

```K:\>dir
 Volume in drive K is KBFS

 Directory of K:\

08/30/1754  06:43 PM    <DIR>          private
08/30/1754  06:43 PM    <DIR>          public
08/30/1754  06:43 PM                 0 kbfs.error.txt
               1 File(s)              0 bytes
               2 Dir(s)  107,362,101,248 bytes free

K:\>cd public
The parameter is incorrect.

K:\>cd private
The system cannot find the path specified.

K:\>
```

my log id: 231e61a2cd389a8c7089ac1c

**Comment by cjb** [comment]
CC @zanderz

**Comment by zanderz** [comment]
cc @taruti

**Comment by zanderz** [comment]
There seem to be lots of entries indicating it doesn't think you are logged in. Could you try rebooting and then opening an instance of `Keybase CMD `and entering `keybase logout`, then `keybase login`?

**Comment by cjb** [comment]
And there's no GUI log. Did it just fail log send, or was it not running?

**Comment by zanderz** [comment]
Status output seems to show UI processes running.

**Comment by zong0** [comment]
I just decided to run the .vbs commands manually to see what's going on. The `keybase ctl watchdog` ran fine; logging in also succeeded, through the GUI flow. However, the Dokan stuff failed. K: mounted correctly and can be seen in "My Computer". However, opening up K: in Explorer (for example) immediately terminated `kbfsdokan.exe`. The full cmd capture of `kbfsdokan.exe -debug k: > dokanlog.txt 2>&1` is attached.

Note, starting on line 36 or 37 of the printout is what goes to stderr immediately after opening up the K: drive in Explorer. On the command line it's slightly different: `cd K:` works; in K:, `dir` even works and you see 'public' and 'private' in the listing. However, `cd public` terminates `kbfsdokan.exe` in the way described as well. Hope this helps.

[dokanlog.txt](https://github.com/keybase/client/files/201634/dokanlog.txt)

**Comment by taruti** [comment]
I can see the bug in dokanlog.txt, it was committed on 2016-03-31, will submit a fix today.

**Comment by taruti** [comment]
The fix has a PR now, @zanderz will create a new build probably with the fix.

**Comment by zong0** [comment]
So, I guess this error wasn't logged to file? If that is indeed the case, and referencing #2399, you may want to log errors like this when kbfsdokan.exe is already dying by dumping via the shell (as I have done), rather than relying on kbfsdokan.exe itself.

**Comment by zanderz** [comment]
Please either run `keybase update check` or download https://s3.amazonaws.com/prerelease.keybase.io/windows/keybase_setup_gui_1.0.15-20160404111414%2B0112799.386.exe for an update which contains this fix.

**Comment by zong0** [comment]
The update yesterday fixed my problem.
