### ISSUE TITLE
Keybase utility changes Windows CPU timer resolution

### ISSUE THREAD

**Issue by nscaife** [keybase/client#2525]
`Client:  1.0.14
Service: 1.0.14`

`Microsoft Windows [Version 10.0.10586]`

On Windows, the Keybase background utility requests an increased CPU timer resolution, even when idling.  This can cause decreased battery life on mobile devices.  From `powercfg -energy`:

![capture](https://cloud.githubusercontent.com/assets/644072/14250217/7346e6dc-fa4b-11e5-9958-2555739398b6.PNG)

Is this intentional? It looks like the utility is idling in the background but keeps the request active.

**Comment by cjb** [comment]
CC @zanderz @taruti

**Comment by taruti** [comment]
This is probably https://github.com/golang/go/issues/8687

@nscaife can you confirm what Runtime says in Platform information from `keybase status`? 

This should be fixed in versions compiled with 1.6, but present in versions compiled with 1.5.x.

**Comment by nscaife** [comment]
@taruti No problem, here's that output:

```
Platform Information:
    OS:        windows
    Runtime:   go1.5.3
    Arch:      386
```

**Comment by taruti** [comment]
Thank you.

This should go away when updating Keybase to a version built with Go version 1.6. (I'd wait 24h before updating for a build with #2522 fix included).

**Comment by zanderz** [comment]
Please try https://dist.keybase.io/windows/keybase_setup_1.0.15.386.exe

**Comment by nscaife** [comment]
This looks like it is fixed now, thanks!
