### ISSUE TITLE
git-remote-keybase error: Server: block does not exist (on multiple repo)

### ISSUE THREAD

**Issue by user-09876** [keybase/client#25291]
Hello,

There are a few repositories in my private keybase, that I can no longer clone, getting the following error.

```bash
Cryptographic cloning: (16.10%) 12.66/78.64 MB... 
git-remote-keybase error: (1) Server: block does not exist
```

I've tried to clone from an other computer where keybase is installed, but I am getting the same errors.

Any idea how I could further debug? I've got very important data in these repo, and can no longer access it.

Best

**Comment by user-09876** [comment]
Thanks for your answer.

I cannot write inside the private KBFS directory as it does not seem to exist on this machine.
I've tried creating it at `/keybase/` and, re-installing keybase/kbfs/keybase-gui, but it still does not seem to do anything.

I can access the repositories though the keybase GUI on my phone, but still cannot clone it on any other machine where I have keybase installed (re-installed).

Any idea how I can have it cloned on a new machine, or have keybase re-installed in a clean state?

Best,
U

**Comment by strib** [comment]
Hmm yeah your log does say "permission denied" for `/keybase`.  Not sure what's going on there, maybe you can try removing that directory and reinstalling the keybase package.  But that just acts as a symlink to the real mount directory, which is usually something like `/run/user/UID/keybase/kbfs` -- you can see what that should be with `keybase config get mountdir` (and you can change it with a similar command, changing "get" into "set" I think).

**Comment by user-09876** [comment]
Hello,

I've tried deleting all keybase related files and packages on my machine, and cloning again the repository, but still getting the same error.

Also tried installing keybase on an other machine and cloning again, but also getting the same error.

Any idea ho I could further debug?

The repository I am trying to clone contain very important data (for me), and I don't have a copy anywhere as keybase was my source of truth, and I really need to get back access to it.

Through the UI on my phone and GUI app on the computer, I can still see the repo and all their content, but can only download files one by one. 

Is there a possibility to download the entire repo, as zip for example, as it is possible on github?

Thanks in advance for your help.

**Comment by strib** [comment]
Are you able to access your private directory from the command line now, either under `/keybase/private` or `/run/user/$UID/keybase/kbfs`?  Once you are in there, you can `cd .kbfs_git` and look at or copy the raw git repo.  There is probably one file with a corrupt block in there or something, but you can try to copy to everything else.

**Comment by user-09876** [comment]
Hello and thank you; yes that seems to work, I will investigate in that direction.
