### ISSUE TITLE
Upgraded to Golang v1.19.3?

### ISSUE THREAD

**Issue by lonnietc** [keybase/client#25306]
Hello,

I was monitoring the latest master branch updates and it seemed like @joshblum had updated things to the latest Golang v1.19.3 but when I grabbed the branch this morning and tried to compile it, I still get the ERROR in the kbfsdokan:

```
> go version
go version go1.19.3 windows/amd64

> go build ./kbfs/kbfsdokan
go: downloading github.com/keybase/goleveldb v1.0.1-0.20221007195407-9881c0c26e65
# github.com/keybase/client/go/kbfs/dokan
kbfs\dokan\cgo.go:699:24: cannot convert func() _Ctype_HANDLE {…}() (value of type _Ctype_HANDLE) to type syscall.Handle
```

Turns out that the core keybase builds correctly with Go v1.19.3

```
> go build ./keybase
```

Also, how do you run a local keybase.exe service to connect for development?

I tried "keybase.exe service" but that seems to run but I get an error message when trying to connect to the localhost.

Thanks

**Comment by ztaru** [comment]
Hi, can you confirm that build works for you with Go 1.18.9 or has worked in the past?

Building `github.com/keybase/client/go/kbfs/dokan` works locally with Go 1.19.4 on master branch.

Can you paste the output of `go env`? Do you have Dokan and Windows headers where your C compiler can find them?

**Comment by ztaru** [comment]
Hi, this should be fixed by https://github.com/keybase/client/commit/f2769591b719890b089466d99c2625d9a360c82a

Please reopen the issue and ping me if you have further issues.
