### ISSUE TITLE
Mastodon social proof not working

### ISSUE THREAD

**Issue by pmepablo** [keybase/client#25349]
Keybase no longer seems to be able to see my proof on mastodon.social.  I did notice that it's up there twice

https://mastodon.social/@pmepablo/104535755774584603
and
https://mastodon.social/@pmepablo/104535749777109988

So it's probably on me.  Odd thing is that it used to work.

**Comment by 3b0b** [comment]
mastodon/mastodon#17405

I assume @joenepraat wil be happy to address any complaints

**Comment by pmepablo** [comment]
Thanks very much.
