### ISSUE TITLE
Can't start kbfs

### ISSUE THREAD

**Issue by reem** [keybase/client#2534]
OS: OS X
Keybase Version: keybase version 1.0.15-20160401130013+78dff87

I can't seem to start kbfs, `keybase ctl restart` hasn't helped.

Output of `keybase status`:

```
Username:      jonreem
Logged in:     yes

Device:
    name:      laptop
    ID:        6fcca53180e3f64881ad6ee5d6f34518
    status:    active

Session:       no session
    is valid:  yes
    keys:      locked
    lksec:     not loaded

KBFS:
    status:    not running
    version:   1.0.2-20160401130057+25510ca
    log:       /Users/reem/Library/Logs/keybase.kbfs.log

Service:
    status:    running
    version:   1.0.15-20160401130013+78dff87
    log:       /Users/reem/Library/Logs/keybase.service.log

Platform Information:
    OS:        darwin
    Runtime:   go1.6
    Arch:      amd64

Client:
    version:   1.0.15-20160401130013+78dff87

Desktop app:
    status:    running
    version:   1.0.15-20160401130013+78dff87
    log:       /Users/reem/Library/Logs/Keybase.app.log

Config path:   /Users/reem/Library/Application Support/Keybase/config.json
Default user:  jonreem
Other users:

command-line client:
    keybase status [pid: 15719, version: 1.0.15-20160401130013+78dff87]

desktop:
    /Applications/Keybase.app/Contents/Frameworks/Keybase Helper.app/Contents/MacOS/Keybase Helper --type=renderer --no-sandbox --lang=en-US --node-integration=true --num-raster-threads=4 --enable-zero-copy --enable-gpu-memory-buffer-compositor-resources --content-image-texture-target=3553,3553,3553,3553,3553,34037,3553,3553,3553,3553,34037,3553,34037,34037 --video-image-texture-target=34037 --channel=12348.1.186385196 [pid: 12354, version: 1.0.15-20160401130013+78dff87, description: Menubar]
    /Applications/Keybase.app/Contents/Frameworks/Keybase Helper.app/Contents/MacOS/Keybase Helper --type=renderer --no-sandbox --lang=en-US --node-integration=true --num-raster-threads=4 --enable-zero-copy --enable-gpu-memory-buffer-compositor-resources --content-image-texture-target=3553,3553,3553,3553,3553,34037,3553,3553,3553,3553,34037,3553,34037,34037 --video-image-texture-target=34037 --channel=12348.2.1751919681 [pid: 12355, version: 1.0.15-20160401130013+78dff87, description: Main Renderer]
    /Applications/Keybase.app/Contents/MacOS/Electron -psn_0_25102319 [pid: 12348, version: 1.0.15-20160401130013+78dff87, description: Main Thread]
```

Output of `keybase launchd list`:

```
keybase.service: Running (pid=14800) [Keybase]
keybase.kbfs: Not Running exit=2 [KBFS]
```

`keybase log send` id: ec6a9aea3bde5eb2c5ef791c

**Comment by strib** [comment]
The log says:

```
2016/04/04 14:09:21 mount helper error: mount_kbfuse: failed to mount /keybase@/dev/kbfuse0: Operation not permitted
```

Does your OSX user have administrative privileges?

**Comment by reem** [comment]
I was not a root user when running any start commands, should I `sudo keybase ctl restart` or `sudo keybase launchd start keybase.kbfs`?

**Comment by strib** [comment]
You shouldn't need to be root.  I just meant admin privileges on your non-root account, e.g.: https://superuser.com/questions/114422/how-to-grant-admin-permissions-to-user-account-in-snow-leopard

**Comment by reem** [comment]
Oh, in that case yes, I am an admin user.

**Comment by strib** [comment]
And you've dragged the keybase dmg into the applications folder and launched it from within that folder?

(We're reaching the end of my ability to debug OSX issues, so if that's not it I'll need to get someone else to take a look...)

**Comment by reem** [comment]
Yeah, I've done that as well, still not working.

**Comment by strib** [comment]
Ok, @gabriel can you take a look please?

**Comment by gabriel** [comment]
This seems like another kbfs might be running which has the mount already?

Is this installed or running as another user?

You could try doing:

```
keybase uninstall
pkill kbfs
keybase install
```

**Comment by reem** [comment]
Just tried that, didn't change anything. `mount` doesn't list any custom mounts.

**Comment by reem** [comment]
Note that it looks like keybase comes with its own version of fuse (kbfuse), and I also have osxfuse installed, if this could be causing a problem.

**Comment by gabriel** [comment]
what does `ls -al` look like for `/keybase` (permissions)?

**Comment by gabriel** [comment]
Yeah we have a separate KBFuse that we manage that can co-exist with OSXFuse, so that shouldn't be the issue...

Also, what's the output of:

```
kextstat | grep fuse
```

**Comment by reem** [comment]
It didn't exist, and when I created it with `sudo mkdir /keybase` I get:

```
❯ ls -al /keybase
total 0
drwxr-xr-x   2 root  wheel    68 Apr  4 15:48 .
drwxr-xr-x  36 root  wheel  1292 Apr  4 15:48 ..
```

```
❯ kextstat | grep fuse
152    0 0xffffff7f832db000 0x16000    0x16000    com.github.osxfuse.filesystems.osxfusefs (2.8.3) 7DBFEA1C-C986-3A12-9419-C09D25A6F3EA <7 5 4 3 1>
249    0 0xffffff7f833d2000 0x1a000    0x1a000    com.github.kbfuse.filesystems.kbfuse (3.2.0) AF9EEF06-5277-351B-83D6-D9E65624AB90 <7 5 4 3 1>
```

---

Is KBFuse open source? I've worked with osxfuse before and have been pretty frustrated with the API so I'm curious to see what you all changed.

**Comment by gabriel** [comment]
It doesn't exist? The log id from above seemed to think it did...
Can you rm `/keybase` and then restart the Keybase.app? The app will create this directory with the right permissions.

KBFuse is exactly same as OSXFuse but it's namespaced (or "branded") so we can control and enforce specific versions and not conflict with other apps.

**Comment by reem** [comment]
That worked! Odd. Thanks for your help. Makes sense re: kbfuse.

**Comment by gabriel** [comment]
I'm gonna make an issue to add some checks around this for the future. It should probably resolve/fix any permissions problems it encounters.

Thanks for helping debug!

**Comment by lherlitz** [comment]
I think this is the same issue I'm having on macOS Sierra. I'm getting 
`keybase.service: Running (pid=2407) [Keybase]
keybase.kbfs: Not Running exit=2 [KBFS]
keybase.updater: Running (pid=2422) [Updater]` 
after running `keybase launchd list `

How do I do your solution:

> Can you rm /keybase and then restart the Keybase.app? The app will create this directory with the right permissions.

**Comment by gabriel** [comment]
We are still testing the macOS sierra builds and waiting on golang fixes. There we some issues with golang which are still being resolved by that team.

**Comment by gabriel** [comment]
Here is a build which supports macOS 10.12 (Sierra):
https://prerelease.keybase.io/darwin/Keybase-1.0.17-20160817191833%2Be83e8a5.dmg

**Comment by lherlitz** [comment]
Suggestions on how to get it up and running once I've installed it? Same error as before.

**Comment by lherlitz** [comment]
`▶ ERROR keybase.kbfs is not running (exit status 2`

**Comment by gabriel** [comment]
Can you post a `keybase log send` ID?

**Comment by lherlitz** [comment]
279edf7db429d756207ea81c

**Comment by gabriel** [comment]
Oh it's possible we need to reset permissions on the placeholder /keybase directory.

If you do:
```sh
keybase ctl stop
keybase uninstall
sudo rmdir /keybase
# Then re-open app.
open /Applications/Keybase.app/
```

If this doesn't fix, lmk and will dig further.

We have a patch coming soon to look for and fix permissions problems if something weird happened (or in your case an earlier Sierra incompatibility), to make this stuff a little more bulletproof.

**Comment by lherlitz** [comment]
Did all that. Same as before - doesn't work.

**Comment by lherlitz** [comment]
455bfe78989294c9f20b3f1c

**Comment by gabriel** [comment]
From the logs it looks like somehow the old version of the app (helper tool) re-created the directory with the bad permissions before the new one ran. 

Now that you have the more recent app with fixes, can we try one more time?
```sh
keybase ctl stop
keybase uninstall
sudo rmdir /keybase
open /Applications/Keybase.app/
```

**Comment by lherlitz** [comment]
Do I need to remove the UI app from my applications folder at all? I've done all of these steps again and still, the Keybase folder will not open.

**Comment by lherlitz** [comment]
New log ID `ce5c9d5dafdeb39120d3f61c`

**Comment by lherlitz** [comment]
Seems like a _lot_ of helpers.
![](http://g.recordit.co/O0fnQdyzlp.gif)

**Comment by lherlitz** [comment]
After uninstalling and physically removing the app, there were still helpers running. I managed to find and remove them as well. Did a full fresh restart. My other computer detected the new install and rekeyed my files. Still can't open them. New log ID `f22503d0f108f0a5f8ae7d1c`

**Comment by gabriel** [comment]
The helpers are ok. 

Sorry it's still not working! I'll have to dig into the logs a little deeper.

**Comment by lherlitz** [comment]
No apology needed. I know Keybase is in alpha and I'm running a beta OS, so I'm playing with fire here. 😄 

I'm hope this just helps y'all with testing before Sierra goes live next month.

**Comment by gabriel** [comment]
Yep this is super helpful.

Can you try running this version:
https://keybase.pub/gabrielh/Keybase-1.0.17-20160824235155%2B51f7870.dmg

It has some extra debugging in it.

**Comment by gabriel** [comment]
Oh and can you do the following when installing:

- Quit Keybase.app
- Copy from dmg to /Applications
- Run `keybase ctl stop` from command line
- Then `open /Applications/Keybase.app`

**Comment by lherlitz** [comment]
`▶ ERROR No service (plist) installed with label: keybase.kbfs`

Log ID `64f78d8ad23953ae2728f41c`

**Comment by lherlitz** [comment]
I feel like we're getting closer. I can actually open the Keybase folder now without getting the error message that I don't have permission. However, the folder is completely empty and never shows private or public folders.
![](http://g.recordit.co/e4LUhhUtjj.gif)

**Comment by gabriel** [comment]
I'm still a little baffled what's going on, the fuse mount is still erroring the same way and the error is especially cryptic... And I can't reproduce it either (on a machine and a vm so far).

If you `ls -al /` what does the keybase folder line look like:
It might look something like this:
```
drwx------     2 gabe  staff     68 Aug 25 14:25 keybase
```

What is the output of:
```sh
kextstat | grep fuse
```

It should look something like this:
```
 290    0 0xffffff7f83f8b000 0x19000    0x19000    com.github.kbfuse.filesystems.kbfuse (3.4.2) 3D1D2A40-206A-39DD-A1F6-5DE4AD1A42B2 <7 5 4 3 1>
```

And what is the output of `mount -t kbfuse`. It might not list anything.

And finally... when you start Keybase, do you see anything happen in the system.log.. You can view from Console.app (or looking at `/private/var/log/system.log`).

**Comment by gabriel** [comment]
Oh yeah, and are you on the latest Sierra beta? (I think beta 7)... In `About This Mac` does it say `Version 10.12 Beta (16A304a)`.

**Comment by lherlitz** [comment]
Yes, that's the version.

`ls -al /` returns nothing about Keybase
![](http://g.recordit.co/zTL2xzd6Jw.gif)

`kextstat | grep fuse` returns nothing
![](http://g.recordit.co/7EPIqZlUio.gif)

Console:

`Aug 25 17:49:26 Lucs-MacBook-Pro keybase.Helper[30277]: Request: version({
	})
Aug 25 17:49:26 --- last message repeated 3 times ---
Aug 25 17:49:26 Lucs-MacBook-Pro com.apple.xpc.launchd[1] (keybase.updater): This service is defined to be constantly running and is inherently inefficient.
Aug 25 17:49:28 Lucs-MacBook-Pro com.apple.xpc.launchd[1] (keybase.service): This service is defined to be constantly running and is inherently inefficient.
Aug 25 17:49:29 Lucs-MacBook-Pro keybase.Helper[30277]: Request: remove({
	    path = "/keybase";
	})
Aug 25 17:49:29 --- last message repeated 1 time ---
Aug 25 17:49:29 Lucs-MacBook-Pro keybase.Helper[30277]: Request: createDirectory({
	    directory = "/keybase";
	    excludeFromBackup = 1;
	    gid = 20;
	    permissions = 448;
	    uid = 501;
	})
Aug 25 17:49:30 --- last message repeated 1 time ---
Aug 25 17:49:30 Lucs-MacBook-Pro com.apple.xpc.launchd[1] (keybase.kbfs): This service is defined to be constantly running and is inherently inefficient.
Aug 25 17:49:31 Lucs-MacBook-Pro com.apple.xpc.launchd[1] (keybase.kbfs[44599]): Service exited with abnormal code: 2
Aug 25 17:49:31 Lucs-MacBook-Pro com.apple.xpc.launchd[1] (keybase.kbfs): Service only ran for 0 seconds. Pushing respawn out by 10 seconds.
Aug 25 17:49:32 Lucs-MacBook-Pro Console[44553]: BUG in libdispatch client: kevent[EVFILT_MACHPORT] monitored resource vanished before the source cancel handler was invoked
Aug 25 17:49:39 Lucs-MacBook-Pro com.apple.xpc.launchd[1] (com.apple.quicklook[44615]): Endpoint has been activated through legacy launch(3) APIs. Please switch to XPC or bootstrap_check_in(): com.apple.quicklook
Aug 25 17:49:41 Lucs-MacBook-Pro com.apple.xpc.launchd[1] (keybase.kbfs[44616]): Service exited with abnormal code: 2
Aug 25 17:49:41 Lucs-MacBook-Pro com.apple.xpc.launchd[1] (keybase.kbfs): Service only ran for 0 seconds. Pushing respawn out by 10 seconds.
Aug 25 17:49:41 Lucs-MacBook-Pro com.apple.xpc.launchd[1] (com.apple.imfoundation.IMRemoteURLConnectionAgent): Unknown key for integer: _DirtyJetsamMemoryLimit
`

**Comment by gabriel** [comment]
ok, maybe it's the kext failing to load... what happens if you run this: 

```
/Library/Filesystems/kbfuse.fs/Contents/Resources/load_kbfuse 
echo $?
```

Then when you run `kextstat | grep fuse` does it show anything.

What is the output of (so I can see permissions): 
```
ls -al /Library/Filesystems/kbfuse.fs/Contents/Resources/load_kbfuse
```

**Comment by lherlitz** [comment]
I did grep instead of grep fuse the first time. Here's the scoop:

`Last login: Thu Aug 25 18:29:25 on ttys000
Lucs-MacBook-Pro:~ lucherlitz$ /Library/Filesystems/kbfuse.fs/Contents/Resources/load_kbfuse 
Lucs-MacBook-Pro:~ lucherlitz$ echo $?
6
Lucs-MacBook-Pro:~ lucherlitz$ kextstat | grep
usage: grep [-abcDEFGHhIiJLlmnOoqRSsUVvwxZ] [-A num] [-B num] [-C[num]]
	[-e pattern] [-f file] [--binary-files=value] [--color=when]
	[--context[=num]] [--directories=action] [--label] [--line-buffered]
	[--null] [pattern] [file ...]
Lucs-MacBook-Pro:~ lucherlitz$ kextstat | grep fuse
Lucs-MacBook-Pro:~ lucherlitz$ ls -al /Library/Filesystems/kbfuse.fs/Contents/Resources/load_kbfuse
-rwsr-xr-x@ 1 root  wheel  26636 Apr 12 15:40 /Library/Filesystems/kbfuse.fs/Contents/Resources/load_kbfuse`

**Comment by lherlitz** [comment]
http://recordit.co/oKcZoOWy91

**Comment by gabriel** [comment]
ok, it's the kext failing to load and isn't directly a mount issue... we're getting closer.. I'll keep digging.

**Comment by lherlitz** [comment]
Sweet! Thank you!

**Comment by gabriel** [comment]
What happens if you run and install the latest osxfuse:
https://github.com/osxfuse/osxfuse/releases/download/osxfuse-3.4.2/osxfuse-3.4.2.dmg

(kbfuse is a renamed version of that, so we don't conflict with existing fuse installs, if people rely on specific versions of fuse)

After installing, what happens if you do:

```sh
/Library/Filesystems/osxfuse.fs/Contents/Resources/load_osxfuse 
echo $?
```

And then whats the output of `kextstat | grep fuse` again?

**Comment by lherlitz** [comment]
![](http://g.recordit.co/x7Xn51me7r.gif)

**Comment by gabriel** [comment]
Ok, getting closer.. what is the output of:
```
ls -ld $(find /Library/Filesystems/kbfuse.fs/)
```

And the output of:
```
codesign --verify --verbose=4 /Library/Filesystems/kbfuse.fs
```

**Comment by lherlitz** [comment]
[Terminal Saved Output.txt](https://github.com/keybase/client/files/438272/Terminal.Saved.Output.txt)

**Comment by gabriel** [comment]
ok, I think I see the problem... one last thing (I think):

```sh
cat /Library/Filesystems/kbfuse.fs//Contents/Info.plist
```

**Comment by lherlitz** [comment]
[Terminal Saved Output 2.txt](https://github.com/keybase/client/files/438286/Terminal.Saved.Output.2.txt)

**Comment by gabriel** [comment]
ok, I know what the issue is... I'll have an fix soon. Thanks a ton for your help!

**Comment by gabriel** [comment]
Ok, this build should work:
https://keybase.pub/gabrielh/Keybase-1.0.17-20160826020144%2B61c0667.dmg

**Comment by lherlitz** [comment]
You, sir, are a genius! It works!

**Comment by lherlitz** [comment]
Well, I now have two keybase folders, seemingly identical. One on my desktop, one at the top level.  Can't remove either. but, I can add files, so that's working!

**Comment by egp** [comment]
Hooray, that fixed it for me also.

**Comment by zbeat** [comment]
> Ok, this build should work:
https://keybase.pub/gabrielh/Keybase-1.0.17-20160826020144%2B61c0667.dmg

@gabriel Is there a more recent fix I can grab?

**Comment by gabriel** [comment]
Our latest release now works on Sierra: https://keybase.io/docs/the_app/install_macos

**Comment by zbeat** [comment]
@gabriel If by [latest release](https://github.com/keybase/client/releases) you mean 1.0.17, that's what I'm running:
<img width="813" alt="keybase-1 0 17-error-sierra" src="https://cloud.githubusercontent.com/assets/21324/19197287/cb51d846-8c6d-11e6-8174-de48fd1c9c24.png">

**Comment by cjb** [comment]
@zbeat No, there's a newer version available now.  The version string is 1.0.17-20160930202009+0229d49, you can get it from an automatic update (prompted hourly) or from https://keybase.io/docs/the_app/install_macos.

**Comment by zbeat** [comment]
@cjb And magically a popup appears 1 hour later:
<img width="690" alt="keybase-1 0 17-update" src="https://cloud.githubusercontent.com/assets/21324/19198883/2e3caf6e-8c76-11e6-80cb-72bee67aa667.png">

👍
