### ISSUE TITLE
keybase.pub TLS certificate expired on 12/28/2022

### ISSUE THREAD

**Issue by gene1wood** [keybase/client#25398]
@joshblum Looks like you may be active over at Zoom here during this slow week. The `keybase.pub` TLS cert just expired.

https://keybase.pub/

You should renew it (and maybe enable monitoring for cert expiration)

Also reported [over on reddit](https://www.reddit.com/r/Keybase/comments/zyhnyg/keybasepub_https_certificate_expired/)

**Comment by kocour** [comment]
Also notice, that all public proofs hosted at this domain are falsely reported to users as broken due to expired cert.

**Comment by gene1wood** [comment]
Another reddit thread on it here : https://www.reddit.com/r/Keybase/comments/zyoc58/keybasepub_cert_expired_can_someone_look_at_this/

**Comment by gene1wood** [comment]
Or @chrisnojima maybe you can contact Zoom SREs?

**Comment by qgustavor** [comment]
[Seems it got renewed.](https://user-images.githubusercontent.com/1020670/210100315-59300525-7a50-4009-9d06-75e92e17e369.png)

**Comment by gene1wood** [comment]
Yup, it was just updated today. Thanks Zoom team!
