### ISSUE TITLE
Linux: Mount works, cannot work with files

### ISSUE THREAD

**Issue by doodlemania2** [keybase/client#2549]
I can move around the KBFS with CD but cannot touch or vim any file or even ls within the system.

my log id: 839d7c4d142efa413476f41c

**Comment by strib** [comment]
Looks like your device restarted, and you didn't re-login to KBFS or unlock your private key.  If you don't see the GUI prompt, you can try doing `keybase unlock` to get it to work, but it looks like at the very end of the log it might have started working again?

**Comment by doodlemania2** [comment]
Well, call me sheepish...sorry about that and thanks Strib!
