### ISSUE TITLE
'Context deadline exceeded' error when uploading a short mov clip

### ISSUE THREAD

**Issue by jonalmeida** [keybase/client#2551]
STR:
1. Created a screen recording with QuickTime (about 5 secs worth of recording)
2. Direct from QT, save the file to your keybase directory.

<img width="326" alt="screen shot 2016-04-06 at 1 33 31 pm" src="https://cloud.githubusercontent.com/assets/1370580/14326506/4b9f8c3a-fbfc-11e5-9267-0c40eeed1487.png">

Keybase GUI Version: 1.0.14-20160312001243+91a29db

my log id: ca91f875fc8e7377afb3531c

**Comment by cjb** [comment]
Please could you run `keybase update run` and retry?  Unfortunately we stranded you on a pretty old release with an updater breakage (on 3/12).

**Comment by jonalmeida** [comment]
Ah shoot, I was wondering why I don't get those notifications about new builds anymore.

**Comment by cjb** [comment]
Thanks.  It might not fix the problem -- this error happens whenever a KBFS operation is blocked for more than 19 seconds, which can happen if you have a lot to upload and not a fast net connection.  In the medium-term we'll batch writes locally to avoid having to get them to KBFS before this timeout happens!

**Comment by jonalmeida** [comment]
Yeah, that would be great if it would save locally first! Any application that tries to read or write to /keybase ends up locking until the save/upload is complete.

Updating seems to have fixed my issue though. Thanks!
