### ISSUE TITLE
Having A tough time providing proof i need for keybase to prove my github account & I tripple checked it & i know every single time its right! Please help OpenSource

### ISSUE THREAD

**Issue by ghost** [keybase/client#25544]

**Comment by gonzalob** [comment]
I suggest you provide some information to get help. Your keybase username, the link to your gist proof would be good starters.

**Comment by gonzalob** [comment]
Your gist doesn't seem to be public. It is critical that it can be readable by everyone, as keybase clients check proofs on their side every now and then.

Make sure it is visible at https://gist.github.com/J-Richardson22

**Comment by gonzalob** [comment]
Your gist doesn't seem to be named keybase.md. Please check against, for instance, mine: https://gist.github.com/gonzalob/7ecf9696f2506fc75e35

For agility's sake, find me at keybase and we'll follow up there. We can later come back here and leave the details for future reference.

**Comment by gonzalob** [comment]
Still suffixed with .txt. It has to be **keybase.md**

Once you get it working, `keybase id -s` should get you something like this:

```
% keybase id -s
▶ INFO Identifying gonz0
...
✔ "gonzalob" on github: https://gist.github.com/7ecf9696f2506fc75e35
...
```
