### ISSUE TITLE
Error when trying to log in

### ISSUE THREAD

**Issue by zurchpet** [keybase/client#2556]
Keybase GUI Version: 1.0.15-20160406164315+a1674b4

Arch Linux.
Latest version from AUR installed.

See screenshot:

![keybase_037](https://cloud.githubusercontent.com/assets/155581/14342912/c1ee9d44-fc9d-11e5-8c0d-2e5ecf17afc0.png)

And keybase log send gives me:

Continue sending logs to keybase.io? (type 'YES' to confirm): YES
▶ WARNING error opening log "/home/zurchpet/.cache/keybase/keybase.start.log": open /home/zurchpet/.cache/keybase/keybase.start.log: no such file or directory
▶ ERROR API network error: Post https://api.keybase.io/_/api/1.0/logdump/send.json: x509: certificate has expired or is not yet valid

Please tell me if I can provide more information.

**Comment by klette** [comment]
The SSL certificate used by api.keybase.io has expired. So the CLI-tools dont work either.

**Comment by ghalfacree** [comment]
Same problem here, with CLI output:

Just upgraded to the latest Keybase Linux beta build - the one with the GUI for KBFS - and it's throwing a nasty error. `run_keybase` seems to work fine, but the GUI tells me I'm logged out and brings up a "provisioning error" when I enter my username. The CLI app, meanwhile, throws this when I `keybase login`: `ERROR API network error: Get https://api.keybase.io/_/api/1.0/merkle/path.json?poll=10&uid=a6d85424e7127b85b6a36823ae4b1700: x509: certificate has expired or is not yet valid (error 1601)`

`keybase version` returns:
Client:  1.0.15-20160406160016+a1674b4
Service: 1.0.15-20160406160016+a1674b4

**Comment by maxtaco** [comment]
Thanks folks, on it.  Our cert expired.  I'll get a new one out in a few minutes...

**Comment by maxtaco** [comment]
Should be fixed, try again?  I made a new cert/key on the server-side.

**Comment by ghalfacree** [comment]
@maxtaco Yup, that's working fine now. Ta!

**Comment by zurchpet** [comment]
All is working again. Thanks :+1: Have a nice day.

**Comment by kevin-tla** [comment]
@maxtaco 

I think your certificates expired again. Was using wget on a linux machine to the keys and I'm getting this:

ERROR: The certificate of ‘keybase.io’ is not trusted.
ERROR: The certificate of ‘keybase.io’ has expired.
