### ISSUE TITLE
Browsing around in /keybase/ to save a text file results in errors

### ISSUE THREAD

**Issue by mikaelf** [keybase/client#2564]
When I browse the directory /keybase/ in Mac OS X I get the following error messages:
`Keybase: Bad folder. /keybase/private/ is not a Keybase folder. All folders begin with /keybase/private or /keybase/public.`
`Keybase: User not found. untitled.txt is not a Keybase user`

log id: 8e585a8ee431d7896e28191c

🌠

**Comment by cjb** [comment]
@strib The code on the desktop side looks correct to me:
```js
    [enums.kbfs.FSErrorType.badFolder]: {
      title: 'Keybase: Bad folder',
      body: `${tlf} is not a Keybase folder. All folders begin with /keybase/private or /keybase/public.`
    },
    [enums.kbfs.FSErrorType.userNotFound]: {
      title: 'Keybase: User not found',
      body: `${notification.params.username} is not a Keybase user`
    }
```

**Comment by strib** [comment]
@cjb: That first one should be `${notification.params.tlf}`, which is different from what you are calculating as `${tlf}` above this code.

Here are the actual unfiltered complaints from the log:
```
2016-03-29T07:54:16.346656 ▶ [DEBU kbfsfuse fs.go:252] 413 /keybase/åi is not a Keybase folder.  All folders begin with /keybase/private or /keybase/public. [tags:FID=idZEe7dOPoU7G6LMwkcyaQ]
...
2016-04-07T10:15:45.240032 ▶ [DEBU FUSE serve.go:838] 356 -> [ID=0x4] Lookup error=ENOENT: /keybase/untitled.txt is not a Keybase folder.  All folders begin with /keybase/private or /keybase/public.
```
So @mikaelf  it looks like something on your device is trying to lookup `/keybase/åi` and `/keybase/untitled.txt`, which are not valid paths.

**Comment by cjb** [comment]
@strib Oops, thanks.  Opened PR.
