### ISSUE TITLE
Corrupted private folder with too device revocation

### ISSUE THREAD

**Issue by zmanian** [keybase/client#2572]
It looks like revoking a bunch of devices corrupted my private folder
my log id: 7dfe32b9dad5ab0aecf9261c

**Comment by strib** [comment]
It appears that the revoked device somehow wrote to the folder AFTER it was revoked, at least according to our server timestamps:

```
26149 2016-04-09T20:20:20.162764 ▶ [DEBU kbfs kbpki_client.go:121] 0fd Not trusting revoked verifying key 0120f846af53c06b764bfa8632047894bc8cbd3328b2192c7d411b7b5c0765bcffa70a for user c5fed3d56138e21ca4603dc5a205ab00 (revoked time: 2016-04-09 20:11:23 -0700 PDT vs. server time 2016-04-09 20:17:18 -0700 PDT) [tags:FID=1yhP3IazHSEA3F7p1RWCIw]
```

That is, your `ZakiPixel2` device wrote to the folder 6 minutes after it was revoked.  In theory your device from the session should have been logged out once it was revoked, and the server should have started rejecting your writes, but there might be a small lag there.

@zmanian: any chance you can do a `keybase log send` from `ZakiPixel2`, so we can see what exactly happened when it was revoked?

@maxtaco: the timestamp on the revocation is the _server_ timestamp, not the client timestamp, right?

**Comment by zmanian** [comment]
I was having trouble logging in on the device. I kept getting into an inconsistent login state. I think I blew away the logs. But I didn't start revocations until I got a stable login on the device.

**Comment by zmanian** [comment]
Here is a log id from the that device.
db1c493ca050d614c632421c

**Comment by strib** [comment]
Ok thanks, that's helpful.  I think I see the problem.  Your device `ZakiPixel2` last wrote to the folder around 18:32, and then got revoked at 20:11.  Then, you provisioned `ExtaPixelish` (I guess from the same physical hardware) and tried to access KBFS.   This device didn't yet have access to the folder, and so requested a rekey of the folder by setting the `rekey` bit of the folder MD around 20:17 -- but it leaves the current "writer" signature alone, which was still signed by the old device.  (It makes a "reader" signature over different metadata fields.)

Then when your other device saw the new folder metadata, it sees the server timestamp for the rekey bit, and tries to verify the "writer" signature using that same timestamp, at which point the device wasn't valid anymore.

So, this is a bug in our client.  The good news is that your folder metadata isn't corrupted, you're just being "protected" from it erroneously.  Tomorrow or Monday I will figure out a way to fix the timestamps we use for verification in this way, and we'll get a new build of the KBFS client that will be able to read your folder.  In the meantime, very sorry for the inconvenience!

**Comment by strib** [comment]
Ok, I just committed a fix for this in our repo.  It should go out in the public builds on Wednesday morning.  Please update on Wednesday and let me know if it fixes the issue for you.

**Comment by zmanian** [comment]
Will report back!

**Comment by zmanian** [comment]
The Wednesday update fixed things for me. I can access my folders again
