### ISSUE TITLE
Windows public/private directories are emtpy 

### ISSUE THREAD

**Issue by sirishkumar** [keybase/client#2576]
Suddenly public and private folders on windows are empty for my directory(sirishkumar), but I can see the files in linux and https://keybase.pub/sirishkumar/ folder. I can see public files of other user on windows but not mine.

Tried keybase logout and login, it didn't helped.

my log id: f5f44b21d05c25b9c86eb21c

**Comment by taruti** [comment]
Looks like something on bserver and not specific to Windows? @strib have you got any idea?

**Comment by strib** [comment]
Hi @sirishkumar.  It looks like the folder is in a conflicted state on your Windows device.  That means that two of your devices tried to write to the folder at the same time.  Looking at our logs, it appears your device `DigitalOcean` wrote to the folder at `2016-04-11T13:08:41Z`, while `EBLapTop` wrote to it about 2.5 minutes later but without having known about the previous update.  Usually, KBFS is able to recover from conflicts like this automatically, but in your case it seems to be stuck in a state where it expects the server to have some data that it doesn't have.

Unfortunately, the logs from `EBLapTop` were large, and the default `log send` command didn't upload enough of the log.  Can you please try again with the command `keybase log send -n 1000000` and let us know the new log ID?  Thanks!

**Comment by sirishkumar** [comment]
New log id with above command a086db2c9d817156c9d1071c

**Comment by sirishkumar** [comment]
Reinstalling the Keybase client also didn't helped in restoring the view. How can fix this for the time being?

**Comment by strib** [comment]
Hi @sirishkumar.   Thanks to your logs, we found a bug in our code.  We have a background process that cleans up old data to free up your quota, and it had a race condition that got triggered when the device was in a conflicting mode.  What happens is that our conflict resolution process succeeds, but the device doesn't know it succeeded.  Later, some of the data associated with that device's conflict branch are deleted, leaving the device stranded and unable to read any data or get out of the conflict mode.  It looks like this happened to your twice on two different folders.

We have to fix this for you on our servers, by clearing the state of your device on our servers. That is easy for us, but we would like your public permission to mess with your data like that.  To give us permission, can you please run the following command on one of your devices and post the output here?  Make sure to substitute the current date and time where indicated.

```
keybase sign -m "<DATE_AND_TIME>: Please clear the conflict branches for folders /keybase/private/sirishkumar and /keybase/public/sirishkumar."
```

**Comment by sirishkumar** [comment]
@strib Output below
BEGIN KEYBASE SALTPACK SIGNED MESSAGE. kXR7VktZdyH7rvq v5wcIkHbsGmcH4f cfLNs840q
aBnaug O6MWHnO64x2GI32 AxTf0IV8gJ0np6p 80VBj4jJOUDZ3bs zVTb9l9qGbNEzeQ PajVDp6Op
KqbQhQ rgEy8NV6P81Ec7L N8vlB9fHWgotS5v DY5MK2IQ6zWXkci siEfA0I9vI8Ax3P UFvuPM6vI
MCkUOg N7uV6VXnF6DSSV4 CpW5s7dnx7Qgr5J Of41j8Hf7oDqFfU 5Z5D1TviTDCfgCZ csDQAwLPf
C1OQjm 8US6AWJOCcP0yGY PCGPrvt0tAxa3NY 1RbFrHfjqOdovoG wO4PPfk0ZLpw5Bk 9hs99q06O
15i9cO zPtlBQj6E0KVDda QVubECMwJC5xc2p gkfH6JtjMTbdHWp eWAEtznQzUW7Qa6 pAtHJJvM3
Bwirwm SzrONt62EeRXfOw DXVKDsBXjv1ePNy lZk58W8. END KEYBASE SALTPACK SIGNED MESS
AGE.

**Comment by strib** [comment]
Thanks @sirishkumar, your branches have been cleared.  You might need to restart KBFS on your device to see the changes.  Let us know if everything looks ok now.

**Comment by sirishkumar** [comment]
@strib its ok now. Thank you

**Comment by strib** [comment]
Great!
