### ISSUE TITLE
Browsing /keybase causes lots of "Keybase: User not found" errors

### ISSUE THREAD

**Issue by lyoshenka** [keybase/client#2586]
I'm on Ubuntu 14.04. These errors pop up every time the Linux prompt shows up, right before the prompt appears. However, if you stay in the same directory and press Enter a few times in a row, the errors will only happen the first time (feels like some sort of caching...).

![keybase bug](https://cloud.githubusercontent.com/assets/362784/14446138/b73c924e-0020-11e6-9c8b-64aed3f9ad21.png)

my log id: 5b43e50f75e9882e17f54f1c

**Comment by cjb** [comment]
It looks like your environment might be configured to look for and load .so files from whichever current directory you're in. Do you know if that might be the case?

If so, it's a super bad idea. Someone could perhaps, for example, put .so files in their /keybase/public directory that take over your machine when you cd into it.

I hope I'm not being too alarmist, but I'd actually encourage you to stop using KBFS until we figure out what's performing these lookups. Maybe it's something in your shell rc scripts?

**Comment by lyoshenka** [comment]
Looks like it was [gvm](https://github.com/moovweb/gvm). Not sure why it was doing this. I'll shut it off till I can figure out what's up. Thanks for the help.

**Comment by maxtaco** [comment]
Maybe you have `LD_LIBRARY_PATH` set to include `.`?

**Comment by lyoshenka** [comment]
Apparently, if you do something like `LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:${nonexistent_var}`, it will leave the path with a trailing semicolon, which will somehow cause the path to include `.`. Did not know that. Thanks for pointing me in the right direction.
