### ISSUE TITLE
Usability after update on server requires logout and login. Only running login does not work

### ISSUE THREAD

**Issue by sirishkumar** [keybase/client#2600]
I have updated keybase client on my server. Few issues I have observed 

- After update running cd to /keybase hangs forever.
- Currently every update requires user to log in again in all systems(windows, linux).  So when I ran "keybase login", nothing happens. Access to kbfs is possible only after running keybase logout and keybase login

This I consider only as usability issue for headless systems.

my log id: 71d061f1c543963f73bd041c

**Comment by maxtaco** [comment]
Does 'keybase unlock' work?

**Comment by sirishkumar** [comment]
When cd to keybase hangs, I didn't had the control of the terminal, Ctrl+C does not work, I had to close the terminal manually. 

I didn't tried running keybase unlock from another terminal session. In next update I can try running "keybase unlock".

**Comment by sirishkumar** [comment]
Resolving this, I no longer see this issue
