### ISSUE TITLE
TLS certificate appears to have expired 

### ISSUE THREAD

**Issue by mathieujobin** [keybase/client#26089]
I cannot send messages

Certificate for api-0.core.keybaseapi.com has expired on the 31st 16:42:33 UTC

**Comment by socketbox** [comment]
26088

**Comment by gene1wood** [comment]
Fixed in fbebbc9f1ba29e21ae6d3ee2edc21a7703d0019f

**Comment by apalmer27516** [comment]
For those of you eager to get this running again ASAP, I can confirm that it works to just download the latest client (6.2.3) source, swap out the "ca.go" file with updated certificate, and rebuild per the instructions in "go/README.md". Then shutdown Keybase from the GUI client, swap out the keybase binary, and restart with the GUI and it should work.

**Comment by cuiqg** [comment]
The ios app is still like this.
