### ISSUE TITLE
Failed to send a message. Api network error: Please check the error on the attached screenshot.

### ISSUE THREAD

**Issue by pythonguru101** [keybase/client#26092]
Keybase GUI Version: 6.2.3-20230928111529+eba57c1814

![image](https://github.com/keybase/client/assets/26586879/1e0ee665-9038-409c-a8d4-77090521e2c5)

**Comment by lleb** [comment]
same, on both android and iPhone.  the Android was semi-easy to address.  Had to manually search keybase in their app store.  there was a "hidden" not showing in my list of apps in need of update there.  Updated and poof it worked.  Sadly that is not an option for the iPhone.  This should be marked as high priority and addressed asap.

**Comment by dgem** [comment]
any news on this, seems like the expired cert was replaced by a self signed / untrusted ca
![IMG_6306](https://github.com/keybase/client/assets/630761/c06fce6a-881b-4cc0-abab-1feaadc555c9)

**Comment by sattekop** [comment]
Same issue here. I hope it can be solved.

**Comment by chrisnojima** [comment]
redownload the client from keybase.io
android is out and ios is submitted

**Comment by libbyw2008** [comment]
I have also encountered the same issue and hope it can be resolved soon.
Error code 1601

**Comment by davidpurdue** [comment]
There seems to be a problem with the certificate on the api site:
```
$ curl -kv https://api-0.core.keybaseapi.com/
*   Trying 54.145.238.238:443...
* Connected to api-0.core.keybaseapi.com (54.145.238.238) port 443
...
* Server certificate:
*  subject: CN=api-0.core.keybaseapi.com; O=Keybase; OU=Keybase LLC; L=NYC; ST=NY; C=US
*  start date: Dec 31 20:08:16 2023 GMT
*  expire date: Dec 30 20:08:16 2025 GMT
*  issuer: C=US; ST=NY; L=New York; O=Keybase LLC; OU=Cert Authority; CN=keybase.io/emailAddress=ca@keybase.io
*  SSL certificate verify result: unable to get local issuer certificate (20), continuing anyway.
```

**Comment by parithosh** [comment]
Re-downloading the client fixed the issue for me.

**Comment by LefterisJP** [comment]
yeah same here. Updating the package in archlinux worked.

**Comment by npdoty** [comment]
Can someone update the Keybase website and blog to note the failure condition and how to fix it? If every user needs to re-install their client, they'll need some prominent indications to do so.

**Comment by parithosh** [comment]
Can we also get some more clarity on what the change actually was? Seems like `curl -kv https://api-0.core.keybaseapi.com/` still returns an expired cert. Was there some reason the cert was just not renewed? Is there some info on the new CA being used?

**Comment by Mugane** [comment]
Same.

**Comment by joshblum** [comment]
Please update to the latest client. Thanks! 
https://x.com/KeybaseIO/status/1741990472560615473?s=20
