### ISSUE TITLE
Cannot login: "You are offline"

### ISSUE THREAD

**Issue by multiscan** [keybase/client#26096]
Keybase GUI Version: 6.2.4-20231019203304+5cfcf6b41e
macOS Monterey version 12.6.6

When I try to login into keybase, I keep getting the message "You are offline" (see screenshot below).
I can connect to the api.keybase.io therefore I am not off-line:

```
cangiani@GiovaMBP ~ % curl -k -I 'https://api.keybase.io/_/api/1.0/user/lookup.json?fields=basics%2Cpublic_keys%2Cpictures&multi=1&username=multiscan'
HTTP/1.1 200 OK
Date: Tue, 02 Jan 2024 15:03:47 GMT
Content-Type: application/json; charset=utf-8
Content-Length: 2930
...
```
Note that I had to use the `-k` option because the certificate is self-signed but this seams not to be the problem as for #2371

Is there something else I can check on my system ? I have already tried to reboot the system and reset my modem.

Thanks,

giovanni

<img width="118" alt="Screenshot 2024-01-02 at 15 56 44" src="https://github.com/keybase/client/assets/12849/155a6e18-2e78-4015-8c4b-f90a8d772a33">

**Comment by multiscan** [comment]
May be the certificate issue is different from the one of #2371 because I get an error message also if I try to use the keybase cli:
```
cangiani@GiovaMBP ~ % keybase login
▶ ERROR API network error: Get "https://api-0.core.keybaseapi.com/_/api/1.0/getsalt.json?email_or_username=multiscan&pdpka_login=1": x509: certificate signed by unknown authority (code 1601)
```

**Comment by multiscan** [comment]
I think you can merge this issue with #26092 sorry for not finding this out earlier.

**Comment by multiscan** [comment]
It actually works by manually downloading the latest binary version. You can definitely close this issue. Thanks.

**Comment by joshblum** [comment]
Please update to the latest client. Thanks! 
https://x.com/KeybaseIO/status/1741990472560615473?s=20
