### ISSUE TITLE
Cannot send chat messages on Windows client

### ISSUE THREAD

**Issue by jamisonj** [keybase/client#26103]
On the Windows client on Windows 11, I cannot send a message. I get this error:

```This messge failed to send. Api network error: get "http://api-0.core.keybaseapi.com/_/api/1.0/merkle/root.json?c=1&last=25285882&skip_last=1": x509: certificate signed by unknown authority. Retry or Cancel.```

**Comment by dschneiderch** [comment]
https://github.com/keybase/client/issues/26102#issuecomment-1874506305

**Comment by jamisonj** [comment]
Confirmed that this was resolved by re-installing from the website. See https://github.com/keybase/client/issues/26102#issuecomment-1874506305
