### ISSUE TITLE
Error on Kebase update - Ubuntu 22.04.

### ISSUE THREAD

**Issue by DiagonalArg** [keybase/client#26121]
Ubuntu 22.04.  New update.  I believe this was to fix the cert issue.  When restarting during update, /keybase doesn't exist, so we get the following error:

```
Setting up keybase (6.2.4-20240101011938.ae7e4a1c15) ...
Autorestarting Keybase via systemd for dev.
mkdir: cannot stat ‘/keybase’: Transport endpoint is not connected
chown: cannot access '/keybase': Transport endpoint is not connected
chmod: cannot access '/keybase': Transport endpoint is not connected
dpkg: error processing package keybase (--configure):
 installed keybase package post-installation script subprocess returned error exit status 1
Errors were encountered while processing:
 keybase
E: Sub-process /usr/bin/dpkg returned an error code (1)

```

**Comment by aolieman** [comment]
Also affects Ubuntu 23.10. It occasionally leaves dpkg hanging, but doesn't seem to cause any major issues in my case.

**Comment by perinm** [comment]
Duplicate of https://github.com/keybase/client/issues/25984

fix available at: https://github.com/keybase/client/issues/25984#issuecomment-1806824959

**Comment by DiagonalArg** [comment]
The problem has actually gone away for Ubuntu 22.04 without my intervention.  I'm not sure if @aolieman had the same experience, but I'll close this error report.

**Comment by DiagonalArg** [comment]
The problem has actually gone away for Ubuntu 22.04 without my intervention.  I'm not sure if @aolieman had the same experience, but I'll close this error report.

**Comment by aolieman** [comment]
Indeed, I had the same experience. The transport endpoint error was resolved (I believe in a subsequent release).
