### ISSUE TITLE
Windows Error "File is in use by another application or user"

### ISSUE THREAD

**Issue by sirishkumar** [keybase/client#2613]
I have downloaded a document from my mail client to keybase private folder. When I tried opening the file I get below error. There is no other application accessing this file(Checked it using process explorer ). I tried copying the file to another folder in keybase, I still see the same problem. I was able to open the file after copying the file to local storage from keybase.

![fileopenedbyotheruser](https://cloud.githubusercontent.com/assets/27522/14520416/b369e134-0224-11e6-861e-59d532ec7150.png)

my log id: 488fd13c7f4a461eded77e1c and
397e4d68bad4a1c97350661c(Uploaded using keybase log send -n 1000000 as earlier I had issues uploading huge files and it failed silently in the background)

**Comment by strib** [comment]
@taruti?

**Comment by sirishkumar** [comment]
I did not see this error again. Closing it
