### ISSUE TITLE
Build problem: `cannot find package ... in any of ...  (from $GOROOT) ...  (from $GOPATH)`

### ISSUE THREAD

**Issue by ar-jan** [keybase/client#26144]
I'm trying to bump Keybase version packaged for Void Linux since it's broken due to the certificate problem.

I run into problems with various packages that can't be found:

> cannot find package "github.com/btcsuite/btcutil/bech32" in any of:
> 	/usr/lib/go/src/github.com/btcsuite/btcutil/bech32 (from $GOROOT)
> 	/builddir/keybase-6.2.4/src/github.com/btcsuite/btcutil/bech32 (from $GOPATH)
> ...
> cannot find package "github.com/stellar/go/build" in any of:
> 	/usr/lib/go/src/github.com/stellar/go/build (from $GOROOT)
> 	/builddir/keybase-6.2.4/src/github.com/stellar/go/build (from $GOPATH)
> github.com/asaskevich/govalidator (download)
> github.com/manucorporat/sse (download)
> github.com/segmentio/go-loggly (download)
> github.com/BurntSushi/toml (download)
> cannot find package "github.com/stellar/go/clients/horizon" in any of:
> 	/usr/lib/go/src/github.com/stellar/go/clients/horizon (from $GOROOT)
> 	/builddir/keybase-6.2.4/src/github.com/stellar/go/clients/horizon (from $GOPATH)
> ...
> github.com/blevesearch/vellum (download)
> github.com/blevesearch/zapx (download)
> cannot find package "github.com/blevesearch/zapx/v11" in any of:
>         /usr/lib/go/src/github.com/blevesearch/zapx/v11 (from $GOROOT)
>         /builddir/keybase-6.2.4/src/github.com/blevesearch/zapx/v11 (from $GOPATH)
> cannot find package "github.com/blevesearch/zapx/v12" in any of:
>         /usr/lib/go/src/github.com/blevesearch/zapx/v12 (from $GOROOT)
>         /builddir/keybase-6.2.4/src/github.com/blevesearch/zapx/v12 (from $GOPATH)
> cannot find package "github.com/blevesearch/zapx/v13" in any of:
>         /usr/lib/go/src/github.com/blevesearch/zapx/v13 (from $GOROOT)
>         /builddir/keybase-6.2.4/src/github.com/blevesearch/zapx/v13 (from $GOPATH)
> cannot find package "github.com/blevesearch/zapx/v14" in any of:
>         /usr/lib/go/src/github.com/blevesearch/zapx/v14 (from $GOROOT)
>         /builddir/keybase-6.2.4/src/github.com/blevesearch/zapx/v14 (from $GOPATH)
> cannot find package "github.com/blevesearch/zapx/v15" in any of:
>         /usr/lib/go/src/github.com/blevesearch/zapx/v15 (from $GOROOT)
>         /builddir/keybase-6.2.4/src/github.com/blevesearch/zapx/v15 (from $GOPATH)
> ...
> cannot find package "github.com/blevesearch/bleve/index/store" in any of:
>         /usr/lib/go/src/github.com/blevesearch/bleve/index/store (from $GOROOT)
>         /builddir/keybase-6.2.4/src/github.com/blevesearch/bleve/index/store (from $GOPATH)

Seems it may have something to do with having to use go modules? I don't know anything about packaging Go, any pointers?

**Comment by lee2sman** [comment]
Hi @ar-jan this was completed and merged. Try updating or reinstalling from the Void repos. This issue can thankfully be closed.
