### ISSUE TITLE
keybase.pub: kbfs web server is offline

### ISSUE THREAD

**Issue by i8degrees** [keybase/client#2616]
Good morning there,

Just to let you know, the Keybase.pub web server is reporting: 

**Not Found**
Sorry, but that file path is not legit. Jump back to the Keybase.pub site.

when trying to access user pages, i.e.: https://keybase.pub/i8degrees/

This has been happening for a friend and myself anytime we try to access user pages via the web at keybase.pub. This service has been down since April 14, 2016 at **roughly** 01:24 CST, AKA -06:00 GMT.

The main index at keybase.pub is still up. Also, the back-end storage, **kbfs** and its /Keybase filesystem is still responsive and appears to be fine.

Cheers,
Jeffrey Carpenter <i8degrees@gmail.com>

**Comment by cjb** [comment]
@i8degrees Thanks!  It's fixed now.

@strib Log send '5e9a58e915d22262d08b4a1c' -- it seems that the Linux kbfsfuse process died silently, it wasn't running.
