### ISSUE TITLE
Getting ERROR bad session: server rejected session; is your device revoked? on all devices

### ISSUE THREAD

**Issue by mikebryant** [keybase/client#26164]
Haven't revoked any devices etc - all are failing

Unable to provision a new device with a paper key - same error

Log ID is `bae651ef689e848671d6ea1c`

**Comment by mikebryant** [comment]
Same issue with logging into keybase.io - `Unknown error: BAD_SESSION / Failure in verify PDPKA5`

I know the passphrase is correct, because if I use some random password I get - `Incorrect password. Fix it or [reset your password](https://keybase.io/#). You might need to set one in the app if you haven’t already.`

@chrisnojima @joshblum are you able to look into this? This seems [to have happened](https://github.com/keybase/client/issues?q=is%3Aissue+is%3Aopen+bad+session) to many people, with no resolution. In the current state, feels like everyone should get off keybase as a matter of urgency before all their data is made inaccessible too

**Comment by mathieujobin** [comment]
This is very problematic for me.

My account is broken on all devices... What happened... Seems to have happened around 6.4.0 release 

Or Maybe because I have recharged my old iphone with an old version of keybase on it ? Note the phone still run iOS 12.5.5

Now everything is broken ...

Please help

**Comment by mathieujobin** [comment]
Looks like someone reported our accounts... For whatever reason 

And without much checks, our accounts got banned from using Keybase 

Which is stupid, in my case, it's the reporter who was trying to scam me...

**Comment by mathieujobin** [comment]
I am unblocked 

Thank you so much 🙏

**Comment by mikebryant** [comment]
@mathieujobin How did you get unblocked? I've been stuck like this for months - and just tried again, still won't work

**Comment by mikebryant** [comment]
I've had my account restored, thank you :)

**Comment by TheonlyLMR** [comment]
I too am having this issue, can you provide any more information on how you got your account restored?
