### ISSUE TITLE
Disabled wallet without making ID available 

### ISSUE THREAD

**Issue by trailstrider** [keybase/client#26230]
See picture.  Cannot get full ID for wallet.   Key copy works, but unable to get the entirety of the id.  It’s truncated, and no way to select the remainder. 

![IMG_1001](https://github.com/keybase/client/assets/710843/6aab475d-9820-4c9e-b075-15a140d77a54)

Sad that the wallet function is on its way out.  😢

**Comment by chrisnojima** [comment]
https://github.com/keybase/client/pull/26255
