### ISSUE TITLE
Windows : Downloading file directly to keybase failed

### ISSUE THREAD

**Issue by sirishkumar** [keybase/client#2624]
I tried downloading a file from a website directly to keybase, it failed. After this error keybase drive is inaccessible, I was able to access before this issue occurred. 

Before saving the file I created the folder to which I intended to save the file directly from the File Save as window.

![windowerror](https://cloud.githubusercontent.com/assets/27522/14561584/8777d84e-0317-11e6-8211-78276c282977.png)

Attached logfiles are before the keybase drive became inaccessible and after the error occurred. I was unable to upload log file again after drive became inaccessible.

```
- ERROR API network error: Post https://api.keybase.io/_/api/1.0/logdump/send.js
on: net/http: request canceled

```
my log id: 9d1f538552c7d1d0d26c161c

**Comment by zanderz** [comment]
cc @taruti

**Comment by taruti** [comment]
Writes end up blocked because of too many dirty bytes.

**Comment by sirishkumar** [comment]
When I tailed the logs, it felt like something was running in infinite loop as the logs never stop. And there was no other activity other than saving this particular file

**Comment by sirishkumar** [comment]
This works now,  you can close this if this was addressed by some fix
