### ISSUE TITLE
Gui and chat work but git clone or push fails with cert errors

### ISSUE THREAD

**Issue by spearman** [keybase/client#26245]
Trying to clone or push a git repository gives `git-remote-keybase error: (1) x509: certificate signed by unknown authority`.  This is keybase 6.2.4. The GUI and chat works fine. Trying to view contents of git repositories in the GUI also fails.

There is a warning output from `keybase service`:

```
$ keybase service
▶ INFO | net.Listen on unix:/run/user/1000/keybase/keybased.sock
▶ WARNING {unix://@} Reply error for 9: EOF
```

**Comment by kopiczko** [comment]
Possibly a dupe of https://github.com/keybase/client/issues/26241

**Comment by spearman** [comment]
Seems to have been resolved
