### ISSUE TITLE
Mac app tray icon is always dark 

### ISSUE THREAD

**Issue by sandipndev** [keybase/client#26263]
<img width="208" alt="Screenshot 2024-02-21 at 10 47 55 AM" src="https://github.com/keybase/client/assets/40622610/c904ba12-d2b1-48c5-84a1-0009496c8af8">

It looks weird when the background is light and the icon is light as well. Many people might be using something which has light background.

**Comment by chrisnojima** [comment]
this is fixed in 6.3, out in a bit

**Comment by oerp-odoo** [comment]
I have the opposite problem, when there is notification, it looks like keybase icon becomes dark and I actually can't see it anymore on Linux/Ubuntu:

![Selection_1431](https://github.com/user-attachments/assets/561a6107-b1a2-4c6c-a59d-7f1c6c735a7a)

You can barely see the icon on dark bar.. If there are no notifications, then I can see it normally:

![Selection_1432](https://github.com/user-attachments/assets/c8153484-d814-4bc9-a1e1-0b4ad0b77eff)
