### ISSUE TITLE
Keybase is gone?

### ISSUE THREAD

**Issue by jasonkarns** [keybase/client#26351]
Keybase app on macOS Sonoma (14.4) seems broken.

<img width="984" alt="image" src="https://github.com/keybase/client/assets/119972/5164a521-bb69-4f4e-93f3-b1a924428968">

Fails on tabs: People, Teams, Git, Devices, and Settings.

The error details indicate failure to hit keybaseapi.com (can't copy the error message because someone decided this shouldn't be rendered using a simple text control)

Regardless, keybaseapi.com seems to be down which is probably what's breaking the app. 

<img width="651" alt="image" src="https://github.com/keybase/client/assets/119972/3889293d-c2b2-454e-b31b-61b7d94cf89d">

<img width="611" alt="image" src="https://github.com/keybase/client/assets/119972/532a275e-4f67-4aea-aad0-2256cfefe2e0">

**Comment by songgao** [comment]
@jasonkarns We’re still up! Sorry for then inconvenience — there was a x509 related issue that we couldn’t fix with an auto update. But the newest clients have the fix. If you download and install a client from http://keybase.io it should start working again.
