### ISSUE TITLE
Error: disk is full 

### ISSUE THREAD

**Issue by texastoland** [keybase/client#2654]
Keybase GUI Version: 1.0.15-20160412203450+95be805

I can't copy a 61 KB PDF into my public folder. I consistently receive the message `The operation can't be completed because the disk is full` disconcertingly leaving a 0 KB file. I was able to get a bunch synced last night using Forklift. Any tricks?

**Comment by strib** [comment]
Hmm, we don't actually enforce quotas right now, so this may be a local issue.  but I've never seen it before.  Would you mind sharing your logs with `keybase log send`, and reporting the log ID here, so we can take a look?

**Comment by AppShipIt** [comment]
my log id: c470650b9bc238d9ec8f421c

**Comment by strib** [comment]
The only error I can find in your log is a timeout error when your client was performing a ton of writes, which is currently expected under certain bulk write/copy conditions.  That would indeed leave a 0-byte file.  My best guess is that whatever program you were using for copying files (forklift?) misintepreted the error code we sent (for timeouts, we send an "I/O error" error code, usually) and showed you a misleading error message.

Until we get around to fixing bulk write performance, you should just be able to retry failures like that.  Sorry for the inconvenience.

**Comment by AppShipIt** [comment]
It was actually Finder that produced that message. I also attempted it with both Forklift and their GUI for rsync with different errors regarding timeouts. I'm literally trying to write a single 61 KB PDF 😓

**Comment by strib** [comment]
It's still happening consistently?

**Comment by AppShipIt** [comment]
It was as of this morning but I just attempted [successfully](https://keybase.pub/appshipit/Resumes/Resume-Toland.pdf). I deleted the empty ones first and copied each of two one at a time in Finder.

**Comment by strib** [comment]
Hmm, this morning in your logs I'm seeing a lot of internet connectivity errors trying to reach our servers.  As far as I know we didn't have downtime.  I wonder if the other failures were just general network crankiness?

**Comment by AppShipIt** [comment]
That was my feel. I'd be beyond glad to provide any information possible! I love the service except for that sticking point.

**Comment by strib** [comment]
Well if you happen to know exactly what time (by your computer's local clock) you encountered each of the various errors, that would be helpful.  You can also check the OSX notification center to see what Keybase popup notifications you received.

**Comment by AppShipIt** [comment]
Checking Console but I've cleared NC since then.

**Comment by strib** [comment]
Ok, well keep an eye on it please.  If it happens again let us know and send in new logs.  But yeah, timeouts during bad network conditions or during bulk write/copies are known and will be fixed someday.  Sorry for the frustration in the meantime.

**Comment by strib** [comment]
Version 1.0.20 has architectural changes that should greatly improve the large write experience.  If you're still seeing problems, please open a new issue.
