### ISSUE TITLE
Please enter the passphrase to unlock the secret key for: Device "mydevice"

### ISSUE THREAD

**Issue by patricklucas** [keybase/client#2659]
I get the above message when I try to issue a tracking request, but I can't figure out which passphrase it's asking me for. It's neither of my user passphrase or paper key, so what is it? Is it something I have to use another device to generate?

```
$ keybase track <someone>
▶ INFO Generating tracking statement for <someone>
✔ public key fingerprint: ABCD ...
✔ "<someone>" on github: https://gist.github.com/<1234567> [cached 2016-04-21 11:36:15 EDT]
Publicly write tracking statement to server? [y/N] y
```

At this point a dialog appears with the above message.

```
▶ ERROR GETPIN response didn't start with D; got "ERR 83886179 Operation cancelled <Pinentry>"
```

**Comment by patricklucas** [comment]
On another device, I attempted the same action, and it accepted my user passphrase.

**Comment by patrickxb** [comment]
It looks like you are using an odd pinentry application on the device that is giving the error.

**Comment by patricklucas** [comment]
I don't think so. I tried unsetting DISPLAY, and the error as printed to the terminal is now:

```
▶ ERROR Failed to unlock key; bad passphrase
```

I _am_ running the Ubuntu 16.04, newly released today, but it doesn't seem like that should affect this.

**Comment by patricklucas** [comment]
In lieu of a response here, I'm going to just delete/re-add the device.

It's a shame Keybase doesn't allow you to re-use a device name even if you've fully expunged it from your account. Annoying to have to add a serial number to all my device names.

**Comment by eau-u4f** [comment]
Sounds similar.

I am trying to remove those keys that keybase has added "paperkey" and "device" keys.
both of them are asking some "passphrase" to be removed, I have NO IDEA what that passphrase should be since my gpg key passphrase does not work.

What is happening?! what are those references/keys if I cannot control them from my GPG key ultimately.

I just wanted to see how keybase GPG wrapper could be useful and the encryption etc... and it created all those keys few months ago (when I did not ask to)

this is what I am using:

VERSION:
   1.0.5-6

**Comment by maxtaco** [comment]
Super old version, can you upgrade?

**Comment by patricklucas** [comment]
This has started happening on another of my devices too.

When I try to track someone, it prompts:

```
Please enter the passphrase to unlock the secret key for:
Device "antares 1"

Reason: tracking signature:
```

It does not accept my account passphrase, so I'm not sure what it's asking for here. This time I'm using the latest Windows client.

**Comment by patricklucas** [comment]
cc @patrickxb since you replied initially and this issue is no longer on the first page.

**Comment by maxtaco** [comment]
@patricklucas you are 100% certain that the same passphrase that works on machine A isn't working on machine B?  Certainly it's our intention that the same passphrase works in both places, there could be a bug with the system though, but it's impossible for us to reproduce.

Have you recently changed your passphrase?

Did your passphrase previously work on machine B and then it stopped working on machine B?

**Comment by patricklucas** [comment]
Apologies for the delay, I finally got around to trying this again.

And it doesn't reproduce. I'm mystified: I tried repeatedly, confirming four or five times that the passphrase was correct.

Perhaps there's some transient issue that cause both the original problem and this one? I don't know. I'll reopen if it happens again.

**Comment by covertress** [comment]
Your desired username: covertress
A public name for this device [home computer]: Dominator
▶ ERROR GETPIN response didn't start with D; got "ERR 83886179 Operation cancelled <Pinentry>"

**Comment by maxtaco** [comment]
Hi @covertress can you try a `keybase log send` from the CLI?

Thank you!

**Comment by covertress** [comment]
Hi @maxtaco 
------------
Success! Your log ID is:

  30dbbe6926e899a76af9831c

Here's a URL to submit new bug reports containing this ID:

  https://github.com/keybase/client/issues/new?body=[write%20something%20useful%20and%20descriptive%20here]%0A%0Amy%20log%20id:%2030dbbe6926e899a76af9831c

Thanks!
------------
P.S. I can break anything! xD

**Comment by maxtaco** [comment]
@patrickxb can you check out this one?  

there's a known bug that we're not handling newer versions of pinentry and how they cancel input, but the two other questions are: (1) why was input canceled; and (2) why was pinentry being used in the first place?
