### ISSUE TITLE
client asks for paper key about 15 times or so

### ISSUE THREAD

**Issue by benaryorg** [keybase/client#2677]
Yes, I clicked cancel and the pinentry window reopened more than ten times or so (keybase version 1.0.15)

This is just wrong.

Related to #2674

**Comment by maxtaco** [comment]
Can you provide us some useful debugging information. What did the pinentry show? 

It sounds like a bug, but we'll need more info to debug and fix it.  If you care to, you can `keybase log send`, that will help us greatly

**Comment by benaryorg** [comment]
`keybase login` if I choose to use the paper key.

**Comment by patrickxb** [comment]
Hi @benaryorg, I tried to reproduce your issue using `keybase login` and when I selected a paper key and then canceled the pinentry window, the pinentry window did not reopen.  I tried several different flows but cancel worked every time.

Could you help us track this down by reproducing it and then running `keybase log send` to upload your recent log files?  That will also send the result of `keybase status` which will help us see the exact version you are using.

Thank you very much.
