### ISSUE TITLE
Windows - Two private folders with same content

### ISSUE THREAD

**Issue by sirishkumar** [keybase/client#2681]
Keybase GUI Version: 1.0.15-20160413083549+d37acc1

Today I observed two private folders of mine with same content but different names

![two_folders](https://cloud.githubusercontent.com/assets/27522/14778587/18318632-0ad4-11e6-839a-6e74e762c117.png)

Logid :  2c814a99c417bca243a8341c

**Comment by strib** [comment]
Hi @sirishkumar, how did you get to the first one? Did you type that in or follow a link from somewhere?  It is intentional that the uid name resolves to the same folder as your keybase username (it is the same thing as `foo@twitter` resolving to the corresponding keybase user name), but you should never see that first name under `/keybase/private/`.

**Comment by sirishkumar** [comment]
@strib Folder was present under k:/private and I can see the same in under linux

**Comment by strib** [comment]
Hrmm.  @oconnor663 can we check if @sirishkumar's favorites list includes a weird uid string?  Or it could be a libdokan issue I guess.  @taruti?  Aliases aren't supposed to show up in the folderlist contents, right?

**Comment by taruti** [comment]
@strib, libdokan uses EmptyFolders like libfuse did a few months ago, this is related to KBFS-971. I'll try to get a fix out today.

**Comment by oconnor663** [comment]
@strib Sirish's favorites list does in fact include a weird private TLF: `a34ae1625e08c1eb95afd64a62515100@uid`.

**Comment by strib** [comment]
Whoa, thanks @oconnor663.  Can we nuke entry that for now?  It's probably from a libdokan bug that @taruti is looking at now.

**Comment by oconnor663** [comment]
I see 11 users with ___@uid favorites, including @strib, @akalin, and @malgorithms. Should we delete all of them?

**Comment by strib** [comment]
Super weird.  Do you happen to have ctimes for those?  I think they're safe to nuke, but I'm wondering if they've been created lately or due to some really old bug.

**Comment by oconnor663** [comment]
posted at https://keybase.atlassian.net/browse/KBFS-1005

**Comment by strib** [comment]
We deleted the weird uid favorites, and have a theory about why they happened (from a bug that has since been fixed).  So @sirishkumar you shouldn't have that favorite anymore, and for new releases it shouldn't be possible to get into that state again.
