### ISSUE TITLE
Write timeout

### ISSUE THREAD

**Issue by RickyB98** [keybase/client#2682]
This might be a duplicate. This morning, I couldn't upload a PDF file, even though it was not that big (3,3 MB). My connection is very poor in terms of upload speed - this poor: http://www.speedtest.net/my-result/5276875586 - so it might be that timeouts are too short. However, despite it being poor, it is not unstable, so it shouldn't drop when uploading.

Regards,
Riccardo Bello

my log id: 4fd267f509808ffbda477b1c

**Comment by strib** [comment]
Yep, this is a known issue covered elsewhere (e.g. #1981).  We still have to work to do to get bulk data uploads (> 5 MB) working reliably.  We're hoping to getto it soon.  Thanks for the report!  Closing as a dup.
