### ISSUE TITLE
Some sort of error via Notification

### ISSUE THREAD

**Issue by CameronBanga** [keybase/client#2683]
Didn't catch the exact error, something maybe about an action taking too long. But got an error notification that asked me to send a log to the team, so following up here.

my log id: 240b9e865a745c96e68d711c

**Comment by strib** [comment]
Hi @CameronBanga -- looks like you had a few timeout errors trying to read a public directory, and then a "502 Bad Gateway" error.  This was shortly after a restart, so I'm guessing there was a temporary network hiccup somewhere.

Are you still having issues reading folders?  If not, we can probably close this out.

**Comment by CameronBanga** [comment]
Nope, no issues, I'll close out. Didn't catch all of the alert, tried to tap on it for more info, but went away and just saw "File a notification." 

If anything seems off, I'll reopen!
