### ISSUE TITLE
Reddit fails to verify and any attempts to solve it on my end fail

### ISSUE THREAD

**Issue by nathanpalmer** [keybase/client#26948]
Hello,

I started getting emails from Keybase saying my reddit proof was failing. I tried to solve it myself by having keybase recreate the proof 2 days ago. That still didn't solve it. My post is here:

https://www.reddit.com/r/KeybaseProofs/comments/1d5b5ze/my_keybase_proof_redditnatepalmer/

Not sure what else can be done on my end though.

**Comment by VRHamilton** [comment]
I have this problem, too.

**Comment by NoSubstitute** [comment]
reddit proof suddenly reported as working again.

**Comment by nathanpalmer** [comment]
Yup, just started working again. Nothing changed on my end.
