### ISSUE TITLE
Getting a black blank screen when logging in.

### ISSUE THREAD

**Issue by doodlemania2** [keybase/client#2702]
Keybase GUI Version: 1.0.15-20160413083549+d37acc1

![image](https://cloud.githubusercontent.com/assets/5252217/14829874/5d921c0c-0bb3-11e6-8aaf-91657ceb8140.png)

causes cmd prmpt to fail also:
![image](https://cloud.githubusercontent.com/assets/5252217/14829882/6ae8e2d2-0bb3-11e6-83e7-05273cf1fbcd.png)

**Comment by doodlemania2** [comment]
That's funny - when I pasted the image it seemed to work but the screen on my monitor is solid black!

**Comment by doodlemania2** [comment]
Was able to do some screen scraping to get successfully logged in but then it shows me logged out almost as soon as I click close on the UI screen: 
![image](https://cloud.githubusercontent.com/assets/5252217/14830027/301889f4-0bb4-11e6-863a-fd1050c403a2.png)

**Comment by doodlemania2** [comment]
FYI - This is Win10 Build 14328 :)

**Comment by zanderz** [comment]
Hi, we are working on a number of issues with our Windows filesystem alpha. The best thing would be to hold tight until we have worked some of these out. Second best might be to exit the gui and continue signing in with the command line. Don't forget, after logging in you may have to also issue the `keybase unlock` command for the filesystem to work. You can tell the status with the `keybase status` command.

**Comment by doodlemania2** [comment]
Thank ya sir! Had some "similar" troubles on Ubuntu a bit ago thought might be related. After logging in and registering the new device, it said I was logged in, but then I wasn't. Restarted (run_keybase) and it cleared up. Not sure if related, just passing along. All good from Linux land now.

**Comment by MarcoPolo** [comment]
Fixed here: https://github.com/keybase/client/pull/2707

Thanks!
