### ISSUE TITLE
Windows client no longer available for download

### ISSUE THREAD

**Issue by toddself** [keybase/client#2734]
Just booted into an old windows partition and wanted to grab some files from my kbfs but the download page no longer links to a windows installer?

Has windows been pulled from the beta?  Should we remove existing Windows clients?

**Comment by toddself** [comment]
FYI I've been using this to shuttle data between linux, mac os & windows for a few months now and it's really, really great!

**Comment by zanderz** [comment]
We had some critical issues come up which combined in ways alarming enough to pause production. We are nearly done working them out and will put it back up very soon, maybe even this evening. I'll make sure you're among the first to know. Thanks for the feedback!

**Comment by maxtaco** [comment]
We did not discover any security vulnerabilities in the windows release, it's important to note. The effects of the bugs were that the product just didn't initialize properly, and because useless after the failure.

**Comment by toddself** [comment]
Literally going to be my next question! Thanks again for the awesome software.

**Comment by zanderz** [comment]
Improved Windows version is available, please check it out!
