### ISSUE TITLE
cannot open directory .: Input/output error

### ISSUE THREAD

**Issue by donaldedgar** [keybase/client#2737]
I can currently access private folders shared with someone else, and my public folders, but if I try and move/copy/create anything in my private folder I get: `cannot open directory .: Input/output error`. This is happenening on two different computers, both of which are Linux. I can open the folder, but that's as far as it'll let me go. 

my log id: f68a122b1b89c558bab48f1c

**Comment by cjb** [comment]
@strib `Verify result for 1466-byte message with SignatureInfo [..]: Verification failed`

@donaldedgar Did you revoke any devices?

**Comment by strib** [comment]
@cjb: there were revokes, but he's running a bleeding edge update that should be able to handle signatures from revoked keys that were valid at the time.

I wonder if this is another instance of https://github.com/keybase/client/issues/2432#issuecomment-200540492 -- in that case, a bug in our code (from a version in march) could make the folder unverifiable when you provision a device via pgp key, and then use your paper key to access your KBFS folders.  Looks like you might have done this the first time you provisioned `SparkyBox`.  I'm going to look at some stuff on our servers to try to verify.

If that ends up being it, we'll have to undo a couple of revisions for that folder with your signed permission. Shouldn't lose any data.  I'll let you know when we figure it out.

**Comment by strib** [comment]
We confirmed that this is the same bug.  The folder was last written in March, by a buggy version of KBFS.  Sorry about that!  We'll revert the folder to a version that works, but we need your signed permission.  Please run the following command on one of your devices, and substitute the current date and time as indicated:

```
keybase sign -m "<DATE_AND_TIME>: Please revert folder /keybase/private/donaldedgar to a correctly-signed revision.
```

And post the output here publicly.  Sorry about the inconvenience!

**Comment by donaldedgar** [comment]
@strib No worries about the inconvenience! It's part of the alpha testing, no?

```
BEGIN KEYBASE SALTPACK SIGNED MESSAGE. kXR7VktZdyH7rvq v5wcIkHbs7trawm qnxfBIKz2UWqjLw yHtE2sI9cQOuWES udyF7tMayHBO8uK YCcgo8aaHhGRLxN FTZPuuV9yBlMSr8 rfOH34HcnUemXF0 Lqs60AWsQ3yakr7 KdH8a4loReMsu3B TFnIN5l3FbHMiOf vY20iGT8Fcr3hGV Tt9NyVAvAVTAf8v Dtyx6st6TKnMbcN qZ9CVNym8qHJ0YX l68W6WVrapvq1D2 QtjadxJA9TL7fUZ ne9BElYxcwf74P2 uZrmdIy4LoCmqTv G9Tu7pp5F96Cax3 eO2f7whw9PK5vwI YOfSyQat8xW6NXw pyeuaChzeUy5Fiw Z7xe7aGCaerR1Tf AS1wGTS4QEmAU3n 9RhvYdR9CzwTIWO P5BOEMZK4lAyJUe m4twu. END KEYBASE SALTPACK SIGNED MESSAGE.
```

Thanks for your help on this!

**Comment by strib** [comment]
@donaldedgar awesome thanks for understanding.  Ok, we've removed the problematic revision from that folder.  Try accessing it again after restarting kbfs from one of your devices that already had access to it. If you use a device that hasn't yet had access to the folder, it may tell you to turn on one of your other devices, and if you don't after 10 minutes it should prompt you for your paper key.

Let me know how it goes!

**Comment by donaldedgar** [comment]
@strib Saw a prompt on my computer before seeing your response, so I did eventually have to enter my paper key. At any rate, I was able to successfully save a file to my private drive both via the command prompt and the file manager, so I think it's working again.

Thanks for your help!
