### ISSUE TITLE
Copying file into keybase filesystem failed

### ISSUE THREAD

**Issue by simonyangme** [keybase/client#2740]
Trying to copy a file into keybase filesystem failed:

```
% cp ~/SomeLocation/pen_and_paper.jpg /keybase/public/simonyang
cp: ./pen_and_paper.jpg: Input/output error
%
```

my log id: 2e4b22c4551d513b9a29fa1c

**Comment by strib** [comment]
Thanks for the report.  This is known problem -- on OSX, when you're writing more than 5MB at once and your network connection to our servers is a bit slow, the operation can timeout.  (If you're running the Keybase UI, there should have been a popup notification mentioning this.)

We definitely plan to improve performance in future versions.  In the meantime, try the `cp` again?

**Comment by simonyangme** [comment]
Ah, was on slow wifi. Will give it a shot later with a better connection.

**Comment by simonyangme** [comment]
Uploaded successfully with a better internet connection.

**Comment by OJFord** [comment]
I'm seeing the same with a solid connection, and only tens of bytes. (In fact, even `touch` times out.)

**Comment by strib** [comment]
@OJFord feel free to open a new issue and include logs with `keybase log send`.  Sounds like a different issue to me.
