### ISSUE TITLE
Keybase client (macOS) always turns on Open Automatically at Login (no way to disable for users that don't want that)

### ISSUE THREAD

**Issue by wls** [keybase/client#27581]
I'm using macOS and when I run KeyBase, I get a message from Settings:

Login Item Added
"Keybase.app" will open automatically when you log in.
You can manage this in Login Items Settings.

I shut down KeyBase, remove the item from Login Item's list of apps to open, and again the next time I use KeyBase, it readds this.

It doesn't ask.  It doesn't warn.  It just does.  And there is no way to tell it that I really know what I'm doing, and I understand the consequences.  It should honor a user's preferences the way it honors their privacy.

PROBLEM:  There is no setting in KeyBase's Settings to enable/disable the Open at Login.

EXAMPLE:  Dropbox has a Preferences screen that has a toggle for Open Dropbox upon startup.  (It's being polite and respectful of end-user needs.)

SOLUTION: Add a similar toggle.

**Comment by kg4zow** [comment]
In the Keybase client, go to "Settings &#x2192; Advanced &#x2192; Open Keybase on startup" and turn the checkbox off there.

If System Preferences is open to the "General &#x2192; Login Items" page, you will see it adding and removing "Keybase.app" from the list when you turn the checkbox on and off.

**Comment by wls** [comment]
( I swear I looked multiple times before submitting this.  Found the Open Keybase on Startup checkbox and unchecked it. Thank you.
