### ISSUE TITLE
Copying file off KBFS throws timeout error

### ISSUE THREAD

**Issue by zph** [keybase/client#2772]
Copying 85MB file off of KBFS throws a timeout error. 

ie
`mv /keybase/private/me,someone_else/sample.tar.gz ~/downloads/`

More details in the following logs:

my log id: 1a1b7e94e0d4ab45f6407e1c

Let me know if I can provide additional info :D.

**Comment by strib** [comment]
Hi @zph -- this is a known issue on OSX in our buffering logic when the file is > 5 MB.  Sorry for the inconvenience -- we're planning to fix it in future releases (on the order of a couple months from now).

For now my best advice is just to try again -- eventually it might work, depending on your network connection!

**Comment by zph** [comment]
Awesome.

Thanks for the response and info. I tried it again and it was eventually copied :).

**Comment by strib** [comment]
For the record, I misread your description at first and thought you were writing a file.  Now I see you were actually trying to read a file -- it looks like your kernel did a read of `4194304` bytes at once, and your network (or are servers) wasn't fast enough to download that before the 19-second OSX timeout kicked in.

We can certainly be smarter about this and return less data that the kernel asked for if we've been waiting too long.  I'll make an internal issue for this.  Thanks for the report!

**Comment by zph** [comment]
Awesome, thanks for taking a deeper look at it :).

Great work and keep it up!

**Comment by taruti** [comment]
This should be fixed by https://github.com/keybase/kbfs/pull/63 which will be soonish in a release.

Please reopen if this occurs in a release with the fix.

**Comment by zph** [comment]
Thank you for the follow up :D.

Keep up the good work!
