### ISSUE TITLE
kbfs users on keybase.pub not found

### ISSUE THREAD

**Issue by paulhugel** [keybase/client#2775]
Do not see any of the user sites working 
error: URL's  for users  keybase.pub returned text  "not found"

paul$ keybase unlock

keybase log send

Continue sending logs to keybase.io? (type 'YES' to confirm): YES
▶ WARNING error opening log "/Users/paul/Library/Logs/keybase.updater.log": open /Users/paul/Library/Logs/keybase.updater.log: no such file or directory

------------
Success! Your log ID is:

  b9cde1327846cd229f19f31c

Here's a URL to submit new bug reports containing this ID:

  https://github.com/keybase/client/issues/new?body=[write%20something%20useful%20and%20descriptive%20here]%0A%0Amy%20log%20id:%20b9cde1327846cd229f19f31c

Thanks!
------------

Pauls-MacBook-Air:~ paul$ keybase update check
▶ INFO Checking for update, current version is 1.0.15-20160503130017+9e2ad3e
▶ INFO Using updater source: Remote (https://s3.amazonaws.com/prerelease.keybase.io)
▶ INFO Request "https://s3.amazonaws.com/prerelease.keybase.io/update-darwin-prod.json"
▶ INFO Checking update with version: 1.0.15-20160503130017+9e2ad3e
▶ INFO Update matches current version: 1.0.15-20160503130017+9e2ad3e = 1.0.15-20160503130017+9e2ad3e
Pauls-MacBook-Air:~ paul$ keybase update check-in-use
▶ WARNING Continuing despite error in lsof: Error running /usr/sbin/lsof [-w -F pcuftn /keybase]: exit status 1 ()

my log id: b9cde1327846cd229f19f31c

**Comment by cjb** [comment]
Thanks, fixed now.  Log send: 069221e9bc1c617a7c17b81c

Looks like the kbfsfuse process just disappeared on the server.  Nothing in dmesg or keybase.kbfs.log to suggest why.

**Comment by paulhugel** [comment]
Mahalo cjb
