### ISSUE TITLE
KBFS-/keybase/private/[username] was modified by a revoked or bad device

### ISSUE THREAD

**Issue by chrisse-m** [keybase/client#2780]
Hey, after I installed Ubuntu 16.04 and opened my KBFS-Private Folder I got this error message:
`keybase/private/[username] was modified by a revoked or bad device`

-chris
my log id: ba0596ef52b4066f4c2f811c

**Comment by strib** [comment]
Looks like you reset your Keybase account/sigchain on 5/1?  That means whatever data you had in your private folder before then is lost.  It looks like your public folder is in the same boat.  We can reset it to a blank folder manually if you want (currently working on an automatic way of doing this).  If you want us to do that, we need a public signed statement of permission.  Please run the following command on one of your devices, and substitute the current date and time as indicated:

```
keybase sign -m "<DATE_AND_TIME>: Please completely reset folders /keybase/private/chrissem and /keybase/public/chrissem because I reset my Keybase account."
```

and post the output here.  Thanks!

**Comment by strib** [comment]
[Note: I didn't bother anonymizing your Keybase username, since you've linked your github identity to it already.]

**Comment by chrisse-m** [comment]
Yeh I tried to fix the problem by resetting my account so the data isn't the problem.

**Comment by strib** [comment]
Well the reset account is definitely the problem now.  I'll look back at your logs to see if something else was going on before.

**Comment by strib** [comment]
Oh, actually your logs only go back to the point where you reset your account.  So I can't tell what happened before that.  Are you sure you were previously getting the exact same error message before you reset your account?

Let me know what you'd like to do about resetting the folders to a blank slate.

**Comment by chrisse-m** [comment]
we can do a total reset of my account I have no problem with that. So I'll sign the phrase you send me?

**Comment by strib** [comment]
Sounds good.  Yeah, just run the command I posted above, and post the output here.  (Substitute in the current date and time.)

**Comment by chrisse-m** [comment]
`BEGIN KEYBASE SALTPACK SIGNED MESSAGE. kXR7VktZdyH7rvq v5wcIkHbsIyimjk NVBQKzeq23wM1cq 7nZoFJsB05fAI3j 70fMLXG9qoNOs1e a1riSTZDseIRrd0 k2XqaMi8FketrzE 0yHQJXbGs9aI3Hf fji6tOQuGgIzT9o sqz1U46C8EsDMLc xLTGukkcS5pG4sH P9b5Q7QRmgUrqg8 jUWbJA7YhCRV4Jb iWv542FbHGDoGhZ j8gvDNylvwNI9QZ gqIOVnehkoGb9fz yM6OFRKQJG5IwRT U9qN6jN0RDxFNpN mwailEhUqxiwNsT wFniookw7TNglvZ DNzdWajzM10IwqN VyfBA4SoMTG1tXf zGWfde8G4XvgnNR XJ2EcUlWgsOGS38 r1nPtgm2PabTe13 WUne6kYCA45bkub fu97kFyr7P1B3Mf 1bqkxftOq3RnJsb FyTKUCexIRhhpBI dsZTJOAwT6fZWux NLNYfSQiPv2U4m0 . END KEYBASE SALTPACK SIGNED MESSAGE.
`
there you go. THX for the support

**Comment by strib** [comment]
Ok, the folders have been reset.  Please give them a try!

**Comment by chrisse-m** [comment]
ok It's working:
`https://keybase.pub/chrissem/test.txt`

thx again 
-chris

**Comment by strib** [comment]
Beautiful!

**Comment by DarthWed** [comment]
Hello there :)

05/10/2016 - 08:45 AM CEST: Please completely reset folders /keybase/private/wed and /keybase/public/wed because I reset my Keybase account.

BEGIN KEYBASE SALTPACK SIGNED MESSAGE. kXR7VktZdyH7rvq v5wcIkHbs41bK3H gDDr6tn3UR2BxSK 0jaccCKrxN0JGaX lnkNEkbjlm2P76J LXgO2fyRD6JbLrK BE0zR576sLtCr9j RNp8OXmroYlKITA vNhR8586PvYao14 wz9p6ulToBlJlE9 kI1zPCCSTDFbTIv ZyyYPITRMNP8ri1 C4ikaUxTDM1JTQ0 kCFZViHrnZ68fDZ G7VApGREKYp5uyL CykIsOSFFCCbySj r4KuRQjifQj5Scl LzgNo2IVsOmlRAr AlAZY4A99DaJm8P ZlUR5xyb2vzs6fW tO3sonCHNAwL9ZK jD6NPQc6Qbkyy1d xnH0mFu8a5caLVR XJ2EcUlWgsOGS38 r1nPtgm2PabTe13 WYmoQB6pbdcO1dW Dr61YEb1onzeSRQ xOHyZ6FolYBUPOn EezICGd3VYiLdQH uHkrAaq04ahFRcD AED9acJ2WsBYLFg . END KEYBASE SALTPACK SIGNED MESSAGE.

Thank you very much!
