### ISSUE TITLE
Some sort of sign from leadership please?

### ISSUE THREAD

**Issue by samheuck** [keybase/client#27969]
**Describe the bug**
https://keybase.io/blog has not had any activity since 2020.
https://investors.zoom.us/node/7551/pdf: also from 2020.

Talking about Kebase, as a product, publicly, doesn't seem to be happening.

**To Reproduce**
1. Google "Keybase news"
2. Click on a result
3. Scroll down to : where it inevitably says "Is keybase dead?"

**Expected behavior**
A clear and concise description of what the possible futures are.

**Screenshots**

<img width="944" alt="Screenshot 2024-09-19 at 10 55 02" src="https://github.com/user-attachments/assets/d3b1552e-19da-47cf-8ccc-f5ab4c48a08a">

**Comment by samheuck** [comment]
Aaaand it closed my issue.

**Comment by nikelborm** [comment]
daaamn, that's so funnyyyy

**Comment by nikelborm** [comment]
https://github.com/keybase/client/graphs/contributors
![Screenshot from 2024-09-20 00-59-32](https://github.com/user-attachments/assets/87ad85df-ed4f-4840-b0ec-0c7c76f27265)

**Comment by nikelborm** [comment]
but the issue was closed because of 345567 (no sure what this means)

https://github.com/keybase/client/blob/master/.github/workflows/issues.yml
