### ISSUE TITLE
Mac Notification: /keybase/System is not a Keybase folder (kbfs)

### ISSUE THREAD

**Issue by lorenzschmid** [keybase/client#2815]
Having installed the beta version of keybase containing the [Keybase Filesystem](https://keybase.io/docs/kbfs) I get notified every once in a while with the following notification:
![screen shot 2016-05-09 at 22 16 04](https://cloud.githubusercontent.com/assets/3830671/15206877/ac5fee60-1822-11e6-9bb0-3ed655137343.png)

It seems as if the OSX tries to create a general `System` folder inside the `/keybase` folder which in return is not understood by keybase as it neither is named `private` or `public`, the only acceptable folder at this place.

My OSX version is `10.11.4 (15E65)`.

**Comment by cjb** [comment]
It's probably some other application on your system. You could leave `opensnoop` running in a terminal to try to find out which one.

**Comment by lorenzschmid** [comment]
Thanks, I will have a look at it.
