### ISSUE TITLE
reinstalled Arch  GNU/Linux  on my laptop now I can't authentificate from it

### ISSUE THREAD

**Issue by ChrisFernandez** [keybase/client#2861]
so I' m trying to login from the cLI and adding it as a new device since I see NO option to just update the info and make this the old one.. since is the same device..
but I'm getting an error over and over and can' t do anything at all since im not logged in, from the website I can't do anything at all :( such is a shame.. 

```
cfernandez@cfernandez-linux ~]$ keybase login
Your keybase username or email address: cfernandez

The device you are currently using needs to be provisioned.
Which one of your existing devices would you like to use
to provision this new device?

        1. [computer]   rek2-desktop
        2. [computer]   rek2-laptop
        3. [paper key]  above seed
        4. I don't have access to any of these devices.

Choose a device: 1
Type this verification code into your other device:

        large gesture movie gym exclude wood talent genius

If you are using the command line client on your other device, run this command:

        keybase device add

It will then prompt you for the verification code above.
```

so I proceed in a second terminal.

```
[cfernandez@cfernandez-linux recipes]$ keybase device add
▶ ERROR Operation timed out
```

**Comment by maxtaco** [comment]
Can you post a `keybase -d device add` on the second machine?  thanks

**Comment by ChrisFernandez** [comment]
I was able to do it with the seed,  but for the future will be nice to be able to do it with username/passwd with out the seed, I format a lot my computers every 3-6 months at least to make sure is clean, is a pain to have a create new devices and is ok if it works.. :) but when it does not then sucks. cheers

**Comment by ChrisFernandez** [comment]
deleting  this
