### ISSUE TITLE
Public section not showing personal public folder in history

### ISSUE THREAD

**Issue by Walkersneps** [keybase/client#2875]
In the OS X client's menubar "floating" window, the `private/` and `public/` sections keep the history of the most recently opened sub-folders.
The issue I'm reporting is that the `public/` section omits my own public folder from the list, so every time I need to access it, I have to type my username.
If it's supposed to work this way, I'd suggest to reconsider it.

**Comment by cjb** [comment]
@Walkersneps Could you try an update ("keybase update check") and re-test?  I think we might have fixed this one already.

**Comment by Walkersneps** [comment]
@cjb Just tried, looks like I'm already updated with the latest version (console gave me `▶ INFO Update matches current version: 1.0.15-20160519130020+51248e3 = 1.0.15-20160519130020+51248e3`), and I'm still experiences the issue. I'm on OS X 10.10.5.

**Comment by cjb** [comment]
@Walkersneps Thanks -- are you sure that your public folder isn't anywhere in the list?  Mine is in the list, but not at the top.

(I'm running a slightly newer build than your latest public one, so I might have to ask you to retest again in a few days..)

**Comment by Walkersneps** [comment]
@cjb Yes, I've only got 2 folders in the list, and none of those is my own.
Here's a screenshot:
![screenshot](https://cloud.githubusercontent.com/assets/7949250/15543513/7f10441e-2295-11e6-8040-7c10c96bb4db.png)

I'll report as soon as I get a client update.

**Comment by cjb** [comment]
Cool, I think I've confirmed that this is fixed in our test builds (though the list isn't alphabetized and should be..) and not fixed in our public builds, there'll be an update in a few days.

**Comment by Walkersneps** [comment]
Updated and now the issue is fixed!
