### ISSUE TITLE
The icon displayed in the status bar is too small/unclear

### ISSUE THREAD

**Issue by karora** [keybase/client#2882]
Keybase GUI Version: 1.0.15-20160520160055+f4ef15a

Perhaps this is a HiDpi screen issue - the status bar icon doesn't seem to scale when I increase the panel size, and to be honest I only recognize it by the fact that it is unrecognisable!

**Comment by chromakode** [comment]
Thanks for this feedback! Could you please share a screenshot of what the icon looks like on your panel, and the version of your desktop environment?

**Comment by karora** [comment]
Screenshot attached!

![screenshot from 2016-05-25 10-30-34](https://cloud.githubusercontent.com/assets/147257/15545560/a504913a-2294-11e6-9079-5411e5a6edcd.png)

**Comment by karora** [comment]
Yesterday I was running Cinnamon on Ubuntu 16.04 when I filed the bug, although overnight I switched the laptop to Debian Unstable, and I tried it under Gnome 3 Classic which exhibited the same problem.  I'm now running Cinnamon again on Debian now, and see the same issue.  The screenshot above is from Cinnamon 3.0.2 under Debian.

**Comment by chromakode** [comment]
Thanks @karora! One of our engineers has experienced this too :) I've submitted this bug to our internal tracker.

**Comment by awendland** [comment]
@karora I believe that this issue has been fixed, and should be available in the next public build :)
