### ISSUE TITLE
High CPU usage

### ISSUE THREAD

**Issue by paulo-coelho** [keybase/client#2892]
[write something useful and descriptive here]
Tried 1.0.15 and 1.0.16. The CPU is 100% for kbfs. The same happens on Ubuntu 14.04.
my log id: 15f5d34b9e617026f361991c

**Comment by cjb** [comment]
Hi @paulo-coelho, it looks like you're running one of our test builds for OS X, that's surprising. How did you install it?

**Comment by paulo-coelho** [comment]
I download the first version from keybase.io/friends-of-keybase (1.0.15-20160519130020+51248e3)

After running "keybase update check" to see if there was a new version that would solved the high cpu usage issue, I saw the updater source URL and tried https://s3.amazonaws.com/prerelease.keybase.io/index.html , where I found the test versions.

**Comment by cjb** [comment]
Thanks.  @strib, any ideas on the CPU usage?

@paulo-coelho, were you doing anything inside KBFS when the CPU usage happens?

**Comment by paulo-coelho** [comment]
Nothing at all. I just run the sequence logout, uninstall, install and login. After that the kbfs process goes to 100% and remains. I can still access public folders and my personal private folder. However, I’ve noticed that I cannot access anymore some random data of around 200MB that I put in a shared folder with my wife just to test (/private/pattycoelho,paulocoelho).

**Comment by strib** [comment]
Hi @paulo-coelho, thanks for the report.  I don't see anything unusual in the logs, so we'll have to dig deeper.  Would you mind sharing some more information?

* A screenshot showing the CPU usage (and if it's easy, a graph over time?  I'm not an OS X guy so I don't know how easy that is to get).
* The output of `tail -n +1 /keybase/.kbfs_profiles/*` while the CPU is at 100%.

The latter command could potentially contain sensitive info (it shouldn't, but I can't say that 100% for sure), so you might want to drop it in /keybase/private/strib@github,paulocoelho and let me know it's there.

Thanks!

**Comment by paulo-coelho** [comment]
Hi strib, I uploaded the screenshot. There’s no need for a graph, because as long as I run "keybase login” kbfs process jumps to 100% and stays like this.
I suspect there is something wrong with the private folder I share with my wife (pattycoelho,paulocoelho). I tried chris,paulocoelho and stib@github,paulocoelho and they work fine, but I can’t even run ls on pattycoelho,paulocoelho . I don’t know if the CPU usage has any relation with that. Could you please destroy the folder and its content? Or maybe there’s something different with my wife’s profile related to kbfs.

**Comment by strib** [comment]
Thanks @paulo-coelho, that was really helpful.  I'm pretty sure I see the bug, and you're right, it's specific to that one folder.  We're still investigating, but it's probably a client-side problem that we can fix with an update -- in that case, you should be able to update your client once a new build is out, and it would fix itself, i.e. we wouldn't have to destroy the folder.

But we can still destroy it if you want -- what do you prefer?

**Comment by paulo-coelho** [comment]
If you could destroy I’d be grateful. The files are not important at all. I’m glad I could help. Keep going with the project, I really like the idea of making the use of cryptography more popular.

**Comment by strib** [comment]
Ok, will do, though we need a signed statement from you to destroy it, to make us sleep better at night.  Please run the following command on one of your devices, and substitute the current date and time as indicated:

```
keybase sign -m "<DATE_AND_TIME>: Please completely reset folder /keybase/private/pattycoelho,paulocoelho due to a client CPU usage bug provoked by the folder."
```

and post the output here. Thanks!

**Comment by paulo-coelho** [comment]
Here is my signed statement:

BEGIN KEYBASE SALTPACK SIGNED MESSAGE. kXR7VktZdyH7rvq v5wcIkHbsFk8Dg6 SBpcuPiiYDZ4rYi c6QI6dmFAF3DbdR bteSXuj4cpsPmn6 WuKTiuOHhOgWJyb AoU3Y5dxq5XzNcK cJvFdj7jJOtTboc pi4jhh2OYEPxs0t l8xdz22MorrAMfH gxFh4qlmlG8dg2c BqNnvRTMMR1oN7o DM7G3sOeWakfEn4 2CsGoUaMIy3RApw 56HcuPheJ7z3VOG LLczozExVuhCTfR JduvhMeIAR8954D pfvO3sonCHNAwL7 a3OgHdvLcdK4gLD 2E2PN5YpwWM5UeT fNZuBz5wez3JLgS YVDeSSJytipMImt vTGubgmBdlIqYP7 g7YwvwvRA4FBFIJ fkm5Ix5u33NzGvR x2hmNVA3KcNXEqO i3Dh18BC7rV7lmB VMm7QTJAZFi3X6t AlplgY3NX0jbm0n ID16wguV4k29ciJ CiEkHDwIl5l8jwC KleTpuC400. END KEYBASE SALTPACK SIGNED MESSAGE.

Thanks!

**Comment by strib** [comment]
Thanks @paulo-coelho, the folder has been reset.  Both of you should see the changes when you restart KBFS next.

**Comment by strib** [comment]
Also, the relevant bug fixes are in the next release, so we can close this out when you confirm your CPU issue is fixed.
