### ISSUE TITLE
ERROR EOF on login attempt

### ISSUE THREAD

**Issue by jackusm** [keybase/client#2897]
I get asked for my username/email, then choose a method to provision the new device, then after entering a public name for the device I get ▶ ERROR EOF

my log id: ccbee76282d543a2264c0e1c

**Comment by oconnor663** [comment]
This looks like an Arch-specific bug, which has something to do with the `gccgo` build they're using in place of the regular go compiler. We're still tracking down the problem.

**Comment by endophage** [comment]
@jackusm way to work around it in the meantime, if you have docker installed you can use this dockerfile (run command is at the top) https://gist.github.com/endophage/a514c2631ccc5f6ebb575232e7063622

**Comment by jackusm** [comment]
Thanks a lot, I love the idea of docker, but I have no idea how to build it. Okay, so that's wrong as I can build it (created a folder with your gist saved as Dockerfile and ran "docker build .") but am I supposed to name it or something? "Unable to find image 'keybase:latest' locally". Sorry

**Comment by endophage** [comment]
Yeah sorry, I didn't provide full instructions but good job for working it out before I got back to my computer!

**Comment by oconnor663** [comment]
More discussion at https://github.com/keybase/client/issues/2897

Related to undefined behavior in Go clarified at https://github.com/golang/go/issues/15905

**Comment by bootstraponline** [comment]
I think this issue can be closed. There's a new docker supported login method.

https://github.com/keybase/client/pull/11500
