### ISSUE TITLE
Windows: Extended frozen file explorer after reboot/before login

### ISSUE THREAD

**Issue by zanderz** [keybase/client#2916]
I thought we had cranked down timeouts to 19 seconds but I still see this:
1. Get logged in and browse around some private keybase folders with file explorer
2. Reboot (don't sign into keybase yet)
3. Open file explorer again and try to navigate to a non-kb directory

It seems explorer is trying to access private folders for listing them in the "recently used" list, but this freezes the whole thing for minutes at a time. Several timeout popups appear.

This is with dokan 0.8.0, latest master, built this morning:
1.0.16-20160527074935+7c9e507

my log id: 60d359e8829e68ffeea98e1c

**Comment by zanderz** [comment]
I did not see it just now on Windows 10 with the 2-week old client we're still shipping on the website:
KBFS:
    status:    running
    version:   1.0.2-20160513144641+2e3e40f
    log:       C:\Users\IEUser\AppData\Roaming\Keybase\keybase.kbfs.log

Service:
    status:    running
    version:   1.0.15-20160513144641+568ef0a
    log:       C:\Users\IEUser\AppData\Roaming\Keybase\keybase.service.log

I could not test the latest Dokan 1.0.0RC4 because my VM quits working properly when it's installed (possibly related to having to disable driver signing enforcement?)

Windows7 does not show this problem with Dokan 1.0.0RC4. Testing 0.8.0 on Win7 now.

**Comment by zanderz** [comment]
Could not repro on Win7. Also failed to re-repro on Win10, so this is a bit of a UFO. Maybe caused by a network hiccup at a specific time?

**Comment by zanderz** [comment]
@taruti

**Comment by taruti** [comment]
This warrants a libdokan specific hack, will implement.

**Comment by zanderz** [comment]
Fresh batch of logs with the dokan 1 test branch. Same symptom: explorer frozen at reboot when keys are left locked.
0e63316aa37fd81021e27a1c
Hung around 13:08 - 13:09 I think, then unlocked with pinentry at 13:15
@taruti

**Comment by taruti** [comment]
Was this with https://github.com/keybase/kbfs/pull/13 merged (the logs look like it was missing)?

**Comment by zanderz** [comment]
Frozen for more than a minute at 9:53 AM
d3a95a0ad3e46236ec91051c

Note that kbfs should be the same as 83d77672e01f8b3a58a3afea12324633a3dcee62, despite my unnecessary merge.

**Comment by zanderz** [comment]
Seems better with recent fixes. Closing.
