### ISSUE TITLE
Keybase spams that /keybase/Thumbs.db is not a Keybase folder

### ISSUE THREAD

**Issue by DarthWed** [keybase/client#3025]
I'm using KBFS on Windows and OS X. I assume that windows creates /keybase/Thumbs.db and that leads on OS X for some notifications from the keybase client.

<img width="318" alt="bildschirmfoto 2016-06-08 um 10 53 08" src="https://cloud.githubusercontent.com/assets/9463106/15888638/f4b5db7a-2d67-11e6-938a-52f8d108a68b.png">

**Comment by strib** [comment]
Thanks @DarthWed!  I've pushed a fix to suppress this notification, it'll be in the next Windows release.

**Comment by DarthWed** [comment]
That message appears on OS X, not on windows.
I just assumed that windows is creating that file.

**Comment by strib** [comment]
Ah ok, no nothing is allowed to create a file under `/keybase`, so this must be something the OS X system or one of your applications is looking up on each mountpoint.  In any case, it'll be fixed in the next OS X release as well.
