### ISSUE TITLE
Mac OS Keybase Icon invisible in dark menu bar

### ISSUE THREAD

**Issue by sebflipper** [keybase/client#3066]
Since a recent update the menu bar icon is now invisible when the menu bar is set to dark mode on Mac OS X El Capitan 10.11.5 (15F34).
<img width="334" alt="screen shot 2016-06-11 at 17 59 07" src="https://cloud.githubusercontent.com/assets/144435/15986407/3c6ca4aa-2fff-11e6-9026-0eab92e8c843.png">

The icon is still clickable, but appears as a blank space.
<img width="780" alt="screen shot 2016-06-11 at 18 01 09" src="https://cloud.githubusercontent.com/assets/144435/15986403/08b74d7c-2fff-11e6-97e8-cd886d13126c.png">

Keybase GUI Version: 1.0.16-20160609201138+1e7a713

**Comment by chrisnojima** [comment]
This has been resolved in the next release

**Comment by stephenyeargin** [comment]
I'm having the inverse of this problem, and I think I know the culprit. The computer was running overnight when [Flux](http://justgetflux.com) automatically enables dark mode at sunset, and disables it at sunrise.

![screen shot 2016-07-04 at 12 12 04 pm](https://cloud.githubusercontent.com/assets/80459/16567092/8d97684a-41e0-11e6-932f-e7840ccb0add.png)

Keybase GUI Version: 1.0.16-20160630135211+c643773

**Comment by chrisnojima** [comment]
We'll look into it. We currently swap the icon on startup but not if that
preference changes while running.
