### ISSUE TITLE
Cannot login with new Keybase app (1.0.16-20160615195851+9200593)

### ISSUE THREAD

**Issue by soumyaray** [keybase/client#3135]
I've put the keybase app in my Applications folder on OSX

When I try to login with the GUI, I am asked to enter username/email and passphrase. After the passphrase is entered, I get:

"There was an error provisioning
Unknown error: Error: GPG is unavailable on this device"

my log id: 2e5e257b6369f5b5fdbe5b1c

**Comment by soumyaray** [comment]
I resolved this by doing keybase login at the command line (which also created a paperkey). I am now logged into the GUI. I feel the GUI login could have mentioned this.

Thanks for the awesome and incredibly competent effort at making keybase!

**Comment by knowtheory** [comment]
As a heads up i bumped into this error too and didn't know what to do (except search for other people with the same problem) until i landed on this ticket!

I also solved my problem by logging in via the `keybase` command.
