### ISSUE TITLE
Input/Output error when accessing public/private folder

### ISSUE THREAD

**Issue by rgruyters** [keybase/client#3159]
Hi,

I want to access my public and/or private folder, but I get an error message stated "Input/Output error".
Tried to uninstall and reinstall keybase, but no luck.

    $ cd /keybase/public/rgruyters
    $ ls
    ls: .: Input/output error
    $ 
    $ echo "This is a test" > test.txt
    -bash: test.txt: Input/output error
    $
    $ ls
    ls: .: Input/output error
    $

my log id: 2a8f1e00402d1708a8245f1c

**Comment by cjb** [comment]
@rgruyters Hi, this was an outage at our end, apologies.  It's fixed now!

**Comment by rgruyters** [comment]
Yes it is working again. thanks.
