### ISSUE TITLE
Access denied to public/martindevans

### ISSUE THREAD

**Issue by martindevans** [keybase/client#3160]
On a fresh install of keybase FS on windows I have access denied to write to my own directory.

![2016-06-22_15-09-20](https://cloud.githubusercontent.com/assets/177519/16269779/b0f3a672-388b-11e6-827d-59a9f4bf18c9.gif)

You can see here I right click (it takes a while to pop up. In fact explorer is "not responding" for second or two). I create a new text file which pops up a box telling me I need admin permission (which I grant), and then it denies me again.

After this failure I tried dragging a file from another location into K:/public/martindevans and this worked fine (you can see the file [here](https://keybase.pub/martindevans/New%20Text%20Document.txt)). I edited this file (in the keybase directory) and that worked fine too, so it's just trying to create new files via right click which is a problem.

Edit:

I just tried this process again (right click, new file) and it worked totally fine! I tried deleting all files in the folder, guessing perhaps it's a problem when the directory is empty, but that worked fine too.

**Comment by strib** [comment]
Hi @martindevans -- can you please do a `keybase log send` from the Keybase CMD app and let us know the log ID so we can investigate?  Thanks!

**Comment by martindevans** [comment]
I have done so, here's the response from keybase:

```
- WARNING error opening log "C:\\Users\\Martin\\AppData\\Roaming\\Keybase\\keybase.start.log": open C:\Users\Martin\AppData\Roaming\Keybase\keybase.start.log: The system cannot find the file specified.


------------
Success! Your log ID is:

  d6232a18d4855fd809edf31c
```

**Comment by strib** [comment]
It looks like you were hitting the same server issue described in #3141.  It should be resolved now.  Please close this issue if everything's working for you still.  Thanks, and sorry for the inconvenience.
