### ISSUE TITLE
Persistent icon notification in menu bar

### ISSUE THREAD

**Issue by arneheggestad** [keybase/client#3161]
I have a notification dot on my menu bar icon, saying that my personal private folder is new. This started at the same time as some KBFS problems (#3143), which are now resolved.

Keybase GUI Version: 1.0.16-20160621190121+4d16a4b

<img width="122" alt="screen shot 2016-06-22 at 10 30 49 am" src="https://cloud.githubusercontent.com/assets/1536792/16270571/c7284e38-3864-11e6-8107-216282f91cf7.png">
<img width="318" alt="screen shot 2016-06-22 at 10 31 00 am" src="https://cloud.githubusercontent.com/assets/1536792/16270580/ce3a14c2-3864-11e6-8293-f56d3b888838.png">

**Comment by cjb** [comment]
@arneheggestad Thanks for the report.  Have you ever run `cd /keybase/private/arneheggestad`?  Are there files in the folder?

**Comment by arneheggestad** [comment]
Yes. I can see the files both from `ls` on the command line and in the Finder window.

**Comment by chrisnojima** [comment]
can you run ```keybase log send``` and post the id here? Thanks!

**Comment by arneheggestad** [comment]
@chrisnojima I'm out of the office this afternoon, but will do so when I get in tomorrow morning and post the ID.

**Comment by Walkersneps** [comment]
I'm experiencing the same bug, but with my public folder being notified as new.

My log id: fede09d3977a18527d5c4d1c

**Comment by arneheggestad** [comment]
@chrisnojima I just submitted my log. ID f4a469fc66a06971f61aab1c.

Thanks.

**Comment by chrisnojima** [comment]
Thanks, we're investigating

**Comment by chrisnojima** [comment]
Hi, we've identified a fix and will roll it out soon

**Comment by chrisnojima** [comment]
@arneheggestad @Walkersneps can you verify this is resolved?

**Comment by arneheggestad** [comment]
@chrisnojima Yes, looks like it's resolved for me. Thanks!

**Comment by chrisnojima** [comment]
Cool
