### ISSUE TITLE
Login continues to spin on Ubuntu 16.04

### ISSUE THREAD

**Issue by cgsmith** [keybase/client#3166]
Keybase GUI Version: 1.0.16-20160621171254+92767fa

The login on initial install just spins.

**Comment by cjb** [comment]
Please could you run `keybase log send` and tell us the output, and mention anything about what you were doing when it started to spin?  Thanks!

**Comment by cgsmith** [comment]
Thanks for the quick reply @cjb 

my log id: 38e76ce5c9b862b4acfa761c

**Comment by cgsmith** [comment]
I tried to login again but the login is just spinning, I hit the back button and come back to 'login' and it is still spinning even without a username in the text field.

I force closed keybase and will try again - just trying to find it now :D

**Comment by cjb** [comment]
Type `run_keybase` :)

**Comment by cgsmith** [comment]
@cjb working now - must have needed the good ol' reboot
