### ISSUE TITLE
Tried to upload a file

### ISSUE THREAD

**Issue by adammenges** [keybase/client#3173]
Steps to reproduce:
1. Buy an Apple computer.
2. Download and open Keybase.dmg.
3. Drag Keybase into your Applications folder & run it.
4. Try to copy file to private folder

my log id: dfca74fe122fd1acc797401c

**Comment by adammenges** [comment]
Also I keep getting the notification about sending logs, guess I need to restart.

**Comment by strib** [comment]
Hi @adammenges -- thanks for the logs.  I assume this is a large file?  If so, that's a known timeout issue for files > 5 MB.  We're actively working on it, sorry for the inconvenience.  This is referenced in several other open issues, including #1981.

**Comment by adammenges** [comment]
Semi large 20mb or something, cool glad you guys are aware of it

**Comment by strib** [comment]
The latest versions of KBFS for Linux and OS X (`1.0.16-20160627110020+11e6f10` and higher) include both performance improvements, and timeout avoidance, so it should be possible now to upload large amounts of data on all but the worst network connections without seeing an error.  Performance will still be pretty slow, since it involves synchronous round trips to our servers, but it should be a bit faster than before, and more importantly error-free.

Please try it out when you get a chance and let me know if things seem better.  Thanks!

**Comment by adammenges** [comment]
Nah still got a too long and fail error 😢

**Comment by strib** [comment]
@adammenges can you please do a `keybase log send`?

**Comment by adammenges** [comment]
8b2534b1d6bee9a43601901c

**Comment by strib** [comment]
Hmm, @adammenges I'm seeing it takes about 7 seconds for you to send the first 512KB of data to our servers.  Does that sound right?  Would you mind sharing your connection upload speed as reported by [http://www.speedtest.net/](http://www.speedtest.net/)?

(To be clear: this is definitely our problem, our clients should be able to handle any connection speed.  But unfortunately on OS X we are constrained by a hard timeout on file system operations.  Our latest fix should be able to handle connections of about 250KB/s or better, but it seems yours might be lower than that -- or you were using the connection for another big transfer at the same time.  Either way, we need to improve how we handle stuff like this, so thanks for helping out!)

**Comment by adammenges** [comment]
Here you go! Same computer / connection, but of course it may have been faster or slower at that time. FWIW currently feels like the same speed as then.

http://beta.speedtest.net/result/5441007157

**Comment by strib** [comment]
Hmm, ok then!  Thanks much.  Do you remember if you were doing much else with the connection or with your CPU at the time of that upload attempt?  I have no other theories for why a 512K upload would take 7 seconds on a connection like that.

Anyway, I'll think about ways to accommodate speeds like that.  Also, we're currently working on writing to local disk first and then uploading the bytes in the background, which would eliminate this issue, but that's still somewhat far away.

**Comment by adammenges** [comment]
Actually yea, tensorflow was off in the background eating all my resources, or at least a good chunk of them.

Good luck fixing! I'm excited for the product to be in a solid state. Side note, probably not the right place for this, but not sure where else it'd go, hopefully you guys are considering storage limits beyond the typical 1TB offered. One vacations worth of photos can be ~700gb. Privacy and storage space are the only reasons I need to operate a NAS. Would be nice to take one more thing off the list of things I need to maintain.

**Comment by strib** [comment]
Version 1.0.20 has architectural changes that should greatly improve the large write experience.  If you're still seeing problems, please open a new issue.
