### ISSUE TITLE
Debian Jessie KBFS access

### ISSUE THREAD

**Issue by ArnaudFabre** [keybase/client#3174]
Hi,

I am running Debian 8.4 and installed from https://prerelease.keybase.io/keybase_amd64.deb and I have some problems accessing KBFS.

 Here is what I tried :
- Install goes fine
- First run_keybase command showed me a GUI
- Tryed to log in and the spin goes turning forever. I close the GUI.
- Tryed to look at some ferret/whatever button in the bar of my gnome-shell... found nothing. 
- Tryed to run_keybase again. No more GUI.
- Tryed to access /keybase/public folders in the console with cd : nothing happens.
- Tryed to login first with keybase login, it works as stated by keybase status.
- Tryed to access /keybase/public folders in the console with cd, ls : nothing happens.
- Tryed to send logs with keybase log send. No log sub command found...
- keybase version gives me that :
keybase (keybase.io CLI) v0.8.23
- node.js v5.10.1
- gpg (GnuPG) 2.0.26
- libgcrypt 1.6.3
Identifies as: 'keybase.io node.js client v0.8.23 linux'
- Tryed to update with keybase update... Installation goes and finally same version in the output.
- Tryed reinstall and run_keybase again. No GUI, no access.

I had keybase installed "a long time ago" and did not use it a lot since then.
Any idea ?

Thanks,

**Comment by strib** [comment]
Hi @ArnaudFabre -- would you mind running `keybase log send` and reporting the log ID here, so we can take a look?  Thanks!

**Comment by maxtaco** [comment]
This seems like a path problem and still finding the old node-based
keybase.  This is an issue on Linux but not OS X. @oconnor663 can you
investigate?

**Comment by oconnor663** [comment]
Agreed with @maxtaco, that `keybase (keybase.io CLI) v0.8.23` bit is the old node client. @ArnaudFabre, can you give us the output of `which keybase`? I'm guessing you have something node-related at the front of your `PATH`, and that that's shadowing the `/usr/bin/keybase` binary that the .deb package installed.

**Comment by maxtaco** [comment]
I'd be all in favor of absolute paths, I think...

**Comment by ArnaudFabre** [comment]
Previous installation in /usr/local/bin/keybase was shadowing the /usr/bin/keybase binary.
Fixing the PATH make it work.

Thank you very much for your help !
