### ISSUE TITLE
Can't build go client using 'go get'

### ISSUE THREAD

**Issue by Intrainos** [keybase/client#3175]
I'm follow go/README.md build command, but can't build because of code.google.com/p/rsc/qr (go/qrcode/qrcode.go)

```
$ go get github.com/keybase/client/go/keybase
# cd .; hg clone -U https://code.google.com/p/rsc /home/username/gopath/src/code.google.com/p/rsc
abort: HTTP Error 404: Not Found
package code.google.com/p/rsc/qr: exit status 255
```

**Comment by maxtaco** [comment]
Does

``` 
GO15VENDOREXPERIMENT=1 go get github.com/keybase/client/go/keybase
```
work any better?

**Comment by Intrainos** [comment]
No, same
```
$ GO15VENDOREXPERIMENT=1 go get github.com/keybase/client/go/keybase
# cd .; hg clone -U https://code.google.com/p/rsc /home/osmc/gopath/src/code.google.com/p/rsc
abort: HTTP Error 404: Not Found
package code.google.com/p/rsc/qr: exit status 255
```

**Comment by maxtaco** [comment]
Which version of `go` are you running?

**Comment by Intrainos** [comment]
```
$ go version
go version go1.3.3 linux/arm
```

Maybe golang-go debian arm build version is too low?
ps. maybe not version problem i think, google code is shutdowned

**Comment by maxtaco** [comment]
Oh I see. Your version of Go is ancient and therefore doesn't respect vendoring.  We're targeting version `1.5.3` and above of Go, so I wouldn't expect things to work on your version.

**Comment by maxtaco** [comment]
I'm going to close this issue.  We'll eventually change our vendoring to point at the new `rsc/qr`, but on new Gos, it doesn't matter, we don't go fetching code during the build process, both for correctness and for security....
