### ISSUE TITLE
Can't login?

### ISSUE THREAD

**Issue by Arinerron** [keybase/client#3180]
```
<snip>@<snip> ~ $ keybase login
Your keybase username or email address: arinerron
▶ ERROR Failed to open session file /home/<snip>/.cache/keybase/session.json.<snip> for writing: open /home/<snip>/.cache/keybase/session.json.<snip>: permission denied
▶ WARNING Failed to remove session file: remove /home/<snip>/.cache/keybase/session.json: no such file or directory
▶ ERROR open /home/<snip>/.cache/keybase/session.json.<snip>: permission denied

<snip>@<snip> ~ $ sudo keybase login
[sudo] password for <snip>:
Oops, you are trying to run as an admin user (Uid: 0). This isn't supported.

<snip>@<snip> ~ $ 
```

I snipped my pc account name, computer hostname, and the session id.

**Comment by cjb** [comment]
It looks like the user you are logged in does not have write access to their $HOME/.cache/keybase directory.

**Comment by Arinerron** [comment]
@cjb Solution?

**Comment by cjb** [comment]
Not super comfortable offering a solution without knowing more about the misconfiguration and how it got to be that way.  You could run `ls -la $HOME/.cache/keybase` to see who owns the directory and go from there.

**Comment by Arinerron** [comment]
@cjb Looks like root owns all the files

**Comment by Arinerron** [comment]
Credit to @beardog108 who suggested I chown the keybase cache:

`sudo chown -R <account name> ~/.cache/keybase/`

**Comment by Rubenkl** [comment]
What about the 'Bash on Ubuntu on Windows' tool that is shipped recently with the updates of Windows 10? I hoped to see an easier workflow using the bash terminal, but this error message pops up.

**Comment by cjb** [comment]
@Rubenkl We haven't tested this and I don't expect it to work.
