### ISSUE TITLE
Javascript error with Keybase.app

### ISSUE THREAD

**Issue by jubianchi** [keybase/client#3191]
Here is what I get when clicking on the keybase icon in the menu bar:

<img width="435" alt="capture d ecran 2016-06-24 a 12 00 22" src="https://cloud.githubusercontent.com/assets/327237/16334782/49c42e62-3a03-11e6-9338-7345ca8701a9.png">

my log id: 38229673afe1c375b0453c1c

**Comment by cjb** [comment]
Hi, are you running the new macOS beta?

**Comment by jubianchi** [comment]
Yes I'm running a version I installed yesterday:

```
$ keybase --version

keybase version 1.0.16-20160621190121+4d16a4b
```

**Comment by lherlitz** [comment]
I have this same error and am also running the new macOS beta

**Comment by cjb** [comment]
@lherlitz hi, please could you run `keybase log send` and tell us the result? thanks! we're looking at this now.

**Comment by cjb** [comment]
Hi @jubianchi and @lherlitz, is it possible you tried to quit the app (e.g. with cmd-q) before getting this error? Looks like we've got a bug around quitting, just trying to see whether that's your one.

**Comment by jubianchi** [comment]
@cjb AFAIR this is exactly what happened.

**Comment by cjb** [comment]
@jubianchi Oh, cool, thanks. We'll have a fix for you soon, in the meantime you could kill and relaunch Keybase to get it working again.

**Comment by jubianchi** [comment]
@cjb yes this is what I did ;) Glad to hear you have a fix.

**Comment by lherlitz** [comment]
I still can't get mine working.

**Comment by lherlitz** [comment]
Log ID: de854dd144789266116c681c

**Comment by jubianchi** [comment]
@cjb FYI, I just installed an update this morning and I still get the same error (Log ID: `7d5bd67478975f36b094821c`). What I did was:

* Open the keybase menu (from the status bar)
* Go to "Public"
* Request "Chris" public folder
* Once the Keybase popup opened I hit CMD+Q

**Comment by lherlitz** [comment]
I'm not even getting that far.  The GUI seems completely unresponsive.  I got the notification I was logged in and I got that I received a new private folder, but I cannot open any folders.

**Comment by cjb** [comment]
Thanks folks, we haven't pushed the fix out yet. We'll get a fixed build out soon. (In the meantime you could use Keybase by killing and relaunching it, and avoiding cmd-q.)

**Comment by lherlitz** [comment]
I've attempted to do that with no luck.

**Comment by cjb** [comment]
@lherlitz Not sure what's up then, sorry -- please wait and try our fix, and we'll continue to investigate if it doesn't help you.

**Comment by jubianchi** [comment]
@lherlitz I use `killall Keybase` on OSX and it fixed the problem.

**Comment by cjb** [comment]
Hi, the build containing this fix is live now.  (You can run "keybase update check" and run the longer command it mentions to get it immediately.)  Let us know if you have any more problems!

**Comment by jubianchi** [comment]
@cjb thanks, I just pulled the update and everything is fine now!

Good job and thanks for the fix.

I'm closing this issue since it's resolved.
