### ISSUE TITLE
I got error "Keybase Possibly revoked data detected" 

### ISSUE THREAD

**Issue by fordantitrust** [keybase/client#3212]
I reset my keys and proofs my social identify and reinstall keybase, I got error "Keybase Possibly revoked data detected" 

/keybase/private/[myusername] was modified by a revoked or bad device.

Please suggest solution for this issue.

keybase sign -m "<DATE_AND_TIME>: Please
reset folder /keybase/private/fordantitrust and /keybase/public/fordantitrust be
cause I reset my Keybase account."

BEGIN KEYBASE SALTPACK SIGNED MESSAGE. kXR7VktZdyH7rvq v5wcIkHbsAOw4VE sjeCgVTxY
uuqWAm LwfPot4EVyyinnX MaaGkTQagfiDFeb fT3ZHd6ZST2Nihn nGH9XrIStQnMCOB MWWfWw6Ue
K7BAYG BUMUQ4U9oBH8gji MI4llbJdWt9MFLs G2fYEG8ZDwJwruj sXEZSgOXzULG6KY n7LnRuzgJ
Fr9WjM I733TZsV0Tg32VM ZSuwf7h2JNJqOxP XZvz5n5WohXMrT8 nhUF4pr0d8PKZaC h78QQVEHO
vkzvGo kHBhGo0kc1OM46r kOnuXL4KjmYDfsi RBEsgUsFylZg4m9 m5LPd7C17F6KM4Y jV1bZPw50
tzL5RS ioDOXQR0baoJXC9 U03UDGSwH6PsTmL vN9U8h6DNJeopB9 0CjAgEhMHi6w3wk bKlyMJBlu
1sJKUn AMbYQWOzzDX4vqz oUBdQktiZGRl1Mf 7Elxk7aImlE. END KEYBASE SALTPACK SIGNED
MESSAGE.

my log id: 23504d59ba7fdc6ca76cd71c

**Comment by strib** [comment]
Hi @fordantitrust -- we can certainly reset those folders. But in your signed message, you left in "<DATE_AND_TIME>", and you're supposed to substitute in the current date and time.  Without that, there could be a replay attack for the message.  So can you please make a new signature over a message containing the current date and time (and the rest of the text), and post it here?  Then we'll reset those folders.

**Comment by fordantitrust** [comment]
FYI. 

Thank you very much.

2016-06-27-093005 PDT: Please reset folder /keybase/private/fordantitrust and /keybase/public/fordantitrust be cause I reset my Keybase account.

BEGIN KEYBASE SALTPACK SIGNED MESSAGE. kXR7VktZdyH7rvq v5wcIkHbsAOw4VE sjeCgVTxY
uuqWAm LwfPot4EVyyinnX MaaGkTQaggLVv6b qFGieWhPe4UQzuD Eevno4vOxsBlFFN QJ08PycUm
jkzDEc mcGlMo1v6sHXELG lHec78IyDFxdnLL iBpQnfsGT5NgACD trBID0F3MMVRvQn 4fA6KSLMv
0j8UDF plBZNd9JuG9EhM1 fBcIKJ4OQO97AIo XwSyMjs05DruYA7 4w8Jw8OlGxs29KU pj7S4RdVk
nOG6Rh xURHk1ZRnpkebLA FjqcVdDmvUiFxQT fQfNPmkPpy7QmQc cr5iTOvzoyC6lfr mXxWs6S7b
xowrYR 7rk3g9q24q5t0MZ KZpRICs8pIzGIyw ZXbBZZ2GBKj82xS ZHPobznJbJFxnrq hQVW6edkH
PJzKTR W18VBGMHn029GnP 5TM8aLcrxO5R1tI 2akRCFW85GpUehw D59cCO. END KEYBASE SALTP
ACK SIGNED MESSAGE.

**Comment by strib** [comment]
Thanks! These have been reset.  Please check, and close out this issue if things work for you now.

**Comment by fordantitrust** [comment]
Thank you for support ^^
