### ISSUE TITLE
Encrypting a large amount of files at once

### ISSUE THREAD

**Issue by orta** [keybase/client#3241]
I just tried throwing 1.64GB worth of files into a public dir, looks like it stopped and died

my log id: 5201c94b4fc89c3537711d1c

**Comment by strib** [comment]
Thanks for the report, and for trying to trust us with so much data!  This is something we've known about for a long time (see #1981 for one dup), and the fix should actually be in the next upgrade (not sure when that will be live though).

Closing as a dup, but keep your eyes on #1981 for when to retry.

**Comment by orta** [comment]
Works for me 👍
