### ISSUE TITLE
macOS versions

### ISSUE THREAD

**Issue by adammenges** [keybase/client#3256]
<img width="417" alt="screen shot 2016-06-28 at 3 47 36 pm" src="https://cloud.githubusercontent.com/assets/817438/16435506/4eacbb74-3d4b-11e6-827e-72002ae828dd.png">

my log id: 82eaf93e20e8107374f22e1c

**Comment by jsejcksn** [comment]
@adammenges I think it's all stored remotely now, so nothing persists locally on your computer. Think of the `/keybase` folder like an alias to their remote server (which you just happen to be able to interact with in Finder).

**Comment by adammenges** [comment]
I don't think the remote aspect has anything to do with it. Files on a typical NAS do not alert in this way, for instance.

Anyone working on a Mac is going to see the notifications, and not be able to use features they are used to using if they store their files on keybase if it says like this.

**Comment by strib** [comment]
We've looked into this before and can't support it right now, unfortunately.  It's an HFS-only thing, e.g.: http://helpdesk.rushfiles.com/support/solutions/articles/5000553289-osx-volume-does-not-support-permanent-version-storage

Right now the only known workaround is clicking the checkbox so it doesn't show up again.

If it makes you feel better, KBFS will have it's own "permanent version storage", but we probably still won't be able to integrate it with macOS.
