### ISSUE TITLE
Using commandline with zsh shell creates all matching directories

### ISSUE THREAD

**Issue by JeroenBoersma** [keybase/client#3263]
Under Linux when using the commandline to navigate to a public folder like mine `/keybase/public/srcoder` will also create all matching users because of the suggestion lookup.

So I've already ended up with all suggestions like `/keybase/public/src`, `/keybase/public/sr`, etc.
Because I vannot remove them I will end up with a lot of distracting directories.

keybase version 1.0.16-20160627164435+e95f9ff

**Comment by strib** [comment]
Urg, sorry, that's annoying.  You can remove them with `rmdir`, but they will just come back again I think.  We will have to figure out a way around this.  Thanks for the report.

**Comment by brkattk** [comment]
Keybase GUI Version: 1.0.16-20160627110020+11e6f10

I'm unable to remove the incorrect directories altogether. 

```
rmdir: /keybase/private/brkattk,someuser: Input/output error

**Comment by cjb** [comment]
Please run "keybase log send", thanks.

**Comment by brkattk** [comment]
Sent: 2b1ac369e692fb9370d4041c

**Comment by cjb** [comment]
@strib 
```
33058 2016-06-30T11:08:44.987686 ▶ [DEBU kbfs(kbfsfuse) folderlist.go:219] 8122 FolderList Remove brkattk,xxxxxxxxxx [tags:FID=Lp6wl0XQiMiHSxgxK1Va3w]
33059 2016-06-30T11:08:44.988798 ▶ [DEBU kbfs(kbfsfuse) folderlist.go:220] 8123 Can't delete a favorite without a handle [tags:FID=Lp6wl0XQiMiHSxgxK1Va3w]
33060 2016-06-30T11:08:44.988833 ▶ [DEBU FUSE serve.go:845] 8124 -> [ID=0x4] Remove error=EIO: Can't delete a favorite without a handle
```

**Comment by strib** [comment]
Ah, I see.  Your client wasn't able to verify the identity of one of the folder participants, and left the folder in an unexpected state.  Definitely a bug, I'll work on it today.

Were you able to delete your other public folders created by the completion script?

**Comment by brkattk** [comment]
Yes, but they (obviously) come back

**Comment by JeroenBoersma** [comment]
This issue doesn't occur anymore, so I guess it's fixed
