### ISSUE TITLE
Bash tab completion hanging on OSX

### ISSUE THREAD

**Issue by jericson** [keybase/client#3272]
While using tab to find a file under `/keybase/private/{username}`, bash hung for a few seconds and the keybase app asked me to send the log.  Since then, I've found that tab completion _always_ hangs and requires a `^C` to continue. It does not seem to be a matter of caching. 

The problem is not isolated to `/keybase` paths, but did seem to start around the time I started using the new keybase client.

my log id: e850978282892a7e339e091c

**Comment by strib** [comment]
Hi @jericson -- seems like you aren't connected to our backend servers when the timeouts were happening:

```
27866 2016-06-29T01:38:00.168391 ▶ [WARN kbfs connection.go:353] c57 (CONN BlockServerRemote 929b3bb2) Connection: error dialing transport: dial tcp: lookup bserver.kbfs.keybase.io: no such host
```

So your computer couldn't resolve "bserver.kbfs.keybase.io" -- maybe you were having DNS troubles?

**Comment by jericson** [comment]
Maybe. But if I can ping the server immediately before and after tab completion hangs:

```
$ ping bserver.kbfs.keybase.io
PING bserver-elb-207251293.us-east-1.elb.amazonaws.com (52.20.57.80): 56 data bytes
64 bytes from 52.20.57.80: icmp_seq=0 ttl=41 time=101.189 ms
64 bytes from 52.20.57.80: icmp_seq=1 ttl=41 time=115.909 ms
64 bytes from 52.20.57.80: icmp_seq=2 ttl=41 time=118.324 ms
64 bytes from 52.20.57.80: icmp_seq=3 ttl=41 time=100.171 ms
64 bytes from 52.20.57.80: icmp_seq=4 ttl=41 time=116.212 ms
^C
--- bserver-elb-207251293.us-east-1.elb.amazonaws.com ping statistics ---
5 packets transmitted, 5 packets received, 0.0% packet loss
```

**Comment by strib** [comment]
Hmm, I definitely see issues in the log of being able to keep a steady connection open to the servers.  But the hang seems to happen specifically when you are trying to list your "favorite" folders (the ones that show up under `public/` and `private/`).

Looking into it further, I see another timeout here:

```
31194 2016-06-29T12:48:48.187850 ▶ [DEBU keybase engine.go:66] 11e5 - RunEngine(FavoriteList) -> ERROR: API network error: Get https://api.keybase.io/_/api/1.0/sesscheck.json: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
```

@maxtaco: can you check if there's any chance this is a server-side issue?

**Comment by jericson** [comment]
I got the latest client update and it occurred to me I should restart my bash session. After updating and restarting bash, tab completion is working. I _think_ it was a problem with me not restarting bash after getting the update the other day.

**Comment by maxtaco** [comment]
Here's the corresponding (redacted) server log for that timeslice for @jericson:

```
[29/Jun/2016:15:26:03 -0400] "GET /_/api/1.0/merkle/path.json?poll=10&uid=f7ea90ecb3d0923032ee7d9e3c215319 HTTP/1.1" 200 105373 "-" "darwin:Keybase CLI (go1.6.2):1.0.16" "-" "-"
[29/Jun/2016:15:26:05 -0400] "GET /_/api/1.0/pkg/update.json?auto_update=1&install_id=XXXX HTTP/1.1" 200 849 "-" "Go-http-client/1.1" "-" "-"
[29/Jun/2016:15:48:50 -0400] "GET /_/api/1.0/sesscheck.json HTTP/1.1" 200 230 "-" "darwin:Keybase CLI (go1.6.2):1.0.16" "-" "-"
[29/Jun/2016:15:48:50 -0400] "GET /_/api/1.0/kbfs/favorite/list.json HTTP/1.1" 200 296 "-" "darwin:Keybase CLI (go1.6.2):1.0.16" "-" "-"
```

In other words, the sesscheck right after the failing one seemed to work; but the one that fails (as you see above) never showed up on the server.  I guess we can attribute it to network flakiness or some network problem we're going to have trouble debugging.

I wonder if we should be timing out and retrying API requests more aggressively for certain calls.  Certainly `GET`s like `sesscheck` wouldn't be adversely affected.
