### ISSUE TITLE
Can I store the signed status of a file outside of KBFS?

### ISSUE THREAD

**Issue by alanbowman** [keybase/client#3283]
(This may relate to #2250)

If a user writes to /keybase/public/username/abdicate.txt saying "I abdicate the throne", then I can read from there and tell that it was definitely them that wrote it.  I can also copy the the file to a "local" directory, but it then loses its signed status.  If they change their mind and delete the file, I have no way of proving that they ever wrote it in the first place.

Have I missed something?  Or is there a way of saving the file contents along with the fact that it has been signed?  I guess if signatures are performed at the block level rather than the file level then this is hard.

**Comment by strib** [comment]
KBFS doesn't sign individual files (or blocks); instead, we organize the folder into a merkle hash tree and the writer only signs the root on each update to the folder.  The signed root for every folder gets hashed into the blockchain once an hour, so in theory it is possible to build tools to prove that a given version of a folder was signed by a particular user at a particular time, but we don't currently expose a way to do that through the KBFS interface.  We are considering it for the long term, but it's not on the short term road map.

**Comment by alanbowman** [comment]
OK, that's pretty clear.  Thanks.
