### ISSUE TITLE
Creating private share with user who doesn't have a key setup causes finder/terminal to hang when navigating the folder for that share in KBFS

### ISSUE THREAD

**Issue by nathankleyn** [keybase/client#3284]
If one creates a private share with a user who hasn't setup their PGP key yet, going to the directory for that share on the KBFS causes CPU usage to spike and long periods of hanging in Finder and on the terminal.

**Steps To Reproduce:**
1. Setup a share with a user who hasn't setup their PGP key yet.
2. Navigate to the directory for that share in either Finder or in a terminal.

**Expected Behaviour:**

There should not be any hanging and the folder should open successfully, or perhaps display some kind of warning/error.

**Actual Behaviour:**

Finder and terminal applications hang if the folder is opened.

my log id: 34beb0800fadd61bc5595d1c

**Comment by strib** [comment]
Hi @nathankleyn, I see in your logs where you were trying to open a folder with someone without keys, but I can't find evidence of any hangs.  Can you give an approximate timestamp when this happened?

Or maybe better yet, reproduce it and then do a `keybase log send` right away, so I know that it's the most recent thing that happened in the log?

Also, I'd be interested to know if you can figure out which process name is using the CPU. Thanks!

**Comment by strib** [comment]
Hmm, though it looks like in the meantime the user you were interacting with now does have keys, so it might be hard to reproduce the same way.  I guess you could find a random Keybase user without keys?

**Comment by nathankleyn** [comment]
Hey, I'm so sorry! I never saw notification for these comments! The issue appeared to be transient, dunno exactly what happened but it never hung again in the same way. I'll close and reopen if it ever happens again.

Keep up the great work! 👍
