### ISSUE TITLE
"Which device would you like to connect with?"

### ISSUE THREAD

**Issue by tobyjaguar** [keybase/client#3294]
![screen shot 2016-06-30 at 6 28 11 pm](https://cloud.githubusercontent.com/assets/16940072/16506660/dcd4d79a-3ef1-11e6-9772-d02fb0950f9e.png)

I just installed the keybase app on my OS X 10.11.5 machine and logged in which prompted me with this...what is this? I believe the first option is an old VirtualBox drive...

**Comment by strib** [comment]
`deborah_vview` is a machine on which you installed Keybase, on May 3rd: https://keybase.io/talgya/devices

`dream multiply` is the public label for the paper key you created at the same time, which should be written down in your wallet.

**Comment by tobyjaguar** [comment]
hmm...well that clears that up. Thank you.
