### ISSUE TITLE
Feature request: Don't start keybase automatically at login

### ISSUE THREAD

**Issue by casey** [keybase/client#3311]
After installing keybase on OS X, it starts whenever I login in, and pops its window momentarily.

Looking at my login items on the Users & Groups page doesn't show keybase as a login item.

It should register itself as a login item, so that I can disable it from starting automatically.

**Comment by libeclipse** [comment]
Related: #3302

**Comment by libeclipse** [comment]
I agree that the GUI at least should not open on login.

**Comment by jsejcksn** [comment]
Keybase should not run or mount unless I want it to. Users shouldn't be forced to run the app all the time (including persistently across restarts).

The only way I have found to avoid this issue is to uninstall keybase when I am not using it, but even then, `keybase.Helper` is still running.

**Comment by hirschnase** [comment]
+1 for this!

**Comment by garhirunrat** [comment]
First time okay
second damm stop it! whyyy???
third mmmm should I delete the app?...
forth Google "delete keybase mac"

**Comment by feamcor** [comment]
+1K for this!

**Comment by joeunrue** [comment]
You can remove the keybase* files from ~/Library/LaunchAgents and it won't auto launch until the next time you manually launch the app at least, when the files are re-added.

**Comment by JiriKacirek** [comment]
It's 2019 and this issue is not fixed. Keybase cannot be even removed from "Login items" because it will appear there again during the restart.

**Comment by eli-schwartz** [comment]
On linux, keybase creates a sentinel file in the configuration directory which tells it not to recreate the autostart file. `keybase ctl autostart` is used to provide manual control over enabling/disabling it.

Maybe keybase should do the same or similar on other OSes as well.

**Comment by heronhaye** [comment]
In Keybase 5.0, you can change this setting in the GUI on all platforms. Please make a new issue if you are still having trouble. Thanks!

@JiriKacirek, please change this option from the Settings tab in the app. It will not reappear.
