### ISSUE TITLE
Spurious "This computer and possibly others are unable to read some of your folders"

### ISSUE THREAD

**Issue by zanderz** [keybase/client#3313]
I got this message to turn on one of my other devices because I wouldn't be able to read my folders, but I was signed into one of the ones listed, and my folders worked ok. It popped up a couple of times after dismissing.
![image](https://cloud.githubusercontent.com/assets/862397/16535162/2698e2ce-3f9a-11e6-8585-c6d6cafdba2b.png)

my log id: 918f188e0894dc248115a61c

**Comment by maxtaco** [comment]
FML

**Comment by zanderz** [comment]
Aw! Is this a blocker or should this build go out?

**Comment by maxtaco** [comment]
This is likely related to reader rekeying not working as I have mentioned
in kbfs tickets be we need to examine further

Steve please move discussion to Jira.

**Comment by zanderz** [comment]
Moving to https://keybase.atlassian.net/browse/CORE-3317
