### ISSUE TITLE
Sign git commits

### ISSUE THREAD

**Issue by meeDamian** [keybase/client#3318]
It's more of a meta question/suggestion than the actual issue, but…

**Why don't you guys sign your commits?**

It's quite trivial to set up and even to link with your Keybase identities. It seems like quite a reasonable thing to do on a security and privacy concerned, E2E encryption project :).

**Comment by cjb** [comment]
Speaking for myself, just being lazy and habitual. We do sign all of our software releases, of course. But if you want to imagine it's *actually* a principled stance of ours, here's Linus telling you not to do it:

http://git.661346.n2.nabble.com/GPG-signing-for-git-commit-td2582986.html

**Comment by meeDamian** [comment]
That was quite informative. Now I'm wondering why that option exists there in the first place…

Anyway, thank you! And closing.
