### ISSUE TITLE
Windows 10: no icon on system tray

### ISSUE THREAD

**Issue by hacdias** [keybase/client#3321]
Hey!

I've installed the new version of Keybase's application for Windows and there is no icon on system tray until I open `C:\Users\Henrique Dias\AppData\Roaming\Keybase\Gui\Keybase.exe`. Is that supposed to happen? I thought it should appear on startup, but I rebooted the laptop and nothing happened.

One more thing: you should change the icon of the app. :)

Thanks! :D

**Comment by zanderz** [comment]
There are supposed to be 2 shortcuts in `%appdata%\Microsoft\Windows\Start Menu\Programs\Startup` after installation, otherwise something went wrong. Can you do `keybase log send` and provide the log ID?

Thanks.

**Comment by hacdias** [comment]
Hey!

Actually, there is a GUIStartup in there, and there is a process called runquiet on task manager. But there's no icon in the tray. 

I sent the log anyway, but I received this error:

`- WARNING error opening log "C:\\Users\\Henrique Dias\\AppData\\Roaming\\Keybase\\keybase.start.log": open C:\Users\Henrique Dias\AppData\Roaming\Keybase\keybase.start.log: The system cannot find the file specified.`

The id is `ddd4ca92afe16c41e81d6a1c`.

Thanks!

**Comment by zanderz** [comment]
Thank you. Logs indicate a browser window crash - we will investigate further.

**Comment by hacdias** [comment]
You're welcome.
