### ISSUE TITLE
- ERROR Access is denied.

### ISSUE THREAD

**Issue by aburgd** [keybase/client#3327]
Any command with a verb (like `keybase login`, `keybase pgp list`, `keybase search [user]`) returns 
`- ERROR Access is denied.` on Windows 10 build 1511, keybase version `1.0.16-20160701140709+9c6469c`. 
Below are the folder and file permissions dialogs for my user account.
![File and Folder Permissions](https://cloud.githubusercontent.com/assets/6305821/16572679/d82b0c04-4230-11e6-815a-ef9f48b177e4.png)

my log id: 8b3971fb89ca09569c7e371c

**Comment by zanderz** [comment]
Do any commands work, such as `keybase cert`?
Can you please add a screen cap or text copy of running `keybase --local-rpc-debug-unsafe=vips --debug=1 ping` ? (The "unsafe" in the name of that argument is a warning for use with more sensitive commands than ping.)
Thanks.

**Comment by maxtaco** [comment]
@aburgd please don't do that above, that will reveal private information!

**Comment by aburgd** [comment]
Running `keybase cert` still returns `- ERROR Access is denied.` 
![](http://puu.sh/pRf18/1709312083.png)

**Comment by zanderz** [comment]
After some conferring, we agree that the results of `keybase --local-rpc-debug-unsafe=vips --debug=1` are safe to share for commands like `cert` and `ping`. (Other commands may log sensitive secrets when used with that flag.)

I can reproduce this if I run the service process under elevated admin permissions and issue client commands without elevation. Is it possible that the process launches as a different user? or was installed as administrator? One way to check would be to end all running keybase.exe processes and try issuing the commands again.

**Comment by aburgd** [comment]
It is possible that the client was installed as admin (was trying to resolve an issue that dealt with Avast's Hardened Mode). 
***
After ending all of the keybase.exe processes and running `keybase --local-rpc-debug-unsafe=vips --debug=1 ping` results in the following https://gist.github.com/aburgd/4884c54c7dcc75724b1d650a0ca66272

No error this time.

**Comment by zanderz** [comment]
I believe that if you were to uninstall and then reinstall as regular user, it would be OK.

More vexing is how hard it is to distinguish this case in the logs - I thought the pipe would be named differently. We will look into adding some more debugging.

**Comment by aburgd** [comment]
Uninstalling and reinstalling did the trick - thank you for your help! I'm glad I could assist with further development.

**Comment by ereli** [comment]
I have the same issue.
reinstalling it doesn't help.
it only works if you open cmd.exe with admin privileges.
If you thought about reinstalling as normal user - you can't. the setup won't execute as a regular user.

**Comment by zanderz** [comment]
@ereli Normal user in this case is someone with permission to install software, not running "as administrator" with elevated privileges but possibly in the administrator group. It definitely works if installed this way. Sometimes a corporately administered PC has restrictions on installing things, for example. Also, reinstalling means uninstalling the old one first. Note that you may need to also uninstall "Dokan Library Bundle" before launching the newer installer .exe.

What error message do you get when you try to install?

**Comment by ereli** [comment]
I just downloaded the latest build (`keybase_setup_386.exe`).
![image](https://cloud.githubusercontent.com/assets/1475340/26742435/900c16ce-47d5-11e7-9183-fe5b2b2ad16f.png)

The installer starts and exists after couple seconds - not dialog appears on the screen. 
I'm on
```
OS Name:                   Microsoft Windows 10 Pro
OS Version:                10.0.15063 N/A Build 15063
```
is there a way to turn on some logging so we'd be able to see where's the error?

**Comment by zanderz** [comment]
It should leave logs already, look in '%TEMP%\Keybase*log`. I'd be interested to see what's in there.

**Comment by ereli** [comment]
It doesn't say much
```
[26A4:1428][2017-06-02T13:34:35]i001: Burn v3.10.2.2516, Windows v10.0 (Build 15063: Service Pack 0), path: C:\Users\User\AppData\Local\Temp\{19078315-2B42-48D6-B342-66868572AB7B}\.cr\keybase_setup_386.exe
[26A4:1428][2017-06-02T13:34:35]i000: Initializing string variable 'DokanInstallFolder' to value '[ProgramFiles6432Folder]Dokan\Dokan Library-1.0.0'
[26A4:1428][2017-06-02T13:34:35]i009: Command Line: '-burn.clean.room=C:\Users\User\Downloads\keybase_setup_386.exe'
[26A4:1428][2017-06-02T13:34:35]i000: Setting string variable 'WixBundleOriginalSource' to value 'C:\Users\User\Downloads\keybase_setup_386.exe'
[26A4:1428][2017-06-02T13:34:35]i000: Setting string variable 'WixBundleOriginalSourceFolder' to value 'C:\Users\User\Downloads\'
[26A4:1428][2017-06-02T13:34:35]i000: Setting string variable 'LOGPATH_PROP' to value 'C:\Users\User\AppData\Local\Temp\Keybase_20170602133435.log'
[26A4:1428][2017-06-02T13:34:35]i000: Setting string variable 'WixBundleName' to value 'Keybase'
[26A4:1428][2017-06-02T13:34:35]i000: Setting string variable 'WixBundleManufacturer' to value 'Keybase, Inc.'
[26A4:3A88][2017-06-02T13:34:35]i000: Setting numeric variable 'WixStdBALanguageId' to value 1033
[26A4:3A88][2017-06-02T13:34:35]i000: Setting version variable 'WixBundleFileVersion' to value '1.0.23.789'

```

That's the entire log.
I'm using the default UAC settings
![image](https://cloud.githubusercontent.com/assets/1475340/26744245/fd7ab38a-47dc-11e7-8ffd-914216a1d448.png)

**Comment by zanderz** [comment]
this is really weird. Everything else is uninstalled? What if you invoke it with the '/layout' option? That's supposed to log what would happen without actually installing anything.

Do you have any actively blocking AV software installed?
