### ISSUE TITLE
KBFS won't start on OS X 

### ISSUE THREAD

**Issue by zerotao** [keybase/client#3328]
keybase.kbfs continually exits with "Service exited with abnormal code: 2"

my log id: b530812712fc4e2eb66f6f1c

**Comment by strib** [comment]
Hi @zerotao -- are you running as a user with admin privileges in OS X?  From the KBFS logs, it seems like the user doesn't have permission to mount a file system:

```
2016/07/05 08:15:43 mount helper error: mount_kbfuse: failed to mount /keybase@/dev/kbfuse0: Operation not permitted
```

**Comment by zerotao** [comment]
hmmm, yes I am running as a user with admin privileges. Turns out I had a /keybase directory with bad permissions from a prior install.

**Comment by ringods** [comment]
Is there any option of running Keybase in a regular non-admin user account? I run all my software from a non-admin account, so why should Keybase differ?
