### ISSUE TITLE
"Possibly revoked data"

### ISSUE THREAD

**Issue by lucasantarella** [keybase/client#3344]
Not sure what's going on here but all my devices give me a "Possibly revoked data" error when I try to view my private folder on KBFS. Please help!

my log id: cd380b3df2a5d2e4bca1561c

**Comment by lucasantarella** [comment]
I read somewhere that you can manually reset my folders if I post a signed message. Here ya go:
```
BEGIN KEYBASE SALTPACK SIGNED MESSAGE. kXR7VktZdyH7rvq v5wcIkHbsJVF6jf f7X6xg9CVy4f4nY 9ekugevkV54JHEK 2swQgbyg951W2Ts ASIu6u80226DZ1j Ll98IdWzTbj3wn7 rK2qimRU5IrR9RJ NETBX4DucR4epou f7gi0IuBRt4oGbu P0m0I9hYkL3Idcz FOE294XU9OW9xv4 s4bMD1Dds1qT5YL RWfrk7vB0846Its nBcbV7gB2Yf9TJL r26xlNQ7Dg90MeF xOUVSIWH4xMDgjp QW1RMYKMgLpVxNO v2BUpsFuHPmqWid mnX55dsP46cEnUS JO3sonCHNAwL9ZK jD6NPKwEYwW2gLd JzreJkuX50EOFnN 6qgmZweKTVjVFtr yPnf4pgcaRZe8vJ DK5he5iihbMUYnm HCdnGW8ikTfZUOJ jiGku79ZN7keYMn dIWx66J8VAd7NnK OiZU4JyH60BWhdS e0qiYPjItuTk134 XYbsEBo9GNLnnou . END KEYBASE SALTPACK SIGNED MESSAGE.
```

**Comment by strib** [comment]
Hi @lucasantarella -- I can't access our servers at the moment, but I'll reset your folders when I get to the office in the morning.

**Comment by lucasantarella** [comment]
Thanks a ton!

**Comment by lucasantarella** [comment]
Accidently closed...

**Comment by lucasantarella** [comment]
Hey @strib can you let me know when you reset my folders? Not to sound like I'm rushing or anything, just let me know so I verify that it's working again.

**Comment by strib** [comment]
Ok done.  Please close if things look ok.

**Comment by lucasantarella** [comment]
Awesome! Thanks so much!
