### ISSUE TITLE
Install of OS X Keybase GUI app does not install/launch any kbfs or fuse services

### ISSUE THREAD

**Issue by nugget** [keybase/client#3350]
I'm trying to get KBFS working on one of my computers and it doesn't seem to install any of the pre-requisites.  I've tried uninstalling and reinstalling (via brew and via the DMG app) as well as manually installing fuse (also via brew)

`keybase fuse status` says:
```{
  "version": "",
  "bundleVersion": "",
  "kextID": "",
  "path": "",
  "kextStarted": false,
  "installStatus": 2,
  "installAction": 4,
  "mountInfos": null,
  "status": {
    "code": 0,
    "name": "",
    "desc": "",
    "fields": null
  }
}```

OS X version 10.11.5 with nothing particularly wonky.

my log id: 4e960eb1c165f24ddb095e1c

**Comment by cjb** [comment]
CC @gabriel

**Comment by ghalfacree** [comment]
I'm seeing the same issue with macOS 10.12 Beta 2. The Keybase File System was working fine prior to upgrading to the beta, but has since broken. The GUI app appears to work fine, but Finder cannot open the /keybase directory and attempting to change directory to /keybase (or any subdirectory thereof) at the terminal gives a "permission denied" error. As with @nugget, the fuse status reads as blank.

Tried deleting /keybase and letting Keybase recreate it; no change. Tried adding the execute bit; I can open the directory, but its contents is empty. Tried uninstalling Keybase completely and reinstalling from the latest download; no change.

Versions:
Client:  1.0.16-20160630135211+c643773
Service: 1.0.16-20160630135211+c643773

**Comment by cjb** [comment]
@ghalfacree Thanks.  This might not be the same bug as above, since the person who opened this issue was not on the beta.  I don't think any of us at Keybase have tried the beta yet, so it's not very surprising that it's not working there -- we'll check it out.

**Comment by gabriel** [comment]
@nugget Can you try installing the latest bleeding edge here:
https://prerelease.keybase.io/darwin/Keybase-1.0.16-20160707110020%2Bee537fc.dmg

If that doesn't work, can you run this (and post the output):
```sh
/Applications/Keybase.app/Contents/Resources/KeybaseInstaller.app/Contents/MacOS/Keybase --app-path=/Applications/Keybase.app --run-mode=prod
```

**Comment by nugget** [comment]
Thanks for reminding me to update.  For better or for worse, a reboot seems to have magically resolved whatever the problem was with the machine in question.  Similarly for another machine onto which I installed the client where I experienced the same problem.

I've now set up the GUI and KBFS on three machines.  One went as expected and two exhibited this problem where after install the keybase client appeared unable to locate fuse or some other problem which blocked the /keybase file mount.  Both of them started working after a reboot.

In all three cases I had a much older version of the keybase client installed (via OS X homebrew) and my assumption is that the installer somehow fails to completely remove/stop/something that old client.

Unfortunately this means that the KBFS stuff is now working on the two affected machines, so I'm not sure how valuable my testing can be.

**Comment by nugget** [comment]
Also, for what it's worth, I did spend some time doing some blind poking and prodding with "keybase launchd" restarts and uninstall/reinstallations when the machine was in its inconsistent state.  I was never able to discover any action which got it working until the reboot.

I hate this kind of bug report too, but that's where I am right now.

**Comment by gabriel** [comment]
Yeah I saw in the logs that a previous homebrew version was there, which should be ok (the installer should uninstall that service and unlink it).

I did see in the log the installer crashing which would explain it not working.

If you get a chance could you send me a log id from what a machines that got fixed after a reboot?

**Comment by nugget** [comment]
Here's the same machine now that everything works: ab44f482e4acde6c52fab51c

**Comment by gabriel** [comment]
@ghalfacree I can repro your issue and am working on a fix... fuse support is currently still technically experimental on 10.12 so need to flip some bits... Will probably be a couple days before a fix

**Comment by gabriel** [comment]
@ghalfacree Looks like more than a few days for 10.12 support... golang currently has issues as welll as fuse, https://github.com/golang/go/issues/16272

**Comment by gabriel** [comment]
@ghalfacree he is a experimental build with 10.12 support https://keybase.pub/gabrielh/Keybase-1.0.16-20160719202255%2Bc44efcc.dmg

before installing, you should run: `keybase uninstall` from the command line (or reboot after installing would work too)

**Comment by ghalfacree** [comment]
@gabriel Thanks for the experimental build, but unfortunately it doesn't appear to have made any difference. I ran `keybase uninstall`, installed the new build, ran it, got the same "permission denied" error when attempting to access /keybase. Deleted /keybase, rebooted, ran keybase, same error again.

**Comment by gabriel** [comment]
Here is a build which supports macOS 10.12 (Sierra):
https://prerelease.keybase.io/darwin/Keybase-1.0.17-20160817191833%2Be83e8a5.dmg

**Comment by meeDamian** [comment]
`MacOS 10.12 Beta (16A294a)` && `Keybase 1.0.17-20160817191833+e83e8a5` still not working. Did run `keybase uninstall` and did reboot. Can I submit something that might help you guys?

**Comment by cjb** [comment]
@meeDamien Please run `keybase log send` and report the ID, thanks!

**Comment by meeDamian** [comment]
Sent, and here's the id: `29952bf8ed22b1fb20ac391c`

**Comment by cjb** [comment]
Thanks, CC @gabriel

**Comment by ghalfacree** [comment]
Same experience as @meeDamian: the new build exhibits the same issues as previous builds, running macOS Public Beta 6.

Log ID: 9fee8bf20451d67d06af2b1c

**Comment by meeDamian** [comment]
I just noticed that I have a couple more volumes mounted:
<img width="282" alt="screen shot 2016-08-24 at 00 07 23" src="https://cloud.githubusercontent.com/assets/526657/17899776/040bd90e-698f-11e6-9e6a-d7c349ae6cd7.png">

```
/Volumes/Keybase
/Volumes/Keybase 1
```

Not sure if 3rd is related, but I think it wasn't there before:

```
/Volumes/FUSE for macOS
```

**Comment by gabriel** [comment]
Sorry it's not working, and thanks a bunch for helping us debug this! For some reason I'm not able to repro directly.

Can you try running this version:
https://keybase.pub/gabrielh/Keybase-1.0.17-20160824235155%2B51f7870.dmg

It has some extra debugging in it.

When installing that dmg, can you do the following:
- Quit Keybase.app
- Copy from that dmg to /Applications
- Run `keybase ctl stop` from command line
- Then `open /Applications/Keybase.app`

**Comment by gabriel** [comment]
@meeDamian those mounts are from the dmg's.. you can safely unmount those to have them go away

**Comment by gabriel** [comment]
We've found an issue where the kext isn't loading on some Sierra installs, so the the version posted above still may not work. I'll post an update when we have a fix for that.

**Comment by gabriel** [comment]
We found an issue when upgrading to Sierra, this build should work:
https://keybase.pub/gabrielh/Keybase-1.0.17-20160826020144%2B61c0667.dmg

**Comment by meeDamian** [comment]
Thanks for updates @gabriel! 

The latest version does indeed work, but only partially and it's **really** unstable. 

examples:
Running `ls /keybase` or `ls /key<tab>` hangs indefinitely and freezes Finder completely: neither `^C` nor closing the terminal window helps.

Running `keybase uninstall` hangs in the same manner just after printing out: `INFO Stopping homebrew.mxcl.kbfs`

As far as I can tell now, only reboot helps.

Typing full commands by hand as: `ls /keybase/private/meedamian` or `cat /keybase/private/meedamian/someFile.txt` works as expected (I'd even say faster than it did before).

Log ID: `fb256677f38c4a838099761c`

Versions: `MacOS 10.12 Beta (16A304a)`, `Keybase Client: 1.0.17-20160826020144+61c0667`

PS. sorry for this https://github.com/keybase/client/issues/3350#issuecomment-241787382 😂

**Comment by gabriel** [comment]
Yeah, the old version was hang city, and in a way only a restart could probably handle.

**Comment by meeDamian** [comment]
> the old version

the _new_ version being `1.0.17-20160829110024+c4e8dc8`?

**Comment by gabriel** [comment]
After upgrading to `1.0.17-20160826020144+61c0667`, it might require an OS restart.

So, if you update to that build 1.0.17-20160826020144+61c0667 and restarted the OS and you are still seeing weirdness/slowness it sounds like a perf issue? If so we should probably open a new issue and get another log ID?

Thanks for help debugging.

**Comment by meeDamian** [comment]
After upgrading to `1.0.17-20160829110024+c4e8dc8` and a reboot everything kbfs-related works as expected and is pretty responsive. I presume the issue might be closed now (and the perf issue is not needed).
