### ISSUE TITLE
Can't abandon a proof from client

### ISSUE THREAD

**Issue by mhalano** [keybase/client#3370]
I created to http proofs inadvertently. On efrom my domain, that's ok, but another for a common subdomain (www). I want to abandon that, but there is no way to do this via keybase client, just web and I need a PGP key (I still don't have one).

**Comment by maxtaco** [comment]
Try

```
keybase sigs lists
keybase sigs revoke <sig-id>
```

That should do it....

**Comment by mhalano** [comment]
@maxtaco 
Thanks, work pretty well. But shouldn't have a easy and more intuitive way, something like 'unproof' or 'prove --revoke'?

**Comment by maxtaco** [comment]
Yes, 100%

We hope to hit parity sometime with the website and make the website read-only, but Rome wasn't built...
