### ISSUE TITLE
Copy .rar issue

### ISSUE THREAD

**Issue by BrendanJ** [keybase/client#3374]
Keybase GUI Version: 1.0.16-20160701141100+9c6469c

I've never seen this error before, so I believe it has to do with Keybase. I'm attempting to copy a .rar archive from a folder on my computer to a private Keybase folder. About 5mb into the copy, it stops copying and gives me this error message:

> An unexpected error is keeping you from copying the file. If you continue to receive this error, you can use the error code to search for help with this problem.
> 
> Error 0x80070057: The parameter is incorrect

http://i.imgur.com/H2XUqTR.jpg

I've tried with .zip and .rar archives, both are roughly 180MB

**Comment by strib** [comment]
Known issue with files larger than 5MB.  See #1981.  Actively working on making it work better for large files.  Sorry for the inconvenience!
