### ISSUE TITLE
Can't access kbfs private folders after reset my keybase account

### ISSUE THREAD

**Issue by imolein** [keybase/client#3423]
Hi,
after I reset my keybase account and start from scratch, I can't use my kbfs private and public folder anymore. Even if I delete the folder and recreate it, I became the message that this folder was modified by a revoked or bad device. This also applies to all shared privat folders, which where created before the reset.
Is it possible to reset the folders too or did I oversee something?

my log id: 115808e791022302f118141c

Thanks in advance

**Comment by strib** [comment]
We're working on an automatic way to reset your folders but it's not ready yet. We can reset them manually, but we need your signed, public permission. If you want us to do that, please run the following command on one of your devices, and substitute the current date and time as indicated:

```
keybase sign -m "<DATE_AND_TIME>: Please completely reset folders /keybase/private/imo and /keybase/public/imo because I reset my Keybase account."
```

and post the output here.  If there are other shared folders you want to reset as well and you don't mind naming them publicly, please add them to the above message.  If you don't want to expose who you are sharing data with, you can make a second message with those folder names (in the same format as above), and encrypt them just for me, like so:

```
keybase encrypt -m "<DATE_AND_TIME>: Please completely reset folders <FOLDER_NAMES> because I reset my Keybase account." strib@github
```

Note that you will lose all data in any of the reset folders.  We are close to having our automatic folder reset stuff ready, which would just move the data out of the way and keep it accessible to users that haven't been reset, so you might prefer to wait for that feature as an alternative to the above.

**Comment by imolein** [comment]
Thanks for the detailed answer and here are the permisson's. 

Signed message for reset of privat and public folder:
`BEGIN KEYBASE SALTPACK SIGNED MESSAGE. kXR7VktZdyH7rvq v5wcIkHbsMxbYKz siCPvBzDObrjTqA s31nuaVkAaE3QM7 Pewu2eQBI5jsRAC n6x621zGmbKNdQt 523zNiNPTT3Qu9o R9XVIURT5WefGOt XHFGZGgdQSfAIZb SrbORTwh0eEcOcP hOgWDvCRjRqe1RM OS01HZ69i7Lj27A HPoOM4IauPaGGaP eocEgSJDx9qgyCN WzbA2BQysmNm2eB sx3lR811cLEuWAX qdsGxdDS6RpHnFP H5ZRXIwAKlgrVKP KzFyIO0xMtndcPk RyTapsy8eyx9biN NQAytu3cplGhoRB s1P817omA9uirMD DCYU0RvyKuK0xV7 h2JNJqOxPr18Wtz 9kPLG2BuT0sQk0B 7xGiBljyfrUZCUe 5PHsr2DEE393SPU pLB5U6LcE3oWuWj dWVFEBjolV1vrlH ERDJQ7QqtMpxgoa JO7H8g6yM5XJcUw wm3YNnc. END KEYBASE SALTPACK SIGNED MESSAGE.`

Encrypted message for shared folders:
`BEGIN KEYBASE SALTPACK ENCRYPTED MESSAGE. kiVagqKWSHjJD0o 7vgiRxqIgj1fGBh cp4jpp7tHnzJyJ4 yIt7Tk4W3FDIKk3 lNJGuqD3SMxVcGk sw0y9DNLZSRGzT3 uGzI522p7hIw2eF IvqXL6Es5oX2riq Wz8P8vVTSscv0uj CuVjl6Ao4u9LBAU KPZfTsxTjFwVSEg 7rO0RsrNvNu86EA GTmnJ5Eakh6UuLX M5USvyfc2sXSJp5 UvHvseRgn1wgeJO YobJ5ErwPTiThMS IBsnivBbFAaGWqA jlfFYZFiJJpF8gr G8pDpfN0t7SdxCM 22kcDAqbrxTJshE 0n3JNqCKFUvVQ61 joZA2TjjGXS4NQB ZVpk21xG03Q1Z1M c83rCxMEgNMWhIj 4nK7vdDJopDfKsu lymKZZAl75VIrU4 45lHNYSG0FUyg4U NHi8ph9YIshaGcQ o8Jow83xjqVWlaJ iP3aoRms0LQcYg8 vxMctXG8Tza6IPK nLbo9h2CphRlKq0 y4x387XDNWuNgnV tTuj6jDSUSgsKvt K0921E0dN15mrij 4eeE6bW5LY8YWqL 1if1Yzl9671EFHZ Xr7OpM77bm2yIi7 IXD05MZ6sN4uJsE 5cZOkwvpa8Mm3WH 38JjDYNierrrPq1 y2HGeNZUtSzhuqo rhsRgDsTAy3nTiR 2AwPckBBIzv4Zd2 KVX06OAM5tRqqlx yxV4mFyZ96RPC4V WrPgPU3ehYIhgvn WOEKDRqkdnB4X19 OFpYBzH53tFBX3c qnUPuz7LuWNW1Jn oUx0WELs1v1XD5A CJJPMozGVKJ90IQ ZApMamfElfSDZRu ftOxw9qNVS5jU29 eBpY6R0jZkqBfiI p8BXhuM9TQ0qHeZ LuoHO10Me6TvcfU hRtdZ7FobgCKn6q qYRJ0tEgMSSf8VQ qWiSADO8O2fU3eq MFYf2BqGkT111Qo fPiOV1KXm2ELCtn QyvkpQ2OY3a5JuI Q4uvT2VVQAD5Y8b 7LYRINT2cypFxeW 8TkMz4wygubtFdU AtiQQelLHbIq5UD c2DrX68A4jSDkZY eATbL8v2mAznmZ7 rUdhYs4EZ1XMrbb lBzBYxvqCkvYKhw MzXuUZv1Z7X87IP Rrxh1r6zDcHhkot OmIMZO8cXGJKLOM NfSdzqgg14USEng 0n9hFFDJSsz11zZ jTmrO8hcthOXok0 iQHs2Y8RbALLDU8 2nKNfQJBhSTdTrq coutKZa1MOA9vpo fMUxmMvXxtxRcEN DLELVkiZoCVCHHh TOpbbtCJ4hB7WJI wCng2q4iqzyAtnw 66x7D4S95DA2aPl sSoHNzoYxmSnpJI mP9MlTCxtFeyLLQ G9w5dG8eKZWWF6N kYqPPLLZudGwNoy C9suggsf3Asz0OZ SjAA04AXCoWduES nOcGtHXseyOjD6f KR8tJpSp0igDQTH Up6V2Ght17A1B6B y0X7PHjqLfKvpPQ uTDecm1prsDZBZF ohmq3VFiCdNUkd0 mZ6nnbMbPhoQOvF DHw0Eg1M7nqPGD6 VrIcpx87q9oYU9V yVDo7ITW5zRwSg5 EowRNu1LhB24YqC A5TZcYSxoV2rPWy Sb8F9x1vklwFIiw 5QE0FTNgAoyq1LR dFJLpBU2Wfs6m44 XS40roXSWwRNni6 6uXmvixtt1JJRrl SHNYntfM0OrPHyH sYbMoNVuAAofKyq 4DrAcnuIUYwthxV Nme0rfbn6Ge5Mbl CeBD0aDLXFt2wJ8 26IliEmfub1D4B6 GcnSG4SzcWMDNvr 8SCBfLhL8FKmOBB 3nOxjJDAKIlbgrZ Vdq0hYPoODwLpK4 FKu8AuijQyoxo68 ClsLC3PafhbD0gl 1yRj07Abj3KgZ1U PUN2Sq5D6qnGD56 MRqYbO0g2OTF5uT QJ8jON0d9EXtMmA vpyn5tV2qWi5O10 akKlQjo3koyrpwT bHgRQxjkntCLRYF w1OzzqRxVHixOhn arSRlXtOUIJxuZk XcGQP0ZZwalav2I gSIpntD5w16kwlH BtSLF53WOQBJJkV T1CtUbFjrxEgJir Qt7e8MrE2Y9X7oL JFyOna0A4iYr0ea TOrUSRz7TXgjFDi 9yYfp3VhiNM46kD gAwCm8OlvWlowb7 BRpgUEJ4Crc95fR Zg81TT35Hta6Ldl UtWqX3Y7ZDDZ9lG fisi4KXpLo4hycC 2eHbz8YB7efssUU eNySc5IcXjWAk08 DpCV9GTmpVZX4B4 jUCE6GjJih. END KEYBASE SALTPACK ENCRYPTED MESSAGE.`

The data in the folders are not important. Since I'm not planing to reset my account often, it will work for me. :)
Thanks for the great work!

**Comment by strib** [comment]
Ok, all the folders have been reset.  Please check them out and close this out if it seems ok.

**Comment by imolein** [comment]
Thank you, it's working.
