### ISSUE TITLE
Keybase: Possibly revoked data detected

### ISSUE THREAD

**Issue by YAAK** [keybase/client#3427]
After several times resetting my key and start from scratch, when trying to open my public folder, I'm receiving this error message:

> Keybase: Possibly revoked data detected. /keybase/public/{{my_id}} was modified by a revoked or bad device. Use 'keybase log send' to file an issue with the Keybase admins.

my log id: 52200e8520a5dac96a7abf1c

BEGIN KEYBASE SALTPACK SIGNED MESSAGE. kXR7VktZdyH7rvq v5wcIkHbrxINrDl qJF8L7914KWKG7I yFhP9lYYt5fU7hW iVTVJ7RFGz3IIcm EhcRiHqJPU6PzMA 5oYv746NOUVFy8r fxax9KHYc4cMsE9 CjR6Rglknaca2b5 lUGvnVywSrn27dO Hk6uJMl23SD0ZQ3 HhmcU8KtU5lsLr5 a4AsYFQ7S6YWwGy MXVlUGBbd1daCdX kRiqmJ4OQO97AIn scTIR5IIImNULc4 ZNzE3Pdni09N1Gy SA4BFALhhW2kpUx Zl5HWoag4Lgq4bk lcll88SZQtn7WpE XRMYKMgV9T24fCM zXbHIvxv3TazJhs AWamNjHnn17pLJS ioDOXQR0baoJXC9 U03UDGSwH6PsWje rmLDggjtfTdEDlA bisBVSyRC1IroYq GkPERFRlotuxih4 H89UsAi5nPFGJC3 K1IbZ0qw8HAu3XV EQAMpcMcXU8. END KEYBASE SALTPACK SIGNED MESSAGE.

**Comment by strib** [comment]
I reset your public folder.  Looks like your private folder was created recently and doesn't need a reset.  Please try them out and close this issue if things look ok.

**Comment by YAAK** [comment]
Amazing! Works like a charm! Thanks @strib
