### ISSUE TITLE
[Linux] Keybase GUI can't connect to socket

### ISSUE THREAD

**Issue by DerEnderKeks** [keybase/client#3451]
If I execute `run_keybase` the GUI doesn't open.

In the log files it says:

> log: Wed Jul 13 2016 05:45:17 GMT+0200 (CEST) (1468381517579): RPC [I] localhost: connecting (attempt 892)
> log: Wed Jul 13 2016 05:45:17 GMT+0200 (CEST) (1468381517580): RPC [W] localhost: Error: connect ENOENT /keybase/keybased.sock
> From Keybase: log: Wed Jul 13 2016 05:45:17 GMT+0200 (CEST) (1468381517593): RPC [I] localhost: connecting (attempt 891)
> From Keybase: log: Wed Jul 13 2016 05:45:17 GMT+0200 (CEST) (1468381517593): RPC [W] localhost: Error: connect ENOENT /keybase/keybased.sock
> From Keybase: log: Wed Jul 13 2016 05:45:18 GMT+0200 (CEST) (1468381518508): RPC [I] localhost: connecting (attempt 892)
> From Keybase: log: Wed Jul 13 2016 05:45:18 GMT+0200 (CEST) (1468381518509): RPC [W] localhost: Error: connect ENOENT /keybase/keybased.sock
> Only one instance of keybase GUI allowed, bailing!
> Only one instance of keybase GUI allowed, bailing!

With `sudo run_keybase` the GUI opens but it still can't connect to the socket.

I'm using Linux Mint 18 (Cinnamon).

my log id: ed5d0fd0642901330106191c

**Comment by cjb** [comment]
Please share:
```
echo $XDG_CACHE_HOME
```

**Comment by DerEnderKeks** [comment]
It's empty. (Or maybe a `\n`)

**Comment by cjb** [comment]
Okay, try:
```
XDG_CACHE_HOME=$HOME/.cache XDG_CONFIG_HOME=$HOME/.config run_keybase
```

**Comment by DerEnderKeks** [comment]
How can I completely stop keybase? (It doesn't start because there is already an instance running..)

**Comment by cjb** [comment]
That's odd.  run_keybase is supposed to kill it for you.

`killall keybase` should do it.  But that's already part of `run_keybase`, so I'm confused.  You could share `ps awfux | grep -i keybase`.

**Comment by DerEnderKeks** [comment]
> derende+ 15977  0.0  0.0  15792  1088 pts/3    S+   20:35   0:00      \_ grep --color=auto --exclude-dir=.bzr --exclude-dir=CVS --exclude-dir=.git --exclude-dir=.hg --exclude-dir=.svn -i keybase
> derende+ 13097  0.0  0.2 482308 20960 pts/1    Sl   20:21   0:00 keybase -d --log-file=/home/derenderkeks/.cache/keybase/keybase.service.log service

(The first one is probably from oh-my-zsh or something like that)

**Comment by cjb** [comment]
it looks like `killall keybase` would kill that process

**Comment by DerEnderKeks** [comment]
Well, it kills it but it looks like keybase doesn't really care about whether it's running or not..

> derenderkeks@derenderkeks-laptop  ~  
>  $ tail -n 5 ~/.cache/keybase/Keybase.app.log
> Only one instance of keybase GUI allowed, bailing!
> Only one instance of keybase GUI allowed, bailing!
> Only one instance of keybase GUI allowed, bailing!
> Only one instance of keybase GUI allowed, bailing!
> Only one instance of keybase GUI allowed, bailing!
> 
>  derenderkeks@derenderkeks-laptop  ~  
>  $ echo "\n" >> ~/.cache/keybase/Keybase.app.log
> 
>  derenderkeks@derenderkeks-laptop  ~  
>  $ killall keybase 
> 
>  derenderkeks@derenderkeks-laptop  ~  
>  $ run_keybase 
> Launching keybase service...
> Mounting /keybase...
> Launching Keybase GUI...
> Success!
>                                                   ▄▄▄▄█▀    
> ╭───────────────────────╮          ▄▄          ▄▄▄█▄▄▀      
> │                       │         ███▄▄▄▄▄▄▄▄▄▄███▄██       
> │  Encrypt everything!  │       ▄▄▄████▄▄▄███████████       
> │                       ├────  ▄▄▄▄▄████▄█████████████      
> ╰───────────────────────╯      ███▄█▄█████████████████▄▄    
>                                 ▀▄███████▄▀ ███████████▄▄   
>                                   ▄▄▄▄███    ███████████▄▄  
>                                  ▄████████   ██████████████ 
>                                 ▄███▄█████▄▄  ▀▄████████████
>                                ███████▄▄██▄█▄▄ █████████████
>                               ▄▄█████████████▄▄ ████████████
>                            ▄██▄▄████▄▄▄█▄▄█████ ████████████
>                                 ███▄▄▄▄▄███████▄▄█████████▄▀
>                                 ▄█████▄▄█████████████▄█████ 
>                                 █▄██████████▄▄▄▄▄▄▄███████  
>                               ▄▄▄▄▄██▄▄█████▄████████████   
>                             ▀▀▀▀▀▀▀▀▄▄▄▄██▄▀ ▀▀▄▄▄▄▄▄▀▀▀    
>                                   ▀▀▀▀▀▀▀▀▀                 
> 
>  derenderkeks@derenderkeks-laptop  ~  
>  $ tail -n 5 ~/.cache/keybase/Keybase.app.log
> Only one instance of keybase GUI allowed, bailing!
> Only one instance of keybase GUI allowed, bailing!
> 
> 
> Only one instance of keybase GUI allowed, bailing!
> 
>  derenderkeks@derenderkeks-laptop  ~  
>  $

**Comment by DerEnderKeks** [comment]
I think we can close this as I'm not even using the same distro anymore and the issue no longer persists because of that.
