### ISSUE TITLE
[Windows] Blue screen a few minutes after boot.

### ISSUE THREAD

**Issue by talkahe** [keybase/client#3470]
I have installed Keybase on my Windows computer. After a few minutes working it's show a blue screen (unexpected_kernel_mode_trap). I have disabled keybase on startup and all works fine.

my log id: c66d431a163f4b6cf1c5671c

**Comment by zanderz** [comment]
BSODs have been reported by users who have Symantec Desktop Encryption or BitDefender Antivirus Pro installed. Do you have either of those, or some other active AV suite, or other product with a filesystem driver?

**Comment by talkahe** [comment]
@zanderz I have BitDefender Total Security installed.

**Comment by zenyr** [comment]
I had at least 3 BSODs within a few minutes after launching Keybase on Windows 10. (driver-pool-something and pagefile-fault-something)
I do not have either of those but I do have lots of geeky-softwares, including DRM'd font manager which may or may not be hooking into the file system alongside of Windows Defender (the default bundled one)

**Comment by zanderz** [comment]
@talkahe We are closing in on a possible fix to allow coexistence with BitDefender, but it will take a couple more days.

@zenyr We haven't yet tracked any BSODs from a machine with neither BitDefender nor Symantec installed, so we would be very interested to see what the conflict may be. Can you post a recent .dmp file from your %windir%\minidump directory to somewhere non-public? And if you issue the command `sc query type= driver`, it would be interesting to see which other filesystem drivers are installed.

**Comment by zenyr** [comment]
@zanderz Okay, I've configured to build minidumps via advanced system configuration. Unfortunately prior BSODs that I mentioned had not left any salvageable dumps so I'll re-install keybase and see if I could fetch a dump or few. I had to uninstall keybase to avoid BSODs on my main working PC at my office.

**Comment by taruti** [comment]
@talkahe @zenyr

A new release ( https://prerelease.keybase.io/windows/Keybase_1.0.16-20160803133001%2B64450b3.386.exe ) should have fixed this.

Please reopen this issue and/or highlight me if the issue persists after updating.
