### ISSUE TITLE
After "starting over", my laptop is revoked

### ISSUE THREAD

**Issue by victorandree** [keybase/client#3474]
I started over my keybase account from scratch and now my laptop's key (which had a device key previously) is being treated as revoked by Keybase. When logging in through the Keybase app, I first couldn't reuse the previous device name (`liberia`), getting that it was already in use, so I just appended today's date (`liberia20160714`) and I could log in.

Now, if I try to access KBFS on my machine, I get errors and this notification (from, for example, `ls` in `/keybase/public/victorandree`):

> **Keybase: Possibly revoked data detected**
> /keybase/public/victorandree was modified by a revoked or bad device. Use 'keybase log send' to file an issue with the Keybase admins.

I've rebooted a couple of times but haven't cleaned my data in other ways. Seems like my laptop is in sort of a limbo state.

I'm https://keybase.io/victorandree

Edit: I can e.g. provision new paper keys with my laptop, however, some things are working only sometimes... If I `cd /keybase/private/victorandree`, KBFS rekeyed everything and it seems to work. But that doesn't seem to happen for public.

my log id: 36992d8951879061c0a08f1c

**Comment by victorandree** [comment]
Okay seems this might be the same issue as #2472? If that's the case, here's a signed request to completely reset my folders:

```
BEGIN KEYBASE SALTPACK SIGNED MESSAGE.
kXR7VktZdyH7rvq v5wcIkHbs9P0NGi 4ZzS6veOAP4iP1X OcCSTnOX6oCNnYP
u4WvnGUeo7mNuuF CG2rvV76DTg8rDD t75x1teN7pQULP2 wP1dblPa3QZaNDG
mS48Y4YXhE8sHBT gkDNDLWgHqqaORC QrTUdDJdZyADTPg VmbpNDA9hSxOMWn
5gv6rjlswOWzVa0 QkzJoXHgbtENr1Q RU8nIPheJ7z3VOG LLczozExVuhCTfR
JduvhMeIAR8954a dihPSx6rEciW1I6 oTd0tbkm74TEazk GIeHBl4LwXQhGoI
G7dBpUUzRugVNcy D4xHKj4i0E8Xrud f3yjBvOSBbCUM9N Z6Z98laH5FqSL1n
1E8ulZHgJGGlDd8 jCRESZvlqObkB2j 0Dew2Z5BxUbea9W 7ovW6jz9NQVuTwT
GYsWnZgf8ixmdCC EfxA5BN3dXpLVlR KpG95xXbWSMilC2 zJiW3ZRf1A9ZSyY
mO.
END KEYBASE SALTPACK SIGNED MESSAGE.
```

Thanks!

**Comment by strib** [comment]
@victorandree ok, the folders are reset.  Can you please check them and close this issue if everything looks ok?

**Comment by victorandree** [comment]
@strib Thanks a lot! Everything works great now. This is an amazingly interesting project! ⚡
