### ISSUE TITLE
GPG Key Import error

### ISSUE THREAD

**Issue by markaltmann** [keybase/client#3483]
Keybase GUI Version: 1.0.16-20160712110019+8652095

c02q84vafvh8:~ altmama$ keybase pgp import
▶ WARNING push handler: Failure in message replay: unknown RekeyUIHandler category: "tlf"
▶ WARNING push handler: Failure in message replay: unknown RekeyUIHandler category: "tlf"

^C▶ ERROR interrupted

**Comment by maxtaco** [comment]
You can ignore those warnings for now.  `keybase pgp import` is just waiting for input from stardard input
