### ISSUE TITLE
Validation succeeded without card

### ISSUE THREAD

**Issue by Gunni** [keybase/client#3509]
Hey,

I just validated my domain wave.is without having my pgp private key inserted.

How it signed the proof without having my key i do not know.

	○ gpg -k
	C:/Users/gunnarg/AppData/Roaming/gnupg/pubring.gpg
	--------------------------------------------------
	pub   2048R/0x7EC575FC46B8E78C 2016-07-16 [expires: 2026-07-14]
	uid                 [ultimate] Gunnar Guðvarðarson <gunni@wave.is>
	sub   2048R/0x2BBB225990244420 2016-07-16 [expires: 2026-07-14]
	sub   2048R/0x3337A7C8ECA99DBD 2016-07-16 [expires: 2026-07-14]
	
	○ gpg -K
	C:/Users/gunnarg/AppData/Roaming/gnupg/secring.gpg
	--------------------------------------------------
	sec>  2048R/0x7EC575FC46B8E78C 2016-07-16 [expires: 2026-07-14]
		Card serial no. = 0006 04159873
	uid                            Gunnar Guðvarðarson <gunni@wave.is>
	ssb>  2048R/0x2BBB225990244420 2016-07-16
	ssb>  2048R/0x3337A7C8ECA99DBD 2016-07-16

When the card is not inserted, any calls to signing or similar cause gpg to fail since it cannot access the actual private key, just a stub pointing to the card.

**Comment by maxtaco** [comment]
You made a [signature](https://keybase.io/gunni/sigchain#4ff2af35c2c039fffe4493a082d97bdefe4a0bb91c7c13f1e7d8e02ec6cd8f2e0f) with your per-device key.  See this [blog post](https://keybase.io/blog/keybase-new-key-model) for more information.
