### ISSUE TITLE
large file write failed

### ISSUE THREAD

**Issue by vijayp** [keybase/client#3512]
I tried to rsync  a ~ 200 MB file to my private directory and the operation timed out and left the files partially written. (from Europe)

my log id: 6ff7bd59d93b182421c0af1c

**Comment by strib** [comment]
Thanks! Known issue (see #1981 for example).  The release coming out today or tomorrow should have improvements to this, though I'm not sure it's still 100% ready for slow connections yet.  Closing as a dup.
