### ISSUE TITLE
I was asked to send a log....

### ISSUE THREAD

**Issue by mhykes** [keybase/client#3533]
This said there was trouble syncing one of my KBFS directories.  I think this may have timed out because it started syncing before I hibernated my laptop this morning, and then timed out when I brought the laptop back from hibernation many hours later (and had not yet joined the new wireless network).

If so, this is likely to be a common issue and might need a less scary notification.

my log id: 3461afda7ac2c6dbe3d0021c

**Comment by strib** [comment]
Ah yeah, that can happen. Your log seems normal -- you probably just weren't connected to the network yet while Windows tried to access the file system.  Sorry for the scare!
