### ISSUE TITLE
Client UI gets "stuck" after clicking "New private folder" button

### ISSUE THREAD

**Issue by michaelroland** [keybase/client#3549]
Keybase GUI Version: 1.0.16-20160713110836+a1c00b3
OS: Windows 7 Professional SP1 64-bit

After clicking on the button "New private folder" ("private/" tab), the button turns slightly darker and the UI of the client gets somewhat "stuck". This is the resulting UI layout (after pressing the "New private folder", then clicking on the "public/" tab header, and then clicking on the "private/" tab header):

![Screenshot keybase client](https://cloud.githubusercontent.com/assets/11541477/16993717/c542dfe2-4ea4-11e6-953f-c514c244233d.png)

"stuck" means that:
- Clicking on the menu button (icon in upper left corner) results in a color change of the icon (between white and blue) but the menu does not pop up.
- Clicking on the "public/" / "private/" tab headers changes the background color between dark blue and white. Nothing else seems to change.
- Clicking outside the window hides the keybase window. Clicking on the tray icon shows the window again.
- Clicking on my username hides the keybase window. Nothing else seems to happen.
- Killing all instances of `Keybase.exe` (the one located in `%APPDATA%\Keybase\Gui\`) and re-opening it makes the UI responsive again.

**Comment by michaelroland** [comment]
Maybe related to #3542?

**Comment by michaelroland** [comment]
The same happens when clicking on the "Open public folder" button. Same after a reboot.

**Comment by iFreilicht** [comment]
I can confirm that this issue occurs on Windows 10 (64bit, version 10.0.10586 Build 10586)
as well.

**Comment by michaelroland** [comment]
An update to version 1.0.16-20160726182036+0c2a52a solved the issue for me.
