### ISSUE TITLE
I got error "Keybase: Files need to be rekeyed"

### ISSUE THREAD

**Issue by fordantitrust** [keybase/client#3560]
Keybase: Files need to be rekeyed
Please open one of your other computers to unlock /keybase/private/fordantitrust

Please suggest solution for this issue.

keybase sign -m "2016-07-21-151400 GMT +7
: Please reset folder /keybase/private/fordantitrust and /keybase/public/fordant
itrust be cause I reinstall Keybase."

BEGIN KEYBASE SALTPACK SIGNED MESSAGE. kXR7VktZdyH7rvq v5wcIkHbsD15G4z xs6k0wQA2
TURVOX w1JD2YCPhpbMHbG 1OcBzhrAq6uubEh UPaXz7OnV9DMOd5 wCeLnuLYqF1MmtZ HwQGD16bN
QvxFkF 6PmDfPiHE5iwDmd Hr2NqoBgkdNWDQA GlMB4RilD8AgWGG Em01bHdsqesDSW1 7rj5hg6SL
utfxyJ K3pLTot39PQbNBI cY7NjD5xA1xZEW2 iHBzMMNqAV55mA3 3B8CR5gDumPWNNl eznQfCpZT
XXAiVK vkYArY8cb0QnSYM fXljXXwVA2THkhX tRMYKMgV9T24fCM FSHBnHwGYMMZLdC SZsSpRhoB
JPXef7 efMeaqYatvAqCZJ vQF4NJGAPAvyMyt IzUxVxE7HNgEFSR rR3DEHSvx3DVoqq WJcYr57Xv
5RiJ4y FdJATTgbjvdVxie WEbfWL6BvapieJh 4JybZiDZZ6RePJI . END KEYBASE SALTPACK SI
GNED MESSAGE.

**Comment by strib** [comment]
Hi @fordantitrust -- it seems like you've revoked all your devices without resetting your entire account?  (Via https://keybase.io/fordantitrust/devices).  Does that sound right?

Even if we reset your folders, you won't be able to do anything with them until you have an active device.

Can you explain a little more about your situation please?  Thanks!

**Comment by fordantitrust** [comment]
I tried to reinstall and activate my devices for sync my existing file in KBFS and I got error above.

Now I revoked  all devices and I want to reset and purge all files in my KBFS.

Thank you ;)

**Comment by strib** [comment]
Ok, I can reset them, but do you understand that you still won't be able to use KBFS until you provision a new device (and/or re-provision an existing one)?

The other problem I'm not sure what device signed the statement you posted above.  It must have been signed by a device you have already revoked.  Because of that, I technically shouldn't trust it, since it has no connection to any of your current proofs.  Would you be able to provision a new device to your account, and then post a re-signed message?  Thanks!

**Comment by fordantitrust** [comment]
keybase sign -m "2016-07-22-020200 GMT +7 : Please reset folder /keybase/private/fordantitrust and /keybase/public/fordantitrust be cause I reinstall Keybase."

BEGIN KEYBASE SALTPACK SIGNED MESSAGE. kXR7VktZdyH7rvq v5wcIkHbrydqdg7 2swgQfSlD
E4YISc kTWeBHSgcTkjpGT wzDEsMSHf1LTXV6 fDW8GYLus2JEp7g iCuKr6BEsSeMEE1 7iqHiEbja
p3T8RW FXGCBRqj3bIewj8 0rYlfGAi3rEvEWm ng1CEPEXD0G02SR cMTc4agkco4X0zk zFtL5sePm
5nF4VF zRRmRqR8p8C3KAE EKDznD4SwUhSRK2 gjhPLxuzueZRdNN 2EKUr3TM2oUAZmP nsrBFSKfS
4ejXGE pHqUP3alqQ27V8f 8zKyNux5ygzbcny MN6jN0RDzVM9PXz ome9plgC0O9q19I N8b1yoNDe
FZ3z9N ylZFlyhb3c0zCDa Z0xeQpH9ugFD2u0 pc7RiG3yj4zKblP 4r3eJNJcRTItp7I 2s4SJVubk
EavgPO MdBqPzv428192J7 39PRCnqztZbdImm SEjd7AR4gr8pVG7 Q8. END KEYBASE SALTPACK
SIGNED MESSAGE.

Thank you ;)

**Comment by strib** [comment]
Ok, the folders are now reset. Can you please check them out, and close this out if things look ok?

**Comment by fordantitrust** [comment]
Thank you ;)
