### ISSUE TITLE
K:\ is not accessible. Access is denied.

### ISSUE THREAD

**Issue by coreyog** [keybase/client#3562]
Windows K: drive. Windows 10 x64 Pro.

I got a notification saying my K: was "rekeying" and of the 2 Win 10 machines I have keybase installed on only one of them can access the K:.

I've only just been invited so I can't say much about if it worked before. Aside from uninstalling and reinstalling is there a way to just refresh the K: or to remove and re-add it without removing keybase?

my log id: f66861bfb0bff9c544304f1c

**Comment by coreyog** [comment]
I restarted the machine and signed back into the Keybase client. Now when I open My Computer to look at the drive it's in a perpetual loop of adding the K: and removing it. At no time do I have access.

I've submitted new logs:
my log id: 39d614f764f298cc5ec8231c

**Comment by strib** [comment]
@zanderz @taruti -- ever seen anything like this?  I don't see anything obviously wrong from the kbfs logs other than:

```
516 2016-07-20T15:44:33.557025 - [ERRO kbfs mounter.go:55] 016 Failed to mount dokan filesystem (i=8): Dokan failed: -5
...
530 2016-07-20T15:44:35.174073 - [INFO kbfs start.go:66] 022 Mounting the filesystem was a success!
```

repeated occasionally.

**Comment by taruti** [comment]
@strib, If mounting fails we retry it a few times till we succeed. This could be caused by e.g. an old stale mount.

**Comment by ElectronicWar** [comment]
K:\ never shows up for me (K is also not used by other drives), log is full with "Failed to mount dokan filesystem". Windows 10 Professional x64.
my log id: 7af6cfdff08dd513cf591f1c

**Comment by coreyog** [comment]
Since the last update (1.0.16-20160726182036+0c2a52a) my K:/ has sorted itself out and is working on both of my Win10 machines.
