### ISSUE TITLE
Write timeout while sending large ZIP.  

### ISSUE THREAD

**Issue by keith24** [keybase/client#3586]
I was writing a large zip (1.3 gb) to my public folder (and simultaneously uploading several other directories to my private folder).  One transfer is still running OK, but the ZIP timed out.  The taskbar notification said `The write operation took too long and failed`.  

`my log id: d43b5d4223d65ddedac77b1c`

I also got this error while sending the log: 

``` sh
▶ WARNING error opening log "/home/keith/.cache/keybase/keybase.updater.log": open /home/keith/.cache/keybase/keybase.updater.log: no such file or directory
```

I can copy any of these files per request: 

``` sh
keith@keith-acer:~/.cache/keybase$ ls -la /home/keith/.cache/keybase
total 353584
drwxrwxr-x  2 keith keith      4096 Jul 22 20:06 .
drwx------ 52 keith keith      4096 Jul 22 18:50 ..
-rw-rw-r--  1 keith keith   1970832 Jul 22 14:36 Keybase.app.log
-rw-------  1 keith keith  88106053 Jul 22 20:20 keybase.kbfs.log
-rw-------  1 keith keith 134217871 Jul 22 20:02 keybase.kbfs.log-20160722T195732-20160722T200209
-rw-------  1 keith keith 134217773 Jul 22 20:06 keybase.kbfs.log-20160722T200209-20160722T200608
-rw-------  1 keith keith   3508197 Jul 22 20:20 keybase.service.log
-rw-rw-r--  1 keith keith       219 Jul 21 15:05 keybase.start.log
-rw-------  1 keith keith       384 Jul 22 19:51 session.json
```

**Comment by strib** [comment]
Hi @keith24 -- thanks for the report.  I took a look at your logs and it seems like KBFS is definitely struggling to transfer data over your network connection within the timeout imposed on us by your operating system.  It's definitely made worse by the fact that you are writing to multiple folders at once, but that's no excuse.  We are currently working on a better strategy for large network transfers that will be ready in the next couple months.  Until then, sorry for the inconvenience!

**Comment by keith24** [comment]
Oh, it's no inconvenience!  I know what beta means.  KBFS is already _very_ impressive as is.  

I can't be of any technical help here, so I'm unsubscribing.  If you need more info, you can request it with the email address on my profile.

**Comment by strib** [comment]
Version 1.0.20 has architectural changes that should greatly improve the large write experience.  If you're still seeing problems, please open a new issue.
