### ISSUE TITLE
Old machine formatted, Can't get a new machine connected

### ISSUE THREAD

**Issue by seefood** [keybase/client#3589]
I have not used keybase in a while, and the only machine I had connected to it is gone. I now got a new Mac from work, installed Keybase by "brew install", copied the .gnupg over. I try to log in and get:
```
❯ keybase login
Your keybase username or email address: ia42
▶ ERROR Message wasn't signed
```
When I try to log in by email. it asks for my "keybase passphrase", but I don't remember having set one, also I see on my account I have a paper key, but I don't remember creating that either (I have all my secrets in keepass, and those are the kind of things I would have kept there).

so... help?

Log ID: 77731c7f44d00bc3cbdd341c

**Comment by maxtaco** [comment]
You can try our most recent client, available via the [download page](https://keybase.io/download).  That will get you slightly further, but I still think you need to reset your account.  Since you have a device key, I'll need to do it for you.

**Comment by seefood** [comment]
Problem resolved, it was artifacts in my trustdb, introduced by gpg1, choked on by gpg2.
