### ISSUE TITLE
Allow hiding of dock icon on macOS

### ISSUE THREAD

**Issue by tylerreckart** [keybase/client#3606]
Would love an option to only have the menu-bar icon displayed when the app is open
<img width="125" alt="image 2016-07-26 at 10 14 17 am" src="https://cloud.githubusercontent.com/assets/1633919/17141400/e5fe736c-5319-11e6-8f6e-e325676b2b12.png">

**Comment by awendland** [comment]
Hello @tylerreckart! We had some long discussions about this part of the UX. The final decision to make the dock icon present is based off of precedent of Chrome and Evernote: both keep the dock icon visible when the application window is closed by the close button or with *Cmd-W*; the app icon finally disappears once you hit *Cmd-Q*.

**Comment by tylerreckart** [comment]
@awendland Ah okay. Guess I'll just have to get used to it in my dock. I'm just a stickler for the way the dock looks 😄
