### ISSUE TITLE
Tried to invite a user by writing to /keybase/private/xxx,yyy@example.com/secret.txt => failed

### ISSUE THREAD

**Issue by eswenson1** [keybase/client#3623]
I tried to use the "sharing encrypted files" way to invite a user to Keybase.  Since I didn't know the user's twitter handle, but only an email address, I tried to use that email address.  I got an "No such file or directory" error trying to write the file.  From reading the doc, I would have expected that this would have worked, and that a) the file would have been encrypted with my public key, and b) an invitation would be sent to the email address used.  Upon that user's registration (with that email address), I would have expected to have the file automatically rekeyed with the user's public key.  

Is it the case that this approach doesn't work with email addresses?  If so, that is a pretty serious deficiency, since an email address is the most likely "handle" that a user will know for another user.

My log id is:  11a411f83372d14638d9011c

**Comment by strib** [comment]
KBFS only support Keybase proofs, and Keybase proofs have to be publicly verifiable.  We don't have a good way yet to support public proofs for emails (though we've done a little bit of thinking about it).

Where in the docs does it imply that an email address should work?

**Comment by eswenson1** [comment]
Nowhere in the docs is this implied. The example I've seen has only shown one "handle" -- the twitter id. I just assumed (incorrectly) that since you sign up with an email address and then generates proofs and associated these with your account, that Keybase would allow use of the email address as the "handle". I, obviously, just assumed incorrectly.

**Comment by strib** [comment]
Ok, understood.  The issue is there is no foolproof way to prove to user1 that user2 really signed up for Keybase with a given email address, without trusting the server (and leaking the email address associated with the account).  We might be able to support certain types of email addresses (e.g., `gmail.com`), but we're unlikely to find a general solution for this in the near term.  Sorry!
