### ISSUE TITLE
Can't open GUI after installation on linux

### ISSUE THREAD

**Issue by Ian321** [keybase/client#3631]
run_keybase returns:
Unmounting /keybase...
Shutting down kbfsfuse...
Shutting down keybase service...
Launching keybase service...
Mounting /keybase...
Launching Keybase GUI...
Success!

but the gui won't launch
command line works tho

my log id: d222a966fca2704e2c49321c

**Comment by cjb** [comment]
Seems like maybe your environment doesn't have $XDG_RUNTIME_DIR set.  Does that sound right?

**Comment by Ian321** [comment]
`echo $XDG_RUNTIME_DIR` returns `/run/user/1000` is it supposed to be something else @cjb ?

**Comment by cjb** [comment]
Oh!  You're running `run_keybase` as root.  That doesn't work.  Try it without sudo, or logged in as a regular user, etc?

**Comment by cjb** [comment]
@oconnor663 Perhaps `run_keybase` should refuse to run as root.

**Comment by Ian321** [comment]
@cjb somehow my $XDG_RUNTIME_DIR is also `/run/user/1000` as user but i never changed it.
And when i try to change it, it resets after a restart

**Comment by Ian321** [comment]
I changed `XDG_RUNTIME_DIR` inside `~/.profile` and it works now
Thx for the help
