### ISSUE TITLE
Keybase filesystem, osx, can't sync file

### ISSUE THREAD

**Issue by ExiaSR** [keybase/client#3640]
I am running keybase on mac, and it seems like the file cannot be uploaded.

my log id: 96e77198507c6baa8c416d1c

**Comment by strib** [comment]
Hi @ExiaSR, thanks for the report.  I looked through your log, and couldn't find any instances of a file create/write/upload that failed.  Could you be a little more specific about what you were doing, and what error you saw exactly?  Ideally you could tell me the time, and/or the filename involved.  (If you want to keep the filename private, you could encrypt it just for me: https://keybase.io/strib.)

**Comment by ExiaSR** [comment]
I creat a fila called index.md, and simply cp it into the filesytem directory, keybase/public/exiasr. Then I keep refreshing the web page keybase.pub/exiasr, but the file doesn't show up.
I just redo this process at the moment at comment this issue.
the new log ID is:e3a21e1011cb6399c476e41c

**Comment by strib** [comment]
Hi @ExiaSR -- strangely your log contains no mention of a file called `index.md`.  It's as if either KBFS wasn't running while you did this, or you copied it into some non-KBFS directory.  Is there any chance of that?  If not, does `index.md` show up when you `ls /keybase/pubilc/exiasr` locally?  (And with or without the existing `id_rsa.pub` file that's already in there?)

**Comment by ExiaSR** [comment]
@strib This idea occurs to me as well, so I kill the keybase process and restart it. It seems like whenever I restart keybase, index.md is gone when id_rsa.pub is still there. It's so wired, is it some kind of glitch? Or is it possibly due to the internet connection that the file cannot be uploaded or recognized by the KBFS?

**Comment by ExiaSR** [comment]
<img width="628" alt="screen shot 2016-08-03 at 11 41 02 am" src="https://cloud.githubusercontent.com/assets/8373004/17353110/430f174a-596f-11e6-8390-ac97407c16ee.png">

**Comment by strib** [comment]
Hi @ExiaSR -- it looks like your terminal is looking in `~/keybase/public/exiasr`, which is not the right path -- you put a tilde in front of it.  However your open call has the right path: `/keybase/public/exiasr`.  Unless you did some custom symlinking on `~/keybase`, that's probably the issue.

**Comment by ExiaSR** [comment]
Hi @strib I though the directory it's under user's home directory. Thanks!
