### ISSUE TITLE
Non user-friendly messages about the absence of the Internet

### ISSUE THREAD

**Issue by Himura2la** [keybase/client#3644]
my log id: 2d0b5c5b6ffdc16ec3eb6f1c

**Comment by cjb** [comment]
@Himura2la What did the messages say?

**Comment by Himura2la** [comment]
I can't reproduce now, but it was about timeout with an invitation to send logs. Will attach screenshot if I was able to reproduce. 
I forgot I have lost the connection and the sending-logs command barely made me realize it is so
```

- WARNING error opening log "C:\\Users\\Himura\\AppData\\Roaming\\Keybase\\keybase.start.log": open C:\Users\Himura\AppData\Roaming\Keybase\keybase.start.log: The system cannot find the file specified.
- ERROR API network error: Post https://api.keybase.io/_/api/1.0/logdump/send.json: dial tcp: lookup api.keybase.io: getaddrinfow: No such host is known.

```

**Comment by strib** [comment]
Thanks for the report.  The issue is we can't easily tell the difference between a complete internet outage and a slow operation.  We're explicitly being conservative for now to make sure we catch all the real errors.  Sorry for the inconvenience.

**Comment by Himura2la** [comment]
OK, no problem, This issue is definitely minor.
