### ISSUE TITLE
GetFreeDiskSpace triggers timeout errors when there's no connectivity

### ISSUE THREAD

**Issue by jtsmith0101** [keybase/client#3659]
Just having a look at the link.....

I did have a goofy error message from the command prompt...
- WARNING error opening log "C:\Users\jtsmi\AppData\Roaming\Keybase\keybase.start.log": open C:\Users\jtsmi\AppData\Roaming\Keybase\keybase.start.log: The system cannot find the file specified.

The notification windows said I had an error which generated a log file.  Further advised me to enter the "keybase log send" command.

Cheers,

James

my log id: bbd60590b25cc6566b41cd1c

**Comment by strib** [comment]
Hi @jtsmith0101 -- does the log belong to one of your open issues?  If so, can you post the log ID as a comment there and close this standalone issue?

**Comment by jtsmith0101** [comment]
The log should coincide with the first issue I reported?

On 2 August 2016 6:48:44 AM AEST, Jeremy Stribling <notifications@github.com> wrote:
>Hi @jtsmith0101 -- does the log belong to one of your open issues?  If
>so, can you post the log ID as a comment there and close this
>standalone issue?
>
>---
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/keybase/client/issues/3659#issuecomment-236703102



James T. Smith
Co-Founder & COO
Made For Me
Skype: jtsmith73
Mobile: +61 413 738 332
Phone: 1300 787 304
Email: james.smith@madefor.me
GPO Box 2224, Canberra, ACT, 2601

madefor.me
twitter.com/madeforme3D
facebook.com/madeforme3D
madefor.me is a service by:
Euclidify Pty Ltd
ABN 25 166 998 938

Sent from my mobile device

**Comment by strib** [comment]
The confusing thing is that this is the first issue you opened in this repo.  The next one came two days later.

**Comment by jtsmith0101** [comment]
Fair enough.  The log file was for an error message that kept popping up when the computer would wake up from sleep but didn't yet have an internet connection. I may have submitted two log files for the same symptom. 

Hope that helps.



On 2 August 2016 6:54:31 AM AEST, Jeremy Stribling <notifications@github.com> wrote:
>The confusing thing is that this is the first issue you opened in this
>repo.  The next one came two days later.
>
>---
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/keybase/client/issues/3659#issuecomment-236704679



James T. Smith
Co-Founder & COO
Made For Me
Skype: jtsmith73
Mobile: +61 413 738 332
Phone: 1300 787 304
Email: james.smith@madefor.me
GPO Box 2224, Canberra, ACT, 2601

madefor.me
twitter.com/madeforme3D
facebook.com/madeforme3D
madefor.me is a service by:
Euclidify Pty Ltd
ABN 25 166 998 938

Sent from my mobile device

**Comment by strib** [comment]
Ah ok, thanks!  That's definitely a known issue.  We're still trying to figure out how best to balance completeness vs. annoyingness for user notifications.  On Windows in particular, the OS wants to know about the free disk space all the time, even when you're not using the file system explicitly, and that seems to be causing the timeout in your case.  I'll leave this open as we consider whether to change that behavior, maybe just for this specific case of `GetFreeDiskSpace`.

**Comment by taruti** [comment]
This should be better in the next release.

**Comment by jtsmith0101** [comment]
this can be closed
