### ISSUE TITLE
Can't login with keybase client, no useful information in logs

### ISSUE THREAD

**Issue by exabrial** [keybase/client#3664]
I use ECC keys, not sure if that's relevant
I install everything (gpg21, keybase) from brew

Log snippet:

> 016-07-29T08:41:40.334218 ▶ [DEBU keybase login_provision.go:419] 0fb got synced secret key
> 2016-07-29T08:41:40.334242 ▶ [DEBU keybase skb.go:787] 0fc + PromptAndUnlock(sign new device)
> 2016-07-29T08:41:40.392424 ▶ [DEBU keybase skb.go:789] 0fd - PromptAndUnlock -> ok
> panic: impossible
> 
> goroutine 62 [running]:
> panic(0x4b05ca0, 0xc82024a4a0)
>   /usr/local/Cellar/go/1.6.2/libexec/src/runtime/panic.go:481 +0x3e6
> github.com/keybase/client/go/vendor/github.com/keybase/go-crypto/openpgp/packet.(*PrivateKey).parsePrivateKey(0xc820198340, 0xc82024e600, 0x34, 0x600, 0x0, 0x0)
>   /private/tmp/keybase-20160524-73770-117dq2z/client-1.0.16/src/github.com/keybase/client/go/vendor/github.com/keybase/go-crypto/openpgp/packet/private_key.go:294 +0xdc

my log id: 81b206eb1d8c5b771bd4e11c

**Comment by maxtaco** [comment]
Can you try the other login method --- of shelling out to GPG?

**Comment by exabrial** [comment]
I'm not sure what that means... For proving my identities that seems to work (with the giant curl command) but I'm unsure how to do that while trying to login to the keybase command line client.

**Comment by maxtaco** [comment]
The CLI should give you two options on how to log in the first time if
you're using a PGP key. If you care to, post the who transcript of what
happens when you try to log in.

**Comment by exabrial** [comment]
oddly enough it doesn't:

> jonathanfisher@odin ~ $ keybase login
> ▶ WARNING Session file found but user is not logged in. Deleting session file.
> Your keybase username or email address: exabrial
> ▶ ERROR EOF
> jonathanfisher@odin ~ $ 
>

**Comment by maxtaco** [comment]
Ah, you're exactly right. Sorry for the misdiagnosis.  It's a situation we don't see very often. The issue is that the keybase CLI is crashing our your ECC PGP key. We'll take a look and get back to you.  Might be in the backlog though since it's a pretty localized/uncommon error. Thank you!

**Comment by zapu** [comment]
@exabrial would you mind trying this again? And if it still fails, please give me some info on how to generate keys that cause this panic. ECC key support should have improved lately in general. Thank you!

**Comment by exabrial** [comment]
Yep! It's been working great for awhile. Thank you
