### ISSUE TITLE
[KBFS]  No such file or directory

### ISSUE THREAD

**Issue by emilstahl** [keybase/client#3667]
```
$  cd /keybase/public/emilstahl
bash: cd: /keybase/public/emilstahl: No such file or directory
```

Another thing:
```
▶ WARNING error opening log "/home/emil/.cache/keybase/keybase.kbfs.log": open /home/emil/.cache/keybase/keybase.kbfs.log: no such file or directory
▶ WARNING error opening log "/home/emil/.cache/keybase/Keybase.app.log": open /home/emil/.cache/keybase/Keybase.app.log: no such file or directory
▶ WARNING error opening log "/home/emil/.cache/keybase/keybase.updater.log": open /home/emil/.cache/keybase/keybase.updater.log: no such file or directory
▶ WARNING error opening log "/home/emil/.cache/keybase/keybase.start.log": open /home/emil/.cache/keybase/keybase.start.log: no such file or directory
```
my log id: 7f60f4b2e99b75b975fea71c

**Comment by cjb** [comment]
@emilstahl You still don't have KBFS running at all.

**Comment by cjb** [comment]
(Did you type `run_keybase` to start it?)

**Comment by emilstahl** [comment]
Yes I did. However I restarted the machine.. it works 👍

**Comment by emilstahl** [comment]
It is mounted, but I can't create, move or list files.

my log id: 6b5c4d46335779cb7dc4a91c

**Comment by cjb** [comment]
You now have KBFS running, but not the desktop GUI app that's trying to prompt you for your passphrase:

1 /opt/keybase/Keybase: error while loading shared libraries: libgconf-2.so.4: cannot open shared object file: No such file or directory

**Comment by cjb** [comment]
Okay, you can use `keybase login` on your server to log in without the GUI. You'll be missing some notifications, though..

**Comment by cjb** [comment]
Do we have a bug report from you for the "loading indefinitely" bug on OS X, maybe with a log send?

**Comment by emilstahl** [comment]
@cjb I'm already logged in.

I'm gonna file a bug report on the login issue next week. I don't have that computer with me.

**Comment by cjb** [comment]
KBFS seems sure that you aren't logged in.  If `keybase login` just exits straight away, does `keybase unlock` maybe do something?

**Comment by emilstahl** [comment]
```
Session:       emilstahl [loaded: yes, cleared: no, expired: yes]
    is valid:  yes
    keys:      unlocked

Key status:
    stream:    cached
    secret:    not stored
    dev sig:   cached
    dev enc:   cached
    paper sig: not cached
    paper enc: not cached
    prompt:    show
    tsec:      cached

KBFS:
    status:    running
    version:   1.0.2-20160728160033+3830bf4
    log:       /home/emil/.cache/keybase/keybase.kbfs.log

Service:
    status:    running
    version:   1.0.16-20160728160033+4e1c5b4
    log:       /home/emil/.cache/keybase/keybase.service.log
```

```
$ keybase login
$ keybase unlock
```

**Comment by maxtaco** [comment]
Unlock isn't needed anymore. Login should do it.  Either a further core bug
or a further kbfs authentication bug.  According to status the signing key
is available so I think the latter.

**Comment by maxtaco** [comment]
Does it work if you restart the kbfs daemon?

**Comment by emilstahl** [comment]
@maxtaco Yes! Thanks 👍
