### ISSUE TITLE
Permission denied for /keybase/* (public, private and subdirs)

### ISSUE THREAD

**Issue by pddevins** [keybase/client#3678]
I had a previous version (unknown) of keybase and recently downloaded the update (2 days ago). I am attempting to navigate to any folder in /keybase/public or /keybase/private but keep getting a "Permission denied". the read write access on the main keybase folder seems correct : dwr------ myuser mygroup

my log id: 1b2c07b040d83dc225be961c

**Comment by maxtaco** [comment]
@gabriel looks like kbfsfuse won't mount, gets permission denied...

**Comment by strib** [comment]
@pddevins looks like you're running the macOS Sierra beta.  We're still testing support for that, hopefully coming soon!
