### ISSUE TITLE
Don't know how to stop copying this file.

### ISSUE THREAD

**Issue by yeswecan** [keybase/client#3689]
[write something useful and descriptive here]

I tried to copy file using Mac's Finder. It's stuck in a copying state and Keybase constantly tells me that the write operation has failed, but nothing is working so far to stop it. Do I have to reboot?

my log id: b2e60c79e7846a77888daa1c

**Comment by yeswecan** [comment]
It seems that the Finder is stuck though, not Keybase.

**Comment by yeswecan** [comment]
Read operation has taken too much time too after the Finder is killed.

**Comment by yeswecan** [comment]
I'm still getting these errors.

**Comment by maxtaco** [comment]
We'll take a look, thank you....

**Comment by maxtaco** [comment]
I suspect the original login problem was never resolved.  Can you:

```
keybase logout
keybase login
```

From the command line?

**Comment by corroded** [comment]
I think this might be related https://github.com/keybase/client/issues/3709

**Comment by strib** [comment]
Version 1.0.20 has architectural changes that should greatly improve the large write experience.  If you're still seeing problems, please open a new issue.
