### ISSUE TITLE
Untracked user's folder keeps listed

### ISSUE THREAD

**Issue by olegkorol** [keybase/client#3698]
Keybase GUI Version: 1.0.16-20160728160033+4e1c5b4

Hi,

when I untrack a user his folder keeps appearing under /keybase/public/username as well as in the GUI.
Is it a bug or it just takes some time for them to disappear completely?

Thanks.

**Comment by cjb** [comment]
Hi, the way to remove a folder you've been using is:
```
rmdir /keybase/public/username
```
There'll be a GUI way to do it shortly.

**Comment by olegkorol** [comment]
Oh I see. That means that after
`keybase untrack username`
I have to additonaly delete (manually) the public folder with
`rmdir /keybase/public/username` ?

**Comment by cjb** [comment]
Yes.

**Comment by olegkorol** [comment]
Wouldn't it be better to have these two steps in one single command, or is there any reason for it being like this?

**Comment by cjb** [comment]
Thanks for the suggestion, it's a good idea but we probably won't get to it for a while.

**Comment by olegkorol** [comment]
I guess there is more important stuff going on right now ;) Thanks again for the answer.
