### ISSUE TITLE
is there a way to check for updates on Linux ?

### ISSUE THREAD

**Issue by doudou** [keybase/client#3706]
"keybase updater check" says the updater is unsupported, and the download link is not versioned, so there's no easy way to check whether the client should be updated.

**Comment by cjb** [comment]
Hi, which Linux distro do you use?  Can your package manager tell you this?

**Comment by ElectronicWar** [comment]
On windows `keybase update check` was replaced with just `upd check`. Maybe on linux as well?

**Comment by cjb** [comment]
On Linux we just use your system package manager for updates.

**Comment by doudou** [comment]
> On Linux we just use your system package manager for updates.

Mmmm ... I missed/forgot that one. Sorry for the noise.

It would IMO be better, then if all of this would be explained in the install page. I probably got confused by the fact that one has to install a debian package (I'm on Ubuntu) to get .... the source and the GPG keys installed and the "real" package then installed.

Somehow would personally feel more secure (I do realize that it's a feeling more than anything) if I had the option of doing these steps manually.
