### ISSUE TITLE
Trying to upload an mp3 file takes too long and just fails after a while

### ISSUE THREAD

**Issue by corroded** [keybase/client#3709]
Tried opening my private folder, dragged an mp3 into a subfolder and just fails

(File date is wonky as well. Original file has a proper date)

<img width="461" alt="screen shot 2016-08-03 at 1 18 42 am" src="https://cloud.githubusercontent.com/assets/46548/17338206/e7f5d886-5918-11e6-8008-0884cbe4a4a1.png">

my log id: 4b175b4c3a140d912ffebf1c

**Comment by strib** [comment]
Thanks.  We've recently identified some issues around the algorithm we use to control these timeouts -- we'll be working on fixing it soon.

**Comment by thehouseorgan** [comment]
Any progress on this issue as I'm having the same problem?

**Comment by strib** [comment]
Yep, plenty of progress.  In fact the latest client has most of the file system code necessary for this, we just haven't turned it on by default yet as 1) we're still testing it, and 2) none of the UX work has been done. Maybe soon we'll post instructions on how to enable it by hand if some users comfortable with early testing want to try it out.

**Comment by thehouseorgan** [comment]
Super, thanks for the update. I'll keep an eye out for when it's available to test.

Many thanks

**Comment by strib** [comment]
Version 1.0.20 has architectural changes that should greatly improve the large write experience.  If you're still seeing problems, please open a new issue.
