### ISSUE TITLE
Read error opening a shared private folder between me and Chris

### ISSUE THREAD

**Issue by jtsmith0101** [keybase/client#3720]
Keybase GUI Version: 1.0.16-20160726182352+0c2a52a

Log ID: 5e32a8bf681164f50259111c

**Comment by strib** [comment]
Hmm, it looks like it's taking you too long to check all of chris's proofs.  As a workaround, you can try to run `keybase id chris` on the command line, which will cache the checks for kbfs to use later.

@patrickxb @maxtaco: identifies of chris taking more than 29 seconds in a recent build?  For example, see the identify that starts at `2016-08-03T09:08:23` in the service log.

**Comment by jtsmith0101** [comment]
What is the benefit of checking all of the ids?  How much trust does the
system really need to pass on?  Wouldn't one or two be enough?

**Comment by maxtaco** [comment]
Looks like @jtsmith0101 is running 0c2a52a but Song's fix went after that at caa08bba6f5583c81941bc2a348e99169538e09f. The fix was to change the timeout from 60s to 10s on remote proofs, though @songgao, I just realized, we're not timing out DNS lookups, are we?  One of Chris's proofs didn't complete.

@jtsmith0101 to answer your question, if you track someone, we check that all of the proofs that you tracked are still valid.  If one fails, we block the operation.

**Comment by jtsmith0101** [comment]
Got it..... so, the less proofs someone has makes the operation more likely
to complete because there are less moving parts to check.  For example, if
the twitter check is good, but coinbase is having problems with their
connectivity and times out, then the operation fails.... even though the
identity may in fact be good.  How do you address third-party reliability
issues on the checks?

**Comment by songgao** [comment]
@maxtaco I looked into Go's `net` code a little bit. On unix, it's [using a timeout of 5 seconds, with two attemps](https://github.com/golang/go/blob/5fe1b35ed214a8ece13449f5788dd9f5c927379f/src/net/dnsconfig_unix.go#L38). On windows, it's using [a system call](https://github.com/golang/go/blob/5fe1b35ed214a8ece13449f5788dd9f5c927379f/src/net/lookup_windows.go#L256), which seems to be configurable from the Registry. So it looks like we should be find with not timout out DNS explicitly.

How do I tell which of chris's proof didn't complete?

**Comment by maxtaco** [comment]
there is debug output for it but i didn't follow it through

**Comment by jtsmith0101** [comment]
this can be closed
