### ISSUE TITLE
No access to keybase file system on ubuntu

### ISSUE THREAD

**Issue by operator-DD3** [keybase/client#3755]
For the life of me I cannot get the keybase filesystem to work. CD-ing to the folder does not work and says "No such file or directory"
my log id: 9dacac836c09a06f9e081e1c

**Comment by strib** [comment]
How did you install it?  Via `apt-get` or are you trying something else?  Looks like the installation process didn't create the `/keybase` mountpoint.  From your log:

```
1 2016-08-04T19:06:34.197708 ▶ [INFO kbfs start.go:27] 002 KBFS version 1.0.2-20160803184116+1f541f0
2 2016-08-04T19:06:34.198272 ▶ [DEBU kbfs main.go:107] 003 Mounting: /keybase
3 kbfsfuse error: (2) mountpoint does not exist: /keybase
```

**Comment by operator-DD3** [comment]
I used apt-get. Not sure what happened, but everything is working fine now.
Thanks for your time.

Hire me to work from home! LOL

**Comment by strib** [comment]
Ok, cool.  Weird, let us know if you ever figure out how you got into that state.
