### ISSUE TITLE
Completely ignores KDE and GTK+3 theme

### ISSUE THREAD

**Issue by JohnMHarrisJr** [keybase/client#3771]
The Keybase application completely ignores the native theme, and doesn't look like a native application at all.

**Comment by tehbmar** [comment]
http://i.imgur.com/hso9w32.png

Mine seems to be working just fine.  Can you expand?  Are you possibly running ```run_keybase``` as root?  It could be loading up the window GUI for the root profile instead of your local user making you see an unfamiliar UI (If you have themes etc)

**Comment by JohnMHarrisJr** [comment]
I am definitely not running keybase as root, or as any other user than my own. The window border perfectly matches my desktop environment and is enforced by my window manager. The contents of the window are what are entirely different. This is also shown in your screenshot.

On August 11, 2016 10:54:00 AM EDT, Brandon Martinez <notifications@github.com> wrote:
>http://i.imgur.com/hso9w32.png
>
>Mine seems to be working just fine.  Can you expand?  Are you possibly
>running ```run_keybase``` as root?  It could be loading up the window
>GUI for the root profile instead of your local user making you see an
>unfamiliar UI (If you have themes etc)

-- 
John M. Harris, Jr.
PGP Key: f2ea233509f192f98464c2e94f8f03c64bb38ffd

Sent from my Android device. Please excuse my brevity.

**Comment by JohnMHarrisJr** [comment]
In which case Keybase looks entirely out of place, and seems to ignore the user's desktop environment when setting up the UI. This is the issue. I knew that much from the start.

On August 11, 2016 11:26:38 AM EDT, Chris Ball <notifications@github.com> wrote:
>Yes, Keybase isn't a KDE or GTK+3 application, that's why it doesn't
>use their themes.

-- 
John M. Harris, Jr.
PGP Key: f2ea233509f192f98464c2e94f8f03c64bb38ffd

Sent from my Android device. Please excuse my brevity.

**Comment by cjb** [comment]
Closing this out, the choice not to use GTK or KDE is intentional.
