### ISSUE TITLE
Timeout listing user folder contents.

### ISSUE THREAD

**Issue by jrosengren** [keybase/client#3780]
Seeing a timeout error when trying to view another user's public folder through Finder or command-line.

my log id: b2c54ef2159e1d6941c8221c

**Comment by jrosengren** [comment]
Killing all of the Keybase processes and restarting the app appears to have fixed the issue.

**Comment by strib** [comment]
Looks like you were unable to connect to our backend servers during this time, leading to the timeouts.  Hopefully (for us) it was a client-side networking issue that resolved itself.
