### ISSUE TITLE
Installing in Ubuntu getting error

### ISSUE THREAD

**Issue by wksantiago** [keybase/client#3817]
I am getting the following error:

pi@ubuntu21computer:~$ sudo dpkg -i keybase_i386.deb
Selecting previously unselected package keybase:i386.
(Reading database ... 116656 files and directories currently installed.)
Preparing to unpack keybase_i386.deb ...
Unpacking keybase:i386 (1.0.16-20160809160037.24badd1) ...
dpkg: dependency problems prevent configuration of keybase:i386:
 keybase:i386 depends on libappindicator1; however:
  Package libappindicator1:i386 is not installed.
 keybase:i386 depends on fuse; however:

dpkg: error processing package keybase:i386 (--install):
 dependency problems - leaving unconfigured
Processing triggers for mime-support (3.59ubuntu1) ...
Errors were encountered while processing:
 keybase:i386
pi@ubuntu21computer:~$

**Comment by wksantiago** [comment]
https://github.com/keybase/client/issues/new?body=[write%20something%20useful%20and%20descriptive%20here]%0A%0Amy%20log%20id:%200ea8dd0ffbd9c2d05fa0661c

**Comment by wksantiago** [comment]
my log id: 0ea8dd0ffbd9c2d05fa0661c

**Comment by strib** [comment]
You need to install the dependencies:

```
dpkg: dependency problems prevent configuration of keybase:i386:
keybase:i386 depends on libappindicator1; however:
Package libappindicator1:i386 is not installed.
keybase:i386 depends on fuse; however:

```

**Comment by strib** [comment]
See the rest of the instructions on the download page:

```
...
sudo apt-get install -f
run_keybase
```

**Comment by wksantiago** [comment]
My challenge is ho to install libappindicator1

**Comment by cjb** [comment]
The `apt-get install -f` line will do it for you.

**Comment by wksantiago** [comment]
Thanks
