### ISSUE TITLE
Individual Private Folder not appearing in the Widget

### ISSUE THREAD

**Issue by jtsmith0101** [keybase/client#3820]
Keybase GUI Version: 1.0.16-20160726182352+0c2a52a

Weird

**Comment by strib** [comment]
Could you please do a `keybase log send` and/or a screenshot to explain what you mean?

**Comment by jtsmith0101** [comment]
Log ID: 67699923c10dce4a6da8d61c

Have a look at the attached to see what I mean....

The widget doesn't display my private folder (just me), but the folder does
exist

On another note, I'm unable to remove folders.  The zombie things keep
returning!
