### ISSUE TITLE
Keybase freezes upon hitting Get Info in Finder

### ISSUE THREAD

**Issue by awesomebing1** [keybase/client#3824]
I opened up my keybase private folder and decided to hit get info in the Finder. The window immediately froze, and I got a notification from Keybase saying it was rekeying. It continued to freeze until I finally got another notification saying there was a read timeout and that I should run `keybase log send`, leading me to submit this issue. I'm using El Capitan (10.11.6), and I suspect the read timeout was because of some DNS issues on my network.

my log id: 42cd2f6de18c69be3801471c

**Comment by strib** [comment]
Hi @awesomebing1 -- yeah, it looks like it took a really long time to connect to one of our servers:

```
2016-08-10T11:34:37.235648 ▶ [WARN kbfs(BSR) bserver_remote.go:153] 774d disconnected
2016-08-10T11:34:37.235759 ▶ [DEBU kbfs connection.go:348] 774e (CONN BlockServerRemote 8dc960cb) Connection: dialing transport
...
2016-08-10T11:34:51.150443 ▶ [DEBU kbfs connection.go:380] 7798 (CONN BlockServerRemote 8dc960cb) Connection: connected
```

Potentially due to a DNS lookup being slow, as you suggested, though I can't say for sure.  We are working on a solution that will work better under poor network conditions.

**Comment by awesomebing1** [comment]
Okay, good to know. I figured I should upload it just in case it wasn't a DNS issue.

I'm going to close this since it's working for me now, plus it wasn't your issue, it was mine (as a client).
