### ISSUE TITLE
keybase update doesn't work in Windows and upd.exe hangs

### ISSUE THREAD

**Issue by mfczureal** [keybase/client#3842]
Keybase GUI Version: 1.0.16-20160713110836+a1c00b3

I run "upd check" and it seems to run okay, but running upd.exe tells me it finds keybase.exe okay, then an INFO line that says "updater 0.2.5" and a Debug line "Starting (ticker 1h0m0s)" and just hangs there.  I can't find any docs on how this command should be run.

**Comment by cjb** [comment]
It's waiting an hour before performing its next check.

upd.exe should be running in the background already. You shouldn't have to launch it.

**Comment by mfczureal** [comment]
Ahhhh...good to know, thank you.  I just checked task manager and indeed, upd.exe is already running.
