### ISSUE TITLE
MultiAccount Permission Issue

### ISSUE THREAD

**Issue by Wolf1098** [keybase/client#3862]
I have logged into 2 different accounts and browsed files and now get spammed with 

Keybase: Access Denied
You don't have {something} access to \keybase\private{private folder} 

after loging out
#### Edit Adding Attachment

![keybase](https://cloud.githubusercontent.com/assets/11269584/17611708/7f7b84d0-5ffe-11e6-8824-5e277b56b735.png)

my log id: 887b00b09e5a54b0d9c10a1c

**Comment by strib** [comment]
This is probably the result of Windows trying to load recent content you've looked at.  Maybe try clearing out the recent list of files from explorer?  (e.g., http://www.tenforums.com/tutorials/6712-file-explorer-history-clear-windows-10-a.html)

**Comment by Wolf1098** [comment]
Imma try it and see

**Comment by Wolf1098** [comment]
Seems to have fixed the issue, I wounder if there is a work around, i feel like it wouldn't be easy to implement except clearing the cache when you logout of the client which isn't ideal
