### ISSUE TITLE
App is not loading on a Mac

### ISSUE THREAD

**Issue by davedub** [keybase/client#3865]
Running OS X El Capitan Version 10.11.6

All I see after launching the app is a "loading ..." wait page.

![screen shot 2016-08-11 at 10 52 53 pm](https://cloud.githubusercontent.com/assets/961729/17613885/8b41f656-6016-11e6-90c9-062185c6a14d.png)

Thus any troubleshooting on the command line is impossible

 ~ $ keybase login
zsh: command not found: keybase

What am I doing wrong ..? Thanks ..

**Comment by kylebrowning** [comment]
They've said multiple times it doesn't work on macOS Sierra.

**Comment by cjb** [comment]
@kylebrowning This reporter says they're on El Capitan, not Sierra.

**Comment by kylebrowning** [comment]
My bad.

**Comment by cjb** [comment]
CC @gabriel

**Comment by davedub** [comment]
Working now after rebooting machine.
