### ISSUE TITLE
RPM signature not verifiable

### ISSUE THREAD

**Issue by Achimh3011** [keybase/client#3868]
at least I could not find the key anywhere.

```
Retrieving package keybase-1.0.16.20160809160037.24badd1-1.x86_64                               (1/1),  56.8 MiB (172.3 MiB unpacked)
keybase_amd64.rpm:
    Header V4 RSA/SHA1 Signature, key ID 656d16c7: NOKEY
    V4 RSA/SHA1 Signature, key ID 656d16c7: NOKEY

keybase-1.0.16.20160809160037.24badd1-1.x86_64 (Plain RPM files cache): Signature verification failed [4-Signatures public key is not available]
Abort, retry, ignore? [a/r/i] (a): 
```

**Comment by strib** [comment]
cc @oconnor663

**Comment by oconnor663** [comment]
@Achimh3011 could you include the command you ran to get to this point? Did you install directly with `rpm`?

I think if you use the instructions [here](https://keybase.io/docs/the_app/install_linux) and install with `yum` (or probably with `dnf` in some slightly modified way), you will bypass this error. In the state that you're seeing, I think it'll work if you choose ignore too, and then it should install our PGP key in your RPM keyring. (That might feel dirty compared to getting the fingerprint from our website and fetching the key manually first, but at the end of the day I think both approaches are open to the same Evil Keybase attacks.)

**Comment by Achimh3011** [comment]
@oconnor663 yes, it feels dirty. Posting the public key for your RPM-signing in *multiple* places (including the github repo) would give it a lot more cred. Sure, its not totally proof, but at least one could verify it in different places before installing some binaries that do who-knows-what on one's system.

**Comment by oconnor663** [comment]
Ah I probably should've mentioned a couple places where you can get it:

https://keybase.io/docs/server_security/our_code_signing_key
https://github.com/keybase/client/blob/master/packaging/linux/code_signing_fingerprint

**Comment by Achimh3011** [comment]
Oh, I did not search long enough... Thanks for the pointer. Maybe a link on the download page would make sense in the longer run? Anyway, after importing the key signature verification worked during installation (as expected).

**Comment by oconnor663** [comment]
Great. I'll go ahead and add a mention on that page. Thanks for following up.
