### ISSUE TITLE
Need global options

### ISSUE THREAD

**Issue by zander** [keybase/client#3869]
The keybase app supports tor by adding 2 arguments to the invocation of 'keybase'.

The problem is that after a reboot (linux with kde) the keybase background process is already running and it already started communicating with the main server over the plain internet.

Ideally I could edit the (json) config file to make sure that the arguments I need to be passed to the background instance as well as the keybase-fuse process are passed automatically without any manual interference from me.

Maybe this is already possible but the config file just isn't documented to the level that it should be, in which case I'd love to know how to make this work.

Otherwise I'd suggest a new feature to be added which is that there is some config file for command-line arguments.

**Comment by cjb** [comment]
The desktop autostart file calls a command called `run_keybase` -- I think you can edit that shell script to do what you need.  Oh, but it'll be overwritten when you upgrade Keybase.. so I guess you're right that we can't do this easily yet.

**Comment by abeluck** [comment]
I looked everywhere for this, and finally stumbled on this issue.

I just want a package/update friendly way to add `--tor-mode` or `--proxy` to the `run_keybase` script.

**Comment by libBletchley** [comment]
Some more undocumented things this dodgy package does:
 * Creates a daily cronjob in `/etc/cron.daily/keybase`
 * Tampers with Chromium and Firefox (`/etc/chromium/native-messaging-hosts/io.keybase.kbnm.json`, `/usr/lib/mozilla/native-messaging-hosts/io.keybase.kbnm.json`)
 * Injects a blob that is described as a "snapshot blob" (`/opt/keybase/snapshot_blob.bin`)
 * Injects a blob to do something with git (`/usr/bin/git-remote-keybase`)
 * Injects a blob called `kbnm`
 * Creates a `kbfs` service (possibly for file sharing, but we can only guess from github content as opposed to the user guide)

**Comment by zander** [comment]
@libBletchley I suggest you investigate what those files do, calling them "blobs" is rather odd, they are open source scripts or executables for most I checked.

Either way, please open a different task, I opened this one and your comments are completely irrelevant to this specific issue. You are confusing issues here.

**Comment by libBletchley** [comment]
@zander
> I suggest you investigate what those files do

That's just it.. I shouldn't have to.  It should be documented.  Your words: "just isn't documented to the level that it should be" .. "I'd love to know how to make this work."

Furthermore, public inquiry _is_ investigation.

> calling them "blobs" is rather odd, they are open source scripts or executables for most I checked.

None are scripts.  One is simply "data":
```
$ file /usr/bin/kbnm
/usr/bin/kbnm: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, not stripped
$ file /usr/bin/git-remote-keybase
/usr/bin/git-remote-keybase: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 2.6.32, BuildID[sha1]=250aad55705a64ef761b9a3bd6aa58799ccceecb, not stripped
$ file /opt/keybase/snapshot_blob.bin
/opt/keybase/snapshot_blob.bin: data
```
Sure I could examine the code (considering the lacking docs), and maybe I will once I'm assured that I'm not repeating someone elses effort.  But the lacking docs is the common issue here.

> Either way, please open a different task, I opened this one and your comments are completely irrelevant to this specific issue. You are confusing issues here.

You said:

"after a reboot (linux with kde) the keybase background process is already running and it already started communicating with the main server over the plain internet."

This is my problem.  Same issue.

It's a server pretending to be an app.  It's undocumented.  It fails the rule of least astonishment because it does unexpected things making clearnet connections without notice.

**Comment by zander** [comment]
> I shouldn't have to. 

Sorry, keybase is not someone you paid money to, they owe you nothing.Your attitude where you claim normally build executables from open source code are 'blobs' is one that gets you ignored. Its close to wilful ignorance.

You are writing comments to "my" bugreport with the result of the chances of my issue getting addressed less and less as you rant on and on.

Please go open your own issue.

**Comment by libBletchley** [comment]
> Sorry, keybase is not someone you paid money to, they owe you nothing.

This is a deeply and profoundly naïve expression of idiocy demonstrating copious flaws and misunderstandings.

1. We do not write bug reports to get a handout - bug report authors have no expectation of benefiting from it
2. Bug reports are an uncompensated contribution **from** the author **to** the project (you have it backwards as to where the contribution is being made)
3. Bug reports serve to warn **other users** of issues, even if it fails to advance the quality of the software
4. The gratis nature of a project is wholly irrelevant and does not justify bugs, tricks, traps, pitfalls, shenanigans, or suppression of reports thereof.
5. Bugs are a reality in free software as well as proprietary software.  Discoverers have a moral **duty** to report what they find regardless of what they paid for the software.

> You are writing comments to "my" bugreport 

You do not own a bug report.  Bug reports are a community effort and github has designed them as such.  If you don't want to participate in society, please excuse yourself.  A proprietary project is more suitable for you if you want to own something.

**Comment by oconnor663** [comment]
I've deleted some comments from this thread for being not nice. Let's keep it nice folks.

@zander we're a few days away from turning on systemd integration for our background services. Once that's all turned on (or if you want to turn it on yourself now by setting `KEYBASE_SYSTEMD=1` in whatever place affects your whole desktop), you should be able to edit the flags that the service is started with using something like `systemctl --user edit keybase.service`. (Some [examples](https://askubuntu.com/a/659268/73244).) Please let us know if you get a chance to give that a shot.

**Comment by zander** [comment]
> we're a few days away from turning on systemd integration for our background services.

Can you point to more docs on the design for this?

My first thought is that the current keybase system is per-user, you can have multiple users on the same single machine use different keybase accounts.  
How is this property preserved in a system-wide service? Security to separate those users chats etc sounds rather tricky to do.

**Comment by oconnor663** [comment]
Apologies for not documenting this at all (you can find some details in another issue: https://github.com/keybase/client/issues/5355#issuecomment-342590835). In part that's because our documentation story isn't stellar in general, and in part it's because the exact details won't be stable until we've had it turned on in production long enough to be confident of them.

To your specific question, we're installing user-level services, rather than system-wide services, so the security situation shouldn't change much. If you look inside `run_keybase`, you can see our two startup paths, `start_background` (old) and `start_systemd` (new, but still off by default). In particular, in the latter we launch our services with `systemctl --user`.

**Comment by libBletchley** [comment]
@oconnor663 
> I've deleted some comments from this thread for being not nice. Let's keep it nice folks.

Holy shit!  When i read this in email, i figured you just deleted the uncivil comments (which would have amounted to 2 msgs at most), not actual bug reports!  It's very malicious, uncivil, and destructive to censor bug reports.

**Comment by xkr47** [comment]
Couldn't we just change the `--tor-mode` to persistently save the mode to use and always use that after that in that installation? A new option `--tor-mode none` would then be needed to persistently disable it if one wanted to.

Alternatively you could add a new flag not to break existing usage e.g. `--tor-mode-persist <mode>`.

Then we wouldn't have to worry about hacky editing of startup scripts and whatnot other software that might use keybase..

**Comment by heronhaye** [comment]
@xkr47 You can change your tor mode settings with the json config file. See https://keybase.io/docs/command_line/tor.

In general, most options can be controlled by the json config file permanently without messing with run_keybase or editing systemd units. But if you need more control and you're on systemd, you can use drop-in units; they won't be overwritten on upgrade.
