### ISSUE TITLE
Windows client issue

### ISSUE THREAD

**Issue by tonkku107** [keybase/client#3887]
Keybase GUI Version: 1.0.16-20160713110836+a1c00b3

I got sick of it asking for the password on every time I started up my computer, I disabled it from starting as I start my computer, and now I have no way of opening it without running the installer with the repair option... The GUI also wont let me login at all.

**Comment by maxtaco** [comment]
cc: @zanderz

**Comment by zanderz** [comment]
The startup mechanism is just a shortcut in the startup folder. If you copy those somewhere else, you can invoke them when you wish. Note that one shortcut is for the background services, and one is for the GUI - you won't be able to login without both.

**Comment by tonkku107** [comment]
The startup folder is empty. I disabled 2 runquiet.exes from task manager's startup section to make it not start on startup. I tried running those manually, but nothing happens.

**Comment by juanminm** [comment]
@tonkku107 You must run them like this:

For the Service: `runquiet keybase.exe ctl watchdog2`
For the GUI: `runquiet Gui\keybase.exe` or just open it on the start menu

**Comment by tonkku107** [comment]
Alright, thanks.
Would be nice to have a shortcut on the start menu that starts both tho...

**Comment by zanderz** [comment]
Also, BTW, the GUI is now smart enough to start the services if they are not found, so you shouldn't need both links any longer.
