### ISSUE TITLE
Accessible appcast?

### ISSUE THREAD

**Issue by vitorgalvao** [keybase/client#3898]
In [homebrew-cask](https://github.com/caskroom/homebrew-cask) (CLI tool to install GUI apps on macOS), our reference files for each app (called “casks”, [here’s the one for keybase](https://github.com/caskroom/homebrew-cask/blob/master/Casks/keybase.rb)) contain all the details to install and uninstall the specific app, but we also like to have an appcast, as it (with the help of automated scripts) helps us to know when a cask is outdated and update it, so any user installing it through us will get the most up-to-date version.

[Another homebrew-cask member](https://github.com/caskroom/homebrew-cask/pull/23819#issuecomment-239975766) found [this file](https://github.com/keybase/client/blob/master/osx/Scripts/Updater/site/appcast.xml), but there are some problems with it. The first thought is to use the URL for the appcast referenced in it (https://keybase-app.s3.amazonaws.com/appcast.xml) but it is unavailable. The second though is to use that github-hosted file itself, but it only references up to version `0.1.8` while the link on [your downloads page](https://keybase.io/docs/the_app/install_macos) downloads version `1.0.16`. The thought is then to use [your github releases page](https://github.com/keybase/client/releases) (since we can get an appcast from it by just [appending `.atom` to the URL](https://github.com/keybase/client/releases.atom)), but that is at version `1.0.17`.

Do you have any appcast URL we can leverage, that is in sync with the app downloaded from the website?

**Comment by maxtaco** [comment]
Cc: @cjb

**Comment by cjb** [comment]
Also CC @gabriel

**Comment by gabriel** [comment]
There is no current appcast (the one in the repo is really really old from when we were experimenting with a fully native app).
We're still in "prerelease" mode, but once we start doing more standard type releasing, we'll want to support a cask and so will probably do it then. We're getting close to that but not quite there.

**Comment by vitorgalvao** [comment]
We’ve since [added one](https://github.com/caskroom/homebrew-cask/blob/46733648d038b1f5a8f1df6b5c8afeeb6aa69fa4/Casks/keybase.rb#L6) that seems to be working.
