### ISSUE TITLE
Bluescreen on Windows

### ISSUE THREAD

**Issue by stylersnico** [keybase/client#3899]
Hi,

The latest Keybase client cause bluescreen on Windows.

How can I have the simple command line client again ? I don't want a GUI or a filesystem from keybase, just command line client.

[dump.txt](https://github.com/keybase/client/files/419981/dump.txt)

[Desktop.zip](https://github.com/keybase/client/files/419983/Desktop.zip)

Thanks

**Comment by maxtaco** [comment]
cc: @zanderz

**Comment by zanderz** [comment]
Do you have a security suite with a filesystem driver installed, such as BitDefender, Symantec, etc.? We have found conflicts with certain of these drivers and will be releasing a fix sometime soon.

You can uninstall Dokany and remove the startup shortcuts to have just command line, but it is not an officially supported configuration.

**Comment by stylersnico** [comment]
Yes, I do, I have the latest Bitdefender Total Security installed.

**Comment by zanderz** [comment]
We will soon be releasing https://prerelease.keybase.io/windows/Keybase_1.0.17-20160820134520%2B9aefaa4.386.exe, which has updated drivers that work better with BitDefender. You can try it now if you like, it would be helpful for us to know whether you still get blue screens.

**Comment by stylersnico** [comment]
@zanderz I'm using it since yesterday afternoon and everything just work fine, thanks 👍
