### ISSUE TITLE
OS X: App won't load

### ISSUE THREAD

**Issue by cspeer** [keybase/client#3900]
Keybase GUI Version: 1.0.16-20160803190018+268b023

Hi there,

after installing and starting the app the app's screen says "Loading..." but nothing happens, the app won't load.

**Comment by cjb** [comment]
CC: @gabriel

**Comment by Geekfish** [comment]
Hey guys, I've got the same issue. At first I thought maybe little snitch is blocking it, but I have disabled it and still getting the same problem.

**Comment by LDubya** [comment]
same

version: 1.0.16-20160803190018+268b023

**Comment by ceez** [comment]
Same problem.

I was able to do a brew install keybase and get the CLI, however.

**Comment by gabriel** [comment]
Sorry this fell off my radar...

Can you try this more recent version:
https://s3.amazonaws.com/prerelease.keybase.io/darwin/Keybase-1.0.17-20160823110029%2Bdfc9854.dmg

If it still doesn't work can you do a log send and post the ID:

```
/Applications/Keybase.app/Contents/SharedSupport/bin/keybase log send
```

And if you could try running the installer manually:

```
/Applications/Keybase.app/Contents/Resources/KeybaseInstaller.app/Contents/MacOS/Keybase --app-path=/Applications/Keybase.app --run-mode=prod
```

and lmk what happens to that. Thanks!

**Comment by gabriel** [comment]
We have a new build which might resolve installer flakiness, in this build if you want to try it out:
https://keybase.pub/gabrielh/Keybase-1.0.17-20160830185045%2B1a947f1.dmg

**Comment by gabriel** [comment]
Known issue we are working on getting fix into release channel. See https://github.com/keybase/client/issues/4150 for more info. 

If you encounter this bug, this build resolves it temporarily:
https://keybase.pub/gabrielh/Keybase-1.0.17-20160830185045%2B1a947f1.dmg
