### ISSUE TITLE
Cannot create shared private folder from Linux (RHEL7.2, SELinux enabled), access works

### ISSUE THREAD

**Issue by jwildeboer** [keybase/client#3903]
Trying to cd /keybase/private/georgzoche,jwildeboer for the first time ever on Linux results in endless loop of something. The command never returns. Sending a SIGHUP (CTRL-C) does nothing. I had to close the terminal window.

Doing the same on MacOS Just Works(tm). I created a test.txt file from my Macbook. And lo and behold. *AFTER* I did that on MacOS I could cd to it on Linux and read and edit the file just fine.

So I *guess* that the initial access on a non-used shared directory from a Linux machine fails for some reason.

my log id: da39d0bc4849ddefc5b04e1c

**Comment by strib** [comment]
Hi @jwildeboer -- super weird.  In the log I see where you are looking up the shared folder, and from our perspective it looks like it succeeds, but then later an interrupt comes in (presumably from you hitting ctrl-c).  Example:

```
980 2016-08-16T17:15:19.902989 ▶ [DEBU kbfs(kbfsfuse) folderlist.go:100] 3d6 FL Lookup georgzoche,jwildeboer [tags:FID=kJ1BD-2o5CzHAkiUqm8mkA]
981 2016-08-16T17:15:19.903086 ▶ [DEBU kbfs(kbfsfuse) folderlist.go:103] 3d7 Request complete [tags:FID=kJ1BD-2o5CzHAkiUqm8mkA]
982 2016-08-16T17:16:52.314657 ▶ [DEBU FUSE serve.go:783] 3d8 <- Interrupt [ID=0x129 Node=0x0 Uid=0 Gid=0 Pid=0] ID 0x128
983 2016-08-16T17:16:52.315225 ▶ [DEBU FUSE serve.go:845] 3d9 -> [ID=0x129] Interrupt
```

That "Request complete" line is the last thing KBFS logs on the way back out after servicing the request.

However, usually `bazil.org/fuse` would log something when it sends the response back to the user, but I don't see that happening here.  @tv42 maybe you can take a look to see why the fuse layer doesn't think the request is complete?

Also @jwildeboer -- another `keybase log send` after you got it working might be useful.  Thanks!

**Comment by jwildeboer** [comment]
Here are the exact steps performed. Environment: RHEL 7.2 x86_64 up2date. The shared directory has never been used before.

1.  cd /keybase/private/georgzoche,jwildeboer in shell. Hm. Nothing happens, command doesn't return. Press CTRL+c a few times. Nothing.  Maybe CTRL+z? Nope. 

2. Open the app on the top bar (I use Gnome), switch to private, good. I see the directory.  So open it in Nautilus. Says "loading ..." In the taskbar. Right click in Nautilus, trying to create a txt file. File progress dialog opens but also never returns.

3. Close Nautilus window. Close creating file window. Close terminal.

4. Hm. Still nothing. Keybase logout.  Keybase login. Hrmpf. Error window "you might lose files, use other machine" or sth similar.

5. Switch to MacBook Air. cd via terminal. Works! Create a txt file. Works! Ok. Back to Linux. cd. Works. Textile? Yup. Is there.

Will send current log when back home. ATM enjoying beer in beer garden. Munich life, sorry ;-)

**Comment by tv42** [comment]
@strib After the `Lookup` handler returns successfully, there's a call to `Attr` on the new `Node`, maybe a `GenerateInode` (not used by kbfs), and the new `Node` is saved to a `NodeID`->`Node` lookup table. The last bit needs a mutex, which is not meant to be held for long, or while calling app logic. Triggering a stack trace would give more info.

**Comment by tv42** [comment]
@strib Oh if the mutex from my last comment was at fault, the `Interrupt` would hang too, before sending the response.

**Comment by strib** [comment]
@tv42: Ah ok, thanks.  Looks like it's theoretically possible for the Attr call into KBFS (on a`libfuse.TLF` node type) to hang without printing anything.  I'll stare at it some more.

**Comment by strib** [comment]
Now I see where the hang is originating, and it's definitely in KBFS while holding the libfuse dir lock:

```
2016-08-16T17:13:43.109964 ▶ [DEBU kbfs(kbfsfuse) dir.go:755] 38d Loading root directory for folder georgzoche,jwildeboer (public: false) [tags:FID=mmzB4rfMw6PqV2IvNCarFw]
2016-08-16T17:13:43.110028 ▶ [DEBU kbfs kbfs_ops.go:291] 38e GetOrCreateRootNode(/keybase/private/georgzoche,jwildeboer, ) [tags:FID=mmzB4rfMw6PqV2IvNCarFw]
```

This operation never returned.  It did reach the server, and the server returned the expected response.  It must be stuck somewhere in between fetching the metadata and identifying the participants, but I'm not sure where that could be.  Maybe once @jwildeboer uploads a new log send I'll get more clues by looking at how it got unstuck.

**Comment by jwildeboer** [comment]
And here is another one after going into a new directory that didn't exist. It got stuck after trying to ls:

Log id: 3712259fd747977bef1ac51c

[jwildebo@jwildebo ~]$ cd /keybase/private/jwildeboer,exiledsurfer
[jwildebo@jwildebo jwildeboer,exiledsurfer]$ ls
^Cls: cannot open directory .: Interrupted system call

[jwildebo@jwildebo jwildeboer,exiledsurfer]$ keybase log send

**Comment by jwildeboer** [comment]
System information:

[jwildebo@jwildebo ~]$ cat /etc/redhat-release 
Red Hat Enterprise Linux Workstation release 7.2 (Maipo)
[jwildebo@jwildebo ~]$ uname -a
Linux jwildebo.XXXXXXX.csb 3.10.0-370.el7.rhel73drm.10.x86_64 #1 SMP Thu Mar 31 11:25:20 EDT 2016 x86_64 x86_64 x86_64 GNU/Linux
[jwildebo@jwildebo ~]$ rpm -qa | grep keybase
keybase-1.0.17.20160815160038.99c5a56-1.x86_64

**Comment by jwildeboer** [comment]
2 months with no communication, closing issue.
