### ISSUE TITLE
no way to disable launch on startup?

### ISSUE THREAD

**Issue by huzzam** [keybase/client#3904]
Keybase GUI Version: 1.0.16-20160803190018+268b023

I can find no way to disable Keybase from launching on computer startup / account login. The normal method of auto-starting — addition in the "Users & Groups" control panel / Login Items tab, doesn't seem to be used here. Additionally, there's no preference for not autostarting.

on OSX

**Comment by afaur** [comment]
Open finder and press `cmd+shift+g` then type in `~/Library/LaunchAgents` and press enter.
<img width="185" alt="folder" src="https://cloud.githubusercontent.com/assets/898523/17827592/fa0257b4-6644-11e6-935e-44b47441b7ae.png">
You will find three files in this directory that you will need to remove. (see below)
<img width="310" alt="files" src="https://cloud.githubusercontent.com/assets/898523/17827608/46d2864a-6645-11e6-9ca6-80a5a100fd43.png">
Restart computer and keybase should not be running at startup.

For more information about launchd visit: http://launchd.info/

**Comment by huzzam** [comment]
thank you! will this also disable my ability to use keybase when i want to?

**Comment by afaur** [comment]
Very good question.  I honestly am not sure, I just tried running again and looks like it will prompt you to try and reinstall some things.  I did this myself because I figured if it didn't work next time I use it I would just reinstall, and that would be less annoying since I don't use it often.

**Comment by lukejanicke** [comment]
@afaur Yes, that works.

I am guessing the developers intend to provide a "Launch at Login" option in the apps preferences. Even still, the app should use System Preferences > Users & Groups > Login Items. That way ordinary users can easily control Keybase launch behaviour.

**Comment by derekhardwick** [comment]
@lukejanicke this!  Login items should always be used for this kind of thing.

**Comment by jhellenthal** [comment]
It would be really great if the GUI would not pop on login as well. While I don't spend a lot of time logging out or in from restarts or otherwise... it is not always a preferable matter to let unintended viewers of your screen to know what you are running or using actively. Nor is it enjoyable having to close the keybase window upon every login. Workflow or initial login becomes a nuisance. Please provide an option to only load the status bar icon instead.

**Comment by jhellenthal** [comment]
For others looking to disable key base launch options please see ( keybase help launchd )...
$ keybase launchd list
keybase.service: Running (pid=416) [Keybase]
keybase.kbfs: Running (pid=427) [KBFS]
keybase.updater: Running (pid=407) [Updater]
$ keybase launchd uninstall keybase.service

etc...

**Comment by phlebotinum** [comment]
Just realized there is no option. INSTANT UNINSTALL. Let me know when your marketing strategies grow up.

**Comment by ffflorian** [comment]
Same on Debian. Of course I can delete `~/.config/autostart/keybase_autostart.desktop`, but everytime I start the Keybase Client, the autostart file was created again. Quite annoying.

**Comment by uapasha** [comment]
@ffflorian this file has following lines
```
# Uncomment the following line to disable Keybase autostart:
# Hidden=true
```
I guess uncommenting this may help.

**Comment by ffflorian** [comment]
@uapasha Thanks, good idea.

**Comment by NoahO** [comment]
This is a problem for me too. Now that Keybase has a mobile client, I'd prefer to not have the mac client taking space on my menu bar, when I'm going to get push notifications on my phone of changes anyway.

**Comment by aaronraimist** [comment]
Not sure when it changed but it is definitely in the Login Items settings as of version 1.0.34-20171027003854+8e989533a. You can close this issue.

![screen shot 2017-11-10 at 6 46 00 pm](https://user-images.githubusercontent.com/5855073/32684394-b68053d2-c648-11e7-9088-a2df4c53296f.png)

**Comment by maxtaco** [comment]
The update here is that we've found a race-condition that sometimes prevents the setting from sticking. We'll hopefully fix it in the next release. Thanks for your patience!

cc: @patrickxb

**Comment by olivercaine** [comment]
Even after disabling Keybase in Login Items it readds itself after a restart. Very annoying.

**Comment by heronhaye** [comment]
@olivercaine on mac, please disable Keybase autostart from within the app in Settings->Advanced.
