### ISSUE TITLE
Ubuntu 12.04 Keybase App Stalls Indefinitely

### ISSUE THREAD

**Issue by nicorellius** [keybase/client#3931]
Basically, keybase CLI works, but the GUI doesn't. I get the attached window indefinitely. Previously, it would go beyond this but stall after I enter my username. It would never ask for password... Now it just stalls at the attached window.
![keybase_app_stall](https://cloud.githubusercontent.com/assets/3189080/17742816/5f4d17a8-6456-11e6-9c72-7048074d7397.png)

my log id: 5cb5fe7da20872b109155c1c

**Comment by cjb** [comment]
It looks like you don't have an `$XDG_RUNTIME_DIR` environment variable set.  You could try:

XDG_RUNTIME_DIR=$HOME/.config run_keybase

**Comment by nicorellius** [comment]
That worked nicely. Thanks!
