### ISSUE TITLE
[Windows] Uploading .msi timed out

### ISSUE THREAD

**Issue by coldwaterq** [keybase/client#3946]
When I tried to copy the Pokemon Uranium installer to my keybase file system on windows the operation timed out. Let me know if you need any other information. And thanks for making this.

my log id: 9168174098870a4f5e9b811c

**Comment by strib** [comment]
Thanks, looks like you hit a known issue with uploading large files in that release. We're actively working on it, the next release should be a bit better, with some major improvements coming in a few months.

However, I'm more concerned about the panic you hit just after the timeout:

```
1637 unexpected fault address 0x1f270b6
1638 fatal error: fault
1639 [signal 0xc0000005 code=0x0 addr=0x1f270b6 pc=0x454bec]
1640
1641 goroutine 690 [running]:
1642 runtime.throw(0xf97290, 0x5)
1643 C:/Go/src/runtime/panic.go:547 +0x7f fp=0x1249968c sp=0x12499680
1644 runtime.sigpanic()
1645 C:/Go/src/runtime/signal_windows.go:164 +0x116 fp=0x124996a4 sp=0x1249968c
1646 runtime.memmove(0x1abac330, 0x1f270b6, 0x7fcc4)
1647 C:/Go/src/runtime/memmove_386.s:77 +0x6c fp=0x124996a8 sp=0x124996a4
```

Looks like you might have run out of memory.  Are you willing to share how many GB of RAM this Windows machine/VM has?  Thanks!

**Comment by coldwaterq** [comment]
I'm not positive which laptop I was on when I submitted that, so it was either one with 8 GB or one with 16GB. Either way, it would have had enough memory that it shouldn't be running out in my opinion. They both have Windows 10 64bit.

Is it possible that the language you are using, looks like Go, has a default memory size for the program. I know Java has this and it can be super annoying. Or maybe things just aren't getting freed.

Best of luck, and let me know if you need anything else.

**Comment by taruti** [comment]
The Windows build is 32bit so it can use much less memory at most ~2gb.

**Comment by coldwaterq** [comment]
Then the ~2GB limit is definitely the memory limit the program had at the
time of execution, because I had much more than that available at the time.

**Comment by strib** [comment]
Version 1.0.20 has architectural changes that should greatly improve the large write experience.  If you're still seeing problems, please open a new issue.
