### ISSUE TITLE
Windows public folder is Read Only

### ISSUE THREAD

**Issue by coldwaterq** [keybase/client#3952]
The K:\public\coldwaterq folder can't have anything moved to it. I moved things into it from my other computer yesterday and that worked, and I can create a folder and move things into the new folder, but I can't move things into the root of K:\public\coldwaterq.

If there is anything you would like me to try let me know. I have tried signing out of Windows and back in, and Signing out of Keybase and back in but neither fixed it. 

my log id: fd4e6a650d265d2b06351a1c

**Comment by coldwaterq** [comment]
So it turns out that only robots.txt couldn't be copied, but I could create a file in the directory called robots.txt and put the same data in it, so I don't really know what the issue was?

**Comment by strib** [comment]
For the record, this didn't have anything to do with the particular file -- it looks like there is a bug that made it looked like you were logged out to our servers, when really you weren't.  We'll be looking into it.  Sorry for the inconvenience and thanks for the report.

**Comment by strib** [comment]
Confirmed that this is something we fixed already, and will be in the next Windows release.

**Comment by coldwaterq** [comment]
Awesome, glad I could help, and I will continue to report anything I find.
Love your sites, and tools. Thanks.

**Comment by taruti** [comment]
@coldwaterq Did the new Windows version solve things for you?

**Comment by coldwaterq** [comment]
I haven't run into this issue again and was able to transfer the file that was failing before, but I don't think I updated. I am version 1.0.16-20160713110422+a1c00b3, and I haven't noticed an update dialog. Does it just do it in the background, or do I have to do something?

**Comment by zanderz** [comment]
Hopefully releasing 1.0.17-20160822152935+692af12 today, stay tuned. You should get a dialog prompting to install the update. We'll check back with you to make sure once we've released.

**Comment by zanderz** [comment]
v1.0.17-20160822152935+692af12 is in the public update channel. If you aren't prompted within 24 hours, open the Keybase Shell and enter `upd check`.

**Comment by coldwaterq** [comment]
I got the update, I'll let you know and open this if this issue happens
again.
