### ISSUE TITLE
Notification panel menu is unusable when Google Analytics is blocked 

### ISSUE THREAD

**Issue by reece** [keybase/client#3955]
Keybase GUI Version: 1.0.17-20160816160049+f27f469
Ubuntu 16.04

I installed Keybase yesterday. This showed up in the notification panel:

![selection_046](https://cloud.githubusercontent.com/assets/109453/17786835/842b7c96-653b-11e6-9c46-6f2acc7efeaf.png)

The cause is that I use Privacy Badger, which by default disables Google Analytics URLs. Enabling Google Analytics immediately fixed the problem.

**Comment by cjb** [comment]
Huh, that seems unlikely to be the cause -- as far as I know, we don't use Google Analytics at all.  Please could you re-run the experiment?

**Comment by reece** [comment]
Okay, I'm all washed up. I can't reproduce. Closing. I'll reopen if it recurs . Sorry for the chatter.

**Comment by cjb** [comment]
Thanks.  FWIW we bind "ctrl+alt+k+b" to open that pane, so that's one possible cause for it opening.  Another might be an error condition that you saw once but can't reproduce.
