### ISSUE TITLE
Can't remove favorite public folders (Windows)

### ISSUE THREAD

**Issue by mplx** [keybase/client#3958]
I did the public folders tutorial on the keybase website with user `chris` but when I remove the folder as described in the docs it still shows up again after deletion.

I want to get rid of `chris` - sorry! ;) - but it doesn't work at all: deleted in Windows Explorer, cmd shell and cygwin bash. Also installed the current keybase client on a fresh Windows installation - folder is still here.

`keybase 1.0.16-20160713110422+a1c00b3`
`kbfsdokan 1.0.2-20160713110422+9603f1b`

tried with `Win7` and `Win8.1` (both amd64 & german locales)

my log id: 37218a599f675fdf83b79d1c

**Comment by strib** [comment]
@mplx -- what exactly are you doing to remove the `public\chris` folder?  In your logs, I don't see any calls for actually removing the folder.  Can you tell me exactly what commands you tried?

**Comment by mplx** [comment]
* Windows Explorer

enter the kbfs drive, folder public, mark chris, press delete, confirm ok, no error, folder disappers; hit F5; folder is here again

* cygwin / rmdir (as suggested)

enter cygwin bash, cd to /cygdrive/(kbfs letter)/public

```
$ rmdir chris
$ ls
chris  mplx
```

* cygwin / rm -Rf

enter cygwin bash, cd to /cygdrive/(kbfs letter)/public

```
$ rm -Rf chris
rm: das Entfernen von 'chris/verified_software/ubuntu-16.04' ist nicht möglich: Directory not empty
rm: das Entfernen von 'chris/security_stuff' ist nicht möglich: Directory not empty
rm: das Entfernen von 'chris/random' ist nicht möglich: Directory not empty
rm: das Entfernen von 'chris/Photos/this_is_a_dir/foo/bar/another_directory' ist nicht möglich: Directory not empty
```

**Comment by strib** [comment]
Thanks!  The `rmdir` thing definitely works on Linux/OS X, but I don't know if cygwin bash does the right thing.  Now I do see one removal call (Windows logging is slightly different, I missed it the first time), but I guess it didn't work.

@mplx: did you try `rmdir` in the normal Windows command prompt?  (Without the recursive option.) That's the way I've seen people do it in the past (I don't have a Windows test box handy at the moment).

@taruti: any other ideas?

**Comment by mplx** [comment]
Output from Windows command prompt:

```
E:\>cd public

E:\public>rmdir chris

E:\public>dir
 Datenträger in Laufwerk E: ist KBFS

 Verzeichnis von E:\public

18.08.2016  22:38    <DIR>          .
18.08.2016  22:38    <DIR>          ..
31.08.1754  00:43    <DIR>          mplx
31.08.1754  00:43    <DIR>          chris
               0 Datei(en),              0 Bytes
               4 Verzeichnis(se), 10.737.411.072 Bytes frei
```

**Comment by strib** [comment]
Weird.  Ok thanks.  @taruti?

**Comment by mplx** [comment]
It seems after removal its gone for a few moments but then appears again

* Windows CMD

```
E:\public>dir
 Datenträger in Laufwerk E: ist KBFS

 Verzeichnis von E:\public

18.08.2016  23:14    <DIR>          .
18.08.2016  23:14    <DIR>          ..
31.08.1754  00:43    <DIR>          chris
31.08.1754  00:43    <DIR>          mplx
               0 Datei(en),              0 Bytes
               4 Verzeichnis(se), 10.737.411.072 Bytes frei

E:\public>rmdir chris

E:\public>dir
 Datenträger in Laufwerk E: ist KBFS

 Verzeichnis von E:\public

18.08.2016  23:14    <DIR>          .
18.08.2016  23:14    <DIR>          ..
31.08.1754  00:43    <DIR>          mplx
               0 Datei(en),              0 Bytes
               3 Verzeichnis(se), 10.737.411.072 Bytes frei

E:\public>dir
 Datenträger in Laufwerk E: ist KBFS

 Verzeichnis von E:\public

18.08.2016  23:14    <DIR>          .
18.08.2016  23:14    <DIR>          ..
31.08.1754  00:43    <DIR>          mplx
31.08.1754  00:43    <DIR>          chris
               0 Datei(en),              0 Bytes
               4 Verzeichnis(se), 10.737.411.072 Bytes frei
```

* Cygwin bash

```
/cygdrive/e/public
$ date && ls && date && rmdir chris && date && ls && sleep 1 && date && ls
Do, 18. Aug 2016 23:13:12
chris  mplx
Do, 18. Aug 2016 23:13:13
Do, 18. Aug 2016 23:13:13
mplx
Do, 18. Aug 2016 23:13:14
chris  mplx
```

* Sidenote

compare quite strange dates Windows cmd to Cygwin - local date is 2016-08-18 ~23:19

```
E:\public>dir
 Datenträger in Laufwerk E: ist KBFS

 Verzeichnis von E:\public

18.08.2016  23:19    <DIR>          .
18.08.2016  23:19    <DIR>          ..
31.08.1754  00:43    <DIR>          chris
31.08.1754  00:43    <DIR>          mplx
```

```
$ ls -la
insgesamt 3
drwxr-xr-x 1 mpircher Kein 0 30. Aug 1754  .
drwxr-xr-x 1 mpircher Kein 0 30. Aug 1754  ..
drwxr-xr-x 1 mpircher Kein 0  3. Aug 15:22 chris
drwxr-xr-x 1 mpircher Kein 0 18. Aug 16:38 mplx
```

**Comment by strib** [comment]
@mplx -- it's possible Windows Explorer recent file activity is bringing it back by trying to stat recent files.  Maybe clearing explorer file history will help?

**Comment by jtsmith0101** [comment]
strib, this is the exact same problem I'm experiencing with my private and public folders referenced in issue 3982

**Comment by mplx** [comment]
I've strong doubts this is an caching issue - I upgraded keybase on computer A to current version, had the deletion problems there and then upgraded computer B - the multiple deleted folder showed up there without being accessed before.

@jtsmith0101 
1.) what locale do you use?
2.) do you have other virtual file systems installed? personally i'm using boxcryptor classic which may interfere with keybase' dokan?

**Comment by jtsmith0101** [comment]
Interesting comment on the boxcryptor... I've installed it some months back
but haven't used it.

I also use GPG4win for local key management and local
encryption/decryption.

**Comment by jtsmith0101** [comment]
I also use Veracrypt.... forgot to mention that....

I'll uninstall boxcryptor since I'm not using it.... see if that helps.....

**Comment by jtsmith0101** [comment]
I take it back.... I did not have Boxcryptor installed on this machine.  I
do have GPG4Win (Kleopatra) and Veracrypt...

**Comment by juanminm** [comment]
Both GPG4Win and Veracrypt here, I have seen that problem but I doubt is related to any of the two software unless you are using a Veracrypt container in there. Close any Explorer windows, close or kill Keybase GUI (if running) then close and reopen a CMD window, then try rmdir the public folder. I've just seen a few causes of not deleting permanently but only on Windows 10:

- You are trying to delete the folder using the Explorer window.
- The Explorer window (or at much current explorere.exe process) is open when you tried to use `rmdir K:\public\user` which causes it to reappear inmediatly.
- [Windows 10 specific] RuntimeBroker.exe was querying that folder. Killing the process then deleting the folder and a reboot for precaution made K:\public\chris folder finally disappear for me.

If none of that works, you can try using [Process Monitor](https://technet.microsoft.com/en-us/sysinternals/bb896645?f=255&MSPPError=-2147217396) at Windows Sysinternals page to find out what process is querying that folder after you `rmdir` it.

After executing the program (it is portable), for the sake of the use of memory, it is better if you activate the option at "Filter > Drop Filtered Events", specially if the folder reappears after some minutes (the typical "chris" pop-up).

Click on the Filter icon (![filter_icon](https://cloud.githubusercontent.com/assets/14891772/17838153/ce5b8054-67c5-11e6-8e20-6dff851a8089.png)). Then add the next filter (replacing "/public/chris" with the path of the folder):
![filter_to_add](https://cloud.githubusercontent.com/assets/14891772/17838160/12df23f2-67c6-11e6-8913-178fd26af741.png)

After hitting "Apply" and "OK", it should show only operations by any process to the specific path except those excluded by default. You can then try `rmdir` the folder and see which process or processes are bringing it back. A `rmdir` looks like this:

![rmdir_process](https://cloud.githubusercontent.com/assets/14891772/17838273/b6dc6cfa-67c9-11e6-9ca5-90c92975f31d.png)

To stop capturing, hit the capture button (![capture_icon](https://cloud.githubusercontent.com/assets/14891772/17838190/e730cce6-67c6-11e6-879d-100470b31869.png)), it should have a red X afterwards.
Same for the autoscrolling, hit the autoscroll button (![scroll_icon](https://cloud.githubusercontent.com/assets/14891772/17838192/037d4be0-67c7-11e6-87a0-8b0daec7099a.png))

**Comment by jtsmith0101** [comment]
Success!  I was able to remove the public folder instance of "chris".

I closed all instances of the windows explorer and used command line rmdir.

**Comment by taruti** [comment]
@jsmith0101 Can this be closed?

Unfortunately there are lots of suspects that may access a directory but process monitor helps like  @juanminm said.

**Comment by jtsmith0101** [comment]
I think this can be resolved.
