### ISSUE TITLE
Crashing on macOS Sierra

### ISSUE THREAD

**Issue by briantopping** [keybase/client#4003]
Hi there, interesting looking client for macOS, but doesn't seem to behave well. Hanging at full utilization, etc.

What can I do to help?

**Hardware Overview:**
  Model Name:	MacBook Pro
  Model Identifier:	MacBookPro10,1
  Processor Name:	Intel Core i7
  Processor Speed:	2.8 GHz
  Number of Processors:	1
  Total Number of Cores:	4
  L2 Cache (per Core):	256 KB
  L3 Cache:	8 MB
  Memory:	8 GB
  Boot ROM Version:	MBP101.00EE.B0A
  SMC Version (system):	2.3f36

**System Software Overview:**
  System Version:	macOS 10.12 (16A304a)
  Kernel Version:	Darwin 16.0.0
  Boot Volume:	Macintosh HD
  Boot Mode:	Normal
  Computer Name:	BTopping-MBPro
  User Name:	Brian Topping (btopping)
  Secure Virtual Memory:	Enabled
  System Integrity Protection:	Enabled
  Time since boot:	15:16

**Comment by cjb** [comment]
@briantopping We don't have Sierra support yet, working on it.

CC @gabriel

**Comment by briantopping** [comment]
No worries, I figured that may be true. 

The last developer preview didn't have an update to Xcode command line tools, which indicates to me there were no breaking changes at the library level. Clock is ticking, they'll probably be releasing soon! :)

**Comment by gabriel** [comment]
Can you try this release:
https://prerelease.keybase.io/darwin/Keybase-1.0.17-20160823110029%2Bdfc9854.dmg

**Comment by gabriel** [comment]
We've found an issue where the kext isn't loading on some Sierra installs, so the the version posted above still may not work. I'll post an update when we have a fix for that.

**Comment by gabriel** [comment]
We found an issue when upgrading to Sierra, this build should work:
https://keybase.pub/gabrielh/Keybase-1.0.17-20160826020144%2B61c0667.dmg

**Comment by briantopping** [comment]
Okay thanks Gabriel, I will give it a look this weekend. :)

**Comment by idyll** [comment]
That new build works for me.

**Comment by snej** [comment]
I ran the build for a while and was starting to have some nasty system stability problems where various processes, especially Finder, would lock up for minutes at a time. From sampling them, it looked like they were blocked in filesystem calls looking for volume information, so I started to suspect the fake (FUSE?) filesystem that Keybase mounts. I quit Keybase and haven't had a problem since.

**Comment by gabriel** [comment]
Is this using the new build from the link above? (Also might require a restart, since the current public version is ultra hangy on Sierra.)

**Comment by briantopping** [comment]
Hi all, so I gave that one a shot and it's better in that it's not hanging my machine. After install, it did not insist that I reboot, and it actually worked (i.e. `/keybase/briantopping` existed) somewhat until I did. Once I rebooted, it did not lock up, but it did go into 15% CPU mode (presumably one core on a 8 hyper core machine) for some time. After the CPU settled down, it's behaving as I might expect, but it is using more CPU (kernel_task hovering around 9%). 

How do I gracefully uninstall?

**Comment by gabriel** [comment]
@briantopping Sorry you are having issues. Before uninstalling can you do another `keybase log send` so we can look at the perf issues?

To uninstall:
- Run `keybase uninstall` to remove services.
- Then you can remove the placeholder `/keybase` directory: `sudo rmdir /keybase`
- Then you can unload the kext: `kextunload -b com.github.kbfuse.filesystems.kbfuse`
- Remove the kext: `sudo rm -rf /Library/Filesystems/kbfuse.fs`
- Then remove the helper `sudo rm /Library/PrivilegedHelperTools/keybase.Helper`.

We're still in progress on complete uninstaller (having `keybase uninstall` remove everything), but that is coming soon.

**Comment by briantopping** [comment]
Thanks @gabriel! 

Results from log: `Success! Your log ID is: 36e6d19420a6f29c2b592b1c`

I'll keep watching the thread to try new results. :)

**Comment by briantopping** [comment]
Ok, just an update after uninstalling and rebooting to avoid ratholes on your side: Once I uninstalled and rebooted, the kernel was still at 9%, so I think this must have to do with the debug state of macOS and not Keybase.

**Comment by gabriel** [comment]
Yeah it's hard to tell what in the kernel is causing cpu usage. Also sometimes the samples in Activity Monitor can be misleading cause they are snapshots. Energy usage for a process might be a greater indicator for measure if a process is using lots of resources over time.

**Comment by briantopping** [comment]
no worries, I just wanted to make sure I didn't lead you guys astray...

**Comment by billinghamj** [comment]
FYI - I'm currently running `1.0.17-20160908190031+139f86e` and have not yet had any CPU usage problems, and the folders are working (although the contents of folders loads very slowly).

**Comment by eswat2** [comment]
thank you for the info on how to uninstall keybase, hoping that resolves my short term issues with sierra!!

i've had nothing but trouble after updating to sierra (i know self inflicted).  Opening finder & doing anything that deals with processes (ie. Activity Monitor) will hang forever.  Started looking for kernel extensions and realized that keybase had one, so i checked here.  Looking forward to trying this again when it supports Sierra.

**Comment by cjb** [comment]
@eswat2 Sorry about this!  It looks like it's an incompatibility between Keybase (really, any FUSE filesystem) and Time Machine on Sierra.  We'll disable KBFS on Sierra until it's fixed.
