### ISSUE TITLE
Bash Completion Files

### ISSUE THREAD

**Issue by briantopping** [keybase/client#4004]
Hi, something that would be useful and could be reused on all platforms is Bash completion files.  See http://davidalger.com/development/bash-completion-on-os-x-with-brew/ for macOS, for instance.

**Comment by espoelstra** [comment]
There have been a few different issues and pull requests around this, see the discussion and on https://github.com/keybase/keybase-issues/issues/147 and the merged PR at https://github.com/keybase/client/pull/10058

**Comment by briantopping** [comment]
Ok thanks @espoelstra!
