### ISSUE TITLE
Verifying the keybase binary

### ISSUE THREAD

**Issue by FreekKalter** [keybase/client#4025]
How do I verify the keybase binary after i have downloaded it? I have the signing key from:
https://keybase.io/docs/server_security/our_code_signing_key
But I need a .sig file, or a checksum of some sort to verify it right? I could not find this anywhere in the download section.

**Comment by cjb** [comment]
@FreekKalter Which file did you download? (Linux, macOS, etc)

**Comment by FreekKalter** [comment]
https://prerelease.keybase.io/keybase_amd64.deb

**Comment by cjb** [comment]
Ah.  I think RPM packages contain the signature inside themselves, but for DEB files it's actually the apt repository that's signed with this key.  (prerelease.keybase.io is an apt repo, installed by the .deb)

So your answer might involve running `apt-sig` etc.

CC @oconnor663

**Comment by FreekKalter** [comment]
Ok, Iooked into this. Apparently you can add a public key with `apt-key add code_signing_key.asc`, which returns 'OK'.
Then you should be able to verify it with `debsig-verify keybase_amd64.deb.asc`. 
But I get this output: `debsig: Origin Signature check failed. This deb might not be signed. `

**Comment by cjb** [comment]
Ah, it's our apt repo metadata that's signed (and automatically checked by apt), not the .deb.  I didn't realize you can sign .debs now.  We'll look into signing those too.

**Comment by FreekKalter** [comment]
Ok thanks, also for the quick response btw.

**Comment by oconnor663** [comment]
@FreekKalter there must be a more convenient way to do this, but I think you could do what APT does by hand with something like this:

1. Confirm that our `InRelease` file has a vaild signature.
2. Confirm that our `Packages` file matches the hash from 1.
3. Confirm that our `.deb` file matches the hash from 2.

```
$ curl --silent prerelease.keybase.io/deb/dists/stable/InRelease | gpg -d        
Codename: stable
Date: Thu, 25 Aug 2016 16:08:17 UTC
Architectures: i386 amd64
Components: main
MD5Sum:
 b1941a032e359d9276cf0c55fb52d021 503 main/binary-i386/Packages
 ca9801303109e254fea10226605c607d 363 main/binary-i386/Packages.gz
 5e77d15a7c8b516e15488780beb4ad24 35 main/binary-i386/Release
 3ebd9b791086cd9ebddeaba9c1c5afce 505 main/binary-amd64/Packages
 3e4936ed93d5635d44e110f95c3f3687 363 main/binary-amd64/Packages.gz
 063287201b2354699acfe229a752201d 36 main/binary-amd64/Release
SHA1:
 e7f06cc9461005387c82b70714a578ba328f0646 503 main/binary-i386/Packages
 a351619035023acc886fb64d358216d849242cd6 363 main/binary-i386/Packages.gz
 ea0e5aa4a1859481eb8929e40af14736bd50387b 35 main/binary-i386/Release
 9148198ccb982af30b85b16fdd419b7854d38505 505 main/binary-amd64/Packages
 ea3c626bf5293dd046f485653b43ea6f92876e38 363 main/binary-amd64/Packages.gz
 f9082edea14092794f38390390e06abf8a922f7d 36 main/binary-amd64/Release
SHA256:
 f362eca14f658dabe83ade076668b4d0f9964e627fb946419bd81083b7504749 503 main/binary-i386/Packages
 843c4a293e59bbd38dd846f6b894e1fe295cbf5b9b32cb703bf72d05c6affa64 363 main/binary-i386/Packages.gz
 2ca4451c438b7f4614813919cded632edc7d0318dd7b120d5aa77ec03f055dd6 35 main/binary-i386/Release
 7a77e772e40d3da3693cfa0ca41568da6da9101e0857c169e1a889dab1cf9197 505 main/binary-amd64/Packages
 acc3ed950c8d14ee22700695b5864172db457b3edf4591c91c77b1118a32ed71 363 main/binary-amd64/Packages.gz
 f4aafa353a338baedf9e98523c13d7ffeda979ec3cf745f9fad977dd770595c8 36 main/binary-amd64/Release
gpg: Signature made Thu 25 Aug 2016 12:08:17 PM EDT using RSA key ID 656D16C7
gpg: Good signature from "Keybase.io Code Signing (v1) <code@keybase.io>" [unknown]
gpg: WARNING: This key is not certified with a trusted signature!
gpg:          There is no indication that the signature belongs to the owner.
Primary key fingerprint: 222B 85B0 F90B E2D2 4CFE  B93F 4748 4E50 656D 16C7

$ curl --silent prerelease.keybase.io/deb/dists/stable/main/binary-amd64/Packages | sha256sum -
7a77e772e40d3da3693cfa0ca41568da6da9101e0857c169e1a889dab1cf9197  -

$ curl --silent prerelease.keybase.io/deb/dists/stable/main/binary-amd64/Packages              
Package: keybase
Version: 1.0.17-20160825160033.cefe001
Architecture: amd64
Installed-Size: 186636
Maintainer: Keybase Bugs <bugs@keybase.io>
Priority: optional
Section: misc
Filename: pool/main/k/keybase/keybase_1.0.17-20160825160033.cefe001_amd64.deb
Size: 43948656
SHA256: 68ef1a3feaad73a4547dc1cd40eef211ca5bcb9dde62ba21c97029c4a9dfb7fe
SHA1: 525c0543464ab70ed07e859ced70e06fe7a0949e
MD5sum: 3173c76862de7765524077cb066f7b58
Description: Keybase's command line client
Depends: libappindicator1, fuse

$ curl --silent prerelease.keybase.io/deb/pool/main/k/keybase/keybase_1.0.17-20160825160033.cefe001_amd64.deb | sha256sum -
68ef1a3feaad73a4547dc1cd40eef211ca5bcb9dde62ba21c97029c4a9dfb7fe  -
```

**Comment by sampablokuper** [comment]
@cjb , "*Ah, it's our apt repo metadata that's signed (and automatically checked by apt), not the .deb. I didn't realize you can sign .debs now. We'll look into signing those too.*"

Just to be clear: GnuPG will let you sign any kind of file. There was never a need to wait for some kind of .deb-specific signing mechanism. As such, if you or one of your colleagues whose keys are reasonably trustworthy would be willing to swiftly make a detached signature on https://prerelease.keybase.io/keybase_amd64.deb and another on https://prerelease.keybase.io/keybase_i386.deb , and provide links to those signatures from https://keybase.io/docs/the_app/install_linux , it would substantially improve the ease with which users can install Keybase on Debian-derived distros.

**Comment by chudke** [comment]
So what is the current method of verifying https://prerelease.keybase.io/keybase_amd64.deb?
