### ISSUE TITLE
Keybase Passphrase Selectively Works

### ISSUE THREAD

**Issue by rjwrightohio** [keybase/client#4061]
Keybase GUI Version: 1.0.16-20160803190018+268b023

I can successfully enter my passphrase to unlock KDFS; however that same passphrase does not permit me to sign a test message on the CLI (mac) nor via website. Utilizing my password manager so i believe i have the correct passphrase.

-Robert

**Comment by juanminm** [comment]
It depends on what kind of passphrase you are using. If for the KBFs it uses your Keybase password/passphrase, that's different from the passphrase of your key.

**Comment by rjwrightohio** [comment]
So i revoked the public key via the CLI and the drop syntax. Then generating the key again via "keybase pgp gen"; now permits  my signing via web interface and my keybase passphrase.

Originally i generated my key; 1password didnt save (or i messed it up), and lost my pass phrase. Changed it. maybe that action is the culprit?

**Comment by rjwrightohio** [comment]
Closing since revoke/gen fixed my problem
