### ISSUE TITLE
Please reset KBFS folders

### ISSUE THREAD

**Issue by sdigit** [keybase/client#4062]
I reset my account and changed PGP keys since last using KBFS, and have nothing in kbfs I need to keep so would like it reset to make it usable once more.

Per instructions found in another issue:
```
BEGIN KEYBASE SALTPACK SIGNED MESSAGE. kXR7VktZdyH7rvq v5wcIkHbsMk3n7W 5MUXAEkYZfIFMOC 7GQH2eCOZQXdGTq jxzxJ4F6SVvKbNU qUk9mt7GGhc88Vu VzLyWwFFYPcLEXn q76aBwtkI9ucY8N z7VmrXoxjEu1sNx msdYiNIznrStobc pZi4mzCZZyDmDzI zZpbgPvuDy9VbDS 3ms3vZM6zc7pMSl cPXRgcbDOzlR5uy fr91A9m7jIldsAN eQKcJIngVjxju5m d1bKuiXW47RD6R8 J6rR8eQxbrEO4RV dAL1MIih3HMx25F NAND8LyX9A3dnkf zO3sonCHNAwL9ZK jD6NPGlMujVWPZe Dv8rgEtLLgDFtOt A6lcqt6NdjChOeV jHfcRmPz8t1PEfC NyH6Lph7ymrQ2EZ RFvKPCMPfoZvmdf UuVs9xXeUYfFUwa 0. END KEYBASE SALTPACK SIGNED MESSAGE.
```

**Comment by strib** [comment]
Hi @sdigit -- we are supposed to be doing this automatically now.  Are your folders still unusable to you? If so, can you please try accessing them under your new account and then do a `keybase log send` so we can check why it's not working?  Thanks!

**Comment by strib** [comment]
Oh, looks like you reset last April.  Is that the last time you used KBFS?  If so, please confirm and we'll manually reset for you.

**Comment by sdigit** [comment]
That sounds about right. Go ahead with the wipe, thanks!

**Comment by strib** [comment]
Very sorry for the delay!  I've just reset your single-user public and private folders.  You have one other private share folder, but the other user on that folder should be able to rekey for you if they haven't already.

Please close this out if everything looks ok.  Thanks!

**Comment by sdigit** [comment]
I was just able to rmdir that shared directory (hadn't occurred to me to try that :grin:) and it looks like I'm all good again now -- closing this out. Thanks again!
