### ISSUE TITLE
'keybase' or 'update' process using tons of CPU indefinitely

### ISSUE THREAD

**Issue by snej** [keybase/client#4068]
In the past few days, Keybase processes named either `update` or `keybase` have occasionally started consuming 75%-100% of a CPU, causing my MacBook Pro to heat up. This never seems to stop once it's started, until I kill the process.

I've tried running `sample` on the process but there's nothing in the backtrace — is it written in a language like Go that doesn't use the platform ABI for function calls?

my log id: 12167f4977c7890d86327a1c

Possibly relevant: I'm running the macOS Sierra beta (was on beta 6, updated to beta 7 yesterday.)

**Comment by cjb** [comment]
Yeah, it's because you're on the Sierra beta, we don't support it yet.  Working on it!  Yes, it's written in Golang.

**Comment by snej** [comment]
(Heh, at least `sample` doesn't segfault on Go processes anymore.)

How do I disable Keybase for the time being? Couldn't find a setting for that in the GUI.

**Comment by cjb** [comment]
Do you have a Keybase icon in the top menubar? If so, try clicking on it, then on the dropdown in the top left of that new window, then Quit Keybase.

**Comment by snej** [comment]
Oh yeah, forgot about the menu item!

Is there a 'master' issue covering this, that I can monitor? Looks like it might be #4003. There's a Sierra-compatible experimental build posted there, that I'll try installing.

**Comment by gabriel** [comment]
Yeah please try the build posted there and lmk there if you have any problems.
