### ISSUE TITLE
keybase client just displays "Loading..." message

### ISSUE THREAD

**Issue by ryanquinlan** [keybase/client#4075]
Keybase GUI Version: 1.0.16-20160803190018+268b023

First install of keybase on OS X 10.11.6, client won't get past loading message.

**Comment by cjb** [comment]
Thanks, we've had some other reports of this.  CC @gabriel

**Comment by ryanquinlan** [comment]
yeah, sorry, searched after i submitted this :(

**Comment by cjb** [comment]
No worries, it's good that we know you're in that state, I think @gabriel is having trouble reproing and will be glad to have some help.

**Comment by gabriel** [comment]
Can you try this more recent version:
https://s3.amazonaws.com/prerelease.keybase.io/darwin/Keybase-1.0.17-20160823110029%2Bdfc9854.dmg

If it still fails, can you run (and post ID):

```sh
/Applications/Keybase.app/Contents/SharedSupport/bin/keybase log send
```

Thanks!

**Comment by nagakputtagunta** [comment]
I have the same issue and I tried the version you posted above. Still the same behavior.

Log ID: 87bd456dcd9a6243d4c57a1c

**Comment by nagakputtagunta** [comment]
I was able to get past the "Loading..." state by installing the services via the command line.

```
~ ❯❯❯ /Applications/Keybase.app/Contents/SharedSupport/bin/keybase login

There are no Keybase services installed, you might try running: keybase install

▶ ERROR dial unix /Users/naga/Library/Caches/Keybase/keybased.sock: connect: no such file or directory
~ ❯❯❯ /Applications/Keybase.app/Contents/SharedSupport/bin/keybase install                                                                                                     ⏎
▶ INFO Stopping keybase.updater
▶ INFO Saving /Users/naga/Library/LaunchAgents/keybase.updater.plist
▶ INFO Starting keybase.updater
▶ INFO Stopping keybase.service
▶ INFO Stopping homebrew.mxcl.keybase
▶ INFO Saving /Users/naga/Library/LaunchAgents/keybase.service.plist
▶ INFO Starting keybase.service
▶ INFO Install Updater: OK
▶ INFO Install Service: OK
▶ INFO Install KBFS: stat /keybase: no such file or directory
~ ❯❯❯ /Applications/Keybase.app/Contents/SharedSupport/bin/keybase login
Your keybase username or email address: ▶ ERROR input canceled
```

**Comment by gabriel** [comment]
Thanks for the log.

If you restart your computer, does it get fixed?

(You can run `keybase uninstall` to reverse the `keybase install` before restarting.)

**Comment by gabriel** [comment]
@nagakputtagunta This is an issue we're seeing in a small subset of users that are unable to reproduce... If you could run this in the Terminal and post the output, would be **really really** helpful:

```sh
/Applications/Keybase.app/Contents/Resources/KeybaseInstaller.app/Contents/MacOS/Keybase --app-path=/Applications/Keybase.app --run-mode=prod
```

If it seems like it gets hung when you run that can you do the following in a separate Terminal window to see if it unsticks (and dumps some output):

```sh
kill -ABRT `ps aux | grep "/Applications/Keybase.app/Contents/SharedSupport/bin/keybase" | grep -v grep | awk '{ print $2 }'`
```

**Comment by gabriel** [comment]
We have a new build which might resolve installer flakiness, in this build if you want to try it out:
https://keybase.pub/gabrielh/Keybase-1.0.17-20160830185045%2B1a947f1.dmg

**Comment by ryanquinlan** [comment]
Keybase-1.0.17-20160830185045%2B1a947f1.dmg

This build installed without issue. Thanks for the quick turnaround.
