### ISSUE TITLE
Keybase command line program sent 12 invites for to one user, for one file copied

### ISSUE THREAD

**Issue by Bujiraso** [keybase/client#4082]
Hi there,

For this bug to occur, first I moved into a private, shared twitter folder (e.g. `cd /keybase/private/me,user@twitter`) and then also opened the folder in Nautilus file manager. Following this I copied a 14 megabyte mp3 to the folder with Nautilus. 
A single pop-up from the keybase client asked me to send a link to my friend (also, it has been unclear to me if these links need to be shared privately -- can anyone claim them?). I sent the link, and he signed up.
Upon receiving an email that he accepted, I was told I had 11 invites left, when I previously had 23, implying 11 were used without my knowledge (+ the 1 within my knowledge). I didn't much worry about it but upon accessing my invites page today I noticed that some 12 invites were opened to this one user@twitter friend.

I've deleted them and my log id is: `1571f31f958cf422422b441c`

Let me know if any other information would be useful.
Thanks!

**Comment by strib** [comment]
Oops, sorry about that, thanks for the report.  I opened keybase/kbfs#287 to fix.

**Comment by strib** [comment]
This will be fixed in the next release.
