### ISSUE TITLE
App stuck at "Loading" screen on OS X

### ISSUE THREAD

**Issue by offby1** [keybase/client#4086]
Similar to #3865  (actually, identical, but that bug is closed and I see no way to reopen it).

The creator of that bug found that rebooting fixed the problem, but I've rebooted and am still hitting it.

If it helps any, I've attached the output of the "Sample" command from Activity Monitor.
[Sample of Keybase.txt](https://github.com/keybase/client/files/441152/Sample.of.Keybase.txt)

**Comment by chrisnojima** [comment]
Can you run 'keybase log send' from the terminal?

**Comment by offby1** [comment]
@chrisnojima: it doesn't seem to be doing anything:
```
(venv3.Darwin) :) 15:24:40 [Eric-Hanchrows-MacBook-Pro pyramid-tinyurl-doodle] (master)$ /Applications/Keybase.app/Contents/SharedSupport/bin/keybase log send
This command will send recent keybase log entries to keybase.io
for debugging purposes only.

These logs don’t include your private keys or encrypted data,
but they will include filenames and other metadata keybase normally
can’t read, for debugging purposes.

Continue sending logs to keybase.io? (type 'YES' to confirm): YES
YES
```

Now it's just sitting there, not using CPU nor hitting the disk nor network.

**Comment by chrisnojima** [comment]
@gabriel want to take a look at this log

**Comment by gabriel** [comment]
Can you try this more recent version:
https://s3.amazonaws.com/prerelease.keybase.io/darwin/Keybase-1.0.17-20160823110029%2Bdfc9854.dmg

If it still doesn't work can you do a log send and post the ID:

```
/Applications/Keybase.app/Contents/SharedSupport/bin/keybase log send
```

And if you could try running the installer manually:

```
/Applications/Keybase.app/Contents/Resources/KeybaseInstaller.app/Contents/MacOS/Keybase --app-path=/Applications/Keybase.app --run-mode=prod
```

and lmk what happens to that. Thanks!

**Comment by gabriel** [comment]
And if all that still fails, would be good to know if restarting the computer overcomes it (which might imply a gatekeeper issue).

**Comment by gabriel** [comment]
Re-reading this, you already tried to reboot... This is an issue we're seeing in a small subset of users that are unable to reproduce... 

If you could run this in the Terminal and post the output, would be **really really** helpful:

```sh
/Applications/Keybase.app/Contents/Resources/KeybaseInstaller.app/Contents/MacOS/Keybase --app-path=/Applications/Keybase.app --run-mode=prod
```

If it seems like it gets hung when you run that can you do the following to see if it unsticks (and dumps some output):

```sh
ps aux | grep "/Applications/Keybase.app/Contents/SharedSupport/bin/keybase" | grep -v grep | awk '{ print $2 }'
```

**Comment by gabriel** [comment]
We have a new build which might resolve installer flakiness, in this build if you want to try it out:
https://keybase.pub/gabrielh/Keybase-1.0.17-20160830185045%2B1a947f1.dmg

**Comment by gabriel** [comment]
Known issue we are working on getting fix into release channel. See https://github.com/keybase/client/issues/4150 for more info. 

If you encounter this bug, this build resolves it temporarily:
https://keybase.pub/gabrielh/Keybase-1.0.17-20160830185045%2B1a947f1.dmg
