### ISSUE TITLE
Timeout during installation of update - OSX 10.11.6

### ISSUE THREAD

**Issue by jnews0n** [keybase/client#4101]
Keybase GUI Version: 1.0.17-20160829110024+c4e8dc8

![30_08_2016__8_46_am](https://cloud.githubusercontent.com/assets/3401578/18070059/ae0ad938-6e8e-11e6-9438-678633e93f72.jpg)

Logs sent separately with log id 04d26c8e110238ee87b5821c

**Comment by gabriel** [comment]
Can you do `keybase log send` again... Need a little more logging that occurred after this dialog.

**Comment by jnews0n** [comment]
Have completed keybase log send - refer issue https://github.com/keybase/client/issues/4118
