### ISSUE TITLE
"Open folders" command from menu bar tries generates strange system notif

### ISSUE THREAD

**Issue by silashundt** [keybase/client#4115]
This is what the notification looks like:

![image](https://cloud.githubusercontent.com/assets/345119/18107825/698d233a-6ebe-11e6-8ddb-f892700045b7.png)

In my testing, Finder.app must have no open windows at time of invocation. Keybase GUI application is installed in /Applications/.

Keybase GUI Version: 1.0.17-20160829110024+c4e8dc8

**Comment by gabriel** [comment]
Dupe of https://github.com/keybase/client/issues/4084
