### ISSUE TITLE
Timeout during installation of update - OSX 10.11.6

### ISSUE THREAD

**Issue by jnews0n** [keybase/client#4118]
![30_08_2016__8_46_am](https://cloud.githubusercontent.com/assets/3401578/18110034/a219d1a4-6f58-11e6-933a-a34d4953f8e3.jpg)

my log id: a2fa7d0aaec06ead0b26001c

**Comment by gabriel** [comment]
Just to clarify, did you do this log send after closing that dialog (either Quit or Ignore)? Thanks!

**Comment by gabriel** [comment]
Would it be possible to do another `log send`? Am super interested in this failure and need a bit more info in the log. Thanks!

**Comment by jnews0n** [comment]
Hi Gabriel,

After. 


Cheers,

Jon
---

**Comment by gabriel** [comment]
We found this issue and have are testing the fix which should be available this week.

**Comment by gabriel** [comment]
This is fixed in latest version released last week (1.0.17-20160913233827+18b5a25).
