### ISSUE TITLE
Three invites sent when inviting one via command line

### ISSUE THREAD

**Issue by mudmanc4** [keybase/client#4139]
Sending an invite /keybase/private/myself,otheruser@twitter appears to work fine, yet when going back to the web interface, there are three invites generated off one request. 
Each invite has it's own 'id' 

Bug or not? One for each 'device'?
my log id: 170ae5652a9fcb262fc04c1c

**Comment by DewaldV** [comment]
Hi,

**Comment by strib** [comment]
Thanks guys, this is a dup of #4082 and will be fixed in the next release.  Sorry for the inconvenience!  You can reclaim unused invites via the web.
