### ISSUE TITLE
On a mac, just get a "loading" screen. Cannot login

### ISSUE THREAD

**Issue by steve500002** [keybase/client#4150]
<img width="795" alt="screen shot 2016-09-01 at 22 29 09" src="https://cloud.githubusercontent.com/assets/845216/18185078/cd4dcd3a-7093-11e6-8570-b218aff5d1de.png">

Cannot access commandline either
<img width="977" alt="screen shot 2016-09-01 at 22 32 48" src="https://cloud.githubusercontent.com/assets/845216/18185124/0ed0f138-7094-11e6-9dc6-1c53e606ae6e.png">

Keybase GUI Version: 1.0.17-20160829110024+c4e8dc8

**Comment by cjb** [comment]
Thanks for the report, CC @gabriel

**Comment by gabriel** [comment]
Can you do:

```
/Applications/Keybase.app/Contents/SharedSupport/bin/keybase
```

Also, after that, can you try this build:
https://keybase.pub/gabrielh/Keybase-1.0.17-20160830185045%2B1a947f1.dmg

**Comment by steve500002** [comment]
Hi Gabriel

Did you want this?

1.0.17-20160829110024+c4e8dc8

Steve

**Comment by gabriel** [comment]
Nope, the log send should show a "log ID" that looks something like `676523e5ba000d2bacba9c1c`

**Comment by steve500002** [comment]
Hi

New dmg worked fine. Logged in now

Steve

**Comment by gabriel** [comment]
Known issue we are working on getting fix into release channel. See https://github.com/keybase/client/issues/4150 for more info. 

Thanks for reporting the issue!

**Comment by steve500002** [comment]
No sorry it did not 

I have just run key base status and got this - but now have new version installed :-)

/Applications/Keybase.app/Contents/SharedSupport/bin/keybase status
Username:      stevebrett
Logged in:     yes

Device:
    name:      steve's laptop
    ID:        4d52c0b97b61bc2d6842ab57083e4a18
    status:    active

Session:       stevebrett [salt only]
    is valid:  yes
    keys:      unlocked

Key status:
    stream:    cached
    secret:    not stored
    dev sig:   cached
    dev enc:   cached
    paper sig: not cached
    paper enc: not cached
    prompt:    show
    tsec:      cached

KBFS:
    status:    running
    version:   1.0.2-20160830185112+885505d
    log:       /Users/stevebrett/Library/Logs/keybase.kbfs.log

Service:
    status:    running
    version:   1.0.17-20160830185045+1a947f1
    log:       /Users/stevebrett/Library/Logs/keybase.service.log

Updater:
    log:       /Users/stevebrett/Library/Logs/keybase.updater.log

Platform Information:
    OS:        darwin
    Runtime:   go1.7
    Arch:      amd64

Client:
    version:   1.0.17-20160830185045+1a947f1

Desktop app:
    status:    running
    version:   1.0.17-20160830185045+1a947f1
    log:       /Users/stevebrett/Library/Logs/Keybase.app.log

Config path:   /Users/stevebrett/Library/Application Support/Keybase/config.json
Default user:  stevebrett
Other users:

command-line client:
    /Applications/Keybase.app/Contents/SharedSupport/bin/keybase status [pid: 70803, version: 1.0.17-20160830185045+1a947f1]

desktop:
    /Applications/Keybase.app/Contents/MacOS/Keybase -psn_0_23209505 [pid: 70706, version: 1.0.17-20160830185045+1a947f1, description: Main Thread]
    /Applications/Keybase.app/Contents/Frameworks/Keybase Helper.app/Contents/MacOS/Keybase Helper --type=renderer --no-sandbox --primordial-pipe-token=8FC22E6135686E8F2338F43942353CB6 --lang=en-US --node-integration=true --hidden-page --enable-pinch --num-raster-threads=2 --enable-zero-copy --disable-partial-raster --enable-gpu-memory-buffer-compositor-resources --content-image-texture-target=3553,3553,3553,3553,3553,34037,3553,3553,3553,3553,3553,34037,3553,34037,34037 --video-image-texture-target=3553,3553,3553,3553,3553,34037,3553,3553,3553,3553,3553,34037,3553,34037,34037 --mojo-channel-token=169E4CB5024E8F6DD1FBD12DAB3C1615 --mojo-application-channel-token=8E7E091B7280DCF7D6E0B9ED2222DC80 --channel=70706.1.492759441 [pid: 70710, version: 1.0.17-20160830185045+1a947f1, description: Menubar]
    /Applications/Keybase.app/Contents/Frameworks/Keybase Helper.app/Contents/MacOS/Keybase Helper --type=renderer --no-sandbox --primordial-pipe-token=0623BCDE5EE95927BB1EDB05F3F3B52E --lang=en-US --node-integration=true --hidden-page --enable-pinch --num-raster-threads=2 --enable-zero-copy --disable-partial-raster --enable-gpu-memory-buffer-compositor-resources --content-image-texture-target=3553,3553,3553,3553,3553,34037,3553,3553,3553,3553,3553,34037,3553,34037,34037 --video-image-texture-target=3553,3553,3553,3553,3553,34037,3553,3553,3553,3553,3553,34037,3553,34037,34037 --mojo-channel-token=4BE212C84577D9ABB2C5F58B96671BC0 --mojo-application-channel-token=16BD0BB90855FD331BE87BE1A1D38937 --channel=70706.2.1539537055 [pid: 70711, version: 1.0.17-20160830185045+1a947f1, description: Main Renderer]

KBFS:
    /Applications/Keybase.app/Contents/SharedSupport/bin/kbfs -debug -log-file=/Users/stevebrett/Library/Logs/keybase.kbfs.log -runtime-dir=/Users/stevebrett/Library/Caches/Keybase /keybase [pid: 70737, version: 1.0.2-20160830185112+885505d]

**Comment by steve500002** [comment]
No problems

Steve

**Comment by arionl** [comment]
I know this is a closed issue, but FYI, I ran into this problem if I placed "Keybase.app" is a location other than /Applications. Guess there is some logic baked in that makes that assumption?

**Comment by gabriel** [comment]
@arionl I think more recent builds should work better if not in /Applications..

Can you try his recent version: https://prerelease.keybase.io/darwin/Keybase-1.0.18-20161209203922%2B7173f3e.dmg

And the post ID from `keybase log send` if it still not loading?
Are you running from ~/Applications?
