### ISSUE TITLE
Keybase not included in path if installed in ~/Applications

### ISSUE THREAD

**Issue by scottw** [keybase/client#4151]
Keybase GUI Version: 1.0.17-20160829110024+c4e8dc8

After dragging the OS X app to my Applications folder (I used `~/Applications`, not `/Applications`) and running that application, the terminal could still not find the keybase command-line app. I manually added `$HOME/Applications/Keybase.app/Contents/SharedSupport/bin` to my `PATH` environment variable—seems ok now.

**Comment by gabriel** [comment]
Yeah we don't currently include `keybase` in the path if installed in ~/Applications.

**Comment by gabriel** [comment]
We have a fix for this in master, and will be in a public build soon.

**Comment by gabriel** [comment]
This was fixed awhile back, forgot to close.
