### ISSUE TITLE
Ability to move the keybase folder to another location

### ISSUE THREAD

**Issue by Paradoxis** [keybase/client#4162]
Keybase GUI Version: 1.0.17-20160829110024+c4e8dc8

My keybase folder currently shows up on my desktop, is it possible to have it mounted to my home directory (or other directory of choice?) I'm currently using OS X

**Comment by adilsoncarvalho** [comment]
Same issue

**Comment by strib** [comment]
Dup of keybase/keybase-issues#2306 and keybase/client#3349
