### ISSUE TITLE
Ubuntu Linux GUI shows big white box

### ISSUE THREAD

**Issue by czlee** [keybase/client#4184]
I'm finding a rather unhelpful GUI (or what I assume is meant to be a GUI) shortly after installing on Ubuntu 16.04 LTS:

![keybase-screenshot-1](https://cloud.githubusercontent.com/assets/1725499/18261405/71310e42-73ac-11e6-8ea2-53f808c974ae.png)

![keybase-screenshot-2](https://cloud.githubusercontent.com/assets/1725499/18261404/712d74f8-73ac-11e6-8047-796dbe64cb44.png)

That white box is always there, and always on top, so it gets in the way of basically everything. It seems that I'm able to click "through" it though (I just can't see what I'm clicking). The black box only appears when I click on the Keybase icon in the top-right.

If I `sudo apt-get remove keybase`, it all goes away (though obviously then I can't use Keybase anymore :disappointed:)

The keybase command line seems to work fine, at least with logging in and out (and sending logs), though I didn't try very much with it (_e.g._ I haven't actually tried encrypting a message).

This is in a VirtualBox virtual machine on a Windows host, if that changes anything.

my log id: a85bad70e897f57e130c711c

**Comment by cjb** [comment]
Ah, yes, it's caused by VirtualBox. You'll find that Google Chrome doesn't work either with this setup.

**Comment by czlee** [comment]
Interesting, Chrome works fine (in VirtualBox), though it didn't always—for a couple of years it had an issue with different symptoms (though probably related). I don't recall whether it was a new VirtualBox version or new Chrome version that fixed it though.

**Comment by cjb** [comment]
Huh!  Okay.  You might find `/opt/keybase/Keybase --disable-gpu` to help as a workaround.. it's caused by accelerated GPU drivers not working inside vbox.

**Comment by czlee** [comment]
Bingo! Well, sort of—running the command directly gave me this repeated forever, I assume because I hadn't started the service or something?

```
From Keybase: log: Tue Sep 06 2016 10:41:30 GMT-0700 (PDT) (1473183690866): RPC [I] localhost: connecting (attempt 193)
From Keybase: log: Tue Sep 06 2016 10:41:30 GMT-0700 (PDT) (1473183690866): RPC [W] localhost: Error: connect ENOENT /run/user/1000/keybase/keybased.sock
From Keybase: log: Tue Sep 06 2016 10:41:31 GMT-0700 (PDT) (1473183691696): RPC [I] localhost: connecting (attempt 110)
From Keybase: log: Tue Sep 06 2016 10:41:31 GMT-0700 (PDT) (1473183691697): RPC [W] localhost: Error: connect ENOENT /run/user/1000/keybase/keybased.sock
log: Tue Sep 06 2016 10:41:31 GMT-0700 (PDT) (1473183691745): RPC [I] localhost: connecting (attempt 201)
log: Tue Sep 06 2016 10:41:31 GMT-0700 (PDT) (1473183691746): RPC [W] localhost: Error: connect ENOENT /run/user/1000/keybase/keybased.sock
From Keybase: log: Tue Sep 06 2016 10:41:31 GMT-0700 (PDT) (1473183691874): RPC [I] localhost: connecting (attempt 194)
From Keybase: log: Tue Sep 06 2016 10:41:31 GMT-0700 (PDT) (1473183691883): RPC [W] localhost: Error: connect ENOENT /run/user/1000/keybase/keybased.sock
log: Tue Sep 06 2016 10:41:32 GMT-0700 (PDT) (1473183692747): RPC [I] localhost: connecting (attempt 202)
log: Tue Sep 06 2016 10:41:32 GMT-0700 (PDT) (1473183692749): RPC [W] localhost: Error: connect ENOENT /run/user/1000/keybase/keybased.sock
```

But instead I edited `run_keybase` to add `--disable-gpu` to line 49 and now it works perfectly =) thanks!

**Comment by cjb** [comment]
@czlee Cool, I was going to suggest that but next time you update Keybase your changes to `run_keybase` will be overwritten, sorry about that!

**Comment by czlee** [comment]
Yeah, I was thinking this workaround might be a nuisance every time I update Keybase or something. I guess it's not ideal, but I can live with it. :smiley: Unless there's something you want to do about it, like have some persistent option for this purpose or something? I can manage without one, just throwing ideas around.

**Comment by ublock725** [comment]
Hello,
I had the same problem, I fixed it using your post @czlee and this post too (https://www.reddit.com/r/pop_os/comments/uc48rx/keybase_gui_launches_then_vanishes_after) so thanks a lot!

I find a workaround by editing the following service file:
`/usr/lib/systemd/user/keybase.gui.service`
_Line 22_ - I add this argument:
`ExecStart=/opt/keybase/Keybase --disable-gpu`
Hope this will help!
