### ISSUE TITLE
How to get kbfs working on headless server?

### ISSUE THREAD

**Issue by Efreak** [keybase/client#4185]
So there's a debian/ubuntu repo over at http://dist.keybase.io/linux/deb/repo. I've got keybase installed from there. Not sure if that might be relevant to [keybase-issues#377](https://github.com/keybase/keybase-issues/issues/377)?

However, I'm not entirely sure if I'm up to date or not...The latest version in it is 1.0.16, but my windows computer is on 1.0.17. The updater log given in `keybase status` (screenshot below) doesn't exist.

I can't get kbfs working (I don't have a GUI, I'm on a headless server). There is no _[run_keybase](http://blog.daviddworken.com/posts/kbfs-on-linux/)_ command/file installed, however looking at the repo I have downloaded, it seems to run a file called kbfsfuse. Yet `sudo updatedb && locate kbfs` returns no results. I saw another issue somewhere (I've got too many issues open and can't find it now) that recommended running `keybase unlock`; I did this and entered my password, however kbfs is _still_ not running. `keybase status` does not have a reported version number for it. It does tell me where to find the logfile for it, but said logfile does not exist.

Am I doing something wrong here? Or are headless servers not actually supported?

[Here's a log showing what I've tried](http://a.pomf.cat/cjunes.png) (the discarded `locate` results are cloned git repos and such from ~March)

**Comment by strib** [comment]
I think the debian repo with KBFS included is `http://prerelease.keybase.io/deb`.  Does that help?

And yes, with a headless server you will have to run `keybase unlock --stdin` manually to enter your passphase.  Depending on your use case, it will be slightly less secure because we won't be able to notify you about the proofs of the users you're sharing data with.  Though if you track someone, and one of their proofs breaks, the file system will return errors instead of letting you see possibly compromised data -- but you won't have an easy way of knowing what's going on.

**Comment by gabriel** [comment]
@malgorithms I wonder if we could have a `keybase` command that would show the user what would be required to access a folder (via cli only)...

Something like:

```
> ls /keybase/private/gabrielh,userb
ls: Error
> keybase fs check /keybase/private/gabrielh,userb
You need to identify userb in order to view this folder.
> keybase id userb
...
> ls 

```

**Comment by gabriel** [comment]
We could add a bash prompt helper whenever you enter a keybase folder, it could run this check on that path so that any errors would be displayed.

**Comment by malgorithms** [comment]
> I wonder if we could have a keybase command that would show the user what would be required to access a folder (via cli only)...

this can be bundled with something like an `fs stat` command:

```
keybase fs stat <some file or path in kbfs>
```

- tells you issues, such as what you describe
- tells you who last edited/signed and when
- tells you quota info (this is helpful for folders/files; a 1GB file in a share could be 90% mine, for example)

etc.

**Comment by virtualdxs** [comment]
I just figured out that kbfs is a separate package, but I can't find the mount. `keybase status` reports:

    KBFS:
        status:    running
        version:   1.0.2
        log:       /home/duncan/.cache/keybase/keybase.kbfs.log
        mount:     /run/user/1000/keybase/kbfs
But that mount doesn't exist.

**Comment by strib** [comment]
Sounds like you're on arch?  On arch, you have to explicitly create the mount directory yourself.  You might consider setting it to something else via `keybase config set mountdir /home/$USER/keybase` (for example), since the run dir gets blasted away on each reboot.

**Comment by virtualdxs** [comment]
Yep, that's exactly it. I created it and now I get an error because I just upgraded my kernel. Why does kbfs not autocreate that?

**Comment by strib** [comment]
Big discussion here: https://github.com/keybase/kbfs/pull/1669

**Comment by virtualdxs** [comment]
Thanks! This ticket should probably be closed, since there's a way to do this now.

**Comment by eli-schwartz** [comment]
> like you're on arch? On arch, you have to explicitly create the mount directory yourself.

In this case, a headless server means no running GUI tools like run_keybase, anyway. :p
