### ISSUE TITLE
How to uninstall the OSX client?

### ISSUE THREAD

**Issue by balupton** [keybase/client#4226]
Trying to generate a gpg key to use with git, but seems the new GUI keybase client just isn't ready yet. I wish to uninstall it. How can I do so?

**Comment by gabriel** [comment]
To uninstall keybase and KBFS:

```sh
# Uninstall services and unmount
keybase uninstall
# Remove placeholder dir
sudo rmdir /keybase
# Unload kext
sudo kextunload -b com.github.kbfuse.filesystems.kbfuse
# Remove kext
sudo rm -rf /Library/Filesystems/kbfuse.fs
# Remove helper
sudo rm /Library/PrivilegedHelperTools/keybase.Helper
```

We're still in progress on having `keybase uninstall` remove everything), but that is coming very soon.

**Comment by balupton** [comment]
Cool cheers

**Comment by her** [comment]
It also needs to be mentioned that you must remove /Applications/Keybase.app https://github.com/keybase/client/issues/4247 

Thanks guys

**Comment by tbfld** [comment]
Related, and also on OSX (Sierra), I want to keep the CLI tools, but I'd like to get rid of just the GUI bits — how can I do that? There doesn't seem to be any mention of this in the documentation.

**Comment by gabriel** [comment]
`keybase uninstall` will leave the symlink around...

You can use standalone mode, or install service only:

```
keybase --standalone id
```

or

```
keybase install --components=service
keybase id
```

In the future, we want to be able to support custom (minimal) installs, but it's currently easier for us to have everyone running the app the same way.

**Comment by johanbove** [comment]
Thank you @gabriel for the clear and complete instructions and thank you @balupton for raising this question. 🍻

**Comment by mooreniemi** [comment]
I've tried everything on this page, and still get this on every reboot: 

![screen shot 2016-10-25 at 6 57 11 pm](https://cloud.githubusercontent.com/assets/1695630/19707366/20273fb6-9ae5-11e6-8ce2-514481d8b7c9.jpg)

**Comment by maxtaco** [comment]
@mooreniemi you are trying to install, correct?  @gabriel any further ideas? Thanks

**Comment by mooreniemi** [comment]
@maxtaco I am trying to _uninstall_.

**Comment by maxtaco** [comment]
That's what I meant to write, sorry!!! OK, pinging @gabriel for more ideas. Sorry about any inconvenience.

**Comment by gabriel** [comment]
Oops sorry for the late reply.

You can remove Keybase from startup via `System Preferences | Users & Groups | Login Items`.
Or you can delete the app /Applications/Keybase.app (and it will be removed from startup automatically).

We have an issue to have `keybase uninstall` do this (via https://keybase.atlassian.net/browse/DESKTOP-1277).

**Comment by weingart** [comment]
Unfortunately, brew just moved to using keybase within a cask, and installed this extra stuff in a manner that was somewhat unexpected...

I realize this was not really your doing, but it was unfortunate.  I hope that keybase will release a CLI version soon, at which point I'll be happy to install it again.  Until then...

**Comment by gabriel** [comment]
@weingart Thanks for feedback... we are aware we have users who want the minimal keybase command line only version and is something we want to support in the future

cc @malgorithms

**Comment by maraoz** [comment]
Any ideas on how to uninstall on ubuntu? `keybase uninstall` is not working for me :-1:

**Comment by gabriel** [comment]
`keybase uninstall` only works for macOS.. I think you uninstall via the package manager otherwise? @oconnor663

**Comment by maxtaco** [comment]
`apt remove keybase` works. I closed it in #7897

**Comment by davemurphy** [comment]
on macOS 10.13.2 I executed the key base uninstall command and deleted the app.
When I restarted the machine - it hung on boot up. Spent a couple of hours diagnosing the problem and it was an incomplete keybase uninstall. (Had to boot with non system kexts disabled.)

Basically, since SIP was introduced to macOS, trusted privileged kernels are loaded into /Library/StagedExtensions.

On my system I found the following Keybase components (after I ran the key base uninstall):

/Library/StagedExtensions/Library/Filesystems/kbfuse.fs
/Library/StagedExtensions/Library/Filesystems/kbfuse.fs/Contents/Extensions/10.10/kbfuse.kext
/Library/StagedExtensions/Library/Filesystems/kbfuse.fs/Contents/Extensions/10.10/kbfuse.kext/Contents/MacOS/kbfuse

Manually deleting these and restarting the machine fully solved the problem.
I suggest the key base uninstall script check for and remove these components in StagedExtensions.

cheers
rgds Dave

**Comment by maxtaco** [comment]
Sorry about this @davemurphy, we'll investigate....

**Comment by davemurphy** [comment]
no problem @maxtaco hopefully the description is specific enough to help fix the problem.

**Comment by drorata** [comment]
I cannot even run `keybase` from my console. What is the uninstalling procedure on macOS?

**Comment by drorata** [comment]
I uninstalled the app and reinstalled it. Then I had `keybase` available and I ran `keybase uninstall`. Next, I removed the app.

Now, after restarting the box, I still see  `~/Library/Application Support/Keybase` (3.6GB). Is it safe to delete it?

**Comment by maxtaco** [comment]
I would save the config.json and the secrets.you.mpack files, they have
your irreplaceable crypto credentials that you can use in the future to
access your encrypted data.

**Comment by drorata** [comment]
@maxtaco and otherwise safely remove the folder?

**Comment by maxtaco** [comment]
Out of curiosity which folders are taking up the most space?

**Comment by drorata** [comment]
Running `du -h -d 1 . | sort -h` inside `~/Library/Application Support/Keybase` yields:

```
4.0K	./Local Storage
4.0K	./kbfs_journal
 16K	./synced_tlf_config
 40K	./GPUCache
 52K	./kbfs_sync_cache
568K	./keybase.chat.leveldb
9.5M	./Cache
 14M	./keybase.leveldb
3.5G	./kbfs_block_cache
3.6G	.
```

Is it safe to remove (keeping the files mentioned above)?

**Comment by maxtaco** [comment]
Ah, OK.  Feel free to blast away kbfs_block_cache, for sure. Thanks

**Comment by drorata** [comment]
@maxtaco what about the whole directory?

**Comment by maxtaco** [comment]
Personally I'd retain config.json and secretkeys.you.mpack, if  you ever
plan to use keybase again....  but everything else is disposable.

**Comment by TheFullResolution** [comment]
After uninstalling Keybase I am left with the shortcut in the finder. I tried even reset settings of the finder or installing Keybase and uninstalling it again... But the shortcut is still there, when I click on it I get a message "The operation can’t be completed because the original item for “Keybase” can’t be found."
