### ISSUE TITLE
Incorrect permissions on private folder after mounting filesystem

### ISSUE THREAD

**Issue by daniel-noland** [keybase/client#4228]
Possible duplicate / related to  #3262

Created fresh vm to test keybase filesystem.  When I mounted the fs, all went ok, save that my private folder was owned by root.  

Observed output:
```
[dnoland@keybase-test private]$ ls -l
total 0
drwx------ 1 root root 0 Sep  8 14:15 dnoland
[dnoland@keybase-test keybase]$ keybase version
Client:  1.0.17-20160908193355+c2873a5
Service: 1.0.17-20160908193355+c2873a5
[dnoland@keybase-test keybase]$ uname -a
Linux keybase-test 4.7.2-1-ARCH #1 SMP PREEMPT Sat Aug 20 23:02:56 CEST 2016 x86_64 GNU/Linux
```

1) This is a usability issue: you can just 

```
chown -R $(whoami) ~/keybase/private/${KEYBASE_USERNAME}
``` 
or (not as good) 

```
chmod o+rw ~/keybase/private/${KEYBASE_USERNAME}
```

to fix the problem, but if the people using this FS are not familiar with \*nix file permissions, this is going to be an issue.

2) This is a *potential* security problem (some discussion of this in #3262).  My first thought is that some systems (grsecurity / PAX) allow the admin to deny execute permissions on ALL files NOT owned by root.  I can't say how that would interact with FUSE  (I don't use FUSE much, so let me know if I'm just a noob :D).

my log id: 22ee1bd34003891b40f8831c

**Comment by cjb** [comment]
@daniel-noland FUSE actually doesn't follow Unix permissions.  If you try "sudo ls /keybase/private/your_username" you'll see that it fails.  Regardless of the Unix permissions, your user running kbfsfuse is the only one who can view your /keybase dirs.

**Comment by strib** [comment]
The Unix permissions are meaningless in KBFS.  All the local security is enforced by FUSE (it won't let any non-mounting user, including root, access the mount).  We should do a better job at showing permissions so users don't get confused, but there's no actual problem that I know of.

**Comment by daniel-noland** [comment]
@cjb, @strib Thanks for the quick reply :smile:
 
I should have been more clear.  I understand that FUSE is Unix permissions agnostic.  However, the permissions it presents are apparently significant.  I don't know if this is clear from the log, but I was denied read access to my private directory until I ran the `chown` command detailed above; no r or w bit set for that directory.

**Comment by strib** [comment]
@daniel-noland waaah?  That's very odd, chown should have no effect in KBFS at all.

Your log did not include any KBFS logs.  Are you running it in some manual way?  Does anything exist in `"/home/dnoland/.cache/keybase/keybase.kbfs.log`?

**Comment by daniel-noland** [comment]
@strib 
My procedure:

1. Installed the Arch Linux AUR package available [here](https://aur.archlinux.org/packages/keybase-bin/) on a new VM.  Precious little else installed.
2. I then ran: `keybase login` and followed the instructions to add the device.  That seemed to be successful.
3. The `keybase login` does not produce a `~/keybase` directory or run any FUSE mounts that I can see.  However, I noticed that the keybase-bin package brought in `/usr/bin/kbfsfuse`, the use of which seems obvious enough: `kbfsfuse ~/keybase`.  That allows me to access public and private dirs on my laptop without difficulty.  However, I was unable to `ls` the `~/keybase/private/dnoland/` dir due to permission denied.  The `chown` fixed it.

Perhaps I have done something dumb? :smile_cat:

As for `/home/dnoland/.cache/keybase/keybase.kbfs.log`, yes there is 1.8M of Unicode in that file.  I can send you any and all of that file.  Is it security sensitive or should I simply attach?

**Comment by strib** [comment]
Ahh, the community AUR package doesn't include KBFS (see keybase/kbfs#309).  When you install the `keybase-bin` package, you need to run it using the provided `run_keybase` script.  Without doing that, you are missing a bunch of required environment variables and I'm surprised you were even able to connect to the local keybase daemon or any of the KBFS servers.  Perhaps you weren't.

Also note that `run_keybase` mounts it at `/keybase`, not `~/keybase`.

**Comment by daniel-noland** [comment]
There is the trouble!  Will take another swing at it when I get a minute.

Thanks!

**Comment by daniel-noland** [comment]
Round 2.

**Warning:** I did this on my laptop, which is hardly a sanitary testing environment.  I will repeat this on a clean system when I get a chance.

Procedure:

1. Totally purge keybase from my laptop system: `pacaur -Runs keybase-bin`
2. Stash old config files `mv ~/.config/keybase{,.old}` (they were likely trash anyway)
3. Reinstall keybase `pacaur -S keybase-bin`
4. `run_keybase` and follow shiny GUI dialog to init new system.

This all *seems* to work.  FUSE mounts KBFS at /keybase.  However I still get permissions issues. 

![install](https://cloud.githubusercontent.com/assets/343784/18373053/18ed4198-75fe-11e6-850b-a66a35c6ef6e.png)

Interestingly, they can no longer be resolved by changing the \*nix permissions (which makes sense I guess).  The problem may well be that I have failed to completely purge the old mistake.  

![perms](https://cloud.githubusercontent.com/assets/343784/18373004/ccddba12-75fd-11e6-9188-ef8fbfa170a6.png)

As for the trouble with the log submissions:
```
▶ WARNING error opening log "/home/dnoland/.cache/keybase/keybase.updater.log": open /home/dnoland/.cache/keybase/keybase.updater.log: no such file or directory
```
![log_error](https://cloud.githubusercontent.com/assets/343784/18373063/3185e3f4-75fe-11e6-9264-43546704a3b9.png)

If this message was shown before then I did not notice it.

If you have a suggestion on how to do this in a more sanitary way I am all ears.  Failing that I think my best plan at this point is to just declare bankruptcy and revert my system to a previous btrfs snapshot and try again tomorrow.

I submitted a final log in the hope that it is useful / complete (seems like a longshot, but likely I like completeness)
Log id: 5bee30af2dff005654205f1c

Thanks again! :smile:

**Comment by strib** [comment]
@daniel-noland thanks for the details and your patience!

Now KBFS thinks you logged out of Keybase:

```
2016-09-08T19:11:13.310688 ▶ [DEBU kbfs keybase_service_base.go:215] 06f Current session logged out
2016-09-08T19:11:13.310907 ▶ [DEBU kbfs keybase_service_base.go:219] 070 MDServerRemote: Refreshing auth token...
2016-09-08T19:11:13.310961 ▶ [DEBU kbfs mdserver_remote.go:214] 071 MDServerRemote: resetAuth called
2016-09-08T19:11:13.312651 ▶ [DEBU kbfs mdserver_remote.go:214] 072 MDServerRemote: User logged out, skipping resetAuth
2016-09-08T19:11:13.312693 ▶ [DEBU kbfs keybase_service_base.go:219] 073 MDServerRemote: no session available, connection remains anonymous
```

According to the Keybase daemon logs, something did call logout locally:

```
73462 2016-09-08T19:11:13.310125 ▶ [DEBU keybase api.go:644] afd - API call logout success
73463 2016-09-08T19:11:13.310184 ▶ [DEBU keybase session.go:299] afe + invalidating session
```

Can you think of any reason that might have happened?  An explicit `keybase login` might fix it for you.  We have actually been looking at a similar bug internally today, so there might be a race condition you hit...

**Comment by strib** [comment]
Actually scratch that.  It looks like you provisioned a new device, and the KBFS server didn't know about it yet.  (This is a known, rare race.)  So the KBFS server rejected your requests even though you were properly logged in.

I think that kind of problem might correct itself over time, but if it doesn't, try running `run_keybase` again and see if that fixes it.  Sorry!

**Comment by strib** [comment]
Yay!  We have an internal ticket for that authorization race on a new device provision.  Thanks for bearing with us.
