### ISSUE TITLE
"keybase pgp import -i seckey.asc" results in error

### ISSUE THREAD

**Issue by tquid** [keybase/client#4235]
I'm trying to get set up with some existing gnupg keys. Unfortunately I get an error:

```
$ keybase pgp import -i seckey.asc 
▶ ERROR openpgp: unsupported feature: hash not available: 9
```

**Comment by tquid** [comment]
```
$ keybase version
Client:  1.0.17-20160829110024+c4e8dc8
Service: 1.0.17-20160829110024+c4e8dc8
```

**Comment by maxtaco** [comment]
Thanks for the feedback. This is a GPG feature that Go's PGP libraries don't yet support. It's in our backlog of things to fix. Cheers.

**Comment by tquid** [comment]
Is this a feature I can work around, perhaps by exporting the keys with some flag?

**Comment by maxtaco** [comment]
Hi  @tquid sorry for the slow reply.  Can you try it again, and then issue `keybase log send`?  I can't tell from the error message which operation was failing, since it either might be in signature verification, or s2k stretching. Thanks.

**Comment by tquid** [comment]
No problem. Here is the URL output by `keybase log send`:

https://github.com/keybase/client/issues/new?body=[write%20something%20useful%20and%20descriptive%20here]%0A%0Amy%20log%20id:%2086db1470277ce6e3e354a61c

**Comment by maxtaco** [comment]
Urg, weirdly enough, that log didn't mention the error. I'll have to scratch my head a bit more.
