### ISSUE TITLE
Trust graph is wrong or I am confused

### ISSUE THREAD

**Issue by daniel-noland** [keybase/client#4236]
(apologies in advance for any pedantry)

After playing around with adding and revoking devices for a while I reached this trust state:
![graph](https://cloud.githubusercontent.com/assets/343784/18374469/6dfaace6-760a-11e6-8ed5-813e1a576a2a.png)
which *seems* invalid to me.

Now it is likely that I just don't understand the mechanics of keybase very well, so please correct me where I am wrong.

1. The thesis of keybase is to authenticate everything back to PGP bedrock.
2. All files which appear in KBFS (public and private) are signed.
3. "paper keys" provide a means of data recovery, and an additional trust mechanism capable of provisioning new devices.

If that is correct, then taken together I believe that the trust digraphs available at `https://keybase.io/${KEYBASE_USERNAME}/graph` should always be 
1. strongly connected 
2. symmetric

Further, any node which has been revoked is, by definition, *no longer* a valid link in the trust digraph.

The 'image cup' paper key node was generated when I created my account.  Presumably the signature of the associated string is stored on the keybase servers somewhere.  Perhaps the 'image cup' associated string was also used in a pbkdf to generate a symmetric key(s) (and the asymmetrically encrypted form of these symmetric keys are also stored on the keybase servers to allow me to recover data using my GPG key?). 

To the degree that my assumptions are correct, this all seems well and good to me.

However, my laptop 'marvin' has subsequently been revoked.  If you remove the marvin node from that digraph it looses the 'strongly connected' property, effectively decoupling the 'image cup' node from my PGP 'root'.

My first thought is that the trust digraph is simply incorrect.  The paper key should be directly connected to my GPG key node no?

If not, then I am a bit lost.

For example, I understand that every file which appears in KBFS is signed.  But now I don't understand which key is doing the signing.  My GPG key is kept on a yubikey smart card.  Normally this is invisible to any applications which rely on GPG, but it does give me the ability to completely vanish my main key from any computer at a whim.
![smart_card_redacted](https://cloud.githubusercontent.com/assets/343784/18375219/622cf3c2-7611-11e6-913d-0950abe32a77.png)

If I unplug my yubikey I can still write to my public and private folders.  Since it can't be using my main key for signing this seems to imply that the keybase client generated some ancillary key (presumably signed by my GPG key or some descendant at some point).  That seems fine, but shouldn't it still link back to the GPG key via a current trust chain?  Wouldn't fragmenting my identity across multiple trust chains defeat the purpose of keybase?

(again, sorry for the pedantic ticket)

**Comment by strib** [comment]
Hi @daniel-noland.  The graph is just showing the chain of trust that led to those keys being established in the first place.  It's ok if individual nodes are revoked -- they just had to be legitimate nodes _at the time they were used to sign the new keys below them into your account_.   The direct links in the graph don't imply anything about the current trust in the keys left in your account, it is just tracing how they originally got there.

Specifically the graph is showing that you used your GPG key to provision your device `marvin`.  When `marvin` is provisioned, it generates a brand new public/private key pair (not PGP, but ECC) and signs it into your public sigchain using your GPG.  Next, you provisioned your `image cup` paper key, _using `marvin`'s private key to sign it into your sigchain_.  Later, when you delete `marvin`, `image cup` is still a valid key because `marvin` was valid at the time you made the paper key.

KBFS does not use PGP/GPG at all.  It only signs things using your local device key, and data is encrypted only for your local device keys and your paper keys.  PGP is only used when provisioning devices (and when you run `keybase pgp ...` commands).

Does that help clarify?

**Comment by daniel-noland** [comment]
Hello @strib.  I think that makes sense.  Again, please point to where I'm wrong.

The function of that graph is to illustrate the *history* of the trust chain, **not** the 'web of trust' concept ('web of trust' in the altered sense that keybase uses).  

The current 'web of trust' is important, but is not shown because its structure is trivial and ubiquitous: a star graph [;K_{1,n};] wherein the central node is a master ECC key and the leaf nodes (including the user's PGP key and all paper keys) are just entities which have been verified by the central ECC key one way or another.

The central difference between the public and private directories in KBFS is that the private files are signed by the local device key and encrypted against *all* of the ECC keys associated with the user's master key, while public files are only signed by the local device key.

The keybase servers then decide to accept modifications to the KBFS files iff 

1. the user has permissions to modify that file 
2. the {file, modifications} are signed by a device key trusted by the user's master key.

A similar story for read access.

If correct, this seems like a much more reasonable architecture than I had running around in my skull before.  In retrospect, I should have realized that I was wrong before since I was not strictly required to upload a PGP key.

**Comment by strib** [comment]
Yes, mostly right.  Except there is no "master ECC key", they are all equal.  Any valid key can be used to revoke any other key.  So the "web of trust" isn't really a star, it's just an unordered collection of ECC keys made up of all the ones in your sigchain that haven't yet been revoked.

Another minor quibble: files themselves aren't encrypted; each Keybase folder (e.g., `private/USER1,USER2` is a Keybase "folder") has a secret key, and that secret key is what's encrypted for each ECC key.  And then that secret key is what's used to encrypt the data, so file encryption only has to be done once per folder.  More details in https://keybase.io/docs/crypto/kbfs.

**Comment by daniel-noland** [comment]
Ok so the "web of trust" can have a more complex topology.  I will read that link.  Thanks for all your help!  I would call this one closed :smile:

**Comment by strib** [comment]
There's no topology at all, it's not even really a web.  Each user has a "sigchain", where each link can declare a new trusted key or revocation, and it must be signed by some previous declared key that hasn't yet been revoked.  When you're deciding what keys to trust for a user, you just walk that chain (checking tha the signatures match some unrevoked key at that point in the sigchain) and collect keys, and then remove keys from that collection when you find it has been revoked.

**Comment by daniel-noland** [comment]
Ok, I see what you mean.  Pretty sure I do at least.  You just walk the chain, form a set, and then test that the set contains a relevant key.  It isn't a graph as there is no edge set.  You can (and do) render the chain a digraph, but that is somewhat incidental.  At the end of the day a key is either in the trust set or it isn't.

**Comment by strib** [comment]
Yup!
