### ISSUE TITLE
Uninstall Failed

### ISSUE THREAD

**Issue by LeeMcCartney** [keybase/client#4247]
Uninstall failed. 

App still tries to run at startup but then fails. error 11.

my log id: 0b59e22c5ebb2c9f6383941c

**Comment by maxtaco** [comment]
cc: @gabriel

**Comment by gabriel** [comment]
If you trash /Applications/Keybase.app, it won't start on boot. (Or you can remove Keybase from System Preferences, Users, Login Items.

The error you encountered is also know issue and fix should be out soon (are still testing it).

**Comment by gabriel** [comment]
This is fixed in latest version released last week (1.0.17-20160913233827+18b5a25).
