### ISSUE TITLE
Error Timeout(-11)

### ISSUE THREAD

**Issue by Walkersneps** [keybase/client#4250]
This dialog popped up a couple seconds after typing my password to let Keybase update.
![Error popup screenshot](https://cloud.githubusercontent.com/assets/7949250/18417863/f57c7d38-783b-11e6-841c-d50b74eb88f8.png) 

I uploaded the error message on Pastebin ==> http://pastebin.com/ysj7HWsC
Log sent after clicking the `Ignore` button ==> 19a2897a1066aa8dd587df1c

**Comment by cjb** [comment]
Thanks! CC @gabriel.

**Comment by gabriel** [comment]
This is fixed in new builds which we are currently still testing but should be out in the next few days.

It should be a very transient error.. meaning it shouldn't come up that often. And if you quit and restart you should be ok.

Thanks for the report!

**Comment by anthonygreen** [comment]
Same issue

**Comment by Walkersneps** [comment]
It happened again today.

Error paste ==> http://pastebin.com/wD66Q038
Keybase log id ==> 10317ff4034bf27252a11c1c

**Comment by gabriel** [comment]
This is fixed in latest version released last week (1.0.17-20160913233827+18b5a25).
