### ISSUE TITLE
OS X: Force To Provisioned A Device That's Already Been Provisioned On Login

### ISSUE THREAD

**Issue by briandcosta** [keybase/client#4251]
Hey,

I'm currently trying to login and KB is asking me to provision my current device...trouble is my current device is already provisioned...it's even on the list of devices I can pick from.

I've sent in a log: 8be1f1c6b2d097bde8fee61c

--Brian

**Comment by briandcosta** [comment]
Anyone? Max? Chris?

**Comment by maxtaco** [comment]
I will take a look today when I get to my desk

**Comment by maxtaco** [comment]
@briandcosta Sorry for the delay. I think we had an issue with our earlier updater (Cc: @gabriel  and @patrickxb) in which configuration files were being wiped out. But we can recreate it for me.  Which machine are having trouble with now --- `Cloud` or `Zidane`?  Thanks!

**Comment by maxtaco** [comment]
Hi @briandcosta, Can you tell me what's currently in:

```
$HOME/Library/Application Support/Keybase/config.json
```

Here's what it should be:

```json
{
    "current_user": "briancosta",
    "users": {
        "briancosta": {
            "device": "f8e8df6cff2efa1bc520679f36d77b18",
            "id" : "81516a543bdf30f4af42a44543ea0800",
            "name": "briancosta",
            "salt": "57a7e72087d02cdc1d6cd31878dd5ac1"
        }
    }
}
```

So you can replace it and see if that helps.  After you replace, you should:

```
keybase ctl stop
keybase ctl start
```

**Comment by briandcosta** [comment]
Hey Max,

Sorry for the delay!

Currently, I'm working with Zidane, and there's no config.json file there. There used to be...I looked at it before I posted this thread! Right now in that folder there's only another folder, keybase.leveldb.

As for Cloud, it has it's JSON file and it's very similar to what you have posted above, only of course  the device ID is different. The Keybase folder on Cloud contains that config.json file, a secretkeys file, and the keybase.leveldb folder. I can probably use Time Machine or Backblaze to get that JSON file back on Zidane, or would you rather I just re-create it?

--Brian

**Comment by maxtaco** [comment]
We had a bug in our earlier updater (we think, we never repro'ed it) that trashed people's config files.  We haven't seen it recently, so hopefully it's been resolved. I think that config file above should work for you.  Give it a shot, and let me know if it helps!

**Comment by briandcosta** [comment]
Hey,

My Homebrew install was being strange (not letting me update to 1.0) so I ended up just axing it and KB and doing a reinstall of both. Trying this now...hang tight!

**Comment by briandcosta** [comment]
Ok! That seemed to do it! I did get a No secret key available, but since this is a new install, that's expected. I'll just need to reimport those. I'll report back in a bit.

--Bri

**Comment by briandcosta** [comment]
Hmm, when I try to import a key it just hangs.

**Comment by maxtaco** [comment]
It is reading from standard input

**Comment by briandcosta** [comment]
Both Cloud and Zidane do it. CLoud also has dec sig and enc "stored" and Zidane does not.

**Comment by briandcosta** [comment]
Oh, am I supposed to paste my key in the CLI? I thought it grabbed it from my GPG Keyring. I felt like it did that originally.

**Comment by briandcosta** [comment]
Seems Cloud is fine, just followed someone and it authenticated. So Zidane is just not happy.

**Comment by maxtaco** [comment]
On Zidane is there a file called secrets.briancosta.mpack in your config
directory?  You shouldn't need pgp by the way, it is now optional.  Only
needed for pgp operations.

**Comment by briandcosta** [comment]
There is. But my Keys are PGP.

**Comment by briandcosta** [comment]
(I remember it being easier to get KB to see your locally kept keys...)

**Comment by briandcosta** [comment]
Hey Max,
Any more thoughts on this issue?
--Brian

**Comment by maxtaco** [comment]
What's the current issue?

**Comment by briandcosta** [comment]
You asked if there was a "On Zidane is there a file called secrets.briancosta.mpack in your config
directory?" Originally I replied yes, but I mis read the post, and no, there is not.

**Comment by briandcosta** [comment]
I'm not currently at the system, but will be later this evening. Just wanted to ping you before I forgot :)

**Comment by maxtaco** [comment]
Oh ok! I you don't have `keybase.briancosta.mpack` on Zidane, then you have no choice but to reprovision Zidane.

**Comment by briandcosta** [comment]
Damn...can I use the same name? I saw on other threads this is an issue...

**Comment by maxtaco** [comment]
Yeah, I'm very sorry, we don't let people reuse hostnames fear of rollback attacks.

**Comment by briandcosta** [comment]
But my stuff got blown away! :( So do I deprovision it from Cloud then reprovision when I sign on?

**Comment by briandcosta** [comment]
(I'm gonna check to see of my Backblaze or TM have a copy...I did that once already and did not see it though...but I'll double check.)

**Comment by maxtaco** [comment]
no, I think you should just run `keybase login` on `Zidane` and it should step you through the reprovision workflow...

The key file is `secrets.briancosta.mpack` --- that's your secret keyring that no one can recover without breaking EC crypto.

**Comment by briandcosta** [comment]
Because when I login on Zidane, it logs in fine but does not ask to re provision, but when I try to encrypt anything, I just get a missing keys error. I'll have more info when I get home.

**Comment by maxtaco** [comment]
Ok, I think I understand better.

Which command line are you using to decrypt? And which failure do you see?

**Comment by briandcosta** [comment]
I'll need to answer that when I get home and I'll write a sequence of events of what happens as I login. Originally it said I was unable to login because Zidane was not provisioned...but it was and once we rebuilt the config.json, I was able to login, but now it was missing my keys. :)

**Comment by briandcosta** [comment]
Strangely, Backblaze HAS a secrets file for Cloud, but not Zidane. Super weird because they where both setup on the same day...

**Comment by briandcosta** [comment]
Oh nice! My local TM has a copy of my Zidane secret file :) (remoting in)

**Comment by briandcosta** [comment]
Ok, I'm back home on Zidane. I can restore the original Keybase folder that was created on Feb 4th of this year which has the following:

![screen shot 2016-10-03 at 7 56 48 pm](https://cloud.githubusercontent.com/assets/8441355/19061214/a71380e6-89a3-11e6-9099-f8580cbd69ce.png)

**Comment by maxtaco** [comment]
Sure, try this:

```
keybase ctl stop
# move those files back into place
keybase ctl start
```

**Comment by briandcosta** [comment]
Will do and I'll let you know what happens this evening!

**Comment by briandcosta** [comment]
Ok, I think that's got it!

I restored from TM the original config.json file and secretkey's file. I did NOT restore the existing keybase.leveldb directory. If I should, let me know.

I was able to login, encrypt a message to myself and decrypt it.

Log: a631e54d2de87d5a30d2441c

**Comment by briandcosta** [comment]
Was also able to encrypt a PGP message and decrypt it in OSX, but not the Keybase CLI, but that's not normally something I'd do.

**Comment by briandcosta** [comment]
Looks like we got it! Sorry, meant to close!
