### ISSUE TITLE
Periodic lsof causing CPU load spikes?

### ISSUE THREAD

**Issue by ddellacosta** [keybase/client#4253]
Not sure if this is redundant w/https://github.com/keybase/client/issues/3050 or not: I've noticed that my entire system will slow to a crawl periodically, maybe every half hour or so, and it seems to be caused by `lsof` running against a folder in `/`.  Is there anything I can do to adjust this?

Mac OS X 10.11.6, `keybase -v` gives me `keybase version 1.0.16-20160630135211+c643773`, if there's any other pertinent information let me know.

Thanks!

**Comment by cjb** [comment]
Thanks for the report, CC @gabriel.

Please could you run `keybase log send` and tell us the ID?  Are you aware of having files open in KBFS at the moment?

**Comment by ddellacosta** [comment]
Hi @cjb, here's the log id that gave me: 4b0bbcad5228a331c1e0381c

>  Are you aware of having files open in KBFS at the moment?

I am not. Is this something I could check on for you in some way, or is ignorance of what this is enough to tell you what you need to know?

**Comment by cjb** [comment]
Ignorance is enough.  Thanks!  We'll get back to you.

**Comment by ddellacosta** [comment]
Cool, thanks for looking into it!!

**Comment by gabriel** [comment]
Could you try running a more recent version:
https://s3.amazonaws.com/prerelease.keybase.io/darwin/Keybase-1.0.17-20160829110024%2Bc4e8dc8.dmg

I don't see anything obvious in the logs...

We do sometimes run `lsof` on `/keybase` to see if anything is using it... If you run this command:

```
/usr/sbin/lsof -w -F pcuftn /keybase
```

does it trigger slowness?

If you close the app and run `keybase uninstall`, your machine doesn't experience any slowness?

Are you running iStat Menus by any chance?

**Comment by gabriel** [comment]
Also when you experience slowness do you see anything in system.log (can see via Console.app)? If you filter by `keybase` in Activity Monitor does it show high memory (or energy) usage?

These things are a little hard to pinpoint so any extra info you can think of would be great.

**Comment by ddellacosta** [comment]
Hi @gabriel , I haven't tried uninstalling yet but here's some more info for now:

- I'm not running iStat Menus
- When I run the `lsof` command you gave me I don't see anything special in the logs, but I do see CPU going up to 99% and the effect is very noticeable: sound output hiccups, interactivity is slowed down to a crawl (in fact just as I was typing this comment the already scheduled `lsof` kicked off and I had to stop typing for 15 seconds or so).  Screenshot attached.

So it definitely seems like that particular `lsof` command is killing things, not sure why.  I'll try upgrading now.  Thanks for your response!

<img width="1440" alt="screen shot 2016-09-13 at 10 38 01 am" src="https://cloud.githubusercontent.com/assets/32021/18478354/e7b0ba34-799e-11e6-9ce0-71f6c78368d3.png">

**Comment by gabriel** [comment]
k yeah that doesn't look good...

Is this running on the more recent version I linked above (if not can you try):
https://prerelease.keybase.io/darwin/Keybase-1.0.17-20160829110024%2Bc4e8dc8.dmg

**Comment by ddellacosta** [comment]
@gabriel After upgrading yesterday I'm not seeing these spikes any more. Will keep my eye on stuff but think you can close this if you want--will leave it up to you. Thanks to you and @cjb for taking the time to help me resolve this issue!

**Comment by Alhadis** [comment]
Is there an ETA for a stable release of this?

**Comment by gabriel** [comment]
This might have been related to performance issues we had in the past but should now be resolved. If not we can re-open a new ticket.

You can get an up to date builds here: https://keybase.io/download
