### ISSUE TITLE
Revoked device names cannot be reused

### ISSUE THREAD

**Issue by OJFord** [keybase/client#4260]
It's not obvious to me why inactive and subsequently revoked devices cannot have their names reused; though I understand this may be a security consideration for an issue I'm not aware of (when are device names used in any form of trust?).

However, this is a problematic UX particularly when reinstalling the device's OS.

Is there some sort of state or secret that can be exported and imported to allow reusing a device name across installs?

**Comment by 0xdevalias** [comment]
Dupe: https://github.com/keybase/keybase-issues/issues/1952

**Comment by anowlcalledjosh** [comment]
> Is there some sort of state or secret that can be exported and imported to allow reusing a device name across installs?

There is, although it's not exactly recommended. On Linux, you need to persist (some of) the files in `~/.config/keybase` – when I tried it, it seemed to be enough to keep `secretkeys.$USER.mpack` and (parts of) `config.json`.

**Comment by OJFord** [comment]
Closing as dupe per above.
