### ISSUE TITLE
Incorrect error when trying to write without permission

### ISSUE THREAD

**Issue by aacunningham** [keybase/client#4271]
Running Linux Mint 18 (practically Ubuntu 16.04) and using the client. If I try to create a file/folder in /keybase/public/someotheruser, I get a notification saying:

"You does not have read access to /keybase/public/someotheruser"

It should probably be "You **do** not have **write** access to /keybase/public/someotheruser"

**Comment by strib** [comment]
In the latest Linux release that just came out today, I see "write access" when I try to `mkdir /keybase/public/chris/test`.

However, I still see "You does".  @cjb I thought we fixed that?  Or has it not been merged yet?

**Comment by cjb** [comment]
@strib it's merged.. perhaps you didn't `run_keybase` after updating?  I see "cjb does  not have write access to /keybase/public/chris", with an extra space in there that I'll fix now.

**Comment by strib** [comment]
Ah yes, I see it now.  I thought the update process ran `run_keybase` for me, but I guess it doesn't do that anymore.  Strangely `keybase status` definitely showed the new KBFS version, but I guess `Keybase` didn't get re-run.

**Comment by aacunningham** [comment]
Just ran apt upgrade and I am running today's version. I also ran run_keybase

When I run `echo "hello" > /keybase/public/chris/test.txt` I get:

"aacunningham does  not have write access to /keybase/public/chris"

But when I run the same command but pointed at /keybase/public/someguyiknow/test.txt I get:

"aacunningham does  not have read access to /keybase/public/someguyifollow"

I've tried multiple people, but only this user so far has shown me the error.

**Comment by cjb** [comment]
> I thought the update process ran run_keybase for me

Meaning `apt-get upgrade keybase`? It doesn't do anything other than change the files on disk, you do need to `run_keybase` afterwards.

**Comment by strib** [comment]
@aacunningham: Does `someguyifollow` have keys in their Keybase profile?  Does he/she have a public directory with data in it already?

**Comment by strib** [comment]
@cjb: `apt-get install keybase`, but yes.  I'm just mistaken.

**Comment by aacunningham** [comment]
@strib I'm not entirely sure about whether they have keys in their Keybase profile, still pretty new to this whole program. They definitely don't have any files in there public directory yet though.

**Comment by aacunningham** [comment]
@strib Might have found something!

He just added a file to his public directory, and it's now showing the correct error message for me.

**Comment by strib** [comment]
Ah ok, I can repro on someone who hasn't yet created their own public directory yet.  I'll file a ticket to track internally.  Thanks!

**Comment by aacunningham** [comment]
No problem, thanks a lot for this incredibly cool program!

**Comment by strib** [comment]
Should be fixed in the next release, thanks!
