### ISSUE TITLE
Application fails to install helper and quits ( MacOS 10.11.6 )

### ISSUE THREAD

**Issue by RafPe** [keybase/client#4312]
App crashes with error XPC Error: Connection invalid

my log id: 060e403a102894df8fbbb61c

**Comment by maxtaco** [comment]
Cc: @gabriel

**Comment by gabriel** [comment]
What happens if you run:

```sh
# Quit app
pkill Keybase
# Kill helper tool process
sudo pkill keybase.Helper
# Start app
open /Applications/Keybase.app
```

Does it resolve the issue? Also it might be fixed with a reboot.

**Comment by RafPe** [comment]
Hey 

Seems like whatever have happen to my mac killed not only keybase. Also docker and other apps failed. 

I cannot reproduce anymore as I was at the point of when I needed to have working app and decided to flash my disk. 

But thanks for helping out!
