### ISSUE TITLE
KBFS fails to mount after upgrade to Windows 10 build 14926

### ISSUE THREAD

**Issue by cerebrate** [keybase/client#4313]
kbfsdokan reports the following error when run manually; otherwise, no errors appear other than in logs, and the absence of the k: drive:

"ERROR Failed to mount dokan filesystem (i=8): Dokan failed: -99"

my log id: e02d1af3f908d937c840791c

**Comment by maxtaco** [comment]
Cc: @zanderz

**Comment by cerebrate** [comment]
FYI: I have fixed this problem locally by removing the Dokan supplied with Keybase and replacing it with the Dokan 1.0 release version.

**Comment by maxtaco** [comment]
Cc @zanderz
