### ISSUE TITLE
Failed to mkdir on windows

### ISSUE THREAD

**Issue by ollieleahy** [keybase/client#4314]
Installed keybase filesystem on windows 10. 

Tried to create a subdirectory in my private keybase directory, the command failed.

my log id: 754c383b4d582bccc14e3e1c

**Comment by strib** [comment]
Looks to me like a network issue -- either you couldn't connect to our backend block servers through your network temporarily, or else our backend block servers were down (they weren't, to my knowledge).  In any case, it should be temporary -- does it work now?

**Comment by ollieleahy** [comment]
Yes it was temporary, and it was directly after installing on windows. After I rebooted it worked, might have been that installation was not complete, I suppose.

Thanks for the response
