### ISSUE TITLE
Finder Folders Fail to Open on macOS Sierra

### ISSUE THREAD

**Issue by rminnick** [keybase/client#4323]
Folders won't open from UI in menu bar or app window.  Also appears to be crashing finder when it attempts to open.

my log id: 3e7c2e0a9173eb317e48551c

**Comment by cjb** [comment]
Thanks for the report, CC @gabriel

**Comment by rminnick** [comment]
Additionally, the Keybase app freezes/locks up when I attempt to exit/close.

Finder still won't open/relaunch after Keybase has been killed.

**Comment by gabriel** [comment]
Sounds similar to this:
https://github.com/keybase/client/issues/4237

I'm still having trouble reproducing... I am downloading the new GM seed now though. (I was testing on the previous see from before sept 15.)

Can you kill ABRT kbfs and do a log send?

```sh
pkill -ABRT kbfs
keybase log send
```

**Comment by gabriel** [comment]
Also, can you try the latest build here: https://s3.amazonaws.com/prerelease.keybase.io/darwin/Keybase-1.0.17-20160919145206%2Baa3dc4a.dmg

Maybe reboot after installing?

**Comment by rminnick** [comment]
Trying the latest build now.  Will let you know how it fares.

**Comment by rminnick** [comment]
The latest build seems to be working with no crashing.  I'll close this for now and will re-open if longer use proves otherwise.

Thanks guys!

**Comment by gabriel** [comment]
I'm able to reproduce this, and seems to happen if api.keybase.io becomes unreachable. We're looking into a fix.
