### ISSUE TITLE
/keybase/Contents is not a keybase folder error

### ISSUE THREAD

**Issue by eirannejad** [keybase/client#4350]
Keybase GUI Version: 1.0.17-20160913233827+18b5a25

Action:
Keybase menu bar icon > Menu > `Open folders`

Keybase then opens the folders in finder but also sends a notification with the message:
`/keybase/Contents is not a keybase folder error. All folders begin with /keybase/private or /keybase/public...`

**Comment by strib** [comment]
This will be fixed in the next release, thanks.
