### ISSUE TITLE
/keybase/System is not a keybase folder error #4350

### ISSUE THREAD

**Issue by eirannejad** [keybase/client#4351]
Keybase GUI Version: 1.0.17-20160913233827+18b5a25

Action:
Finder > Get Info (On keybase remote folder)

Finder shows the info for the folder but keybase sends a notification with the message:
`/keybase/System is not a keybase folder error. All folders begin with /keybase/private or /keybase/public...`

**Comment by strib** [comment]
This will be fixed in the next release, thanks.
