### ISSUE TITLE
proxy support on macOS lacking

### ISSUE THREAD

**Issue by logich** [keybase/client#4360]
Keybase GUI Version: 1.0.17-20160829110024+c4e8dc8

Inside of my company we have a complex web proxy system with a defined autoproxy url. This is setup under a particular network interface and web browsers seem to have little problem with it. However, I have seldom found a command line tool with support. I need to explicitly set and export an HTTPS_PROXY envionment variable for keybase to talk to it's servers properly. I'd rather not do that for the GUI.

**Comment by maxtaco** [comment]
You should only need to do it for the background service since all gui
actions go through the service.

**Comment by cjb** [comment]
@logich Please see #4071.

**Comment by logich** [comment]
Understood and if I explicitly set the proxy server host and port with the environment variables either on the command line or in the system preferences GUI it works like a champ. However I was hoping that there was a way to leverage the proxy auto configuration file (PAC). I am going to cobble a script with https://github.com/pacparser/pacparser for now that will set the environment variables for me for specific apps and the hosts I expect them to connect to at their runtime.
