### ISSUE TITLE
Problem with updating my public filesystem......

### ISSUE THREAD

**Issue by mathmare** [keybase/client#4373]
Hey, so I reinstalled Linux to my computer and regenerated a new PGP key. Whenever I add a file to my /keybase/public/{username}/ directory, I don't see it come up in my keybase.pub website. In fact, when I deleted the old index.html from the directory, it still appeared on the site. I don't know if it's a bug or something I missed.

Keybase GUI Version: 1.0.17-20160919160132+a13b967

**Comment by strib** [comment]
Hi @mathmare -- by "regenerated a new PGP key", it looks like you mean you actually completely reset your Keybase account?  (Two days ago, judging by your [sigchain](https://keybase.io/hackermaneia/sigchain#6805165ea3cd0e93debce31aa0136f29e7fb7d1c43eeedfb97a3a2ce953fd3050f).)  In that case, keybase.pub probably still has your old, pre-reset public folder cached locally.  If that sounds right, let me know and I'll restart keybase.pub to pick up the new one.

**Comment by mathmare** [comment]
@strib Yes, that's what I meant (I could have worded it better). If you could help me out then that would be nice. Thank you.

**Comment by strib** [comment]
Done!  Sorry for the delay.
