### ISSUE TITLE
KBFS fails to mount on Windows

### ISSUE THREAD

**Issue by joshlitherland** [keybase/client#4392]
KBFS is failing to mount.  Attempted changing drive letter to Y: by setting an environment variable, though K: should be free.  

Running kbfsdokan from the command line, I get lots of this:

```
2016-09-22T17:49:39.084769 - [WARN kbfs connection.go:354] 03a (CONN KeybaseDaemonRPC 6cc6fd95) Connection: error dialing transport: Timed out waiting for pipe '\\.\pipe\kbservice\Users\Josh Litherland\AppData\Roaming\Keybase\keybased.sock' to come available
2016-09-22T17:49:39.085270 - [WARN kbfs connection.go:519] 03b KeybaseDaemonRPC: connection error: "Timed out waiting for pipe '\\\\.\\pipe\\kbservice\\Users\\Josh Litherland\\AppData\\Roaming\\Keybase\\keybased.sock' to come available"; retrying in 2.22916351s
2016-09-22T17:49:39.952385 - [DEBU kbfs connection.go:349] 03c (CONN CryptoClient d50f14c1) Connection: dialing transport
2016-09-22T17:49:40.949593 - [ERRO kbfs mounter.go:53] 03d Failed to mount dokan filesystem (i=64): Dokan failed: -99
```
my log id: b293b051e3fb815f362e1d1c'

**Comment by joshlitherland** [comment]
Wiped everything clean, removed Dokan drivers by hand, then reinstalled.  Working now.  Don't... don't really know why.

**Comment by taruti** [comment]
This sounds like there was a Dokan version conflict. Did you ever install Dokan by hand in the past?

The error (-99) means that loading dokan1.dll failed.

Cc @zanderz

**Comment by joshlitherland** [comment]
Yes and no.  Here's the sequence of events.  TL;DR: apparently Dokan is included with my HTC Vive software packages, but not installed anywhere in C:\Windows.  Not sure whether this is related to my initial difficulties or not.

Installed the keybase client.  About 2 days later when I decided to check out KBFS, noticed it wasn't working, drilled down and found the error in the included logs (-99).  

Made this ticket, then investigated the list of issues here and noticed someone else had fixed the same error by hand-installing the release version of Dokan.  Tried that, then started getting an error (-3), which I believe was "driver failed to start".  Tinkered for a bit with hand-replacing dokan1.dll in %APPDATA%\Keybase with the one from the Dokan release install, never got clear of that (-3) error.

Ran the uninstallers for both Keybase and Dokan.  Reinstalled Keybase.  Still had (-3) error.

Ran the uninstallers again, then searched my entire OS drive for files with /dokan/i in the name.  Removed them by hand.  **Noticed in doing so that the Dokan library appeared in my HTC Vive software packages,** though not apparently installed to C:\Windows anywhere.  Left them there in C:\Program Files\Common Files\HTC\Vive\Drivers\dokan.

Scoured dokan out of the registry.  Rebooted.  Reinstalled Keybase.  Everything works!  Closed ticket.

Please let me know if I can test anything further to help you narrow down this issue, I'm very willing to assist.  However, to be clear I am up and running with KBFS now. 

Thanks!

**Comment by taruti** [comment]
Your -3 was probably related to dokan1.sys and dokan1.dll version mismatch from the manual install.

Thanks for reporting things and glad things  worked out for you!
