### ISSUE TITLE
macOS Sierra: CLI tools missing from path

### ISSUE THREAD

**Issue by cbrunnkvist** [keybase/client#4398]
I downloaded, dragged and dropped the app as usual. The GUI upon first launch then prompted me about KBFS not being supported yet in Sierra, which is fine. But I guess it should still allow me to perform other tasks using the `keybase` command? But there was however never anything added to the `$PATH`.

(I _can_ still successfully run the command, but of course given the absolute path `/Applications/Keybase.app/Contents/SharedSupport/bin/keybase`)

my log id: 04954a67c52ea03b0e8d671c

**Comment by cbrunnkvist** [comment]
I just received the update that stated "- support for macOS Sierra" (log now says `version: 1.0.17-20160922174631+f87e42c`) but still observing identical behaviour: warning about KBFS, ignore to continue, looks fine but utils still not added to path when I open a new Terminal.

**Comment by manuelgerstner** [comment]
Exactly the same behaviour on my Sierra machine as described by @cbrunnkvist. 

- warning is still shown that Sierra is not supported
- keybase CLI can only be accessed manually

**Comment by maxtaco** [comment]
Cc: @gabriel on this one, seems like a new issue with Sierra.  We'll get on it.

**Comment by webRat** [comment]
I just downloaded keybase for the first time and I'm experiencing the same issue. I was expecting to be able to use the command line, but I can't.

**Comment by cbrunnkvist** [comment]
I checked additional filesystems and I originally had an old version of MacFUSE installed, but its kext was not loaded and even after removing this driver, the install step works exactly as before (i.e. not)

**Comment by sjafferali** [comment]
Didn't realize there was already a issue open on this. A few others that appear to be the same issue at #4468 and #4491

**Comment by gabriel** [comment]
The KBFS error message on Sierra is short circuiting and causing the CLI install to not happen. This will be fixed when we re-enable KBFS on Sierra which is happening very shortly.

**Comment by gabriel** [comment]
We just release 1.0.17-20160930202009+0229d49 and this should be fixed.

**Comment by ardian** [comment]
@gabriel thanks, will try that tomorrow.

**Comment by NikosEfthias** [comment]
it still doesn't work for some reason
