### ISSUE TITLE
Win10 KBFS

### ISSUE THREAD

**Issue by miwilc** [keybase/client#4399]
I am using  KBFS on my laptop when I try to open the k:\ or k:\private folders It says that it timed out and it can't open the folder 

my log id: 8c07a673b5c74a18173c261c

**Comment by strib** [comment]
I see errors like the following in your logs:

```
write tcp ...: wsasend: An established connection was aborted by the software in your host machine.
```

It looks like maybe there's a firewall that's blocking access to our servers?

**Comment by miwilc** [comment]
I no longer have access to the machine mentioned in this issue, nor can I reproduce it. closing.
