### ISSUE TITLE
"write took too long to respond" notification

### ISSUE THREAD

**Issue by soulware** [keybase/client#4415]
Writing to a file on kbfs just popped a notification up saying the write took too long to responde and to run a `keybase log send`. So here it is - 

my log id: a98625da2488f91727866a1c

This is what I originally ran when I received the error - 

```
echo "hello" > /keybase/private/soulware/hello.txt
```

**Comment by soulware** [comment]
Also seeing errors when mv'ing a small text file - 

```
mv hello.txt hello2.txt     
mv: rename hello.txt to hello2.txt: Input/output error
```

**Comment by strib** [comment]
We were seeing heavy traffic this morning and some users were seeing access errors.  Sorry for the inconvenience.  Does everything look ok now?  If so, please close out. We're investigating ways to prevent this from happening in the future.

**Comment by soulware** [comment]
Looks ok now. Thanks for the info.
