### ISSUE TITLE
Public directory on keybase.pub not found, strange log lines

### ISSUE THREAD

**Issue by jcassee** [keybase/client#4417]
This evening I noticed my public directory on keybase.pub (https://keybase.pub/jcassee/) no longer exists. Also this line keeps appearing in my logs (not sure if related):

`2016-09-24T20:31:40.392922 ▶ [WARN kbfs connection.go:414] 1fc MDServerRemote: DoCommand error: "MDServerErrorThrottle{ProvisionedThroughputExceededException: The level of configured provisioned throughput for the table was exceeded. Consider increasing your provisioning level with the UpdateTable API}"; retrying in 9.13107888s`

my log id: beb67a8a11da2e22ec18281c

**Comment by jcassee** [comment]
Also, `/keybase/kbfs.error.txt` contains exactly one line with the same error: `md-server: MDServerErrorThrottle{Duplicate re-registration}`

**Comment by strib** [comment]
Looks like it's back now.  Does it look ok for you now?  We were getting hit with a lot of traffic this morning, and it was preventing access for some (possibly keybase.pub) -- hence those throttle errors.  Please close out if everything looks ok now.

**Comment by jcassee** [comment]
Yes, it's working again. Thanks for the explanation!
