### ISSUE TITLE
[Windows 10 v1607 x64] KBFS Intermittent file access issues

### ISSUE THREAD

**Issue by ThatNateGuy** [keybase/client#4418]
Since the most recent update, the Keybase desktop no longer prompts me for my passphrase. I am, after a reboot, able to see the contents of my KBFS files, but then my access is lost and I am only able to see the Public and Private folders, but neither of their contents.

Already tried repair, reinstall, log off and log on via the shell. 

<img width="265" alt="2016-09-24 18_50_49-location is not available" src="https://cloud.githubusercontent.com/assets/3309578/18811751/bd29d3f2-8288-11e6-8326-3100a642d687.png">

my log id: d561b6abf30648c290a7581c

**Comment by strib** [comment]
Earlier today we were having excess traffic that was causing access issues for a portion of our users.  It looks like you might have been affected.  Are things working better now?  If not, maybe try one more restart, since we fixed the issue fairly recently.  Let us know how it goes, thanks!

**Comment by ThatNateGuy** [comment]
So far, so good after a reboot. Would you guys like another log file or is this enough?

**Comment by strib** [comment]
We're good, thanks!  Sorry for the inconvenience, let us know if it breaks again though
