### ISSUE TITLE
Unable to open private folders

### ISSUE THREAD

**Issue by jtsmith0101** [keybase/client#4419]
Was unable to see my private folders display when I opened from the widget.  Was the same result from the Keybase app.  

my log id: ecc7d9460702cff41b37361c

**Comment by jtsmith0101** [comment]
Restarted keybase and the folders displayed. However, I wasn't challenged to re enter my passphrase.  As a result, unable to open folders.

**Comment by strib** [comment]
The latest versions of Keybase don't require your password on a restart, we cache it securely locally until you explicitly log out.

It looks like you can't access your folders because of an excess of traffic hitting our servers.  We're working on it, sorry!

**Comment by jtsmith0101** [comment]
Excess traffic is good, right?

I was able to access my folder this morning from Windows.

**Comment by jtsmith0101** [comment]
this can be closed
