### ISSUE TITLE
Was not challenged for Passphrase on restart

### ISSUE THREAD

**Issue by jtsmith0101** [keybase/client#4420]
Perhaps a race condition?

Restarted the machine, but was not challenged with a passphrase.  Could display the devices, but unable to access my folders.

my log id: a0311b9d3d5677931896741c

**Comment by strib** [comment]
The lack of passphrase dialog is intentional.  The latest versions of Keybase don't require it, we cache it securely locally until you explicitly log out.

**Comment by jtsmith0101** [comment]
okay
