### ISSUE TITLE
Possibly related to #4419 and #4420

### ISSUE THREAD

**Issue by jtsmith0101** [keybase/client#4421]
Odd behavior in Linux.  Was not challenged for a passphrase.  Attempted to modify a file I had access to, but after modification, Dolphin kept crashing...

my log id: df9b97afffee0e490778861c

**Comment by strib** [comment]
As mentioned elsewhere, passphrase entry is no longer required unless you log out explicitly.

What is Dolphin?  The game simulator?  Does that have anything to do with the file you modified?  I don't see any errors in your log, but I'm not really sure what to look for.

**Comment by jtsmith0101** [comment]
no worries.  Dolphin is Kubuntu's version of windows explorer

**Comment by jtsmith0101** [comment]
this can be closed
