### ISSUE TITLE
Inconsistent bahavior on App - Does not display devices

### ISSUE THREAD

**Issue by jtsmith0101** [keybase/client#4423]
About 50% of the time.... the app does not display associated devices.   Please see screenshot, attached.
![2016-09-26](https://cloud.githubusercontent.com/assets/10441596/18819265/99c8b678-83d0-11e6-9533-4c23dff93591.png)

my log id: 1fb630e11d6d08b8b55e9e1c

**Comment by maxtaco** [comment]
Are you perhaps switching between several accounts?

**Comment by maxtaco** [comment]
Also, what does `keybase device list` on the command line show?

**Comment by jtsmith0101** [comment]
Hi Max,

The device list was as I expected.

I don't usually use Linux for Keybase, unless something isn't working well
in Windows....

When the app has an update available, is it possible to somehow either
email or post what those changes are?  Perhaps some new features?

Cheers,

James

**Comment by MarcoPolo** [comment]
Thanks James, I think I have a fix here: https://github.com/keybase/client/pull/4432

**Comment by jtsmith0101** [comment]
This can be closed.
