### ISSUE TITLE
Keybase client on Win7 doesn't start up, doesn't ask for login, does not mount KBFS

### ISSUE THREAD

**Issue by Chaos99** [keybase/client#4425]
The gui client just displays 'Loading ....' indefinitely without asking for a login.
Using the CLI is possible and will trigger a login, but this doesn't change the state of the GUI client.

Also the KBFS seems not to be mounted correctly. I see the drive letter K, but can't access it with the Windows Explorer. Doing a `cd K: ` and `dir` in the CLI yields a file listing with keybase-files, but no folders matching my private/public shares.

Log file is: d01b6430073130b08a15901c
System is Win7.

**Comment by maxtaco** [comment]
Cc: @zanderz

**Comment by zanderz** [comment]
Your log shows that the Keybase service can't be found or isn't running. Can you please uninstall both Keybase and Dokan Library from the control panel, reboot, and install the latest from https://s3.amazonaws.com/prerelease.keybase.io/keybase_setup_386.exe, then send logs again if there is still an issue? Thanks.

**Comment by Chaos99** [comment]
Clean reboot already solved the issue without uninstalling. Seems like the process was killed and nothing restarted it. Is the Client trying to restart a missing service?

Closing as fixed.

**Comment by Tourountzis** [comment]
Having same issue as the initial Ticket describes.

**Comment by maxtaco** [comment]
Cc: @zanderz
