### ISSUE TITLE
Keybase GUI seems stuck on 'Loading'

### ISSUE THREAD

**Issue by subbes** [keybase/client#4456]
Previously installed keybase through brew (1.0.15);  just downloaded the GUI .app and installed to "/Applications/Techy Rubbish".

The Keybase window appears stuck on 'Loading...' and I'm not sure what to do next.  I have tried:
1. Various combnations of quitting and relaunching .app, 
2. Quit app, brew upgrade keybase to 1.0.17, re-open app,
3. quit app, keybase uninstall, delete app, reinstall app

The GUI still displays only 'Loading...' and nothing else.  Is there meant to be an indicator of progress?  What should be my next steps?  

Mac OS X 10.10.5 (Yosemite).

Logs: 
2000c6e9e569803ed125471c
d0c5289e20aa2b9e12e2d31c
64bf0db9310cd4735ff21c1c

**Comment by cjb** [comment]
Try moving /usr/bin/keybase somewhere else and restarting the app. Sorry for the bad experience.

**Comment by subbes** [comment]
Unfortunately /usr/bin/keybase doesn't exist.

**Comment by subbes** [comment]
Some motion...

I was previously running Keybase.app from a subdirectory of Applications.  I moved it to the top level, and while it still looks like it's stuck on 'Loading,' there's some network activity happening so it might not actually be stuck.

I'll open a separate "Keybase should cope if it's not in the top level of the Applications folder" issue if it turns out to have been the only problem.

New log: 7fb701a8d4fe139085a0f11c

**Comment by subbes** [comment]
Update:  the GUI is now working!  I believe that the location of the app was the only issue.

**Comment by gabriel** [comment]
If Keybase isn't run from Applications it won't try to overwrite symlink in /usr/local/bin which means if you had brew installed then running `keybase` from Terminal might use old binary, and trigger a brew service start which might conflict with the app service.

This is a known issue and something we want to fix as soon as we can. Thanks for the bug report!

**Comment by gabriel** [comment]
We have a fix for this in master, and will be in a public build soon.
