### ISSUE TITLE
Kbfs seems to be borked.

### ISSUE THREAD

**Issue by awilson-cloudpassage** [keybase/client#4458]
Keybase GUI Version: 1.0.17-20160922174631+f87e42c
Everythong under /keybase is gone, but from only one computer.  All others are fine.  Is it possible to re-initialize KBFS on one host?

**Comment by cjb** [comment]
Please can you run `keybase log send` on the machine without KBFS access?

Is it running macOS Sierra, by chance?  (KBFS is temporarily disabled on that OS.)

**Comment by awilson-cloudpassage** [comment]
Yep, I just installed Sierra.  Sounds like that's the issue.  You still want the log?

**Comment by clamsmaloney** [comment]
1.0.17-20160929010715+fb25cc7 is working for me on Sierra, including KBFS. Will report back if I encounter any issues.

**Comment by ashmastaflash** [comment]
Please close, opened under #4462 with ref. to debug log.
