### ISSUE TITLE
FR: "keybase log show"

### ISSUE THREAD

**Issue by tml** [keybase/client#4473]
It would be nice if I could do something locally with "keybase log" to see what data would be sent on "keybase log send" - maybe "keybase log show" could open in my default editor a copy of the data that would be sent?

**Comment by strib** [comment]
`keybase status` shows you the location of the log files that are to be sent, so you could load them up in an editor yourself?  The logs themselves can be hundreds of thousands of lines of code, so there's not likely to be a way to show them automatically that will suit everyone on every platform.

**Comment by tml** [comment]
`keybase status | grep 'log:' | awk '{print $2}'` works fine for me.
