### ISSUE TITLE
Keybase updated on Sierra fail

### ISSUE THREAD

**Issue by eleanorstrib** [keybase/client#4486]
I get this error message periodically when the keybase app is open on my computer, running Sierra
![screen shot 2016-09-30 at 8 21 02 pm](https://cloud.githubusercontent.com/assets/8164570/19011502/3bc777d8-874c-11e6-949d-d994ed1bbcec.png)

my log id: 3e6aea31627089713d13051c

**Comment by gabriel** [comment]
Thanks for the bug report. This is a known issue and we are working on a fix.

**Comment by gabriel** [comment]
Timeout issues are resolved in recent builds.
