### ISSUE TITLE
ERROR GPG error: exit status 2

### ISSUE THREAD

**Issue by marianoju** [keybase/client#4504]
#### What happened so far
1. I have installed the [Keybase 64-bit application for Linux](https://keybase.io/docs/the_app/install_linux) 
2. executed `run_keybase`
3. entered my credentials 
4. executed `keybase log send` and send recent keybase log entries to keybase.io for debugging purposes only (my log id: 8797d72c576f05ae8027381c). 

#### What I expected
No error. 

#### What happened instead
Login via Keybase GUI app *and* command-line result in an error message: 

> **There was an error provisioning**
> Unknown error: GPG error: exit status 2

![error gpg error exit status 2](https://cloud.githubusercontent.com/assets/6254428/19070663/ad6a948c-8a2c-11e6-95cd-d7b863e3e452.png)

![screenshot from 2016-10-04 11-39-15](https://cloud.githubusercontent.com/assets/6254428/19070658/a88ad1e8-8a2c-11e6-94c3-07e0b4d020f0.png)

#### My Configuration
- Ubuntu 16.04.1 LTS (Xenial Xerus) 64-bit
- Kernel Linux 4.4.0-38-generic
- GNOME 3.18.3
- Memory: 7.5 GiB
- Processor: Intel® Core™ i5-3320M CPU @ 2.60GHz × 4

**Comment by maxtaco** [comment]
Something is going on with your local GPG configuration:

```
359 2016-10-04T11:34:10.274454 ▶ [DEBU keybase gpg_cli.go:66] 167 | configured GPG w/ path: /usr/bin/gpg2
360 2016-10-04T11:34:10.274507 ▶ [DEBU keybase gpg_cli.go:353] 168 | running Gpg: /usr/bin/gpg2 --no-tty --with-colons --fingerprint -K
361 2016-10-04T11:34:10.278105 ▶ [DEBU keybase gpg_cli.go:332] 169 gpg: starting migration from earlier GnuPG versions
362 2016-10-04T11:34:10.278930 ▶ [DEBU keybase gpg_cli.go:332] 16a gpg: porting secret keys from '/home/user/.gnupg/secring.gpg' to gpg-agent
363 2016-10-04T11:34:10.278971 ▶ [DEBU keybase gpg_cli.go:332] 16b gpg: can't open '/home/user/.gnupg/secring.gpg': Permission denied
```

**Comment by maxtaco** [comment]
Can you issue `/usr/bin/gpg2 --no-tty --with-colons --fingerprint -K`?  That will likely cause the same `permission denied` error.  Once that's fixed, login should work.

**Comment by marianoju** [comment]
I have found and removed '/home/user/.gnupg/secring.gpg', which was causing some other problems too. Keybase app is running smoothly now. Thanks for the advice!
