### ISSUE TITLE
Windows 10 - Client spits up a 'GPG is unavailable on this device' error.

### ISSUE THREAD

**Issue by dintendocoltd** [keybase/client#4521]
So, I got the Keybase client. Installed it and restarted my machine and after I logged in through the client, Keybase complains that 'GPG is unavailable on this device'.

Log ID: 4a96564a664af7496823131c
OS: Windows 10 Pro

<img src="https://dintendocoltd.co.uk/image/i09-42-06.png"></img>

Any workarounds for this? Or am I just simply missing an application that Keybase relies on?

**Comment by taruti** [comment]
Cc @zanderz

**Comment by maxtaco** [comment]
You do need GPG installed because you previously were managing your PGP private key, and your Windows client needs access to that private key to prove yourself to the server.

Do you have GPG installed on this machine?

**Comment by dintendocoltd** [comment]
@maxtaco I did not have PGP installed -- I recently installed GPG4Win, restarted my machine and it worked.
