### ISSUE TITLE
keeps opening on start up

### ISSUE THREAD

**Issue by IIlllIllII** [keybase/client#4556]

**Comment by maxtaco** [comment]
very old version

**Comment by IIlllIllII** [comment]
no update in app?

**Comment by IIlllIllII** [comment]
@maxtaco i downloaded the latest version trying to log in tells me this: unhandled incomping rpc 142 keybase.1.provisionUi.PromtNewDeviceName
what should i do?

**Comment by IIlllIllII** [comment]
@maxtaco i delete the old version and try to log in again get this https://puu.sh/rImcf/433e1f5a1a.png

**Comment by IIlllIllII** [comment]
i deleted my old account and invited myself again, sorry if thats bad im new to cryptography

**Comment by IIlllIllII** [comment]
put an update option within the app
