### ISSUE TITLE
Keybase: Files need to be rekeyed

### ISSUE THREAD

**Issue by genos** [keybase/client#4564]
Similar to [this issue](https://github.com/keybase/client/issues/3286) and [this one](https://github.com/keybase/client/issues/3560), I keep getting the `files need to be rekeyed` error. This is because I had to completely wipe & reinstall my OS after attempting to update to Max OS X Sierra. Thanks very much, and sorry for the trouble!

```keybase sign -m "$(date) Please reset folder /keybase/private/genos and /keybase/public/genos because a Sierra failure required Keybase reinstall"```

> BEGIN KEYBASE SALTPACK SIGNED MESSAGE. kXR7VktZdyH7rvq v5wcIkHbry9gp7X B1iumFtotenM6Zc xQt9CSLbd2Yr3Mb KtwTFPxti9sMjFd F7GlBZ3jWTb2MBV q7y2jR4chz9q5JF sKpaiuyCdRUDrRH DFcwqBw7aqViL6V gOffUr9JzgTfjWF 34WJjVu2Cdh9NWM qLaXdDcONPjZ3KX N9Kxx2RQvYRgWqy Z7c1zTWr4iivcdn gUWAO7dLgiiz5cR Wzfy0NikTg7tnKr FxmGLbfkWKYuzJ2 JZRRMYKMgLpVxNO v2BRqxgn15IHjrq I84dedcWd7Q3Ry0 jNL22D2xLMfE1aj Ay3NlbA1bMYBiS0 QkipMZAp3dSkBQR qiQNWIl2U9wJnVe BJ5C7fHKHkc2sPI ct1hlJkpgEHEFIS vyu3LSKU8XmWcMz Pbp45Bs8qZBcYkc KxFDQWZk0HnVjat Y4zrqKrpLFIxkEa Oe4GeAvUY8AXukc uHQ5KP3I02PRY. END KEYBASE SALTPACK SIGNED MESSAGE.

**Comment by strib** [comment]
Ok, I will look into this a little later today.

Out of curiousity, why did you revoke your paper key `morning juice`?  You could have recovered the folders with that (which should be independent of your OS installation).

**Comment by genos** [comment]
@strib I absolutely could have, sorry. In my frenzy to get this computer up and running again, I mistakenly revoked the paper key. My apologies!

**Comment by strib** [comment]
Bummer!  We plan to fix up our clients to give you better warnings when you're about to revoke a key that will lose you access to your data, but we haven't done that yet.  Sorry!

I reset those folders.  Please check it out, and close this out if things look good.

**Comment by genos** [comment]
Looks like that did the trick! Thanks for your time.
