### ISSUE TITLE
error (77) running the "curl" to verify key or install Keybase CLI

### ISSUE THREAD

**Issue by SylvainLapoix** [keybase/client#4573]
I tried to [install the Linux version of the Keybase CLI](https://keybase.io/docs/the_app/install_linux) (I'm on Ubuntu 16.04) and got this error :

`curl: (77) error setting certificate verify locations: 
  CAfile: /etc/pki/tls/certs/ca-bundle.crt 
  CApath: none`

I had the very same error report when trying to verify my public key.

Hence, I can't use the app.

Hope someone will help me to get out of my misery.

**Comment by oconnor663** [comment]
Sorry for taking so long to get back to you. Is it this command that's failing?

    curl -O https://prerelease.keybase.io/keybase_amd64.deb

Is `curl` working for you if you hit other HTTPS URLs? Maybe https://keybase.io or https://www.google.com?

**Comment by oconnor663** [comment]
Also this StackOverflow answer might help? http://stackoverflow.com/a/13400988/823869

> This error is related to a missing package: ca-certificates. Install it.
>
> In Ubuntu Linux (and similar distro):
>
> `sudo apt-get install ca-certificates`

If this is the problem I'd want to know more about why this happened to you and not other people? If the situation was "curl doesn't work on HTTPS on Ubuntu by default", I would hope we'd have noticed by now :(

**Comment by SylvainLapoix** [comment]
Thanks for getting back to me.

I tried the ca-certificates install but it's up to date as of the rest of my programs
`ca-certificates is already the newest version (20160104ubuntu1).`

Although, I tried tu `curl` some HTTPS URL and it actually didn't work, ending with the same error as before. So the catch must be around there.

**Comment by SylvainLapoix** [comment]
Tried [this answer](http://stackoverflow.com/a/31424970), seems to work. I'm retrying the install and let you know about my progress.

**Comment by SylvainLapoix** [comment]
And it's a success :+1: 

Thank you for your help (and fixing my `curl` problem in the process) !
