### ISSUE TITLE
Windows client does not open folders or allow filesystem interaction

### ISSUE THREAD

**Issue by avastmick** [keybase/client#4610]
Keybase GUI Version: 1.0.17-20160908172408+f09996a

Windows 10 Pro, v.1607 OSBuild 14393.321

Behaviour: the Windows version of the client does not allow filesystem interaction, either from the GUI or the Shell

This is likely due to Windows blacklisting kbfsdokan.exe during install due to the fact the executable is unsigned and subsequently blocked by the ``Service Control Manager``
<eventvwr>
```
The dokan1 service failed to start due to the following error: 
Windows cannot verify the digital signature for this file. A recent hardware or software change might have installed a file that is signed incorrectly or damaged, or that might be malicious software from an unknown source.
```
</eventvwr>

**Comment by zanderz** [comment]
This is a known issue, sorry for your troubles. We haven't gotten our drivers through the special process, but the Dokany project has. It should work if you uninstall the dokan we provided and install this one: https://github.com/dokan-dev/dokany/releases/tag/v1.0.0

**Comment by avastmick** [comment]
Okay. Done that, seems to work. Can close.

Thanks
