### ISSUE TITLE
Client issue after update

### ISSUE THREAD

**Issue by BrandonIngalls** [keybase/client#4621]
## Issue

The keybase client ran into an issue upon restarting the daemon after an update.
I ran `keybase unlock` after an update but nothing happened for a while so I issued a `<Ctrl> + C`.

Log ID: **13f380a84083e723e400dc1c**

``` bash
[~]$ keybase unlock
▶ WARNING Restarting after upgrade; service is running v1.0.17-20161007160040+61672fe, while v1.0.17-20161013160323+c0170f4 is available
▶ INFO Restarting service...
▶ INFO Forking background server with pid=6960

▶ ERROR interrupted

[~]$ keybase unlock
▶ ERROR interrupted

[~]$ keybase sign
lol

▶ ERROR Operation timed out

[~]$ lol
zsh: lol: command not found...

[~]$ keybase sign
lol
▶ ERROR Operation timed out
zsh: lol: command not found...
```
## Resolution

I ran `keybase ctl stop` and then `keybase unlock` to ensure everything was up and running again.

**Comment by cjb** [comment]
CC @gabriel

@BrandonIngalls Thanks for the report, how did you install this new version?

**Comment by BrandonIngalls** [comment]
The updated version came from the keybase repo.
```bash
[~]$ rpm -qi keybase       
Name        : keybase
Version     : 1.0.17.20161013160323.c0170f4
Release     : 1
Architecture: x86_64
Install Date: Thu 13 Oct 2016 06:54:46 PM EDT
Group       : Unspecified
Size        : 171568888
License     : BSD
Signature   : RSA/SHA1, Thu 13 Oct 2016 12:12:10 PM EDT, Key ID 47484e50656d16c7
Source RPM  : keybase-1.0.17.20161013160323.c0170f4-1.src.rpm
Build Date  : Thu 13 Oct 2016 12:11:49 PM EDT
Build Host  : 59e55808d185
Relocations : (not relocatable)
Summary     : Keybase command line client
Description :
Keybase command line client
```

The `keybase unlock` command was the first thing I ran after the update -- I think.

**Comment by cjb** [comment]
Thanks!  Checking it out.

**Comment by gabriel** [comment]
cc @oconnor663

**Comment by oconnor663** [comment]
@BrandonIngalls I don't have a theory here, and nothing in particular is jumping out at me in the logs. Have you seen this again since?

**Comment by BrandonIngalls** [comment]
@oconnor663 I have not run into the issue again.

**Comment by gabriel** [comment]
@oconnor663 Closing?
