### ISSUE TITLE
When I upgrade to Ubuntu 16.10 I lost the icon :(

### ISSUE THREAD

**Issue by Saphyel** [keybase/client#4627]
Keybase GUI Version: 1.0.17-20161007160040+61672fe

**Comment by cjb** [comment]
Hi! Which desktop are you using? Unity, Unity7, GNOME, KDE etc?

**Comment by Saphyel** [comment]
Unity/Gnome (default) I mean, not the 8 version. I think maybe on part of the upgrade to 16.10 Ubuntu deleted the icon..
