### ISSUE TITLE
Keybase read timeout on Sierra

### ISSUE THREAD

**Issue by sarajimenez** [keybase/client#4641]
I get this error periodically, running Sierra

<img width="307" alt="screen shot 2016-10-16 at 20 59 11" src="https://cloud.githubusercontent.com/assets/22877210/19423210/c493fa8e-93e3-11e6-90d0-508152f4775e.png">

my log id: 2dfebe779b629c2cbe28501c

**Comment by strib** [comment]
Hi @sarajimenez, thanks for the report.  It seems like your computer was having trouble reaching our servers within the timeout period.  Do you know how fast/reliable your internet connection was during that time?  Or maybe you were maxing out your CPU running other programs?  I don't see any immediate clues in our logs as to why it was so slow.

**Comment by ivanoats** [comment]
I am also seeing very high CPU usage on Sierra. I frequently have to kill keybase.

**Comment by maxtaco** [comment]
@cjb / @gabriel  did we decide this is due to the new Poll bug in Sierra?

**Comment by cjb** [comment]
@ivanoats Please could you send in a `keybase log send`? Thanks!

**Comment by ivanoats** [comment]
ok, thanks.   https://github.com/keybase/client/issues/new?body=[write%20something%20useful%20and%20descriptive%20here]%0A%0Amy%20log%20id:%201494504486d5132a59beea1c

**Comment by ivanoats** [comment]
ok - my log id: 1494504486d5132a59beea1c  . thanks!

**Comment by gabriel** [comment]
@ivanoats Read timeout and high CPU might be unrelated, or at least probably want to track them as separate issues. Moved your issue to: https://github.com/keybase/client/issues/4671

The read timeouts I've seen happen on sparse connectivity. We can run with network link conditioner to find when this happens?
