### ISSUE TITLE
CLI Error Unexpected version clash

### ISSUE THREAD

**Issue by dhuyvetter** [keybase/client#4654]
On windows on the command line, when I try for instance `> keybase login` I get this error:

`ERROR Unexpected version clash; client is at v1.0.15, which *less than* server at v1.0.17-20160908172133+f09996a`

I have tried uninstalling Keybase and installing the latest version from [here](https://keybase.io/docs/the_app/install_windows), but I keep getting this error.

my log id: 82a14c60aedd170888fd011c

**Comment by maxtaco** [comment]
@zanderz please take a look.  Likely there are two versions of KEybase in your path, and the old one (v1.0.15) wasn't properly cleaned up

**Comment by dhuyvetter** [comment]
I cannot find any other keybase.exe in my path or elsewhere, except the one at C:\Program Files (x86)\Keybase which says it's modified date is 2016-04-01. How can I update this? I keep downloading and uninstalling an re-installing from https://keybase.io/docs/the_app/install_windows but that doesn't seem to change this version. Where or how do I get the latest keybase cli?

**Comment by maxtaco** [comment]
You have the most recent version, but the old one is getting in the way.  Can you delete `C:\Program Files (x86)\Keybase\keybase.exe`?

**Comment by maxtaco** [comment]
BTW, @zanderz will know more

**Comment by dhuyvetter** [comment]
How do I add the new version to my path? I mean, where is it located on Windows? I cannot find it at it isn't added to my path automatically, so I cannot run keybase on the command line when I delete that old version.

**Comment by dhuyvetter** [comment]
Think I found it in my \AppData\Roaming\Keybase folder.

**Comment by maxtaco** [comment]
Are you using the "Keybase Shell"?

**Comment by dhuyvetter** [comment]
Yes, I managed to get it up to date, now `keybase help` gives the right version: `1.0.17-20160908172133+f09996a`

**Comment by dhuyvetter** [comment]
So yeah, this issue can be marked as closed.
