### ISSUE TITLE
repeatedly asked for passphrase on secondary device

### ISSUE THREAD

**Issue by drammock** [keybase/client#4661]
possibly related to #4634 

I have a working install on my laptop, and added second device (desktop).  Desktop is acting weird; I get "input/output error" when trying to view private folders in Thunar or using `ls` in terminal.  I keep getting prompted with GUI boxes asking me to 

> please enter your keybase passphrase to unlock the secret key for device {DESKTOP-NAME}". 

Nothing I put in there works; tried my keybase passphrase (works to log in to website), the passphrase of my GPG key, and the paper key that was auto-generated for my account.  Tried `keybase logout; keybase login` which then showed my username and prompted me first to login with my keybase passphrase (the one I use for the website, which worked) but immediately showed the second prompt again (which doesn't work).  At some point it added a "too many failures, giving up" message in red, below the passphrase entry box.  At that point I tried `keybase deprovision`, which doesn't work either: I just get that same prompt for a passphrase that I apparently don't have.

When I provisioned the Desktop device by typing in the paper-key-like list of words that was showing on the laptop, was I supposed to save that?  Is that the "device passphrase" it keeps asking for?

my log ID: 95cc17d7db958037ec717d1c

**Comment by maxtaco** [comment]
Very worrisome.  Thanks so much for the feedback.   I'll look into it

**Comment by maxtaco** [comment]
Can you try this for me:

```
keybase db nuke
keybase login
```
?

**Comment by drammock** [comment]
after nuke and login, I get the same GUI prompt, and the same "failed to unlock key; bad passphrase" result.

**Comment by maxtaco** [comment]
Ok, we have some theories about what went wrong. I'll investigate further.  In the mean time, you might try to follow the "fix" in #4634, which is to manually deprovision and then reprovision with your paper key.  I'm looking into it with utmost priority.

**Comment by drammock** [comment]
is there a chance of a fix that doesn't require deprovisioning?  If I deprovision then I lose this device name, which is annoying.

**Comment by maxtaco** [comment]
I'm not quite sure.  My best guess as to what's wrong is that there's a bug somewhere in encrypting the secret key on your second device.  Unfortunately this sort of thing is very hard for us to debug since we don't want to know your passphrase or your secret key. But it's happened twice now, so there's likely some bug.

**Comment by maxtaco** [comment]
We have a PR up at #4667, but that won't save you from having to reprovision your second device.  I think we're going to put repair code into the new client.

**Comment by drammock** [comment]
Thanks @maxtaco I'll reprovision today then.

**Comment by maxtaco** [comment]
Maybe wait until our PR is merged? It is stuck in CI right now since it
affects all 5 platforms differently.

**Comment by drammock** [comment]
Good point. More importantly I should wait until that PR is part of my local install. Will the package update description reference specific issue numbers?

**Comment by oconnor663** [comment]
@drammock no, we don't generate any update descriptions. `keybase version` shows you the short commit hash you have installed though.

**Comment by drammock** [comment]
FYI, I did *not* have to reprovision my second machine.  After waiting a week, installing updated keybase through apt, and a `run_keybase`, this problem no longer occurs.  Hooray for #4667 and #4683!

**Comment by maxtaco** [comment]
Cool, I'm glad, thanks so much for your help in debugging.

There is a further PR (#4962) that goes and cleans up the mess for good.
