### ISSUE TITLE
KBFS issue with space in filename

### ISSUE THREAD

**Issue by sdigit** [keybase/client#4663]
I was testing to be sure I could create files in KBFS and read them on both devices I use (I can), and noticed something strange: when I used nemo (in Fedora 24) to create a file (`Untitled Document`), I actually ended up with two files: `Untitled` and `Document`.

Is this a known issue? I have no great need for spaces in my kbfs filenames, but I wanted to report this in case it was a string parsing bug somewhere or the like.

**Comment by strib** [comment]
Hi @sdigit -- interesting.  I don't have a problem with this with Ubuntu's default file explorer (i.e., it makes a single "Untitled Folder" directory).  I don't know of any outstanding KBFS issues in this area.  You're sure that nemo works correctly on a normal filesystem as well?  If you'd like to reproduce it and then do a `keybase log send`, I can take a look and see what file system calls are coming in from the operating system.

**Comment by sdigit** [comment]
I am unable to replicate it any longer; I was using nemo under Fedora 24 and have updated packages since it first happened; I'm going to close this since it appears to no longer be an issue and will reopen it if it recurs.
