### ISSUE TITLE
Error No secret key available

### ISSUE THREAD

**Issue by fruitloop** [keybase/client#4675]
Hi, I use my TREZOR (https://buytrezor.com?a=cfd415e2d9db) to store my GPG Private Keys, therefore there is no private Key on my machine. 

If I try to add the public key the client tells me:

```
[roland@Turtle:~] % gpg2 --export --armor 7E9266BFAA9BE177D92DDAFB51F3833053F2E698|keybase pgp import   
▶ ERROR No secret key available
```

my log id: 41d706058f0d69d47ddab11c

**Comment by fruitloop** [comment]
Ping

**Comment by maxtaco** [comment]
Sorry we don't currently support this mode of operation.  What do you mean to do here, just associate your public PGP key with your keybase account?

**Comment by fruitloop** [comment]
Pretty much yes. Since this is a place to link Public Keys to Social Profiles it makes sense to upload the GnuPG Key even if I can't use the functionality of decrypting/signing. (I am using my trezor agent for that)

**Comment by caraka** [comment]
I'm trying to do much the same thing. I use a nitrokey pro, which I thought was compatible from previous issues I've seen, but I am unable to load the pgp key if my client was opened with the passphrase, or to open the client with the passphrase if I have loaded (and verified!) the pgp key via the browser. It's a viscous circle.

**Comment by maxtaco** [comment]
Have you guys tried 'keybase pgp select --no-import'?

**Comment by caraka** [comment]
I had not. When I tried it just now, it says no PGP keys available, etc. gpg --list-keys shows them, public and subkeys. Judging by other threads talking about Yubikeys, the nitrokey should work.

**Comment by fruitloop** [comment]
I tried `keybase pgp select --no-import` and it failed with:
```
Choose a key: ▶ WARNING GPG index error at line 7: Unknown subfield: grp
▶ WARNING GPG index error at line 10: Unknown subfield: grp
▶ WARNING GPG index error at line 14: Unknown subfield: grp
```

**Comment by maxtaco** [comment]
Which version of keybase?

That is just a warning (that I fixed a few weeks ago) but likely something
else failed.  Can you do a 'keybase log send'

**Comment by fruitloop** [comment]
I'm using Version 1.0.17
```
keybase log send

------------
Success! Your log ID is:

  3bb3b18f14abe195f29d191c
...
```

**Comment by maxtaco** [comment]
I'm pretty sure this bug is fixed.  Are you running the brew-installed version of keybase?  That's a little bit out of date.  The DMG bundle release from our main site should have a fix.

**Comment by fruitloop** [comment]
I removed the version by brew and installed your DNG now a `keybase pgp list` shows nothing at all. With `gpg2 -k` however I can see all my keys.

**Comment by maxtaco** [comment]
Did you try `keybase pgp select --no-import` again?

**Comment by fruitloop** [comment]
`keybase pgp select --no-import` returns:
`▶ ERROR GPG error: exit status 2`

**Comment by maxtaco** [comment]
Can you do another `keybase log send`?

**Comment by fruitloop** [comment]
Log ID: 0db909fd9af71cd2d9fe591c

**Comment by maxtaco** [comment]
Thanks, seems like it's still failing on something Trezor-related, but I haven't tested with one, so I can'r repro.

**Comment by fruitloop** [comment]
Given that one needs the Private key on the same system as keybase it seems that it would also not be possible to handle air gapped offline keys?

**Comment by maxtaco** [comment]
We have per-device keys. People without PGP use that. People with PGP use their PGP key as another "device" key since it has all of the same powers as a per-device key.  But the keybase per-device keys never leave their devices.  They just sign each other into rotation.  See [this blog post](https://keybase.io/blog/keybase-new-key-model).

**Comment by maxtaco** [comment]
You've hit a corner case that we don't have too much bandwidth to throw at, since it's unusual relative to our common use cases (people not using PGP or using PGP without Trezor-like devices)

**Comment by fruitloop** [comment]
so there is no way to 'not use' and just upload my PGP key since I have a device key already? as well as a paper key.

**Comment by maxtaco** [comment]
Not as of right now though we are an open source shop and do welcome
contributions and bug fixes!!
