### ISSUE TITLE
Device List not loading after system restart

### ISSUE THREAD

**Issue by jtsmith0101** [keybase/client#4680]
I believe I've reported this in the past.  In case I didn't, here is the log.

Completed a computer restart and keybase did not load the approved device list in the GUI.

my log id: 491015a282b3543e9289b91c

**Comment by maxtaco** [comment]
Does `keybase device list` give the right answer?

**Comment by jtsmith0101** [comment]
Yes.... and the error is inconsistent.  Sometimes the device list loads.
Sometimes it doesn't.

**Comment by maxtaco** [comment]
Cc: @chrisnojima

**Comment by chrisnojima** [comment]
I think we have a fix for this. It'll be in the next update, thanks!
