### ISSUE TITLE
KBFS not running

### ISSUE THREAD

**Issue by axd** [keybase/client#4700]
I've installed the client successfully but the KBFS system isn't working. I have access to /keybase folder but there is no "public" and "private" folders as well. 

I've sent my logs already.

Thanks.
 
my log id: c46b3b5e052469dc7819401c

**Comment by strib** [comment]
@axd: did you start keybase with the `run_keybase` command?  Looks like KBFS never started, and that's the command which does it.  You need to run it explicitly on Linux.

**Comment by axd** [comment]
@strib Thank you man. It is running now. I didn't found that command in the docs.

**Comment by strib** [comment]
Ok great!  It's on this page in all the instructions for running on various flavors of Linux: https://keybase.io/docs/the_app/install_linux
