### ISSUE TITLE
disabling KBFS? (windows)

### ISSUE THREAD

**Issue by draeath** [keybase/client#4713]
I installed the keybase client on a windows box to play around. It seems KBFS came with it and I now have an unwanted drive letter.

How can I turn this off? I don't want this functionality. There seems to be nothing regarding turning this off (or even changing the drive letter) in the documentation.

**Comment by draeath** [comment]
I'd also like to do this on linux. A fuse filesystem was mounted that *i don't want* and I don't see where this was set up.

**Comment by taruti** [comment]
Cc @zanderz

**Comment by zanderz** [comment]
You can remove the startup shortcuts which launch our background processes from `%appdata%\Roaming\Microsoft\Windows\Start Menu\Programs\Startup`. Soon we will have better support for changing the drive letter, but you can do this with the command `keybase config set mountdir X:` where X is your new letter.

**Comment by jwshields** [comment]
This does not seem ideal at all. 
I just installed Keybase on a Windows machine of mine. Ever since I installed it, one of my network drives had the KBFS icon on it- I was pulling my hair out trying to figure out where it was coming from, other than the obvious sign it was something Keybase related.

I have a large amount of drives and can't afford to have something mounted when I don't want it there. I don't see any option of disabling it.

**Comment by zanderz** [comment]
The only way to disable that for now is to modify the startup shortcut. Go to `%appdata%\Microsoft\Windows\Start Menu\Programs\Startup` and modify the command line for the KeybaseStartup shortcut, replacing this:
`runquiet.exe keybase.exe ctl watchdog2`
with:
`runquiet.exe keybase.exe ctl watchdog`

**Comment by draeath** [comment]
How is this done on Linux, out of curiosity?

**Comment by zanderz** [comment]
Update: Running without a KBFS mount is not officially supported, but on Windows you can unofficially you can uninstall Dokan and change your startup shortcut back to `watchdog2`.

**Comment by ageis** [comment]
@draeth there is an environment variable called `KEYBASE_NO_KBF`. export and set it to `1` in your profile/environment/systemd session.

**Comment by ageis** [comment]
> How is this done on Linux, out of curiosity?

@draeath there is an environment variable called `KEYBASE_NO_KBF`. export and set it to `1` in your profile/environment/systemd session.
