### ISSUE TITLE
installed keybase on another laptop and permission denied when I cd into /keybase

### ISSUE THREAD

**Issue by ChrisFernandez** [keybase/client#4718]
https://github.com/keybase/client/issues/new?body=[write%20something%20useful%20and%20descriptive%20here]%0A%0Amy%20log%20id:%20a8897246f9f54ff9e487f71c

if I use the UI then I can access it but not with the terminal...

**Comment by strib** [comment]
Hi @ChrisFernandez -- it may take some time for your other devices to rekey your folders to give your new device access -- maybe you tried to get into them on the terminal for they were ready?  Does it work now, or is it still broken?  I don't see any unusual "permission denied" errors in your log.

**Comment by maxtaco** [comment]
@ChrisFernandez did you see any notifications that you should facilitate rekey by turning your original device on (or by entering your backup key)/

**Comment by ChrisFernandez** [comment]
@maxtaco you were right.. works now... thanks... BTW what's the ETA for a non-beta version :dancer:
