### ISSUE TITLE
Allow the use of qubes-gpg-client for split-gpg setup in QubesOS

### ISSUE THREAD

**Issue by graffen** [keybase/client#4722]
I'm using keybase on my laptop that runs Qubes OS and I have set up my private gpg keys using https://www.qubes-os.org/doc/split-gpg/. That means I don't have my private keys in the same VM that runs keybase, thus I can't use `keybase pgp sign`. 

Is there a way to specify that keybase should use the `qubes-gpg-client` wrapper instead of the built-in/system client, when trying to access my private keys?

**Comment by maxtaco** [comment]
You can try:

```
keybase config set gpg.command qubes-gpg-client
```

?

**Comment by graffen** [comment]
Nope, no luck. 
```
user@personal:~$ keybase config set gpg.command /usr/bin/qubes-gpg-client
user@personal:~$ keybase pgp sign -m "Hi"
▶ ERROR No secret key available
```
I also tried without the full path to qubes-gpg-client

**Comment by maxtaco** [comment]
You might not want to use keybase for PGP operations then, other than pulling PGP keys into your PGP keyring.  I haven't played around with this configuration much.

**Comment by graffen** [comment]
I played around with it a little more. It turns out that some commands actually do use the configured wrapper (meaning I get the Qubes popup asking if I wish to grant access to my gpg key on another AppVM through split-gpg), for example `keybase pgp pull` and `keybase pgp update`. But commands that require access to my private key, like `keybase pgp decrypt` or `keybase pgp sign` fail on not being able to find the key.

**Comment by maxtaco** [comment]
Have you tried `keybase pgp import` to import the PGP key into your keybase keyring?  We don't shell out for the commands you mentioned

**Comment by graffen** [comment]
Ah ok... well the whole point is that I don't want my private key to reside on an AppVM that has internet access. That's what makes the Qubes Split GPG setup so nice, that my private key is never directly exposed to the network (exactly like if it was on a YubiKey or a smartcard). I'll just continue to use qubes-gpg-client directly instead of going through keybase for now. Thanks.

**Comment by maxtaco** [comment]
Cool, makes sense!

**Comment by petertodd** [comment]
FYI I have this type of setup as well, and would appreciate a fix.
