### ISSUE TITLE
Is there a current build list anywhere?

### ISSUE THREAD

**Issue by rminnick** [keybase/client#4730]
I can never tell if I'm on the current version or if my autoupdate is working.  It would be nice to compare the output of `keybase -v` to something useful.

**Comment by maxtaco** [comment]
Sorry to not be more explicit, but does [this help](https://prerelease.keybase.io/)?

**Comment by rminnick** [comment]
Indeed it does - I just like to have a location to check and ensure I'm running the most current build before I raise any issues/etc.  My MacBook Pro dislikes autoupdates of any variety.

Appreciate it!
