### ISSUE TITLE
Unknown error: GPG is unavailable on this device

### ISSUE THREAD

**Issue by MLWALK3R** [keybase/client#4732]
[same issue as #3337]

my log id: 836a8c437e9a42e8a779581c

**Comment by cjb** [comment]
@MLWALK3R Thanks!  Do you think you have `gpg` installed?  Does running `gpg` and/or `gpg2` do something?

**Comment by MLWALK3R** [comment]
I've not installed GPG I just assumed keybase had its own version it used.

**Comment by cjb** [comment]
Thanks.  @maxtaco or @patrickxb, does it look correct that gpg was required for this log?

**Comment by MLWALK3R** [comment]
Also I'm using windows not OSX/Linux just incase you're not aware ;)

**Comment by cjb** [comment]
Got it, thanks.  Have you ever used the Keybase app on Windows on this computer before?  Was today your first ever install, or an upgrade?

**Comment by MLWALK3R** [comment]
I installed it today, then got an update (rebooted etc).

**Comment by MLWALK3R** [comment]
I've got it working now installed gpg4win and ran some commands via the Shell
