### ISSUE TITLE
cronjob refers to chrome

### ISSUE THREAD

**Issue by ptman** [keybase/client#4738]
https://github.com/keybase/client/blob/master/packaging/linux/deb/cron.template#L7

**Comment by maxtaco** [comment]
Cc: @oconnor663

**Comment by oconnor663** [comment]
Yes, I've preserved the chromium copyright and comments verbatim. Funny you should mention that script, we just had a [huge issue with it](https://github.com/keybase/client/pull/4733). (Were you following our commits maybe?)

**Comment by ptman** [comment]
No, I was trying to figure out what the /keybase directory in my root is doing, re #4739
