### ISSUE TITLE
"ERROR EOF" when trying to add a new device from an existing device

### ISSUE THREAD

**Issue by TheMRod** [keybase/client#4747]
I'm trying to add a new device from my existing device "offworld." When I try and do this, I get "ERROR EOF."

```
~ keybase device add
What kind of device are you adding?

(1) Desktop or laptop
(2) Mobile phone

Choose a device type: 1
▶ ERROR EOF
```
I have tried logging out and then re-logging into Keybase on the existing device, but it didn't help.

my log id: e8dab91550cde41d5150501c

**Comment by TheMRod** [comment]
For what it's worth, I was able to use my paper key fine.

**Comment by maxtaco** [comment]
Never seen this before, seems like you ran out of memory when stretching the shared secret via scrypt!  What sort of machine are you on?

Thanks!

**Comment by TheMRod** [comment]
Out of memory seems **VERY** likely! This is running on a 512MB DigitalOcean instance, the cheap $5/month kind. I run out of memory just doing software updates. I'll try adding a device with more free RAM and see how that works.

**Comment by maxtaco** [comment]
Ah cool, thanks. Yeah, this part of the key-exchange is *intentionally* memory-hungry, to prevent a corrupt server from snooping or corrupting your session.

**Comment by TheMRod** [comment]
OK, it worked fine once I quit SpamAssassin and freed up a bunch of RAM. Thanks for the help on that! I'll close this bug report.
