### ISSUE TITLE
Can't log in due to not being able to set proxy settings

### ISSUE THREAD

**Issue by maraisr** [keybase/client#4777]
```
Unknown error: API network error: Get https://api.keybase.io/_/api/1.0/user/lookup.json?fields=basics%2Cpublic_keys%2Cpictures&multi=1&username=UNAME: read tcp 192.168.12.35:49365->XXXXXXXXXXXX: wsarecv: An existing connection was forcibly closed by the remote host.
```

**Comment by patrickxb** [comment]
@maraisr are you using the `--proxy` flag?  Or you can set `proxy` in your config file with 

    keybase config set proxy https://myproxy.whatever

If that didn't help, please run 

    keybase log send

after a failed login attempt and post the log id here and we'll investigate.

Thanks!

**Comment by letroll** [comment]
Same here. How can I set port, username and password of my http proxy?

**Comment by kaskavalci** [comment]
Duplicate of #4557
