### ISSUE TITLE
Popup for changed proofs does not render properly

### ISSUE THREAD

**Issue by NthPortal** [keybase/client#4779]
The popup is below.

![I don't think it's supposed to look like this](https://i.gyazo.com/eb05e6aa35718f8dc2c7ee291687ea66.png)

my log id: 6ba8bb960ddc2a98dcdb9d1c

**Comment by maxtaco** [comment]
Cc: @chrisnojima. Looks like the lookup to `https://chris.keybase.pub` failed, but then the popup didn't render properly.  Feels like a race condition.  Looks like all of the RPCs were fired from my perspective...

**Comment by chrisnojima** [comment]
Investigating

**Comment by NthPortal** [comment]
Do we assume this is fixed?
