### ISSUE TITLE
bitcoin publish error bad gateway.

### ISSUE THREAD

**Issue by djdesign** [keybase/client#4791]
Publishing bitcoin address for bash returns 502 bad gateway.

my log id: d89e570f70675944eb27ff1c

**Comment by oconnor663** [comment]
Very glad for the report! Should be fixed shortly.

**Comment by oconnor663** [comment]
@djdesign it should be fixed now, could you give it another shot?

**Comment by djdesign** [comment]
@oconnor663 confirmed working like a charm. What was the issue?

**Comment by oconnor663** [comment]
Nothing interesting I'm afraid. Just some out-of-sync dependency metadata that happened to affect that endpoint in particular.

**Comment by djdesign** [comment]
At it was a simplier resolve.
Thanks again!
