### ISSUE TITLE
Error while git pushing over cellphone connection

### ISSUE THREAD

**Issue by becomingwisest** [keybase/client#4802]
I was updating my blog while tethered to my cell phone, and I use keybase to sync the git repo (/keybase/private/becomingwisest/becoming.wise.st.git) between computers

$ git push origin
Counting objects: 4, done.
Delta compression using up to 8 threads.
Compressing objects: 100% (4/4), done.
Writing objects: 100% (4/4), 1.78 KiB | 0 bytes/s, done.
Total 4 (delta 2), reused 0 (delta 0)
remote: error: unable to create temporary file: Input/output error
remote: fatal: failed to write object
error: unpack failed: unpack-objects abnormal exit
To /keybase/private/becomingwisest/becoming.wise.st.git
 ! [remote rejected] master -> master (unpacker error)
error: failed to push some refs to '/keybase/private/becomingwisest/becoming.wise.st.git'

my log id: 4162b23a58c00de7a2f0c41c

**Comment by strib** [comment]
Hmm, sorry about that.  It looks like Amazon (our storage host) may have been having issues, which kept forcing your client to retry until eventually hitting a timeout.  I _think_ it was a random occurrence, and unrelated to your cell phone tethering, but I'll keep my eyes open for similar issues.

Note that soon we'll be able to better insulate your FS from network and storage issues like this (though the git use case is a little tricky, though I think the improvements should still work fine for single-user repos like this one).

**Comment by becomingwisest** [comment]
Cool. Anything else needed before you close this?

**Comment by strib** [comment]
We don't need anything more from you, thanks!

I'm on the fence about whether to close it though, since we didn't actually fix anything and I'm not 100% sure there's nothing we could have done to help.  I'll probably keep it open for now, but if you'd prefer it closed, feel free.

**Comment by strib** [comment]
Version 1.0.20 has architectural changes that should greatly improve the large write experience.  If you're still seeing problems, please open a new issue.
