### ISSUE TITLE
Can't login from CLI

### ISSUE THREAD

**Issue by jungziege** [keybase/client#4808]
When attempting to login, pinentry pops up, and I enter my password, and then I get the following response:
```
$ keybase login
▶ ERROR no auth system available (error 100)
```

Playing around with it, I noticed that that error also shows up when my password is wrong. But, I just successfully used this password to log into the website. 

my log id: 8bb34e824f873d816f72bc1c

**Comment by maxtaco** [comment]
Your client is super out-of-date.  Can you upgrade?

**Comment by jungziege** [comment]
Seems to have disappeared with the update -- thanks!
