### ISSUE TITLE
Keybase CLT not in PATH with Keybase.app in ~/Applications

### ISSUE THREAD

**Issue by rnkn** [keybase/client#4840]
When installing Keybase.app into ~/Applications the app runs but `keybase` is not found in `PATH`.

Just mentioning because it confused me for a bit. I had installed via Homebrew first, then uninstalled and used Keybase.app... then didn't have the CLT.

Keybase GUI Version: 1.0.18-20161109120011+4d00aa8

**Comment by cjb** [comment]
CC @gabriel

**Comment by ELBeavers** [comment]
Same here on macOS 10.12.1, also with Version 1.0.18-20161109120011+4d00aa8

**Comment by ELBeavers** [comment]
Turns out, reinstalling from homebrew seemed to update with the the latest 1.0.18 version. Could not find this documented anywhere on keybase.io.

Please set me straight if there is a more correct way.

**Comment by gabriel** [comment]
Thanks for bug report, this is a dupe of https://github.com/keybase/client/issues/4840

We see this coming up more and more, so likely will bump up the priority on this.

**Comment by gabriel** [comment]
Oops I mean dupe of https://github.com/keybase/client/issues/4151
