### ISSUE TITLE
keybase stuck at loading 

### ISSUE THREAD

**Issue by RobbiNespu** [keybase/client#4841]
Hi there! 
I am using fedora 24  (x64) and installing keybase using this command :
`$ sudo dnf install https://prerelease.keybase.io/keybase_amd64.rpm `

when I type `$ run_keybase` it said
```
Launching keybase service...
Mounting /keybase...
Launching Keybase GUI...
Success!
```

but it keep stuck at
![screenshot from 2016-11-12 23-14-26](https://cloud.githubusercontent.com/assets/3077875/20238780/cb6cf50e-a92d-11e6-9178-49d1c4e89958.png)

When I tried login using terminal, i got
```
$ keybase login
▶ ERROR dial unix /run/user/0/keybase/keybased.sock: connect: permission denied
```

It is a bug? or any work around?

**Comment by cjb** [comment]
Thanks, that's strange. Are you able to run `keybase --standalone log send`?

CC @oconnor663

**Comment by RobbiNespu** [comment]
Nope, its nope working
![screenshot from 2016-11-12 23-22-52](https://cloud.githubusercontent.com/assets/3077875/20238832/f898d952-a92e-11e6-8113-b35f30bfad4c.png)

Tried as root user too and it said :
`ops, you are trying to run as an admin user (Uid: 0). This isn't supported.`

**Comment by cjb** [comment]
Hi, I asked for `log send`, not `log`.

**Comment by RobbiNespu** [comment]
Hi , i already attach the picture as above (on the second line). it said error mkdir. Seem permission was denied

**Comment by cjb** [comment]
Ah! Thanks. Okay, we'll check it out. Are you aware of anything strange about your installation, like extra security features?

**Comment by RobbiNespu** [comment]
Sorry, do you mean my OS? I have firewall loaded but not active
```
$ systemctl status firewalld
● firewalld.service - firewalld - dynamic firewall daemon
   Loaded: loaded (/usr/lib/systemd/system/firewalld.service; disabled; vendor p
   Active: inactive (dead)
```

**Comment by oconnor663** [comment]
`/run/user/0/...`

That seems like a red flag to me. `0` is the root user. I'd expect something like `/run/user/1000` for a regular user. Do you know how you might've ended up with root's value of `XDG_RUNTIME_DIR`?

**Comment by RobbiNespu** [comment]
@oconnor663 I dont know.. but yes, user/0/ is root. I solved this problem by 
`$ sudo dnf remove keybase`
then log-out from my Fedora and login back
`$ sudo dnf remove keybase`
`$ run_keybase`

and now it worked
