### ISSUE TITLE
Private folders not opening from Widget / App

### ISSUE THREAD

**Issue by jtsmith0101** [keybase/client#4843]
Just installed the update, restarted and tested the newest feature.... from the "open" link in the folder summary view, or from within the target private share I'm looking at, I'm unable to open folders.

I am able to open folders from navigating to the folder from within the Windows Explorer.

my log id: deee6975ad599fd61da5301c

**Comment by maxtaco** [comment]
cc: @zanderz and @taruti

**Comment by jtsmith0101** [comment]
Just installed update in Linux and it works as advertised.

**Comment by jtsmith0101** [comment]
this can be closed
