### ISSUE TITLE
Difficulty logging into Windows Desktop Client

### ISSUE THREAD

**Issue by averagejoey2000** [keybase/client#4844]
I have 2 computers with keybase installed, and after installng the new update on the second computer, I can't log in. I get ERROR: No auth system available (100)
The password I'm using works for keybase.io though.

my log id: 8524cd0e98cc74647d661f1c

**Comment by maxtaco** [comment]
Can you upgrade to the most recent client?  That should fix it for you. LMK if not.

**Comment by averagejoey2000** [comment]
Fixed
