### ISSUE TITLE
Can't login on Windows 10

### ISSUE THREAD

**Issue by benpollinger** [keybase/client#4852]
Keybase GUI Version: 1.0.18-20161107205110+a86cda8

Hello, I'm getting this error:

> There was en error provisioning
> Unknown error: Bad key family: InsertServerEldestKey found a non-matching eldest key

I can log into the keybase website but I can't do anything until I sign my public key, which is why I'm trying to use the Windows app!

**Comment by zanderz** [comment]
Can you open Keybase Shell and perform `keybase log send` and post the log ID? Thanks.

**Comment by benpollinger** [comment]
Hello, thanks for the quick reply, it's:
 6c19499b5a53637fcef4b61c

**Comment by maxtaco** [comment]
@oconnor663 can you take a look? Repro with `keybase id benpollinger`

**Comment by oconnor663** [comment]
Hi Ben, it looks like you're in a tricky state:

- You've uploaded a PGP public key that does not have an identity in it of the form `benpollinger@keybase.io`, _and_
- You haven't made any signatures with it.

It hasn't been possible to get into that state in a long time, but it looks like you uploaded your key back in 2014! I think the easiest thing to do at this point will be to reset your account using the website. Then you should be able to log in with the desktop client and re-select your PGP key on the Keybase command line with `keybase pgp select`.

**Comment by oconnor663** [comment]
Here's the control for doing that:

![image](https://cloud.githubusercontent.com/assets/860932/20321497/a4f0ce9c-ab43-11e6-8100-f43929e3ba74.png)

**Comment by benpollinger** [comment]
OK, I see. I created my account in 2014 but couldn't get my head round the linux process at the time, so forgot about it. Now back to try the Windows client out (don't think there was one then).

I've created a new key in the browser and logged in from the Windows client. All looks good!

Thanks again for your help everyone.
