### ISSUE TITLE
Can't verify myself on Facebook

### ISSUE THREAD

**Issue by hwkr** [keybase/client#4883]
Facebook verification fails for me. Note: I did just set it up today. Does it take time to propogate?

```
$ keybase id hwkr
▶ INFO Identifying hwkr
✔ public key fingerprint: 8B36 5C76 DE77 F7CE F270 A4B9 6305 64E9 0758 21B8
✔ "hwkr" on github: https://gist.github.com/81f55f3aa5a10a06f7aa671b1a031aea [cached 2016-11-17 10:09:08 PST]
✔ "bnhwkr" on twitter: https://twitter.com/bnhwkr/status/779460944883613696 [cached 2016-11-17 10:09:07 PST]
▶ WARNING | Check status (uid=b07c62a582466aeecf83663704dfa719, seq=17, link=9c7577ea63de78fb80612ededbfd43b90f0e6634e2cde93500fb1a6385cdc868) failed with error: Couldn't find username href. (code=106)
✖ "bnhwkr" on facebook failed: Couldn't find username href. (code=106)
```

You can find the Facebook verification post [here](https://www.facebook.com/bnhwkr/posts/10211422463302533).

my log id: 9b34c408eb35ca4fb4e79d1c

**Comment by strib** [comment]
@oconnor663

**Comment by maxtaco** [comment]
Did you install via brew?  The brew version might be out-of-date...

**Comment by oconnor663** [comment]
`Couldn't find username href` is the error than our first version of Facebook support ran into for people with the "don't allow search engines to index my profile" Facebook privacy setting turned on. It should be fixed in our latest public release though. I think you can force an update with this command?

    /Applications/Keybase.app/Contents/SharedSupport/bin/updater check

Does that fix it?

**Comment by hwkr** [comment]
Fixed it! Thank you!

**Comment by rspeed** [comment]
There's something odd going on with [the releases page](https://github.com/keybase/client/releases) which may be directly contributing to this issue. It shows 1.0.18 as the latest release, which is also the version Homebrew installs, but the actual downloads attached to that release are for 1.1.45 and 1.1.46. It appears that this is a side-effect of there not being any tags in the repository… which is a serious issue in itself.

**Comment by cjb** [comment]
@rspeed We don't regularly make releases through GitHub, or encourage people to use Homebrew for Keybase.  The download at https://keybase.io/download will keep itself up to date.

**Comment by rspeed** [comment]
1. That's the GUI version, which is *extremely* bloated and doesn't provide a CLI version that follows Unix norms.
1. According to the Finder info, that's still version 1.0.18.
1. As I just pointed out, there are updated versions of the CLI version distributed through Github, but they're not being properly tagged.

Whatever is going on, this is a *huge* mess.
