### ISSUE TITLE
Fuse Install Error, KextManager failed to load with status: -603946985

### ISSUE THREAD

**Issue by itys** [keybase/client#4890]
[write something useful and descriptive here]
*rubs lucky rabbitsfoot*

On first run the attached error displayed announcing that FUSE failed to install: 
Fuse: Install, Install Error: KextManager failed to load with status: -603946985, Not Installed, Bundle Version: 3.5.2

Mount directory: Unknown, 
KBFS: Unknown, 
CLI: Unknown, 

The interface worked fine but most of the user fields aside from username weren't populated. Clicking through public/private folders doesn't do anything

Stopping the app (Command-Q) left the background process and bar agent running (intentional I'm assuming) so I quit through the bar menu and thinking perhaps I missed step 1.5 between Buy an Apple Computer and Download Keybase.dmg so I manually installed FUSE for macOS 3.5.3 from https://osxfuse.github.io/ 

Restarting the Keybase app, no error this time but also nothing but my local info populated. My list is however available.  The shade-out graphic on Open Folder animates but doesn't open. 

Perhaps notable in this error log is: Can't set GPG_TTY; discover failed 
MacGPG2 is installed and the gpg-agent status is running and available, however echo $GPG_TTY via the CLI gives null output. 

Attempts to read the /keybase filesystem fail:
cd: permission denied: /keybase
cat: /keybase/public/chris/plan.txt: Permission denied

I have a separate $GOPATH defined, any use of that variable? 

When I have time I'll troubleshoot a bit more, feel free to send information requests. 

OS: 10.11.6 (15G31) El Capitan
GPG: gpg (GnuPG/MacGPG2) 2.0.30
libgcrypt 1.6.6
brew: Homebrew 1.0.7
Attached: First run error log
[b64c0fd62c673f020788361c.txt](https://github.com/keybase/client/files/598370/b64c0fd62c673f020788361c.txt)

my log id: b64c0fd62c673f020788361c

**Comment by cjb** [comment]
CC @gabriel

**Comment by gabriel** [comment]
Whats the output of `keybase fuse status`?

**Comment by itys** [comment]
$ keybase fuse status
{
  "version": "3.5.2",
  "bundleVersion": "",
  "kextID": "com.github.kbfuse.filesystems.kbfuse",
  "path": "/Library/Filesystems/kbfuse.fs",
  "kextStarted": false,
  "installStatus": 4,
  "installAction": 0,
  "mountInfos": [],
  "status": {
    "code": 0,
    "name": "OK",
    "desc": "OK",
    "fields": null
  }

**Comment by gabriel** [comment]
What happens if you do:
```
/Library/Filesystems/kbfuse.fs/Contents/Resources/load_kbfuse
echo $?
```

**Comment by itys** [comment]
$ /Library/Filesystems/kbfuse.fs/Contents/Resources/load_kbfuse
<blank> 
$ echo $?
255

**Comment by gabriel** [comment]
What is the output of:

```
ls -al /Library/Filesystems/kbfuse.fs/Contents/Resources/load_kbfuse
```

**Comment by itys** [comment]
```
$ ls -al /Library/Filesystems/kbfuse.fs/Contents/Resources/load_kbfuse
-rwsr-xr-x@ 1 root  wheel  26680 Nov 16 13:13 /Library/Filesystems/kbfuse.fs/Contents/Resources/load_kbfuse
```

**Comment by gabriel** [comment]
What is the output of:
```
kextstat | grep fuse
```

**Comment by itys** [comment]
`$ kextstat | grep fuse

`

**Comment by gabriel** [comment]
What happens if you remove `/Library/Filesystems/kbfuse.fs` directory. And then restart the app (do `pkill Keybase` and then open /Applications/Keybase.app`).

**Comment by itys** [comment]
[b64c0fd62c673f020788361c-1.txt](https://github.com/keybase/client/files/598516/b64c0fd62c673f020788361c-1.txt)

**Comment by itys** [comment]
Option to ignore or quit. Ignore. KBFS Not Found Shaded box at top. Local device shows under Devices (no change since before the removal of the directory, paper key shows as well)

**Comment by itys** [comment]
Console output for searches: 
11/17/16 3:35:00.625 PM com.apple.xpc.launchd[1]: (keybase.kbfs[85584]) Service exited with abnormal code: 2

**Comment by gabriel** [comment]
hmm... yeah weird the kext isn't loading... can you post another `keybase log send` ID?

what happens if you reboot?

**Comment by itys** [comment]
61e3a2206454c23f37f48f1c

Will submit a second after a reboot here in a few.

**Comment by itys** [comment]
"Did you try turning it off and back on again" fixed it. 
Two more log IDs for you: 
4f9d02b718631d40103cdc1c right after the reboot
da9937a8e064e7158b76241c after successful upload of [plan.txt](https://mjharmon.keybase.pub/plan.txt) 

Quite awesome indeed. 

Issue resolved, no personal priority on the dangling "what happened?" question as known workaround exists - reboot.

**Comment by gabriel** [comment]
I should have asked you to look in /var/system.log about any error messages...

Do you see anything in there that looks interesting around 1:19pm PST?
(when you ran `/Library/Filesystems/kbfuse.fs/Contents/Resources/load_kbfuse`)

**Comment by gabriel** [comment]
Actually gonna keep open cause at some point would like to figure out why this happened (was it a fuse bug or OS bug or...)

**Comment by itys** [comment]
This is about the time of the initial install

```
Nov 17 15:36:26 neutron kernel[0]: kbfuse: Failed to register major device number
Nov 17 15:36:26 neutron kernel[0]: Kext com.github.kbfuse.filesystems.kbfuse start failed (result 0x5).
Nov 17 15:36:26 neutron kernel[0]: Kext com.github.kbfuse.filesystems.kbfuse failed to load (0xdc008017).
Nov 17 15:36:26 neutron kernel[0]: Failed to load kext com.github.kbfuse.filesystems.kbfuse (error 0xdc008017).
Nov 17 15:36:26 neutron com.apple.kextd[53]: Failed to load /Library/Filesystems/kbfuse.fs/Contents/Extensions/10.11/kbfuse.kext - (libkern/kext) kext (kmod) start/stop routine failed.
```
... repeated until

```
Nov 17 16:10:47 neutron kernel[0]: Failed to load kext com.github.kbfuse.filesystems.kbfuse (error 0xdc008017).
Nov 17 16:10:47 neutron com.apple.kextd[53]: Failed to load /Library/Filesystems/kbfuse.fs/Contents/Extensions/10.11/kbfuse.kext - (libkern/kext) kext (kmod) start/stop routine failed.
```

then the reboot

```
Nov 17 16:13:10 neutron kernel[0]: kbfuse: starting (3.5.2, Sep 27 2016, 10:56:03)
```

(nothing since)

**Comment by gabriel** [comment]
Yeah this looks like an issue with macOS and Fuse re: device slots as referenced here:
https://github.com/osxfuse/osxfuse/issues/254

Thanks for the bug report, sorry you hit something strange :)
