### ISSUE TITLE
Client timed out on Mac

### ISSUE THREAD

**Issue by tedpelas** [keybase/client#4915]
[write something useful and descriptive here]

my log id: abf95086f3790595c14e8c1c

**Comment by strib** [comment]
Hi @tedpelas -- I see the timeouts in the log, and nothing much looks out of the ordinary except that some network calls to our servers were taking a long time. Is there any chance your CPU was overloaded at the time, or that your network connection was spotty?

**Comment by tedpelas** [comment]
Hi @strib -- You are correct, my CPU was overloaded during that time and my laptop came back from hibernation. In that case I think we can close this case :)

**Comment by strib** [comment]
Ok, thanks for the info.  We're working on making it less fragile to CPU and network disturbances.  Thanks for the report.
