### ISSUE TITLE
"ERROR Server claimed not to have this user in its tree (we had v=5)" when I try to login

### ISSUE THREAD

**Issue by sanity** [keybase/client#4944]
I tried to login using a (probably) older version of the keybase mac client.  I got the error above.  I then installed the latest version of keybase and got this:

> There was an error provisioning

> Unknown error: Server claimed not to have this user in its tree (we had v=5)

my log id: 4a472e8c64be32148ab5a01c

**Comment by maxtaco** [comment]
Try a `keybase db nuke`?

**Comment by sanity** [comment]
That worked, thanks!
