### ISSUE TITLE
Changed proofs message appears blank

### ISSUE THREAD

**Issue by stephenyeargin** [keybase/client#4954]
![screen shot 2016-11-28 at 9 05 23 am](https://cloud.githubusercontent.com/assets/80459/20673209/d85e16da-b549-11e6-88f0-a510b4db66bf.png)

my log id: b8e12e1e7c803ab46a13261c

The system prompted me to submit a bug report. This was the only screen out of the ordinary (never loads)

**Comment by maxtaco** [comment]
Thanks @stephenyeargin. @chrisnojima, I'm actually able to repro this issue right now, since @jinyangli's server at NYU isn't replying to HTTP requests and is timing out in a pretty bad way.

**Comment by chrisnojima** [comment]
We have a fix that's been merged in. Should be in the next build. Thanks!
