### ISSUE TITLE
ERROR bad signature: Unknown signature subpacket: 33 (error 1002)

### ISSUE THREAD

**Issue by kierdavis** [keybase/client#5023]
When trying to log in from the command line using `keybase login`, I encounter this error message after selecting option 1:

```
▶ ERROR bad signature: Unknown signature subpacket: 33 (error 1002)
```

Full output:

```
$ keybase login
Your keybase username or email address: kierdavis@gmail.com
Please enter the Keybase passphrase for kierdavis@gmail.com (12+ characters): 
In order to authorize this installation, keybase needs to sign this installation
with your GPG secret key 8139C5FCEDA73ABF.

You have two options.

(1) Keybase can use GPG commands to sign the installation.

(2) Keybase can export your secret key from GPG and save it to keybase's local encrypted
    keyring. This way, it can be used in 'keybase pgp sign' and 'keybase pgp decrypt' 
    going forward.
Which do you prefer?: 1
Enter a public name for this device: coloris
▶ ERROR bad signature: Unknown signature subpacket: 33 (error 1002)
```

The login works if I select option 2, though I'd still be interested to know why option 1 didn't work.

my log id: 09d13b105bc30f885b06581c

keybase version: 1.0.18
Go version: 1.7

**Comment by maxtaco** [comment]
Many many dupes on this one.

**Comment by kierdavis** [comment]
Hmm, you're right: #4947, [keybase-issues#2668](https://github.com/keybase/keybase-issues/issues/2668), [keybase-issues#111](https://github.com/keybase/keybase-issues/issues/111). Though I looked quite hard for dupes, but obviously not hard enough.

**Comment by maxtaco** [comment]
I hope to get to this today or tomorrow.
