### ISSUE TITLE
Uploading iso fails on Windows

### ISSUE THREAD

**Issue by coldwaterq** [keybase/client#5030]
I was trying to upload tails-i386-2.7.1.iso and it gets about half way and then fails. with:
"Error 0x800703E3: The I/O operation has been aborted because of either a thread exit or an application request"

my log id: 2050a7d2a5785c11f5f0041c

Edit: This happened while trying to put it in my private folder, and public folder.

**Comment by strib** [comment]
Thanks, looks like you're hitting a well-known timeout problem with big files.  Sorry for the inconvenience.  We're working on a solution.

**Comment by strib** [comment]
Version 1.0.20 has architectural changes that should greatly improve the large write experience.  If you're still seeing problems, please open a new issue.
