### ISSUE TITLE
KBFS not available

### ISSUE THREAD

**Issue by Darunada** [keybase/client#5050]
My K:\ drive appears in explorer but attempting to access it says it's unavailable.  

```
[Window Title]
Location is not available

[Content]
K:\ is unavailable. If the location is on this PC, make sure the device or drive is connected or the disc is inserted, and then try again. If the location is on a network, make sure you’re connected to the network or Internet, and then try again. If the location still can’t be found, it might have been moved or deleted.

[OK]
```

It used to work, but suddenly has stopped.

I uninstalled the windows client and reinstalled the newest version.  Starting the keybase desktop app the window opens an error message

```
KBFS client wasn't found
Error: KBFS client wasn't found at t.Error (native) at new t 
(file:///C:/Users/.../AppData/Roaming/Keybase/Gui/resources/app/desktop/dist/index.bundle.js:11:5254) at a 
(file:///C:/Users/.../AppData/Roaming/Keybase/Gui/resources/app/desktop/dist/index.bundle.js:11:4885) at o 
(file:///C:/Users/.../AppData/Roaming/Keybase/Gui/resources/app/desktop/dist/index.bundle.js:11:4810) at 
file:///C:/Users/.../AppData/Roaming/Keybase/Gui/resources/app/desktop/dist/index.bundle.js:5:23565 at 
file:///C:/Users/.../AppData/Roaming/Keybase/Gui/resources/app/desktop/dist/index.bundle.js:53:23817 at e.t.Deferrals.e._call 
(file:///C:/Users/.../AppData/Roaming/Keybase/Gui/resources/app/desktop/dist/index.bundle.js:35:1893) at 
file:///C:/Users/.../AppData/Roaming/Keybase/Gui/resources/app/desktop/dist/index.bundle.js:35:2044 at c 
(file:///C:/Users/.../AppData/Roaming/Keybase/Gui/resources/app/desktop/dist/index.bundle.js:35:1671) at e.t.Deferrals.e._fulfill 
(file:///C:/Users/.../AppData/Roaming/Keybase/Gui/resources/app/desktop/dist/index.bundle.js:35:2003)
```

my log id: 1a072efb9d1b82002405bd1c

**Comment by zanderz** [comment]
Hi, I see a failed installation in your logs at one point due to vcredist_2015_x86, which is odd because that shouldn't be necessary on your system. Also, there is a `c:\bin\keybase.exe` running, of an older version not matching the other .exe files, which is not a target directory we use for that file. I would recommend removing this executable and rebooting, and if the right service still isn't running (`C:\\Users\\Lea\\AppData\\Roaming\\Keybase\\keybase.exe`), try uninstalling and then installing again.

**Comment by Darunada** [comment]
Thanks that did it.  I don't know why that exe was in c:/bin but I bet I felt real slick when I put it there.
