### ISSUE TITLE
KBFS client not found when starting key base app after reinstall

### ISSUE THREAD

**Issue by sean-brandt** [keybase/client#5070]
After reinstalling, key base unable to find KBFS client. /keybase is giving a 'permission denied'

**Comment by strib** [comment]
Can you please do a `keybase log send` and report the log ID here?

**Comment by sean-brandt** [comment]
Log id: 7055c09ba006a0ec12ed911c

**Comment by strib** [comment]
cc @patrickxb 

It seems that you haven't unlocked your local device key with your passphrase yet.  I'm not sure if this is a bug on our end since I don't know what's supposed to happen on macOS after a "reinstall".  Does the Keybase GUI give you a login option?  Or maybe you can try `keybase logout` and `keybase login`?

**Comment by sean-brandt** [comment]
Running through a key base logout/login appears to have resolved the issue.

**Comment by sean-brandt** [comment]
Still seeing this error:

Error: KBFS client wasn't found at t.Error (native) at new t (file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/index.bundle.js:11:5254) at a (file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/index.bundle.js:11:4885) at o (file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/index.bundle.js:11:4810) at file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/index.bundle.js:5:23565 at file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/index.bundle.js:53:23817 at e.t.Deferrals.e._call (file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/index.bundle.js:35:1893) at file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/index.bundle.js:35:2044 at c (file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/index.bundle.js:35:1671) at e.t.Deferrals.e._fulfill (file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/index.bundle.js:35:2003)


Also of note, the perms on the /keybase folder aren't correct:

ls -ld /keybase               
drw-------  2 sean  staff  68 Dec 11 12:44 /keybase

**Comment by strib** [comment]
cc: @cjb @gabriel 

The permissions are intentionally set that way while KBFS is not running, to prevent you from accidentally writing to that folder.  So something is keeping it from starting up.  Anyone have any ideas?  I couldn't find anything interesting in the logdump above (f61c49b28e2baf3e8f24611c) but not sure what to look for.

**Comment by sean-brandt** [comment]
I deprovisioned this particular machine, uninstalled keybase, wiped all traces I could find on the system and then downloaded a fresh copy. On startup of the app, after being asked to allow the privileged helper file to be installed, I immediately get an error about the KBFS client not being found.

log id: 68014acf26c11a46bd7eb91c

Image of screen: 

![keybase](https://cloud.githubusercontent.com/assets/4678/21107765/d574db58-c060-11e6-86cc-b17642d38689.png)

**Comment by sean-brandt** [comment]
After login and rekey, it appears that kbfs is now attached properly to this machine. It still has the wrong quota/disk usage, but I've got another issue opened on this. 

This may just be user error and poor UI, or there was something under the covers that needed a full reset, I'm uncertain.

**Comment by gabriel** [comment]
This is a known issue... fix is [here](https://github.com/keybase/client/pull/5051). Might be a few days before we do a release though.

**Comment by sean-brandt** [comment]
Thanks, will watch for the next release.

**Comment by gabriel** [comment]
Gonna leave this open till the fix goes live.
