### ISSUE TITLE
Can not log in keybase.

### ISSUE THREAD

**Issue by DoITCreative** [keybase/client#5074]
Hello, I created account on keybase.io, then to create a key I must be logged in.
I successfully logged in, but when I were specifying device name, I made typo.
So I decided to do "keybase deprovision".
Now when I trying to log in, keybase gives error:
▶ WARNING Error running Bug 3964 repairman: lksec load: no device id set, thus can't fetch server half
▶ WARNING In Bug 3964 repair: lksec load: no device id set, thus can't fetch server half
▶ ERROR eldest called on user with existing eldest KID
How to solve it?

my log id: 84911bc15eab0e802f637c1c

**Comment by cjb** [comment]
Thanks for the report, CC @maxtaco

**Comment by maxtaco** [comment]
My guess is that deprovisioning killed this user's last key

@oconnor663 can you look into this?

**Comment by oconnor663** [comment]
Yes, that's what's happened. https://keybase.io/doitcreative/sigchain

@DoITCreative I'm sorry for not having a better error message for you there. (I've filed an [internal issue](https://keybase.atlassian.net/browse/CORE-4228) for us.) What's happening is that there are no keys on your account at all, and because your account hasn't been "hard reset" you're getting an error when your new login attempts to add one. What you need to do is go on the website and do the reset here:

![image](https://cloud.githubusercontent.com/assets/860932/21108252/9f538f68-c062-11e6-92cf-d5e2b5378890.png)

That would normally force you to redo all the social proofs you've done, which is one reason we don't do it automatically, but if your case (if I found the right account above) it looks like there's nothing to redo?

**Comment by DoITCreative** [comment]
Oconnor663, thanks for review, but I do not have option "reset my keys & start from scratch", because I have not added any keys yet. And to add them I must be logged in.

**Comment by DoITCreative** [comment]
Also, when I tryed curl method to add key, it gives following error:
Code: 908
Name: KEY_NEED_REVOKE
Description: You need to delete your active key before uploading a new one

**Comment by DoITCreative** [comment]
But there is no option to delete any keys.

**Comment by DoITCreative** [comment]
![screenshot at 18-46-37](https://cloud.githubusercontent.com/assets/15136796/21110067/11d943be-c09c-11e6-9746-830a3b5a2d26.png)

**Comment by oconnor663** [comment]
Oh no, you're totally right, if you haven't uploaded a PGP key before then you're in a state where "reset" doesn't show up, and it becomes unfixable. I can reset your account for you manually. I'll contact you over email.

**Comment by DoITCreative** [comment]
Ok, thanks ;-)

**Comment by DoITCreative** [comment]
It's working now, thanks, oconnor663!

**Comment by kevin3-black** [comment]
@oconnor663 I'm in the exact same situation, I revoked my only key in an attempt to rename my device and adding a new PGP key doesn't seem to work. Unless there's now another way to fix this that I'm missing, could you manually reset my account?

[keybase.io/kevin3black](http://keybase.io/kevin3black)

**Comment by oconnor663** [comment]
@kevin3-black done, apologies for the wait.

**Comment by fellowish** [comment]
Hey, connor. I'm in the exact same situation as these two... Unfortunately, there's no way back into the account. :\

keybase.io/oldrego

If you could help with this, I'd be thankful.

**Comment by Oldrego** [comment]
Heyya, Connor. I'm actually in the same boat as the people before me, with no access to my account. :\

keybase.io/oldrego

If you could help reset it, I'd be much obliged.

**Comment by oconnor663** [comment]
@Oldrego I'll email you on the side.

**Comment by ChristopherClarke** [comment]
@oconnor663 I've managed to do the same thing as all the others before me. No PGP and no keys remaining. Could you help me out?

keybase.io/chrisclarke

Thanks in advance

**Comment by efritzsche** [comment]
@oconnor663 I also locked myself out while playing around and setting up my account today.

https://keybase.io/efritzsche

Can you do a reset? I would appreciate it.

**Comment by oconnor663** [comment]
@efritzsche done.

**Comment by efritzsche** [comment]
Everything is working now, thank you very much :)
