### ISSUE TITLE
Non-escaped characters

### ISSUE THREAD

**Issue by amagnus** [keybase/client#5076]
Hello,

I wanted to report this simple issue: here is what happens when the message I'm encrypting contains an exclamation point:

```
keybase encrypt valentin -m "what's going on?!"
-bash: !": event not found
```

Should we escape it instead?

I'm running version 1.0.18-20161116190722+95f8303.

**Comment by BrandonIngalls** [comment]
This is not a Keybase issue, typically `!` needs to be quoted.

From the bash manpage
> When the command history expansion facilities are being used (see HISTORY EXPANSION below), the history expansion character, usually !, must be quoted to prevent  history  expan‐
       sion.

Example
```bash
bash-4.2$ history
    1  history
    2  echo 'command1'
    3  echo 'command2'
    4  echo 'command1'
    5  history

bash-4.2$ !3
echo 'command2'
command2

bash-4.2$ echo "Example !2"
echo "Example echo 'command1'"
Example echo 'command1'

bash-4.2$ echo "Example2 $(!2)"
echo "Example2 $(echo 'command1')"
Example2 command1
```
