### ISSUE TITLE
Can't access shared folder

### ISSUE THREAD

**Issue by danilotsr** [keybase/client#5085]
Keybase GUI Version: 1.0.18-20161116190722+95f8303

Can't access shared folder (with 3 users), even though it shows up in the tree directory for a few seconds and then disappears: `danilotsr,photobologic,sophied`

**Comment by sdawson** [comment]
As an addition to the issue above, I'm the person who created the folder originally via the Keybase GUI (Version 1.0.18-20161116190722+95f8303 as well), and I'm able to see and open the directory normally from my machine. I'm using a Mac running OSX Version 10.11.6 (15G1108).

**Comment by strib** [comment]
@danilotsr can you please go a `keybase log send`?

And when you say it "shows up in the tree directory", what do you mean exactly?  `ls /keybase/private`?  Or something in the Keybase GUI?

**Comment by danilotsr** [comment]
> can you please do a keybase log send?
@strib, sure, my log id was `acb28582535d187ed030981c`

> And when you say it "shows up in the tree directory", what do you mean exactly?
I could see in the Keybase GUI and in Mac OS's Finder, but I could not see in via `ls /keybase/private`

**Comment by strib** [comment]
@danilotsr thanks.  It looks like the Keybase service is complaining about not being able to write to its database because the local disk partition is full.  Does that sound possible?

**Comment by danilotsr** [comment]
@strib in fact I ran into disk utilization issues last week, but I have released 75GB since then. I restarted Keybase and it was able to write to the local disk now, so this is resolved. Thanks for the help.

**Comment by strib** [comment]
Hmm, ok, thanks.  @maxtaco it seems the keybase service or leveldb might be caching the out-of-disk error?

**Comment by maxtaco** [comment]
I don't see immediately where or why. Any idea which RPC is sending back a cached value?
