### ISSUE TITLE
Stuck at "set a public name for this device"

### ISSUE THREAD

**Issue by etherReal** [keybase/client#5087]
Keybase GUI Version: 1.0.18-20161212170620+a59ea83
OS: Xubuntu 16:06

Both "Continue" and "Back" buttons have no effect.

**Comment by maxtaco** [comment]
Please do a `keybase log send`?

**Comment by etherReal** [comment]
log sent.  
also when I click the tray icon, the pop up tells me that "you are logged out of Keybase! (Log in)" when I click (Log in) it leads me to the set pub name for device page.

**Comment by maxtaco** [comment]
log ID?

**Comment by etherReal** [comment]
67ac2cf60edc644be3f98b1c

Sorry thought that had been piped too :)

**Comment by etherReal** [comment]
Don't know what you did but today it just worked

:grinning:

**Comment by etherReal** [comment]
Closed this issue by mistake when clicking the tray menu showed me as logged in.

In that popup I can see my private and public folders but the  "folder" and "users" icons at centre top both lead to  "set a public name for this device" where once more UI is stuck.

**Comment by cjb** [comment]
@maxtaco we've got a log ID now: 67ac2cf60edc644be3f98b1c

**Comment by etherReal** [comment]
:tada:  Woot now it really is fixed!  
If you did something it was the right thing.  If not then gremlins.

THANKS!  

P.S. the overall Uex is LUSH :+1:
