### ISSUE TITLE
Proxy: Updater: Unknown, Install Error: Task timed out

### ISSUE THREAD

**Issue by azizur** [keybase/client#5088]
Every time my mac restart, I am getting the following error. Only thing I can think of is proxy. **App should work with my system proxy settings.**

Keybase GUI Version: 1.0.18-20161116190722+95f8303

```
Task timed out: /Applications/Keybase.app/Contents/SharedSupport/bin/keybase -d --log-format=file install --format=json --components=updater --timeout=90s

Installer: 1.1.44
Privileged Helper: Installed, Bundle Version: 1.0.29, Version: 1.0.29
Updater: Unknown, Install Error: Task timed out: /Applications/Keybase.app/Contents/SharedSupport/bin/keybase -d --log-format=file install --format=json --components=updater --timeout=90s
Service: Unknown, 
Fuse: Unknown, 
Mount directory: Unknown, 
KBFS: Unknown, 
CLI: Unknown, 

Log:
Version: 1.1.44
Installables: (
    "Privileged Helper",
    Updater,
    Service,
    Fuse,
    "Mount directory",
    KBFS,
    CLI
)
Install: Privileged Helper
Connecting to keybase.Helper (privileged=1)
Connected
Helper version: {
    build = 2;
    version = "1.0.29";
}
Helper version: {
    build = 2;
    version = "1.0.29";
}
Install: Updater
Task: /Applications/Keybase.app/Contents/SharedSupport/bin/keybase -d --log-format=file install --format=json --components=updater --timeout=90s
Task error: Error Domain=Keybase Code=-210 "Task timed out: /Applications/Keybase.app/Contents/SharedSupport/bin/keybase -d --log-format=file install --format=json --components=updater --timeout=90s" UserInfo={NSLocalizedDescription=Task timed out: /Applications/Keybase.app/Contents/SharedSupport/bin/keybase -d --log-format=file install --format=json --components=updater --timeout=90s, NSLocalizedRecoveryOptions=(
    OK
)}
Task EOF
Already completed, skipping (completion)
Install complete
Privileged Helper: Installed, Bundle Version: 1.0.29
Version: 1.0.29
Updater: Install Error: Task timed out: /Applications/Keybase.app/Contents/SharedSupport/bin/keybase -d --log-format=file install --format=json --components=updater --timeout=90s
```

**Comment by cjb** [comment]
CC @gabriel

**Comment by gabriel** [comment]
@azizur can you do a `/Applications/Keybase.app/Contents/SharedSupport/bin/keybase log send` and post the ID?

**Comment by azizur** [comment]
@gabriel 

my log id: f0245903d0d17a276f8bbb1c

Just a privacy concern from me, The send command does come with a warning, but it should let me see what it is actually sending before sending it out to a server I have no idea where it's going.

When I looked at the `Keybase.app.log` file I am a bit concern that it logs personal details. I.e.: search queries. These logs file are readable to by any one who has access to the system. Logging search queries/results like this is an invasion of privacy. Anyone who has access to the system is able to create a picture of who else you have been talking to or looking up.

**Comment by azizur** [comment]
@cjb and @gabriel any update on this? Keybase client hangs my mac from startup. I think the timeout needs to be even shorter to fail fast. I spend about 5mins waiting for it error.

**Comment by gabriel** [comment]
Sorry for the late reply.

When you say it hangs your mac on startup, your whole computer is frozen or just the Keybase app? If you remove Keybase from startup (via System Preferences, Users & Groups, Login Items), does your system still exhibit problems on startup?

Can you try a very recent beta build:
https://prerelease.keybase.io/darwin/Keybase-1.0.18-20161227210312%2B1d6f524.dmg

What is the output of this:
```
/Applications/Keybase.app/Contents/SharedSupport/bin/keybase -d --log-format=file install --format=json --components=updater --timeout=10s
```

Do you see anything in /var/log/system.log about your clock time being adjusted?

**Comment by azizur** [comment]
@gabriel FYI I have uninstalled the app and issue have gone away.

**Comment by gabriel** [comment]
Is this still an issue with latest version? If so please re-open.
