### ISSUE TITLE
KBFS on Headless Ubuntu server - Permission denied

### ISSUE THREAD

**Issue by greyhoundforty** [keybase/client#5089]
I installed Keybase and KBFS on my headless Ubuntu server. I logged in successfully and now see a /keybase/public/<my-id> folder but I cannot copy any files to it. I tried using `echo 'MY_KEYBASE_PASSWORD' | keybase unlock --stdin` as suggested in another thread but although the console does not log any errors I still get permission denied when trying to copy files to my public folder. Oddly though I can use `echo >` to create a new file without any permission issues. 

```
$ echo "test" > /keybase/public/greyhoundforty/test.txt
$
```

my log id: 7bca343bfc104a767db9301c

**Comment by strib** [comment]
Hi @greyhoundforty, it looks like your new device hasn't yet been given access to that device by one of your older devices.  On a system with a GUI, you would have gotten a dialogue explaining this, but we don't have any way to tell you that on a headless system.  Please try turning on your `macbook` device and running Keybase, and after a few minutes it should grant access to your new device.

**Comment by greyhoundforty** [comment]
Keybase has been running on my Macbook for about an hour now and I've used `echo 'MY_KEYBASE_PASSWORD' | keybase unlock --stdin` a few times. Nothing has popped up so far in the GUI. I will keep an eye out and try to see if I can locate a more concrete error.

**Comment by strib** [comment]
Can you do a new log send from both devices and report the IDs here?

**Comment by greyhoundforty** [comment]
BalorBase (Headless server) -Log ID - 756d7ef8e111fad561b3cb1c
Tycho (Macbook) - Log ID - 19c78a5d707640d67741ba1c

- Thanks

**Comment by strib** [comment]
Thanks.  And is `/keybase/public/greyhoundforty` still the folder you're having trouble with?  I don't see any issues with it in the current `BalorBase` log.  I only see one access to it, trying to look up a filename that doesn't exist in the folder.  I don't see any write/copy attempts.  Can you please clarify what exactly is failing for you now?

**Comment by greyhoundforty** [comment]
Weird, it seems that `sudo` in front of the `cp` command was the issue. The file I wanted to copy to `/keybase/public/greyhoundforty` was owned by root so I used sudo. I dropped the sudo part of the copy command and it seems to be working. Sorry for the bother.

**Comment by strib** [comment]
Ah right.  `root` doesn't have permission to access your KBFS files, only the user running keybase does.
