### ISSUE TITLE
There was an error provisioning

### ISSUE THREAD

**Issue by joshuad31** [keybase/client#5113]
Installation failed log file attached

[Keybase_20161214184224.txt](https://github.com/keybase/client/files/653513/Keybase_20161214184224.txt)
![untitled](https://cloud.githubusercontent.com/assets/5976059/21207459/c665ae3e-c22d-11e6-80bd-fe273064a965.jpg)

**Comment by joshuad31** [comment]
ok so installing this KB does fix this problem but then afterwards I have another problem.

There was an error provisioning
Unknown error: no auth system available; consider upgrading your client if it's old

There was an error provisioning
unknown error: login via email address without pdpka_login=true flag is deprecated

![2016-12-14 23_25_22-keybase](https://cloud.githubusercontent.com/assets/5976059/21212790/6f92301e-c255-11e6-8fb5-72891546daef.jpg)
![untitled2](https://cloud.githubusercontent.com/assets/5976059/21212794/72ef29ba-c255-11e6-87ea-695cc762f0cc.jpg)

**Comment by joshuad31** [comment]
I know that users typically get this type of error if there is any sort of authentication issue however I can log into keybase.io and my password is correct.

My date / time clock is also correct so this is not a timezone / date time issue.

**Comment by maxtaco** [comment]
Is this a very old version of keybase? It sure seems like it

**Comment by zanderz** [comment]
This was the current production build, released Nov 16 (until today's release). If this does not go away after updating to the current release, please perform a `keybase log send` from the Keybase Shell and post the log ID.

**Comment by joshuad31** [comment]
@maxtaco @zanderz Ok I got it to work.  What happened is there was a small popup window I didn't see that requested I reboot my machine.  Because I didn't reboot I was getting this error.  Now it works fine as you can see here:
https://keybase.pub/joshuad31/
