### ISSUE TITLE
Rename device

### ISSUE THREAD

**Issue by thebeastgamer25** [keybase/client#5147]
Hi there! I accidentally named my computer device something I don't want it to be. Is there a way I could rename it?

**Comment by BrandonIngalls** [comment]
You can not rename a device, they are immutable.

You could issue a `keybase deprovision` which will revoke your device named **keybase** and then sign back in using a paperkey.

If you do not have a copy of your `worry farm` paperkey you can use the `keybase paperkey` command before running **deprovision** to generate a new one.

When choosing a device name please note that it is not possible to ever create another device with the same name [keybase/keybase-issues#1952].  So if you name your new device **Desktop** and were to lose access to your device key (hdd dies, reinstall os without backup, etc) you will never be able to add another device named **Desktop**, even if you reset your Keybase account.

**Comment by cjb** [comment]
Thanks for the great reply @BrandonIngalls!

By the way, it's possible to perform these actions from the Devices tab in the GUI instead of the CLI if you prefer.

**Comment by cjb** [comment]
@malgorithms I suppose we might want to offer a Rename Device operation in the GUI (performing a provision followed by rekey and revoke behind the scenes).

**Comment by thebeastgamer25** [comment]
i agree @cjb

**Comment by malgorithms** [comment]
>  I suppose we might want to offer a Rename Device operation in the GUI (performing a provision followed by rekey and revoke behind the scenes).

yeah, agreed. we'd talked about at some point allowing a rename as an explicit sig chain item, which might be better. But I'm not sure.

With this technique (provision then revoke), we'd have to make sure all KBFS rekeying completed before performing the revocation. And would the client be usable in the meantime, with the old key or the new key? There'd be some things to figure out.
