### ISSUE TITLE
Provision after OS re-install fails due to rekey failure

### ISSUE THREAD

**Issue by RubenHoms** [keybase/client#5149]
I've just switched to Arch Linux from Ubuntu and wanted to provision the new install with keybase so I could access my private folder. I've entered my paper key to prove my identity and used my password to login to the GUI client. It just says that the folder needs to be rekeyed and when I enter the paper key (starting with `will chase`)  it pops up with a notification that it is rekeying (all seems well so far!).

However, I've let it run for a few hours and nothing has happened. When I open the folder I get an access denied message and keybase comes up saying the files need to be rekeyed. So it seems I'm stuck in this process. How do I unlock my private folder and rekey successfully? Am I just being impatient or is there something else wrong here?
my log id: 36c9f81142efe650164ebb1c

**Comment by cjb** [comment]
CC @strib

**Comment by strib** [comment]
Hi @RubenHoms.  This is due to a bug we have fixed in `master` that hasn't yet made it to the Linux release yet (keybase/kbfs#587 I think).  It will be in the next update, hopefully tomorrow.  Sorry for the inconvenience!

**Comment by RubenHoms** [comment]
@strib Thanks for the update! Just for my information, how and when do the packages get updated? Is that on a set interval or just whenever a 'release' version is ready? I know it's partly my own fault here for not making a backup before I reinstalled but I kinda need access to the private folder. :joy:

**Comment by cjb** [comment]
@RubenHoms Hi, the new version is released now.  We normally release once every weekday.
