### ISSUE TITLE
Unremovable folder

### ISSUE THREAD

**Issue by samskinnerphd** [keybase/client#5150]
I just downloaded the update to the Keybase app on a macbook running OSX 10.11.6.  As part of that process, Keybase placed a folder "keybase" on my desktop, with two empty folders inside: "public" and "private".  I can neither move the folder around on the desktop (to get it out of the way), nor, more importantly can I delete the folders.  Further, the keybase folder is not recognized when I run an "ls" command in Terminal.

How do I get rid of it?   Thanks,  Sam

my log id: 3db623065b9d52140e7a921c

my log id: 3db623065b9d52140e7a921c

**Comment by strib** [comment]
cc: @gabriel 

This is KBFS (https://keybase.io/docs/kbfs), it comes with Keybase.

I don't know what you mean by "not recognized" by `ls`. Does `cd /keybase/private/samskinnerphd` in the Terminal work for you?

**Comment by samskinnerphd** [comment]
Hi Jeremy,

Thanks for getting back to me!

The keybase download/upgrade placed a folder on my desktop labelled “keybase”.  Inside are two empty folders: “public” and “private”.  Both are empty.

I cannot delete any of the folders, nor can I move the keybase folder to an inconspicuous place on my desktop.  The download came with no documentation suggesting that the folder might have a purpose.  Your link suggests it does.  But the placement on my desktop is very inconvenient, at minimum.

When I type “ls” in terminal, the keybase folder is not listed.  When I try to cd into the folder, I get an error message: “no such file or directory”

If I try moving a file into /keybase/public, as suggested by the link you included, I get a popup message “Copying <filename> to “public””.  The message has persisted for several minutes and I am now unable to open or move the file that is being copied.

Will I need to delete the entire keybase app?  Will even that make this keybase folder disappear?

Thanks, Sam
_________
Sam Skinner, PhD
Roswell, GA  30076

Cell: 678-585-7757
Email: samskinnerphd@gmail.com

**Comment by gabriel** [comment]
In Finder, Preferences if you unselect "Connected servers" the folder won't show up on your desktop.
