### ISSUE TITLE
Cannot Rekey Private Folders

### ISSUE THREAD

**Issue by drohm** [keybase/client#5152]
I reinstalled my OS and added my device back (with a new name) and keybase is telling me to rekey my private folders or I'm at risk of losing the data.  I'm doing what it says but it won't rekey the folders.  This is over the span of a couple days so I'm pretty sure its not time related.

I've read all the docs and help but I'm not sure how to get this fixed.

![keybase-rekey](https://cloud.githubusercontent.com/assets/184959/21296441/af64df98-c539-11e6-9f3f-4d4a7e718f34.png)

![keybase-rekey-2](https://cloud.githubusercontent.com/assets/184959/21296463/4ecc9922-c53a-11e6-8d00-bef79dd2731a.png)

**Comment by cjb** [comment]
Sorry about this. It's a bug at our end. We have a fix but it's not yet in a public build.

**Comment by drohm** [comment]
Thanks @cjb. Any way to manually reset the folders or should I wait for the fix to get released?

**Comment by drohm** [comment]
The update released today works great.  I clicked on 'Rekey' and it successfully rekeyed my private folders this time.  Thanks for the fix.
