### ISSUE TITLE
Error when installing on OSX at "set public name for this device"

### ISSUE THREAD

**Issue by Arachnid** [keybase/client#5155]
After installing the Keybase app and entering my username and password, I get to the page asking me for a name for my device. I enter "MBP" and get a Javascript error at the top of the window (whose contents, regrettably, I have forgotten, and cannot seem to get to recur; hopefully it is captured in the log). Thereafter, restarting the Keybase app just takes me back to the 'name your device' page, and clicking Continue has no effect.

my log id: 546c5515ab8291522db5661c

**Comment by cjb** [comment]
@Arachnid Hi, we've released a fix for this now.  (You should get the update within an hour.)
