### ISSUE TITLE
Windows version is broken

### ISSUE THREAD

**Issue by JamieH** [keybase/client#5163]
I downloaded the latest Windows build from https://keybase.io/docs/the_app/install_windows and found  I can't even login, not via the UI or the CLI. 

```
C:\Users\Jamie\AppData\Local\Keybase>keybase login
Your keybase username or email address: jamieh
- WARNING Upgrade recommended to client version 1.0.18 or above (you have v1.0.18-20161214181335+e063e25)
- WARNING To upgrade, download the latest Keybase installer from https://keybase.io/download
- ERROR 400 Bad Request

C:\Users\Jamie\AppData\Local\Keybase>keybase log

C:\Users\Jamie\AppData\Local\Keybase>keybase log send
This command will send recent keybase log entries to keybase.io
for debugging purposes only.

These logs don’t include your private keys or encrypted data,
but they will include filenames and other metadata keybase normally
can’t read, for debugging purposes.

Continue sending logs to keybase.io? (type 'YES' to confirm): yes
- WARNING Upgrade recommended to client version 1.0.18 or above (you have v1.0.18-20161214181335+e063e25)
- WARNING To upgrade, download the latest Keybase installer from https://keybase.io/download
- ERROR 400 Bad Request
```

Also:
`- WARNING Upgrade recommended to client version 1.0.18 or above (you have v1.0.18-20161214181335+e063e25)` - clearly I have 1.0.18?

**Comment by maxtaco** [comment]
cc: @zanderz

**Comment by JamieH** [comment]
Managed to get the Windows version to upload a log. 51de1e337b079fde79e43d1c

**Comment by cjb** [comment]
@JamieH we just backed out the bad server change that was causing this, sorry for the trouble!

**Comment by JamieH** [comment]
Ah, Thought it might have been a client bug since it was throwing a 400 error, rather then a 500.

**Comment by cjb** [comment]
The server was telling the client that the client had issued a bad request due to being out of date (4xx), but the server was wrong :)
