### ISSUE TITLE
Frequent Kernel Panics (Sierra 10.12.2)

### ISSUE THREAD

**Issue by milsyobtaf** [keybase/client#5190]
For the past several weeks I've experienced at least one Kernel Panic per week on my (brand new out of the box) Early 2015 MBP 13". It always occurred while importing a database in my work virtual machine, running with vagrant inside Virtual Box. After weeks of troubleshooting different aspects, and IT finally giving in and issuing me a brand new laptop, I had the same trouble. At the top of the stack trace of all of these Kernel Panics was `com.github.kbfuse.filesystems.kbfuse	3.5.2`. I saw some other somewhat related issues with Keybase, file mounts, and Sierra in your issue queue, so I tried removing it, and things seem to be going well so far. Attached is my most recent KP report, and my keybase logs. I'm just going to keep it uninstalled on my work machine for now and hope the issue is ironed out in the future. I think an option to install keybase without KBFS would be rad.

No need to troubleshoot with me, I just wanted to pass along these data points.

[Kernel_2016-12-21-140901_katara.panic.txt](https://github.com/keybase/client/files/667263/Kernel_2016-12-21-140901_katara.panic.txt)

my log id: d08c9324f51dfe3a551b7d1c

**Comment by cjb** [comment]
Thanks for the report, please let us know if you see more panics without KBFS installed.

CC @strib

**Comment by strib** [comment]
cc: @bfleischer

I don't see anything suspicious in the KBFS logs, and I don't know of any kernel panics stemming from kbfuse/osxfuse.  To my knowledge, kbfuse shouldn't interact with bluetooth at all directly.

I would guess the ordering in the modules list just reflects what order the modules were loaded in, and Keybase probably tends to run last.

All that said, we've seen strange kernel interactions before, so this could be related to something specific about your machine and KBFS together.  I haven't seen it repro'd anywhere else, but I'll keep my eyes open and please let us know if you see it again without KBFS installed.

**Comment by bfleischer** [comment]
Apple did not release the debug symbols for the two Bluetooth kernel extensions in the stack trace but as far as I can tell this crash is not caused by KBFS. It seems to be Bluetooth related and is triggered in the IOKit part of the kernel. KBFS lives in the BSD part.

    0xffffff9224e23a20 : 0xffffff8009af211c panic (in kernel) (debug.c:462)
    0xffffff9224e23aa0 : 0xffffff8009c05ead kernel_trap (in kernel) (trap.c:799)
    0xffffff9224e23c80 : 0xffffff8009aa3743 trap_from_kernel (in kernel) + 38
    0xffffff9224e23ca0 : 0xffffff8009a9f9ff lck_rw_lock_exclusive (in kernel) + 15
    0xffffff9224e23db0 : 0xffffff800a0bd90a IOEventSource::free() (in kernel) (IOEventSource.cpp:166)

However, it would be interesting to see if the panics stop without KBFS installed.

**Comment by fuzzygroup** [comment]
I've seen similar issues all documented here: http://fuzzyblog.io/blog/osx/2017/10/08/forensic-computing-2-kernel-panics-and-kexts.html . For now I've deleted keybase and manually uninstalled the kext.  I'll try and post back if my system becomes more stable.

**Comment by fuzzygroup** [comment]
Just to give an update, I've since suffered from two additional crashes AFTER I removed this kext so I don't think it had anything to do with it.  Apologies for casting aspersions on Keybase.

**Comment by maxtaco** [comment]
Thanks for following up @fuzzygroup!

**Comment by bfleischer** [comment]
Thanks for following up @fuzzygroup.

However, I would like to add that none of the panic logs you posted on your blog indicates that kbfuse might be to blame for the panics. You wrote that in each case kbfuse was the last loaded kext. This is not correct:

* October 8: com.apple.driver.AppleXsanScheme 
* October 7: com.apple.iokit.AppleBCM5701Ethernet
* September 30: com.apple.driver.AppleXsanScheme
* August 27: com.apple.filesystems.msdosfs

It is true that kbfuse is among the loaded kexts in all panic logs, but, in all fairness, so are 124 other kexts.

> A quick google for the term osx kernel panic fuse gave me 49,100 results so I’m not the only one thinking this.

Undifferentiated comments like the above are kind of frustrating. The search will unearth all panic logs that contain the word "fuse". As you have seen every panic log contains a list of loaded kexts at the time of the crash. The fact that a panic log contains the word "fuse" does not mean FUSE is to blame for the crash.
