### ISSUE TITLE
Passphase not accepted on Fedora 25 x86_64

### ISSUE THREAD

**Issue by thejpster** [keybase/client#5197]
Keybase runs fine on my other two Linux machines (CentOS 7 desktop and Ubuntu 14.04 server), but running on Fedora 25 I'm having trouble. I've revoked the device ID and created a new one, but still no dice.

1. Run `keybase login`
2. Pop up passphrase prompt appears
3. Enter correct passphrase (it works fine on the website)
4. Pop up re-appears saying "Failed to unlock key; bad passphrase"
5. Go to 3

Edit: keybase version 1.0.18-20161219190415+7868d49

**Comment by maxtaco** [comment]
Can you do a 'keybase log send'?


Is your clock way out of whack btw?

**Comment by thejpster** [comment]
Time is set with chrony and appears accurate.

Log ID e3d6ba0852933f4ad3c4e51c

**Comment by maxtaco** [comment]
Urg, I don't recognize this issue, and it's next to impossible for me to debug since I don't want to know your passphrase or you secret keys, etc.   But no one else is reporting it.

We did previously have a bug (#3964), but it was fixed, and you should have been OK after your account reset.  Maybe I can bother you try one last thing. Run `keybase deprovision`, and then run `rm -rf ~/.config/keybase ~/.local/data/keybase ~/.cache/keybase` and then try to login and provision one last time (on Cobalt 2).  

Really sorry about this!

**Comment by thejpster** [comment]
OK, so I delete the folders but I couldn't deprovision because that needs a passphrase.

I've now created a new device (Cobalt 3) and that seems OK. But if I do anything that requires the pinentry box, the box appears completely blank. Just a plain white rectangle. Logging in to the full Keybase application seems OK.

Log ID 3c07013a8faec900b5ddbe1c

**Comment by maxtaco** [comment]
I believe @cjb recently fixed this bug

**Comment by thejpster** [comment]
Is it safe to try what's in master? Happy to give that a go.

**Comment by maxtaco** [comment]
What are you doing that needs a pin entry?

It should be pretty uncommon after your login the first time.

**Comment by thejpster** [comment]
I did a `keybase logout` followed by a `keybase login` to check that the pinentry dialog was now working. After I run `keybase login` the blank pinentry dialog appears. If I kill that, and run `run_keybase` instead, I'm able to enter the passphrase into the keybase application itself, which works fine.

**Comment by cjb** [comment]
Sorry about the bug. We've fixed it, but I'm reluctant to do a new release during the holiday while most people aren't around.

You could try using the command line to do your initial login (keybase login) with the GUI not running, that should work and let you use the GUI afterwards without further pinentry.

**Comment by maxtaco** [comment]
:+1:

**Comment by thejpster** [comment]
No worries. I love the tool and I just want to help.

My initial issue has gone so feel free to close this.

**Comment by cjb** [comment]
Hi, this fix is released now.
