### ISSUE TITLE
Pinentry window blank when logging in 

### ISSUE THREAD

**Issue by noflag** [keybase/client#5209]
The window appears, but is blank and doesn't allow passphrase input. 

Mint 18 Sarah based on Ubuntu 16.14

**Comment by cjb** [comment]
Thanks, sorry about this, we've got a fix for this but it's not released yet due to the holiday period.  You could try killing the GUI app and logging in from `keybase login` on the console as a workaround.

**Comment by cjb** [comment]
Hi, this fix is released now.
