### ISSUE TITLE
KBFS unmounts on waking from sleep 

### ISSUE THREAD

**Issue by plttn** [keybase/client#5215]
On my Surface Book, often times FS won't come back up after waking from sleep/hibernate. I have to reboot to get it to remount. 

my log id: `29943a639c2b96b51394a51c`

log id immediately after waking up from sleep: `33aaa4060d94f799ce532e1c`

**Comment by strib** [comment]
cc: @zanderz @taruti, this is with Windows.

**Comment by strib** [comment]
I don't see anything obviously weird in the KBFS log, seems like the process wasn't running anymore or was completely locked up.

@plttn: what exactly do you see when this happens?  The drive is entirely missing?  Or is it there, but empty?  Or something else?

**Comment by plttn** [comment]
@strib: the drive letter is showing, but missing the KBFS label/size, and trying to open it just throws an explorer error. Restarting Keybase GUI doesn't kick FS back into functioning.

**Comment by linux-modder** [comment]
As mentioned in slack, can you check networking auth/re-auth in that time frame OR if  your suspend scripts are  killing networking, I have seen weird things happen when a oterwise random de-auth or  prolonged offline after idle time.

**Comment by plttn** [comment]
So looks like there's no easy way to determine if Modern Standby is the issue on the Surface, as you can't set the Surface to use S3 sleep instead of Modern Standby/InstantGo. 

The next time I close the lid I'll first check the status of FS after it's been in S0ix for a while, then after letting it sit for a couple hours and going into full hibernate. Logs soon-ish.

**Comment by plttn** [comment]
Here's a wake after S0ix. SB was woken at 8:17pm on 12-30. 

`421eb862dcbadf87d3d5181c`

**Comment by taruti** [comment]
I think this might be surface Windows kernel unmounting the filesystem.

https://github.com/dokan-dev/dokany/issues/413 seems like the same issue.

**Comment by plttn** [comment]
So since this isn't just a problem with KFBS, is there really no solve until dokan on Windows resolves it?

**Comment by rivy** [comment]
Any further progress here?
Or in the meanwhile some workaround to remount KBFS?

**Comment by rivy** [comment]
Using `keybase ctl restart`, from the command line after a wake-up, seems to be a work-around for the issue for me. It looks like it restores normal KBFS functionality.

So, if that works, how about just automatically remounting KBFS after waking from sleep?

**Comment by taruti** [comment]
@rivy @plttn does this work for you with the current release?

**Comment by taruti** [comment]
Thank you for responding, closing this issue. Feel free to reopen if needed.
