### ISSUE TITLE
Write Time in Error

### ISSUE THREAD

**Issue by jtsmith0101** [keybase/client#5216]
Sluggishly saving a shared file.... Ultimately tripping an error on a few of the saves.

my log id: ebb9c2e67118ea2c2b29bc1c

**Comment by strib** [comment]
Thanks for the report.  This is a strange one, as it seems KBFS thinks there are some bytes stuck in the buffer for uploading, but nothing is being uploaded.  That's causing backpressure on your foreground writes until they timeout.  I've seen similar things (like in #4736) but haven't investigated much yet.

Please let me know if it happens again or if you have a reliable repro.  If you're stuck in this state, for now please just restart Keybase and try again.  Sorry for the inconvenience.

**Comment by strib** [comment]
Version 1.0.20 has architectural changes that should greatly improve the large write experience.  If you're still seeing problems, please open a new issue.
