### ISSUE TITLE
Installation dependency

### ISSUE THREAD

**Issue by dreddpenguin** [keybase/client#5242]
[write something useful and descriptive here]
Installing keybase on CentOS 7.3, minimal install, an error occurred during RPM installation.

Redirecting to /bin/systemctl start  atd.service
Failed to start atd.service: Unit not found.

The at package was not installed and is not listed as a dependency for keybase_amd64.rpm

my log id: b8481a8aa81a0f298691aa1c

**Comment by gabriel** [comment]
cc @oconnor663

**Comment by oconnor663** [comment]
We use the `at` command in the postinstall script, in the same way Google Chrome does. When I try to remove `at` on my Fedora VM, and then install Keybase, I see this error:

```
Redirecting to /bin/systemctl start  atd.service
Failed to start atd.service: Unit atd.service not found.
```

But the install succeeds after that, and the error isn't critical. (It's running a cronjob that will run later on its own.) Did the install succeed for you?

**Comment by dreddpenguin** [comment]
The installation did complete, I was just reporting for possible missing dependency definition.

**Comment by oconnor663** [comment]
Got it, thanks. There are already some unavoidable error messages in that install to do with the PGP signing key, so we won't be able to make it super clean, but it might make sense to add the `at` dependency if it's that easy. Do we suspect that'll work across all RPM-based distros?

**Comment by oconnor663** [comment]
That fix will go out with our next build, usually within a day or two. Let me know if you get a chance to try it out again.
