### ISSUE TITLE
Mac OS X: cannot execute any CLI command, GUI install (permissions?)

### ISSUE THREAD

**Issue by peterrenshaw** [keybase/client#5243]
Key base GUI Version: 1.0.18-20161219185928+7868d49
OS: Mac OSX: El Capitan, 10.11.6

1/ What happened?
* Installed above version.
* tried to generate pgp
* fails on command line

2/ Steps to reproduce
* install kb version for mac
* go to command line (terminal) and enter following command.

>   mac:~ pr$ sudo /usr/local/bin/keybase pgp gen
>   Oops, you are trying to run as an admin user (Uid: 0). This isn't supported.

* error reported. 
* note: cannot run without ^sudo^, messages 

  mac:~ pr$ /usr/local/bin/keybase pgp gen
   -bash: /usr/local/bin/keybase: Permission denied

* note: if I run command with sudo I can see command on cli but cannot run

> mac:~ pr$ sudo /usr/local/bin/keybase pgp

>  peters-MBP:~ pr$ sudo /usr/local/bin/keybase pgp
>NAME:
>   keybase pgp - Manage keybase PGP keys
>
>USAGE:
>  keybase pgp <command> [arguments...]
>
>COMMANDS:
>   gen		Generate a new PGP key and write to local secret keychain
>   pull		Download the latest PGP keys for people you track.
 >  update	Update your public PGP keys on keybase with those exported from the local GPG keyring
>   select	Select a key as your own and register the public half with the server
>   sign		PGP sign a document.
>   encrypt	PGP encrypt messages or files for keybase users
>   decrypt	PGP decrypt messages or files for keybase users
>   verify	PGP verify message or file signatures for keybase users
>   export	Export a PGP key from keybase
>   import	Import a PGP key into keybase
>   drop		Drop Keybase's use of a PGP key
>   list		List the active PGP keys in your account.
>   purge	Purge all PGP keys from Keybase keyring
>   help, h	Shows a list of commands or help for one command
   
* when I try gen, 

>    pr$ sudo /usr/local/bin/keybase pgp gen
>    Oops, you are trying to run as an admin user (Uid: 0). This isn't supported.

3/ What I expect?

* download kb
* install kb
* go to bash (terminal) and run command

>  mac:~ pr$ keybase pgp gen

* results in generated pgp key

**Comment by cjb** [comment]
Thanks for the report, CC @gabriel

**Comment by gabriel** [comment]
What does `/usr/local/bin/keybase` point to.. what is the output of:

```
ls -al /usr/local/bin/keybase
```

**Comment by peterrenshaw** [comment]
okay, required to use ^sudo^

> sudo ls -al /usr/local/bin/keybase

results in 

> lrwxr-xr-x  1 root  wheel  60  2 Jan 17:21 /usr/local/bin/keybase -> /Applications/Keybase.app/Contents/SharedSupport/bin/keybase

**Comment by gabriel** [comment]
What happens if you try:

```
/Applications/Keybase.app/Contents/SharedSupport/bin/keybase id
```

There seems to be something wrong with /usr/local permissions maybe?

What is the output of:
```
ls -al /usr/local
```

**Comment by peterrenshaw** [comment]
ok run...
> /Applications/Keybase.app/Contents/SharedSupport/bin/keybase id

yields

> There are no Keybase services installed, you might try running: key base install
> ▶ ERROR There were multiple errors: dial unix /Users/pr/Library/Group  Containers/keybase/Library/Caches/Keybase/keybased.sock: connect: no such file or directory; dial unix /Users/pr/Library/Caches/Keybase/keybased.sock: connect: no such file or directory

then 

> mbp:~ pr$ ls -al /usr/local
> total 0
> drwxr-xr-x   3 root  wheel  102  6 Oct 07:37 .
> drwxr-xr-x@ 12 root  wheel  408  6 Oct 07:37 ..
> drwx------   8 root  wheel  272  2 Jan 17:21 bin

Permissions I reckon. I noticed on the install (not familiar with MacOS/installs) that the Keybase installer would not install when it appeared. In other apps, the installer allows you to click the application icon, it moves to the applications icon, symbolising installing. 

supposition:
I bet there is a problem installing and the permissions is side effect. If you looked at the text file with the new bug reports, you'll see there is a mention of no install of CLI.

**Comment by gabriel** [comment]
Ah yeah /usr/local/bin is unreadable by anyone but root...

To fix, you can run:

```
sudo chmod a+rx /usr/local/bin
```

**Comment by peterrenshaw** [comment]
do 
> sudo chmod a+rx /usr/local/bin
gain access to keybase cli
> keybase pgp gen
everything ok. stuffing around with passphrase and generated pgp via cli.

thx gabriel. I reckon this is closed for me, however, the question I ask myself, 

> "Is this simply a application GUI install permission problem?"  (check/change permissions on install)
>                                   OR 
> do you get users to go to the cli and do the CHMOD?

PR

**Comment by gabriel** [comment]
Yeah it's strange that /usr/local/bin was created with bad permissions. It might be a bug on our end. I'll check it out. Thanks for the bug report.

**Comment by peterrenshaw** [comment]
thx @gabiel, not a killer for technically inclined users, but an average user? I could't even submit a bug.
