### ISSUE TITLE
Error using keybase

### ISSUE THREAD

**Issue by jimiz12** [keybase/client#5244]
Install on Mac with macOS

GUI error - Unhanded incoming RPC 174 keybase.1.provisionUi.chooseGPGmethod

Command line error - ERROR Could not open key: no valid primary key self-signature or key(s) have expired (error 905)

Key appears to be valid and not expired.

my log id: 603f09a0bf5c07252140c01c

**Comment by maxtaco** [comment]
Did you eventually get things working?  It looks as if you updated your key via the website and then were able to login from the CLI?

**Comment by jimiz12** [comment]
Yes.  After some looking it appears that adjusting the key manually on the site:   Export Public Key from GPG locally and updating on the site.  I was able to update.

Closing this.
