### ISSUE TITLE
Invite Code Requirement Discrepancy

### ISSUE THREAD

**Issue by li-norman-1997** [keybase/client#5246]
For the Windows client (v1.0.18, latest), when invoking `keybase signup` in the Keybase Shell, an invite code is required else the registration request fails.

However, on the website (https://keybase.io/), when utilizing the `Join` function / button, an invite code is not requested and is not required for successful registration.

Relevant file (I think): https://github.com/keybase/client/blob/master/go/client/cmd_signup.go
I would submit a PR but I unfortunately do not know Go :(

As a secondary question, do future signups from this point forward require invite codes?

Thanks!
And have a great day!

**Comment by cjb** [comment]
Yes, we're in the process of removing the invite code restriction.  As you point out it's been relaxed on the website and hasn't been relaxed in the clients yet, but it will be sometime soon.

(No need to submit a PR, thanks.)

**Comment by li-norman-1997** [comment]
Thanks for the quick response!
And that sounds great!

I'll close the issue.
