### ISSUE TITLE
Can't login to keybase

### ISSUE THREAD

**Issue by etcook** [keybase/client#5247]
I can't seem to login to keybase using the cli or the application.

When I login with the app, I type in my username and passphrase, but then it removes my avatar on the screen and hangs. When I type in keybase login in the shell, it'll eventually just time out.

my log id: b38349dfa063b7fcaf82631c

**Comment by patrickxb** [comment]
It looks like there a passphrase prompt window showing somewhere (perhaps occluded by another window) that is blocking further requests.

If you quit keybase via menubar app and start it again, it should be ok.  Or find the passphrase prompt window.

**Comment by etcook** [comment]
@patrickxb I tried uninstalling, reinstalling and only doing it from the command line to no avail. I think something was corrupted. I ended up just resetting my account and starting from scratch. That seems to have resolved the issues. Thanks!
