### ISSUE TITLE
FIles added in KBFS don't appear to upload successfully using CentOS 7 app

### ISSUE THREAD

**Issue by adam-rw** [keybase/client#5250]
If I create a file in /keybase/_username_/public/index.md for example, it says that it is signing and uploading it, but it never gets there, or at least it can't be found by using the public URL for it.

I've sent a log file to hopefully help you debug. Get back to me if you have any questions.

my log id: 6cbc871902d18dda1ec51a1c

**Comment by cjb** [comment]
This usually means that you recently reset your account and keybase.pub is still showing the pre-reset files.  Is that the case here?

**Comment by adam-rw** [comment]
That is definitely possible, as I did have to reset my credentials the other day. Is it something I can fix my side?

**Comment by strib** [comment]
We need to restart our keybase.pub server, which I just did.  Does it look ok now @adam-rw?  Please close if so.

**Comment by adam-rw** [comment]
@strib Yep, looks good now. Thanks for your help.
