### ISSUE TITLE
faild to copy 20mb file

### ISSUE THREAD

**Issue by maxyor6040** [keybase/client#5258]
failed to copy file to private common dir using mac's Finder app

my log id: 76c954438ab0ec1229cf0f1c

**Comment by strib** [comment]
Hi @maxyor6040, thanks for the report.  This is a known issue when copying large-ish files over slow-ish networks or on slow-ish CPUs.  We have a fix that's almost ready for public consumption, hopefully in the next couple weeks.  Sorry for the inconvenience, my best advice for now is to try again.

**Comment by maxyor6040** [comment]
cool, thanks
