### ISSUE TITLE
Odd notifications

### ISSUE THREAD

**Issue by matthewbodaly** [keybase/client#5300]
![screen shot 2017-01-05 at 8 10 10 pm](https://cloud.githubusercontent.com/assets/2467428/21707277/0352dd9c-d383-11e6-92d9-d673f87db72d.png)
<img width="83" alt="screen shot 2017-01-05 at 8 10 00 pm" src="https://cloud.githubusercontent.com/assets/2467428/21707278/035732fc-d383-11e6-9e5d-10476d0ab52c.png">

Keybase GUI Version: 1.0.18-20161219185928+7868d49

After accepting new followers. Client does not dismiss alerts.

- Ignoring all followers does not affect change
- restarting computer / keybase client does not make the alerts go away.

**Comment by cjb** [comment]
@maxtaco @mmaxim Gregor TLF calculation bug?

The client's a bit old. But I think the client's just repeating Gregor numbers?

**Comment by matthewbodaly** [comment]
Just did a log send.

Version number is Version 1.0.18-20161219185928+7868d49 (1.0.18-20161219185928+7868d49).
Installed fresh yesterday. 

Gonna try a full uninstall / install.

**Comment by matthewbodaly** [comment]
Uninstall / reinstall still shows a notification. 
Version number didn't change. 
Heh. Sweet. can totally wait till the next version.

**Comment by mmaxim** [comment]
Yeah this is fixed in a later build than the one linked here, should be fixed when we release it.

**Comment by matthewbodaly** [comment]
Great. Thanks much.
