### ISSUE TITLE
[Question] Android

### ISSUE THREAD

**Issue by MTRNord** [keybase/client#5314]
Hi just wanted to ask of there is any way to get access to the Private keybase Filesystem from my Android phone. (i have no PC in reach currently)

**Comment by cjb** [comment]
No, only the public side through https://keybase.pub. We're working on an Android app that will give you access to provate

**Comment by MTRNord** [comment]
Thanks for info :)

**Comment by renatoathaydes** [comment]
Hi @cjb. Have you made any progress on sync'ing private files in the mobile apps?
I would be happy to even access the mounted file system using a terminal emulator like [Termux](https://play.google.com/store/apps/details?id=com.termux), if possible.

**Comment by cjb** [comment]
@renatoathaydes Hi.  Yes, the latest mobile app has a "Files" section that gives access to KBFS files.

**Comment by mberasategi** [comment]
Interested in this as well. Is it possible to have the private files locally stored somehow in Android?

**Comment by PresGas** [comment]
Since this initial question and scope is fulfilled AND closed.  I think a new issue/feature request should be opened.
