### ISSUE TITLE
2 Different files

### ISSUE THREAD

**Issue by griffen4** [keybase/client#5316]
Keybase GUI Version: 1.0.18-20161219123904+7868d49

For some reason on my windows machine when i open my private folder on Keybase there are 2 files one file is Encrypted and the other is un-encrypted. I dont know if this is a bug but they are the same file just one is encrypted and the other is not.

Example: https://gyazo.com/0a95b6bdbe2c77bb8784cb9e3f58e31b

**Comment by cjb** [comment]
CC @strib 

It seems most likely thqt you made that file using software that keeps backup files in the same directory.

Not sure what you mean by one being encrypted. Everything in KBFS is encrypted, but doesn't appear encrypted because it's decrypted for you on the fly.

**Comment by griffen4** [comment]
What i mean by encrypted is that the one with the  ._ before the name when you try and open it is unreadable AKA encrypted. Now this isn't a big deal just thought i would post it just in case other people are having this issue they don't freak out.

**Comment by strib** [comment]
I agree with @cjb.  It looks like you have a `MacOS` device as well.  In macOS, files that start with `._` aren't shown on the command line (though if you did an `ls -la` you should be able to see them).  So some application, possibly a backup app like @cjb suggests) is making encrypted backups for you and storing them in the same directory.  If that's not something you want, you'll have to configure that app on your macOS device to skip the `/keybase` mountpoint.
