### ISSUE TITLE
Input/output error in my public dir

### ISSUE THREAD

**Issue by Sanqui** [keybase/client#5317]
Looks like my KBFS directory got broken somehow.  I can't access it:
```
sanky@kuriputo> ls /keybase/public/sanqui
ls: cannot open directory '/keybase/public/sanqui': Input/output error
```

I can access somebody else's, though:
```
sanky@kuriputo> ls /keybase/public/marcopolo
 banana-bread.txt   construction_files   id_rsa.pub  'loading demo.mov'        stuff          website
'Classy Dyno.mp4'   games                index.html   signal_fingerprint.txt   trip-reports
```

I can also access my private folder just fine:
```
sanky@kuriputo> ls /keybase/private/sanqui
feathers  secret.txt  tmp
```

Finally, my folder is accessible perfectly fine from keybase.pub: https://keybase.pub/sanqui/owl_avatar_4x.png

I'm running Arch Linux and Keybase version keybase-bin-1.0.18_20170106182907+0e09285-1.

log id before updating Keybase: 4fa8a03762517ca1011f1c1c
log id after updating Keybase: 1cbb40141f90bdd5ef1a201c

**Comment by strib** [comment]
Hi @Sanqui.  You're running KBFS version `1.0.2-20161121170756+4847211`, even after the upgrade, which is too old to read the version of that folder you've written (presumably you wrote it from a different, more up-to-date client).  Normally you'd get a GUI notification letting you know to upgrade your client, I'm not sure why you're not seeing it (I don't know what we support on Arch exactly).

In any case, try updating your complete Keybase package, including KBFS, and you should be ok.

**Comment by cjb** [comment]
@Sanqui  Ah, sounds like maybe you just need to "run_keybase" after the upgrade to restart with the newer services.

**Comment by Sanqui** [comment]
Ah, indeed `run_keybase` did the trick.  I forgot about that and didn't notice any notifications.  Thank you and sorry for the false report!
