### ISSUE TITLE
Why must Keybase open my browser to show me Getting Started on every launch? :(

### ISSUE THREAD

**Issue by taylorbanks** [keybase/client#5321]
Keybase GUI Version: 1.0.18-20161219185928+7868d49

**Comment by maxtaco** [comment]
this seems like a bug, @cjb / @gabriel

**Comment by cjb** [comment]
Yes, it shouldn't.  @taylorbanks, please could you run `keybase log send`?  Thanks!

**Comment by taylorbanks** [comment]
Success! log ID:   2b8df04790e03d951ee0f41c


Why I jump out of bed every morning: http://TheLearningBanks.com
How I afford this dream life: http://Ecom.School

**Comment by gabriel** [comment]
What's the output of?

```
ls -al "~/Library/Application Support/Keybase/started.txt"
ls -al ~/Library/Caches/Keybase/started.txt
```

**Comment by taylorbanks** [comment]
No such file or directory in either location.


Why I jump out of bed every morning: http://TheLearningBanks.com
How I afford this dream life: http://Ecom.School

**Comment by gabriel** [comment]
What are the permissions of `~/Library/Application Support/Keybase` and `~/Library/Caches/Keybase`?

```
ls -al ~/Library/Application\ Support/ | grep Keybase
ls -al ~/Library/Caches/ | grep Keybase
```

Are you able to run:

```
touch "~/Library/Application Support/Keybase/started.txt"
```

**Comment by taylorbanks** [comment]
Hmm.. 700 permission on both. The file now exists (prior to attempting to
touch it). :\


Why I jump out of bed every morning: http://TheLearningBanks.com
How I afford this dream life: http://Ecom.School

**Comment by gabriel** [comment]
Do you still get the "getting started" web page on startup or has that stopped happening?
