### ISSUE TITLE
keybase.1.provisionUi.chooseGPGMethod

### ISSUE THREAD

**Issue by tkdberger** [keybase/client#5339]
I tried to do a fresh install of the Keybase app on a Windows system with gpg4win (and my private key available.) This error *consistently* appears on login.

my log id: ccb78830a3d8f389b2e1361c

**Comment by tkdberger** [comment]
Logging in from shell works fine.

**Comment by maxtaco** [comment]
can you take a screenshot?

**Comment by tkdberger** [comment]
Not right now, sorry, but I'll give you an @ mention when I have one.

**Comment by taruti** [comment]
@tkdberger any update on this?

**Comment by tkdberger** [comment]
No, sadly. I logged in from the shell and everything was good, then I cut out Windows for a while.
