### ISSUE TITLE
Keybase Windows 10 - Stuck on Loading

### ISSUE THREAD

**Issue by GoodiesHQ** [keybase/client#5418]
I previously had Keybase CLI-only version 1.0.15. After downloading the new client and uninstalling the old one, the new one installed to my %appdata% directory. When I open the GUI (normally and as admin) I receive only a screen saying "loading" (picture below).

I saw some reports of this happening on OSX. The solution was apparently to move it to a different directory. I did so, just for fun, but it still does not work.

Screen:
http://i.imgur.com/qDvhUM3.png

my log id: 9ce700c6787f444c2f9f131c

**Comment by GoodiesHQ** [comment]
Apologies, the issue did not persist after reboot. It is working as expected.

**Comment by ennorehling** [comment]
I'm having the same problem on Windows 7, both on first start after installation, and after a reboot.

Trying to provide a log file, I get:
C:\Users\Enno\AppData\Local\Keybase>keybase log send
- ERROR Error decoding config file C:\Users\Enno\AppData\Local\Keybase\config.json
- ERROR invalid character '\x00' looking for beginning of value

The config.json file is a binary file made up entirely of zero bytes, which does not bode well.

**Comment by maxtaco** [comment]
cc: @zanderz

**Comment by ennorehling** [comment]
Deleting the broken config.json file worked, and it was replaced with a new one.

**Comment by l1x** [comment]
> * config.json

Thanks, removing the file (config.json) fixed it for me too.
