### ISSUE TITLE
Windows Notice to run "Keybase log send" out of the blue

### ISSUE THREAD

**Issue by jgreever** [keybase/client#5442]
Just updated Java on my PC, about 5 minutes later, Keybase asked me to type "keybase log send" so they could analyze the log. Everything else seems to be working fine, even Keybase.

```
Windows 10 Pro (Version 1607, OS Build: 14393.693)
Intel i7-6700k
Asus z170-p D3 motherboard
MSI GTX 970 4G
32GB RAM (Corsair/XMP)
256GB SDD (Kingston HyperX)

keybase version
Client:  1.0.18-20161219123615+7868d49
Service: 1.0.18-20161219123615+7868d49

my log id: c222d14e0dbd885b6071eb1c
```

Please let me know if there is anything else I can post to assist with this!
Thank you!

-Justin

**Comment by strib** [comment]
Thanks for the report!  Looks like a background process that periodically fetches your quota usage from the server experienced a timeout while making a network call.  I can't tell from the logs why it happened -- maybe a temporary networking blip or something.  Probably a false alarm. Thanks for bringing it to our attention though!

**Comment by jgreever** [comment]
Thank you very much for the reply! I will go ahead and close this as it's not really a bug in my scenario.
