### ISSUE TITLE
keybase.kbfs isn't running (load kext exit status 255)

### ISSUE THREAD

**Issue by whitj00** [keybase/client#5507]
I'm getting this error

My log id is 69ca310701e070870d245c1c

**Comment by cjb** [comment]
@gabriel @strib any ideas?  looks like kbfsfuse isn't coming up on macOS

**Comment by gabriel** [comment]
The log shows error trying to mount:

```
172 2017-01-20T14:34:30.918252 ▶ [DEBU kbfs main.go:104] 002 Mounting: /keybase
173 kbfsfuse error: (2) exit status 255
```

I think 255 is a "file system is not available" but not sure.

@whitj00 what is the output of:

```sh
kextstat | grep kbfuse
```

**Comment by whitj00** [comment]
No output

**Comment by gabriel** [comment]
What happens if you run:

```sh
/Applications/Keybase.app/Contents/Resources/KeybaseInstaller.app/Contents/MacOS/Keybase --install-fuse --timeout=60 --run-mode=prod --app-path=/Applications/Keybase.app
```

**Comment by gabriel** [comment]
Same issue here: https://github.com/keybase/keybase-issues/issues/2721

**Comment by gabriel** [comment]
@whitj00 Are you running any anti-virus or vpn software (seeing if it might conflict with fuse)

Does the issue resolve after rebooting?

**Comment by gabriel** [comment]
I was able to reproduce the problem by running VMWare. Are any of you running that?

**Comment by gabriel** [comment]
If you quit virtualbox and vmware, are you able to startup the Keybase.app?

**Comment by gabriel** [comment]
OK, this issue is the os not having enough device slots left:

> FUSE needs to register a virtual device for exchanging messages between the kernel and the actual file system implementation running in user space. The number of available device slots is limited by macOS. So if you are using other software like VMware, VirtualBox, TunTap, Intel HAXM, ..., that eat up all free device slots, FUSE will not be able to register its virtual device.

> On a brand new install of macOS 10.12 there are six free device slots. VMware and VirtualBox require multiple slots each. TunTap (VPN) requires two slots, as far as I know. Intel HAXM requires at least one slot.

https://github.com/osxfuse/osxfuse/issues/358#issuecomment-279086264

**Comment by sapran** [comment]
I use proXPN, LittleFlocker, and of course VirtualBox (as I believe do many of Keybase fans). Yes, attempt to load kext results in 255. What next?

**Comment by whitj00** [comment]
Hi sorry, just saw this.  Once I rebooted my computer it worked again.

Thanks!

**Comment by gabriel** [comment]
I'm gonna keep this open, cause we'll need to at least notify the user of the specific error, and how to workaround it

**Comment by daneov** [comment]
@gabriel Thanks for referencing me to this one. So it should be ok if I remove e.g. VirtualBox (freeing up those slots)?

**Comment by gabriel** [comment]
VirtualBox seems to load some kexts on bootup so if you aren't using it, yeah uninstalling that might fix it for you.

**Comment by galuszkak** [comment]
So I'm not sure if understood this correctly but I'm using VPN + VirtualBox (for backend dev) and Intel HAXM (for Android dev) and because of that I can't use KBFS? 
Is there any way to make more slots available? For now it looks I can't use OS X client because of that.

**Comment by gabriel** [comment]
Other solutions here:
https://github.com/keybase/client/wiki/Troubleshooting#solutions

(If you aren't connecting to windows machines, you can unload the smb kext)

**Comment by wieczorek1990** [comment]
I think it might conflict with Docker too.
