### ISSUE TITLE
No resolution for name 

### ISSUE THREAD

**Issue by stefanivic** [keybase/client#5512]
[write something useful and descriptive here]
I made mistake with my username so i deleted the account, i also had it setup on my Linux PC ( Ubuntu Gnome 16.10 ) so when i tried to login with a new account i am getting `no resolution for name=nightwalkerkg`

my log id: 062e4ddada8017d55b0ad01c

**Comment by maxtaco** [comment]
I just put in a fix for this

Can solve temporarily with 'keybase db nuke'

LMK if that works

**Comment by stefanivic** [comment]
@maxtaco yes it did! Thanks for the quick answer.

**Comment by agusmakmun** [comment]
Possible duplicate: https://github.com/keybase/client/issues/5464
