### ISSUE TITLE
PGP Update does not work

### ISSUE THREAD

**Issue by kinnla** [keybase/client#5513]
When I type `keybase pgp update` the command fails with `▶ ERROR dial unix /Users/<myusername>/Library/Caches/Keybase/keybased.sock: connect: no such file or directory`.

Last time I ran an update was January 20. `keybase version` gives me `Client:  1.0.16`.

my log id: 74546cccce70b44e37929c1c

**Comment by maxtaco** [comment]
Your install seems borked, as that build is pretty old by now. 

Cc @gabriel

**Comment by cjb** [comment]
I think the updates are working, but it sounds like `keybase` is running a Brew version.

**Comment by kinnla** [comment]
`brew install` gives me `gnupg2`, `gpg-agent` and other stuff, but not keybase. Probably the update I triggered on Jan 20 did not complete correctly. I noticed a change (my keybase folder contained in the favorites of my side bar), but now the command line interface does not work correctly and my email address is displayed as "not verified".

**Comment by kinnla** [comment]
I downloaded `Keybase.dmg` and replaced the keybase app in my Application folder. It's version 1.0.18-20170120152345+482842b. But no effect on the command line tool, it still gives me version `Client:  1.0.16`. How to update the command line tool, if the updater stuck?

**Comment by cjb** [comment]
Could you paste:

ls -l /usr/bin/keybase

ls -l /usr/local/bin/keybase

**Comment by maxtaco** [comment]
Definitely smells like a PATH problem

I was going to suggest 'brew uninstall keybase'

**Comment by kinnla** [comment]
`$ ls -l /usr/bin/keybase
ls: /usr/bin/keybase: No such file or directory
$ ls -l /usr/local/bin/keybase
lrwxr-xr-x  1 myusername  admin  60 17 Oct 17:21 /usr/local/bin/keybase -> /Applications/Keybase.app/Contents/SharedSupport/bin/keybase
$ ls -l /Users/myusername/Library/Caches/Keybase/
total 40
-rw-r--r--  1 myusername  staff   90 22 Jan 12:56 kbfs.info
-rw-r--r--  1 myusername  staff   94 22 Jan 12:56 keybased.info
-rw-------  1 myusername  staff    5 22 Jan 12:56 keybased.pid
-rw-------  1 myusername  staff  308 22 Jan 16:21 session.json
-rw-r--r--  1 myusername  staff   46 25 Oct 11:42 started.txt
$  `

**Comment by cjb** [comment]
@kinnla Thanks for the help! One more please:
```
which keybase
```

**Comment by kinnla** [comment]
$ which keybase
/opt/local/bin/keybase
$ ls -la /opt/local/bin/keybase 
-rwxr-xr-x  1 root  admin  40808732 23 Jun  2016 /opt/local/bin/keybase
$

June 2016, that's probably when I first tried to install keybase and then asked for an invite. It might indeed be a remainder from a brew install. Shall I replace the binary with a symlink to `/Applications/Keybase.app/Contents/SharedSupport/bin/keybase` ?

**Comment by cjb** [comment]
Thanks. You could just move it out of the way, so the one in /usr/local/bin is used instead. Let us know how it goes.

@gabriel Do you recall Brew installing to /opt/local? Should we warn the user if `which keybase != /usr/local/bin/keybase`?

**Comment by kinnla** [comment]
Thx guys!

**Comment by gabriel** [comment]
If you install and run Keybase.app it will overwrite the /usr/local/bin/keybase symlink (which unlinks the brew install). But if it is somewhere else (like /opt/local/bin/) and thats earlier in the PATH, then it wouldn't fix that case.

Because it's a binary in /opt/local/bin/ it seems like that was built and installed manually there? Brew wouldn't go in /opt unless you overrode the brew prefix and even then it would be a symlink? So must have been a manual build or something?

**Comment by kinnla** [comment]
it was macports not brew. Sorry for confusion, I switched to brew in September, so the June install must have been from macports: https://distfiles.macports.org/keybase/client-1.0.16.tar.gz

**Comment by cjb** [comment]
@kinnla Thanks!

@gabriel Want to add something that busts a MacPorts symlink too?
