### ISSUE TITLE
Secure Chat failing to initialize following system reboot

### ISSUE THREAD

**Issue by jtsmith0101** [keybase/client#5514]
Just like the title says.... I rebooted... everything else in the GUI is coming up fine... but the chat function is not.  It is "Securing..." and doesn't seem to be progressing beyond that.  My existing chats are not displaying, either.

my log id: effead81e28f1cadca65b31c

**Comment by jtsmith0101** [comment]
worked on subsequent reboot

**Comment by maxtaco** [comment]
I Believe this is fixed in the next release

Cc: @chrisnojima

**Comment by chrisnojima** [comment]
We have a which which may resolve this issue but it's possible it won't. Let's reopen this if you see it again after receiving an update. Thanks!
