### ISSUE TITLE
Need a folder reset (and closing chats)

### ISSUE THREAD

**Issue by daveio** [keybase/client#5532]
Firstly, is it possible to close chats once opened?

And the meaty issue - key overlap shenanigans happened and now I no longer have access to
`/keybase/private/dave,poggs`

Please reset this folder and any other folders not accessible with my latest paper key and the
`macos-sierra_dave-rmbp`
device.

Signed statement follows:

`Tue 24 Jan 2017 12:29:33 GMT: Please completely reset folder /keybase/private/dave,poggs because I no longer have access to any of the devices it is keyed for. Please also reset any files or folders not accessible with my most recent paper key or the macos-sierra_dave-rmbp device.`

`BEGIN KEYBASE SALTPACK SIGNED MESSAGE. kXR7VktZdyH7rvq v5wcIkHbrydPq7b dn6b2iXFVDgh9VO Xe7OtM9iaTvGv0O Y3tw9qBl3WzqgUi OTcoSTOWPJmsIJR BJaR2bvJEAnMPWs 1vCNymTCQQKZfod V2Pgy85zy0VrVuI MqOptGgQc9DRnje jaF2Icui086NFLV xpqg1SHul2DJ9eh DdQJqJKjFChPHu7 HhbGiaMQYW3PHxR Ap7PeC8k728h55V xQeUBaxrzUlYwQH e1Q7yAIO2SsfXzO mbwOI0sinHFiFn5 sk14UF1feIw5Zm2 QqSx6DI9a8fwfrx HOWvb8AzrBkz2yH hbL6F5JL4AiiHVP xK0rD8zQv3pTd7R NLy6OVBF6dYzb2e ghvdyt1VaVQDhH5 wVkKx6Scg8JXO3s rO9XLumF97k3U0u aSmLzgE32IKeIri ug1v5sgdouOHfW9 mogeG5yzvwYfSD4 sBrs9x7ixOkwYpq XkU7bhGCSJbeWNL cK8nLvUYBOJShsi VBs6odCpaZsi7l0 Mgs6NO7h9TR930f RCmCDhnPjQvkhnC 2frS6bEwNDYBt6K cdTtNZJp4RxjPgx 4Caq1ni2j7XBCa9 AhOvinzpQa4S08p FVXbCvFBTL9jztk afcfALwlLdMl8CM hV9uqKAmWSDDkkL BFwiGctlWDY. END KEYBASE SALTPACK SIGNED MESSAGE.`

**Comment by strib** [comment]
Sorry @daveio, I just noticed this.  I actually don't see any folders that aren't accessible with your current set of keys.  Are you still having issues with folders, or does everything seem fixed now?

**Comment by daveio** [comment]
@strib Sadly no, it seems to be still broken. `keybase log send` identifier `005484fc67d31a7e2382781c` if that helps.

**Comment by strib** [comment]
Super weird @daveio, I confirmed it's still keyed for your other devices.  I don't know why it wasn't showing up as problematic in our internal tables.

I reset it, can you confirm that things are ok now?  (Might require a Keybase restart.)
