### ISSUE TITLE
Opening up the invite list

### ISSUE THREAD

**Issue by RyanSinger** [keybase/client#5541]
How are things going with scaling? Is there any way to get many (thousands?) of invites? I'm looking at using keybase as an ID service for an enterprise use case, but would need to be able to ask many users to register.

**Comment by RyanSinger** [comment]
We could potentially be interested in a support agreement with $$, if that helps.

**Comment by strib** [comment]
cc: @malgorithms

**Comment by malgorithms** [comment]
Hi Ryan - emailed the gmail address on your github profile. closing this and we can discuss there. if anyone else stumbles on this: we're not looking for support contracts right now, but we'll give a large batch of invites to orgs, assuming they understand keybase is still in early beta/late alpha
