### ISSUE TITLE
Keybase client hangs on login, K:\ never mounts

### ISSUE THREAD

**Issue by Zbob750** [keybase/client#5544]
![client](http://i.imgur.com/iBDN7Ky.png)

The client just hangs on 'Loading...' and never goes anywhere. The K:\ drive is also not mounted anywhere.
I do get the little Keybase icon in my notification tray, and it will show me the normal menu, but nothing works except opening a keybase shell.

I have verified that I am logged in, and I have made sure keybase was unlocked via the keybase shell.
I have tried uninstalling keybase and removing all of it's data from AppData, after re-installing it fixes the problem until the next reboot, when this problem then starts re-occurring. I do not have this issue on Linux.

Thanks

my log id: 3c418a1381905a30283e921c

**Comment by puppycodes** [comment]
+1

**Comment by cjb** [comment]
Thanks for the report, CC @zanderz

**Comment by zanderz** [comment]
It is not clear when the reboots occurred in the logs, but I do see the GUI waiting to connect to the service for an hour at a time or so. Is there a chance the startup shortcuts for the service weren't installed properly? This might happen on a corportate machine with a restrictive security policy, for example.

Do you see a KeybaseStartup shortcut in `%APPDATA%\Microsoft\Windows\Start Menu\Programs\Startup` ?

**Comment by Zbob750** [comment]
My system is not associated with a domain or any other corporate policy deployment service.
It appears as though the shortcuts were incorrect however, they both pointed to an improper location. After fixing them, they worked as they should.

I removed all the keybase data and uninstalled it and the dokan library from my system and then reinstalled it, hoping to see if I could get it to happen again. However it all seems to be working properly again. I can no longer reproduce this behavior after a reboot, or at all. Though I still do not know what caused it.

Thank you for your assistance, and for pointing me in the proper direction.
