### ISSUE TITLE
Need my folders reset

### ISSUE THREAD

**Issue by jmerriweather** [keybase/client#5559]
I believe I've done something similar to issue https://github.com/keybase/keybase-issues/issues/2769
I revoked a device while setting up another device, now my folders say they need to rekey but when attempting to rekey it does nothing.

I have nothing important in my folders.

my log id: f9654a715f8676439298cb1c

**Comment by strib** [comment]
It looks like you added a new device `JM-PC`, and for some reason just one of your folders hasn't been keyed for it yet.  Looking at your log, it seems like maybe your existing device from which you sent the log, `MGMT-JM-BOOK`, doesn't know about the new device at the time it tried to rekey that folder.

This is probably a bug, but looks like this was less than an hour ago.  Can you try waiting another hour and seeing if it's still a problem?  Or you can try restarting KBFS on `MGMT-JM-BOOK` to see if that helps.  It might fix itself.  Another option is trying to rekey from `JM-PC` and entering your paper key when prompted.

If none of that works and it's still annoying you, I can reset the folder.

**Comment by strib** [comment]
Oops, I mean for two of your folders.  I think it'll fix itself in less than an hour, if you leave `MGMT-JM-BOOK` running or restart KBFS on it.

**Comment by jmerriweather** [comment]
thanks @strib I'll wait the hour and give it another shot

**Comment by jmerriweather** [comment]
It's all working now, I should be more patient. Thanks again @strib
