### ISSUE TITLE
Rekeying fails silently

### ISSUE THREAD

**Issue by fucx** [keybase/client#5601]
I have recently added a new computer to my account. When entering a paper key to start the re-keying process, everything looks like it's working, but it's not actually re-keying my private folders.
So every time I check the GUI, I'm asked to re-key the non-accessible folders.

my log id: b881110c7abdefcc7e9b9f1c

**Comment by strib** [comment]
Hi @fucx -- this is the same issue as #5519, and we have a fix in review (keybase/kbfs#699) right now that will be in the next release, and your folders should get fixed up then.  Sorry for the inconvenience.

**Comment by fucx** [comment]
I've updated to the latest version now, and the error still persists.

My new log ID is: 20003e8bec16d2d063799e1c

**Comment by strib** [comment]
Sadly the fix didn't make it into that version.  Definitely in the next release (tomorrow, I hope!).

If you want to try fixing it now, another user had success by adding a new device key.  So you could try adding a new paper key if you don't want to wait for the next release -- you can always revoke it once the new release is out if you don't want it anymore.

**Comment by fucx** [comment]
Adding a new key didn't work for me, so I'll just wait for the next release then. Thanks for your help, I appreciate it!

**Comment by fucx** [comment]
It's working now, after today's update. Thanks!
