### ISSUE TITLE
hackernews show as verified on keybase.io web site but not in keybase client

### ISSUE THREAD

**Issue by visionik** [keybase/client#5614]
I posted proof on my hackernews profile and checked it from the macos client.

following that, the macos keybase client shows that my hackernews account is "unreachable" with the following details:

Your proof could not be found, and Keybase has stopped checking.  How would you like to proceed?

however the keybase.io web site now indicates i've proved my hackernews account.

I've tried rechecking from the client but it still doesn't verify.

my log id: 73681594473798b29284b11c

**Comment by visionik** [comment]
it took about 15 minutes, but the client now shows hackernews as verified too.  is this delay expected?

**Comment by maxtaco** [comment]
Yeah, their API server is super flakey and laggy, there's nothing we can do
about.

**Comment by visionik** [comment]
great thanks.  dns is verified in the macos client now too.  closing.
