### ISSUE TITLE
High CPU on Mac

### ISSUE THREAD

**Issue by DemianD** [keybase/client#5626]
Dear,

Keybase is using a lot of CPU, is there a reason for this?
And a fix?

I can't provide more info about this.

<img width="1046" alt="schermafbeelding 2017-02-01 om 14 26 05" src="https://cloud.githubusercontent.com/assets/5346497/22508484/7d0730c2-e88a-11e6-8be4-953f96065a7e.png">

my log id: 4103f10e7d9316bdcc9aff1c

Demian

**Comment by maxtaco** [comment]
hmm, this is the super old brew version, huh.  Can you uninstall the brew version and try the DMG we directly distribute?

**Comment by DemianD** [comment]
I have updated brew.
Will notify here if this didn't work out

**Comment by DemianD** [comment]
Hello @maxtaco 

I still have this error:

![image](https://cloud.githubusercontent.com/assets/5346497/23958377/34c24c50-09a2-11e7-929d-8e6424282ea7.png)

### Homebrew
Homebrew 1.1.11-77-g7685618a1
Homebrew/homebrew-core (git revision 85cd; last commit 2017-03-15)

### Keybase version
Client:  1.0.20-20170309192151+e30557a
Service: 1.0.20-20170309192151+e30557a

I've uninstalled my keybase version, and installed directly the dmg
Other options?

**Comment by maxtaco** [comment]
This is nothing to worry about, it's just virtual memory.  See this: https://github.com/keybase/keybase-issues/issues/1908
