### ISSUE TITLE
Can't prove twitter, username has underscore

### ISSUE THREAD

**Issue by JuanCaicedo** [keybase/client#5628]
_Not sure what repo to post this in, I'll gladly close and reopen someplace else_

I'm trying to authorize twitter and I keep seeing this message even though [I've posted already](https://twitter.com/_juancaicedo/status/826818535154388992)

```
Couldn't find posted proof.
Check Twitter again now? [Y/n] n
```

I think the username is correct since I see this message if I try to restart

```
$ keybase prove twitter
You already have a proof for _juancaicedo@twitter; overwrite? [y/N]
```

However, is it possible that the leading underscore in my username is causing a problem?

**Comment by cjb** [comment]
@oconnor663, any ideas?

**Comment by oconnor663** [comment]
It looks like you omitted the "Verifying myself" part of the tweet text. That part is required.

**Comment by oconnor663** [comment]
Apologies for not having a more helpful error message here. Our proof checker is pretty strict right now, for a couple reasons: 1) It's easier to get less strict over time than it is to get stricter, and 2) we don't want to make it too easy for someone to accidentally prove something they didn't meant to prove.

**Comment by JuanCaicedo** [comment]
This worked great, sorry for the user error 😝
