### ISSUE TITLE
Repeating notifications about KBFS re-keying

### ISSUE THREAD

**Issue by Xalaxis** [keybase/client#5641]
The end result is something which looks somewhat like #2346. I get a re-keying notification fairly regularly between every 1-5 minutes despite no access being made to the KBFS.  As I understand it, re-keying should only need to occur if the keys of either side of the conversation change?
![chrome_2017-02-02_11-40-03](https://cloud.githubusercontent.com/assets/12937964/22548217/57661c6c-e93d-11e6-991c-22625ae6605e.png)

**Comment by strib** [comment]
Hmm, yeah that doesn't seem right.  Are you willing to run `keybase log send`, and report the resulting log ID here, so we can see more details about your platform/version and logs?

**Comment by Xalaxis** [comment]
Erm. Maybe this could be related?

- ERROR API network error: Post https://api.keybase.io/_/api/1.0/logdump/send.json: read tcp 10.1.1.117:39031->54.84.82.15:443: wsarecv: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.

The connection seems stable enough for normal browsing.  Ping 17ms.

**Comment by strib** [comment]
Strange.  Are you behind some kind of proxy/firewall that could be messing with ssl traffic?  Not sure how that would lead to rekeying messages, but something weird is going on...

**Comment by Xalaxis** [comment]
I'm behind a firewall but it doesn't make any changes to SSL traffic.  I managed to get the log to submit (bc0c9a6a22165cb030b3861c).  Maybe it was just a flaky line after all?

**Comment by strib** [comment]
Ah, this is the same issue as #5601.  There's a bug in that version of the client that is failing to rekey, but it keeps trying.  I guess it sends the notification before it figure out it fails.  Sorry about that.

Unfortunately we haven't released a Windows client with the fix yet.  We plan to in the next few days I think.  Until then, I'm not sure there's a good workaround unfortunately, other than a new client on some non-Windows computer if you have one handy, and letting that one do the rekey.

**Comment by strib** [comment]
Ah, we just released a new Windows version.  Hopefully it works for you; if so, please close this out.

**Comment by Xalaxis** [comment]
No re-keys seem to be waiting any more.  I'm going to hold off declaring this closed until it's run for a day tomorrow but it's looking good so far!

**Comment by Xalaxis** [comment]
Looks good.  Great job!
