### ISSUE TITLE
"ERROR decrypt error: no suitable device key found"

### ISSUE THREAD

**Issue by markspolakovs** [keybase/client#5674]
I have a saltpack encrypted file to myself `keybase encrypt markspolakovs -i foo -o foo.asc`. I reinstalled Windows and Keybase, and tried to decrypt it, only to get the message:

```
Decryption failed; try one of these devices instead:
  * Doubleprime-Reinstall (desktop); provisioned 1 day ago (2017-02-02 22:52:02 CET)
  * Enterprise (desktop); provisioned 8 months ago (2016-05-16 17:53:04 CEST)
  * coyote appear (backup); provisioned 7 months ago (2016-06-27 08:55:10 CEST)
- ERROR decrypt error: no suitable device key found
```

Doubleprime-Reinstall is my old Windows install that I installed over today, and I had just entered the coyote appear key into `keybase rekey`.

My log ID is `534c9a1d1f2943d49d95841c`

**Comment by maxtaco** [comment]
Try `keybase decrypt --paperkey`

**Comment by markspolakovs** [comment]
@maxtaco worked, thanks! Maybe the output should be clarified on this. Might send a PR your way, although I've never written Go before ;)
