### ISSUE TITLE
Unable to access folders

### ISSUE THREAD

**Issue by hazardv** [keybase/client#5685]
I have a private shared folder with another user. Using the windows GUI I went to folders->private and then clicked on the shared folder. It then showed me buttons labeled Open Folder and Ignore Folder. Open folder does not seem to do anything. The same goes for my personal private and public folders. 

When I go to the Windows file explorer I see the "K drive" under My Computer but when I double click on it a message pops up stating that the location is not available.

my log id: 3f0ae0ed720aa8c1ad622d1c

**Comment by strib** [comment]
```
13059 2017-02-06T12:19:19.212625 - [ERRO kbfs mounter.go:57] 02b Failed to mount dokan filesystem (i=64): Dokan failed: code=-5 "Mount error"
```

@zanderz @taruti?

**Comment by taruti** [comment]
@hazardv does this reoccur after rebooting?

**Comment by hazardv** [comment]
I just restarted and it appears to be working.
