### ISSUE TITLE
New app icon is hideous [Low priority]

### ISSUE THREAD

**Issue by maxweisspoker** [keybase/client#5705]
Keybase GUI Version: 1.0.18-20170206170059+4931777

This is obviously low priority, but the new application icon is absolutely horrible.  For the love of god please revert to the old icon, or have a gui option to set the icon.  I can't stress enough how absolutely horrid the new icon is.

I love the project otherwise and have no complaints.  Please keep up the amazing work.  I love what you guys do.  Except the icon.  Throw whoever came up with that in a lava pit.  That icon will be a significant hindrance to adoption and usage.

I just -- I really can't stress enough how much I hate the new icon.

**Comment by bennycornelissen** [comment]
@maxweisspoker I've seen no changes to the app icon so far, but any change to an app icon of a security related product like Keybase is surely going to throw people off. Any chance of sharing the new app icon here so we know what it is supposed to look like?

**Comment by maxweisspoker** [comment]
Damn, I really liked the crying dog logo.  Well whatever, I'll go fork the repo and revert it back for myself.  Should I bother creating a pull request, or am I the sole dissenter?

PS: Have I mentioned how much I dislike the new icon?

**Comment by gabriel** [comment]
Are you on MacOS? If so, you can replace any app icon by dragging an icns file into the top left icon in "Get Info". Go to /Applications in Finder and choose "Get Info".

![2017-02-07 at 1 49 pm](https://cloud.githubusercontent.com/assets/2669/22713214/5c8d494c-ed3c-11e6-889b-5035d6cc7e02.png)

Old icon here:
https://github.com/keybase/client/blob/b6f4dba0a5352d3f5102908573249dab0917156d/media/icons/Keybase.icns

It might get replaced after an update though.

**Comment by maxweisspoker** [comment]
Yeah I know I can just replace the launcher icon, but the app icon is still there and still appears as programmed in the tray and the GUI.  It's fine though, you guys absolutely should do what you think is best, it is your project after all.  And it was silly and stupid and petty of me to open an issue for this.  I'll just fork it and use the old icon for myself.  I'll close this issue.  Thanks for the responses though.
