### ISSUE TITLE
Client stuck at "Loading..."

### ISSUE THREAD

**Issue by michael-pesce** [keybase/client#5733]
I've seen the other threads that discuss this issue (most from mid-2016), but nothing suggested seems to work. 

my log id: f732726c16843e47132bb81c

**Comment by cjb** [comment]
Thanks for the report, CC @gabriel and @chrisnojima

**Comment by michael-pesce** [comment]
`michael$ /Applications/Keybase.app/Contents/Resources/KeybaseInstaller.app/Contents/MacOS/Keybase --app-path=/Applications/Keybase.app --run-mode=prod`

> 02.08.2017 13:29:00.681 Installer:42[DEBG] Version: 1.1.46
> 02.08.2017 13:29:00.681 Installer:54[ERROR] Error parsing: Error Domain=Keybase Code=-1 "Invalid timeout: 0" UserInfo={NSLocalizedDescription=Invalid timeout: 0, NSLocalizedRecoveryOptions=(
>     OK
> )}

**Comment by poppingtonic** [comment]
Can concur:

```bash

[~]$ keybase log send
This command will send recent keybase log entries to keybase.io
for debugging purposes only.

These logs don’t include your private keys or encrypted data,
but they will include filenames and other metadata keybase normally
can’t read, for debugging purposes.

Continue sending logs to keybase.io? (type 'YES' to confirm): yes
▶ INFO ignoring error getting keybase status: API network error: doRetry failed, attempts: 6, timeout 11.390625s, last err: Get https://api.keybase.io/_/api/1.0/sesscheck.json: dial tcp: lookup api.keybase.io: no such host (error 1601)
▶ ERROR API network error: Post https://api.keybase.io/_/api/1.0/logdump/send.json: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
```

**Comment by poppingtonic** [comment]
I just looked at the documentation, and it says:

```
To restart Keybase after an update, type run_keybase. This will kill and restart everything, including the KBFS fuse mount.
```
After that, my client started normally.
I think a more visible instruction to do this would be really helpful, or an OS-specific hook.

**Comment by gabriel** [comment]
@michael-pesce This is same issue as https://github.com/keybase/client/issues/5830

I finally was able to repro and made a fix. Should be in upcoming version early next week.

I'll close this so discussion can be centralized there.

**Comment by gabriel** [comment]
@poppingtonic Your issue is different, maybe we can open up a different issue for that? (cc @oconnor663 )

**Comment by oconnor663** [comment]
I've seen this one before (cc @maxtaco): `API network error: doRetry failed, attempts: 6, timeout 11.390625s, last err: Get https://api.keybase.io/_/api/1.0/sesscheck.json: dial tcp: lookup api.keybase.io: no such host (error 1601)`

For me it comes up after closing and opening my laptop sometimes. I've filed an [internal issue](https://keybase.atlassian.net/browse/CORE-4611) for us to fix it. Could you tell me as much as you can about your Arch setup? Is that Gnome 3? Are you running NetworkManager? So far I've never seen it happen outside of Arch, so it might be related to one of our packages. Thanks for your help.

**Comment by poppingtonic** [comment]
No problem, @oconnor663. I'm running Gnome 3 with NetworkManager, yes.
