### ISSUE TITLE
There was a problem connecting to the server dialog and white/blank UI

### ISSUE THREAD

**Issue by mokele** [keybase/client#5739]
Since removing a previous Apple Time Capsule from my home network I have started receiving dialogs of an application attempting to read from it even though it is no longer there. I have tracked this down to being the keybase app for some unknown reasons.

The app does not load instantly, hangs, the OSX dialog appears 'There was a problem connecting to the server "time capsule name here"', then instantly after ok-ing this the keybase icon is added to the system bar at the top.

The tray icon is unresponsive, causes pointer beach-balling, and after another hang the "There was a problem connecting to the server" dialog comes back, and after ok-ing this time a keybase window arrives but is entirely white/blank.

Attempted to search for other similar threads to no avail :/

![screen shot 2017-02-08 at 20 41 02](https://cloud.githubusercontent.com/assets/36778/22756798/4649aca2-ee40-11e6-86eb-4baa6d0897cb.png)

![screen shot 2017-02-08 at 20 44 22](https://cloud.githubusercontent.com/assets/36778/22756801/48e10ce4-ee40-11e6-8c92-215b2f5a2205.png)

**Comment by cjb** [comment]
Huh!  Yes, this is the first report we've received like this one.

CC @gabriel @akalin

**Comment by gabriel** [comment]
@keybase/react-hackers 

BTW, I've gotten all my chrome based apps to fail and hang (including Alfred, Keybase and Chrome) if I had stopped by an exception in Chrome dev tools.

**Comment by gabriel** [comment]
@cjb is this related to all white bug we've seen reported in other places... I don't know status of that.

**Comment by mokele** [comment]
This was due to a shared path from a now non-existent external drive being listed in the Login Items list in System Preferences -> Users & Groups -> Login Items. It didn't matter that they were unchecked/unused – simply having them listed there was enough.

Presumably this caused some really odd knock-on effects that seemed entirely unrelated. A couple of days ago it seem like Spotify was also affected by delayed start-up due to this issue. What surprises me is that it even affected starting keybase manually rather than just at start-up time where I'd assume this Login Items list is actually relevant. But no, it was always affected.

Very odd behaviour. Very very odd. and I assume entirely OSX related and very hard to circumvent as an app developer being an OS configuration related fix and nothing that should affect an app.

Very surprised. Closing ticket.
