### ISSUE TITLE
reddit link from keybase client do not work

### ISSUE THREAD

**Issue by rdslw** [keybase/client#5741]
Keybase GUI Version: 1.0.18-20170207061119+ce0f90d

After trying to add proof for reddit account, I'm asked for user name. I enter it and then keybase shows me link to click. Clicking it does NOT result in any action (browser which waits in background does NOT open any new window).

It worked fine for twitter link on the very same computer.

My cfg:
windows 10pro
chrome beta channel
security options and ublock etc may be of effect (yet twitter link worked...)

**Comment by zanderz** [comment]
Can you please open `Keybase Shell`, perform `keybase log send`, and copy the log ID here? Thanks.

**Comment by rdslw** [comment]
Log ID is:   e0347718d95dd37a0706e11c                            
BTW I did two tries of reddit. After first try, I revoked it and tried again. Second reddit try is still not revoked. 
In logs you can see successfull github/twitter.

**Comment by rdslw** [comment]
@zanderz Is there a way to manualy create reddit post using information from existing prove data? 
Or command line ?
I'm interested specifically in using existing 'limbo' proof, not generating new one.

**Comment by Curbob** [comment]
I'm having the same problem

Log ID: 97b07fdf7859231a0933ff1c

**Comment by pale2hall** [comment]
I'm having the same issue.

Log: 8e410eab9ea27050a77c0f1c

Windows 10, Chrome Version 56.0.2924.87 (64-bit) set as my default browser.

**Comment by DavidBurela** [comment]
Same issue here. Windows 10. Edge set as default browser. Logged into my account in browser. 
But clicking the link in Keybase UI does nothing, doesn't launch edge or provide any feedback when you click. Twitter & GitHub both worked fine

**Comment by DavidBurela** [comment]
I was able to resolve by using the CLI `keybase prove reddit davidburela` which generated a URL for me. BUT for some reason pasting it into Edge would only populate the text, not the title. But pasting url into chrome populated both.

**Comment by malgorithms** [comment]
I believe this is fixed now. Can you all try to make a Reddit proof again?

**Comment by rdslw** [comment]
Yep, after revoking lingering proof, the new one works for me. Thank you.
