### ISSUE TITLE
Cannot create a Keybase public chat

### ISSUE THREAD

**Issue by zmanian** [keybase/client#5746]
Keybase GUI Version: 1.0.18-20170208165022+dc66461

```
keybase chat send --public zmanian "Hello public keybase"
Creating a new PUBLIC CHAT conversation: zmanian.
▶ ERROR creating conversation error: error creating conversation: unknown TLF ID: cfc5b8a3b92e938cd3c612fa7bea2f17
```

**Comment by maxtaco** [comment]
Thanks @zmanian, we're tracking down this bug, it happens to some but not others.  Can you `keybase log send`?  Many thanks!

**Comment by mmaxim** [comment]
Hey @zmanian, we actually don't need the log send, we seem to have found the root cause here and are working on a fix.

**Comment by charlie-wasp** [comment]
I've got version 1.0.37, got the same error

**Comment by maxtaco** [comment]
thanks, cc: @mmaxim, that original bug should be fixed, i wonder if there is a new one.

**Comment by mmaxim** [comment]
I think this is fallout from the server problems this morning @maxtaco, going to close. @charlie-wasp feel free to re-open if you try again and it doesn't work.

**Comment by charlie-wasp** [comment]
Thank you for your replies, it seems working now 👍 Keep up the good work and thank you for the Keybase!
