### ISSUE TITLE
Chat: ERROR creating conversation error: unexpected number (0) of conversation; need 1

### ISSUE THREAD

**Issue by TheMRod** [keybase/client#5758]
I compiled the kbfsfuse binary on Slackware 32-bit. I was able to connect to KBFS and see my pre-existing public and private files. When I tried to run the chat, I got this error:

```
$ keybase chat send bigfoot "another test"
Creating new CHAT conversation: bigfoot,mbc
▶ ERROR creating conversation error: unexpected number (0) of conversation; need 1
```

my log id: 880d3715de13a865cbb4a81c

**Comment by maxtaco** [comment]
cc: @mmaxim 

thanks for the bug report

**Comment by TheMRod** [comment]
FWIW, Slackware 64's current chat CLI client works fine.
