### ISSUE TITLE
No files in public keybase.pub folder

### ISSUE THREAD

**Issue by mfin** [keybase/client#5774]
Hey!

I have a weird problem with my public folder.

Some time ago I added a file (hello.txt) to my public keybase.pub folder, when I was testing the functionality. Yesterday, I restored my profile and added a brand new PGP key to my account. I've set that up and everything was working as it should, except for the Keybase filesystem.

There were no files in my public folder and if I added one, it wasn't seen from my keybase.pub page. I literally have no idea how to further test this, so if I can be of any help while debugging this, let me know.

my log id: 01cfa0b22767223112f5a81c

**Comment by mfin** [comment]
I noticed that both files I've added today are perfectly synced across both my computers and that old file, hello.txt, is absent from both of them.

**Comment by cjb** [comment]
@mfin Hi, I expect this is because you reset your account but keybase.pub is still seeing your old account instead of your new one.  It's only a problem for keybase.pub.  It'll get fixed automatically the next time keybase.pub restarts.  I don't have an ETA for that, though.  Is that okay?

**Comment by mfin** [comment]
Of course it is, I'll close this for now. 👍

**Comment by strib** [comment]
Dang, I thought I had fixed this bug.  I'll look into it again when I get a chance.  Sorry!

**Comment by strib** [comment]
@mfin: we happened to restart keybase.pub today so you should be good to go.

**Comment by mfin** [comment]
@strib affirmative, it works now! 👍
