### ISSUE TITLE
Errors while adding a new device

### ISSUE THREAD

**Issue by capndesign** [keybase/client#5782]
I’m not sure how to reproduce this, but here’s what I did:

1. Install the keybase client on another laptop ("My Work Laptop").
2. Try and key it from "My Laptop" by entering the multi word key provided.
3. It seemed to complete, so I closed "My Laptop".
4. "My Work Laptop" asked me to open my other machine to rekey.
5. I couldn’t figure out how, so I  revoked the device from "my work laptop".
6. Try to re-add the device with the same method, but got an error. (see screenshot below)
7. I entered my passphrase and Keybase successfully logged in on "My Work Laptop".
8. On "My Laptop", it was asking me to rekey using "My Laptop" or the follow step (see 2nd screenshot). It never showed "My Work Laptop".

Keybase GUI Version: 1.0.18-20170208165022+dc66461

<img width="696" alt="screenshot 2017-02-09 12 23 05" src="https://cloud.githubusercontent.com/assets/75802/22797552/aae68284-eecc-11e6-8df7-06819ea007d9.png">

![screenshot 2017-02-09 13 14 27](https://cloud.githubusercontent.com/assets/75802/22797622/efb2e6c8-eecc-11e6-8d7b-df8361d58db2.png)

**Comment by maxtaco** [comment]
cc: @patrickxb 

Also cc: @malgorithms, on the rekey timing issue we knew about

**Comment by capndesign** [comment]
Log ID for "My Work Laptop": 6f026ac4d404bf5ca51dde1c

**Comment by capndesign** [comment]
Log ID for "My Laptop": eade77576b3a95b9a460ce1c

**Comment by patrickxb** [comment]
@capndesign a few clarifying questions:

Is "My Work Laptop" working with keybase?

During the process, you revoked "My Laptop", and the error screenshot above is when you are trying to provision "My Laptop" again?

**Comment by capndesign** [comment]
@patrickxb 
> Is "My Work Laptop" working with keybase?

Actually, "My Work Laptop" is working better than "My Laptop". Chat is working fine on both machines, but "Work" only needs to rekey for my private folder. "My Laptop" needs me to enter the paper key to access any folder.

> During the process, you revoked "My Laptop", and the error screenshot above is when you are trying to provision "My Laptop" again?

Yes

**Comment by capndesign** [comment]
Good news! Somehow, magically, this has resolved itself on both computers. I only have "My Laptop" at home right now, but here’s a log ID in case it is helpful: f0b0eee4ec946de9b33f671c

**Comment by songgao** [comment]
Thanks for reporting!

Resolved by keybase/client#5850 and keybase/kbfs#760
