### ISSUE TITLE
Windows Installation - Cannot remove old versions

### ISSUE THREAD

**Issue by shampto3** [keybase/client#5785]
I had attempted to install keybase about 6 months ago, but it ended up not working. I'm trying again, and this time it brings up a couple of errors:

1. It brings up that the `Keybase.mi` resource is unavailable. The source it points to doesn't exist (it says `"{803E48B3-ECDB-4B7D-9795-63FAD60A2E26}v1.0.16.79"` but there is only a folder called `"{94288048-AB68-44B3-9E83-B1D5226B556F}v1.0.18.565"`. When I try the default source it says there is no such folder, and when I try the existing folder it says it is not a valid installation package for the product Keybase Apps.
1. Once I give up and click cancel it says "The older version of Keybase Apps cannot be removed. Contact your technical support group."

I don't know if this has anything to do with the previous attempt, but I've tried to clear my computer of anything related to keybase, but I always get the same error.

Here are the [logs](https://gist.github.com/shampto3/757c412865bba6b850a7d5378cc7f54b) it gives me at the end. Any help would be appreciated.

**Comment by cjb** [comment]
Thanks for the report, sorry about this, CC @zanderz.

**Comment by zanderz** [comment]
To [uninstall when the original msi is missing](https://support.venafi.com/hc/en-us/articles/215911917-Error-Uninstall-an-MSI-and-msiexec-fails-asking-for-path-of-old-MSI), try doing `msiexec -X {803E48B3-ECDB-4B7D-9795-63FAD60A2E26}` (with our without curly braces, not sure). If that GUID doesn't work, you can follow along with the linked instructions to find Keybase in the registry to get the product GUID from there.

**Comment by shampto3** [comment]
Thanks for the reply @zanderz - I tried running the `msiexec -X 803E48B3-ECDB-4B7D-9795-63FAD60A2E26` (without braces is what works) and it brings up a Windows Installer error that says

    This installation package could not be opened. 
    Verify that the package exists and that you can access it, 
    or contact the application vendor to verify that this is a valid Windows Installer package.

I used the given link to find the proper GUID but that same one was the only one I could ever find. I've searched a lot of different places for the missing .msi file (cache, recycle bin, etc.) and I can't find the old file. I may have somehow gotten rid of it when I was trying to solve the problem earlier or back when I first tried to install it. I don't know what else I can do to uninstall it.

It's not Keybase's fault, so I understand if you want to go ahead and close this issue.

**Comment by zanderz** [comment]
One more thing to try: I believe the original missing installer is here:
https://s3.amazonaws.com/prerelease.keybase.io/windows/Keybase_1.0.16-20160713110422%2Ba1c00b3.386.exe
Maybe if you install this original bundle, then uninstall Keybase and Dokan again?

**Comment by shampto3** [comment]
That worked (after a little bit of finagling)! Thanks a bunch @zanderz!
