### ISSUE TITLE
How did you generate the squirrel?

### ISSUE THREAD

**Issue by MichaelAquilina** [keybase/client#5789]
This isnt really an issue but I did not know how else to ask this question. How did you generate the [squirrel](https://github.com/keybase/client/blob/master/packaging/linux/crypto_squirrel.txt) that shows in the terminal at the startup of keybase on linux? Is there a tool?

**Comment by cjb** [comment]
@MichaelAquilina https://github.com/erkin/ponysay/blob/master/ponies/squirrel.pony

**Comment by MichaelAquilina** [comment]
Thanks for the quick reply!
