### ISSUE TITLE
CLI "keybase chat api" never returns

### ISSUE THREAD

**Issue by damomurf** [keybase/client#5798]
Invoking "keybase chat api" in the CLI, the app just sits there and seems to never return.

my log id: 033f38a4b92cdd9b5e872d1c

**Comment by maxtaco** [comment]
i think it's expected. it's waiting for a command on standard input

**Comment by maxtaco** [comment]
```
$ echo '{}' | keybase chat api
▶ ERROR invalid v1 method ""
```

**Comment by damomurf** [comment]
Ah, sorry. That's quite obvious when you think about it! Thanks folks.
