### ISSUE TITLE
Getting error when trying to copy files

### ISSUE THREAD

**Issue by JustBru00** [keybase/client#5802]
![Image of Error](http://i.imgur.com/Gg2vMQQ.png)

![System Specs](http://i.imgur.com/HQAydca.png)

my log id: a5584f38e33f0f057579671c

**Comment by strib** [comment]
Hi @JustBru00, thanks for the report.  It looks like you happened upon a way to crash the file system while writing a file.  I'll probably be able to get a fix into master tomorrow, and it should be in the next Windows release (next week?).  Sorry for the inconvenience!

**Comment by strib** [comment]
The fix (keybase/kbfs#748) is now in master. Hopefully we'll get a new Windows release out soon.

If you're looking for a workaround, the only thing I can think of is to delete all 0-byte files in your KBFS that are more than a week or two old. Then restart KBFS, and try to copy your file in again.  Maybe not very helpful, I know.

**Comment by JustBru00** [comment]
Thanks for looking into it I can wait until the fix is put out. 😄
