### ISSUE TITLE
Certificate Error

### ISSUE THREAD

**Issue by brandonsturgeon** [keybase/client#5807]
Keybase GUI Version: 1.0.18-20170208085427+dc66461

My company uses a custom certificate, and due to this I cannot login to Keybase windows.

**Comment by zanderz** [comment]
Where does it fail exactly? Is installation successful?

**Comment by brandonsturgeon** [comment]
Installation is successful, I notice the error when I try to log in for the first time on the Desktop app.

**Comment by cjb** [comment]
@brandonsturgeon It sounds like your company wants to intercept your encrypted traffic and re-encrypt it so they can read it?  We don't support that -- it defeats the purpose of using encryption.

**Comment by brandonsturgeon** [comment]
Erm. Okay.

**Comment by cjb** [comment]
@brandonsturgeon Happy to talk more if I've misunderstood something about your setup.  Do you know what the "custom certificate" is?

**Comment by brandonsturgeon** [comment]
I'm afraid I don't know much about networking, so I didn't want to dispute your claim.

The company uses cloud security service which requires us to install a custom root certificate on some of our machines to remedy various authentication problems.

I'm really not sure to what extent we use this service or what "pieces" we have enabled, so I'm afraid I can't go into too much detail there.
