### ISSUE TITLE
No way to disable auto-start

### ISSUE THREAD

**Issue by golfdish** [keybase/client#5808]
Keybase GUI Version: 1.0.18-20170208165022+dc66461

I can't find any option not to auto-start the KeyBase app when my computer starts.

**Comment by gabriel** [comment]
Are you on macos? If so, in System Preferences, Users & Groups, Login Items, and then you can remove Keybase from there.

We should add a preference in the app too though.

**Comment by golfdish** [comment]
This is macOS Sierra, yes.  Thanks, and I agree the option should be surfaced in the app as well.
