### ISSUE TITLE
Can't quit full screen mode

### ISSUE THREAD

**Issue by mattes** [keybase/client#5823]
Keybase GUI Version: 1.0.18-20170209165653+17b641d

MacOS 10.12.2 

The top bar is not being shown.

**Comment by cjb** [comment]
Huh, I didn't think we had a full screen mode. Can you share a screenshot?

**Comment by mattes** [comment]
I was starring at Chrome and Slack last night, and then trying to find the "exit full screen button" in keybase. I just realize that both apps must have added them purposely and many other apps don't do that. 

Exiting full screen mode in keybase works fine and as expected. My mistake. 

<img width="333" alt="screen shot 2017-02-11 at 10 56 07 am" src="https://cloud.githubusercontent.com/assets/1240531/22856571/d5dbdcfa-f048-11e6-823f-cbbbff649bb3.png">
<img width="107" alt="screen shot 2017-02-11 at 10 56 34 am" src="https://cloud.githubusercontent.com/assets/1240531/22856572/d90aed08-f048-11e6-8aad-f16ce6730fb3.png">

**Comment by minton** [comment]
I'm using `Version 1.0.44-20180223192708+9a9ccec79` on `macOS 10.13.3` and there does not appear to be a way out of fullscreen. I clicked the macOS green full screen button to run key base as fullscreen. However, now the top bar is no longer shown and I can't exit full screen. I've tried the normal shortcut <kbd>⌘</kbd>+<kbd>^</kbd>+<kbd>F</kbd> but it doesn't work.

![stuck_in_fullscreen](https://user-images.githubusercontent.com/750757/36692829-34e30b08-1b07-11e8-9e03-15055aa71803.gif)

I've even tried quitting Keybase and restarting but it loads back in the same condition.

Any ideas?
