### ISSUE TITLE
Keybase client app and unusable on HiDPI displays

### ISSUE THREAD

**Issue by psiniemi** [keybase/client#5825]
I have Ubuntu 16.10 on a Dell Precision 5510m with a 3840x2160 resolution display (~280ppi) and the text is so small that the app is unusable. Also can't find a way of making the text bigger.

**Comment by dkasak** [comment]
Any news on this? This is a pretty big usability problem.

**Comment by xkr47** [comment]
- [X] Looks good on 100dpi
- [ ] Looks good on 280dpi

**Comment by stefanotorresi** [comment]
I'm experiencing this problem too on a Dell XPS 15 with a 3840x2160 display on Linux Manjaro Gnome.
UI is completely unusable.

**Comment by rubiojr** [comment]
The systemd unit changes in https://github.com/keybase/client/issues/5797 fixed it for me, using Ubuntu 18.04.

**Comment by heronhaye** [comment]
Hi, you can now increase the font size with Ctrl-+. Please make a new issue if you still have trouble, thanks!

**Comment by psiniemi** [comment]
Thanks - works great! :+1:

**Comment by xkr47** [comment]
This is excellent! Thanks @heronhaye!

**Comment by xkr47** [comment]
It even remembers between startups, nice.

**Comment by ng0177** [comment]
I recommend to mention is somewhere visible for all those not reading this threat. It works great!
