### ISSUE TITLE
▶ ERROR GetConversationForCLILocal error: error unboxing chat message: KBFS client wasn't found

### ISSUE THREAD

**Issue by 0x7fff9** [keybase/client#5827]
Hi!

the app was working and out of the blue I started to get this error:
```
error unboxing chat message: KBFS client wasn't found
```

<img width="746" alt="image" src="https://cloud.githubusercontent.com/assets/24276463/22854166/354c3f6c-f068-11e6-9646-0e00b344068e.png">

<img width="676" alt="image" src="https://cloud.githubusercontent.com/assets/24276463/22854170/5146906e-f068-11e6-9727-0d760da579f1.png">

My log id is: `2622a842a305017a4f99b11c`

Is this familiar? I have logoff,logon. Revoked the device and re-add. still the error persists.

Thanks a lot and keep up with the great work.

cheers.

**Comment by gabriel** [comment]
Yeah this is same as https://github.com/keybase/client/issues/5830

Will close this and move discussion there.
