### ISSUE TITLE
Support for Mobile Version

### ISSUE THREAD

**Issue by hypery2k** [keybase/client#5828]
Did you need support with distribution the mobile app for iOS and Android? I could publish it with my developer account on App and PlayStore

**Comment by cjb** [comment]
No, please don't do that. We have developer accounts too.

**Comment by hypery2k** [comment]
Okay, got it ;)

Any chance to sign up for an alpha release. Can test an various Android and iOS devices

-- 
Martin Reinhardt
Sent with Airmail

Von: Ball Chris <notifications@github.com>
Antworten: keybase/client <reply@reply.github.com>
Datum: 11. Februar 2017 at 16:07:55
An: keybase/client <client@noreply.github.com>
CC: Reinhardt Martin <contact@martinreinhardt-online.de>, Author <author@noreply.github.com>
Betreff:  Re: [keybase/client] Support for Mobile Version (#5828)  

No, please don't do that. We have developer accounts too.

**Comment by themotu** [comment]
I volunteer for alpha also, have a plethora of devices
