### ISSUE TITLE
Added new device, but not getting recognized by other devices

### ISSUE THREAD

**Issue by omkelderman** [keybase/client#5832]
I added a new device (my desktop) and it gave me a code, I entered that one on my laptop and my desktop seem to like it, since it continued with the setup proces. But my laptop doesnt seem to recognize it or something. It says something about things being done last by an unknown device. The log is coming from my laptop.

my log id: 6dc773947d22ec302b85e21c

**Comment by omkelderman** [comment]
hmm, my desktop started complaining suddenly, so aparently it wasnt added correctly.. I gave my desktop my paper key and that seems to fix the issue there, but my laptop is still in a bugged state 😢

**Comment by songgao** [comment]
Thanks for reporting!

Resolved by keybase/client#5850 and keybase/kbfs#760

**Comment by omkelderman** [comment]
confirmed laptop not being in bugged state anymore 👍
