### ISSUE TITLE
stuck

### ISSUE THREAD

**Issue by jmdugan** [keybase/client#5862]
tried to install keybase on mac laptop, osx 10.11.6, latest

got this: http://i.imgur.com/JFQbTS8.png

restarted app, it did it again.  restarted laptop, it did it again.  

no instructions, no help, no link, nothing online on the website.  <?>

where are the logs?  apparently there is one, but "keybase log send" doesn't say where it is

searched in ~/Library/Application Support/Keybase did not find anything helpful

what action is supposed to come next?

my log id: b4190f2227363c8c08621c1c

**Comment by maxtaco** [comment]
the issue is this:

```
1073 2017-02-13T20:45:27.921829 ▶ [DEBU keybase gpg_cli.go:353] 403 | running Gpg: /usr/local/bin/gpg --no-tty --armor --sign -u e3a091f223617b3613da61e1dc6dfc240b180120
1074 2017-02-13T20:45:27.931409 ▶ [DEBU keybase gpg_cli.go:332] 404 gpg: Sorry, no terminal at all requested - can't get input
1075 2017-02-13T20:45:27.931838 ▶ [DEBU keybase gpg_key.go:50] 405 - GPGKey Signing -> GPG error: exit status 2
```

haven't seen this issue before, but it's GPG, so I'm not surprised.  It's an incredibly inconvenient app to integrate with.  Does gpg work on the command line for you?

**Comment by jmdugan** [comment]
yes, it works command line. it only does, do not use it with a gui ever

**Comment by jmdugan** [comment]
where/how can that log be viewed?

**Comment by jmdugan** [comment]
gpg is installed using brew, from package gnupg

#> brew info gnupg
gnupg: stable 1.4.21 (bottled)
GNU Pretty Good Privacy (PGP) package
https://www.gnupg.org/
/usr/local/Cellar/gnupg/1.4.20 (53 files, 5.4M) *
  Poured from bottle on 2016-03-08 at 14:23:47
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/gnupg.rb

**Comment by jmdugan** [comment]
so you know, typically when using this private key to sign something, the passphrase is required, and the command line interface offer the place to enter it

like, 

'''
You need a passphrase to unlock the secret key for"
key details...
key details...

Enter passphrase: _'''

but if an external app is trying to call gpg and the key has to be unlocked, and you want to pass the passphrase back, you might use something like

gpg --no-version --no-verbose --batch --output - --passphrase-fd 0 --armor --detach-sign --textmode args args args ...

(or something like that)

which will allow gpg to read in the passphrase from STDIN

**Comment by maxtaco** [comment]
Try 'keybase login' from the command line. That should work in your case.

**Comment by jmdugan** [comment]
worked!  thank you
