### ISSUE TITLE
Cannot connect to keybase from ubuntu

### ISSUE THREAD

**Issue by karask** [keybase/client#5865]
My local machine (Ubuntu 16.04 64bit) has gpg properly installed with a private key. I have imported the public key to keybase (via the website).

I wanted to use the chat app and installed keybase on my machine. However, when I try to login it says:

"
Sorry!
You can't provision using a passphrase, since you've established a PGP key.
You have options: - Install GPG on this machine and import your PGP private key into it  ....."
"

My machine already has gpg with a private key in it. The corresponding public key is on keybase.

What needs to be done?

my log id: 8d9341693e26498880e0981c

**Comment by juanminm** [comment]
Check that the secret key appears using both `gpg --list-secret-keys` and `gpg2  --list-secret-keys`. Keybase may be trying to locate the key in one of those versions.

**Comment by karask** [comment]
`gpg --list-secret-keys`  shows that my secret key is there

**Comment by maxtaco** [comment]
Keybase uses `gpg2` by default.  What does `gpg2 --list-secret-keys` show?

To change this setting:
```
keybase config set gpg /path/to/gpg/version1
```

**Comment by karask** [comment]
Using `gpg2 --list-secret-keys` displays nothing (gpg2 exists but there are no keys)

I tried `keybase config set gpg /usr/bin/gpg` and then tried `run_keybase` again but I got the same issue as above. 

I assume, that if it finds gpg properly is will not ask me for the passphrase, right?

**Comment by maxtaco** [comment]
Do `keybase log send`

**Comment by maxtaco** [comment]
After you've tried again

**Comment by karask** [comment]
Ok, I got log id: 7cbc2da2cc217ddeb8fc691c

(and a new github issue url which I will not use...)

**Comment by maxtaco** [comment]
Sorry, my bad, I gave you the wrong setting. Do this:

```
keybase config set -c gpg
keybase config set gpg.command /usr/bin/gpg
```

**Comment by karask** [comment]
OK, now it passed that stage. Then it asked me if I want to upload my key pair to keybase or use "one-time shell to gpg". I chose the later, entered a name for the device and got:

"Unknown error: GPG error: exit status 2"

**Comment by maxtaco** [comment]
Please another log send.

**Comment by karask** [comment]
log id: b2ea3a1c1e0a09bd565bca1c

**Comment by maxtaco** [comment]
It seems like you don't have GPG pinentry installed.  Have you tried command-line installation?

`keybase login`

**Comment by maxtaco** [comment]
CC: @chrisnojima on this.  It might make sense to have the electron app recommend this fall-back.  If people don't have pinentry installed, right now CLI login is the best approach. It would be possible to build out a pinentry step here, but with a lot of effort, and it seems to affect very few people.

**Comment by karask** [comment]
After I went through the process with `keybase login` everything went as expected.

Thanks

**Comment by maxtaco** [comment]
Glad it worked, and sorry for the hiccups.

**Comment by chrisnojima** [comment]
tickted: https://keybase.atlassian.net/browse/DESKTOP-2875
