### ISSUE TITLE
Keybase remains in Disconnected state if application launches before connecting to Wifi

### ISSUE THREAD

**Issue by olelink** [keybase/client#5866]
Keybase GUI Version: 1.0.18-20170208085427+dc66461

Windows version: 10 (Anniversary Edition) - Windows 10 Version 1607

**Comment by olelink** [comment]
From what I can tell in my logs, it appears to keep trying to use a pipe (from the network connection) that was never established correctly

**Comment by cjb** [comment]
Thanks, I think we've got a fix for this that we haven't released yet on Windows, should be out in the next few days!

**Comment by olelink** [comment]
Good news.  Thanks!

**Comment by taruti** [comment]
@olelink Was this resolved for you?

**Comment by olelink** [comment]
@taruti Yes.  Updated and tested 2 days ago
