### ISSUE TITLE
Ghost chat

### ISSUE THREAD

**Issue by jarlah** [keybase/client#5871]
I noticed I had a ghost chat below my active chats. Clicked it and poked around, tried to open the menu where the mute checkbox is. Then it went totally bananas.

![screenshot from 2017-02-14 20-40-12](https://cloud.githubusercontent.com/assets/404102/22946521/eaa3fad0-f2f7-11e6-96e6-40aaed359a5f.png)

my log id: a555f778978f8df3591d141c

**Comment by cjb** [comment]
Thanks for the report, I've made an internal bug report to track this.  Does quitting and restarting the app fix it?

**Comment by jarlah** [comment]
i solved it by accident when hitting the mute button.

**Comment by jarlah** [comment]
after getting the error. tried to make it reappear
