### ISSUE TITLE
Cannot login, my password or secret key does not work, and now I need to change my key, but keybase app keeps crashing.

### ISSUE THREAD

**Issue by S3curityPlu5** [keybase/client#5879]
Keybase GUI Version: 1.0.18-20170208085427+dc66461
I cannot restart the app, without restarting the server.  Cannot figure out why my secret key won't let me log in.  If it was easier to just revoke key and import or generate a new key. I would not be posting this bug.
This is on Windows server 2016 14393 up to date build as of 2=15=17

**Comment by maxtaco** [comment]
Can you still log into the web site?

Please run `keybase log send`

CC: @zanderz

**Comment by S3curityPlu5** [comment]
Yes I can log in to the website, 
I am now troubleshooting the app again, I will send the log and reinstall

**Comment by S3curityPlu5** [comment]
Sorry about this I just closed it, as this was fixed in last update, and I forgot about this post
