### ISSUE TITLE
Read operations timing out for private folder on keybase

### ISSUE THREAD

**Issue by borrrden** [keybase/client#5886]
This is happening on both Windows and macOS, but I wonder if it is my network connection?

my log id: 6dcf7a5373584d551e1cc41c

**Comment by strib** [comment]
Yeah, it looks like you sent a read request to our servers, and our server didn't get it in time to respond before the timeout.  Actually, our server doesn't seem to have ever gotten it.

Do you have a slow network connection in general?

**Comment by borrrden** [comment]
Not usually (200 megabit fiber connection in Tokyo), in fact I resorted to syncing these files through Dropbox instead and it completed in seconds.   Yesterday it was acting funny though...

**Comment by strib** [comment]
Ok, thanks. I take it back actually, I think your request did get to the server, but you must not have received the response in time.  We don't have any geo-replication (probably unlike Dropbox) and Tokyo's about as far as you can get from our servers, so maybe this is a temporary bottleneck somewhere?  Was it wokring ok before this started happening (and has it fixed itself yet)?

**Comment by borrrden** [comment]
It has happened for the past 24 hours at least.  It used to work alright as recently as a week or two ago.

**Comment by strib** [comment]
Hmm, ok.  In the log you sent, I only see it happening once in the last month, about a minute before you sent the log. Please let us know if it continues to happen tomorrow.

**Comment by borrrden** [comment]
Sorry, there is an explanation for that.  The other times it happened were from my other machine, and I haven't figured out how to run keybase command line on Windows.

**Comment by zapu** [comment]
![image](https://cloud.githubusercontent.com/assets/451974/23014594/e872da0e-f42f-11e6-9877-dd92f446b698.png)

(This menu opens after you click the "3 bar" icon).

It opens a shell in which you can run `keybase` cmd tool.

**Comment by borrrden** [comment]
Thanks for that!  I knew it had to be something simple I was missing.  

Windows logs:  33f4ef3c936eaabac7bb491c

**Comment by borrrden** [comment]
The problem seems to have cleared itself up though (from both machines).  I just tried it now.

**Comment by strib** [comment]
I'm glad it's working!  Nothing has changed on our end, so I'm going to chalk this up to some temporary Internet bottleneck somewhere between your client and our servers.  If it happens again, please let us know.  Thanks for the report!
