### ISSUE TITLE
Unable to verify reddit account

### ISSUE THREAD

**Issue by jgbresson** [keybase/client#5888]
When I go to verify my reddit account the client does nothing when I click the link to open the form.

my log id: a9c3291fce2a04473dab7e1c

**Comment by jgbresson** [comment]
I ended up using the command line instead, but doing it through the client still does not work.

**Comment by malgorithms** [comment]
we have dupes of this so I'm closing this one. Also, I think we just fixed it, but I'll wait to close them all until comfirmed.
