### ISSUE TITLE
KBFS: Can't copy files from private folder to public folder (error code -36)

### ISSUE THREAD

**Issue by Simonmoush** [keybase/client#5894]
Keybase GUI Version: 1.0.18-20170209165653+17b641d

Dragging files from my personal private folder to my personal public folder doesn't succeed and raises the following error:
"
The Finder can’t complete the operation because some data in “test.txt” can’t be read or written.
(Error code -36)
"

Copying the files to an intermediate location on my computer and then to the public folder works fine.

![bug report](https://cloud.githubusercontent.com/assets/732242/23030738/a3f4c736-f43c-11e6-9641-1217e28109d5.jpg)

**Comment by strib** [comment]
@Simonmoush: Thanks, this is a known bug in Finder, and we're working on a workaround right now.  You can hold option/alt when you click and drag, or you can use `mv` in the terminal.

**Comment by Simonmoush** [comment]
Ok, Thanks!
