### ISSUE TITLE
I can't verify the reddit link, it doesn't do anything when clicking the form

### ISSUE THREAD

**Issue by Juvls** [keybase/client#5912]
Keybase GUI Version: 1.0.18-20170216112451+a5b6199

Hi, I am using Windows 10 client, when trying to verify my reddit account using the client it doesn't open the form when clicking on the link so I can't verify it.

![17-02-2017 18-28-14](https://cloud.githubusercontent.com/assets/12261309/23078104/3bf77a12-f53f-11e6-847f-e48e03053fb3.jpg)

**Comment by Juvls** [comment]
When trying to do it through the web site, I've got this error message on reddit web site.

![17-02-2017 18-40-28](https://cloud.githubusercontent.com/assets/12261309/23078464/bd9ae580-f540-11e6-9354-f8302d82c536.jpg)

**Comment by cjb** [comment]
@Juvls Reddit is down.

**Comment by Juvls** [comment]
@cjb I can access the rest of the web site, only the keybase part seems down

**Comment by cjb** [comment]
It's still a server error from their end, we can't fix it.  Try again soon.

**Comment by Juvls** [comment]
Fair enough, thanks! 👍
