### ISSUE TITLE
passphrase recovery fails

### ISSUE THREAD

**Issue by hoodie** [keybase/client#5929]
Hey there , when I try to recover my passphrase I get asked for a new passphrase before the process fails with:
`▶ ERROR could not find UID or username for self`
What's wrong here?

(version: 1.0.18)

**Comment by maxtaco** [comment]
It might be your client is out of date.

**Comment by maxtaco** [comment]
Please do a Log send

**Comment by maxtaco** [comment]
Cc: @mlsteele

**Comment by hoodie** [comment]
6ce25df56c00b0303ac6c71c

**Comment by maxtaco** [comment]
I believe your client is out of date, but I can't tell for sure from your version string

@hoodie can you login via the Web site btw?

(cc : @cjb and @gabriel and @zanderz and @oconnor663, we should bump the version on the client)

**Comment by hoodie** [comment]
yopp, seems to work now - thx
I've reinstalled the app, version seems the same though
