### ISSUE TITLE
Chat send error

### ISSUE THREAD

**Issue by djdesign** [keybase/client#5945]
Upon attempts to send a message to a fellow keybase user, faced with error message `r(>_<)-i Failed to send.` after recent update to `Version 1.0.18-20170209165653+17b641d `. 

![Messaging Error Keybase.io User](https://thedjdesign.com/hazel/screen_shot_2017-02-20_at_12_25_02_pm.png)

my log id: e414fba6f03ca2b504007a1c

**Comment by mmaxim** [comment]
Looks like `zacchaeus` reset their account earlier today, which has been a problem case for us. The next release will hopefully get this to be smoother. Can you talk to them now?

**Comment by djdesign** [comment]
Still failing. But think it has todo with their account being reset with no social links, there is a button on their profile within in the app to accept. But able to see any click events happening.

**Comment by mmaxim** [comment]
Try typing:
keybase db nuke
And restarting Keybase and see if it fixes the problem. Sorry!






On Mon, Feb 20, 2017 at 5:49 PM -0500, "Daniel Willitzer" <notifications@github.com> wrote:










Still failing. But think it has todo with their account being reset with no social links, there is a button on their profile within in the app to accept. But able to see any click events happening.

**Comment by djdesign** [comment]
No Dice. 

I am able to reproduce this error with other profiles/followers I talk with. Am I just lucky?


Daniel Willitzer
daniel@thedjdesign.com
