### ISSUE TITLE
Cannot delete bio from the app

### ISSUE THREAD

**Issue by jmhale** [keybase/client#5947]
When you go to delete the text in your bio in the app, once you delete the last character, the entire bio text repopulates the field. 

If you highlight the whole text and hit backspace, the first keypress does nothing. 

Re-highlighting the text and pressing backspace again deletes the text and leaves the field empty, but hitting Save doesn't have any effect.

my log id: 9f7b3c5d9f7e218462815a1c

**Comment by timmc** [comment]
What OS? Happens to me as well, with client version 1.0.18-20170224170054+d0aa303 on Debian Linux 8 ("Jessie").

**Comment by jmhale** [comment]
@timmc Mine is happening on macOS Sierra (10.12.3), client build `1.0.18-20170223162556+af0e640`

**Comment by jmhale** [comment]
This is an old issue and seems to have been fixed sometime between the initial report and my current client version: `3.0.0-20190205183613+6394d03e6c`, so I'm going to close this.
