### ISSUE TITLE
github enterprise connectivity

### ISSUE THREAD

**Issue by schnide** [keybase/client#5964]
Looked through current issues and did not see this as issue. Sorry if it exists and I missed it in my searches.

The ability to connect to an on premise enterprise github server as can do with github.com.

An example would be github.someschool.edu [hope that doesn't exist]

Please let me know if I can provide further information.

Thanks

**Comment by cjb** [comment]
Hi, if you mean for GitHub proofs, this wouldn't work -- the point of proofs is that they're *publicly* verifiable by the entire Keybase user community.

**Comment by schnide** [comment]
ok, thanks
