### ISSUE TITLE
Re-Key private folder failing

### ISSUE THREAD

**Issue by miketweaver** [keybase/client#5968]
I lost a harddrive, and re-installed my OS. At the same time, I installed keybase on the new install.
I followed the prompts, and was able to open private folders shared to me with other people. As everything seemed to be working, I then revoked my old device and paperkey. I then generated a new key.

At that point I attempted to open my private folder and saw this:

<img width="353" alt="Keybase - Files need to be re-keyed" src="https://cloud.githubusercontent.com/assets/5581855/23187751/3d979098-f849-11e6-8397-2a4812b51884.png">

I then decided to use the paper key to start the re-keying process (`$ keybase rekey paper`). When entering it in, everything looks like it's working, but that popup still appears, and my private folder still seems empty. 
```
$ keybase rekey status
No TLFs need rekeying.
$ keybase version
Client:  1.0.18-20170209165653+17b641d
Service: 1.0.18-20170209165653+17b641d
```
my log id: aca6504859fbfd05ba6c361c

**Comment by maxtaco** [comment]
cc: @songgao  can you take a look at this one?

**Comment by strib** [comment]
I am already looking.  @miketweaver it looks like you created that paper key (`nation anxiety`) today, after revoking your other paper keys?  This folder was never keyed for your current paper key.  Does that sound right?  Why did you revoke your old paper key (specifically `swim scene`)?

**Comment by miketweaver** [comment]
@strib That sounds exactly right. 

The revocation of the old paper key `swim scene` was because of a mis-understanding of the paperkey system. I've since reviewed the documentation and have a better understanding of paperkeys. I still have record of the old paper key.

**Comment by strib** [comment]
Thanks.  Do you have data in that folder you need to recover, or is it ok to reset the folder completely?

@maxtaco @patrickxb: is there any way to restore a wrongly-revoked paper key, or input it using `keybase rekey`?

**Comment by maxtaco** [comment]
no, we'd have to build that

**Comment by miketweaver** [comment]
@strib Well, I have the data encrypted elsewhere, though it would take me a few days to get access to it. I'd rather not have to go get it, but it **is** recoverable. I understand the mistake was on my part for incorrectly revoking that key and am completely fine with resetting the folder, if needed.

**Comment by strib** [comment]
It looks like there's no way to recover that data, without us building something new into our software, which would take significantly longer than a few days I think.

We definitely need to get better about warning you on the CLI when you're about to revoke a key that will cause you to lose access to your private data.  I know we've talked about it, not sure what the status is.  Sorry we let you get into this mess.

Resetting seems like the best option to me, unless you're willing to dive into the code and somehow trick your local client into accepting the revoked paper key.  If you want me to proceed with the reset, please run this command on an currently-valid keybase device, and substitute the current date and time where indicated:

```
keybase sign -m "<DATE_AND_TIME>: Please reset folder /keybase/private/bashninja because all the devices that have access have been revoked."
```

and post the results here.

**Comment by miketweaver** [comment]
```
BEGIN KEYBASE SALTPACK SIGNED MESSAGE. kXR7VktZdyH7rvq v5wcIkHbsF0EYND zNhOJyZlGqcWH22 xDErfIHwsiYd4UA KDAyNh40HKu7B58 7iOFpoUZwSIPGOr gLNdeNXKpvPD9G9 GMcuAN1XSBlJEN7 n6XwofIcOx1A8tg nLCBVlOx1eTC8Ku cjAfb1FH2dhB5HQ opcnbcFcZSxRAPg WUkhbFUkEwVAUkc LLDFNRRUwJcT8sE mQspO7f5LThCulN 7tpmOVAMX9a27TL ZhHGSVH7FfEGN0o 6qoP0WFLYdzNjiY xLJyVz1HqvF1x9i rJBDZDAMtfpNABQ eNo2Lvhn5JaNDLB wX7MWE0Po1DGxzH i6aSrK3SAItsrFO 3EjYklxxyMFwKUv MRoT0y2zuGbg9R6 RYD9ueNHQSaviAg vWHOeUb8DRpx25y oZRrlnsZCgLnyoG yWcfLmmY9p4ffd0 PNF6HztBDfkN9hW 0e. END KEYBASE SALTPACK SIGNED MESSAGE.
```

**Comment by strib** [comment]
Ok, it should be reset now.  Please check it out and close this if everything seems ok.
