### ISSUE TITLE
Write lock conflict

### ISSUE THREAD

**Issue by itys** [keybase/client#5969]
Log id: d58f77ad249bcad098ab411c 

Details on what happens when attempting to delete a file while transferring a folder on OS X. Operation eventually finished without additional user interaction.

**Comment by strib** [comment]
Thanks for the report.  Hmm, that's an odd error message, it doesn't look like it's coming from KBFS.  What programs were you using for transfer, and what showed you that error message?

I do see some timeout errors in your keybase log, but those are expected in the current release under some situations (we should be fixing them soon).  I don't know how they'd end up showing you a lock error though.

**Comment by itys** [comment]
This was a drag-and-drop via the Finder for the transfer, and a Cmd-Del
in the Finder folder for the delete. The message I believe was via the
normal thing-used-to-be-known-as-a-growl notification.

Attempts to replicate a couple times so far have failed (Log ID
5f306ec74e18857120bacb1c):
1. Drag and drop large archive
2. Delete file from active transfer folder
3. Works *shrug*

**Comment by itys** [comment]
Closing due to non-reproducibility.
