### ISSUE TITLE
Error writing file to shared private folder

### ISSUE THREAD

**Issue by javbotero** [keybase/client#5984]
Tried a few times without luck to add a relatively small file (11.7 MB) to a shared private folder. Got several Keybase warnings about the write operation before getting a Mac OS error code -36 (IoErr). Had to relaunch Finder and restart Keybase to recover.

Adding a much smaller file (30 bytes) to the same private folder worked fine.

my log id: a5d8f42594fd4ddfe76c781c

**Comment by strib** [comment]
@javbotero: thanks for the report. Believe it or not your client is having trouble uploading 8MB to our server within the file system timeout allowed by your OS (19 seconds).  We are actively working on fixes that makes writes not depend on your network connection speed; those should be out next month.  Sorry for the inconvenience.

**Comment by strib** [comment]
Version 1.0.20 has architectural changes that should greatly improve the large write experience.  If you're still seeing problems, please open a new issue.

**Comment by javbotero** [comment]
@strib Awesome. Thanks so much for letting me know and for the great work.
