### ISSUE TITLE
Option to disable client starting automatically upon login (Windows)

### ISSUE THREAD

**Issue by patricklucas** [keybase/client#5990]
Keybase GUI Version: 1.0.18-20170130201446+3f505f9

Apologies if this has been answered already, but I can't seem to find the option to disable starting Keybase on login. It's very possible I am just blind and haven't seen it. Could someone point me to this option?

I expected to find it in the context menu of the tray icon, the drop down on the mini-Keybase pane, or in the settings area of the main GUI.

**Comment by ro-bb** [comment]
There seems to be no such option. I tried disabling the created autostart entry.
It doesn't start anymore, but I can manage to start it manually. I tried it by starting the GUI, then it's loading forever. If I execture the runquiet.exe nothing happens and with the command line, I can login, but can't manage to start the fileserver. login and ctl doesn't help me.
I'm running Win 10 64bit

**Comment by zanderz** [comment]
There is no user interface for disabling start at startup, but you can remove the 2 shortcuts from `%appdata%\Microsoft\Windows\Start Menu\Programs\Startup`. There is one for the GUI and one for the daemon, and if the GUI is started by itself it won't be able to do anything.

`runquiet.exe` is just a launcher that hides the console window. The actual command it launces to start the daemon is `keybase ctl watchdog2`.

**Comment by bigtlb** [comment]
It would be really nice if there was an option to disable startup after login, and the GUI would detect and launch the daemon, if it notices the daemon isn't running when it is started.

**Comment by gaites** [comment]
An interface option would be great.

**Comment by heronhaye** [comment]
Should be available for Windows. Please make a new ticket if it doesn't work, thanks!
