### ISSUE TITLE
Cant user keybase passphrase

### ISSUE THREAD

**Issue by mshdk** [keybase/client#6034]
Hi

When I try following someone on the website it says: Error: Your private key appears corrupted (no valid primary key self-signature or key(s) have expired)

Unfortunatly I have uninstalled the keybase application on my laptop (probook) so I reinstalled it. But it does not appear to accept my keyphrase. The keyphrase works on the keybase website, if I paste the same password into the webbrowser it is accepted for the login but not when pasting into the app. I have also manually typed it many times.

What to do? Should I recover the passphrase using the paper key?

my log id: 53a634394fb5ee20ff2b981c

**Comment by maxtaco** [comment]
Can you update your PGP public key via the website?  it looks like your key is expired.

**Comment by mshdk** [comment]
Hi

I started all over in the webinterface with a new PGP key, but it appears that I cant log in using the application. I have tried uninstalling the keybase application and reinstalling but when I try to login I get this error:

- ERROR SecretSyncer: no device found for ID=dc1ce65a9601745596b80c896dab8018

(OS is windows 10 pro)

I have send log files here: f2fdc7b2747f33e68d1b031c

**Comment by maxtaco** [comment]
we'll put this bug in our bug tracker.  you can likely fix this issue with

```
keybase config set -c current_user
keybase config set -c users
keybase ctl restart
keybase login
```

**Comment by maxtaco** [comment]
Actually, @mshdk, scratch the above, can you try this?

```
keybase db nuke
keybase login
```

Thanks!

**Comment by maxtaco** [comment]
Well shucks. In the first case your key had expired.  But it seems like you deleted your account a bunch of times in a row, and that might have introduced additional bugs.

**Comment by maxtaco** [comment]
this bug was fixed in #6094

**Comment by mshdk** [comment]
Thanks, nuke did not work but this did:

keybase config set -c current_user
keybase config set -c users
keybase ctl restart
keybase login

**Comment by maxtaco** [comment]
cool, thanks, it's fixed in the next release....
