### ISSUE TITLE
[Win10] - Folders do not mount successfully when drive K: already exists.

### ISSUE THREAD

**Issue by Stormtalons** [keybase/client#6036]
My desktop has had a K drive for almost as long as I can remember... which, as I discovered, the keybase client apparently does not like. My kbfs logs are full of lines like the following:

```
[ERRO kbfs mounter.go:57] 01f Failed to mount dokan filesystem (i=8): Dokan failed: code=-5 "Mount error"
[ERRO kbfs mounter.go:57] 02a Failed to mount dokan filesystem (i=16): Dokan failed: code=-5 "Mount error"
[ERRO kbfs mounter.go:57] 02b Failed to mount dokan filesystem (i=32): Dokan failed: code=-5 "Mount error"
[ERRO kbfs mounter.go:57] 02c Failed to mount dokan filesystem (i=64): Dokan failed: code=-5 "Mount error"
[ERRO kbfs mounter.go:57] 02d Failed to mount dokan filesystem (i=128): Dokan failed: code=-5 "Mount error"
```

Upon investigation, I found that the "mountdir" setting in config.json doesn't appear to do anything... changing it from "K:" to an unused letter didn't force keybase to use it. Changing my K drive to a different letter seems to be a suitable workaround, albeit an inconvenient one.

Please let me know if more information would be helpful.

**Comment by ctd1500** [comment]
You can change the kbfs drive letter by running `keybase kbfsmount set X:` on the keybase shell and then restarting.
https://github.com/keybase/client/issues/4317#issuecomment-260665549

**Comment by Stormtalons** [comment]
Thank you for linking to that other ticket... I did search before creating a new one, but didn't find anything.
