### ISSUE TITLE
KBFS client not found on Windows 7 after multiple repair, reboot, install attempts.

### ISSUE THREAD

**Issue by GoJiTa972** [keybase/client#6042]
Hi,

 I couldn't get the K: drive to mount. I tried several things that I saw in different support requests about the "KBFS client not found" message, including repairing the installation and then reboot, update and then reboot, etc. I don't know what to do anymore, and this happens on both of my windows clients (one at work and one at home, totally different network but same OS, Windows 7 professional). Most of the time it's a Driver Install error for Dokan or a Start Error. 

What is the clean way to do this ? Are there any known compatibility issues with antivirus or security software such as Kaspersky Antivirus ?

my log id: 4d33df133248d3e978dc8d1c

**Comment by maxtaco** [comment]
Cc: @zanderz, please investigate?

**Comment by GoJiTa972** [comment]
Here's a more recent logId for the "kbfsdokan -debug -mount-from-service" command *bf468633b6b82b397575cf1c*

**Comment by zanderz** [comment]
Keybase does not think the Dokan drivers (our virtual filesystem implementation) are installed properly, though I do see Dokan1 listed as a filesystem driver in your logs. If you open a command prompt as administrator and enter `sc query dokan1`, what does it say?

You are on Windows 7? Occasionally a required Windows service pack fails to install. I can't quite tell if that happened because your logs are not in English.

**Comment by GoJiTa972** [comment]
Hi, sorry for the late reply

SERVICE_NAME: dokan1
        TYPE               : 2  FILE_SYSTEM_DRIVER
        STATE              : 3  STOP_PENDING
                                (STOPPABLE, NOT_PAUSABLE, IGNORES_SHUTDOWN)
        WIN32_EXIT_CODE    : 0  (0x0)
        SERVICE_EXIT_CODE  : 0  (0x0)
        CHECKPOINT         : 0x0
        WAIT_HINT          : 0x0

Which logs are you talking about ? My system is in French (guilty, adopted Canadian :D ) but the keybase logs seemed to be in English, what am I missing ?

**Comment by GoJiTa972** [comment]
Soooo 45ae766bee632d5339746e1c for the latest log ids

**Comment by GoJiTa972** [comment]
Oh and `sc query dokan1` produces this
SERVICE_NAME: dokan1
        TYPE               : 2  FILE_SYSTEM_DRIVER
        STATE              : 4  RUNNING
                                (STOPPABLE, NOT_PAUSABLE, IGNORES_SHUTDOWN)
        WIN32_EXIT_CODE    : 0  (0x0)
        SERVICE_EXIT_CODE  : 0  (0x0)
        CHECKPOINT         : 0x0
        WAIT_HINT          : 0x0
But still no K: drive (and no, no other drive already uses this letter)

**Comment by zanderz** [comment]
What are the results of entering the following in Keybase Shell?
`keybase kbfsmount get`
`keybase kbfsmount getall`
If `get` shows no drive letter selected, and `getall` shows K: available, it may just be a matter of issuing `keybase kbfsmount set K:`. Your logs look like some configuration error prevented a letter from being selected.

**Comment by GoJiTa972** [comment]
`C:\Users\GoJiTa972\AppData\Local\Keybase>keybase kbfsmount get
K:
C:\Users\GoJiTa972\AppData\Local\Keybase>keybase kbfsmount getall
[I: J: K: N: O: Q: T: U: W: Y: Z:]
C:\Users\GoJiTa972\AppData\Local\Keybase>`

**Comment by GoJiTa972** [comment]
Do you have any history of people having issues with Kaspersky Antivirus and Keybase ? I also have Ext2FS volume manager installed, but no ext 3/4 drives currently connected. And all the internal drives besides C: are located on software Raid 1 arrays (Intel Rapid Storage)

**Comment by GoJiTa972** [comment]
I think I have a lead. The ShadowProtect service (great backup/restore utility IMHO). I uninstalled it from one of my machines and the K: drive appeared at the next reboot. Now it is still installed on my main machine (and won't be uninstalled), would it be possible for you guys to test a keybase install on Windows 7 with this third party software installed ?

**Comment by taruti** [comment]
Confirming that this was caused by Dokan drivers not working properly.

Various versions of different AV products cause issues from time to time with the Dokan drivers (and we try to fix them).

Is https://www.storagecraft.com/products/shadowprotect-spx the version of ShadowProtect you are using?

**Comment by GoJiTa972** [comment]
Oh no, an older one, it's 
ShadowProtect Desktop 5 - Home User Bundle
https://buy.ca.storagecraft.com/ShadowProtect-Backup-for-Desktop-Operating-Systems-C18.aspx

**Comment by GoJiTa972** [comment]
Yup, didn't change anything.

**Comment by GoJiTa972** [comment]
Any news on this subject ?

**Comment by zanderz** [comment]
We've been evaluating an updated set of drivers, available in this experimental installer build: http://s3.amazonaws.com/prerelease.keybase.io/windows/Keybase_1.0.39-20171221112423%2B31648cae1.386.exe
It would be very interesting to see if this helps your issue.

**Comment by GoJiTa972** [comment]
Hi guys, sorry for the late feedback. Unfortunately, it doesn't work, no K: drive.

**Comment by GoJiTa972** [comment]
Would you have another updated exe that I could test ? Not being able to use Keybase with a commonly used backup utility is an obstacle :(

**Comment by zanderz** [comment]
You mean "not being able to mount the filesystem". There are still chat, teams, Git, and filesystem via the command line `keybase fs` commands. Driver incompatibility among 3rd party software (and sometimes Microsoft itself) is a problem for many products on Windows and is unlikely to be resolved soon. We are working on a way to present the filesystem in the GUI to make it easier to use without drivers.

**Comment by taruti** [comment]
The underlying technical issue is Dokan not working with ShadowProtect.

**Comment by GoJiTa972** [comment]
OK guys, thanks a lot for the update. Could this problem be added somewhere in a known issues list ?
Now I have to find a convenient backup solution that would allow me to mount the filesystem at home ^_^;
Keep up the hard work!
