### ISSUE TITLE
I've a process doing tons of io to keybase

### ISSUE THREAD

**Issue by davecb** [keybase/client#6043]
netstat says:
$ sudo netstat -p | grep 36668
tcp        0      0 miles:36668             ec2-52-0-30-77.co:https ESTABLISHED 6157/kbfsfuse  

7KiB out at the moment: I'll capture some of it with wireshark and then kill the process   
$ ps -ef | grep 6157
davecb    6157     1  0 07:46 ?        00:00:05 kbfsfuse -debug -log-to-file /keybase
davecb   17350 14907  0 10:49 pts/1    00:00:00 grep --color=auto 6157
$ sudo kill -HUP 6157
 

my log id: d4953e4663d5197c18b8821c

**Comment by strib** [comment]
This is the keybase file system.  It looks like you have killed the keybase daemon (which runs as process `keybase`, and now the file system is stuck trying to connect to that daemon.

I can't tell what type of OS you're running, but you just need to restart the full Keybase suite to recover I think.  On Linux this is `run_keybase`.

(7KB is a "ton" of I/O??)

**Comment by davecb** [comment]
Thanks: I indeed was missing the daemon, and my network activity indicator went from barely measurable to 7 and stuck there, talking to somebody unfamiliar, named ec2-52-0-30-77.co (;-))
