### ISSUE TITLE
Uploading Large Files to Keybase File System Fails on Windows

### ISSUE THREAD

**Issue by compumike08** [keybase/client#6049]
I am running the Keybase File System on my Windows 10 laptop. Whenever I try to upload a large file to my keybase folder, the file upload starts and progresses normally for a bit, but then it halts with an error that says:
```
An unexpected error is keeping you from copying the file. If you continue to receive this error, you can use the error code to search for help with this problem.

Error 0x800703E3: The I/O operation has been aborted because of either a thread exit or an application request.
```
After that error occurs, if I go to my Keybase folder where I was trying to upload the file to, I'll see the file there as if it was uploaded, but if I try to open the file it will say the file could not be opened (the exact error message I get when trying to open the file will depend on the type of file I tried to upload, and the application I'm using to try and open the file). Also, the file size listed for the un-openable file in my Keybase folder will show as one of two different things, depending on the file type:
- **.zip file:** The file size will listed in the folder will show as however much of the file was able to upload before the upload error occurred.
- **.mov file:** The file size listed in the folder will always show as the full file size, regardless of how much of the file managed to be transferred before the error occurred.
But in both cases, opening the file will be impossible.

Also, in addition to simply copying and pasting the file to be uploaded using Windows Explorer as you would normally do, I also tried copying the file from the Windows Command Prompt, the Keybase Shell, and the Git BASH for Windows terminal command prompt which provides all of the basic Linux commands for file manipulation (i.e. `cp /d/**/*.* /k/private/**/*.*`). All of those methods failed in exactly the same way (the file transfer started okay, progressed for a while, and then cut out part way through).

It is important to note that this problem happens only with larger files. Smaller files I can upload without any problem. I can't really give a specific size cutoff at which point the uploads start to fail, as it isn't really that consistent. Smaller files always complete without a problem, medium files sometimes complete (sometimes I'll get the error message for medium sized files, but if I keep trying a few times eventually the upload will succeed), and larger files almost always fail no matter how many times I try to upload them. As a **very** rough estimate, I would say with confidence that files under about 100 MB or so _usually_ complete without a problem, files between 100 MB and roughly 300-600 MB can sometimes complete but often require multiple attempts, and files roughly bigger than 600 MB rarely complete no matter how many times I try. But again, those are **very** rough estimates, and I would not rely on them being accurate when you try to figure out what the problem is. Also, in that middle range where the files sometimes complete but require multiple attempts, the larger the file is within that range the more likely it is to error out, and the greater the numbers of attempts it will take me to get the upload to succeed (on average).

I've attached a screenshot of the error message below (for the sake of privacy, I cropped out the bottom half of the error dialog box which shows the details of the specific file I tried to upload).

I also used the `keybase log send` command to send you my logs shortly after I made several attempts to upload a file that was roughly 900 MB in size, and the upload failed to complete successfully. I tried to upload it several times in it's native file format, then I zipped the file with WinZip and tried to upload the ZIP file several times. (it didn't compress very well, so the zipped file was only 1 MB smaller than the native file). I tried using the regular Windows File Explorer, as well as using the Git BASH for Windows command terminal using the `cp /d/**/*.* /k/private/**/*.*` command. The error occurred every single time.

Note that the path for the source location of the file on my local computer is the 'D' drive; that is because I have a laptop with both a solid state and a traditional hard drive, and I have all of my regular files and documents on the traditional 'D' hard drive and reserve the 'C' drive for OS files and program files only. However, I did try moving the file from my 'D' drive to my 'C' drive and then trying to upload it to Keybase from there, but I got the exact same error behavior. I mention this here because I tried to upload the file from my 'C' drive **after** I sent my logs to Keybase, so you won't see that attempt in the logs. I wanted to make sure you were aware that I _did_ try uploading the file to Keybase from my 'C' drive and got the same error so you didn't waste your time investigating if the source drive location was somehow related to the problem.

Please let me know if you need any more information.

**Screenshot:**
![screenshota](https://cloud.githubusercontent.com/assets/8941730/23375695/3fc83572-fcf7-11e6-9c84-1b4365f58440.png)

my log id: 0f3516f31b96bbd6aedbbf1c

**Comment by strib** [comment]
Hi @compumike08 -- thanks for the detailed report.  This is a well-known problem, and we are actively working on fixes where writes will depend less on network and CPU speed.  It should be ready in a couple weeks.

**Comment by compumike08** [comment]
@strib: Are there any suggested workarounds in the meantime? Also, is this problem limited to Windows computers, or is it affecting all operating systems?

**Comment by strib** [comment]
Windows and macOS.  Suggested workaround is to try on a faster network or a CPU with more power, depending on your situation.  You can also use programs like `rsync` (not sure what the Windows equivalent is) to resume partial file transfers.

**Comment by compumike08** [comment]
@strib: Okay, I'll give a faster network a try. You said only Windows & macOS are affected. Would uploading from a computer running Ubuntu Linux be immune to this problem?

Also, if I can get the file uploaded over a faster network and/or from Ubuntu, can you confirm that reading large files from Keybase to a Windows computer will not experience this problem at all? I've never personally experienced it when reading from Keybase, but then again I don't really have any large files on Keybase to try and read, since the write issue has prevented me from uploading large files in the first place ;)

**Comment by strib** [comment]
> @strib: Okay, I'll give a faster network a try. You said only Windows & macOS are affected. Would uploading from a computer running Ubuntu Linux be immune to this proble

Things are better on Linux because the OS doesn't impose a timeout for file system operations like Windows and macOS.  There is still a timeout that KBFS uses internally, so if things are super slow you might hit that.  But it will have an easier time, for sure.

> can you confirm that reading large files from Keybase to a Windows computer will not experience this problem at all?

Reading doesn't usually have the same problem, because data is usually read in smaller chunks (also download speed is often faster than upload speed).  Of course, I can't completely rule it out on a 56kbps network, for example...

**Comment by strib** [comment]
Version 1.0.20 has architectural changes that should greatly improve the large write experience.  If you're still seeing problems, please open a new issue.
