### ISSUE TITLE
Files need to be rekeyed

### ISSUE THREAD

**Issue by iandees** [keybase/client#6052]
I'm trying to write to my private keybase files directory and Finder is giving me the notification: 

![image](https://cloud.githubusercontent.com/assets/261584/23377690/eb4bd3de-fcfe-11e6-8786-3b4ed19ff61b.png)

I don't have another device to open the files on: how can I respond to this notification?

Keybase GUI Version: 1.0.18-20170223162556+af0e640

**Comment by strib** [comment]
Hi @iandees -- according to [your sigchain](https://keybase.io/iandees/sigchain), you previously had a device and a paper key, but revoked both of them before making your new device and paper key.  So your private folder is probably keyed for those old devices, and you have no way to get to it now.

We can reset the folder for you manually, but you'll lose all the data in there now.  If you want us to do that, please run this command on an currently-valid keybase device, and substitute the current date and time where indicated:

```
keybase sign -m "<DATE_AND_TIME>: Please reset folder /keybase/private/iandees because all the devices that have access have been revoked."
```

and post the results here.

**Comment by iandees** [comment]
Huh, interesting. I didn't have access to Keybase files until I had this device keyed. :man_shrugging: 

```
BEGIN KEYBASE SALTPACK SIGNED MESSAGE. kXR7VktZdyH7rvq v5wcIkHbsK5cXdE eOaU9oOau4Y2KCN KKkOAYaEEvQzx6j Of6RJR28aZXZpEd u2PW6sI6UVTx4zx 2pZlOD762A0OnOt LuquywFADTUubCp xLqtSvaCMlN1q2r 0rTFYR90gFzeC4S 3uuMLFzu25ZY352 c0kOOEoF44ylED2 klACmIBXXCSPBta kpFCxl1diS7lo5K 4vrHG7f5LThCulN 7tpmOVAMX9a27TL ZhHGSVH7FfEGN0o 6qoP0WFLYdzP1Y1 rJYxjxjZ13TAPJO 8vmPhUmwHY6GT1r pS4tswWu0K2m4Pg RgRIFm7FM0l1Qcs vleS4Oae5LengE7 h2JNxC7BUNJGPBz uKcqAfdc3gx1Zfd jLZ0dKBOOuvU4PU 5PSkVoKynN1efs8 U4DZb9j49EO7e11 9uCi6AXeXAKPUcQ zMvEiHKXa9DglE. END KEYBASE SALTPACK SIGNED MESSAGE.
```

**Comment by strib** [comment]
Ok you should be all set. Please confirm and close this out if it seems ok.

**Comment by iandees** [comment]
Looks good. Thanks!
