### ISSUE TITLE
Can't recover passphrase

### ISSUE THREAD

**Issue by twoqubed** [keybase/client#6062]
I have been trying to recover my passphrase off and on for days. I signed up quite a while ago and I don't remember what my passphrase is. I have tried to recover it using the web site, but I never receive an email.

my log id: e47f737cb1e1758e85c6831c

**Comment by maxtaco** [comment]
We've only sent one email to the keybase account `twoqubed`, and that was a welcome email back in 2016

**Comment by twoqubed** [comment]
Turns out, different username for me. User error.

Thanks for the help.
