### ISSUE TITLE
Cannot log in

### ISSUE THREAD

**Issue by habi** [keybase/client#6089]
I've downloaded the Keybase app (on OS X 10.12.3 (16D32)) and would like to log in.
But I can't, I get the error shown in the attached screenshot.

![screen shot 2017-03-01 at 21 26 07](https://cloud.githubusercontent.com/assets/1651235/23479828/034355fc-fec6-11e6-8945-c9bdbc7cb0ad.PNG)

my log id: 536dbb0dff8f515c6518251c

**Comment by cjb** [comment]
Sorry about that.  We'll check it out, in the meantime I suspect you'll be able to log in (and then use the GUI) by running `keybase login` in the terminal.

**Comment by habi** [comment]
When I want to log in from the terminal (`keybase login`), I get an error about

    Your keybase username or email address: habi
    ▶ ERROR SecretSyncer: no device found for ID=$REDACTED$

**Comment by cjb** [comment]
Thanks, CC @patrickxb.  (Perhaps run log send again, please?)

**Comment by maxtaco** [comment]
We'll try to take a look soon.  Have you recently reset your account?

**Comment by habi** [comment]
I've cleaned up my Twitter account and (by error) deleted the keybase tweet.
I wanted to redo that, and thus 'had' to upgrade the app.
I've now done several tries of logging in, the farthest I get is to the point where keybase complains about my key being expired, even though it won't expire until March 2012, as seen in the attachment.

![screen shot 2017-03-01 at 21 36 51](https://cloud.githubusercontent.com/assets/1651235/23480233/823e5d9c-fec7-11e6-8a40-a9fe72f580b1.PNG)

**Comment by habi** [comment]
A new log is sent as 6dd52641f5d2bb206bb9df1c

**Comment by patrickxb** [comment]
Ok, your key definitely isn't expired.  I see the expiration time of 1537736527 (september 2018).

**Comment by patrickxb** [comment]
Did you enter the passphrase for the PGP private key when it asked for "You need a passphrase to unlock the secret key..."?  

We have had a confusing prompt in the past (I believe a fix for that is in for the next release).

**Comment by habi** [comment]
> Did you enter the passphrase for the PGP private key when it asked for "You need a passphrase to unlock the secret key..."?

I’m not asked to unlock the key, it just complains about it being expired…

**Comment by maxtaco** [comment]
Digging now.  Can you export here your public key?

```
/usr/local/MacGPG2/bin/gpg2 --no-tty --armor --export 090ba12ba7baf36a6c5b4b3df5c29d9fda96595c
```

Thank you!

**Comment by habi** [comment]
You’ll find the public key here: http://davidhaberthuer.ch/pgp/

**Comment by maxtaco** [comment]
are you sure that's the same one we'd get with the above?

**Comment by habi** [comment]
Yes, I just updated it now.

**Comment by maxtaco** [comment]
Oh, I see.  The key you have on keybase's servers actually *is* expired. Can you use the website to update it?  I think that will solve your problem.  Then you'll be able to log in.

**Comment by maxtaco** [comment]
This is what your key on our servers says:

```
pub   2048R/DA96595C 2012-03-18 [expired: 2016-03-18]
uid                  David Haberthür (davidhaberthür.ch) <email@davidhaberthuer.ch>
uid                  David Haberthür (alternate private email) <habi@gna.ch>
uid                  David Haberthür (work email) <david.haberthuer@psi.ch>
uid                  David Haberthür (alternate private email) <david.haberthuer@gmail.com>
uid                  [jpeg image of size 11125]
```

**Comment by habi** [comment]
This was indeed the problem. But I didn't think it could be this from the error messages I got :)
Thanks for pointing me in the right direction, I'm now logged in and everything works as expected.
