### ISSUE TITLE
Auto updater notification failed to update

### ISSUE THREAD

**Issue by otteydw** [keybase/client#6118]
Recently I've seen success with keybase auto-updating itself seamlessly in the background.  For the first time this morning, I received a popup (guessing this is new functionality) where it was telling me that a new version was available and listed the features (which I thought I already had).

So I went through with attempting the update but ultimately got an error window.

![image](https://cloud.githubusercontent.com/assets/11666012/23552138/5d7e86f4-ffe8-11e6-8fbb-6889e99a09ee.png)

The end of the log shows:
```
[35A4:1AD0][2017-03-03T07:47:51]e000: Error 0x80070666: Cannot install a product when a newer version is installed.
```

I'll also mention that the error popup is too small for the error that was displayed.

my log id: 297936253eee72c15ee85b1c

**Comment by cjb** [comment]
Thanks for the report, CC @zanderz

**Comment by maxtaco** [comment]
@zanderz I made an internal ticket CORE-4705 and put it into our sprint with high priority.

**Comment by otteydw** [comment]
ok.  I shut down my laptop to head into the office.  Shortly after I opened it up again, I got the popup.  This time I read it more closely (I assume this was the same one as previous).  Note that the "current" version is blank between the ().
![image](https://cloud.githubusercontent.com/assets/11666012/23555488/21d050d8-fff7-11e6-94ed-3c638f0d68b4.png)

And indeed as I selected "Apply" the installer failed with the same error.

**Comment by zanderz** [comment]
This is the same bug as before, where the updater is not able to get the keybase version. There was a lengthy discussion on https://github.com/keybase/client/pull/5202 with little agreement what to do, but clearly we should try again @maxtaco @gabriel @patrickxb.

Maybe if nothing else we could add a more stringent check after the update is downloaded, to really make sure it needs to be applied.

**Comment by maxtaco** [comment]
I did push a PR to make `keybase version -S` more robust and to not make any RPCs.

**Comment by maxtaco** [comment]
Run `keybase -d version -S` to see what's happening.  It should be way simpler.

**Comment by gabriel** [comment]
If the version command times out (after 20 seconds), then we figure it most be broken?

I suggested doing a check for os.Args in main() and fmt.Sprintf(version) so that nothing is started.

**Comment by otteydw** [comment]
This seems to now be resolved.  The latest update provides a proper version number in the parentheses.  And the upgrade was successful.
