### ISSUE TITLE
Error getting staus

### ISSUE THREAD

**Issue by AndersH3** [keybase/client#6135]
When running <code>keybase login</code>
 <code>ERROR dial unix /run/user/1000/keybase/keybased.sock: connect: no such file or directory</code>

and <code>run_keybase</code> never starts.

<code>ERROR dial unix /run/user/1000/keybase/keybased.sock: connect: no such file or directory</code>

my log id: 2638b0a2c5384f54d9c5a41c

**Comment by cjb** [comment]
@AndresH3 I see this in the log:

stat /home/anonymous/.local/share/keybase/keybase.leveldb: permission denied

**Comment by AndersH3** [comment]
<code>export me=$USER;sudo chown $me -R /home/$me/.local;stat /home/$me/.local/share/keybase/keybase.leveldb</code> solved it. Thanks.

**Comment by AndersH3** [comment]
keybase log send
This command will send recent keybase log entries to keybase.io
for debugging purposes only.

These logs don’t include your private keys or encrypted data,
but they will include filenames and other metadata keybase normally
can’t read, for debugging purposes.

Continue sending logs to keybase.io? (type 'YES' to confirm): YES
▶ INFO ignoring UI logs: GUI main process wasn't found
▶ ERROR API network error: Post https://api.keybase.io/_/api/1.0/logdump/send.json: Connect failed

**Comment by cjb** [comment]
Are you aware of any software or network firewall that might block connections to api.keybase.io?

**Comment by cjb** [comment]
And are you trying to `run_keybase` as root? That doesn't work, it needs to be a normal user.

**Comment by AndersH3** [comment]
@cjb 
firewall disabled and running as user 1000

**Comment by cjb** [comment]
@AndersH3 I can't really help other than to point out that something is stopping you from making https connections to api.keybase.io.

**Comment by AndersH3** [comment]
Connection works now so issue is now https://github.com/keybase/client/issues/6180.
