### ISSUE TITLE
Disconnected

### ISSUE THREAD

**Issue by iangetz** [keybase/client#6137]
First try: I downloaded and installed the Windows client which seemed to work. Tried running a terminal command... long story, I uninstalled the app because it wasn't working.

Second try: Found workarounds online for using Keybase CLI application. Re-installed Windows client. But once opened, even after a restart, the client seems to be unable to connect to the internet. 
![disconnected](https://cloud.githubusercontent.com/assets/7103964/23589286/2f3979f0-0198-11e7-9889-bff36393b60f.png)

my log id: 23e0c46b44d05f257dff561c

I'm excited about this app and will continue trying. I did not find exact situation online so submitting a ticket.

Cheers,
Ian

**Comment by cjb** [comment]
Thanks for the report, CC @zanderz @maxtaco @patrickxb 
```
18096 2017-03-05T11:35:54.254920-05:00 - [DEBU keybase engine.go:66] 1b4 - RunEngine(ListTracking) -> ok
18097 panic: runtime error: invalid memory address or nil pointer dereference
```

**Comment by maxtaco** [comment]
@patrickxb can you take this one?

**Comment by maxtaco** [comment]
```
18103 github.com/keybase/client/go/libkb.(*IdentityTable).GetTrackList(0x0, 0x0, 0x0, 0x0)
18104 C:/Jenkins/workspace/windows-installer_0/src/github.com/keybase/client/go/libkb/id_table.go:1141 +0x2d
```

**Comment by maxtaco** [comment]
i'm already looking at it now, let me just put a PR

**Comment by maxtaco** [comment]
PR up in #6142

**Comment by maxtaco** [comment]
Ok, the PR is in.  I'm slightly concerned this is a workaround of a deeper problem.

**Comment by KidPluto** [comment]
It is common for the chat app to be looking for the internet, before I am connected to the internet.  I had this same issue this morning, with that same cute screen shot above.  It is never clear to me how to stop/start this application.  I have had this working with no problems for a couple of weeks now.  At the moment the problem has cleared.  I have since rebooted.  Thx

**Comment by Sjgouws** [comment]
I am still experiencing this issue, however the occurrences are rare. If for example my connection drops for over 5-10 mins, Keybase will(sometimes) struggle to reconnect. I have to exit and restart the app to get it working.

@KidPluto You can 'quit' out of Keybase via the notifications area icon, click the Keybase icon, click the 'hamburger-ish' menu on the top right and click 'quit' at the bottom of that menu. (Windows)

**Comment by iangetz** [comment]
Hello. I don't think it was connectivity related but I don't know much. I uninstalled and removed every file I could find (again) and started over. It worked this time!

If there was anything in the log submitted, I hope it helps fix issues for the future.

Ian

**Comment by adsactly** [comment]
Hmm, I am having the same issue Keybase won't connect.

**Comment by zanderz** [comment]
@adsactly @joshuaferrara Are you on Windows? One user experiencing this disconnected message had it solved with the fix contained in this special build, if you would like to try: https://s3.amazonaws.com/prerelease.keybase.io/windows/Keybase_1.0.21-20170428134902%2B4280d08.386.exe

**Comment by joshuaferrara** [comment]
@zanderz Yes, I am on windows. That build is working for me!

**Comment by Zenexer** [comment]
Still experiencing this issue on Windows 10 x64.

**Comment by zanderz** [comment]
@Zenexer can you do a `keybase log send` at the Keybase Shell? Have you disabled any Keybase startup shortcuts?

**Comment by Zenexer** [comment]
@zanderz That was the first thing I checked; they were enabled.  I'll send the logs next time I'm at that computer.

**Comment by phoniks** [comment]
I'm helping someone else who is using keybase, and they seem to be having this issue as well.  Was a permanent fix ever discovered?  I wonder if the same exe would function at this point or if it would be too outdated - this issue is almost 2 years old after all.  I'm on a mac, and not super familiar with Windows.
