### ISSUE TITLE
Issue with KBFS

### ISSUE THREAD

**Issue by PokeAcer549** [keybase/client#6171]
When attempting to access my account after logging in via `keybase login pokeacer` and entering my passphrase (and then my paper key via GUI when it asks me to unlock my KBFS Folder), it still asks to open another computer.

My log id: 2afbf4a40e1c086a3217641c

**Comment by strib** [comment]
Hi @PokeAcer549, thanks for the report.  It looks like that folder is only keyed for your devices `Linevast VPS` and `Parent's Tablet`.  If you open Keybase on one of those devices, it will rekey the folder for your new devices (including your new paper key).  Hope that helps.

**Comment by PokeAcer549** [comment]
How am I able to rekey via the CLI? I have it on my VPS, and the other tablet is not yet available for rekeying.

**Comment by strib** [comment]
You shouldn't need to run any commands, all you need to do is make sure Keybase is running and you're logged in on one of those devices.  It should rekey automatically for you in the background.  If it doesn't, please do a `keybase log send` from one of those devices and let us know the ID here.

**Comment by PokeAcer549** [comment]
OK c:

**Comment by PokeAcer549** [comment]
Log ID from my VPS: `bd7ab8c2c35f6be9e371511c`

**Comment by cjb** [comment]
@PokeAcer549 From your log:

3 2016/10/08 13:15:31 mount helper error: fusermount: fuse device not found, try 'modprobe fuse' first

**Comment by PokeAcer549** [comment]
```modprobe: ERROR: ../libkmod/libkmod.c:507 kmod_lookup_alias_from_builtin_file() could not open builtin file '/lib/modules/2.6.32-042stab113.21/modules.builtin.bin'
modprobe: FATAL: Module fuse not found.
```
I checked, FUSE is installed.
![Picture](http://i.imgur.com/5IEtMVj.png)

**Comment by PokeAcer549** [comment]
I'm currently having issues with attempting to login to Keybase on the tablet device which has not been online for months (I reinstalled Keybase)

**Comment by strib** [comment]
@PokeAcer549: I assume "VPS" means "Virtual private server"?  It looks like your host doesn't allow FUSE to run, you might need special permissions, e.g.: https://github.com/TurboGit/hubicfuse/issues/85 and https://github.com/yadayada/acd_cli/issues/222.

If you can't get it working on the tablet, we might be able to run KBFS without needing the FUSE module on the VPS, using the command line.  Something like:

```
KEYBASE_RUN_MODE=prod kbfsfuse -mount-type none /keybase
```

might work?

**Comment by PokeAcer549** [comment]
There we go: Since my tablet corrupted itself I had to reinstall keybase and that needs rekeying, however the Keybase app is now running in a screen using your command, and it's telling me that rekeying is occuring
!(Screenshot of the command)[http://i.imgur.com/GF3T0Uo.png]

**Comment by PokeAcer549** [comment]
Closing since no TLFs need re-keying :D

**Comment by strib** [comment]
Great!  I can confirm on our end that your folders seem to be rekeyed to your new devices now.
