### ISSUE TITLE
App will not show a login window...

### ISSUE THREAD

**Issue by MrHerisson** [keybase/client#6174]
Keybase GUI Version: 1.0.18-20170223121400+af0e640

First time use today was fine but now, the app is stuck on loading..the tray icon shows a login button but nothing is happening when pressed..will try to uninstall and reinstall

**Comment by cjb** [comment]
Thanks for the report, please could you try running `keybase log send`?  And, which OS are you using?

**Comment by davidcraig** [comment]
This just happened for me also on Windows 10 Client.

**Comment by cjb** [comment]
Thanks, CC @zanderz

**Comment by davidcraig** [comment]
Ok, you may also know but just for reference, if I try keybase login from the keybase shell it gives error EOF

**Comment by cjb** [comment]
Yeah, makes sense.

**Comment by davidcraig** [comment]
I have downloaded the latest version of the installer (which was 31kb larger than the one I had) and the issue is now resolved for me.  Thanks for the info @cjb

**Comment by cjb** [comment]
Cool, glad it's fixed for you.
