### ISSUE TITLE
No read access to public chats

### ISSUE THREAD

**Issue by coldwaterq** [keybase/client#6218]
If I try to run 

keybase chat read --public marcopolo

I get:

marcopolo: 2017-03-10T17:56:52.878587-08:00 - [ERRO keybase standard.go:208] 001 GetConversationForCLILocal error: error unboxing chat message: coldwaterq does not have read access to directory /keybase/private/marcopolo

I didn't expect to see this for a public message so I thought I should report it. I am on Windows in case that matters.

**Comment by strib** [comment]
@mmaxim: I'm mystified where this error message is coming from.  I can reproduce this for `marcopolo` locally, and in the KBFS log all I see are successful accesses to the public folder.  A chat person should probably triage this first, but let me know there's anything I should look at.

**Comment by mmaxim** [comment]
@MarcoPolo probably created that public chat when there was a bug in chat that would make these behave like private chats. I'll need to clear that conversation and Marco can re-create it.

**Comment by mmaxim** [comment]
This should be fixed now, although the conversation is now empty.
