### ISSUE TITLE
Event timeout of some sort

### ISSUE THREAD

**Issue by kode54** [keybase/client#6310]
I received an event timeout of some sort while rekeying my kbfs with a paper key, possibly because I took more than 30 seconds to retrieve my paper key for the prompt.

my log id: 9153036d0b0892abd8ab2c1c

**Comment by strib** [comment]
@kode54: I don't think we require a 30-second limit for entering your paper key anywhere.  Could you explain more about what you saw?  Was it a popup message, or did a file system operation fail?  Is anything still broken for you, or are you just reporting seeing the message?

**Comment by kode54** [comment]
It was a notification that popped up so quickly that I didn't get a chance to screen grab it. If I see it again, I'll re-open the report and submit more logs.
