### ISSUE TITLE
Stuck loading after deleting account

### ISSUE THREAD

**Issue by TheLazyHatGuy** [keybase/client#6311]
I'm not 100% if this is a bug or my bad connection but I deleted my old account using the website and when I went to login to my new account on the Windows client, it is stuck at the loading screen

my log id: c93b1c0ea4190b6281462c1c

**Comment by zanderz** [comment]
If you right click the tray icon and quit from the menu on the popup widget, then restart Keybase (this is just the GUI part) from the start menu, does it work?

**Comment by TheLazyHatGuy** [comment]
No. It is still stuck at the loading screen

**Comment by zanderz** [comment]
ah, I see on second look, your background service's log stops on March 8, though the GUI one has entries from the 21st. It is unclear why this should be, except there is evidence of network unavailability at times, and this can cause problems we're still working on. 

Meanwhile, I think the service should be restarted. You could either reboot or kill both lower-case `keybase.exe` processes and issue `keybase ctl watchdog2` at the Keybase Shell. Once the service is working, you may need to also do `keybase logout` now that your account has changed.

**Comment by TheLazyHatGuy** [comment]
I can't find Keybase listed as a service only a process

**Comment by TheLazyHatGuy** [comment]
I managed to reinstall it and now it lets me login but for some reason the KeyBase Web Drive isn't working

**Comment by TheLazyHatGuy** [comment]
It turns out I was just missing my paper key. Thanks for your help
