### ISSUE TITLE
Cannot use chat

### ISSUE THREAD

**Issue by tperunsky** [keybase/client#6316]
When I try to use chat, I get an error like this: http://take.ms/eXX32
I'm not 100% sure, but I think other error messages have showed up too, but I never screencapped them. I tried reinstalling the app, but it didn't help. Sometimes the chat window simply stays stuck at "digging ancient messages". 

my log id: adaefbea99b59e09782c101c

**Comment by cjb** [comment]
Thanks for the report.

@strib and @mmaxim, the (truncated?) error looks like:
```
++Chat: | localizerPipeline: error localizing: convID: XXX err: error unboxing chat message: This device does not yet have
```

**Comment by strib** [comment]
Looks like you are trying to read a folder that another Keybase user made for you before you installed Keybase on any of your devices, but that user hasn't yet come back online and keyed that folder for you since you installed it.  You should ask him/her to sign into Keybase to give you access.

@cjb: wonder why this isn't surfacing in the GUI...

**Comment by tperunsky** [comment]
I am trying to create a new chat though. There were some messages from one user, but I also tried creating a new chat with that user and a new chat with another user. You can try sending a test message to me at `tperunsky`. I have keybase running right now.

**Comment by strib** [comment]
@tperunsky: yep, it looks like both users you tried had the same issue -- they both made KBFS folders or chats with you before you installed any devices, and now they need to come online to rekey the folders before you can access them.

I sent you a test message, let me know if you receive it.

**Comment by tperunsky** [comment]
@strib I received your message. 
So if I understand this correctly, it means I cannot send messages to those users until they come back online.

**Comment by strib** [comment]
That's correct.  I thought we surfaced that a little better in the UI but I guess not.  Sorry for the inconvenience.

**Comment by tperunsky** [comment]
@strib No problem. I suppose I can close this.
