### ISSUE TITLE
Unable to login in Linux terminal

### ISSUE THREAD

**Issue by pyratebeard** [keybase/client#6333]
Installed keybase for Linux as per instructions. Attempt to run `keybase login` but after entering username am presented with following error:

 `ERROR Failed to get getpin greeting: EOF`

Running Arch Linux (4.9.11-1-ARCH) on Asus Eee netbook.

my log id: 27858f8eee1f0431495af41c

**Comment by maxtaco** [comment]
There's something wrong with the pinentry installed on your machine.  Try disabling it:

```
keybase config set -b pinentry.disabled 1
```

**Comment by pyratebeard** [comment]
That has worked, cheers @maxtaco
