### ISSUE TITLE
GUI stuck on 'loading'. Archlinux (aur/keybase-bin)

### ISSUE THREAD

**Issue by jck** [keybase/client#6343]
I started keybase using `run_keybase`

my log id: e5feba2fdba3b465bed9211c

**Comment by cjb** [comment]
@jck The error is:
```
110 2017/03/23 14:58:06 mount helper error: fusermount: fuse device not found, try 'modprobe fuse' first
```
Perhaps you compiled your own kernel without FUSE support, or somehow disabled FUSE.

**Comment by jck** [comment]
Turns out I forgot to reboot after updating the kernel.

Sorry for the noise!
