### ISSUE TITLE
Need folder reset

### ISSUE THREAD

**Issue by fgsch** [keybase/client#6368]
Can you please reset my private folder?
Thanks.

Statement:

Mon 27 Mar 2017 00:32:27 BST: Please completely reset folder /keybase/private/fgsch because I no longer have access to any of the devices it is keyed for.

Signed message:

BEGIN KEYBASE SALTPACK SIGNED MESSAGE. kXR7VktZdyH7rvq v5wcIkHbrwbR9mW SmOk3V9EN5OcGRP tLBgLHROJCmbu5I 8OFIxMLPzYliDMd a0vdF4VtOrHJkBr LrEsurXvWdDbotw hqxhzv0p4TRdWEA T8eJcP1pHn85wbu NDU9VjANj5LMKWz Nx4ouVuSYwe29DE bPYEBcMhbbKzpm9 ouvMinGrlRH7xfU 5GDauGifL98Dfyf ew2jqD4T3Z4zdiT VOk8G7HOQMCCzEo gRET4nJuidl2uSj 00EQQ9rj0oGCn6N 1PrJRDJWV07ujq3 fHRZf4wcPvXVUNt LN6qgmZweKTKmzt WnSwemE3zTnMR9B 6vygJRtMqHJWqGN 6RqOav5EUjrPej3 wmg1YKm57tPYA5n 53aZOAngenG2QQU TsYmiYniTPok807 SCavR5V5leG0j4R kqQ9KvMs8go0Ez2 ReDC9PzV96Yo7TJ VRzS2V3dcInUChU hTsYDWykBW5t3ax 8mw4. END KEYBASE SALTPACK SIGNED MESSAGE.

**Comment by strib** [comment]
I've reset your private folder.  Please check it out and close this if everything looks ok.

Would you be willing to give us some context about how you lost all the devices (including the paper keys), and any feedback for us as to how we could change things to have minimized the risk of that happening?  Thanks!

**Comment by strib** [comment]
By the way, I notice that one of your remaining private folders is with a user that doesn't have any device keys. That means that user won't be able to rekey it for you, even once they add a device, since only your (lost) devices can read it.

If you want me to reset that one as well, please append another signature here. If you want to keep the other username private, you can encrypt it for me (strib@github) before you post, or you can put it in /keybase/private/fgsch,strib.

**Comment by fgsch** [comment]
Thanks a lot. It's working now.

Regarding the first part, it was self inflicted. Long story short, I switched to a new laptop and the previous one was zeroed before I have any chance to migrate things.

As for the folder, here's the signed message:

BEGIN KEYBASE SALTPACK SIGNED MESSAGE. kXR7VktZdyH7rvq v5wcIkHbrwbR9mW SmOk3V9EN5OcGRP tLBgLHROJCmbu5I 8OFIxMLPzZDmCoD QEUDX0EJcC50VmW FuW1VByCDYj9wGL hdF9G5PZlKFbaz6 durtyFWGLkCGabR WaD8DcCdtndFJ6u 5L7uMY491B2qKMr lhLKKkk3txPY02e BAn2sWSPzdWAq7P ZAKDmd30OqHZKsJ U3iFwNylyWlqf3i tF91HX9iLSl52Wn uGO8503aVwwPfd7 nIBWa3kYkqZTlPi Qp0GKLvui7OgDmP hcxLTP9u25Z9ZBZ UBKbm7K1gCfcZPg EELqT3BuXOvVXTB A1I87YFCuRroe. END KEYBASE SALTPACK SIGNED MESSAGE.

Statement:

Please reset the private folder I have with <username>.

Thanks a lot and sorry for the problem.

**Comment by strib** [comment]
Looking at your folders again, I think I was wrong.  The folder I was thinking of actually is missing keys for _you_, and not the other user.  I got it backwards. Sorry for the confusion, I think you're all good now.
