### ISSUE TITLE
OS X client never starts

### ISSUE THREAD

**Issue by anderm3** [keybase/client#6403]
I reinstalled the app and rebooted my machine. The app would appear in the system tray and would open an application window but the window was all white and never did anything.

my log id: 77bc92016f744d69bb8e7f1c

**Comment by cjb** [comment]
Thanks for the report, CC @gabriel

**Comment by anderm3** [comment]
It may be worth noting that Keybase does run on my MacBook Air running Sierra 10.12.3 but I am experiencing this issue on an iMac which is also running 10.12.3.  I likely don't have the exact same mix of third party software on both machines but both have homebrew and are otherwise fairly stock.

**Comment by gabriel** [comment]
Can you try a recent prerelease version?
https://prerelease.keybase.io/darwin/Keybase-1.0.20-20170410190644%2B82957bf.dmg

**Comment by gabriel** [comment]
@anderm3 Are you still having this issue with a more recent build from https://keybase.io?

**Comment by anderm3** [comment]
<img width="827" alt="screen shot 2017-05-08 at 2 11 43 pm" src="https://cloud.githubusercontent.com/assets/2721335/25818333/4b234532-33f8-11e7-915d-f7b1629ef386.png">

**Comment by anderm3** [comment]
<img width="824" alt="screen shot 2017-05-08 at 2 15 23 pm" src="https://cloud.githubusercontent.com/assets/2721335/25818517/d084af72-33f8-11e7-94cc-92dd2a22c882.png">
Looks like both the version linked earlier in the thread and the latest release on the site still both get stuck for me drawing the login UI.

**Comment by gabriel** [comment]
Can you post another `keybase log send` from the latest version?

**Comment by anderm3** [comment]
I pushed log ID c569f8c09313cddc4164431c that generated this on the console;
```
▶ INFO ignoring error getting keybase status: There were multiple errors: dial unix /Users/mra/Library/Group Containers/keybase/Library/Caches/Keybase/keybased.sock: connect: no such file or directory; dial unix /Users/mra/Library/Caches/Keybase/keybased.sock: connect: no such file or directory
▶ INFO ignoring UI logs: There were multiple errors: dial unix /Users/mra/Library/Group Containers/keybase/Library/Caches/Keybase/keybased.sock: connect: no such file or directory; dial unix /Users/mra/Library/Caches/Keybase/keybased.sock: connect: no such file or directory
```
I verified that the directory did exist but it did in fact not contain the socket.

**Comment by gabriel** [comment]
Can you try to update to the latest, by running:

```
/Applications/Keybase.app/Contents/SharedSupport/bin/updater check
```

**Comment by crunchie84** [comment]
I'm facing the same issue as @anderm3 

I previously had keybase installed using brew, removed it and the GUI from my applications folder before downloading the newest version from keybase.io and droppign it in the root of my Application folder.

Current version of keybase installed is `Client:  1.0.22-20170515141716+b608f0e`
Invoking `/Applications/Keybase.app/Contents/SharedSupport/bin/updater check` resulted in 
```
2017/05/19 11:14:30 DEBG Received update response: updater.Update{Version:"1.0.22-20170515141716+b608f0e", Name:"v1.0.22-20170515141716+b608f0e", Description:"....(removed by @crunchie84)...", InstallID:"c3319a8e21edac1586c19a3ce9cde9cd04704d8ac6efa61d", RequestID:"", Type:0, PublishedAt:1494857836000, Props:[]updater.Property(nil), Asset:(*updater.Asset)(0xc42017a870), NeedUpdate:false}
```

I'm running `Mac OS X El Capitan, 10.11.6`.

My log id is `7575cb464b5f5a263a84b21c`

**Comment by gabriel** [comment]
You have to run the UI app in order for the command line to work, since we need to show identify warnings if tracker statements have changed.

It's currently an all of Keybase or nothing approach. We want to have a standalone command line version in the future, but now you need to have the Keybase.app running.

**Comment by crunchie84** [comment]
@gabriel maybe it was a bit unclear from my comment. Invoking the UI using `open /Applications/Keybase.app` shows the Keybase logo in the menu bar and the main window opens. But the main window does not load; it's contents stays empty (white). Clicking on the Keybase icon in the menu bar does not open the drop down menu (showing your folders, chats etc).

**Comment by gabriel** [comment]
@crunchie84 Oops, misunderstood... Can you try doing...

```sh
keybase ctl stop
# And then re-open
open /Applications/Keybase
```

If still messed up, can you do another log send?

Thanks!

**Comment by crunchie84** [comment]
@gabriel somehow the app became un-stuck. Doing `keybase ctl stop` & restart also now returns the application to a working state. Very weird

**Comment by gabriel** [comment]
@anderm3 Are you still having problems on latest version of the app? If so please re-open.

**Comment by dctucker** [comment]
```
0 ~$ /Applications/Keybase.app/Contents/SharedSupport/bin/keybase ctl restart
▶ INFO Stopping Keybase app
▶ INFO Terminated Keybase [33792]
▶ INFO Uninstall mount: /Volumes/Keybase (casey)
▶ INFO log directory "/Volumes/Casey iMac HD/Users/casey/Library/Logs" is writable by current user
▶ INFO log path file "/Volumes/Casey iMac HD/Users/casey/Library/Logs/keybase.start.log" doesn't exist yet (should be ok)
▶ INFO paths in plist look ok and have valid permissions
▶ INFO Saving /Volumes/Casey iMac HD/Users/casey/Library/LaunchAgents/keybase.service.plist
▶ INFO Starting keybase.service
▶ INFO Waiting for keybase.service to be loaded...
▶ ERROR stat /Volumes/Keybase (casey): no such file or directory
▶ INFO log directory "/Volumes/Casey iMac HD/Users/casey/Library/Logs" is writable by current user
▶ INFO log path file "/Volumes/Casey iMac HD/Users/casey/Library/Logs/keybase.updater.log" doesn't exist yet (should be ok)
▶ INFO paths in plist look ok and have valid permissions
▶ INFO Saving /Volumes/Casey iMac HD/Users/casey/Library/LaunchAgents/keybase.updater.plist
▶ INFO Starting keybase.updater
▶ INFO Waiting for keybase.updater to be loaded...
▶ INFO Opening /Applications/Keybase.app
▶ WARNING | Changing current working directory because path for dialing is too long
▶ ERROR stat /Volumes/Keybase (casey): no such file or directory
```

Encountering this on latest Mac OS X High Sierra.

**Comment by dctucker** [comment]
Log ID `5b9302e7ae1a3e71b0cd0c1c`

**Comment by mikesperber** [comment]
See this too:

Log ID 7e32c77c1ce91d21c911591c
