### ISSUE TITLE
Windows Client - Enable to Login (Database Provisioning Error / Error 505)

### ISSUE THREAD

**Issue by tonyrayo** [keybase/client#6440]
Hi, I just recently signed up with Keybase (via website; e-mail confirmed) however I'm having trouble actually logging into the Windows client (1.0.20-20170317111045+6cc2f52).

The same results happen whether I use the GUI or the CLI.

If I choose to enter my username on either client, it immediately throws an exception.  GUI says "There was a provisioning error" then below that "Unknown Error: DB error"; CLI simply says "ERROR DB error (error 505)".  If I instead enter my e-mail address, it seems to accept this, but then throws the same error as before when I correctly enter my password.

:heart: bleeding-edge tech! 😄

**Comment by cjb** [comment]
Hi!  Sorry about this, we're in the middle of an outage at the moment.  Should be back up soon.

**Comment by mnaser** [comment]
It's backup and running for me!

**Comment by tonyrayo** [comment]
Same; everything is working great and I can dive in (well, during my lunch break)!  I thought it actually had to do with a creation of a local db; if I knew it was actually trying to access the site then I would have left it be for an hour and tried again then (the Internet version of "unplugging something and then plugging it back in").
