### ISSUE TITLE
Error signing up

### ISSUE THREAD

**Issue by whmountains** [keybase/client#6441]
I got a DB error at the end of the signup process.  Looks like it worked anyway though since I got a confirmation email.

my log id: 36048e3323bff93999dd141c

**Comment by whmountains** [comment]
When trying to sign in with my new credentials, I get the following error:

**There was an error provisioning**
Unknown error: DB error

**Comment by cjb** [comment]
@whmountains Thanks, we're in the middle of an outage so it's not your fault.  Should be back soon.

**Comment by cjb** [comment]
(You should be able to login now.)

**Comment by whmountains** [comment]
Thank you!
