### ISSUE TITLE
"quit" doesn't actually quit keybase

### ISSUE THREAD

**Issue by ketzacoatl** [keybase/client#6447]
A core tenant in building trust with the software you run is being able to tell it what to do, and to have it respect your wishes. Given the critical nature of what Keybase does for its user, I only want to run keybase when I am actively using it. EG, I don't want it running idle when I'm not looking to use keybase.

Thus, when I am done using the keybase GUI, I tell it to "quit", but this doesn't actually quit Keybase, it only closes the GUI. After using the "quit" button in the GUI's menu, I still see the icon in my desktop panel. This erodes my trust (I'm telling it to quit, but it hasn't actually quit). Further, I then see that the icon in my desktop's panel has a menu, and there is a "quit" button here.. but when I tell it to "quit", while the icon disappears, `ps` tells me it is still running:

```
ᐅ ps aux | grep Keybase -i
... keybase -d --log-file=/home/user/.cache/keybase/keybase.service.log service --auto-forked
... kbfsfuse -debug -log-to-file /keybase
```

If I tell keybase to quit, I expect it to quit everything and completely shutdown. I should not have to use `kill` to get keybase to stop running.

Given that we're talking about GPG and crypto, I'm sure you understand the importance of trusting the software you run. While I have a great deal more trust for keybase than I do other software, the stakes are high and so are my expectations. Given those circumstance, rather than just being a little bit annoyed, this type of issue makes me skeptical of the keybase client.

Is there a significant reason to justify the app's quit not completely killing the software? Eg, is this "by design"?

**Comment by ketzacoatl** [comment]
Another data point: I just found `keybase ctl stop`, and that stops/kills the client, but doesn't do anything about `kbfsfuse`.

**Comment by cjb** [comment]
I agree that having the panel icon's Quit quit all of Keybase would be better.  That's actually what we do on Windows and Mac.  We don't do it on Linux because we haven't integrated with a supervisor (like systemd) yet.  We plan to do something like that in the future, though.

**Comment by ariddell** [comment]
I uninstalled keybase after I saw this behavior. It's especially troubling / hard to understand if one is only using the command-line.

**Comment by jean** [comment]
I found this issue after `powertop` showed idle keybase as one of the processes consuming significant power.

**Comment by daveloyall** [comment]
I tried `File > Quit` in the GUI.  The I tried `sudo systemctl stop keybase.mount`, which did something...  Then, as a last resort, `killall kbfsfuse; killall keybase; killall Keybase`.  That did it.

For starters, please provide a shell script for properly shutting down all keybase-related processes.

**Comment by maxtaco** [comment]
‘keybase ctl stop’ should work.

**Comment by zanderz** [comment]
Internal windows issue: CORE-3563

**Comment by daveloyall** [comment]
Hi, @maxtaco.  Thank you for your suggestion.  Unfortunately, it didn't work.

It does stop a process named `keybase` (lower case).  It does not stop the four `Keybase` processes nor the `kbfsfuse` process.

I'm using `Client:  1.0.34-20171012160058+c282fb227`.

Cheers, thanks!

**Comment by jessereynolds** [comment]
Still hitting this problem on Mac. I can quit the app and it looks like it's quit but if I use Spotlight or Alfred to launch the app again it takes me back to where I was in the UI, it clearly had not quit. 

I have to use Force Quit to actually quit it. 

Is this really intended behavior?

**Comment by heronhaye** [comment]
Reposting from https://github.com/keybase/client/issues/3773:

(On Linux)
After the latest update, `run_keybase -k` will shut down all Keybase processes unconditionally (service, kbfs, gui, redirector).

If you're using systemd (check with `systemctl --user status keybase`), you can use it to stop and start the four units independently.
```
systemctl --user stop keybase.gui
```
just stops the gui. The other ones are `keybase`, `kbfs`, and `keybase-redirector`.

Additionally, if you're using a graphical DE and you want to turn autostart off, you can do this in your DE settings or in
```
keybase ctl autostart --disable
```

There's more information available at https://keybase.io/docs/linux-user-guide. Let me know if these features aren't working for you or if you have a question or suggestion.

**Comment by scottlowe** [comment]
Right let's get straight to the point here. There are multiple issues now, concerning the disingenuous behaviour of the Keybase app. It does not quit when asked too. Moreover on the Mac which I'm using, the keybase menu app continues to run and we then have to quit that too.  I never asked for the menu item either.

I'm going to come out and say it: As far as I can tell the developers of Keybase have no intention of changing this behaviour  - this issue has been open for 2 years. It is deliberate.

I agree with @ketzacoatl that "A core tenant in building trust with the software you run is being able to tell it what to do, and to have it respect your wishes".

Well you've lost my trust.

Additionally, I've just discovered that the Keybase app adds itself as a Login item when I quit the main app. And if I remove the Login item after the main app is quit, and then quit the Menu / Helper item too, that also re-adds the Login item as it quits. I really didn't expect this kind of shady background behaviour of doing things without telling me, but I've seen enough now to get the measure of the organization behind keybase, which has also been borderline spammy with its emails to me.

But there's good news: Rest assured, guys that you won't be seeing anymore complaints from me here, because this is your third strike and you're out!

Deleting Keybase from my system. I will never use it again.

**Comment by heronhaye** [comment]
@scottlowe 
If you open the popup via the system tray, there should be a hamburger menu at the top right with an option for "Quit App". After you click that, does `ps aux | grep -iE 'keybase|kbfs'` show any output for you?

**Comment by scottlowe** [comment]
@heronhaye Thanks for the pointer, but I'm currently using the macOS version. I probably shouldn't have confused a thread what is primarily a Linux thread with Mac stuff.

The original related complaint (referenced in the other issues) is that we shouldn't have to go to a Mac menu bar or else Linux / Windows system tray when we've already asked the main app to quit.

That said, I was fully annoyed at the time and wanted to pull together all of the related issues here, but in retrospect, (and not at all annoyed today) I've probably made it more confusing for anybody trying to follow all this. Sorry for adding to the complexity!

**Comment by heronhaye** [comment]
No problem, the flow I mentioned should work on Mac though.

**Comment by ketzacoatl** [comment]
Another data point: After running `keybase ctl stop`, `/usr/bin/keybase-redirector /keybase` is still running. That's likely related to `kbfsfuse`.

The fact this is still an issue is a bit more troubling than the original issue.

*Could the keybase devs share with us, some more info about your opinions on this issue?*

What is the reasoning behind this design decision? If it just "happens to be", is there an objection to making `quit` fully quit the app? Is this not important, or why is the issue still unresolved? Should we close it as "won't fix", or is there a WIP plan forming for what we _would_ do to resolve this issue?

Thanks

**Comment by heronhaye** [comment]
@ketzacoatl 
No, this is a bug in the Linux version: see the PR at https://github.com/keybase/client/pull/16680/files#diff-ee2d20b1f4704cde4fb8767209b66496R1047. 

For now, please run `run_keybase -k` to stop all Keybase processes, including the redirector. Also, yes, it is related to kbfsfuse (it provides the `/keybase` mount).

**Comment by ketzacoatl** [comment]
Thanks for the pointer on `run_keybase -k`, that's nice. I wish the gui menu would just do that. Any word on why that isn't the case?

**Comment by junderw** [comment]
@ketzacoatl It was an unintentional bug / side effect of Linux builds only.

Windows and Mac builds stop all processes when you click quit on the tray icon.

**Comment by heronhaye** [comment]
@ketzacoatl working on it: https://github.com/keybase/client/pull/16949.

**Comment by ketzacoatl** [comment]
> It was an unintentional bug / side effect of Linux builds only.

That's the assumption, but assumptions are problematic, and not good enough when we're talking about the level of trust that we need for software that does what Keybase does.

I want to believe (and do!) the devs have good intentions, but please, just look at the history in this ticket.. it doesn't quite align with what you would expect from a small mistake that is actually extremely significant. This also isn't the first day we're opening and commenting on this issue... and look how many other users created their own versions in the 2 years since I opened this issue. So, for those reasons, I don't find your comment all that compelling.

**Comment by heronhaye** [comment]
Keybase 4.0 has a Quit Keybase button in the main app in the GUI.

![2019-05-08-164233_367x601_scrot](https://user-images.githubusercontent.com/28712558/57407074-5671eb80-71b0-11e9-9713-581f9baa3808.png)

Also, `keybase ctl stop` should work as expected on Linux.

**Comment by ketzacoatl** [comment]
@heronhaye, but if you run `ps aux | grep keybase`, is there anything running?

The version of keybase I have also has "Quit App" in the gui, but the issue is that _it doesn't actually quit all of keybase_.

For example after opening and closing keybase a bunch, logging in each time and all that, we can see there's a long-lived instance of keybase that doesn't go away. Even after quitting, it's still running:
```
$ ps aux | grep keybase
... 101:45 /usr/bin/keybase --use-default-log-file --debug service
...  0:01 /usr/bin/keybase-redirector /keybase
```

**Comment by heronhaye** [comment]
@ketzacoatl Yes, this is a bug that was fixed. Please upgrade (`keybase version` should return 4.0.0) and try again.
