### ISSUE TITLE
Keybase app constantly loses connection

### ISSUE THREAD

**Issue by whmountains** [keybase/client#6460]
I initially encountered #6441.  That seems to be fixed, but I still can't log in because the page keeps reloading:

![keybase error](https://cloud.githubusercontent.com/assets/8680147/24588472/300294ee-179f-11e7-9304-c2c6a5cb24b1.gif)

Incidentally, IconServicesAgent also unexpectedly quit when the app launched.  I'm not sure if that's related or not.

I also want to clarify that this isn't a complaint.  I understand that this is Alpha software and these issues are expected.  I'm simply reporting them to help you guys out.

**Comment by cjb** [comment]
Thanks for the report.  Please could you run `keybase log send` and tell us the ID?

**Comment by whmountains** [comment]
```
This command will send recent keybase log entries to keybase.io
for debugging purposes only.

These logs don’t include your private keys or encrypted data,
but they will include filenames and other metadata keybase normally
can’t read, for debugging purposes.

Continue sending logs to keybase.io? (type 'YES' to confirm): yes
▶ INFO ignoring error getting keybase status: There were multiple errors: dial unix /Users/mmc/Library/Group Containers/keybase/Library/Caches/Keybase/keybased.sock: connect: connection refused; dial unix /Users/mmc/Library/Caches/Keybase/keybased.sock: connect: no such file or directory
▶ INFO ignoring UI logs: There were multiple errors: dial unix /Users/mmc/Library/Group Containers/keybase/Library/Caches/Keybase/keybased.sock: connect: connection refused; dial unix /Users/mmc/Library/Caches/Keybase/keybased.sock: connect: no such file or directory


------------
Success! Your log ID is:

  c83ea436a3193353e9c4f41c

Here's a URL to submit new bug reports containing this ID:

  https://github.com/keybase/client/issues/new?body=[write%20something%20useful%20and%20descriptive%20here]%0A%0Amy%20log%20id:%20c83ea436a3193353e9c4f41c

Thanks!
------------
```

**Comment by cjb** [comment]
Thanks for the log send!  Please could you try running `keybase logout` and `keybase login`?  Looks like your account's a bad state due to the server outage that happened during your signup, and this should fix it.

**Comment by whmountains** [comment]
This is what happens when I do that: https://asciinema.org/a/eoorwig88y0jx9dj1fjpuscwg

**Comment by maxtaco** [comment]
Ah, your service is crashlooping before it can get to logging you out.  We're going to fix this but I want to unlock you now if possible. Try this:

```
keybase --standalone logout
```

Thanks for your help and patience!

**Comment by whmountains** [comment]
I'm in!  Thanks for you help.

I had to use the standalone flag for both the login and logout commands, but that fixed the problem.
