### ISSUE TITLE
Coinbase proof is bad but I don't see it on website

### ISSUE THREAD

**Issue by fidian** [keybase/client#6520]
When I check my own identify, I see that the coinbase proof is bad and coinbase.com/fidian doesn't exist.

When I check on the website, I do not see a coinbase proof.

Is it possible that coinbase removed the userid shorthand in their URIs? I don't see the ability to set that option nor even my username in coinbase. It looks like they are strictly using email address now. Is there a way to remove this proof or change the verification somehow? I don't see the option for it in the command-line client.

![image](https://cloud.githubusercontent.com/assets/428348/24767887/41b1332e-1ac6-11e7-9c8f-03a0c143f268.png)

**Comment by plttn** [comment]
Coinbase abruptly killed public payment profiles, and as such it no longer works.

[More info here](https://keybase.io/blog/abrupt-termination-of-coinbase-support)

**Comment by fidian** [comment]
Great link. When will the desktop client be updated so my co-workers stop
getting the alerts in red?

**Comment by maxtaco** [comment]
It should already be --- which version are you running?

**Comment by fidian** [comment]
I was out of date because I didn't run the software update in a while. Everything is working fine and I thank you for your time.
