### ISSUE TITLE
client: pgp export doesn't work if you have multiple keys

### ISSUE THREAD

**Issue by arjunravinarayan** [keybase/client#6548]
If I run `keybase pgp export` when I have multiple keys,
the command fails with
```
▶ WARNING Found several matches:
user: Arjun Narayan <arjunravinarayan@gmail.com>
4096-bit RSA key, ID B0887D53E44DE44B, created 2016-07-29

user: Arjun Narayan <arjunravinarayan@gmail.com>
4096-bit RSA key, ID 8B5C75D0E61DFFE8, created 2016-07-29

user: Arjun Narayan <arjun@cockroachlabs.com>
4096-bit RSA key, ID BBF9D487C942BB14, created 2016-08-01

user: Arjun Narayan <arjunravinarayan@gmail.com>
4096-bit RSA key, ID F1D713E5941DF634, created 2016-12-23

user: Arjun Narayan <arjunravinarayan@gmail.com>
4096-bit RSA key, ID A67FEE834B7168D6, created 2017-04-07

▶ ERROR Specify a key to export
```
However, `keybase pgp export A67FEE` (or any variation thereof) returns
`Error parsing command line arguments: export doesn't take args`

There is no way to specify a key.

**Comment by arjunravinarayan** [comment]
Upon further inspection of the code, it appears that if you use the `--query` option and specify a key (with an exact match, not just a prefix) export works. The documentation displayed on `--help` could be improved to specify this. Closing the issue in any case.

**Comment by 0xdevalias** [comment]
This is still undocumented as far as I can see. Other commands just have a `-k` to select the key.. that would be the most obvious solution here.. I'd argue this should be reopened (but among the 1100+ open issues that's probably irrelevant..)

For those wanting the exact command: `keybase pgp export --query YOURHASHHERE`
