### ISSUE TITLE
`keybase pgp select --no-import` asks for a passphrase for "import of key"

### ISSUE THREAD

**Issue by JustATrick** [keybase/client#6549]
I'm trying to get my public pgp key into keybase, and I don't want to import my secret key. When I run `keybase pgp select --no-import` I'm asked for my passphrase twice. The first time is by the standard dialog that gpg uses on my system. After I comply I'm asked a second time by keybase, which says "Reason: Import of key into Keybase keyring".

![keybase's passphrase prompt](https://sinking.in/images/2nd_passphrase_request.png)

I'm now feeling confused and suspicious: I used `--no-import` to say I didn't want to import, but the wording of the dialog seems to contradict that. And I don't know why I'm being asked for my passphrase a second time. I was under the impression that the passphrase was just used to sign the public key, and so it would only be needed once, by gpg (and not keybase).

Have I misunderstood something? Is this second passphrase prompt necessary, and if so could it be made to explain itself more clearly?

(I found [this comment](https://news.ycombinator.com/item?id=7503239) which said:
> There's one instance in which we prompt for your PGP password directly [...] that's adding the username <you@keybase.io> to your public key if it's not already there

and so I had already made a uid for my key ("keybase.io/mickbrooks <mickbrooks@keybase.io>") matching the pattern I found from another user. Did I miss anything?)

**Comment by maxtaco** [comment]
Thanks for the report, we'll take a look. CC: @zapu can you make a ticket?

**Comment by zapu** [comment]
Internal id: CORE-4898

Thank you for the report!

**Comment by victortoso** [comment]
Had the same issue. It only imports the public key, you can verify with keybase pgp export -s which should not print you private key afterwards. It should not request the pgp password for the public key...

**Comment by jzacsh** [comment]
any updates here? even temporary clarification would be nice _(I didn't even know about `--no-import` and was **still** suspicious as to why I'd want to type my passphrase anywhere other than the gpg toolchain)_

**Comment by zapu** [comment]
Sorry, this is one of several GitHub issues and internal tickets about this problem.

A fix was merged a while ago: https://github.com/keybase/client/pull/7414 that will shell out to GPG in order to make a reverse-signature of PGP key. We reverse-sign to prove that user uploading a key is also the owner of said key. We used to do this with go-crypto library, but now the secret key will not leave gpg keyring anymore.

Let me know if you have any further questions! Thanks.

**Comment by jzacsh** [comment]
@zapu thanks for the update! So, to confirm, if my download of the keybard `.deb` would have had that pull request in it, then I'd not be prompted by the keybase app (that screenshot above) as I was?

**Comment by zapu** [comment]
Right, you would not see a Keybase prompt for key passphrase during `keybase pgp select --no-import`, but you would still see GPG prompting you for the passphrase. Because now we do that:

```
2017-07-12T21:53:34.072737+02:00 ▶ [DEBU keybase log.go:30] 0d4 | GPGKey reverse delegate to CLI
2017-07-12T21:53:34.072996+02:00 ▶ [DEBU keybase gpg_cli.go:225] 0d5 GPG version:
gpg (GnuPG) 2.1.15
libgcrypt 1.7.2-beta
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Home: /tmp/tmp.1exRTUE0z3/.gnupg
Supported algorithms:
Pubkey: RSA, ELG, DSA, ECDH, ECDSA, EDDSA
Cipher: IDEA, 3DES, CAST5, BLOWFISH, AES, AES192, AES256, TWOFISH,
        CAMELLIA128, CAMELLIA192, CAMELLIA256
Hash: SHA1, RIPEMD160, SHA256, SHA384, SHA512, SHA224
Compression: Uncompressed, ZIP, ZLIB, BZIP2
2017-07-12T21:53:34.073071+02:00 ▶ [DEBU keybase gpg_cli.go:353] 0d6 | running Gpg: /usr/bin/gpg2 --armor --sign -u ab1059a2529b7619986480c8c9293dacd499084d
2017-07-12T21:53:34.073104+02:00 ▶ [DEBU keybase gpg_cli.go:360] 0d7 | setting GPG_TTY=/dev/pts/18
2017-07-12T21:53:53.662046+02:00 ▶ [DEBU keybase log.go:30] 0d8 - GPGKey Signing -> %!s(<nil>)
```

so the `/usr/bin/gpg2 --armor --sign -u ab1059a2529b7619986480c8c9293dacd499084d` command needs to unlock key, but otherwise the secret key is not exported.

**Comment by JustATrick** [comment]
Thanks for the update. The new version worked as I expected, so I'll close this issue now.

**Comment by ransford** [comment]
I just ran into the same dialog before learning about `--no-import`.  I had just generated a new keypair to replace an expiring one and was trying to upload only the public part to Keybase.

Called without `--no-import`, `keybase pgp select` creates a dialog box asking me for the secret part's passphrase.  `Reason: Import of key into Keybase keyring` isn't quiiiite specific enough.  Which key, and why?

**Comment by irogaro** [comment]
Same issue here (macos x). Simple question : why is --no-import not implemented by default? Do you really need to import it?

**Comment by shredding** [comment]
Same here. Killed my great 1st impression somewhat.

**Comment by maxtaco** [comment]
Because some people like to use keybase instead of pgp for decrypt/sign.  Note that it's just importing to a locally stored keychain, encrypted using the same policies as the reset of your private keybase credentials (like your device private key).

`keybase help gpg` has more specifics.

**Comment by irogaro** [comment]
I guess Keybase can be use as a GPG keyring app if you don't have already one. And since most users do not use this kind of app, it is primarily made for them ... Might be an explanation

**Comment by maxtaco** [comment]
@irogaro  exactly
