### ISSUE TITLE
How to go about using subkeys after removing the master key?

### ISSUE THREAD

**Issue by hashhar** [keybase/client#6551]
1. I created a key from gpg on the command line.  
2. I added two user ids (one that matches the e-mail on my Keybase).  
3. I then added an encryption only subkey.
4. I moved the keys to encrypted media.
5. I then exported secret subkeys and deleted the secret keys from GPG.
6. Reimport the secret subkeys. This effectively means that the master key has been removed and can be seen using `gpg -K` showing `sec#` instead of `sec` in front of master key.

I then used `keybase pgp select` to link this to keybase.

# Issue:

I want to be able to use the crypto within the browser too so I proceed to upload my encrypted private key. The page tells me to:

```bash
gpg -K --keyid-format long --with-colons --with-fingerprint
# then export the one you want (look next to `fpr`)
gpg --export-secret-keys -a keyid
```

The issue is I don't understand what keyid I should use since I now have 3 `fpr` (Fingerprint) entries (one for the master key (SC), one for the default encryption key (E) and one for the signing key I generated manually (S).

If I only upload my signing key (S) then would it differ anyway from if I uploaded the master key (SC)?

**Comment by hashhar** [comment]
I just noticed that the armored output generated using `export-secret-keys` is different when I change my GPG_HOME. The output differs only in length. The initial few lines are same but the ending differs. The output from the GPG_HOME without the master keypair is shorter.

**Comment by juanminm** [comment]
If you use `gpg --export-secret-keys -a KeyID`, it doesn't matter if you put your master key fingerprint or KeyID or the subkeys ones, it will end up exporting the whole master key and subkeys block. Only `gpg -a --export-secret-subkeys SubkeyID! [SubkeyID2! ... ]` will make a difference in what you put there as you would be exporting only the specified subkeys.
If there is any missing secret part (master key (sec#) or other subkeys (ssb#)) only the present secret parts will be exported (in your case, your current encryption and signing subkeys) when using `--export-secret-keys`.

As for if it will work on the website, I don't know the answer so wait for one

**Comment by sergeevabc** [comment]
Err… Hello? :)

**Comment by sergeevabc** [comment]
So, what’s the status? Does keybase-specific subkey work as expected, @hashhar?

**Comment by hashhar** [comment]
@sergeevabc Sorry for the massive delay. Forgot this even existed. I did eventually run into the issue you linked and I can confirm that this works when adding the master key. Just the subkeys won't work.
