### ISSUE TITLE
Read operation timed out

### ISSUE THREAD

**Issue by sydbarrett74** [keybase/client#6556]
OS: Windows 10 Insider Fast Ring build 16170

The message I received in Notifications flashed by too quickly for me to capture it, but here is the essence: 'The keybase read operation timed out. Please run "keybase log send" so our team can examine it.' Again, not verbatim, but it gives the gist of the error message.

I receive this error every time I bring my laptop out of hibernation.

my log id: e72109abe26ca172b67f251c

**Comment by strib** [comment]
Thanks for the report, sorry for the annoyance.  Windows has a tendency to ask us for how much space is available all the time, and if the request comes in right before hibernation it will time out once you come back. We should probably suppress that notification on Windows.  It's safe to ignore it for now.

**Comment by sydbarrett74** [comment]
Thank you for the prompt reply!

I was afraid it was a portent of something more serious, but I'll heed your advice and close this particular issue out. :)
