### ISSUE TITLE
Unable to login, key expired and Keybase can't find it in GPG Keychain

### ISSUE THREAD

**Issue by srkiNZ84** [keybase/client#6564]
Keybase GUI Version: 1.0.20-20170317000044+73c5db6

Hi,

I've recently downloaded the Keybase.io App and am trying to login. However, I'm a user that verified with my PGP key and therefore I am trying to login using the "keybase login" CLI command. When attempting to login, I've also realised that my PGP key has expired and I haven't generated a new one. As such, when I try to login, I get the following warning and error:

<img width="716" alt="expired_key_unable_to_find" src="https://cloud.githubusercontent.com/assets/163910/24883533/662a5236-1e99-11e7-917a-6d8996ccb093.png">

I understand why Keybase might not let me login with an expired key, however, the error saying that it cannot find the key is a mystery to me as the key is there in my [GPG Keychain](https://gpgtools.org/). It is not however, in the OS X  Keychain.

With this in mind, can I please ask:
* Does Keybase.io let you login with an expired PGP key if you haven't generated a new one?
* Does Keybase.io support looking for keys in any other keychain other than the built in OS X Keychain? (specifically asking about GPG Keychain)

Love your work!
Thank you :-)

**Comment by srkiNZ84** [comment]
my log id: 3e064b7bf31fa2901529531c

<img width="937" alt="gpg_keychain_keys" src="https://cloud.githubusercontent.com/assets/163910/24884371/2765ab5a-1e9d-11e7-8c23-7ff5ec1f6561.png">

**Comment by maxtaco** [comment]
Can you paste the output of this command?

```
/usr/local/MacGPG2/bin/gpg2 --no-tty --with-colons --fingerprint -K 29A3A3C7
```

**Comment by srkiNZ84** [comment]
Sure, here it is:

```
$ /usr/local/MacGPG2/bin/gpg2 --no-tty --with-colons --fingerprint -K 29A3A3C7
sec::4096:1:EFF4107E29A3A3C7:1421015930:1452551930:::::sc::::
fpr:::::::::6F8B56EE24F4D49308C78373EFF4107E29A3A3C7:
uid:::::1421015930::93D06C476444BCAD8B0B098EBD2E6D10D845E3E3::Srdan Dukic (Serge) <srdan.dukic@gmail.com>:
ssb::4096:1:DF743A302AEB10E6:1421015930:1452551930:::::e::::
```

**Comment by maxtaco** [comment]
I think your GPG key expired a long time ago.  Try extending it via `gpg --edit-key`

**Comment by srkiNZ84** [comment]
> Does Keybase.io let you login with an expired PGP key if you haven't generated a new one?
ok, so I guess that's a "no"? With a workaround that you can edit the key and change the expiry (I didn't realize you could do this)

> Does Keybase.io support looking for keys in any other keychain other than the built in OS X Keychain?
So, it does look and find the keys in the GPG Keychain, but ignores them if expired (and then errors out, saying it can't find the key).

It would be nice if attempting the login with an expired key produced an error message such as:

"Sorry, unable to use primary key 9A8A... as it has expired. Please extend it using 'gpg --edit-key' or reset account..."

Thank you again

**Comment by srkiNZ84** [comment]
Ok, so with having modified the expiry date, I get further in the login process, but am still getting errors when trying to log in (same error, regardless whether option 1 or 2 is chosen):

```
srdan@Srdans-MacBook-Pro:~/code/clair$ keybase login
Your keybase username or email address: srdan.dukic@gmail.com
In order to authorize this installation, keybase needs to sign this installation
with your GPG secret key EFF4107E29A3A3C7.

You have two options.

(1) Keybase can use GPG commands to sign the installation.

(2) Keybase can export your secret key from GPG and save it to keybase's local encrypted
    keyring. This way, it can be used in 'keybase pgp sign' and 'keybase pgp decrypt'
    going forward.
Which do you prefer?: 1
Enter a public name for this device: macbook

You need a passphrase to unlock the secret key for
user: "Srdan Dukic (Serge) <srdan.dukic@gmail.com>"
4096-bit RSA key, ID 29A3A3C7, created 2015-01-11

▶ ERROR Could not open key: no valid primary key self-signature or key(s) have expired (error 905)
```

**Comment by maxtaco** [comment]
Can you use the Web interface to update your public key with the newly
updated public key?  Use the GPG+Curl mode

**Comment by srkiNZ84** [comment]
Success! That worked, thank you very much! :-)
