### ISSUE TITLE
undefined: NullChatSyncer

### ISSUE THREAD

**Issue by redshodan** [keybase/client#6566]
When trying to install keybase client on a chromebook I get the following error:

baron@localhost ~/pkgs/go-path $ go get github.com/keybase/client/go/keybase
baron@localhost ~/pkgs/go-path $ go install -tags production github.com/keybase/client/go/keybase
# github.com/keybase/client/go/libkb
src/github.com/keybase/client/go/libkb/globals.go:190: undefined: NullChatSyncer

It's a chromebook, ARM, running crouton with Ubuntu Yakkety.

baron@localhost ~/pkgs/go-path $ go version
go version go1.7.1 linux/arm

**Comment by maxtaco** [comment]
Sorry about this, we have a PR in the works.

**Comment by maxtaco** [comment]
Fixed in #6568. Thanks for the report.

**Comment by redshodan** [comment]
Great, that works for me. Thank you for the quick response!
