### ISSUE TITLE
Keybase hangs when pinentry program is set to /usr/bin/pinentry-curses

### ISSUE THREAD

**Issue by hashhar** [keybase/client#6575]
The keybase client seems to hang if:

1. The gpg pinentry is set to '/usr/bin/pinentry-curses'.
2. The client issues the command `keybase pgp select`.

Manually looking at the process that is running it seems that keybase is waiting for `/usr/bin/gpg2 --no-tty --armor --export-secret-key fingerprint` and since keybase 'owns' the terminal, there is a deadlock kind of situation.

# Possible Fixes:

1. Add a timeout.
2. Check what the pinentry program is? It can be found in the `gpg-agent.conf`. Alert the user that `/usr/bin/pinentry-curses` isn't supported yet.
3. Support curses pinentry. This is not important in my view since the default for GPG is the GUI pinentry and VERY FEW people may have it set to the curses interface. A warning should suffice.

**Comment by maxtaco** [comment]
this works with a lot of people, it's something about your config. it might be sending the pinentry to another terminal.  @zapu haven't you tested this recently?

**Comment by hashhar** [comment]
@maxtaco I'll check once again. It could be something in my config or maybe the GPG_TTY wasn't set properly. It's known to cause such issues.

I'm not at my machine right now though so I'll be able to check it sometime later today.

**Comment by maxtaco** [comment]
We do our best to set `GPG_TTY` automatically, which is quite tricky.  But I don't know if we override the `GPG_TTY` provided...

**Comment by zapu** [comment]
We had a small fix recently for this (https://github.com/keybase/client/pull/6411), but I don't know if it's in public build yet.

**Comment by zapu** [comment]
@hashhar could you try to reproduce this and do a `keybase log send` ?

**Comment by hashhar** [comment]
@zapu Yes. That works. It's in the `keybase-bin` package on ArchLinux. (I think it's built from git master that's why).

**Comment by hashhar** [comment]
@maxtaco For completeness, the program worked even when I had manually set a GPG_TTY.
