### ISSUE TITLE
** Account problem ** Folder needing rekey and unable to rekey

### ISSUE THREAD

**Issue by lucasantarella** [keybase/client#6581]
So I have this folder in my account between me and another user. I think it's using an older device's key that I no longer have access to and I can't rekey or delete the folder. 

Can someone at keybase manually delete the folder from my account? I don't care about any contents it might have.

I and the other user can both provide signed messages proving our identities.

**Comment by strib** [comment]
Yes, we can manually reset it if you give us signed statements (ideally from both of you).  For a shared folder to get into this state though, I'd expect that you would have both had to completely revoke all of your devices at nearly the same time, which is pretty rare.  (Or, maybe it was a folder you created with someone before they had any Keybase devices, and it was just you that revoked the original devices.)

Also, it would make my life a bit easier if you are willing to do a `keybase log send` showing the access problem and share the resulting ID here.

To request the folder reset, please run this command on an currently-valid keybase device, and substitute the current date, time,and user list where indicated:

```
keybase sign -m "<DATE_AND_TIME>: Please reset folder /keybase/private/<USER_LIST> because all the devices that have access have been revoked."
```

and post the results here.

**Comment by strib** [comment]
(By the way, if you want to keep the identity of the other person private, you can send me these signatures via keybase chat or put them in `/keybase/private/lucasantarella,strib@github`).

**Comment by lucasantarella** [comment]
@strib 

Here's my log ID: 1d0479e604474ed80f90c71c

Probably should've started with that...my bad.

I'll be sending the signatures via keybase in a sec.

**Comment by strib** [comment]
Ok, I've reset the folder. Can you please check it out and close this out if things look ok?  (Might require a KBFS restart.)

By the way, the problem wasn't that both of you revoked your old devices, I think it was because this folder was made around the time of #3344 when you reset your account, and we didn't have a feature back then to clear out broken automatically back then (we have it now).

**Comment by lucasantarella** [comment]
@strib Working now. Thanks so much!
