### ISSUE TITLE
Keybase chat read access issue

### ISSUE THREAD

**Issue by MarcelloTheArcane** [keybase/client#6592]
after the latest update (updated 11:52, 13/04/2017) I ran `keybase chat list` and this happened: 

    [4]  (unverified) [name] (files before ma...          [???] error unboxing chat message: This device does not yet have read access to directory /keybase/...
    github.com/keybase/kbfs/libkbfs.(*KeyManagerStandard).getTLFCryptKeyParams
    /root/build/gopaths/amd64/src/github.com/keybase/kbfs/libkbfs/key_manager.go:287     github.com/keybase/kbfs/libkbfs.(*KeyManagerStandard).getTLFCryptKey
    /root/build/gopaths/amd64/src/github.com/keybase/kbfs/libkbfs/key_manager.go:146
    github.com/keybase/kbfs/libkbfs.(*KeyManagerStandard).getTLFCryptKeyUsingCurrentDevice
    /root/build/gopaths/amd64/src/github.com/keybase/kbfs/libkbfs/key_manager.go:80
    github.com/keybase/kbfs/libkbfs.(*KeyManagerStandard).GetTLFCryptKeyOfAllGeneration
    /root/build/gopaths/amd64/src/github.com/keybase/kbfs/libkbfs/key_manager.go:64github.com/keybas    e/kbfs/libkbfs.(*KBFSOpsStandard).GetTLFCryptKeys
    /root/build/gopaths/amd64/src/github.com/keybase/kbfs/libkbfs/kbfs_ops.go:409
    github.com/keybase/kbfs/libkbfs.(*KeybaseServiceBase).GetTLFCryptKeys
    s/keybase_service_base.go:656
    github.com/keybase/kbfs/vendor/github.com/keybase/client/go/protocol/keybase1.TlfKeysProtocol...
    /root/build/gopaths/amd64/src/github.com/keybase/kbfs/vendor/github.com/keybase/client/go/p
    r...
    github.com/keybase/kbfs/vendor/github.com/keybase/go-framed-msgpack-rpc/rpc.    (*callRequest).Serve
    /root/build/gopaths/amd64/src/github.com/keybase/kbfs/vendor/github.com/keybase/go-framed-m
    s...
    github.com/keybase/kbfs/vendor/github.com/keybase/go-framed-msgpack-rpc/rpc.    (*receiveHandler)...
    /root/build/gopaths/amd64/src/github.com/keybase/kbfs/vendor/github.com/keybase/go-framed-m
    s...
    runtime.goexit
    /usr/local/go/src/runtime/asm_amd64.s:2086 

This is because I recently wiped all my keys and started again, so it doesn't have read access to the old chats (perfectly understandable).  Before the update though, it would just say a single message like `??? can't read chat - waiting for clients to open keybase` (or something.  I can't remember the exact wording)

Could keybase be configured to recognise that it can't read the chats and not scream so loud?  

my log id: 288d383470bdf9113688861c

**Comment by strib** [comment]
@mmaxim @patrickxb: is something treating an unreadable error as fatal?

**Comment by MarcelloTheArcane** [comment]
solved with the latest update.

**Comment by tombusby** [comment]
I'm having this issue. Just setup keybase today

**Comment by tombusby** [comment]
FYI, this was on first run for the ubuntu .deb file installation.

Closing and re-opening fixed the problem.
