### ISSUE TITLE
packaging/osx: does ComponentNameKBNM need to be included elsewhere?

### ISSUE THREAD

**Issue by shazow** [keybase/client#6637]
In [install_darwin.go](https://github.com/keybase/client/blob/master/go/install/install_darwin.go#L463), I have a

```go
	if libkb.IsIn(string(ComponentNameKBNM), components, false) {
		err = InstallKBNM(context, binPath, log)
		...
	}
```

But it occurred to me that I never added `ComponentNameKBNM` to any of the default install targets? (Or did I by accident?) Specifically looking at:

https://github.com/keybase/client/blob/master/go/client/cmd_install_osx.go#L87

and

https://github.com/keybase/client/blob/master/go/client/cmd_ctl_start_osx.go#L61

Is my install code inherently broken, or are those other lists superfluous for what I need? (cc @gabriel)

**Comment by gabriel** [comment]
The native calls `keybase install --components={name}` on each component.

If you want to support KBNM being installed if a user runs `keybase install`, then we should add to default list. Yeah we should do this.

**Comment by gabriel** [comment]
It would be nice to have the native installer call `keybase install` to simplify things and is something we were thinking about doing but haven't gotten to.

**Comment by shazow** [comment]
@gabriel Do I need to add it to both places or just the one?

**Comment by gabriel** [comment]
Just install
