### ISSUE TITLE
Reset my private and public folders. Thanks!

### ISSUE THREAD

**Issue by iSm1le** [keybase/client#6662]
20.04.2017 - 19:24:39,42 : Hello. Reset my public /keybase/public/ism1le and private /keybase/private/ism1le folders cause i changed keys/devices.

BEGIN KEYBASE SALTPACK SIGNED MESSAGE. kXR7VktZdyH7rvq v5wcIkHbry3W1BQ Y7eQST15mJEqMnE z0Pt3QQ8Rgb1pKa Kk85q8uEksG9rNd 0aRskPh2HdeLTYK 2HKqeFVGYJuYuAA KBFkH3TkUJRiplS 0nqF638fPrvm5gy yVnrevxo3zdMpjK VKOeHrXIKR7RRjY Fk8nYbIliSQR4qW 7AtGwu8TH8mqJUt UUeAzDqSsyozeaY nfabcBsxHwq4vIM UXLBq439EwSuxgB vzfKAovwEPIBw0E LreN6jN0RDzVM9P XzooQJ5EiDvWSnZ LnNcXJEeuopCtwx HO3sonCHNAwL7a3 OgHdvLblKWyWLdq Nbq86F306pchazR qlz8iW4LhE7vYUj 0gRtxHaPAWAxucK GieXPzIe2fXuDTb dgeWND8XA77tabN 6XnJnqdNR4HgWoJ le0FFdYpj2CqSQS Dn5GYkGI2Q1eDYI o63svE9euxyoFfL dAwBFeUa. END KEYBASE SALTPACK SIGNED MESSAGE.

Thanks.

my log id: 2434ccc8000161bedc80d31c

**Comment by strib** [comment]
@iSm1le: I reset your private folder.  Please try it out (maybe require a KBFS restart) and close this if things seem ok now.

Your public folder shouldn't need a reset.  If you're having problems with it, let me know.
