### ISSUE TITLE
Can't login in OS X KeyBase app

### ISSUE THREAD

**Issue by garcev** [keybase/client#6712]
Keybase GUI Version: 1.0.21-20170413194119+9dea6e1

I get this error when trying to login.
<img width="795" alt="screen shot 2017-04-24 at 10 01 49 pm" src="https://cloud.githubusercontent.com/assets/7450718/25356294/f4a4a246-2939-11e7-8f8c-38f93533eb99.png">

**Comment by cjb** [comment]
Hi, please try `keybase login` from the command line.

**Comment by garcev** [comment]
Hi,

```
$ keybase login
Your keybase username or email address: YYYY@YYYY.com
▶ ERROR GPG error: exit status 2
```

It looks like gpg software needed to be updated. After update all works fine.

Thank you for the help!
