### ISSUE TITLE
 Add ability to delete entire conversation threads from a device

### ISSUE THREAD

**Issue by CameronBanga** [keybase/client#6724]
I'm not worried about you guys reading my messages, I trust the crypto. But I may want to delete entire conversations from my keybase chat, in case my computer/phone, etc, was stolen or left open, etc.

I don't see the ability to do this? I tried every way  I could imagine, but seems impossible to do?

**Comment by maxtaco** [comment]
Cc: @chrisnojima

**Comment by chrisnojima** [comment]
This feature is on the roadmap but not in the first version

**Comment by slajax** [comment]
@chrisnojima Any update on this? 

It's very basic functionality for a chat that intends to be secure.

**Comment by dabura667** [comment]
Yeah. I am personally waiting for this as well as a self-destruct timer a la Telegram secret chats.

**Comment by chrisnojima** [comment]
@maxtaco 's team is actually working on this next. the self-destruct stuff is a sep. feature
