### ISSUE TITLE
Ability to Edit other people's messages, even though it doesn't stick, seems odd

### ISSUE THREAD

**Issue by CameronBanga** [keybase/client#6725]
Currently, if I long hold on the message of another user, an Edit option appears and you can make changes to the text. This kinda just feels real odd, as I wouldn't imagine I should ever be able to edit someone else's messages.

I can't actually edit their messages, and no changes I make are saved, which is what I would expect. But just feels weird the first time you try it and see it.

Additionally, I can't delete other people's messages from the chat, but I feel like i should be able to do that, if I don't want to see what they sent me in my stream any longer.

**Comment by maxtaco** [comment]
Cc: @chrisnojima

**Comment by chrisnojima** [comment]
this was fixed https://github.com/keybase/client/pull/6694
