### ISSUE TITLE
Places stuff on my desktop

### ISSUE THREAD

**Issue by haf** [keybase/client#6728]
Keybase GUI Version: 1.0.21-20170413194119+9dea6e1

And it cannot be removed and doesn't show up in the terminal's `ls` command.

<img width="188" alt="screen shot 2017-04-25 at 11 01 10" src="https://cloud.githubusercontent.com/assets/193115/25377002/80aead60-29a6-11e7-9505-d67f2674b5e4.png">

The red hair destroys my zen desktop feeling.

**Comment by gabriel** [comment]
I think that is the dmg mounted (if you unmount in Finder).

Also you can unselect "Connected Servers" in Finder Preferences, to not have the keybase folder mount show up on desktop.

**Comment by haf** [comment]
Yes, indeed that was the dmg. Confusing :)
