### ISSUE TITLE
App fails to connect on launch

### ISSUE THREAD

**Issue by xaque208** [keybase/client#6759]
On Archlinux, with keybase-git, or keybase-bin, both fail to keep a connection, Telling me "Oops, unable to connect to our servers" or some such.  It never recovers.  I have no other issues with my network.  I have IPv4 and IPv6 routes and connectivity to services over both address families.  Please advise.

Secondarily, if there is a way to read messages from the command line, I'd love to know.  keybase chat read myfriend just hangs.

**Comment by maxtaco** [comment]
Can you send a `keybase log send`? Thx

cc: @oconnor663 and @cjb for arch

**Comment by oconnor663** [comment]
This might be another recurrence of https://github.com/keybase/client/issues/5733#issuecomment-278440637 ([JIRA](https://keybase.atlassian.net/browse/CORE-4611))

@xaque208 are you using `NetworkManager`? Are you on a laptop where connectivity comes and goes, like when you close the lid? We have some issue in that environment that we haven't tracked down yet.

**Comment by mitar** [comment]
I am also encountering this. On Mac OS X. Submitted the log 085719ee003e5cd7c6ecc61c.

**Comment by maxtaco** [comment]
Cc: @patrickxb  this is another "No UID given to Syncer..." bug

**Comment by patrickxb** [comment]
@mitar thanks for the bug report.  We have a fix for this that will be in the next build.

I believe that `keybase logout` followed by a login (either by the GUI or `keybase login`) will get you back into the app.

Sorry for the inconvenience.

**Comment by mitar** [comment]
The workaround worked. Thanks!

**Comment by xaque208** [comment]
@oconnor663 I am using NetworkManager, though I should mention that the connection is solid when I'm trying to launch the app.  Specifically this is not an issue for me re-connecting, but an issue connecting at all.

**Comment by xaque208** [comment]
I tested the logout and login, and now the app looks to open.  Thanks for the response.
