### ISSUE TITLE
my session expires when I go to notification settings

### ISSUE THREAD

**Issue by elopio** [keybase/client#6783]
Every time I try to go to Settings > Notifications in the electron client, my session expires.

I get thrown back to the login screen, with a message that says "your session has expired.".
It also shows this trace:
`Error: your session has expired. at t (file:///opt/keybase/resources/app/desktop/dist/index.bundle.js:18:8047) at new t (file:///opt/keybase/resources/app/desktop/dist/index.bundle.js:18:8867) at s (file:///opt/keybase/resources/app/desktop/dist/index.bundle.js:18:8443) at i (file:///opt/keybase/resources/app/desktop/dist/index.bundle.js:18:8371) at file:///opt/keybase/resources/app/desktop/dist/index.bundle.js:14:19678 at file:///opt/keybase/resources/app/desktop/dist/index.bundle.js:76:27386 at e.t.Deferrals.e._call (file:///opt/keybase/resources/app/desktop/dist/index.bundle.js:42:19169) at file:///opt/keybase/resources/app/desktop/dist/index.bundle.js:42:19320 at c (file:///opt/keybase/resources/app/desktop/dist/index.bundle.js:42:18947) at e.t.Deferrals.e._fulfill (file:///opt/keybase/resources/app/desktop/dist/index.bundle.js:42:19279)`

I'm using Ubuntu Gnome 17.04. I installed keybase with the deb:
```
$ curl -O https://prerelease.keybase.io/keybase_amd64.deb

$ keybase -v
keybase version 1.0.21-20170428160949+36e780b
```

**Comment by strib** [comment]
Thanks for the report.  Would you mind filing this over at keybase/client instead?  Doesn't seem KBFS-specific.

Also, if you're willing, a `keybase log send` would be good to include in that report.

**Comment by strib** [comment]
Derp nevermind, sorry!

**Comment by maxtaco** [comment]
I repro'ed, this is a serious issue.

CC: @chrisnojima  and @patrickxb 

We're right on it, thanks for the report!

**Comment by elopio** [comment]
Thanks to you. Everything else has worked flawlessly ^_^

**Comment by patrickxb** [comment]
A fix for this will be in the next build.  Thanks for reporting it!

**Comment by cjb** [comment]
The fixed build's out now, thanks.
