### ISSUE TITLE
Login fails, reproducible

### ISSUE THREAD

**Issue by gruenheit** [keybase/client#6794]
Keybase GUI Version: 1.0.21-20170428110011+0ccdf77
macOS 10.12.4 (16E195)

Starting the app, restarting it, just the same, login fails.

**Comment by maxtaco** [comment]
Can you do a `keybase log send`?

Cc: @patrickxb

**Comment by gruenheit** [comment]
------------
Success! Your log ID is:

  772fa055243fc8e6b314641c

Here's a URL to submit new bug reports containing this ID:

  https://github.com/keybase/client/issues/new?body=[write%20something%20useful%20and%20descriptive%20here]%0A%0Amy%20log%20id:%20772fa055243fc8e6b314641c

Thanks!
------------

**Comment by maxtaco** [comment]
@gruenheit had you logged out previous to the upgrade?

**Comment by maxtaco** [comment]
@patrickxb:

```
12561 2017-04-29T21:30:08.192415+02:00 ▶ [DEBU keybase login_state.go:1072] 41d - Account "Bootstrap"
12562 2017-04-29T21:30:08.192429+02:00 ▶ [DEBU keybase bootstrap.go:86] 41e connected, running full tracker2 syncer
12563 2017-04-29T21:30:08.192447+02:00 ▶ [DEBU keybase engine.go:67] 41f - RunEngine(Bootstrap) -> ERROR: No UID given to syncer
```

**Comment by gruenheit** [comment]
Well, I logged out before, yes. What upgrade you mean?

**Comment by maxtaco** [comment]
Looks like your software auto-upgraded to the 4/28 release, which is normal.  I believe @patrickxb fixed this bug, but I thought that was before this release went out.  Let's see what he has to say. Thanks for your feedback...

**Comment by gruenheit** [comment]
Thank you! greetings from Kiel.

**Comment by patrickxb** [comment]
@gruenheit we have a fix for this that will be in the next build.

In the meantime, `keybase logout` followed by a login (via GUI or `keybase login`) should get you back into the app.

Vielen dank!

**Comment by gruenheit** [comment]
solved!
