### ISSUE TITLE
Logs out randomly, doesn't require password

### ISSUE THREAD

**Issue by mirorauhala** [keybase/client#6811]
Client logs out the current user when navigating to Settings > Notifications. After that it allows the user to log back in without providing a password.

[See video](https://mirorauhala.keybase.pub/screenshots/keybase-wtf-2017.mp4)

**UPDATE:**
The `your session has expired` message also spilled out the following.

Error: your session has expired. at t (file:///C:/Users/Miro/AppData/Local/Keybase/Gui/resources/app/desktop/dist/index.bundle.js:18:6316) at new t (file:///C:/Users/Miro/AppData/Local/Keybase/Gui/resources/app/desktop/dist/index.bundle.js:18:7136) at s (file:///C:/Users/Miro/AppData/Local/Keybase/Gui/resources/app/desktop/dist/index.bundle.js:18:6712) at i (file:///C:/Users/Miro/AppData/Local/Keybase/Gui/resources/app/desktop/dist/index.bundle.js:18:6640) at file:///C:/Users/Miro/AppData/Local/Keybase/Gui/resources/app/desktop/dist/index.bundle.js:14:20529 at file:///C:/Users/Miro/AppData/Local/Keybase/Gui/resources/app/desktop/dist/index.bundle.js:76:27386 at e.t.Deferrals.e._call (file:///C:/Users/Miro/AppData/Local/Keybase/Gui/resources/app/desktop/dist/index.bundle.js:42:19061) at file:///C:/Users/Miro/AppData/Local/Keybase/Gui/resources/app/desktop/dist/index.bundle.js:42:19212 at c (file:///C:/Users/Miro/AppData/Local/Keybase/Gui/resources/app/desktop/dist/index.bundle.js:42:18839) at e.t.Deferrals.e._fulfill (file:///C:/Users/Miro/AppData/Local/Keybase/Gui/resources/app/desktop/dist/index.bundle.js:42:19171)

my log id: 2d6c6ad26c0404978f69871c

**Comment by maxtaco** [comment]
Thanks for the bug report, we have a fix in. Cc: @patrickxb for more details.

**Comment by patrickxb** [comment]
Yes, it should be fixed in the next build.  Sorry for this issue, but thanks for the video!

**Comment by cjb** [comment]
Thanks, this is fixed in the latest build now.

**Comment by mirorauhala** [comment]
Awesome!! However, the incident left a question in my mind: How do you log out from the client?

**Comment by maxtaco** [comment]
Either `keybase logout` from the CLI or the right menu of the keybase
widget from the GUI

**Comment by patrickxb** [comment]
`keybase logout` from CLI is the only way to logout on a desktop device.
