### ISSUE TITLE
Settings>Notifications error

### ISSUE THREAD

**Issue by mahrud** [keybase/client#6825]
When I try to visit the Settings>Notifications tab keybase kicks me out and returns the following error:

Error: your session has expired. at t (file:///opt/keybase/resources/app/desktop/dist/index.bundle.js:18:8047) at new t (file:///opt/keybase/resources/app/desktop/dist/index.bundle.js:18:8867) at s (file:///opt/keybase/resources/app/desktop/dist/index.bundle.js:18:8443) at i (file:///opt/keybase/resources/app/desktop/dist/index.bundle.js:18:8371) at file:///opt/keybase/resources/app/desktop/dist/index.bundle.js:14:19678 at file:///opt/keybase/resources/app/desktop/dist/index.bundle.js:76:27386 at e.t.Deferrals.e._call (file:///opt/keybase/resources/app/desktop/dist/index.bundle.js:42:19169) at file:///opt/keybase/resources/app/desktop/dist/index.bundle.js:42:19320 at c (file:///opt/keybase/resources/app/desktop/dist/index.bundle.js:42:18947) at e.t.Deferrals.e._fulfill (file:///opt/keybase/resources/app/desktop/dist/index.bundle.js:42:19279)

See a screenshot at /keybase/public/mahrud/keybase/keybase_notification_error.png

my log id: 06007195d885ec7c4a10441c

**Comment by cjb** [comment]
Thanks!  This is fixed in the latest update.
