### ISSUE TITLE
Please delete my private folder, I screwed it. Thank you :)

### ISSUE THREAD

**Issue by Thewest123** [keybase/client#6830]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

Hi,

I accidentally uninstalled the Keybase app and deleted all registry entries. So please delete my /thewest123/private/ folder, because Keybase says I need to rekey, but I can't.

Thank you much.
Regards,
Jan Černý
-----BEGIN PGP SIGNATURE-----
Version: Keybase OpenPGP v2.0.70
Comment: https://keybase.io/crypto

wsFcBAABCgAGBQJZCJePAAoJEDcbbv7qEaIIJEoP/j70P7iPIgtwnerJ28hmgbUW
CDWfoRWELJYAc6TsaVdnDxw9MngUvYAEs/AWts+jy3g3BAujEYT4oZjHhr3QWBMk
xmlHemotAnAqTWeILquiyzvvrRZtVAxkGn8uQXudaTqBW6zmEElRjUlc0dGfDj+p
tc7BiRWGWqhW3ZGl0JagOn4PPmivF/BwuJTjgt9r+of7YxLxu84vJYqnAbqmufN8
ggNK6PedaRtKp2OfqMBPbqvlxB8sqVhZLq7NfKyCInZyCnlW3IUcp1ldj0OiCMfu
BNfZLfpdAW9HUikVNDBaOZZJ61vDl0Rei/mAkEl7VpvN/FDpu0boE+07+heNyKdz
lrpK2NB0bQNFzdUWjNyaF+yZTKxPiDgFNHYN5ULnooZA8UeillmPETCghiQMGnH2
OB4jKoXj6LMHfL3nnbpA81QuMdXUqeQL99K/rfLrD/oqTQB2bOqVdeiw7F4MowSC
IrZDjHockmBZMQbeY6CQo/0VuvjHPxiBulnroTzXM8+S9iC0vlsaD9W1PcR9rM3C
FmSI+AET+tWcxgFhBoLD4+Ma1aBLMqBME+Qt/W5cXX5Mc9KGWn/lvMojnzVvEyD5
zvLYLnFrxNqx1BeenDnSKnzjhMaIspz13a9pJFH6rG14hplChqfSSb+T9ta6fC30
aU4NuFaMtOOEmD5s7AIJ
=JVWp
-----END PGP SIGNATURE-----

**Comment by strib** [comment]
I've deleted this folder.  Please check things out (might require a Keybase app restart) and close this out if things look ok.

We recommend you keep one of your paper keys written down offline to prevent future issues like this.

**Comment by Thewest123** [comment]
I was so stupid, that I revoked the keys after app reinstallation because I thought that I won't need them anymore.
Now, I am smarter and I will be more careful next time.

Again, thanks for deleting. Everything works fine. :)
