### ISSUE TITLE
Repeatable Logout Issue on Windows 10

### ISSUE THREAD

**Issue by Sdcopeland** [keybase/client#6834]
Using the GUI app, whenever I go to settings and then click on the notification subsection I am immediately logged out of my current session and am required to log back in

**Comment by taruti** [comment]
Cc @zanderz

**Comment by zanderz** [comment]
@Sdcopeland Can you open the `Keybase Shell` and issue `keybase log send`?

**Comment by cjb** [comment]
@Sdcopeland Hi!  We've since fixed this bug in the latest update, no need to submit a log send.  Thanks for the report.
