### ISSUE TITLE
Github Identy prove not working for usernames, that contain simple dots `.`

### ISSUE THREAD

**Issue by sweisgerber-dev** [keybase/client#6850]
I tried to verify my github identity manually via commandline and with the keybase commandline tool.
The error was the same in both cases. I suspect the dot in my username?

_But this is only an assumption._

### Manually with bash, gpg and pipes

``` bash
 curl \
>   --data-urlencode sig="`\
>    echo '{"body":{"key":{"eldest_kid":"
[... CUTTED ...]
>   --data-urlencode remote_username="sweisgerber.dev" \
>   https://keybase.io/_/api/1.0/sig/post.json
Error in your post
-------------------

Code: 100
Name: INPUT_ERROR
Description: Bad remote_username given: sweisgerber.dev
```

### keybase tool

``` bash
keybase prove github sweisgerber.dev
▶ ERROR Bad username: 'sweisgerber.dev'
```

Twitter verification with the keybase tool worked. Account and key signing with bash, gpg & pipes also worked.

**Comment by nlevitt** [comment]
+1 Same issue?

```
$ keybase id mike.maxim@facebook
▶ ERROR In resolving 'mike.maxim@facebook': No resolution found
```
vs
```
$ keybase id ccoyne77@facebook
▶ INFO Identifying chris
✔ public key fingerprint: 94AA 3A5B DBD4 0EA5 49CA BAF9 FBC0 7D6A 9701 6CB3
฿  bitcoin 1BjgMvwVkpmmJ5HFGZ3L3H1G6fcKLNGT5h
✔ admin of DNS zone chriscoyne.com: found TXT entry keybase-site-verification=2_UwxonS869gxbETQdXrKtIpmV1u8539FmGWLQiKdew
✔ "malgorithms" on reddit: https://www.reddit.com/r/KeybaseProofs/comments/5vj9ez/my_keybase_proof_redditmalgorithms_keybasechris/
✔ "malgorithms" on hackernews: https://news.ycombinator.com/user?id=malgorithms
✔ "malgorithms" on twitter: https://twitter.com/malgorithms/status/433640580220874754
✔ "malgorithms" on github: https://gist.github.com/2d5bed094c6429c63f21
✔ admin of chriscoyne.com via HTTPS: https://chriscoyne.com/keybase.txt
✔ "ccoyne77" on facebook: https://facebook.com/10158198173985206_10158632053400206
✔ admin of keybase.io via HTTPS: https://keybase.io/.well-known/keybase.txt
```

**Comment by maxtaco** [comment]
Thanks for the report, looks like a bug.

[This works](https://keybase.io/_/api/1.0/user/lookup.json?facebook=mike.maxim&fields=basics%2Cpublic_keys%2Cpictures&load_deleted=1&multi=1)

[This does not](https://keybase.io/_/api/1.0/user/lookup.json?facebook=mikemaxim&fields=basics%2Cpublic_keys%2Cpictures&load_deleted=1&multi=1)

Looks like the client is stripping the dot erroneously

cc: @oconnor663

**Comment by oconnor663** [comment]
@sweisgerber-dev for your original report, GitHub doesn't allow dots in usernames. Did you mean to use a hyphen?

**Comment by sweisgerber-dev** [comment]
It seems I mixed up the email address with the username.
I'm sorry. Verification worked with a hyphen, closing this issue therefore.
