### ISSUE TITLE
Unsolicited reboot and subsequent application fault on Windows 10

### ISSUE THREAD

**Issue by cdokolas** [keybase/client#6851]
While working, the Keybase GUI popped-up for a split second and then I got Windows' "Restaring" screen.

Upon restart I checked the Event Logs and saw this (some identifiers anonymized):
```
The process C:\Users\user\AppData\Local\Temp\{905BDD7E-09B8-4E65-9A16-4A7D2B0C601F}\.cr\Keybase_1.0.22-20170502065015+f384d79.386.exe (PCNAME) has initiated the restart of computer PCNAME on behalf of user domain\user for the following reason: Application: Installation (Planned)
 Reason Code: 0x80040002
 Shutdown Type: restart
 Comment: 
```

Also, the Keybase GUI doesn't start now, and the Event Log contains this event (some identifiers anonymized):
```
Faulting application name: Keybase.exe, version: 1.0.22.0, time stamp: 0x584ba0b4
Faulting module name: Keybase.exe, version: 1.0.22.0, time stamp: 0x584ba0b4
Exception code: 0x80000003
Fault offset: 0x00264ef9
Faulting process id: 0x2c4c
Faulting application start time: 0x01d2c3ea9600ef39
Faulting application path: C:\Users\user\AppData\Local\Keybase\Gui\Keybase.exe
Faulting module path: C:\Users\user\AppData\Local\Keybase\Gui\Keybase.exe
Report Id: fa111c7c-5fb2-4aa1-9999-d2d8b64ef204
Faulting package full name: 
Faulting package-relative application ID: 
```

**Comment by cjb** [comment]
Thanks for the report, sorry for the hassle.

Please could you try running `keybase log send` from inside the Keybase Shell terminal app?

CC @zanderz

**Comment by cdokolas** [comment]
@cjb: Done!
Log ID: `78fc4ceec1793d298ae7091c`

**Comment by cdokolas** [comment]
I'm going to re-install keybase. I'm just waiting for your feedback to make sure there's nothing else you may need before I do this.

BTW: Will I have to add as new device?

TIA

**Comment by cjb** [comment]
Hi, it'll be a few hours before we can look into the logs and get back to you -- if you need to use Keybase before then I'd say go ahead and reinstall, otherwise it might be useful to have your system still in the bad state.

**Comment by cdokolas** [comment]
No hurry. I'll wait.

**Comment by zanderz** [comment]
On Windows, the silent update sequence is supposed to launch our package with the `/quiet` option, which in turn uninstalls the current version and installs the new one. Your log shows that the silent uninstall failed because some GUI process was still running, holding files:
```
Info 1603.The file C:\Users\cdokolas\AppData\Local\Keybase\Gui\ffmpeg.dll is being held in use by the following process: Name: slack, Id: 8808, Window Title: '(not determined yet)'.  Close that application and retry.

...
Info 1603.The file C:\Users\cdokolas\AppData\Local\Keybase\Gui\node.dll is being held in use by the following process: Name: slack, Id: 8808, Window Title: '(not determined yet)'.  Close that application and retry.
```
Do you actually run Slack? Do you have any idea why it might be holding those files?

Files in use is one of the many conditions under which our installer will say a reboot is required, which unfortunately in silent mode will just happen immediately, unprompted. We will try to address this case as well. Meanwhile, it should work if you use the control panel to uninstall Keybase first, then re-install from the website.

**Comment by zanderz** [comment]
https://keybase.atlassian.net/browse/CORE-5110

**Comment by cdokolas** [comment]
Update: Re-installation fixed it. No re-registering of client needed.

**Comment by qgustavor** [comment]
Same problem happened here a few minutes ago:

```
The process C:\Users\user\AppData\Local\Temp\{36FE3061-C174-4F9C-9B60-D07E6D1EAD0F}
\.cr\Keybase_1.0.22-20170515071844+b608f0e.386.exe (pcname) has initiated the restart
of computer pcname on behalf of user pcname\user for the following reason: Application:
Installation (Planned)
Reason Code: 0x80040002
Shutdown Type: restart
```

Logged at 15/05/17 18:00:32 (GMT-3). `keybase log send` is failing with `Client.Timeout exceeded while awaiting headers`. Version is 1.0.22-20170515071844+b608f0e.

**Comment by cdokolas** [comment]
The auto-reboot happened again a few minutes ago as I was working on a remote virtual machine doing recovery on a database.

The new installation started without problems.

Guys, this auto-reboot thing has to be fixed!

**Comment by zanderz** [comment]
@cdokolas Can you do a Keybase log send at the Keybase she'll?

**Comment by cdokolas** [comment]
Log ID: a9300331b8f299ee4e312c1c

**Comment by zanderz** [comment]
@cdokolas Thanks for the log. We have made a change to prevent this, but it was not in your updater yet, but now it is:
https://github.com/keybase/go-updater/pull/133/commits/3faa5de16ed2f2815238c852787ca520c44f90ec
Please let us know if it happens again with this update, we don't like silent reboots either and would never do it on purpose.
