### ISSUE TITLE
If /keybase owned by different user (keybase.kbfs not running)

### ISSUE THREAD

**Issue by hakamadare** [keybase/client#6869]
This morning I'm repeatedly seeing KBFS unable to load.  I've tried rebooting, I've confirmed that VirtualBox is not installed, I've uninstalled a third-party VPN client (TunnelBear); how do I get some more information about the source of the problem?  I don't want to just keep changing things at random :)

my log id: 646c0edde32a277e9ac3501c

**Comment by maxtaco** [comment]
Thanks for the report. CC: @gabriel on it!

**Comment by gabriel** [comment]
@strib I'm seeing this error:
```
2017/05/04 10:42:55 mount helper error: mount_kbfuse: failed to mount /keybase@/dev/kbfuse0: Operation not permitted
kbfsfuse error: (2) mount_osxfusefs: exit status 71
```

Have you seen that before?

**Comment by gabriel** [comment]
@hakamadare Are you running keybase as another user at the same time? That might be the problem.

If you quit Keybase, does `/keybase` exist? If you remove it, that might fix it since it's owned by a different user.

**Comment by gabriel** [comment]
We should have a better error message in this scenario too.

**Comment by hakamadare** [comment]
aha!  @gabriel that's it.  i have two user accounts on the same machine (work and personal, see #2604), that's probably what happened.  after changing the permissions, KBFS runs without error.

it would be nice to have a more informative error message in this event :)
