### ISSUE TITLE
GUI not loading, no KBFS

### ISSUE THREAD

**Issue by plttn** [keybase/client#6897]
So on my Surface Book (which seems to have lots of trouble with Keybase [#5215]), I now can't load the client at all. KBFS isn't starting, so I don't even have the K: drive that would be inaccessible anymore. 

my log id: `8eed4a4c49681b668b1f5d1c`

**Comment by plttn** [comment]
Upon further inspection, it looks like both of my Windows clients cannot load GUI or access KBFS. 

other client log: `3d55f92809ff36a9b3ffa41c`

**Comment by maxtaco** [comment]
cc: @zanderz

**Comment by plttn** [comment]
Looks like this is potentially an AV interaction issue. 

https://virustotal.com/en/file/e638a56952be1f3f78b7f1c41fb875c9d6b93717ba4554263ec25b8afdb722d6/analysis/1493082395/

I use Bitdefender, which is one of the AVs flagging `runquiet.exe`.

**Comment by zanderz** [comment]
It does look as though our launcher utility, runquiet.exe, was blocked.
Among the measures we're taking to cut down on this, we're renaming runquiet.exe to keybaserq.exe, and we're going to stop rebuilding it for every release, so hopefully the false positive reports can have more of an effect. If you would like to try the keybaserq change, you can [download it here](https://s3.amazonaws.com/prerelease.keybase.io/windows/Keybase_1.0.22-20170505141404%2B2a65c39.386.exe)

**Comment by plttn** [comment]
Looks like that version (and today's definition updates in Bitdefender) stops the trojan detection in the shortcut, but still flags [keybaserq](https://www.virustotal.com/en/file/1bf95ea81e25ee011d275ec1188bb6f6af5c01bcc4dc326244fe2cd2e90333d2/analysis/). I've added an exclusion for now in Bitdefender.

**Comment by zanderz** [comment]
thank you, that's an interesting result. We'll re-submit.

**Comment by jsb2092** [comment]
I am still having the issue with the release from zanderz from 2 days ago.  Every time I restart my computer, it won't load keybase without uninstall and reinstalling it.  I am not using any 3rd part AV application other than that built into Windows.

**Comment by zanderz** [comment]
@jsb2092 You said the version from 9 days ago fixed this, right? https://github.com/keybase/client/issues/6687#issuecomment-298427438
And now it came back? The same fix should be in both builds. Can you please do a `keybase log send`? Thanks.

**Comment by jsb2092** [comment]
@zanderz Correct, it DID fix it, until I rebooted.

The log ID is: 11a20128ef0f87012647a31c

**Comment by zanderz** [comment]
Thank you @jsb2092. I see the GUI connecting to the service at 9:44 today in this log, did it work that time or was it in disconnected state?

**Comment by jsb2092** [comment]
@zanderz Correct, that was after a reinstall.  This is a log after a reboot
f46a54966723ef893fb1941c

**Comment by zanderz** [comment]
ah ok, @jbs2092, the service doesn't seem to be running at all in that second log. The installer logs seem to  show that the startup shortcut was added OK. Does Task Manager show any instance of `keybase.exe` running (lower-case)? Do you have a shortcut called `KeybaseStartup` in `%APPDATA%\Microsoft\Windows\Start Menu\Programs\Startup` ? 

If keybase.exe is not running and the shortcut is present, can you try just invoking it?

Maybe our log send needs to add some of this info, but in the meantime, thanks again.

**Comment by jsb2092** [comment]
@zanderz 
I have 4 instances of keybase.exe running in task manager.  KeybaseStatup is in the startup folder

This is a new log, along with some output from when I generated it.
- INFO ignoring error getting keybase status: Timed out waiting for pipe '\\.\pipe\kbservice\Users\jsb\AppData\Local\Keybase\keybased.sock' to come available
- INFO ignoring UI logs: Timed out waiting for pipe '\\.\pipe\kbservice\Users\jsb\AppData\Local\Keybase\keybased.sock' to come available


------------
Success! Your log ID is:

  3c3d4f0dd2561b09075a4c1c

**Comment by zanderz** [comment]
@jsb2092 Are these 4 instances of `Keybase.exe` (capitalized), or are any of them `keybase.exe` (all lower case)? Did you double-click KeybaseStartup?

**Comment by jsb2092** [comment]
@zanderz sorry, I didn't fully answer previously.  They were all with an uppercase K, and clicking on the KeybaseStartup caused two lowercase k instances to start (named Keybase utility)

**Comment by zanderz** [comment]
@jsb2092 The 3c3d4f0dd2561b09075a4c1c log still looks like lower-case `keybase.exe` is not running at all - I assume it was sent before you launched KeybaseStartup? If not, is the GUI connected now? If the GUI is still not connected, can you "quit" it via the tray menu and restart it with the start menu `Keybase` shortcut?

**Comment by jsb2092** [comment]
@zanderz yes, that was before I ran statup, and running the startup manually did fix it.
