### ISSUE TITLE
Unable to provision new iOS device

### ISSUE THREAD

**Issue by dmytton** [keybase/client#6907]
Using the iOS beta (1.0.0 179) on iPhone 7 Plus (iOS :

1. Tap log in
2. Enter username `davidmytton`
3. Tap the laptop device I want to connect with
4. Scan the QR code from the screen

The view changes to a blank view and remains there forever. 

After several attempts and force close, I did also manage to get it to go to a login screen saying "Pick an option" but with no options to select, and a red "Unknown RPC error"

![img_0591](https://cloud.githubusercontent.com/assets/117833/25823657/aec2601e-3434-11e7-94c9-4a3514de4175.PNG)

![img_0592](https://cloud.githubusercontent.com/assets/117833/25823786/0c1603f6-3435-11e7-82e9-9403d2dfab8b.PNG)

**Comment by cjb** [comment]
Thanks!  We've just pushed a fix for this bug, it'll be in the next update.

**Comment by dmytton** [comment]
Confirmed fixed on 1.0.1 (2)
