### ISSUE TITLE
Window just says loading forever

### ISSUE THREAD

**Issue by johnmarc** [keybase/client#6940]
Unable to log in or proceed
Keybase GUI Version: 1.0.22-20170510160050+38e68d7
ubuntu 17.04

**Comment by cjb** [comment]
@johnmarc please can you run `keybase log send` in a terminal and tell us the ID?

**Comment by johnmarc** [comment]
my log id: 420ece3ba9825ba9d9a6ee1c

**Comment by johnmarc** [comment]
also:  898821c6afe0d33b3ba52d1c
from with the daemon running

**Comment by cjb** [comment]
the error is

93 2017-05-10T15:35:45.710389-04:00 ▶ [ERRO keybase standard.go:230] 017 open /home/(you)/.config/autostart/keybase_autostart.desktop: permission denied

**Comment by johnmarc** [comment]
Thanks dropbox for setting that up as owned by root.  You guys should detect that and ask for sudo.

**Comment by cjb** [comment]
Ah, weird.  You're the first person to report this error to us.  But you're probably not the first Dropbox user who installed Keybase.  Wonder what's up with that.

**Comment by johnmarc** [comment]
dropbox was literally the first thing I installed when I set up this machine, so it likely created the autostart directory and was running as root when it did so for whatever reason

**Comment by johnmarc** [comment]
anyway I'm good now
