### ISSUE TITLE
Can't access /keybase/private/MYUSERNAME

### ISSUE THREAD

**Issue by daveio** [keybase/client#6952]
I can't access /keybase/private/dave or /keybase/private/dave,olivercole as it asks for rekeying by opening the Keybase app on the device I'm using, or entering a paper key the app already knows (and even if re-entered, nothing changes). This is an issue I've encountered before.

I can only assume there is something wacky in the tree of devices I've built up over time. Is it possible to completely reset my account, re-enrol devices, and recreate proofs? I don't have anything important stored on KBFS so if I lose access to its current contents, that's fine.

While this keeps popping up, I can't rely on Keybase to be useful 😞 

In an ideal world I'd delete my account and recreate it, but the deletion process explicitly says that I can't re-use my username - since I managed to snag 'dave', I'm really reluctant to lose it.

Any assistance greatly appreciated.

my log id: ee1826886119c1cc687b801c

**Comment by strib** [comment]
Sorry @daveio, this looks to be related to a new server rollout we did today.  It's returning incorrect timestamps, and makes it look like the updates to those folders happened _after_ you revoked the device that made the updates, rather than before.  Shouldn't need to do anything to your account or the folders, we just have to fix the backend.  We're looking at it now.

**Comment by daveio** [comment]
@strib Thanks for the info, these things happen 😄  Is there anywhere I can get notified that the fixup is done, so I can make sure everything goes back to normal on my end too?

**Comment by strib** [comment]
It should be working now, we reverted the fix (hadn't gotten back here to update yet, sorry).  Can you confirm things look ok?

**Comment by strib** [comment]
(might need a Keybase restart to see it working)

**Comment by daveio** [comment]
@strib ...and sorted. Yep, that was definitely the issue. Thanks again!
