### ISSUE TITLE
Unable to prove facebook

### ISSUE THREAD

**Issue by portante** [keybase/client#6988]
Posting the link provided by command line, "`keybase prove facebook portante`", gives me simple page with, "`Error 403. Bad input.`".

**Comment by portante** [comment]
I have not been able to prove my facebook account as a result.

**Comment by maxtaco** [comment]
cc: @oconnor663

**Comment by lepinkainen** [comment]
I'm having the exact same issue.

**Comment by jparnzen** [comment]
Happening here too. I've tried Chrome and Safari on macOS 10.12.4, both continually failed. Thought it might be a browser plugin (maybe ublock origin) but disabling that didn't help. Same error as @portante upon submitting the post to facebook. URL showing in the address bar for the error is:
https://keybase.io/_/facebook_callback?sig_id_med=WO3NzV0vgmadcnzpWBzHf5oOkkvmnfA8twLqQM21FoI&token=lgHZIDI3OWE5Mjc3MDFjMTRmMjRmNWFkMGZiZTExOTMyYjE5zlkX2oTOAAP0gMDEIGlz8UgYFBI8ZqPT3yA%2BIOaSlsfUViR85yapoZ2sJMNF#_=_

**Comment by dddw** [comment]
same here... indeed on mac sierra... can try to replicate it on debian.

**Comment by oconnor663** [comment]
Working on a fix. You can follow along in https://github.com/keybase/keybase-issues/issues/2974.

**Comment by oconnor663** [comment]
Ok, the fix is live. Please try it out and let me know if you run into problems.

Note that you'll need the very latest version of the client, or you'll see an `Unexpected path` error.

**Comment by portante** [comment]
Fixed, thanks!
