### ISSUE TITLE
Website: Non-direct path to sigchain and graph? 

### ISSUE THREAD

**Issue by diego898** [keybase/client#7011]
From my main site:

https://keybase.io/diego/

it seems the only way to get to my graph and sigchain, is to click on devices to get to:

https://keybase.io/diego/devices

From there, I can now click on the tabs to get to:

https://keybase.io/diego/graph

and

https://keybase.io/diego/sigchain

Is this desired? 

Note: I'm not sure if this is the best repo for this

**Comment by cjb** [comment]
Yes, that's desired.

**Comment by diego898** [comment]
Hm. that seems a bit strange to me but ok
