### ISSUE TITLE
Application not starting fully

### ISSUE THREAD

**Issue by JeroenDeDauw** [keybase/client#7015]
![hangs](https://cloud.githubusercontent.com/assets/146040/26124779/f7d120c8-3a7f-11e7-8efc-5ab1f3e052eb.png)

I get this on my desktop machine. Working fine on my laptop. Both running Kubuntu. No idea what's going wrong or how to debug.

Followed the instructions at https://keybase.io/docs/the_app/install_linux for x64 Ubuntu. Removed and reinstalled, same issue.

When executing `run_keybase` I get

> $ run_keybase
Shutting down kbfsfuse...
Launching keybase service...
Mounting /keybase...
Launching Keybase GUI...
Success!

After which the window comes up and does bugger all.

> $ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 17.04
Release:        17.04
Codename:       zesty

App version: I don't know, it's not in the help menu and it's not output to the CLI either.

> $ keybase log send
usage: keybase [-h] [-v] [-p PASSPHRASE] [-c CONFIG] [-i] [-d] [-q] [-C]                                                                                                                                                                           
               [--port PORT] [--no-tls] [--host HOST]
               ...

**Comment by cjb** [comment]
It sounds like you might have a super old version of `keybase` on your $PATH, since it doesn't seem to support `keybase log send`.  Try moving it out of the way?  `which keybase` to see where it is.

**Comment by JeroenDeDauw** [comment]
Indeed. I ran `sudo rm /usr/local/bin/keybase` and installed the thing again. Works now. Thanks
