### ISSUE TITLE
Disabling KBFS drive makes client unable to login

### ISSUE THREAD

**Issue by Albirew** [keybase/client#7022]
Following #4713 to disable KBFS, I replaced `watchdog2` by `watchdog` on KeybaseStartup link.
At  next reboot, Keybase GUI would not login at all.

Keybase GUI Version: 1.0.22-20170515072240+b608f0e
[keybase.app.log](https://pastebin.com/GiDkMCAj)
[keybase.service.log](https://pastebin.com/6V1eb4w1)

**Comment by maxtaco** [comment]
Please do a 'keybase log send' from your shell.


Thanks

**Comment by Albirew** [comment]
Here is my log ID:

  e8fe4eebe2641237e0de601c

**Comment by jzila** [comment]
KBFS isn't running on this user's device. Chat requires KBFS. The instructions in #4713 disable KBFS completely, where they should actually launch KBFS with `-mount-type=none`. cc @zanderz

**Comment by zanderz** [comment]
@Albirew 4713 was a long time ago, before we had Chat. Sorry for the confusion, and thanks for reading the issues first. If you really don't want the filesystem, you should uninstall Dokan and put your shortcut back to `watchdog2` and chat should work again after restart.

**Comment by Albirew** [comment]
Thanks a lot, this indeed work now.
Too bad there's not an option to choose when to mount KBFS (at boot, manually or never) but I understand there's more critical tasks to do before thinking about customization =)
