### ISSUE TITLE
Keybase updated on 5/15 ended ability to access secure channels

### ISSUE THREAD

**Issue by DeepMac** [keybase/client#7029]
[NOTE: Edited to change screenshot to protect others privacy]

Updated on 5/15/17. Lost connectivity to a group chat (5 people including me). Restarted PC several days later. Could access all chats except group chat. Continued to receive notices that encrypted messages were waiting but attempting to view them gives a "securing..." wait dialog.

Tried logging out, and then logging back in. After entering passphrase it threw odd errors about time-outs, but eventually connected. Still couldn't access chat.

Attempted a Repair installation, failed. Log indicated a VC Redistribution package it was looking for in package cache was missing. Uninstalled and re-installed. Attempted to login via command line, got "Aborting, error connecting" messages.

Uninstalled again. Renamed AppData sub-dirs under user profile, re-installed and ran. Attempted to add PC as a new device, got bizarre loop error message. Seemed to automatically "add" itself without user data entry after a while. Attempted to login, times-out trying to login.

Similar attempts to authorize and login via the mobile app on an Android phone are stimied. Account may be compromised and/or corrupted, :(

See screenshots of running through a fresh install with the original profile data in place.
![k1](https://cloud.githubusercontent.com/assets/4560942/26177098/62914e50-3b26-11e7-84dc-c2a948c04a08.png)
![k2](https://cloud.githubusercontent.com/assets/4560942/26177099/6291e70c-3b26-11e7-848f-d083050b06e4.png)
![k3](https://cloud.githubusercontent.com/assets/4560942/26177100/6293494e-3b26-11e7-9b05-e231e81b12f5.png)
![k4](https://cloud.githubusercontent.com/assets/4560942/26177101/6297f714-3b26-11e7-9d80-6c589e5da539.png)
![k5](https://cloud.githubusercontent.com/assets/4560942/26177096/6290b29c-3b26-11e7-8ef7-3bb06454221a.png)
![k6](https://cloud.githubusercontent.com/assets/4560942/26179103/8ee0351c-3b2f-11e7-9be5-8daa9b7163f6.png)
![k7](https://cloud.githubusercontent.com/assets/4560942/26177097/6290cab6-3b26-11e7-99cf-34eccf3dfdfe.png)

my log id: 8be25de1be88b3be52f4af1c

**Comment by maxtaco** [comment]
Cc @zanderz

**Comment by jzila** [comment]
@DeepMac: Thanks for the report! I have a fix in the works that should address this scenario. In the meantime, I'd appreciate some help debugging:

Please give me the output of the following commands:
```
dir %USERPROFILE%\AppData\Local\Keybase\kbfs_block_cache
type %USERPROFILE%\AppData\Local\Keybase\kbfs_block_cache\version
```

To workaround this issue, you can do the following:
WARNING: DELETING MULTIPLE FILES
```
rd /S /Q %USERPROFILE%\AppData\Local\Keybase\kbfs_block_cache
```

**Comment by DeepMac** [comment]
For dir %USERPROFILE%\AppData\Local\Keybase\kbfs_block_cache

```
04/28/2017  02:59 PM    <DIR>          .
04/28/2017  02:59 PM    <DIR>          ..
04/28/2017  02:59 PM    <DIR>          v1
05/13/2017  08:05 PM                 1 version
               1 File(s)              1 bytes
               3 Dir(s)  276,146,511,872 bytes free
```
However for type %USERPROFILE%\AppData\Local\Keybase\kbfs_block_cache\version I get nothing.  The file contains just a single byte with a value of zero.

As for rd /S /Q %USERPROFILE%\AppData\Local\Keybase\kbfs_block_cache
well that just made it worse, ultimately. Now I can't see *any* of the historical chat data. >_<

Feel free to hit me up with as much debugging/troubleshooting requests as you need.

**Comment by jzila** [comment]
@DeepMac thanks! Could you submit another `keybase log send` please?

**Comment by jzila** [comment]
Next, from the "Keybase Shell" (same place you type `keybase log send`), try the following:
```
keybase ctl stop --kill-kbfs
keybase ctl start watchdog2
```

**Comment by jzila** [comment]
If after ~30 seconds that still doesn't work, please submit another log send.

**Comment by DeepMac** [comment]
I sent the first keybase log as you requested and attempted to run keybase ctl stop --kill-kbfs but it threw an error about not being able to connect to the pipe. I ended up rebooting entirely and now it seems to be fully functional again!
I'll report if I see anything untoward related to the issue here. If you still want me to run the keybase ctl commands let me know.

**Comment by jzila** [comment]
Glad to hear it @DeepMac. Sorry about these issues; FWIW you've helped narrow down many of the failure modes in the initialization of the disk cache so I can make it much more robust :)

**Comment by jzila** [comment]
I'm closing the ticket for now since it seems that you're unblocked. Please reopen if it happens again.
