### ISSUE TITLE
Keybase App shows only blank panes

### ISSUE THREAD

**Issue by tml** [keybase/client#7049]
It's me again - the guy from #4472. Same problem - white panes in the app, rebooting and reloading the launchctl process don't restore it. Currently trying a complete reinstall of keybase. The app was working about a week ago, but it appears there was a brew update on 2017-05-15 which appears to have broken it for me.

my log id: f6c23ce3e165de7710bc151c

**Comment by maxtaco** [comment]
Looks like your keybase service isn't running...

**Comment by tml** [comment]
`keybase status` says:

```
KBFS:
    status:    running
    version:   1.0.2-20170515141757+8c10902
    log:       /Users/joeysmith/Library/Logs/keybase.kbfs.log

Service:
    status:    running
    version:   1.0.22-20170515141716+b608f0e
    log:       /Users/joeysmith/Library/Logs/keybase.service.log
```

**Comment by tml** [comment]
I have also just confirmed that I am able to have chats with people using the "keybase chat" tool.

**Comment by maxtaco** [comment]
Hmm, then weirdly the electron UI is having issues connecting.  It is a
permissions thing, did you run some install components as root?

Cc: @gabriel

**Comment by tml** [comment]
Not that I am aware of. However, a complete uninstall and reinstall of the app seems to have cleared the issue up, so feel free from my end to mark this as closed - mostly, I just wanted to make sure you guys got the logs in case it's a deeper issue.

If there's any commands I can run or info I can provide that might help you uncover the root cause, let me know.

**Comment by Heliosmaster** [comment]
This might be related to #6965 ?
