### ISSUE TITLE
Unable to login: `problem communicating with our servies`

### ISSUE THREAD

**Issue by ThomasVuillaume** [keybase/client#7076]
Good morning everyone !

I have some troubles loggin in Keybase for a few days. It's not able to log in the Windows app, and says it has problem communicating with our servies.

I just sent some logs under id: 1d0fa2a4fc98fed45619c51c

Hope this helps...

Good luck guys !

**Comment by jzila** [comment]
@ThomasVuillaume: Please do the following:
```
del %USERPROFILE%\AppData\Local\Keybase\kbfs_block_cache\version
```
We've merged a fix for this issue and the next public build will include it.

**Comment by ThomasVuillaume** [comment]
Hey great this is fixed with this tweak ! 

Thank you !

**Comment by ThomasVuillaume** [comment]
Just curious before closing, any clue what was the issue ?

**Comment by jzila** [comment]
Not sure why the bad write happens, but we've made a disk cache initialization errors nonfatal going forward.
