### ISSUE TITLE
Can't find the private PGP key

### ISSUE THREAD

**Issue by BigBlueHat** [keybase/client#7082]
I used the keybase UI to generate a PGP key during setup. It was nice and easy and made me happy. 😁 

However, when I went to backup the private key, it's un-findable...which is concerning. It also means I'm unable to use the various gpg tools with the key.

I'm sure it's here some place... Some pointers would be helpful.

Thanks!
🎩

**Comment by zapu** [comment]
If you have generated PGP key on the website, told it to store your secret key (encrypted), and it's not in your local gpg keychain, you can export your secret key using `keybase pgp export -s`. Let me know if that answers your question - there are multiple ways to generate and store PGP keys, maybe I got that wrong. 

Thank you for using Keybase!

**Comment by BigBlueHat** [comment]
@zapu thanks! I used the Windows 10 app and only kept a copy on the local machine. I'll try the export command and report back! Cheers!

**Comment by zapu** [comment]
@BigBlueHat Did you manage to get your key exported? I can help further if you still have troubles.

**Comment by BigBlueHat** [comment]
Yep! Thanks @zapu That worked like a charm.

It's probably worth documenting some place besides here, though. I'll make another ticket. 😸
