### ISSUE TITLE
Unable to login to client; can login to site

### ISSUE THREAD

**Issue by schmichael** [keybase/client#7114]
I created a keybase account ages ago, but I stopped using it and [because I can't be trusted with pgp keys](http://pgp.mit.edu/pks/lookup?search=michael+schurter&op=index) decided to delete my pgp key on the way out.

I tried using keybase again today and while I can login to the site, neither the CLI nor GUI let me in:

![cli](https://cloud.githubusercontent.com/assets/113362/26367095/51b05272-3fa2-11e7-9340-95ab3c9756fe.png)

![gui](https://cloud.githubusercontent.com/assets/113362/26367097/546f2038-3fa2-11e7-8f3d-6c6387163758.png)

I'm guessing the client doesn't like accounts without pgp keys associated? I'm not sure how to get started with keybase again without just creating a new account.

Email on account: michael.schurter@gmail.com

**Comment by jzila** [comment]
@schmichael: we'll need a log from your client to be able to help: `keybase log send` from a terminal, with a quick description in the prompt (or a link to this ticket).

Additionally, it's possible that you didn't have your email address on the account. Is this you?
https://keybase.io/schmichael
If so, you can try logging in with the username instead of the email address.

**Comment by schmichael** [comment]
Log ID: 3b341786f317d4d142309e1c

That account is me. That email address is associated and verified. Same error message if I try logging in with schmichael.

**Comment by jzila** [comment]
Thanks! @maxtaco: would you mind taking a look?

**Comment by maxtaco** [comment]
This is some corner case having to do with a reset account seems like

**Comment by maxtaco** [comment]
@oconnor663 when you get a chance can you check this out?

**Comment by maxtaco** [comment]
Also, for now try `keybase db nuke` and see if that helps

**Comment by schmichael** [comment]
`keybase db nuke` fixed it! (Well I actually just `rm -RF ./local/shared/keybase/` to be safe)

Now the chat I reinstalled keybase to open is stuck saying "Securing..."

I'm guessing since I don't have a pgp key there's no way for it to continue? (`keybase pgp list` is empty)

**Comment by maxtaco** [comment]
Can you do another `keybase log send`?

**Comment by oconnor663** [comment]
(I'll follow up here if we get another log send from @schmichael.)

**Comment by schmichael** [comment]
New log: e393265ae2b82bdaabce361c

It mysteriously works after a reboot though so.... feel free to close.

**Comment by jzila** [comment]
@oconnor663: do you want to continue debugging this, or should we count our blessings and close?

**Comment by oconnor663** [comment]
Filed [a task](https://keybase.atlassian.net/browse/CORE-5421).

**Comment by schmichael** [comment]
Let me help.
