### ISSUE TITLE
[Android] App crashes on startup

### ISSUE THREAD

**Issue by io4** [keybase/client#7123]
First start worked fine, but since I first rebooted it cant start.

Android Version: 4.4.4
LogCat output: http://pastebin.com/raw/hYhDtHfq

I am a root user, so I could extract more debugging info if needed.

**Comment by NoahSchmitz** [comment]
Never has worked for me. Crashes almost immediately after launching. I assumed it was because I am running Android "O" but maybe not. Nexus 6P if that helps

**Comment by CWRau** [comment]
Crashes immediately after launch for me as well. I'm also running Android O, but on a Nexus 5x.
LogCat; https://keybase.pub/cwrau/Keybase%20Android%20Crash.log

**Comment by io4** [comment]
I found that the keybase *service* is fine. Since I still get notfications from new messages.

It has to be a UI loading issue...

**Comment by techtheory** [comment]
Same issue. Running Android O beta. App crashes during its startup. Never get past blue patterned splash screen.

**Comment by ismail-s** [comment]
Same issue on KitKat.

**Comment by CWRau** [comment]
This issue has been resolved for me in version 1.0.3
(Running Android O Developer Preview 3 on Nexus 5X, not rooted)

**Comment by io4** [comment]
Not fixed for me. This time I am allowed to "Inform" the error.

@CWRau did you clean data to fix?

**Comment by CWRau** [comment]
@io4 
No, but I never had the app running before, so it wouldn't have changed anything anyway
