### ISSUE TITLE
Why is passphrase needed to add my public key?

### ISSUE THREAD

**Issue by reybango** [keybase/client#7134]
Sorry for posting here but I couldn't find a support email on the site.

I wanted to know why my pgp passphrase for my private key is needed to add the public key to keybase. When I added my key via the CLI, I was prompted for my private key passphrase which kind of threw me off. I submitted another key to a public keyserver and wasn't asked for my passphrase. 

Would love your thoughts on this.

**Comment by malgorithms** [comment]
answered this in keybase chat separately, but figured I would post here:

> it's because the keybase app wants you to prove (to the world) you own the private key and that you want it associated with your account.  "reybango" owns some account, and maybe some other keys and social announcements.  To provably connect your PGP key with redbango, the PGP private key must sign a statement claiming to be reybango (and actually referencing your other key(s) on your account). This prevents impostors - for example, you putting my public key on your profile....traditional key servers are full of fake keys, for example there are like 1000's of fake gavin andresen keys on the public key servers. (notably this is possible because they don't demand you prove ownership of an email account.)
> ​
> by default the keybase app just sends commands to GPG to do this for you, but it needs your passphrase to do that. Keybase can also import your private key into its own keychain (locally) so you can do things like keybase pgp sign later without using GPG at all. but that's an optional thing -- normally it uses that passphrase once and then throws it away.
> ​
> `keybase help gpg` for better explanations btw!
