### ISSUE TITLE
Chromium extension: Opening tweets causes additional "Keybase Chat"-buttons to appear

### ISSUE THREAD

**Issue by sundhaug92** [keybase/client#7139]
1. Open a twitter profile page
2. Click on a tweet
3. Repeat 2 until satisfied

Result:
![image](https://cloud.githubusercontent.com/assets/519283/26434357/a2481974-4108-11e7-9669-7f47be4c636b.png)

**Comment by strib** [comment]
cc: @shazow

**Comment by shazow** [comment]
I'll have a fix pushed out shortly! :)

**Comment by shazow** [comment]
Fixed in v1.8.9 which should be live any minute now.
