### ISSUE TITLE
Reddit proof fails

### ISSUE THREAD

**Issue by PaulSpoerry** [keybase/client#7166]
My Reddit proof keeps failing. I've tried twice now. The link to the proof is here: https://www.reddit.com/r/KeybaseProofs/comments/6defxm/my_keybase_proof_redditt1pimp_keybasepaulspoerry/

It is possible that it's because I use a different handle there than on Reddit? Is that an issue?

**Comment by maxtaco** [comment]
Graylisted

**Comment by PaulSpoerry** [comment]
Thank for the quick reply @maxtaco. I've google'd and even looked ON reddit. What's greylisting?

**Comment by maxtaco** [comment]
Another possible theory --- did you delete the reddit statement after the proof worked?

**Comment by cjb** [comment]
@PaulSpoerry We're thinking your account's shadowbanned -- you can see your posts but no-one else can.

If an incognito window *doesn't* show your post but your logged in account does, that's what it is.

**Comment by PaulSpoerry** [comment]
Thanks @cjb . I'll admit I'm not a heavy reddit contributor (I find a lot of content but I'm not often contributing). Curiously, if I go incognito I can see my [keybase proof](https://www.reddit.com/r/KeybaseProofs/comments/6dh8u4/my_keybase_proof_redditt1pimp_keybasepaulspoerry/) and I can see comments that I've made ([ex](https://www.reddit.com/r/antivirus/comments/5ps05l/avoid_the_new_version_of_malwarebytes_30/)) and [my profile](https://www.reddit.com/user/T1Pimp).

**Comment by cjb** [comment]
@PaulSpoerry I can't see your profile.  I still suspect you're shadowbaned, not sure why going incognito didn't help show that though.

**Comment by PaulSpoerry** [comment]
Thanks for the help @cjb and @maxtaco. It was my profile on reddit. It's been reinstated and the proof now works. Thanks so much!
