### ISSUE TITLE
[Android] Creating facebook proofs fails

### ISSUE THREAD

**Issue by sporkwitch** [keybase/client#7170]
When attempting to generate a Facebook proof on the Android version (running on Asus Chromebook C100 Flip and direct-from-Google Nexus 6) it appears to display something about making a post, then immediately returns to asking for username with a red error about an unexpected hash.

**Comment by plttn** [comment]
Facebook proofs are currently broke, see [keybase on twitter](https://twitter.com/KeybaseIO/status/868121041910026240).

**Comment by sporkwitch** [comment]
Issue resolved
