### ISSUE TITLE
[Android] New chat messages delayed

### ISSUE THREAD

**Issue by sporkwitch** [keybase/client#7171]
In the chat function, notifications for new messages appear, but the application itself does not update for minutes at a time, if at all.  Issue present on Asus Chromebook C100 Flip and direct-from-Google Nexus 6.

**Comment by zoof** [comment]
I've noticed the same issue on a Galaxy s3 running Cyanogenmod.

**Comment by sporkwitch** [comment]
Issue appears to be resolved
