### ISSUE TITLE
Invite email verification errors on whitespace

### ISSUE THREAD

**Issue by mholkesvik** [keybase/client#7172]
<img width="293" alt="with trailing space" src="https://cloud.githubusercontent.com/assets/1395356/26509193/95d05e18-420c-11e7-92a2-2216f5d66e28.png">

Keybase Desktop on Mac

"Friend's email" input field complains when a valid email has a trailing space.

**Comment by cmeury** [comment]
Encountered that as well, but on the Android app (latest version, 1.0.2, updated 18 May 2017). Leading or trailing space leads to the error:

**There was an error provisioning**
Unknown error: Bad username or email:
`email@example.com`

**Comment by chrisnojima** [comment]
Ticketed on our side, thanks!
