### ISSUE TITLE
Twitter and Github -only avatars are not very inclusive

### ISSUE THREAD

**Issue by eki** [keybase/client#7255]
Got my wife to try keybase and the first thing she wanted to do was set her avatar... she's not a software developer (no Github) and doesn't like twitter... so, uh, I guess she's SOL.  : \

Would absolutely *love* if setting a profile picture were as easy as dropping the image into her kbfs. I'd actually love to use that, too, even though I have a github-based avatar. I think kbfs would actually be a nice place to store something like an avatar picture that I end up re-using on multiple services, but can never find when I need to upload it to yet-another-social-blah.  : )

**Comment by yahooeny** [comment]
it's to my understanding that keybase relies on gravitars which are linked to the email address you sign up with
https://en.gravatar.com/

**Comment by eki** [comment]
I can't find any reference to gravatar in the docs or in the app. I see there have been issues opened to request gravatar support, but I don't see anything saying it's been definitively added.

The keybase desktop app says, "For now, Keybase shows your profile photo from your Twitter or Github proofs."

**Comment by Syncrossus** [comment]
I agree that the avatar system seems arbitrarily restricting. To be fair however, your wife is not Keybase's target demographic (whether she *should* be is another debate entirely).

**Comment by strib** [comment]
This isn't the case anymore.  You can put avatars in `/keybase/public/<you>/me/avatar.jpg`.
