### ISSUE TITLE
kbfs not uploading files

### ISSUE THREAD

**Issue by lyneca** [keybase/client#7258]
Hello,
Stuff I put in my /private/me,other/ folder isn't appearing for the other person or any of my other devices.
I am also unable to receive any changes, except once initially when killing keybase and kbfsfuse and then running run_keybase.

my log id: 0c45c3d0180bb7775763c71c

**Comment by lyneca** [comment]
Okay, this managed to fix itself somehow...

**Comment by strib** [comment]
Hi @lyneca -- sorry, you were hitting a known bug in a new performance optimization. It is fixed in the most recent releases, so maybe you upgraded and restarted Keybase to get it to work?  Let me know if you see any more issues.

**Comment by bs78ta** [comment]
Running Keybase on windows 7 64 bit. The files I am putting in my keybase folder are not uploading to server. It will show them encrypting and uploading but the process never finishes. The timer will count down fron 8 sec to 4 and then just restarts again at 8. Never finishes the loop. Attaching pic, Thanks
![Untitled](https://user-images.githubusercontent.com/32412352/55584899-01dbdc00-56eb-11e9-99e9-0f6104fc68fc.png)
