### ISSUE TITLE
Issue after reset

### ISSUE THREAD

**Issue by PokeAcer** [keybase/client#7261]
After resetting my account with new keys for security (I used to have my VPS and such on there and I'd rather not), I have issues with chat. My first message sends fine, but any message after that fails; it keeps getting random errors or network connectivity issues.

my log id: b382a07700fce35a213efc1c

**Comment by maxtaco** [comment]
Can you try `keybase logout` and then `keybase login` from the prompt?

**Comment by PokeAcer** [comment]
After doing such, it worked fine on my phone and Desktop; thanks! :3
