### ISSUE TITLE
Cannot push to private bare repo

### ISSUE THREAD

**Issue by spiveeworks** [keybase/client#7264]
I made a repository on an external hard drive, committed some things, and then made a bare clone in my personal folder.
Pushing to this repo worked once, but now when I attempt to push I get:

```
Counting objects: 6, done.
Delta compression using up to 6 threads.
Compressing objects: 100% (3/3), done.
Writing objects: 100% (3/3), 1001 bytes | 0 bytes/s, done.
Total 3 (delta 1), reused 0 (delta 0)
error: Couldn't set refs/heads/plan
To K:/private/spivee/short
 ! [remote rejected] plan -> plan (failed to write)
error: failed to push some refs to 'K:/private/spivee/short'

```
I copied the bare repo out using explorer, and set up a new remote to which I could push without issue.

useful and descriptive: 775d23033f1ba504bea03d1c

**Comment by strib** [comment]
Hi @spiveeworks, I don't see any immediately obvious errors in the log -- do you know about what time you had the error?  Or about how long before you sent the log?  Thanks.

**Comment by strib** [comment]
Oh I did find this error, not sure if it's fatal for git or not:

```
2017-06-05T08:29:09.412572+10:00 - [DEBU kbfs file.go:58] d5f2 Cleanup {{{2} plan.lock 0x12498380 0x15170ed8 0x1431f850 {}}} [tags:DID=Wghy2H3xbvoOGqaDCtaHgw]
2017-06-05T08:29:09.412572+10:00 - [DEBU kbfs dir.go:124] d5f3 Request complete [tags:DID=Wghy2H3xbvoOGqaDCtaHgw]
2017-06-05T08:29:09.412572+10:00 - [DEBU kbfs fs.go:570] d5f4 refusing to replace existing target [tags:DID=Wghy2H3xbvoOGqaDCtaHgw]
```

@taruti any ideas?

**Comment by spiveeworks** [comment]
I think I tried pushing a number of times, including maybe within an hour prior to sending the log?
Sorry that I can't help more

**Comment by spiveeworks** [comment]
I tried `git push` again and sent an updated log: afafd157a0af4eb91480391c
as described the push was about 09:22

**Comment by spiveeworks** [comment]
sometimes I get decryption notifications when I push (presumably when the cache is clear) but I don't get encryption notifications as far as I can tell. That time I got no notifications.

**Comment by strib** [comment]
Thanks!  I see that same error a 09:22:

```
2017-06-05T09:22:45.444512+10:00 - [DEBU kbfs file.go:58] ea96 Cleanup {{{2} plan.lock 0x12498380 0x14988368 0x1431f850 {}}} [tags:DID=IGbj_OxKcD3c9HvzVayYHg]
2017-06-05T09:22:45.444512+10:00 - [DEBU kbfs dir.go:124] ea97 Request complete [tags:DID=IGbj_OxKcD3c9HvzVayYHg]
2017-06-05T09:22:45.444512+10:00 - [DEBU kbfs fs.go:570] ea98 refusing to replace existing target [tags:DID=IGbj_OxKcD3c9HvzVayYHg]
```

@taruti can you please take a look?

**Comment by taruti** [comment]
Will look at this tomorrow morning. Error comes from a MoveFile (i.e. rename) with existing target. 

@spiveeworks does this reoccur if you manually remove `plan.lock`? An interrupted git run might have left it behind.

**Comment by spiveeworks** [comment]
there is no `plan.lock`

also I just noticed that when I push using gitextensions I get the following dialog:
![image](https://cloud.githubusercontent.com/assets/9738637/26806590/fae94e78-4a94-11e7-8bf4-d8c98a9bbf87.png)

**Comment by spiveeworks** [comment]
so I realized that the last time a push worked, it was from Ubuntu on the same machine, so I tried that again and it worked: 80f0b88f72ab33417ba0e61c

The push was in the last few minutes.

**Comment by spiveeworks** [comment]
pushing from windows still doesn't work, I tried cloning the repo out of private again to see if it was config related, and am now getting

```
"C:\Program Files (x86)\Git\bin\git.exe" clone -v --recurse-submodules --progress "K:/private/spivee/short" "T:/docs/short-new/short"
Cloning into 'T:/docs/short-new/short'...
fatal: failed to open 'K:/private/spivee/short/objects/info': No such file or directory
fatal: The remote end hung up unexpectedly
Done
```
