### ISSUE TITLE
ERROR Bad key found: no private key material or GPGKey

### ISSUE THREAD

**Issue by ambigit** [keybase/client#7265]
When I try to log in through command line or GUI, after entering my password, I get the following error:

"▶ ERROR Bad key found: no private key material or GPGKey"

I think that I have the same issue as below, but I do not understand the solution:
https://github.com/keybase/client/issues/3743

Thanks

**Comment by maxtaco** [comment]
Can you please provide some more info.  Please do `keybase log send` and we'll take a look

**Comment by ambigit** [comment]
Yep Log ID: 01b16c63c6c6d64d076e191c

**Comment by zapu** [comment]
@ambigit hello and sorry for your troubles. Do you still have that key in your gpg keyring? Can you post result of `gpg2 -K` which would print basic information about your keys? Do you use any type of hardware key vaults or smart cards?

**Comment by ambigit** [comment]
I get this. (put some 'x's for personal info) 

/Users/xxx/.gnupg/secring.gpg
-----------------------------
sec#  4096R/C87C17F2 2016-10-23 [expires: 2017-10-23]
uid                  xx xxx <xxxx@gmail.com>
ssb   4096R/D7E78AF9 2016-10-23
ssb   4096R/B63E0D1C 2016-10-23


So yeah my secret key is not in my gpg keyring, but I thought I could sign with subkeys so I don't have to keep the master sec on my laptop? I basically followed this guide: https://alexcabal.com/creating-the-perfect-gpg-keypair/

**Comment by ambigit** [comment]
Ok I worked out what I needed to do...I must have uploaded a subkey rather than the master key to keybase. Not sure if that is the only way it is supposed to work but resetting keybase with my master key did the trick.

**Comment by zapu** [comment]
Glad you solved it! Unfortunately it's hard to be compatible with every key configuration when using third party libraries (in our case, kbpgp and go-crypto), so some non-trivial setups give people troubles. Now that you have devices provisioned, you shouldn't run into these kind of problems again. Happy Keybasing!

**Comment by ambigit** [comment]
Thanks!
