### ISSUE TITLE
User Enumeration

### ISSUE THREAD

**Issue by rafaelh** [keybase/client#7266]
Hi guys, really enjoying the app so far. This isn't exactly stop press, but I thought it worth mentioning: it's possible to [enumerate the users](https://www.owasp.org/index.php/Testing_for_User_Enumeration_and_Guessable_User_Account_(OWASP-AT-002)) on the site by entering a target email address and a random password.

![userenumeration](https://cloud.githubusercontent.com/assets/3272113/26770291/a1acbc06-49f8-11e7-85c1-af71e1886745.png)

Ideally the error message should be non-specific regarding whether the email address or password were incorrect, to increase the difficulty of guessing credentials.

**Comment by davidwengier** [comment]
This also exists on the "Recover account" page

**Comment by cjb** [comment]
Hi folks -- Keybase sigchains are public documents, we don't try to keep user info private. If you want to see whether a given username exists you can just go to their public profile page..

**Comment by rafaelh** [comment]
I can understand making user list public, but does that extend to allowing you to guess which email address they use for credentials?

**Comment by maxtaco** [comment]
Thanks @rafaelh  and @davidwengier.  We're aware of the *email* enumeration list, but it's a UX/security tradeoff, and since we have pretty aggressive rate-limiting on these endpoints, we think it's worth it.

**Comment by rafaelh** [comment]
That makes sense. Thanks for taking the time to respond.

**Comment by maxtaco** [comment]
Thank you for the report!
