### ISSUE TITLE
Chat shows message contents when screen is locked

### ISSUE THREAD

**Issue by kg4zow** [keybase/client#7269]
When the MacOS Keybase client receives an incoming chat message, it sends a notification through Apple's desktop notification system, which causes a box/bubble to appear on the screen, even if the screen saver is active and the screen is locked.

The problem is, **this notification contains the content of the received chat message.** If I'm chatting with somebody about something which needs to remain private, and I lock the screen while I step away from my desk, anybody who happens to walk by my desk and glance at the screen while I'm away can read those incoming chat messages.

MacOS - Keybase `1.0.23-20170522181119+8a8aea0`

**Comment by kg4zow** [comment]
Also, I just noticed the Copyright message at the bottom of the "About" window says "2015" rather than "2015,2016,2017" (i.e. every year during which changes were made to the code.)

**Comment by seth-outreach** [comment]
You can turn off lock screen notifications per-app in MacOS
<img width="667" alt="screen shot 2018-01-03 at 4 32 23 pm" src="https://user-images.githubusercontent.com/22355157/34545803-265572e8-f0a4-11e7-8f57-f6d21737c31e.png">

It'd still be nice if they were either off by default or provided some message content obfuscation.

**Comment by kg4zow** [comment]
The problem isn't that the notifications *exist*, although turning off the "Show notifications on lock screen" checkbox is a valid work-around until the problem can be fixed.

The problem is that the notifications **contain the actual text of the message** that somebody sent to me.

**Comment by huyz** [comment]
> The problem is that the notifications contain the actual text of the message that somebody sent to me.

Yeah that's a problem.  I can see that we can disable "mobile plaintext notifications", but can we also disable "desktop plaintext notifications"

**Comment by tomcallahan** [comment]
+1 -- I've had a chat message flash up before when showing something on my screen to a coworker that I really did not want him to see and I do not see how to turn that off.

Ideally I'd love to see it the way slack does it -- Options for show notification with content, show notification  with just name of sender, and don't show notification.

**Comment by brokenthumbs** [comment]
Is this the official channel for leaving feedback / asking for feature requests? Honest question, first timer with Keybase, and I also want this feature to exist.

**Comment by kg4zow** [comment]
@brokenthumbs This is the official repository for the Keybase client's code, and assuming they're using Github the way it was designed, this "issue" is on their list of things to look at. It doesn't look like anybody above is one of the developers so it's possible they haven't seen it yet, but I'm sure at some point they will.

For now I've just turned notifications off on the work machine, since I also get notifications on my phone and iPad. It's not ideal, but it does keep message content from unexpectedly showing up on the screen (or in whatever logs Apple may keep for their notification system.)

**Comment by izcet** [comment]
Was just about to create this ticket myself. The worst part about this is that it is on by default and has no settings to disable within the app. Not just hiding message contents, but even disabling desktop notifications at all. 

It looks like it's been 5 months since this issue was created -- should the maintainers be pinged somewhere else?

**Comment by jeremysears** [comment]
It looks like issues should be reported here:
https://github.com/keybase/keybase-issues

**Comment by izcet** [comment]
^ Other issue created at that repo, thanks @jeremysears!

**Comment by joshblum** [comment]
closed via #17337
