### ISSUE TITLE
There was an error provisioning

### ISSUE THREAD

**Issue by wpk-** [keybase/client#7281]
Keybase GUI Version: 1.0.23-20170522110822+8a8aea0

Not specifically a problem with the GUI version. It started when I wanted to add a public ZCash address via the website. That didn't work, with the below error. Then I downloaded the mobile and desktop clients but cannot login in either because they give this same error after entering the device name.

There was an error provisioning
Unknown error: downgrade lease (by KID) active for 0101188a...........very long string...........

**Comment by maxtaco** [comment]
On it, thanks!

**Comment by wpk-** [comment]
Wow, that's lightspeed. Did I press submit already?

**Comment by maxtaco** [comment]
should be fixed!  though i hope you are not in a stuck state

can you try it again?

**Comment by wpk-** [comment]
You're a hero. Thanks.

**Comment by maxtaco** [comment]
thank you, sorry for the bug!!!
