### ISSUE TITLE
Keybase doesn't have access to my private folder...

### ISSUE THREAD

**Issue by FishyFing** [keybase/client#7306]
I installed the Keybase Mac app today, and was given this...

![shot_2017-06-07_12-13-10](https://user-images.githubusercontent.com/8279924/26875620-b78b2570-4b7a-11e7-9c4f-0a4eb55a5542.png)

**Comment by strib** [comment]
Hi @FishyFing, that's a special macOS fake file.  It's nothing to worry about, but you shouldn't be seeing an error notification for it.  I'll look into why.  It would help if you can do a `keybase log send` and report the resulting log ID here, so I can see what version of our software you're running.  Thanks.

**Comment by strib** [comment]
By the way, can you still access the real folder, `/keybase/private/franc_ist`?

**Comment by FishyFing** [comment]
ye, i can open it from inside keybase, and finder, but keybase throws the error whenever i open it from inside keybase. 

(I'll send the log over when I get home later)

**Comment by FishyFing** [comment]
Log ID: `5b5df0e89519a74c4433591c` @strib

**Comment by strib** [comment]
Thanks.  I have a PR up to get rid of that notification: keybase/kbfs#1023.

**Comment by strib** [comment]
Should be fixed in the next release.
