### ISSUE TITLE
When keybase will be available on other iOS Store (France for instance)

### ISSUE THREAD

**Issue by pipiche38** [keybase/client#7307]
Today keybase app on iOS is only available on a US Apple Store. When will it be available on other stores ?

**Comment by cjb** [comment]
It's available (almost) everywhere except France, because France has a law that requires government permission to import cryptography.  We don't have an ETA on receiving that permission from the French government.

**Comment by Gui13** [comment]
It is quite simple to ask for (I'm french and have asked for it once). Did you start the process of asking it?
Forms are here: https://www.ssi.gouv.fr/en/regulation/cryptology/how-to-submit-an-application/

(sadly you have to use Adobe's PDF reader... talk about interoperability)

**Comment by vjeantet** [comment]
Any update ?

**Comment by sheldon** [comment]
I'd really like to use this too, any chance it's been submitted yet?

**Comment by objectifnul** [comment]
installation package (Android): 

https://cedesguin-drive.mycozy.cloud/public?sharecode=eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJzaGFyZSIsImlhdCI6MTUxODQ3MjMxNCwiaXNzIjoiY2VkZXNndWluLm15Y296eS5jbG91ZCIsInN1YiI6ImVtYWlsIn0.SSK3hioIz1RrTIAuOp43B6cPacM-XP63gpO0RJJCNQnRmftp-QHSESsexQXcFDyCV54pK5J32rXH9DOu1PHCQA&id=4e41b3a823abb3ba91ad579ee39f7409

**Comment by pipiche38** [comment]
Available now
