### ISSUE TITLE
Error: public key appears corrupted (no valid primary key self-signature or key(s) have expired)

### ISSUE THREAD

**Issue by soumyaray** [keybase/client#7325]
![fb error](https://user-images.githubusercontent.com/1926704/26909023-c90b3efa-4c30-11e7-9582-6c0a65ca284a.png)
My Facebook verification is suddenly failing (was working before). When I ask to replace my post, I get the error:
`Error: Your public key appears corrupted (no valid primary key self-signature or key(s) have expired)`

My public key has not expired; not sure how to proceed.

**Comment by maxtaco** [comment]
Urg, sorry about this, seems like 1 or 2 bugs.  Can you try `keybase log send` and we can take a look?  Did you maybe change your privacy settings on FB or anything like it btw?

**Comment by maxtaco** [comment]
Did you delete your facebook proof btw? I didn't see it on your profile

**Comment by soumyaray** [comment]
strange -- i didn't delete it but it can't be found.  let me try revoking and reposting it.

**Comment by soumyaray** [comment]
i reposted it and it works now.  sorry about the confusion.  again, not sure where my earlier posting went. thanks for responding so quickly!
