### ISSUE TITLE
Does not have permission to use camera

### ISSUE THREAD

**Issue by ogfomk** [keybase/client#7329]
I have a Samsung Galaxy Core Prime (Cheap Phone). I am trying to recreate this issue: https://github.com/keybase/client/issues/7277 .  So I have reinstalled the android client. Now I should mention that the camera has never worked for authentication (it does work for taking photos and it also works with a QR/Bar Code program.) and the message is that it "Couldn't get camera permissions." 

I have uploaded a Feedback with log from My Android install. 

https://plus.google.com/u/0/+AlexanderNuttall/posts/ADYELt72xps Here is a photo from a tablet that also has the same issue.

I have fixed the link. It should work better.

**Comment by ogfomk** [comment]
Just installed 20 June update and the app does not have permission to use camera for qr code recognition.

**Comment by jgomo3** [comment]
I have the same problem. Installed yesterday in my Android phone and it does not have permission to use the QR reader.

**Comment by jgomo3** [comment]
I have the same problem. Installed yesterday in my Android phone and it does not have permission to use the QR reader.

Also, I was able to add devices with the text code, but today I can't. After typing the text and pushing  **Continue** nothing happens.

**Comment by filipszu** [comment]
Same here Motorola Moto G.

**Comment by alex9099** [comment]
same as @jgomo3, camera doesn't work and i can't add with text

**Comment by koyuawsmbrtn** [comment]
Same on Android 5, Wiko Lenny 2
Hopefully they will fix it soon 😕

**Comment by goteguru** [comment]
Same with Samsung Note2.  'Couldn't get camera permissions'.

**Comment by ninz** [comment]
Having the same problem on my Galaxy S3. Can't get camera permissions and typing text code does nothing when I try to hit "Continue"

**Comment by DarkHole1** [comment]
The same problem with Android 5.

**Comment by alex9099** [comment]
Android nougat works fine, maybe some compatibility problem

**Comment by koyuawsmbrtn** [comment]
@alex9099 it's because permissions were introduced in Android Marshmallow. Android Lollipop and below doesn't have a permission system, so the Keybase App asks for something, which isn't there.

**Comment by goteguru** [comment]
ah, good to know, thx @Koyu .
however the software should be able to detect the version and avoid asking
for what doesnt exist.

**Comment by DarkHole1** [comment]
@koyuawsmbrtn but apk has permissions to camera on lollipop

**Comment by koyuawsmbrtn** [comment]
@goteguru yes, but the software doesn't look what android version is running, it's just asking for permission no matter what phone/tablet it is. that's exactly the same issue the developers of tusky ran into one day. a workaround was by looking if the device is running android marshmallow or below and then reacting differently.

@DarkHole1 sure it has the permission in the .xml file, where all the permissions are listed, but the app itself just errors on android lollipop, where android marshmallow and above are just working fine. even versions above look into that file, but android lollipop is missing the permission prompt, which was introduced on android marshmallow. the keybase app wants the permission prompt, but it desperately fails.
