### ISSUE TITLE
Windows client randomly corrupts after autoupdate

### ISSUE THREAD

**Issue by foxpy** [keybase/client#7361]
One day I've realised I have no access to KBFS.

![explorer_2017-06-11_05-35-17](https://user-images.githubusercontent.com/24505352/27007780-d5617b5e-4e67-11e7-8759-97aa8b5cdeb5.png)

After some restarting I decided to repair client, but looks like I've to fully reinstall it.

![keybase_1 0 23-20170522110415 8a8aea0 386_2017-06-11_05-37-11](https://user-images.githubusercontent.com/24505352/27007784-08fcb32a-4e68-11e7-8c29-9b26e160347d.png)

P. S. This is not the first time I've the issue.

**Comment by zapu** [comment]
cc @zanderz

**Comment by foxpy** [comment]
The issue was absolutely unnecessary.
