### ISSUE TITLE
Reset private folder

### ISSUE THREAD

**Issue by mikemcmurray** [keybase/client#7396]
I mistakenly rebuilt my laptop and revoked the paper key late last year so have lost access to my private folder. New laptop, keys, etc fine but would like to use /keybase/private/mikemcmurray again, if you can reset it please.

BEGIN KEYBASE SALTPACK SIGNED MESSAGE. kXR7VktZdyH7rvq v5wcIkHbrxlticW zXTPz61VpIpTFpT T36v5BcxfrgZQRt Yvs8w2HIq787eCw rShlo5BVtuV3Xrp ZvbpvPayyEXBQXJ 64G1AzElJAjeCpm 1aeEW1U5sR0u67C Pfcn5kbmSDP0KuP ZNFDUyQYz0rc6MR 1XyA1S6uW0bjQWH 95IORFQZqgHwpv6 Zb0pdLT1JdJsDdc 8MpQAO3XUsGcBTP KPJ0xcLc9arpgjS ltbYLw9eEvL8X0e lIpO3C6YiR06rXp z2BqsJ6P3EahpFD eyo2d7o8vWsNL4l cR7rmg9oS8jXjmA 2jioZNpA4WdSJ8N pRwrJvv3c1hgRAN 6KXuNRxEsTCcz7R ZO6bRTqV1xcEr9Q R4O9tb0Vk8LSkXJ dr9womxwC0Lr3i4 yf741ZYtLdtSwCr 8A80j6AgdoG4I1M VBcRZR89tA1JA34 KNG2qMzvFOLNnAN xvFlV7Sp1PSJPM. END KEYBASE SALTPACK SIGNED MESSAGE.

**Comment by strib** [comment]
@mikemcmurray: I reset the folder.  Please check it out and close this if everything seems ok.  (Might require a Keybase restart.)

**Comment by mikemcmurray** [comment]
Awesome, thanks very much @strib it's working fine again.
