### ISSUE TITLE
Windows Client Stuck in 'loading' screen

### ISSUE THREAD

**Issue by richardevs** [keybase/client#7397]
After a period of time not using the program, it seems to be stuck in 'loading' screen.

my log id: 056f233f8a8a966f080fdd1c

**Comment by gabefair** [comment]
I am also having this issue. 
Windows 10.0.15063. 16gb of RAM, Intel i7-7700HQ

**Comment by maxtaco** [comment]
@gabefair please do `keybase log send`

**Comment by maxtaco** [comment]
OK, thanks. @zanderz pls take a look, both cases show the typical error, I believe because the keybase service isn't running.

What is the workaround until the next release?

**Comment by zanderz** [comment]
@gabefair It looks like things worked after the last May 22 update, until June 1 or so. Did you disable any Keybase startup shortcuts? Does rebooting not help? The next release, out soon, will help address this condition. Until then, you could try opening Keybase Shell and entering `keybaserq "C:\Users\Richard S. Leung\AppData\Local\Keybase\keybase.exe" ctl watchdog2`

**Comment by gabefair** [comment]
@zanderz so the issue was that I disabled the "Keybase quiet start utility" from loading on startup b/c I wanted keybase to run when I say it should. Also it runs twice on startup.
![image](https://user-images.githubusercontent.com/2096785/27153574-fdbbfe16-511f-11e7-9bca-4d6ad874fe5c.png)

**Comment by zanderz** [comment]
![image](https://user-images.githubusercontent.com/862397/27158083-d9630844-5119-11e7-98ba-bed0516b2220.png)
The quiet start utility launches both the GUI and essential Keybase services - if you expand those entries, you'll see they are not duplicates. Disabling the background service will prevent Keybase from functioning (until the next release).

**Comment by richardevs** [comment]
The "ctl watchdog2" command to the Keybase Shell solve the issue.
