### ISSUE TITLE
Unknown error: eldest called on user with existing eldest KID

### ISSUE THREAD

**Issue by iodeslykos** [keybase/client#7406]
Installed Keybase for the first time, made a typo in the device name, and figured there was a method to rename. Ended up deleting the device and locking myself out.

```
"There was an error provisioning

Unknown error: eldest call on user with existing eldest KID"
```

From reading other issues, it sounds like I need an account reset. My apologies.

**Comment by maxtaco** [comment]
keybase username?

**Comment by iodeslykos** [comment]
iodeslykos

**Comment by maxtaco** [comment]
ok, reset
