### ISSUE TITLE
No Keybase Icon in tray after Ubuntu release upgrade

### ISSUE THREAD

**Issue by zwarag** [keybase/client#7410]
I did `do-release-upgrade` on my ubuntu 16.10. So with this command now my ubuntu is on 17.04.  
After this upgrade, there is no keybase icon in the tray. I also do not hear any sound or text notification when someone writes to me.

**Comment by zwarag** [comment]
Found a solution, had to run `env XDG_CURRENT_DESKTOP=Unity run_keybase` in command line. Then it worked for the time being executed from terminal.
To make a temporary fix i change my `./local/share/applications/keybase.desktop`.  
Loog for **Exec=** and change it to **Exec=env XDG_CURRENT_DESKTOP=Unity run_keybase**  
  
I assume that run_keybase is not whitelisted in the unity system-tray list.

**Comment by dakira** [comment]
Keybase seems to be an Electron app as this is an Electron bug which was fixed upstream. So when keybase updates their Electron dependency, this bug should go away.

**Comment by zwarag** [comment]
This has been fixed in the latest release or Electron or Keybase.
