### ISSUE TITLE
Can't install on Samsung Galaxy Note 4

### ISSUE THREAD

**Issue by Lokda** [keybase/client#7420]
Hi.

The Keybase app (Android) can't be installed on Samsung Galaxy Note 4. I can't see it in Playstore.

**Comment by lodart** [comment]
Me neither on a Honor 6X ; when I go [here](https://play.google.com/store/apps/details?id=io.keybase.ossifrage&rdid=io.keybase.ossifrage) from my computer, it tells me that I can't install it from my device country (France)

**Comment by l-vincent-l** [comment]
In France I can't install it on a samsung a5 neither.

**Comment by rtripault** [comment]
Same issue (France again) on LG-G5. A workaround is to install it using yalp store (hoping that could help)

**Comment by Lokda** [comment]
It ok for Galaxy Note 4, it's working.

Thx.
