### ISSUE TITLE
Some simple themeing in the client please

### ISSUE THREAD

**Issue by Fancellu2** [keybase/client#7447]
Using the windows client, all very bright, tiny fonts which can't change.

Would be nice to have a dark theme, and also make fonts bigger. Its frankly uncomfortable to even look at.

**Comment by cykosyc** [comment]
i agree with you on maybe offering some simple chat client themes. I currently like the blue theme that im using on my debian linux system, but it would be nice to change it up as well.

**Comment by 2E0PGS** [comment]
Yes please implement dark theme or option to follow GTK+ system theme on Linux!
Nerds like using chat applications at night or in the dark!
My IRC client has a dark theme...

**Comment by Jay1** [comment]
Is this doable nowadays? It's the only white windows on my tiling WM everything else is dark themed... It's not a big deal but i'd like my keybase to blend in of course

**Comment by verygoodsoftwarenotvirus** [comment]
With the release of OS X Mojave, and it's much-lauded "Dark Mode", this would be extra great for mac users. :)

**Comment by discoli** [comment]
This would be awesome, the light theme doesn't really work for me, something darker would be easier to use as everything I use nowadays is dark.

Would love to see this ++

**Comment by MiakoMoto** [comment]
+1

**Comment by Fancellu2** [comment]
Is this EVER going to happen?

posted this over a year ago. 

I frankly can't use this chat. I use Signal instead, which has a lovely dark mode

**Comment by verygoodsoftwarenotvirus** [comment]
@Fancellu2 [be the change you want to see in the world](https://github.com/keybase/client/fork)

**Comment by briansok** [comment]
+1

**Comment by maduce** [comment]
+100

**Comment by lerker100** [comment]
Is there a dark mode in the works?

**Comment by Oxymoron290** [comment]
Can we have a dark theme now plz

**Comment by discoli** [comment]
how long till dark theme, literally only thing stopping me from using it

**Comment by fancellu** [comment]
Ditto to all of this. I simply can't use keybase chat as it blinds me. Changing styling isn't the hardest thing in the world is it? Given that many of us work in IT, we know that it simply isn't.

**Comment by bleonard252** [comment]
If anyone can direct me where to go I'll try to add it

**Comment by brunph** [comment]
> If anyone can direct me where to go I'll try to add it

you can check here, this is for the windows build. other builds for another os might require some other tweaking.
[style.css](https://github.com/keybase/client/blob/master/shared/desktop/renderer/style.css)

**Comment by zwarag** [comment]
@bleonard252 @brunph I think the "real" issue here is that there is no functionality to swap themes. Just changing the css will not do the trick... Well I guess they will not accept a PR that changes the default/standard theme for everybody.

So yeah there is a little bit more to do that just change the css file. Does anybody know if there is a keybase channel where they talk about development. So that we/I could ask the devs what they would do? Maybe we can just code and the devs just tell us what do, or give some kind of guidance in form of a rough plan or something.

**Comment by lerker100** [comment]
We could just start @ ing  some of the devs. Many not the greatest idea but it would get there attention. Or message them OK keybase.

**Comment by bleonard252** [comment]
I would need to figure out how to set and apply the settings, too. Just changing the CSS wouldn't cut it.

I could apply it as I did [here](https://github.com/bleonard252/vivid-fe/blob/4d39622ebfaee11cbd8a35ebb8781c020a2d3b36/index.html#L47) for the desktop client, but I have to get the setting.

**Comment by zwarag** [comment]
@cjb @jzila 
Hi, I think we have 2-3 people willing to work on this issue.
Would it be possible to get a little guidance on how to approach this issue?

We figured that keybase does not yet have a changeable theming functionality.
Where could we save the Theme preference and is there a place where we can see how to read/write such preferences from the frontend?

**Comment by jzila** [comment]
This is something we'll need to do internally. We will be doing some investigation into this in the next few months. We try to put a lot of intention into our design, and as such any theming will get a full internal design pass before being implemented. Consequently, there isn't a convenient way to have the community run with such an endeavor.

**Comment by lerker100** [comment]
I think it would be worth it to try to open a way for people from the community to help develope new features. Maybe it would be possible to have one of the main developers lead a group of programmers from the community to develope new features?

**Comment by Oxymoron290** [comment]
"open source"

**Comment by bleonard252** [comment]
> "open source"

> This is something we'll need to do internally. We will be doing some investigation into this in the next few months. We try to put a lot of intention into our design, and as such any theming will get a full internal design pass before being implemented. **Consequently, there isn't a convenient way to have the community run with such an endeavor.**

liars

**Comment by heronhaye** [comment]
Dark mode released in Keybase 4.6.0 under Settings->Display->Appearance.

**Comment by heronhaye** [comment]
Also, Ctrl-= and Ctrl-- work to zoom in and out.

**Comment by zwarag** [comment]
Thank you!!!

**Comment by lerker100** [comment]
This has been my only complaint with keybase. Thank you so much!
