### ISSUE TITLE
Paper key not accepted.

### ISSUE THREAD

**Issue by DevSlashNull** [keybase/client#7448]
Changed distros on both of my machines a few months back, and just got around to reinstalling Keybase. I've entered my 12-word passphrase, but the app will not accept it. States that I have not entered enough words for a paper key.

Has the paper key word count changed, and if so, does this invalidate my old keys and render the account unrecoverable?

**Comment by maxtaco** [comment]
it is 13 words long. Should work on all devices. Hasn't changed, we promise!

**Comment by DevSlashNull** [comment]
Argh, somehow missed one in that copy. Found the backup-backup with all the words. Sorry about that! Thank goodness for backup redundancy.
