### ISSUE TITLE
backslashes entered in chat window don't print unless escaped

### ISSUE THREAD

**Issue by JeffMelton** [keybase/client#7469]
Tested on Windows 10, Linux (Fedora 25) and iOS.

Enter: ¯\_(ツ)_/¯  in the chat and send. What displays: ¯_(ツ)_/¯

Enter: ¯\\_(ツ)_/¯ in the chat and send. What displays: ¯\_(ツ)_/¯ 

Gotta have our shrugmoji, y'all.

**Comment by jannescb** [comment]
having similar issue sending strong passwords including \

**Comment by JeffMelton** [comment]
Cleaning up my ancient/abandoned issues. 😬
