### ISSUE TITLE
Input/Output error reading my private directory, persists until reboot

### ISSUE THREAD

**Issue by oliverjensen-wk** [keybase/client#7475]
I'm logged in to keybase (I've tried logging out and back in again), and cannot read my private directory. Attempting to do so results in:

```
$ ls /keybase/private/ojensen
ls: /keybase/private/ojensen: Input/output error
```

However, I *can* access private shared directories:

```
$ ls /keybase/private/ojensen,rfmcpherson
[expected list of files]
```

By description, this appears to be similar to [this issue](https://github.com/keybase/client/issues/5826), but since that issue was closed as fixed I suspect the underlying cause may be different.

my log id: d3f3deb049cae9909798b61c

**Comment by oliverjensen-wk** [comment]
Rebooting the machine resolved the issue.

**Comment by strib** [comment]
Hi @oliverjensen-wk: thanks for the report!  I think I found the bug; I just put up a KBFS PR to fix it.  Until the fix makes it into a release, restarting Keybase is indeed the best remedy when you get into this state.

**Comment by strib** [comment]
I pushed the fix to master, should be fixed in the next release.  Thanks for reporting!
