### ISSUE TITLE
Unable to recover Keybase account

### ISSUE THREAD

**Issue by nikhildhamija24** [keybase/client#7481]
Keybase GUI version : keybase version 1.0.24-20170619144856+91a6943

Hi Max,

I am unable to recover my keybase account and I am stuck being asked for the paper key which I do not have.

Keybase thinks I am logged in which I am not. I still have possession of the device.
Keybase is telling me to do keybase passphrase recover
Which brings up the app and tells me to enter the paperkey.

I tried going through the website recover flow and it keeps telling me to do the same thing.
Run keybase passphrase recover

My keybase username is @nikhil24

please advice..

**Comment by nikhildhamija24** [comment]
Thank you for your help @maxtaco . This issue has been resolved.

**Comment by TrustyMan** [comment]
can you help me to recover keybase account?
I forgot my paperkey.
