### ISSUE TITLE
"There was an error provisioning" iOS

### ISSUE THREAD

**Issue by samkohn** [keybase/client#7483]
May be related to #7278 
What I did:

1. Create a keybase account online and upload PGP public/private key pair
2. Download iOS app and try to log in

What happened:

"There was an error provisioning" screen (see screenshot). Apparently there's a problem because my PGP private key is not loaded onto my phone. I don't think I should have to do that, though (and regardless, there are not clear instructions on how to do that on the splash screen).

Expected behavior:

I should be able to download and log into the iOS app after having signed up online. My understanding is that there is a way to authorize devices without having to copy PGP keys but that information is not on the error screen and I can't find a way around it.

![image](https://user-images.githubusercontent.com/719743/27421285-9d86c944-56de-11e7-9bd7-6d8806e0494d.jpeg)

Thanks for all your hard work!

**Comment by maxtaco** [comment]
You have to install keybase on the machine that has your private key.
Keybase will need a PGP signature during its login process. Then you can
provision your mobile device with your desktop.

**Comment by samkohn** [comment]
Thanks. The desktop version isn't compatible with my older OS (Mac OS 10.9) so I was hoping to just use the mobile and browser versions, but I guess that's not possible.
