### ISSUE TITLE
Cant add iPhone

### ISSUE THREAD

**Issue by OGKevin** [keybase/client#7512]
When i try to add my iPhone via QR code i get the following error:

```
Unknown error: bad signature: All JSON proof characters must be in the visible ASCII set (properly escaped UTF8 is permissible)
```

I get this error after i enter a name for the device.

**Comment by maxtaco** [comment]
Did you use any sort of interesting characters in your device name?

**Comment by OGKevin** [comment]
Kevin's iPhone is what i've named it. But all my devices are called like that. Kevin's MacBook, VPS etc etc

**Comment by maxtaco** [comment]
Can you run 'keybase log send' from the terminal?

**Comment by OGKevin** [comment]
Done `my log id: abceab0ea005fc7de326231c` hope there is some useful info in there.

**Comment by maxtaco** [comment]
The problem is that you're using a `0x99` apostrophe (which is rendered `’`). We need a better error message, but if you use `'` (AKA `0x27`) you should be fine. We'll fix the error message. Thanks for your feedback.

**Comment by OGKevin** [comment]
Hmm, don't think i see that character in my iPhone keyboard 🤔 I copy pasted it and got it to work. Thanks for the support 👍 and keep up the good work 👋 .
