### ISSUE TITLE
[Manjaro Linux][Destination socket disconnected]

### ISSUE THREAD

**Issue by gcamerli** [keybase/client#7520]
Keybase GUI Version: 1.0.24-20170622160028+e5ac865

I can't access to my private and public folders.

**Comment by strib** [comment]
Hi @gcamerli, please do `keybase log send` from the command line so we can see what's wrong.  Thanks.

**Comment by gcamerli** [comment]
Hi @strib, when I tried to do this I received this error output:

`▶ ERROR API network error: Post https://api.keybase.io/_/api/1.0/logdump/send.json: net/http: request canceled (Client.Timeout exceeded while awaiting headers)`

Thanks

**Comment by strib** [comment]
@gcamerli: odd.  Any chance you're behind some kind of VPN or firewall that could be restricting access to our API servers?  Seem like you can't connect.

**Comment by gcamerli** [comment]
@strib: even. I didn't have any kind of issue before yesterday using a VPN. I also tried to disconnect it and change several servers but nothing happens.

**Comment by gcamerli** [comment]
@strib today is working! So I close this issue even if I don't understand what happened.
