### ISSUE TITLE
Overlapping lines in chat

### ISSUE THREAD

**Issue by NthPortal** [keybase/client#7613]
Keybase Client Version (Windows): 1.0.24-20170619073621+91a6943

In one of my chats, two successive messages are partly overlapping.

![overlapping word "encrypted"](https://i.gyazo.com/de203faec06a4c98836ae8df06d34ec2.png)

Maximizing and then un-maximizing the window fixed the problem.

![no longer overlapping](https://i.gyazo.com/003cc6d20ede275382c1d5c3a1bcc2b3.png)

**Comment by aaa11235** [comment]
I've experienced this in `Version (Mac) 1.0.33-20171003193446+d9ceb86ac`

**Comment by NthPortal** [comment]
Is this still an issue?

**Comment by NthPortal** [comment]
closing as probably very stale
