### ISSUE TITLE
DB Error when revoking/dropping pgp key

### ISSUE THREAD

**Issue by mehuman** [keybase/client#7615]
I'm getting "▶ ERROR DB error" when trying to revoke/drop my pgp key. Same error occurs when running from the commandline, mac app, and android app.

-Mark

**Comment by cjb** [comment]
Thanks, CC @maxtaco @patrickxb.

**Comment by maxtaco** [comment]
I believe @zapu just fixed this. @zapu do we need a merge and a rollout or
is it a different bug?

**Comment by zapu** [comment]
If it's CORE-5589, then I started on Friday but haven't finished it yet.

@mehuman I think the workaround is to remove your encrypted secret key first, on the website; and then try `pgp drop`. Let me know if this worked.

**Comment by mehuman** [comment]
@zapu The delete from the website and then a drop from the mac client worked.

I will add that switching between using drop and revoke between the different clients is confusing.
Drop - Mac client, Windows client, cli
Revoke - Android client, Website

Thanks for the help!
