### ISSUE TITLE
Unable to "Drop" my public PGP Key (revoke)

### ISSUE THREAD

**Issue by jtsmith0101** [keybase/client#7626]
Attempted to revoke from the laptop (log id: f7a81c36522d731196bb151c) and from the phone.  Both attempts resulted in a DB Error.

**Comment by jtsmith0101** [comment]
also, unable to drop the key from the windows app

**Comment by Aquilae32** [comment]
I read something about this. Try to revoke the key from the keybase _web site_ first. Then from the terminal on your computer.

**Comment by jtsmith0101** [comment]
Thanks for that.  That was the workflow I attempted first.  The site
redirects me to revoke the key from a listed-device in my sigchain.  The
windows app, the command prompt and my phone all point to a DB Error.

**Comment by maxtaco** [comment]
This bug should be fixed now (the DB error that prevented your revoke from
happening).  Sorry for the bug and the inconvenience

**Comment by jtsmith0101** [comment]
that fixed it.... now a new ticket for a new issue....
