### ISSUE TITLE
Revoked all Devices

### ISSUE THREAD

**Issue by jhampton139** [keybase/client#7628]
Hello,
 I revoked all devices when resetting my passphrase which has prevented me from logging into any clients until I reset my account.  When logged into my account in the browser, the spot to reset the account has been replaced with a notification to install the client, but does not go away after uninstall and reinstallation on all devices.  I apologize in advance for any inconvenience, what steps do I need to take to remedy this?
username - joshyouuh

Josh

**Comment by maxtaco** [comment]
I just reset your account, you can log in and start all over again.
