### ISSUE TITLE
Unable to verify CACert.org key chain

### ISSUE THREAD

**Issue by flamarion** [keybase/client#7647]
Hi,

Could you please update keybase  with the root certificates from CACert.org?

I'm user of CACert certificates and keybase doesn't identify my SSL certificates from my website.

Regards,

Flamarion Jorge

http://www.cacert.org/
http://www.cacert.org/index.php?id=3

**Comment by maxtaco** [comment]
[Won't fix](https://security.stackexchange.com/questions/126538/why-is-cacert-not-trusted-by-my-browser)
