### ISSUE TITLE
email address suddenly NOT verified?

### ISSUE THREAD

**Issue by Mikeinnc** [keybase/client#7686]
Keybase GUI Version: 1.0.24-20170619074027+91a6943

I have just added a new (Windows laptop) device to my keybase account (the previous device is a Linux laptop), and suddenly I am told my previously verified email address is 'x Not verified'. What is worse is that I cannot for the life of me see a way to 'reverify' it! Help, please!!

**Comment by Mikeinnc** [comment]
![keybase](https://user-images.githubusercontent.com/2187158/27999027-749f6f2a-654a-11e7-8948-68b560bce386.jpg)

Here's what I see.

**Comment by Mikeinnc** [comment]
OK, panic over! I have worked out how to fix it.

**Comment by dabaer** [comment]
How did you fix this? I was expecting some sort of verification email from keybase but got only notification emails from them.
