### ISSUE TITLE
Error Provisioning Account

### ISSUE THREAD

**Issue by waynekwlee** [keybase/client#7688]
Hi,
I just signed up for the account and I wanted to rename my device.  I revoked the device so that I can add it back but now I get an error message that says " Cannot add a new device when all existing devices are revoked.  Reset your account on keybase.io" 

How can I fix this?

 My login is waynekwlee.

**Comment by maxtaco** [comment]
OK, I reset your account

**Comment by waynekwlee** [comment]
Thanks! I'm all set.
