### ISSUE TITLE
Reset private folder

### ISSUE THREAD

**Issue by budged** [keybase/client#7689]
Hi, I couldn't find my old paper key, so I've recreated it and can't get access to /private folder now.
There's no valuable information there so can you please reset it?

BEGIN KEYBASE SALTPACK SIGNED MESSAGE. kXR7VktZdyH7rvq v5weRa0zkM4WQY4 SKBbpVKFno2rA0a vIRFPl8zhcjgqio nlI3dntRXiElAWf AVr6R5ZhjWz3exK iZmUVPi4XHTCNbk 2qU1PK5F50V9UKm Fz5dKkwOkPknSr5 68lWD5O3y4GIJ80 bpZ0RjcaHOlUn9E yi002sfr27cDlr2 wyhJY2LvnPM0yz4 Rhnaan1VxX6GnFV wThdlN6jMxJ5ld1 ReUj9p6Z85G7GYz TQMbrZa9nWcYEhT AqiNzdZB9IxzCaH Xm39ggdNyYXsIc2 qpj9v1wKJpHiAtf SOzQeKGi6ahq0NF L2o193Xn0VhE4nd Xnsmxi9scmClEW9 ovbAherEAI. END KEYBASE SALTPACK SIGNED MESSAGE.

**Comment by strib** [comment]
I reset the folder.  Please check it out and close this if everything seems ok.  (Might require a Keybase restart.)

**Comment by budged** [comment]
Thanks!
