### ISSUE TITLE
[keybase chat] markdown parser fails to recognize semicolon as part of a valid URL

### ISSUE THREAD

**Issue by JeffMelton** [keybase/client#7705]
Per [RFC 3986](http://www.ietf.org/rfc/rfc3986.txt), a semicolon is a valid separator for queries. However, when posting in Keybase chat, only the portion of the URL up to the semicolon is parsed. It'll end up looking like this:

[https://example.com/full.path](https://example.com/full.path);query

The expected behavior is: https://example.com/full.path;query

**Comment by ElectronicWar** [comment]
It's also the same with the exclamation mark "!" symbol

**Comment by einarmagnus** [comment]
Same issue with underscore, e.g. https://en.wikipedia.org/wiki/Solitaire_(cipher)

**Comment by einarmagnus** [comment]
Actually, it's probably the opening parenthesis that's the problem, not the underscore.

**Comment by JeffMelton** [comment]
Cleaning up my ancient/abandoned issues. 😬
