### ISSUE TITLE
Having issues with Keybase reporting reading from folder

### ISSUE THREAD

**Issue by agentbond007** [keybase/client#7738]
[write something useful and descriptive here]

my log id: 41711f2d5a3b8307aa8b141c

**Comment by strib** [comment]
Hi @agentbond007, it looks like you're having internet connectivity issues to our servers:

```
2017-07-12T18:38:18.050593 ▶ [WARN kbfs connection.go:370] 135e (CONN MDServerRemote 74425d11) Connection: error dialing transport: dial tcp 52.200.152.55:443: connect: operation not permitted
2017-07-12T18:38:18.050672 ▶ [WARN kbfs connection.go:535] 135f MDServerRemote: connection error: "dial tcp 52.200.152.55:443: connect: operation not permitted"; retrying in 2s
````

Perhaps you are behind some kind of firewall?  As far as I know, our servers have been fine all day.

**Comment by agentbond007** [comment]
Thank you @strib .  What's intriguing about this issue is that it appears only when connect with an OpenVPN tunnel .   I'm tempted to put a wireshark on it but any thoughts why a  OpenSSL tunnel might cause a communication problem with Keybase? 
. 2017.07.13 04:58:15 - OpenVPN > OpenVPN 2.4.0 x86_64-apple-darwin16.3.0 [SSL (OpenSSL)] [LZO] [LZ4] [MH/RECVDA] [AEAD]  
Thank you.

**Comment by strib** [comment]
Interesting.  I'm sorry, I don't know anything about that offhand!  Please let us know if you learn anything.

**Comment by agentbond007** [comment]
Problem solved.  Checked firewall rules and alas there was a block on KBFS for a certain profile.  Thank you @strib
