### ISSUE TITLE
Unable to Revoke Identity on Profile

### ISSUE THREAD

**Issue by futbolfrank** [keybase/client#7754]
I am attempting to revoke my identity, however unable to do so.

Attempting on Website has the following:
_Error: failed to post to the server: need a merkle root when revoking_

In addition, attempting via the Keybase Desktop application results in error as well.

Is there a fix to the error above or another way to remove identities successfully?

**Comment by maxtaco** [comment]
Thanks for pointing this out! I have a fix in works, I'll let you know when you can try again.

**Comment by maxtaco** [comment]
Ok, try it again? Thanks!

**Comment by futbolfrank** [comment]
No problem!
Tried to revoke in the browser and got the following error:
_Error: failed to post to the server: need a downgrade lease ID and merkle root; consider upgrading your client_

However, I was successfully able to revoke through the desktop app.
Thanks!

**Comment by maxtaco** [comment]
Ah, I shoudl fix that!

**Comment by maxtaco** [comment]
Have a fix too, thanks for letting me know
