### ISSUE TITLE
Folders not showing up anymore

### ISSUE THREAD

**Issue by bennycornelissen** [keybase/client#7788]
I just updated my Keybase client to the latest stable version: 

```
$ keybase version
Client:  1.0.25-20170715002410+acae5b06f
Service: 1.0.25-20170715002410+acae5b06f
```
and added my iPhone to my devices. All seemed well, until none of my KBFS folders showed up anywhere in the interface or Finder. I can manually `cd` into my folders (if I remember their names) and read/write contents. 

```
[benny:/keybase/private] $ ls -la
[benny:/keybase/private] $ cd bennycornelissen
[benny:/keybase/private/bennycornelissen] $ ls -l
total 6
... < regular ls output here >
```

Any clues?

my log id: bf3f56f99945b0512cf9101c

**Comment by strib** [comment]
@maxtaco/@oconnor663 : This user is getting a DB error when listing favorites:

```
2017-07-17T21:41:24.870445+02:00 ▶ [DEBU kbfs(kbfsfuse) folderlist.go:236] 583 FL ReadDirAll [tags:FID=e-gPlEid6sNjhW4CFO3dPA]
2017-07-17T21:41:25.008423+02:00 ▶ [DEBU kbfs(kbfsfuse) folderlist.go:238] 584 DB error (error 505) [tags:FID=e-gPlEid6sNjhW4CFO3dPA]
2017-07-17T21:41:25.008466+02:00 ▶ [DEBU FUSE serve.go:845] 585 -> [ID=0x1e] Read error=EIO: DB error (error 505)
```

Any ideas?

**Comment by maxtaco** [comment]
cc: @modalduality / @oconnor663

**Comment by maxtaco** [comment]
It's a server bug, we're rolling back. Sorry about that.

**Comment by maxtaco** [comment]
ok, fixed for now with a rollback.

**Comment by bennycornelissen** [comment]
I'm still recovering from the amazing fast response. 😆 Thanks guys!  @maxtaco @strib

**Comment by bennycornelissen** [comment]
And I can confirm, everything is back to normal over here. 👍
