### ISSUE TITLE
Logging failure due to no keybase directory on OSX

### ISSUE THREAD

**Issue by BenjaminHCCarr** [keybase/client#7792]
It appears that no directory is being tested for/created for keybase on install or selfupdate/autoupdate:

`2017-07-17T18:56:02.555464-04:00 ▶ [ERRO keybase standard.go:230] 031 stat /keybase: no such file or directory`

This is the relevant block:
https://github.com/keybase/client/blob/cb3bef8fc44eb3732d911c8647b9b2df5978eb89/go/logger/standard.go#L229-L231

There is no `keybase` directory in either `/var/log` or `~/Library/Logs/`

**Comment by BenjaminHCCarr** [comment]
@cjb clear something up
```
tyr:~/Library/Logs benc$ ls keybase.
keybase.kbfs.log     
keybase.service.log
keybase.start.log
keybase.updater.log
```
does exist.

**Comment by cjb** [comment]
Logs are there, /keybase is there later, so there's no bug here.

**Comment by BenjaminHCCarr** [comment]
Yeah was going to close it. It appears that `keybase ctl restart` still has the error.

You need to fully exit the GUI and restart it to so it does not error on stat `/keybase`

All errors are reported as `[ERRO keybase standard.go:230]` as that is the logging line in the `GO` code. Sorry for the issue.

Full `PEBKAC`
