### ISSUE TITLE
KBFS error

### ISSUE THREAD

**Issue by ndw** [keybase/client#7834]
Hello,

I'm running Ubuntu 17.04. After the latest update, when I start up, keybase says "KBFS error" and "disk cache not initialized, please report this error" or words to that effect.

I don't see a log file or anything in any of the usual places, but I'm happy to send more forensics if you tell me what you need.

**Comment by cjb** [comment]
Thanks for the report, CC @strib.

Please could you run `keybase log send` and show the result?

**Comment by strib** [comment]
No need for a log send, this is a known issue and should be fixed in today's Linux build.  There was no error really, it was an errant warning.

**Comment by ndw** [comment]
Righto. Glad it's sorted.

**Comment by gulprun** [comment]
it happens to me again 
`keybase status [pid: 24967, version: 2.3.0-20180622162432+de291a9e4e]`
