### ISSUE TITLE
KBFS error : Disk cache not initialized

### ISSUE THREAD

**Issue by papey** [keybase/client#7839]
run_keybase command throw a KBFS error, I can't find any logs to understand what component is failing behind the scenes. See the scrot below for details : 

![2017-07-20-181201_312x90_scrot](https://user-images.githubusercontent.com/17273325/28427678-4755700c-6d77-11e7-9b51-24d60d25370b.png)

my log id: bf3a679d9e85ed2624e5161c

**Comment by strib** [comment]
Yes, known issue (and dup of #7834).  This is an incorrect error notification that slipped into yesterday's Linux release.  It will be fixed in the next Linux build, hopefully sometime today.  Sorry for the inconvenience.
