### ISSUE TITLE
ERROR per user key bad box coverage (error 284)

### ISSUE THREAD

**Issue by psiyan** [keybase/client#7851]
Unable to `keybase login`
Process fails with the following 
```
▶ WARNING Unknown signature type per_user_key
▶ WARNING Account.CreateStreamCache overwriting existing StreamCache
▶ ERROR per user key bad box coverage (error 284)
```

keybase version 1.0.22 on GNU/Linux 4.12.2-1-hardened (Arch)

**Comment by maxtaco** [comment]
Hi, an upgrade of your client should fix this.

**Comment by psiyan** [comment]
Resolved by updating!
Thanks!
