### ISSUE TITLE
GUI not launching on Debian 9

### ISSUE THREAD

**Issue by wilsonehusin** [keybase/client#7866]
I submitted the log (66e925aeaf57b85b7051c41c). Tried both `run_keybase` and from the application menu, nothing works.

**Comment by cjb** [comment]
CC @oconnor663, the error is `/opt/keybase/Keybase: error while loading shared libraries: libgconf-2.so.4: cannot open shared object file: No such file or directory`.

**Comment by oconnor663** [comment]
Interesting, the Arch packages take a dependency on gconf. Sounds like we might need to do that on Debian too? @wilsonehusin, could you give us as much detail as possible about what system you're running?

**Comment by wilsonehusin** [comment]
It was a fresh Debian 9 GNOME install on an Intel i5 2nd Generation system. I did install the `libappindicator1` manually before proceeding with `sudo dpkg -i keybase_amd64.deb` so not sure if that would make the difference.

If this helps anything, I tried this on elementaryOS (Ubuntu-based) without installing `libappindicator1` manually and it works fine and the one in elementaryOS works perfect.

**Comment by oconnor663** [comment]
Ok I repro'd this with a fresh Debian 9 install and the default desktop environment. Seems like we should have a dependency on `libgconf-2-4`. I'm curious why this didn't come up before. Maybe a dependency change between Debian 8 and Debian 9 (which released just a month ago)?

**Comment by wilsonehusin** [comment]
Oh, that might be it. I never tried it on Debian 8 so I did not know if it works there.

I noticed that the `libgconf-2-4` on [Debian 8](https://packages.debian.org/jessie/libgconf-2-4) has a dependency of `multiarch-support` while on [Debian 9](https://packages.debian.org/stretch/libgconf-2-4) it's gone.   
(I'm just writing out everything I can find because I don't know this libgconf thing)

**Comment by oconnor663** [comment]
Ok, this should be fixed with the next package release, hopefully today.
