### ISSUE TITLE
I should be able to generate a "Paper Key" with just my PGP key

### ISSUE THREAD

**Issue by urda** [keybase/client#7874]
I would love to be able to generate a `paper key` from just my PGP key with Keybase. I would then use this single paper key to "on board" all my devices.

This could generate a graph of:

```
+--------+                                                   +-----------------+
| Device | +---+                                       +---+ | Social Identity |
+--------+     |                                       |     +-----------------+
               |                                       |
+--------+     |   +-----------+         +---------+   |     +-----------------+
| Device | +-----> | Paper Key | <-----> | PGP Key | <-----+ | Social Identity |
+--------+     |   +-----------+         +---------+   |     +-----------------+
               |                                       |
+--------+     |                                       |     +-----------------+
| Device | +---+                                       +---+ | Social Identity |
+--------+                                                   +-----------------+

```

# Why?

For users like myself who do manage their own PGP key very well, but want to extend into Keybase and allow Keybase to create their device keys, with a single point of uplink contact to my true identity, my PGP key.

**Comment by villasv** [comment]
I agree, I really wish I could start with a Paper Key and then follow with my devices later. I'd really like to reuse my existing paperkey, much like I can reuse my PGP key as wel...

**Comment by dabura667** [comment]
> with a single point of uplink contact to my true identity, my PGP key.

Also one thing to consider. Adding this feature will NOT make the paper key your "single point of uplink" as you are probably imagining it.

In keybase, let's say you were able to make the graph you describe; revoking the paper key will not revoke the devices...

It seems like you are assuming that all the devices are connected by the paper key and revoking the paper key will be a kill switch for you. That's not true. You will need to revoke each device one by one.
