### ISSUE TITLE
Keybase App should integrate with 1Password

### ISSUE THREAD

**Issue by urda** [keybase/client#7875]
# Expected:

When I'm logging into my Keybase account on my iPhone, I expect Keybase app to detect if 1Password is on my phone and [use the 1Password integration service](https://blog.agilebits.com/1password-apps/)

# Observed:

No integration

**Comment by kkarhan** [comment]
keybase seems to have some weird issues with password managers - even on desktops.
I know of people being locked out due to errors in between copypasting password manager and keybase' login.
