### ISSUE TITLE
chat unboxing error

### ISSUE THREAD

**Issue by zoof** [keybase/client#7883]
`error unboxing chat message: chat version error: unhandled messageboxed version 2 critical: true`

This happened with the last three messages I sent but not earlier ones or the ones I received in response.  The messages I sent were from roughly 2-1/2 weeks ago.

**Comment by zoof** [comment]
In fact, I just sent a message and I got the same error from the responses.

**Comment by maxtaco** [comment]
I think you need to upgrade your client

**Comment by zoof** [comment]
It is up-to-date.

**Comment by maxtaco** [comment]
What platform / what version

**Comment by zoof** [comment]
64-bit Debian Jessie.

    $ keybase --version
    keybase version 1.0.18-20170227170113+3bf85d0

**Comment by maxtaco** [comment]
That's an extremely old version

@oconnor663  or @cjb might know more specifics about why your version is so old

**Comment by oconnor663** [comment]
@zoof do you do system updates regularly? Does the `keybase` package not get updated with you do `apt-get upgrade` or similar?

**Comment by zoof** [comment]
I do but for some reason there is no keybase sources list in /etc/apt/sources.list.d.  I even uninstalled it and installed the current version (so it is now working again) and still no sources list.

**Comment by zoof** [comment]
I think what must happened is that I tried keybase early on and uninstalled it and deleted /etc/apt/sources.d/keybase.list.  But when the chat functionality came online I reinstalled it and /etc/default/keybase dictated that it not reinstall /etc/apt/sources.d/keybase.list.

**Comment by oconnor663** [comment]
Ahh, because you manually deleted the list file after the first uninstall? Interesting. Yeah, we kept that default file mechanism from Chrome's install scripts, and it seems nice to give people a way to prevent our repo from getting re-added all the time, but I wonder if it's going to end up causing more trouble than it saves anyone.

**Comment by zoof** [comment]
Probably a one-off problem. I expect most people are not as anal as I am about clearing out unused list files.  But clearly not anal enough since I left the `/etc/default/keybase` file! ;)

**Comment by oconnor663** [comment]
This is our punishment for laying out files that aren't included in the package manifest!
