### ISSUE TITLE
How to uninstall on ubuntu?

### ISSUE THREAD

**Issue by maraoz** [keybase/client#7897]
This is outrageous... keybase sowftware automatically opens on startup and I find no way to disable that.
I want to uninstall the software and I also can't find how to do that.

Not cool! Can anyone lend a hand? Googling didn't help. `keybase help` didn't help. [This issue](https://github.com/keybase/client/issues/4226) on uninstalling on OS X didn't help. Fuck keybase for taking my laptop hostage.

**Comment by maxtaco** [comment]
```
apt-get remove keybase
```

**Comment by immartian** [comment]
it's not fully uninstalled

**Comment by SubSeven57** [comment]
@immartian `sudo apt-get purge keybase && sudo apt-get autoclean`should do the job.

**Comment by immartian** [comment]
indeed. Thanks.

**Comment by henok321** [comment]
To remove the user specific content remove the following directories:

`rm -rf ~/.local/share/keybas ~/.config/keybase

**Comment by jgomo3** [comment]
Removing those files should be done by the `apt-get purge` command, but is not the case. If you are not aware of this, anybody installing again keybase in that machine, would have access to the user account.

**Comment by joaovarelas** [comment]
This is sad... Keybase should be concerned with user privacy & security.

**Comment by maxtaco** [comment]
Thanks @jgomo3 and @henok321 for the feedback. This is a tough call for us, since that data cannot be recovered (it's secret keys that never leave the device), and can result in data loss if deleted.  Sometimes it's hard to find the right balance between local security and prevention of data loss.  We'll consider the change requested though.

**Comment by spam-man** [comment]
IMHO, this is a seriously bad design. How come there is no option or preferences to config startup behavior from the client? For me, and I bet for most users, this feels malicious, as if the app is taking over the system without the option to disable it. Bad bad...

**Comment by ayberkt** [comment]
In addition to the instructions suggested by @subsevenx, it seems to be necessary to run `sudo rmdir /keybase` to get rid of the `/keybase` directory.

**Comment by dharvey-consbio** [comment]
My process was as follows. I'm duplicating steps suggested above by @subsevenx, @henok321 and @ayberkt for convenience of anyone who comes across this, but also to put the whole process into perspective.

#### First, as described above
```
# Uninstall
sudo apt-get purge keybase
sudo apt-get autoclean
# Remove user data at the risk of losing unrecoverable keys
rm -rf ~/.local/share/keybase ~/.config/keybase
# Delete empty directory in root
sudo rm -r /keybase
```
#### Then manually remove from package management
```
# Remove from apt list
sudo rm /var/lib/apt/lists/prerelease.keybase*
sudo rm /etc/apt/sources.list.d/keybase.list
# Untrust the key
apt-key list  # To get the following key
sudo apt-key del 656D16C7
```
#### Finally, just to be sure...
```
sudo apt-get update
sudo apt-get autoremove
sudo apt-get autoclean
sudo apt-get clean
sudo dpkg --configure -a
sudo apt-get -f install
```

**Comment by r34117y** [comment]
Well, `sudo rm -r /keybase` results in error in my case (Ubuntu 22):

```
rm: cannot remove '/keybase/KBFS_NOT_RUNNING': Read-only file system
```

Any clues?

**Comment by dienteperro** [comment]
> Well, `sudo rm -r /keybase` results in error in my case (Ubuntu 22):
> 
> ```
> rm: cannot remove '/keybase/KBFS_NOT_RUNNING': Read-only file system
> ```
> 
> Any clues?

logout and login again and run that command then.

**Comment by immartian** [comment]
since Keybase is over, we can switch to Nostr or Yggdrasil Network, both
are open-sourced on github.
