### ISSUE TITLE
Produce new release version

### ISSUE THREAD

**Issue by staktrace** [keybase/client#7907]
Following the fix for FreeBSD in keybase/keybase-issues#3022 I asked the FreeBSD package maintainer to update the version of keybase in the FreeBSD packages system. However he said that they only update the ports based on the "official releases" which is currently at 1.0.21. - https://github.com/keybase/client/releases/latest

@oconnor663 Would you mind pushing a new release tag for 1.0.26 or whatever the latest stable thing is?

**Comment by oconnor663** [comment]
I'd ask the maintainer to consider anything in this list an "official" release: https://s3.amazonaws.com/prerelease.keybase.io/linux_binaries/deb/index.html. We also update the Arch `keybase-bin` user package in lockstep with those Debian releases. Would that be acceptable?

**Comment by staktrace** [comment]
@sunpoet ^

**Comment by woodsb02** [comment]
@oconnor663 is there a reason why these releases aren't being tagged as such in GitHub?
https://github.com/keybase/client/releases

**Comment by sunpoet** [comment]
Instead of tracking all commits of version.go, it'll be helpful if these releases are being tagged.

@oconnor663 I think https://prerelease.keybase.io/ is the list of pre-releases and Debian follows it.

**Comment by oconnor663** [comment]
Our Linux releases occur almost daily, unless there's a break in CI. I think it would feel excessive to tag the repo every day?

**Comment by sunpoet** [comment]
IMHO, they only need to tag 1.0.27 when someone changes version.go from 1.0.26 to 1.0.27. It won't be an everyday job.

https://github.com/keybase/client/commits/master/go/libkb/version.go

**Comment by oconnor663** [comment]
For better or for worse, our real version number bumps like 1.0.26 -> 1.0.27 don't happen with much regularity. We wouldn't downstream packagers to wait for a version bump before downloading new bits. Are there any other desktop apps with really frequent updates, that we would want to emulate? (Dropbox maybe?)

**Comment by staktrace** [comment]
Looks like releases are getting tagged now, thanks!
