### ISSUE TITLE
Keybase Windows download 

### ISSUE THREAD

**Issue by stibio** [keybase/client#7921]
How can I validate the Keybase download files? Maybe I'm being blind but I can't spot any signatures or even hashes to check the exe with.

I've imported the code public key found here - https://keybase.io/docs/server_security/our_code_signing_key but can't see anything on the download pages.

**Comment by zanderz** [comment]
You can look at https://s3.amazonaws.com/prerelease.keybase.io/index.html and click the update link for your platform - the resulting json has saltpack signatures. Maybe we should surface such signatures more obviously.

**Comment by stibio** [comment]
Thanks for the response zanderz, will check those now. It might be good to surface them somewhere near the download button or at the bottom of the download page especially considering the goals of keybase.

Cheers again
