### ISSUE TITLE
Had to reinstall Keybase Desktop Client - Arch Linux

### ISSUE THREAD

**Issue by jrswab** [keybase/client#7939]
I had to reinstall the keybase desktop client due to an OS wipe and reboot. I keep getting this error when loading chats:

`error unboxing chat message: KBFS client wasn't found`

I've seen other issues with the same (or similar) message but not in this use case. Did I miss a fix in the list of issues?

**Comment by jrswab** [comment]
Seems like the issue resolved itself after a root into Kernel 4.9.37-1-lts

**Comment by cjb** [comment]
Ah, probably means you installed FUSE for kbfs and it compiled against the kernel on disk that you hadn't booted into yet.

**Comment by jrswab** [comment]
That makes sense. Thanks for the heads up!
