### ISSUE TITLE
[Bug] Chrome Extension does not recognize the client

### ISSUE THREAD

**Issue by dabura667** [keybase/client#7943]
OS: Linux Mint 18.1
Keybase version: keybase version 1.0.27-20170728162822+aa79be55c
Chrome version: 60.0.3112.78 (Official Build) （64 bit）

I click on the "Keybase Chat" button on someone's SNS page and I get "You need the Keybase app to send chat messages." With the install Keybase button.

My keybase is up and running, chatting with some friends right now as I speak, and yet Chrome Extension is not showing it.

**Comment by dabura667** [comment]
Also, Keybase Chrome extension version is: 1.10.5

**Comment by faasie** [comment]
Seeing the same here.
OS: OpenSUSE
Browser: Chromium
Extension: v 1.10.5

Thanks!

**Comment by jennajon** [comment]
Ditto on the extension requesting KeyBase be installed.. version 1.10.5.

**Comment by junderw** [comment]
Just upgraded to 1.0.27-20170802161439+b6dff3f9a from the ppa, and now Keybase client on Linux is working fine with the 1.10.5 version of the extension.

**Comment by faasie** [comment]
Same here. Upgraded as @junderw did and working just fine now.

Thanks!

**Comment by jennajon** [comment]
**NOT WORKING** FOR MacOS Sierra. 
Especially since Keybase  Version 1.0.26-20170724171020+b095a794e (1.0.26-20170724171020+b095a794e) IS the current version.
