### ISSUE TITLE
Can't remove device

### ISSUE THREAD

**Issue by klingtnet** [keybase/client#7949]
Removing a device from the list fails with the error message: `need a downgrade lease ID and merkle root; consider upgrading your client (error 291)`. I am using the latest release version so there is no possibility to upgrade the client (except build from master, maybe):

```sh
$ keybase --version
keybase version 1.0.22
```

The following command failed:

```sh
$ keybase device remove "754e07deaa6254dc3475083fa0cb9f18"
▶ INFO Revoking KIDs:
▶ INFO   012094ae70ea8cda69c91924d8ab9de4f7ce40dc90251af5a8cc9aa693e940c566870a
▶ INFO   0121740772aac4c9a9d705cb70db3315f56abd35229cd64dc0253c6373729e3f587f0a
▶ ERROR need a downgrade lease ID and merkle root; consider upgrading your client (error 291)
```

**Comment by maxtaco** [comment]
Very old version. What platform are you on?

**Comment by klingtnet** [comment]
I'm on Arch Linux. Why is this an old version, the latest [keybase client release](https://github.com/keybase/client/releases) is `1.0.22`.

**Comment by maxtaco** [comment]
Cc: @oconnor663 who saw this problem previously. We're up to 1.0.26 or so. The release is from the spring.

**Comment by klingtnet** [comment]
Ok, but how should one know if the github releases are not properly updated?
Anyhow, I will try to use the latest version from [keybase.io](https://keybase.io/download).

**Comment by maxtaco** [comment]
Cc: @cjb also!

**Comment by cjb** [comment]
You can also use the keybase package from AUR, that's always up to date.

**Comment by oconnor663** [comment]
This is the mismatch between the `community/keybase` package (an official Arch package not built by us, despite the name) and the `aur/keybase-bin` package, which is the one we direct people to in our install instructions. We could tag the github repo more frequently to provoke downstream builds, and maybe we should, but even still this official package doesn't contain KBFS or GUI bits.

**Comment by klingtnet** [comment]
@oconnor663 Thanks! I am now using `keybase-bin` in version `keybase version 1.0.27-20170728162822+aa79be55c` which fixed the issue.
