### ISSUE TITLE
Use client to sign proofs using gpg

### ISSUE THREAD

**Issue by Gunni** [keybase/client#7950]
As the description states, i want to use the `keybase prove` command in the client to sign proofs, but instead of using computer key, i want to sign using GPG key.

My gpg key is hosted on a YubiKey 4 key.

**Comment by maxtaco** [comment]
this should be possible if you use the web site.

**Comment by Gunni** [comment]
@maxtaco it is indeed, using some curl commands and various piping, which does not work on windows.

Atleast not without using various methods i have not got working.
