### ISSUE TITLE
Client errors when provisioning

### ISSUE THREAD

**Issue by Gunni** [keybase/client#7961]
When i try to provision my work computer with my GPG key i get the following sequence:

![1](https://user-images.githubusercontent.com/358099/28830410-26115584-76c6-11e7-92b4-3193a60cf106.PNG)

![2](https://user-images.githubusercontent.com/358099/28830417-2b176fbe-76c6-11e7-9ee3-9c8655617d0b.PNG)

![3](https://user-images.githubusercontent.com/358099/28830421-2d3e11d0-76c6-11e7-9134-b3c73fecc1db.PNG)

![4](https://user-images.githubusercontent.com/358099/28830423-302bb406-76c6-11e7-9847-28da2e6a03f7.PNG)

And i am unable to continue.

I am trying to provision this device using my GPG key.

**Comment by maxtaco** [comment]
Can you do a keybase log send?

**Comment by maxtaco** [comment]
Cc @patrickxb likely this is an issue with not allowing PGP provisioning after a PUK upgrade.

**Comment by patrickxb** [comment]
That is behaving as expected.

**Comment by maxtaco** [comment]
But why show the passphrase provisioning option if we know it's going to fail?

**Comment by patrickxb** [comment]
Desktop needs to make a release.  They are supposed to have that fixed.  Service sends them details about when to show it, when not to.

**Comment by patrickxb** [comment]
https://github.com/keybase/client/pull/7767

(it's been in the service for 27 days:  https://github.com/keybase/client/pull/7637)

**Comment by Gunni** [comment]
I was under the impression that i would still be able to use GPG to sign devices/sites... etc...

Are you saying that GPG login is not allowed?

**Comment by patrickxb** [comment]
Once you have a device provisioned, you are not allowed to use GPG to provision any additional devices, you need to use one of your existing devices.

Sorry for the inconvenience, but this was a necessary tradeoff we had to make.

**Comment by maxtaco** [comment]
Documentation to follow soon.  There's now a *per-user key* whose secret half is encrypted for all of your device keys, but we were afraid to have clients encrypt for PGP keys, since they are so hard to manage.  This per-user key in term will drive our new teams product.

**Comment by Gunni** [comment]
So, as i understand it, i used my pgp key to sign my machine key, but then when i want to add another machine, i am no longer allowed to use my pgp key to add more machines.

Why block gpg keys, you make a graph of signatures, why not _allow_ gpg keys for advanced users?

I should note that my machine key is my _least_ trusted key, with my gpg key being my most trusted, i want to use it.

**Comment by maxtaco** [comment]
This policy simplifies our implementation and seems right for the most Keybase users. As with anything, we can't please everyone unless we make our app hopelessly complex, which will certainly displease users!

**Comment by Gunni** [comment]
> Also, PGP continues to be supported, and, heck, you can now have multiple PGP keys on one account. For the truly bold among us. -- https://keybase.io/blog/keybase-new-key-model

I would like to use pgp keys even if it only possible using expert commands.
