### ISSUE TITLE
why is this happening? can't read #reddit?

### ISSUE THREAD

**Issue by nimbosa** [keybase/client#7972]
i NEVER touched anything, posted the form exactly as pre-filled by keybase, YET it fails? 

my latest PROOF is [here](https://www.reddit.com/r/KeybaseProofs/comments/6r19ku/my_keybase_proof_redditnimbosa_keybasenimbosa/)

it failed [two](https://www.reddit.com/r/KeybaseProofs/comments/6qyccm/my_keybase_proof_redditnimbosa_keybasenimbosa/) [times](https://www.reddit.com/r/KeybaseProofs/comments/6qy9ji/my_keybase_proof_redditnimbosa_keybasenimbosa/) before! what gives this error?

my log id: e5261f071817460d36782b1c
![keybase_2017-08-02_03-03-14](https://user-images.githubusercontent.com/3531340/28855653-a2fbcf8e-7770-11e7-8a95-233d8abc1e5c.png)

**Comment by kkarhan** [comment]
Your links do work.
I guess an API problem?

**Comment by kkarhan** [comment]
Maybe it's possible that keybase and/or reddit locked you out from completing this step.

This may be caused by either keybase or reddit API limits [something you can do nithing about, cuz they have to fix that!] or too many attempts in a too short timeline.

Maybe retry it a few days later?

**Comment by nimbosa** [comment]
it failed on [the first try](https://www.reddit.com/r/KeybaseProofs/comments/6qyccm/my_keybase_proof_redditnimbosa_keybasenimbosa/) (from the desktop client-GUI), it cannot be because of too many attempts, it failed a second time (again from the desktop client-CmdLine) so i tried it from the browser on the keybase.io website and [it succeeded](https://www.reddit.com/r/KeybaseProofs/comments/6r19ku/my_keybase_proof_redditnimbosa_keybasenimbosa/)!

[i was thinking](https://www.reddit.com/r/KeybaseProofs/comments/6r19ku/my_keybase_proof_redditnimbosa_keybasenimbosa/dl1lekj/) it could be malformed messages or wrong format issued from the desktop client, comparing the first two attempts which failed and had exactly same format, and the third one which activated but had a different format that the other two, as i remarked [here](https://www.reddit.com/r/KeybaseProofs/comments/6r19ku/my_keybase_proof_redditnimbosa_keybasenimbosa/dl1lekj/):

it is easy to get to the bottom of this, comparing the two, the difference is obvious
![keybase_2017-08-04_00-01-32](https://user-images.githubusercontent.com/3531340/28931333-4c256ea2-78a8-11e7-8c22-050bac01589b.png)

the part where it says "**Proof**" in the first TWO attempts, both issued from the desktop client, includes this, shown as one long line with a horizontal scrollbar ([right part of the image](https://www.reddit.com/r/KeybaseProofs/comments/6qyccm/my_keybase_proof_redditnimbosa_keybasenimbosa/)):
`hKRib2R5hqhkZXRhY2hlZMOpaGFzaF90eXBlCqNrZXnEIwEgGEyNzLdaH/+rqVaf1bpWYFESNddmpu5olUdmeivTM3wKp3BheWxvYWTFAzp7ImJvZHkiOnsia2V5Ijp7ImVsZGVzdF9raWQiOiIwMTIwMTg0YzhkY2NiNzVhMWZmZmFiYTk1NjlmZDViYTU2NjA1MTEyMzVkNzY2YTZlZTY4OTU0NzY2N2EyYmQzMzM3YzBhIiwiaG9zdCI6ImtleWJhc2UuaW8iLCJraWQiOiIwMTIwMTg0YzhkY2NiNzVhMWZmZmFiYTk1NjlmZDViYTU2NjA1MTEyMzVkNzY2YTZlZTY4OTU0NzY2N2EyYmQzMzM3YzBhIiwidWlkIjoiNTM2MzhkODAwNmUwMTI1M2Y5ZmVmNjNmMzAxZGJmMTkiLCJ1c2VybmFtZSI6Im5pbWJvc2EifSwibWVya2xlX3Jvb3QiOnsiY3RpbWUiOjE1MDE2MDg1MTAsImhhc2giOiIyZGI0ZWIyMmNjYTI0Yjg0ODNmMzljOTc2OTE0OWVlNGYzZWJhZGJjOTcxOGVmNzIyMDdiNDc3MTBiY2ZiYWFlZmY5MjNmNjNlNGIwYWJiYmMwNDI5NGM5N2U5NmNkZWQyYTgxMDhiMzU4MGYzOGUzMzI4NjE1N2M2ZTMxNmY3ZCIsImhhc2hfbWV0YSI6ImRkYjViZTlkZmEwMDA3MjI5MGEzOTJjNWM0YzljZGVkM2IxMmQ1YzFmZjI5YTM2ODBmZmZlMjA5M2UyZjY2YjYiLCJzZXFubyI6MTI5NTk4N30sInNlcnZpY2UiOnsibmFtZSI6InJlZGRpdCIsInVzZXJuYW1lIjoibmltYm9zYSJ9LCJ0eXBlIjoid2ViX3NlcnZpY2VfYmluZGluZyIsInZlcnNpb24iOjF9LCJjbGllbnQiOnsibmFtZSI6ImtleWJhc2UuaW8gZ28gY2xpZW50IiwidmVyc2lvbiI6IjEuMC4yNyJ9LCJjdGltZSI6MTUwMTYwODU1NCwiZXhwaXJlX2luIjo1MDQ1NzYwMDAsInByZXYiOiJjODUyYjdhNTc0M2EyZWY4ZTczNDQ2MmUyZjNjYjc5NGJiNGUzM2E0M2Q4ZmQ2ZDUzYTU2ODgzZWExZWQyMTFlIiwic2Vxbm8iOjUsInRhZyI6InNpZ25hdHVyZSJ9o3NpZ8RA87AYwrxEWlESEADSwdQg0H0i2TTq828e26cho8AuNkwGIL2IIUcV6AXpkZbAyGVIfr4i2UErpM5m//e4nc6UD6hzaWdfdHlwZSCkaGFzaIKkdHlwZQildmFsdWXEIHhctibozYFoH9LkAzj8ZsuwtSxdJ/ezdUWeDjqKDnR+o3RhZ80CAqd2ZXJzaW9uAQ==`
.

while [the one that succeeded (shown on the left)](https://www.reddit.com/r/KeybaseProofs/comments/6r19ku/my_keybase_proof_redditnimbosa_keybasenimbosa/) has this text instead:
```
-----BEGIN PGP MESSAGE-----
Version: Keybase OpenPGP v2.0.73
Comment: https://keybase.io/crypto

yMPuAnicdVN7UFVFHL6kWeIoVL6NrMNgTvjYc3bPnj2IkoYyqWnlY1JwbufsA6/X
ey+ec0EIMTXHfDToiM5omZNGWqNYMjVCRCpRCAqZWTLjMzBMCSbJKTSV9jI6UzP1
x87Z85vv+37f79vd6r49PNFRCb8OvNlSuDor6njV4mzPvJXjtuQrdojlKUn5ip93
f/hixt2w1+9jSpICVA2oBFHCKLUN3VKFEJZtmTo2BdNtS8cY6KqqQZ0ZGFuYc0xM
Hcm9YWk2gxAaFFjKKEX4gpncyXJ8wbCUxUyjKsGaATmhhoYFsw0VSB2dUxULU6pw
ggwgiQtDboQhzdmWy8f4QrImf7zd9v4Df983UG2CIRVS0+IaMCgBpkQbAgJiUQyJ
5GJBTZPpwEaECoyAQXSMiBwQc8hQt+/sbjkdSgIjAGAuE9GhMAUXGEotldlCNSNA
lztBK8AlOugL2CHXUgpGKQHu+BdzrxMKhSPZ0rAvglB1oGKkIqLJ+Sx3oTfAw5Yk
2tjGVBg2103GVZUyw0SccsuGhEAgbAR1QzV0W5M4QVRqatAyhIaIhRkgkEkbLl8S
DMkOmokJ0aUDh+eE/DzS3PVlytRcJSldMRBiAGGKVWCaVDMhRxhoyEQQErkYYthk
mi1MlchJiUmRJRCghsEIIobAQCgLCiLNnBwf7Ra/N7rDGfOF/zeOcF5WpLKU2957
XK/tCzJ5NyQlhzuuLxSU5iXy30lhDYxSeG6Wz+FeXwShG1ieBpDVLDmglKREwwTp
DDOBMJY3C3Ck2ybWNEMwoEEVagBASxBCdQNAbCAoDx8xgxPNUhH8R3RSNGxlSk0Z
WNAKZztcKag6mtHTExXt6fXgA5FH44nuHXv/KTWhmK6sfglt+tAqu33ookVntsNU
uN6dELPt/O+pYz7zT+gs3tFWVrq93jPQueImJ4aXnO58v66y67G2gg9rZk04lbli
dlH75KatddXjcmeM3nzy1aV7e9x4t/7hPgc2navvPfydo1pFjVN3uqU9+o2C1RWp
cN5Lgac641KamseNOHWzaPL3z/b6/HzKxtMjHnn7QKHI/utcoDw+bcpb6yaO3BRd
eiz9q4SOaYnZevuF4/vGl4GOvPQbO4wn3zuyu6NPcsNypzHOu7vtmpJSOvvlmOLW
nevjmysCLTeer59fOWdX6aovuxKn5Y/YCMGGxviDoztF3PLo3gmXLlc1xTxX/dDP
G2aW/7D+etPZkoq12/xDXsgZXFIz6ZfNSXOP7W1dNmja4aJhr5gnn/62Yc4HO/Ji
Z+XuA7tuwdpbW0abPH1ibHVa/8wt3oOH/H1fL3+idc7dSWtq3ZauZ15LSt58cQkT
A67utqf+EUcuJtdOnH547IVm/gVCk//cv5NOXbXt1KOzv1v3dVPmnv7r2hryM67f
/W1Y/+b52tm7n6blFs8/l7KrR2vJ+JEzYgfsV1YuXPDJsgUDE8ceyv1x67I+yXMb
PB+9uD3YLz7hp8aZl7IHsdvDexauGlyYcftE6q1LOTPPTKn85srJtj3Fs8orR17r
EI/vPTv3zdq1l4dEjQfXytI+PpJRdKf6xNX4yjVld5rroFu6IlCDaEnj9L8BivwD
+g==
=cNq2
-----END PGP MESSAGE-----
```

there is a disparity between the commands issued from the keybase.io website and the commands issued from the command line or GUI of the desktop client, as shown by these different outputs demonstrated above.. i hope the development team sees this? have they not tested this before deployment? does this happen with any other keybase user on reddit? or am i the only one seeing this? iM using the latest client for GNU/Linux (i know it's ALPHA, [from here](https://prerelease.keybase.io/keybase_amd64.deb) 2days ago) and the extensions for Chrome (.crx) and Firefox (.xpi)

**Comment by nimbosa** [comment]
Another Redditor here: #7990.
@maxtaco @malgorithms

**Comment by maxtaco** [comment]
@nimbosa I don't think you've misdiagnosed the issue. For some reason the server didn't see the post at all the first time. Usually this is due to some sort of reddit anti-abuse mechanism. We're seeing very few complaints here, so chances are it's working as well as it can from our end. Almost always, with reddit, problems are due to graylisting or other anti-abuse systems.
