### ISSUE TITLE
Windows Keybase File System doesn´t work

### ISSUE THREAD

**Issue by Sougu** [keybase/client#7975]
Hello,
there are 2 things that don´t work:
1. The "Open folder" button in the gui
2. I cant use the keybase device (k: on windows)

my log id: 387e8c541ec3540ee2d79b1c

**Comment by strib** [comment]
cc @zanderz @taruti

**Comment by zanderz** [comment]
"Open Folder" regression tracked with DESKTOP-4396

**Comment by zanderz** [comment]
Can you please paste the results of doing these commands in the Keybase Shell:
`keybase kbfsmount get`
`keybase kbfsmount getall`

If "K:" is listed by the getall command, could you try:
`keybase kbfsmount set K:`
and restarting? Thanks.

**Comment by Sougu** [comment]
Now it works, thanks!
