### ISSUE TITLE
Feature request: option to limit chat history/logging

### ISSUE THREAD

**Issue by comex** [keybase/client#7988]
If I'm having a sensitive conversation on Keybase Chat, I may want to keep chat history ephemeral, rather than having the whole conversation logged 'forever'.

One approach would be manually deleting conversation history on a regular basis.  Apparently in Keybase Chat that's not even possible at the moment! (#6096)  But even if it were, it'd be poorly suited to this use case:

- Deleting a conversation would remove all messages, even recent ones, whereas it would be better to remove only old messages.
- I might forget.
- The other participant(s) in the conversation might forget, and it would be awkward to have to keep reminding them :)

Instead, I should be able to configure a chat to automatically remove messages after a certain age.  Ideally this would automatically apply to all participants, but it would also be useful to have a version that only applied to my view of the conversation.

Comparison to other services:
- Several tools that speak the OTR encryption protocol can automatically disable logging for OTR chats, either by default or as an option - e.g. [Pidgin](https://riseup.net/en/security/message-security/otr#setting-up-otr).
- Google Talk used to have an "off the record" option that (just) disabled logging, but no longer.

**Comment by jzila** [comment]
We intend to eventually provide forward secrecy. From https://keybase.io/blog/keybase-chat:
> How Keybase solves this problem:
> * End-to-end encrypt all messages,
> * but only "exploding messages" (coming soon) will have FS.
> * Therefore, your history will survive, encrypted, except for the messages you choose.

That said, your feedback is useful in highlighting several use cases:
* Sometimes people want exploding conversations, not just exploding messages.
* Sometimes people want to retroactively decide that messages should have been exploding.

Thanks so much for your feedback! It'll definitely be helpful when we begin designing these features.

**Comment by DiagonalArg** [comment]
While this can get infinitely complicated, in my use case the Signal approach of being able to set a timer so that messages older than a certain time (day/week etc) disappear, is sufficient.

**Comment by ChildishGiant** [comment]
There's now [self-destructing](https://keybase.io/blog/keybase-exploding-messages) messages
