### ISSUE TITLE
Unable to run the desktop client on Windows

### ISSUE THREAD

**Issue by duttakapil** [keybase/client#8008]
Hi folks, appreciate all the work you guys are doing. 

I tried to open my Keybase Windows client today, and it just won't go beyond the loading screen. I tried to operate it from the tray icon, and after some time it worked. But now again, it's stuck on this screen : 

![image](https://user-images.githubusercontent.com/6577624/28963111-8ba9c0dc-7925-11e7-82b8-54049ded6d10.png)

My Internet is working fine. 

OS : Windows 10 Home 64-bit 

Should I uninstall and reinstall again?

**Comment by maxtaco** [comment]
Please run `keybase log send`.  @zanderz can you check it out?

**Comment by duttakapil** [comment]
Done. My log id: 4997b1abaf0cb56bf27dc91c

**Comment by maxtaco** [comment]
Thanks

**Comment by maxtaco** [comment]
You have a super old version. Can you grab the latest from our website?

**Comment by duttakapil** [comment]
I did, and it's working fine now. Thanks :)
