### ISSUE TITLE
No response from 'max@keybase.io' when attempting to reset a password on an account with active device and/or paper keys

### ISSUE THREAD

**Issue by jph** [keybase/client#8009]
I have attempted to reset my password on the keybase.io website, at which point the error within the password reset form asks for me to contact max@keybase.io. I have emailed this address twice, once in May and once in June, to which I have at the time of writing received 0 replies.

I don't have access to computer-1 nor my paper key.

![screenshot from 2017-08-04 22-22-34](https://user-images.githubusercontent.com/155770/28968485-8505be32-7963-11e7-84df-c6538178f698.png)

**Comment by maxtaco** [comment]
Maybe it's winding up in my spam folder. Can you try again and put some keyword in there I can search for. Also post that keyword here.

**Comment by jph** [comment]
@maxtaco Sent another email using the word of the day "chthonic" as a keyword. Thanks!
