### ISSUE TITLE
Instability in Windows 10 16257

### ISSUE THREAD

**Issue by dkackman** [keybase/client#8022]
I'm running Windows 10 insider preview 16257.rs3_release.170728-1700. Installed windows client. The keybase login hung and after a subsequent reboot, windows itself would lock up about 30 seconds after logging into the OS. 
Reverting to a restore point in windows got things back to normal but I'm afraid I no longer have the version of keybase that was installed. It was the version linked on the homepage on 8/3/2017.

**Comment by loudambiance** [comment]
I can confirm that this issue is also present in Windows Build: 16251.rs3_release.170721-2122. It took me 3 and half hours to figure out it was keybase causing the issue (I did not have a restore point to revert to).

**Comment by jzila** [comment]
Dupe of #7591
