### ISSUE TITLE
▶ ERROR No PGP keys available to choose from.

### ISSUE THREAD

**Issue by abitrolly** [keybase/client#8030]
I can't add GPG key after `keybase login`. Now it says to use `keybase pgp select`, which fails
```
$ keybase pgp select
▶ ERROR No PGP keys available to choose from.
```
But there are keys available
```
$ gpg -K
/home/anatoli/.gnupg/secring.gpg
--------------------------------
sec   4096R/78619180 2017-08-07
uid                  Anatoli Babenia <anatoli@rainforce.org>
ssb   4096R/EB3D9346 2017-08-07
```

**Comment by maxtaco** [comment]
Looks like that key just expired

**Comment by abitrolly** [comment]
@maxtaco how to check?

**Comment by maxtaco** [comment]
`gpg --edit-key` and or google around.

**Comment by abitrolly** [comment]
Not expired
```
pub  4096R/78619180  created: 2017-08-07  expires: never       usage: SC  
                     trust: ultimate      validity: ultimate
sub  4096R/EB3D9346  created: 2017-08-07  expires: never       usage: E   
[ultimate] (1). Anatoli Babenia <anatoli@rainforce.org>
```

**Comment by maxtaco** [comment]
Do a 'keybase log send' and @zapu can take a look when he gets a chance.

**Comment by abitrolly** [comment]
Log id 95d0b6583b2cc0c12e1a7d1c

**Comment by zapu** [comment]
Thanks! Can you do `which gpg` ?

**Comment by abitrolly** [comment]
```
$ which gpg
/usr/bin/gpg
```

**Comment by zapu** [comment]
What happens when you do
```
/usr/bin/gpg --no-tty --with-colons --fingerprint -K
echo $?
```

**Comment by abitrolly** [comment]
```
$ /usr/bin/gpg --no-tty --with-colons --fingerprint -K
sec::4096:1:3C9D625278619180:2017-08-07::::Anatoli Babenia <anatoli@rainforce.org>:::
fpr:::::::::DA3A0F734283FEA5A9141C833C9D625278619180:
ssb::4096:1:A34F7047EB3D9346:2017-08-07:::::::
$ echo $?
0
```

**Comment by abitrolly** [comment]
@zapu any news?

**Comment by zapu** [comment]
Sorry for leaving you in the dark. I've been unable to debug this any further. Even when I go and substitute my gpg binary to something that just prints your `--with-colons --fingerprint -K` result, I get proper behavior:

```
» keybase config set gpg.command /home/michal/gpg2_no_keys.py
» keybase pgp select
▶ INFO Forking background server with pid=11769
#    Algo    Key Id             Created   UserId
=    ====    ======             =======   ======
1    4096R   3C9D625278619180             Anatoli Babenia <anatoli@rainforce.org>
Choose a key: 1
▶ WARNING not exportable error: ImportKey (secret: true) error: No secret key found for fingerprint da3a0f734283fea5a9141c833c9d625278619180 (*errors.errorString)
▶ ERROR ImportKey (secret: true) error: No secret key found for fingerprint da3a0f734283fea5a9141c833c9d625278619180
```

(it will not go any further because I don't have the actual key I selected)

we will need more info to debug this one. For starters, is Keybase server running as the same user as the user with gpg keychain?

**Comment by squiter** [comment]
I'm having the same error of @abitrolly ... and I don't know how to debug this.

**Comment by zapu** [comment]
Would you mind going through the same debugging steps? 

that is, running these commands:
```
/usr/bin/gpg --no-tty --with-colons --fingerprint -K
echo $?
```

Also please do `keybase log send`. Thanks! Sorry for your troubles

**Comment by gordonel** [comment]
@zapu Hi there. Having the same issue, but the above method didn't work and debugging got me nowhere. The only different thing here is that I'm using https://github.com/romanz/trezor-agent with my Trezor. Any advice?

**Comment by zapu** [comment]
Hey @gordonel sorry I was out last week. Can you walk me through what are you trying to do? I'm unfamiliar with using Trezor for PGP. Do you have PGP keys in local GPG keyring and does it use Trezor as a smart card?

**Comment by gordonel** [comment]
I figured it out already :)

Basically, it creates a separate keyring that won't work without a Trezor plugged in and Trezor would do the signing and other stuff. I was able to add my GPG key by using Fedora and replacing the normal keyring with the Trezor one somehow. I think the problem is that Keybase ignores GNUPGHOME when it's set in .bashrc: https://github.com/romanz/trezor-agent/issues/295
-------- Original Message --------

**Comment by zapu** [comment]
Right, that's correct... this has come up before. I'm glad you figured that out. I'll bring up this issue internally that people are still getting burned by it.

**Comment by grnqrtr** [comment]
I'm having the same problem that @gordonel had. Does keybase still not take into account $GNUPGHOME ? Any help would be appreciated. Here is some info:

```
[grnqrtr@manjaro ~]$ echo $GNUPGHOME
/home/grnqrtr/.gnupg/trezor
[grnqrtr@manjaro ~]$ gpg -K         
/home/grnqrtr/.gnupg/trezor/pubring.kbx
---------------------------------------
sec   nistp256 2020-03-27 [SC]
      C6515C3CB09D83CCD614A4B70DB3437DA47ECB2F
uid           [ultimate] Travis Kilson <travis.kilson@gmail.com>
ssb   nistp256 2020-03-27 [E]

[grnqrtr@manjaro ~]$ keybase pgp select
You are selecting a PGP key from your local GnuPG keychain, and
will publish a statement signed with this key to make it part of
your Keybase.io identity.

Note that GnuPG will prompt you to perform this signature.

You can also import the secret key to *local*, *encrypted* Keybase
keyring, enabling decryption and signing with the Keybase client.
To do that, use "--import" flag.

Learn more: keybase pgp help select

▶ ERROR No PGP keys available to choose from.
```

**Comment by dragon788** [comment]
I believe in newer versions of Keybase they are using an internal Gnupg implementation so using a wrapper in lieu of the gnupg binary might not work anymore, but this might be another way to accomplish it without running [standalone commands](https://github.com/keybase/client/issues/2014#issuecomment-183817500) if you can still request an alternate gpg with the `keybase pgp advanced` option `--gpg` that is mentioned to supply your own binary/script.

https://github.com/keybase/client/issues/12895#issuecomment-406616278

**Comment by abitrolly** [comment]
`keybase` is sold.
