### ISSUE TITLE
Verification of Hacker News profile never succeeds

### ISSUE THREAD

**Issue by schliemannosaurusrex** [keybase/client#8079]
My Hacker News profile cannot be verified:

[ my public key: https://keybase.io/schliemanski; my proof: https://keybase.io/schliemanski/sigs/NEFxV6VK_x68N4FKRWQwhtTBTVZ-JK4Szo9LI9VgObw ]

![10-08-_2017_11-50-39](https://user-images.githubusercontent.com/24608408/29165175-30e36f8a-7dc2-11e7-9c94-c1d11d452ae8.png)

**Comment by modalduality** [comment]
@schliemannosaurusrex I believe you need at least 2 karma to verify.

**Comment by schliemannosaurusrex** [comment]
Thanks that´s it! 

![9176152-104217380_9-s1-v1](https://user-images.githubusercontent.com/24608408/29167519-ff439ae6-7dca-11e7-8164-ea6382bc63bf.png)
