### ISSUE TITLE
Yet another folder delete request.

### ISSUE THREAD

**Issue by virtualdxs** [keybase/client#8104]
BEGIN KEYBASE SALTPACK SIGNED MESSAGE. kXR7VktZdyH7rvq v5weRa0zkQaC5O7 j5kmeevsTEWeOgl BebQC86WhEoMa0t v5VkNlpStHUsrdl lfjVE4CaaxHacdn bfjXJoIe4YqT7xT V72jLNgxtGMmvJs wHkFpqLb4oSPeTx sj1XlQ0r4XtJuPD oHDg9s2RwpkC5m0 CmAmZvJssSkqHRO fZUFTc3WQMTw93z KY8rpWHWxtZh7Gk tqkbLJwpE12wdI0 0c9vek7BZtBrDQ1 LqLCg2GH0YNWDT4 WgzNKP0Ss2D3ic4 AgfQZ97L2Pq4nkJ 2gwpYBEAJVwsB1b UO3iB8cycH0NLtd pFQGuIoviyVaHrR YVM4AZ7mgNAp980 nXGwQTdaC7eOLs4 bMysA. END KEYBASE SALTPACK SIGNED MESSAGE.

**Comment by strib** [comment]
Hi @virtualdxs.  (Sorry for the delayed response, I've been on vacation.)  According to our servers, you should be able to read your private folder from your "K7DXS Laptop Arch" device.  If you still can't read it, there might be something else wrong, and a delete might not fix it.  If you are still having issues, can you please do a `keybase log send` after trying to access the folder, and let me know the resulting log ID?  Thanks.
