### ISSUE TITLE
▶ ERROR need a downgrade lease ID and merkle root; consider upgrading your client (error 291)

### ISSUE THREAD

**Issue by edef1c** [keybase/client#8110]
I'm currently using Keybase 1.0.22, which as far as I can tell, is the latest release.
Nevertheless, trying to revoke my lost device results in the following:
```
edef@cheetah ~> keybase device remove 0bf246ec5e2989cee46b743b0d4f7318
▶ INFO Revoking KIDs:
▶ INFO   012015bfd7d0a70c0a478e6c457aaa9fe9f4386f7d0f76fca448da118cdd991d86870a
▶ INFO   01212fd73c0aaabb20a06f2d4cda8422b4d3b650e792cd7a434f4c3dcdc7ab2cba100a
▶ ERROR need a downgrade lease ID and merkle root; consider upgrading your client (error 291)
```

**Comment by maxtaco** [comment]
It's not, it's super old. @oconnor663 can you help?

**Comment by oconnor663** [comment]
@edef1c are you using the Arch `community/keybase` package by any chance? If so, we should probably just tag our repo again. It's not how we usually make releases, but it's what this particular Arch package looks for, and some downstream BSD folks use GitHub tags too.

**Comment by oconnor663** [comment]
New version is tagged. Not sure how long before I expect to see an automatic rebuild of https://www.archlinux.org/packages/community/x86_64/keybase/.

**Comment by oconnor663** [comment]
Looks like that package has been updated in the official repos (thanks Felix for hosting that automation). Will still take some amount of time to propagate out to mirrors. And waiting for confirmation that that is in fact the package that @edef1c is using.

**Comment by edef1c** [comment]
Nope, I'm using NixOS, though we use GitHub tags on too. Would be happy to update the package.

**Comment by edef1c** [comment]
NixOS package is getting upgraded when https://github.com/NixOS/nixpkgs/pull/28290 merges, thanks for the tag. The new package version resolves my issues.
