### ISSUE TITLE
PGP Select

### ISSUE THREAD

**Issue by aytekinar** [keybase/client#8132]
### Description

When I issue `keybase pgp select`, I receive the following error:
```
#    Algo    Key Id             Created   UserId
=    ====    ======             =======   ======
1    4096R   44E60EE40CE08EA5             Arda Aytekin <arda@aytekin.biz>, Arda Aytekin <aytekin@kth.se>, Arda Aytekin <aytekin@protonmail.com>
Choose a key: 1
▶ ERROR ImportKey (secret: true) error: GPG error: exit status 2
```

The output of my `gpg --list-secret-keys --with-keygrip` is as follows:
```
/home/aytekin/.gnupg/pubring.gpg
--------------------------------
sec   rsa4096 2015-12-08 [C]
      F705F2977705F4CC60D760CE44E60EE40CE08EA5
      Keygrip = 40EB82D69DDE73C4204489F371BDAEC3C96849F4
uid           [ultimate] Arda Aytekin (Home) <arda@aytekin.biz>
uid           [ultimate] Arda Aytekin (Work) <aytekin@kth.se>
uid           [ultimate] Arda Aytekin (Other) <aytekin@protonmail.com>
ssb>  rsa4096 2017-08-16 [S] [expires: 2018-12-31]
      Keygrip = 9178C496505E65404223C6CFEF881B2467634D52
ssb>  rsa4096 2017-08-16 [E] [expires: 2018-12-31]
      Keygrip = 930AA30F3E8C62AA387659C31CAA4869B86BEF2F
ssb>  rsa4096 2017-08-16 [A] [expires: 2018-12-31]
      Keygrip = CB5E8BD859B3CBBC1D48939E7142673230CCDE68
ssb>  rsa2048 2017-08-16 [S] [expires: 2018-12-31]
      Keygrip = DE8801D5E95D24D73C70A1976D8BB7C1C7FFCD30
ssb>  rsa2048 2017-08-16 [E] [expires: 2018-12-31]
      Keygrip = 668BBD2AE3A778BE37041CD44D8AF1017BADEA7B
ssb>  rsa2048 2017-08-16 [A] [expires: 2018-12-31]
      Keygrip = 33DD3DD62E689BB7A75BC0A13B2C213D322A2664
```

Basically, I have two sets of GPG keys: 1 set (RSA4096; S,E,A) on my Yubikey 4, another set (RSA2048; S,E,A) on my Yubikey NEO.

In my setup, I do not have the secret subkeys present on the laptop. However, I have the secret subkeys backed up in another hard-disk. On a daily basis, I simply insert either of my cards when doing GPG-related operations.

I'd appreciate if you helped me import a GPG key onto `keybase.io`. By the way, I wouldn't want to `keybase pgp import`, if possible. `keybase pgp select` is good enough for my purposes (just the public part).

**My log ID.** `f6ffa46465abfcda4db52b1c`

**EDIT.** `keybase pgp select --no-import` apprently did the trick for me (just confirming the *public* part of my key). Still, it would be nice to know how to be able to use my smartcards together with the local Keybase keychain.

**Comment by maxtaco** [comment]
Some sort of local misconfig or incompatibility with your gpg configuration:

```
11920 2017-08-16T14:42:58.968057+02:00 ▶ [DEBU keybase gpg_cli.go:353] 3f0 | running Gpg: /usr/bin/gpg2 --no-tty --armor --export-secret-key f705f2977705f4cc60d760ce44e60ee40ce08ea5
11922 2017-08-16T14:44:03.505466+02:00 ▶ [DEBU keybase gpg_cli.go:332] 3f2 gpg: key 40EB82D69DDE73C4204489F371BDAEC3C96849F4: error receiving key from agent: Timeout - skipped
```

Try `keybase pgp select --no-import`

**Comment by aytekinar** [comment]
Thank you for your prompt answer!
