### ISSUE TITLE
KBFS issue - no folder structure exists

### ISSUE THREAD

**Issue by dbldub** [keybase/client#8153]
[On macOS. /keybase files are not available. When doing an ls /keybase, the error I receive is - ls: : Device not configured.]

my log id: bac0e32d8daa7049a4f2191c

**Comment by strib** [comment]
Hi @dbldub, I took a quick look at your logs, and everything seems ok. Is it possible you've had a terminal tab open under `/keybase` for multiple days, and that's where you're seeing the problem?  If so, a `cd /keybase` would fix it.  The app updates and restarts itself on macOS, which umounts and re-mounts `/keybase`, so any old tabs would still be `cd`'d into an old mountpoint.

If that doesn't help, let me know and I'll look more deeply into it.

**Comment by dbldub** [comment]
Hi @strib,
I usually close the terminal application when I'm done with it. I started a new terminal session and tried the lines below.

`Last login: Thu Aug 17 15:36:05 on ttys000
Wades-MBP:~ wade$ cd /keybase/
Wades-MBP:keybase wade$ ls
.
Wades-MBP:keybase wade$ pwd
/keybase
Wades-MBP:keybase wade$ ls
ls: .: Device not configured`

The file structure was empty, then I couldn't list again after that.

Thanks.

**Comment by strib** [comment]
Ok thanks.  Are you willing to do a `keybase log send` so I can look at what might be wrong?

**Comment by dbldub** [comment]
I was using my machine today when I noticed that the Keybase application was not running. I started the application, and then the folder structure was there. It seems that the KBFS is working as expected now. I see the files I created on keybase.pub. Restarting the Keybase application the other day did not help. I'm not sure what happened. Is there any other troubleshooting that is possible, or do we close the issue?

**Comment by strib** [comment]
I guess if the application got shut down somehow, that would explain things.  If you'd like us to investigate why it might have been shut down (whether a crash or a user action or something else), then please send logs and we'll look.  Otherwise feel free to close this out.

**Comment by dbldub** [comment]
Thanks. I will close the issue.
