### ISSUE TITLE
Set not mine bitcoin address as mine on Keybase. Is bitcoin address on keybase profile a proof of identity?

### ISSUE THREAD

**Issue by Drabiv** [keybase/client#8164]
I was testing setting of bitcoin address, I took first bitcoin address that I found on keybase and was able to set it as mine own without any problem. Shouldn't there be some verification, checking that you control bitcoin address that you set as yours? At least to avoid loss of bitcoins sent to wrong address set by mistake by the owner of keybase profile. Also potentially, it can lead to a misrepresentation of identity, when someone knows someone by its bitcoin public address. 
I guess, what I am getting at, is that showing bitcoin address on keybase profile page in the same column with proofs of identity is misleading, as currently, it is not a proof of identity, it is just an address, that might or might not belong to the keybase identity.

**Comment by dabura667** [comment]
I fully agree with you.

However, the logistics of this are difficult. If you require a user to sign a message using their bitcoin address private key...

1. Many wallet apps don't have this feature, so there is a high hurdle for people to sign messages using their private key. This discourages use of the feature.
2. What about P2SH addresses which could be anything, maybe not even dealing with signatures at all... (I could make a P2SH that is "What is 1 + 1?" and the only data needed to send bitcoin from that address is "2") And the more common usage of multisig (2 sigs out of 4 etc.) has no standard method of signing.

So there is an EXTREMELY high burden on development to add this feature... and the result is that LESS PEOPLE USE the feature.

I see your point about misleading.

1. Find a rich address that isn't on anyone's Keybase.
2. Add it on your Keybase.
3. Flash it around to get investors to believe some investment scheme that you'll invest x Bitcoins etc. And if they're stupid, they might just look at your Keybase and take that as proof.

**Comment by Drabiv** [comment]
Thanks @dabura667 that clarifies a lot. To avoid confusion, I would still suggest to move cryptocurrency addresses to another column and label it somehow, so it is clear that it is not a proof of identity.

**Comment by dabura667** [comment]
I agree.
