### ISSUE TITLE
Intermittent disconnects from drive K:

### ISSUE THREAD

**Issue by aaagever** [keybase/client#8166]
Keybase GUI Version: 1.0.28-20170815141344+c36e316

Hi,
When accessing drive K:, to copy some of my files to the private folder, I constantly get intermittent disconnects. 
Bottom line - I cannot copy files to the private folder.

**Comment by strib** [comment]
Hi @aaagever, can you please run `keybase log send` from the Keybase shell, and let us know the resulting ID here, so we can investigate?  Thanks!

**Comment by aaagever** [comment]
Hi @strib , my log ID was 29afbd47c99bf01bd614351c

Thanks!

**Comment by strib** [comment]
Hmm, we are having out-of-memory issues (showing up in the disk block cache for some reason, cc @jzila).

@aaagever, can you please tell us how much RAM this windows device has?  Is it a VM?

**Comment by aaagever** [comment]
16GB RAM. Not a VM.

**Comment by jzila** [comment]
@strib: the OOM crash is at ~1GB RAM, so I'm not sure. Looks like both crashes are during CR of a large file that needs to be copied entirely.

**Comment by strib** [comment]
@aaagever: you definitely hit a bug in the filesystem, and I think it's being made worse by the fact that we do 32-bit builds for Windows (even for 64-bit machines), which is making you hit an artificial memory limit.

The problem essentially is that you wrote a bunch of data into the filesystem, and we _staged_ it locally on your hard drive until we can successfully send it over to our servers.  Unfortunately, the amount of staged data you have (about 3GB I think) is overwhelming the memory limitations of the Windows build.  We obviously need to make that impossible, but it's going to take some time.

If you want a quick (and unsatisfying) fix, I think you can shut down Keybase and delete all the staged data from your disk, and then when Keybase starts back up it shouldn't crash anymore.  Of course then that data wouldn't appear to be in your folder anymore, so if that's you're only copy, it's not a good solution.  If you do want to try that, shut down Keybase completely and delete this directory: `C:\Users\<YOUR_LOCAL_WINDOWS_USER_NAME>\AppData\Local\Keybase\kbfs_journal\v1\012078884d2c35087a64013f3c9aac475d9d-31c3c220236f4491`.  (Substitute in your local Windows user name where indicated, I didn't want to leak it publicly.)

Once the filesystem is stable again, you can try to put the data back in it, but until we have a fix you should probably copy things in more slowly, say ~500MB at a time or so if possible.  Sorry for the inconvenience, I know that sucks!

If the Keybase copy of your data is too important to lose, or you are willing to wait for a fix, let us know and we'll try to prioritize a fix, but I'm not sure how long it would take to get a release in your hands.

**Comment by aaagever** [comment]
Interesting. Will deleting that directory also delete everything that's in my "private" folder?

**Comment by strib** [comment]
It will only delete the stuff in your private home folder (i.e., not in any shared private folders) that hasn't yet been written to our servers (stuff you can't see from any of your other devices yet).

**Comment by aaagever** [comment]
Worked! Thanks!!
Now just for my knowledge, did you say that the private home folder is backed up on your servers?
Will I be able to access it via web and/or mobile in the future?

Thanks again.

**Comment by strib** [comment]
Yes, our servers hold all data that gets uploaded successfully from one of your laptop/desktop machines, and can serve that data back to any other laptop/desktop that can mount the directory.  In the future, mobile devices will work too; web will probably never work for private folders, due to security concerns, but public folders are available at https://keybase.pub.

If you want more technical info, check out https://keybase.io/docs/kbfs/understanding_kbfs.

**Comment by aaagever** [comment]
Thanks for everything! Closing this issue now.
