### ISSUE TITLE
Unable to login to Keybase with private key imported in GPG

### ISSUE THREAD

**Issue by golyalpha** [keybase/client#8177]
I have just exported my private key from Keybase.io and imported it into GPG manually, unfortunately, when I do `keybase login`, input my keybase email, it asks me for the password, and later to verify with one of the devices linked to my account. 
I have two, my mobile phone, which is currently discharged and the charging connector is broken, and my laptop, which has just gone through a reinstall, and I'm trying to reauthenticate with keybase. 
Do I have to run a different command to log into keybase with my GPG Private Key?

**Comment by maxtaco** [comment]
We've recently rolled out new features that make it unsupported to use PGP provisioning (except when you provision your first device).  The details are [here](https://keybase.io/docs/teams/puk). If you don't have a paper key, you either need to get your phone fixed, or reset your account.

**Comment by golyalpha** [comment]
Well, I hoped that wouldn't be the case... Thanks anyways.
