### ISSUE TITLE
Bug with pgp encrypting and signing from website

### ISSUE THREAD

**Issue by Engelberg** [keybase/client#8216]
When you use the keybase website form to encrypt a message for another user and click the checkbox to sign that the message is from you, the website erroneously encrypts the message with your own public key, rather than using the public key of the intended recipient.

This appears to be a relatively new bug that I haven't encountered before.

**Comment by maxtaco** [comment]
If you are logged in it encrypts for both you and the recipient.  It had
been this way for a long time!

**Comment by Engelberg** [comment]
When I didn't check the "sign" box, the recipient was able to decrypt the message, but when I did check the "sign" box and used "encrypt and sign", the recipient said the message did not decrypt, and he received an error message that the signature was not on file with keybase.

In the first case, I was not able to decrypt my own message, but in the second case I was able to decrypt my message, which is why I assumed that the problem was that had been encrypted for me and *not* the intended recipient.

**Comment by maxtaco** [comment]
Thanks for the feedback. @zapu can you take a look?

**Comment by Engelberg** [comment]
I tried it again, and this time it worked.

I think that, possibly, when I used my password manager to fill in the password for signing the message, it treated the recipient field as "username" and filled that in as well with my name.

So, user error (me).  Closing.

**Comment by maxtaco** [comment]
phew! thanks for the follow up.  yeah, that would be a bad bug if true.
