### ISSUE TITLE
Action Required (Install Keybase)

### ISSUE THREAD

**Issue by caffeinatedMike** [keybase/client#8220]
![keybase](https://user-images.githubusercontent.com/22151742/29721546-a9ae7c28-898b-11e7-96da-33de79acbcb6.png)
Getting the above message and cannot send/receive messages to people I follow while others I have talked to say they were not required to download Keybase. I need to be able to use the service without installing Keybase as the computers I mainly plan on using it will not allow the installation (policy issues).

**Comment by Asternitix** [comment]
Does the policy allow for PGP use? If so, keybase.io/crypto will be suitable. if not, use the mobile version if permissible.
