### ISSUE TITLE
Do not use electron if you care about security

### ISSUE THREAD

**Issue by gagarine** [keybase/client#8255]
First, using electron is building on top of a huge stack with a lot of potential security issues.

But most importantly, you are basically running a browser with full access to your OS. That mean a XSS can not only access to the application functionality but also potentially read/write your system files. There is, of course, progress and improvement but the stack structure is by design insecure.

Then, Javascript is not the language designed with security in mind. I'm not saying JS is not secure, but it's very easy to write insecure code with it. TypeScript help, but again, you have a bigger stack... you don't control the quality of external libraries or tools.

Javascript is not better than C and C++, that are also languages where security problem are right around the corner. Java and now Rust are a lot more solid in this regard.

See also :

- https://www.elttam.com.au/blog/a-review-of-the-eff-secure-messaging-scorecard-pt2/ 
- http://blog.scottlogic.com/2016/03/09/As-It-Stands-Electron-Security.html
- http://blog.scottlogic.com/2016/06/01/An-update-on-Electron-Security.html

**Comment by Syncrossus** [comment]
[Here](https://github.com/electron/electron/issues?q=is%3Aissue+is%3Aopen+security+label%3Afixme%2Fsecurity) is a list of known security-related issues in electron

**Comment by ronnicek** [comment]
So you suggesting Java as better alternative to it? I dont want to start some flame.. but most of people doesnt care about up to date their Java.. and [list of security CVE`s of Java is endless](http://www.cvedetails.com/vulnerability-list.php?vendor_id=93&product_id=19117&version_id=0&page=1&hasexp=0&opdos=0&opec=0&opov=0&opcsrf=0&opgpriv=0&opsqli=0&opxss=0&opdirt=0&opmemc=0&ophttprs=0&opbyp=0&opfileinc=0&opginf=0&cvssscoremin=0&cvssscoremax=0&year=0&month=0&cweid=0&order=1&trc=527&sha=e7bd4bdaede94939bbb984bced9c264b834fc20c)..  and still counting :)

**Comment by gagarine** [comment]
@ronnicek I do not suggest Java because of the environment, but because it's harder to make dangerous code in Java than JavaScript. (FYI you can bundle the JRM in your app so you don't rely on the one eventually installed on the target desktop.)

Really your instinct does not tell you you should choose a statistically typed language for a highly sensitive application? Something you can for example tests on build time? No? Keep in mind that if you fuck around with security with those kind of product some peoples can literally be killed by their gov, for example.

To be clear, I don't recommend any particular technology especially because I'm not an expert in those. I'm simply saying electron/JavaScript seem a bad choice in terms of security. I listed other languages and stacks to put things a bit in perspective.

**Comment by cjb** [comment]
Let's not start language wars, please.

**Comment by gagarine** [comment]
Again. I don't care about the language. I only care about security. So if someone can send a link that says "electron/js is a great stack for security sensitive applications"  I would be happy.
