### ISSUE TITLE
Cannot login to app after deleting mobile app

### ISSUE THREAD

**Issue by MylesBorins** [keybase/client#8311]
Oh hey! I was unaware that installing the mobile app created a new level of 2FA. After deleting it from my phone I am now unable to log in to any other devices.

Do I need to make a new account?

**Comment by MylesBorins** [comment]
This is an experience breaking problem.

**Comment by cjb** [comment]
Hi! Sorry to hear this. Do you still have any logged in desktop devices or your paper key, if you made one?

I'd say email max@keybase.io to see if we can help fix this.

**Comment by cjb** [comment]
@MylesBorins Oh, and if you can still log in to your profile, there's a "reset your keys" option behind a gear icon on your profile page. (You'll have to re-do your social proofs.)

**Comment by maxtaco** [comment]
I can reset your account if you've lost all devices.  But email as @cjb says

**Comment by cjb** [comment]
.. and you would lose access to chats and files, so it's a last resort kind of thing.

**Comment by MylesBorins** [comment]
taking it to email. thanks

**Comment by cjb** [comment]
It looks like you have a phone and computer registered. Just to be clear: if you still have the computer install, you don't need to do any of this. It's not 2FA, having any device is sufficient.
