### ISSUE TITLE
Not able to sign or export private key

### ISSUE THREAD

**Issue by fism** [keybase/client#8389]
I am unable to sign or export the private key via the Keybase shell. I since have updated the client but still do not receive any feedback from the keybase command.

my log id: 9b37df3091f00530d3462a1c

**Comment by maxtaco** [comment]
@zapu can you take this one?

**Comment by fism** [comment]
I was able to resolve it with the following commands:

`keybase logout
keybase stop
keybase start
keybase login`

For some reason after I upgraded the dialog to enter in my private key wasn't displaying.
