### ISSUE TITLE
Cannot access private folders

### ISSUE THREAD

**Issue by BigGiantHead** [keybase/client#8426]
Hi,

Since installing the latest Keybase version I cannot open my private folders. I saw that there are other people with the same issue so I followed you instructions and here is the signed message.

BEGIN KEYBASE SALTPACK SIGNED MESSAGE. kXR7VktZdyH7rvq v5weRa0zkP6wfqG qEZpkajOAnEoBGM rEoH5rlHpQ383pR Byr1SlpsnwAdkHu BBHgV1NfAEO57K1 n7aepIAJ4tnxn0i iVM6czOssdhfBNp bGZf1E5RJ4MlfDG ANVxtYNyhKBHDMM ULOv7R8sCn0Ucbh SE3wsGIUvk9L6tE B6wXifqAaFLEZTR faf7cwMlAPfJl9A 6TgqOPheYbNxPCF hcOutaC3lEeBvGW qfHh4QPJOxXmmDG pzKN6mvldCJzvlI 4spkU63NIGdP2fz GooIhMiWg1mO6w7 33VmHogSreWOQu9 rK5Jd7c6. END KEYBASE SALTPACK SIGNED MESSAGE.

I hope that this does not happen every time I install a new version.

Thanks

**Comment by cjb** [comment]
Hi, you don't need a reset, just need to turn the mount back on in the Folders tab.
