### ISSUE TITLE
The item “avatar” can’t be copied because there isn’t enough free space.

### ISSUE THREAD

**Issue by mathiasconradt** [keybase/client#8432]
I ty to upload an avatar image (422kb) to the public folder, as it is mentioned on the keybase website:

> Pro tip: With Keybase installed on your computer, you can put a picture up to 5MB in /keybase/public/mathiasconradt/me/avatar.jpg (or avatar.png) and select it here.

However, it fails with the error message 

`The item “avatar” can’t be copied because there isn’t enough free space.`

when I drag it into the folder (creating a "me" folder worked, copying a file into it doesn't). And I have 34GB of free disk space.

![screen shot 2017-09-13 at 18 07 30](https://user-images.githubusercontent.com/295122/30388263-7457ed10-98af-11e7-8963-6de2b9357915.png)

(I'm on Mac OS X)

What's interesting: the file does not show in Finder, but it does show in PathFinder (https://cocoatech.com/#/):

![screen shot 2017-09-13 at 18 19 39](https://user-images.githubusercontent.com/295122/30388583-6b058488-98b0-11e7-8641-ce7984a873b0.png)
 
with `._avatar.jpg` being 4k of size and `avatar.jpg` being 0b.

**Comment by mathiasconradt** [comment]
After a while, I was able to delete the empty 0byte file again and re-upload it. It's now working, but I still think that there are some problems with that mounted folder of keybase and the desktop client probably locking something here.

I am closing this ticket now, however I think that there is something not working properly.

**Comment by strib** [comment]
@mathiasconradt: you can get that message if you're out of Keybase quota, not just your local hard drive space.  If you want to run `keybase log send`, I can take a look and see if I can figure out why you got the error.

**Comment by mathiasconradt** [comment]
@strib I just sent the log:

```
Success! Your log ID is:

  951a719475973626f53eef1c

Here's a URL to submit new bug reports containing this ID:

  https://github.com/keybase/client/issues/new?body=[write%20something%20useful%20and%20descriptive%20here]%0A%0Amy%20log%20id:%20951a719475973626f53eef1c

Thanks!
```

Regarding:

`You can get that message if you're out of Keybase quota`

Understood, but I just signed up for keybase an hour ago or so, and I had no files at all in my keybase folder. The avatar.jpg was basically the very first file I was going to upload/copy into that folder.

**Comment by mathiasconradt** [comment]
What's also interesting is that the error message does not say 'avatar.jpg' but only 'avatar', dropping the suffix.

**Comment by strib** [comment]
Hmm, I don't see any errors returned by our code in the logs.  It looks like macOS created the file, and just never even tried to write data into it.  I've seen this before when the OS thinks there's not enough space for it in our drive.  But according to our logs, the `/keybase` mount should be reporting 250GB free.

Is it possible some other partition on your computer, like maybe `/tmp/` or your Trash directory, are low on space?  Could you share the output of `df -h`?

**Comment by mathiasconradt** [comment]
@strib This is the output:

```
Filesystem      Size   Used  Avail Capacity   iused   ifree %iused  Mounted on
/dev/disk0s2   465Gi  432Gi   33Gi    93% 113350612 8577617   93%   /
devfs          376Ki  376Ki    0Bi   100%      1300       0  100%   /dev
map -hosts       0Bi    0Bi    0Bi   100%         0       0  100%   /net
map auto_home    0Bi    0Bi    0Bi   100%         0       0  100%   /home
/dev/disk3s1   447Mi  287Mi  160Mi    65%     73596   40952   64%   /Volumes/Keybase
kbfs@kbfuse0   250Gi  546Ki  250Gi     1%         0       0  100%   /keybase
```

**Comment by mathiasconradt** [comment]
I think it might actually be a problem with the native Mac OS X Finder app. The problem seems to only happen with the Finder, it does not happen with the third-party app PathFinder (https://cocoatech.com/#/).

I just made a screencast, where I tried to copy images to the keybase folder via Folder (at the top of the screen) and via PathFinder (at the bottom of the screen). You can see the difference. Weirdly for some files there is no problem even with the Finder, but in most cases, the problem occurs.

Screencast: https://www.dropbox.com/s/0tkyzoq6zinr8vr/720.mov?dl=0
