### ISSUE TITLE
Keybase folders are showing up in Explorer, contra message.

### ISSUE THREAD

**Issue by cerebrate** [keybase/client#8490]
After the latest Keybase upgrade (Windows client), the Folders page displays a message "Your Keybase folders are currently not showing up in your explorer", even though the K: drive is as present and accessible as it's always been, per enclosed screenshot.

![keybase-yesno](https://user-images.githubusercontent.com/371623/30520975-210e9b24-9b7d-11e7-9cc6-416534e2889e.PNG)

**Comment by cerebrate** [comment]
(It does appear to have disabled click-to-open-folder functionality in the client, however, even though manual navigation works fine.)

**Comment by maxtaco** [comment]
@cerebrate thanks for the report

cc: @zanderz

**Comment by unlocKing** [comment]
the update on win 10 works for me, however on a new clean win 7 install I get the same as above or just a continuous disconnected

**Comment by zanderz** [comment]
@cerebrate @unlocKing Please do a `keybase log send` so we can see why this might have happened on your systems.

**Comment by cerebrate** [comment]
@zanderz Is done. My log id is 0ac1c4316e37ff4a121ea51c .

**Comment by magicstone1412** [comment]
I had the same issues My log id bb8a5a6e4cff66a21722db1c

**Comment by Mystiflow** [comment]
Checking in for same issue, 0f281ea4a4333e489d26d81c

**Comment by zanderz** [comment]
Sorry for the delay. This week's upcoming release should improve these issues - I'll update here when it is available.

**Comment by szul** [comment]
Has this been resolved? Getting it on a fresh reset Windows 10. Log ID: e72ccda667a9a9abb8d87a1c

**Comment by szul** [comment]
I managed to solve my issue above by following the comment in issue #8968 to reinstall Dokan.
