### ISSUE TITLE
Failure to verify a twitter account

### ISSUE THREAD

**Issue by macosxguru** [keybase/client#8521]
I have no idea what the problem is. The app consistently fails to verify the twitter account. 

This is the link to the verification tweet: https://twitter.com/macosxguru/status/909941977122185216

You guys might be overwhelmed with sign ups.

macosxguru

**Comment by cjb** [comment]
@macosxguru The bit.ly link looks strange.

**Comment by macosxguru** [comment]
Twitter made that link. I didn't.

**Comment by macosxguru** [comment]
It is verified now. Sorry my mistake.
