### ISSUE TITLE
macOS: Option to hide the running app indicator in dock

### ISSUE THREAD

**Issue by MindTooth** [keybase/client#8525]
Keybase GUI Version: 1.0.30-20170915193210+8c3c799f2

Hi,

Would love for the app to have an option to hide the running app indicatior in the dock, and just show in the menu bar.
At least when the window is hidden.

**Comment by azag0** [comment]
When you quit the app, it will remain in the menu bar. Only quitting it from there fully quits it.

**Comment by MindTooth** [comment]
Yes it does 👍   Thank you.
