### ISSUE TITLE
No way to disable "Launch at login" in OSX

### ISSUE THREAD

**Issue by m-o-e** [keybase/client#8558]
Keybase GUI Version: 1.0.30-20170915193210+8c3c799f2

There should be a checkbox to toggle "Launch at login" in the preferences.

**Comment by maxtaco** [comment]
Yes there is, just go through your macOS's "System Preferences > Users & Groups > Login Items"  settings window

**Comment by m-o-e** [comment]
It is common practice to provide that toggle in the app preferences.
On my machine Keybase is the only auto-starting app that doesn't have it.
