### ISSUE TITLE
Provisioning Error (OSX)

### ISSUE THREAD

**Issue by nvk** [keybase/client#8564]
`Unknown error: GPG error: exit status 2`

![keybase 2017-09-20 10-37-52](https://user-images.githubusercontent.com/797193/30650068-f992a1d8-9def-11e7-9e97-934f9086c085.png)

**Comment by zapu** [comment]
Hello, can you do `keybase log send` from command line (or Keybase Shell if on Windows)? Thank you

**Comment by nvk** [comment]
np, `20947cb41647f8bd87093f2b1c`

**Comment by zapu** [comment]
Is this during login?

**Comment by nvk** [comment]
Correct

**Comment by zapu** [comment]
Can you try to log in from command line? Command is `keybase login`.

**Comment by nvk** [comment]
My apologies, the issue is on "One-time shell to GPG" not on the login step

**Comment by nvk** [comment]
Nevermind, a restart seem to have cleared the issue. Possible issues is not handling delays on connections due to little snitch time to approve the window. Or possible delay on GnuPG/MacGPG2 key signing.

**Comment by zapu** [comment]
The logs suggested at some GPG problem.
```
▶ [DEBU keybase gpg_cli.go:336] 22f gpg: problem with the agent: Timeout
▶ [DEBU keybase gpg_cli.go:336] 231 gpg: signing failed: Operation cancelled
```

the GPG situation is not perfect, sometimes this happens because GPG_TTY not being set correctly by Keybase when shelling out. I'm glad your issue is resolved, though!

**Comment by nvk** [comment]
👍
