### ISSUE TITLE
New install loading forever

### ISSUE THREAD

**Issue by Aranad** [keybase/client#8578]
I've been running keybase for a year or so on one laptop, and today wanted to add another laptop, but unfortunately the process isn't working. The app installed fine (Mint 18.1) but when I run it it just says "loading..." forever - I can't add new device or anything because everything's just progress bars with loading even after hours.

Keybase GUI Version: 1.0.31-20170919160225+373810357

**Comment by maxtaco** [comment]
Hmmm....  Did you `run_keybase`?  CC: @cjb and @oconnor663

**Comment by Aranad** [comment]
Yep, it runs fine, but just the window stays loading, here's a screenshot:
![screenshot from 2017-09-21 06-40-24](https://user-images.githubusercontent.com/1755922/30689665-0752f19e-9e98-11e7-8b1b-0e6160349235.png)

**Comment by Aranad** [comment]
Oh yeah and It says I'm not logged in and doesn't have "open keybase" in the menu, when I click login nothing happens. I am logged in at the keybase.io site...

**Comment by maxtaco** [comment]
Do 'keybase log send'

**Comment by Aranad** [comment]
ok sent with ID 8a65d9f5da2692f08db4c91c

**Comment by maxtaco** [comment]
looks like your keybase service isn't running, as suspected above. @cjb or @oconnor663  can help more

**Comment by Aranad** [comment]
Oh yeah just realised it wasn't running due to perms as I ran from root before, it's running again now with the same loading problem and I can see in the app log its just infinitely saying this:
log: Thu Sep 21 2017 11:40:57 GMT-0300 (BRT) (1506004857869): RPC [W] localhost: Error: connect ENOENT /run/user/1000/keybase/keybased.sock

**Comment by Aranad** [comment]
there seems to be some things listening...
netstat -nlp|grep key
unix  2      [ ACC ]     STREAM     LISTENING     22842    1716/gnome-keyring- /run/user/1000/keyring/control
unix  2      [ ACC ]     STREAM     LISTENING     23014    1716/gnome-keyring- /run/user/1000/keyring/pkcs11
unix  2      [ ACC ]     ST

**Comment by Aranad** [comment]
It's working now! Seemed to be that permissions of dirs had got messed up when I ran as root one time... I nuked all the kb dirs in .local, .config and .cache and then it worked :-)

**Comment by jzila** [comment]
Awesome! Closing this issue.
