### ISSUE TITLE
Team API akin to `keybase chat api`?

### ISSUE THREAD

**Issue by woodruffw** [keybase/client#8579]
Are there plans to introduce a command-line JSON team management API similar to `keybase chat api`? 

I see that `keybase team list-memberships` takes a `--json` flag, and it would be great to expose a similar interface for all team management functionality via `keybase team api` or something similar.

Thanks!

**Comment by patrickxb** [comment]
We're working on it, thanks!

**Comment by woodruffw** [comment]
I see `keybase team api` as of my last update, thanks a ton for adding this!

**Comment by junderw** [comment]
@patrickxb there seems to be an error in `keybase team api -m '{"method": "list-self-memberships"}'`

the "teams" array contains one object per member of every team I am in... 

It should be an array of objects where the number of objects = the number of teams I'm in.
If you want to put all users in there, make a "users" key in the subsequent team objects please.

**Comment by patrickxb** [comment]
@junderw I noticed this yesterday as well.  I think something changed out from underneath `list-self-memberships` in the `keybase team api` command recently, as it wasn't doing that when I first wrote it.

I will make an internal ticket and we will fix it.  Sorry for the inconvenience, there have been a lot of changes with team functionality recently.
