### ISSUE TITLE
KBFS Disk Space Showing as 250GB on Windows

### ISSUE THREAD

**Issue by k3nsai** [keybase/client#8583]
I have recently noticed that the KBFS Disk shows up as a 250GB drive on my 3 Windows 10 machines.
While that would be nice, I don't think its correct and you might want to take a look at this.
.BR

**Comment by strib** [comment]
It is correct!  Enjoy!

**Comment by k3nsai** [comment]
Incredible! Thank you for this great app & feature!
👍 🥇
