### ISSUE TITLE
Auto-scrolling on new message

### ISSUE THREAD

**Issue by bitstein** [keybase/client#8585]
In a chat, when you scroll back to see historical messages, when a new message is sent, the scroll jerks to a new location. Keybase should implement something similar to Slack where upon new messages, the scroll stays in the same y-position, and a popup at the bottom lets you know there are new messages. This way reading old messages is a smoother, uninterrupted experience.

**Comment by mmaxim** [comment]
I think this is fixed right @chrisnojima? Should be available in next release if I am right.

**Comment by bitstein** [comment]
Oh great. Thanks, @mmaxim!

**Comment by chrisnojima** [comment]
this is on desktop? if so we did fix this auto scroll down behavior (a regression actually). there is a design to do the button to scroll you down but we haven't gotten to it yet

**Comment by evvvritt** [comment]
Hi @chrisnojima, I'm currently experiencing the "un-fixed" behavior in `1.0.48-20180516160420+b56432f520`, auto-scrolls me to bottom of chat on new messages :/

**Comment by chrisnojima** [comment]
This hasn't been merged yet. Next release

**Comment by keybaseIOS-ux** [comment]
This is still an issue in the iOS client.
