### ISSUE TITLE
Startup Error

### ISSUE THREAD

**Issue by JPKCom** [keybase/client#8607]
my log id: 5c44610a29e643616fe8781c

The error occurred directly at startup, after the iMac (macOS Version 10.12.6) was booted, after clicking on "Login" in the top macOS status bar.

`▶ INFO ignoring error getting keybase status: There were multiple errors: dial unix /Users/JPK/Library/Group Containers/keybase/Library/Caches/Keybase/keybased.sock: connect: no such file or directory; dial unix /Users/JPK/Library/Caches/Keybase/keybased.sock: connect: no such file or directory
▶ INFO ignoring UI logs: There were multiple errors: dial unix /Users/JPK/Library/Group Containers/keybase/Library/Caches/Keybase/keybased.sock: connect: no such file or directory; dial unix /Users/JPK/Library/Caches/Keybase/keybased.sock: connect: no such file or directory`

**Comment by maxtaco** [comment]
Does restarting your mac work?

**Comment by JPKCom** [comment]
That was not necessary. After the client crashed, restarting it was enough. Also I didn't have to log in again.

**Comment by retrobabel** [comment]
I'm getting the same issue, but it's not resolved after restart. My log ID: 5f67de9913237ca46ab97b1c

**Comment by maxtaco** [comment]
@retrobabel, can you run:

```
ls -lsa ~/Library/LaunchAgents/
```

Thanks!

**Comment by maxtaco** [comment]
Also:

```
launchctl list
```

would be useful too.

thanks!
