### ISSUE TITLE
Cannot import my pgp key

### ISSUE THREAD

**Issue by ThierryIT** [keybase/client#8609]
Hello,
New to Keybase, I am trying to import my personal pgp pub key.

From the Keybase shell:

keybase pgp select:

...
...

Do not list the right version of my key .... If using GPA or Kleopatra it is working.

Any idea ?

Thx

**Comment by lapwat** [comment]
`gpg --list-keys` should show you the fingerprint of the keys in your keychain
Then `keyboard pgp fingerprint` to import it.

Did you try that ?

**Comment by ThierryIT** [comment]
keyboard ?

**Comment by lapwat** [comment]
keybase sorry

**Comment by ThierryIT** [comment]
Error GPG error: exit status 2

**Comment by lapwat** [comment]
Sorry to hear that, it worked like a charm for me :(

**Comment by junderw** [comment]
Try gpg -K and make sure you have the private keys on your keychain. If the key is listed with a * before it, that means “you don’t have this private key”

**Comment by ThierryIT** [comment]
Hi,
My private gpg key is not in my PC. I am, as it should be, only working with subkeys ... So not possible to import subkeys ?
Thx

**Comment by maxtaco** [comment]
This isn’t a very commonly requested feature and we probably are not going to get around to implementing it.  But the client is open source and we accepts PRs!

**Comment by ThierryIT** [comment]
Thx for this information.

**Comment by maxtaco** [comment]
Actually on second thought his might be supported (I haven’t tried importing a secret key with offline master).  The import failure might also be due to a gpg configuration failure. Check your log and see if any errors were output.

**Comment by maxtaco** [comment]
Cc @zapu who would know for sure.

**Comment by ThierryIT** [comment]
I have a colleague who is using his personal key with an offline master too ... 
He is under Linux ... I have asked him how did he do ... 
Thx

**Comment by junderw** [comment]
Did you ise the fingerprint of the subkey or the fingerprint of the master key?

**Comment by ThierryIT** [comment]
From subkey:

I have first revoke my keybase pgp key.
And:

C:\Users\tst\AppData\Local\Keybase>keybase pgp select 4B084B7D2345540C82E493702FA49B909E26E4B6
- ERROR GPG error: exit status 2

C:\Users\tst\AppData\Local\Keybase>keybase pgp select 4B084B7D2345540C82E493702FA49B909E26E4B6 --multi
- ERROR GPG error: exit status 2

C:\Users\tst\AppData\Local\Keybase>keybase pgp select 4B084B7D2345540C82E493702FA49B909E26E4B6 --no-import
- ERROR GPG error: exit status 2

I have forgotten to tell you that I have moved my personal subkeys to my Yubico key.
So it might be a problem ...
What I am going to do, is to create a new Keybase account with my second personal pgp key (no offline master key, no Yubico key) and try to do it ....

Thx

**Comment by ThierryIT** [comment]
Working with my second pgp key.

**Comment by junderw** [comment]
Yeah... yubikeys and offline keys don’t play well with keybase.

**Comment by zapu** [comment]
@ThierryIT can you try the failing `pgp select` commands again and do `keybase log send` ?

Importing a key with offline master key should work. Yubikey was tested as well but maybe there are other bugs. Thanks in advance!

**Comment by ThierryIT** [comment]
ID: 1cbcd667e9190f3586dc7b1c
Thx

**Comment by linux-modder** [comment]
yubikeys DO work with kb, you just need to use gpg-agent and yubikey ( I have same thing with gpg-agent -- ssh ( on fedora linux tho)

**Comment by ThierryIT** [comment]
Any news ?
Thx

**Comment by johntdyer** [comment]
@linux-modder  you said

> yubikeys DO work with kb, you just need to use gpg-agent and yubikey ( I have same thing with gpg-agent -- ssh ( on fedora linux tho)

but I dont see any details on what exactly this means, and how we can implement this "fix" ?  Details would be appreciated 

-John

**Comment by RiFi2k** [comment]
Just got this to work while using subkeys on Fedora 27 as described [here](https://alexcabal.com/creating-the-perfect-gpg-keypair/)
After following the standard steps for subkeys what you need to do is
`gpg --export-secret-key --armor > secret`
(also you can mount in memory and export to there if it makes you feel better)
`cat secret | keybase pgp import`
Enter your secret key passphrase when the prompt pops up, then you should be good to go

**Comment by ThierryIT** [comment]
Heu ... Seems that you need to use your master key ... 
Mine is offline and it seems to be a problem.

**Comment by linux-modder** [comment]
@ThierryIT offline as in the pure sense or a hardware token meaning offline?

If you use:

```
gpg edit-key {keyid} 
toggle 
gpg --export-secret-key --armor >  secret 
cat secret | keybase pgp import  
```

A Master key IS NOT needed.

**Comment by ThierryIT** [comment]
I have followed this link: https://intelligentsysadmin.wordpress.com/2018/02/27/keybase-and-gnupg-and-yubikey-oh-my/

And it is working !!

**Comment by Aiosa** [comment]
I would like to pinpoint that `keybase pgp select --no-import` no longer works...

**Comment by zapu** [comment]
Hey @Aiosa i'll be happy to look but can you bring me up to speed on what exactly are you trying to do and the steps that fail? Thanks

**Comment by Aiosa** [comment]
Hello, well I just tried to upload my public key to keybase from PGP, while having the private parts stored on a smartcard. I was unable to import them because the private part was -obviously- missing. So I was looking for a solution because the keybase app could not see my keys.  I came across this command, but it was outdated. Thus I just clarified the discussion for possible future explorers.

Finally I got `keybase pgp select` working after successfully issuing `gpg --list-secret-keys` -- it seems the keys were invisible even to PGP client so I had to replug the card. Seems keybase no longer requires a private key part to be present.
You could help me how to use the private key though. PGP can see my private keys but keybase fails with "no secret keys awailable" error. I am aware this question is out of topic though :(

**Comment by zapu** [comment]
Glad you managed to get your key selected.

The way things work right now, you won't be able to use the private key, though. Keybase client is not able to communicate with the smart card to do PGP operations. What's preferred here is to use Keybase as a key directory, so people can discover your key or send you messages, but use gpg to decrypt or sign.
