### ISSUE TITLE
very annoying notices every time i run keybase

### ISSUE THREAD

**Issue by zacheryph** [keybase/client#8612]
I cannot even login without getting the following. Afterward EVERY single time i run the command i get the same notice. I want to wipe my account to use a new GPG key and reset my graph and everything. I have now attempted to multiple times and just get annoying output every time. The best part is reusing device names isn't allowed but there is also no way to see device names previously used. So even though I am using the same device, due to wiping my account multiple times I will see "devicenameSOME_RANDOM_NUMBER". This makes NO sense to me.  I want to make my laptop "xps" cause thats what it is. not "xps3".  Please just WIPE any and all old devices/keys/signatures/etc from my account. 

> see how annoying running `keybase` is, EVERY TIME

```
➜  ~  keybase login 
Your keybase username or email address: zacheryph
▶ NOTICE Failed to parse public key at position 12 [tags:LU=rj0MYSo0_gQB]
▶ INFO Error verifying subchain from 38: Sigchain specified that KID 01011ccb2b9778ba0ffcaee27a16e1297daec40dfa3d36512396328a9a26b3f9b5c10a is a PGP key with hash e6d509fa9e676be2c8fc8450ad320868f8f0822b33ba2eb00e2ce6396239ec22 but no version of the key with that hash was found [tags:LU=rj0MYSo0_gQB]
```

**Comment by zacheryph** [comment]
At the very least `Reset your keys & start from scratch` needs to be reworded to "hide your current stuff so it cant be used again"

Disallowing device names and/or reusing a key causing error messages every execution is hardly "starting from scratch"

**Comment by maxtaco** [comment]
thanks for the report!  this is a problem, we'll take a look right away

**Comment by maxtaco** [comment]
I can repro with `keybase id zacheryph`. We'll try to fix it ASAP.

**Comment by maxtaco** [comment]
https://keybase.io/docs/teams/puk

**Comment by maxtaco** [comment]
Closed in #8652. It'll be fixed in the next release. Though it's just, at this point, a harmless warning.

**Comment by zacheryph** [comment]
OK. Apologize. I overreacted a little bit.  There is probably no chance of removing entries that were there are there?

**Comment by maxtaco** [comment]
I don't think there's a need to do that. The bug in #8652 allows all users to parse that bad key in your sigchain.  So the entry will act like a normal entry.

**Comment by zacheryph** [comment]
I was thinking of the xps* entries that existed for 5 minutes but i will just use a different name. Thank you.
