### ISSUE TITLE
Dark colour scheme

### ISSUE THREAD

**Issue by meejah** [keybase/client#8621]
It would be really nice if there was a "dark" variant of the colour scheme for users with generally dark colours in their workspace.

Thanks!

**Comment by afiskon** [comment]
:+1:

**Comment by cadox8** [comment]
It would be great 💜

**Comment by yohanboniface** [comment]
Dup of #10016 (more activity in there it seems)

**Comment by glyph** [comment]
Please do this!  In addition to being necessary now to match with dark mode in [macOS](https://support.apple.com/en-us/HT208976) and [windows](https://support.microsoft.com/en-us/help/4043948/windows-10-whats-new-in-recent-updates#section-2), [it's an accessibility issue](http://www.cgpgrey.com/blog/dark-mode-as-accessibility-feature).

**Comment by livejamie** [comment]
I'd be happy to contribute

**Comment by heronhaye** [comment]
Dark mode released in Keybase 4.6.0 under Settings->Display->Appearance.
