### ISSUE TITLE
Ohter prove than IT relative ?

### ISSUE THREAD

**Issue by ThierryIT** [keybase/client#8634]
Hi,
I have just create a new account for my wife.
And I had a revelation ... How people who have nothing to do with the IT environment can prove their ID through IT relating things like: Reddit, Github Hacker news ... ??
Why not add other possibility like Linkedin ??
Today my wife doesn't have any facebook, twitter, reddit, Github ... account. And if I did understand well, if there is no prove of ID, the user is notr able to share his public folder (as exemple)??
Thx

**Comment by ThierryIT** [comment]
No reaction ?

**Comment by dabura667** [comment]
You can share folders without any proofs.
