### ISSUE TITLE
Keybase hardly working as non-admin.

### ISSUE THREAD

**Issue by ringods** [keybase/client#8635]
So far, I have continuously errors with Keybase when running it under a regular (so non-admin) account.

my log id: 18e02e07c3848e0a7a2fe01c

**Comment by ThierryIT** [comment]
under windows ?

**Comment by ringods** [comment]
MacOS X 10.12.6

**Comment by ThierryIT** [comment]
Seems to be a problem for people who are not working as admin on their pc ... But I am newbie with Keybase.

**Comment by strib** [comment]
Hi @ringods, can you please be more specific about what "hardly working" means?  In your logs, it looks like Keybase is shut down.

Note that if this is a new install, the FUSE driver is not installed by default.  To install, you have to go to the Folders tab in the Keybase GUI.  You'll need the root password to install it.

**Comment by ringods** [comment]
@strib I have followed the uninstall steps from #4226 clean my setup first. I reinstalled Keybase completely and now it seems the kbfuse file system in the Finder seems to work correctly for my non-admin account.
