### ISSUE TITLE
DNS Proof 

### ISSUE THREAD

**Issue by originell** [keybase/client#8678]
My keybase: https://keybase.io/luisnell

I'm trying to proof a domain I own (originell.org). The process fails. Here's the `dig` output though:

```
❯ dig -t txt originell.org

; <<>> DiG 9.8.3-P1 <<>> -t txt originell.org
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 32744
;; flags: qr rd ra; QUERY: 1, ANSWER: 2, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;originell.org.			IN	TXT

;; ANSWER SECTION:
originell.org.		63627	IN	TXT	"keybase-site-verification=8rwCaPwwo3LunpjK4zR4LM0wwse2h4v8S3F4Lzs-PmE"
originell.org.		63627	IN	TXT	"v=spf1"

;; Query time: 67 msec
;; SERVER: 8.8.8.8#53(8.8.8.8)
;; WHEN: Wed Sep 27 15:08:47 2017
;; MSG SIZE  rcvd: 132
```

The `keybase-site-verification` is in there. 

Not entirely sure, but could this have something to do with my site not being online?

**Comment by maxtaco** [comment]
you have a very long TTL.  our servers might have  a cached copy and might not have to reload until 63627s from now

**Comment by originell** [comment]
Nice catch! However, I set that more than 17 hours ago. Should be about 25 hours now.

Nevertheless, if the entry looks correct to you, I might just wait another day.

**Comment by RowanKaag** [comment]
I'm having the same issue, however my TTL should be sufficiently lower.

# dig txt @8.8.8.8 _keybase.rowankaag.nl

; <<>> DiG 9.8.3-P1 <<>> txt @8.8.8.8 _keybase.rowankaag.nl
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 55833
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;_keybase.rowankaag.nl.		IN	TXT

;; ANSWER SECTION:
_keybase.rowankaag.nl.	149	IN	TXT	"keybase-site-verification=sw9fmRiPrnu8hYP7cOsVE4PRrJpi5sLTTbdI1wLjqgM"

;; Query time: 58 msec
;; SERVER: 8.8.8.8#53(8.8.8.8)
;; WHEN: Sat Oct 21 18:08:11 2017
;; MSG SIZE  rcvd: 121

**Comment by originell** [comment]
Note: I think my mistake was not specifying it for `_keybase.originell.org.` .. Total overlooked that part. Trying again. :)

**Comment by RowanKaag** [comment]
p.s. iOS app says "verified", while macOS app says "DNS unreachable". Both behind the same network, firewall, etc.

**Comment by originell** [comment]
update from my side: now that I specified the TXT record for `_keybase`, the verification worked. I was too stupid haha

**Comment by RowanKaag** [comment]
Mine is working now as well, did update to "Version 1.0.34-20171027003854+8e989533a" though.

**Comment by originell** [comment]
then i guess we can close this :)
