### ISSUE TITLE
Is it not possible to setup new device without accessing other devices?

### ISSUE THREAD

**Issue by hersh-verthun** [keybase/client#8722]
I signed up for keybase using my **home computer** a few days ago and added Github handle to the keybase account.  After that I did not provision any other device to my keybase account. Last night I wiped the **Home Computer** OS drive and did a fresh install of the operating system. I realized later that I had lost access to the only device that was linked to my keybase account.

On launching the keybase app on this fresh install of OS, I was prompted to enter my keybase username. I remember my keybase username and entered it successfully. Next I was asked to choose a device to connect with, showing me the **Home Computer** I originally linked with my keybase account.  This is where I get stuck because this **Home Computer** does not exist now. I have attached a screenshot of this window.

![screenshot_keybase_window_prompting_device_to_connect](https://user-images.githubusercontent.com/22866232/31040315-8587e54a-a575-11e7-951b-985f91a94c4e.png)

Please advise what I should do to link my fresh installation to keybase account.

**Comment by dabura667** [comment]
login via web UI and revoke all keys.

You will have to re-confirm your github.

**Comment by hersh-verthun** [comment]
@dabura667 I setup a team on keybase when I signed up. Would revoking keys mean I'd lose access to that team-id as well?

**Comment by dabura667** [comment]
I don't know.

But it doesn't matter, since you don't have the key and can't recover the key, so even if you decided "I don't want to revoke the key because it would leave me locked out of my team" you still don't have the key, so you can't access your team now, anyways.

**Comment by hersh-verthun** [comment]
When I signed up I was given a passphrase, I have that with me. That doesn't help?

**Comment by dabura667** [comment]
nope

**Comment by hersh-verthun** [comment]
I have to say, docs are really bad. I am very confused, this is very unlike other identity services. There is always some way to gain access to one's account.

**Comment by dabura667** [comment]
> I have to say, docs are really bad.

I agree

> I am very confused, this is very unlike other identity services.

That is true. The goal is to do something no other identity service does. Keybase is completely trustless.

> There is always some way to gain access to one's account.

Which means that someone is always holding a master key... Keybase does not require trust because they have no master key.

**Comment by hersh-verthun** [comment]
> Keybase is completely trustless.

sounds heartless too.  I appreciate the sincerity of developers to keep Keybase incorruptible but I'd appreciate them even more if there was some warning on the homepage for all the ways a user could lose access to their account.
