### ISSUE TITLE
Request: disable message preview in notifications, conversation lists

### ISSUE THREAD

**Issue by gwilym** [keybase/client#8731]
For situations where you're sharing or presenting your screen, or just working in any space where your screen can be glanced by others, it would be nice to disable message previews in conversation lists and desktop notifications, while still retaining the ability to be notified of some activity ("new message in ..." without a preview of the message). Especially since the targeted usage for keybase is for potentially sensitive messages, and showing a preview of it could be a security/privacy hazard.

Specifically, I'm on OSX.

**Comment by smcquay** [comment]
I need to be able to not have message contents show up until I bring the messages to the foreground. I have currently resorted to changing the alert type to "None" in System Preferences > Notifications > Keybase.

![image](https://user-images.githubusercontent.com/333234/41945872-4626e8b0-7964-11e8-96a8-7b5a728c3e1f.png)

**Comment by joshblum** [comment]
closed via #17337
