### ISSUE TITLE
Keybase Reddit verification is not working

### ISSUE THREAD

**Issue by netzkobold** [keybase/client#8786]
I followed all instructions (logged in and posted without changes) but Keybase keeps saying

> "We've been checking it repeatedly, and from our perspective, it's either (a) not there, or (b) not posted precisely." 

But it's there just fine.

**Comment by esilva-everbridge** [comment]
I am seeing this as well.

**Comment by netzkobold** [comment]
Can anybody from Keybase acknowledge the issue or suggest a fix? This is still occurring as of now.

**Comment by strib** [comment]
You might be shadowbanned.  Try http://nullprogram.com/am-i-shadowbanned/.

**Comment by netzkobold** [comment]
@strib thanks, I am, that's helpful information, I had to look up what that even is, now I can go through "It's difficult. It's really, really, really, really difficult." process of getting un-shadowbanned
