### ISSUE TITLE
Can't access team after todays update macOS Sierra 10.12.6

### ISSUE THREAD

**Issue by 0xff7** [keybase/client#8798]
I installed the keybase update today and now I can't access my team. When I try and connect through the mac app it gets stuck on "securing" for a little then disconnects and says "EOF from server"

Here is the error log
`ofError at s.t.Dispatch.n._dispatch_reset (file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/index.bundle.js:6:250333) at e.close (file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/index.bundle.js:6:236086) at s.t.Transport.n._close (file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/index.bundle.js:6:239595) at s.t.Transport.n._handle_close (file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/index.bundle.js:6:239998) at Socket.<anonymous> (file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/index.bundle.js:6:240398) at emitOne (events.js:101:20) at Socket.emit (events.js:191:7) at Pipe._handle.close [as _onclose] (net.js:510:12)`

**Comment by maxtaco** [comment]
Thanks, and sorry for the bug. Can you try a restart of the OS? Sorry about that.

Also, a `keybase log send` will help us debug.

**Comment by 0xff7** [comment]
@maxtaco Any ideas if theres something I need to do on my end or if it is in fact a bug?

**Comment by patrickxb** [comment]
@0xff7 it's an actual bug, fixing it now.  Thanks for the report and the log.

**Comment by patrickxb** [comment]
@0xff7 could you try the following?

1. `keybase db nuke`
2. quit keybase app from the menubar widget and then launch Keybase again
3. try to access your team

We think there might be some stale data in your disk cache.  

Despite its warnings, `keybase db nuke` is safe and is just removing the disk cache.  Quitting the app and restarting it just makes sure you're starting with fresh caches.

Thank you!

**Comment by 0xff7** [comment]
@patrickxb clearing the cache worked. Thanks for helping me resolve this and keep up the great work!

**Comment by patrickxb** [comment]
Great, thanks for reporting the bug!
