### ISSUE TITLE
Cannot add new team member

### ISSUE THREAD

**Issue by skozin** [keybase/client#8800]
Keybase GUI Version: 1.0.32-20171002191217+341a3c38c

I tried to add a new team member:

```
$ keybase team add-member team_name --user=member_name --role=writer
Pending! Keybase stored a team invitation for member_name. When they open the Keybase app, their account will be upgraded and you will be notified.
```

But, when they opened their Keybase app, they saw no invite. And no invite in their email. I tried to resend the invite by running the command above again, but got error `An invite for this user already exists`.

Then I tried to remove this member from the team in order to add them again, but got another error:

```
$ keybase team remove-member -u member_name team_name
Are you sure? [y/N] y
▶ ERROR invite required for username
```

The person I'm trying to add tried to request access to the team. I've got the email saying that access was requested, and I should run `keybase team add-member` to fulfill the request. But, as I've shown above, this command fails saying that invite already exists.

I have tried to add them as a `reader` and `admin` with the same error. Trying to add them as an `owner` resulted in another error:

```
▶ ERROR We are sorry, you have hit a bug! The user you are inviting (kadmil) hasn't logged into
Keybase for a while and needs to upgrade their account. Until they do, you can only add them to this team
as an admin, reader or writer. So you have three options: (1) wait until kadmil upgrades;
(2) wait until all Keybase users get the fixed app (by 2017-11-07); or (3) add kadmil as an admin (or reader or writer)
```

But they have logged in just before that after logging out (we tried this multiple times, on desktop, mobile and web).

What else can I try?

**Comment by maxtaco** [comment]
Thanks for this detailed report. We've fixed almost all of these bugs in master, but we have to wait for rollouts and release, etc.

The underlying bug --- that the user you're trying to add hasn't upgraded --- has also been fixed with a server bug.  So this issue should just work itself out on its own without any effort on your part.

**Comment by skozin** [comment]
Thanks for the prompt response! Approximately, how long should we wait, i.e. when I should update this issue if it's still not fixed?

**Comment by maxtaco** [comment]
Seems like his account just got upgraded, and he should have been auto-added into the team.

**Comment by maxtaco** [comment]
(And it also appears that he's now in the team, lmk if not...)

**Comment by skozin** [comment]
Thanks a lot, I'll check with him. I see him in the team, just want to make sure he has access to the chat. Anyway, closing this as, even if he doesn't, it would be another issue :)

Thanks a lot for your help!
