### ISSUE TITLE
Issue with GIthub Desktop / Keybase on Windows 10 Insiders RS4

### ISSUE THREAD

**Issue by johnturek** [keybase/client#8804]
Greetings,

@malgorithms mentioned on Reddit to have me post my log here.    I am trying to clone a new empty repo called "Test"  

![capture](https://user-images.githubusercontent.com/53944/31190307-bd4ec700-a908-11e7-88e2-175182bea3b6.JPG)

Test is a fresh repo and did not already exist. 

I am not sure if its a Keybase issue or GitHub Desktop

my log id: 9088949e3e4cad26e391a71c

**Comment by maxtaco** [comment]
It seems like there's something already at `C:\Users\JohnV\Documents\Test`?  Maybe try `C:\Users\JohnV\Documents\Test2`

**Comment by johnturek** [comment]
Thank you @maxtaco.   I was able to get past that screen by utilizing `c:\Test`  but now I am getting this error:
<pre>
Cloning into 'C:\Test'...
git: 'remote-keubase' is not a git command. See 'git --help'.

The most similar command is
	remote-keybase
Error(s) during clone:
git clone failed: exit status 128
</pre>

**Comment by strib** [comment]
@johnturek: looks like you mistyped "keybase://" as "keubase://"?

**Comment by johnturek** [comment]
Nevermind!  Problem existed between keyboard and chair.. I am sorry @strib and @maxtaco.  Thanks for all your work!
