### ISSUE TITLE
git-remote-keybase error pushing to Keybase repo

### ISSUE THREAD

**Issue by CraigCottingham** [keybase/client#8812]
I have an existing Git repository that I've been using for a while. I created an encrypted repo (call it "foo") in the app, added a remote for it to `.git/config` like so:

```
[remote "keybase"]
        url = keybase://private/craigcottingham/foo
        fetch = +refs/heads/*:refs/remotes/keybase/*
```

Now, when I try to push to it, I get

```
$ git push keybase master
Initializing Keybase... done.
Syncing with Keybase... done.
git-remote-keybase error: (1) 15:8: unquoted '\' must be followed by new line
error: failed to push some refs to 'keybase://private/craigcottingham/foo'
```

Unfortunately, that's all the error I see.

OS: macOS Sierra 10.12.6
git: 2.14.2

**Comment by strib** [comment]
@CraigCottingham: hrm, that's no fun, thanks for the report.  Can you please do a `keybase log send` and let us know the resulting ID?

**Comment by strib** [comment]
Can't repro locally.  By the way, I saw this early in developing git-remote-keybase, but only on Windows, where there are backslashes in the filenames, and we added some fixes for that.  I'm curious if your local git checkout, from where you're doing the push, somehow has a backslash in its path, or some other interesting character (like a space, for example).

**Comment by CraigCottingham** [comment]
`keybase log send` ID: b7edb1b4c647931c7666201c

The path to this local checkout has no unusual characters in it: `/Users/craigc/Projects/trademark-free-naval-warfare`

**Comment by strib** [comment]
The user found backlashes, generated by Tower, in one of his local git config files, that it causing `git-remote-keybase` to blow up.  We'll work on a fix.

**Comment by strib** [comment]
I just merged a commit that should fix this in the next release.  Sorry for the bad experience!
