### ISSUE TITLE
Is it possible to selectively encrypt: only a subset of files

### ISSUE THREAD

**Issue by yogiben** [keybase/client#8838]
We're using [GitCrypt](https://github.com/AGWA/git-crypt).

It lets you specify what files should be encrypted. This is useful because you can still view PRs in the web GUI (unencrypted files) but encrypt sensitive info like environment variables.

Is this functionality possible? I couldn't see it in the readme.

**Comment by strib** [comment]
No, sorry, it's all or nothing.  We encrypt at the storage layer, not at individual files.  Because of that, we will probably never be able to support showing data on a website.  Though someday we might implement a PR view in our client.
