### ISSUE TITLE
Extra Files

### ISSUE THREAD

**Issue by jakebasile** [keybase/client#8859]
I'm seeing extra files on the KBFS drive. They all seem to be duplicates of true files prepended with '._', but the contents of the duplicate files isn't the same.

For example, I have a picture of me in a dashing fedora at `K:\public\jakebasile\fedora.jpg` or `/keybase/jakebasile/public/fedora.jpg`, but there is also an extra file at `K:\public\jakebasile\._fedora.jpg` or `/keybase/jakebasile/public/._fedora.jpg`

These files were added from macOS Sierra and the duplicates show on both macOS Sierra and Windows 10. They do not show up at keybase.pub/jakebasile. 

my log id: 6458cda7f0e420f5548b631c

**Comment by jzila** [comment]
macOS creates these metadata files when you browse in Finder. They don't have anything to do with Keybase.
