### ISSUE TITLE
Breaks ssh

### ISSUE THREAD

**Issue by pquodling** [keybase/client#8863]
running on an Imac (will test soon with MBP) running High Sierra - Keybase installed via Homebrew, and am running Iterm2 that fires up tmux. 

previously I could log into a remote server (passwordless) with an ssh myname@thenodeid.

This now returns 

Unable to negotiate with 2001:yyy:xxxx::4 port 22: no matching cipher found. Their offer: aes128-cbc,3des-cbc,twofish128-cbc,cast128-cbc,twofish-cbc,blowfish-cbc,aes192-cbc,aes256-cbc,twofish192-cbc,twofish256-cbc,arcfour,des-cbc@ssh.com,rc2-cbc@ssh.com
 (the xxxx and yyy are to anonymize the IP address. 

Most of the setup for this mode of operation is in ./ssh/config and it is still there and hasn't changed. 

ideas?

**Comment by maxtaco** [comment]
I'm pretty sure this is unrelated to keybase.

**Comment by pquodling** [comment]
Indeed - a Cipher line in the ssh config file fixed it

**Comment by sskras** [comment]
@pquodling , I am getting the same output.  Out of curiousity: what cipher name(s) did you put into ssh config, please?
