### ISSUE TITLE
White screen on Linux when clicking the Git button

### ISSUE THREAD

**Issue by MakotoTheKnight** [keybase/client#8864]
I'm attempting to use the encrypted Git feature and am seeing a white screen come up in the client instead.

my log id: 27548d96c958cf57ac380f1c

**Comment by dakira** [comment]
Keybase GUI Version: 1.0.34-20171006000413+5fe91ae13

**Comment by maxtaco** [comment]
We will investigate first thing.  Can you do a ‘keybase log send’ ?

**Comment by dakira** [comment]
Log ID: 52e5f51f980733162205cd1c

**Comment by maxtaco** [comment]
Thanks. Cc @oconnor663

**Comment by maxtaco** [comment]
Dupe of #8872 and now fixed in master

**Comment by oconnor663** [comment]
(fix should be out already if you upgrade to latest)

**Comment by dakira** [comment]
Confirming fix.

**Comment by MakotoTheKnight** [comment]
I am confirming the fix as well.
