### ISSUE TITLE
terminal keybase prove twitter - nil pointer exception 

### ISSUE THREAD

**Issue by TheLeftMoose** [keybase/client#8867]
keybase prove twitter is written on your page for installing client on linux. Bu
t it gets a runtime error and throughs an nil pointer exeption

my log id: f2ec9e10fe8ec271aee4aa1c

**Comment by maxtaco** [comment]
Thanks for the report, it is likely due to a big refactor I committed yesterday.  I will check it out first thing.

**Comment by maxtaco** [comment]
Fixed in #8868.  Sorry for the bug an thanks for the bug report. Should go out with a fix today.
