### ISSUE TITLE
blank window on selecting Git tab

### ISSUE THREAD

**Issue by geiziry** [keybase/client#8877]
I just installed keybase on ubuntu 17.04, and on selecting the Git tab I got a blank screen.
I rebooted the pc and tried again, and still getting the same blank window

my log id: 71bfa9f968e63559f499e51c

**Comment by maxtaco** [comment]
Sorry, known bug that we just rolled a fix for. Can you see if there's an update ready?

**Comment by bmellstrom** [comment]
I had the same problem; seems to be fixed after upgrade!

**Comment by geiziry** [comment]
updated, and it's fixed

thanks alot
