### ISSUE TITLE
Install Error After Updating to macOS High Sierra

### ISSUE THREAD

**Issue by craigwatson** [keybase/client#8888]
Error message:

> We were unable to load KBFS (Fuse kext). This may be due to a limitation in MacOS where there aren't any device slots available. Device slots can be taken up by apps such as VMWare, VirtualBox, anti-virus programs, VPN programs and Intel HAXM.
>
> Please run `keybase log send` to report the error.

my log id: d7f49f1cef6f38ee161a8e1c

**Comment by maxtaco** [comment]
thanks.  Did you click "ignore" or "quit"?

**Comment by craigwatson** [comment]
@maxtaco I've tried both, clicking "ignore" will allow the UI to load but `/keybase` is empty.

**Comment by maxtaco** [comment]
ok, great.  Well that's working as intended.  Are you indeed running any of those programs listed? VMWare, VirtualBox, etc?

**Comment by craigwatson** [comment]
I do have VirtualBox and TunnelBlick installed, but no VMs running or VPN tunnels active.

**Comment by maxtaco** [comment]
Yeah it probably doesn't matter, i think they swoop in in front of keybase and grab the KEXT slots.  There's not much more we can do.

**Comment by maxtaco** [comment]
cc: @cjb / @chrisnojima, not sure if there is any mitigations we have up our sleeves.

**Comment by craigwatson** [comment]
A reboot seems to have cleared it (duh, should have tried that!) - a useful improvement would be to display some kind of info about what other devices are holding the slots, but I guess it's a race for the Kext slots.

Will close for now, thanks!

**Comment by maxtaco** [comment]
Ah good to know, thanks!

**Comment by phonetrips** [comment]
I am getting that same error message when Keybase starts and I do not run any VM or VPN software. I do have Sophos antivirus so I will try stopping that to see if it makes a difference.

But my real question is that the error message tells me: "Please run `keybase log send` to report the error." I have no idea where to do that. I can't find that function in any menu and I can't find a Keybase command prompt to type that.

**Comment by danielbressan** [comment]
I am also getting this error. I have restarted mult times and every time I restart and keybase starts up, I see this error. I have nothing mounted and have no VMs installed. I believe it's what stopping me from accessing keybase files from finder. Anyone still around on this post to help?

**Comment by maxtaco** [comment]
@strib sometimes has a suggestion or two

**Comment by strib** [comment]
@danielbressan please do a `keybase log send` and post the resulting log ID.  I'd prefer a new github issue if you can, this one is closed.
