### ISSUE TITLE
Feature request - Add Gab.ai for proofs

### ISSUE THREAD

**Issue by legostax** [keybase/client#8904]
I don't know what else needs to be said.  I'd like to be able to use my https://gab.ai account for a proof.
I really appreciate Keybase and the work being done it!

**Comment by nathanchere** [comment]
https://github.com/keybase/keybase-issues/issues/2692

**Comment by legostax** [comment]
Whoops, the issue you referenced didn't come up in my search originally when I made this one...weird.  Closing in favor of keybase/keybase-issues#2692
