### ISSUE TITLE
Cannot start gui or cli client

### ISSUE THREAD

**Issue by spion06** [keybase/client#8932]
I cannot start the GUI or cli client for keybase. Looking at the output of `keybase ctl start` makes me think it's an issue with how it's finding the keybase CLI client potentially. 

my log id: c00a4747b1333835b5c3831c
5c56d46df64c3ecd89f02e1c

```
$ keybase ctl start
▶ INFO Saving /Users/km022926/Library/LaunchAgents/keybase.service.plist
▶ INFO Starting keybase.service
▶ INFO Waiting for keybase.service to be loaded...
▶ ERROR Error installing Keybase service: keybase.service is not running
▶ ERROR keybase.service is not running
▶ ERROR stat /keybase: no such file or directory
▶ INFO Saving /Users/km022926/Library/LaunchAgents/keybase.updater.plist
▶ INFO Starting keybase.updater
▶ INFO Waiting for keybase.updater to be loaded...
▶ ERROR Error installing updater service: keybase.updater is not running
▶ ERROR keybase.updater is not running
▶ INFO Opening /Applications/Keybase.app
▶ ERROR There were multiple errors: keybase.service is not running; stat /keybase: no such file or directory; keybase.updater is not running
```

**Comment by maxtaco** [comment]
What are the permissions on `/Users/km022926/Library/LaunchAgents/`? 

Also, relatedly, do you run LastPass?

**Comment by spion06** [comment]
I run 1passoword but not lastpass. Permissions on LaunchAgents looks fine from what I can tell

```
$ ls -lh /Users/km022926/Library/ | grep LaunchAgents
drwx------    4 km022926  Domain Users   136B Oct  9 15:41 LaunchAgents
```

**Comment by maxtaco** [comment]
Yeah, it sure does. Do you see `keybase.service.plist` in that directory?

**Comment by spion06** [comment]
I do not

```
$ ls -lh /Users/km022926/Library/LaunchAgents/
total 16
-rw-r--r--  1 km022926  Domain Users   588B Aug 25  2016 net.tunnelblick.tunnelblick.LaunchAtLogin.plist
-rw-r--r--@ 1 km022926  Domain Users   677B Apr 18  2016 org.virtualbox.vboxwebsrv.plist
```

**Comment by maxtaco** [comment]
Yeah, that's our bug here, but damned if I can figure it out.  `launchctl` says it works, but then it noops. 

Do you think your mac is in a state where it wants to restart due to an OS upgrade?

**Comment by spion06** [comment]
actually i think it is. I can try giving it a restart and see if that does anything

**Comment by maxtaco** [comment]
I had a case like this where a restart "fixed" it.  Ug!

**Comment by spion06** [comment]
yeah. looks like a restart fixed it :( kinda strange/annoying but at least i know now!

**Comment by maxtaco** [comment]
thanks for your feedback. Sucks that the remediation is so unsatisfying. We'll continue to scratch our heads over here.
