### ISSUE TITLE
git remote helper and lfs support

### ISSUE THREAD

**Issue by apeyroux** [keybase/client#8936]
I want to use Git LFS with keybase remote helper but : 

```
Remote "keybase" does not support the LFS locking API. Consider disabling it with:
  $ git config lfs.keybase://private/apeyroux/docs.git/info/lfs.locksverify false
```

Do you plan to add git lfs support?

Regards

**Comment by strib** [comment]
Thanks for the suggestion.  We looked into it already, and found that the LFS protocol can only run over HTTPS.  Unfortunately for us, that would require running a server on a port on localhost, which is a non-starter on some platforms (like Linux) due to local firewall restrictions.  Maybe we'll revisit this someday or work with the LFS team on tweaking the protocol, but for now I don't see how it can work in a cross-platform way.

**Comment by AngryAnt** [comment]
@strib What sort of priority does this revisit have? I realise that *your* team probably doesn't rely on a lot of large binary files versioned, but that obviously doesn't necessarily hold true for your community.

**Comment by strib** [comment]
Again, it's not about how our team uses git.  It's about the fact that to support LFS, we have to run an HTTPS server.  However, since I wrote the above, we've actually made some progress on that, not for git but for other stuff.

cc: @jzila @songgao I wonder if we can use the existing file server for LFS somehow.

**Comment by AngryAnt** [comment]
Apologies. I did not mean to imply that the git usage patterns of your team informs technical issues - just that it could very naturally affect awareness of the problem.

Like many others, I would be very curious about this progress you mention and, if applicable, any advice allowing us to connect dots in order to arrive at a functional LFS/-like setup for teams.

**Comment by jzila** [comment]
@strib @songgao I'll make an internal ticket to investigate.

**Comment by brenthuisman** [comment]
Has there been progress on this issue?

**Comment by jzila** [comment]
We've investigated and have it on our list. But it's relatively low priority right now.

**Comment by kav** [comment]
Worth noting you don't need an http server if you define a custom transfer type https://github.com/git-lfs/git-lfs/blob/master/docs/custom-transfers.md you get json via stdin. Might make this process significantly more straightforward. Also +1 to the issue in general

**Comment by hiradyazdan** [comment]
Is there any update on this yet?

**Comment by dukejones** [comment]
It looks like there is no hard requirement for a HTTP server with the `standalonetransferagent` config option.  Here is a simple example in go:

https://github.com/sinbad/lfs-folderstore

My go is really bad but I may take a crack at it. Something like:

1. keybase lfs install : adds config to local .git/config to use the local binary for keybase:// urls, and no API server.  [Think about concurrency option.]
2. keybase lfs : program listening on stdin for tus.io json commands.  
3. Parse the init message href, keybase://team/<teamname>/<reponame>  or keybase://private/<myname>/<reponame> and upload files to /keybase/team/<teamname>/git-lfs/<reponame>
4. Do the uploads, returning progress messages
5. Complete.

Similar with downloads.

.git/config something like:
```
[lfs "customtransfer.keybase"]
	path = keybase-lfs
[lfs]
	standalonetransferagent = keybase
```

**Comment by strib** [comment]
Thanks for putting in the legwork here!  This looks pretty promising; I didn't realize this option existed.  We'll look into it soon!

**Comment by AngryAnt** [comment]
[Everyone liked that]

**Comment by dukejones** [comment]
Thank for the encouragement!  I would love to have a decentralized storage workflow for managing asset versions for my project using LFS & keybase.

I have verified that my go is not at the level for me to make a substantive contribution here.  For the record here are the references I was using to develop:

https://github.com/git-lfs/git-lfs/blob/master/docs/custom-transfers.md

https://github.com/git-lfs/git-lfs/wiki/Troubleshooting

Many thanks!  I am continually impressed by keybase. Such amazing work.

**Comment by strib** [comment]
Good news everyone!  Using @dukejones's suggestion, the current master version of Keybase now supports LFS.  If you use the Linux [nightly build](https://keybase.io/docs/linux-user-guide#nightly-builds), you can try it out.  See some info on how to set it up at https://keybase.io/docs/git/index#support-for-git-lfs-large-file-storage- .

This has only been lightly tested, so let me know if you run into any issues.

If you're not running the Linux nightly build, you'll be able to try it out as of our next release, 5.1.0, out in a couple weeks.

**Comment by dideler** [comment]
It seems the LFS documentation has been removed from https://keybase.io/docs/git/index#support-for-git-lfs-large-file-storage-. Any idea where it's been moved to?

**Comment by nandalopes** [comment]
Run `keybase git lfs-config` from command line. This will add the following settings on your `git/config` file:

```
[lfs]
	standalonetransferagent = keybase-lfs
[lfs "customtransfer.keybase-lfs"]
	path = git-remote-keybase
	args = lfs origin <keybase remote url>
```

**Comment by yb66** [comment]
Hi @nandalopes,

My keybase remote is not named `origin` but `kb`.

Given that, is the `origin` in `args = lfs origin <keybase remote url>` the same as keybase's remote name, or is it to tell LFS that `<keybase remote url>` is the LFS origin?

I need to know whether to replace it with the actual remote name. I don't want to experiment, I've had enough LFS problems in my life to clear up! (o_º)

Regards,
iain

**Comment by ultrasound1372** [comment]
I have some git repositories that use LFS that I have privately on GitHub, but wanted to also mirror them to Keybase. I created repos for them in Keybase, did lfs-config, and added the new remote to my existing repos named keybase. I then execute git push keybase. It says it's uploading, but it takes quite a long time and in the process uses all 16 GB of my available RAM and then swaps so much that virtual memory is up to 36 GB. For reference these repos are no bigger than 2 GB. I checked task manager and saw that for a single push operation there are multiple instances of git-remote-keybase.exe running, each of which is using up to gigabytes of RAM. What is happening here?

**Comment by jw4466261** [comment]
https://assetvest.org company is a changing situation in the world economy and financial markets. They ensure that the returns are satisfactory and 100% risk free. predominantly, Assetvest company has been the strong proponent investment strategies for natural resources, stock market and cryptocurrency investment program where investors make daily profits using the ROI (Return on investment) they have stabilized an efficient trading strategy to ensure maximum profit on real stocks, natural resources and Cryptocurrency investments.from what you've invested in the company and they also offer 2.25%-1.77% transfer commission with a minimum deposit of $ 100, The maximum deposit on their investment section (plan)depends on the investment category you are investing on. Their tier is unlimited as the company has multiple investment plans that work well and each of the investment plans has it own percentage offer. Their withdrawal are fast to any external wallet. meaning that after 3days of your investment, you can choose to withdraw both your capital and daily profits. You can even increase your investment by reloading your investment plan, making a new deposit or requesting a new withdrawal limit, you can choose to make a deposit as many times a day or at any time of your choosing as soon as you're liquid enough on your cash flow to make deposits. The same applies when prompted to do so, depending on the amount you have on your balance, you can withdraw at any time. The higher your investment, the faster the returns you will receive in return will grow. They're very stable and profitable. And also fast during the withdrawal on every withdrawal transaction.
