### ISSUE TITLE
Please Reset Private Folder

### ISSUE THREAD

**Issue by robbielamb** [keybase/client#8944]
I rebuilt my devices and revoked my paper key so I lost access to my private folder. I would like to play with the new git integration in my private folder /keybase/private/robbielamb. Thanks.

BEGIN KEYBASE SALTPACK SIGNED MESSAGE. kXR7VktZdyH7rvq v5weRa0zkOLKMAg 9ZztQnHWNTHKsr8 RX8nMfw3BJ6RGey P4xaHSO2US4qRaq ZCONUGAYx4ZZV4a GmHPqJdTfAEkpYo 4TiJhAjUUEZ1KqK SAM1OCECJllRiul iULUwYZfuPphQO9 iSqpXeVeyPx2ho5 HJYVFKt1QHo6NRh qL7aKdEEzla9r8e gh94t4uvnuIpWx7 KDHYfQAyu82tAVU Q0C8gOrdZy3YKNN GZdyNnvMJnlhiZ0 ZznRXIroUZyzM5R sGaboPzQpcwAwFX Q4UPTeiqyEJR01I P7hKFoQD17e9uB4 Hp5822YY82EOkqn SVPLuaFRH8wGUZ7 gPCS5GEXQs7wrqc hYFgo6FEokYHECC Z9LfQWXgb73uQQ9 rj0oGCn6N1PrJRD JWV07ujq3fHRZjL N25zNkFzXp9ZNRQ z8r8ZGZf1W. END KEYBASE SALTPACK SIGNED MESSAGE.

**Comment by strib** [comment]
Hi @robbielamb, I'm happy to reset your folder, but please include the current date and time in the message you sign over (to prevent someone from reusing this message in the future to impersonate you).  Thanks!

**Comment by robbielamb** [comment]
Let's try this.

I rebuilt my devices and revoked my paper key and lost access to my private folder. I would like to play with the new git integration in my private folder /keybase/private/robbielamb.

This message is timestamped at Wed Oct 11 00:42:40 UTC 2017.
BEGIN KEYBASE SALTPACK SIGNED MESSAGE. kXR7VktZdyH7rvq v5weRa0zkOLKMAg 9ZztQnHWNTHKsr8 RX8nMfw3BJ6RGey P4xaHSO2US5CulD czOBuuPFeiEK2VA GuLg9e0sdgdJicO c1MzOYOLpHrytr6 4W6Eo89zBR3tvDm fUWEyychfxgH4rq vreVHar6yTh1x6q gW6QoIgJKCHBMY6 lei0QLzpcme3Qbx 5JrA8e3VIARZCyO NZj9hNLY55p7foJ tBZI84Pxby15L6k NnJfzufpUkgTcZn fgeQeEObiiuRCmH C65bJMCqJrYVWuC N2f01BV8fVkJO1P UQfCpZTXXAhpuGI mLnIHm7qStnJIIT HbVxmmpTktRVw0Q erM762S3hDClh7r IZ3e2w385MmqG1R pJ7jjCLRywO7Q75 nIEcQU6wR5Zkd1S L7Lr1KbAtXVjedK QiVdOzHsJrQfCpZ TXXAiVSxQ3HVUkR 1KT3LkkfyhZoMdv EVATfFGzOW7kUml LA3Le7xlchWLrWS eovGZ3TuGyFFsEX Yjxp1U0P0G8nuPO THP8pGAKvwB682p C. END KEYBASE SALTPACK SIGNED MESSAGE.

**Comment by strib** [comment]
@robbielamb: I reset the folder.  Please check it out and close this if everything seems ok.  (Might require a Keybase restart.)

**Comment by robbielamb** [comment]
Looks good! Thanks.
