### ISSUE TITLE
Where is the data for KBFS (is this how I would do backups?)

### ISSUE THREAD

**Issue by SoreGums** [keybase/client#8947]
So would I be using 10GB of data eventually on a keybase.io server somewhere with KBFS?
My home internet has a whopping massive 0.3mbps connection - so "streaming" from my home computer via the internet to my phone while out and about is not going to work well.

If this is not a "sync" model how do I run backups?
Do I simply tar the folder and thus read every file thus forcing the data to come onto the computer doing the tar? Also where does this data come from? my home computer or a keybase.io server?

When does data show up for other endpoints, once keybase.io has a copy or what?

Cheers :)

I'm in the process of figuring out where to go to next as Dropbox & Google being able to hand over my data to anyone when they feel like it is not cool _(terms of service whatever, the data is accessible to them, they can do it - I don't mind if people hand over garbled unusable data dumps (encrypted data))_

**Comment by strib** [comment]
The data comes to your devices Keybase servers when you read a file for the first time, and after that we try to cache it locally as long as you have room on your hard drive, or until the file changes.  So if you `tar` in a directory you've never read before, it will indeed stream all the data from our servers.  The second time you do it, it should read all the unchanged data from the cache on your hard drive, whenever possible.

So yeah, the only way to do backups is just to copy or tar all the data out of the /keybase/private/whatever directory you care about.

Let me know if you have more questions.

**Comment by SoreGums** [comment]
and hello from 2019 - just googled "how to backup kbfs" and No.1 for me is this.

time to close - thanks for the info ;)
