### ISSUE TITLE
Files/folders not appearing in private folder

### ISSUE THREAD

**Issue by defnotryan** [keybase/client#8950]
I had Keybase installed on a Macbook Pro for months, and just recently installed it on two more devices (iPhone and then Macbook). Before I installed Keybase on my Macbook I wrote a test file to my private folder (`/keybase/defnotryan/private`), intending to check it later on my Macbook. When I installed Keybase on my Macbook it prompted me to Rekey the filesystem. I wasn't sure what that meant so I just clicked the buttons I thought it wanted me to. After that I verified that I could read the test file on my Macbook. Then I wrote a bunch (~800MB) of files to my private folder using my Macbook. The next day I tried to inspect the contents of my private folder on my Macbook Pro, and my private folder appeared empty in both Finder and terminal. If I try to write anything to my private folder I get "The operation can't be completed. An unexpected error occurred (error code -36)." Executing `touch test` in the folder yields an IO error. The Macbook, on the other hand, seems to be reading/writing the filesystem successfully.

Things I've tried:
- Exit Keybase and relaunch
- Reboot
- Googling for similar issues (not much luck--issue #2576 looked similar but resolution required intervention on your end so there was nothing for me to pursue)
- Signing out of Keybase and signing back in (this resulted in a funny state where my private folder disappeared completely from `/keybase/private`, until I quit Keybase and relaunched it)

Thanks for your help!

Keybase GUI Version: 1.0.33-20171003193446+d9ceb86ac

**Comment by defnotryan** [comment]
Log ID is 383d34677b6e8383390c511c

Thanks!

**Comment by strib** [comment]
Oof, looks like you might have hit the same bug as #8903, which led your folder to become unreachable.  (I could verify it for sure if you send logs from your Macbook as well.)

I tried to restore the root directory that your Macbook Pro is trying to access.  However, it's hard for me to know whether they will be other issues after that with unreadable files or subdirectories, or files that appear to be missing now.  Please check it out and let me know if anything else seems weird.

**Comment by defnotryan** [comment]
Thanks for your work on this.

I now see a directory that originated from the MBP but not a directory that originated from the MB.

I didn't have anything important in there--if it's simpler, feel free to reset it:

```
BEGIN KEYBASE SALTPACK SIGNED MESSAGE. kXR7VktZdyH7rvq v5weRa0zkGGn637 lcUhvadzmrABfpf XEOeOQxsvHGLjuF T2zNl5XeffYtrsG Kkq60Ys00SDJZbO qkqYMPyeyFJ0ucT Vbnbjl3uRzc9et0 RWawbvLlEyIHxbQ bw3MDw1KeJ7dK9v c7LzNPmLCYXot4L woGeP3DMcfyKoHe yDaIhcgCKfvrYab WQ8fwvEAUbG36N5 3lz1wJwpE12wdI0 0c9vek7BZtBrDQ1 LqLCg2GH0YNWDT4 WgzNKP0Ss2D3ic4 AgfQZ8Ujv2rXa6S auFjmRfIMLJGFuz IN1xTZdYO7kumGd 12yBCtQlYwN6JTz S4pKoYsQCBslyU0 To1G. END KEYBASE SALTPACK SIGNED MESSAGE.
```

**Comment by strib** [comment]
I reset the folder.  Please check it out and close this if everything seems ok.  (Might require a Keybase restart.)

Sorry you had such an epically bad experience. If this is the same bug as #8903, it will be fixed in the next release.

**Comment by defnotryan** [comment]
Looks back to normal; thanks!

No worries--I think Keybase is seriously cool, and I'm excited to see it develop and mature.
