### ISSUE TITLE
Install error (updater, service, kbfs)

### ISSUE THREAD

**Issue by paczkow** [keybase/client#8952]
OSX: I am able to copy the app into /Applications folder. However, when launching the app displays error/alert window with two option Quit and Ignore. The error states:

Keybase Install Error
There was an error trying to install the updater
There was an error trying to install the service
There was an error trying to install the kbfs

The end results is, I am unable to use Keybase.

my log id: 01b375d8f975adeac5eb981c

**Comment by maxtaco** [comment]
Can you run:

```
ls -lsa ~/Library
ls -lsa ~/Library/LaunchAgents
launchctl print-disabled system
```

And paste in the replies?

**Comment by paczkow** [comment]
Under letter K:

ls -lsa ~/Library:
[...]
 0 drwxr-xr-x    3 user1  staff     96 Oct 13  2016 Keyboard/
 0 drwx------+   2 user1  staff     64 Feb  5  2014 Keyboard Layouts/
 0 drwxr-xr-x    5 user1  staff    160 Sep 28  2016 KeyboardServices/
 0 drwxr-xr-x   13 user1  staff    416 Oct 10 10:06 Keychains/
[...]

ls -lsa ~/Library/LaunchAgents: 
empty

launchctl print-disabled system:
disabled services = {
	"com.apple.hdiejectd" => false
	"com.parallels.mobile.kextloader.launchdaemon" => false
	"com.metakine.handsoff.daemon" => false
	"com.apple.AppleFileServer" => true
	"com.apple.screensharing" => true
	"com.parallels.mobile.dispatcher.launchdaemon" => false
	"com.apple.ManagedClientAgent.enrollagent" => true
	"com.apple.mtmd" => false
	"com.apple.ftpd" => true
	"com.apple.rpmuxd" => false
	"com.apple.usbmuxd" => false
	"com.microsoft.office.licensing.helper" => false
	"com.apple.mrt" => false
	"com.apple.smbd" => true
	"com.apple.ManagedClient.enrollagent" => true
	"com.apple.mtmfs" => true
	"com.apple.stackshot" => false
	"com.apple.CalendarAgent" => false
	"org.apache.httpd" => true
	"org.net-snmp.snmpd" => true
	"com.apple.pacemaker" => true
	"com.apple.apsd" => false
	"org.macosforge.xquartz.privileged_startx" => false
}

What are you looking for in particular, Keybase services?

**Comment by maxtaco** [comment]
I would also like to see the permissions on the directory LaunchAgents
itself.

Thanks

**Comment by paczkow** [comment]
drwxr-xr-x    3 root  staff     96 Feb  5  2014 LaunchAgents/

Thanks Max.

**Comment by maxtaco** [comment]
Yeah, that's the problem, some other app shat on the permissions of that directory. If you:

```
chown $(USER):staff LaunchAgents
```

and start keybase again, it should work

**Comment by paczkow** [comment]
Thanks much. Worked. Your prompt help is much appreciated. Best!

**Comment by maxtaco** [comment]
No worries. We're going to work on automating this fix, but it's great to know that in your case it was the cause.  Thanks for your help

cc: @cjb and @chrisnojima

**Comment by paczkow** [comment]
I think the "fault" could have been some long time ago I set those permissions manually on purpose. Hard to track what this minuscule mind of mind decided to do in the past. Thanks.

**Comment by maxtaco** [comment]
Nah, it's hit enough different people that it's likely a misbehaving app that first escalates privileges and then twiddles with `launchd` as root.

**Comment by paczkow** [comment]
I concur. I have tested to chown back to root (revert to previous option), killall all Keybase processes, and relaunch. The error remains. This means the /Users/$(USER)/Library/LaunchAgents must be owned by the operating user.
