### ISSUE TITLE
git pull not working

### ISSUE THREAD

**Issue by jerodg** [keybase/client#8959]
I've a keybase git-repo with a couple folders,
If I delete one of those folders on the file-system and do a 'git pull' it claims everything is up to date.
 - If I do 'git diff' it shows all the files that were deleted
If I delete the whole thing and clone again I get all folders as expected.

**Comment by jyn514** [comment]
@jerodg that's not how git works. Your *remote* repo is up to date, but you haven't queued any changes to push. If you wanted to update the repository, use `git commit --all -m <message here> && git push`.
