### ISSUE TITLE
Keybase requires login to be created before accepting

### ISSUE THREAD

**Issue by oconnor0** [keybase/client#8971]
I was recently invited to a team and told to install and run a command: `keybase team accept-invite --token=...`
I then get the error
```
- WARNING fixHeaders: session required, but error getting sessionArgs: Login required
- ERROR Login required
```
I later realized I needed to create a new account which I did. That command then worked successfully.

It might be good to include that step in the email or to change the message to be clearer about "There is no account on this computer. Please login to the client or create a new account."

**Comment by maxtaco** [comment]
thanks for the bug report. We've fixed this in master.
