### ISSUE TITLE
Can't pull from keybase encrypted git repo

### ISSUE THREAD

**Issue by Ryan09** [keybase/client#8998]
I've successfully made a repo inside keybase and pushed to it a few times, however I've just tried to do a pull from another computer and I get:

```
Initializing Keybase... done.
Syncing with Keybase... done.

git-remote-keybase error: (1) malformed refspec, separators are wrong
git-remote-keybase error: (1) malformed refspec, separators are wrong
```

my log id: 357336e473619372ab35301c

**Comment by Ryan09** [comment]
For some more context, the clone works successfully, but running fetch gives the same error.

I've tried making a new repo on the second machine and pulling to the first, and it has the same issue.

Both machines are windows.

**Comment by Ryan09** [comment]
Did some more testing and I think this was an issue outside of keybase, so I'll close the issue.

**Comment by strib** [comment]
You may have already figured this out, but it looks like you put the whole git repo URL in your remote name.  I see things like this in the log:

```
 refs/heads/master:refs/remotes/keybase://private/...
```

Usually you want to create a remote with a short name and use that, something like:
```
git remote create kb keybase://private/...
git push kb --all
```
