### ISSUE TITLE
Client is unusable

### ISSUE THREAD

**Issue by ruipacheco** [keybase/client#9016]
I've started using Keybase as a chat client and find it barely usable. I really like the idea but the implementation is very flakey. Every time I open the client I click on "People" and nothing loads. Just a blank window with placeholder shapes. Sometimes I get an error to the effect of "Server sent EOF" or something like that.

I've been trying to use the desktop client to follow and unfollow people and every time I can click on a user it just... stays there. Nothing happens. I have to do everything through the website.

I also what seem to be random disconnects from the server. I get strange error messages on top of the window, white text in black background. They're don't tell me much on what to do next.

I've tried to open and close the client to see if the issues go away but, see my previous ticket, that doesn't always work.

Finally, `keybase log send` hangs as much as the client with the same EOF errors.

I really like the idea behind Keybase but right now I'm finding it too frustrating to use.

**Comment by maxtaco** [comment]
seems like a bug and/or a crasher.  Which version of keybase? Run `keybase version`

Thanks, sorry for the issue

**Comment by ruipacheco** [comment]
```
⟩ keybase version
Client:  1.0.33-20171003193446+d9ceb86ac
Service: 1.0.33-20171003193446+d9ceb86ac
```

**Comment by ruipacheco** [comment]
Latest OSX.

**Comment by maxtaco** [comment]
Can you run `keybase db nuke` and then try it again?

**Comment by ruipacheco** [comment]
Should I kill -9 the app first?

**Comment by maxtaco** [comment]
it seems to me it's in a crash loop, so i didn't think that would be necessary, but i'm really not sure

i haven't seen this issue before, and it's hard to know without seeing a log (which as you said above you can't do)

**Comment by ruipacheco** [comment]
```
⟩ keybase db nuke
Really blast away your local database? (type 'YES' to confirm): YES
▶ WARNING Nuking database /Users/ruihpacheco/Library/Application Support/Keybase/keybase.leveldb
▶ WARNING Nuking chat database /Users/ruihpacheco/Library/Application Support/Keybase/keybase.chat.leveldb
```

I quit by right clicking on the dock icon and pressing "Quit" which in my experience truly kills the app. Then I restarted the app, waited a bit while it did something in the background and then it presented me with the login screen.

I entered my email and waited. This was strange because there was no visual feedback that there was any background work being done. It finally asked for my password and I entered and waited more without any feedback and then this:

> request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)

The error message is much bigger but this seems to be the gist of it. I can't copy/paste and since it's a URL and parameters I'm not sure I wouldn't make a mistake typing it in.

**Comment by ruipacheco** [comment]
So, 3 things:

* No feedback when something happens in the background
* There's a typo on "canceled".
* I can't login

**Comment by maxtaco** [comment]
Are you behind a firewall of some sort?

**Comment by ruipacheco** [comment]
I have Little Snitch, but its configured to let all Keybase traffic through. OSX firewall also not blocking. And this issue is intermittent.

**Comment by ruipacheco** [comment]
One more thing, I sometimes can do `keybase log send`. Did so yesterday while fighting this issue.

**Comment by ruipacheco** [comment]
So for fun I just tried to do `keybase log send` and this came out:

⟩ keybase log send
This command will send recent keybase log entries to keybase.io
for debugging purposes only.

These logs don’t include your private keys or encrypted data,
but they will include filenames and other metadata keybase normally
can’t read, for debugging purposes.

Continue sending logs to keybase.io? (type 'YES' to confirm): YES
Enter feedback (or ENTER to send): 
▶ INFO ignoring error getting keybase status: There were multiple errors: dial unix /Users/ruihpacheco/Library/Group Containers/keybase/Library/Caches/Keybase/keybased.sock: connect: no such file or directory; dial unix /Users/ruihpacheco/Library/Caches/Keybase/keybased.sock: connect: no such file or directory
▶ INFO ignoring UI logs: There were multiple errors: dial unix /Users/ruihpacheco/Library/Group Containers/keybase/Library/Caches/Keybase/keybased.sock: connect: no such file or directory; dial unix /Users/ruihpacheco/Library/Caches/Keybase/keybased.sock: connect: no such file or directory

**Comment by ruipacheco** [comment]
```
------------
Success! Your log ID is:

  d2c0c8e24ccef8343ef6201c

Here's a URL to submit new bug reports containing this ID:

  https://github.com/keybase/client/issues/new?body=[write%20something%20useful%20and%20descriptive%20here]%0A%0Amy%20log%20id:%20d2c0c8e24ccef8343ef6201c

Thanks!
------------

```

**Comment by maxtaco** [comment]
great, we'll take a look. thanks

**Comment by maxtaco** [comment]
```2017-10-12T22:07:45.114812+02:00 ▶ [DEBU keybase standard.go:178] 1e0 - API GET https://api.keybase.io/_/api/1.0/user/lookup.json?fields=basics%2Cpublic_keys%2Cpictures&load_deleted=1&multi=1&username=ruipacheco: err=ERROR: API network error: doRetry failed, attempts: 3, timeout 13.5s, last err: context deadline exceeded, status="", jsonwBytes=0 [tags:API=ih-HlCSuaes4]```

Are you sure this endpoint is getting through your firewall?

**Comment by maxtaco** [comment]
cc: @patrickxb  who is helping me debug

**Comment by ruipacheco** [comment]
I've now disabled Little Snitch and the OSX firewall. I can load the people I'm following, and unfollow them, but I can't load any chat messages.

Got an error, black background with white text, saying something to the effect of not being able to connect to the chat server.

**Comment by ruipacheco** [comment]
I closed the client by right clicking on the dock and Quit. Reloaded the client, got black banner with white text saying "Internal Error: API request requires session, but session token empty" and then this exception:

`Error: Internal error: API request requires session, but session token empty at l.t (file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/index.bundle.js:1:248847) at l (file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/index.bundle.js:1:249451) at s (file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/index.bundle.js:1:249142) at t.convertToError (file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/index.bundle.js:1:249329) at _rpcClient.invoke.e (file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/index.bundle.js:1:236048) at file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/index.bundle.js:11:246580 at e.t.Deferrals.e._call (file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/index.bundle.js:6:233815) at file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/index.bundle.js:6:233966 at s (file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/index.bundle.js:6:233595) at e.t.Deferrals.e._fulfill (file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/index.bundle.js:6:233925)`

**Comment by maxtaco** [comment]
try to quit and restart the app

**Comment by maxtaco** [comment]
and try to logout and log back in

**Comment by ruipacheco** [comment]
Can't log out. Client hangs without loading UI and when I click on logout nothing happens. Quitting and restarting the app does not change this.

Little Snitch and OSX firewall are confirmed disabled.

**Comment by maxtaco** [comment]
Do another `keybase log send` and we'll take another look. It appears you've pushed the app into a broken state due to your firewall settings.

**Comment by ruipacheco** [comment]
Am now getting a random exception:

`Error: Can't load devices at r (file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/index.bundle.js:6:1049050) at r.throw (<anonymous>) at n (file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/index.bundle.js:6:152845) at n (file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/index.bundle.js:6:153671) at file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/index.bundle.js:6:154644 at <anonymous> at process._tickCallback (internal/process/next_tick.js:109:7)`

**Comment by ruipacheco** [comment]
be4830c03accb36f30c91e1c

**Comment by maxtaco** [comment]
We're still seeing a ton of network calls failing.

**Comment by ruipacheco** [comment]
Anti-virus, firewall and Little Snitch are disabled. I have youtube in the background and am unfollowing people in the client. Not sure what else could be in the way. Maybe at the ISP level?

**Comment by maxtaco** [comment]
I'm  not sure, but our other users aren't reporting these issues, so at this point, I think it's local to your configuration and I'm not in a good position to debug it.

**Comment by ruipacheco** [comment]
What else do you need from me?

**Comment by maxtaco** [comment]
I can't provide any more support, have lots of other things vying for my attention.  I think the problem is still local to your config, so you'd have to find a want to figure it out.  Watch the logs show in `keybase status` to see what network calls are failing. I see these right now:

```2017-10-12T23:10:29.815216+02:00 ▶ [DEBU keybase standard.go:178] 142 - API GET https://api.keybase.io/_/api/1.0/merkle/path.json?last=1568622&load_deleted=1&poll=10&sig_hints_low=85&uid=a86855c3f3874c741573a0f6c0178d19: err=ERROR: API network error: Get https://api.keybase.io/_/api/1.0/merkle/path.json?last=1568622&load_deleted=1&poll=10&sig_hints_low=85&uid=a86855c3f3874c741573a0f6c0178d19: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers), status="", jsonwBytes=0 [tags:API=niDVoyOWb7-5,ID2=PBjTUbfNuwsp,LU=iNNqULr1R2ka]
2017-10-12T23:10:29.815216+02:00 ▶ [DEBU keybase standard.go:178] 143 - API GET https://api.keybase.io/_/api/1.0/merkle/path.json?last=1568622&load_deleted=1&poll=10&sig_hints_low=85&uid=a86855c3f3874c741573a0f6c0178d19: err=ERROR: API network error: Get https://api.keybase.io/_/api/1.0/merkle/path.json?last=1568622&load_deleted=1&poll=10&sig_hints_low=85&uid=a86855c3f3874c741573a0f6c0178d19: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers), status="", jsonwBytes=0 [tags:LU=eDPaEMrgvVFa,API=A0JzNDtc_NAD]
```

**Comment by ruipacheco** [comment]
Will do, thanks for the help!

**Comment by btamayo** [comment]
@ruipacheco Did you ever manage to find a fix for this? I've been getting the same error for a few weeks now on one of my machines.

**Comment by ruipacheco** [comment]
I followed the instructions of the team in this thread and right now the client seems to work fine. `keybase db nuke` seems to have been the only thing I hadn't done before, but it's impossible to know what else happened.
