### ISSUE TITLE
Team folder not syncing

### ISSUE THREAD

**Issue by PhilRW** [keybase/client#9034]
Team folder is out of sync, not quite sure what to do or how to proceed to reset it. Would be great if there was a reset/resync functionality somewhere in the CLI but so far my efforts have not been fruitful.

my log id: ca2347d3a39a5a70f3861f1c

**Comment by strib** [comment]
Looks like your local device is in a conflict state due to some bug in our code.  I'll look into it further.  If you're in a pinch and need a quick fix to get back in sync (but discard whatever data you've written in the meantime), let me know.

**Comment by PhilRW** [comment]
Thanks for the fast response. It's not a huge deal but glad I could help find a bug. Perhaps there should be a feature request for the ability of users to perform this discard/reset on their own? :)

**Comment by strib** [comment]
There is something like that, but we don't advertise it because if it happens, it usually means a bug and we want to hear about it!  I'll look into this for a bit and let you know what the best thing to do is.

**Comment by strib** [comment]
Hmm, this is a super weird one.  I suspect it might be an unusual symptom of another bug that we've already fixed, but I'm not sure.

Would you be willing to share the private metadata history of that folder with me so I can debug a bit more?  It wouldn't contain any file data, just file/dir names, attributes, and sizes.  If so, please go into that folder and run `cp .kbfs_update_history /keybase/private/strib@github,philrw@github/client_9034_update_history.json`.  Note that will probably take a long time to run, maybe on the order of 10-20 minutes.  Also note that the file `.kbfs_update_history` does not appear in the directory listing, you can have to try reading it in order for it to appear.

**Comment by strib** [comment]
It might also be useful to have your full set of logs, rather than the subset sent by `keybase log send`.  If you're willing to share those, you can find your log directory in the output of `keybase status`.  Go into there, and run `tar -czf /keybase/private/strib@github,philrw@github/client_9034_kbfs_logs.tgz keybase.kbfs*`.  Thanks!

**Comment by strib** [comment]
@PhilRW: if you're willing to try out a test build, I made a special test release that I think will resolve the conflicts on your folder successfully: https://s3.amazonaws.com/prerelease.keybase.io/darwin-test/Keybase-1.0.34-20171013202904%2Be45b61ae8.dmg

Install that, look inside the team folder, and hopefully it should quickly come up to speed (with a couple minutes).

If you're not willing to try that, we can back out your local changes to that folder with a simple command, and you can re-add that data again manually.

**Comment by PhilRW** [comment]
Which client machines should I try this build on?

**Comment by strib** [comment]
The one you sent me logs from: `CL MacBook Pro`

**Comment by PhilRW** [comment]
It's installed and running now but still seems to have the discrepancies.

**Comment by strib** [comment]
Hmm ok, if you do another `keybase log send` and post the ID here, I'll take a look.

**Comment by PhilRW** [comment]
033636620617d1a87634371c

**Comment by strib** [comment]
Thanks.  Seems like there was a second bug hiding behind the first one.  Looking...

**Comment by strib** [comment]
@PhilRW: here's another build to try out, with a new fix.  Thanks!

https://s3.amazonaws.com/prerelease.keybase.io/darwin-test/Keybase-1.0.34-20171013234544%2B8bdf88aed.dmg

**Comment by PhilRW** [comment]
That seemed to work; I came back overnight and it looks to be syncing now.
