### ISSUE TITLE
Reset private folder

### ISSUE THREAD

**Issue by philpl** [keybase/client#9038]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

Hiya, a while ago I've removed all my previous devices and I've gone through 2 GPG keys during that time as well. I've now noticed that I can neither use the private folder nor Git on Keybase.

Can some help me to reset it please? Sorry, btw, didn't find any other way to contact someone on the site.
-----BEGIN PGP SIGNATURE-----
Version: Keybase OpenPGP v2.0.74
Comment: https://keybase.io/crypto

wsFcBAABCgAGBQJZ4PvLAAoJELi+9rN3hi/eAgsQALGQfIxxmkZSaeKUHXdljAPo
wbFCKaBAJRj6V33FIxh0jtYGMvDjSPViuMiI6ZWjj7W/t1KbScaql5Ns/3ZN7+fG
rp5J+X35PbSZapf0KnvuDR4KZTV7iGMt7QLXJ9CrTVyuQ4drpkuTcF+CdR+6L1w7
U5/rjcKri7pdO26Scm7qlzCRI2lHD27RzXSrtrkXCGPe14gvpgwau9btHCv0wBKQ
2GGj0r3ecPtpLPgNSyj1a6o29+TxDfIjono2RiEhywn5fnYiZx+xKDz/aHzO0Jaf
C0HxCsql6ecOvT2UcfZs8N1/+syz2o/isuCq0Oh8I46uTAvbStmQt6liUAY1jRUn
o/WJ5y8e5zslco5L/8hKNuD/RlLRpi1vHBvHZykfVgnhxHsxf9IGo/PxsJb7iow8
pHunKjFuiF+fbuGPR5N9o4zXyeMVECLxzF2/RkRjz/5ekucMLhaO0kBP2Wn17oS8
9hSQ/o14TflufTWyIQQ8Hn1QaXmw50vgx8hMSNdRC7Vm74J2JNS9CMWdg2iZRhJF
WziVYmDApnorBaOL/vSsir78YnACnceKXvvRbPZ5/guwszXzDhQiOOhGPW170URw
pq1LfLQV6MrDeUk1E/Rnhp75+n+gqQRu7I3mkOWbFd4MbwzYmHGyuz/na36376Gb
QvRqRXtbUdEckuo0ncLz
=5Ikk
-----END PGP SIGNATURE-----

**Comment by strib** [comment]
I reset the folder.  Please check it out and close this if everything seems ok.  (Might require a Keybase restart.)

**Comment by philpl** [comment]
Seems to work perfectly now! Thanks for the quick help ❤️
