### ISSUE TITLE
Unable to login (the key is no longer active)

### ISSUE THREAD

**Issue by mauvehed** [keybase/client#9057]
- Ubuntu 16.04.3 (64-bit)
- keybase version 1.0.34-20171012160058+c282fb227

I had an old npm installed keybase which I removed and reinstalled using the .deb file. I X-forwarded the 'run_keybase' command over SSH and when I try to login it throws an error saying:

"Error Provisioning"

"Unknown error: The key 'SUPER_LONG_HEX_STRING_HERE' is no longer active"

And that's all the further I can get. I don't see this on google or any issues here. What have I hit upon?

**Comment by maxtaco** [comment]
If you run a `keybase log send`, we can take a look, but it's likely not a recoverable situation.

**Comment by maxtaco** [comment]
(meaning you'll have to reset your account most likely)

**Comment by mauvehed** [comment]
Sent. d8c0c735794f37c0abe7421c

**Comment by maxtaco** [comment]
Which provisioning path did you choose?

**Comment by maxtaco** [comment]
@patrickxb can you take a look?  this seems to be a buggy provisioning scenario.  @mauvehed it can likely be fixed.

**Comment by mauvehed** [comment]
> Which provisioning path did you choose?

..I'm not sure? What would this choice have been?

**Comment by patrickxb** [comment]
@mauvehed it looks like you are logging in on a revoked device (`bloatis`).  We have a fix for this, but it hasn't been released yet.   In the meantime, can you try

    keybase logout
    keybase login

that should work for you.

Thanks!

**Comment by mauvehed** [comment]
@patrickxb this appears to have fixed my problem! The original thing I was trying to do was clone the keybase git repo and this now works on the device that issued the error.

Thanks much everyone!

**Comment by patrickxb** [comment]
Glad it worked...
