### ISSUE TITLE
Git clone stuck on Initializing Keybase... done.

### ISSUE THREAD

**Issue by josecanhelp** [keybase/client#9063]
I'm trying to clone a private repository into my digital ocean server and it get's stuck at `Initializing Keybase... done.`

```
jose@ubuntu-512mb-nyc3-01:~$ git clone keybase://private/josecanhelp/josesoto.com
Cloning into 'josesoto.com'...
Initializing Keybase... done.
```

my log id: ca9ba9f896266301a20d5a1c

**Comment by strib** [comment]
@josecanhelp: it looks like your keybase background daemon can't start up because of this error:

```
2017-10-13T07:16:48.536490Z ▶ [ERRO keybase standard.go:232] 021 mkdir /run/user/0/keybase: permission denied
```

I'm not really sure what that means -- maybe you're trying to run as root, when you should be running as a regular user?

**Comment by josecanhelp** [comment]
Thanks for the info, @strib. 

I was logged into keybase via the root user, but I was attempting to clone as a normal user. Running `keybase login` from the normal user and re-setting up the device fixed the issue for me.
