### ISSUE TITLE
Cannot start keybase after installing

### ISSUE THREAD

**Issue by larsnystrom** [keybase/client#9067]
I just installed keybase for the first time on macOS. When I try to start keybase I see this:

![image](https://user-images.githubusercontent.com/1000370/31614848-fb8ec6e0-b287-11e7-8d0e-c0dca5ebeb9c.png)

Restarting keybase does not work.

my log id: 2b2f6de986bcc06e18d5b31c

**Comment by maxtaco** [comment]
Hi, sorry about this. This is likely a permissions issue.  Can you `ls -lsa ~/Library/LaunchAgents`?

**Comment by maxtaco** [comment]
Right, but we're also trying to figure out what the permissions on the directory are.  How about run this:

```
ls -lsa ~/Library/ | grep LaunchAgents
```

**Comment by larsnystrom** [comment]
Oh, sorry. Yeah, here's the output:

    0 drwxr-xr-x    4 root  staff    128 25 Mar  2017 LaunchAgents

**Comment by maxtaco** [comment]
yeah, that's the problem.  Do you run LastPass by any chance? We've had reports that it messes up this directory in this problem.  Anyways, you can solve this issue via:

```
sudo chown <your-username>:staff ~/Library/LaunchAgents
```

And Keybase should work again. We're working on a workaround for this problem. Some other app that you've installed has in a sense corrupted your system.  

Let me know if this fix works...

**Comment by larsnystrom** [comment]
Yes, that solved the issue. I do have LastPass installed, but I really can't understand why they'd change the owner of that directory. Seems like a pretty crazy bug.

**Comment by maxtaco** [comment]
Ah cool.  Well several others have reported it. My guess is that they escalate privileges for whatever reason, and then run the `launchctl` commands as `root`, which resets the permissions on the directories.

**Comment by larsnystrom** [comment]
Hm, yeah probably. Well, I'm going to close this now.
