### ISSUE TITLE
Bitcoin address for own profile displays on apps but not on web

### ISSUE THREAD

**Issue by johnnyRose** [keybase/client#9072]
When viewing my own profile on a browser after setting a Bitcoin address, it continues to prompt me to add an address. When viewing my profile on the Windows or iOS app, it correctly displays my Bitcoin address. See below screenshot:

![chrome_2017-10-16_11-52-06](https://user-images.githubusercontent.com/6598538/31624701-2a515228-b269-11e7-81be-be760891b5b1.png)

I added this Bitcoin address several days ago ([October 5th, 2017 to be exact](https://keybase.io/johnnyrose/sigchain#6f851ea746fb38f51d00c7473a62174ecf3f229c55c0b9022dc7b294f2f9561f0f)).

**Comment by maxtaco** [comment]
we'll take a look, thanks

**Comment by mlsteele** [comment]
@johnnyRose [Fixed](https://keybase.io/johnnyrose)!

The website was hiding it because it was signed by a key was since revoked. But sigs like that are still valid.

**Comment by johnnyRose** [comment]
@mlsteele nice! Thanks for following up!
