### ISSUE TITLE
How do I find my KID (Key ID)?

### ISSUE THREAD

**Issue by gmihovics** [keybase/client#9073]
I am trying to write an app that uses the Keybase API. I am currently trying to authenticate against the API using the `getSalt` and `login` endpoints. In the [docs](https://keybase.io/docs/api/1.0/call/login) for the `login` endpoint, it says I need to include my **KID** in the signed blob. The problem is, I can't seem to find my **KID** anywhere and I really don't understand how to generate it based on the [instructions in the docs](https://keybase.io/docs/api/1.0/kid)

Is there anyone who can point me in the right direction?

**Comment by maxtaco** [comment]
Sorry the docs leave something to be desired. The KID is the public key in the case of NaC (minus the leading `0x0120` and the trailing `0x0a`. 

Check out this [sample code](https://github.com/keybase/node-login)

**Comment by gmihovics** [comment]
@maxtaco, that works perfectly, thanks for the help
