### ISSUE TITLE
[Feature Request] Universal iOS support for the iPad

### ISSUE THREAD

**Issue by garrettoreilly** [keybase/client#9082]

**Comment by specious** [comment]
It would be incredibly useful not to have to rotate the iPad into portrait orientation every time just to use Keybase.

![28d6fc07-1e67-4fbb-8c1d-7ca65e6f4a31](https://user-images.githubusercontent.com/451178/34081558-497508b4-e31c-11e7-9ada-ecbaa440e915.png)

**Comment by specious** [comment]
Looks like universal support was enabled in #6230 and removed in #6836.

**Comment by BergQuester** [comment]
Dupe of #8909 which as of writing has an open pull request.
