### ISSUE TITLE
HackerNews verification

### ISSUE THREAD

**Issue by kika** [keybase/client#9088]
Similar to #5614 but doesn't seem to be the HN API issue

When verifying HN username I've added your proof to the profile and the app says I can't find it. I've pressed "check again" and it found it, but in the profile, the HN username stays unverified. I've got an email that my HN proof succeeded. I've redone this, this time replacing the profile with your proof and the same thing repeated - can't find the first time, finds the second time, sends an email that everything is fine, in the profile HN handle stays red.

**Comment by jimbodenjr** [comment]
I have the same issue.  I am assuming that when you place the text that is provided to the profile, that it is put in the about section of the profile?

**Comment by kika** [comment]
Yes.
I figured that you just need to wait a long time. My account became verified after a few days (I don't know when exactly).
