### ISSUE TITLE
KBFS (Fuse kext) Install Error post High Sierra upgrade

### ISSUE THREAD

**Issue by coreygo** [keybase/client#9102]
1. Upgrade from Sierra to High Sierra
2. Receive KBFS (Fuse kext) Install Error… my log id: be662a9cf30450e9819b831c
3. Click Ignore
4. Keybase folder error

![screen shot 2017-10-17 at 16 44 11](https://user-images.githubusercontent.com/649879/31694760-f290fc6a-b35a-11e7-9e5e-210b5cb4cf27.png)

![screen shot 2017-10-17 at 16 45 39](https://user-images.githubusercontent.com/649879/31694820-49e5e584-b35b-11e7-995c-82c7a74d453a.png)

**Comment by coreygo** [comment]
Likely duplicates... #8549 #8906

**Comment by maxtaco** [comment]
Yeah sadly there is nothing we can do here.  You can quit some of those other apps if you are using them.  But seems like they grabbed the slots and there were none left for keybase. Let me know if you don’t run any of those apps and we are off base.

**Comment by wundrellama** [comment]
I'm also having this issue.  Log ID is 026c32e2fbaf438442f3161c.

I'm not running any of the listed apps, nor am I running anything similar.

**Comment by coreygo** [comment]
@maxtaco Womp. Looks like I'm out of luck… What's up exactly? Are there some High Sierra release notes that point to what's changed? I know about [TN2459](https://developer.apple.com/library/content/technotes/tn2459/_index.html#//apple_ref/doc/uid/DTS40017658) but that's not this.

```
kextstat | grep -v com.apple
Index Refs Address            Size       Wired      Name (Version) UUID <Linked Against>
  130    0 0xffffff7f80b4b000 0x9000     0x9000     net.telestream.driver.TelestreamAudio (1.1.1) 97394489-75E6-39C3-A0AF-658A94F1CA3B <93 5 4 3 1>
  163    0 0xffffff7f80c34000 0x7000     0x7000     net.sf.tuntaposx.tap (1.0) 23FDB715-3D0D-3A26-ACBA-E3794C231CB7 <7 5 4 1>
  166    0 0xffffff7f83650000 0x14000    0x14000    com.intel.kext.intelhaxm (6.0.5) 8C4C5339-F7AA-36E5-A052-3D2E7DC6DF16 <7 5 4 3 1>
  167    3 0xffffff7f83664000 0x62000    0x62000    org.virtualbox.kext.VBoxDrv (5.1.28) C0F0EDBE-F7FA-3189-8D24-48F02415C348 <7 5 4 3 1>
  172    0 0xffffff7f836c6000 0x8000     0x8000     org.virtualbox.kext.VBoxUSB (5.1.28) 93025612-D707-3185-AA16-5D987EA2F72E <171 167 52 7 5 4 3 1>
  173    0 0xffffff7f836ce000 0x5000     0x5000     org.virtualbox.kext.VBoxNetFlt (5.1.28) F8FCB36B-980B-3823-BFCB-765E43593678 <167 7 5 4 3 1>
  174    0 0xffffff7f836d3000 0x6000     0x6000     org.virtualbox.kext.VBoxNetAdp (5.1.28) 6AE4C456-BA43-328E-8464-1CAA4C6F7BB8 <167 5 4 1>
  176    0 0xffffff7f836d9000 0x16000    0x16000    com.google.dfsfuse.filesystems.dfsfuse (3.5.3) CD32A127-3580-3A13-B2CD-D0193BB13E2A <7 5 4 3 1>
```

**Comment by maxtaco** [comment]
I wish I knew what changed.  I guess we'd have to see that list before the upgrade.  Maybe your last remaining slot was taken up by one of those software packages, and they previously used no or fewer slots.

**Comment by coreygo** [comment]
@maxtaco Unfortunately I didn't think to check prior to the upgrade. I cleaned the system after hitting the error. For example I had VMWare Fusion installed in addition to VirtualBox… of course that was the case on Sierra but KeyBase didn't have any issues. If device slot availability is the issue one would imagine hitting this when the system wasn't as "clean".
