### ISSUE TITLE
UI Suggestion: Confirm Sign Out

### ISSUE THREAD

**Issue by squatched** [keybase/client#9115]
Keybase GUI Version: 1.0.34-20171012160058+c282fb227

It would be nice to have a confirmation when signing out. I accidentally hit the "Sign Out" button which was a minor inconvenience.

**Comment by dragon788** [comment]
I very much agree. The worst part is sometimes signing back in to the same account (I have a couple I use for separation of concerns) the client acts weird until I use `run_keybase` again.

**Comment by specious** [comment]
I would like to document this moment in history for posterity, from when it will someday be looked back on as the early days of Keybase. It sort of freaked me out how easily it logged me out.

Now I wonder what some of the other buttons might do without warning.

![keybase-settings-sign-out](https://user-images.githubusercontent.com/451178/34311651-c1352cb2-e72c-11e7-9b50-53c440e98405.png)

**Comment by M-Pixel** [comment]
This has been fixed: Keybase now shows a warning when clicking "Sign out".  This issue should be closed.

**Comment by squatched** [comment]
A dialog has been added that makes this at least a 2-step process. Love the "Confirm you have your password, you're gonna need it!" design.
