### ISSUE TITLE
Show subteam's #general channel underneath the parent "big team"

### ISSUE THREAD

**Issue by hach-que** [keybase/client#9129]
For organisational purposes, and to maintain the same kind of layout that you'd see in Slack/Mattermost, it'd be preferable if subteams appeared underneath the parent "big team".

Right now, if you have a special directors-only channel as a subteam, it'll appear completely separate from the rest of the big team in the sidebar, even though the equivalent "private channel" behaviour in other products would show it underneath the same instance.

**Comment by unlocKing** [comment]
creating a new channel in the subteam will make it show as big team.

you can disable that new channel after if you have no need for it and it will still show as big team under your main big team.

**Comment by hach-que** [comment]
What do you mean by disable? I tried deleting the new channel but that reverts it back to a normal team instead of a big team.

**Comment by hach-que** [comment]
Ah, I'm guessing you just mean leave the channel after creating it. That works.
