### ISSUE TITLE
Export / import for team chats

### ISSUE THREAD

**Issue by hach-que** [keybase/client#9146]
It'd be ideal if there was a way to import existing data from Slack/Mattermost into team chats, maintaining the old usernames and timestamps on messages.

Now obviously there's no way for Keybase to verify the integrity of these messages (because they're coming from an old unsecured system), so maybe the import could just be signed by one of the team owners, and then if anyone is looking at those old messages, they can see via some visual indicator that they're the result of an import, and not actually signed or made by the person with that username.

We'd also like to be able to regularly export our team conversations. If Keybase servers go down tomorrow (after all, there's no revenue generation for Keybase at the moment!), we don't want to suddenly be locked out of all of our data and message history (Git is a little less concerning because there's distributed copies on other machines).

**Comment by dabura667** [comment]
is there a way to export all chat data from Slack?????.......... TIL... lol

**Comment by junderw** [comment]
Yeah. Importing channels, messages, and files from a Slack export would be great... (might take a while though...)

**Comment by jeffdoolittle** [comment]
Any progress on this?
