### ISSUE TITLE
Keybase client fails to start on OSX 10.13

### ISSUE THREAD

**Issue by Oneiroi** [keybase/client#9151]
Keybase client fails to start on 10.13 this ocurred this morning and was working fine yesterday.

The error presented is as per the following screenshot:

![image](https://user-images.githubusercontent.com/478678/31811233-b7cf4ac8-b576-11e7-9e9f-473413365eea.png)

* There was an error trying to install the updater
* There was an error trying to install the service
* There was an error trying to install the kbfs

my log id: 5ddb94a3acea983e6923a71c

keybase version 1.0.33-20171003193446+d9ceb86ac

**Comment by maxtaco** [comment]
What are the permissions on your LaunchAgents folders?

```
ls -lsa ~/Library | grep LaunchAgents
```

**Comment by Oneiroi** [comment]
`0 drwx------   13 username staff   416 Oct 20 09:07 LaunchAgents`

**Comment by maxtaco** [comment]
Hmm, I hate to recommend this, but can you restart your Mac? Usually it's one of those two issues, but your permissions look OK

**Comment by Oneiroi** [comment]
@maxtaco a restart seems to have solved the issue I reported, closing this issue for the moment as I am presuming this to be an OS and not Keybase issue.
