### ISSUE TITLE
Options for creating my own app

### ISSUE THREAD

**Issue by emmaguy** [keybase/client#9163]
Hi!

I have been poking around this repo for the last couple days exploring the options to create my own Keybase Android app (there are some things lacking in the official app which I imagine will get added over time, but thought it would be a fun exercise to try and build a native app anyway).

Thus far, I have concluded that I have the following options:

1. Roll it myself - call the Keybase web api directly and login `/getsalt` and `/login` as documented [here](https://keybase.io/docs/api/1.0/intro)
2. Reuse the `keybaselib.aar` binary you can compile from this repo and figure out the avro-based RPC commands to send/receive messages (using `read64` and `writeB64` I think?) to the server that gets started by the dependency

I'm not sure (at least I haven't found docs for!) a web api for chat, without that kind of limits the usefulness of option 1 - is there one?

As for 2, are there docs/examples of how the RPC stuff works? I tried running the react native app with the intention of figuring it out, but got a bit lost with the unfamiliarity/masses of code.

Any recommendations/other options/other concerns that would thwart this idea? I'm also not sure how the devices concept would work in either case, whether the new app would count as a separate device or if it could someone reuse the existing stuff.

Thanks in advance!

Incidentally, if there's a more appropriate place to ask this (is there a public dev keybase team?), please let me know 😅

**Comment by ologunB** [comment]
@emmaguy Good day, any idea where I can download the keybaselib.aar or maybe the repo to build from?
