### ISSUE TITLE
missing public folder - how to restore on remote linuxVM with Keybase.io installed (command line only)

### ISSUE THREAD

**Issue by wireddude** [keybase/client#9164]
installed keybase in the cloud, command line only. was working fine, and then I installed KBSecret which seemed to blow away my /public folder mount. The public folder is still there. I've deleted KBSecret for now.  I'm thinking I will uninstall keybase and reinstall.

my log id: 1046bf6e5e0419e39e55a01c

**Comment by strib** [comment]
@wireddude it seems like you tried to write into `/keybase` before you were actually running the KBFS process.  Now you have local data under the `/keybase` directory, and KBFS is refusing to mount on top of that local data.  You should use the `mount` command to make sure nothing is mounted at `/keybase`/, then `rm -rf /keybase/*`, then `run_keybase`, and then try to use kbsecret.

**Comment by wireddude** [comment]
it all worked but it never re-mounts the /keybase mountpoint again, even though run_keybase says it sucessfully did

**Comment by strib** [comment]
@wireddude: it still looks as if you have data under your local `/keybase` directory.  Please do these steps:

```sh
if killall Keybase &> /dev/null ; then
  echo Shutting down Keybase GUI...
fi
if fusermount -uz /keybase &> /dev/null ; then
  echo Unmounting /keybase...
fi
if killall kbfsfuse &> /dev/null ; then
  echo Shutting down kbfsfuse...
fi
if killall keybase &> /dev/null ; then
  echo Shutting down keybase service...
fi
mkdir /tmp/keybase_backup
sudo mv -rf /keybase/* /tmp/keybase_backup/
run_keybase
```

Also note that `keybase fs ls /keybase` isn't a valid command by itself, you need to try `keybase fs ls /keybase/private`, for example.

**Comment by wireddude** [comment]
Thanks!
