### ISSUE TITLE
Research inability to prove (Twitter) identity

### ISSUE THREAD

**Issue by ldexterldesign** [keybase/client#9165]
Hi,

Hope you're well

Thanks for software

I'm unable to prove my Twitter identity

Could this be because my Keybase and Twitter use different email addresses?

Let me know if you have any issues - happy to help

Hope to hear back

Yours faithfully

**Comment by malonehedges** [comment]
@ldexterldesign You probably need to provide more information and ask for help in another place. This is likely not an issue with the client of Keybase. What's your keybase username and twitter username? Can you provide a link to your twitter proof that failed?

**Comment by ldexterldesign** [comment]
NO REPLY NECESSARY

Thanks for reply

Sorry, forgot to close this issue

I resolved the issue right after creating this issue by generating the tweet for Keybase to query - perhaps the instructions weren't clear or I didn't read well enough

Regards
