### ISSUE TITLE
cannot logout from kybase.io

### ISSUE THREAD

**Issue by PPogorzelskiS** [keybase/client#9170]
after hitting logout button, I'm not fully logged out. The header suggests I'm not logged in, but I can still manage my keybase account. So how can I be sure I have logged out????

Regards
Piotr

![keybase-logout-devicesvisible-screenshot from 2017-10-22 19-01-37](https://user-images.githubusercontent.com/23261450/31864366-742f7c92-b75c-11e7-80c5-0dfad3842670.png)

**Comment by maxtaco** [comment]
The page you have shown is fully public.  For instance [this is my device page](https://keybase.io/max/devices).
