### ISSUE TITLE
Keybase error while trying to login

### ISSUE THREAD

**Issue by webkernel** [keybase/client#9174]
Keybase GUI Version: 1.0.24-20170622160028+e5ac865

Error: Unknown RPC Error at l.t (file:///opt/keybase/resources/app/desktop/dist/index.bundle.js:1:237583) at l (file:///opt/keybase/resources/app/desktop/dist/index.bundle.js:1:238111) at u (file:///opt/keybase/resources/app/desktop/dist/index.bundle.js:1:238025) at s (file:///opt/keybase/resources/app/desktop/dist/index.bundle.js:1:237950) at _rpcClient.invoke.e (file:///opt/keybase/resources/app/desktop/dist/index.bundle.js:1:219059) at file:///opt/keybase/resources/app/desktop/dist/index.bundle.js:83:46589 at e.t.Deferrals.e._call (file:///opt/keybase/resources/app/desktop/dist/index.bundle.js:8:28805) at file:///opt/keybase/resources/app/desktop/dist/index.bundle.js:8:28956 at s (file:///opt/keybase/resources/app/desktop/dist/index.bundle.js:8:28585) at e.t.Deferrals.e._fulfill (file:///opt/keybase/resources/app/desktop/dist/index.bundle.js:8:28915)

**Comment by maxtaco** [comment]
super old version, can you upgrade?

**Comment by webkernel** [comment]
updated version solved the problem

thanks
