### ISSUE TITLE
DNS proof not accessible from Windows client

### ISSUE THREAD

**Issue by afalk42** [keybase/client#9189]
The following DNS proof for ownership of my domain is validated an accepted in both the Android client as well as the web interface: [https://keybase.io/afalk/sigchain#8351751c3a1a3c20ba191919f7d78925113f97b3f31762e2be97e047141f4dcc0f](https://keybase.io/afalk/sigchain#8351751c3a1a3c20ba191919f7d78925113f97b3f31762e2be97e047141f4dcc0f )
However, in the Windows client it is showing as "UNREACHABLE":
![image](https://user-images.githubusercontent.com/6906332/31920571-ebc08e50-b837-11e7-9729-53c215c1abe6.png)

I have verified that the proof can be manually verified with dig from the exact same machine, so local DNS server caching is not the issue:
![image](https://user-images.githubusercontent.com/6906332/31920632-3a3626da-b838-11e7-93cd-f769f511e130.png)

**Comment by taruti** [comment]
@zanderz

**Comment by afalk42** [comment]
Apologies for leaving this issue open. It did resolve itself after about 24 hours. So it muse have been some DNS caching if not in Windows itself, then perhaps in the libraries used by the keybase Windows client. The proof of ownership of the domain is now validating correctly on all platforms.
