### ISSUE TITLE
Extension for Brave Browser

### ISSUE THREAD

**Issue by luixxiul** [keybase/client#9192]
Hello,

I am just wondering if the extension would be added to Brave Browser (https://github.com/brave/browser-laptop).

Though the extension implementation is not open yet, it seems that the extension seems to be able to be integrated easily. Here you can see how it would be implemented on Brave Browser: https://community.brave.com/t/keybase-io-chat/9563

![](https://discourse-cdn-sjc1.com/standard2/uploads/brave/original/2X/4/48f9bedddf714ae3cddf4864611805c8007459af.png)

I know that the extension is still beta, but I personally would love to see the extension is available on Brave Browser. Is there any plan to work with the team? Thanks!

**Comment by luixxiul** [comment]
By copying the extension from Google's extension folder to the app folder of Brave and adding some modifications (changing the folder name etc), it actually works!

<img width="1012" alt="screenshot 2017-10-25 20 43 40" src="https://user-images.githubusercontent.com/3362943/31997110-c58c10bc-b9c5-11e7-91bb-bc54f5581b64.png">
<img width="1087" alt="screenshot 2017-10-25 20 43 29" src="https://user-images.githubusercontent.com/3362943/31997111-c5b28788-b9c5-11e7-81e5-8ea341537b2f.png">
<img width="1171" alt="screenshot 2017-10-25 20 43 00" src="https://user-images.githubusercontent.com/3362943/31997112-c5e08930-b9c5-11e7-95db-0e8ef6457aa4.png">

what do you think about that?

**Comment by Mikaela** [comment]
Brave development version is also directly able to use Chromium Store and at the moment does use it.
