### ISSUE TITLE
BUG Fix bio text erroneous space

### ISSUE THREAD

**Issue by ldexterldesign** [keybase/client#9250]
Hi all,

Hope you're well

Thanks for software

https://keybase.io/ldexterldesign

Strangely, there appears to be erroneous spacing inserted into my bio

Screen shot(s):

<img width="1440" alt="screen shot 2017-10-26 at 11 59 23" src="https://user-images.githubusercontent.com/1715809/32047235-96cad10c-ba45-11e7-9ce8-48e502060b90.png">
<img width="1440" alt="screen shot 2017-10-26 at 11 59 41" src="https://user-images.githubusercontent.com/1715809/32047233-96723fba-ba45-11e7-970b-8f2ce176bf41.png">
<img width="1440" alt="screen shot 2017-10-26 at 11 59 29" src="https://user-images.githubusercontent.com/1715809/32047234-96a718ac-ba45-11e7-981e-48a6c918a2cf.png">

If anyone else reading this agrees please up-vote or reply "+1"

NB I've recreated the issue in all the browsers I have installed (i.e. Beaker, Brave, Firefox, Tor, Vivaldi)

Let me know if you have any issues - happy to help

Hope this is clear/useful and to hear back

Regards

**Comment by ldexterldesign** [comment]
BUMP

**Comment by maxtaco** [comment]
cc: @keybase/react-hackers

**Comment by chrisnojima** [comment]
@malgorithms

**Comment by malgorithms** [comment]
I can't tell from your screenshot - are you sure you didn't write that whitespace in when editing? Can you show me an instance where what you saved in your textarea doesn't then match what you see in the same textarea when you go to edit?

note that we currently strip newlines/extra spaces on display (independent of whether you've saved them). So if you write this as your bio:

```
this
is      a test
```

it should be displayed, intentionally, as `this is a test`. But when you go to edit it, you should see your own formatting.

**Comment by ldexterldesign** [comment]
Thanks for reply

Yep, I'm sure

I will assume there's some (backend) URL regex at work:

<img width="403" alt="screen shot 2017-11-02 at 18 44 19" src="https://user-images.githubusercontent.com/1715809/32341496-f3c8840e-bffd-11e7-993c-82292dca1ee2.png">

Let me know if you have any issues - happy to help

Hope to hear back

Regards

**Comment by malgorithms** [comment]
thanks - this should be fixed. It took me a minute to realize you were talking about the text in the middle of your URL's, as opposed to the whitespace linebreak differences.

anyway, thanks, should be good now. Please close if satisfactory.
