### ISSUE TITLE
[LINUX] 34306b2 broke everything

### ISSUE THREAD

**Issue by junderw** [keybase/client#9306]
I just updated the PPA to 34306b2e65a847f5cc632c1c833db36987cf1aad which was release 5 minutes ago and now all chats are loading endlessly and team and git tabs don't load at all.

log ID 29846cd6737079a8947e901c

**Comment by cjb** [comment]
Thanks for the report.  You're totally right.  We're working on it now.  Fix incoming.

**Comment by cjb** [comment]
Fix is out now.

**Comment by junderw** [comment]
Confirmed fixed
