### ISSUE TITLE
push to keybase remote fails with `push.gpgSign = if-asked`

### ISSUE THREAD

**Issue by Celti** [keybase/client#9309]
On the theory that signatures everywhere possible are better than not, I have `push.gpgSign` set to `if-asked` in my global git configuration. Pushing to a keybase remote fails in this situation, instead of simply advertising no support for signed pushes:

```
celti@dana ~/.password-store $ git push keybase master
Initializing Keybase... done.
Syncing with Keybase... done.
fatal: helper keybase does not support --signed=if-asked
```

**Comment by strib** [comment]
Thanks for the report!  I just posted a PR that should fix this.

**Comment by strib** [comment]
Merged!
