### ISSUE TITLE
Can't stop automatic starting on macOS High Sierra

### ISSUE THREAD

**Issue by incyi** [keybase/client#9371]
Keybase GUI Version: 1.0.34-20171027003854+8e989533a

I don't want that the keybase client automatically starts on boot. But this is not possible. When I remove it from my Login Items from my account, it's adding again itself to there.

**Comment by maxtaco** [comment]
Thanks for this report. If so, it's a bug and when look into it. Thanks...

**Comment by maxtaco** [comment]
(We'll investigate and follow up)

**Comment by ziyaddin** [comment]
#9406 #9410

**Comment by maxtaco** [comment]
I wasn't able to reproduce this behavior.  Can you tell me what you tried and what you observed? Thank you!

**Comment by incyi** [comment]
When I install the keybase client on my mac. And start keybase, close keybase.
Go to settings -> Account -> my login name -> startup items. And remove there keybase.
Then start keybase and check back in the startup items, it's added again.
When I reboot, it is starting again.

**Comment by maxtaco** [comment]
I can't repro this behavior, are you sure it's removed from startup items? Can you show me a screenshot of what your startup items looks like after it's been removed? Thank you.

**Comment by patrickxb** [comment]
@incyi I know this might sound crazy, but is there any chance your display resolution is changing between when you quit keybase and start it again?

Assuming that's not the issue, could you post the output of the following:

    ls -l ~/Library/Application\ Support/Keybase/app-state.json

(I'm curious if there is a permissions problem writing to that file)

The contents of ~/Library/Application Support/Keybase/app-state.json itself would be helpful.  It will look something like:

    {"x":1416,"y":23,"width":1144,"height":736,"windowHidden":false,"isMaximized":false,"isFullScreen":false,"displayBounds":{"x":0,"y":0,"width":2560,"height":1440},"tab":null,"dockHidden":false,"openAtLoginSet":true}

Thanks!

**Comment by incyi** [comment]
{"x":440,"y":203,"width":800,"height":600,"windowHidden":false,"isMaximized":false,"isFullScreen":false,"displayBounds":{"x":0,"y":0,"width":1680,"height":1050},"tab":null,"dockHidden":false,"openAtLoginSet":true}


I see that openAtLoginSet true is, can I change this manually by editing this file ?

**Comment by incyi** [comment]
Fixed
