### ISSUE TITLE
encrypted git question: device move

### ISSUE THREAD

**Issue by drudru** [keybase/client#9403]
hi,

The encrypted git is a great feature. I want to use it soon. Before I jump, I am doing a little research.

it is not clear to me what will happen if I lose a device. You mentioned device keys for _signing_.

For example: I have installed keybase on my laptop. Lets say it stops working (this actually happened recently). I may not be able to restore from a backup. How can I get at my encrypted git repo on another install?

I probably don't understand how the underlying encryption is working for the git repo.

Can I just start with a fresh install and reclone?
Or do I need to always have a second device (phone? - the shared key you mention)
Or do I need to specifically have a clone on another device?

**Comment by strib** [comment]
If you lose access to all devices currently registered to your Keybase account, you will lose access to all of your personal, private git repos from our servers.

For this reason we recommend that you always have at least two devices registered with Keybase.  Ideally both of them would be computers or phones, but you can also add "paper key" devices, which is a secret string of words you can write down, and later use to provision a new device into your account.

If you don't have a usable second device, you'll have to reset your account.  At that point, you can re-create the repo if you have a local checkout.  But as long as you have a second device, you don't need a checkout.

**Comment by drudru** [comment]
Thx for your quick reply.

So, If I used encrypted git, and I lost my laptop, my data would be lost forever (catastrophic). That is fair. I want to use this feature so I need to know how to avoid this.

Ok, let me (attempt :-) ) to build a mental model.

Keybase stores the encrypted git repo.
It is encrypted with a key. (just AES? some variant)

This key is stored where? (Probably each device)

All device keypairs must be registered with with keybase.io.
Each device has a device key pair.
Devices share keys with each other as well? (provisioning)
It is possible to generate a paper key pair.
A device can be initialized with this paper key pair.

Is it safe to assume that when a new, shared-object is created... all those entities will need that key. So, when a git repo or a chat is provisioned, etc... the device doing this must encrypt the key for all those who are sharing. If a new device/team member is brought online, then they cannot participate until _at least one_ of the devices shares the key?

So, if I added a device after losing my laptop, it would not have the encrypted git key, correct?

**Comment by strib** [comment]
Your mental model is basically correct.  Private git data is stored in your private Keybase FS folder, and so the data is encrypted the same way as your regular files.  For more details about how the KBFS encryption works, where keys are stored, etc,  check out https://keybase.io/docs/crypto/kbfs.

> Is it safe to assume that when a new, shared-object is created... all those entities will need that key. So, when a git repo or a chat is provisioned, etc... the device doing this must encrypt the key for all those who are sharing. If a new device/team member is brought online, then they cannot participate until at least one of the devices shares the key?

Correct.  Though in these terms, a KBFS folder is the "shared object", not an individual git repo.

> So, if I added a device after losing my laptop, it would not have the encrypted git key, correct?

If the laptop was the only device, then yes, that is correct.

**Comment by maxtaco** [comment]
Also we use the NaCl library and therefore XSalsa20 rather than AES.

**Comment by drudru** [comment]
@strib - thanks this is helpful.
@maxtaco - thx - good to know.

I'll read up on KBFS later, but I think I have enough info to move forward now.
I will start using encrypted git, but also have another secure key-pair (probly paper).
Then I'll test it out.

Thanks 👍
