### ISSUE TITLE
Can't stop automatic starting on Ubuntu 16.04 Linux

### ISSUE THREAD

**Issue by ziyaddin** [keybase/client#9410]
There are no settings to choose whether I want automatic starting or not. Would be great to add that kind of functionality. Otherwise, there is no way to stop automatic starting of the program.

**Comment by maxtaco** [comment]
cc @oconnor663 for an update on this

**Comment by oconnor663** [comment]
@ziyaddin take a look at `~/.config/autostart/keybase_autostart.desktop`:

```
# Uncomment the following line to disable Keybase autostart:
#Hidden=true
```

Apologies for not having a setting for this in the GUI yet.

**Comment by ziyaddin** [comment]
@oconnor663 Thank you! No problem, it is not a big deal to disable it by using the mentioned method. The only issue is usability.

**Comment by dgw** [comment]
Just wanted to drop a note here, since I found this issue and checked `~/.config/autostart/keybase_autostart.desktop` to find terminal commands instead:

```
# To toggle autostart on, run
# `keybase ctl autostart --enable`
# or to toggle off,
# `keybase ctl autostart --disable`.
# Note that this will overwrite any changes you have made.
```

**Comment by heronhaye** [comment]
In Keybase 5.0, you can change this setting in the GUI on all platforms. Please make a new issue if you are still having trouble. Thanks!
