### ISSUE TITLE
Can't open my own private folder: Permission denied

### ISSUE THREAD

**Issue by heyarne** [keybase/client#9413]
I was trying to quickly transfer something between my laptop (macOS 10.12) and my Android Phone when I realized I don't have access to my private folder on my mac.

```
$ ls -l /keybase/private/
total 0
dr-x------  1 heyarne  wheel  0 Nov  7 13:42 heyarne
dr-x------  1 heyarne  wheel  0 Nov  7 13:42 heyarne,uberspace
$ touch foo.txt
$ mv foo.txt /keybase/private/heyarne/
mv: rename foo.txt to /keybase/private/heyarne/foo.txt: Permission denied
$ ls -l /keybase/public/
total 1
drwx------  1 heyarne  wheel  469 Aug 21  2016 heyarne
$ mv foo.txt /keybase/public/heyarne/
$ # works flawlessly so i try to correct the permission on my private folder
$ chmod -R +w /keybase/private/heyarne
chmod: Unable to change file mode on /keybase/private/heyarne: Permission denied
chmod: /keybase/private/heyarne: Permission denied
chmod: Unable to change file mode on /keybase/private/heyarne: Permission denied
$ sudo chmod -R +w /keybase/private/heyarne
Password:
chmod: Unable to change file mode on /keybase/private/heyarne: No such file or directory
chmod: /keybase/private/heyarne: No such file or directory
chmod: Unable to change file mode on /keybase/private/heyarne: No such file or directory
```

I recently set up this computer from a time machine backup. Maybe this has something to do with it? If i try put a file into the folder with Finder I get asked for my password and after a short while the transfer fails by telling me I have no permission.

Also:

```
$ cd /keybase/private/heyarne/
<E> fish: getcwd() failed with errno 13/Permission denied
<E> fish: Could not determine current working directory. Is your locale set correctly?
cd: Could not set PWD variable
<E> fish: getcwd() failed with errno 13/Permission denied
```

my log id: 15934f3dab08be9ef964ec1c

**Comment by strib** [comment]
@heyarne: Looks like you revoked all devices that previously had access to your private folder, and you added new devices after those old devices went offline.  Without a period of overlap between your old and new devices, there's no way to recover the data.

If you want us to reset your folder, please run this command on a currently-valid keybase device, and substitute the current date and time where indicated:

```
keybase sign -m "<DATE_AND_TIME>: Please reset folder /keybase/private/heyarne because all the devices that have access have been revoked."
```

and post the results here.

**Comment by heyarne** [comment]
BEGIN KEYBASE SALTPACK SIGNED MESSAGE. kXR7VktZdyH7rvq v5weRa0zkXsg3Qw fvMYWowasJJMoCD 1DplViutEA2CeCI KdEMWA97PiTFdZK 340XlnzMK6T476I xTiuZiVc9WrDYB6 V7r7iWrtFyFWdpm YHb8CtM8H7MtXO1 7tqSfhzRz1gRtM0 XHtImUubfjr703T 1v6lzmg4WdDCf8y 2SiexyLP0pJFl1l BEXVzWwsdK45PhS B6SRu7dLgij2E6Q 7hfhVzRamBU34IK XhYGjQqRxHFCSx4 u3yQQ9rj0oGCn6N 1PrJRDJWV07ujq3 fHRZfmjSf05JL9a UO2cTFPLRrSxQjM IV431aA7bHRDBo8 14BSvqPE5NYJQD5 xHMfaCHAEcoQTCs Ea3l7tJuShGNKV8 mBI6. END KEYBASE SALTPACK SIGNED MESSAGE.

**Comment by heyarne** [comment]
It is true that i revoked some of my earlier keys because i lost access to the devices they were connected with, as you can also see in my graph. i realized now that people also can't encrypt anything for me anymore: 

```
$ keybase pgp encrypt -m "ooooops" heyarne
  
  
▶ ERROR openpgp: invalid argument: cannot encrypt a message to key id 8bc45aa56264e016 because it has no encryption keys
```

How do I fix this? I thought by having my PGP key unchanged it would still work but apparently I was wrong.

**Comment by maxtaco** [comment]
Your PGP encryption subkey expired on 2017-10-05

You can update it locally using gpg and then push the public keybase to keybase with `keybase pgp update`.  Or the web site.

```
$ curl https://keybase.io/heyarne/pgp_keys.asc?fingerprint=6b6e6a698bd2d09557d19ee18bc45aa56264e016 | gpg --list-packets
:public key packet:
	version 4, algo 1, created 1444075577, expires 0
	pkey[0]: [4096 bits]
	pkey[1]: [17 bits]
	keyid: 8BC45AA56264E016
:user ID packet: "Arne Schl\xc3\xbcter <arne@schlueter.is>"
:signature packet: algo 1, keyid 8BC45AA56264E016
	version 4, created 1444075577, md5len 0, sigclass 0x13
	digest algo 10, begin of digest 40 5a
	hashed subpkt 2 len 4 (sig created 2015-10-05)
	hashed subpkt 27 len 1 (key flags: 03)
	hashed subpkt 9 len 4 (key expires after 2y0d0h0m)
	hashed subpkt 11 len 4 (pref-sym-algos: 9 8 7 3)
	hashed subpkt 21 len 4 (pref-hash-algos: 10 9 8 11)
	hashed subpkt 22 len 4 (pref-zip-algos: 2 3 1 0)
	hashed subpkt 30 len 1 (features: 01)
	hashed subpkt 23 len 1 (key server preferences: 80)
	subpkt 16 len 8 (issuer key ID 8BC45AA56264E016)
	data: [4094 bits]
:public sub key packet:
	version 4, algo 1, created 1444075577, expires 0
	pkey[0]: [4096 bits]
	pkey[1]: [17 bits]
	keyid: A5D6F3099BA9294B
:signature packet: algo 1, keyid 8BC45AA56264E016
	version 4, created 1444075577, md5len 0, sigclass 0x18
	digest algo 10, begin of digest 62 c1
	hashed subpkt 2 len 4 (sig created 2015-10-05)
	hashed subpkt 27 len 1 (key flags: 0C)
	hashed subpkt 9 len 4 (key expires after 2y0d0h0m)
	subpkt 16 len 8 (issuer key ID 8BC45AA56264E016)
	data: [4095 bits]
```

**Comment by strib** [comment]
@heyarne: I reset the folder.  Please check it out and close this if everything seems ok.  (Might require a Keybase restart.)

**Comment by mariusrugan** [comment]
hi @strib: i have exact the same problem, am a moron and revoked all other devices.

i ran a 
`keybase sign -m "<DATE_AND_TIME_AS_STRING>: Please reset folder /keybase/private/mariusrugan because all the devices that have access have been revoked because i am a moron."`

BEGIN KEYBASE SALTPACK SIGNED MESSAGE. kXR7VktZdyH7rvq v5weRa0zkHR3Gsu aGfs0FkcvwE3cg3 Iv8CFeCCojXLdbA dQ5vGiKt85mxJQ6 sT9ydaxERN4OiVk kPWg3B2jlXl7Hbf 8fB6fAJ6fZNIFKc ActAn9wHR0zU6cZ yruDhB1lenD3m09 ua6HtNHXeP21Q8V 3wUk75rT05HHNlD yU7Qh6QdvzCFS4p U2VCfVI9IGVWV89 m6KVmBQWiU9vXzB 8ReOeojKFTjsZc7 JuZGKQSBC3sUW91 pUNPSx6rEciW1I6 oTd0tbkm74CC2G8 TDX5zrUgVSE4vys bRqlz8i7udKATFB 6NmU8r8WpNOwWZE yMflvZdMopsYyJN ZKmSyHkJ1d80beR tzk3V91irUiyVQr iqgq1Wfm4UZt0D2 3MDCwMYi12EXs6. END KEYBASE SALTPACK SIGNED MESSAGE.

would you please reset this one too ?
thanks in advance.

**Comment by heyarne** [comment]
@strib Thank you very much. My issue is thereby mostly resolved – I do however still have a shared private folder (`heyarne,uberspace`) that was empty anyways and I now can't access it. Is there any way to remove it?

**Comment by strib** [comment]
@heyarne: `rmdir /keybase/private/heyarne,uberspace` should remove it from your list, or you can mark it as ignored on the folders tab of the Keybase GUI.

**Comment by strib** [comment]
@mariusrugan: I reset the folder.  Please check it out and close this if everything seems ok.  (Might require a Keybase restart.)

**Comment by mariusrugan** [comment]
it works, thanks a lot, @strib
