### ISSUE TITLE
Device problems

### ISSUE THREAD

**Issue by Biosias** [keybase/client#9428]
Hi, yesterday my only device with keybase app got corrupted and I had to wipe HDD and reinstall everything. Now I want to activate keybase app on this new installation but the app is telling me to confirm it on device (which got corrupted) with installed keybase app. I really don't know what to do.

**Comment by maxtaco** [comment]
If you don’t have any other active devices you have to reset your account.

**Comment by Biosias** [comment]
Thanks !
