### ISSUE TITLE
"Invalid device name"

### ISSUE THREAD

**Issue by j127** [keybase/client#9451]
I'm trying to login for the first time on Ubuntu 16.04 (64 bit) and it doesn't want to accept any device names. I've just created an account on the website and downloaded the client.

I enter various device names: 

![keybase2](https://user-images.githubusercontent.com/96479/32581657-a7b9eb74-c49f-11e7-90af-4f5e56c8eb4a.png)

It gave this error message no matter what I tried:

![keybase1](https://user-images.githubusercontent.com/96479/32581658-a7d92db8-c49f-11e7-9110-04905a588632.png)

After a few attempts, this error message was shown:

![keybase3](https://user-images.githubusercontent.com/96479/32581656-a78f5350-c49f-11e7-9547-4d4c818cc334.png)

my log id: f264d76cf7b220e241c6951c

**Comment by maxtaco** [comment]
Sorry about this, something is weird, and it's getting misreported as a bad device. @patrickxb do you have any ideas?

**Comment by agiantwhale** [comment]
Facing the same issue on RHEL

**Comment by maxtaco** [comment]
Megawhoops. It's a bug in our Linux build, the fix is in https://github.com/keybase/client/pull/9455 and we'll have a launch tomorrow. Thanks!

**Comment by oren** [comment]
the same issue on Ubuntu. Looking forward to try it again tomorrow.

**Comment by oren** [comment]
Also, i would suggest explaining what are the implications of public name. what does it mean and can i change it later on etc.. Thanks

**Comment by JeanFred** [comment]
I hit the same issue on Ubuntu 16.04. Thanks for the quick fix − looking forward to it!

**Comment by oconnor663** [comment]
We _just_ shipped a new Linux build that should fix this issue. Please let us know if anyone's still seeing it after updating to 1.0.35-20171109144506+0a5d2ba25.

**Comment by JeanFred** [comment]
@oconnor663 I can confirm the latest build (Ubuntu 64bits) solves the issue for me. Thanks!

**Comment by j127** [comment]
It works now, thanks.
