### ISSUE TITLE
I cannot access file i copied into my private keybase directory

### ISSUE THREAD

**Issue by tijs** [keybase/client#9478]
Keybase GUI Version: 1.0.34-20171027003854+8e989533a

I'm running the latest Mac OSX client on High Sierra and while managed to move files into my private folder in keybase whenever i want to get them out i get the following error. Please advise as i'd hate for those files to be lost. Can i mount the keybase directory in another way than the GUI app perhaps?

<img width="407" alt="screen shot 2017-11-10 at 16 37 24" src="https://user-images.githubusercontent.com/3108/32665714-881d4d0a-c635-11e7-82f6-65a2dfda9205.png">

**Comment by tijs** [comment]
Just tested this using the CLI as well but while i get a file listing the first time i do `ls -la` when i try to actually copy or move an of the listed files it does not work. After i've tried another `ls` tells me the folder is empty.

```
# tijs @ anwar in /keybase/private/tijs [16:45:54] 
$ ls    
ls: .: No such file or directory
```

Did i basically just trash all the files i put in keybase?

**Comment by strib** [comment]
Hi @tijs, can you please do a `keybase log send` from your device, and post the log ID here, so we can see what's going on?  Thanks!

**Comment by tijs** [comment]
@strib thanks, this is it: a49b7acae7e22a069593071c

**Comment by strib** [comment]
Looks like the same underlying problem as #8937 -- KBFS is crashing and restarting.

But you're running a newer version with more debugging inserted, so I might be able to get to the bottom of it now.

We can fix it by blowing away any local changes you've made that haven't been synced with the server yet, if you want, but it seems like there's a fair amount of it so that might not be a great option.  I will spend time now looking into it, and try to get a fix together.  If I do, I can make an experimental build for you to try, if you'd rather wait for that.

**Comment by tijs** [comment]
@strib thanks! i'd rather wait if that gives me a better chance to extract everything intact.

**Comment by strib** [comment]
Of course!  A wise choice.  I'll keep you posted.

**Comment by tijs** [comment]
i wouldn't mind a cli only version if you have such a thing btw. the gui does not add much for me as i'm not using the chat. just the file storage and perhaps the git support at some point.

**Comment by strib** [comment]
We don't have a mac package like that right now.  You could potentially write your own scripts to mount the `kbfs` binary youself, and run the `keybase` background service, but I don't have much guidance for you there.

**Comment by tijs** [comment]
hmm, i'll just wait 😊

**Comment by strib** [comment]
Hi @tijs.  I think I tracked it down (keybase/kbfs#1329).  Can you please try this build out?  https://s3.amazonaws.com/prerelease.keybase.io/darwin-test/Keybase-1.0.35-20171110225117%2B20869a537.dmg

If it works, your directory should be working again at most a few minutes after Keybase restarts.  If it doesn't seem to be working, please run `keybase log send` again and I'll take another look.

**Comment by tijs** [comment]
@strib yup that fixed whatever that was. thanks man.

**Comment by strib** [comment]
Huzzah!  The fix is now merged and will be in the next official release.
