### ISSUE TITLE
various errors and slow (MacOS)

### ISSUE THREAD

**Issue by moo-im-a-cow** [keybase/client#9538]
Hi
since i installed the client, it has been very slow to load anything,
when i send myself a chat message, i get "error creating conversation: timeout calling chat server"
when i try to create a git repository, i get "Unknown RPC Error"
the /keybase folder doesnt load. (tried enabling / disabling it through the client)
`$ cd /Keybase`
`cd: error retrieving current directory: getcwd: cannot access parent directories: Input/output error`
OSX sierra 10.12.6 (16G29)
Keybase client Version 1.0.34-20171027003854+8e989533a (1.0.34-20171027003854+8e989533a)

I have tried rebooting, quiting / reopening keybase, reinstalling keybase.

I have 2 log ids, (not sure if reinstalling keybase removed logs)
before reinstall: 3f4cc17afe79a3f85da2f71c
after reinstall: 9a385faed4b8362004e9541c

**Comment by maxtaco** [comment]
we had a service outage this morning, can you try it now? thank you

**Comment by moo-im-a-cow** [comment]
thanks, it seems to be working now
