### ISSUE TITLE
Deleted chat messages can be leaked

### ISSUE THREAD

**Issue by mgwalker** [keybase/client#9599]
In the MacOS desktop client, the most recent chat message sent to or received from a contact is shown under their username in the chat window.  If that is the only message in the chat and you delete that message, the preview still shows it  Screenshot attached to help clarify what I mean.  On left is the list of chats I have open - the top most is with myself.  In it, you see a snippet of the last message I sent ("boop").  On the right is the actual chat content, where I have deleted that message, which was the final message in chat.  The snippet, however, remains.

<img width="912" alt="screen shot 2017-11-16 at 9 31 57 pm" src="https://user-images.githubusercontent.com/1775733/32928154-38e5db68-cb16-11e7-8838-ff561e03c9f2.png">

If you completely quit the desktop app, the chat will be gone from the list on restart, which resolves the issue.  It's pretty minor, but it surprised me so I thought I'd log it.

**Comment by rltvty** [comment]
also seen on mac client today.  Can be a security issue if a secret was passed.
