### ISSUE TITLE
Can't chat with self on MacOS Desktop app

### ISSUE THREAD

**Issue by tripleee** [keybase/client#9603]
I was able to open a chat session with myself on my iPhone, but I cannot open the same session in the MacOS desktop Keybase app -- it shows my name when I search for it, but then when I click it, it says "Sorry, no humans match this" (like it does when you search for a phrase which doesn't match any username).

I have found this to be a useful feature in other chat applications for quickly sharing links and images between my phone and my desktop, so it would be nice if this could work.

**Comment by maxtaco** [comment]
This sounds like a bug, can you send feedback from the app? Thsnk

**Comment by tripleee** [comment]
@maxtaco I'm afraid I can't see how to do that. The app doesn't have anything like a help or feedback section (apart from the OS built-in help which doesn't seem to be populated -- searching for "feedback" in there only brings me general MacOS help topics, nothing related to this particular app).  Sorry if I'm missing something obvious ...?

**Comment by maxtaco** [comment]
Open your terminal and type `keybase log send`

**Comment by tripleee** [comment]
```
Success! Your log ID is:

  09be24f012ed4864c3b05e1c

Here's a URL to submit new bug reports containing this ID:

  https://github.com/keybase/client/issues/new?body=[write%20something%20useful%20and%20descriptive%20here]%0A%0Amy%20log%20id:%2009be24f012ed4864c3b05e1c
```

**Comment by maxtaco** [comment]
@mmaxim can you take a peak at this one?

**Comment by mmaxim** [comment]
That search is improved a lot in the release that is going out today, hopefully that will fix this problem. @tripleee are you running the search from the "Jump to Chat" input box?

![image](https://user-images.githubusercontent.com/1250314/33074467-52e91990-ce94-11e7-894a-e6200b713274.png)

**Comment by tripleee** [comment]
Seems to work now, I guess I got the new build?
