### ISSUE TITLE
Issues logging in with keys on smart card

### ISSUE THREAD

**Issue by jbergler** [keybase/client#9622]
Hey Team,

Similar to #2086 I can't seem to convince keybase that I have a key available for it to sign things.

```
% keybase login jbergler
▶ ERROR Sorry, your account is already established with a PGP public key, but this
utility cannot find the corresponding private key on this machine.
This is the fingerprint of the PGP key in your account:

   96E2 DE2B 3AE9 9269 CE32 5E07 DB6B E344 84B1 4344

You need to prove you're you. We suggest one of the following:

   - put one of the PGP private keys listed above on this machine and try again
   - reset your account and start fresh: https://keybase.io/#account-reset
```

Key is available
```
% gpg --no-tty --with-colons --fingerprint -K | grep 96E2
fpr:::::::::96E2DE2B3AE99269CE325E07DB6BE34484B14344:
```

And I can sign things with it.
```
-----BEGIN PGP MESSAGE-----

owEBfwKA/ZANAwAKAdtr40SEsUNEAcs4YgBaESw/OTZFMiBERTJCIDNBRTkgOTI2
OSBDRTMyIDVFMDcgREI2QiBFMzQ0IDg0QjEgNDM0NAqJAjMEAAEKAB0WIQSW4t4r
OumSac4yXgfba+NEhLFDRAUCWhEsQwAKCRDba+NEhLFDRKQHEACQzi25MeBG2LGi
VqG5HuM2gaHsTPdjW6ZNAREahpAz49eLH1K0Nbp41hzzdVd4Bp4KiEcSl0IkH1E7
fO9z6Pk22wslyNYYYyOqivyHSCDP6P3GYlidMTxBXftfubSq6gb5+zUsoEDrPScp
oY3VlEQ6fzRtQ8p8B+Emloqz2fu1RRIvENmctJ/HdsICDVbkhINleNSdsyz0ZbRg
5nLIgsmH0DBNDUV0+lYJBWyLaV1hIz9PlNNsykNlMv41BOZyq4LwmV6Z2XoBHREP
rbsGngsU680mi+rms6HEDF3eL21PKrsfhes+f7PE9pW3b2P7XKVcp+KYxmvqISZ8
alTChY0NzX0+fTyX6n9+0RQc0DbHDYGikCyn0Y/ChUqTjJlyHHZm5DlYoZ/mvHqs
VMSZpGQBtDZCZVOLVpy41FWdB4vYWY47GRThhQcUkKQxlSuhAvzdDB7XFw5iHTqp
xQ4UwyhRa7JzjAyOA6X7I0lUbVeLu/DjOWSY0tVK4+0SKaUhDOU+pu8uAzzLeat4
CNYAVgb0jplDC/E7bYasxMuq4X2xPZoYpj4zH9DT87aiy3MFgEocvyTgyozQB40Y
XOUCfYl7teTnOy1diZcLFmHprsKFIYR13AunGFJ3C7xMlBbOjdv3Kn61WJ8MpdXN
9H+POqnZmqffqYDpF9wFdydmP9BUkA==
=aSI1
-----END PGP MESSAGE-----
gpg: Signature made Sat Nov 18 23:01:23 2017 PST
gpg:                using RSA key 96E2DE2B3AE99269CE325E07DB6BE34484B14344
gpg: Good signature from "Jonas Bergler <jbergler@meraki.com>" [ultimate]
gpg:                 aka "Jonas Bergler <jonas@meraki.com>" [ultimate]
gpg:                 aka "Jonas Bergler <jonas@bergler.name>" [ultimate]
gpg:                 aka "Jonas Bergler <me@jonasbergler.com>" [ultimate]
Primary key fingerprint: 96E2 DE2B 3AE9 9269 CE32  5E07 DB6B E344 84B1 4344
```

`Success! Your log ID is: ebc68e408f1ed2f19062031c`

**Comment by maxtaco** [comment]
Can you share with me the output of:

```
/usr/local/bin/gpg --no-tty --with-colons --fingerprint -K
```

?  If so then we can try to debug it.  You can encrypt it for me if you'd like

**Comment by jbergler** [comment]
@maxtaco ```-----BEGIN PGP MESSAGE-----

hQIMA2BSsq0xpmMcAQ//Zxp/lXBGgZM6uWvBfE3bB+VVY1Gt+sXAhesL74gamAJa
74nSK0Vo9YTb1YR/k6KWyzS8aL77zTDwYgkKiSdFp0+DceQhTDMTs9/IFuj7PnEM
m0bOxuo+GA337KGCKyjwu9AQEBVdvCgkzsQN0ySVLtUW679iosE9CECOYksHGuMR
j10ZUu/CYQurQ7C6xtabtTdGbGx6jKLqx3XTZ8+dVFkrexe2eD7/+XX0ff4F7NfR
wMwlP1bBLMlfwhVlwF5b8+TYSjTPqBNxKtm0eH6nYyrbg/C1/zIB+lgHOmtqkV60
Ndy/mXDcB4vLsERIcMtyN1jl6dTdq5ZD/a8R5IhF3+nOpHnf3b5sb1iUjKtcusbi
p+38OG6dN/YxpNxCjTvOf8z0GrcGhst2wpl6FZsNZcoYRRdvAMPscDfW+rwoLu4m
hVZUeRplr1sCporUbpsuI0p+gHAN4VtCOMCpFq+xygLq8LWBUoBZkaFU10OXnSHh
bozpgKuvSHWpTeMJK62PFuNgD7GmIiWOWNicOySv9RKRbh2q07c1SRDvicKkA4F/
WxVwKNvBj9fkgJmDXGkDg+iM0pgKsM/XWKzB/QBpxrXj7cwcYyo4YmnqeumKmAdJ
nE26MPuSjAgE2/VMH8ipxU+9LJXOGIic+EzhobnIArl+jp33jGEQ5Rc0ZddCXbHS
6QG1isdwcMl6XMuhY0Sri+LIDlefmVsOQwVNyaIGD8eJGroH/iiuKJVEDPOhMZUu
0aj/yOywp9kWQhcX6eI1sI389Vg0mr0kkTj+n+Sn2QvHJzttZuLgzpVRsmhxx7n0
lAYB3nYm2qVvZV/ZMxQX28lRhQe3KgUfi0CAOzXbVdaCQeTOBBW9c4ckuFkJi8P3
yIjU9aICQFEppAhxqyacR1cyKEMCreej6bQcsHXM+gn3n/NcyVf5XLxt8vRsuBW+
RSGWPsqgqRxKeBlLV+CUk/ujNR0wFOpvYlnMZ7/V+JyZzgPV+LqQVIb7pjmObaaC
MjKiOdBZ2dH0Ns6YUQr8qBsjc/yctbvvRPPN0OP/bVfXsEEh8ioDDzhA1zG+0h2i
QwopFzqK5RNatf+yKC/uHLrf2RocZpns/BV9WTKhHB1JtmhDFTCRkt3RF5HIfeg4
LPCAEZ5AhaUvtUvbbZdurv5qKW4evmLzcaFJjqoC6mXQrcvs2TNkEXYZkSyExJhM
VQDS23zTx9qNF/Jn+IxqTVn259PN3yJnVpAalXaeUtidW81yoXPm+MA4l2vvmnt1
5ddIkrvmPZcyNPxpyhUWEbUx311Cd2l2N4G1PEEqeb8kuM4MoK/OXTWjpJD2NePz
HaHX8t9yPvwPYgKd5LSUtM4FkI65QKx9YXqKUzNSpNZCZxyCaGbvLyaJiBvIhfKs
A9tezUHOaEWjmhw8QD0V+LYiaCcUwDgBMZloQHBwrJQbc5jHjU2RNldA3g3Uo1id
stk7aB7GMicso02ANWT5Tv4VDVpKw9qxp8wQ5HV6odt9eBPLjChiz6c=
=2ujY
-----END PGP MESSAGE-----```

**Comment by maxtaco** [comment]
thanks @jbergler; and you're sure it's not an issue of having two `gpg`s at two different paths, and we're picking the wrong one (in `/usr/local/bin`?)

**Comment by maxtaco** [comment]
Eh, looks like I can repro, a bug somewhere in our parsing the output... Investigating...

**Comment by maxtaco** [comment]
No, I take it back, everything seems fine.  My best bet is two GPGs under two different paths, and the Keybase app is finding the wrong one.

**Comment by jbergler** [comment]
I thought of that over the weekend and set ```% keybase config get
{"gpg":{"command":"/usr/local/bin/gpg"}}```

**Comment by maxtaco** [comment]
What does ‘which gpg’ say?

**Comment by jbergler** [comment]
```
% which gpg
/usr/local/bin/gpg
```

**Comment by maxtaco** [comment]
Pretty vexed here.  @zapu step in if you have any ideas.

@jbergler  when you run `gpg -K` from the terminal, does it prompt you for a passphrase?

Also, what happens if you run `keybase login` from the prompt?

**Comment by zapu** [comment]
Hello! Would you mind trying

```
/usr/local/bin/gpg --no-tty --with-colons --fingerprint -K
echo $?
```

Sometimes gpg returns status `2` and it trips the parsing code. I don't remember if it's visible in log file or not, though

**Comment by maxtaco** [comment]
(@zapu BTW that decrypted output is in the JIRA ticket)

**Comment by maxtaco** [comment]
(which seems totally as expected)

**Comment by jbergler** [comment]
```
% /usr/local/bin/gpg --no-tty --with-colons --fingerprint -K > /dev/null; echo $?
0
```

**Comment by jbergler** [comment]
Also, `gpg -K` doesn't prompt for a password.
`keybase login jbergler` goes through the flow where the Keybase UI prompts for my Keybase password, and then results in that error in the terminal.

It's possibly worth pointing out that I have two smart cards, one has my master signing key (for the key fingerprint that keybase wants). The other has the keys `AF71E67CB14833A5` `0B0E533016C4D661` and `D0F5626D806531BA`

**Comment by maxtaco** [comment]
Which of them were available when you ran the above `gpg -K` by hand and sent me the output?

**Comment by jbergler** [comment]
```
~/Dropbox/Keys/gpg % gpg -K
/Users/jbergler/Dropbox/Keys/gpg/pubring.gpg
--------------------------------------------
sec>  rsa4096/DB6BE34484B14344 2014-12-30 [SC] [expires: 2019-08-30]
      Key fingerprint = 96E2 DE2B 3AE9 9269 CE32  5E07 DB6B E344 84B1 4344
      Card serial no. = 0005 00002ABA
uid                 [ultimate] Jonas Bergler <jbergler@meraki.com>
uid                 [ultimate] Jonas Bergler <jonas@meraki.com>
uid                 [ultimate] Jonas Bergler <jonas@bergler.name>
uid                 [ultimate] Jonas Bergler <me@jonasbergler.com>
ssb>  rsa2048/AF71E67CB14833A5 2014-12-30 [S] [expires: 2018-08-30]
ssb>  rsa2048/0B0E533016C4D661 2014-12-30 [E] [expires: 2018-08-30]
ssb>  rsa2048/D0F5626D806531BA 2014-12-30 [A] [expires: 2018-08-30]
```

**Comment by maxtaco** [comment]
So one thing I noticed is that you don't keep your keyring in a standard place, you keep it on dropbox. Are you setting any environment variables to tell GPG this?

**Comment by maxtaco** [comment]
Assuming this is the problem (which I think it likely is), you can solve it in one of a few ways:

# Configure `launchd` to set the same GPG environment variables as you do for your shell.
# Hand-edit your `config.json` file to set `"gpg" : { "options" : [ "--home", "/path/to/your/home" ] }` or some such, and then `killall keybase`.  We don't have a good `keybase config set` subcommand for making an array JSON value, we haven't needed it yet.

**Comment by jbergler** [comment]
Ah, interesting - yes I configure gpg from my environment
```
% env | grep GNUPG
GNUPGHOME=/Users/jbergler/Dropbox/Keys/gpg
```

Setting that option in the json file worked, I'm now able to login correctly.
I'll accept this as an advanced 'feature' for now - thanks for the help
