### ISSUE TITLE
Team chat - Error unboxing chat message

### ISSUE THREAD

**Issue by unlocKing** [keybase/client#9627]
After resetting my keys, I can no longer access teams I was a co-owner of, a message appears "Error unboxing chat message..."

I have been added back as an owner.

my log id: 90a1cbdeade36718c9f5c11c

**Comment by maxtaco** [comment]
cc: @malgorithms /  @mmaxim

**Comment by maxtaco** [comment]
@unlocKing why did you reset your account?

**Comment by unlocKing** [comment]
Sorted now..

Thanks Max.
