### ISSUE TITLE
That domain isn't loading. Are you running a site there?

### ISSUE THREAD

**Issue by ennorehling** [keybase/client#9662]
I received notification that my proof for wiki.eressea.de stopped working after updating my TLS certificate this weekend. The proof is still in place, but nevertheless, I tried the "Replace" option, and it gave me this error message: That domain isn't loading. Are you running a site there?

The site and proof load fine in a browser from several locations. Something wrong on your end, maybe?

**Comment by RoryH** [comment]
Seeing the same problem here. Modified TLS configuration on my site recently, and now getting the same symptoms as above.

**Comment by etu** [comment]
I recently (few months ago) changed email for my TLS certificate using Let's Encrypt, the crypto, webserver and webpage is all the same. Just changed email.

And today Keybase told me that the proof is gone, but I can look at it here: https://elis.nu/keybase.txt

And when doing a replace I get the same message as above: `That domain isn't loading. Are you running a site there?`

**Comment by RoryH** [comment]
For the record, my problem turned out to be badly configured SSL, when I corrected everything keybase was happy again.

**Comment by ennorehling** [comment]
@RoryH : badly configured how? My site is still "not loading", and I do not see what's wrong with the SSL configuration.

**Comment by x2on** [comment]
Here the same problem, site works fine with Let's encrypt cert in browser, but on Keybase there is "That domain isn't loading. Are you running a site there?" error...

**Comment by maxtaco** [comment]
Hey guys. We got hit by a node v8 bug. We will get a fix out hopefully
today. Thanks for the report

Which urls btw?

**Comment by x2on** [comment]
My proof is https://felixschulze.de/keybase.txt

**Comment by maxtaco** [comment]
Might be fixed, try it now?

**Comment by x2on** [comment]
Looks like it works now. My domain is back in the keybase portal without any action from my side.

**Comment by maxtaco** [comment]
Great, glad it's fixed.This was the bug: https://github.com/nodejs/node/issues/16196

**Comment by ennorehling** [comment]
Still not fixed for me. Site is https://wiki.eressea.de/

**Comment by maxtaco** [comment]
Doesn’t load in my browser either.

**Comment by etu** [comment]
@ennorehling I suggest taking a look at your certificate chain here: https://www.ssllabs.com/ssltest/analyze.html?d=wiki.eressea.de&hideResults=on&latest, it seems to be incomplete.

A simple way I use to test if the chain is complete or not is to try it with curl. Desktop browsers tend to compensate for that in some way. But curl, mobile browsers and many others doesn't.

**Comment by ennorehling** [comment]
You're right, the certificate chain was messed up. That fixed it!
