### ISSUE TITLE
Source build instructions

### ISSUE THREAD

**Issue by zenmetsu** [keybase/client#9672]
I was not able to find build instructions within the codebase.  Are these available somewhere?  I'm mainly a C/C++ guy and not too familiar with Go yet, so be gentle.  I'm attempting to improve the current Gentoo ebuilds for this package which seem to not be building the desktop app.  While commandline keybase is fine for some functions, it is not exactly the best choice for team communications.

As far as I can tell, the GOPATH in the ebuilds is being set, and then keybase is built with `go build -v -x -tags production -o "${T}/keybase" github.com/keybase/client/go/keybase`    Is there something else required to get the desktop app to build?

**Comment by maxtaco** [comment]
Cc @oconnor663

**Comment by oconnor663** [comment]
Take a look at what the Arch Linux `keybase-git` package does to build for source: https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=keybase-git

There's also the `keybase-bin` package, if you just want to unpack our Debian packages for the binaries: https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=keybase-bin

**Comment by zenmetsu** [comment]
Thanks.  I'd prefer not to toss a bin in here, as I said, I'm trying to improve the existing gentoo ebuilds.

It appears that the build method that I mentioned above fails to generate the desktop app, even when kbfs and electron are present on the system.  If I build using the method used by Arch, it "works", but I do notice that it has to be a git pull... downloading the tarball, even from git, means that that build_binaries.sh script fails.  This presents a problem because of gentoo's build process.  The binaries all end up under /tmp as well, which will result in somewhat messy build scripts for this distro.  I'll have to read through the build_binaries.sh script and see if I can emulate that to some extent in my ebuild.  

I love the app on android/windows... it just feels like a little love could be given to the build process and documentation.  Since I have enough info to put together a solution, I'll close this issue in 48hrs and give folks a chance to chime in with suggestions on building.

**Comment by oconnor663** [comment]
The tarball issue sounds like a bug we might be able to fix in `build_binaries.sh`. Let me take a look.

For the `/tmp` issue, you can pass a second argument to `build_binaries.sh` that tells it where to build.

**Comment by oconnor663** [comment]
Ok, there are basically two things we do with `git` commands:

- We find the root of the current project. That was mainly to be robust to this script getting moved around in the repo, but I think we could easily replace it with a hardcoded `../../` sort of thing.
- We figure out the current commit for both client and kbfs, so that we can build a version string out of it. We could add a pair of environment variables that let you override this, so that git is never called. Hopefully your build scripts already have an idea of what version they expect to build, and they can export these variables without too much extra trouble?

Does it sound like those changes would work for you?

**Comment by zenmetsu** [comment]
Allowing the user to pass parameters to the build script would probably be beneficial, but in looking over the build script I think that I have a good enough understanding to move forward.  I'd likely just apply a patch to modify the build_binaries.sh script in-place prior to compiling to make it fit this repo's development environment.  

Thanks for the input, you gave me what I needed.  If you feel that there is merit in updating the build scripts for general use, then have at it, but gentoo and its derivatives are a bit of a corner case and it really should be up to the distro's package maintainers to deal with that.

**Comment by oconnor663** [comment]
That is *incredibly* generous of you all :)

**Comment by zenmetsu** [comment]
I don't speak with any official capacity.  I am only a user that is planning on putting a new ebuild together for my own repo.  There is an official package for gentoo, but as I mentioned above, it has issues that I am trying to resolve.  That maintainer may wish to hit me upside the head with a brick for being so "generous"  :D 

I'll go ahead and close this issue.  Thanks again.
