### ISSUE TITLE
"Cannot manage implicit team by name"

### ISSUE THREAD

**Issue by vrinek** [keybase/client#9675]
I'm seeing this error when using the GUI. Functionality of the few features (git + profile) I use is not affected:

<img width="801" alt="screen shot 2017-11-24 at 14 19 59" src="https://user-images.githubusercontent.com/81346/33212335-e20a16b6-d122-11e7-98ab-feb1e7bdc197.png">

* Keybase version 1.0.36-20171122003217+f68b10ef8
* macOS 10.13 High Sierra

Any pointers on how to debug this?

**Comment by maxtaco** [comment]
Can you send `keybase log send`

CC: @mmaxim, we've seen this one before, remind me why it happens?  I thought we had fixed it before the release....

**Comment by vrinek** [comment]
@maxtaco sent! Log ID `a1383ae0344c2fde5826811c`

**Comment by vrinek** [comment]
4 years ago this was relevant. I doubt it's relevant now. Closing.
