### ISSUE TITLE
Can't access private folder, or setup encrypted git repo.

### ISSUE THREAD

**Issue by bmv437** [keybase/client#9681]
Hey there,

I get this error when I try to open my private folder, or try and setup and encrypted git repo. Everything else like chat, modifying my public folder contents, etc seems to work find.

```
ERROR This device does not yet have read access to directory /keybase/private/bmv437, log into Keybase from one of your other devices to grant access
```

The device it's referring to (`bvandegrift-isobar-mac`) had a harddrive failure, and I no longer have that key. I also had the unfortunate luck of writing down my paper key incorrectly (`toxic deposit`), so I couldn't use that to recover. [See the graph here](https://keybase.io/bmv437/graph)

How can we fix this?

Thanks,
Brandon

**Comment by strib** [comment]
Without a valid device (either computer, mobile phone, or paper key) that has access to the folder, the data in the folder is lost, I'm afraid.  We can reset it completely to get Keybase usable again, if you're sure it can't be recovered.  If you want us to reset your folder, please run this command on a currently-valid keybase device, and substitute the current date and time where indicated:

```
keybase sign -m "<DATE_AND_TIME>: Please reset folder /keybase/private/bmv437 because all the devices that have access have been revoked."
```

and post the results here.

**Comment by bmv437** [comment]
You can reset it, thank you!

```
BEGIN KEYBASE SALTPACK SIGNED MESSAGE. kXR7VktZdyH7rvq v5weRa0zkItBEPR 9hGYPLVwSokOp9E FpdCRdQJP5mJsAK WO0EWpmSCUhZKkt kuSXZGcgEDHHDcX tFiaLLwusZgjTts 3fnu6GI1PUZrDls Pc2pa9ubm87dd6v hAYg0nj7jRJPCTo sA5XwnfXxcQdB7D 91oCmKLXIUp6FG4 7KQBIKp76WpWvjK RmrCo7Jd1yObBYj Sm07QO2VbByGCPC MOpuQKDVGkyShnj CHkYvgAVbq49opC RftRbFrE7oUgMvE AxX7JunbqarnNqG hAJxX5pU90ZA2XP ZRIbbJ0l0xLt9F8 rEHI19fUppUyXwi W8JSIUXLldmzmI8 QLmOsg. END KEYBASE SALTPACK SIGNED MESSAGE.
```

**Comment by strib** [comment]
I reset the folder.  Please check it out and close this if everything seems ok.  (Might require a Keybase restart.)

**Comment by bmv437** [comment]
Yup, that worked. Thank you!
