### ISSUE TITLE
Dependency weirdness w/ vendored "context" library

### ISSUE THREAD

**Issue by waynr** [keybase/client#9682]
Someone sent me an encrypted message and it's been a while since I had keybase running on my computer so I decided to try building it. To do this I eventually happened upon these build instructions: https://github.com/keybase/client/tree/master/go#building

Unfortunately, I got this incomprehensible nonsense:

```
zsh/3 5703 % go install -tags production github.com/keybase/client/go/keybase
# github.com/keybase/client/go/teams
src/github.com/keybase/client/go/teams/handler.go:19: cannot use func literal (type func("context".Context, int) error) as type func("github.com/keybase/client/go/vendor/golang.org/x/net/context".Context, int) error in argument to RetryOnSigOldSeqnoError
src/github.com/keybase/client/go/teams/handler.go:131: cannot use func literal (type func("context".Context, int) error) as type func("github.com/keybase/client/go/vendor/golang.org/x/net/context".Context, int) error in argument to RetryOnSigOldSeqnoError
src/github.com/keybase/client/go/teams/handler.go:250: cannot use func literal (type func("context".Context, int) error) as type func("github.com/keybase/client/go/vendor/golang.org/x/net/context".Context, int) error in argument to RetryOnSigOldSeqnoError
src/github.com/keybase/client/go/teams/rename.go:40: cannot use func literal (type func("context".Context, int) error) as type func("github.com/keybase/client/go/vendor/golang.org/x/net/context".Context, int) error in argument to RetryOnSigOldSeqnoErro
```

It looks like a conflict between vendored and standard library dependencies. This seems to fix the problem:

```
sed -ie 's/\"context\"/\"golang.org\/x\/net\/context\"/' $(grep -rl '\"context\"')
```

Run from the root of `$GOPATH/src/github.com/keybase/client` after running `go get github.com/keybase/client/go/keybase` per the instructions linked above. Of course it's necessary to undo the resulting changes in https://github.com/keybase/client/tree/master/go/vendor/golang.org/x/net/context

I don't know jack about go or why it's necessary to vendor dependencies like this. From an outsider's perspective it looks like a total mess.

**Comment by maxtaco** [comment]
Need a newer version of go

**Comment by waynr** [comment]
@maxtaco here's the output of `go version`:

```
go version go1.8.1 linux/amd64
```

How much newer should I aim for?

**Comment by waynr** [comment]
Also, even if it's true that I need a newer version of go to avoid the problem described in my original message, the documentation does say

> You need to have both Git and Go 1.8 or higher installed.

**Comment by maxtaco** [comment]
Ok the doc is out of date.  I think you now need 1.9. It snuck in since we
all use 1.9.  We will update the docs. Sorry about that.

**Comment by waynr** [comment]
I've confirmed that using go1.9.x solves my problem, thanks for the help!

**Comment by maxtaco** [comment]
We've updated the docs too.  Thanks for your feedback
