### ISSUE TITLE
Exit/Quit doesn't work

### ISSUE THREAD

**Issue by gjedeer** [keybase/client#9709]
Reproducing (xubuntu 16.04)

1. In main window, go to File - Quit - the icon is still next to your clock.
2. Click icon - another smaller window pops up (not sure what it's for) - click hamburger menu, then click quit
3. Icon disappears 
4. Program is still running

```
➜  ~ ps  x |grep keybase
23647 ?        Sl     0:00 keybase -d --log-file=[redacted]/.cache/keybase/keybase.service.log service --auto-forked
23648 ?        Sl     0:00 kbfsfuse -debug -log-to-file /keybase
```

Suggestions:
1. Rename File-Quit to File-Close or make it actually quit keybase
2. Kill all leftover processes before actually exiting keybase

**Comment by heronhaye** [comment]
(On Linux)
`run_keybase -k` will shut down all Keybase processes unconditionally (service, kbfs, gui, redirector).

There's more information available at https://keybase.io/docs/linux-user-guide. Let me know if these features aren't working for you or if you have a question or suggestion.

The second flow you describe with the hamburger menu->Quit app should work in the next release, it's a bug that it doesn't.

**Comment by gjedeer** [comment]
Okay, run_keybase -k seems to do the job.

On a  similar note (let me know if I should open another bug): it doesn't seem to be possible to not have Keybase set to autostart and just run it manually. When I stop the keybase systemd user services, run_keybase doesn't work. I need to enable them every time I want to run it. Is there a workaround?

**Comment by heronhaye** [comment]
`keybase ctl autostart --disable`
to turn off xdg autostart.

We do not `enable` any systemd services by default, in favor of using xdg autostart to run `run_keybase` so it can be used on systems without systemd.

So if the behavior you want is Keybase should not autostart when you login, but you want `run_keybase` to start it up when needed, the first command listed should do the trick. You can `systemctl --user disable keybase kbfs keybase.gui keybase-redirector` to disable the systemd units as well, if you enabled them manually.

>When I stop the keybase systemd user services, run_keybase doesn't work. I need to enable them every time I want to run it.
Can you explain more what you mean by this? Do you mean stopping/starting or disabling/enabling? What is the output of `run_keybase` when it doesn't work?

**Comment by heronhaye** [comment]
Keybase 4.0 has a Quit Keybase button in the main app in the GUI.

![2019-05-08-164233_367x601_scrot](https://user-images.githubusercontent.com/28712558/57407074-5671eb80-71b0-11e9-9713-581f9baa3808.png)

Also, `keybase ctl stop` should work as expected on Linux.

**Comment by gjedeer** [comment]
I've never enabled the units manually. I learned about their existence when trying to get rid of background keybase processes.

I've quit keybase, unmasked the services (not enabled), upgraded to 4.0, ran as advised:

    keybase ctl autostart --disable

then started keybase:

```
$ run_keybase 
Starting via systemd...
run_keybase: Success!
(squirrel)
```

and after using Quit from the 🍔 menu I can confirm: no more background processes, you guys finally made it!
