### ISSUE TITLE
Cannot import pgp subkey

### ISSUE THREAD

**Issue by cdanger** [keybase/client#9714]
Hello,
I want to select a PGP subkey for Keybase but command 'keybase pgp select' does not allow me to. It only allows to select the master key.

```
$ keybase pgp select
#    Algo    Key Id             Created   UserId
=    ====    ======             =======   ======
1    4096R   7577CAAD0382346F             cdanger <cdanger@users.noreply.github.com>
```

```
$ gpg2 --list-secret-keys
`sec#  rsa4096/0382346F 2017-11-06 [SC]
uid         [ultimate] cdanger (GitHub) <cdanger@users.noreply.github.com>
ssb   rsa4096/C7C57BF5 2017-11-06 [E]
ssb   rsa4096/D00B62B1 2017-11-07 [S]
ssb   rsa4096/866A3457 2017-11-07 [A]
```

How to fix this?

my log id: 10c344519b7fc541ad94551c

**Comment by maxtaco** [comment]
If you just want to advertise this PGP key in your profile, then try `keybase pgp select --no-import`

**Comment by cdanger** [comment]
Same issue with --no-import option. It only allows to select the master key [SC]. Subkeys (flagged *ssb* above) are not available for selection.

**Comment by maxtaco** [comment]
That should be OK.  You'll sign your keybase ID with that subkey, and it will be linked to the offline master, thereby proving you own the offline master.  This works and we've tested it.

**Comment by cdanger** [comment]
The issue - besides advertising in my profile - is that I cannot use the `keybase pgp encrypt/decrypt` commands with the subkeys because I cannot make them available for use with `keybase pgp select`.

**Comment by maxtaco** [comment]
It's extremely challenging for us to support all of PGP, and we see diminishing returns past what we do already support. I'd recommend using good old `gpg` for encrypt/decrypt in your configuration.

**Comment by cdanger** [comment]
Alright then, I can leave with that, closing the issue. Thanks for the prompt reply :-)

**Comment by maxtaco** [comment]
You're welcome!
