### ISSUE TITLE
Encrypting files for teams.

### ISSUE THREAD

**Issue by funnylookinhat** [keybase/client#9717]
I'm not sure if this simply isn't documented or not supported.  Given that I've created a team called "foobar", I would expect to be able to do something like the following:

`keybase encrypt foobar -i myfile -o myfile.keybase`

This complains about the team foobar not existing.  I've also tried other obvious ideas like `keybase encrypt team/foobar` to no avail.  Is this supported?  Is there a command to do this?

**Comment by maxtaco** [comment]
good point, cc: @oconnor663

**Comment by oconnor663** [comment]
It's not yet supported. Teams were invented after the last round of changes to the saltpack format, and we haven't gone back to add support for them. But it's on the list of missing teams features, and we do plan to do it.

**Comment by brainstorm** [comment]
We would be super interested to have this feature in for our [terraform/team infrastructure](https://www.terraform.io/docs/providers/aws/r/iam_user_login_profile.html) :)

I wonder if just wrapping the way issue https://github.com/keybase/kbfs/issues/774 encrypts data for multiple users as a shortcut for this feature would work or if it's a bit more involved?

/cc @reisingerf

**Comment by scottrigby** [comment]
@maxtaco Curious where that landed?

**Comment by maxtaco** [comment]
```keybase encrypt``

**Comment by funnylookinhat** [comment]
Awesome!

For anyone who lands on this thread - you can specify `--team` now as a target:

```
$ keybase encrypt --help | grep "\-\-team"
  - Team encryption, available through the "--team" flag, encrypts the message
   --team [--team option --team option]	Encrypt for a team. Can be specified multiple times.
```

**Comment by scottrigby** [comment]
Ah, this has been done since last July 😻 💯  https://github.com/keybase/client/pull/12724

**Comment by Engelberg** [comment]
To decrypt a message encrypted for a team, do you have to specify the team name to the decrypt command, or does keybase automatically know that you are a member of the team in question?

**Comment by AMarcedone** [comment]
No need to specify the team to decrypt.
