### ISSUE TITLE
add new device

### ISSUE THREAD

**Issue by ludo-g** [keybase/client#9744]
Keybase GUI Version: 1.0.36-20171130170056+7bb3376d1
Hi,

I can't add a new device in same OS (ubuntu).
On my other computer, I have my window with code...
On my principal computer, I put the code : or the submit button doesn't work, or it submited but nothing happening after, or just now I'm in the same screen, blocked...

**Comment by maxtaco** [comment]
Can you run `keybase log send` on both machines?

**Comment by dwaindibbley** [comment]
I have the same problem

**Comment by maxtaco** [comment]
If you do ‘keybase log send’ from both devices we will debug it

**Comment by jerodg** [comment]
I am experiencing the same issue. The QR scanner on my phone says it captured a code even if I point it at the floor. The text codes don't work on the phone or my laptop. It doesn't say anything went wrong it simply does nothing.

log_id: 20f0aefb1df20e902d19ca1c  (from new device trying to activate) Windows 10
log_id: df3f93bf50a66e97e8e7b11c  (from activated desktop) Windows 7

**Comment by jzila** [comment]
@maxtaco, the logs are now available: ^

**Comment by maxtaco** [comment]
@jerodg your clock is way off, and that's preventing you from using our service.

Did you see any error messages to this effect?

**Comment by maxtaco** [comment]
@jzila: never heard back from @dwaindibbley and @jerodg just jumped onto an unrelated ticket.

closing this one out, we've solved a bunch of problems with provisioning. if it's still a problem, we'll see more tickets.
