### ISSUE TITLE
SentinelOne Flagging Keybase app on Windows as mailicious?

### ISSUE THREAD

**Issue by ebekker** [keybase/client#9764]
I'm opening this ticket to see if anyone else is experiencing this or can confirm, is anyone else finding that SentinelOne (a/v software) is flagging Keybase as malicious and quarantining it?

**Comment by zanderz** [comment]
What message are you getting exactly? The currently shipping installer shows up clean for 65/65 engines on VirusTotal: https://www.virustotal.com/#/file/1d4a5381ce23b44b855cd856214530d79b5b703bee35e4191f9bcac76c433f27/detection

**Comment by heini** [comment]
See also #8895. Same issue, different AV.

**Comment by ebekker** [comment]
I worked with Sentinel One and our local admin to simply whitelist the app.
