### ISSUE TITLE
This word is invalid, paper key problem 

### ISSUE THREAD

**Issue by Ociramma** [keybase/client#9804]
I had broken my screen month ago and got locked out from Keybase. Today I've managed to replace the screen, create paper key and decided to flash new ROM on phone. But I'm not able to login with my paper key now, I get "Bad passphrase: Please try again. This word is ivalid: grind.". But I'm pretty sure I made no mistakes while rewriting code.. And there aren't any similar looking word to grind, that I've could have misteken it with. I was distro hopping and have no access to my other devices (old phone ROM and old distro on PC), so I have no chance of recovering my account and git?

**Comment by maxtaco** [comment]
Check the “bip39” dictionary for the set of acceptable words.  There is
likely a word that is one edit distance off from the word you wrote down.

**Comment by Ociramma** [comment]
So I can't even write few word without mistakes after all. And I've found my word in dictionary, thank you !

**Comment by maxtaco** [comment]
Yes! Glad it worked!
