### ISSUE TITLE
Lost 250 GB of space on the Disk (Linux Ubuntu) SSD

### ISSUE THREAD

**Issue by computerluca** [keybase/client#9832]
After installing Keybase i noticed that my free space of the disk has decremented enormously.
So i run df -h and I noticed a new partition of 250 GB !!!!!!! and I lost 250 GB of space on the Disk. 
I uninstalled keybase, but the space has not been reclaimed.

**Comment by strib** [comment]
That was not a new partition on your local drive.  It is 250 GB of new space that we give you for free, that is stored in the cloud, not locally.
