### ISSUE TITLE
run_keybase gives " Process /bin/false exited with status 1" on CentOS 7

### ISSUE THREAD

**Issue by thejpster** [keybase/client#9847]
Keybase updates itself in the background and I don't use it much. Today I ran the CLI and it had to restart the service. On restarting it said:

```
$ keybase device remove "XXX"
▶ WARNING Restarting after upgrade; service is running v1.0.36-20171201172100+492737ab8, while v1.0.37-20171206230413+e6b362a87 is available
▶ INFO Restarting service...
▶ INFO Starting keybase.service.
Failed to restart keybase.service: Process /bin/false exited with status 1
See system logs and 'systemctl status keybase.service' for details.
▶ ERROR Failed to start keybase.service.
▶ ERROR Error in spawning server process: exit status 1
▶ ERROR exit status 1
```

I've tried uninstalling and re-installing and I get the same error:

```
$ sudo yum install https://prerelease.keybase.io/keybase_amd64.rpm
Loaded plugins: auto-update-debuginfo, fastestmirror, langpacks
keybase_amd64.rpm                                                                                                      |  93 MB  00:00:06     
Examining /var/tmp/yum-root-st5A7Q/keybase_amd64.rpm: keybase-1.0.37.20171206230413.e6b362a87-1.x86_64
Marking /var/tmp/yum-root-st5A7Q/keybase_amd64.rpm to be installed
Resolving Dependencies
--> Running transaction check
---> Package keybase.x86_64 0:1.0.37.20171206230413.e6b362a87-1 will be installed
--> Finished Dependency Resolution

Dependencies Resolved

==============================================================================================================================================
 Package                  Arch                    Version                                               Repository                       Size
==============================================================================================================================================
Installing:
 keybase                  x86_64                  1.0.37.20171206230413.e6b362a87-1                     /keybase_amd64                  246 M

Transaction Summary
==============================================================================================================================================
Install  1 Package

Total size: 246 M
Installed size: 246 M
Is this ok [y/d/N]: y
Downloading packages:
Running transaction check
Running transaction test
Transaction test succeeded
Running transaction
  Installing : keybase-1.0.37.20171206230413.e6b362a87-1.x86_64                                                                           1/1 
Redirecting to /bin/systemctl start atd.service
  Verifying  : keybase-1.0.37.20171206230413.e6b362a87-1.x86_64                                                                           1/1 

Installed:
  keybase.x86_64 0:1.0.37.20171206230413.e6b362a87-1                                                                                          

Complete!
$ run_keybase 
Starting via systemd.
Failed to execute operation: Process /bin/false exited with status 1

```

The platform is CentOS 7 x86-64.

**Comment by maxtaco** [comment]
cc @oconnor663

**Comment by oconnor663** [comment]
We just shipped some systemd-related changes, and it looks we broke you :(

Googling around a bit for that `/bin/false` error, it sounds like you might be in a situation where systemd is running for your system, but you don't have a user-level instance of systemd running as your user. Do you know whether your systemd setup was configured when you installed CentOS, or whether you set it up manually afterwards? If you run `systemctl --user status`, do you get a similar error?

It's possible we should be detecting this condition and choosing to start up in the previous non-systemd mode. But I didn't want to ship logic like that until I had a better idea of how users would get into this situation, and whether we should treat it as an error or not.

**Comment by thejpster** [comment]
Yes, anything with --user seems to give the same error. As far as in know
this is a normal desktop install of 7.1 with the latest yum updates to 7.4
(or whatever they're at).

**Comment by oconnor663** [comment]
I'll try to repro the same setup and see if I can hit these errors.

**Comment by shaman007** [comment]
Same issue for me for about 2 weeks on the RHEL 7.4.

**Comment by jarekg83** [comment]
https://github.com/keybase/client/pull/9941/commits/90d6494a1f352044586a72203e6e88a463faaaff

edit /usr/bin/run_keybase and either comment out lines 111-113 and 115 to leave just start_backgroud function commenting out all conditionals around systemd.

`if wants_systemd ; then
      start_systemd
  else
      start_background
  fi
`

**Comment by oconnor663** [comment]
More discussion in https://github.com/keybase/client/pull/9941. We should be able to fix this pretty quickly, and I'll test it by hand on some VMs.

**Comment by oconnor663** [comment]
The fix for this landed, and it'll go out with our next Linux build, probably tomorrow.

**Comment by oconnor663** [comment]
Just kidding it's going out in 10 minutes.
