### ISSUE TITLE
Keybase Install Error: Unable to launch on MacOS

### ISSUE THREAD

**Issue by hwbehrens** [keybase/client#9854]
When launching Keybase (as of today), I get an error on launch asking me to Quit or Ignore, and to submit my log (ID below). Regardless of what I choose, I cannot continue. Any ideas?

my log id: f1c553e4cd44d4aa6457de1c

![screen shot 2017-12-08 at 13 39 04](https://user-images.githubusercontent.com/6589744/33784247-4f62ca32-dc1d-11e7-96fc-76c840168116.png)

**Comment by maxtaco** [comment]
sorry about that! thanks for the report

@patrickxb  can you check it out? thx

**Comment by hwbehrens** [comment]
I should also clarify, this is not a new install; it previously worked fine. In fact, the error message above first appeared spontaneously (presumably from some background process initialized by the menu bar widget). It recurs whenever I try to manually relaunch the software, however (as described above).

**Comment by patrickxb** [comment]
Looking

**Comment by patrickxb** [comment]
This seems to be the problem:

    12632 2017/12/08 13:37:29 ERR updater service not starting due to lockPID error: open /Users/hwbehren/Library/Caches/Keybase/updater.pid: no such file or directory

It's been a while, I'll look at the code now to try to figure out the issue.

**Comment by patrickxb** [comment]
@hwbehrens does this directory exist on your computer?

     /Users/hwbehren/Library/Caches/Keybase

**Comment by hwbehrens** [comment]
No, it does not/did not exist. I tried recreating it with mkdir, but it didn't change the behavior.

**Comment by patrickxb** [comment]
Thanks, sorry for the issues.  Can you do another `keybase log send` now that that directory works?

**Comment by hwbehrens** [comment]
Looks like it created the updated.pid file in there, but still no go. I tried chmod 777 to see if it might be a permissions issue on the directory as well, but still no dice.

New logs at : `ccb42c5669b8a2b02ed2621c`

Contents of the updater.pid file is: `7348`

Also, in the process of packing up the logs, it looks like something came and deleted everything in the Caches directory. Not sure what could be causing that, or how often it happens; I'll have to follow up with IT if that's what's breaking everything. Since it's just caches, should it matter, though?

**Comment by patrickxb** [comment]
Can you start keybase now, or it's still busted?

**Comment by hwbehrens** [comment]
No, still busted. If the folder is missing, it fails immediately; if I create the folder myself, it creates the updater.pid file in the folder and *then* fails.

**Comment by patrickxb** [comment]
Ok, can you try running this little macOS application to check the permissions on your ~/Library directories?

https://keybase.pub/patrick/src/KeybaseFixer/KeybaseFixer.app.tar.gz

It's an applescript application, you can view the source here:

https://keybase.pub/patrick/src/KeybaseFixer/

After you run that, try launching Keybase again.

Thanks for your patience!

**Comment by hwbehrens** [comment]
Alright, I ran it. It prompted me for an admin password, which I provided, and then it quit with no further dialogs (which looks like the expected behavior, from the source).

However, there was no change in the behavior for Keybase - same 'install' error. Sorry! Anything else I can try?

**Comment by hwbehrens** [comment]
It looks like there might have been another build pushed in the meantime that resolved the error; I've attached the new version information as a screenshot.
![screen shot 2017-12-19 at 20 24 24](https://user-images.githubusercontent.com/6589744/34189870-f3b0485e-e4fa-11e7-94d9-d36b2d47748c.png)

**Comment by hwbehrens** [comment]
Although I don't think we found the core issue, since it's fixed for me, I'm happy to close this issue. I'll leave it up to you, in case you'd prefer to leave it open until the root cause can be found.

**Comment by patrickxb** [comment]
@hwbehrens that is great news! I meant to follow up with you after it was released to see if it worked.

We moved the directory where we were storing those PID files out of ~/Library/Caches.  I don't know what's deleting the files in that directory for you, but you should be allowed to delete them, so we found a better place for them.

Thanks for helping us track it down.  I'm going to go ahead and close this.

**Comment by kk575072** [comment]
Dear Team,

I have the same issue on MAC pro. I'm unable to install Keybase encountering same error as mentioned above though the suggestions executed. Could you please suggest.

Sudheer
