### ISSUE TITLE
[Urgent] Keybase desktop clients prevent switching IME to Japanese language

### ISSUE THREAD

**Issue by junderw** [keybase/client#9861]
Client:  1.0.37-20171208170249+025062c3a
Service: 1.0.37-20171208170249+025062c3a

We have to type using english letters now and it's super hard to read...

Please restore the functionality of allowing for non-English IME input.

On all other apps I have certain buttons on my keyboard that switch to Japanese and back to English.

This button does not work on Keybase.

**Comment by junderw** [comment]
iPhone lets me type Japanese.

**Comment by ElectronicWar** [comment]
Cannot reproduce here. IME switching with Win+Spacebar and the language button works fine here.
Windows 10 Pro 1703 in English with 4 keyboard languages installed (German, English, Microsoft Japanese IME and Google Japanese IME)

keybase version 1.0.37-20171208121326+523e543

**Comment by junderw** [comment]
Client:  1.0.37-20171206230413+e6b362a87
Service: 1.0.37-20171206230413+e6b362a87

This version did not experience this issue.

**Comment by junderw** [comment]
So the culprit is somewhere in this diff:

https://github.com/keybase/client/compare/e6b362a87...025062c3a

**Comment by maxtaco** [comment]
cc: @keybase/react-hackers 

Sorry about the bug!

**Comment by junderw** [comment]
Looking at the diff (note: I am not a UI dev) it looks like the only thing that should affect ALL chat boxes (teams and individual chats all prevent Japanese IME switching) would be the following change:

My understanding is that in react, reducers are extremely pervasive and affect large swaths of the UI.

None of the other parts of the diff seem like they'd affect a Linux desktop.

Perhaps conversationState being set to isStale is breaking something....

```javascript
// shared/reducers/chat.js
   case ChatGen.inboxStale: {
     return state.update('conversationStates', conversationStates =>
       conversationStates.map((conversationState, conversationIDKey) => {
         console.log(`reducer: setting thread stale from inbox stale: ${conversationIDKey}`)
         return conversationState.set('isStale', true)
       })
     )
   }
```

**Comment by cjb** [comment]
That doesn't make sense to be as an explanation, sorry.  :(

Think we could get you to keep bisecting?

**Comment by junderw** [comment]
If you could instruct me on how to do so, I will try.

**Comment by junderw** [comment]
I recently installed go 1.9, but I don't know what the loop of commands would be between each bisect. (seeing as run_keybase seems to run a lot of processes and there are cronjobs and all sorts of bells and whistles... not sure how I would use git bisect to do that without accidentally leaving a process up or something and ruining the bisect.

**Comment by junderw** [comment]
I built the GUI and client with yarn:

```bash
killall keybase
killall Keybase
version="$(./packaging/version.sh devel)"
binary_name="$(./packaging/binary_name.sh devel)"
build_number="$(echo -n "$version" | sed 's/.*-//')"
ldflags_client="-X github.com/keybase/client/go/libkb.PrereleaseBuild=$build_number"
sudo go build -tags "production prerelease" -ldflags "$ldflags_client" -o "/usr/bin/keybase" github.com/keybase/client/go/keybase
cd shared
yarn run package -- --platform linux --arch "x64" --appVersion "$version"
sudo rm /opt/keybase/Keybase
sudo cp $GOPATH/src/github.com/keybase/client/shared/desktop/release/linux-x64/Keybase-linux-x64/Keybase /opt/keybase/Keybase
cd ..
```

with the last version that worked... and now it says

Client:  1.0.37-20171213171816+e6b362a
Service: 1.0.37-20171213171816+e6b362a

So the dates are new but the commit is the same... and yet I still have the problem.

However, I found a way to avoid the problem.

When I run Keybase at startup, OR if I run by clicking the keybase icon on my start menu, IME is broken.

However, if I open terminal and use the command `/opt/keybase/Keybase &` from the terminal and disown it, I can magically use the IME again...

This method also works on the newer commit.

So what is the difference between running from terminal the GUI only, and running the icon in my start menu......???

**Comment by junderw** [comment]
Isolated the cause:

systemd boot caused it. running run_keybase after setting `export KEYBASE_SYSTEMD=0` gives me full access to the IME.

**Comment by junderw** [comment]
I built so many versions......... but the cause was the debian install methodology... lol

**Comment by strib** [comment]
Calling @oconnor663 to the rescue!

**Comment by oconnor663** [comment]
Thanks for digging into this. The problem is almost certainly that there are certain environment variables that make IME work, which we aren't forwarding to the GUI when it's launched under systemd.

Could you try applying the following change to `run_keybase`, to see if it fixes the problem for you?

```diff
diff --git a/packaging/linux/run_keybase b/packaging/linux/run_keybase
index 9dfc9231d..56b4808fb 100755
--- a/packaging/linux/run_keybase
+++ b/packaging/linux/run_keybase
@@ -64,16 +64,7 @@ start_systemd() {
   # This script is intended to be run after updates, so we need to reload
   # potentially changed unit files.
   systemctl --user daemon-reload
-  # The GUI needs access to the env var KEYBASE_START_UI. This is set to
-  # "hideWindow" by the autostart file that might be calling us. We need to
-  # pass it along.
-  echo "KEYBASE_START_UI=${KEYBASE_START_UI:-}" > "$runtime_dir/keybase.gui.env"
-  # Some distros (e.g. Ubuntu 16.04) don't make X session variables available
-  # to user units automatically. Add them to the env file ourselves.
-  echo "DISPLAY=${DISPLAY:-}" >> "$runtime_dir/keybase.gui.env"
-  echo "XAUTHORITY=${XAUTHORITY:-}" >> "$runtime_dir/keybase.gui.env"
-  echo "XDG_CURRENT_DESKTOP=${XDG_CURRENT_DESKTOP:-}" >> "$runtime_dir/keybase.gui.env"
-  echo "DBUS_SESSION_BUS_ADDRESS=${DBUS_SESSION_BUS_ADDRESS:-}" >> "$runtime_dir/keybase.gui.env"
+  env > "$runtime_dir/keybase.gui.env"
   # The keybase.gui.service unit has keybase.service and kbfs.service as
   # dependencies, so we don't have to list them here. But including them lets
   # us report an error if they fail to start. Also prefer `restart` to `start`
```

As the comment there mentions, there are some differences between how distros like Ubuntu 16.04 launch user services, and how the latest version of systemd running on Arch Linux launches them. It's possible that this problem is already fixed in that latest version, and anecdotally I can use IME on my own desktop (Gnome Shell 3.26). But we'll probably want to ship this fix for everyone, if it does work. We might even want to make it apply to the non-gui services too, under the assumption that something somewhere will break if we don't?

**Comment by junderw** [comment]
@oconnor663 

I narrowed down the culprit:

Adding the following one line fixed the issue.

`echo "GTK_IM_MODULE=${GTK_IM_MODULE:-}" >> "$runtime_dir/keybase.gui.env"`

CLUTTER_IM_MODULE=xim
QT_IM_MODULE=fcitx
QT4_IM_MODULE=fcitx
GTK_IM_MODULE=fcitx

I have 4 IM_MODULE env variables here, and only GTK made any difference... I guess my cinnamon desktop was choosing GTK and checking the env for which IME to use. fcitx is my IME.

**Comment by junderw** [comment]
This was interesting... https://unix.stackexchange.com/questions/260601/understanding-setting-up-different-input-methods

Perhaps adding

CLUTTER_IM_MODULE
GTK_IM_MODULE
QT_IM_MODULE
QT4_IM_MODULE
XMODIFIERS

just to cover all bases?

**Comment by oconnor663** [comment]
@junderw I realized as part of testing this, that the original problem doesn't repro on Ubuntu 16.04. What distro were you seeing it on?

**Comment by junderw** [comment]
OS = Linux Mint 18.3
IME = fcitx
JP IME = fcitx-mozc

**Comment by oconnor663** [comment]
The fix in https://github.com/keybase/client/pull/10009 should go out with today's build.
