### ISSUE TITLE
libasound2 libnss3 missing from Ubuntu 64 package

### ISSUE THREAD

**Issue by tcely** [keybase/client#9872]
The GUI doesn't start without these.

**Comment by stigmergik** [comment]
Also missing from 32 bits. Installed on Whonix (Debian) with `keybase_i386.deb` and GUI silently failed to start when opening from KDE start menu.

Did some digging, found `/opt/keybase/Keybase`, then tried running that from the command line and saw the error about missing libnss3.

After `sudo apt-get install libnss3` things worked, didn't need to add libasound2 though.

**Comment by tcely** [comment]
@stigmergik You might want to file this as a distinct issue.
