### ISSUE TITLE
Notification email talks about mobile app like it doesn't exist yet

### ISSUE THREAD

**Issue by staktrace** [keybase/client#9887]
I added a new mobile device and got a notification email from notify@keybase.io which includes stuff like this:

```
### What happens if I wipe/restore a mobile install of Keybase?

 Our mobile app isn't ready, but we're answering this in advance.
```

This needs a once-over to acknowledge the existence of the (quite good) mobile app.

**Comment by maxtaco** [comment]
cc @malgorithms

**Comment by malgorithms** [comment]
ah thanks, this is specifically in the plaintext version of the email. fixed.
