### ISSUE TITLE
Not enough words for a paper key.

### ISSUE THREAD

**Issue by dschaper** [keybase/client#9890]
I'm trying to add a new system to Keybase and I do not have access to the old system to use that as a verification process. I'm using the sponsor share that I generated and have used successfully in the past with 11 key words. When I use this again I get the above listed error. `Bad passphrase: Not enough words entered for a paper key. Please try again. 

```
keybase version 1.0.37-20171208170249+025062c3a
"Linux Mint 18.3"
```

**Comment by maxtaco** [comment]
@patrickxb  it's 13 words, right?

**Comment by patrickxb** [comment]
Yes, 13.

**Comment by dschaper** [comment]
Ah, I was using just the key words, didn't prefix it with the first two words that describe the paper key type. Thanks for the enlightenment.

**Comment by maxtaco** [comment]
👍 Maybe the app should give better errors

**Comment by dschaper** [comment]
Might be a good enhancement, respond back that the proper number of words is 13 and that it begins with the key type.
