### ISSUE TITLE
Shared Directory REKEY Doesn't Go Away

### ISSUE THREAD

**Issue by adraffy** [keybase/client#9909]
I installed Keybase on my desktop and made a chat with a friend.  We then created a shared directory and exchanged files.  Next, we added our iPhones to our Keybase account.  Since then, our shared directory indicates that it needs a REKEY from my desktop machine and the only option is "Open the Keybase app".  I added another desktop and was unable to view the shared folder.  

I created a paper key `keybase paper`, ran `keybase rekey paper` on both desktops, and got a dialog box indicating success (don't remember exactly).  Now the shared directory works correctly but it's still telling me to REKEY on all my devices.

my log id: 4dd3eaab4b1cbde7319dfc1c

**Comment by strib** [comment]
@adraffy we had a temporary server issue last night and this morning.  It should be ok now, is the rekey badge gone?

Other logs related to this issue: 54c559298bdaa4c946c1f31c

**Comment by adraffy** [comment]
Yes, the badge was gone this morning.  Thank you.

**Comment by strib** [comment]
Great, sorry for the confusion.
