### ISSUE TITLE
Freezes when trying to activate on Linux Mint 18.3 (Ubuntu 16.04) via phone

### ISSUE THREAD

**Issue by dwaindibbley** [keybase/client#9910]
Keybase GUI Version: 1.0.37-20171208170249+025062c3a

After scanning the QR code from phone or entering text both ends lock and no progress can be made

**Comment by maxtaco** [comment]
If you send feedback from both devices that will help us debug it. Use ‘keybase log send’ from the CLI and feedback from the phone

**Comment by dwaindibbley** [comment]
Done

**Comment by maxtaco** [comment]
What is your keybase name?  And can you specify which device was your "provisioned" device and what was your "new" device?  Which platform and/or device name? Finally, when you did a `keybase log send`, what was the hex ID it gave for the log?

cc: @keybase/react-hackers, I think there might be a regression in provisioining

**Comment by dwaindibbley** [comment]
datapower Lenovo was the PC I was trying to activate and Note 8 was the phone I was attempting to use as the activator

**Comment by dwaindibbley** [comment]
This issue appears to be fixed in latest version ???? (Can't find a version number in the software)
