### ISSUE TITLE
403 Forbidden on latest Linux Client

### ISSUE THREAD

**Issue by charlesj** [keybase/client#9915]
I originally installed keybase from:  https://prerelease.keybase.io/keybase_amd64.deb

It apparently added some apt-repositories, which is great.  But that repository started giving key errors a month ago, and now keybase is not able to upgrade from the command line (using apt-get dist-upgrade).  

It gives an error:
```
E: Failed to fetch http://prerelease.keybase.io/deb/pool/main/k/keybase/keybase_1.0.35-20171114170030.d28b65dbe_amd64.deb  403  Forbidden [IP: 13.33.151.41 80]
```
The error from `apt-get update`:
```
Err:6 http://prerelease.keybase.io/deb stable InRelease                                                                                                                                                                                  
  The following signatures were invalid: KEYEXPIRED 1511107367  KEYEXPIRED 1511107367  KEYEXPIRED 1511107367
```

My next step is to uninstall keybase and upgrade the rest of my computer, and then to figure out how to get keybase back.  Thought you should know about the expired key and forbidden issues, and this seemed like the only channel to do it.

**Comment by maxtaco** [comment]
cc @oconnor663

**Comment by oconnor663** [comment]
Thanks for the report. We have a doc up about this problem: https://keybase.io/docs/the_app/linux_expired_key. The short version is that if you repeat the original installation steps, everything should just work :)

**Comment by oconnor663** [comment]
(It's possible the 403 error is an unrelated issue, so if fixing the PGP issue doesn't fix the 403, please let me know.)

**Comment by charlesj** [comment]
Based on what you said, After uninstalling, I simply reran my automation to re-install keybase and it picked up the new key.  Thank you!
