### ISSUE TITLE
KBFS on Android

### ISSUE THREAD

**Issue by nickgarber** [keybase/client#9948]
Relates to: https://keybase.io/docs/kbfs
Just excited for this feature, (didn't see an existing issue), and wanted a reference to track the work. Cheers!

**Comment by bbigras** [comment]
Any progress on this? I'm interested in keybase since dropbox dropped support for encrypted file-systems.

**Comment by strib** [comment]
Yep, this has been working for months.  It's a bit limited in terms of interacting with the files, but we're actively improving it.  Look for the "Files" section in the menu of the app.

**Comment by eterps** [comment]
Are there plans for (limited) support for syncing with a local folder on Android?

**Comment by bbigras** [comment]
> Are there plans for (limited) support for syncing with a local folder on Android?

That could be useful for apps like [Orgzly](http://www.orgzly.com/). Unless the files could be accessed with an API.

**Comment by nickgarber** [comment]
It's exactly Orgzly that I had in mind when filling this issue.

Is there any guidance or roadmap available for how to use KBFS from other
apps, (on Android or in general)?

**Comment by staticvoidmaine** [comment]
I'm interested in this feature for use with a [Pass](https://www.passwordstore.org/) store. I'm sure you're hard at work on it, just adding another use case! :)
