### ISSUE TITLE
Keybase can't connect on mac and immediately crashes on iphone

### ISSUE THREAD

**Issue by llimllib** [keybase/client#9965]
On Mac, keybase just says "disconnected". It occasionally flashes the start of rendering the UI, but then jumps back to the loading icon and says "disconnected". If I open console and search keybase, I get a bunch of errors like: `default	22:12:53.754409 -0500	keybase	UNIX error exception: 17`

On my iPhone, keybase launches, displays a message about notifications, then if I hit "got it", it crashes within less than a second.

I've been playing with linux, so I've been provisioning/deprovisioning devices a bunch. It's possible that has messed up keybase?

Is there any further info I can provide to help you debug?

**Comment by maxtaco** [comment]
On mac, please run: `keybase log send`

On iPhone, please send feedback from within the app

thank you

**Comment by llimllib** [comment]
On mac, the sending failed with:

```
▶ INFO ignoring error getting keybase status: There were multiple errors: dial unix /Users/llimllib/Library/Group Containers/keybase/Library/Caches/Keybase/keybased.sock: connect: connection refused; dial unix /Users/llimllib/Library/Caches/Keybase/keybased.sock: connect: no such file or directory
▶ INFO ignoring UI logs: There were multiple errors: dial unix /Users/llimllib/Library/Group Containers/keybase/Library/Caches/Keybase/keybased.sock: connect: connection refused; dial unix /Users/llimllib/Library/Caches/Keybase/keybased.sock: connect: no such file or directory
```

eventually, it got to telling me succes, my log id is: `ee8c8480078b85214195561c`

On iphone, I can't manage to open the app, so I can't send you logs.

**Comment by llimllib** [comment]
`/Users/llimllib/Library/Group\ Containers/keybase/Library/Caches/Keybase/keybased.sock` exists, is a socket, and has reasonable-looking permissions:

```
$ file /Users/llimllib/Library/Group\ Containers/keybase/Library/Caches/Keybase/keybased.sock
/Users/llimllib/Library/Group Containers/keybase/Library/Caches/Keybase/keybased.sock: socket
10:25 PM hickory:~
$ ls -alh /Users/llimllib/Library/Group\ Containers/keybase/Library/Caches/Keybase/keybased.sock
srwxr-xr-x  1 llimllib  staff     0B Dec 18 22:25 /Users/llimllib/Library/Group Containers/keybase/Library/Caches/Keybase/keybased.sock=
```

**Comment by maxtaco** [comment]
It's likely the same issue in both places, I see a crasher on an NPE in your logs. We'll have to take a loko at it.

**Comment by llimllib** [comment]
Thanks, appreciate it

**Comment by maxtaco** [comment]
See #9968 for the fix. I'm not sure when we can ship a release though, the holiday will slow down our release schedule.  Thanks for your patience and the bug report!
